### ISSUE TITLE
Date returns invalid Date for valid dates.

### ISSUE THREAD

**Issue by AleksandarFaraj** [expo/expo#782]
I have an issue when uploading my project to Expo.

I have to concat dates into the format below and when I test it locally it works. However when I publish to the Expo service or use Snack, then the date returns invalid date. 

new Date("2017-09-13 00:13:28")

Steps to reproduce:

Upload following or create Snack using:

```
export default class App extends Component {
  render() {
    var date = new Date("2017-09-13 00:13:28");
    alert(date)
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>
          {date}
        </Text>
        <Card title="Local Modules">
        <AssetExample />
        </Card>
      </View>
    );
  }
}
```

**Comment by ide** [comment]
When you're testing locally, are you running the JS in remote debugging mode? In that mode, the JS runs in Chrome which is a completely different JS runtime than on the device and has a different implementation of the `Date` constructor.

**Comment by AleksandarFaraj** [comment]
@ide No, I am not running remote debugging mode.

Using the same date format in node cli returns a valid date, it's in expo this happens for some reason.

new Date("2017-09-13 00:13:28"); // In expo, Invalid date

new Date("2017-09-13 00:13:28"); // In node, 2017-09-12T22:13:28.000Z

Node Version, v8.6.0

package.json
"dependencies": {
    "expo": "^21.0.0",
    "native-base": "^2.3.2",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.4",
    "react-native-pathjs-charts": "0.0.31",
    "react-navigation": "^1.0.0-beta.13"
  }

**Comment by ide** [comment]
Node uses the same JS implementation as Chrome so I’m not surprised there’s a difference between Node and your phone. Try running that code in Safari on your phone and you should see the same difference.

It’s surprising that React Native and Expo differ because the same JS engine is used. Are you testing on the same device? What OS is your device on?

**Comment by AleksandarFaraj** [comment]
@ide I noticed I have not been clear enough.

When I say it returns bad dates on Expo this means that I upload a project online to Expo using Expo Publish.
When I say I run Node, I mean that I run the command "node"
When I say I run it with React Native, I mean that I am running it locally but still through the Expo app.

This error occurs when I use the online Expo platform or Snack.

> What OS is your device on?

I am running macOS High Sierra

> Are you testing on the same device?

Yes, I'm testing on the same iPhone

> Try running that code in Safari on your phone and you should see the same difference.

Yes safari returns invalid date. However, my concern is that the local expo project works but not a published expo project.

`> new Date("2017-09-13 00:13:28")
< Invalid Date`

**Comment by dikaiosune** [comment]
@AleksandarFaraj when you say "local" expo project, do you have Chrome debugging enabled?

**Comment by AleksandarFaraj** [comment]
@dikaiosune No I do not

**Comment by amaurymartiny** [comment]
Can repro.

- Local expo project without Chrome debugging: `Invalid date`
- Local expo project with Chrome debugging: correct date
- Published expo app: `Invalid date`

**Comment by ide** [comment]
Chrome debugging will produce different behavior because V8 differs from JSC. This is how React Native works so I don’t think there’s much to do on Expo’s side.

**Comment by phitien** [comment]
Hi there, 
Do you manage to fix this issue. I got the same thing. No JS debugging remotely enabled.

**Comment by MatheusNaldi** [comment]
@phitien 

I solved this in this way: https://stackoverflow.com/a/45152231/8407147

Just replace the space in the middle of the date with a T
`new Date('2017-09-13 00:13:28'.replace(' ', 'T'))`

**Comment by zerobytes** [comment]
This issue still happens. We should know which repository is responsible for this and open the issue at the correct one. 
@MatheusNaldi answer works, but it should not be required as the space instead of T should be a valid date, as it is in V8

**Comment by ide** [comment]
Different JS VMs have different Date parsing rules. If after careful reading of the ECMA spec (https://www.ecma-international.org/ecma-262/9.0/index.html#sec-date.parse) you find there to be a bug in a JS VM implementation, that is something to address, but if the spec leaves the behavior open, you need to write your application code in a way that follows the API rather than a single implementation.

> The function first attempts to parse the format of the String according to the rules (including extended years) called out in Date Time String Format (20.3.1.15). If the String does not conform to that format the function may fall back to any implementation-specific heuristics or implementation-specific date formats.

Additionally, the spec says you must have "T" in an ISO string (https://www.ecma-international.org/ecma-262/9.0/index.html#sec-date-time-string-format).
