### ISSUE TITLE
[ANDROID] Permissions.askAsync(Permissions.NOTIFICATIONS) does not show notification modal

### ISSUE THREAD

**Issue by ronaiza-cardoso** [expo/expo#7820]
## 🐛 Bug Report

I have this code and tested on my android device, tablet Samsung s4, and when I run this function the notification modal does not show up.

```
 async function handleAskPermissions() {
    try {
      const { status, ...rest } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
      if (status === 'granted') {
        console.log('handleAskPermissions -->', { status, rest });
      }
      Alert.alert('Please, allow notifications on your system settings', '', [
        { text: 'OK', onPress: () => handleNext() },
      ]);
    } catch (error) {
      console.log('handleAskPermissions -> error -->', { error });
    } finally {
      StorageProvider.setPermissions(true);
    }
  }

....
render() { 
   
           <TouchableOpacity onPress={() => handleAskPermissions()}>
              <Text >ACTIVATE NOTIFICATIONS</Text>
            </TouchableOpacity> 
  
}
```

This is the response of the ` const { status, ...rest } = await Permissions.askAsync(Permissions.NOTIFICATIONS);`
```

handleAskPermissions --> Object {
  "rest": Object {
    "canAskAgain": true,
    "expires": "never",
    "granted": true,
    "permissions": Object {
      "notifications": Object {
        "canAskAgain": true,
        "expires": "never",
        "granted": true,
        "status": "denied",
      },
    },
  },
  "status": "denied",
}
```

### Environment
```
 Expo CLI 3.17.24 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.3.7
    npmGlobalPackages:
      expo-cli: 3.17.24
```
Tested in the Sansumg tab s4 device.

### Reproducible Demo
https://snack.expo.io/@rcardoso/permissions.askasync---bug

I don't understand why  the `granted` var is true and the `status` is denied
https://docs.expo.io/versions/v37.0.0/sdk/permissions/#permissionresponse

**Comment by jonathanstiansen** [comment]
Hey @ronaiza-cardoso on android notification permissions are automatically given. That's why you don't see the dialog. If you're concerned about not getting them it's likely you don't have firebase set up on your project, or haven't given Expo your cloud messaging API key. Like so: `expo push:android:upload --api-key <firebase_cloud_messaging_key>`

**Comment by cruzach** [comment]
thanks @jonathanstiansen 😄 the notification permission isn't classified as a "dangerous permission" which require prompting the user - see [here](https://developer.android.com/guide/topics/permissions/overview#normal_permissions) for more info

**Comment by arveenkumar55** [comment]
@jonathanstiansen can u explain why the granted var is true and the status is denied? I am facing same issue on my device.
