### ISSUE TITLE
Audio stops playing after while with expo-av

### ISSUE THREAD

**Issue by pooyabe** [expo/expo#7824]
### Environment
Android

`  Expo CLI 3.17.15 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.1 - S:\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Users\PooyA\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - S:\nodejs\npm.CMD
`

### Steps to Reproduce

when playing a music using expo-av components.
after running the app, music plays correctly but after while,unreasonable its stops playing just before the music ends in random duration in each time running the app!!

### Expected Behavior
Play music without problems Or even show some errors!

### Actual Behavior
stopping music after random while (!!) without any error just this warning:

> Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground.

### Simplified Codes

```jsx
import React, { Component } from 'react'
import { Audio } from 'expo-av'

handlePlaySound = async fileAdd => {
    const soundObj = new Audio.Sound();
    try{
        await soundObj.loadAsync(fielAdd);
        await soundObj.playAsync;
    }catch(error){
        console.log(error);
    }
}
export default function HomeScreen() {
    let source = require('./assets/sounds/bg.mp3');
    this.handlePlaySound(source);

    return (.....Ui Components
    );
  }
```

**Comment by cruzach** [comment]
Testing this with this snack- https://snack.expo.io/@charliecruzan/mad-croissant - the audio doesn't stop until it's finished. Could you provide more information on how to reproduce this?

**Comment by pooyabe** [comment]
> 
> 
> Testing this with this snack- https://snack.expo.io/@charliecruzan/mad-croissant - the audio doesn't stop until it's finished. Could you provide more information on how to reproduce this?

--running node.js --version
12.16.1
--npm --version
6.13.4
--expo init projectName
--cd projectName
--react-native --version
2.0.1
--expo --version
3.17.15

write that codes in app.js and nothing else!
testing in Android device (Nokia 6)

this problem still after i export .apk installable app.

**Comment by cruzach** [comment]
You will need to run `expo install expo-av`

**Comment by pooyabe** [comment]
> 
> 
> You will need to run `expo install expo-av`

yeah i have it sorry forgot to mention!!

for more details this is my package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "~10.0.0",
    "@react-native-community/masked-view": "0.1.5",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "expo": "~36.0.0",
    "expo-asset": "~8.0.0",
    "expo-av": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-web-browser": "~8.0.0",
    "native-base": "^2.13.8",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-preset-expo": "~8.0.0",
    "jest-expo": "~36.0.1"
  },
  "private": true
}

```

**Comment by cruzach** [comment]
Running the snack code in fresh, blank `expo init` project didn't reproduce this issue for 🙁 please provide a minimal reproducible example- [here's a guide on how to do that](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by timendez** [comment]
This is also happening to me! Mine involves playing a bunch of different sounds and then after a while it just stops all audio... I'll see if I can get logs around whats going on when it fails, but it's reproduceable on my published app on Google Play.

**Comment by timendez** [comment]
I ended up "fixing" my problem by using `unloadAsync` within the `setOnPlaybackStatusUpdate` callback ->

```javascript
const soundObject = new Audio.Sound();
try {
    soundObject.setOnPlaybackStatusUpdate((status) => {
        if (!status.didJustFinish) return;
        soundObject.unloadAsync();
    });
    const audioFile = audioMap[fileName.replace(/ /g, '')];
    await soundObject.loadAsync(audioFile);
    await soundObject.playAsync();
} catch (error) {
    console.log(error);
}
```

However, I believe my problem is more related to constant stopping and starting of new, short audio clips rather than prolonged duration of one.

**Comment by IjzerenHein** [comment]
Hi! @timendez is on the right track here. When you load a Sound object, you will also need to unload it using `unloadAsync`, otherwise it will not be cleaned up and you will run out of memory.

@pooyabe Please try the solution provided by @timendez in https://github.com/expo/expo/issues/7824#issuecomment-623882159

**Comment by magiqapps** [comment]
I'm seeing a similar issue with expo av. Audio stops with this conditions:
- Android device (iOS works fine)
- App in background or locked for a random while.
- Audio goes back when in foreground.

The only difference in my case is that it is a radio stream, there is no file to load and no end, so not sure if the fix applies the same. I'm using unloadAsync just when unmounting the component.

More details:
- expo cli 3.26.0
- expo 38.0.10
- react-native sdk 38.0.2
- expo-av 8.4.0

Android models tested:
- ZTE, Android 9
- Huawei, Android 10

Any recommendation?

**Comment by lopauru** [comment]
> I'm seeing a similar issue with expo av. Audio stops with this conditions:
> 
> * Android device (iOS works fine)
> * App in background or locked for a random while.
> * Audio goes back when in foreground.
> 
> The only difference in my case is that it is a radio stream, there is no file to load and no end, so not sure if the fix applies the same. I'm using unloadAsync just when unmounting the component.
> 
> More details:
> 
> * expo cli 3.26.0
> * expo 38.0.9
> * expo-av 8.2.1
> 
> Android models tested:
> 
> * ZTE, Android 9
> * Huawei, Android 10
> 
> Any recommendation?
> 
> *** UPDATE Sep-3 ***
> New tests confirm that this related issue is only seen when the Android device is locked and not charging. It seems exoplayer playing in background consumes enough battery to make the device battery optimization stop the playback.
> Does this behavior match what others are seeing? otherwise I may need to open a new issue to track power management & expo-av in Android.

Hello,

Im facing the same problem for months now without any fix.

Do you have any fix or recommendation for this issue?

**Comment by gianpietro-magiqapps** [comment]
@lopauru I have no workaround yet.
I opened issue #10056 for what we are observing, please help by adding more evidence to it.

**Comment by gianpietro-magiqapps** [comment]
Hi, in my case I had to eject and use react-native-track-player, which Android and iOS do recognize as an audio player, so the problem is gone.

**Comment by garrett-gottlieb** [comment]
This issue still exists and should be reopened

**Comment by Draigan** [comment]
For me it was just a memory leak. U have to unmount it 
```
  React.useEffect(() => {
    return sound
      ? () => {
          console.log('Unloading Sound');
          sound.unloadAsync();
        }
      : undefined;
  }, [sound]);

```

**Comment by artsnr1** [comment]
It's still there in sdk 49...sigh!!

**Comment by filipecatraia** [comment]
I'm not one for posting “us too!”, but this has been the case for about a year. We've tried all manners of workarounds. In the past I think we got it working by calling an internal method of AV that allowed you to destroy objects. Now we destroy the whole screen when possible.

Playing multiple, short-duration audios in succession brings up the issue 9 times out of 10. Mostly on Android. We do unload the audios after finishing, and we did follow all suggestions in this and other threads.

Very standard issue management is at work here: multiple people report a problem, but since it can't be easily reproduced, no one cares and the issues get closed. Since audio playback is the bread and butter of our app, ejecting from Expo is the only option.

We tremendously value the safety of Expo compared to the Wild West of RN, but issues with AV, SecureStore, Auth, etc., all that get closed without a fix, are not compatible with the needs of professional apps 🤷

**Comment by LunatiqueCoder** [comment]
<img width="722" alt="image" src="https://github.com/expo/expo/assets/55203625/f32f7649-2497-431e-99b8-f0c702e6a0ca">

<br>
<br>

This is the most serious issue in our app right now. I worked so much to replace `react-native-sound` (which was working great) with `expo-av`, and now after I wasted so much time looking for workarounds, I'm considering moving back to `react-native-sound`. 

This bug is almost impossible to reproduce, but it exists. 🥲

**Comment by pooyabe** [comment]
> <img alt="image" width="722" src="https://user-images.githubusercontent.com/55203625/281584239-f32f7649-2497-431e-99b8-f0c702e6a0ca.png">
> 
> This is the most serious issue in our app right now. It started after we replaced `react-native-sound` with `expo-av`. Wasted too much time looking for workarounds so we're considering moving back to `react-native-sound`.
> 
> This bug is almost impossible to reproduce, but it exists. 🥲

I opened this issue 3 year ago, went to military service and returned, now i see it still there!
Maybe it's better to use `react-native-sound` than expo-av as you say.

**Comment by krschacht** [comment]
@pooyabe is react-native-sound compatible with expo or do you have to eject in order to use it?

**Comment by LunatiqueCoder** [comment]
@krschacht Yes, it should be compatible with expo. There is no `eject` anymore in the latest expo versions 🤷🏻

Anyway, we ended up using `react-native-video` instead of `react-native-sound`, because it supports playing both video and audio files. Does not support recording though.

If you decide to go for `react-native-video`, I would suggest you to go for the alpha version because it's actually pretty much stable, unless you want to use subtitles (still work in progress)

**Comment by pooyabe** [comment]
> @pooyabe is react-native-sound compatible with expo or do you have to eject in order to use it?

Please have my pardon, but i am not working on any project needing this issue at this time, and that project that had this problem was for 3 years ago. so, i don't know :)
but it seems that after these years, other developers still face the problem.
