### ISSUE TITLE
Cannot resolve assets-library:// or ph:// schemes on iOS in bare config

### ISSUE THREAD

**Issue by Ashoat** [expo/expo#7826]
To resolve these schemes a custom `RCTURLRequestHandler` is necessary. Up until RN0.61, it was possible to get this by linking `RCTCameraRoll`, which includes `RCTAssetsLibraryRequestHandler`. However in RN0.61 this was deprecated. 

The Expo managed workflow relies on a custom patch to `react-native` to continue using the old `RCTAssetsLibraryRequestHandler`: https://github.com/expo/react-native/commit/7a357f9748624ca7c9223648a76b6dca68a66623

This is not possible to reproduce in the bare workflow, which makes it difficult to use `expo-media-library`. A workaround is to install `@react-native-community/cameraroll`, which provides similar functionality via [RNCAssetsLibraryRequestHandler](https://github.com/react-native-community/react-native-cameraroll/blob/master/ios/RNCAssetsLibraryRequestHandler.m).

However, relying on custom patches to `react-native` isn't a good solution for bare workflows. We should see if it's possible to move this functionality elsewhere. Would `expo-media-library` be a good candidate?

**Comment by brentvatne** [comment]
expo-media-library seems like a great fit for this! cc @tsapeta who built expo-media-library

**Comment by Ashoat** [comment]
@tsapeta - let me know, down to put up a PR for this!

**Comment by tsapeta** [comment]
Hey @Ashoat! Yeah, you're right. We need to copy this request handler functionality over to MediaLibrary but I'm afraid just copying the file won't be enough. Also, I guess MediaLibrary is not the only module that may require this handler. We will need to investigate it more and find out the best possible solution to this problem. I'm moving this issue to SDK38 board and going to give it more priority 😉 We will reach out to you once we have this discussed about what needs to be done!
