### ISSUE TITLE
Error: Couldn't get push token for device. Check that your FCM configuration is valid.

### ISSUE THREAD

**Issue by cesarve77** [expo/expo#7831]
### Environment

```
Expo CLI 3.17.24 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.24

```

Runing expo 2.15.1 on Android device

### Steps to Reproduce
Create a fresh app
```
 expo init
```
Modify App.js content with code in https://docs.expo.io/versions/latest/guides/push-notifications/#example-usage
```
expo r
```

### Expected Behavior

Get the device token

### Actual Behavior

In the Browser debug console I got: 
```
Possible Unhandled Promise Rejection (id: 0):
Error: Couldn't get push token for device. Check that your FCM configuration is valid.
Error: Couldn't get push token for device. Check that your FCM configuration is valid.
```
for line: 
```
token = await Notifications.getExpoPushTokenAsync();
```

In the metro console
```
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:99:50 in fn
* http://192.168.1.20:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:123335:45 in Object.getExpoPushTokenAsync
* App.js:13:38 in AppContainer#registerForPushNotificationsAsync
- node_modules/regenerator-runtime/runtime.js:45:39 in tryCatch
- node_modules/regenerator-runtime/runtime.js:274:21 in invoke

```
### Reproducible Demo

This is the exact same code than my local machine

https://snack.expo.io/USwkyxS4i

But in snack it works

**Comment by cruzach** [comment]
hey @cesarve77 sorry that notifications aren't working right off the bat for you, locally. Are you signed in? (run `expo whoami` to check that)

I can't reproduce this running the code from that snack locally (running Android 10, pixel, signed in to both Expo Client app and the `expo-cli`)

**Comment by cesarve77** [comment]
It is weird, I did it again and this time it works,

The only difference I remember is: this time I install expo-permissions
thru
```
install expo-permissions
```

Last time I did thru npm, it makes differences?

Thanks for you quickly help, Feel free to close the issue, if I find
something else I will reopen it and comment on it
Cheers.

**Comment by sjchmiela** [comment]
Hey, could you please try reinstalling the Expo client on your device (uninstall and install again)? 😕

**Comment by qalqi** [comment]
+1

**Comment by olegkalyta** [comment]
Same here

**Comment by sjchmiela** [comment]
Cross-posting from https://github.com/expo/expo/issues/7884#issuecomment-617050920:

> Hey all,
>
>- if you are experiencing this bug in Expo Client app, please ensure that you have the latest version (2.15.4, as of the time of writing this message). This bug has been fixed in the 2.15.1 release. Please also ensure that you are logged in in `expo-cli` as per https://github.com/expo/expo/issues/7831#issuecomment-613647709.
>- if you are experiencing this bug in standalone apps:
>  - if you are sure you provide a valid Google services configuration, please try rebuilding your apps. The fix has been deployed to builders on April 20th (not long ago). Check out https://github.com/expo/expo/issues/7727#issuecomment-616674874 to see why do you need to rebuild your app and ensure that your configuration is the way it should be. You may need to close and rerun the app.
>  - if you aren't sure if you are providing a valid Google services configuration, head over to [Using FCM for Notifications guide](https://docs.expo.io/versions/latest/guides/using-fcm/) and follow it closely to fix the problem.
>
>Let me know if this has helped you fix the problem!

**Comment by daniely-93** [comment]
> Cross-posting from [#7884 (comment)](https://github.com/expo/expo/issues/7884#issuecomment-617050920):
> 
> > Hey all,
> > 
> > * if you are experiencing this bug in Expo Client app, please ensure that you have the latest version (2.15.4, as of the time of writing this message). This bug has been fixed in the 2.15.1 release. Please also ensure that you are logged in in `expo-cli` as per [#7831 (comment)](https://github.com/expo/expo/issues/7831#issuecomment-613647709).
> > * if you are experiencing this bug in standalone apps:
> >   
> >   * if you are sure you provide a valid Google services configuration, please try rebuilding your apps. The fix has been deployed to builders on April 20th (not long ago). Check out [#7727 (comment)](https://github.com/expo/expo/issues/7727#issuecomment-616674874) to see why do you need to rebuild your app and ensure that your configuration is the way it should be. You may need to close and rerun the app.
> >   * if you aren't sure if you are providing a valid Google services configuration, head over to [Using FCM for Notifications guide](https://docs.expo.io/versions/latest/guides/using-fcm/) and follow it closely to fix the problem.
> > 
> > Let me know if this has helped you fix the problem!

I had a similar problem, I followed the FCM guide and it fixed my issue, thanks :)

**Comment by fi-nik** [comment]
Hey, i'm getting same error, but we don't use firebase at all, i mean, we don't have custom google services. Does anyone have solution?

**Comment by sjchmiela** [comment]
If you want to use notifications on Android you'll need to setup a Firebase project. 🙂

\<in grim voice>It's the only way.</in grim voice>

https://docs.expo.io/guides/using-fcm/#client-setup

**Comment by rosnaib11** [comment]
Same issue after building standalone app, expo 37.0.0

**Comment by finik-htec** [comment]
> If you want to use notifications on Android you'll need to setup a Firebase project. 🙂
> 
> <in grim voice>It's the only way.</in grim voice>
> 
> https://docs.expo.io/guides/using-fcm/#client-setup

But when this change happen? On sdk 37? On sdk 35 you could have push notifications without firebase project.

**Comment by fi-nik** [comment]
> If you want to use notifications on Android you'll need to setup a Firebase project. 🙂
> 
> <in grim voice>It's the only way.</in grim voice>
> 
> https://docs.expo.io/guides/using-fcm/#client-setup

But when this change happen? On sdk 37? On sdk 35 you could have push notifications without firebase project.

**Comment by sjchmiela** [comment]
That is correct, sorry that it hasn't been communicated as well as it should. See more information [in CHANGELOG](https://github.com/expo/expo/blob/master/CHANGELOG.md#-breaking-changes-1).

**Comment by fi-nik** [comment]
> That is correct, sorry that it hasn't been communicated as well as it should. See more information [in CHANGELOG](https://github.com/expo/expo/blob/master/CHANGELOG.md#-breaking-changes-1).

Thanks, sorry but i have one more question. I see we need to upload server key, what will happen with production if we upload this key? What will happen with users with old versions, who are still using sdk 35? Will expo servers handle those type of things?

**Comment by dhcmega** [comment]
> If you want to use notifications on Android you'll need to setup a Firebase project. 🙂
> 
> <in grim voice>It's the only way.</in grim voice>
> 
> https://docs.expo.io/guides/using-fcm/#client-setup

Hi this is new restriction out of the blue?
I have a published app, upgraded to SDK37, and published the new build.
All my previous users are receiving notifications normaly, but new users have no token (Couldn't get push token for device. Check that your FCM configuration is valid.)

What is it going on here? FCM is now mandatory? https://docs.expo.io/guides/using-fcm/?redirected Because it was always optional and it's not avaiable for iOS

Please clarify!

Thanks!!

**Comment by brentvatne** [comment]
FCM is not required on iOS. It is required on Android. https://developers.google.com/cloud-messaging/faq

**Comment by dhcmega** [comment]
@brentvatne Hi! thanks for getting back to me.
So:
1) Starting on SDK37, new builds need FCM to be enabled in order to have notifications.
2) My SDK36 users (that haven't updated) and the SDK37 users that have updated from SDK36 are both still receiving notifications using the "original" EXPO Token.

If I build a new app with FCM, what will change?
1) Old SDK36 will continue to work normally?
2) New SDK37 will be able to generate a token and work I guess.
3) Users with SDK36, when they update, will get a new EXPO Token?
4) Running `expo push:android:upload --api-key <your-token-here>` will disable the previous "way" of sending notifications or legacy and FCM will live together? I'm afraid of running that command and fixing notifications for new builds but breaking it for old builds.

Thanks again.

**Comment by bill-pairaktaridis** [comment]
This is a strange issue that seems to pop up every now and then. Not all our users have it and I've tested on an entirely fresh install and I'm getting push notifications normally. Also, I had set up FCM quite a while ago and everything seemed to be working fine. Honestly, I don't know if I should worry or not, as the error pops up on Sentry maybe once every couple of days, whereas we send dozens of notifications to most of our users every day.

**Comment by xdajay** [comment]
Expo Guys Didn't expect such poor communication! from your end, we did a limited public release and all android users did not receive any notification, one month back it was generating tokens for android smoothly!

**Comment by dhcmega** [comment]
I just went for it. I don't know if it was really needed.
I have added FCM to my app, registered the server key, created a new build and uploaded it to google play.
Add a feature to re upload the ExponentPushToken every time the home screen is shown.
Testing was working Ok. Now I am waiting for the production build to became public so I can test the real case. I think it will work Ok.
A better Breaking Changes section would have been very helpful.

Thanks

**Comment by Shajansheriff** [comment]
This one [7884](https://github.com/expo/expo/issues/7884#issuecomment-615270862) solved the issue for me.

**Comment by gustavolsilvano** [comment]
I wasn't logged in on expo. To check that, run `expo whoam`i.
If you're not logged in too, just login using `expo login`.

**Comment by BrodaNoel** [comment]
This is weird... 1 month ago I had this problem, so I did what it says in https://github.com/expo/expo/issues/7884#issuecomment-617050920, I build and deployed again, and it works. 1 week ago, I did another build + deploy (standalone, always) and I got it broken again... So, I went to update the FCM file (google service provider) for Android and for iOS (from Firebase), but they have no changes at all.

So now, I have all the FCM files updated (iOS and Android), and I don't have any other workaround here.

**Comment by BrodaNoel** [comment]
I just found this information that may help:
I'm seeing the log that I received on Sentry when it tracked this error, and something weird happens: Clearly I have a problem in my app, because seems like I am trying to get the token 2 times, where the first time it works, but the error is throw in the second try.

Clearly I have an error in my code, because I should not be doing it, but... well... I'm doing it, and I am getting this error. There are the steps that my app if following:

1. Someone opens the app by first time.
1. I ask for the permissions to send push notifications
1. This ANONYMOUS (important!) user grant the permission and I properly get the push token.
1. I save that token in the DB as an "anonymous user token".
1. Then, the anonymous user decides to become an user, she/he registers on the app
1. After the registration process is done, I GET THE TOKEN AGAIN in order to associate it with the new user. <<< 💥 crash.

**Comment by rnakhan** [comment]
BroadNoel - What do you mean by anonymous user? Are you using Firebase anonymous user mechanism by any chance? The token is device specific and should not be affected when your user is signed in or not.

**Comment by BrodaNoel** [comment]
No no. No Firebase login. Just a custom login.

I was just trying to explain why I have 2 executions to check get token. Just giving some context

Broda Noel

**Comment by cruzach** [comment]
@dhcmega it seems like your questions should all be answered by [this response](https://github.com/expo/expo/issues/7727#issuecomment-616674874) that has been linked previously, especially this section:

> **I'm still on SDK lower than 37. How to approach this issue?**
> I was afraid of breaking any behavior that users of previous SDKs may depend on, so I didn't change anything apart from adding a warning.
> 
> If you're on SDK36 or lower and would like to use your own google-services.json:
> 
> - either upgrade to SDK37 and live on a happy life with only googleServicesFile defined in app.json
> - or stay on your current SDK and keep using the workaround described at #7727 (comment).

In short, your SDK 36 users shouldn't be affected. 

It looks like this issue can be closed, if you're running into this error then you should check that your fcm configuration is valid by running `expo push:android:show` from your project directory. If there is no key or that key doesn't match your existing FCM api key, then follow [this guide](https://docs.expo.io/push-notifications/using-fcm/)

**Comment by MedNabilEssefaihi** [comment]
Hello everybody,
To get notification using the expo default code as in the second expo example:
 https://docs.expo.io/versions/latest/sdk/notifications/


To correct the bug:

1 .so expo uses:  async function registerForPushNotificationsAsync() { ... }
2 . inside that function you will find incrementation of 'token':
     token = (await Notifications.getExpoPushTokenAsync()).data;

3. the problem is getExpoPushTokenAsync() isn't return anything because it's works only in ''https://snack.expo.io/''
4. to correct that change it to getDevicePushTokenAsync() => to get your device token:
    token = (await Notifications.getDevicePushTokenAsync()).data;



Good luck eveyone 😃

**Comment by cruzach** [comment]
> the problem is getExpoPushTokenAsync() isn't return anything because it's works only in ''https://snack.expo.io/''

this isn't true. `getExpoPushTokenAsync` should work whether you're running the app in snack or anywhere else

the ExpoPushToken and the DevicePushToken are two separate things. The former is used with Expo's push notification service, the latter is used with other push services like APNS and FCM
