### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by jb9229** [expo/expo#7836]
## 🐛 Bug Report

expo-firebase-recaptcha,

is it possible using 'import { FirebaseRecaptchaVerifier } from 'expo-firebase-recaptcha';'

at React Native  Function Component?

### Environment

expo-firebase-recaptcha: v1.0.0
expo: 37.0.0(using expoKit)

### Reproducible Demo
<img width="348" alt="스크린샷 2020-04-14 오전 11 52 15" src="https://user-images.githubusercontent.com/3200647/79181224-e7ccf180-7e46-11ea-9ab6-80fca775ccdc.png">

**Comment by brentvatne** [comment]
hi! that is not a reproducible demo. please follow the guide on this link and create a new issue, we can’t help you with the information provided here. https://stackoverflow.com/help/minimal-reproducible-example
