### ISSUE TITLE
[android] [image-manipulator] change base64 encoding options to match with other platforms

### ISSUE THREAD

**Issue by jarvisluong** [expo/expo#7837]
This will also affect other modules which produces base64 output as well (camera, file system, ...)

## 🐛 Bug Report

The base64 output from Android and iOS for the method `ImageManipulator.manipulateAsync` does not match given the same image.

The output does not necessary need to be exactly matched, but the way base64 output is created currently not matched. When I look at the source code of expo-image-manipulator, on Android, the output is produced by:

https://github.com/expo/expo/blob/112256a586ebff5e9b78458da6669e6e64a4cedc/packages/expo-image-manipulator/android/src/main/java/expo/modules/imagemanipulator/ImageManipulatorModule.java#L157

This option (Base64.DEFAULT) will produce a base64 result which will inject line termination character every 74 (maybe?) character.

on iOS: https://github.com/expo/expo/blob/112256a586ebff5e9b78458da6669e6e64a4cedc/packages/expo-image-manipulator/ios/EXImageManipulator/EXImageManipulatorModule.m#L266):

This option will produce a base64 result which will be a long line (without line terminators)

and on web:
https://github.com/expo/expo/blob/112256a586ebff5e9b78458da6669e6e64a4cedc/packages/expo-image-manipulator/src/ExpoImageManipulator.web.ts#L199
This method will produce a base64 result which will be a long line (without line terminators)

What we can do is to change the option on Android into:

```
Base64.encodeToString(byteOut.toByteArray(), Base64.NO_WRAP)
```
(reference: 
1. https://developer.android.com/reference/android/util/Base64#NO_WRAP
2. https://stackoverflow.com/questions/32935783/java-different-results-when-decoding-base64-string-with-java-util-base64-vs-and
)

### Steps to Reproduce

Here is a minimal snack: https://snack.expo.io/@bankify_expo_admin/085b26

### Expected Behavior

The base64 output should be the same given the same image

**Comment by cruzach** [comment]
Thanks for the excellent bug report @jarvisluong ! I agree that this should be consistent across all platforms

Would you like to open a PR for this change?

**Comment by jarvisluong** [comment]
@cruzach Definitely, Should we change the base64 encoding for FileSystem and Camera as well?

**Comment by cruzach** [comment]
Seems like you [aren't the only one who's discovered this](https://github.com/expo/expo/issues/1522) so that may be a good idea. I'm not sure if this would then be considered a breaking change though

**Comment by jarvisluong** [comment]
I see that in FileSystem the decoding method is already using .NO_WRAP as here:

https://github.com/expo/expo/blob/0ed80a9dd68f1580f64971c9de33187c9ae505ff/packages/expo-file-system/android/src/main/java/expo/modules/filesystem/FileSystemModule.java#L248

So yes, bringing existing decoders to be the same option would be a good idea!

**Comment by cruzach** [comment]
thanks @jarvisluong ! closed in https://github.com/expo/expo/pull/7841
