### ISSUE TITLE
[Bare Workflow] Disabling OTA updates not functioning

### ISSUE THREAD

**Issue by jonathanstiansen** [expo/expo#7839]
### Environment

 Expo CLI 3.17.24 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.17.24

### Steps to Reproduce
As listed on the expo-updates page [here](https://github.com/expo/expo/tree/master/packages/expo-updates#configuration) I've added the `.ENABLED` key to my `main/AndroidManifest.xml` like so

``` xml
      <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="37.0.0" />
      <meta-data android:name="expo.modules.updates.ENABLED" android:value="false" />
      <meta-data android:name="expo.modules.updates.EXPO_RELEASE_CHANNEL" android:value="default" />
```

And added the `EXUpdatesEnabled` key to my ios `Expo.plist` like so:

```
	<key>EXUpdatesEnabled</key>
	<string>false</string>
	<key>EXUpdatesReleaseChannel</key>
	<string>default</string>
	<key>EXUpdatesSDKVersion</key>
	<string>37.0.0</string>
```

I run a release build with Android with `./gradlew installRelease`, copy the created `apk` and put it on an android phone.

For iOS I click the play button while holding the `option` key and select *Build Configuration* -> *Release* and press *Run*

It opens on a simulator showing the app.

When I change my App.js and run an `expo publish` I **get** that update on both iOS and Android. 

### Expected Behavior

I get no update on either iOS nor android

### Actual Behavior
I get the update on both android and iOS. I do realize that when in development mode OTA is always enabled - that's why I selected release builds for both.

### Reproducible Demo
1. Clone [this](https://github.com/jonathanstiansen/ExpoOTADemo) repo. 
2. Run a release build, in the android folder run `./gradlew installRelease`
3. For iOS I click the play button while holding the `option` key and select *Build Configuration* -> *Release* and press *Run*
4. Change `App.js` text in some way.
5. Run `expo publish`

**Comment by jonathanstiansen** [comment]
For iOS I found out why this was happening. Booleans for the plist are not the same format as strings, which makes sense. I had to use XCode to add the value, and select type = boolean and it formatted it properly. With Android are still unable to get it to function as described, we created a work around which I will publish later.

**Comment by edwardchen** [comment]
Shouldn't having expo.updates.enabled == false in app.json configure the app to not do OTA updates?

**Comment by jonathanstiansen** [comment]
@edwardchen it doesn't in bare workflow. Here is the docs for "sort of" disabling them: https://github.com/expo/expo/tree/master/packages/expo-updates 😸

**Comment by josmas** [comment]
@jonathanstiansen could you share your workaround for Android; we've been having a number of issues in the last week that could be explained by the fact the config below in app.json does not apply to bare workflow for SDK 37 with expo-updates:
```
    "updates": {
      "enabled": false,
      "fallbackToCacheTimeout": 0
    },
```

After reading this thread and a couple others, we want to try the following:
For iOS we have changed Expo.plist within xcode and the resulting property when selecting a Boolean with a value of `NO` (as in the expo-updates readme) is:
```
<dict>
	<key>EXUpdatesEnabled</key>
	<false/>
	<key>EXUpdatesCheckOnLaunch</key>
	<string>NEVER</string>
[...]
```

So that should do the trick for iOS. This is what we've done for Android in the manifest:
```
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="false"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="NEVER"/>
```

But I am terrified of publishing again if the instructions do not work for Android. We've had a full week of random crashes and very angry users since we released our v37 upgrade. This may explain some of that randomness.
Any information would be highly appreciated.

**Comment by WolfyUK** [comment]
For Expo 39, only the following would work for me (default `URL` and `VERSION` items **must** be present):

```
<manifest ...>
    ...
    <application ...>
        <meta-data android:name="expo.modules.updates.ENABLED" android:value="false" />
        <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="NEVER" />
        <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="YOUR-APP-URL-HERE" />
        <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="YOUR-APP-SDK-VERSION-HERE" />
        ...
```
