### ISSUE TITLE
Cannot get permissions using PermissionsAndroid on standalone app

### ISSUE THREAD

**Issue by PaperMonster** [expo/expo#784]
I'm trying to request `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` on freshly detached Expo app using [PermissionsAndroid API](https://facebook.github.io/react-native/docs/permissionsandroid.html). The code was almost the same as Camera permission example code except changing `PermissionsAndroid.PERMISSIONS.CAMERA` to `PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE`. However I received following error:

````
Error: Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity.
````

I tried the same code on app created by react-cli and didn't get any error. Seems like Expo SDK activity doesn't extend ReactActivity nor PermissionAwareActivity. Is there any other method to manually request these permissions?

Additional info:
    "expo": "^21.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",

**Comment by ide** [comment]
What version of Android are you using?

**Comment by PaperMonster** [comment]
@ide Tested on Lenovo Moto M Android 6.0

**Comment by TimothyKrell** [comment]
I'm getting this error as well using [this library](https://github.com/transistorsoft/react-native-background-geolocation) and a detached expo-kit project. I don't get the same error using just a vanilla react-native project. Not sure what the problem here is. Using android 7.1.

**Comment by tedkimzikto** [comment]
anyone?

**Comment by ide** [comment]
I'm not sure what the root cause is but if you can modify the Java code yourself and make progress that's probably the best way forward for now.

**Comment by tedkimzikto** [comment]
I will try to implement the PermissionAwareActivity class from MainActivity under android. And see how it goes from there.

I’ve detached the project, just let you guys know. ReactActivity class is already implementing the class Im not sure why the problem causes.

**Comment by mateusmedeiros** [comment]
Chiming in just to say that I'm also having this problem with those exact same versions of everything, also right after ejecting a pure expo app and running on an Android 7.1.

**Comment by tedkimzikto** [comment]
@mateusmedeiros I've managed to implement PemissionAwareActivity from MainActivity under android project. Refer to ReactActivity.java from RN (https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java)

I'm not sure why detached project is not handling these issues :(

**Comment by mateusmedeiros** [comment]
@tedkimzikto Agreed, I think it should be considered a bug for an ejected project with expokit to not have this already implemented in the MainActivity.

I too borrowed some parts from `ReactActivity` to fix this for my project, but it's a shame, this is such a basic functionality compared to other complex things expokit already give us 🙂 .

**Comment by TimothyKrell** [comment]
For those who need it, here is my edit to `MainActivity.java` to get things to work. There may be a better way to write this. I don't know Java very well.

```java
import android.os.Bundle;
import android.annotation.TargetApi;
import android.os.Build;
import android.support.annotation.Nullable;

import com.facebook.react.ReactPackage;
import com.facebook.react.modules.core.PermissionAwareActivity;
import com.facebook.react.modules.core.PermissionListener;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.thehelperbees.helperhive.generated.ExponentBuildConstants;
import host.exp.expoview.ExponentActivity;

//public class MainActivity extends ExponentActivity {
// Original class def ----^
public class MainActivity extends ExponentActivity implements PermissionAwareActivity {

  @Nullable private PermissionListener mPermissionListener;

  @Override
  public String publishedUrl() {
    return "exp://exp.host/@timothykrell/helper-hive";
  }

  @Override
  public String developmentUrl() {
    return ExponentBuildConstants.DEVELOPMENT_URL;
  }

  @Override
  public List<String> sdkVersions() {
    return new ArrayList<>(Arrays.asList("21.0.0"));
  }

  @Override
  public List<ReactPackage> reactPackages() {
    return ((MainApplication) getApplication()).getPackages();
  }

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  @Override
  public Bundle initialProps(Bundle expBundle) {
    // Add extra initialProps here
    return expBundle;
  }


  // Allow using PermissionsAndroid in react-native-background-location library
    // Didn't work with Expo. See https://github.com/expo/expo/issues/784
    // Copied solution from https://github.com/wix/react-native-navigation/pull/470/files
    @TargetApi(Build.VERSION_CODES.M)
    public void requestPermissions(String[] permissions, int requestCode, PermissionListener listener) {
        mPermissionListener = listener;
        requestPermissions(permissions, requestCode);
    }

    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        if (mPermissionListener != null && mPermissionListener.onRequestPermissionsResult(requestCode, permissions, grantResults)) {
            mPermissionListener = null;
        }
    }
}
```

**Comment by watadarkstar** [comment]
@TimothyKrell This no longer works for me in SDK 26. Anyone know why?

**Comment by spaceemotion** [comment]
@watadarkstar It did the trick for me with Expo v28

**Comment by AmolGslab** [comment]
@TimothyKrell Getting same error "Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity." after updating MainActivity.java as provided by you.
Expo V : 55
Android SDK 26

Thanks.

**Comment by AmolGslab** [comment]
@watadarkstar did you fix this issue? I am also using SDK 26.

Thanks

**Comment by TimothyKrell** [comment]
@watadarkstar @AmolGslab I wish I could be of more help, but I don't have any active projects using this code anymore. Wrangling the Java monster on projects like this is a pain!

**Comment by gd1990** [comment]
I am unable to use in expo version 29. Same issue

**Comment by YoruNoHikage** [comment]
I was able to make it work by re-doing what ReactActivity did.

```java
import android.os.Bundle;
import javax.annotation.Nullable;
import com.facebook.react.ReactActivityDelegate;

// ...

public class MainActivity extends DetachActivity implements PermissionAwareActivity {
  private final ReactActivityDelegate mDelegate;

  protected MainActivity() {
    mDelegate = createReactActivityDelegate();
  }

  /**
   * Returns the name of the main component registered from JavaScript.
   * This is used to schedule rendering of the component.
   * e.g. "MoviesApp"
   */
  protected @Nullable String getMainComponentName() {
    return null;
  }

  /**
   * Called at construction time, override if you have a custom delegate implementation.
   */
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName());
  }

  // ...

  @Override
  public void requestPermissions(String[] permissions, int requestCode, PermissionListener listener) {
    mDelegate.requestPermissions(permissions, requestCode, listener);
  }

  @Override
  public void onRequestPermissionsResult(
    int requestCode,
    String[] permissions,
    int[] grantResults) {
    mDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
  }
}
```

**Comment by mguay22** [comment]
This is still a problem with Expo SDK v31.0. @TimothyKrell thank you - your solution worked.

**Comment by StevenJW** [comment]
I'm having this issue with a detached expo project as well. I used the above code but it doesn't seem to change anything for me. Am I supposed to run this with react-native run-android (which gives an error) or still npm start? I'm using expo SDK v32 and Samsung Galaxy S7. Do I need to implement the code from TimothyKrell a certain way or could I just copy-paste it in my MainActivity.java?

**Comment by AdamJNavarro** [comment]
Hey all,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,

Adam
