### ISSUE TITLE
FirebaseRecaptchaVerifier, Cannot call a class as a function

### ISSUE THREAD

**Issue by jb9229** [expo/expo#7845]
## 🐛 Bug Report

expo-firebase-recaptcha,

is it possible using 'import { FirebaseRecaptchaVerifier } from 'expo-firebase-recaptcha';'

at React Native  Function Component?

### Environment

- expo-firebase-recaptcha: v1.0.0

- expo: 37.0.0(using expoKit)

- I refer to the 'https://docs.expo.io/versions/latest/sdk/firebase-recaptcha/#customizing-the-appearance' document

-  'FirebaseRecaptchaVerifierModal' example work find but FirebaseRecaptchaVerifier got error.

### Expected Behavior
Custom LoginScreen React Component mount successfully.

### Actual Behavior
<img width="348" alt="스크린샷 2020-04-14 오전 11 52 15" src="https://user-images.githubusercontent.com/3200647/79181224-e7ccf180-7e46-11ea-9ab6-80fca775ccdc.png">

### Reproducible Demo

1. create expo managed workflow project(expo project -> eject)
2. yarn add expo-firebase-recaptcha
3. create Login React Component
`import * as firebase from 'firebase/app';
import {FirebaseRecaptchaVerifier} from 'expo-firebase-recaptcha'; 

const LoginScreen = () => {
return (
<View>
           < FirebaseRecaptchaVerifier
            ref={ref => recaptchaVerifier = ref}
            firebaseConfig={firebase.app().options} />
     </View>)
}
export default LoginScreen;`

**Comment by brentvatne** [comment]
hi there! this is not a reproducible example, this is a series of steps to reproduce. you also didn't detail whether you actually configured the firebase app as described in https://docs.expo.io/versions/v37.0.0/guides/using-firebase/

further, expokit is deprecated and we do not recommend using it. you can't actually even eject to expokit from a sdk37 project so your instructions don't match the description..

**Comment by jb9229** [comment]
@brentvatne expokit will use until sdk38.

now bare workflow not support air update(OTA??)

I think FirebaseRecaptchaVerifier has a problem or document example is wrong.

**Comment by brentvatne** [comment]
you can use ota updates in bare apps: https://github.com/expo/expo/blob/master/packages/expo-updates/README.md - it is set up by default when you eject or init an app.

can you please create an app that you can share that demonstrates this bug rather than explaining steps? it's too hard to know which steps you left out (you definitely left some out) and whether you did that on purpose or if you think that's all of the steps.

**Comment by brentvatne** [comment]
also cc @IjzerenHein - maybe we need to be really clear that it's necessary to configure firebase before using the recaptcha lib

**Comment by jb9229** [comment]
https://github.com/expo/expo/blob/master/packages/expo-firebase-recaptcha/src/FirebaseRecaptchaVerifier.ts

it is not React Component;;

how can I display the <FirebaseRecaptcha> component inline in our screen?

is it possible extend the class??

if I have to extend the class, I think the FirebaseRecaptchaVerifier example is weird.

**Comment by brentvatne** [comment]
here are examples of it being used: https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/FirebaseRecaptchaScreen.tsx

if you can share a reproducible example we would be happy to help! closing until you provide one

**Comment by jb9229** [comment]
The Reproducible example is already shared from your expo document.

<img width="827" alt="스크린샷 2020-04-15 오후 12 35 41" src="https://user-images.githubusercontent.com/3200647/79296228-cc7ce780-7f15-11ea-984c-ce8f6458cd23.png">

[](https://docs.expo.io/versions/latest/sdk/firebase-recaptcha/#customizing-the-appearance)

**Comment by Leedwing** [comment]
In the example on expo documentation they used `FirebaseRecaptchaVerifier` instead of `FirebaseRecaptcha`.

The render method should look like that:
`render() {
    return (
      <FirebaseRecaptcha
        style={...}
        firebaseConfig={...}

        // Store the reCAPTCHA token when it has been verified
        onVerify={recaptchaToken => this.setState({
          recaptchaToken
        })} />
    );
  }`

Hope it could help someone
