### ISSUE TITLE
Changing the "androidNavigationBar" "backgroundColor" dynamically

### ISSUE THREAD

**Issue by YahiaBadr** [expo/expo#7847]
I want to change the  "androidNavigationBar" style based on some functionality in my expo app.

**Comment by byCedric** [comment]
Hi @YahiaBadr, you should be able to do this with the [StatusBar API in React Native](https://docs.expo.io/versions/latest/react-native/statusbar/). If you have other questions, take a look at our [Expo Developers slack](https://slack.expo.io/) or [our forum](https://forums.expo.io/). It's a great place to ask general questions which are not necessarily issues.

**Comment by allhaze** [comment]
@byCedric, @YahiaBadr asked about androidNavigationBar, not about androidStatusBar.

**Comment by YahiaBadr** [comment]
@allhaze  exactly!

**Comment by byCedric** [comment]
Hi @allhaze and @YahiaBadr, I'm sorry I misunderstood the question! At the moment, we don't have support changing this on the fly in the managed flow. There is an [open feature request here](https://expo.canny.io/feature-requests/p/android-navigation-bar-background-color-change-on-the-fly), which includes a [React Native library](https://github.com/thebylito/react-native-navigation-bar-color) that you can use in bare/ejected flow.

I hope this helps more than my previous comment!

**Comment by YahiaBadr** [comment]
@byCedric It's okay no worry, then i will have to wait for this feature to be added 👍 .
