### ISSUE TITLE
firebase phone auth. is recaptcha required?

### ISSUE THREAD

**Issue by jpb-lourenco** [expo/expo#7854]
Hello, just a quick question (not sure if this is the right place, since it isnt exactly an issue.)

When using the firebase phone auth with expo, is it required to make the user solve a recaptcha or is it possible to remove that?

**Comment by IjzerenHein** [comment]
This is necessary as the Firebase JS SDK requires a reCAPTCHA validation to work for phone auth.
If you really don't want this you could consider using the bare-workflow in which you can use the native SDKs which solves this differently.

**Comment by jpb-lourenco** [comment]
I'll look into that option.
Thank you for the answer

**Comment by SimonHausdorf** [comment]
@IjzerenHein can't we use invisible recaptcha here and only show the modal if recaptcha invisible validation is failing?

**Comment by yonureker** [comment]
@IjzerenHein same as @SimonHausdorf. Is it possible to add the invisible recapthca as mentioned here?  https://firebase.google.com/docs/auth/web/phone-auth#use-invisible-recaptcha

**Comment by SimonHausdorf** [comment]
https://github.com/expo/expo/blob/sdk-38/packages/expo-firebase-recaptcha/src/FirebaseRecaptcha.tsx#L36

This is the line responsible for the appearance of the captcha. However, I wasn't able to figure out how to implement the invisible one. It needs a bit more than just replacing it with `invisible`. Maybe someone will find some time and can open a PR.
