### ISSUE TITLE
[Bare Workflow] SDK 37 expo-notifications "Native module cannot be null" on standalone or simulator build for iOS

### ISSUE THREAD

**Issue by nbgoodall** [expo/expo#7855]
## 🐛 Bug Report

Hey, using `expo-notifications` in the Bare workflow with SDK 37 results in a `Native module cannot be null` error.

### Environment

```
  Expo CLI 3.18.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
    npmGlobalPackages:
      expo-cli: 3.18.0
```

Building for iOS (both Standalone and Simulator builds).
### Steps to Reproduce

1. `expo init testapp` and select the bare workflow.
2. `expo install expo-notifications` then`cd ios && pod install`.
3. Update the `bundleIdentifier` under `ios` in `app.json` to something (e.g. `com.test`).
4. Add `import * as Notifications from 'expo-notifications'` in `App.js`.
5. `expo build:ios -t simulator` (same happens without the simulator build, but quicker to get this working).
6. Download the build and run `tar zxvf <tar file location>`.
7. Open an iOS simulator, and run `xcrun simctl install booted <app_file.app>`.
8. Boot the app!

### Expected Behavior

The app should launch and display the home screen.

### Actual Behavior

It crashes on startup with `Unhandled JS Exception: Invariant Violation: Native module cannot be null.` (seen in the macOS console for the simulator).

### Reproducible Demo

Repo at https://github.com/nbgoodall/expo-notifications-demo (created using the steps above).

Thank you :)

P.S. Expo is awesome.

**Comment by brentvatne** [comment]
hi! `expo build:ios -t simulator` does not work with bare workflow! this is intended for managed workflow. if you'd like to do a simulator build for bare workflow then boot up xcode and hit run.

we're working on making the build services support bare apps but it doesn't yet.

**Comment by brentvatne** [comment]
created https://github.com/expo/expo-cli/issues/1889 to provide a better warning in this case

**Comment by nbgoodall** [comment]
Grand, thank you 🙏
