### ISSUE TITLE
OTA Expo-updates for multiple environments 

### ISSUE THREAD

**Issue by bulby97** [expo/expo#7857]
Is expo-updates working with different environments on a bare workflow ? Do I need to use release-channels ?

How to publish for my staging and prod app ?

As you can see I’m a bit confused at the moment. Expo-updates look awesome but I can’t find any explanations on how to use it correctly with multiple environments.

I would like to have a step by step explanation on how to do that please :slight_smile:

**Comment by brentvatne** [comment]
hello! this same doc that was originally intended for managed workflow applies in this case as well: https://docs.expo.io/versions/v37.0.0/distribution/release-channels/#example-workflow

we're working on reorganizing the docs so things aren't unnecessarily separated between managed and bare workflow now that there is an increasing amount of overlap :) let me know if that helps

**Comment by bulby97** [comment]
Thank you @brentvatne.
So because `expo build` doesn't work with bare workflow, if I understand correctly I'll need to edit `Exshell.plist` and configure a channel for every of my scheme, and then edit `AppConstants.java` to do the same.

Sorry to ask but I'm a complete noob in android. How do I modify the `RELEASE_CHANNEL` value in `AppConstants.java`, where do I find that file in my project and how do I change it for every environment ? Will I need to put stuff inside `res/strings.xml` ?

**Comment by brentvatne** [comment]
you can follow the instructions in https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#configuration for how to do this, it tells you which files the config should be in and what properties to use for release channel and other config properties

**Comment by bulby97** [comment]
Thank you !
