### ISSUE TITLE
How do you read base64 of image that was previously saved using the FileSystem?

### ISSUE THREAD

**Issue by ShayanJavadi** [expo/expo#786]
I save my image like so in my container:

```
export const takePicture = (camera) => async (dispatch) => {
  if (!camera) {
    return;
  }

  let result = await camera.takePictureAsync({ base64: true });

  FileSystem.moveAsync({
    from: result.uri,
    to: `${FileSystem.documentDirectory}photos/Photo_${Date.now()}.jpg`,
  })
    .then(() => {
      dispatch(updatePhotos());
      Vibration.vibrate();
    });
};
```

I understand that base64 is available to me when I take the picture, but is there any way to read the saved image file using the FileSystem? when I try to read the file it throws an error saying cannot read it.

**Comment by ide** [comment]
You should be able to read the image if you have the right permissions. What platform is this?

**Comment by ShayanJavadi** [comment]
@ide It's iOS. I can read the images using an Image tag but I can't read the files data

**Comment by pabeda-bt** [comment]
The same error occurs on me too.

**Comment by sjchmiela** [comment]
It is now achievable with `FileSystem.readAsStringAsync` and providing `base64` option. 🙂
