### ISSUE TITLE
expo-print for web

### ISSUE THREAD

**Issue by DrMisQ** [expo/expo#7862]
expo print in web print current screen doesn't print selected html

    Print.printAsync({
       html: `<p>hello</p>`,
    })

**Comment by byCedric** [comment]
Hi @DrMisQ, thanks for bringing this up! Unfortunately, Print has limited support on web and the docs doesn't properly reflect that. I'll update that to emphasize this.

At the moment, `Print.printAsync` only prints the current screen's HTML. That means you can still use it, but only to print the current screen. The current web printing specification has no feature to print out custom html or documents (uri), [although MDN guide itself provides some workarounds](https://developer.mozilla.org/en-US/docs/Web/Guide/Printing#Examples). If you want these properties to be fully implemented (including some workarounds), please [open a feature request at canny](http://expo.canny.io/).
