### ISSUE TITLE
[Expo 37] [Managed] Netinfo + Real device expo client breaking

### ISSUE THREAD

**Issue by jonathanstiansen** [expo/expo#7871]
## 🐛 Bug Report

1. Freshly downloaded expo client from app store (Supported SDKs includes 37)
2. Our app was upgraded to Expo 37.0.7
3. We run on a local iOS simulator and the app works.
3. When we run on one android device (with most recent updated expo client) we get:`RNCNetInfo.getCurrentState got 3 arguments, expected 2.`
4. When we run on iOS we get a crash of the whole Expo client - no errors show.
5. When we comment out our NetInfo code the app runs everywhere.
6. Our netinfo version is at: `"@react-native-community/netinfo": "5.5.1"`

Seems like this has happened with older versions as well: https://github.com/react-native-community/react-native-netinfo/issues/297

Is it possible that because Netinfo was updated to 5.5.1 after the expo client was release that we are getting two different versions of the native code with our simulators vs app store?

### Environment

Expo CLI 3.18.2 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      npm: 6.9.2 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^37.0.0 => 37.0.7
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^4.3.7 => 4.3.7
    npmGlobalPackages:
      expo-cli: 3.18.2

I'll work on making an reproducable demo after work but if at all possible, it'd be awesome if someone could answer the above question without it :-)

**Comment by byCedric** [comment]
Hi @jonathanstiansen! Thanks for the report. Unfortunately, I couldn't reproduce this error with a clean project. I made a small [repro that you can check on your device here](https://snack.expo.io/@bycedric/netinfo-test).

The issue from the older issues are related to duplicate and incompatible versions being included in the project as nested dependencies. You can quickly check this too by running either one of these commands:

```
$ yarn list @react-native-community/netinfo
$ npm list @react-native-community/netinfo
```

If there are multiple versions, you should be able to see them. In my example, you should see something similar like below. In case this isn't the issue, could you try updating the Expo CLI (e.g. with `expo client:install:android`) to test this on the latest version? If that fails, could you provide a small repro for us so we can investigate it further?

```
/home/cedric/Projects/expo/support/test-netinfo
└── @react-native-community/netinfo@5.5.1 
``` 

Hope it helps 😄

**Comment by jonathanstiansen** [comment]
@byCedric figured it out. Your snack didn't cause an issue. 
This may still be a bug you guys want to fix.

1. In expo 36 - we used to have a key `expo.sdkVersion`. Seemingly it's not required anymore, which is nice. 
2. When running the upgrade script for expo from 36-37 it didn't update it nor delete it.
3. Expo seems to prefer that over the default version, so it was using expo 36 libraries on the phone.
Removing the line:

```
    "sdkVersion": "36.0.0",
```
Solved the problem 😄

**Comment by brentvatne** [comment]
@jonathanstiansen - what expo-cli version are you using? old versions did not remove that field when you update but you can verify this works as expected on new expo-cli with:

- `expo init hello --template blank@sdk-36`
- `cd hello && expo upgrade`

notice that there is no sdkVersion in app.json

**Comment by jonathanstiansen** [comment]
Sounds good @brentvatne at the time I upgraded it was the most up to date - but sounds good! I'll close this.
