### ISSUE TITLE
[expo-splash-screen-command] script never completes for android

### ISSUE THREAD

**Issue by jeb218** [expo/expo#7874]
### Environment

Expo CLI 3.18.2 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.9.0/bin/npm
    npmPackages:
      expo: ^37.0.7 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.18.2

android/ios
### Steps to Reproduce

1. configure managed expo project
2. add in splash screen
3. expo eject
4. yarn run expo-splash-screen -p "android" -r "contain" "#ffffff" ~/splash.png
5. expo-splash-screen never completes, it just hangs there for hours.
6. I ctrl-c'd the process, and of course the splash screen isn't shown since the process didn't complete

### Expected Behavior

script should complete, and make all necessary project modifications, and show the splash screen when the project is run

### Actual Behavior

the script doesn't complete, and doesn't make all the project changes it need to for the splash screen to show up

### Reproducible Demo

https://github.com/jeb218/expoSplashBug

the first time you run `yarn run expo-splash-screen -p "android" -r "contain" "#ffffff" ~/splash.png`

it will respond with: 

There was an error running expo-splash-screen command: EEXIST: file already exists, mkdir '/home/barrus/Development/Jird/expoSplashBug/android/app/src/main/res/drawable'

error Command failed with exit code 1.

Even though that directory does not exist.

The second time (even though now the directory does exist, it won't throw that error), it will just hang there indefinitely until you kill the process.

**Comment by jonathanstiansen** [comment]
Certainly seems like a bug - in the meantime you can get it working by deleting the files in drawable - at the very least the XML files that are empty.

**Comment by jeb218** [comment]
I had tried that in my real project, and while it did then create the xml files again with content, the splash image doesn't show up. I did it now on my demo project, and same thing - it created the files with content, but no splash image shows, just a blank screen. The script doesn't modify MainActivity like I assume it should be doing

After doing what you suggested, and then manually modifying MainActivity, it looks like it is working now. Sadly I'm getting another error now that I wasn't getting before, but it isn't related to splash screens as far as I can tell.

Thanks for your help

**Comment by danielholmes** [comment]
For the hanging issue, I tracked it down in my instance to `configureAndroidManifestXML`. i.e. removing that from `configureAndroidSplashScreen` makes it run fine.

Further digging down it seems to hang on this line in `file-helpers` for me:

```js
replacePatternOccurrence = originalFileContent.search(replacePattern);
```

Which seems crazy (it's just a regex search). I don't have a deep knowledge of regexps, but is there some kind of infinite recursion in this regex that it's trying to use:

```regex
/(?<nameBeforeTheme>(?<=(?<application1>^.*?<application(.*|\n)*?)(?<activity1>^.*?<activity(.|\n)*?android:name="\.MainActivity"(.|\n)*?))(?<androidTheme1>android:theme=".*?"\s*?))|((?<=(?<application2>^.*?<application(.|\n)*?)(?<activity2>^.*?<activity(.|\n)*?))(?<androidTheme2>android:theme=".*?"\s*?)(?=((.|\n)*?android:name="\.MainActivity"(.|\n)*?)))/m
```

**Comment by danielholmes** [comment]
This JS regex tester shows it timing out for my manifest file, which is pretty small, so I think it's probably the case that there's an issue in the regex: https://regex101.com/r/aNrx7D/2

**Comment by bbarthec** [comment]
Sorry that this thing happened to you guys! 😞 
As `expo-splash-screen-command` is actually being rewritten and enhanced a little bit (getting rid of these nasty RegExps is part of this process) I suggest fallbacking to manual configuration for now (you can find instructions in [expo-splash-screen README](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#manual-configuration-1)) 😉

**Comment by erite89** [comment]
Same problem.
As well manual configuration is not working for me.

I did everything according to expo-splash-screen README manual configuration and still have blank Android splash screen.

That's my MainActivity code:
`public class MainActivity extends ReactActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      SplashScreen.show(this, SplashScreenImageResizeMode.COVER, ReactRootView.class);
    }

    @Override
    protected String getMainComponentName() {
        return "main";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
}`

Please help.

**Comment by bbarthec** [comment]
@erite89, given that so many parts of your project have to be configured correctly to achieve `SplashScreen`, your `MainActivity` code is not sufficient to provide any useful feedback regarding your problem. I might be able to help if you provide some [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by ExpoNfinity** [comment]
I'm experincing the issue when spalsscreen remains shown but when i'm touching the screen, i see with console that i actually touch active elements of application screen, i.e. loading passed and application runs behind splash. Like render buffer is stuck with splash.. 
I have to restart app and builder few times to pass by, it eats loooots of time and can be assumed as critical problem

**Comment by ExpoNfinity** [comment]
Uninstalling expo debug client app and installing it again helps btw, hope this will help you to locate the problem

**Comment by ExpoNfinity** [comment]
Bump

**Comment by bbarthec** [comment]
@ExpoNfinity, I see that your problem is not at all connected with the original issue (installation script being stuck vs problem with splash screen being rendered atop of your app while it shouldn't). Do you mind opening separate issue for that according to issue template? 😉 Pretty please 🙏
