### ISSUE TITLE
[expo-firebase-analytics] Firebase analytics logEvent doesn't log parameters

### ISSUE THREAD

**Issue by FatBuTa** [expo/expo#7878]
## 🐛 Bug Report
Can not see params in Firebase Analytics Events
### Environment
Manage project
expo cli: 3.18.0
"expo": "^37.0.0",
"expo-firebase-analytics": "~2.1.1",
"react": "16.9.0",
standalone app android and iOS

### Steps to Reproduce
I follow this guide: https://docs.expo.io/versions/latest/sdk/firebase-analytics/
the logEvent exactly same as example in the guide
`await Analytics.logEvent('ButtonTapped', {
  name: 'settings',
  screen: 'profile',
  purpose: 'Opens the internal settings',
});`

### Expected Behavior
After 24 hours,
1. The 'ButtonTapped' event was logged in the firebase analytics
2. Click to open that event, should see the parameter: "name", "screen", "purpose"

### Actual Behavior
After 24 hours,
1. The 'ButtonTapped' event was logged in the firebase analytics (This one is correct)
2. Click to open that event, can not see the parameter: "name", "screen", "purpose"

**Comment by SethuSenthil** [comment]
Hey, I'm having a similar issue where 'await Analytics.logEvent' does not log anything. Does it take 24 hrs to appear on the console? How did you resolve your issue?

**Comment by FatBuTa** [comment]
@SethuSenthil I don’t do anything. In your case, just wait for 24 hours. That is in the gg docs.
