### ISSUE TITLE
WebBrowser, AppAuth and AuthSession sign in flows skip seeking credentials after signing out 

### ISSUE THREAD

**Issue by desnor** [expo/expo#7879]
### Summary

[I filed an issue last week for this](https://github.com/expo/expo/issues/7763), but I wanted to raise it again as I feel like the response got the wrong end of the stick a bit and I wanted to clarify more closely the issue I'm highlighting, with some more references to issues other people are encountering for detail.

### Environment

  Expo CLI 3.17.18 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.7.1 - /usr/bin/zsh
    Binaries:
      Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v13.6.0/bin/npm
    npmPackages:
      expo: ^37.0.0 => 37.0.6
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.3.7
    npmGlobalPackages:
      expo-cli: 3.17.18

Target where this occurs: iOS in Expo Client and Standalone Build

### Steps to Reproduce

While it happens when using any of the `WebBrowser.openAuthSessionAsync`, `AppAuth.authAsync`, `AuthSession.startAsync`, this example uses `AppAuth.authAsync`.

```ts
export default async function appAuthSignIn() {
  const baseUrl = getSalesforceAppUrl();
  const redirectUrl = AppAuth.getDefaultOAuthRedirect();
  const config: AppAuth.OAuthProps = {
    issuer: baseUrl,
    serviceConfiguration: {
      authorizationEndpoint: SF_AUTHORIZE_URL,
      tokenEndpoint: SF_TOKEN_URL
    },
    clientId: SF_CONSUMER_KEY,
    additionalParameters: {
      display: 'touch'
    },
    redirectUrl
  };

  const authState = await AppAuth.authAsync(config);

  return authState as OAuthSessionTokenResponse;
}
```

1. User signs in via standard oauth flow implemented with `AppAuth.authAsync` to a Salesforce community interface
2. User is redirected back into our app.

This part is all good for an initial authentication session. However after signing out, whether by using the `AppAuth.revokeAsync` or a more manual `fetch` request to the same endpoint, subsequent attempts to sign in skip the user interaction for credentials altogether, despite the access token having been revoked and any browser cookie sessions also deleted from the oauth provider's server.

3. User presses sign in as per steps just above, implemented with `AppAuth.authAsync` to redirect to Salesforce community interface.
4. User is not prompted for credentials but instead redirected immediately back into our expo app with a new access token.

### Expected Behavior

After a user actively signs out of our expo app, and the access token is revoked, the next sign in should request the user to enter their credentials.

### Actual Behavior

Even after actively revoking all session cookies and access tokens for a user they are still not prompted for their credentials on subsequent sign in attempts via the `AppAuth.authAsync` flow.

### Reproducible Demo

Other people have referenced similar issues such as:

* [a different OIDC provider setting a cookie in the auth session that somehow needs to be removed in order to sign in with different accounts](https://github.com/expo/expo/issues/6756#issuecomment-584520743)
* The above issue is referenced in Evan Bacon's [PR here for changes to the AppAuth Module](https://github.com/expo/expo/pull/7450)

I have also seen that `expo-web-browser` uses a deprecated piece of code in the native implementation for iOS [SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession).
I wonder whether potentially swapping out the deprecated `SFAuthenticationSession` for this: [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) which can accept the [prefersEphemeralWebBrowserSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio) prop - possibly that might help in the situation I'm describing?

As an aside, I'm super impressed with Expo and it's been a very pleasant development experience - so hats off and thanks to you all. Any help or referrals for the issue I'm describing are greatly appreciated.

**Comment by desnor** [comment]
Here is an expo forums reference to [someone encountering the same issue](https://forums.expo.io/t/trouble-signing-out-with-appauth-session-persists/33266)

**Comment by desnor** [comment]
and another one [here](https://forums.expo.io/t/authsession-cookies-clean/12933)

**Comment by cruzach** [comment]
thanks @desnor , this is really clear and helpful, and sorry that I misunderstood what you were looking for in the last issue

It looks from this PR that you linked (7450) that this could be addressed there, as it's listed as one of the issues with the current implementation:
> Users cannot clear cookies when they revoke their token, this means it's much harder (if not impossible) to switch users: see related issue.

**Comment by desnor** [comment]
hey thanks @cruzach - if time permits I'd like to be able to help out with this fix if I can, maybe I'll follow it up with @EvanBacon to see how that might work.

**Comment by EvanBacon** [comment]
Really appreciate you collecting all of the data regarding this issue into one place. I’m currently redesigning the auth experience in Expo and a big issue currently is the inability to delete cookies. https://github.com/expo/expo/issues/6756 I’ll raise this with the team and see if we can get a temporary solution into the client.

**Comment by EvanBacon** [comment]
Often you can pass a query param to the provider to let it know that you wish to authenticate from scratch. On Google this looks like [`prompt=select_account`](https://openid.net/specs/openid-connect-core-1_0.html).
In the new `expo-auth-session` this can be done with `extraParams: { prompt: 'select_account' }`.

Seems like clearing auth cookies is a [known problem in iOS](https://stackoverflow.com/questions/56508421/clear-cookies-when-using-aswebauthenticationsession), and the problem persists in [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession?language=objc). 
I think the best thing we could do right now (granted it will take some time) is to add `aswebauthenticationsession` support to `expo-web-browser` on iOS so people can use the incognito auth option [canny](https://expo.canny.io/feature-requests/p/allow-opening-private-authentication-web-sessions-to-avoid-ios-consent-dialog-bo).

In the current version of RN that Expo uses, you can clear all cookies natively with:
```
import Networking from "react-native/Libraries/Network/RCTNetworking";
Networking.clearCookies((hasCookies) => hasCookies)
```
but `hasCookies` always returns `false` after authenticating (on iOS) so this isn't much help.

**Comment by EvanBacon** [comment]
I'm going to be closing this with #7974 since I feel that adequately solves the problem. 
- We can keep tracking aswebauthenticationsession support here: https://expo.canny.io/feature-requests/p/aswebauthenticationsession
- I'd love if you could Salesforce to the [AuthSession guides](https://docs.expo.io/versions/latest/sdk/auth-session/#guides-to-integrate-with-popular-providers). The PR should look similar to this [Twitch support](https://github.com/expo/expo/pull/7963).

**Comment by desnor** [comment]
> Often you can pass a query param to the provider to let it know that you wish to authenticate from scratch. On Google this looks like [`prompt=select_account`](https://openid.net/specs/openid-connect-core-1_0.html).
> In the new `expo-auth-session` this can be done with `extraParams: { prompt: 'select_account' }`.
Yeah I'd hoped that would do the trick previously, but I've experienced strange behaviour when I have tried to pass in a value for the `prompt`. Either passing `login` or `select_account` cause it ti indeed go to the sign in screen, but it still skips seeking the user's credentials, and instead signs them into the actual website that we communicate with in Salesforce, which is just as problematic because the user cannot get back into our mobile app as a result.

> In the current version of RN that Expo uses, you can clear all cookies natively with:
> 
> ```
> import Networking from "react-native/Libraries/Network/RCTNetworking";
> Networking.clearCookies((hasCookies) => hasCookies)
> ```
> 
> but `hasCookies` always returns `false` after authenticating (on iOS) so this isn't much help.

I'll give this one a go - I'd seen references around the place to this but they hadn't given the full path inside the `react-native` module so it was throwing an error due to it not finding the module.

**Comment by desnor** [comment]
> * I'd love if you could add Salesforce to the [AuthSession guides](https://docs.expo.io/versions/latest/sdk/auth-session/#guides-to-integrate-with-popular-providers). The PR should look similar to this [Twitch support](https://github.com/expo/expo/pull/7963).

Yes I'd like to do that, will try and find some time in the next while to add that

**Comment by desnor** [comment]
> > In the current version of RN that Expo uses, you can clear all cookies natively with:
> > ```
> > import Networking from "react-native/Libraries/Network/RCTNetworking";
> > Networking.clearCookies((hasCookies) => hasCookies)
> > ```

Hey @EvanBacon have you been able to make that `Networking.clearCookies` call work yourself?

This doesn't work for me, it can't resolve the path using either `import` or `require` syntax. I can see there are files of that name, with either the `.android.js` or `.ios.js` extension, but it's still not able to resolve it whichever filename I use

**Comment by Harsha1401** [comment]
@desnor @EvanBacon is this issue with ```AppAuth.revokeAsync``` resolved?
