### ISSUE TITLE
Install error on Mac OS High Sierra

### ISSUE THREAD

**Issue by kot-ezhva** [expo/expo#788]
Hi!
First, sorry for my English :-)
When I mounted image, I see empty window.
![image](https://user-images.githubusercontent.com/15121885/31460533-714d1902-aecf-11e7-8533-be41e07434af.png)
After reopening mounted image, I see XDE icon and Application folder.
![image](https://user-images.githubusercontent.com/15121885/31460611-b0ed7822-aecf-11e7-8a10-9b3c0fce7c70.png)
But after drag icon to folder, I see error message.

![image](https://user-images.githubusercontent.com/15121885/31460772-17561ace-aed0-11e7-8791-0f7c5ec55fb1.png)
"The operation could not be completed because one or more of the required objects could not be found. (Error code -43)"
What could be the problem?

 Mac OS high sierra (10.13 (17A405))

**Comment by br4in3x** [comment]
Hi, @kot-ezhva! =) I understand that this is not an answer to your question, but I found that it's absolutely unnecessary to use XDE, the CRNA project can be operated through command line via `npm start` or `exp start` (for more commands please check [exp documentation](https://docs.expo.io/versions/latest/guides/exp-cli.html)).

**Comment by ide** [comment]
Error -43 sounds like an issue with your computer. You can try the solutions here including restarting, repairing your filesystem with Disk Utility, or resetting NVRAM: https://apple.stackexchange.com/questions/139105/error-the-operation-can-t-be-completed-because-one-or-more-required-items-can

**Comment by kot-ezhva** [comment]
@ide, thanks, it helped.
