### ISSUE TITLE
Camera preview is black after component change

### ISSUE THREAD

**Issue by Fedour** [expo/expo#7880]
### Environment

  Expo CLI 3.17.23 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - F:\node.EXE
      npm: 6.13.4 - F:\npm.CMD
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-navigation: ^4.3.7 => 4.3.7

Target:

* Android

### Steps to Reproduce

* Start the app
* Switch to 'Settings' component
* Come back to 'Camera' component

### Expected Behavior

Camera preview should work after component switch

### Actual Behavior

Camera preview is black after component switch

![alt text](https://i.ibb.co/bzxRvN4/Screenshot-20200417-124117-Expo.jpg "Black screen")

### Reproducible Demo

The code is available here : https://gitlab.com/fedour57000/democamera

I also put the code directly here:

App.js
```javascript
// In App.js in a new project

import * as React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import SettingsScreen from './settingsScreen.js';
import CameraScreen from './cameraScreen.js'
import { Ionicons } from '@expo/vector-icons';


const Tab = createBottomTabNavigator();


export default class App extends React.Component {
    render() {
        return (
            <NavigationContainer>
                <Tab.Navigator screenOptions={({ route }) => ({
                    tabBarIcon: ({ color, size }) => {
                        let iconName;
                        
                        if (route.name === 'ScannerScreenTest') {
                        iconName = 'md-qr-scanner';
                        } else if (route.name === 'Settings') {
                        iconName = 'md-settings';
                        }

                        // You can return any component that you like here!
                        return <Ionicons name={iconName} size={size} color={color} />;
                        },
                        })}
                        tabBarOptions={{
                        activeTintColor: 'tomato',
                        inactiveTintColor: 'gray',
                        }}
                >
                    <Tab.Screen name="Camera" component={CameraScreen} />
                    <Tab.Screen name="Settings" component={SettingsScreen} />         
                </Tab.Navigator>
            </NavigationContainer>
        );
      }
}
```

SettingScreen.js
```javascript
import React, {PropTypes} from 'react';
import { Text } from "react-native";

export default class SettingsScreen extends React.Component {
	render() {
    	return (<Text>SettingsScreen</Text>);
    }
}

```

CameraScreen.js
```javascript
import React from 'react';
import { Text, View } from 'react-native';
import { Camera } from 'expo-camera';

import { withNavigationFocus } from 'react-navigation';
import * as Permissions from 'expo-permissions'


class CameraScreen extends React.Component {
    camera = null;

    state = {
        hasCameraPermission: null,
    };

    async componentDidMount() {
        const camera = await Permissions.askAsync(Permissions.CAMERA);
        const hasCameraPermission = (camera.status === 'granted');

        this.setState({ hasCameraPermission });
    };

    render() {
        const { hasCameraPermission } = this.state;

        if (hasCameraPermission === null) {
            return <View />;
        } else if (hasCameraPermission === false) {
            return <Text>Access to camera has been denied.</Text>;
        }

        else if (this.props.isFocused)
        {
        	return (
              <View style={{ flex: 1 }}>
                <Camera style={{ flex: 1 }} type={this.state.cameraType}>
                  
                </Camera>
                <Text> IS FOCUS </Text>
              </View>
            )
        }
    };
};
export default withNavigationFocus(CameraScreen);

```
### Notes

* Apparently this is the same problem as here: https://github.com/expo/expo/issues/5952

*  The text 'IS FOCUS' is displayed so 'this.props.isFocused' is true. The problem therefore comes directly from the camera.

**Comment by byCedric** [comment]
Hi @Fedour! Thanks for the example! 😄 I can confirm this issue is the same as #5952. There are multiple camera instances being mounted, even though you checked if the screen is focused or not.

What's going wrong here is that `withNavigationFocus` is part of React Navigation v4. The other React Navigation parts, like the `NavigationContainer` in `App.js` is from v5. Because they are not compatible, `withNavigationFocus` never receives the navigational changes to determine if the screen is focused or not. You can check this out by using `console.log({ isFocused: this.props.isFocused });` in your render method. When you switch to the settings screen this value should be `false`, instead it remains `true` and causing the issue from #5952.

To fix this, you can try this code. It's your code, but with the fix to get this working in React Navigation v5 😄 To read more about listening to navigation state changes in v5, [check this out](https://reactnavigation.org/docs/navigation-events#navigationaddlistener).

<details>
<summary>The updated `CameraScreen.js`</summary>
<pre>
import React from 'react';
import { Text, View } from 'react-native';
import { Camera } from 'expo-camera';
import * as Permissions from 'expo-permissions'

class CameraScreen extends React.Component {
    camera = null;

    _focusListener = null;
    _blurListener = null;

    state = {
        hasCameraPermission: null,
        isFocused: true,
    };

    async componentDidMount() {
        const camera = await Permissions.getAsync(Permissions.CAMERA);
        const hasCameraPermission = (camera.status === 'granted');

        this._focusListener = this.props.navigation.addListener('focus', () => {
            this.setState({ isFocused: true });
        });

        this._blurListener = this.props.navigation.addListener('blur', () => {
            this.setState({ isFocused: false });
        });

        this.setState({ hasCameraPermission });
    };

    componentWillUnmount() {
        if (this._focusListener) {
            this._focusListener();
            this._focusListener = null;
        }

        if (this._blurListener) {
            this._blurListener();
            this._blurListener = null;
        }
    }

    render() {
        const { hasCameraPermission, isFocused } = this.state;

        if (hasCameraPermission === null) {
            return <View />;
        } else if (hasCameraPermission === false) {
            return <Text>Access to camera has been denied.</Text>;
        }

        else if (isFocused)
        {
        	return (
              <View style={{ flex: 1 }}>
                <Camera style={{ flex: 1 }} type={this.state.cameraType}>

                </Camera>
                <Text> IS FOCUS </Text>
              </View>
            )
        }

        return null;
    };
};
export default CameraScreen;

</pre>
</details>

Hope it helps!

**Comment by Fedour** [comment]
It works perfectly. Thanks a lot ! 😄

**Comment by Jaquedeveloper** [comment]
What if one is using functional components instead?? It does not have componentDidMount() nor componentWillUnmount() methods...

**Comment by ShardulJitkar** [comment]
Can you please let us know the fix for functional components?

**Comment by Yashsoni23** [comment]
For functional component, you need to unmount the camera so if you are using  expo  camera then use following solution
