### ISSUE TITLE
Permissions.getAsync(Permissions.NOTIFICATIONS) promise does not resolve on Expo Client on iOS

### ISSUE THREAD

**Issue by benjamintli** [expo/expo#7886]
### Environment

- Ubuntu 18.04
- Node: v12.16.1
- NPM: 6.14.1
- Expo CLI: 3.11.3
- Expo SDK: 34

  Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.1 - /usr/local/bin/npm
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.11.3

Expo Client, specifically on iOS

### Steps to Reproduce
I'm looking to register the app for push notifications using the following example code taken from the Expo documentation. This works perfectly on android (both standalone and client), but on iOS Expo Client the getAsync() hangs and does not resolve to anything. 

```    
registerForPushNotificationsAsync = async () => {
        if (Constants.isDevice) {
          const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
          let finalStatus = existingStatus;
          if (existingStatus !== 'granted') {
            const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
            finalStatus = status;
          }
          if (finalStatus !== 'granted') {
            alert('Failed to get push token for push notification!');
            return;
          }
          Notifications.getExpoPushTokenAsync().then(
              token => {
                this.setState({ expoPushToken: token });
            }
          ); 
        } else {
          alert('Must use physical device for Push Notifications');
        }
    
        if (Platform.OS === 'android') {
          Notifications.createChannelAndroidAsync('default', {
            name: 'default',
            sound: true,
            priority: 'max',
            vibrate: [0, 250, 250, 250],
          });
        }
      };
```

### Expected Behavior
Push notification token gets generated, notification permission is asked and resolves to granted. 

### Actual Behavior
Asking for notification permissions hang, no dialog appears, push notification token no generated. Promise doesn't resolve

**Comment by cruzach** [comment]
It looks like your dependencies are a little mixed up, you're using SDK 36 but relying on the react native version from SDK 34:
```
expo: ^36.0.2 => 36.0.2
react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
```
Can you try running[ this snack ](https://snack.expo.io/@charliecruzan/c10b13?platform=android&name=Push%20Notifications&sdkVersion=37.0.0&dependencies=expo-constants%2Cexpo-permissions&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv37.0.0%2Fpushnotifications.js) on your device instead? And make sure you aren't disabling push notifications from the Expo app in your iOS Settings

**Comment by benjamintli** [comment]
The snack works! I upgrade expo to match so i'm using SDK 36 across the board and that seemed to fix it! thanks so much for helping
