### ISSUE TITLE
Admob get TestDeviceID for Interstitial

### ISSUE THREAD

**Issue by thomasarbona** [expo/expo#789]
I'm trying to display Interstitial ads in my app. I run my app in the Expo Client on my iPhone.
The problem is that ads never shows up.

```js
AdMobInterstitial.setAdUnitID(AdmobID.afterLevelPlay[Device.isIos ? 'ios' : 'android']);
AdMobInterstitial.setTestDeviceID('EMULATOR');
AdMobInterstitial.requestAd(() =>  AdMobInterstitial.showAd());
```

I'm not sure for the TestDeviceID because i'm not on an emulator, but I don't know how to get the deviceID... Admob doesn't produce any log.

Thank's by advance.

**Comment by ide** [comment]
Google says you can get the test device ID by looking at the adb logs (and maybe iOS native logs?): https://developers.google.com/admob/android/test-ads#add_your_test_device

**Comment by grosa82** [comment]
For iOS I was able to get the device’s identifier using this app (The Identifiers by Shundor Apps). It is available on the App Store. I hope it helps.

**Comment by nicknovitski** [comment]
AdMob also provides documentation on [how to get the test device ID of iOS devices](https://developers.google.com/admob/ios/test-ads#add_your_test_device).
