### ISSUE TITLE
[docs] Be clear about which expo-constants APIs are available in managed vs bare

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#7890]
It can cause confusion like this: https://github.com/expo/expo/issues/7721

**Comment by tylerc** [comment]
And like this: https://github.com/expo/expo/issues/10095

Honestly based on this: https://github.com/expo/expo/issues/7721#issuecomment-619624914 and this: https://github.com/expo/expo/issues/10095#issuecomment-692763611 it seems like there is a broader issue at play here than just docs.

It looks like the next SDK will need some internal fixes.
