### ISSUE TITLE
This Query not run in Sqlite

### ISSUE THREAD

**Issue by josematheus10** [expo/expo#7898]
This Query not run in Sqlite
https://www.db-fiddle.com/f/2bGqr1S8ho7z78BPxcQQ7y/3

**Comment by byCedric** [comment]
Hi @josematheus10! I'm sorry but without a [small repro](https://stackoverflow.com/help/minimal-reproducible-example) there is not much we can do. You could try asking this on the [SQLite forum](https://sqlite.org/forum/forummain) since this is more of an SQLite issue.

Hope it helps!
