### ISSUE TITLE
App crashes after startup in release builds

### ISSUE THREAD

**Issue by nmelentjevs** [expo/expo#7899]
### 🐛 Bug Report
I've already run expo publish. I think my manifest file may be invalid. How can I debug this and figure out what's causing the issue? It works just fine in "debug" configuration.I have been unable to fix that by updating expo-cli. I don't have expokit in my package.json either. The build works in debug mode on both simulator and device.

### Environment:
Expo-cli@3.18.2
System:
OS: macOS 10.15.3
CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
Memory: 2.99 GB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.3 - /usr/local/bin/node
Yarn: 1.16.0 - /usr/local/bin/yarn
npm: 6.14.4 - /usr/local/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
IDEs:
Android Studio: 3.6 AI-192.7142.36.36.6308749
Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
npmPackages:
react: ~16.9.0 => 16.9.0
react-native: ~0.61.5 => 0.61.5
npmGlobalPackages:
create-react-native-app: 2.0.2
react-native-cli: 2.0.1

### Steps to Reproduce
Creating release build in xcode.

### Expected Behavior
App doesn't crash on startup.

### Actual Behavior
App crashes on startup with this error in xcode.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The embedded manifest is invalid. If you are making a release build for the first time, make sure you have run expo publish at least once.'

**Comment by brentvatne** [comment]
hello! could you possibly share your project with me? it would help a lot to debug it.

also, can you search your ios directory for `app.bundle` and `app.manifest` and see if you have multiple occurrences of them? if so, what directories are they in? thanks

**Comment by nmelentjevs** [comment]
You can find my files at https://github.com/nmelentjevs/tileshade. However, the project worked perfectly and all the manifests were generating correctly on expo 36.0.0, so I think it may be the problem with the latest SDK version.

I do have only 1 app.bundle and 1 app.manifest file in the ios/Supporting directory. The app.bundle is empty and the app.manifest is an empty object.

**Comment by pjay79** [comment]
Having exact same issue on release builds on latest Expo SDK Bare Workflow. Although the app successfully builds in local environment and AppCenter, it will crash immediately after splash screen pops up. In my case I'm using Code Push and have not done any expo publish.

```
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 5.37 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 16, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
```

**Comment by pjay79** [comment]
My issues fixed by manually removing expo-updates

**Comment by ckOfor** [comment]
How can I do that @pjay79 ?

**Comment by pjay79** [comment]
Just undo the expo-updates changes in the iOS and Android files, do everything in reverse:

https://github.com/expo/expo/tree/master/packages/expo-updates

Change the Build Phases script 'Bundle Expo Assets' to 'Bundle React Native code and images' and replace the script contents with the default:

```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```
I kept the files under iOS/Supporting directory, ie app.manifest, app.bundle, Expo.plist. The first 2 files had {} as the contents. Removing these files caused the build to break. I also kept the app.json as it was (the default on a Bare Workflow).

Sorry to hijack the original post. Not sure why running expo-publish should is not fixing the problem in the case that you are keeping expo-updates.

**Comment by brettdh** [comment]
@brentvatne Hmm. I'm in the process of migrating from ExpoKit -> managed -> bare with SDK 37, and I'm coming across this issue as well.

I did the `expo publish` step, but I noticed that I do indeed have two copies of the files:

```
ios/the-liturgists
├── Supporting
│   ├── Expo.plist
│   ├── app.bundle
│   └── app.manifest

ios/TheLiturgists
└── Supporting
    ├── app.bundle
    └── app.manifest
```
The first was created on eject, I think; the second was created just now, on `expo publish`.

I pushed a branch with my WIP changes here: https://github.com/theliturgists/app/tree/expo-sdk-37-bare  Note that I've `.gitignore`d the files in `ios/TheLiturgists`. Note also (in commit history) that I manually renamed the xcode project since ejecting (along with various manual fixups), which may have been a mistake - but I felt weird about just calling it `app` everywhere. So, that first one used to be `ios/app/Supporting/app.*` and now it's `ios/the-liturgists/Supporting/app.*`.

**Comment by brentvatne** [comment]
hey @brettdh! what expo-cli version do you have installed?

**Comment by brettdh** [comment]
3.18.4

**Comment by brentvatne** [comment]
i tried to reproduce it by doing the following:

- create a new blank app with `expo init` and then change the name in app.json to "The Liturgists"
- run `expo eject`
- run `expo publish` after eject is complete: the only copy is in `./ios/TheLiturgists/Supporting/app.bundle`

this works as expected. so i think the issue is in the renaming of the project. we default to looking at the name to determine where the app.bundle and app.manifest artifacts should go - in most cases this is fine but in some cases if you customize things and the new location doesn't match up with the name then you will need to use the `ios.publishBundlePath` and `ios.publishManifestPath` fields that you previously used in app.json in expolkit - https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#set-up-appjson

**Comment by brettdh** [comment]
> you will need to use the ios.publishBundlePath and ios.publishManifestPath fields that you previously used in app.json

It appears that this (pointing them to the new files that are in the xcode project) did the trick. Thanks!

(...it's now stuck on the launch screen, but it's no longer crashing immediately, anyway. I'll continue looking into that tomorrow)

**Comment by brettdh** [comment]
@brentvatne is there a similar app.json config item for specifying the location of Expo.plist? I'm wondering if that's not getting filled in because it's in the wrong place as well.

**Comment by brettdh** [comment]
Confirmed that Expo.plist gets filled in if I put it in `ios/TheLiturgists/Supporting/` and does _not_ get filled in if I put it in `ios/the-liturgists/Supporting/`.

Probably simplest to move the files to where expo expects them to be.

**Comment by brettdh** [comment]
Is it fair to say that it would be nicer to get a loud warning/error from something in the standalone app build process indicating that I've built an app without a valid Expo.plist file in it? (Would that fact explain the behavior I'm seeing, where my built app hangs at the splash screen on startup?)

Additionally: Expo.plist seems like a file that should be `.gitignore`d and generated on _every_ publish (because its contents can change with a different `--release-channel`, but instead it's not generated if it doesn't exist, so it has to exist in version control. (I can script around this by copying a template version into place if the actual file doesn't exist, allowing it to be filled in but not committed - but it would be better if expo-cli handled this for me.)

Please let me know if I'm misunderstanding something; my thinking-out-loud here is one part feature request and one part validating my own thought process. 😅

**Comment by brettdh** [comment]
Ha, found these two pieces of code:
- [Finding the `Supporting` directory](https://github.com/expo/expo-cli/blob/990f3b472de68bd669682e45d5d351a128ea14d3/packages/xdl/src/EmbeddedAssets.ts#L331-L359)
- [Updating `.../Supporting/Expo.plist`](https://github.com/expo/expo-cli/blob/990f3b472de68bd669682e45d5d351a128ea14d3/packages/xdl/src/EmbeddedAssets.ts#L262-L275)

I see now you were pointing at `expo.name` in `app.json` above, and that that's what Expo uses to determine where things are located, including `Expo.plist`.

...except when I change it to `the-liturgists` and run `expo publish` again with `ios/the-liturgists/Supporting/Expo.plist` in place, it still doesn't get updated. 🤔

..._because_:

```
> ('the-liturgists'
...     .replace(/[\W_]+/g, '')
...     .normalize('NFD')
...     .replace(/[\u0300-\u036f]/g, '')
... )
'theliturgists'
```

...hmm. I really screwed this up with the rename, huh. I'm probably just going to revert that. 🤦 Or else double down and rename the whole project again.

I really am happy that the bare workflow is replacing ExpoKit, but I also really hope that these fragile quirks and subtle gotchas can be improved soon 😬❤️

**Comment by matheuslipk** [comment]
> My issues fixed by manually removing expo-updates

Thank You! It worked here too.

**Comment by brentvatne** [comment]
@matheuslipk - https://github.com/expo/fyi/blob/master/release-builds-with-expo-updates.md

**Comment by brentvatne** [comment]
hey @brettdh - sorry for the delay. we're actually reworking how expo-updates is integrated into bare projects so none of the issues you've encountered will happen anymore - it won't be necessary to publish before running a release build. good point re: Expo.plist, we may add a field for that.

**Comment by omurilo** [comment]
@brentvatne in my case, the files manifest and bundle dont be created after run `expo publish`, i'm running standalone app because expokit to be discontinued.

I have to wait resolution of the problems or exist a thing to resolve this now?

**Comment by brentvatne** [comment]
@omurilo - have you seen https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf? i'd suggest reading that and updating your app accordingly

**Comment by omurilo** [comment]
@brentvatne Ok, these files no more it be created on build my app. But if I run `expo publish` these too don't created? In my case, they are never created and my `release app` fails on start in Android and iOS.

**Comment by cipriancaba** [comment]
@brentvatne I'm actually having a rather similar issue.. Running `expo-updates@0.2.3` and followed the instructions here https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf

The crash log reads:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not find the expected embedded asset package.json. Check that expo-updates is installed correctly.'
```

I did actually have package.json required in one file but I've removed that and still have the error.. 

```
  Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
```

**Comment by RupamShaw** [comment]
In managed workflow (already have react-native project using expo by reactnativeunimodules). expo publish fills app.manifest and app.bundle and
````
 Expo.plist also passed which contains EXUpdatesEnabled,EXUpdatesLaunchWaitMs,EXUpdatesReleaseChannel, EXUpdatesSDKVersion(string 37.0.0) keys 
```
Expo.plist generates key and string of EXUpdatesURL and <string>https://exp.host/@user/**appname**</string> 
which is valid

but in xcode  run--release mode
error
```
Exception	NSException *	"expo-updates is enabled, but no valid URL is configured under EXUpdatesURL. If you are making a release build for the first time, make sure you have run `expo publish` at least once."	0x00000002829a5260
```

please guide how my xcode-relase mode get EXUpdatesURL 
stuck on launch screen 
```
 xcode  run--debug mode
all good and it works fine.
```
xcode

**Comment by LauraBeatris** [comment]
Same error here...

Even by running ``yarn publish`` the error continues to appear. 

I have followed all the steps in order to configure ``expo-updates`` in a bare workflow project

**Comment by brentvatne** [comment]
@RupamShaw @LauraBeatris - can either of you share your projects or a [mcve](https://stackoverflow.com/help/mcve)? or at the very least, the Expo.plist file would be helpful.

**Comment by LauraBeatris** [comment]
@brentvatne Sure! 

Just to clarify, when I run ``yarn-publish``, it generates the ``app.manifest``, ``app.bundle`` and also updates the ``EXUpdatesURL`` in the ``Expo.plist``. 

AppDelegate.m: https://codeshare.io/5DdjKl
AppDelegate.h: https://codeshare.io/aV7V1R
Expo.plist: https://codeshare.io/5PjVyE

The steps in order to fix it: 
- Added the folder ``Support`` in the XCode project 
- Added ``Expo.plist`` in the ``Copy Bundle Resources``, in order to ``expo-updates`` search for the URL. 

I am also pretty sure that I have followed all the steps in the documentation to set up the ``expo-updates`` in a bare workflow project.

**Comment by omurilo** [comment]
> @brentvatne Sure! 
> 
> Just to clarify, when I run ``yarn-publish``, it generates the ``app.manifest``, ``app.bundle`` and also updates the ``EXUpdatesURL`` in the ``Expo.plist``. 
> 
> AppDelegate.m: https://codeshare.io/5DdjKl
> AppDelegate.h: https://codeshare.io/aV7V1R
> Expo.plist: https://codeshare.io/5PjVyE
> 
> The steps in order to fix it: 
> - Added the folder ``Support`` in the XCode project 
> - Added ``Expo.plist`` in the ``Copy Bundle Resources``, in order to ``expo-updates`` search for the URL. 
> 
> I am also pretty sure that I have followed all the steps in the documentation to set up the ``expo-updates`` in a bare workflow project.  
> 

@LauraBeatris hey there, you created ``Support`` or ``Supporting`` folder?

My issues solved when i'm back to go sdk 38 and eject to bare again.

But I breaked the project again, so I solved the problem with a shell script to copy Expo.plist from another folder to the ``Supporting`` folder at compile time.

**Comment by sumanbhattarai** [comment]
My app works fine in debug mode in iOS. But whenever I try to run the app in release mode, I am getting the following error:
`NSException * "Could not find the expected embedded asset main.jsbundle. Check that expo-updates is installed correctly."`

**Comment by bulent-eroglu** [comment]
I've received `Thread 8: "Could not find the expected embedded asset main.jsbundle. Check that expo-updates is installed correctly."` as well. It was perfectly fine yesterday, I tried to do a release to TestFlight and started to crash on launch

**Comment by WNemencha** [comment]
Same here, app runs perfectly fine on Android debug/release and aswell on iOS debug. It builds fine for iOS release but then when the app gets launched it simply force-close with the following message being printed out in the xcode console:

```
2022-04-07 16:54:25.725479+0200 MyApp[1718:80798] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not find the expected embedded asset main.jsbundle. Check that expo-updates is installed correctly.'
*** First throw call stack:
(0x...)
libc++abi: terminating with uncaught exception of type NSException
```

**Comment by dittmarconsulting** [comment]
Can you please re-open this issue? I'm facing the same problem.

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not find the expected embedded asset Hornbill-Medium.otf. Check that expo-updates is installed correctly.'
```

I have followed all steps. My app works fine in `debug` but as soon as I want to run in `release` mode I get the above error.

I can clearly see the `app.bundle` and the `app.manifest` in the `Supporting` folder and I have a release JS bundle `main.jsbundle` in the project.

I have no idea what else I can do!

**Comment by brentvatne** [comment]
@dittmarconsulting - can you open a new issue and fill out the issue template please? thank you!

**Comment by dittmarconsulting** [comment]
Hi @brentvatne, I removed Expo completely and went with CodePush. A much cleaner solution IMO.

**Comment by cozmoc** [comment]
if you are encountering this issue in 2023+ and you happen to have expo-updates parked and installed but not actually used. the solution was to remove it completely or set `updates.enabled` to `false` in `app.json`

**Comment by timothymiller** [comment]
@cozmoc Disabling it worked for me. Would be nice to enable it in the future.
