### ISSUE TITLE
It would be great if you could include support for the AWS library

### ISSUE THREAD

**Issue by andymac4182** [expo/expo#79]
https://github.com/awslabs/aws-sdk-react-native

**Comment by dikaiosune** [comment]
Looks cool! I am a little concerned that it claims to be a developer preview but that it hasn't seen commits in 7-8 months, but we'll keep an eye on it!

**Comment by terribleben** [comment]
Hello! Can you create a feature request on [canny](https://expo.canny.io/feature-requests) if this is still important to you? Thanks!
