### ISSUE TITLE
Unable to set output extension/encoding to anything other than `.caf` in iOS

### ISSUE THREAD

**Issue by mlg87** [expo/expo#790]
after creating a new recording (`new Audio.Recording()`), i am unable to successfully create a new recorder with the following options:
 ```const AUDIO_RECORDING_OPTIONS = {
  android: {
    extension: '.m4a',
    outputFormat: Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_MPEG_4,
    audioEncoder: Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AAC,
    sampleRate: 44100,
    numberOfChannels: 2,
    bitRate: 128000,
  },
  ios: {
    extension: '.aac',
    outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC,
    audioQuality: Audio.RECORDING_OPTION_IOS_AUDIO_QUALITY_MAX,
    sampleRate: 44100,
    numberOfChannels: 2,
    bitRate: 128000,
    linearPCMBitDepth: 16,
    linearPCMIsBigEndian: false,
    linearPCMIsFloat: false,
  },
};
```
it keeps throwing `error: recorder not created`. it does successfully create a recorder when i use the `Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY` (or low quality), but need the file in `.aac`

**Comment by colinux** [comment]
I have the same problem, I can't record audio in aac/m4a format. I tested a lot of combinations of extensions / outputs formats / audio quality, including with `RECORDING_OPTION_IOS_AUDIO_QUALITY_HIGH`/`.aac` as you described. All of them fails as soon as extension and/or `outputFormat` is different from the default settings.

**Comment by colinux** [comment]
With the Expo upgrade 22.0 > 23.0 it's nicely working with these settings, thanks !
```js
ios: {
    extension: '.m4a',
    outputFormat: Audio.RECORDING_OPTION_IOS_OUTPUT_FORMAT_MPEG4AAC,
    audioQuality: Audio.RECORDING_OPTION_IOS_AUDIO_QUALITY_MEDIUM,
    sampleRate: 44100,
    numberOfChannels: 1,
    bitRate: 96400,
    linearPCMBitDepth: 16,
    linearPCMIsBigEndian: false,
    linearPCMIsFloat: false,
  }
```

**Comment by sjchmiela** [comment]
It has been fixed in https://github.com/expo/expo/commit/31bc69bb241cea213839ac685afc55f3746a7eb9, `outputFormat` field has been interpreted incorrectly.
