### ISSUE TITLE
 Unresolved reference: PermissionAwareActivity

### ISSUE THREAD

**Issue by gwumkt** [expo/expo#7901]
After updating the android studio, now that is what happened..
![image](https://user-images.githubusercontent.com/28900951/79640071-445a4480-8198-11ea-9aa5-5611d8ed6d2c.png)

```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 22.83 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

**Comment by byCedric** [comment]
Hi @gwumkt! Unfortunately, without a [small repro](https://stackoverflow.com/help/minimal-reproducible-example), I'm not sure what could cause this. It looks like the `PermissionAwareActivity` dependency is missing, so the only thing I could suggest is to try cleaning the project, remove installed dependencies and let Android Studio install your project again.

Hope it helps! 😄

**Comment by gwumkt** [comment]
Yes, i just re do all the project and now all good :)
Except other issues of course

**Comment by byCedric** [comment]
Awesome! Good luck fixing the other issues 😄

**Comment by Charlie-Hua** [comment]
> Yes, i just re do all the project and now all good :) Except other issues of course

hi @gwumkt , how did you `redo all the project` exactly? thanks!

**Comment by lukmccall** [comment]
Hi @Charlie-Hua, I'm not sure how gwumkt delt with it. However, you can try to clean the build folder using Android Studio. Then, close the editor and remove `.idea` folder.

**Comment by dummas2008** [comment]
when react-native redirects to https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml, the issue has happened.

**Comment by renanmav** [comment]
Not sure if I understood what @dummas2008 meant by "redirects"

**Comment by JeroenVanSteijn** [comment]
![image](https://user-images.githubusercontent.com/32145092/106297783-60c0fc80-6253-11eb-82a0-3e45721f41c5.png)
Changing the react native version from a .tar.gz link to the actual NPM package fixed it for me

**Comment by listiani13** [comment]
This might help for those who uses monorepo: https://github.com/expo/expo/issues/10283#issuecomment-785698669

**Comment by rodrigorm** [comment]
> ![image](https://user-images.githubusercontent.com/32145092/106297783-60c0fc80-6253-11eb-82a0-3e45721f41c5.png)
> Changing the react native version from a .tar.gz link to the actual NPM package fixed it for me

This is the only solution wich worked for me, thanks.
