### ISSUE TITLE
[docs] expo-web-browser / AuthSession docs not in sync with latest published version 

### ISSUE THREAD

**Issue by lrholmes** [expo/expo#7902]
Hey, super excited to use the universal AuthSession implementation as described on this page: https://docs.expo.io/versions/latest/sdk/auth-session/

However, following this documentation using the latest version of `expo-web-browser`, I'm getting an error that `maybeCompleteAuthSession` is not defined. Indeed, looking at the file as it exists on npm, it seems that the source code is out of sync with GitHub. NPM: https://unpkg.com/browse/expo-web-browser@8.1.1/src/ExpoWebBrowser.web.ts, GitHub: https://github.com/expo/expo/blob/master/packages/expo-web-browser/src/ExpoWebBrowser.web.ts

Seems like a republish may be necessary, but happy to hear if there's anything on my end I can do to help this. 

Thanks!

**Comment by byCedric** [comment]
Hi @lrholmes, thanks for bringing this up! I think we just released `expo-web-browser@8.2.0` with this functionality 😄 Could you try manually updating to this version? (without `expo install`)

cc @EvanBacon we currently have the version constraint `~8.1.0` in [bundled native modules](https://github.com/expo/expo/blob/master/packages/expo/bundledNativeModules.json#L57), and the newly released version (`~8.2.0`) doesn't match that. Should we update this, or is it a new feature and not compatible with SDK 37?

**Comment by lrholmes** [comment]
Woohoo, it works now 🎉 

I have a followup issue, sort of related to this, but different enough that I figured a new issue is more appropriate: #7929 

I'll let you close this one in case you want to update the version constraint as part of it - think that will certainly help others from running into this issue!

**Comment by byCedric** [comment]
Awesome! I was just looking at the new issue, thanks for bringing it up. Sorry about that, we will fix it! 😄 I'll close this one and discuss the bundled native modules changes internally.
