### ISSUE TITLE
[web] expo-auth-session getRedirectUrl throws error

### ISSUE THREAD

**Issue by nandorojo** [expo/expo#7905]
## 🐛 Bug Report

Calling `AuthSession.getRedirectUrl()` on web (with Next.js) throws an error.

### Environment
```
  Expo CLI 3.18.4 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.18.4
```

Using Expo web with Next.js (😍)

### Steps to Reproduce

1. **Create a [nextjs project with expo](https://docs.expo.io/versions/latest/guides/using-nextjs/)**

- Init: `expo init`
- Install: `yarn add -D @expo/next-adapter`
- Configure: `yarn next-expo`

2. `yarn add expo-auth-session`
3. In `pages/index.js`:

```jsx
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import * as AuthSession from 'expo-auth-session'

export default function App() {
  const onPress = () => { 
      console.log('will get url')
      const redirectUrl = AuthSession.getRedirectUrl() // 🚨error here
      console.log({ redirectUrl })
   }

  return (
    <View style={styles.container}>
      <Text onPress={onPress} style={styles.text}>Start Auth Session</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text: {
    fontSize: 16,
    padding: 40
  },
});
```

4. `yarn next dev`, and open `localhost:3000`

5. Click the text.

### Expected Behavior

`getRedirectUrl` should return a string.

### Actual Behavior

The function throws an error. 
<img width="1009" alt="Screen Shot 2020-04-18 at 2 56 07 PM" src="https://user-images.githubusercontent.com/13172299/79668722-d0627100-8184-11ea-872f-6f338dfc654d.png">

### Reproducible Demo

https://github.com/nandorojo/expo-web-auth-session-issue

```sh
git clone https://github.com/nandorojo/expo-web-auth-session-issue
cd expo-web-auth-session-issue
yarn
yarn next dev
# open locahost:3000
```

**Comment by lukmccall** [comment]
Hi @nandorojo, it was fixed by this PR: https://github.com/expo/expo/pull/7656.
However, these changes seem to be not published.

**Comment by lukmccall** [comment]
So, for now, I'm closing this issue. However, feel free to reopen if this bugs will still occur.

**Comment by nandorojo** [comment]
@lukmccall Thanks for letting me know! Has this PR been published to npm? I’m currently using a clone of it locally.
