### ISSUE TITLE
expo-payments-stripe has empty build/index.d.ts file, typescript not working

### ISSUE THREAD

**Issue by bkniffler** [expo/expo#7907]
Hi, trying `expo-payments-stripe` with latest 8.0.1 version, and the index.d.ts file is empty, thus I can't import it into my code with types.

<img width="863" alt="Bildschirmfoto 2020-04-19 um 13 28 31" src="https://user-images.githubusercontent.com/4349324/79686569-aae76d00-8241-11ea-8340-2aacdcf63e65.png">

**Comment by bkniffler** [comment]
Importing like this works: 
```ts
import Stripe from 'expo-payments-stripe/build/Stripe';
```

**Comment by byCedric** [comment]
Hi @bkniffler! Thanks for reporting this, it looks like something went wrong when building the types. I created a PR to get this resolved asap! Meanwhile, the workaround you provided should be sufficient. It's doing exactly that in the faulty `index` file too 😄
