### ISSUE TITLE
FaceDetector from 'expo-face-detector', is it free library ?

### ISSUE THREAD

**Issue by vasanthhr** [expo/expo#7913]
Hello,

I want to use this FaceDetector  that is available in expo-face-detector (now it is expo), Is it free library or it uses Mlkit as back-end paid version?.

I have gone through this below link, but I didnt see anywhere about the usage or license limitation.

[https://docs.expo.io/versions/latest/sdk/facedetector/](https://docs.expo.io/versions/latest/sdk/facedetector/)

```
(import * as FaceDetector from 'expo-face-detector'; )
```

**Comment by byCedric** [comment]
Hi @vasanthhr! The `expo-face-detector` is licensed under MIT, just like most of Expo 😄  Under the hood, it's powered by [ML Kit](https://developers.google.com/ml-kit) (previously [Google's Mobile Vision](https://developers.google.com/vision/introduction)). I think you can find the licenses for this [here](https://mvnrepository.com/artifact/com.google.firebase/firebase-ml-vision-face-model/19.0.0).

Hope it helps!
