### ISSUE TITLE
release-channel lost after redirection from exp.host to expo.io

### ISSUE THREAD

**Issue by massick** [expo/expo#7914]
After publishing with the command `expo publish --release-channel=xyz` before we use to have an url under the domain `exp.host`, now `expo.io`.
There is already a redirection in place but the query string parameters are lost (and the `release-channel` is pretty useful).

**Current behavior:**
this: https://exp.host/@xxx/yyy?release-channel=zzz
to: https://expo.io/@xxx/yyy

**Expected behavior**
from: https://exp.host/@xxx/yyy?release-channel=zzz
to: https://expo.io/@xxx/yyy?release-channel=zzz

**Comment by enguerranws** [comment]
Just experienced this too :/ All params are getting cleared from the original URL.

**Comment by ide** [comment]
Sorry about this. We've made the redirect include query parameters:

```
$ curl -D - -H 'accept: application/expo+json' 'https://expo.io/@user/project?release-channel=test'
HTTP/2 301 
server: nginx/1.17.8
date: Mon, 20 Apr 2020 20:03:32 GMT
content-type: text/plain; charset=utf-8
content-length: 67
location: https://exp.host/@user/project?release-channel=test
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=31536000; includeSubDomains

Redirecting to https://exp.host/@user/project?release-channel=test.       
```

**Comment by massick** [comment]
Hi @ide, the issue I described seems to be the other way around (so from `https://exp.host/@user/project?release-channel=test` I'm been redirected to `https://expo.io/@user/project`), and I don't see it fixed.
Try to copy paste an url like that (the first one) of an existing project in the browser without setting header with curl.

**Comment by ide** [comment]
Gotcha. We'll deploy a change tomorrow with the query parameters in the redirect. In general, though, exp.host URLs are for the API server and not meant to be entered into a web browser and browsing to expo.io URLs is more likely to keep working in the long run.

**Comment by massick** [comment]
@ide yep, it's not a big deal, I'm changing the url in my CI already. Thank you!
