### ISSUE TITLE
How I can select multiple files in DocumentPicker ?

### ISSUE THREAD

**Issue by VictorPullzz** [expo/expo#7918]
### Please note that discussions opened as issues in the core Expo repository will be closed.

  If you have a question about Expo or want to discuss about related aspects, consider posting it
  on our forums at https://forums.expo.io/. 🙂 
In documentation (https://docs.expo.io/versions/latest/sdk/document-picker/) write: 'multiple (boolean) -- (Web Only) Allows multiple files to be selected from the system UI. Defaults to false.' . 
How do i upload multiple files? I need this to submit the form???

**Comment by byCedric** [comment]
Hi @VictorPullzz! Unfortunately, we only support picking single documents on native. For web, we do support multiple! There is a [feature request](https://expo.canny.io/feature-requests/p/capability-of-document-picker-to-select-multiple-files-with-different-extensions) about this, if you need this feature you can upvote and promote that request.

**Comment by VictorPullzz** [comment]
> Hi @VictorPullzz! Unfortunately, we only support picking single documents on native. For web, we do support multiple! There is a [feature request](https://expo.canny.io/feature-requests/p/capability-of-document-picker-to-select-multiple-files-with-different-extensions) about this, if you need this feature you can upvote and promote that request. To work around this issue you can let the user pick them one by one and combine them in the call to the backend.
> 
> Hope it helps

Thx for answer!

**Comment by cdeviabylte** [comment]
We need this too.. Our only reason to "eject" the app...

**Comment by cdeviabylte** [comment]
BTW, I think this feature request should be re-opened. It has 240 votes and it's the same request.
https://expo.canny.io/feature-requests/p/allow-choosing-multiple-images-in-imagepicker

**Comment by ebo7** [comment]
This would be nice!
