### ISSUE TITLE
AD Mob not working

### ISSUE THREAD

**Issue by c7nasr** [expo/expo#7924]
When I try open Admob expo documentation, I can't reach it

Link: https://docs.expo.io/versions/latest/sdk/admob/

![Q3Hi5pRMrZ](https://user-images.githubusercontent.com/42423651/79770230-6cc77780-832d-11ea-98c3-b5ea317ea366.png)

**Comment by byCedric** [comment]
Hi @c7nasr! Thanks for notifying us. On my end, this should work now! 😄 If it still doesn't work for you, [could you try the versioned URL](https://docs.expo.io/versions/v37.0.0/sdk/admob/)? Let me know if this doesn't work for you.

**Comment by c7nasr** [comment]
Hmmm, it still not working, Also when i cleared Cache and History 
![image](https://user-images.githubusercontent.com/42423651/79779274-6c81a900-833a-11ea-862a-e3d63f2edb16.png)

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/latest/sdk/admob/

<img width="1580" alt="Screen Shot 2020-04-20 at 10 11 43 AM" src="https://user-images.githubusercontent.com/90494/79779499-57cbf380-82ef-11ea-97c5-d00afe5335e4.png">


try a different browser? maybe you have some extension installed that is messing up the url?

**Comment by c7nasr** [comment]
oh right. Adblock is blocking page. a mistake from the engine because of its "Ad" page. Thanks
