### ISSUE TITLE
Have long Expo App Store Name but a short Display Name for home screen

### ISSUE THREAD

**Issue by croossin** [expo/expo#7926]
### Environment

  Expo CLI 3.18.2 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.18.2

iOS and Android
### Steps to Reproduce

Use `app.json` to have both a unique AppStore name (longer) and then a short name on the home screen (shorter)

### Expected Behavior

Have a long AppStore name (so it's unique) and have a short display name of the home screen.

### Actual Behavior

The AppStore name is the home screen name

### Reproducible Demo
```json
{
  "displayName": "Short Name",
  "expo": {
    "name": "Long Name: Your Long App Name",
    "slug": "spot",
    ....
}
```

Is it possible to have a short different Display Name than your Expo Name without ejecting?

**Comment by cruzach** [comment]
Hi @croossin ! You can use the `expo.name` field as the display name (short name), and when you submit your standalone app through appstoreconnect, you can choose a longer name for the actual App Store listing

Let me know if that answers your question

**Comment by reft** [comment]
@cruzach How do you choose a longer name when you use eas submit? Adding submit.product.ios.appName/ascAppId seems to be ignored in eas.json

**Comment by GiselaK** [comment]
++

**Comment by GiselaK** [comment]
> @cruzach How do you choose a short name for homescreen when you use eas submit? I have my fullname in expo.name. Changing this to my short name causes the eas submit to go to a different name, (short name).

++
