### ISSUE TITLE
[expo-updates] For those of you who removed expo-updates and seeing no bundle url present error, i got a solution for ya

### ISSUE THREAD

**Issue by guanhuay** [expo/expo#7927]
### Please note that discussions opened as issues in the core Expo repository will be closed.

Recently, I removed expo-updates from my bare-minimum repo (SDK37), basically I just follow the steps listed by on expo-updates README but in a reverse order.

After detached expo-updates, when I tried running it on IOS physical device, I am seeing **"No bundle url present"** error. After quite some time of debugging, I found out it happened because you didn't add this step to your project Build Phases (see below screenshot). This should solved your problem

![Screen Shot 2020-04-20 at 09 23 07](https://user-images.githubusercontent.com/16933391/79775113-9c07c580-82e8-11ea-8bce-a0bd68f0be35.png)

**Comment by pRizz** [comment]
That fixed it for me, thanks!

For convenience, here's the snippet:
```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

**Comment by tonuegbu** [comment]
You've saved me @guanhuay
