### ISSUE TITLE
AuthSession.getRedirectUrl failing on web

### ISSUE THREAD

**Issue by lrholmes** [expo/expo#7929]
### Steps to Reproduce

Can be reproduced by following the documentation described here: https://docs.expo.io/versions/latest/sdk/auth-session/

### Expected Behavior

When I click the button to trigger the auth session code, it should open a popup.

### Actual Behavior

I encounter an error: `ManagedSessionUrlProvider.ts:109 Uncaught (in promise) TypeError: Cannot read property 'startsWith' of undefined`

### Possible Fix / Pointer towards solution

 By checking out what the function expects and observing what works when being run on iOS, the problem appears to be that `manifest.id` isn't provided in `Constants` on the web environment.

I've been able to get around this by adding the following to the example code:

```js
if (Platform.OS === 'web') {
  Constants.manifest.id = `@${MY_EXPO_USERNAME}/${Constants.manifest.slug}`;
  WebBrowser.maybeCompleteAuthSession();
}
```

This works for me for the time being (and the universal auth flow is **_awesome_** 🥇)

Hope this helps to resolve the issue somehow!

**Comment by EvanBacon** [comment]
This has been fixed in https://github.com/expo/expo/pull/7656 but it wasn't pulled into the published version. @brentvatne

**Comment by EvanBacon** [comment]
This should be fixed but I still want to do one more pass on the redirect uri API for the new auth session.
