### ISSUE TITLE
Sign in With Apple stuck on iPad iOS 13.4.1

### ISSUE THREAD

**Issue by appseugene** [expo/expo#7933]
### Environment

  Expo CLI: 3.17.23
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.
gz => 0.61.4

SDK Version: 37.0
Platforms: iOS 13.4.1 (iPad)

### Steps to Reproduce

On Any iPad running iOS 13.4.1, try using the Sign in With Apple flow.

### Expected Behavior

Successful login

### Actual Behavior

Stuck at continue (on Apple login dialog)

#########

Hello, I just got a message from Apple that the Sign in With Apple feature does not work on iPad with iOS 13.4.1 on Wi-Fi. I do not have an actually iPad with that version currently, but it seems that the sign in is just stuck as soon as user has apple UD setup to continue with login: [https://i.ibb.co/GMYDFGH/i-Pad-Issue.jpg](url)

**Comment by byCedric** [comment]
Hi @appseugene! Thanks for the issue. Could you make a [small repro](https://stackoverflow.com/help/minimal-reproducible-example) with this problem for us? That way, we can investigate it a bit faster 😄

**Comment by appseugene** [comment]
@byCedric , I'll try to make a repo, but for now all I wanted is to have someone that has an iPad running iOS 13.4.1 simply try Sign In With Apple (in any Expo project). I just want to see if that even works first.

As mentioned above, my production app is Expo CLI: 3.17.23 with managed workflow and this was inside a standalone app sent to Apple for review. So that's what I'm trying to see if anyone has a standalone app using apple sign in, if that works on iPads...

Sorry if I'm not approaching this correctly here.

**Comment by appseugene** [comment]
after other attempts, the issue was not there anymore.
