### ISSUE TITLE
with-storybook demo / expo-linear-gradient breaks with react-native-web 0.12.2

### ISSUE THREAD

**Issue by oskari** [expo/expo#7938]
## 🐛 Bug Report

With my limited knowledge of these, I would guess the breaking change is:

_from https://github.com/necolas/react-native-web/releases/tag/0.12.0_
> Remove prop types exports from package. These are deprecated in React Native and introduce significant DEV time performance cost. Flow types are now preferred ([1ad1693](https://github.com/necolas/react-native-web/commit/1ad16930391303da511c98879fa7b2002b28c822))

### Environment

  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.19.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4

### Steps to Reproduce

Clone [with-storybook](https://github.com/expo/examples/tree/master/with-storybook) demo, upgrade react-native-web to 0.12.2.
run `yarn storybook`

### Expected Behavior

storybook would work and compile without errors

### Actual Behavior

`ERROR in ./node_modules/expo-linear-gradient/build/LinearGradient.js
Module not found: Error: Can't resolve 'react-native-web/dist/exports/ColorPropType' in '/Users/oskari/projektit/expo-storybook-ts-gradient/node_modules/expo-linear-gradient/build'
 @ ./node_modules/expo-linear-gradient/build/LinearGradient.js 21:0-72 75:28-41
 @ ./node_modules/expo-linear-gradient/build/index.js
 @ ./stories/3-LinearGradient.stories.js
 @ ./stories sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^\/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/resize-observer-polyfill/dist/ResizeObserver.global.js ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./node_modules/expo-linear-gradient/build/LinearGradient.js
Module not found: Error: Can't resolve 'react-native-web/dist/exports/ViewPropTypes' in '/Users/oskari/projektit/expo-storybook-ts-gradient/node_modules/expo-linear-gradient/build'
 @ ./node_modules/expo-linear-gradient/build/LinearGradient.js 23:0-72 74:45-58
 @ ./node_modules/expo-linear-gradient/build/index.js
 @ ./stories/3-LinearGradient.stories.js
 @ ./stories sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|\/)\.).)*?)\/)?(?!\.)(?=.)[^\/]*?\.stories\.js\/?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/resize-observer-polyfill/dist/ResizeObserver.global.js ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/generated-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true`

### Reproducible Demo

1. Clone https://github.com/oskari/expo-storybook-ts-gradient
2. Run `yarn storybook`

**Comment by byCedric** [comment]
Hi @oskari! Thanks for brining it up. At the moment, we only support `react-native web ~0.11.7`. There are a couple of other breaking stuff that we have to fix before we can upgrade. I'll keep this issue open until this is resolved!

**Comment by tomByrer** [comment]
@oskari  The new Expo is released, & they updated this example as well.  It now works good for me, + I also updated `"react-native-web": "0.13.14"`. (I updated manually only this version since it was fixed at 0.13.13.)
