### ISSUE TITLE
iOS: There was an error with this build

### ISSUE THREAD

**Issue by denisjacquemin** [expo/expo#794]
While I was trying build IOS , got stuck with this error. 

`iOS: There was an error with this build`

"exp build:ios -c" doesn't solve the problem. Any Help?
Build ID: e5fa613c-53ab-44f1-9ba0-b483e8beb991

Thank you

**Comment by jhalborg** [comment]
I would try pinging them on Slack instead, as it's not an issue with Expo or the Expo Client, but with the build server for standalone apps

**Comment by dikaiosune** [comment]
@denisjacquemin hi! It looks like we had a problem validating your provisioning profile. Can you try your build again? Going to close this as we're focusing GitHub on bug reports, but please post to the forums if you have issues again!
