### ISSUE TITLE
expo-print doesn't render local files on iOS

### ISSUE THREAD

**Issue by CapelliC** [expo/expo#7940]
The iOS PDF did showed the local images at least til SDK ver.31,
after I discovered that passing the (undocumented?) option
*baseUrl* to Print.printAsync allowed the iOS print engine to load the image files.

Then I had to upgrade to the latest SDK, to follow up with maintenance duties,
and the PDF doesn't show any kind of file:// URIs

I have uploaded a test repo: https://github.com/CapelliC/expo-print-test-pdf-file-uri-missing-ios

(follow up of https://github.com/expo/expo/issues/7435)

**Comment by IjzerenHein** [comment]
I could image that encoding the image inline as base64 could do the trick.

**Comment by CapelliC** [comment]
For iOS, I have encoded in base64, following @IjzerenHein hint. Be sure to test your App with small devices, the workaround probably requires a fair amount of RAM.
You can see [here](https://github.com/CapelliC/expo-print-test-pdf-file-uri-missing-ios) the testbed. Hope it's still working...

**Comment by Gautam8080** [comment]
Thank you so much! I actually tried converting to base64 by AssetUtils.base64forImageUriAsync but didn't work. I spent hours yesterday to sort this out but unfortunately, there isn't much documentation out there to solve the problem, except this thread. I believe the RAM isn't an issue at the moment or as it seems. I will keep that in mind though.

**Comment by vishwaefor** [comment]
Reading local image as following worked for me

        const data = await FileSystem.readAsStringAsync('file://' + uri, {
          encoding: FileSystem.EncodingType.Base64,
        });

        const imageData = 'data:image/png;base64,' + data;

        pdfBody += ` 
          <div class="wrapper">
            <img src="${imageData}" width="100%"  />
          </div>`

**Comment by tsapeta** [comment]
The workaround posted by @vishwaefor seems to be the proper way to fix it. I'm afraid we can't do anything more with this 😞 I'm gonna add a note about this in the docs.

**Comment by axelmy318** [comment]
> Reading local image as following worked for me
> 
> ```
>     const data = await FileSystem.readAsStringAsync('file://' + uri, {
>       encoding: FileSystem.EncodingType.Base64,
>     });
> 
>     const imageData = 'data:image/png;base64,' + data;
> 
>     pdfBody += ` 
>       <div class="wrapper">
>         <img src="${imageData}" width="100%"  />
>       </div>`
> ```

Any idea on how to do that in production ? The file uri is "assets_filname" without extensions but only in production builds... I have no idea what to do with it

**Comment by Vaibhav-162** [comment]
> Reading local image as following worked for me
> 
> ```
>     const data = await FileSystem.readAsStringAsync('file://' + uri, {
>       encoding: FileSystem.EncodingType.Base64,
>     });
> 
>     const imageData = 'data:image/png;base64,' + data;
> 
>     pdfBody += ` 
>       <div class="wrapper">
>         <img src="${imageData}" width="100%"  />
>       </div>`
> ```

shouldn't you use async, I tried using this and got 
expected Buffer size 6308 starts with: 5f5f642866756e6374696f6e2028676c and has protection mode(s): rw-p
and suppose if I try to make it async will be available in src when it create my html ?
