### ISSUE TITLE
Expo Bare Workflow TaskManager - Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

### ISSUE THREAD

**Issue by justin-lu054** [expo/expo#7949]
### Environment
Expo CLI 3.15.4 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 13.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.4 => 0.61.5

I am running on android via `react-native run-android`

### Steps to Reproduce
Run `react-native run-android` on a bare workflow expo project that utilizes the TaskManager module.

### Actual Behavior
Java Runtime Error (See below)
![image](https://user-images.githubusercontent.com/50785101/79901587-08182580-83de-11ea-811b-68d5a596ed32.png)

### Reproducible Demo
The source of this error is in `TaskManagerInternalModule.java`.
```java
private boolean isRunningInHeadlessMode() {
    return mTaskService.isStartedByHeadlessLoader(getAppId());
  }
```

**Comment by DmitryKvant** [comment]
Some news? I have same issue

**Comment by DmitryKvant** [comment]
And I get more this 
`Cannot load settings from file '/Users/dmitrykvant/Projects/handymanApp/node_modules/unimodules-task-manager-interface/android/unimodules-task-manager-interface.iml': File /Users/dmitrykvant/Projects/handymanApp/node_modules/unimodules-task-manager-interface/android/unimodules-task-manager-interface.iml does not exist Please correct the file content`

**Comment by DmitryKvant** [comment]
It must be connected

**Comment by DmitryKvant** [comment]
Update unimodules-task-manager-interface to v5.1.0 fix it

**Comment by DmitryKvant** [comment]
Okey update unimodules to version 8 fix if

**Comment by zlanich** [comment]
@DmitryKvant What package did you upgrade to version 8? I'm seeing something like 5.1.* highest on these packages.
