### ISSUE TITLE
Update documentation about using Info.plist fields to enable Linking.canOpenUrl in standalone apps

### ISSUE THREAD

**Issue by jhalborg** [expo/expo#795]
Hello Expo team, 

First of all, thank you for all that you do!

`Linking.canOpenUrl` does not work properly with Expo it seems. My use case is opening the Instagram app on a specific media ID if installed, and if not, open it in a WebBrowser instead. Hence, I would like to use the call to determine what to do, however it always returns false, even if the app is installed. 

If I try to open the link anyway by just doing `Linking.openUrl('instagram://app')`, Instagram opens just fine. 

It also works with a specific media id 
(`Linking.openUrl(instagram://media?id=${this.props.post.source.id})`)

This problem might be, that as pr the [docs](https://facebook.github.io/react-native/docs/linking.html#canopenurl) for the call, a change must be made to the .plist of iOS:
`NOTE: As of iOS 9, your app needs to provide the LSApplicationQueriesSchemes key inside Info.plist or canOpenURL will always return false.` 

Any way this could be supported, or something I can change locally to make it work without ejecting? Thanks

[Instagram linking docs for reference](https://www.instagram.com/developer/mobile-sharing/iphone-hooks/)

**Comment by dikaiosune** [comment]
Thanks! We cover how to link to other apps in https://docs.expo.io/versions/latest/guides/linking.html#opening-links-to-other-apps, but we should cover in our documentation how to enable `canOpenUrl`. I *believe* it just involves adding the appropriate keys to https://docs.expo.io/versions/latest/guides/configuration.html#infoplist in app.json.

**Comment by brentvatne** [comment]
You can basically get around using canOpenUrl entirely in the docs section that @dikaiosune linked to, you don't need to use it in the client or in standalone, but it's there in case you want to in standalone.

**Comment by jhalborg** [comment]
Great to know about the .plist in the app.json config, I honestly didn't know yet :) I'll implement that too for standalone apps. 

As for getting around using canOpenUrl as you mention, @brentvatne , in my use case I'd like to open an inapp WebBrowser with a link to the specific Instagram media in case the user does not have Instagram installed. As far as I can tell, the only way to circumvent canOpenUrl mentioned in the docs is by using the react-native-app-link to instead open the appstore for the app, or did I misunderstand?

> It’s possible that the user doesn’t have the Lyft app installed, in which case you may want to open the App / Play Store, or let them know that they need to install it first. We recommend using the library react-native-app-link for these cases.

**Comment by brentvatne** [comment]
> As for getting around using canOpenUrl as you mention, @brentvatne , in my use case I'd like to open an inapp WebBrowser with a link to the specific Instagram media in case the user does not have Instagram installed. As far as I can tell, the only way to circumvent canOpenUrl mentioned in the docs is by using the react-native-app-link to instead open the appstore for the app, or did I misunderstand?

look at the source for it, it's just a few lines of code which attempts to open the link and then catches an error if it doesn't work and does whatever you want in that case: https://github.com/fiber-god/react-native-app-link/blob/master/index.js

**Comment by freeall** [comment]
> I believe it just involves adding the appropriate keys to https://docs.expo.io/versions/latest/guides/configuration.html#infoplist in app.json.

Does anyone know what the appropriate keys look like?

I believe it's like this (for `skype:` url's):
``` json
    "ios": {
      "infoPlist": {
        "LSApplicationQueriesSchemes": ["skype"]
      }
    }
```

I can't find any documentation on how `Expo` parses the `infoPlist` property.

**Comment by peterpme** [comment]
@freeall I believe that is the correct format. You'll have to create a new IPA (`exp build:ios`)

**Comment by savlslipchuk** [comment]
I ran into the same problem, but I'm trying to open Skype
