### ISSUE TITLE
Android Expo client internet connection error

### ISSUE THREAD

**Issue by kachnitel** [expo/expo#7953]
## 🐛 Bug Report
The Android Expo client app cannot connect to the internet. It either doesn't open with a blue screen, error log saying "Expo requires an internet connection", or when it does launch it:
- won't see open projects for signed in user
- won't sign in user with a connection error
- Explore tab shows "An unexpected server error has occurred. Sorry about this. We will resolve the issue as soon as quickly as possible. Try again."
- Launching app using QR code it'll build, download and immediately crash with "The expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit ..."

The issue doesn't happen on my Samsung A5, but does happen on Huawei P20 Pro. I found no reference to the issue other than an old resolved forum thread. Reinstall, data reset, cache wipe, device reboot doesn't help.

The only reference to a current issue seems to be a large [number of reviews](https://play.google.com/store/apps/details?id=host.exp.exponent&hl=en_CA&showAllReviews=true) with seemingly similar issue on Google Play.

Connection doesn't work regardless whether it's WiFi or cell. 

I feel like this isn't the right place for the issue, but I didn't find any better.

### Environment

Client version: 2.15.4
Device ID: 91ee-cf9e

### Steps to Reproduce

Try to open the Expo client on an affected device.

### Reproducible Demo

...is a physical device.

**Comment by cruzach** [comment]
Hi! thanks for reporting this

What android OS is your Huawei P20 Pro running?

**Comment by kachnitel** [comment]
It's running Android 9.1. 
I downloaded Expo from the Play store, apparently only newer devices (such as the P40) are restricted so a P20 can use Google services like any other phone, unless there are some exceptions. 
I may have failed to mention it did work just fine before. I took a break in development for a few months so I cannot tell when exactly it stopped working, but going by Google Play reviews it must be the latest version or two, is there an archive I could get an older version to try?

What's really puzzling is the fact even my app built as an APK that also worked fine previously now errors when trying to update with `E_FETCH_MANIFEST_FAILED`. I feel like the issue is related and for whatever reason the device cannot connect to Expo servers, but I have zero clue why would that happen.

**Comment by cruzach** [comment]
here's the link to download v2.14 of the Expo Client - https://d1ahtucjixef4r.cloudfront.net/Exponent-2.14.0.apk

here's the link to download v2.13 of the Expo Client - https://d1ahtucjixef4r.cloudfront.net/Exponent-2.13.1.apk

Can you make sure you're on the most recent version of `expo-cli`?

**Comment by kachnitel** [comment]
So I tested both versions and the error is the same. 

It shouldn't really be related to the CLI because the connection fails before trying to open any projects, but either way I'm using `3.18.6`, updated while trying to troubleshoot but I isolated the issue to the device itself. 

### Problem
I just realised I'm using an [ad blocking VPN](https://blokada.org/index.html), turned it off and voila! 

### Solution
If anyone else runs into such issue, whitelisting `*.expo.io,exp.host` solved the whole problem.

**Comment by Difren77** [comment]
I have the same problem with endless loading and the blue screen in expo go. I don't understand what kind of whitelisting* is.expo.io ,exp.host
