### ISSUE TITLE
[ExponentPushToken] Is a tokenever reused

### ISSUE THREAD

**Issue by Chiefbark** [expo/expo#7960]
I am working on an app where no login is provided but i use firebase.
I need to detect the device with a specific key to access its own data, and i was thinking about using the expo push token.
But I realized that if an app is removed, the token is no longer in use, so **my question is**:
what happens to the tokens that are no longer in used? Can other device have that token?

**Comment by ide** [comment]
The token is currently not reused but this is not part of the API contract. You are guaranteed that no two devices will have the same token at the same time.

If you want to uniquely identify devices across all points in time, I would create an ID with that semantics.
