### ISSUE TITLE
Do video player support active playing when the app goes into background?

### ISSUE THREAD

**Issue by yasahmed** [expo/expo#7965]
Do video player support active playing when the app goes into background ?

**Comment by cruzach** [comment]
Yes, see `staysActiveInBackground` in our docs: https://docs.expo.io/versions/latest/sdk/audio/#audiosetaudiomodeasyncmode

**Comment by yasahmed** [comment]
@cruzach im talking About Video not Audio !

**Comment by cruzach** [comment]
What's the use case of playing a video while the app is backgrounded?

**Comment by yasahmed** [comment]
Listen to Video Sound When app is annactive but it's still working on background

**Comment by markymc** [comment]
This is a real (and I would have assumed common) use case, and [is supported by react-native-video](https://github.com/react-native-video/react-native-video#playinbackground). For example, I'm building an app that allows users to watch music videos. Background playback seems rather important to the UX for such a use case.

**Comment by markymc** [comment]
@cruzach please consider re-opening this 🙇 Thanks!
