### ISSUE TITLE
 play in the background on android expo-av

### ISSUE THREAD

**Issue by emersonrf227** [expo/expo#7966]
in Expo-av I'm having problems playing in the background on the Android operating system, I realized that the problem is solved when I take the battery optimization in the operating system, does anyone know any way to solve this?

**Comment by cruzach** [comment]
What problem are you trying to solve? We keep github reserved for bug reports, so questions like this are better off posted on our [forums](https://forums.expo.io/) (If you think this is a bug, please file a new issue and fill out the bug report template)

I'm guessing the OS is place the app in App Standby - https://developer.android.com/training/monitoring-device-state/doze-standby - although afaik that shouldn't happen while the app is using an activity or foreground service
