### ISSUE TITLE
tar.gz for react-native cause unstable CI installation

### ISSUE THREAD

**Issue by kopax** [expo/expo#7968]
I have error in CI, that keep crashing while running `npm i`.

This makes my expo project the most unstable CI I have ever had.

This is happening now:

```jsx
 npm WARN tar ENOENT: no such file or directory, open '/mnt/mesos/sandbox/builds/momagroup/icimatin-native/node_modules/.staging/hermes-engine-71d66aa1/linux64-bin/hermes-repl'
 npm ERR! code E500
 npm ERR! 500 Internal Server Error - GET https://codeload.github.com/expo/react-native/tar.gz/sdk-36.0.1
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2020-04-23T13_50_24_894Z-debug.log
 ps process exited with code 1
 Running after script...
```

I believe there is a timeout on `codeload.github.com` that cause in general this error: 

```jsx
 8 packages are looking for funding
   run `npm fund` for details
 npm ERR! cb() never called!
 npm ERR! This is an error with npm itself. Please report this error at:
 npm ERR!     <https://npm.community>
 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2020-04-23T13_17_46_944Z-debug.log
 ps process exited with code 1
 Running after script...
```

I must retry an infinite amount of time, some day it fail:

![image](https://user-images.githubusercontent.com/1866564/80107662-a988ae00-857b-11ea-956e-c5465d5162dc.png)

Some day it may pass:

![image](https://user-images.githubusercontent.com/1866564/80107824-dfc62d80-857b-11ea-918d-3a11e6e97de6.png)

Is there another way that I can install this dependency?

**Comment by kopax** [comment]
I am happy that this error 500 comes up because now I can see that using a copy stored on my repository of this file using :

```diff
{
  "dependencies": {
-     "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
+    "react-native": "file:expo/react-native-sdk-36.0.1.tar.gz"
  }
}
```

This makes my CI much more stable. I would suggest to write this in expo documentation because it is not normal that the CI crash due to some timeout. 

It is worth to add that without that file, our applications are completely useless.

**Comment by cruzach** [comment]
Hey, sorry but this is related to recent Github instability, see here - https://www.githubstatus.com/

As for the second error, have you checked the provided logs for more details? I think this could be related to the npm cache (the error message seems to indicate it's a problem with npm, so I'm not sure it's an expo bug)

@kopax , as with previous issues, it's really necessary for you to follow the full bug report template when you file an issue here for us to be able to help

**Comment by kopax** [comment]
Roger that, I have digged into the error and unfortunately I can't find anything related to the cause. I am thinking to switch to yarn
