### ISSUE TITLE
Android FileSystem unable to copy, move, or download takeSnapshotAsync images. 

### ISSUE THREAD

**Issue by jayeszee** [expo/expo#797]
So, I've been using takeSnapshotAsync to create snapshots images of some of my screens. However, it seems like whenever I try to make a more permanent version (by either moving or copying over from the cache) it won't allow me to.

`FileSystem.moveAsync({
from: 'file:///data/user/0/host.exp.exponent/cache/ReactNative_snapshot_image_657185016.png',
to: '${FileSystem.documentDirectory}${id}.png'})`

This actually includes `moveAsync` `downloadAsync` `copyAsync`

I think I had similar issues on iOS but I was at least able to downloadAsync the image so I didn't have to look too deeply into it.

Heres the stack trace:
```
Error: Invalid Filesystem URI 'file:///data/user/0/host.exp.exponent/cache/ReactNative_snapshot_image_657185016.png', make sure it's in the app's scope.
    at createErrorFromErrorData (NativeModules.js:117)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:354)
    at MessageQueue.js:129
    at MessageQueue.__guard (MessageQueue.js:269)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:128)
    at debuggerWorker.js:72
```

**Comment by nikki93** [comment]
This will be addressed in https://github.com/expo/expo/issues/776, closing here.
