### ISSUE TITLE
[docs] list of broken links

### ISSUE THREAD

**Issue by x8core** [expo/expo#7972]
https://docs.expo.io/bare/unimodules-full-list/
I think this page instead of unimodules-full-list, should have slug like "list of broken links"

**Comment by byCedric** [comment]
Hi @x8core! I'm so sorry, thanks for bringing it up. Expect a patch soon!

**Comment by brentvatne** [comment]
my bad, i just restructured the docs yesterday and i missed updating the links in this section. appreciate the report!

**Comment by brentvatne** [comment]
fixed in https://github.com/expo/expo/commit/9d88422587fd88adf7bf4eaee7b467e70823ecd0
and to be very safe i added https://github.com/expo/expo/commit/23832b22902b37ac7e425c53c3edcd20fa023e55 which will redirect links to `/sdk/*` to `/versions/latest/sdk/*`

should be deployed in the next 10 minutes

**Comment by x8core** [comment]
Great! Thank you for hotfix.
