### ISSUE TITLE
error with task-manager , TaskManager: Task "locationTask" has been executed but looks like it is not defined. Please make sure that "TaskManager.defineTask" is called during initialization phase.

### ISSUE THREAD

**Issue by sarahalmunif** [expo/expo#7975]
### Environment

  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.4/11N132i - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.18.6
my app target is iOS

### Steps to Reproduce

1-TaskManager.defineTask() in global scope in app entry file (App.js)
2- Location.startGeofencingAsync('locationTask',[
            {
                "identifier": "A",
                "latitude": lat,
                "longitude": lng, 
                "radius":100,
                "notifyOnEnter": true,
                "notifyOnExit": true,
               
 }
   ])in global scope in app entry file (App.js)
3-Log output

### Expected Behavior

Background geofencing should work exactly as if the app were active.

### Actual Behavior

error which says 
TaskManager: Task "locationTask" has been executed but looks like it is not defined. Please make sure that "TaskManager.defineTask" is called during initialization phase.

### Reproducible Demo
     export default function App(props) {
     var lat=0;
     var lng=0;
     users=firebase.auth().currentUser;
    if(users !=null){
    firebase.database().ref('mgnUsers/'+firebase.auth().currentUser.uid).once('value',(snap)=>{ 
    lat= snap.val().latitude;
    lng= snap.val().longitude;
       })
      try{
       if(!(lat==='0'&& lng==='0')){
        Location.startGeofencingAsync('locationTask',[
            {
                "identifier": "A",
                "latitude": lat,//await AsyncStorage.getItem('latPoint'),
                "longitude": lng, //await AsyncStorage.getItem('lngPoint'),
                "radius":100,
                "notifyOnEnter": true,
                "notifyOnExit": true,
               
            }
           ])
           }
         }
        //  }//end try
        catch(error){
        }//end catch
       }
      }

         TaskManager.defineTask('locationTask', async ({ data, error }) => {

 
         });

**Comment by byCedric** [comment]
Hi @sarahalmunif! Thanks for the report, unfortunately, I can't reproduce this on my end. I recreated your [code in snack](https://snack.expo.io/@bycedric/test-geofencing) (it's currently pinned to Amsterdam) but this worked fine in Snack. Could you elaborate a bit more about how you are using it? Like using it in bare or managed flow? If you can, a [small repro](https://stackoverflow.com/help/minimal-reproducible-example) would also help us determine the issue 😄 

Hope it helps!

**Comment by tsapeta** [comment]
Closing due to no response to the previous comment, not being able to reproduce it and no other user reports similar to this.
