### ISSUE TITLE
`takeSnapshotAsync(...)` should write to `Expo.FileSystem` directories

### ISSUE THREAD

**Issue by nikki93** [expo/expo#798]
`takeSnapshotAsync(....)` currently writes to a directory that isn't read+write-eable by `Expo.FileSystem` functions:
https://github.com/expo/expo/blob/5602c52b43e1d24778e55ffdce94400c2c751214/ios/Exponent/Versioned/Modules/Api/EXViewShot.m#L77
https://github.com/expo/expo/blob/5602c52b43e1d24778e55ffdce94400c2c751214/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/RNViewShotModule.java#L67
Update this to write to something like `Expo.FileSystem.cacheDirectory`.

**Comment by personapp** [comment]
How did you close the issue ?
