### ISSUE TITLE
 A black screen shows before loading the splash screen in iOS

### ISSUE THREAD

**Issue by OscarYuen** [expo/expo#7981]
### Environment

Expo SDK 37 with bare minimum template

### Steps to Reproduce

Create bare minimum template with expo.
Follow the readme for iOS 
https://github.com/expo/expo/tree/master/packages/expo-splash-screen
run on my iOS physical device

### Expected Behavior

There should be no black screen at the start

### Actual Behavior

First a black screen would show.
And then the splash screen shows with bundle loading progress bar

When I switch back to default xib file as splash screen, it doesn't has the black screen at the beginning.

### Reproducible Demo

It's hard to give the demo as it doesn't involve any code on react native...

**Comment by mdcuk34** [comment]
I followed the manual instructions and also received the same behaviour you're experiencing. I solved this by using the [automatic generation](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#automatic-configuration) tool instead.

**Comment by OscarYuen** [comment]
> I followed the manual instructions and also received the same behaviour you're experiencing. I solved this by using the [automatic generation](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#automatic-configuration) tool instead.
Thanks. Automatic generation can solve this issue.

I think "Storyboard Entry Point" is missing in manual instruction.
"Is Initial View Controller" must be ticked in View Controller.
<img width="259" alt="Screenshot 2020-04-24 at 11 32 31 PM" src="https://user-images.githubusercontent.com/5617834/80230196-2acb6800-8684-11ea-895d-33edbb235ca6.png">

**Comment by byCedric** [comment]
Thanks for sharing your solution! Maybe we can add this to the docs? 😄

**Comment by OscarYuen** [comment]
> Thanks for sharing your solution! Maybe we can add this to the docs? 😄

Sure!
