### ISSUE TITLE
expo-splash-screen exits app on load

### ISSUE THREAD

**Issue by rarescrisan** [expo/expo#7987]
### Environment

  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.18.6

Running newly set up bare workflow using `expo init --template bare-minimum` target is simulator iPhone 11 (13.4)

### Steps to Reproduce

`npm i expo-splash-screen --save` then go into `/ios` folder and run `pod install` I can see it in this list.

```
...
 expo-keep-awake@8.1.0 from ../node_modules/expo-keep-awake/ios
 expo-linear-gradient@8.1.0 from ../node_modules/expo-linear-gradient/ios
 expo-location@8.1.0 from ../node_modules/expo-location/ios
 expo-permissions@8.1.0 from ../node_modules/expo-permissions/ios
 expo-splash-screen@0.2.0 from ../node_modules/expo-splash-screen/ios
 expo-sqlite@8.1.0 from ../node_modules/expo-sqlite/ios
...
```

I don't even import it into a file, simply run `npm run ios` which runs `react-native run-ios`  everything build - bundle is 100% simulator loads. The app opens briefly for a second and then exits back to the the home screen or screen where you can see all the apps on the simulator. The React Native app also doesn't have an icon on the app screen for me to tap to open again. 

Essentially - just installing expo-splash-screen causes the application to crash and exit.

### Expected Behavior

App opens and stays open

### Actual Behavior

App opens then immediately exits

### Reproducible Demo
https://github.com/rarescrisan/expo-splash-screen-broken

**Comment by Billy-IV** [comment]
I am also having this issue.  I run my app using "expo start" and it loads there is a flash our landing screen and then it crashes.

**Comment by sarmad1995** [comment]
It has some issues with react navigation, if we have react navigation and expo splash screen.
It crashes on android.

**Comment by byCedric** [comment]
Hi @rarescrisan (and @Billy-IV)! Thanks for the issue and repro! It looks like the default settings for the splash screen are missing. Could you try running `npx expo-splash-screen "#ffffff"`? [More info here](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#automatic-configuration). After this automatic configuration, your repro works fine 😄 

Hope it helps!
