### ISSUE TITLE
Element Inspector shows behind an open modal making it impossible to inspect the elements of a modal

### ISSUE THREAD

**Issue by chialuka** [expo/expo#7989]
I have an expo project and I wanted to inspect the elements on a modal. However, the menu opens behind the modal on both iOS and Android, meaning I'd have to close the modal to see it. This also means I can't inspect the elements of the modal since the button for opening it cannot be clicked when the modal is closed and I am inspecting.

Is there a workaround for this?

**Comment by byCedric** [comment]
Hi @LukasChiama! Thanks for the report, I can confirm this is happening on my devices too. I don't have a quick workaround for this, but maybe others have? (cc @tsapeta). For reference, I could repro this using the [RN modal docs example](https://reactnative.dev/docs/modal).

**Comment by tsapeta** [comment]
Hi @chialuka, is it still an issue in the most recent version of Expo in the App Store?

**Comment by chialuka** [comment]
Hi @tsapeta, I tested with the latest version of Expo from npm and on both Android and iOS simulators. And yes, it is still an issue

**Comment by tsapeta** [comment]
Fix for this is in the native code of Expo app, so updating `expo` package from `npm` cannot solve it.
For iOS simulator, could you try running `expo client:install:ios` (which installs the latest Expo app on your simulator) and then test it again?

**Comment by chialuka** [comment]
@tsapeta, thank you. I can confirm that installing the latest Expo app on the iOS simulator solves this. Doing the same for the Android simulator does not fix it on that platform though

**Comment by joelversafleet** [comment]
This is still happening on Android, using Expo Go app v2.23.2.

I don't have an iPhone or a Mac to run the simulator on, so Android is the only way. 

Could we reopen this issue please? Or should I open a new issue for this?
