### ISSUE TITLE
Could not invoke ExponentLocation.getCurrentPositionAsync error

### ISSUE THREAD

**Issue by skasanibanyan** [expo/expo#799]
I have detached app with ExpoKit to integrate FCM. I have used react-native-fcm plugin and now the app is crashing with **Error: Could not invoke ExponentLocation.getCurrentPositionAsync**

**Comment by poptocrack** [comment]
Yeah, just ran into the same problem this morning. Didn't found a fix yet

**Comment by skasanibanyan** [comment]
I am still stuck with it and trying out different things with no luck. 
I think the problem might be with the versions of some google-services. I didn't get this error before making the changes to gradle files and AndroidManifest file as per the guidelines to setup FCM.

**Comment by poptocrack** [comment]
I found a fix for my problem but it won't work with yours. The problem was coming from MapView and the airbnb plugin.
My principal issue was so dumb: I was using a web API key instead of an Android one, since I have detached, it couldn't work.
The problem wasn't coming from Expo or Location.

I hope it will help you.
Good Luck

**Comment by Fizbanoide** [comment]
Hi guys,

I'm having the same issue since a few minutes, i tried to change my API key for an Android one but it's still not working. I followed this tutorial (https://codeburst.io/react-native-google-map-with-react-native-maps-572e3d3eee14), everything was working fine and right after the last step this error showed up, no clue where this is coming from

**Comment by poptocrack** [comment]
So... I've got this error again. Seems like if you have use of the location in an attached app, and then use detach everything works fine.
But, if you install a plugin ( same error with airbnbmaps and reac-native-ble-manager) the "Could not invoke..) error is thrown. Maybe it has somthing to do with react-native link? I've installed plugins whom did not require to link and everything was fine. Until i used link.

**Comment by Fizbanoide** [comment]
Might be actually, so you're saying that it's worth trying without using link ? Or detach it only when every plugins are installed ?

**Comment by poptocrack** [comment]
You don't need to detach to use google map in expo anyway, there's an implementation coming with expo.
[Docs here](https://docs.expo.io/versions/latest/sdk/map-view.html)

If you havn't detached your app yet, you can't use plugins who require link.
I'm trying some new things, and keep you in touch.

**Comment by Fizbanoide** [comment]
But if you want to show your location on the map you actually need to detach right ? It seems to not be working without detaching it

**Comment by poptocrack** [comment]
Nope, no need to detach, The whole map plugin is working perfectly with Expo.

**Comment by AndresGnu** [comment]
Hi, I had a similar problems and solutions after five hours of testing and errors. I also use expoKit. My problem was when installing React-Native-Firebase. It is a problem related to a version conflict. Expo-Kit-View uses google-play-services version 9.8.0, and in my case, Firebase uses the latest version 11.4.2. You can check this by checking the external libraries in androidstudio.
What has to be done is in the file 'app / build.gradle' exclude the play-services-location package from expoview and add the latest versions. In your case you should only exclude play-services-location. When you do this you must run a 'clean project' and a 'rebuild project'. You can see how the location libraries in version 9.8.0 disappear. The code should look something like this.

dependencies {
.....
  compile('host.exp.exponent:expoview:22.0.0@aar') {
    exclude group: 'com.facebook.android', module: 'facebook-android-sdk'
    exclude group: 'com.facebook.android', module: 'audience-network-sdk'
    exclude group: 'io.nlopez.smartlocation', module: 'library'
    **//Solved Fixed Google GMS**
    exclude group: 'com.google.android.gms', module: 'play-services-maps'
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-location'
    transitive = true;
  }
....
 compile ('com.google.android.gms:play-services-base:11.4.2') {
            force = true;
  }
  compile ('com.google.android.gms:play-services-location:11.4.2') {
            force = true;
  }
  compile ("com.google.android.gms:play-services-maps:11.4.2") {
    force = true;
  }
}

**Comment by radiodario** [comment]
I searched and replaced 9.8.0 on the expokit gradle files and it worked.

**Comment by brentvatne** [comment]
cc @jesseruder

**Comment by sjchmiela** [comment]
This should have been fixed in recent versions of ExpoKit. 🙂
