### ISSUE TITLE
Problems login with Facebook

### ISSUE THREAD

**Issue by georgeMorales** [expo/expo#7990]
Since recently I am having problems with the login with Facebook with different brands of devices.
With Xiaomi, Huawei, Pocophone those I have tried work without problem but with Samsung, two different devices and a Google Pixel I cannot login.
Those are the ones I have tried so far since I have problems ...
Before I have not experienced a similar problem and I logged in with other different devices.
The error I have is similar to when the hash does not match but says: "Error logging in. An error occurred while accessing this application, please try again later."
Expo sdk 37
Expo cli 3.17.11

**Comment by georgeMorales** [comment]
I have already found the solution to the problem, the testers who cannot login do not have the facebook application updated on their devices.

**Comment by byCedric** [comment]
Hi @georgeMorales, thanks for the report and the answer too 😄 Where is the error popping up, on the login page from Facebook or from the response in your Expo app? If it's the Expo app, we might be able to enhance the error message a bit so others can find the issue easier.

**Comment by georgeMorales** [comment]
@byCedric The error appears on the facebook page.

**Comment by byCedric** [comment]
Hmm, that's unfortunate. Are you able to share the code that invokes the Facebook login? If I remember correctly, a certain scope combination could also trigger this random error.

**Comment by georgeMorales** [comment]
The error is not random, because where it appeared the device's facebook application was updated and it worked correctly
`export const socialLogin = () => 
    async (dispatch, getState) => {
        console.log('social login')
        const firestore = firebase.firestore();
        await Facebook.initializeAsync(APP_FACEBOOK);
        //------------------------------------------------------

        try {
           const { type, token } = await Facebook.logInWithReadPermissionsAsync(APP_FACEBOOK, {
                permissions: ['public_profile', 'email' ],
            });
            //console.log(type)
            if (type === 'success') {
                
                // Build Firebase credential with the Facebook access token.
                const credential = firebase.auth.FacebookAuthProvider.credential(token);
                console.log('credential', credential)
                await firebase.auth().signInWithCredential(credential).catch((error) => {
                    console.log(error)
                });
                //console.log('user: ', user) 
                // get user
                const user = firebase.auth().currentUser;
        }
        }
        catch(error) {
        }`

**Comment by JustinRohweller** [comment]
Hello, I have a similar issue, my code is almost exactly the same as yours, and logging in via a modal/web flow (not native app), results in a successful token, but then signInWithCredential fails with the error: "Unsuccessful debug_token response from Facebook: `{"error":{"message":"Error validating application. Cannot get application info due to 
a system error.","type":"OAuthException","code":190,"fbtrace_id":"ArX_GBZgL6QGpx4sgsl3-Ql"}} `     
I have two different applications, with nearly exactly the same code, and the old one works, but the new one doesn't. I was able to login once via the native flow, but the web flow always results in this error.

**Comment by georgeMorales** [comment]
@JustinRohweller The error appears on android and iOS, or just a platform?
It seems that the token returned by facebook is incorrect, do you have the facebook app updated?

**Comment by JustinRohweller** [comment]
@georgeMorales The error is not platform specific, and occurs both on Android and IOS.
The facebook app is updated/is correct. As in`Facebook.logInWithReadPermissionsAsync(APP_FACEBOOK` is correct.
I believe what is happening is that Expo Facebook login returns a token that it believes is ok,
but then when Firebase tries to use it to create a credential: `const credential = firebase.auth.FacebookAuthProvider.credential(token);` Firebase returns the error above, in which case Facebook's servers are saying, actually the token we gave you earlier is bad/ causes OAuthException.
Anyway, I know about this issue as well: https://github.com/expo/expo/issues/6112
So, I plan to just wait until they fix that, the hope being it will fix my issue as well.

**Comment by georgeMorales** [comment]
@JustinRohweller #6112 But this bug is already fixed right? It also happened to me on iOS and it seems that it was fixed in sdk 36. Or at least my partner who is doing the tests on iOS is doing well.
I hope they fix it ... And if I'm not going to have a letter up my sleeve ... In iOS to publish if you have a social login they force you to login with Apple, as a solution would be to login with Apple for iOS and login with gmail for Android.

**Comment by cruzach** [comment]
6112 is iOS only, so if you're seeing an issue that occurs on both platforms, it's _most likely_ a different problem. Without a full bug report, it's hard to try and troubleshoot this, so I recommend closing this and opening a new issue that follows our bug report template

**Comment by JustinRohweller** [comment]
Thanks for the comments guys. Turns out I had used the wrong Facebook secret in Firebase. Feel free to close this.
