### ISSUE TITLE
Mail and Messages apps missing from iOS expo-sharing menu.

### ISSUE THREAD

**Issue by waynebloss** [expo/expo#7991]
### Environment

```sh
Expo CLI 3.18.6 environment info:
    System:
      OS: Linux 4.19 Manjaro Linux
      Shell: 5.0.16 - /bin/bash
    Binaries:
      Node: 13.13.0 - /usr/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.4 - /usr/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
    npmGlobalPackages:
      expo-cli: 3.18.6
```

iOS: 13.4.1

### Steps to Reproduce

Use `expo-sharing` as documented. Code shown below.

### Expected Behavior

Mail and Messages apps should be visible in the share menu in iOS.

### Actual Behavior

Mail and Messages apps are not visible in the share menu in iOS. Every other app that I can share with is visible. This happens for every file type tested so far: PDF and "Office Spreadsheet".

### Reproducible Demo

NOTE: In later tests, I tried adding the `UTI` option of `"com.adobe.pdf"` to the call to `shareAsync` (imported from `expo-sharing`).

```js
    const allowed = await isAvailableAsync();
    if (!allowed) {
      throw new Error("Not allowed");
    }
    let { url, fileName } = data;
    // NOTE: For iOS we had to replace all spaces in filename
    fileName = fileName.replace(/ /g, "_");
    const localFileUrl = await downloadUrl(url, fileName);
    const result = await shareAsync(localFileUrl);
```

Example value for `localFileUrl` being shared, from testing: `file:///var/mobile/Containers/Data/Application/3C04E999-9999-432D-999B-8ADDA0E9999/Documents/ExponentExperienceData/%2540accountname%252Fapplicationname/Xxxxxx_Xxxx_99999999_99999999.pdf`

### Other notes

This might be the answer - https://stackoverflow.com/questions/46531572/uidocumentinteractioncontroller-does-not-open-other-app-in-ios-11/46937932#46937932

> The problem was that I was trying to share a URL to a file inside the app bundle. It seems Apple's apps have permission to access that URL but third-party apps don't. I solved this by first copying the resource to the cache directory and then using that cache directory URL for sharing.

**Comment by byCedric** [comment]
Hi @waynebloss! Thanks for the issue report. If it's related to the answer you provided, have you tried using something like [`FileSystem.getContentUriAsync`](https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemgetcontenturiasyncfileuri) or moving it to the cache with [`FileSystem.cacheDirectory`](https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemcachedirectory)? Maybe you could share the file from URL directly too, that should be accessible by other apps too.

Hope it helps!

**Comment by waynebloss** [comment]
@byCedric Thank you for your response. Neither of those worked for me. If I find the answer, I will post it here.

**Comment by yasirwahid** [comment]
@byCedric  fileSystem is not letting me download local file, the error appearing is the url must be http , https . i have screenshoted my app screen and want to share. in android is working fine but in ios share modal doesnt show apps other than airdrop.
Do you have any idea how to save local uri file to cache directory? or any other idea thanks.

**Comment by zwanzigg** [comment]
Having the same problem, 
using FileSystem.getContentUriAsync or moving it to the cache with FileSystem.cacheDirectory didn't help. Does anybody know the solution?

**Comment by waynebloss** [comment]
Here's the answer - https://forums.expo.io/t/a-possible-way-to-show-a-share-menu-with-expo-without-detaching/9125/4

The code shows using the `Share.share` method from `react-native`:

```js
                 Expo.FileSystem.downloadAsync(
                    urlToYourFile,
                    Expo.FileSystem.documentDirectory + `test.pdf`)
                    .then(({ uri }) => {
                      
                        Share.share({
                            url: uri,
                            title: 'title share',         
                        });
                    })
                    .catch(error => {
                        console.error(error);
                    });
```

So, I tried that in my experimental code - with `import { Share } from "react-native";` and then making a special case for iOS:

```js
  if (Platform.OS === "ios") {
      // Also for iOS, to show the Mail and Contacts sharing options, we need
      // use the bare React-Native facility to do that.
      // const result =
      await Share.share({
        message: fileName,
        title: "Share file",
        url: localFileUrl,
      });
      // console.log("Share.share result: ", result); // prints:
      //    Object {
      //      "action": "sharedAction",
      //      "activityType": "com.apple.UIKit.activity.Mail",
      //    }
    } else {
      // const result =
      await shareAsync(localFileUrl);
      // console.log("shareAsync result: ", result);
    }
```

It works!

**Comment by waynebloss** [comment]
The only problem I have now is that on iOS, `Share.share` never returns if you dismiss the dialog... :(

**Comment by kidroca** [comment]
I have the exact same problem, copying the file to the `FileSystem.cacheDirectory` did not help 
using `FileSystem.getContentUriAsync` just returns the same `file://` path 

```js
console.log('filePath: ', filePath);
const contentUri = await FileSystem.getContentUriAsync(filePath);
console.log('contentUri: ', contentUri);

await Sharing.shareAsync(contentUri, {
  dialogTitle,
  mimeType: 'application/pdf',
  UTI: 'com.adobe.pdf',
});
```

```shell
 filePath:  file:///var/mobile/Containers/Data/Application/DF32C1B1-1A8D-4890-8481-90C43D0CEB2A/Library/Caches/20200511-
MY123-1.pdf
contentUri:  file:///var/mobile/Containers/Data/Application/DF32C1B1-1A8D-4890-8481-90C43D0CEB2A/Library/Caches/2020051
1-MY123-1.pdf
```

This an ejected bare expo project, but the mail or messages option did not appear even before ejecting

**Comment by himrocks33** [comment]
@waynebloss saved me here.  Solution works beautifully.  Seems strange that expo does not allow this functionality on IOS.

**Comment by ansh** [comment]
I just used the `Share` from react-native and this work.

Simply do `import { Share } from "react-native"` and then it should work.
