### ISSUE TITLE
REQUEST_IGNORE_BATTERY_OPTIMIZATIONS Expo Permission

### ISSUE THREAD

**Issue by emersonrf227** [expo/expo#7999]
in expo-permission there would be some way to implement this permission (android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS) I'm doing a radio stream and it happens that in android the music drops due to the network being interrupted in the background so that it normally needs this permission

**Comment by cruzach** [comment]
Hi! This looks like a feature request, so I suggest finding it and upvoting it, or opening a new feature request if there isn't an existing one, on our [canny](https://expo.canny.io/feature-requests)!

**Comment by hallex-abreu** [comment]
am I having the same problem any solution?

**Comment by Javierko** [comment]
Have you found any solution working with Expo packages?
