### ISSUE TITLE
ImagePicker: Return image timestamp/metadata/exif info

### ISSUE THREAD

**Issue by btroia** [expo/expo#80]
Currently, [ImagePicker](https://github.com/exponent/exponent-sdk/blob/master/src/ImagePicker.js) only returns a limited set of information about an image selected by the user (height, width, uri). Would be great to also return other metadata available (timestamp, exif info such as lat/lon, etc.).

This is important for apps that don't upload images to a server for processing (i.e., must extract this information directly on the device). Thanks!

**Comment by terribleben** [comment]
Noted, thanks for the feedback. ImagePicker is due for a major update, so we can consider this.

**Comment by brentvatne** [comment]
Moved to https://github.com/expo/expo/issues/163

**Comment by nikki93** [comment]
EXIF data should be available in SDK 18! 😄

**Comment by nikki93** [comment]
Released!!!! 😮 🎉

**Comment by Patriciadburns1** [comment]
Is exif data available in SDK 32? I am not seeming to reach it. Even though I have it 
    let photo =  await this.camera.takePictureAsync({skipProcessing: true}, {exif: true}, {quality: 1});
