### ISSUE TITLE
You need gallery permissions to use CameraRoll, but can't request them

### ISSUE THREAD

**Issue by Raveler** [expo/expo#800]
If you want to use CameraRoll (because you want to use CameraRoll.saveToCameraRoll, for which there is no alternative in ImagePicker), you can't, because you don't have the right permissions.

The only way to get this to work is to do a call to ImagePicker before, so that the proper permissions are requested. But I don't want to do that; I want to save an image, not pick one or launch the camera!

Asking for Permissions.CAMERA doesn't cut it, it still doesn't work because those permissions don't contain access to the gallery.

So right now, there's really no way to use CameraRoll.saveToCameraRoll without opening a camera first.

**Comment by davepack** [comment]
Hi this is possibly fixed in SDK 22 released yesterday. Can you try creating a snack and see if it works for you now?
