### ISSUE TITLE
Updated to latest Expo - No longer Fast Refreshes

### ISSUE THREAD

**Issue by wontwon** [expo/expo#8000]
### Environment
```
  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.18.6
```

iOS

### Expected Behavior

I just ran expo upgrade to update expo to the latest version. Upon finishing and reloading, expo no longer refreshes on change. 

### Actual Behavior

Once upgrading expo, I expect my app to open with no issue

I'm getting this error message
```
TypeError: hmrClient.send is not a function. (In 'hmrClient.send(JSON.stringify({
        type: 'log-opt-in'
      }))', 'hmrClient.send' is undefined)

enable
    HMRClient.js:70:19
setup
    HMRClient.js:241:6
callFunctionReturnFlushedQueue
    [native code]:0

```

### Reproducible Demo

In console, run expo upgrade. Start app and the error appears

**Comment by brentvatne** [comment]
https://github.com/facebook/react-native/issues/26958

try removing yarn.lock and node_modules and then running yarn again

**Comment by wontwon** [comment]
thanks @brentvatne

**Comment by wontwon** [comment]
@brentvatne just went ahead and removed yarn.lock and node_modules, ran yarn again but still the same issue. Here's the contents of my package.json: 

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "name": "app",
  "dependencies": {
    "@eva-design/eva": "^2.0.0-alpha.1",
    "@expo/vector-icons": "^10.0.0",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.2.4",
    "@react-navigation/drawer": "^5.3.4",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.8",
    "@ui-kitten/components": "^5.0.0-alpha.1",
    "@ui-kitten/eva-icons": "^5.0.0-alpha.1",
    "axios": "^0.19.2",
    "expo": "^37.0.0",
    "expo-av": "~8.1.0",
    "expo-camera": "~8.2.0",
    "expo-font": "~8.1.0",
    "expo-permissions": "~8.1.0",
    "expo-video-thumbnails": "~4.1.0",
    "gravatar": "^1.8.0",
    "lodash": "^4.17.15",
    "mime-types": "^2.1.24",
    "path": "^0.12.7",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-aws3": "^0.0.9",
    "react-native-draggable-flatlist": "^2.3.1",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-raw-bottom-sheet": "^2.1.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-svg": "11.0.1",
    "react-native-ui-lib": "^3.40.0",
    "react-native-web": "^0.11.7",
    "rnal": "^0.2.1",
    "shortid": "^2.2.15",
    "unstated-next": "^1.1.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.1.0",
    "babel-preset-expo": "^8.1.0",
    "eslint": "^6.8.0",
    "eslint-plugin-react": "^7.19.0"
  },
  "private": true
}

```

**Comment by byCedric** [comment]
Hi @wontwon! Thanks for the issue report and your package file. It looks like your dependency `rnal` has an older `react-native` dependency. This may cause some confusion for the metro bundler. I can see [it's fixed in the repository](https://github.com/hayanisaid/rnal/commit/ad414d5d7d0239378413b634795c8e34bad4a1a2), but it's not yet released on NPM. You can ask the maintainer to release that version of rnal, or use the master branch as workaround: 

```
"rnal": "https://github.com/hayanisaid/rnal#master"`
```

<details>
<summary><code>rnal@0.2.1</code> dependencies</summary>
<pre>
"dependencies": {
    "enzyme": "^3.9.0",
    "enzyme-adapter-react-16": "^1.10.0",
    "jest-enzyme": "^7.0.2",
    "react": "16.6.3",
    "react-dom": "^16.8.4",
    "react-native": "0.58.4",
    "styled-components": "^4.1.3"
},
</pre>
</details> 

Hope it helps! 😄

**Comment by limaAniceto** [comment]
Hi there, 
Just for future reference to who finds this.

I was struggling with the same issue, to solve it:
1) If you have `metro-react-native-babel-preset`, set it to at least `0.56`
2) Search in your yarn.lock for `react-native` and check each version, if it doesn't match your `package.json react-native dependency` version, you are gonna get this error

**Comment by wontwon** [comment]
Thank you so much for your help!

**Comment by brentvatne** [comment]
you don't need to install `metro-react-native-babel-preset` in your project - use `babel-preset-expo` instead :) you may run into other issues if you're not using it. if you initialize a new blank project you can check out the config there
