### ISSUE TITLE
Unable to resolve “../../App” from “node_modules/expo/AppEntry.js”

### ISSUE THREAD

**Issue by arshadmhabib** [expo/expo#8012]
![IMG_1102](https://user-images.githubusercontent.com/47796998/80287345-11b3cd00-86ff-11ea-9883-d3e9faa40e8a.PNG)

package.js
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.1.0",
    "@babel/core": "^7.8.6"
  },
  "private": true
}
Can someone help me figure out this issue?

**Comment by brentvatne** [comment]
do you have App.js in your project or did you delete it or move it? it's necessary to have either App.js or index.js in the root of your project.

please share your project on github if you have those and it's showing you this error

**Comment by arshadmhabib** [comment]
Fixed. Thank you!
