### ISSUE TITLE
Unable to resolve "@shoutem/theme" from "node_modules\native-base\dist\src\index.js" 

### ISSUE THREAD

**Issue by arshadmhabib** [expo/expo#8014]
Hello,
I am getting this error. I moved the theme folder into index.js folder. I also tried copying @shoutem/them folder into index.js folder. Still having issue. Any advice would be helpful!
![image](https://user-images.githubusercontent.com/47796998/80290868-89412680-8716-11ea-8a44-3bae919f045e.png)

**Comment by arshadmhabib** [comment]
![image](https://user-images.githubusercontent.com/47796998/80290858-73cbfc80-8716-11ea-96dc-67e8c2add39f.png)

**Comment by brentvatne** [comment]
hi there, you might want to post this issue on native-base. it seems like a bug on their end. i recommend using [react-native-paper](https://callstack.github.io/react-native-paper/) or [react-native-elements](https://react-native-elements.github.io/react-native-elements/) instead
