### ISSUE TITLE
How do you implement the experimental react-native-maps web to NextJS + Expo?

### ISSUE THREAD

**Issue by jackien1** [expo/expo#8018]
### Please note that discussions opened as issues in the core Expo repository will be closed.

  If you have a question about Expo or want to discuss about related aspects, consider posting it
  on our forums at https://forums.expo.io/. 🙂

**Comment by byCedric** [comment]
Hi @jackien1, you can try the solution [from Evan here](https://github.com/expo/expo/issues/6896). Although it's still experimental, it might work.

Hope it helps!
