### ISSUE TITLE
Add jest-expo mocks for vendored native components

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#802]
https://forums.expo.io/t/mapview-causing-error-in-jest-test/3453
https://github.com/airbnb/react-native-maps/issues/829

**Comment by brentvatne** [comment]
@ide - I think you did this?

**Comment by ide** [comment]
Yes, didn't test that it satisfies the RN Maps case though.

**Comment by ide** [comment]
We do this for non-view components now (we include RN-prefixed native modules in the mocks).
