### ISSUE TITLE
Unable to resolve "@react-navigation/native" from "App.js"

### ISSUE THREAD

**Issue by jan-scorl** [expo/expo#8022]
### Environment

 Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.8.0/bin/npm
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.18.6

iOS
### Steps to Reproduce

I installed the managed blank project boilerplate with the CLI. When trying to run the app with `yarn ios`, it throws the error mentioned in the title. It's absurd because App.js does not even require `react-navigation`.

Probably relevant: I first installed the `tabs` boilerplate in the same directory and run it successfully with `yarn ios`. Then I deleted it using `rm -rf`. Afterwards I run the CLI again with the `blank` boilerplate. It still requires `react-navigation`, which is a hint to me that it's somehow still locked into the `tabs` boilerplate project, which used to be in the same directory.

/edit: I just initialised the blank boilerplate in a different directory and its running fine. So it must have to do with the fact that I initialised and run the tabs boilerplate in the same directory before.

### Expected Behavior

No error.

### Actual Behavior

"Unable to resolve "@react-navigation/native" from "App.js"
Failed building JavaScript bundle."

### Reproducible Demo

`expo init app`
`managed blank (no typescript)`
`cd app & yarn ios`

**Comment by byCedric** [comment]
Hi @jan-scorl! Thanks for the issue, and solution 😄 It could be related to `.git` being also initialized, and parts of the old project structure were used. Or maybe even the metro bundler. If you encounter this kind of weird behavior again, you could try clearing the cache. That usually helps:

```
$ rm -rf node_modules yarn.lock package-lock.json
$ yarn (or npm install)
$ expo start --clear
```

Hope it helps for next time 😄
