### ISSUE TITLE
Sticky-immersive androidNavigationBar returning to default system behavior

### ISSUE THREAD

**Issue by gschimiti** [expo/expo#8026]
### Environment

Expo ~37.0.3
Android 10

Target: Android

### Steps to Reproduce

1) configure app.json with androidNavigationBar.visible = "sticky-immersive";

```
app.json:
...
"androidNavigationBar": {
  "visible": "sticky-immersive",
}
...
```

2) Launch app;

3) Take a print screen or switch to another app/android home and come back.

### Expected Behavior

The navbar should be hidden, appearing with a semi-transparent background after sliding from the edges of the screen, without being fixed or colored on the screen.

### Actual Behavior

The navbar works as expected while the app is in use, but loses its behavior and returns to the system default, fixed and colored, when the app is interfered by a print screen or is resumed after being left in the background, for example, after switching to another app or android home screen and coming back.

**Comment by byCedric** [comment]
Hi @gschimiti! Thanks for the report! I think this might be related to #7663, could you try running `expo upgrade` and see if the issue still persists? Hope it helps 😄

**Comment by gschimiti** [comment]
@byCedric, I'm already using the latest version of expo. I built the .apk to test and realized that the problem does not occur. Testing through the Expo app for Android, without building the .apk, the problem occurs. It looks like the app uses only the major version, with SDK 37.0.0 and not minor versions like 37.0.8. Am I right?

**Comment by cruzach** [comment]
Correct @gschimiti , the builders have been updated with this fix (meaning standalone apks and aabs will have the right behavior) but the Expo Client available in the play store does not have this fix yet, and will need to wait until the next time we release an update

**Comment by gschimiti** [comment]
Hello, I think I found another strange behavior involving the androidNavigationBar. When using the keyboard, after clicking to hide it, the navigation bar remains on the screen. Should I open an issue or is there something already notified?
