### ISSUE TITLE
DocumentPicker isn't allowing all file types when browsing iCloud Drive locations

### ISSUE THREAD

**Issue by bkbooth** [expo/expo#8029]
We've got an Expo app that we're currently preparing for release and we use Expo `DocumentPicker` during the onboarding process. We've discovered that when browsing iCloud Drive locations only a subset of files/types are selectable. As far as I can tell we've setup everything correctly according to the [Configuration](https://docs.expo.io/versions/latest/sdk/document-picker/#configuration).

The `.keystore` files we're using (and some other file types eg. `.sketch`) our greyed out and unselectable, but only on iCloud Drive.

- The file we're trying to select is a JSON document using `.keystore` extension.
- Everything works correctly on Android (whether using phone local locations or remote locations)
- Everything works correctly on iPhone when picking local files or from other remote locations (eg. Google Drive)
- We can pick other files from iCloud Drive (eg. images or PDF's), they come into our app and the app has some logic to report that they're invalid files.

Am I missing some required config? Is this a bug? Any help is much appreciated

**Comment by bkbooth** [comment]
Ok, I finally found the solution to this. I needed to declare the document types that our app can handle.

I really think this should be made clearer in the `DocumentPicker` docs. I went around in circles for a long time, and even when I thought I had it figured out, there were no concrete examples I could find anywhere of declaring document types in `app.json`. I basically had to map some iOS `Info.plist` XML examples into the `app.json` format.

It's clearly not impossible to work it out, but it took a long time for me to work out and it's definitely not friendly to newcomers.

For what it's worth if anyone else stumbles across this, these are roughly what I ended up with in my `app.json` (You can search any of the keys to find the reference in the Apple docs to customise to your needs):

```json
{
  "expo": {
    "ios": {
      "infoPlist": {
        "LSSupportsOpeningDocumentsInPlace": false,
        "CFBundleDocumentTypes": [
          {
            "CFBundleTypeName": "My Document",
            "CFBundleTypeRole": "None",
            "LSHandlerRank": "None",
            "LSItemContentTypes": [
              "com.MyOrg.MyApp.MyFiletype",
              "public.data"
            ]
          }
        ],
        "UTExportedTypeDeclarations": [
          {
            "UTTypeConformsTo": ["public.data"],
            "UTTypeDescription": "My File Type",
            "UTTypeIdentifier": "com.MyOrg.MyApp.MyFileType",
            "UTTypeTagSpecification": {
              "public.filename-extension": "myfile",
              "public.mime-type": "application/json"
            }
          }
        ]
      }
    }
  }
}
```

**Comment by cruzach** [comment]
hey @bkbooth , sorry this gave you so much trouble. I agree we should add this to the docs- if you want to open a PR, we'd love a contribution, but if not I can make sure I get around to it

**Comment by RCNNT-Industries** [comment]
Does one need to build/deploy before these work, or did it work instantly in the Expo client?
Did it work with network sources (Dropbox or iCloud), or just on the device itself?

**Comment by bkbooth** [comment]
@RCNNT-Industries I was able to pick any files from on my device or other network sources (eg. Dropbox, Google Drive). I was specifically having the problem of greyed out files on iCloud Drive, and I had to get my app up on App Store Connect (not published) to get the certs, app ID and iCloud Container setup before this config ☝️ worked.

**Comment by bkbooth** [comment]
Thanks @cruzach, I'll see if I can find some time to make a PR for the docs.

Do you know if there's a way with `CFBundleDocumentTypes` and/or `UTExportedTypeDeclarations` (or any other Info.plist properties) to be able to choose _any_ file on iCloud Drive? We want to interop with another extension that exports the same JSON structure, but they use a strange filename by default with no extension and I've tried a bunch of different UTI declarations but I've not been able to make these other files pickable yet.

**Comment by cruzach** [comment]
Not sure 🙁 would need to take a look at Apple's documentation

**Comment by bkbooth** [comment]
I ended up solving this, but I actually had to move away from the Expo `DocumentPicker` and am now using [react-native-document-picker](https://github.com/Elyx0/react-native-document-picker) since we ejected to the bare workflow recently.

I might not be 100% correct with all of this, but it looks like when you set a type of `*/*` which is the default for both Expo's `DocumentPicker` and `react-native-document-picker`, this maps to the `public.content` [UTI](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html) on iOS. This seems to exclude a bunch of _unknown_ file types, which is why defining `UTExportedTypeDeclarations` worked for getting some file types to show. Ideally we'd like to just show all files, so using `react-native-document-picker` I was able to set the type to `public.item` on iOS (the base UTI for all types) and keep the `*/*` mime type for Android.

I couldn't find any way to achieve this in Expo's `DocumentPicker` or maybe I missed it. So another suggestion would be to allow fine-grained type's per-platform, to explicitly set a list of UTI's on iOS.

**Comment by trydalch** [comment]
Do any of you have a solution for selecting a folder using the document picker? I want to allow users to select a save destination inside their icloud drive folder. I've been banging my head reading about package after package. Yet, I can't imagine I'm the only one wanting to do this and there's got to be a good way.
