### ISSUE TITLE
[expo-notifications] query notifications in Notification Tray

### ISSUE THREAD

**Issue by arberK** [expo/expo#8031]
I there a way to listen to a notification, when the app is in the background, but the user did not respond to it. I want to respond to it when the user then starts the application from app icon (i.e. not through notification) 

Same as addNotificationResponseRecievedListener but when the user does not interact with notification. 
Maybe some type of query for all received notifications in the notification tray.

**Comment by sjchmiela** [comment]
Could you see if `Notifications.getPresentedNotificationsAsync()` would solve your problem? Sorry it isn't documented, I must have forgotten about it — will fix soon.

**Comment by arberK** [comment]
> Could you see if `Notifications.getPresentedNotificationsAsync()` would solve your problem? Sorry it isn't documented, I must have forgotten about it — will fix soon.

It's exactly what I was looking for. Had to implement a workaround yesterday, but it will still help me further. Thank you  :)
Please document for others to see.
