### ISSUE TITLE
[expo-notifications] custom sound throws exception

### ISSUE THREAD

**Issue by arberK** [expo/expo#8032]
When trying to use a custom sound. (e.g. "tone.aiff") , the Promise Rejection gets thrown
Error: Failed to schedule notification. Value under key "sound" is of Class NSTaggedPointerString, while NSNumber was expected.

The documentation, however, states that NotificationContentInput can take a boolean or a string:

NotificationContentInput
 {
...
  **sound?: boolean | string;**
...}

**Comment by sjchmiela** [comment]
Good catch, I'll fix it in a second!

**Comment by arberK** [comment]
@sjchmiela thank you for fixing this and for the fix in android. When should we expect for the #8036 to get merged? Could you publish a rc in the meantime? I'm waiting to integrate it into my project, hence I will be testing it immediately

**Comment by sjchmiela** [comment]
Published 0.1.3 containing the fix. Haven't had time to write a proper guide on how to do it yet, so let me know if you have trouble customizing the sounds. You can also look at the `bare-expo` project in which I set up the `notification.wav` custom sound. The gist would be to:

1. create the sound file in WAV format (it's supported by both platforms)
2. drag and drop the file into Xcode project: 
  ![Zrzut ekranu 2020-04-30 o 15 31 36](https://user-images.githubusercontent.com/1151041/80716218-af403f80-8af7-11ea-8aab-ec5e2da7a48a.png)
  I may or may not (I don't remember) had to add it to the target in the _Target Membership_ tab:
  ![Zrzut ekranu 2020-04-30 o 15 32 15](https://user-images.githubusercontent.com/1151041/80716383-db5bc080-8af7-11ea-8fa1-64f70351e697.png)
3. add the WAV file to `android/app/src/main/res/raw/` (create the directory if it's not there)
4. rebuild the applications
5. from now on you should be able to use the filename in `sound` property of the notification (eg. `notification.wav`) and the notification should make the custom sound (provided the handler allows it and the phone is not in silent mode). 🙂

**Comment by arberK** [comment]
I've tested it and I can confirm ist working very well. 👍 

The only problem I now have is the getPresentedNotificationsAsync() in android. It always returns 0. iOS is good. 
I'll open a separate issue for this.

**Comment by nicwhitts** [comment]
> Published 0.1.3 containing the fix. Haven't had time to write a proper guide on how to do it yet, so let me know if you have trouble customizing the sounds. You can also look at the `bare-expo` project in which I set up the `notification.wav` custom sound. The gist would be to:
> 
> 1. create the sound file in WAV format (it's supported by both platforms)
> 2. drag and drop the file into Xcode project:
>    ![Zrzut ekranu 2020-04-30 o 15 31 36](https://user-images.githubusercontent.com/1151041/80716218-af403f80-8af7-11ea-8aab-ec5e2da7a48a.png)
>    I may or may not (I don't remember) had to add it to the target in the _Target Membership_ tab:
>    ![Zrzut ekranu 2020-04-30 o 15 32 15](https://user-images.githubusercontent.com/1151041/80716383-db5bc080-8af7-11ea-8fa1-64f70351e697.png)
> 3. add the WAV file to `android/app/src/main/res/raw/` (create the directory if it's not there)
> 4. rebuild the applications
> 5. from now on you should be able to use the filename in `sound` property of the notification (eg. `notification.wav`) and the notification should make the custom sound (provided the handler allows it and the phone is not in silent mode). 🙂

I can't seem to get this to work after following the steps.

Also, is it possible to play a custom sound from calling the api with the custom string? `https://exp.host/--/api/v2/push/send`

**Comment by veloware** [comment]
Can I just clarify, is custom sounds only available in the bare-workflow?  Thanks!

**Comment by sjchmiela** [comment]
That is, unfortunately, still correct as of fourth quarter of 2020. We are not actively working on adding this feature to managed workflow, but we have this on our todo list!

**Comment by ankitranka1** [comment]
can this be mentioned in the documentation, it doesn't say that custom sound works for bare workflow only - https://docs.expo.io/versions/latest/sdk/notifications/#setting-custom-notification-sounds-on-android
