### ISSUE TITLE
expo-payments-stripe on fresh repository yields stripemodule.init undefined error

### ISSUE THREAD

**Issue by bkniffler** [expo/expo#8034]
### Environment
Build for iOS Simulator

Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.19.2
### Steps to Reproduce
Bootstrap a new (typescript) expo project with expo init, add expo-payments-stripe and do something like: 
```
 await stripe.setOptionsAsync({
        publishableKey: '...',
        merchantId: 'merchant....'
      });

      return stripe
        .paymentRequestWithApplePayAsync(
          [
            {
              label: text,
              amount: amount.toFixed(2),
            },
          ],
          {
            currencyCode: 'GBP',
            countryCode: 'GB',
            shippingMethods: [],
          }
        )
        .catch((err) => {});
```

### Reproducible Demo
https://github.com/bkniffler/expo-stripe-bug

### Expected Behavior
Should work 

### Actual Behavior
Error message
![Simulator Screen Shot - iPhone 11 - 2020-04-27 at 15 36 32](https://user-images.githubusercontent.com/4349324/80378405-e7981180-889c-11ea-9e0f-8c9a0c8fb2d6.png)

### Reproducible Demo
https://github.com/bkniffler/expo-stripe-bug

**Comment by cruzach** [comment]
As the [docs](https://docs.expo.io/versions/latest/sdk/payments/) state, `expo-payments-stripe` is only available in the bare workflow, so I'm going to close this issue. If you still have issues integrating it into a bare expo project, please open a new issue

**Comment by StarNeit** [comment]
@cruzach , is expo-payments-stripe available in the managed workflow for Android?
https://github.com/expo/expo/issues/12028
`expo-payments-stripe` works well in dev environment, but it crashes after build APK.
How can we fix that in managed workflow(android)?
