### ISSUE TITLE
sensors latency in IOS

### ISSUE THREAD

**Issue by royhershkovitz** [expo/expo#8041]
### Environment

Expo CLI 3.19.2 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^36.0.2 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: 0.61.4 => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10

IOS 12.3, iPhone 11 pro. (and some other ios I have checked.)

### Steps to Reproduce
According to documentation:
https://docs.expo.io/versions/latest/sdk/accelerometer/#accelerometersetupdateintervalintervalms
To get the fastest events rate per minute you need to put small ms number like that
import { Accelerometer } from 'expo-sensors';
Accelerometer.setUpdateInterval(ms_sensor_interval);

The problem is the number of events that can be received from the app.
It is performing well on Android, but on IOS I can not get more than 10 HZ (i.e. 10 events per second)
It is also present on Gyroscope and Magnetometer

### Expected Behavior

I would expect at least a 100HZ refresh rate on any IOS's sensor as Apple claims it is possible.
Please see it here: https://developer.apple.com/documentation/coremotion/getting_raw_gyroscope_events
"The maximum frequency at which you can request updates is hardware-dependent but is usually at least 100 Hz."

### Actual Behavior

Can not get more than 10HZ refresh rate on  Gyroscope, Magnetometer, and Accelerometer

### Reproducible Demo
Since sensors are not available on the snack (ios) you cannot see it happen, but you can try it on a real device. The code is edited from my repository. It does work on android and shows around 100 HZ which is good.
https://snack.expo.io/@royhersh/sensors-demo

I ran the example on my device and got 10HZ.

This is very important to many applications that rely on a fast response for better user experience.

**Comment by royhershkovitz** [comment]
I am a developer.
If someone will help me with a quick introduction, maybe I will be able to help and do a pull request for you.

**Comment by cruzach** [comment]
hi @royhershkovitz , you can find the iOS source of the sensors module [here](https://github.com/expo/expo/tree/master/packages/expo-sensors/ios)

how are you judging the hz from your example snack?

**Comment by royhershkovitz** [comment]
Hey, It is the amount of sensorsEvents/TimeOfCollectingInSeconds

**Comment by royhershkovitz** [comment]
https://github.com/expo/expo/blob/master/packages/expo-sensors/ios/EXSensors/EXSensorsManager.m#L73
The default value for accelerometer, gyroscope, and magnetometer is 0.1f which is counted in seconds. it is 10HZ. I wonder why it did not update to 0.001 later

**Comment by royhershkovitz** [comment]
@EvanBacon what do you think? Can you review the snack on your device? Is the problem exist?

**Comment by HadiModarres** [comment]
@royhershkovitz I can still see this issue, I can get 60hz fluid motion on Android but setUpdateInterval doesn't seem to have any effect on iOS, did you ever find a workaround to this?
