### ISSUE TITLE
Error: Warning: Failed prop type: Invalid prop `source` supplied to `Image`

### ISSUE THREAD

**Issue by Dschinemann** [expo/expo#8049]
Using the example of using the expo-image-picker, I was unable to render the image, always returning an error.
The first time I call the function and select the photo it is returning me null in console.log. I thank you for your help.
[code.txt](https://github.com/expo/expo/files/4542796/code.txt)
[error.txt](https://github.com/expo/expo/files/4542797/error.txt)

**Comment by brentvatne** [comment]
you need to pass a valid uri to the source, in this case your image will be null initially. so you can do something like this:

```jsx
{ image === null ? <View /> : <Image style={{width:"100%", height:300, borderRadius:20}} source={{uri:image}} />
```

**Comment by Dschinemann** [comment]
thanks for the feedback ... I've tried it in many ways, I tried it that way too and the error persists. I understand that I am passing a null value, but I am not able to develop this function.

**Comment by Dschinemann** [comment]
I did it, I checked the code again, I realized that I was passing the state value in the wrong way ... thanks.
