### ISSUE TITLE
Video component silently fails when using loadAsync

### ISSUE THREAD

**Issue by alejomendoza** [expo/expo#805]
The first time I try to load the video stream with `loadAsync` from the component `ref`, it silently fails. After I call this function the second time, it works. 
```
async loadAsync(streamUrl: string) {
  return await this.playbackInstance.loadAsync({ uri: streamUrl }, { shouldPlay: true, positionMillis: 0 });
}
```

**Comment by alejomendoza** [comment]
Found out that using the property `usePoster={true}` will make this bug appear. After I take it out, it is gone try it out on this snack:  https://snack.expo.io/HJY7zoBTb

**Comment by sjchmiela** [comment]
Nice catch!

The problem is that when using poster, when the video loads, the internal tree of the `Video` component is being changed and the native video component is being recreated (the new instance doesn't know about the video you said to load).

Fix is on its way!
