### ISSUE TITLE
Can't update to ExpoKit 2.0.1 on iOS

### ISSUE THREAD

**Issue by vlad-zhukov** [expo/expo#807]
I've got a detached Expo app. Following the ['Upgrading ExpoKit'](https://docs.expo.io/versions/latest/guides/expokit.html#upgrading-expokit) I've updated the Podfile, ran `pod install` and got the following output:
```
Analyzing dependencies
Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.0.1`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] The name of the given podspec `yoga` doesn't match the expected one `Yoga`
```
Am I missing something? Do I need to update something else manually?

**Comment by ide** [comment]
Try renaming "Yoga" to "yoga" in your Podfile. This is something we'll cover in the release notes for SDK 22.

**Comment by vlad-zhukov** [comment]
Thanks, that helped. I managed to build an app but get a runtime exception right after loading it. I've no idea how to read the stack, the error message is `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OS_dispatch_data data]: unrecognized selector sent to instance 0x7fb06a88f200'`

**Comment by ide** [comment]
OK thanks, that error is helpful, I have an idea of where it's coming from. We're still in the process of testing SDK 22 so for now I'd recommend holding off from upgrading ExpoKit.

**Comment by ide** [comment]
@vlad-zhukov one more question - what sdkVersion do you have listed in your app.json file?

@terribleben this looks related to RCTSource / NSData in one of the bridge delegate methods. Not sure why the mismatch is happening but it looks like we're thinking the SDK version is < 22 in the bridge delegate but actually using an SDK 22 bridge.

**Comment by vlad-zhukov** [comment]
@ide  It's 22.0.0

**Comment by terribleben** [comment]
Did you follow all the instructions [here](https://docs.expo.io/versions/latest/guides/expokit.html#ios-1)?

**Comment by vlad-zhukov** [comment]
Alright, I've tried to update again to 2.0.2 now from 1.20.5. Followed the instructions, also updated `iosExpoViewUrl` in `app.json` from [here](https://expo.io/--/api/v2/versions) (not sure it's for and if it makes difference) and it all worked! Thanks!
