### ISSUE TITLE
NetInfo is not working with expo web

### ISSUE THREAD

**Issue by tickietackie** [expo/expo#8070]
### Environment

Expo CLI 3.19.2 environment info:
    System:
      OS: Windows 10 10.0.17763
    Binaries:
      Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4

### Steps to Reproduce

- create a fresh project with expo init
- expo install '@react-native-community/netinfo'
- copy in the NetInfo example at App.js
- start expo for web

### Expected Behavior

- project starts without error

### Actual Behavior

TypeError: _react_native_community_netinfo__WEBPACK_IMPORTED_MODULE_4__.useNetInfo is not a function
App
.../NetInfoTest/myNewProject/App.js:6
  3 | import * as NetInfo from '@react-native-community/netinfo';
  4 | 
  5 | export default function App() {
> 6 |   const networkState = NetInfo.useNetInfo();
  7 |   const stateInfo = networkState.isConnected
  8 |     ? 'connected to'
  9 |     : 'disconnected from'

### Reproducible Demo

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import * as NetInfo from '@react-native-community/netinfo';

export default function App() {
  const networkState = NetInfo.useNetInfo();
  const stateInfo = networkState.isConnected
    ? 'connected to'
    : 'disconnected from'

  /*NetInfo.fetch().then(state => {
    console.log('Connection type', state.type);
    console.log('Is connected?', state.isConnected);
  });*/

  return (
    <View style={styles.container}>
      <Text>You are <Text style={styles.state}>{stateInfo}</Text> the internet</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  state: {
    fontWeight: 'bold'
  },
});

```

The same code is working fine for iOS and Android.

**Comment by byCedric** [comment]
Hi @tickietackie! Thanks for the report! This is a hard one and a "relic" from React Native Web 0.11.x. The Netinfo community library has evolved since the extraction from React Native. That means more functionality was added, just like the `useNetinfo` hook. At the moment [Netinfo is aliased to use the internal](https://github.com/expo/expo-cli/blob/c2ca5ad4ad797a156b5901923714004d2bf328a2/packages/webpack-config/src/env/alias.ts#L23-L25), and now outdated Netinfo version. [Here is a discussion about why this was linked to the older React Native Netinfo.](https://github.com/react-native-community/react-native-netinfo/pull/47)

We will probably address this in #8064. If you absolutely need this in web, you can try adding a polyfill like the code below. I'll keep this issue open until we resolved this!

```
import * as CommunityNetInfo from '@react-native-community/netinfo';
import { useEffect, useState, useCallback } from 'react';
import { Platform } from 'react-native';
import NetInfo from 'react-native-web/dist/exports/NetInfo';

function useOldNetInfo() {
  const [netInfo, setNetInfo] = useState<NetInfo.NetInfoState>({});
  const [isConnected, setIsConnected] = useState<boolean>(true);

  const onInfo = useCallback((data) => {
    setNetInfo({ ...data, isConnected });
  }, [isConnected]);

  useEffect(() => {
    NetInfo.getConnectionInfo().then(onInfo);
    NetInfo.isConnected.fetch().then(setIsConnected);
    return NetInfo.addEventListener('connectionChange', onInfo).remove;
  }, [onInfo]);

  return netInfo;
}

export default Platform.select({
  web: useOldNetInfo,
  ios: CommunityNetInfo.useNetInfo,
  android: CommunityNetInfo.useNetInfo,
});
```

**Comment by EvanBacon** [comment]
It is not great that the extracted package changed its API before including web support, we don't have any control over this particular issue unfortunately. I would recommend opening an issue on https://github.com/react-native-community/react-native-netinfo asking for web support in the older API to help people with migration.
