### ISSUE TITLE
Updating the selection props of a TextInput using onSelectionChange causes the caret to jump around

### ISSUE THREAD

**Issue by divonelnc** [expo/expo#8071]
### Environment

    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.15.3 - E:\nodejs\node.EXE
      Yarn: 1.22.0 - E:\Yarn\bin\yarn.CMD
      npm: 6.14.4 - E:\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 

target: Android

### Steps to Reproduce

Use the code from the snack: https://snack.expo.io/rJJfbOGmX

Or generally, create a TextInput where you set the selection props and update it in the onSelectionChange callback.

### Expected Behavior

The caret should move in the same way as if I was not using the selection props.

### Actual Behavior

The caret jumps around. Worse, if you do not set the value props, it crashes with the error: `setSpan(1 ... 1) ends beyond length 0`

Example:
![caret jumping](https://user-images.githubusercontent.com/1695307/80584204-a117f380-8a11-11ea-980a-978ebc52e805.gif)

### Reproducible Demo

https://snack.expo.io/rJJfbOGmX

**Comment by byCedric** [comment]
Hi @divonelnc! Thanks for your report and example. 😄 Unfortunately, I can't reproduce this error on a snack or my phone. The only reason for this behavior that I could think of is the update loop within your component. Let me try to explain 😄 

Under the hood [React's `setState` does not immediately process the new state](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous). This means that events like `onChangeText` or `onSelectionChange` may be called asynchronously without the TextInput component being rendered. This may cause some issues like the one you describe, like the actual text being updated 2x but the selection is still 1 update behind.

I'm not sure what you want to achieve, could you maybe provide some context for that? If you remove the `selection` property, you can still track where the caret is or what the user selected.

Hope it helps!

**Comment by divonelnc** [comment]
Hello, @byCedric . I do not have anything more in my update loop. My code is exactly the same as the snack I sent over. I am not rendering anything else or having any other logic happening.

My end goal is to be able to move the caret manually from outside the component (I am doing an autocomplete feature). This is the minimal code at which I am seeing an issue with.

I have a 100% crash with the following component:

```
function TestComp() {
	const [selection, setselection] = React.useState();

	return (
		<View style={{ justifyContent: "center", flex: 1 }}>
			<TextInput
				style={{ backgroundColor: "red" }}
				selection={selection}
				multiline={true}
				onSelectionChange={(event) => {
					const { nativeEvent: { selection: { start, end }, }, } = event;
					setselection({ start, end });
				}}
			/>
		</View>
	);
}
```

**Comment by divonelnc** [comment]
As the gif I put in the example is with a different code than from the slack, here is a gif showing the issue with an copy-paste of the slack component:
```
class TestInput extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			selection: { start: 0, end: 0 },
			value: "hello world",
		};
	}

	onSelectionChange = ({ nativeEvent: { selection, text } }) => {
		this.setState({ selection });
	};

	onChangeText = (value) => {
		this.setState({ value });
	};

	render() {
		return (
			<TextInput
				onChangeText={this.onChangeText}
				onSelectionChange={this.onSelectionChange}
				selection={this.state.selection}
				style={[{ borderColor: "#F00", borderWidth: 1, marginTop: 100 }]}
				value={this.state.value}
			/>
		);
	}
}
```
![caret jumping 2](https://user-images.githubusercontent.com/1695307/80593263-2b1b8880-8a21-11ea-959a-7cf983f22795.gif)

I also did an expo upgrade in the meantime to make sure I have the latest version:

  Expo CLI 3.19.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.15.3 - E:\nodejs\node.EXE
      Yarn: 1.22.0 - E:\Yarn\bin\yarn.CMD
      npm: 6.14.4 - E:\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.8 => 37.0.8
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4

**Comment by byCedric** [comment]
Thanks for the context! Well, I did some digging and it seems that controlling both the `value` and `selection` results in multiple renders on each keypress. That may be the cause of the "incorrect" selection information, not the batched state changes. ([See issue here](https://github.com/facebook/react-native/issues/28194)).

One thing that I could think of is to work around the double render issue by using refs. [Something like this maybe](https://snack.expo.io/@bycedric/e40062)? ([Based on this SO thread](https://stackoverflow.com/questions/33686748/react-native-setting-textinput-cursor-position))

**Comment by divonelnc** [comment]
Thanks for your quick answer!

I am now wondering if it doesn't have something to do with using the expo-cli? When I run the snack you sent directly from the expo app, it works fine. However, when I copy-paste the code and run it from expo-cli, it has the same issue. My whole app using your code is this :

```
import * as React from "react";
import { TextInput } from "react-native";


class TestComp extends React.Component {
	textInput = React.createRef();

	constructor(props) {
	  super(props);
	  this.state = {
		value: "hello world"
	  };
	}
  
	onSelectionChange = ({ nativeEvent: { selection } }) => {
	  if (this.textInput.current) {
		console.log('setting selection', selection);
		this.textInput.current.setNativeProps({ selection });
	  }
	};
  
	onChangeText = value => {
	  console.log("change text to", value);
	  this.setState({ value });
	};
  
	render() {
	  return (
		<TextInput
		  ref={this.textInput}
		  onChangeText={this.onChangeText}
		  onSelectionChange={this.onSelectionChange}
		  style={[{ borderColor: "#F00", borderWidth: 1, marginTop: 100 }]}
		  value={this.state.value}
		/>
	  );
	}
}

export default function App() {
	return <TestComp />;
}
```
