### ISSUE TITLE
Cannot read property 'speak' of undefined

### ISSUE THREAD

**Issue by berat** [expo/expo#8077]
### Environment

Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2

### Expected Behavior

I want to use this plugin because I want to listen to simple English words aloud.

### Actual Behavior

I wanted to use expo-speech as the sound library. I use @unimodules / core and expo-speech for this. When I try to use the plugin, I get an error saying 'Cannot read property' speak 'of undefined`.
The code I wrote is just this. Speech.speak('hello')

**Comment by cruzach** [comment]
You need to install the package and import it into the file you're using. As the error message states, "Speech" is undefined

Try. the example in the docs- https://docs.expo.io/versions/latest/sdk/speech/

**Comment by berat** [comment]
For example, when I make console.log (Speech.speak), I get on the screen that this is a function. I have already downloaded the code and included it in the project.
