### ISSUE TITLE
[expo-image-picker] [iOS] Image quality degraded after crop with `allowsEditing: true`

### ISSUE THREAD

**Issue by sstur** [expo/expo#8079]
## 🐛 Bug Report

If the user selects a high resolution image, say 3000x2000px, and then crops it to square using the built-in editor (invoked with `allowsEditing` option), then the resulting image is dramatically reduced in quality (usually around 820x820px) instead of the expected 2000x2000px.

This appears to be a consequence of using iOS's built-in `UIImagePickerController`, or specifically using the `UIImagePickerControllerEditedImage` from `UIImagePickerController.InfoKey` which appears to return a lower-resolution version of the cropped image.

See [relevant Expo code here](https://github.com/expo/expo/blob/master/packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m#L224-L228).

Suggested fix:
Instead of getting the `UIImagePickerControllerEditedImage` we should get `UIImagePickerControllerOriginalImage` and `UIImagePickerControllerCropRect` and perform a resolution-preserving crop operation.

The other quirk I noticed is that the `1:1` aspect ratio is not always preserved. It's often off by a few pixels. If we are handling the CropRect ourself, we can control for this. Thoughts?

### Environment

  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - node_modules/.bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.19.2

Target: iOS

### Steps to Reproduce

1. Using `allowsEditing: false`, open the Simulator, pick one of the sample images, log its dimensions.
2. Using `allowsEditing: true`, do the same, but this time crop to square and log it's dimensions.
3. Notice that the image has been downscaled.

### Expected Behavior

The cropping should not downsample the image, if just cropping.

### Actual Behavior

The image has been downsampled.

### Reproducible Demo

https://snack.expo.io/@sstur/image-picker-demo

**Comment by sstur** [comment]
Thanks for triaging @byCedric. Let me know if there's anything more I can do to help make this issue more clear or actionable. Cheers!

**Comment by byCedric** [comment]
Hi @sstur! Sorry, I was trying some things out 😄 I think I found your issue. The main issue that causes the "attempt to write a readonly database" is the non-closed database references. You open the database with `const db = ...`, but never close it. This causes the process to keep it open and may cause issues like this.

Now to fix that, we need to solve another issue. If you run `db.transaction` and `db._db.close` right after each other, the closing isn't waiting for the transaction to finish. I wrapped them into a Promise to use `await` on it.

I [created a new snack based on yours](https://snack.expo.io/@bycedric/sqlite-file-replace-error), it works locally but seems to have some issues in Snack. Could you try running it locally?

Hope it helps!

**Comment by byCedric** [comment]
I'm sorry, I mixed up an issue. Let me get back to you asap!

**Comment by byCedric** [comment]
Hi @sstur, you are right! Thanks for the repo, can confirm this is happening on iOS only. But, I'm not sure about the fix. (cc @tsapeta)
