### ISSUE TITLE
[expo-updates]Override NODE_BINARY to 'node' without checking if it's already set

### ISSUE THREAD

**Issue by mori-azapa** [expo/expo#8081]
### Environment
  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/.nodebrew/current/bin/node
      Yarn: 1.21.1 - ~/.nodebrew/current/bin/yarn
      npm: 6.13.4 - ~/.nodebrew/current/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
    npmGlobalPackages:
      expo-cli: 3.19.2

Target is iOS after eject.

### Steps to Reproduce
I think it's reproducing only `nodebrew` or `nvm` environment. And also it happened after eject.

When I run ejected Expo project on iOS real device after import some external package like 'react-native-ble-plx', Xcode shows up below error.

```
Can't find the 'node' binary to build the React Native bundle.  If you have a non-standard Node.js installation, select your project in Xcode, find  'Build Phases' - 'Bundle React Native code and images' and change NODE_BINARY to an  absolute path to your node executable. You can find it by invoking 'which node' in the terminal
```

So I changed line Xcode's build phase settings, "Bundle Expo Assets" shell to like this. 

```
export NODE_BINARY=/Users/{MyUserName}/.nodebrew/current/bin/node
../node_modules/expo-updates/bundle-expo-assets.sh
```

### Expected Behavior
Xcode build success.

### Actual Behavior
Still occur same error.

### How to fix
To prevent overriding NODE_BINARY variable to specify node executable, on `packages/expo-updates/bundle-expo-assets.sh`, change something like this.

```
6c6,8
<   export NODE_BINARY=node
---
>   if [ -z "$NODE_BINARY" ]; then
>     export NODE_BINARY=node
>   fi
```

**Comment by byCedric** [comment]
Hi @mori-azapa! Thanks for the report! Just to confirm, does this work for you when running your app in production mode? (not the debug config) If so, could you make a PR for this? I think your "how to fix" is pretty good already 😄

**Comment by mori-azapa** [comment]
@byCedric Thank you for your response. I did development phase and production phase (Creating iOS executable using "Archive") with no problem. Created PR. #8148

**Comment by mori-azapa** [comment]
PR #8148 is merged. Thanks!
