### ISSUE TITLE
[docs] Changing SDK version should stay on route when possible

### ISSUE THREAD

**Issue by IjzerenHein** [expo/expo#8086]
Changing the SDK version in the docs will always navigate back to the root of the docs.
When possible, it should stay on the same route.

# Steps to reproduce

- Open https://docs.expo.io/versions/v37.0.0/sdk/appearance/ in the browser
- Change the SDK to 36 using the top-left combo-box
- Route is now at https://docs.expo.io/versions/v36.0.0/

**Comment by byCedric** [comment]
Redirecting back to root could be the fallback behavior if a newer API doesn't exists in the older version. (or the other way around)
