### ISSUE TITLE
Alert crashing the client if passing an object to one of its first 2 arguments

### ISSUE THREAD

**Issue by tomadimitrie** [expo/expo#8087]
### Environment

```
Expo CLI 3.20.0 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - /usr/local/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.0
```

Target: iOS

### Steps to Reproduce

When using Alert with an object as the first or second parameter, the client crashes without a stack trace

### Expected Behavior

It should show a redbox or convert the object to a string

### Actual Behavior

It crashes the client

### Reproducible Demo

```tsx
// App.tsx
import React from "react";
import { View, Alert } from "react-native";

export default function App() {
  React.useEffect(() => {
    Alert.alert({} as any, "AAAA");
  }, []);
  return <View/>;
}
```

**Comment by lukmccall** [comment]
Hi @tomadimitrie, why do you assume that you can pass an object as a parameter to alert function? I don't think that auto converting to a string it's expected behavior here. 

Moreover, I've tested it and in my case, it didn't crash. It's produced an error which you can see below.
![image](https://user-images.githubusercontent.com/9578601/80702428-582f7000-8ae1-11ea-8461-8b3d2dd64c34.png)

**Comment by tomadimitrie** [comment]
Hi @lukmccall. The empty object was just a minimal example. I had a case yesterday where I passed by mistake an `Error` instead of converting it to a string and the client crashes. I am not getting the error you have attached.

**Comment by lukmccall** [comment]
That's weird. Does it happen on the real device? Also, check if your metro bundler is running in development mode (run `expo start` and press <kbd>?</kbd>. You will see your current mode).

**Comment by tomadimitrie** [comment]
@lukmccall yes, it is. I am getting redboxes for anything else but this case

**Comment by mashuk999** [comment]
In Alert function the first argument should be a string. Passing an object is unexpected behaviour.

**Comment by lukmccall** [comment]
You don't get this error code, cause you're using expo-client from the Apple store. So, you're using a release build that doesn't have all the type checks. Unfortunately, we can't do anything about it. 

@mashuk999 is right that passing an object can lead to unexpected behavior and nobody can ensure that the app will produce an error for all of them. Especially in the release build.
