### ISSUE TITLE
isLooping prop causes video to jump

### ISSUE THREAD

**Issue by barnu5** [expo/expo#8088]
It looks like there is regression or that this issue was not successfully resolved. 

There is not a proper fix or workaround for this bug currently. 

Related to previous issue
https://github.com/expo/expo/issues/3488

**Comment by cruzach** [comment]
hey @barnu5 , can you give us a repro for this? And let us know what SDK you're using (this info is all asked for in the bug report template)

**Comment by barnu5** [comment]
Looks like it may have been fixed in latest
