### ISSUE TITLE
ReferenceError: can't find variable i firebase 7.9.0 expo 37

### ISSUE THREAD

**Issue by dragslag** [expo/expo#8089]
## 🐛 Bug Report
Keep getting referenceerror: can't find variable: i 
Appears in AppEntry
Even after going down to 
"firebase": "7.9.0" I still get the error with Expo 37. I suspect its an error with firebase?

Here's my package.json:

``
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "3.0.3",
    "@expo/vector-icons": "~10.0.6",
    "@firebase/firestore": "^1.14.0",
    "@material-ui/core": "^4.8.3",
    "@ovalmoney/react-native-fitness": "^0.2.4",
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "@tensorflow-models/mobilenet": "^2.0.4",
    "@tensorflow/tfjs": "^1.7.2",
    "@tensorflow/tfjs-react-native": "0.1.0-alpha.2",
    "@use-expo/font": "^2.0.0",
    "abstract-chart": "^2.2.3",
    "apollo-boost": "^0.3.1",
    "art": "^0.10.3",
    "base-64": "^0.1.0",
    "d3": "^5.14.2",
    "d3-shape": "^1.3.3",
    "ds": "^1.4.2",
    "expo": "~37.0.3",
    "expo-asset": "~8.1.3",
    "expo-camera": "~8.2.0",
    "expo-cli": "3.19.2",
    "expo-constants": "~9.0.0",
    "expo-file-system": "~8.1.0",
    "expo-firebase-analytics": "^2.1.1",
    "expo-firebase-core": "^1.0.0",
    "expo-font": "~8.1.0",
    "expo-gl": "~8.1.0",
    "expo-gl-cpp": "~8.1.0",
    "expo-image-crop": "^0.2.16",
    "expo-image-manipulator": "~8.1.0",
    "expo-image-picker": "~8.1.0",
    "expo-mail-composer": "~8.1.0",
    "expo-media-library": "~8.1.0",
    "expo-payments-stripe": "~8.1.0",
    "expo-permissions": "~8.1.0",
    "expo-web-browser": "~8.1.0",
    "firebase": "7.9.0",
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.6.0",
    "firebase-tools": "^7.12.1",
    "firestore": "^1.1.6",
    "flow": "^0.2.3",
    "global": "^4.4.0",
    "graphql": "^14.2.1",
    "graphql-tag": "^2.10.1",
    "jest-expo": "^37.0.0",
    "metro": "^0.56.4",
    "metro-config": "^0.56.4",
    "moment": "^2.24.0",
    "native-base": "2.13.8",
    "npm-reinstall": "^3.1.0",
    "prop-types": "^15.6.0",
    "react": "~16.9.0",
    "react-apollo": "^3.1.3",
    "react-d3-graph": "^2.3.0",
    "react-d3-library": "^1.1.8",
    "react-dom": "~16.9.0",
    "react-lifecycles-compat": "^3.0.4",
    "react-moment": "^0.9.7",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-calendar-strip": "^1.4.1",
    "react-native-calendars": "^1.21.0",
    "react-native-camera-roll-picker": "^1.2.3",
    "react-native-chart-kit": "^5.1.1",
    "react-native-chatbot": "0.0.1-alpha.11",
    "react-native-countdown-component": "^2.2.0",
    "react-native-country-picker-modal": "^1.10.0",
    "react-native-date-picker": "^2.2.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^0.26.4",
    "react-native-elements": "2.0.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-firebase": "^5.4.2",
    "react-native-fs": "^2.16.4",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-gifted-chat": "^0.7.3",
    "react-native-gifted-spinner": "^0.1.0",
    "react-native-htmlview": "^0.15.0",
    "react-native-image-picker": "^0.28.1",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-map-link": "^2.2.1",
    "react-native-minicalendar": "^1.0.5",
    "react-native-modal": "^7.0.2",
    "react-native-multiple-select": "^0.4.4",
    "react-native-multiple-select-list": "^1.0.4",
    "react-native-pages": "^0.9.0",
    "react-native-paper": "^2.11.1",
    "react-native-payments": "^0.7.1",
    "react-native-plotly": "^4.0.0",
    "react-native-progress": "^3.6.0",
    "react-native-push-notification": "^3.1.9",
    "react-native-reanimated": "~1.7.0",
    "react-native-render-html": "^4.2.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-scripts": "^2.0.1",
    "react-native-select-multiple": "^2.0.0",
    "react-native-selectmultiple-button": "^0.1.105",
    "react-native-share": "^1.1.3",
    "react-native-simple-survey": "^1.1.0",
    "react-native-slideable-calendar-strip": "^0.3.2",
    "react-native-star-rating": "^1.1.0",
    "react-native-step-indicator": "0.0.10",
    "react-native-svg": "11.0.1",
    "react-native-svg-charts": "^5.4.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swipe-list-view": "^2.1.3",
    "react-native-swiper": "^1.5.14",
    "react-native-table-component": "^1.2.1",
    "react-native-tag-select": "^2.0.0",
    "react-native-typescript-transformer": "^1.2.13",
    "react-native-unimodules": "~0.8.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-viewpager": "^0.2.13",
    "react-native-web": "~0.11.7",
    "react-native-webview": "8.1.1",
    "react-navigation": "^3.13.0",
    "react-navigation-deprecated-tab-navigator": "^1.3.0",
    "react-navigation-stack": "^2.0.12",
    "react-navigation-tabs": "^2.7.0",
    "react-redux": "^7.1.3",
    "react-redux-firebase": "^3.1.1",
    "react-test-renderer": "^16.8.6",
    "redux": "^4.0.5",
    "redux-firestore": "^0.12.0",
    "redux-thunk": "^2.3.0",
    "rn-apple-healthkit": "^0.8.0",
    "typescript": "^3.8.3",
    "update": "^0.7.4",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@react-native-community/cameraroll": "^1.3.0",
    "@react-native-community/image-editor": "^2.2.0",
    "babel-preset-expo": "^8.1.0",
    "@babel/core": "^7.8.6",
    "jest-expo": "~37.0.0",
    "flow-bin": "^0.115.0"
  },
  "private": true
}
`
![image1](https://user-images.githubusercontent.com/33641401/80701679-14883680-8ae0-11ea-9896-5caecaa31f01.png)
`
### Environment

  Expo CLI 3.20.0 environment info:
    System:
      OS: macOS Mojave 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.3 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.20.0
iOS

Bundle builds to 100% and then quits with this error. Been happening for over a week.

This bug was reproduced by a coworker on their machine.

**Comment by mashuk999** [comment]
The issue might be occurring due to undefined variable in your script. Provide more info about your App.js or index.js file

**Comment by dragslag** [comment]
> The issue might be occurring due to undefined variable in your script. Provide more info about your App.js or index.js file

Starting happening after I got the error can't find variable crypto, but then after adding this quick fix I now get can't find variable i.

In App.js
global.crypto = require("@firebase/firestore");
global.crypto.getRandomValues = byteArray => { for (let i = 0; i < byteArray.length; i++) { byteArray[i] = Math.floor(256 * Math.random()); } }if (!global.atob) { global.atob = decode; }

Removing this code from App.js doesn't get rid of the "referenceerror can't find variable: i" problem.

**Comment by mashuk999** [comment]
In ES6 let will create a block scope to function scope. Inside a for loop in every instance there will be new let instance. Try to change let with var or define the variable ahead of for loop. It will fix the issue.

**Comment by mashuk999** [comment]
`global.crypto = require("@firebase/firestore");
global.crypto.getRandomValues = byteArray => { for (var i = 0; i < byteArray.length; i++) { byteArray[i] = Math.floor(256 * Math.random()); } }if (!global.atob) { global.atob = decode; }`

Try this

**Comment by dragslag** [comment]
> `global.crypto = require("@firebase/firestore"); global.crypto.getRandomValues = byteArray => { for (var i = 0; i < byteArray.length; i++) { byteArray[i] = Math.floor(256 * Math.random()); } }if (!global.atob) { global.atob = decode; }`
> 
> Try this

Thank you. It still doesn't work. The problem is not related to this crypto workaround because I still get the error when it is removed from the code.

**Comment by byCedric** [comment]
Hi @dragslag, and thanks for the help @mashuk999 👍 The [crypto issue is a known issue](https://github.com/expo/expo/issues/7507#issuecomment-608299120), but this should work without having to add the workaround if you pin firebase to `7.9.0`. Could you try removing the `global.crypto` code, pinning firebase, and reinstalling all modules (removing `node_modules` and `yarn.lock` or `package-lock.json`)? If this doesn't help, could you set up a small repo with some of the basic files required to cause this issue? It would definitely help us to get this resolved faster! 😄

**Comment by dragslag** [comment]
Thank you @byCedric, I removed the global.crypto, pinned firebase@7.9.0, and removed package-lock.json, removed and reinstalled my node_modules. 

My App.js is:
`
import React, {Component} from 'react';
import { Platform, StatusBar, StyleSheet, View, Image, Text } from 'react-native';
import {AppLoading} from 'expo';
import {Asset} from 'expo-asset';
import * as Font from 'expo-font';
import { Ionicons, Icon } from '@expo/vector-icons';
import RootNavigation from './navigation/RootNavigation';
import MainTabNavigator from './navigation/MainTabNavigator';
import ApiKeys from './constants/ApiKeys';
import AppNavigator from "./navigation/AppNavigator";
import { SplashScreen } from 'expo';
//import AsyncStorage from '@react-native-community/async-storage';
import Constants from 'expo-constants';
import * as Permissions from 'expo-permissions';
import 'firebase/firestore';
import * as firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/functions';  
import * as Analytics from 'expo-firebase-analytics';


export default class App extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            isLoadingComplete: false,
            isAuthenticationReady: false,
            isAuthenticated: false,
            isSplashReady: false,
            isAppReady: false,
            fontLoaded: false,
            isTfReady: false,
            isModelReady: false,
        };

        const firebaseConfig = {
            apiKey: ,
            authDomain: ,
            databaseURL: ,
            projectId: ,
            storageBucket: ,
            messagingSenderId: ,
            measurementId: 
        };
        firebase.initializeApp(firebaseConfig);

        const db = firebase.firestore();

        if (!firebase.apps.length) {
            firebase.initializeApp(ApiKeys.firebaseConfig);
        }
        firebase.auth().onAuthStateChanged(this.onAuthStateChanged);
    }

    onAuthStateChanged = (user) => {
        let jwtToken = firebase.auth().onAuthStateChanged(function(user) {
            if (user) {
                user.getIdToken().then(function(idToken) {  
                    return idToken;
                });
            }
        });

        this.setState({isAuthenticationReady: true});
        this.setState({isAuthenticated: !!user});
        if (user) {

            console.log(user.uid + ' nya');
            firebase.firestore().collection('user').doc(user.uid).set({userId: user.uid});
        }
    }
    getUserData = () => {
        let ref = firebase.database().ref('/');
        ref.on('value', snapshot => {
            const state = snapshot.val();
            this.setState(state);
        });
        console.log('DATA RETRIEVED');
    }
`


And the file that has the referenceerror: can't find variable i
querysnapshot.foreach$argument_0

MyScreen.js
`
import React, { Component } from 'react';
import {
    View,
    Text,
    TouchableOpacity,
    StyleSheet,
    ScrollView,
} from "react-native";
import {Divider, Slider, ListItem} from "react-native-elements";
import {KeyboardAwareScrollView} from "react-native-keyboard-aware-scroll-view";
import * as firebase from 'firebase';
import 'firebase/firestore';
import {Ionicons} from "@expo/vector-icons";
import moment from "moment";


export default class MyScreen extends React.Component {
    constructor(props) {
        super(props);

        const userId = firebase.auth().currentUser.uid;
        this.result = firebase.firestore()
            .collection('users')
            .doc(userId)
            .collection('MyBMI');

        this.refWeighin = firebase.firestore()
            .collection('users')
            .doc(userId)
            .collection('MyWeighin');

        this.state = {
            weight: "",
            Goalweight: '',
            MyWeighin: [],
            MyBMI: [],
        };
    };

    onCollectionBMIUpdate = (querySnapshot) => {
        const MyBMI = [];

        querySnapshot.forEach((doc) => {
            MyBMI.push({
                key: doc.id,
                weight: doc.data().weight,
            });
            this.setState ({
                MyBMI,
                isLoading: false,
            })
        });
    }

    onCollectionWeighinUpdate1 = (querySnapshot) => {
        const MyWeighin = [];

        querySnapshot.forEach((doc) => {
                MyWeighin.push({
                    key: doc.id,
                    Goalweight: doc.data().Goalweight,
                });

        this.setState({
            MyWeighin,
            isLoading: false,
        })
        });
    }

    componentDidMount() {
        this.unsubscribe = this.result.onSnapshot(this.onCollectionBMIUpdate);
        this.unsubscribe = this.refWeighin.onSnapshot(this.onCollectionWeighinUpdate1);
    }

    render () {
        const {weight,  Goalweight} = this.state;

        return (
            <ScrollView>
                <Text>Your starting weight was: {this.state.weight}. Your goal weight is: {this.state.Goalweight}. </Text>
             </ScrollView>

        )
    } 
}
`

It was working perfectly until I went to update my one of my node modules last week and since then I've been uninstalling and reinstalling alternatively with yarn and npm (removing the package-lock & yarn-lock, respectively) to try to get it to work. 

Thank you for your help!

**Comment by dragslag** [comment]
I updated my expo-cli to 3.20.1 and it works now.
