### ISSUE TITLE
Constants.manifest.extra is always undefined (Windows)(Typescript)

### ISSUE THREAD

**Issue by juandav** [expo/expo#8090]
Constants.manifest.extra is undefined
[repo here](https://github.com/juandav/expo-issue-8090)

## Description

when trying to display the value of extra constants this gives undefined.

## Expected Behavior

```ts
import Constants from 'expo-constants';

console.log("extra - ", Constants.manifest.extra);
//  extra - { "mode": "DEVELOPMENT" }
```

## Observed Behavior

I have observed that setting the value directly in app.json continues as undefined.

```ts
import Constants from 'expo-constants';

console.log("extra - ", Constants.manifest.extra);
// extra - undefined
```

## Environment

```sh
 Expo CLI 3.17.24 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: 37.0.8 => 37.0.8
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
    phone
      phone: simulator, emulator and Huawei
      platform: android
      model: LDN-LX3
```

## Reproducible Demo

[repo here](https://github.com/juandav/expo-issue-8090)

### app.config.js
```ts
import { ExpoConfig, ConfigContext } from '@expo/config';
import manifiest from './package.json';

const Mode = {
  DEVELOPMENT: 'DEVELOPMENT',
  QA: 'QA',
  PRODUCTION: 'PRODUCTION',
}

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  version: manifiest.version,
  // All values in extra will be passed to your app.
  extra: {
    mode: Mode.DEVELOPMENT,
  },
});
```

### app.json
```json
{
  "expo": {
    "name": "myapp",
    "slug": "myapp",
    "scheme": "my-app-schema",
    "privacy": "unlisted",
    "version": "1.0.1",
    "orientation": "portrait",
    "description": "My app description",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover"
    },
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "android": {
      "package": "co.com.example.myapp",
      "versionCode": 1
    },
    "androidStatusBar": {
      "hidden": false,
      "translucent": true,
      "barStyle": "light-content",
      "backgroundColor": "#00000000"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "co.com.example.myapp",
      "buildNumber": "1.0.0"
    }
  }
}
```

### src/setup.constants.ts

```ts
import Constants from 'expo-constants';

console.log("extra", Constants.manifest.extra);
```

**Comment by byCedric** [comment]
Hi @juandav! Thanks for the issue report. Unfortunately, I can't reproduce this behavior. For me, your provided code works fine. I did have to edit the `scheme` in your `app.json` to `"scheme": "my-app-schema"`. The reason for this is the upper case letters, those are invalid. Could you try editing this on your end as well and restart the project with `expo start --clear`? 😄 

If you are using the bare workflow instead, the manifest isn't available. That might cause this issue for you too, but only if you are running bare instead of managed.

Hope it helps!

**Comment by juandav** [comment]
hahaha ok just edit it for this example I have it camelCase

**Comment by juandav** [comment]
Ok, I modified it like this for this example, sorry

**Comment by juandav** [comment]
I will create a separate repo based on my project to show what does not work for me, I will be uploading it in the next few hours.

**Comment by juandav** [comment]
https://github.com/juandav/expo-issue-8090

**Comment by byCedric** [comment]
Hi @juandav, thanks for the repository (those things are useful 😄). But also here I'm getting the following output:

```
Running application on ONEPLUS A6003.
Object {
  "mode": "DEVELOPMENT",
}
```

Could you try upgrading your `expo-cli` and/or project with `expo upgrade`?

**Comment by juandav** [comment]
![imagen](https://user-images.githubusercontent.com/12274145/80749470-15bf6080-8aec-11ea-9701-b9d489781ce6.png)

**Comment by marconi** [comment]
I have a similar issue, but for me `Constants.manifest.extra` is populated on iOS simulator but is not present on Android emulator.

**Comment by Rafatcb** [comment]
I am using Android and I am facing that issue too, neither `app.config.js` nor `app.config.ts` changes are applied to the application.

Maybe it is related to https://github.com/expo/expo-cli/issues/1585 ?

**Comment by marconi** [comment]
Just to update, actually it started working for both iOS and Android for me but only if the config is present on `app.json` as an empty key.

**Comment by alkeshattal** [comment]
Facing same issue for Expo CLI version 3.22.3
Windows 10 OS
It works fine on Mac

**Comment by brentvatne** [comment]
> Facing same issue for Expo CLI version 3.22.3
> 
> Windows 10 OS
> 
> It works fine on Mac

please provide a reproducible example

**Comment by davidmyerslup** [comment]
I was also experiencing this issue, but it appears to be a caching problem. I had a misconfigured variable being loaded into manifest.extra, and after correcting it I was still unable to see it despite trying several restarts of both the Expo client and server. The only thing that eventually worked is force clearing the data on the Expo client. After doing this, the updated environment variable is now being picked up and can be accessed from my application.

**Comment by kennethlynne** [comment]
I had issues with the extra property always being undefined until I had both a app.json and a app.config.ts file.

**Comment by greegus** [comment]
I've also found documentation somehow misleading – https://docs.expo.io/workflow/configuration/#dynamic-configuration-with-appconfigjs refers that the `extra` property should be defined as a top-level prop in the object exported by `app.config.js` but in fact, it should rather be nested under the `expo` prop there.

Using `app.config.js` with the following structure finally worked for me (with expo v38)

```javscript
export default {
  expo: {
    name: 'My App'
    version: '1.0.0',
    extra: {
      mode: 'development',
      ...
    },
    ...
  }
});
```

**Comment by aeneasr** [comment]
Hi, I have exactly the same issue as you but:

1. On macOS with the most recent Expo release (39)
2. I am **not** using `app.config.js` - https://github.com/expo/expo/issues/8090#issuecomment-688794880 did also not work for me when trying it out.
3. I have installed `expo install expo-constants`
4. `Constants.manifest` is an empty Object

**Diagnostics**

```
expo diagnostics

  Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.13.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.14 
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: managed
```

**app.json**

```
{
  "expo": {
    "name": "ORY Kratos SelfService UI",
    "slug": "kratos-selfservice-ui-react-native",
    "scheme": "kratos-selfservice-ui-react-native",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

**helper.tsx**

```
import Constants from 'expo-constants';

console.log(Constants) // returns {}
```

**Comment by mdbiscan** [comment]
I'm having this same issue, but only with Xcode building and installing onto a device. Simulator (Android & iOS), Android Devices, and web all work fine reading `Constants.manifest.extra`. I've tried all the solutions suggested here and elsewhere with no effect.

**Comment by ajgrover** [comment]
I had issues with `Constants.manifest.extra` being `null` in production builds using EAS, which caused the app to crash on startup. The solution was to stop using `expo-constants` in favor of the solution detailed [here](https://docs.expo.io/build-reference/variables/). My understanding is that EAS is using some form of the bare workflow that's not compatible with `expo-constants`.

**Comment by brentvatne** [comment]
you can run `expo config --type public` to see what fields will be available in your manifest at runtime. as far as i know there are no reproducible issues with using `Constants.manifest.extra` so i am closing this issue

**Comment by cederom** [comment]
The same here! Works on Android does not work on iOS :-( `expo-cli@4.12.0`, `expo@42.0.5`, `expo-constants@11.1.0`.

**Comment by brentvatne** [comment]
@cederom - post a new issue with a minimal reproducible example: https://stackoverflow.com/help/minimal-reproducible-example
