### ISSUE TITLE
Camera Permissions from Expo-Camera library

### ISSUE THREAD

**Issue by fernando550** [expo/expo#8096]
Hi guys, so I'm a bit of a rookie programmer, and I'm struggling to understand some of this expo library... I see there's expo, expo-camera, and expo-permissions, and there's two ways to import camera:
(A) import { Camera } from 'expo'
(B) import { Camera } from 'expo-camera' (the one im using now)
and then there's also import {Permissions} from 'expo-permissions', even though you can now have the Camera.requestPermissionsAsync()...

Can someone clarifiy the best practice and why? I assume it has to do with updates to the programming conventions for expo.

Additionally, I am having trouble understanding the functionality... I was asked once for permission from my camera to let my app access it. My concern is that I want the app to ask for permission everytime that I go to the camera. I don't see that there's anyway to revoke or nullify permissions from my app, and ideally I would put this in the useEffect hook cleanup function. Let me know! Thanks guys

note: I am using the boilerplate code from the expo example in the camera API docs

**Comment by byCedric** [comment]
Hi @fernando550! I think you can ask these questions in our [Slack community](https://slack.expo.io/) or [forum](https://forums.expo.io/) too, feel free to join them! 😄 But to give you some answers:

- `expo-camera` or `import { Camera } from 'expo';`
Older versions of Expo contained all APIs in the `expo` package, which was ok at first. But as Expo functionality grew, so did the package. [Starting 2019, this was split up to allow running these APIs in other environments than Expo too](https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331). Also, not every app required _every module_, splitting it up also opened up the way for future tree-shaking (removing stuff you don't need). [You should get a warning if you import the Camera like: `import { Camera } from 'expo';`](https://github.com/expo/expo/blob/master/packages/expo/src/removed.ts#L232-L241). 

- `expo-permissions` or `Camera.requestPermissionsAsync`
This one is a bit harder to explain. Basically, `expo-permissions` was created to handle all permissions. If you only need the camera permission, I would go for the built-in `Camera.requestPermissionsAsync`. Under the hood, this method uses the same lower-level APIs as `expo-permissions`. But, if you need more, `expo-permissions` might suit your needs better.

- Revoking permissions
This is something that's currently not possible from within the app. If you want to read more about the common best practices around permissions, I would recommend reading a bit more on [Android's guide](https://developer.android.com/training/permissions/usage-notes) or [Apple's guide](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/requesting-permission/). You can, however, create a custom confirmation modal to enable the camera every time you want to use it. But, this is something that's not recommended, it could feel "annoying" to users.

Hope this helps!
