### ISSUE TITLE
Upload to Android device via usb (or bluetooth) not local network

### ISSUE THREAD

**Issue by ORESoftware** [expo/expo#8098]
I have an Android device plugged into my laptop via USB ports.   My local wifi network is an xfinity public network that doesn't seem to like sharing hosts/ports between machines.

I am looking for this option:

```bash
expo start --usb --android
```

or this option:

```bash
expo start --bluetooth --android
```

so that I can upload the JS bundle to the phone using USB or Bluetooth, NOT WIFI!

thanks

**Comment by byCedric** [comment]
Hi @ORESoftware! You should be able to do this, when you run `expo start` it tries to tunnel your (plugged in) Android device to your computer. When this happens, you can run the Expo CLI in localhost mode. There is a [forum post about this here](https://forums.expo.io/t/run-expo-on-android-device-via-usb/5218/3). Let me know if this does or doesn't work for you 😄

**Comment by ORESoftware** [comment]
what about bluetooth tho?
