### ISSUE TITLE
Not able to send more than 4 POST requests

### ISSUE THREAD

**Issue by James2516** [expo/expo#810]
I'm not able to send more than 4 post request to a nodejs server instantly.
To reproduce: 
1. git clone https://github.com/James2516/react-native-post
2. cd server && npm i && npm start
3. cd client && npm i && npm start

Server is created with `express-generator` and client with `create-react-native-app`.

Client code modified: (App.js)
```
const axios = require('axios');

const API_BASE_URL = 'http://localhost:3010/';

for (let i = 0; i < 20; i++) {
  console.log('posting', i)
  axios.post(API_BASE_URL, { i });
}
```

Server code modified: (routes/index.js)
```
router.post('/', function(req, res, next) {
  console.log('backend received', req.body);
});
```

Output:
```
backend received { i: 0 }
backend received { i: 1 }
backend received { i: 2 }
backend received { i: 3 }
```

The rest of the requests were received several minutes later (sometimes never).

**Comment by fxfactorial** [comment]
`axios.post` returns a Promise. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). Your current code just make and throws away 4 pending Promises.

**Comment by James2516** [comment]
How does that explain why the backend did not receive the remaining 16 POST requests...?

**Comment by fxfactorial** [comment]
I would recommend you try doing the code like:

```
(async () => {
for (let i = 0; i < 20; i++) {
  console.log('posting', i)
  await axios.post(API_BASE_URL, { i });
})()
```

**Comment by James2516** [comment]
Ok figured out what the problem is.
https://github.com/James2516/react-native-post/blob/master/server/routes/index.js#L6
I need to end the POST request (eg. with res.end()) otherwise it'd stop processing more requests.
