### ISSUE TITLE
Problem with iOS build

### ISSUE THREAD

**Issue by mik0205** [expo/expo#811]
I try to build my app but the build status told me:
[exp] iOS: There was an error with this build.

This was the output of my build:
[exp] Building...
[exp] Build started, it may take a few minutes to complete.
[exp] Build ID: f2f84274-cb15-459b-a214-00216d0651b1
[exp] Run `exp build:status` to monitor it.

**Comment by davepack** [comment]
Looks like a problem occurred during the build, but it will most likely work if you try it again. Let us know if anything else comes up.
