### ISSUE TITLE
saveToLibraryAsync is missing returned uri

### ISSUE THREAD

**Issue by rissois** [expo/expo#8113]
Apologies if this is more of a "feature" than a bug, but React Native CameraRoll.saveToCameraRoll() returns the new uri, and assuming MediaLibrary.saveToLibraryAsync() was built on top of this it is surprising that the Promise resolves as void.

**Comment by brentvatne** [comment]
it was not built on top of it, it uses a newer ios api than camera roll does and was built because camera roll lib was insufficient for many use cases. but it may be a good idea to have it return the asset! what’s your use case?

**Comment by rissois** [comment]
I have users uploading their own photos. After they take photos with the option of saving them,  I am tracking the uri for future display to minimize re-downloading images they already have. I basically wanted to upgrade the uri from the temporary takePictureAsync to the more permanent saveToLibraryAsync.

I realize I can also use createAssetAsync, but I was trying to avoid assets since I do not understand them very well, and I believe I'd need to handle assets differently from non-assets and use getContentURIAsync, and things just become a bit of mess when all I needed was the Camera Roll uri.

(personal note: thanks for the quick response and all the amazing work you guys do! I have been teaching myself, and Expo has really accelerated my development)

**Comment by brentvatne** [comment]
one thing you could do is add them to a specific album for your app. then just get all of the contents of that album and display them for users

**Comment by rissois** [comment]
That could work... I'll think about the implications of an album for my users. Thanks for the advice!

**Comment by lukmccall** [comment]
Hi @rissois, the `saveToLibraryAsync` doesn't require the `CAMERA_ROLL` permission. Unfortunately, because of this, it can't return the asset object. So, if you need an asset object, use the `MediaLibrary.createAssetAsync`.
