### ISSUE TITLE
[Bare workflow][SDK 37] Release builds crashes w/ undefined is not an object evaluating(this._nativeModule.startObserving)

### ISSUE THREAD

**Issue by bayoremit** [expo/expo#8116]
## 🐛 Bug Report

I recently just ejected into the bare workflow world, updated all the dependencies that are managed only (Linking, Apploading, bugsnag...). App works fine on the web, works fine w/ `react-native run-ios/android`, just cant seem to get a working release build w/ `expo-notifications`.

After ejecting, we are still relying on using expo's servers for push notifications

### Environment

```
Expo CLI 3.20.1 environment info:
System:
    OS: macOS 10.15.3
    Shell: 5.7.1 - /bin/zsh
Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
npmGlobalPackages:
    expo-cli: 3.20.1
```

Dep list
```
"dependencies": {
    "@bugsnag/js": "7.0.1",
    "@bugsnag/plugin-react": "7.0.1",
    "@expo/vector-icons": "10.1.0",
    "@react-native-community/netinfo": "5.5.1",
    "base-64": "0.1.0",
    "bugsnag-react-native": "2.23.7",
    "cross-fetch": "3.0.4",
    "expo": "37.0.8",
    "expo-analytics-segment": "8.1.0",
    "expo-camera": "8.2.0",
    "expo-constants": "9.0.0",
    "expo-device": "2.1.0",
    "expo-document-picker": "8.1.0",
    "expo-font": "8.1.1",
    "expo-image-manipulator": "8.1.0",
    "expo-image-picker": "8.1.0",
    "expo-linear-gradient": "8.1.0",
    "expo-local-authentication": "9.0.0",
    "expo-notifications": "0.1.2",
    "expo-permissions": "8.1.0",
    "expo-secure-store": "8.1.0",
    "expo-splash-screen": "0.2.0",
    "expo-updates": "0.1.3",
    "lodash": "4.17.15",
    "mobx": "5.15.4",
    "mobx-react": "6.2.2",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-load-script": "0.0.6",
    "react-native": "0.61.5",
    "react-native-animatable": "1.3.3",
    "react-native-gesture-handler": "1.6.0",
    "react-native-reanimated": "1.7.0",
    "react-native-screens": "2.2.0",
    "react-native-svg": "11.0.1",
    "react-native-unimodules": "0.9.0",
    "react-native-web": "0.11.7",
    "react-native-webview": "8.1.1",
    "react-router-dom": "5.1.2",
    "react-router-native": "5.1.2",
    "reflect-metadata": "0.1.13",
    "uuid": "3.4.0"
},
```

App targets (Bare workflow standalone)
- iOS
- Android

### Steps to Reproduce

I'm trying to figure out how to build a release app and have turtle-cli installed to help with making the builds. I see mixed documentation around using turtle to make bare workflow builds and not sure if my release app is crashing because turtle is not built for this or something else. I currently am following [this doc](https://github.com/expo/fyi/blob/master/release-builds-with-expo-updates.md)

Here is my build process
- Run `react-native run-android --variant Release ` for android (similar for ios but different flag for release). This is to ensure the project is built
- Run `expo publish --release-channel alpha` to populate the manifest, bundle and expo_updates stuff
- Run the turtle build commands
- Android: `turtle build:android --keystore-path "/path/to/keystore.jks" --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS -t app-bundle --release-channel alpha -m release -t apk`
- Ios `turtle build:ios --team-id $EXPO_APPLE_TEAM_ID --dist-p12-path "/path/to/dist.p12" --provisioning-profile-path "/path/to/profile.mobileprovision" --release-channel alpha -t simulator`
- Apk or Appbundle or Simulator or ipa all crash right after the splash screen comes up

I am unsure how to debug the ios app, but i figured it might be related to the android situation. On android i use the profile or debug APK to get a sense of whats up and i get this error before the app crashes `TypeError: undefined is not an object evaluating(this._nativeModule.startObserving` I am currently lost and unsure if i am not supposed to be using turtle to make release builds and i should be making builds some other way. This seems to be relating to the `react-native-adapter` EventEmitter in the `unimodules` lib, and seems to be related to calling `addNotificationReceivedListener` in the `expo-notifications` lib. Removing the method prevents the crash, but then notifications don't work

### Expected Behavior

turtle-cli makes a release build that works w/ notifications

### Actual Behavior

Release builds crash w/ `TypeError: undefined is not an object evaluating(this._nativeModule.startObserving`

### Reproducible Demo

Unsure how to make a repo in snacks given this is a bare workflow release build issue and doesn't happen in dev release w/ the packager. I can privately share an APK w/ the team if that helps.

Thanks!

**Comment by hanselsen** [comment]
+1 also getting this.

**Comment by cruzach** [comment]
Turtle-cli does not support building bare workflow apps right now. We're looking into providing a way for bare workflow users to easily build binaries, but for now, you should use Xcode and Android Studio

**Comment by bayoremit** [comment]
@hanselsen i can share what we finally ended up doing if you are still stuck

**Comment by hanselsen** [comment]
Haha no thanks. I moved on to other issues 😂

**Comment by anasanzari** [comment]
it's happening managed flow as well.
expo sdk 37

**Comment by brentvatne** [comment]
can you share a [mcve](https://stackoverflow.com/help/mcve) please @anasanzari?

**Comment by roger-n** [comment]
@bayoremit If you don't mind me asking, what did you end up doing?  Stuck on this rn

**Comment by gbwashleybrown** [comment]
Stuck on this too....

**Comment by cruzach** [comment]
If you're having this issue, please share a reproducible demo. I haven't been able to replicate this issue so far

**Comment by faustoct** [comment]
the same in dettach

**Comment by brentvatne** [comment]
@faustoct:

> If you're having this issue, please share a reproducible demo. I haven't been able to replicate this issue so far

**Comment by faustoct** [comment]
@brentvatne The problem is: _somehow the packages are not imported on MainApplication.java_ I got the same problem on StripePackage. I solve the notification in the same way. Here the step by step to fix it

1. go to MainApplication.java
2. Add import expo.modules.notifications.NotificationsPackage;
3. On ReactModuleRegistryProvider add the Package NotificationsPackage, this is my modules as example
````
public class MainApplication extends Application implements ReactApplication {
  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(Arrays.<Package>asList(
     new ReactAdapterPackage(),
     new ConstantsPackage(),
     new PermissionsPackage(),
     new FileSystemPackage(),
     new LocationPackage(),
     new AdMobPackage(),
     new ImagePickerPackage(),
     new StripePackage(),
     new NotificationsPackage()
  ), null); 
````
4. See that I have to change the last argument to null as mentioned here https://forums.expo.io/t/expo-notifications-in-bare-workflow/35334/2
