### ISSUE TITLE
[expo-gl] Crash on GLView getGL

### ISSUE THREAD

**Issue by gavrix** [expo/expo#8118]
### Environment
bare expo-gl@8.0.0 through unimodules

### Steps to Reproduce
We can't reproduce these issue, we are receiving small percentage of these issues through crash reporting tools.
Here's the stack: 
```ts
   delete global.__EXGLContexts[exglCtxId];
   // determine the prototype to use, depending on OpenGL ES version
   const glesVersion = gl.getParameter(gl.VERSION);
>>   const supportsWebGL2 = parseFloat(glesVersion.split(/[^\d.]+/g).join(' ')) >= 3.0;
   const prototype = supportsWebGL2
   ? global.WebGL2RenderingContext.prototype
   : global.WebGLRenderingContext.prototype;
```

exception is `undefined is not an object (evaluating 'u.split')`

I'm guessing this error means ` gl.getParameter(gl.VERSION)` returned `undefined`.

Not sure what might be the reason for this error, and it is rare, percentage we're seeing is very low, so might be some sort of rare race condition.

**Comment by nicholasio** [comment]
I'm experiencing this issue on android after updating react-native to 0.62. Works fine on iOS

**Comment by nicholasio** [comment]
this might be related: https://github.com/expo/expo/issues/8118

**Comment by cruzach** [comment]
I believe @nicholasio is right, this is probably due to the same issue as 7623, so I'm going to close this as a duplicate, and we can keep it focused in that one issue

**Comment by serhiipalash** [comment]
@cruzach I don't think it's the same issue as `undefined is not an object (evaluating 'gl.__exglCtxId = exglCtxId')`. Can you please reopen this issue?

We had both `undefined is not an object (evaluating 'u.split')` and `undefined is not an object (evaluating 'gl.__exglCtxId = exglCtxId')`. In last release I applied this [fix](https://github.com/expo/expo/issues/7623#issuecomment-625843069) for the second issue. Now we don't have `undefined is not an object (evaluating 'gl.__exglCtxId = exglCtxId')` in production, but still have `undefined is not an object (evaluating 'u.split')`.

**Comment by audrew** [comment]
Receive `TypeError: null is not an object (evaluating 'glesVersion.split')` . any know solution?

**Comment by komelabbbas** [comment]
The issue happens, any solution?
