### ISSUE TITLE
Expo not correctly detecting node version.

### ISSUE THREAD

**Issue by fabulousduck** [expo/expo#8119]
When using the `expo init` command, it warns me that node version `8.10.0` is no longer supported.
Full error:

```
ERROR: Node.js version 8.10.0 is no longer supported.

expo-cli supports following Node.js versions:
* >=10.13.0 <11.0.0 (Active LTS)
* >=12.0.0 <13.0.0 (Active LTS)
* >=13.0.0 <14.0.0 (Current Release)
```

However, when running the `node --version` command, I get the following output:
```
v12.16.3
```

Before using nvm a long time ago, i was running version `8.10.0` leading me to believe expo is not able to see the nvm version but rather goes directly to the underlying node version. I am wondering if there is any solution to this without having to completely uninstall node and reinstall a later version.

**Comment by brentvatne** [comment]
@fabulousduck - I think what is happening is that expo-cli is installed globally by Node 8.10.0 - I would recommend uninstalling it (switch to Node 8.10.0, run `npm uninstall -g expo-cli`) then switch back to node 12 and install it

**Comment by fabulousduck** [comment]
Hey @brentvatne , I tried this but unfortunately it did not work. I even went as far as completely reinstalling nvm and uninstalling expo-cli when it was uninstalled.

**Comment by fabulousduck** [comment]
As a further check i deleted the global npm package folder in 8.10.0. Doing `npm list` in 8.10.0 gives me 

```
(base) λ npm list
/home/ryan
└── (empty)
```

**Comment by brentvatne** [comment]
what if you run `which expo` - where is that being resolved to?

**Comment by fabulousduck** [comment]
I managed to get expo installed under 12.16.3 by completely reinstalling nodejs which was a bit of a pain. But it works now.

**Comment by brentvatne** [comment]
yeah it can be a bit tricky sometimes to juggle global package installs when your machine has had multiple ways of managing node versions over time, glad you figured it out!
