### ISSUE TITLE
nonPersistent in app.json disables hot reload

### ISSUE THREAD

**Issue by BenBrostoff** [expo/expo#812]
First off, thanks for a great project Expo team.

I noticed from a clean `create-react-native-app` that hot reloading will break with the following `app.json` configuration:

```
{
  "expo": {
    "sdkVersion": "21.0.0",
    "packagerOpts": {
      "nonPersistent": false
    }
  }
}
```

This makes sense, as in the `react-native` source it looks like a `watch` option is being disabled if args exist for [`nonPersistent`](https://github.com/facebook/react-native/blob/34487c059192129db07608af4eb27cfad22b2d06/local-cli/server/runServer.js#L205).

I think a number of Expo users are leveraging `nonPersistent` for [CI purposes](https://forums.expo.io/t/what-do-you-use-for-testing-and-ci-for-expo-rn/850/3), and presumably also want hot reloading when developing locally. I think it makes sense to document `nonPersistent` as it can have some important consequences. Would love to help here on the documentation front if this sounds like a good idea!

**Comment by ide** [comment]
It'd probably be nice also to gray out the Hot Reloading option and show an explanation why it's disabled when you tap on it.

**Comment by cruzach** [comment]
Tested this now, `nonPersistent` doesn't disable or prevent hot reloading from being enabled. If you're seeing this now, please open up a new issue
