### ISSUE TITLE
How to load local html on web platform?

### ISSUE THREAD

**Issue by priyanshrastogi** [expo/expo#8120]
I have a HTML string that I want to load using WebView.

On Android and iOS, we can use `react-native-webview` to load local html string. Here is an example:

```
<WebView
      originWhitelist={['*']}
      source={{ html: '<p>I am text</p>' }}
      onNavigationStateChange={this.handleChange}
/>
```

Since react-native-webview is not supported on web. How can I do this on web?

I am using expo sdk 37.

**Comment by sam-coxon** [comment]
@priyanshrastogi how did you fix this?

**Comment by priyanshrastogi** [comment]
@sam-coxon I hosted that html page on github pages and opened it using expo-web-browser
