### ISSUE TITLE
[expo-image-picker] Is there a way to get original uri rather than copying to cache directory?

### ISSUE THREAD

**Issue by ahmetbicer** [expo/expo#8121]
Hi my question is simple. When i use expo-image-picker to choose videos from device it copies the video to app's cache directory. Is there a way to get original uri to video without copying to cache directory? Thank you so much.

Edit: I don't want to use DocumentPicker because it is not returns the width height and duration of the video according to documentation. I just want to set copyToCacheDirectory false just like in DocumentPicker.

**Comment by byCedric** [comment]
Hi @ahmetbicer! The video is copied to the cache because the app needs to access it. What's your use case to get the original path of the file? If you want to send it, you still need access to the content, right?

**Comment by ahmetbicer** [comment]
Hi @byCedric! I am using bare workflow so i can access to video from original uri. I am extracting frames from video. When it caches to the app folders i need to programmatically clean the caches. Obviously i can do that but i just want to know if it is possible. Thank you for the support!

**Comment by Servo97** [comment]
> Hi @byCedric! I am using bare workflow so i can access to video from original uri. I am extracting frames from video. When it caches to the app folders i need to programmatically clean the caches. Obviously i can do that but i just want to know if it is possible. Thank you for the support!

Hi, I'm a noob, can you please let me know if the image/video cache generated by expo gets deleted automatically? 

Or do we need to explicitly delete it to prevent the app from bloating?

**Comment by ahmetbicer** [comment]
> > Hi @byCedric! I am using bare workflow so i can access to video from original uri. I am extracting frames from video. When it caches to the app folders i need to programmatically clean the caches. Obviously i can do that but i just want to know if it is possible. Thank you for the support!
> 
> Hi, I'm a noob, can you please let me know if the image/video cache generated by expo gets deleted automatically?
> 
> Or do we need to explicitly delete it to prevent the app from bloating?

As far as i know you need to explicitly delete the cache folder in order to prevent the bloating. On the other hand i am using expo-media-library and my custom image-picker component instead of expo-image-picker to get the original uri. So i don't have to clear the cache so often.

**Comment by Servo97** [comment]
I see, thanks for the clarification!
