### ISSUE TITLE
[web] Improve SEO (meta & Open Graph fields)

### ISSUE THREAD

**Issue by nandorojo** [expo/expo#8122]
### Expected Behavior

I think it could be a great addition to Expo Web to have some improved SEO. 

If you're using `Next`, then [`next-seo`](https://www.npmjs.com/package/next-seo) is a good solution. 

However, for regular expo web, we're rendering a single static page, so it might make the most sense to have a JSON file with static SEO values that expo uses to generate meta tags in `index.html`.

### Actual Behavior

Some of what expo already has here is great! It currently takes fields from `app.json` and populates them in the `index.html`'s `head`, such as the meta title.

However, there doesn't seem to be a clean way to set open graph fields like an image, or meta description, without running `expo customize:web` and editing the `index.html`

### Proposed change

Just an idea here, but I think something like `expo customize:web` -> `seo.json` could be cool. From there, an `seo.json` file gets added to the `web` folder, where you edit static fields like meta description, etc. 

Or, better yet, it could be an `seo.ts` file that default exports the SEO object (this way there could be typescript support.) The dictionary could mimic the `next-seo` component's props.

I'd be happy to assist if this feels like something that would be useful. If not, happy to think of a different solution! 

A `web` field in `app.json` would work too.

**Comment by EvanBacon** [comment]
We used to have something like this but removed it in favor of ejecting the `index.`html and manually adding meta tags to the head. You can probably use something like https://github.com/nfl/react-helmet to manage SEO as well.

**Comment by nandorojo** [comment]
Got it. I use Helmet with Gatsby, so I’ll add that here too. Thanks!
