### ISSUE TITLE
Styling the BarCodeScanner

### ISSUE THREAD

**Issue by morganOliveira2018** [expo/expo#8124]
### I am curious if anyone has tips for styling this component to make it a bit more attractive similar the Expo app and their QR code scanning where there is virtual aperture. 
Has anyone done a style similar to this image using the [Expo-barcode-scanner ](https://docs.expo.io/versions/latest/sdk/bar-code-scanner/)?
![Screenshot_2](https://user-images.githubusercontent.com/45489794/80867273-cc951b00-8c69-11ea-9d1e-aaa83f526f35.png)

**Comment by RealDyllon** [comment]
I can’t seem tofind the code I used to style my barcode scanner. If I do find it, I will link the code in a snack. Anyway, IIRC, here’s a description:

You can use a parent View component to wrap the barcode scanner and a child View component.

The barcode scanner component should be the full size of the parent.

They child view style should be: zIndex: 10, position: absolute, top: 0, and full size of the parent. This child view should contain the “reticle” icon in the center, scaled as desired. 

Remember, the barcode scanner is actually just a camera viewfinder. You can style pretty much everything as you fancy.

**Comment by morganOliveira2018** [comment]
If you find the code can you send it to me?

Em sáb, 2 de mai de 2020 13:56, Dyllon <notifications@github.com> escreveu:

**Comment by byCedric** [comment]
@morganOliveira2018 You can check out how Expo styles the QR code, maybe it gives you an idea of what @RealDyllon describes 😄 To summarize it, you have to think in layers. The "bottom" layer or view is the camera, and you can style anything over that view.

Hope it helps!
