### ISSUE TITLE
Expo doesn't show fonts without weights in iOS build

### ISSUE THREAD

**Issue by ardaa** [expo/expo#8127]
## 🐛 Bug Report
I forgot to point out that it happens in custom fonts.
### Environment

  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.20.1

iOS Build

### Steps to Reproduce
I followed the steps to use fonts in expo. It works in Expo App and Android APK Build 
```javascript
...
let customFonts = {
  'Caros-ExtraBold': require('../assets/fonts/Caros-ExtraBold.otf'),
  'Caros-Regular': require('../assets/fonts/Caros-Regular.otf'),
};
...
componentDidMount(){
await Font.loadAsync(customFonts);
...}
...
render(){
  if (this.state.fontsLoaded) {
...
```

### Expected Behavior

It should show fonts just like in the Expo app and Android standalone.

### Actual Behavior

It works in Expo App and Android APK Build but doesn't work on iOS without specifying weights. (And for Caros Regular 400 or regular didn't work)

### Reproducible Demo

I wasn't able to make a snack demo. Snack gives a lot of errors. And it shouldn't matter because it only happens on iOS standalone.

**Comment by brentvatne** [comment]
can you provide a reproducible example in a git repo? and screenshots of what you’re seeing? happy to help if you can

**Comment by ardaa** [comment]
> can you provide a reproducible example in a git repo? and screenshots of what you’re seeing? happy to help if you can

Of course. In a few minutes.

**Comment by ardaa** [comment]
Interesting. Just did an example. It works. There may be a problem with my app. Thanks anyway. Will inform if I find a solution.
