### ISSUE TITLE
[notification-android] Getting vibration after notification is being disable foregoround. Push notification Managed workflow

### ISSUE THREAD

**Issue by zifahm** [expo/expo#8128]
## 🐛 Bug Report
Getting psuedo vibration after disabling the notification in foregroud.
```js
  useEffect(() => {
    const notifs = Notifications.addListener(handleNotification);
    return () => {
      notifs.remove();
    };
  }, []);

  const handleNotification = (notification: any) => {
    console.log(AppState.currentState);
    if (AppState.currentState === "active") {
      Notifications.dismissNotificationAsync(
        notification.notificationId
      );
      console.log(notification);
    }
  };
```

I tried even disabling vibration setting it to false but still no avail 
```js
const getPushToken = async () => {
   ...
      if (Platform.OS === "android") {
        Notifications.createChannelAndroidAsync("direct-message", {
          name: "Direct Message",
          sound: false,
          priority: "max",
          vibrate: false,
        });
      }
   ...
  };
```
### Environment
Expo CLI 3.20.1 environment info:
    System:
      OS: Linux 4.15 Linux Mint 19.1 (Tessa)
      Shell: 2.7.1 - /usr/bin/fish
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.21.1 - /usr/bin/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^37.0.8 => 37.0.8
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.20.1

Android, Client.
### Steps to Reproduce

This happens in my android device 8.0.0
### Expected Behavior
No psuedo vibrations.

**Comment by zifahm** [comment]
any idea on how to solve this problem?

**Comment by cruzach** [comment]
Hey @zifahm , I tried to reproduce this using [this snack](https://snack.expo.io/@charliecruzan/no-vibration?platform=android&name=Push%20Notifications&sdkVersion=37.0.0&dependencies=expo-constants%2Cexpo-permissions&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv37.0.0%2Fpushnotifications.js), but was unable to. Could you try using that snack, and if it works correctly, debug your code by taking a look at how you're handling it differently?

**Comment by cruzach** [comment]
Was able to reproduce this on android with the new `expo-notifications` module

**Comment by sjchmiela** [comment]
If I understand correctly, what you want to do is *not* to vibrate the phone (and not to show an alert) if a notification is received while the app is in the foreground.

For this purpose `NotificationHandler` has been developed, see [`setNotificationHandler` docs](https://docs.expo.io/versions/latest/sdk/notifications/#setnotificationhandlerhandler-notificationhandler--null-void). Using

```ts
import * as Notifications from 'expo-notifications';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: false,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});
```

you can tell the Notifications module not to display your notification if it is received in the foreground (if the notification is received in the background the handler will not be called and your notification will be displayed).

I'll close this issue tentatively, but if I didn't get that right feel free to reopen it!
