### ISSUE TITLE
[docs] PLEASE include the proper versions of supported packages per Expo version

### ISSUE THREAD

**Issue by Slapbox** [expo/expo#8129]
`expo install` does not work for us in a monorepo ~~which leaves us with no way to find out what version of `@react-navigation` packages we need except to `expo init` a new project, then `yarn` then `expo install [whatever packages]`.~~

Edit: I'm dumb and this isn't as bad as I had thought - but it would be really nice to be able to find the correct versions listed alongside the releases. I feel like this used to be done with prior SDK blog announcements.

This issue [_persistently_](https://github.com/expo/expo-cli/issues/1804#issuecomment-608645761) makes trouble for us with a mono-repo and while there's a workaround, the packagification of the ecosystem and the time involved in running yarn/rebuilding via metro bundler is quite substantial. Screw up one package and you're in for another 10 minute run through those two things.

**Comment by Slapbox** [comment]
# What normal people can do:

- `expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view`
- `expo start` and wait 6-7 minutes

# What we have to do

- `cd C:\projects`
- `expo init someProject`
- `expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view` (Couldn't detect Expo SDK installed)
- `yarn` (because `expo init` says it's installing packages but apparently doesn't)
- `expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view`
- Wait for install and open `package.json`
- Copy relevant dependencies from dummy project's `package.json` to actual project's `package.json`
- Run `yarn` on actual project
- Finally `expo start` and wait 6-7 minutes

**Comment by Slapbox** [comment]
# End result:

**Time:** ~25 minutes
**Package we needed:** `react-native-safe-area-context@0.7.3`

**Comment by Slapbox** [comment]
A possibly better alternative would be a command line flag that updates the `package.json` in that directory without running any actual `yarn/npm` installations.

**Comment by cruzach** [comment]
thanks, that's a good point and we should add it to the docs

In the meantime- you can find the list of version supported by the sdk by looking at the `bundledNativeModules.json` file on the `sdk-xx` branch (where xx is the sdk version)

this is for sdk 37:
https://github.com/expo/expo/blob/sdk-37/packages/expo/bundledNativeModules.json

**Comment by Slapbox** [comment]
That is super helpful! Thank you @cruzach!
