### ISSUE TITLE
abi37_0_0.com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by HMellor** [expo/expo#8130]
### Environment

Expo CLI 3.20.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.8 => 37.0.8
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-navigation: ^4.1.0 => 4.3.8

Targeting both Android and IOS

### Steps to Reproduce

Using the [`atob` workaround](https://stackoverflow.com/a/60386964/10880714) to use Firebase Firestore I am able to interact with Firestore. But after using the app for a short time afterwards the app crashes (length of time varies).

### Expected Behavior

App should not crash

### Actual Behavior

The app crashes with the following error on the device:
```
abi37_0_0.com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
```

**Comment by sjchmiela** [comment]
Hey @HMellor, I'm sorry you experience this bug. Do you have any more error information coming from the crash? The `cannot be cast` is a generic bug and it's difficult to guess where it's coming from. If you had a stacktrace that would be extremely helpful!

**Comment by HMellor** [comment]
The only place I can see any detail on the error is on the device itself:
![Screenshot_20200504-142524_Expo](https://user-images.githubusercontent.com/19981378/80970791-a317f300-8e13-11ea-9bc8-c974ffd7b5b1.jpg)

**Comment by sjchmiela** [comment]
Hm, unfortunately this looks like a native problem and to debug it we'll need a native stacktrace. Do you feel comfortable using Android Studio? It includes the `logcat` tool which should make it easy to find the stacktrace — https://developer.android.com/studio/debug/am-logcat

If not, would you be able to provide us with a [Snack](https://snack.expo.io/) reproducing the issue?

**Comment by HMellor** [comment]
Unfortunately I think I'd need to give you access to a Firebase Firestore to make a useful Snack. I'll try Android Studio and get back to you. Thanks

**Comment by banjianpan** [comment]
Did anyone figure this out? or is this problem fixed?

**Comment by banjianpan** [comment]
I currently also experiencing this problem. When accessing my firestore, after about 1 minute and 7 seconds, I get the same error as above

**Comment by sjchmiela** [comment]
FWIW it looks like newer releases of Firebase should have this issue fixed — https://github.com/firebase/firebase-js-sdk/issues/2667 🥳
