### ISSUE TITLE
Updates.checkForUpdateAsync is not available on ios

### ISSUE THREAD

**Issue by gurkanguran** [expo/expo#8133]
### Environment

Expo CLI 3.15.4 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.19.0 - /usr/local/opt/node@10/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.15.4

The app's target : iOS Standalone

### Steps to Reproduce

- Implement Updates.checkForUpdateAsync method in a way that it will work after returning to the application from background.
- Deploy your react native expo app to iOS test flight. 
- Run the application.

### Expected Behavior

Updates.checkForUpdateAsync should have worked properly.

### Actual Behavior

I am receiving the following error in Senty 
**Error: The method or property Updates.checkForUpdateAsync is not available on ios, are you sure you've linked all the native dependencies properly?**

### Reproducible Demo

I don't know the issue is reproducible in expo client. I cannot provide anything as i am running into this issue with standalone ios app.

### Code block that throws the error

```
export const checkOTAUpdatesAsync = async () => {
  const update = await Updates.checkForUpdateAsync();
  if (update.isAvailable) {
    await Updates.fetchUpdateAsync();
    await AlertAsync(
      i18n.t('NewVersionAvailable'),
      i18n.t('NewVersionAvailableDescription'),
      [
        {text: i18n.t('Ok'), onPress: () => Updates.reloadAsync()},
      ],
      { cancelable: false },
    );
  }
};
```

**Comment by byCedric** [comment]
Hi @gurkanguran, thanks for the issue report! This one is a bit hard to debug, do you know how you've installed or setup `expo-updates` for your project? It looks like something is up with the native code. It helps to debug this if you can create a small repro with this issue, that way we can start testing it instantly 😄

**Comment by elon-gs** [comment]
I get the exact same error on Android.  I used 'expo install expo-updates' to install it.

`[Error: The method or property Updates.checkForUpdateAsync is not available on android, are you sure you've linked all the native dependencies properly?]`

**Comment by kalliub** [comment]
I'm having a very similar problem. My Android Updates lib works properly.

In my case, I'm importing "Updates" like documentation says, like this:
```JS
import * as Updates from 'expo-updates' 
```
So here goes what happened to me:
Published version 1.4 of my app with these new changes (adding manual OTA updates) and it was working 100% on Android. I went to iOS to make some tests and my app installs v1.3.7 from the App Store (which is its last version there), but I've got a brand new v1.4.

The problem was: From 1.3.7 to 1.4, automatic OTA update works properly. After I added this manual updates, iOS stops on the last 1.4 update, and I couldn't get out of this version via OTA, for example a new 1.4.X version.

Also, still gotta use Sentry to see if there's anything on the logs on production.

Well, maybe could this be the same problem?

**Comment by oporter1** [comment]
I am having the same issue. I have tried: `expo install expo-updates`, `npm install expo-updates`, 'npm add expo-updates` and keep getting error: `Error: The method or property Updates.reloadAsync is not available on ios, are you sure you've linked all the native dependencies properly?` I can see that they are installed correctly and linked in my package.json. Not sure what's up with this...

**Comment by bcarradini** [comment]
From the [expo-updates documentation](https://docs.expo.io/versions/v38.0.0/sdk/updates/):
```
Most of the methods and constants in this module can only be used or tested in release mode; they do not make sense in debug builds where you always load the latest JS from your computer while developing. To test manual updates in the Expo client...
```
It looks like `NativeModulesProxy.ExpoUpdates` just isn't set up to work in development. See the documentation for details on how this can be tested with a published version of your app.

**Comment by Ozaoujal** [comment]
2024 and still getting the same error as above
