### ISSUE TITLE
[Bare Workflow] [Expo-Notifications] App closes when receiving Notification

### ISSUE THREAD

**Issue by joaocosta9** [expo/expo#8141]
Hello !
I recently ejected from managed workflow to bare, and I have been having problems with Push Notifications in android. I already followed the steps in the documentation (integration with FCM ...). And I'm already receiving a token, that I think it's correct. This is the code I'm using to get it
```
`import * as Notifications from "expo-notifications";

registerForPushNotificationsAsync = async () => {
    let experienceId = "@joaocosta9/telepathy";
    let token = await Notifications.getExpoPushTokenAsync({
      experienceId: experienceId
    });
    console.log("this is my token " + JSON.stringify(token));
  };`
```
Im calling the registerForPushNotificationsAsync in ComponentDidMount. The problem is, when I try to send the notification to my physical device using the Push notifications tool, the app immediatly crashes and I don't receive the notification. Does anyone know what this is or can be?
Thanks!!!

**Comment by awinograd** [comment]
This is the same behavior I'm seeing in my app due to the crash described in https://github.com/expo/expo/issues/8142

**Comment by sjchmiela** [comment]
Hey @joaocosta9! Please try upgrading to `expo-notifications@0.1.5` — it should fix the problem. 🙂
