### ISSUE TITLE
Constants.installationId changes after update on Android with SDK 37

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#8145]
Hi guys, 
Today I detected an error that is affecting applications that run on android. 
`Constants.installationId` changes after application update but push token is preserved, possibly this is something related with the `SDK37`, since I didn't detect this type of cases with the previous SDK.

Any advice? thanks !!!

BTW: im ussing the following dependencies (at the time of standalone build):

```
expo: "37.0.7"
react-native: "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz"
```

**Comment by cruzach** [comment]
Is this in the bare workflow, or managed? If it's in the managed workflow, it would help to know if this happens in standalone APKs or in the Expo Client app

**Comment by outaTiME** [comment]
@cruzach its happen on managed workflow in standalone mode

**Comment by cruzach** [comment]
@outaTiME I just tested this by upgrading a project initialized on SDK 36 (`expo init -t blank@sdk-36`), building the apk, installing it, then upgrading that project to sdk 37 with `expo upgrade`, rebuilding, and installing on the device. The `installationId` remained the same across the upgrade

**Comment by outaTiME** [comment]
yup i did the same flow that you mention, the main difference is the update was through the play store.

When you load my standalone app, i save `installationId` and push token from device to database and i have two entries for the same device after the update 

(with different `installationId` but with same push_token), 

here the records:

```
+--------------------------------------+-------------------------------------------+
|           installation_id            |                push_token                 |
+--------------------------------------+-------------------------------------------+
| 5da9d7eb-9854-4b14-b89f-28d56c28e03c | ExponentPushToken[rEcDq-NUqVIBDFBhGmBYHH] |
| b0db7a69-f418-4ddc-a243-adddae1a7443 | ExponentPushToken[rEcDq-NUqVIBDFBhGmBYHH] |
+--------------------------------------+-------------------------------------------+
```

**Comment by cruzach** [comment]
I tested this through the Play store as well, and still get the same installation Id. Are you sure you aren't uninstalling the app between updates?

**Comment by outaTiME** [comment]
Its really wired, i’m pretty sure I didn't reinstall, I will continue to check in more detail

**Comment by cruzach** [comment]
@outaTiME were you able to get more information on this?

**Comment by outaTiME** [comment]
hello @cruzach, in the meantime I did not have much time to verify, but for the moment I did not detect any more cases

**Comment by cruzach** [comment]
okay, then I'm going to close this issue for now but if you're able to reproduce the issue definitely let me know 🙂
