### ISSUE TITLE
keep-awake : error with RN.62

### ISSUE THREAD

**Issue by GManzato** [expo/expo#8147]
### Environment
```
  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.2.0 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
    npmGlobalPackages:
      expo-cli: 3.19.2
```

Target iOS , using react-native-unimodules

### Steps to Reproduce

- add react-native-unimodules
- add expo-keep-awake
- import expo-keep-awake
- add `activateKeepAwake();`

### Actual Behavior

<img width="464" alt="Screenshot 2020-05-05 09 22 05" src="https://user-images.githubusercontent.com/1064904/81027878-e88afd80-8eb1-11ea-99f6-ac6f7680b5f5.png">

### Reproducible Demo

I've created a repo with the issue ( [https://github.com/GManzato/ReproKeepAwake](https://github.com/GManzato/ReproKeepAwake) )

**Comment by brentvatne** [comment]
here's an example of it working with 0.62: https://github.com/brentvatne/issue-8147

you might want to double check the react-native-unimodules config to make sure that you did it all correctly. you can compare it against the one in the project.

to create this project i just did expo init and chose typescript template, then i followed the upgrade steps (just for ios, as per the screenshot above) except for flipper. https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.2
