### ISSUE TITLE
[expo-google-app-auth] Not recognising clientId after upgrade to expo 37

### ISSUE THREAD

**Issue by He1nr1chK** [expo/expo#8149]
### Environment

Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yvm/shim/yarn
      npm: 6.14.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.8 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.1

I upgraded to Expo 37 and the bare workflow from Expo 36 and Expokit

### Steps to Reproduce

Upgrade to bare workflow 

### Expected Behavior

The package should accept my credentials (clientIds) and show an alert asking whether I want to sign in with google.

### Actual Behavior

Before upgrading the Google sign in was working perfectly. After upgrading however I get the error `Error: Please provide the appropriate client ID. See the documentation for more details https://docs.expo.io/versions/latest/sdk/google/#loginasync
`

### Reproducible Demo

```
signInWithGoogle = async () => {
        try {
            const result = await Google.logInAsync({
                androidStandaloneAppClientId:
                    '7234***8644-************.apps.googleusercontent.com',
                iosStandaloneAppClientId:
                    '7234***8644-************.apps.googleusercontent.com',
                scopes: ['profile', 'email'],
            })

            if (result.type === 'success') {
                this.onGoogleSignIn(result)
                return result.accessToken
            } else {
                return { cancelled: true }
            }
        } catch (e) {
            console.log(e)

            return { error: true }
        }
    }
```

The client ids are unique for both Android and iOS.

**Comment by cruzach** [comment]
this is probably due to [this line](https://github.com/expo/expo/blob/master/packages/expo-google-app-auth/src/Google.ts#L91) since appOwnership is falsey in bare workflow. I'm guessing the Android workflow works correctly? if so, we should change
```
Constants.appOwnership === 'standalone'
```
to 
```
isInExpo
```

**Comment by He1nr1chK** [comment]
Hi @cruzach,

Thank you for the response. This might be a stupid question but where/how would I make the change?

**Comment by cruzach** [comment]
can you confirm that your code works on android?

For a PR, the change you would make is in the file I linked above ^ then in the `packages/expo-google-app-auth` directory, run `yarn build`

**Comment by deathemperor** [comment]
I got into this same problem but kind of opposite. My app is managed by expo, but the apk build got `Constants.appOwnership` as `standalone`. Now I have to configure client id for but androidClientId and androidStandaloneAppClientId. I guess it's the same for iOS.

for dev the appOwnership is NOT standalone.

**Comment by cruzach** [comment]
Constants.appOwnership should be standalone for apk builds - https://docs.expo.io/versions/latest/sdk/constants/#constantsappownership

**Comment by deathemperor** [comment]
> Constants.appOwnership should be standalone for apk builds - https://docs.expo.io/versions/latest/sdk/constants/#constantsappownership

this is quite confusing. In development it's `expo` and will continue to be `expo` for good. but apk build is `standalone`. It took me some hours to debug this.

**Comment by cruzach** [comment]
Hm.. what's confusing? In the docs for that field, we state 
> If `expo`, the experience is running inside of the Expo client. If `standalone`, it is a standalone app.

and link to documentation describing what constitutes a standalone app

**Comment by deathemperor** [comment]
the confusing part is all the time I have to import both config or it won't work for one of the client. If that could be written right on the docs page (code example with both configs), it would reduce the time to investigate. Especially for newcomers.
