### ISSUE TITLE
BarCodeScanner doesn't appear to scan interleaved2of5 format as described in the documentation

### ISSUE THREAD

**Issue by str0kes** [expo/expo#815]
As per the docs at https://docs.expo.io/versions/latest/sdk/bar-code-scanner.html the BarCodecanner doesn't appear to scan the interleaved2of5 format as described in the documentation.

I've tried using a couple of barcode generators such as https://manateeworks.com/free-barcode-generator and https://racoindustries.com/barcodegenerator/1d/interleaved-2-of-5/ but the scanner doesn't read them.

Can anyone confirm this is working as intended? Many thanks

**Comment by aalices** [comment]
Hello, sorry you had to wait so long. Seems that you're kinda right about this. Android recognizes only ITF-14 which is an implementation fo Interleaved 2 of 5, and iOS recognizes both but sometimes classifies a ITF-14 as just interleaved 2 of 5. I'll update the docs. Thanks!
