### ISSUE TITLE
how to get the angle of camera

### ISSUE THREAD

**Issue by ElMaghri** [expo/expo#817]
hello for a while I start to develop an application of realityme with React native and part of the application I have to open the cam and test if a GPS point (already predefined) enter the field of view or not
my approach is :
1.  find my position
2.  find the direction of my camera
3. calculate the angle of view of my camera
4. test whether a point falls in this angle or not.

Then my question is how can I have the camera angle? ,and how to determine the direction of vision of the camera?

**Comment by dikaiosune** [comment]
Hi! This kind of question is usually better to ask on our forums. We try to keep GitHub focused on bug reports. You might be able to make this work using one of these APIs:

https://docs.expo.io/versions/latest/sdk/devicemotion.html
https://docs.expo.io/versions/latest/sdk/accelerometer.html
https://docs.expo.io/versions/latest/sdk/gyroscope.html
