### ISSUE TITLE
Expo log as json in terminal

### ISSUE THREAD

**Issue by blackherohd** [expo/expo#8172]
Recently when I run expo in terminal, it show log as json, it hard to read.
I already uninstall & reinstall expo as v3.20.1 and v3.12.0, but it is nothing change. Both of two version working good in another PC.

Windows 10
Node v13.14.0
NPM v6.14.4
Expo v3.20.1 & v3.12.0

![Annotation 2020-05-06 150805](https://user-images.githubusercontent.com/29324851/81151520-45b6aa00-8fab-11ea-81a7-7ea1035bb43f.png)

**Comment by byCedric** [comment]
Hi @blackherohd! It looks like our internal [log debugger is somehow enabled for you](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Logger.ts#L21). Could you check for me if the `DEBUG` environment variable is set to a non-empty value? You should be able to get rid of this by un-setting the `DEBUG` env variable.

Hope it helps!

**Comment by blackherohd** [comment]
It solved, thank @byCedric, I have a User env variable name is DEBUG for module npm debug.
CLOSE!
