### ISSUE TITLE
Release Build Crashes while Debug App Works Fine

### ISSUE THREAD

**Issue by mashuk999** [expo/expo#8173]
### Environment

  Expo CLI 3.20.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.0 => 37.0.8
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: 0.61.4 => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7

Target : Android

### Steps to Reproduce

Debug App is working fine. But when I made the release build using `npx react-native run-android --variant=release` the app crashes at startup.

### Expected Behavior

App should not crash at beginning.

### Actual Behavior

Crash at startup.

### Reproducible Demo

I am using bareworkflow. I have installed lottie-react-native v3. I have also followed the lottie documentation for auto linking failed but nothing  #works.

**Comment by cruzach** [comment]
My guess is that your app doesn't have the JS bundled with it. Have you run `expo publish` at least once before building? Have you followed the guide [here](https://docs.expo.io/bare/updating-your-app/) for configuring `expo-updates`?

**Comment by mashuk999** [comment]
I did but still the release app is crashing.

**Comment by mashuk999** [comment]
Here's the link of project i am trying to build.
https://github.com/mashuk999/corona-chest-scan-mobile

**Comment by brentvatne** [comment]
hey! try following the instructions from https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf?source=collection_home---6------0----------------------- to switch over to the new way of doing updates in bare apps. let me know if this doesn’t work for you again and i will clone your project and help out

**Comment by mashuk999** [comment]
ok i am trying this . Thanks 👍

**Comment by hanselsen** [comment]
> hey! try following the instructions from https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf?source=collection_home---6------0----------------------- to switch over to the new way of doing updates in bare apps. let me know if this doesn’t work for you again and i will clone your project and help out

I tried this and I love the way it should work, but it is not able to create a release APK.
- First I did `expo init` and used Bare Workflow.
- Then following RN way of creating a signed APK
- Use `gradlew installRelease`

It returns with the error `connect ECONNREFUSED 127.0.0.1:8081`.
This seems to be a problem with the Metro builder, but every cache clear, reboot, reinstallation of packages, does not work.

**Comment by joeldixon66** [comment]
@hanselsen I think you might be having a different issue, one which I am also experiencing. If I generate a signed bundle via Android Studio I receive the `connect ECONNREFUSED 127.0.0.1:8081` error that you listed. If I try to perform the build while a separate Metro instance is running (started via `npx react-native start`) the Metro crashes with `Error: EPERM: operation not permitted, ...` shortly after I kick off the build.

I've found that if I kick off the build in Android Studio, wait for my Metro instance to crash and then quickly restart it with `npx react-native start` I get a successful build with bundled resources. Certainly not a desirable setup, but at least I was able to release my app.

**Comment by nebmesemaou** [comment]
advice for the metro bundle crash

`
cd android && gradlew clean && cd ..
`

**Comment by hanselsen** [comment]
I've noticed that it needs a running metro bundler, but it crashes sometimes during this process.
That's why I built a script that keeps metro running forever. It is not pretty, but it works like a charm.
Ps. It's only Windows at this point.

```
const { spawn, exec } = require("child_process");
const fs = require('fs');

const lockFile = './metro.lock';
if(fs.existsSync(lockFile)) {
  const pId = fs.readFileSync(lockFile);
  killProcess(pId);
}
const lock = fs.openSync(lockFile, 'w');
fs.writeSync(lock, `${process.pid}`);
fs.closeSync(lock);

async function start() {
  console.log('Starting metro bundler...');
  await killMetro();
  const metro = spawn("react-native.cmd", ["start", "--reset-cache"], {
    stdio: [process.stdin, process.stdout, process.stderr]
  });
  metro.on("close", code => {
    console.log();
    console.log(`Metro bundler exited with code ${code}`);
    console.log();
    start();
  });
}
function killMetro() {
  return new Promise(res => {
    exec('netstat -ano | find "LISTENING" | find "8081"', (err, o) => {
      try {
        if (o) {
          console.log('Metro was running, killing now');
          const pId = o.split('LISTENING')[1].split('\n')[0].trim();
          killProcess(pId).then(res);
        } else {
          res();
        }
      } catch (e) {
        res();
      }
    });
  });
}
function killProcess(pId) {
  return new Promise(res => {
    exec(`taskkill /F /PID ${pId}`, (err2, o2) => {
      console.log(`${o2}`);
      res();
    });
  });
}

start().then();
```

**Comment by brentvatne** [comment]
if you update to the latest version of expo-updates it should not be necessary to have metro running during the build process. we will start metro programmatically when needed in order to generate the required metadata. i’m afk at the moment but i believe this fix was published 18 days ago

**Comment by hanselsen** [comment]
I do hope it is fixed. Good job guys.
In my case though, it did start metro programmatically, but it crash and did not restart. Hope this is fixed then.

**Comment by AND-GORNIY** [comment]
Had this issue, just updated reanimated to the last version, and it is gone.
