### ISSUE TITLE
App is navigating to the initial route twice on load of ejected app (expo kit)

### ISSUE THREAD

**Issue by AhadCove** [expo/expo#818]
I'm having an issue using react-navigation after the app has been ejected.
Using a stack navigator I'm getting the initial route being loaded twice on load of my app.

This is an expo kit react native ejected app. I tried to make a new app without ejecting it and seen that it was working perfectly fine, but as soon as I ejecting it and loaded it back up, it started doing the same thing as my other ejected app. I even tested ejecting completely with just plain react native and it still worked perfectly. It's only when I eject to expo kit.

What it's doing is mounting the initial component and then navigating to the same initial component immediately. It even will allow me to go back which is the exact same component I was on.

**Comment by davepack** [comment]
Hi, this is a known issue with react-navigation. 

The issue is here: https://github.com/react-community/react-navigation/issues/2599 

And there is a workaround here in this comment that you can try: https://github.com/react-community/react-navigation/issues/2599#issuecomment-337845786

**Comment by AhadCove** [comment]
Hey @davepack is there any explanation as to why this happens?
