### ISSUE TITLE
[docs] iOS build asks for Archive vs Simulator build, not documented

### ISSUE THREAD

**Issue by vjsingh** [expo/expo#8180]
After upgrading to SDK 37 and the latest expo-cli, when I run expo build:ios, it asks whether I want an archive or simulator build. I can't find any note of what this means in the docs, forums, or google.

**Comment by byCedric** [comment]
Hi @vjsingh! We try to explain the differences in that menu too. It's a bit hidden, but it should also be explained [on this page](https://docs.expo.io/distribution/building-standalone-apps/#5-test-it-on-your-device-or). To summarize:
- If you want to test your iOS build on a Simulator, you can't use the archive. Instead, you have to build it specifically for Simulators.
- If you want to publish your iOS build to the store, you have to build the archive.
Where do you think this would be the best place to document in the docs?

**Comment by vjsingh** [comment]
Hey @byCedric ! Thanks for the response.

I would expect it to be next to [this section](https://docs.expo.io/distribution/building-standalone-apps/#if-you-choose-to-build-for-android). 

> **If you choose to build for Android**
When building for android you can choose to build APK (expo build:android -t apk) or Android App Bundle (expo build:android -t app-bundle). 

You could have another section called "If you choose to build for iOS".

Also, just a note that I find the naming of these different options ("APK / App Bundle" and "Simulator / Archive") somewhat confusing 😛

**Comment by byCedric** [comment]
Done, thanks for the tip! I get your confusion, but I think we want to be as close as possible to the official names. While they might be a bit confusing, it's actually what they are called by Apple and Google 😄 I'm not sure if we can tweak the short messages in the menu to describe better what they are?

**Comment by vjsingh** [comment]
Ah! Apparently the short messages don't show up on my terminal for some reason. Those descriptions would have resolved my issue entirely.

For some reason the messages only show up when I highlight the text. I'm using iTerm2 with a dark background. (Second command is highlighted below)

<img width="741" alt="Screen Shot 2020-05-07 at 3 59 47 PM" src="https://user-images.githubusercontent.com/318312/81339265-dc529c00-907b-11ea-8347-bfa725e3794a.png">

**Comment by byCedric** [comment]
Ah, that's interesting, let me try to reproduce that. It might be related to our `dimmed` settings for the text. Do you know what theme or color scheme you are using?

**Comment by vjsingh** [comment]
@byCedric Not sure if this is helpful or not. Using iTerm2

<img width="1616" alt="Screen Shot 2020-05-11 at 8 49 38 AM" src="https://user-images.githubusercontent.com/318312/81563640-85dbab00-9364-11ea-8422-e1b78f0dd0e9.png">
