### ISSUE TITLE
Font.loadAsync on web causes Text using already loaded custom fonts to briefly disappear

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8186]
While playing with the @expo/vector-icons website I noticed that in some cases all of the icons on the page would flash. At first I thought this might be due to some unnecessary re-rendering happening and components being remounted, but it turns out that this seems to be caused by `expo-font`.

### Steps to Reproduce

- Clone https://github.com/brentvatne/web-font-flash-repro
- Run it on web
- Hit the button, notice that for a frame or so the "Example one" text disappears even though neither it or its parent component are re-rendered (uncomment alerts to verify)

Video: https://streamable.com/4ktzbc
Screenshots:
<img width="800" alt="Screen Shot 2020-05-06 at 4 38 04 PM" src="https://user-images.githubusercontent.com/90494/81239023-7c46f180-8fb8-11ea-82c0-7dace854799a.png">
<img width="800" alt="Screen Shot 2020-05-06 at 4 38 10 PM" src="https://user-images.githubusercontent.com/90494/81239030-823cd280-8fb8-11ea-84d1-a99d0659aa51.png">
<img width="800" alt="Screen Shot 2020-05-06 at 4 38 15 PM" src="https://user-images.githubusercontent.com/90494/81239031-849f2c80-8fb8-11ea-8bbf-5f0a258be843.png">

**Comment by EvanBacon** [comment]
This is a platform limitation, there is no good way to detect if the font has loaded so isReady is prematurely set to true. We provide a method for adding the CSS font face directly to your index.html if needed. We also support the font display parameter now as well https://docs.expo.io/versions/latest/sdk/font/#fontdisplay
