### ISSUE TITLE
Expo app stops my internet working

### ISSUE THREAD

**Issue by barnu5** [expo/expo#8189]
NB: I don't yet have a repro demo so I understand it will be hard to work on this issue. I may update with required info as I am able to. 

It's just such a weird bug.

## 🐛 Bug Report
Somehow, a React Native expo app causes my local internet to break. 

### Environment
- In an ejected Expo app
- Running on WSL (Ubuntu)
- 

```
  Expo CLI 3.20.1 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
```

Bare workflow

### Steps to Reproduce
- A few minutes after app start, my laptop (Windows) internet cuts out. Websites say "this page cannot load"
- I can continue to develop OK on the Expo app meanwhile
- Internet is broken until I stop the Expo app
- This did not happen before `expo eject`. 
- Have not pinned it down to any specific code yet, working on that

### Expected Behavior
- Some kind of error is thrown

**Comment by byCedric** [comment]
Hi @barnu5! That's unfortunate, what version of Windows or WSL are you using? Could it be related to [this issue](https://github.com/expo/expo-cli/issues/99#issuecomment-562804479)? We had a similar report that eventually was caused by some bugs in WSL (before Windows Insider Build 18890). Hope it helps!

**Comment by barnu5** [comment]
Hi @byCedric 

Yes, this is a similar issue.

I'm using Microsoft Windows [Version 10.0.18363.815] and WSL 1

I'm not using the insider's build, I have the latest version available. Maybe I can look at getting insider's build. 

[The suggested fix `use command prompt` is not an option due to this issue. ](https://github.com/expo/expo-cli/issues/1974)

I also have a slightly better workaround - 

1. Open powershell as admin
2. `Get-Service LxssManager | Restart-Service`

This kills all WSL processes and makes everything work again.

Problem is, this occurs every 5-10 mins so I'm constantly restarting!

I will look at insider's build meanwhile.

**Comment by byCedric** [comment]
Thanks for the additional info and workaround 😄 I don't think this is something we can fix, Microsoft has to release a new version of WSL for this fix. But, to finish this with _some_ positive notes; I'm running WSL2 with the Insider build 19041.208, and that runs pretty well (also with plain React Native dev). The only issue I have is the [memory usage issue](https://github.com/microsoft/WSL/issues/4166), but restarting WSL with `wsl --shutdown` releases the memory. I have to do that once every couple of hours or so.

Hope this is fixed soon by Microsoft 😄

**Comment by isavega** [comment]
https://github.com/expo/expo-cli/issues/99
