### ISSUE TITLE
on Android: Error while updating property 'borderRadius' of a view managed by: RCTView 

### ISSUE THREAD

**Issue by jpca999** [expo/expo#819]
Didnt test on the android since i uploaded he Expo sdk  21. 
I get this error now.. 
![image](https://user-images.githubusercontent.com/1026325/31835635-5a1b4f74-b5a0-11e7-808c-25ac7b3a7d79.png)

**Comment by brentvatne** [comment]
it looks like you are passing a string to the `borderRadius` property somewhere, when it should be a number

**Comment by jpca999** [comment]
@brentvatne how do i figure where is it happening ?  I search borderRaidus for whole project didnt found it.

**Comment by EvanBacon** [comment]
@jpca999 did you try searching for `borderRaidus` or `borderRadius`?

**Comment by jpca999** [comment]
borderRadius

**Comment by brentvatne** [comment]
perhaps inside of some library that you use, you can try removing pieces and narrowing the error down until you find the library

**Comment by terribleben** [comment]
Hi, as far as I can tell this is an issue with the project's JS (or that of a third party library you've included). Closing since it doesn't seem to be a problem with Expo. Feel free to ask for more help on the [forums](https://forums.expo.io) if you're still stuck.

**Comment by HenokTes72** [comment]
You have to give a value of type double not a string in borderRadius, "50%"  to  50.
