### ISSUE TITLE
[template] expo-template-tabs produces broken test

### ISSUE THREAD

**Issue by matthewmcgarvey** [expo/expo#8198]
## 🐛 Bug Report

The `App-test.js`in expo-template-tabs imports `AppNavigator` rather than `BottomTabNavigator`.

Reference:
https://github.com/expo/expo/blob/634d509d9147297491ae7524a587fd595d7e6fc1/templates/expo-template-tabs/__tests__/App-test.js#L11

It also imports a `NavigationTestUtils` which is no longer valid:
https://github.com/expo/expo/blob/634d509d9147297491ae7524a587fd595d7e6fc1/templates/expo-template-tabs/__tests__/App-test.js#L2

### Steps to Reproduce

```bash
expo init testproject
# choose the tabs option
cd testproject
npm test
```

### Expected Behavior

The tests should pass

### Actual Behavior

The tests fail

**Comment by brentvatne** [comment]
hello! i released an update for the tabs template so there is no longer a failing test - i actually removed the root level snapshot test because it's not actually useful in my opinion.
