### ISSUE TITLE
Infinite error loop when trying to open a non-existing app from clipboard

### ISSUE THREAD

**Issue by dikaiosune** [expo/expo#82]
Moving https://github.com/react-community/create-react-native-app/issues/50 here:

> Not sure if this should go here or somewhere else but on the iOS mobile app when I try to open an app from clipboard that doesn't exist I get an error which is expected because it doesn't exist, but my only option is to Try Again. The only way to exit this screen is to close the app.

cc @brentvatne

**Comment by dikaiosune** [comment]
Also cc @timurtu

**Comment by brentvatne** [comment]
Added "Go back to Expo Home" button for any error screen except in standalone apps.

<img width="487" alt="screen shot 2017-05-31 at 3 08 31 pm" src="https://cloud.githubusercontent.com/assets/90494/26656213/098b21b2-4613-11e7-89af-0d88e1f17428.png">

**Comment by timurtu** [comment]
Cool appreciate it
