### ISSUE TITLE
Uncaught Eror: java.net.connectException: failed to connect to localhost/127.0.0.1:19000

### ISSUE THREAD

**Issue by jpca999** [expo/expo#820]
![image](https://user-images.githubusercontent.com/1026325/31838101-54567754-b5a9-11e7-9389-75d134625dc2.png)

![image](https://user-images.githubusercontent.com/1026325/31838148-73273d44-b5a9-11e7-9762-5eeec36e02d7.png)

![image](https://user-images.githubusercontent.com/1026325/31838154-7746509a-b5a9-11e7-97dc-f9e0ab7182df.png)

![image](https://user-images.githubusercontent.com/1026325/31838208-b730baa6-b5a9-11e7-97c5-44fe51d0ebdd.png)

**Comment by davepack** [comment]
Hi @jpca999, we have a forum where Expo employees and other helpers are able to help you debug your code. By creating an issue here you are missing out on a lot of additional people who could help you out. This github repo is only for reporting issues you have found in Expo. When you have troubles with Expo, you should first post in the forums, which is always our priority and the first place Expo employees go for helping people out. I'm going to close this issue, but please go to [the Expo forums](https://forums.expo.io/c/help) and post your question there. Thank you!
