### ISSUE TITLE
Expo reload doesn't work in iOS

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#821]
Hi guys im getting this issue from SDK 21, the manual refresh doesn't work running Expo on iOS here a example video ... i need to kill Expo and open again to take the changes:

> Take a look the header color it must be red but refresh keep in blue until kill and open expo

![2017-10-20 18_01_28](https://user-images.githubusercontent.com/140472/31841644-bea71f02-b5c0-11e7-87cc-79e2c6368ec0.gif)

**Comment by davepack** [comment]
Hi can you repost this in https://forums.expo.io/c/help. Until we can verify this is an issue with Expo, the forums are the best place to get help debugging. It would also help if you could add code that reproduces the problem, using https://snack.expo.io is very helpful in debugging problems.

**Comment by terribleben** [comment]
Hi, following up here, I think this is a legitimate bug report and I've fixed it here: https://github.com/expo/expo/commit/5ce8c08741218c2560a5c5e3810f2576537c1123

Sorry I didn't see this thread before.

**Comment by outaTiME** [comment]
Awesome @terribleben thanks !!!
