### ISSUE TITLE
expo-image-picker not opening in 1 out of 6 cases with exact same code

### ISSUE THREAD

**Issue by cdelacombaz** [expo/expo#8213]
## 🐛 Bug Report

Hi

I am building an app where a user can take a picture with the camera or select one from the gallery. The same functions to open the camera or gallery are triggered in 3 different scenarios.

**Screens of StackNavigator**
index 0: Home
index 1: Results

**App flow**
- User captures or selects an image from the gallery.
- User is shown a modal (in my app it would be to crop the image. in the snack it's just a modal with a cancel and next button)
- On that results screen, the user can click on a 'NEW' button which will redirect him to the Home. If there is information about the previousMethod (camera/gallery) in route.params, the camera or gallery will be reopened automatically.

**Scenarios**

- Scenario 1: User goes to Home, where he can click on camera or gallery icon. This works fine on Android and iOS.
- Scenario2 **BUG HERE!!!**: User clicks on the cancel button in the modal. This should close the modal and reopen the camera or gallery, based the previousMethod. This works fine on Android. On iOS the image picker doesn't open anymore. It is literally the same code and I do not get any error message. 
- Scenario3: User clicks on 'NEW' button from the results screen which will send info about the method (gallery or camera) via route.params. It will automatically reopen the camera or gallery. This works fine on Android and iOS.

### Environment

  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      npm: 6.14.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.18.6

Development for Android and iOS

### Steps to Reproduce

Here is the Snack to reproduce the issue: https://snack.expo.io/@cdreek/b64938

1. Use an iPhone or iOS simulator
2. Select a picture from the gallery or take a new picture if you use a device
3. When you get to the screen with 'CANCEL' and 'NEXT SCREEN', click on cancel

### Expected Behavior

Step 3 / clicking on cancel should reopen the camera or the gallery, based on previous choice.

### Actual Behavior

The function selectGalleryImageHandler or takeCameraImageHandler are getting triggered as expected. But it seems that the code gets stuck at `const image = await ExpoImagePicker.launchImageLibraryAsync({
      quality: 0.4,
    });`

The app stays on the home screen, the camera or gallery do not open again and the `console.log('image')` never gets executed.

```js
  const selectGalleryImageHandler = async () => {
    const hasPermission = await verifyCameraRollPermissions();
    if (!hasPermission) return;

    setPreviousMethod('gallery')
    console.log('will launch gallery')
    const image = await ExpoImagePicker.launchImageLibraryAsync({
      quality: 0.4,
    });
    console.log('image', image.cancelled)

    if (image.cancelled) {
      return
    } else {
      setUri(image.uri);
      setCropModalVisible(true);
    }
  };
```

### Reproducible Demo

Snack: https://snack.expo.io/@cdreek/b64938

**Comment by byCedric** [comment]
Hi Cedric 😄 Thanks for the issue _and repro_! Tested it and confirm this is happening. But I think it's related to the modal. The modal has an animation that "slides" it out, which means it takes some time to fully remove itself from the screen. I tried replacing your modal with a simple `<Button title="cancel" onPress={cancelHandler} />` and the code works fine with that. Again, I'm not sure why this behavior exists but I think it's related to the modal being animated away.

There are two ways to (temporary) workaround this problem.
1. Add a timeout before calling the `onClose` in your modal component (a bit "hacky" but works)
2. Use something like [`react-native-modal`](https://github.com/react-native-community/react-native-modal) to hook into the animation timing, and execute the pickImage after the animation is completed.

Hope this helps!

**Comment by cdelacombaz** [comment]
Hey Cedric :)

Many thanks for your reply and also possible workarounds!

I tried react-native-modal but somehow `onModalHide` never executed. I finally thought of another approach. I changed animationType of the modal to `none` and it works!

Again, many thanks. I would never have found it out.

BR, Cedric
