### ISSUE TITLE
Splash API should have an option for complex iOS configuration (e.g. just accepting a XIB file)

### ISSUE THREAD

**Issue by cseelus** [expo/expo#822]
The new Splash Screen API in Version 22 works great, quite a feat if you consider the architecture of Expo (standalone) apps, thanks to the devs!

To really conform to the iOS Human Interface Guidelines, an App Launch Screen should "enhance the perception of your app as quick to launch and immediately ready for use". What this means is shown in the first image of the [HIG for the iOS Launch Screen](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/launch-screen/): One should "design a launch screen that’s nearly identical to the first screen of your app".

Apple explicitly states that "the launch screen isn’t a branding opportunity. Don’t design an entry experience that looks like a splash screen or an About window".

Some Apps (besides Apples own) off the top of my head that I think get this right:
- AirBnB
- Airmail
- Google Maps
- Instagram

I tried to implement that with Expo, but given the current limitations, you can only get this right for a certain number of devices. If we only consider Apple smartphones, if you get it right for iPhone 6-8, but it will look wrong on the iPhone 5, 5s, SE as well as 6-8 Plus.  Considering only the tablets, if you get it right on the 9.7" iPads and iPad minis, it will look wrong on the 10.5" and 12.9" iPads.

To get this done using Expo, there would be three options:
- Allow to specify a custom component as Splash Screen, which would be the easiest and cleanest way i think
- The Splash Screen API for iOS could provide options to use different sized images for portrait and landscape, currently there are 7 different iOS screen sizes i guess, which would equal 14 different sizes
- The Splash Screen API could provide another resize option "none", which together with an option "backgroundPosition": "top center" should suffice for Launch screens that only use very simple interface elements (e.g. [a blank Navigation header](http://stuff.imeos.org/persistent/splash-ios.png)) in the upper part of the screen

Any opinions on that?

**Comment by ErkanSensei** [comment]
I've alleviated this by changing the size of the toolBar in the styles to be variable with the screen size. I then took a screenshot, so my app loads right into the first page. This hasn't worked so far with iphone X unfortunately

**Comment by ide** [comment]
With the current splash screen API I wouldn’t recommend trying to replicate your app’s layout because of the implementation work you mentioned. Moving forward we might be able to accept multiple images or take a XIB file and generate the images for you, though iPhone X might be a different beast for the latter.

A custom component is conceptually the nicest approach but doesn’t work out of the box because iOS and Android need actual bitmaps to display before loading code.

**Comment by terribleben** [comment]
Hi, @ide is correct that the current API isn't designed for this use case.

In the future, the most likely outcome is that we'll just provide the option to upload whatever Interface Builder file you want, and we'll bundle that directly as your app's launch screen. We can track that improvement in this issue. Thanks for raising!

**Comment by cseelus** [comment]
A .xib file would work great, this is Apples recommended approach:

> To accommodate this, you can provide a launch screen as an Xcode storyboard or as a set of static images for the devices your app supports. Using an Xcode storyboard is the recommended approach, as storyboards are flexible and adaptable.

Providing the ability to use a specific image for each available iOS device resolution (landscape and portrait) would also work, this should be relatively easy/fast to implement. 
I think these static images would also have to be created by exp from the .xib and provided with the .ipa file?

**Comment by AdamJNavarro** [comment]
Closing this issue in favor of this Feature Request on Canny: https://expo.canny.io/feature-requests/p/app-ui-layout-as-splash-screen
