### ISSUE TITLE
AsyncStorage state is lost when ejecting

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8220]
If you have some data saved to `AsyncStorage` in your deployed managed workflow app, then when you eject and deploy that update it will search in the wrong path for the data.

**Comment by yaroslavnikiforov** [comment]
We experienced this issue after ejecting from managed to a bare workflow. 

On iOS AsyncStorage saves data in text files under `../Documents/RCTAsyncLocalStorage_V1`, but Expo saves it in `../Documents/RCTAsyncLocalStorage`. On Android RN uses SQLite to back up the AsyncStorage. The database file is `/data/data/<package_name>/databases/RKStorage`, but Expo changed it name to `RKStorage-scoped-experience-${encodeURIComponent(<experience-id>)}`.

To fix that on iOS we just renamed folder name using `expo-file-system`:

```
     await FileSystem.moveAsync({
        from: `${FileSystem.documentDirectory}/RCTAsyncLocalStorage`,
        to: `${FileSystem.documentDirectory}/RCTAsyncLocalStorage_V1`,
      })
```

On Android, it's not possible to copy or rename prefixed database with `expo-file-system` or `react-native-fs`, and you will get error 'file is not readable or movable'. So we used this solution:
[https://github.com/expo/expo/issues/2805#issuecomment-539502599](https://github.com/expo/expo/issues/2805#issuecomment-539502599)

But this, of course, should be done by expo-cli when ejecting.

**Comment by luizjr92** [comment]
Does anyone have a snippet for migrating the entire AsyncStorage on Android?

**Comment by luizjr92** [comment]
If you're reading this and thinking if there's an easy workaround, here goes nothing. (Use at your own risk)

https://gist.github.com/luizjr92/db091719f09617abc5909ba64485e395

Just make sure to replace your experience id on line 50

**Comment by valentinbourqui** [comment]
@yaroslavnikiforov There is any way to use ../Documents/RCTAsyncLocalStorage_V1 for IOS and /data/data/<package_name>/databases/RKStorage for android with expo project ? I am currently in the opposite problem. My old application is an RN project and I want to use expo for the new one. Or is it better to use eject process and have back again default RN paths ?

**Comment by rphlmr** [comment]
@valentinbourqui I was in the same use case, migrating from vanilla React Native to expo in one of my app.

You'll need that : 
```
expo-file-system
expo-sqlite
@react-native-community/async-storage (SDK 38)
```

This is how I read vanilla storage on android and ios.

Thanks to other people in this page (and their gist).

It's not the best code of the year but it works 😂

https://gist.github.com/rphlmr/8e7f864a792b67215f2e37a2cef099e3

**Comment by valentinbourqui** [comment]
@rphlmr  Thank you for your response unfortunately I was in a hurry and I fixed it differently. Just implemented a new RN project with react-native-unimodules and expo modules that I need.

But I think your answer may help many others. :)

**Comment by manjuy124** [comment]
Any update on this issue?

**Comment by manjuy124** [comment]
We also upgraded our app from Expokit to Expo SDK. After upgrading, we ran into this issue.
For now to resolve this issue on iOS, we have made [these changes](https://github.com/rt2zz/redux-persist/issues/806#issuecomment-740349529)(we are using redux-persist to persist the data).

**Comment by brentvatne** [comment]
we plan on working on this during the sdk 41 cycle

**Comment by llamaluvr** [comment]
I noticed this on SecureStore, but saw issue https://github.com/expo/expo/issues/8713 was closed in favor of this, so commenting here. I just found out (the hard way....hoo boy am I in trouble) that this is an issue when upgrading our ExpoKit 36 app to Bare on SDK 38 with our API token stored in SecureStore.'

My questions:
1) It sounds like this is potentially affects both iOS and Android, but, with respect to this API token stored in SecureStore, I only experienced the issue on Android. Is there a reason to believe that, with SecureStore, this is only a problem on Android, or should I do more digging to make sure it's not a problem for me on iOS).

2) When the solution arrives with SDK 41, when I upgrade from Bare 38 to Bare 41, should I expect my SecureStore/ AsyncStorage data to migrate over just fine, or should I expect the keys to be missing again?

Thank you!

**Comment by llamaluvr** [comment]
@luizjr92 I guess I'm going to try it now and find out, but do you have any idea if your workaround (at https://gist.github.com/luizjr92/db091719f09617abc5909ba64485e395) also works for SecureStore, or just AsyncStorage? Thank you!

**Comment by luizjr92** [comment]
@llamaluvr I have no idea if this would work for SecureStorage as well, but best of luck to you 🤞🏼. Hope this issue didn't make into production on your application like it did with mine and upset thousands of users, but it all worked out in the end.

The code on https://github.com/react-native-async-storage/async-storage/pull/559 seems like an improved version of that gist, so I'd give that a try.

**Comment by llamaluvr** [comment]
@luizjr92 thanks - ours actually did make it into production, too :-(. We have several white labels and were updating them gradually, and somehow nobody noticed for the first month, until we migrated a couple of apps with by far the largest user base, which happened to coincide with a bunch of new users from regions with 80%+ users on Android.

For anybody else considering patching SecureStore, the code in this file in the PR to fix this permanently would be key: https://github.com/expo/expo/blob/3df6eb5bc71e00915aa820b70b3a658b98d5a9ef/android/expoview/src/main/java/host/exp/exponent/utils/ScopedContext.java. You would have to read the user prefs from the scoped context and then migrate them to non-scoped. The tricky part is that the bit that reads from the scoped context is dependent on stuff in Expoview, and not nearly as easily patched in a bare application.

Thus, we decided the ship has sailed on this one. We're cleaning up the mess, but for the remaining white labels, we're co-oping the solution to migrate the session token from our previous Cordova version to ExpoKit: every time we stash the token in SecureStore on the old version, we'll also write it to a file with react-native-fs. Then on the new version, we'll check that file if there's no token in SecureStore.

**Comment by kevingarry97** [comment]
I'm using react native expo and AsyncStorage, And I want to save users token whenever he signin and if he leaves and comes back he doesn't sign in again, but when I refresh the app the information stored in Asyncstorage disappears. Want some help

**Comment by brentvatne** [comment]
@kevingarry97 - you're using it wrong 😅  you can post to issues https://forums.expo.io for help. this issue is about something else entirely.

<hr />

as of @react-native-async-storage/async-storage@1.15.0 this issue is resolved! please do the following:

- install and use @react-native-async-storage/async-storage@1.15.0 instead of using @react-native-community/async-storage (this is the old package name and will no longer be updated in the future, it will be necessary to change to the new package in sdk 41 anyhow)
- now when you eject and deploy a new version of your app, async storage data saved on your users' devices will continue to work as expected
