### ISSUE TITLE
[expo-updates][bare] assetBundlePatterns changes not reflected in build 

### ISSUE THREAD

**Issue by awinograd** [expo/expo#8221]
### Environment

I'm trying to configure assetBundlePatterns in my bare expo app. I noticed setting the value in `app.json` wasn't changing the bundled assets in my built apk. I needed to run `./gradlew clean` in order to get the new pattern to take effect. I'm guessing the caching done by `expo-updates` build script isn't accounting for "stale" assets.

### Steps to Reproduce

1. set assetBundlePatterns to `**/*`
1. expo publish --target bare
1. build apk
1. decompile apk and note that all assets are bundled in `apk` as expected
1. set assetBundlePatterns to a subset of all assets
1. expo publish --target bare
1. build apk. (note manifest's bundledAssets has correct subset of assets)
1. decompile apk and note note that bundled assets haven't changed in apk

### Expected Behavior

Only assets matching `assetBundlePatterns` should be included in second apk

### Actual Behavior

All assets present in first build are included in second apk.

### Reproducible Demo

If the issue isn't apparent, I can create a repro, just let me know

**Comment by esamelson** [comment]
Hey @awinograd ! Thanks for the report. We've recently changed the build/embed process for apps with `expo-updates` to be more similar to normal RN apps -- now, the embedded JS is generated on-the-fly during the build process and all required assets are embedded. [See this post for more details.](https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf)

I just tested and this issue is no longer present in the new workflow -- if I import an asset in my JS and make a release build, then comment out the import and make a new release build, the build no longer contains the asset.

Will this work for your use case?

**Comment by awinograd** [comment]
@esamelson, yes it does sound like the new behavior in 0.2.0 solves the issue I describe here. I haven't yet upgraded and verified the fix on my end, but I'm sure it works as expected!

Feel free to consider this closed. I'll end up upgrading at point down the road...

**Comment by esamelson** [comment]
Cool, I'll close this for now but can reopen if it remains an issue in the future!

**Comment by awinograd** [comment]
@esamelson I'm going to take you up on your last comment about re-opening (or at least clarification) 😆 

The 0.2.0 publish workflow has been working great (in terms of including only the assets matching assetBundlePatterns). However, I just switched to using the no-publish workflow on 0.2.14 and now whenever a build a new app, it doesn't seem to respect `assetBundlePatterns`. Reading the current docs (and your comments here):

https://docs.expo.io/bare/installing-updates/#-how-do-i-customize-which-assets

> now, the embedded JS is generated on-the-fly during the build process and all required assets are embedded. See this post for more details.

I'm not really sure if what I'm seeing is expected behavior or, in fact, a bug.

Is it expected behavior that *all* assets required in JS at binary build time are included in the resulting binary? If so, is there any way to prevent required assets from being bundled (so that I can decrease download size from the store). Or do I have to manage lazy assets differently now?
