### ISSUE TITLE
[web] Horizontal ScrollView makes scroll bar show on root element on Firefox

### ISSUE THREAD

**Issue by abmantis** [expo/expo#8223]
## 🐛 Bug Report

When having a horizontal ScrollView that is wider than the view, the scroll bar is show on the root view, and not on the ScrollView, on the web browser. On Android it works fine. I don't think it is a problem with react-native-web, since it works fine here: https://codesandbox.io/s/amazing-cdn-ny0x8

You can see the problem with a simple example in this snack: https://snack.expo.io/H1Eq4xheu
A workaround is to put it inside a View with flexDirection:'row', and set any width on the ScrollView: https://snack.expo.io/ocdmefZE6

### Steps to Reproduce

See simple example: https://snack.expo.io/H1Eq4xheu

### Expected Behavior

Scroll bar would should on the ScrollView, and only move the ScrollView contents.

### Actual Behavior

Scroll bar is shown on the root view and move the whole page.

### Reproducible Demo

https://snack.expo.io/H1Eq4xheu

EDIT: I noticed that removing "display: flex" from `<body>` using the Dev Tools inspector results in the correct behavior. The example I linked from codesandbox does not have "display: flex" on body.

**Comment by cruzach** [comment]
@abmantis on iOS, this looks to be working as expected for me - `Scroll bar moves on the ScrollView, and only move the ScrollView contents.`

ios 13, iphone 8

**Comment by abmantis** [comment]
@cruzach I haven't tested on iOS, but the problem also does not happen on Android. Only on the web as I mentioned.

**Comment by cruzach** [comment]
Oh i missed that, sorry!

**Comment by cruzach** [comment]
hm, even on the web sim I'm not seeing the issue

**Comment by abmantis** [comment]
https://snack.expo.io/H1Eq4xheu 
On that expo, you can see that the Text element is outside the ScrollView, but still the scrollbars show bellow the text, and the text moves when using the scrollbar.

**Comment by abmantis** [comment]
@cruzach were you able to reproduce it on Firefox too? Any idea why it doesn't happen on the codesandbox I linked, but happens on expo?

**Comment by EvanBacon** [comment]
We have an opinionated style reset in the `web/index.html` that is based on the recommended `react-native-web` reset. If you would like to customize this functionality you can eject the index.html with `expo customize:web`. I think changing this across all expo web projects could result in a lot of unexpected style changes.

**Comment by abmantis** [comment]
Thanks @EvanBacon. I ended up adding the following to my top component, and it works.

```
  useEffect(() => {
    if (Platform.OS === 'web') {
      // fix body having "display: flex", which messes up ScrollView scrollbars
      document.body.style.display = 'initial';
      const root = document.getElementById('root');
      if (root) {
        root.style.height = '100%';
        root.style.display = 'flex';
      } else {
        console.error("Couldn't get root view to fix web ScrollView.");
      }
    }
  });
```

But shouldn't this be fixed anyway? Because this makes the ScrollView work poorly.
