### ISSUE TITLE
Problem login with Facebook and Firebase

### ISSUE THREAD

**Issue by Katsukiniwa** [expo/expo#8226]
## 🐛 Bug Report
After upgraded Expo version 37, I can't do Facebook sign in with Firebase Auth on iOS and returned this message. However worked on Android.
I checked Facebook App Id and App secret and entered it to Firebase Facebook auth console.

```
Possible Unhandled Promise Rejection (id: 0):
[Error: Unsuccessful debug_token response from Facebook: {"error":{"message":"(#100) The App_id in the input_token did not match the Viewing App","type":"OAuthException","code":100,"fbtrace_id":"********"}}]
```

### Environment

  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nodebrew/current/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nodebrew/current/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.8 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ~4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.20.3
This happened on iOS simulator.

**Comment by alter-io** [comment]
Seeing the same problem on both a device and a simulator via expo client app.

**Comment by Katsukiniwa** [comment]
@alter-io 
I solved this issue.
https://github.com/expo/expo/pull/7931/files
```
- In the Expo Client, all of your Facebook API calls will be made with Expo's Facebook App ID. This means you will not see any related ad info in your Facebook developer page while running your project in the Expo Client.  
- To use your app's own Facebook App ID (and thus see any related ad info in your Facebook developer page), you'll need to [build a standalone app](../../distribution/building-standalone-apps/).  
```
According to this pull request, Facebook Auth is only use on standalone build app.
in app.json, write facebookAppId and facebookScheme and facebookDisplayName and build your app !

**Comment by alter-io** [comment]
Thanks @Katsukiniwa but not being able to use the Expo client app with Facebook login (and firebase) to me is a dealbreaker. The Expo client app is one of the main reasons why I am using Expo. If I cannot log in in my app, the rest is not testable. It seems like they haven't thought about the consequences carefully before making this change.

**Comment by alter-io** [comment]
I downgraded to the previous version of Expo and it works fine now. I'll hold off on the upgrade until this issue is resolved. 

Note the issue is that firebase.auth().signInAndRetrieveDataWithCredential(credential) will not work because the app_id entered in firebase does not match with the credentials created for Facebook login (expo client id FB app).

**Comment by cschlaep** [comment]
Having this same issue.  Downgrading to SDK 36 solves the problem as @alter-io points out but doing so means I can't take advantage of other SDK 37 features like [Firebase Analytics](https://blog.expo.io/using-firebase-analytics-with-expo-222ca84e4d33).

Is there any way to use my own app_id for Facebook login with SDK 37, or at least a way to integrate analytics with SDK 36?  This is throwing a pretty significant wrench in development.

**Comment by cruzach** [comment]
This fix had landed but is not deployed yet. I'll update the documentation with how to use your own facebook app id in a custom Expo Client now

**Comment by cruzach** [comment]
The fix is in production, here's the relevant documentation:
- https://docs.expo.io/versions/latest/sdk/facebook/
- https://docs.expo.io/guides/adhoc-builds/

**Comment by guylandoy** [comment]
@cruzach Thanks for response and attention. 
Why does facebook login with firebase auth is working simply on sdk 36 but now it requires a custom expo client app which requires Apple Developer Account and perhaps a Mac?

**Comment by JonnyBoy333** [comment]
It seems like a decision was made to hardcode Expo's facebook app details in the OAuth requests coming from the ios App Store version of Expo. This saves developers the time of having to create an app and get an App Id on facebooks site if all they want to do is us facebook for a login (and look at profile details). The thing is, by doing this, not only does firebase auth not work anymore but also you are confined to only using `public_profile` and `email` permissions, so if your app uses any of the other 13 permissions available, it is now broken. Which is now referred to as a "slight downside." Considering it takes all of a couple minutes to create an App on facebook's site I don't know if this was a good trade.

**Comment by guylandoy** [comment]
@JonnyBoy333 Decision by expo? 
I think even if you don't need the extra permissions you need to create an app and get appId on facebook's site..
So I don't understand this decision, it worked pretty good and really easy setup with sdk 36 :(

**Comment by JonnyBoy333** [comment]
@guylandoy I think you're right, you do still need to get an App Id, I guess I don't know what this means in the documentation then `No configuration is needed to use the Facebook SDK in the App Store Expo client`. Maybe it is referring to the app.json configuration or something. I don't know who decided on this exactly or why it was decided, maybe @cruzach could tell you.

**Comment by cruzach** [comment]
You can see the context/reasons this was done in the [pr](https://github.com/expo/expo/pull/7931), and the two issues it closes. Basically- redirects from the Facebook app back to the Expo Client didn't work, since you need the facebook URL scheme key in your info.plist

I understand that building the custom client isn't _as_ easy as downloading straight from the app store (if you have any problems, let us know and we can try to improve that), but it was important that Facebook login work as intended in the Expo Client app

I'm not sure what you mean that the documentation is wrong when it says `No configuration is needed to use the Facebook SDK in the App Store Expo client`

**Comment by JonnyBoy333** [comment]
I wouldn't say it's wrong, I just didn't know what configuration it was referring to, setting up the info.plist file? I might recommend putting a note about it in the `Facebook.logInWithReadPermissionsAsync(options)` section, if you skipped straight there you might not realize why it's not working as expected.

I wasn't aware there was an issue with the redirect in previous versions of Expo, from what others have said it sounded like there weren't any issues before, but I can't confirm that from personal experience.

**Comment by cruzach** [comment]
I suppose we can move the "no configuration needed in the app store expo client" to the top of the [configuration section](https://docs.expo.io/versions/latest/sdk/facebook/#configuration) so it's more obvious what you don't need to do (everything)

> if you skipped straight there you might not realize why it's not working as expected

That is true with most modules, if you skip the configuration or set-up section, it might not work as expected 😅 

The two issues were some of the most upvoted/commented on our repo, and I confirmed the bugs. it would only happen if you had the facebook app installed though so maybe that explains why you never saw it occur

**Comment by adrenaline681** [comment]
@cruzach So with the new SDK v37 is not possible to do Facebook login with a REST API like Firebase or Django without using a custom expo client or building a standalone app?

**Comment by leimichelle** [comment]
> I downgraded to the previous version of Expo and it works fine now. I'll hold off on the upgrade until this issue is resolved.
> 
> Note the issue is that firebase.auth().signInAndRetrieveDataWithCredential(credential) will not work because the app_id entered in firebase does not match with the credentials created for Facebook login (expo client id FB app).

expo SDK 37 works for the Faceboook login part, but we still can't use the credential to login with Firebase for the reason you mentioned 🤯
So I think this issue should be closed? since it's  Problem login with Facebook **and Firebase**

**Comment by MattGoldwater** [comment]
I'm still confused after reading this. Is anyone able to use SDK 37 on the managed workflow w/ Facebook and Firebase?

**Comment by adrenaline681** [comment]
@MattGoldwater I wasnt able to make it work. Expo's Facebook AppID is supposed to be internally set but its still asking for one, when I enter my own it will not work.

I decided to drop Expo completely and I've moved my app to React Native CLI standard workflow. Facebook login is working fine now.

**Comment by cruzach** [comment]
Yes, Facebook login integrated with Firebase works on the managed workflow in SDK 37. I linked the documentation that explained this above, but since it seems to still be a point of confusion for folks, I'll explain it here:

In order to solve a bug with logging in via the Facebook **app** when developing in the App Store Expo Client, we decided to use our own Facebook App ID. This has the added benefit of you not having to do any set up at all when you want to test out Facebook Login features.

**However** this means you can no longer integrate with Firebase **in development** when using the **App Store Expo client**. But you _can_ integrate with Firebase in both:
- a standalone app (built with `expo build:ios`) AND 
- a custom Expo client build 

since in both of those cases you are using your own Facebook App ID and app secret (identical to what was done in SDK 36 and below). 

For a guide on how to build a custom Expo client app (spoiler: it's _super_ easy, and if it's not for you, let us know so we can make the process better!) refer to [this documentation](https://docs.expo.io/guides/adhoc-builds/)

**Comment by MattGoldwater** [comment]
@cruzach Thanks! Those docs were largely clear, though if I hadn't read your comment I might've not released I needed to run expo build:ios to view my app in the custom client..

**Comment by cruzach** [comment]
No, you don't need to run `expo build:ios` to view your app in the custom client. A standalone app (`expo build:ios`) is different from a custom client (`expo client:ios`). I recommend the docs on [standalone apps](https://docs.expo.io/distribution/building-standalone-apps/) in addition to the ones i linked above

**Comment by MattGoldwater** [comment]
@cruzach Whoops. Thanks again!

**Comment by leonaburime** [comment]
@cruzach  I tried running `expo client:ios` command to get the "custom client's Bundle ID" from your directions.  Its giving me an error saying I have to have a paid Apple Developer Account?  

- Is this supposed to happen?
- Is there a way around this?

![Screen Shot 2020-06-12 at 11 33 12 PM](https://user-images.githubusercontent.com/8000641/84561914-16f7c600-ad05-11ea-9fff-f515bc474041.png)

**Comment by leonaburime** [comment]
Also I got a Gemfile lock error. Are these two issues separate or will changing the permissions for the Gemfile.lock help me get around the Developer account issue?

![Screen Shot 2020-06-12 at 11 36 44 PM](https://user-images.githubusercontent.com/8000641/84561973-95546800-ad05-11ea-814b-8d994ca20f1c.png)

**Comment by cruzach** [comment]
@leonaburime you need a paid Apple Developer Account to create a custom Expo client app (this is the same account that is required to build apps that you plan to ship to the App Store)

**Comment by usman1579** [comment]
Hi @cruzach  i am facing the same error in the updated version too.

**Comment by blind675** [comment]
Me too.
