### ISSUE TITLE
Sign in with Apple is not localized

### ISSUE THREAD

**Issue by hongyu6868** [expo/expo#8229]
### Environment

  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.3 AI-162.3934792
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.6 => 4.3.8 
    npmGlobalPackages:
      expo-cli: 3.20.3

App's target: iOS and Android, with web platform too (not built with expo)

### Steps to Reproduce

Copy pasted code in example:
https://docs.expo.io/versions/latest/sdk/apple-authentication/

### Expected Behavior

I expected the strings to be localized, or at least give the option to pass in localized strings.

### Actual Behavior

The button text always appears in English.

### Reproducible Demo

Copy pasted example mentioned above will reproduce. 
![image](https://user-images.githubusercontent.com/65089494/81483850-1b652680-920f-11ea-97f8-a81e4799f4f6.png)

**Comment by brentvatne** [comment]
You can add `"CFBundleAllowMixedLocalizations": true` to your `infoPlist` property in app.json - see https://docs.expo.io/workflow/configuration/#ios

once you add this you will need to rebuild the standalone app

**Comment by brentvatne** [comment]
@cruzach @byCedric - can one of you add this to docs?
