### ISSUE TITLE
Expo-speech not working on iOS devices with Silent Mode on

### ISSUE THREAD

**Issue by jameschetwood** [expo/expo#8235]
## 🐛 Bug Report

I'm using expo-speech in my project but the text is not read out in some iOS devices. From getting my friends to test it the results I have are:

Does Work:
iPhone X.  13.3.1
iPhone 10. 
iPhone X.  13.3.1
iPhone 8 Plus.  13.3.1
iPhone 7+.  13.1.2 

Is not working:
iPhone Xs.  13.3.1 
iPhone 8.  13.4.1 - This is my testing phone so I know that the sound works fine on YouTube.

It also works fine in every iOS simulator that Ive tried when developing locally. 

Ive created a very simple repo (link below) to test it out with this code:

```
import React from 'react';
import * as Speech from "expo-speech";
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  setInterval(()=>{
    Speech.speak(`I am a test`);
  }, 2000);

  return (
     <View style={styles.container}>
      <Text>Open up App.tsx to start working on your app!</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Using the Expo app to test it on an iPhone 8 13.4.1 it's also not working.

### Environment

  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.9
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.3

This is a bug on iOS. Ive not tested extensively on Android yet so I'm not sure if this is just an iOS issue.

### Steps to Reproduce

Run my repo or snack on some iOS devices.

### Expected Behavior

It should be read out "I am a test"

### Actual Behavior

On some devices nothing is read out. 

### Reproducible Demo

https://github.com/jameschetwood/expo-sound-test

https://snack.expo.io/@jamesweblondon/sound-test

Here is my live app: https://apps.apple.com/us/app/love-hiit/id1511764271?ls=1

**Comment by jameschetwood** [comment]
Ive also noticed that when using Expo web, on my iPhone 8 13.4.1 the sound does work in Chrome but not in Safari.

**Comment by jorjordandan** [comment]
Working on my iphone Xs version 13.4.1 (reads "I am a test" over and over)

**Comment by jameschetwood** [comment]
Im not sure exactly when it works and doest, but my actual app is live and a lot of people are reporting that it's not working. So Im confident this is a real issue.

**Comment by brentvatne** [comment]
it won't work if their audio is muted, perhaps your friends can double check that?

**Comment by jameschetwood** [comment]
It's also not working on my iPhone. Ive just checked and YouTube plays fine. 

Here is where I posted my app on Reddit. Quite a few people (in addition to friends) are reporting the sound doesn't work so I don't think they could all be user error:
https://www.reddit.com/r/bodyweightfitness/comments/gxs2ei/sharable_hiit_timer/

**Comment by dev0809** [comment]
Hi @jameschetwood 

I had met such case and solved issue using WebView on Expo.
Code snippets here.
```
const audioTag =
      "<audio autoPlay controls src='" + this.audio + "'></audio>";

    return (
      <WebView
        originWhitelist={["*"]}
        source={
          Platform.OS === "ios" ? { html: audioTag } : { uri: this.audio }
        }
      />
    );
```

this.audio contains base64-encoded audio content from Google Speech API.

**Comment by brentvatne** [comment]
@jameschetwood - is your ringer muted?

**Comment by jameschetwood** [comment]
@brentvatne No I just checked and it wasn't.

**Comment by brentvatne** [comment]
to clarify - this means the switch on the side of your phone is in the position such that it will say "Silent mode: off" when it's toggled to that position

**Comment by brentvatne** [comment]
I think what we need to do here is ensure that audio mode configured by expo-av is used by expo-speech, such that `Audio.setAudioModeAsync({ playsInSilentModeIOS: true })` will result in the `Speech.speak` being audible when ios silent mode is enabled

**Comment by jameschetwood** [comment]
Working for me! I'll message my friends who it didn't work for and get them to confirm. 

I agree that ideally it should still play when iOS silent mode is on as this did seem to confuse a number of people.

**Comment by jameschetwood** [comment]
@brentvatne is there any way for me to implement a workout around for even monkey patch this as a short term fix?

**Comment by brentvatne** [comment]
cc @sjchmiela who has more context on expo-av and what may be needed for this to play nicely with expo-speech

**Comment by StevePhuc** [comment]
Have the same issue, before it worked in my iPhone but now not work anymore. Basically I not changed anything

**Comment by StevePhuc** [comment]
@jameschetwood turn off silent in iOS works. Please change the title of this issue; "Expo-speech not working on iOS devices with Silent Mode on"

**Comment by nikki93** [comment]
Calling `Audio.setAudioModeAsync({ playsInSilentModeIOS: true });` doesn't actually make `Speech.speak` work in silent mode. The `Audio.setAudioModeAsync` call eventually gets to this native code on iOS: https://github.com/expo/expo/blob/49369ba7a9e90dc02689c2f2ef99a9512f227923/packages/expo-av/ios/EXAV/EXAV.m#L206-L208

`_getAudioSessionModeRequired` checks for AV objects but is unaware of speech: https://github.com/expo/expo/blob/49369ba7a9e90dc02689c2f2ef99a9512f227923/packages/expo-av/ios/EXAV/EXAV.m#L253-L258

On the implementation side, we could make the AV module aware of speech, or we could go the other way round and make speech register itself with the AV module. Either way this still leaves the question of--on the API side--do we want the user to have to install 'expo-av' and then do the `Audio.setAudioModeAsync` call or do we want to just support an additional `playsInSilentModeIOS: true` option on `Speech.speak` itself.

cc @bbarthec

**Comment by nomi9995** [comment]
@brentvatne  `Audio.setAudioModeAsync({ playsInSilentModeIOS: true })` we have to use this but we also have to play empty sound (Hack) to make it work 
you can see my full answer here: https://stackoverflow.com/a/62331403/8079868

**Comment by btk** [comment]
@nikki93 hey, I built an app that mainly using `expo-speech`. From my perspective I would prefer it be an option of `Speech.speak()` and would expect the default `playsInSilentModeIOS` value `false`, just to make sure developer is in control of making the speech work on silent mode.

for now workout suggested by @nomi9995 works fine.

**Comment by GeorgeBellTMH** [comment]
https://github.com/expo/expo/issues/19407 likely related...

**Comment by alina** [comment]
Having the same issue, would love to be able to set playsInSilentModeIOS as described above

**Comment by atakanbayil** [comment]
Still is an issue and not updated.

**Comment by omutas** [comment]
It is still not working.

**Comment by raffiniert** [comment]
This is a big problem for our soon to be released project. Is there any workaround?

**Comment by raffiniert** [comment]
This issue still persists and is a real problem to our app! Could someone please reopen it and take care?

**Comment by cleversonhabiitech** [comment]
I can confirm that the problem persists....

**Comment by raffiniert** [comment]
Wow, longest open issue I've had on my project www.quazzl.app so far... anyway, I fixed/hacked it with this: https://stackoverflow.com/questions/61949934/expo-speech-not-working-on-some-ios-devices/62331403#62331403

**Comment by raahimkhan** [comment]
Can confirm this is still an issue in 2025. Had to implement as mentioned in: https://stackoverflow.com/questions/61949934/expo-speech-not-working-on-some-ios-devices/62331403#62331403 to workaround it.
