### ISSUE TITLE
[ExpoKit 36] The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable 

### ISSUE THREAD

**Issue by omerdn1** [expo/expo#8236]
### Environment

iOS, ExpoKit 36

### Steps to Reproduce

Came back to a previously working ExpoKit ver 36 project and ran `expo start`. The project was working completely fine a month ago - **no changes/upgrades were made (except a removal of node_modules and reinstallation after the error showed up)**.

### Actual Behavior

I get this error: ```The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable```.

I applied some debugging in validate.fx.js and saw that the expo Constants object has a bunch of undefined/null values.

**It's important to note that I don't have any 'expo' imports in my projects. I'm using the unimodules**

![Image-1](https://user-images.githubusercontent.com/10265367/81498276-a1937280-92cc-11ea-9614-fdd54e81f799.jpg)

**Comment by byCedric** [comment]
Hi @omerdn1! Thanks for the issue report. If you use unimodules, you are using the core system that interacts with some Expo internals. It's not importing the "full expo", just the basic systems where everything is built on 😄 

Usually, if you encounter stuff like this, it's related to unexpected side-effects with your `node_modules`. Could you try doing this?
1. Remove node_modules + package-lock.json (or yarn.lock)
2. Install everything with either NPM or Yarn
3. Start without the cache, `expo start --clear` 

Hope it helps 😄

**Comment by omerdn1** [comment]
@byCedric Unfortunately, I went over all of the steps and it didn't work.
What kind of information could help you to zero in on the problem?
