### ISSUE TITLE
[iOS] - [Expo - Facebook] - Facebook.logInWithReadPermissionsAsync not recognising parameters  

### ISSUE THREAD

**Issue by wazzupex** [expo/expo#8238]
Hi,

Although I'm able to login with Facebook, the permissions I get back in the response are not what I've requested. This issue happens only on iOS (both simulator and device) but works fine with Android. Any suggestions here?

I noticed that when I call the Facebook login method it is not using the parameters set, for example, the 2 example below reults in the same response: 

Adding: user_friends permission request

`await Facebook.initializeAsync(FbAppId);
      const result = await Facebook.logInWithReadPermissionsAsync(FbAppId, { 
        permissions: [
          'public_profile', 
          'email', 
          'user_friends'
        ] 
      } );`

`await Facebook.initializeAsync(FbAppId);
  const result = await Facebook.logInWithReadPermissionsAsync( );`

For both I get the very same response: 
`{
  "declinedPermissions": Array [],
  "expires": 1590712686664,
  "permissions": Array [
    "email",
    "public_profile",
  ],
  "token": "...9yder6snXwEo...",
  "type": "success",
}`

No permissions (user_friends) are being declined as it has been approved by Facebook but it has not been granted as well.

In my package.json this is the version I got 
`"expo-facebook": "^8.1.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
`

**Comment by wazzupex** [comment]
Up... Not even triaged. :(

**Comment by fhenri42** [comment]
Hey do you have any update ?

**Comment by wazzupex** [comment]
Hi @fhenri42 

It was an issue with the FB configuration in the App.json... I was about to change from Expo Facebook to Facebook React-native APIs when I decided "refactor" all the App.json and it worked

Regards,
Alex F Borba

**Comment by fhenri42** [comment]
Can you share your app.json ? plz

**Comment by wazzupex** [comment]
@fhenri42 Find it below... The important part is the 3 properties of facebook and not to mistaken them.

`{
  "expo": {
    "name": "<my App's name>",
    "description": "<my App's description>",
    "slug": "<my App's slug>",
    "facebookScheme": "<your facebook schema starting with fb...>",
    "facebookAppId": "<your facebook App Id>",
    "facebookDisplayName": "<your App Display Name>",
    "privacy": "unlisted",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "<myversioningControl>",
    "orientation": "portrait",
    "icon": "<myIcon>",
    "splash": {
      "backgroundColor": "#000000",
      "resizeMode": "contain",
      "image": "<myLogo>"
    },
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "assets/images/*"
    ],
    "ios": {
      "supportsTablet": false,
      "bundleIdentifier": "<myPackage>",
      "config": {
        "googleMapsApiKey": "<myAPIKey>"
      }
    },
    "android": {
      "package": "<myPackage>",
      "config": {
        "googleMaps": {
          "apiKey": "<myAPIKey>"
        }
      }
    }
  }
}`

**Comment by fhenri42** [comment]
Thx a lot @wazzupex

**Comment by patrinoua** [comment]
> FB configuration in the App.json... I was about to change from Expo Facebook to Facebook React-native APIs when I decided "refactor" all the App.jso

Hi there, I'm running into the same problem! What kind of refactor did you do? :) 

My App.json looks like this: 

{
  "expo": {
    "name": "PingPongBuddies",
    "description": "Play with other Ping Pong Buddies in your area!",
    "slug": "PingPongBuddies",
    "privacy": "public",
    "platforms": ["ios", "android"],
    "version": "1.0.20",
    "githubUrl": "https://github.com/patrinoua/pingPongBuddies/",
    "orientation": "portrait",
    "primaryColor": "#000000",
    "icon": "./assets/icon.png",
    "splash": {
      "resizeMode": "contain",
      "backgroundColor": "#ffffff",
      "image": "./assets/logo-margin.png"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*", "assets/images/*"],
    "ios": {
      "bundleIdentifier": "com.patrinoua.PingPongBuddies",
      "supportsTablet": true,
      "buildNumber": "1.0.20"
    },
    "android": {
      "googleServicesFile": "./google-services.json",
      "package": "com.patrinoua.PingPongBuddies",
      "useNextNotificationsApi": true,
      "versionCode": 20,
      "config":{
        "googleSignIn":{
          "apiKey": "AIza..."
        }
      }
    },
    "facebookScheme": "fb35472...",
    "facebookAppId": "354726...",
    "facebookDisplayName":"PingPongBuddies"
  }
}

should I move something to a different place?

Thanks in advance! =]
