### ISSUE TITLE
SQL Create Table doesn't work when passing table name in arguments array

### ISSUE THREAD

**Issue by bayyatej** [expo/expo#8243]
### Environment

Expo CLI 3.20.3 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7

Managed Workflow developing iOS App.

### Steps to Reproduce

After getting handle on database object try transacting a query creating a table passing the table name as an argument in the arguments parameter of tx.executesql()

The query will not execute successfully and the table will not be created. 

Code snippet included below to illustrate

e.g. in typescript

```
const table = "foo_table";
const db = SQLite.openDatabase("foobar.db");

db.transaction((tx: SQLTransaction) => {
    tx.executeSql(`
                 CREATE TABLE IF NOT EXISTS
                 ? (
                        task_name TEXT
                  );`,
        [table],
        (tx, result) => {
            console.log("success");
        },
      (tx, error) => {
            console.log(error);
       }
    );
});
```

### Expected Behavior
Expected the query to execute valid SQL successfully, expanding ? to the value of table on execution and to create the table with the name specified in the arguments parameter.

### Actual Behavior

Error callback to executeSql fires. Logging error code produces:

`[Error: Error code 1: near "?": syntax error]`

And the table is not created.

I know that the SQL is valid because when I execute the query using JS string interpolation instead of the arguments parameter of executeSql I am able to successfully create the table.

### Reproducible Demo

[https://github.com/bayyatej/ExpoSQLiteBug](https://github.com/bayyatej/ExpoSQLiteBug)

**Comment by byCedric** [comment]
Hi @bayyatej! Thanks for the issue report. Unfortunately, this is a limitation from SQLite itself. To quote [this SO thread](https://stackoverflow.com/questions/1274432/sqlite-parameters-not-allowing-tablename-as-parameter)

>  Generally one cannot use SQL parameters/placeholders for database identifiers (tables, columns, views, schemas, etc.) or database functions (e.g., CURRENT_DATE), but instead only for binding literal values.

One way to work around this limitation is to use JS template syntax. But, that requires you to make sure it does not contain any user-input or sanitize it yourself before running this.

Hope it helps!
