### ISSUE TITLE
One of expo_runtime_version or expo_sdk_version must be defined in the Android app manifest

### ISSUE THREAD

**Issue by hanselsen** [expo/expo#8244]
### Environment
```
  Expo CLI 3.19.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Users\hans\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
```
App target: Bare Workflow Android

### Steps to Reproduce

1. I ejected the project using `expo eject`
2. I followed the instructions on [https://reactnative.dev/docs/signed-apk-android](https://reactnative.dev/docs/signed-apk-android) to be able to run `gradlew installRelease`
- The APK will be generated correctly
3. open the app and it will close immediately

Btw. I ran `expo publish` before.

### Expected Behavior

I wish that it would be at least debuggable, so I can fix the code/config.

### Actual Behavior

So it closes and it shows an error in Logcat:

```
2020-05-11 09:23:56.730 30455-30455/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: [OBFUSCATED], PID: 30455
    java.lang.AssertionError: One of expo_runtime_version or expo_sdk_version must be defined in the Android app manifest
        at f.a.o.m.a(Unknown Source:30)
```

### Reproducible Demo

My [Androidmanifest.xml](https://pastebin.com/VhxWKkZU)

Is this expected behavior based on some clear mistakes or something? It seems to me that it should work out of the box right?

**Comment by sjchmiela** [comment]
I think this comes from `expo-updates` which are installed, but not configured. Could you please ensure that the configuration process, described [here](https://www.npmjs.com/package/expo-updates#configure-for-android) has been followed through for your project? (You could also remove `expo-updates` from your project, depends on your use case and future needs [who wouldn't need OTA updates!]. 😃 )

**Comment by hanselsen** [comment]
Oh ok I see it now.. pretty weird I did not find this sooner. I get some other errors now but I won't discuss that here if I don't find it relevant.

**Comment by hanselsen** [comment]
@sjchmiela this is the error now, maybe you could ellaborate please? 
https://github.com/expo/expo/issues/6973#issuecomment-626670641

**Comment by byCedric** [comment]
I'll close this, let's discuss the other issue in #8248 😄
