### ISSUE TITLE
The Expo SDK requires Expo to run

### ISSUE THREAD

**Issue by hanselsen** [expo/expo#8248]
### Environment

```
  Expo CLI 3.19.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.3.2 - C:\Users\hans\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ~37.0.3 => 37.0.9
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
```

Target: Bare workflow Android

### Steps to Reproduce

My main problem is that I cannot find enough info on how to release apps with a bare workflow, so I have no idea if I am doing it right.  
- I used `expo init` with the bare workflow configuration and wanted to create a release build to run on my app. 
- Then I ran `expo publish` so that I would have manifests and bundles (you would think)
- then running `gradlew installRelease` did not succeed 
- I got the error indicating that I missed a value for `expo.modules.updates.EXPO_UPDATE_URL` in `AndroidManifest.xml`. (there was no placeholder for this, but there is one for `EXPO_SDK_VERSION`.
- then running `gradlew installRelease` did not succeed because `The embedded manifest is invalid or could not be read. Make sure you have created app.manifest and app.bundle files and added them to the `assets` folder.`
- "fixed" this by adding this to `expo.android` in `app.json`:
`
      "publishBundlePath": "./android/app/src/main/assets/app.bundle",
      "publishManifestPath": "./android/app/src/main/assets/app.manifest"
`
- This did help with the error but then this error came `org.json.JSONException: No value for releaseId`

I don't know why, but in another project, I got stuck on this error. https://github.com/expo/expo/issues/6973#issuecomment-626670641

### Expected Behavior

I wish there was a nice up-to-date walkthrough for bare workflow projects, from init to App Store/Play Store.

### Actual Behavior

-

### Reproducible Demo

Placed my code to this repo
https://github.com/hanselsen/expo-bare-workflow-project

**Comment by byCedric** [comment]
Hi @hanselsen, that's not the experience you should have received and for that I'm sorry. We are currently working on fixing your second point (require a publish, before being able to run the app in release mode). 

As for the `Expo SDK requires Expo to run`, this is usually related to issues within your `node_modules`. Could you try this for me?
1. Remove `node_modules` + `package-lock.json` (or `yarn.lock`)
2. Install everything with either NPM or Yarn
3. Create a new published bundle (`expo publish`) (again, we are working on this so hang on 😄)
4. Create APK or run the project with `npm run android` or `yarn android`

I did manage to run your project by doing exactly that. Could be that the (current) published bundle was somehow malformed due to the `node_modules` issues.

Hope it helps!

**Comment by hanselsen** [comment]
Thanks for the response. `npm run android` was working already. I was talking about the release version of the APK which shows this behavior. 
I will try your solution anyway though. Give me a minute.

**Comment by byCedric** [comment]
Yes sorry! That's what I meant, try building the APK or run `npm run android -- --variant=release` 😄

**Comment by hanselsen** [comment]
@byCedric sadly no working (is `npm run android -- --variant=release` not just for running instead of building? Since you have the metro server running locally?).
But it stop right away, but it ends with a different error.
```
com.facebook.react.common.JavascriptException: Invariant Violation: "main" has not been registered. This can happen if:
    * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
    * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., stack:
    runApplication@309:1948
``` 
This is my `index.js`: 
```index.js
import { registerRootComponent } from 'expo';

import App from './App';

registerRootComponent(App);

```
My `package.json`:
```
{
  "main": "index.js",
  "scripts": {
      ...
```

**Comment by Crodaycat** [comment]
Same issue, no imports from 'expo', expo publish ok.

Dependencies:

```
  "dependencies": {
    "@expo/samples": "~36.0.0",
    "@expo/vector-icons": "~10.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "apisauce": "^1.1.1",
    "async": "^3.1.0",
    "expo": "~36.0.0",
    "expo-asset": "~8.0.0",
    "expo-background-fetch": "~8.0.0",
    "expo-constants": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-image-picker": "^8.1.0",
    "expo-location": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "expo-secure-store": "~8.0.0",
    "expo-sqlite": "^8.0.0",
    "expo-task-manager": "8.1.0",
    "expo-web-browser": "~8.0.0",
    "lodash": "^4.17.15",
    "lottie-ios": "3.1.3",
    "lottie-react-native": "^3.4.0",
    "moment": "^2.24.0",
    "q": "^1.5.1",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-masked-text": "^1.13.0",
    "react-native-modal-datetime-picker": "^7.6.1",
    "react-native-modalize": "^1.3.7-rc.1",
    "react-native-paper": "^3.4.0",
    "react-native-picker-select": "^6.3.3",
    "react-native-reanimated": "~1.4.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-unimodules": "^0.8.1",
    "react-native-web": "~0.11.7",
    "react-navigation": "~4.0.10",
    "react-navigation-animated-switch": "^0.4.1",
    "react-navigation-stack": "~1.10.3",
    "react-navigation-tabs": "~2.6.2",
    "react-number-format": "^4.3.1",
    "sentry-expo": "^2.0.1",
    "validate.js": "^0.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-jest": "~24.9.0",
    "babel-preset-expo": "~8.0.0",
    "jest": "~24.9.0",
    "jest-expo": "~36.0.1",
    "metro-react-native-babel-preset": "~0.56.0",
    "react-test-renderer": "~16.9.0"
  },
```

Environment:
```
Expo cli: 3.20.9
System:
      OS: Windows 10 
    Binaries:
      Node: 10.16.0
      Yarn: v1.17.3
      npm: 6.9.0
    IDEs:
      VSCode: 
      Android Studio: Version  3.6.3 Build #AI-192.7142.36.36.6392135
```
