### ISSUE TITLE
General Question: Expo + AWS or FIRBASE

### ISSUE THREAD

**Issue by inglesuniversal** [expo/expo#8249]
I have access to both technologies and API's

I would like to ask to those developers who use EXPO on a daily basis... Which cloud based environment, is friendlier and/or more powerful when used inside a ReactNative App built entirely on Expo.

By that I mean, which out of the two I mention is easier to implement and being able to scale-up to the app's needs as it grows in numbers of users in the market place.

Thanks and STAY SAFE

**Comment by byCedric** [comment]
Hi @inglesuniversal! These questions are better suited in or [forums](https://forums.expo.io/) or [community slack](https://slack.expo.io/) 😄 If you want the AWS alternative for Firebase, I would recommend checking AWS AppSync out. Here are some quick thoughts on that:

- There is no good or bad, they are both excellent rapid-development backend frameworks. [This article sums up the strength of both platforms](https://medium.com/better-programming/should-you-use-aws-or-firebase-for-the-back-end-of-your-mobile-app-a28f93540520), might be good to check this out.
- Expo supports any JS-based library, like the [Firebase web SDK](https://docs.expo.io/guides/using-firebase/) and [AWS Amplify SDK](https://forums.expo.io/t/aws-appsync-in-the-future/9497). @IjzerenHein also [worked really hard on the React Native Firebase implementation](https://docs.expo.io/guides/setup-native-firebase/), also good to check that out.
- Main difference between AWS AppSync and Firebase is the GraphQL vs Rest API, if you are into GraphQL AppSync might be better for you.

But again, there is no clear answer, they are both pretty good and well documented. I would suggest trying to make a quick todo app with both and pick the one you like the most 😄 

Hope it helps!
