### ISSUE TITLE
Get unique device id without ejecting

### ISSUE THREAD

**Issue by James2516** [expo/expo#825]
[This library](https://github.com/rebeccahughes/react-native-device-info#example) allows you to get unique device id / Mac address of Android devices, which doesn't change after reinstallation.

`Expo.Constants.deviceId` changes after every reinstallation (even if the app version number is the same).

Is there a way to get an unique id for Android that doesn't change after reinstallation (at least for if it's the same version), without ejecting?

**Comment by terribleben** [comment]
@jesseruder is this something we should address on Android? On the iOS side this is not supported without detaching and using the IDFA.

**Comment by ide** [comment]
We could possibly add this for standalone apps but can't do it for the Expo client consistently (we don't want to reveal the underlying true ID to protect privacy).

**Comment by James2516** [comment]
Why is it ok to reveal true ID for standalone app but not for app loaded with Expo client?
Anyway I'd be happy with having it just for standalone.

Are you able to give an estimate of when this will be implemented? (before v23?) I'd need to decide if I can wait for it or detach the app now. Thanks.

**Comment by ide** [comment]
This won’t be part of SDK 23 and unlikely to be part of 24.

The reason we wouldn’t expose it via the Expo client is because the IDFA is intended for advertising libraries. The developer of the app is responsible for using the IDFA as intended (from Apple/Google’s perspective) so we would expose it to developers only in apps they wholly own i.e. standalone apps.

**Comment by James2516** [comment]
@AdamJNavarro why is this closed? `Expo.Constants.deviceId` still changes after every reinstallation in sdk 28.

**Comment by AdamJNavarro** [comment]
As a maintenance measure, we've started to close issues that haven't been active for over 6 months. As it is still an issue, happy to re-open.

**Comment by EvanBacon** [comment]
@James2516 it looks like that is the [expected behavior](https://docs.expo.io/versions/latest/sdk/constants#expoconstantsdeviceid)
> An identifier that is unique to this particular device and installation of the Expo client.

It's created (in iOS) as a NSUserDefault that is created with UUID if it's not present. [Source Code Chunk](https://github.com/expo/expo/blob/d718b4b8c390c116837c4d440c06085cca8db5b0/ios/Exponent/Kernel/Core/EXKernel.m#L79-L88)

**Comment by James2516** [comment]
@EvanBacon yes it's intended as documented, but the documented behaviour is undesirable on Android. See the original post at top.

**Comment by reynaldorodriguez** [comment]
We are using in our App deviceId to detect whenever and user logs in in a new device, to do the proper device activation, but when the value changes after reinstallation we have to do all the device authentication again, being the same device, it doesn't make sense, can this be fixed? is this the only way to get a unique identifier from the device?

**Comment by ide** [comment]
The Expo device ID intentionally does not persist across installations. We would be open to renaming this field to “installationId” to minimize future confusion and set expectations better.

A device ID that tracks across installations may trigger extra scrutiny during the app review process, and in general APIs that allow it have been restricted or removed by the native OSes. Ex: https://arstechnica.com/gadgets/2012/09/ask-ars-whats-the-big-deal-with-iphone-udids/

There is an iOS API to store up to two bits of information that persist across device resets even. If the question you are trying to answer is “has my app been installed before?” that’s a feature request we could consider. It’s “who installed this app before?” that is a privacy and app review problem.

**Comment by James2516** [comment]
I have been using the unique device id from `react-native-device-info` on Android for several months without any issues. 

Why not just add the feature, and just deprecate it if Google ever rejects the Expo app because of that?

Better to have extra features than avoiding it completely because there's a risk that it might be rejected...

**Comment by ide** [comment]
> Better to have extra features than avoiding it completely because there's a risk that it might be rejected...

If you wish to take on this risk, you can detach and add the module yourself. The platform inconsistencies, app review risk, and privacy concerns are some of the reasons why we don't provide this tracking capability. Additionally, the maintenance cost of adding an external module adds up so we are judicious in what we choose. Overall, we are working to move Expo to more of a self-service model where the ExpoKit (i.e. detached) workflow is smoother and you build the app on your own machine with full control without being blocked on Expo for adding new modules, app builder queues, and other places where Expo can be a bottleneck today.

**Comment by ide** [comment]
[My most recent comment](https://github.com/expo/expo/issues/825#issuecomment-403101698) explains why getting the IMEI and other especially privacy-sensitive fields is something that is appropriate to implement yourself and is not appropriate for the Expo client.

Additionally I would like to re-affirm that Expo cannot add every feature that is request. Development and maintenance is expensive and to be sustainable from both engineering & business standpoints we need to be judicious in the APIs we choose to include or develop.
