### ISSUE TITLE
[notifications] Duplicate push notifications sent occasionally

### ISSUE THREAD

**Issue by cruzach** [expo/expo#8250]
## 🐛 Bug Report

Creating this issue to keep track of a few reports we've had so far, hopefully by organizing the conversation into one place, we can debug this a little more and find out the root cause (and fix it, if the bug is on our end!)

### Environment

Doesn't seem specific to any particular SDK or platform

### What happens

User receives multiple notifications after sending only 1 request to Expo's servers

### Steps to Reproduce // Reproducible Demo

Unfortunately haven't found a way to reliably reproduce this, please share one if you have!

**Comment by charsville** [comment]
Hi also getting this issue. Seems like the code we are using is consistently sending multiple notifications even though 1 request is sent to the Expo server. Below is our Notification Sender Method:

```javascript
private async SendNotifications(notifications: Array<ExpoPushMessage>): Promise<void> {
		const chunks: Array<Array<ExpoPushMessage>> = this.expo.chunkPushNotifications(notifications);
		const tickets: Array<ExpoPushTicket> = [];
		for (const chunk of chunks) {
			try {
				const ticketChunk: Array<ExpoPushTicket> = await this.expo.sendPushNotificationsAsync(chunk);
				tickets.push(...ticketChunk);
			} catch (error) {
				this.slackLogger.LogToNotificationChannel(
					`Error trying to send a chunk of notifications. Error object: ${JSON.stringify(error)}`,
				);
			}
		}

		setTimeout(() => this.notificationReceiptHandler.HandleReceipts(tickets, notifications), 29 * 60 * 1000);
	}
```

Running expo-server-sdk 3.5.0 on NestJS server

**Comment by phpc91** [comment]
Hi! I'm having this same issue in my organization for quite a time now, and we have not been able to find a way to consistently reproduce this error. It seems to me it has to do with a long list of destinies(ExpoPushTokens). We're using a code almost identical to the one in the [git readme](https://github.com/expo/expo-server-sdk-node), and expo-server-sdk 3.4.0 on NodeJS 10.16.3. Here is our code:

```js
    const expo = new Expo()
    const messages = []
    const pushTokens = to instanceof Array ? [...to] : [to]
    for (const pushToken of pushTokens) {
      if (!Expo.isExpoPushToken(pushToken)) {
        console.log(`Push token ${pushToken} is not a valid Expo push token`)
      } else {
        messages.push({
          to: pushToken,
          data,
          title,
          body,
        })
      }
    }

    const chunks = expo.chunkPushNotifications(messages)
    console.log(`${chunks.length} chunks`)

    const tickets = []
    let i = 1
    for (const chunk of chunks) {
      log(`chunk destinies: ${chunk.map(message => message.to)}`)
      try {
        const ticketChunk = await expo.sendPushNotificationsAsync(chunk)
        console.log(`sent chunk ${i}`)
        tickets.push(...ticketChunk)
      } catch (error) {
        console.log(error)
      }
      i += 1
    }
    console.log('done sending messages')
```

Today we stumbled across this issue once again: we tried to send a list of 5k+ `pushTokens` and many of our users complained that they received 4, 5 or even more push notifications on his/her device. And we can guarantee that this list of `pushTokens` does not have duplicates in it: it is the result of a MongoDB `distinct` query (it produces an array of unique elements).

**Comment by ZackKorman** [comment]
We have been experiencing this issue as well. We are sending about 15k push tokens in batches of 100, with roughly 50ms between each batch. When we do this, sometimes (but not always) our users will get a flood of duplicate push notifications (sometimes 10+ of the same message). I added logging to ensure we are not including the same token in multiple batches or retrying requests, and we are not.

We are using Expo for smaller apps that have far fewer push tokens to send to, and we do not experience this problem.

**Comment by rdarder** [comment]
Hi, we're having the same issue as well. By checking on a few cases, it seems like ios users are affected, but not android ones. It can also be a coincidence, we don't have access to the majority of the recipients.

**Comment by AlexHodovas** [comment]
Hi I have the same issue.
(User receives multiple notifications after sending only 1 request to Expo's servers)
Do you have any options for solutions?

**Comment by dpisarevskiy** [comment]
Hello! Same issue, but when sending from FCM console notification/compose got one message, from call API https://fcm.googleapis.com/v1/projects.... two same notification, one from him with blue (Ʌ) icon, one without icon [].

**Comment by dpisarevskiy** [comment]
Send to this token Notifications.getDevicePushTokenAsync() using managed workflow with FCM.

`curl -X POST -H "Authorization: Bearer ******" -H "Content-Type: application/json" -d '{
  "message":{
      "token":"******",
      "notification":{
        "body":"This is an FCM notification message!",
        "title":"FCM Message"
      }
   }
  }' "https://fcm.googleapis.com/v1/projects/myproject-12334/messages:send"`

```js
import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';
import * as Permissions from 'expo-permissions';
import React, { useState, useEffect, useRef } from 'react';
import { Text, View, Button, Platform } from 'react-native';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

export default function App() {
  const [expoPushToken, setExpoPushToken] = useState('');
  const [expoResponse, setExpoResponse] = useState('');
  const [expoPushTokenDevice, setExpoPushTokenDevice] = useState('');
  const [notification, setNotification] = useState(false);
  const notificationListener = useRef();
  const responseListener = useRef();

  useEffect(() => {
    try {
      Notifications.getDevicePushTokenAsync().then(token => setExpoPushTokenDevice(token) );
    } catch(e) {
      setExpoPushTokenDevice('token');
    }
    registerForPushNotificationsAsync().then(token => setExpoPushToken(token));

    // This listener is fired whenever a notification is received while the app is foregrounded
    notificationListener.current = Notifications.addNotificationReceivedListener(notification => {
      setNotification(notification);
    });

    // This listener is fired whenever a user taps on or interacts with a notification (works when app is foregrounded, backgrounded, or killed)
    responseListener.current = Notifications.addNotificationResponseReceivedListener(response => {
      setExpoResponse(JSON.stringify(response));
    });

    return () => {
      Notifications.removeNotificationSubscription(notificationListener);
      Notifications.removeNotificationSubscription(responseListener);
    };
  }, []);

  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-around',
      }}>
      <Text>Your expo push token: {expoPushToken}</Text>
      <Text>Your expo push token expoPushTokenDevice: {JSON.stringify(expoPushTokenDevice)}</Text>
      <Text>Your expo push token expoResponse: {expoResponse}</Text>
      <View style={{ alignItems: 'center', justifyContent: 'center' }}>
        <Text>Title: {notification && notification.request.content.title} </Text>
        <Text>Body: {notification && notification.request.content.body}</Text>
        <Text>Data: {notification && JSON.stringify(notification.request.content.data)}</Text>
      </View>
      <Button
        title="Press to Send Notification"
        onPress={async () => {
          await sendPushNotification(expoPushToken);
        }}
      />
    </View>
  );
}

// Can use this function below, OR use Expo's Push Notification Tool-> https://expo.io/dashboard/notifications
async function sendPushNotification(expoPushToken) {
  const message = {
    to: expoPushToken,
    sound: 'default',
    title: 'Original Title',
    body: 'And here is the body!',
    data: { data: 'goes here' },
  };

  await fetch('https://exp.host/--/api/v2/push/send', {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Accept-encoding': 'gzip, deflate',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(message),
  });
}

async function registerForPushNotificationsAsync() {
  let token;
  if (Constants.isDevice) {
    const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;
    }
    token = (await Notifications.getExpoPushTokenAsync()).data;
    console.log(token);
  } else {
    alert('Must use physical device for Push Notifications');
  }

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    });
  }

  return token;
}

```

**Comment by lukmccall** [comment]
I'm not sure if this fixes it. Hovewer, it will help with the @dpisarevskiy problem. 

But @dpisarevskiy, you shouldn't send the `notification` object, cause then the remote message doesn't go through `expo-notifications` code. The `body` and `title` you can move to the `data` object.

**Comment by dpisarevskiy** [comment]
@lukmccall can you provide example? 

```json
{
    "message":{
      "token":`${TOKEN}`,
      "sound": 'default',
      "title": 'Original Title',
      "body": 'And here is the body!',
      "data": { data: 'goes here' }
   }
```


```json
 "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"sound\" at 'message': Cannot find field.\nInvalid JSON payload received. Unknown name \"title\" at 'message': Cannot find field.\nInvalid JSON payload received. Unknown name \"body\" at 'message': Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message",
            "description": "Invalid JSON payload received. Unknown name \"sound\" at 'message': Cannot find field."
          },
          {
            "field": "message",
            "description": "Invalid JSON payload received. Unknown name \"title\" at 'message': Cannot find field."
          },
          {
            "field"
Message sent to Firebase for delivery, response:
: "message",
            "description": "Invalid JSON payload received. Unknown name \"body\" at 'message': Cannot find field."
          }
        ]
      }
    ]
  }
```

```json
{
    "message":{
      "token":`${TOKEN}`,
      "notification":{
        "title": 'Original Title',
        "body": 'And here is the body!',
        "data": { "data": 'goes here' }
      }
   }
  }
```

```json
Message sent to Firebase for delivery, response:
{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"data\" at 'message.notification': Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message.notification",
            "description": "Invalid JSON payload received. Unknown name \"data\" at 'message.notification': Cannot find field."
          }
        ]
      }
    ]
  }
}
```

**Comment by dpisarevskiy** [comment]
> 
> 
> I'm not sure if this fixes it. Hovewer, it will help with the @dpisarevskiy problem.
> 
> But @dpisarevskiy, you shouldn't send the `notification` object, cause then the remote message doesn't go through `expo-notifications` code. The `body` and `title` you can move to the `data` object.

Unfortunately isn't worked, can you send example? when I include data field, notification is not going to device. 
Also in this event's on device with apk got nothing, but Notifications2.addListener worked with push from EXPO servers

```js
import * as Notifications from 'expo-notifications';
import { Notifications as Notifications2 } from 'expo';

  Notifications.addNotificationResponseReceivedListener((response) => {
    console.log('App was opened by notification: ', response)
  })
  Notifications2.addListener((data) => {
    // This works for me
    console.log('App was opened by notification: ', data)
    setNotification(data);
  });
```

**Comment by lukmccall** [comment]
@dpisarevskiy, I believe you need to add an `experienceId`. Like here:
```json
{ 
    "message": { 
        "token": "<token>", 
        "data": {
            "body": "This is an FCM notification message!", 
            "title":"FCM Message",
            "experienceId": "@<user_name>/<app_name>"
        }
    } 
}
```

**Comment by dpisarevskiy** [comment]
> 
> 
> @dpisarevskiy, I believe you need to add an `experienceId`. Like here:
> 
> ```json
> { 
>     "message": { 
>         "token": "<token>", 
>         "data": {
>             "body": "This is an FCM notification message!", 
>             "title":"FCM Message",
>             "experienceId": "@<user_name>/<app_name>"
>         }
>     } 
> }
> ```

Thank you so much solution is working!) without duplicate. Excellent

**Comment by Cookizza** [comment]
I am having this problem on production :( just received 20+ duplicates. I can confirm we only hit expo server once from our API to trigger the notification...

**Comment by cruzach** [comment]
hey all, we've [added a note in our docs ](https://docs.expo.io/push-notifications/sending-notifications/) about this:
> Expo makes a best effort to deliver notifications to the push notification services operated by Apple and Google. Expo's infrastructure is designed for at-least-once delivery to the underlying push notification services; it is more likely for a notification to be delivered to Apple or Google more than once rather than not at all, though both are uncommon but possible.

and will continue to investigate why these duplicates are happening and how best to prevent them. In the meantime, we've also written some documentation on [how to send notifications to an Expo app directly through APNs and FCM](https://docs.expo.io/push-notifications/sending-notifications-custom/) so that anyone wanting finer-grained control over their notification infrastructure can have that. Although be aware that you won't be able to send notifications to the Expo client app that you're probably using for development since you won't have access to our push credentials.

**Comment by Bryksin** [comment]
The same issue, our service hit Expo API only once, however on mobile, we receive 2 notifications with a 100% repeatable rate, means it is happening all the time.

We use the recommended [Java Expo SDK](https://github.com/jav/expo-server-sdk-java) mentioned in the [official Expo Docs](https://docs.expo.io/push-notifications/sending-notifications/)

Here is a sending code:
```
private Disposable sendPushNotificationChunk(List<ExpoPushMessage> batch,
                 Map<String, NotificationReceiversMatchingModel> tokenReceiverMap) {
        log.info("Sending Expo Batch with " + batch.size() + " ExpoPushMessage");
        return Mono.fromFuture(pushClient.sendPushNotificationsAsync(batch))
            .doOnNext(expoPushTickets -> {
                for (int i=0; i < expoPushTickets.size(); i++) {
                    ExpoPushTicket ticket = expoPushTickets.get(i);
                    String correspondingToken = getCorrespondingTokenFromBatch(i, batch);
                    if(correspondingToken == null) {
                        log.error("Failed to find corresponding token from batch");
                        continue;
                    }
                    NotificationReceiversMatchingModel receiver = tokenReceiverMap.get(correspondingToken);
                    if (ticket.getStatus() == Status.OK) {
                        setBroadcastResult(correspondingToken, receiver, true, "");
                    } else {
                        if (ticket.getMessage().contains("is not a registered push notification recipient")) {
                            deleteInvalidTokenFromDB(getTokenFromErrorMessage(ticket.getMessage()));
                        } else {
                            setBroadcastResult(correspondingToken, receiver, false, ticket.getMessage());
                        }
                    }
                }
            })
            .subscribe();
    }
```

here are debug logs:
```
"log": "2020-09-02 11:59:00.048  INFO 1 --- [   scheduling-1] c.v.s.n.c.s.SchedulerConfiguration       : Processing 1 requests"
"log": "2020-09-02 11:59:00.049  INFO 1 --- [    elastic-263] c.v.s.n.s.b.NotificationBroadcastService : There 1 PUSH Notification will be send"
"log": "2020-09-02 11:59:00.051  INFO 1 --- [    elastic-265] c.v.s.n.s.b.PushNotificationService      : PUSH NotificationId: 131 will be send to ReceiverId: 12147793 to 1 nr of devices"
"log": "2020-09-02 11:59:00.100  INFO 1 --- [    elastic-264] c.v.s.n.s.b.PushNotificationService      : Total Push receiver tokens: 1"
"log": "2020-09-02 11:59:00.100  INFO 1 --- [    elastic-264] c.v.s.n.s.b.PushNotificationService      : Total Expo Batches: 1"
"log": "2020-09-02 11:59:00.100  INFO 1 --- [    elastic-264] c.v.s.n.s.b.PushNotificationService      : Total Expo Chunks to send: 1"
"log": "2020-09-02 11:59:00.100  INFO 1 --- [    elastic-265] c.v.s.n.s.b.PushNotificationService      : Sending Expo Batch with 1 ExpoPushMessage"
```
as you see according to logs there was one push request with a single receiver token which formed one batch with single ExpoPushMessage

However, there are 2 notifications arrived to end device
![](https://i.gyazo.com/84cf8ff9de77c09859debb2dd512a652.jpg)

P.S. kindly remind about previous [issue I posted](https://github.com/expo/expo/issues/8763) which would allow sanitizing the code and not manually map response ticket to receiver token based on a response order.

**Comment by Aryk** [comment]
> hey all, we've [added a note in our docs ](https://docs.expo.io/push-notifications/sending-notifications/) about this:
> 
> > Expo makes a best effort to deliver notifications to the push notification services operated by Apple and Google. Expo's infrastructure is designed for at-least-once delivery to the underlying push notification services; it is more likely for a notification to be delivered to Apple or Google more than once rather than not at all, though both are uncommon but possible.
> 
> and will continue to investigate why these duplicates are happening and how best to prevent them. In the meantime, we've also written some documentation on [how to send notifications to an Expo app directly through APNs and FCM](https://docs.expo.io/push-notifications/sending-notifications-custom/) so that anyone wanting finer-grained control over their notification infrastructure can have that. Although be aware that you won't be able to send notifications to the Expo client app that you're probably using for development since you won't have access to our push credentials.

FWIW - I'm having this issue on iOS using expo's push notification service.

Many of you are complaining about duplicate notifications sent back-to-back...I'm getting duplicate notifications sent weeks (sometimes months) after the first one was sent.

@cruzach  - Could this also be related to the way Expo's push notification infrastructure is set up?

**Comment by RRaideRR** [comment]
We also hit this problem. The duplicates are sent hours after the initial ones. Anyone has a solution for this?

**Comment by EmmanuelSkapple** [comment]
We have the same problem, every time you enter the app you get all the notifications of the day

**Comment by Gondolav** [comment]
Same problem, all notifications are sent twice

**Comment by klaucode** [comment]
Also same problem, some notifications are sent twice.

**Comment by dnwjn** [comment]
Also having this problem, some users complained that they received 30+ of the same notification.

**Comment by ps-george** [comment]
I'm having this problem, my users are getting 2x of the same notifications

**Comment by carl0shd** [comment]
same problem

**Comment by wuguishifu** [comment]
Same problem, both with locally scheduled notifications and notifications from a server.
