### ISSUE TITLE
Warning: AsyncStorage has been extracted from react-native core

### ISSUE THREAD

**Issue by ghasemikasra39** [expo/expo#8252]
### Environment

```
  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.19.2
```

### Steps to Reproduce

```javascript
import { Video } from 'expo-av';
<Video
  ref={ref => (this.videoRef = ref)}
  source={{ uri: paperPlane.publicUrl }}
  style={styles.video}
  shouldPlay={isVideoPlaying}
  isLooping
  resizeMode="cover"
  isMuted={isVideoMuted}
/>
```

### Expected Behavior

I should not get this warning

### Actual Behavior

```
ExceptionsManager.js:171 Warning: AsyncStorage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/async-storage
```

**Comment by byCedric** [comment]
Hi @ghasemikasra39! Thanks for the issue report. Could you provide a bit more info or [repro](https://stackoverflow.com/help/minimal-reproducible-example) for this one? I'm not sure what's going wrong here. We do have a custom `AsyncStorage` instance that we include in Expo projects. But that should not show this warning.

**Comment by ghasemikasra39** [comment]
Dear @byCedric. I am also getting the same warning when using other packages from expo (expo-image-picker "8.1.0").

**Comment by chahinaghrim** [comment]
Same issue happens to me ..

**Comment by cruzach** [comment]
I believe this a bare project, right @ghasemikasra39 ? Since you're on RN 62

**Comment by ghasemikasra39** [comment]
@cruzach It was an expo managed project. Then I ejected out of expo to bare workflow. Now I am getting this issue

**Comment by cruzach** [comment]
When moving to the bare workflow, you'll need to transition to using `@react-native-community/async-storage`. It seems like we may need to handle that appropriately if you're using expo packages that rely on react-native's asyncStorage

**Comment by ghasemikasra39** [comment]
@cruzach Yes, exactly. You should automatically move to `@react-native-community/async-storage`. The ones I had control on, are already changed to use  `@react-native-community/async-storage`. But I don't have control over expo internal mechanism.

**Comment by brentvatne** [comment]
you can use `@react-native-community/async-storage` in expo managed apps
