### ISSUE TITLE
backend.js:32 Tried to set property `videoStabilizationMode`

### ISSUE THREAD

**Issue by ghasemikasra39** [expo/expo#8253]
### Environment

```
  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.19.2
```

App's target: iOS

### Steps to Reproduce

```javascript
import { Camera } from 'expo-camera';
<Camera
  ref={component => (this.camera = component)}
  style={this.compileCameraStyle()}
  type={cameraType}
  flashMode={cameraFlashMode}
  ratio="16:9"
  videoStabilizationMode={Camera.Constants.VideoStabilization.off}
/>
```

### Expected Behavior

I should not get this warning

### Actual Behavior

```
Tried to set property `videoStabilizationMode` on view manager of view `ExponentCamera` when the view manager does not export such prop.
```

**Comment by chahinaghrim** [comment]
Faced the same. Can anyone help?

**Comment by jeb218** [comment]
Same here

**Comment by cruzach** [comment]
Can you share a snack that reproduces this? I've tried in [this snack](https://snack.expo.io/@charliecruzan/tactless-peach) and didn't get any errors

**Comment by jeb218** [comment]
@cruzach 

What is your expo diagnostics? Are you using an ejected project?

Mine is ejected, and my expo diagnostics are:

```
Expo CLI 3.20.1 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
      Shell: 5.0.16 - /bin/bash
    Binaries:
      Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.7 - ~/.nvm/versions/node/v13.9.0/bin/npm
    npmPackages:
      expo: ^37.0.7 => 37.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: 0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.1
```

It could be a difference in expo/react-native/other module verions - or maybe only works properly in non-ejected projects.

Also, what version of expo-camera is in your package.json? Mine is "expo-camera": "^8.2.0",

**Comment by ghasemikasra39** [comment]
Dear @jeb218 
Mine is `8.2.0`, same as you. My project is an ejected project. I mean, we were using expo managed-workflow, but then we ejected out of expo and now we are getting this warning in bare-workflow.

**Comment by gilbert** [comment]
Same here. Was working fine with managed, but after ejecting we're now getting the warning. Using expo-camera v9.0.0

**Comment by chip-astg** [comment]
I get the same warning when including property videoStabilizationMode, also with a bare workflow.

If I omit videoStabilizationMode from the properties, I get a different warning (using the front camera on an iPhone X):

`Video Stabilization is not supported on this device.`

Using the rear camera (which presumably has video stabilization), and again with videoStabilizationMode property omitted, I get no warning.

So it is ignoring the videoStabilizationMode property but trying to set it to something other than `off` behind the scenes.

**Comment by ErnestoFGonzalez** [comment]
Any updates on this? I'm facing the same issue after ejection with `"expo-camera": "~11.0.2"`.

**Comment by mikefogg** [comment]
Yep, I'm getting the same thing. Any idea why this may be happening? I have expo installed with unimodules in a bare react-native workflow and the camera itself works fine for taking photos, but I get the above warning and I'm unable to record video.

**Comment by ErnestoFGonzalez** [comment]
> Yep, I'm getting the same thing. Any idea why this may be happening? I have expo installed with unimodules in a bare react-native workflow and the camera itself works fine for taking photos, but I get the above warning and I'm unable to record video.

This warning shouldn't prevent you from recording with the camera. Is it possible you have a problem elsewhere?

**Comment by nova2201** [comment]
I have expo installed with unimodules in a bare react-native workflow. I am running into the same thing. It works in debug but does not record anything in the release build. Tried on Both iPhone XR and a newer iPad.

**Comment by ghasemikasra39** [comment]
Dear @nova2201 
So far I could not find any solution for it.

**Comment by adriandiaz** [comment]
Having this issue as well

**Comment by rusakovic** [comment]
Confirm this issue. 
iPhone 7. 
Strange, that is still not resolved

**Comment by gbower30** [comment]
This still has no resolution?
