### ISSUE TITLE
iOS: Splash screen background color does not match in-app background color

### ISSUE THREAD

**Issue by helios1138** [expo/expo#826]
I have splash screen set up with `"backgroundColor": "#99ca25"`, the same color is then used as a background on the startup screen in the app itself. On Android (at least in emulator) they look the same, but on iOS they look visually different.

Side-by-side screenshot:
![img_1520 copy](https://user-images.githubusercontent.com/7106681/31852280-ba88e8ac-b67d-11e7-9b94-15ee4f340601.png)

**Comment by terribleben** [comment]
Thanks for the report. Is this in Expo Client or in an iOS standalone app created with `exp build:ios`? Can you paste your full `splash` configuration including the assets you're using, if any?

**Comment by helios1138** [comment]
>Is this in Expo Client or in an iOS standalone app

standalone

> Can you paste your full `splash` configuration

```
"splash": {
  "image": "./src/assets/images/splash-logo.png",
  "backgroundColor": "#99ca25"
}
```

> assets you're using

`splash-logo.png` is a regular transparent png with white logo, size: 1200x285

**Comment by brentvatne** [comment]
confirmed this on an empty new project:

![confirmed](https://user-images.githubusercontent.com/90494/32021192-8a0620ca-b987-11e7-9e1c-08f97144adba.png)

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#99ca25',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

```
{
  "expo": {
    "name": "NewProject",
    "description": "An empty new project",
    "slug": "NewProject",
    "privacy": "unlisted",
    "sdkVersion": "22.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/icon.png",
      "resizeMode": "contain",
      "backgroundColor": "#99ca25"
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "host.exp.issueeighttwosix"
    }
  }
}
```

**Comment by Dygerati** [comment]
I believe I'm having the same issue, primarily with ios. 

Here's my configuration in `app.json`:
```    
"splash": {
      "image": "./app/resources/misc/splash.png",
      "backgroundColor": "#440000",
      "resizeMode": "contain"
    }
```

And I've attached a screenshot directly from the device below. Taking a color picker to the image, the color on outer perimeter, which should be the specified `#440000`, is actually `#570500`. It looks pretty tacky and I'm holding off on rolling it out. 

Any idea if there's a fix here?

![img_0004](https://user-images.githubusercontent.com/444632/32060643-008a7554-ba35-11e7-8619-33403fc504d5.PNG)

**Comment by helios1138** [comment]
@terribleben any progress on this?

**Comment by terribleben** [comment]
Hey there - @aalices has taken a look, and there is a discrepancy between the color profile being used by the native XIB file we're generating (sRGB apparently) vs. what JS is using in your app. We don't have a solution yet but I thought I'd update here with details about that diagnosis.

**Comment by helios1138** [comment]
@terribleben thanks for the update!

**Comment by aalices** [comment]
Still investigating but I've found a kind of workaround - if developing on MacOS 10.6+ there's an app called ColorSync Utility. It has a Calculator tab where one can provide values from one profile and get them in another. 

So, using @Dygerati example, he wants the launch background to be #440000 that is RGB(68, 0, 0). In the Calcuator, choose sRGB profile, 8-bit range, and type the RGB values. In the right column choose Generic RGB and there you have the (almost, they still can differ slightly) colour. All you need to do is convert this to hex and put as an attribute in iOS `splash` configuration. 

I still haven't found any online converter so you guys can use this workaround if you're not using Mac. I'll also still try to find an automatic way to have the colors set properly.

**Comment by helios1138** [comment]
@aalices thank you, this solution worked for my case

**Comment by anjalsan** [comment]
![image](https://user-images.githubusercontent.com/11261003/34515950-ab9cac8c-f09a-11e7-86e1-eab711d407f2.PNG)

I'm facing the same issue. Here's my configuration in app.json:
`"splash" : {
        "backgroundColor" : "#111111",
        "resizeMode" : "contain",
        "image" : "./assets/icons/splash_screen_ios.png"
      },`

its converting #111111 to #151515. using Sketch I found the desired color (sRGB profile, 8-bit range). its #0E0E0E. and now it's working.

**Comment by onrige** [comment]
Any updates on this? I am also have such problems and workaround it (thanks to @aalices) but it would be great if `build` will do this automatically.

**Comment by ericorruption** [comment]
Using the ColorSync Utility didn't work for me. I was trying to convert the color #7746e8 but still got a slightly different tone than the one I use on the splash screen.

**Comment by bluestann** [comment]
Also having issues using this conversion. I want the background to be "#4b2e83", after the conversion it is "#3A1C70". However, the color still doesn't match and it seems like they both changed when using the converted color.

**Comment by AdamPD** [comment]
This is a pretty bad bug for splash screens.  It really does make the app quite unprofessional.

**Comment by aatreya** [comment]
We manually fixed the issue in our detached iOS app by simply using the color picker in Xcode to select the background color from our image. I noticed this resulted in the color space changing from "calibratedRGB" to "sRGB". Perhaps this might help in figuring out a way to fix the issue?

```
                     </constraints>
                 </imageView>
             </subviews>
-            <color key="backgroundColor" red="0.00392156862745098" green="0.6627450980392157" blue="0.9294117647058824" alpha="1" colorSpace="calibratedRGB"/>
+            <color key="backgroundColor" red="0.007847989909350872" green="0.66200798749923706" blue="0.92825180292129517" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
             <constraints>
                 <constraint firstAttribute="trailing" secondItem="Bsh-cT-K4l" secondAttribute="trailing" id="4Bz-Vy-RfD"/>
                 <constraint firstItem="Bsh-cT-K4l" firstAttribute="top" secondItem="OfY-5Y-tS4" secondAttribute="top" id="5FF-OI-m4s"/>
```

**Comment by terribleben** [comment]
Landed fix internally, will ship with SDK 29

**Comment by ndamofli** [comment]
Issue still persist in ios production app with SDK 29

**Comment by jenskuhrjorgensen** [comment]
Thanks for this thread - it helped me solve my problem. 
FWIW, for me it was enough to change the color profile in Xcode to sRGB:
![Screenshot 2019-05-21 at 09 57 07](https://user-images.githubusercontent.com/28528363/58078414-fcf5bd80-7bae-11e9-9dc0-047273a7c1e3.png)
