### ISSUE TITLE
Eject Expo SDK 37 - iOS won't build Bundle React Native code and images phase

### ISSUE THREAD

**Issue by chasecf** [expo/expo#8266]
### Environment

  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.20.3

### Steps to Reproduce

Run `expo eject` and try running `yarn ios` or go to iOS folder and build the `.xcworkspace`

### Expected Behavior

Expect the iOS project to build without error

### Actual Behavior

Receive error: 

```
+ DEST=/Users/croossin/Library/Developer/Xcode/DerivedData/Spot-dacyrpbiwrmdvabvpmkrcdgtuwuz/Build/Products/Debug-iphonesimulator/ios.app
+ [[ Debug = *Debug* ]]
+ [[ ! iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ [[ iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ echo 'Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.'
Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.
+ exit 0
```

### Remedies

If I remove the line `../node_modules/expo-updates/scripts/create-manifest-ios.sh` in the `Bundle React Native code and images` build phase, it will build without error.  So it is something with the expo updates create manifest.

**Comment by esamelson** [comment]
Thanks very much for the report @chasecf . The fix for this is to add a `metro.config.js` file to your project with [these contents](https://github.com/expo/expo/blob/7d0e9912b1b4f2e8b9e66719fd81ddcbf2fff65b/templates/expo-template-bare-minimum/metro.config.js). We'll be shipping a fix for this to `expo init` and `expo eject` very soon.

**Comment by chasecf** [comment]
@esamelson Unfortunately we are still seeing the issue.  We already had a `metro.config.js` file in our root application.  I add the extra transformer for `assetPlugins` but still are running into this error...  Here is what our `metro.config.js` file looks like with your updates:

```javascript
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer"),
      assetPlugins: ["expo-asset/tools/hashAssetFiles"],
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"],
    },
  };
})();
```

Do you see what else might be causing the issue in this file?

**Comment by esamelson** [comment]
Hey @chasecf - is there a further error message in your Xcode build logs underneath the one you posted?

Also, just to be sure, have you shut down and restarted your packager server since changing metro.config.js?

**Comment by chasecf** [comment]
Fully shutting down Xcode and killer the package server fixed it.  Thanks so much for the speedy response! Awesome!

**Comment by nghiaoi3** [comment]
the issue still persists even though I added the file metro.config.js, and shut down Xcode and server. I am using a ejecte Expo project. Please fix soon. This issue is verv very annoying.

**Comment by brentvatne** [comment]
@nghiaoi3 - please create an issue and fill out the issue template. if possible provide a reproducible example. we can't help you based off of knowing that it is annoying for you - i believe you that it is, but we are helpless without more information. locking this but look forward to your new issue report!
