### ISSUE TITLE
Warning when fresh installing NPM pacakges

### ISSUE THREAD

**Issue by hos4m** [expo/expo#827]
Hello,

I have this issue with NPM packages, whenever I try to install a new package, I got a warning like this:

https://i.imgur.com/8KMcBmB.png

This warning I got when trying to configure ESLint.

**Comment by brentvatne** [comment]
peer dependency warnings happen all the time with npm and confuse lots of people. you can generally ignore them :(

**Comment by brentvatne** [comment]
also, you can use yarn which has (in my opinion) a more reasonable semver strategy for peer dependencies and so you get less warnings
