### ISSUE TITLE
Crypto in Expo app?

### ISSUE THREAD

**Issue by enguerranws** [expo/expo#8270]
## 🐛 Bug Report
Hi,

I'm using crypto-js to handle AES encryption in my Expo app. Not sensitive data, but still, better be safe than sorry. 
Recently, I noticed that `crypto-js`, which was working fine, stopped working since (I guess) I upgrade to Expo 37, throwing this error:
```
The package at "node_modules/crypto-js/core.js" attempted to import the Node standard library module "crypto". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.
```

Any idea how I can keep using an AES encryption in Expo?

### Environment
  ```
Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.7 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.3.8 
    npmGlobalPackages:
      expo-cli: 3.18.6
```

**Comment by brentvatne** [comment]
does this suit your needs? https://docs.expo.io/versions/latest/sdk/crypto/

**Comment by enguerranws** [comment]
@brentvatne No, it does not provide AES encryption, which I use in my app workflow. IMHO, `expo-crypto `actually just provides hash, not encryption.

**Comment by brentvatne** [comment]
might be helpful to check your git history to see what version of crypto-js you were using before upgrading. it looks like the file that is called out in the error message changed 3 months ago with a commit message related to what you're seeing https://github.com/brix/crypto-js/blob/develop/src/core.js

**Comment by brentvatne** [comment]
this is causing the error: https://github.com/brix/crypto-js/blame/develop/src/core.js#L28

metro will support conditional imports in the near future and this type of thing will work but currently you can't wrap try/catch around require with metro because all imports are static

**Comment by brentvatne** [comment]
closing this because it's an issue with crypto-js react-native compatibility and the error we provide here is actually very accurately pointing at the problem of the crypto nodejs api not being available in expo managed workflow / react-native apps. you could open an issue on that repo and suggest they use .native.js extension to fork the logic to work with react-native, or in the future this may work using https://github.com/facebook/metro/pull/511

**Comment by enguerranws** [comment]
Thanks @brentvatne for looking into this! I'll open an issue on crypto-js repo. Meanwhile, I'll downgrade the package in my package.json.

**Comment by asmailov** [comment]
> Thanks @brentvatne for looking into this! I'll open an issue on crypto-js repo. Meanwhile, I'll downgrade the package in my package.json.

Can you link to the issue inthe crypto-js repo?

**Comment by josh-gree** [comment]
Anybody got any updates on this? Can't seem to find any packages for doing RSA encryption that work with managed expo? Do I need to move to bare workflow in order to do it?

**Comment by Segfaultd** [comment]
Imo `expo-crypto` should be named `expo-hashing` cause it does nothing related to cryptography.

It's a shame that there is no real package available to do cryptographic encryption on Expo managed workflow. I mean, isn't it a must-have?
