### ISSUE TITLE
create-manifest scripts in expo updates missing

### ISSUE THREAD

**Issue by HugoChengMyC** [expo/expo#8271]
### Environment

Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.0.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.8 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^2.18.2 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.20.1

### Steps to Reproduce
expo eject 
npm install expo-updates
open android studio -> build 

### Expected Behavior

build should work after following documentation of setting up expo updates for bare workflow

### Actual Behavior

android studio returns build error "/node_modules/expo-assets/scripts/create-manifest-android.gradle' as it does not exist"

following the guide to set up expo -updates. but so far its not working!. in your instructions you listed to add this line
" …/node_modules/expo-updates/scripts/create-manifest-ios.sh " to the build_phases in xCode and " …/node_modules/expo-updates/scripts/create-manifest-android.gradle" in the build.gradle file in android, but i checked and none of these files exist, therefore the build fails. I tried to remove the line, the build works but the assets are not bundled correctly . please update your documentation or include steps to get these files. it is frustrating trying to debug this and trying to get a release build out

**Comment by brentvatne** [comment]
hi @HugoChengMyC! what version of expo-updates is installed in your project?

**Comment by giautm** [comment]
I face to same issue, then I ugprade to `expo-updates@0.2.0`.

**Comment by HugoChengMyC** [comment]
i have expo-updates 0.2.1

here is the package.json

{
  "name": "myco-mobile-app",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.4",
    "jest": "~25.2.6",
    "jest-enzyme": "^6.0.1",
    "jest-expo": "^37.0.0",
    "jest-serializer-enzyme": "^1.0.0",
    "jetifier": "^1.6.5",
    "react-dom": "16.9.0",
    "react-native-mock": "^0.3.1",
    "react-native-scripts": "1.14.0",
    "react-native-unimodules": "~0.8.1",
    "react-test-renderer": "^16.4.0",
    "sinon": "^5.0.10"
  },
  "scripts": {
    "postinstall": "jetify",
    "startTest": "npm test; expo start",
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
    "setupFilesAfterEnv": [
      "./__mocks__/mockFirebase"
    ],
    "automock": false
  },
  "dependencies": {
    "@babel/core": "^7.1.0",
    "@expo/vector-icons": "^10.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "d3": "^4.13.0",
    "expo": "^37.0.8",
    "expo-asset": "^8.1.5",
    "expo-font": "~8.1.0",
    "expo-permissions": "~8.1.0",
    "expo-secure-store": "~8.1.0",
    "expo-splash-screen": "^0.2.3",
    "expo-updates": "^0.2.1",
    "jsdom": "^11.11.0",
    "prop-types": "^15.6.1",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",
    "react-native-calendar-picker": "^5.14.0",
    "react-native-chip-view": "0.0.11",
    "react-native-dash": "0.0.9",
    "react-native-elements": "^1.1.0",
    "react-native-extended-stylesheet": "^0.10.0",
    "react-native-firebase": "^5.2.3",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-material-tabs": "^3.8.1",
    "react-native-modal": "^5.2.0",
    "react-native-modal-datetime-picker": "^4.7.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-picker-dropdown": "^0.1.2",
    "react-native-pinch-zoom-view": "^0.2.0",
    "react-native-progress-circle": "^2.0.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-render-html": "^3.10.0",
    "react-native-screens": "~2.2.0",
    "react-native-simple-radio-button": "^2.7.1",
    "react-native-svg": "11.0.1",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-tag-autocomplete": "^1.0.21",
    "react-native-timeline-listview": "^0.2.3",
    "react-native-timeline-theme": "0.0.9",
    "react-native-unimodules": "~0.9.0",
    "react-native-vector-icons": "^6.3.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^2.18.2",
    "whatwg-fetch": "^2.0.4"
  },
  "rnpm": {
    "assets": [
      "./app/assets/fonts"
    ]
  }
}

**Comment by brentvatne** [comment]
thanks! @esamelson will be looking into this right away and will get back to you soon

**Comment by giautm** [comment]
`scripts` still exists in` expo-updates@0.2.1`

<img width="693" alt="Screen Shot 2020-05-13 at 03 11 39" src="https://user-images.githubusercontent.com/12751435/81740692-90628580-94c7-11ea-8737-17887e92ccaf.png">

**Comment by brentvatne** [comment]
@HugoChengMyC - can you share the contents of your node_modules/expo-updates/scripts directory?

**Comment by brentvatne** [comment]
@HugoChengMyC - are you sure 0.2.1 is actually installed? we can't reproduce this.

**Comment by HugoChengMyC** [comment]
afte i installed 0.2.0 the scripts folder is back. but im not sure why the newer version didnt work either

**Comment by brentvatne** [comment]
that wouldn't happen, npm install will always give you the same package, i think something else must have occurred. glad it was resolved. if it happens again somehow please open a new issue and provide some info for how we can reproduce it! thanks

**Comment by nghiaoi3** [comment]
this issue also happen in my iOs project. I cannot build my project, the error always displayed in XCode: 

" line 4: ../node_modules/expo-updates/scripts/create-manifest-ios.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code"

**Comment by oximer** [comment]
I'm having the error reported here. https://github.com/expo/expo/issues/8294

Then, I notice that this error is related to expo-update 0.2.0
I tried to downgrade it to 0.1.0

Now, I'm having the same error than @nghiaoi3 
I eject my project 1 day ago.

**Comment by oximer** [comment]
@brentvatne

**Comment by mattaronoff** [comment]
I'm also seeing this combination of errors (this error prior to upgrading to expo-update 0.2.1, and then #8294 afterwards, on a newly ejected project that was working fine as a managed app.

**Comment by oximer** [comment]
So I notice that if I downgrade expo-update to 0.1.0 again and then remove ../node_modules/expo-updates/scripts/create-manifest-ios.sh scripts from the Build Phases. Access it through xcode. 

```
Build Phases
In Xcode, under the Build Phases tab of your main project, expand the phase entitled "Bundle React Native code and images." Add the following line to the bottom of the script:

../node_modules/expo-updates/scripts/create-manifest-ios.sh
This provides expo-updates with some important metadata about the update and assets that are embedded in your IPA.
```

I'm not pretty sure about the consequences of it. 
It seems to me that expo creates an inconsistent state for those that eject their projects on the last days.

@mattaronoff

**Comment by mattaronoff** [comment]
@oximer Thanks, will check that out later today. Question for anyone: I'd love to understand better what that script is intended to do before removing it... :-)

**Comment by oximer** [comment]
Looking for it, it seems related to expo-assets.
Since I'm not using it on my project, I hope it doesn't cause troubles.

**Comment by mattaronoff** [comment]
FYI, this seems relevant for my case (newly ejected project where I can restart the eject: https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf

**Comment by esamelson** [comment]
@mattaronoff - thanks for pointing this out!! We've just released an update to the expo package so that `expo install` will use the latest version of expo-updates, and in `expo-cli@3.20.6` we've updated the `expo eject` command to use the version of expo-updates that's configured in the native project. Hopefully that will address the issue you're referring to.

**Comment by rrnara** [comment]
Did you have metro.config.js already on your repo before the eject? If so do you have the following line inside transformer:
`assetPlugins: ['expo-asset/tools/hashAssetFiles']`

**Comment by RupamShaw** [comment]
I am using bareflow used expo init same issue facing
````
Showing Recent Errors Only
Error: The hashAssetFiles Metro plugin is not configured. You need to add a metro.config.js to your project that configures Metro to use this plugin. See https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#metroconfigjs for an example.
````

**Comment by brentvatne** [comment]
read the error message and do what it tells you to do :)

**Comment by eugeniogalioto** [comment]
I had the eject->upgrade flow described above by @mattaronoff 

I have seen that the createManifest.js file in scripts folder in expo-updates is not called at all. That file generates app.manifest that causes the exception "embedded manifest is invalid or could not be read". I have this issue on Android in debug mode both on simulator and physical device. I have created a new project and ejected it to find some differences but I have not found nothing that helps. How could I patch my flow to reflect the update->eject flow?
