### ISSUE TITLE
[docs] Make push notifications doc easier to digest

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8274]
It's pretty long and there is tons of content and code. We should look into how we can make the doc easier to navigate and digest. I think having a table of contents sidebar would be very helpful here.

**Comment by sjchmiela** [comment]
If possible, being able to have subpages (Notion-like) under an API or a guide would seem to me like a great addition:
- not only we could we group all the relevant information in one place (eg. [README of `expo-notifications`](https://github.com/expo/expo/tree/master/packages/expo-notifications) is starting to be a bit unwieldy with all the information regarding setup, configuration, Expo server API, module API etc. + FCM configuration, Uploading Server Credentials)
- consuming topics would be easier if the page contains only one topic at a time with a clear start and an end

![Zrzut ekranu 2020-05-13 o 12 50 44](https://user-images.githubusercontent.com/1151041/81803858-85841100-9518-11ea-9959-42cace3e1f4d.png) ![Zrzut ekranu 2020-05-13 o 12 51 00](https://user-images.githubusercontent.com/1151041/81803870-8a48c500-9518-11ea-9201-255f72caa555.png)
