### ISSUE TITLE
[nextjs] AppLoading does not appear to work when using next.js

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#8275]
### Environment

  Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: 37.0.7 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.8.0

### Steps to Reproduce

Add `AppLoading` to a next app to load fonts.

### Expected Behavior

App renders and runs.

### Actual Behavior

`× ReferenceError: window is not defined`

or 

`ReferenceError: localStorage is not defined`

### Reproducible Demo

https://github.com/chrisdrackett/apploadingnext

**Comment by byCedric** [comment]
Hi @chrisdrackett, it seems that `<AppLoading />` includes error handling that is not supported on web or with NextJS. We will take a closer look if this can work without this on web. (cc @EvanBacon) For now, I would recommend not-using app loading. Instead, you can use `componentDidMount` as a workaround to load the fonts. Here is an example from the repo you linked:

```
import * as React from 'react';
import * as Font from 'expo-font'
import { Image, Text, View } from 'react-native';
import Constants from 'expo-constants';
import { Asset } from 'expo-asset';

export default class App extends React.Component {
  state = {
    isReady: false,
  };

  async componentDidMount() {
    await this.loadResources();
    this.setState({ isReady: true });
  }

  render() {
    return (
      <View style={{ flex: 1, backgroundColor: 'red' }}>
        <Text style={{ fontFamily: 'Arial' }}>It works!</Text>
      </View>
    );
  }

  async loadResources() {
    await Promise.all([
      Font.loadAsync({
        'Arial': require(`../assets/Arial.ttf`),
      }),
    ]);
  }
}
``` 

Hope this helps!

**Comment by chrisdrackett** [comment]
no worries! We found a work around :)

might be worth updating https://docs.expo.io/versions/latest/sdk/app-loading/#__next as it says it should work on web!

**Comment by EvanBacon** [comment]
`web` environments are different to `node` (SSR) environments.
