### ISSUE TITLE
Hot reload doesn't work

### ISSUE THREAD

**Issue by onrige** [expo/expo#828]
Hot reload doesn't work after update to 22 version. iOS 10.3 Simulator. I see messages about hot reload but there is no changes on the screen.

**Comment by christiangenco** [comment]
On Expo XDE 2.21.0, set to `Host: Tunnel` and `Protocol: exp`, scanning the QR code on iOS 11.0.3 with Expo 2.0.1 doesn't do anything

Changing the `Protocol` to `http` and entering the URL manually opens the app metadata in Safari.

It's working on my Android phone.

**Comment by terribleben** [comment]
Hi @onrige, enabling Hot Reloading currently works for me on the Expo "tab navigation" template project, running SDK 22, iOS 11 simulator, iOS client 2.0.1. Changes I make are reflected in the app right away. Can you provide a [Snack](https://snack.expo.io/) that reproduces this issue for you?

@christiangenco it sounds like you are reporting a separate issue about QR codes not doing what you expect. Can you open another thread?

**Comment by onrige** [comment]
@terribleben it would be difficult to do something in snack like in my case but I can try. I am using RNRF v4 (based on React Navigation) if it can help.

**Comment by brentvatne** [comment]
hello! please post this issue on rnrf or react-navigation repo unless you can giver us a reproducible example without either of those libraries! if you can do that, please re-create this issue with it. thanks!

**Comment by onrige** [comment]
I found the solution solution. If someone will catch the same issue - all you need is to delete yarn.lock (or package-lock.json i think) and install all fresh packages. In my case it did the trick.

**Comment by hmajid2301** [comment]
@onrige Solution worked for me, I cannot seem to hot reload until I delete the package-lock.json file.

**Comment by navedkhan012** [comment]
i my case it play on production mode when change it to develpoment  mode it work fine.

**Comment by Foveluy** [comment]
@onrige save my day & ass
