### ISSUE TITLE
Standalone IPA deployment issue 

### ISSUE THREAD

**Issue by santhoshdasari786** [expo/expo#8285]
I had deployed the IOS app to app store but rejected due to crash in 13.4.1
To know more about issue :- [https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple113/v4/7c/b0/47/7cb047a8-2224-04d2-2ffc-8f958650e753/attachment-4470690927062855060crashlog-BD026F49-8E71-4050-912C-1875D1F62CD7.txt?accessKey=1589603683_3756099918839185616_USNRwH8LIhM%2FCHj%2FFFTgi9I8B%2Fa0I8r9%2Bw5RNWF2Bp4ZoPQWqGEOp2k8ctLt11szw8d3%2BLap%2BeCRur2PQufvYW0BL%2BBnQLkoWBlb7rt3gOqInY2N38ZF2ZIXAYKv0HWQeYmLzd1S191rNR6n91%2B30ln2heXD1QQ4JCS1PPDKnmfqE1iWARo4D9Jy0iU5OZozDWaJnrIX1EkN4oxVaYOu%2BjuJ%2BY5caxHDQKSl31y%2FkFNoazfhj%2Fh%2BbVPLChg3R6Vl](url)

When i Decoded the crash issues i got error as below
 __38-[SEGSegmentIntegration staticContext]_block_invoke (in ComJangphaiSefu) (SEGSegmentIntegration.m:192)
and 
(EXUserNotificationPermissionRequester.m:74)

Error trace logs from apple team :-
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000010
VM Region Info: 0x10 is not in any region.  Bytes before following region: 4302880752
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 000000010078c000-0000000100790000 [   16K] r-x/r-x SM=COW  ...mJangphaiSefu

.....
Thread 3 name:  Dispatch queue: host.exp.exponent.EXUserNotificationCenter
Thread 3 Crashed:
0   libobjc.A.dylib               	0x000000019fa8e6ac 0x19fa6d000 + 136876
1   ComJangphaiSefu               	0x00000001008fbfb0 0x10078c000 + 1507248
2   ComJangphaiSefu               	0x00000001008fbfb0 0x10078c000 + 1507248
3   libdispatch.dylib             	0x000000019f9fcec4 0x19f9fb000 + 7876
4   libdispatch.dylib             	0x000000019f9fe33c 0x19f9fb000 + 13116
5   libdispatch.dylib             	0x000000019fa0485c 0x19f9fb000 + 39004
6   libdispatch.dylib             	0x000000019fa05290 0x19f9fb000 + 41616
7   libdispatch.dylib             	0x000000019fa0e928 0x19f9fb000 + 80168
8   libsystem_pthread.dylib       	0x000000019fa65714 0x19fa62000 + 14100
9   libsystem_pthread.dylib       	0x000000019fa6b9c8 0x19fa62000 + 39368

**Comment by cruzach** [comment]
Hey @santhoshdasari786, we need quite a bit more info here to help you. Please open a new issue and follow the bug report template we provide, especially including a minimal, reproducible demo. Thanks!
