### ISSUE TITLE
[expo-local-authentication] disableDeviceFallback option in android

### ISSUE THREAD

**Issue by Jekiwijaya** [expo/expo#8286]
## 🐛 Bug Report
I think parameter `disableDeviceFallback` in [LocalAuthentication. authenticateAsync(options)](https://docs.expo.io/versions/latest/sdk/local-authentication/#localauthenticationauthenticateasyncoptions) should also set false in android
https://github.com/expo/expo/blob/936202cf5132a34b920b64955171bb09eb0a7b7a/packages/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java#L142

### Expected Behavior
when passing `disableDeviceFallback` true in android, also disable pin fallback in android

### Actual Behavior
`disableDeviceFallback` only supported for ios

**Comment by LinusU** [comment]
Just realised that I have already volunteered to submit a PR for this, but never got the time 😬 

ref: https://github.com/expo/expo/pull/6891#issuecomment-581794377

If anyone wants to pick it up, it should be pretty straight forward. When the option `disableDeviceFallback` is given as `true`, pass `false` to `setDeviceCredentialAllowed` instead of `true`.

**Comment by byCedric** [comment]
Fixed by #8219 🚀

**Comment by gie3d** [comment]
Hi @byCedric thank you very much. I'm really looking forward for that PR. Seen it's been merged but would this be release as part of the new expo version or this can be added the latest version manually? (I tried `expo install expo-local-notification@9.1.1`)

**Comment by byCedric** [comment]
Hi @gie3d! You should be able to install `9.1.1`, outside the `expo install` command 😄 e.g. with `yarn add expo-local-authentication@9.1.1`. But be aware, this only works for bare workflow projects at the moment (includes native code changes). I'm afraid this change won't make SDK 37. We are currently testing and packing SDK 38, so most of our resources go to this now. We hope to get this out soon!
