### ISSUE TITLE
Throws error 'variable is not defined' for variable which is not in the codebase anymore

### ISSUE THREAD

**Issue by jan-scorl** [expo/expo#8287]
### Environment

Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.8.0/bin/npm
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.19.2

### Steps to Reproduce

I added some code to my app which led to the error `variable is not defined`. `variable` is just a placeholder name for a state variable I created. I then removed any instances and references to `variable` from my code, restarted the bundler, even deleted `node_modules` and it still shows the error `variable is not defined`.

### Expected Behavior

Since the variable is completely removed from the codebase, it shouldn't throw this error anymore.

### Actual Behavior

It throws the error which breaks the app.

```
timeRemaining is not defined
- node_modules/expo/build/ExpoLazy.js:18:42 in <global>
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:13042:30 in finishClassComponent
- ... 9 more stack frames from framework internals
```

**Comment by jan-scorl** [comment]
After waiting for 30 minutes, the error suddenly disappeared. But then the app previewed in Simulator did not respond to any code changes anymore. I had to exit the live preview in the expo app in Simulator, clear the list of 'recently opened apps' in the expo app in Simulator and then restart the bundler. Now it's at least reflecting my code changes again. There seems to be a caching issue with the expo app in Simulator.

**Comment by byCedric** [comment]
Hi @jan-scorl! The metro bundler has a built-in cache to deliver the changes in your code as fast as possible. Have you tried running your project with `expo start --clear`? This should empty that cache and rebuild your full project from scratch.

**Comment by jan-scorl** [comment]
I can’t reconstruct the issue so I couldn’t test the command yet. However, I will keep it in mind in case this will happen again. Thank you.
