### ISSUE TITLE
expo-updates crashing (on debug)

### ISSUE THREAD

**Issue by nicwhitts** [expo/expo#8289]
I ejected from managed into standalone. iOS

I'm trying to get expo-updates setup. But running into problems.

Firstly, following the docs. I try to add `../node_modules/expo-updates/scripts/create-manifest-ios.sh` into `Bundle React Native code and images` phase.

But i don't have this phase.

If i add into another phase, it won't build with error:

```
Error: The hashAssetFiles Metro plugin is not configured. You need to add a metro.config.js to your project that configures Metro to use this plugin. See https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#metroconfigjs for an example.
```
I have my `metro.config.js` file setup as requested.

If i remove this build phase script,  it crashes when i `checkForUpdateAsync` with error:
```
2020-05-13 14:43:06.006469+0100 ios[430:24926] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[OS_dispatch_data writeToFile:options:error:]: nil file argument'
```

This seems to only happen in debug? Can't figure out how to confirm its working in release yet

I don't quite know why i can't align with the docs here, as nothing seems to be working

But the default OTA functionality works fine from expo, but id like to control this more

**Comment by joshglenn** [comment]
Hi @nicwhitts . I am getting the same `hashAssetFiles Metro plugin is not configured` error. And I am on a brand new project, which uses the expo bare typescript template (not managed expo). 

I am wondering if the issues we're having are somehow related.

Out of curiosity, what version of xcode are you running?

**Comment by brentvatne** [comment]
is there any chance that you two have a react-native packager instance running for another project? i cannot reproduce this.

if either you can share a reproducible example that would be helpful. please note that it does not reproduce for us with a brand new project, so you may want to test in that situation and compare it with your project.

**Comment by joshglenn** [comment]
Hi Brent. Thanks for the follow up. I don't have a reproducible example. I thought I did. But after I ran `yarn cache clean` then `yarn` again. Now everything is fine. Which is weird. Because I literally did just that in the beginning. expo init, pod install, then yarn ios. Should be the same outcome, right?

**Comment by brentvatne** [comment]
i think it's possible that you had a separate metro bundler instance running and didn't notice, it's easy for that to happen because it will spawn a new terminal window when you run a build and then you minimize it and forget about it. something to keep an eye out for when you're working on a bare app

**Comment by nicwhitts** [comment]
> is there any chance that you two have a react-native packager instance running for another project? i cannot reproduce this.
> 
> if either you can share a reproducible example that would be helpful. please note that it does not reproduce for us with a brand new project, so you may want to test in that situation and compare it with your project. and if ti happens to you in that situation, try rebooting your computer to be totally sure there isn't some other metro process running that is getting the bundle requests.

Thanks for the info. I solved the `hashAssetFiles` problem because you were indeed right about the extra metro bundler running!

I now can build successfully, but i still have the original problem of 
``` 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[OS_dispatch_data writeToFile:options:error:]: nil file argument'
```

I will try to create a reproducible demo but not sure how i can do this right now, do you have any ideas what might be causing this? It seems to only 'crash' on debug. Haven't verified if it actually works on release

**Comment by nicwhitts** [comment]
It seems that in release mode the `reloadAsync` isn't working either.. 
It says that there is always a new version available

**Comment by rrnara** [comment]
Did you have metro.config.js already on your repo before the eject? If so do you have the following line inside transformer:
`assetPlugins: ['expo-asset/tools/hashAssetFiles']`
