### ISSUE TITLE
[Expo 37] No native ExpoFirebaseCore module found, are you sure the expo-firebase-core module is linked properly?

### ISSUE THREAD

**Issue by oleks-fedotov** [expo/expo#8291]
Hey volks, I'm not sure if that is a bug but for me something is definitely not working properly.

I updated Expo to version 37 and installed `expo-firebase-analytics` / `expo-analytics-core` (via `expo add`).
When running the app getting this log:
`No native ExpoFirebaseCore module found, are you sure the expo-firebase-core module is linked properly?`
 and hence `expo-firebase-analytics` doesn't work as well.

When trying to use `Analytics.logEvent` this is thrown in the rejected promise `undefined is not an object (evaluating 'ExpoFirebaseAnalytics[funcName]')`.

here are some deps of the project we have:
```
"expo": "^37.0.0",
"expo-firebase-analytics": "~2.1.2",
"expo-firebase-core": "~1.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
```

Anybody knows where to dig in order to solve this issue?

I tried to add `firebase` deps to the project, but so far it didn't help.
Expo CLI version - `3.20.3`

Any help would be much appreciated 🙏

**Comment by brentvatne** [comment]
hello! i think this is an issue with your app. did you upgrade with `expo upgrade`?

i'd suggest creating a new project and trying it there, then you can compare that your existing project to see where you made a mistake. read more about how to create minimal examples in https://stackoverflow.com/help/mcve

if you can reproduce it in a new app then please re-create this issue with a link to the minimal example on github :)

here is an example repo i just made to test this: https://github.com/brentvatne/issue-8291

note that you don't actually need to install expo-firebase-core, it's bundled in expo-firebase analytics

**Comment by dekameron22** [comment]
+1 same happens with my project

**Comment by oleks-fedotov** [comment]
@brentvatne thanks for your help, trying it out on the clean project is indeed a good idea.

Yes, the update was done with `expo upgrade`, however we faced the expo app crash after the upgrade (expo app was also updated) and so far I know it's not really possible to retrieve any logs from this crash. Do you know if that's possible somehow to know the reason for the crash? I can include the whole package.json deps here if needed

Another interesting part that reverting back `"sdkVertion": "36.0.0"` to `app.json` fixed the crash of expo application, but apparently seems like it's an incorrect was of fixing this problem 😄

I'll try to create a brand new project using expo 36, then go through the update process and integrate expo-firebase-analytics to it, will let you know how it worked out.

Cheers!
