### ISSUE TITLE
Expo SDK 37 Bare App - When publishing via expo on Bare app icons are not rendering 

### ISSUE THREAD

**Issue by chasecf** [expo/expo#8293]
### Environment

  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ^0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.3

### Steps to Reproduce

Eject from Expo using `expo eject`.  When you run `expo publish` and launch the application again, the icons are all crossed out.

To my knowledge, Expo SDK 37 allows for OTA updates.

### Expected Behavior

Icons to look normal.

### Actual Behavior

Icons are crossed out.  Seems similar to these posts/bugs but not sure if they are ejected:
#7792 
[SDK37 Expo vector icon can not display after publish](https://forums.expo.io/t/sdk37-expo-vector-icon-can-not-display-after-publish/36519)

### Reproducible Demo

Eject from Expo SDK 37 and then try to use publish.

**Comment by brentvatne** [comment]
here is a topic from forums: https://forums.expo.io/t/expo-icons-are-showing-up-as-only-in-standalone-ios-and-published-ios-sdk37/36964/4?u=notbrent

if you want to publish for use in expo client, then run `expo publish --target managed` and you likely want to use a different release channel than you use for your bare app. i'm working on improving documentation around this, sorry for the hassle

**Comment by chasecf** [comment]
@brentvatne Could you possibly help clarify?  We ejected so we need the ios and android folders, however, in that forum post it seems like the recommendation is to delete those folders?  Also, when you say "publish for use in expo client", does that mean you can't get OTA updates on ejected apps?  Are you saying in the ejected state I can "publish" by just running `expo publish --target managed` even tho I am an ejected expo app?

**Comment by brentvatne** [comment]
from your original post:

> Eject from Expo using expo eject. When you run expo publish and launch the application again, the icons are all crossed out.

i assumed this meant when you ran in expo client, can you clarify?

> Are you saying in the ejected state I can "publish" by just running expo publish --target managed even tho I am an ejected expo app?

yep, [you can publish for use in expo client](https://docs.expo.io/bare/using-expo-client/) but you have to explicitly specify that target. otherwise, it will publish for bare. expo-updates continues to work in ejected apps - https://docs.expo.io/versions/latest/sdk/updates/

**Comment by chasecf** [comment]
Okay maybe the misunderstanding is on my side around the definition of "expo client".  Is expo client the actual expo app that you are loading your application on?

What I am trying to achieve, for clarity, is:
- Eject application
- Have the standard `.xcworkspace` project in the `ios` folder (which I can edit/upload to iTunesConnect)
- Release above application and then use `expo publish --target managed`? to deploy a new OTA update to the released binary without having to do an AppStore deploy.

I am not sure where expo client fits into this, but that is most likely due to me not understanding exactly what the expo client is.

**Comment by brentvatne** [comment]
Expo client is the application you download from the App Store or Play Store or run in your simulator in managed workflow - the app on the top of this page: https://expo.io/tools

Let's chat on Slack as it may be easier, I pinged you there

**Comment by brentvatne** [comment]
I created a new project from the bare typescript template, used an icon from `@expo/vector-icons`, published it with `expo publish` and then did a release build (it's optional to publish first, it just updates the metadata in Expo.plist to know where to look for over-the-air-updates)

It loaded as expected. I then went and added a new icon, and ran `expo publish` again. I closed the app, reopened it, waited a sec for it to download (by default it downloads updates in background), then restarted the app. The icon showed up as expected:

<img width="559" alt="Screen Shot 2020-05-13 at 2 23 09 PM" src="https://user-images.githubusercontent.com/90494/81867279-460ff180-9525-11ea-84d9-574ef399b07e.png">

If you can provide a minimal reproducible example of explain what I am doing differently here than you I'd be happy to help more! Feel free to follow up in our Slack conversation or here.

**Comment by macfanatic** [comment]
I had issues with the following just now:

- a new expo 37 app, about a week old, using icons
- `expo build:ios` and `expo upload:ios`, beta approved, installed via testflight on device
- icons worked fine on that build and on the simulator

Then I noticed I wanted to publish a few changes to testers:
- committed changes
- `expo publish`
- restarted testflight build on device, see my changes appear
- all my icons are broken

I was able to fix the issue by running:

- `expo publish --target managed`

I do have the `ios` and `android` folders in my root project directory, but they've been there after running `expo init` with the typescript template.  I have not used them, but assume they could be deleted.
