### ISSUE TITLE
ios Project fails with `The hashAssetFiles Metro plugin is not configured`

### ISSUE THREAD

**Issue by joshglenn** [expo/expo#8294]
## 🐛 Bug Report

On a fresh, bare typescript expo project, I get the error: `The hashAssetFiles Metro plugin is not configured. You need to add a metro.config.js to your project that configures Metro to use this plugin`

### Environment

  Expo CLI 3.20.0 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.19.0 - /usr/local/bin/node
      Yarn: 1.22.0 - ~/.yarn/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.10 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.0

### Steps to Reproduce

1. create the project `expo init` and choose unmanaged bare typescript template
2. run pod install from the ios folder 
3. run `yarn ios`

### Expected Behavior

yarn ios should build without incident

### Actual Behavior

Build fails with this message: `[redacted]`

### Reproducible Demo

~https://github.com/joshglenn/expo-issue-may-13~ this does not reproduce the reported issue

**Comment by brentvatne** [comment]
hi! this does not fail for me. is it possible that you have a react-native packager instance running from a separate project?

**Comment by joshglenn** [comment]
Interesting. The only packager that was running here was the one started when I ran build in Xcode. I have created new projects with expo init, as recently as yesterday. Out of curiosity, which version of Xcode did you try this with?

**Comment by joshglenn** [comment]
@brentvatne Wow. I just spun up a virtual mac in the cloud and built this on a system with Xcode 10.1 (it's failing locally on xcode 11.3.1)

With xcode 10.1 on that remote machine it ran it without any problem whatsoever. Very odd, indeed. 

I want to build it locally. Trouble is, I don't know where the trouble is :-)

**Comment by joshglenn** [comment]
So, I walked away from this for an hour or so, and came back to it. I ran `yarn cache clean`, then `yarn`. Afterward, I ran `yarn ios`. This time it worked. No idea what happened. Any ideas?

**Comment by oximer** [comment]
I notice that after eject my project, the same error occurs after starting using "expo-updates": "~0.2.0".
It was working with "expo-updates": "~0.1.0",

**Comment by oximer** [comment]
@joshglenn it seems to that the issue continues

**Comment by mattaronoff** [comment]
I'm seeing this same blocking issue with expo-updates 0.2.1 on a newly-ejected project (and if I downgrade, I see #8271 instead).

**Comment by epixapp** [comment]
Same issue with expo-updates 0.2.0.

**Comment by brentvatne** [comment]
hello! if you are having this issue then please provide a mcve! https://stackoverflow.com/help/mcve

we **cannot reproduce this on our end** and **we need you to provide a project that does reproduce it for us to understand what is happening for the small group of people who are encountering this**.

alternatively, if you can give us very detailed steps that reproduce this reliably, that also works. but please test those steps exactly as you describe before posting, because it takes us time to walk through them and you'd be surprised how often such steps do not actually reproduce the reported issue!

**Comment by melvinmt** [comment]
same here, tried it with a fresh install as well

repro steps:
```
$ expo init <project-name>
$ expo eject
$ yarn ios
$ <metro error>
```

**Comment by mdcuk34** [comment]
We faced this issue when upgrading from expo-updates `1.x.x` to `2.0.0`.  The problem was I was running `react-native start` from my terminal inside the project instead of running `yarn start` (` "start": "react-native start"`) before bundling the code through Xcode.

**Comment by shamoons** [comment]
Same issue

**Comment by matt454** [comment]
Same here!

**Comment by byCedric** [comment]
Please don't comment "same here", it's not useful for anyone to determine the exact issue here. Adding a 👍 to the issue is also fine if you just want to express that you are experiencing this issue too. But, to resolve this we need to be able to reproduce this. To quote @brentvatne:

> hello! if you are having this issue then please provide a mcve! stackoverflow.com/help/mcve

> we cannot reproduce this on our end and we need you to provide a project that does reproduce it for us to understand what is happening for the small group of people who are encountering this.

**Comment by chrmod** [comment]
@byCedric @brentvatne I can confirm that a fresh install as illustrated in https://github.com/expo/expo/issues/8294#issuecomment-629037499 is affected by this problem. 
I run into it while ejecting a fairly new expo app. Updating to latest expo, expo-cli and expo-updates did not fix the issue.

It looks like it is related to https://github.com/expo/expo/pull/8324. That PR rely on `@react-native-community/cli` which is not listed as a dependency on freshly ejected project. 

On clean project `npm run ios` results with:
```
Error: Cannot find module '@react-native-community/cli/build/commands/bundle/filterPlatformAssetScales'
Require stack:
- /Users/chrmod/Projects/game/node_modules/expo-updates/scripts/createManifest.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/chrmod/Projects/game/node_modules/expo-updates/scripts/createManifest.js:1:35)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/chrmod/Projects/game/node_modules/expo-updates/scripts/createManifest.js'
  ]
}
```

Installing `@react-native-community/cli` complains about:
```
The hashAssetFiles Metro plugin is not configured. You need to add a metro.config.js to your project that configures Metro to use this plugin
```

All problems go away after running `pod install`

**Comment by msauther** [comment]
I was able to reproduce it with the exact steps provided by @melvinmt.

Unfortunately the steps provided by @chrmod didn't fix the issue for me.

**Comment by esamelson** [comment]
Hey all - this has been fixed with expo-updates@0.2.3. If you are experiencing this issue still, please try upgrading to the latest version!

**Comment by msauther** [comment]
I'm still experiencing the same issue after upgrading
Steps to reproduce:
$ expo init mve2
? Choose a template: expo-template-tabs
$npm view expo-updates

expo-updates@0.2.3 | MIT | deps: 2 | versions: 13

$ expo eject
$pod install
...
 expo-updates@0.2.3 from ../node_modules/expo-updates/ios
...

$yarn its
... 
Error: The hashAssetFiles Metro plugin is not configured. You need to add a metro.config.js to your project that configures Metro to use this plugin. See https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#metroconfigjs for an example.
...

Please let me know how i can better assist as this is a blocker for me atm.

**Comment by chrmod** [comment]
@msauther does `expo eject` generate `metro.config.js` for you? 
As it is not clear from your comments, have you run `pod install` in the `ios` directory or in application root directory (it will only work in ios directory)?

**Comment by msauther** [comment]
pod install is run from the ios directory.

$ find . -name metro.config.js -print
./node_modules/react-native/template/metro.config.js
./node_modules/metro/src/integration_tests/metro.config.js

Find command ran from the project root.

Anything else I can provide?

**Comment by shamoons** [comment]
> Hey all - this has been fixed with expo-updates@0.2.3. If you are experiencing this issue still, please try upgrading to the latest version!

Do we need to simply `yarn add expo-updates`? Or do we have to include it somewhere as well?

**Comment by brentvatne** [comment]
yeah you can just install the latest version `yarn add expo-updates@latest`

**Comment by shamoons** [comment]
Do I need to `import` it anywhere?

**Comment by esamelson** [comment]
Hi all -- to resolve this issue, please follow the directions that were given to you in the error message and add a metro.config.js [that looks like this](https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#metroconfigjs) to your project root.

As of now, all projects created with `expo init` and `expo eject` should include this file prebundled. If you run these commands and the resulting project does not include this file, make sure you're on the latest expo-cli (`npm install -g expo-cli`). If this is still a problem after upgrading, please provide a clear list of steps we can take to reliably reproduce the issue. Thank you!

**Comment by cyrildiagne** [comment]
Hi - I've added a `metro.config.json` at the root of my project, upgraded `expo-updates` to 0.2.3 and ran `pod install` but still facing the `The hashAssetFiles Metro plugin is not configured` error when running `yarn ios`.

Is there anything else I should check?

**Comment by msauther** [comment]
@esamelson I've followed the instructions provide, I've upgraded my expo-cli.  The metro.config.js is created in my project root. however still seeing the same error.

Steps performed:
$expo init mv3
$yarn add expo-updates@latest
$expo eject
$cd iOS
$pod install
$cd ..
$yarn ios

Error seen.

$ expo-cli --version
3.20.9

$ cat metro.config.js
module.exports = {
  transformer: {
    assetPlugins: ['expo-asset/tools/hashAssetFiles'],
  },
};

**Comment by shamoons** [comment]
> Hi - I've added a `metro.config.json` at the root of my project, upgraded `expo-updates` to 0.2.3 and ran `pod install` but still facing the `The hashAssetFiles Metro plugin is not configured` error when running `yarn ios`.
> 
> Is there anything else I should check?
> 
> **Update:** I've restarted metro and now it works. Thanks!

How did you restart `metro`?

**Comment by msauther** [comment]
I also had to kill the metro bundler.

Once restarted I can build now.  Thank you all for your support.

@shmoons to kill the metro bundler, find the process that is created when you start your process, whether it was from yarn or npm start.  Once that process is killed and you kick off the process again a new instance of metro bundler will be created.

**Comment by vasujogani** [comment]
also getting this after `expo eject`

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'libwebp' from project 'Pods')

**Comment by samstorino** [comment]
I had this issue after ejecting expo from the managed to bare workflow. Prior to this I was debugging on the iOS simulator. Rebooting my machine ended up resolving the issue, likely because all instances of the metro bundler were terminated.

**Comment by brentvatne** [comment]
possible solutions:

- update to the latest version of expo-cli, undo your eject and eject again
- kill all metro bundler instances (or reboot your machine if you're unsure how)

if these don't resolve your issue, please open a new issue and fill in the issue template :)
