### ISSUE TITLE
[Camera] takePictureAsync() delay - Android

### ISSUE THREAD

**Issue by macleysousa** [expo/expo#8296]
Hello.

I'm using the module from Expo in my React Native App

In the **takePictureAsync()** method I am noticing a delay of 3 to 4 seconds.

```js
 var options = { quality: 0 };
 this.camera.takePictureAsync(options).then(data => this.setState({ photo: data }));
```

Does anyone know how to solve this problem?

**Comment by byCedric** [comment]
Hi @macleysousa! Under the hood the image is being processed on Android. I think this is mostly the cause of your delay. You can disable that by adding the `skipProcessing: true` option to `takePictureAsync`. Here is an [example with this](https://snack.expo.io/@bycedric/camera-skipprocessing). Some more context on why we are doing this by default is [in the docs](https://docs.expo.io/versions/latest/sdk/camera/#takepictureasync):

> **skipProcessing (_boolean_)** - Android only. If set to true, camera skips orientation adjustment and returns an image straight from the device's camera. If enabled, quality option is discarded (processing pipeline is skipped as a whole). Although enabling this option reduces image delivery time significantly, it may cause the image to appear in a wrong orientation in the Image component (at the time of writing, it does not respect EXIF orientation of the images). 

Hope this helps! If not, let me know. 😄
