### ISSUE TITLE
html tags in Platform.OS === 'web' ?

### ISSUE THREAD

**Issue by javidoweb** [expo/expo#8298]
Hello. Hope you are great
i wish it was posible that we coild use Html tags on Platform.OS === web specifically!!?🤔🤔
`  Platform.OS === 'web'
    ? <select>
        <Option>Option 1</Option>
        <Option>Option 2</Option>
        <Option>Option 3</Option>
      </select>
    : <View style={{flex: 1}}>
        <text>There is no Select/Option on mobile!!</text>
    </View>`

**Comment by brentvatne** [comment]
hi!

if you are going to use this, create a separate file for the functionality you need and use the `.web.js` extension

so, create something like `MySelect.web.js` and `MySelect.js`

please keep questions like this to https://forums.expo.io in the future. the issues are for bug reports.
