### ISSUE TITLE
Camera full screen feature request

### ISSUE THREAD

**Issue by joshg111** [expo/expo#830]
Can you add a full screen option to the camera component? Currently in Android I'm getting the nav buttons showing up on the bottom eg. back button, home button, and setting button. I would rather not break out from the way expo handles all the native code, but I do know there are some react native libraries which have enabled this feature by writing native code.

**Comment by brentvatne** [comment]
Hello! Feature requests belong here: https://expo.canny.io/feature-requests

If you would like to add a full screen camera view, you should just use a modal component and put the camera inside of it.
