### ISSUE TITLE
AuthSession not working for Authorization Code Flow

### ISSUE THREAD

**Issue by zamgill** [expo/expo#8300]
### Environment

Expo CLI 3.20.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.1 - C:\Program Files (x86)\Nodist\bin\node.EXE
      Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files (x86)\Nodist\bin\npm.EXE
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7

Target: iOS and Android

### Steps to Reproduce

Using the following code to start the authentication prompt:
```
const request = await AuthSession.loadAsync(
    {
      client_id: "xxxx-xxxxxxxx-xxxx-xxxxxx",
      redirectUri: AuthSession.makeRedirectUri({
        native: "exp://localhost:19000",
      }),
      scopes: ["openid", "profile", "email", "offline_access"],
      grant_type: "authorization_code",
    },
    discovery
  );

const result = await request.promptAsync();
```

### Expected Behavior

Expected it to return the authorization code and then use that code to acquire and return access_token and id_token.

### Actual Behavior

Only returns authorization code.

### Reproducible Demo

```
const request = await AuthSession.loadAsync(
    {
      client_id: "xxxx-xxxxxxxx-xxxx-xxxxxx",
      redirectUri: AuthSession.makeRedirectUri({
        native: "exp://localhost:19000",
      }),
      scopes: ["openid", "profile", "email", "offline_access"],
      grant_type: "authorization_code",
    },
    discovery
  );

const result = await request.promptAsync();
```

**Comment by byCedric** [comment]
Hi @zamgill, thanks for the issue! What `discovery` are you using to authenticate? It could be related to some settings in there. Without that I won't be able to reproduce the issue.

**Comment by zamgill** [comment]
Hi @byCedric following is my discovery statement:

```
const discovery = await AuthSession.fetchDiscoveryAsync(
      "https://login.microsoftonline.com/{tenant_id}/v2.0"
    );
```

I'm replacing `{tenant_id}` with my Azure Tenant.

**Comment by TimoGruber** [comment]
#8473

**Comment by sebastienlabine** [comment]
@EvanBacon  +1. It should have the same behavior as `expo-app-auth` for code exchange, because **that's is considered the best practice** for requesting Access Tokens. The **implicit flow is not recommanded** as per [OAuth2 documentation](https://auth0.com/docs/flows/concepts/implicit), and it makes no sence for expo to recommand using the Implicit Flow.

> The OAuth 2.0 BCP states that you should not use the Implicit Flow to request Access Tokens from the Authorization Server. For this reason, we recommend that you use the Authorization Code Flow with PKCE

**Comment by sebastienlabine** [comment]
Any updates?

**Comment by EvanBacon** [comment]
This is the intended behavior, some functionality is not yet implemented in auth-session.

Token methods have been in the works for a while but they still require a lot more testing https://github.com/expo/expo/pull/8051 -- feel free to copy the features into your project if needed. 
Under the hood, code exchange is performing a fetch request so I wouldn't consider this to be explicitly blocking anyone.

Generally authorization code flow requires a secret which you shouldn't store in the client code but rather a server. If you wish to perform an authorization request without an external server you can check out the implicit auth flow which some providers support. I've documented how to do implicit auth for a bunch of providers in the docs: https://docs.expo.io/guides/authentication/

**Comment by darryl1975** [comment]
Hi EvanBacon,

I m having the same issue.

I tried the following code to login to Azure AD and am successfuly to login to Azure.

let client_Id = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx';
  let client_Secret = 'yyyyyyyyyyyy_yyyyyyy-yyy-yyyyyyyyy';
  let scopesList: string[] = ['openid', 'profile', 'email', 'offline_access'];

  let authorization_Endpoint = 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/oauth2/authorize';
  let token_Endpoint = 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/oauth2/token';

  // AuthRequestConfig
  let reqConfig: AuthSession.AuthRequestConfig = {
    //responseType: ResponseType.Token,
    clientId: client_Id,
    clientSecret: client_Secret,
    redirectUri: redirect_uri,
    scopes: scopesList,
    usePKCE: true
  }

  let discoveryConfig: AuthSession.DiscoveryDocument = {
    authorizationEndpoint: authorization_Endpoint,
    tokenEndpoint: token_Endpoint
  }

  let authRequestConfig: AuthSession.AuthRequestConfig = {
    clientId: client_Id,
    clientSecret: client_Secret,
    redirectUri: redirect_uri,
    scopes: scopesList,
    prompt: AuthSession.Prompt.Login
  };

  // Create and load an auth request
  const [request, result, promptAsync] = AuthSession.useAuthRequest(
    reqConfig,
    discoveryConfig
  );


However,  the response doesn't provide me the email or id_token or access_token.

I tried to use the return code provided in response.params.code to retrieve a token. However, I am unsuccessful.

The following is the code I have to retrieve a token (on button clicked):

const getToken = async () => {
    try {
      var rslt: any = result;
      console.log('App getToken (rslt): ', rslt.params.code);

      const accessToken = new AuthSession.AccessTokenRequest({
        clientId: client_Id,
        clientSecret: client_Secret,
        code: rslt.params.code,
        redirectUri: redirect_uri,
        scopes: scopesList,
      });

      console.log(accessToken);

      const responseToken = await AuthSession.exchangeCodeAsync(accessToken, { tokenEndpoint: discovery.tokenEndpoint });
      console.log(JSON.stringify(responseToken, null, 4))
    } catch (err) {
      console.log(err);
      console.log(JSON.stringify(err, null, 4))
    };
  };


The error I encountered:

App retrieveToken (error):  [Error: The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
More info: AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE.
Trace ID: 256b595a-2503-4d44-83e4-1ac91add3400
Correlation ID: e74b0bd0-52ef-4f65-923b-2c0afee976e1
Timestamp: 2020-10-29 03:38:28Z]
Unrecognized event: {"type":"client_log","level":"log","data":["App retrieveToken (error): ","[Error: The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\nMore info: AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE.\r\nTrace ID: 256b595a-2503-4d44-83e4-1ac91add3400\r\nCorrelation ID: e74b0bd0-52ef-4f65-923b-2c0afee976e1\r\nTimestamp: 2020-10-29 03:38:28Z]"]}


Please advice what I can do. 

Thank you.

**Comment by darryl1975** [comment]
Hi,

I have also encountered the same error.

May I know if there is a solution to this and how it was resolved?

Appreciate. Thank you.

**Comment by AnthonyMyatt** [comment]
For me the trick was to add the following to the config params for exchangeCodeAsync().

`extraParams: {
        code_verifier: request.codeVerifier
},`

**Comment by howardwu1** [comment]
Does anyone know how to return both access token and id token in the same request? Or could maybe give a good workaround here?  Currently it seems like the default is to give an undefined id token, and if you specify id_token in the requestType, it works but then you don't get your access token anymore.

**Comment by samih-sghier** [comment]
My issue was fixed following @AnthonyMyatt suggestion 👍

**Comment by yeguacelestial** [comment]
Thank you @AnthonyMyatt , been struggling with this like 2 days straight.

If someone is using TypeScript, you can handle the empty string as follows:
```typescript
extraParams: {
    code_verifier: request?.codeVerifier ? request.codeVerifier : ''
}
```

**Comment by davidmetcal** [comment]
Hi,

Has there been any udpate on this? I am trying to move from an implicit flow (which works but I am using a server to access user data) to an Auth Code flow - however the request seems to fail when I change the responseType to code.

Here is my full request:

```
GoogleAuthRequest {
  "clientId" :CLIENT_ID,
  "clientSecret": undefined,
  "codeChallenge": "lmxvF6Wpj3op4SK1ityGLvHNC-impx3PnMm1RH4u0yQ",
  "codeChallengeMethod": "S256",
  "codeVerifier": "yB0qe12SwFhduH4we28vxv8teb5ow77L4IU9RlpDyOzAMXARLAPXAkbWZFugZFynvQGGwRsw6m75JScZxPvxcuISchpvIP2KTadDMSd6qMZ267hzFfCCDRRGRd7lc6s0",
  "extraParams": Object {},
  "prompt": "consent",
  "redirectUri": "https://auth.expo.io/@MY_LOGIN/MY-PROJECT",
  "responseType": "code",
  "scopes": Array [
    "openid",
    "https://www.googleapis.com/auth/userinfo.profile",
    "https://www.googleapis.com/auth/userinfo.email",
  ],
  "state": "q6KTfxiZmU",
  "url": FULL_URL_POPULATED HERE,
  "usePKCE": true,
}
```

And the error response when trying to use the Auth Code Flow:

```
[Unhandled promise rejection: Error: The request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, includes multiple credentials, utilizes more than one mechanism for authenticating the client, or is otherwise malformed.]
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:110650:321 in _createSuperInternal
at node_modules/expo-modules-core/build/errors/CodedError.js:10:8 in constructor
at node_modules/expo-auth-session/build/Errors.js:1:0 in <global>
at node_modules/expo-auth-session/build/Errors.js:65:9 in ResponseError#constructor
at node_modules/expo-auth-session/build/Errors.js:1:0 in <global>
at node_modules/expo-auth-session/build/Errors.js:89:16 in TokenError#constructor
at node_modules/expo-auth-session/build/TokenRequest.js:159:4 in performAsync
```

My initial thinking is if there is something stopping the Auth Flow from happening? I can see in the scopes automatically have the openid listed which I'm not sure I require when requesting the Auth code, I haven't had much luck removing this parameter to test it.

**Comment by Mphatheleni** [comment]
> For me the trick was to add the following to the config params for exchangeCodeAsync().
> 
> `extraParams: { code_verifier: request.codeVerifier },`

For anyone struggling with this in 2024, I used this answer to solve mine
