### ISSUE TITLE
Unable to install Expo client on iOS

### ISSUE THREAD

**Issue by James2516** [expo/expo#831]
I installed XCode 9.1 beta yesterday and subsequently uninstalled it (and remains with Xcode 9.0), but now i can no longer open a react native app on the iPhone simulator.

It's able to start the simulator, but the terminal header just rapidly toggle between node and simctl and Expo client doesn't get installed.

I have try reinstalling XCode, didn't fix the problem.

Gif: https://thumbs.gfycat.com/ThirstyYoungAmazontreeboa-size_restricted.gif

**Comment by terribleben** [comment]
What happens when you run `xcode-select --print-path` ?

We have some manual instructions for installing the Expo Client simulator build [here](https://gist.github.com/jesseruder/a627c0dc0427f074d1aecba997c349ef), do those work for you?

**Comment by terribleben** [comment]
Going to consolidate this with https://github.com/expo/expo/issues/894 - feel free to add any other info there.

**Comment by DWboutin** [comment]
I installed Expo Client manually for IOS simulator. I clearly see the Expo app, but my app won't launch at all and if I click on Run on IOS simulator, it keeps trying to install it. I just updated xcode to the latest version. What can I do to solve this? 

Thank you for your help!

`node -v` v10.9.0

<img width="251" alt="Screen Shot 2019-06-01 at 1 33 26 PM" src="https://user-images.githubusercontent.com/1322006/58752021-d4ef3f80-8475-11e9-8d4c-591101eada7f.png">

**Comment by zachbroad** [comment]
Does this happen to you on a fresh project? Can you post your package.json?

**Comment by DWboutin** [comment]
Yes, a very new project

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  },
  "private": true
}
```

**Comment by 2hands10fingers** [comment]
+1. 

@terribleben My "Installing Expo client on iOS simulator...." hangs. I'm using the latest version of Expo (`"expo-cli": "^2.18.7"`) and Xcode.
