### ISSUE TITLE
expo start:web  show  issues.

### ISSUE THREAD

**Issue by yrjwcharm** [expo/expo#8317]
![image](https://user-images.githubusercontent.com/34397383/82019580-13e3c880-96ba-11ea-98d5-cf1473dfc71b.png)

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/82019913-a2f0e080-96ba-11ea-848d-cc253d6cc71c.png)

**Comment by LinusU** [comment]
A better issue title would be: "Static class props not supported with Expo Web"

**Comment by byCedric** [comment]
Hi @yrjwcharm, could you provide a small repro for this? It looks like the library you want to use (`teaset`) is not pre-transpiled. This makes sense for React Native libraries, they expect the Metro bundler doing the compiling and transpiling for you. 

I think it might be very similar to #8060. You can try this fix/workaround to include `teaset` to the babel transpile list. Instead of `@ui-kitten`, try `teaset` 😄 

Hope it helps!

**Comment by yrjwcharm** [comment]
@byCedric  How  to solve it! I don't understand your words . could you say  minutely？How to do it specifically

**Comment by brentvatne** [comment]
@yrjwcharm - @byCedric is asking if you can provide a repository that reproduces the problem you are experiencing.

he is also suggesting that you try `teaset` instead of `uikitten` and asked you to look at his response in https://github.com/expo/expo/issues/8060

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/82276872-10518980-99b9-11ea-9380-07135c81ebbd.png)
this file doesn't find.

**Comment by yrjwcharm** [comment]
@byCedric

**Comment by yrjwcharm** [comment]
expo start:web stills show issues.
![image](https://user-images.githubusercontent.com/34397383/82279604-8a850c80-99bf-11ea-90ec-1d40fabc11aa.png)

**Comment by yrjwcharm** [comment]
@byCedric  Big Boss help!!!

**Comment by yrjwcharm** [comment]
> A better issue title would be: "Static class props not supported with Expo Web"

How can we support it

**Comment by byCedric** [comment]
Try [creating a custom webpack config](https://docs.expo.io/guides/customizing-webpack/), something like the example below. This lets Babel transpile your `teaset` module 😄 

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = function(env, argv) {
  // add babel config if it doesn't exists
  if (!env.babel) env.babel = {};
  // add teaset and merge any existing dangerouslyAddModulePathsToTranspile
  env.babel.dangerouslyAddModulePathsToTranspile = [
    ...env.babel.dangerouslyAddModulePathsToTranspile,
    'teaset',
  ];

  return createExpoWebpackConfigAsync(env, argv);
};
```

**Comment by yrjwcharm** [comment]
@byCedric 
![image](https://user-images.githubusercontent.com/34397383/82395580-650b0800-9a7e-11ea-9da4-b8347e4b6a7f.png)

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/82396676-1612a200-9a81-11ea-8841-e2da7b6f905e.png)
I commented out the above line of code and didn't report an error. But other errors were reported
![image](https://user-images.githubusercontent.com/34397383/82396770-58d47a00-9a81-11ea-922f-7fba0527a60c.png)

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/82396770-58d47a00-9a81-11ea-922f-7fba0527a60c.png)

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/82397350-da78d780-9a82-11ea-9968-d9fcb0db2785.png)

**Comment by yrjwcharm** [comment]
@byCedric @LinusU  help ! help! help!

**Comment by EvanBacon** [comment]
Hello, sorry you've run into trouble using Expo web. Your most recent issue seems to be related to `react-native-legacy-components` not supporting web. Web support is new and mostly an Expo thing, packages prefixed with `react-native-*` are not guaranteed to support web. 

The package `react-native-legacy-components` has an internal structure like:

```
...
NavigatorBreadcrumbNavigationBarStyles.android.js  
NavigatorBreadcrumbNavigationBarStyles.ios.js      
```
The bundler (Webpack on web) cannot resolve a `.android`, `.ios`, or `.native` file. I would suggest not using `react-native-legacy-components` (it's ~20 versions behind `react-native`) and perhaps opening an issue to `teaset` asking them to upgrade their library. In the meantime if you need navigation + UI, I recommend using React Navigation which is an Expo library, and `react-native-paper` which is maintained by a core member of Expo.
