### ISSUE TITLE
[expo-updates] How to set release channel programmatically

### ISSUE THREAD

**Issue by arlyon** [expo/expo#8318]
There is currently no documentation on how to build for a given release channel in the bare workflow _programmatically_. As of now, I need to manually change values deep in some config file which is not very ergonomic. Is there a plan to allow setting this from env vars etc?

edit: scripts (either a gradle file or through some xcode config) would be a better alternative. Updating plists is painful.

**Comment by arlyon** [comment]
To be clear, I mean through scripts (either a gradle file or through some xcode config). Updating plists is painful.

**Comment by esamelson** [comment]
Hey there @arlyon - this is a great idea and we'd be happy to accept a high quality PR adding this functionality, if you'd like to take a crack! 🙂

**Comment by barelyhuman** [comment]
I'm not sure if this is worthy of a PR but here's a bash script for people who'd like a simple solution
```bash
#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
PROJECT_DIR="${SCRIPT_DIR}/.."

EXPO_PLIST="ios/multiURLUpdates/Supporting/Expo.plist"
RESULT=$(/usr/libexec/PlistBuddy -c "SET EXUpdatesReleaseChannel $1" ${PROJECT_DIR}/${EXPO_PLIST} 2>&1)
if [ $? -eq 0 ]; then
  echo "Updated EXUpdatesReleaseChannel in ${EXPO_PLIST} to $1"
else
  echo "Error occurred: ${RESULT}"
fi

ANDROID_MANIFEST="android/app/src/main/AndroidManifest.xml"
RESULT=$(sed -i '' 's/expo.modules.updates.EXPO_RELEASE_CHANNEL\" android:value=".*"/expo.modules.updates.EXPO_RELEASE_CHANNEL\" android:value="'$1'"/' ${PROJECT_DIR}/${ANDROID_MANIFEST} 2>&1)
if [ $? -eq 0 ]; then
  echo "Updated EXPO_RELEASE_CHANNEL in $ANDROID_MANIFEST to $1"
else
  echo "Error occurred: ${RESULT}"
fi
```

I currently use it with the above script residing in a folder named `scripts` and executing it as such 
```
```

**Comment by ankitgehlot123** [comment]
did anybody found a better way to do it?

**Comment by sathishkrishnan20** [comment]
For anyone looking without the react-native-config. Use the below steps.

**Add User Defined Environment Variable:**

1. Navigate to Build Settings.
2. Add a new User Defined Environment Variable named EXPO_CHANNEL_NAME for your specific scheme/environment.


**Add a New Run Script Phase:**

1. Under Build Phases, add a new Run Script Phase.
2. Ensure the script is placed before the Copy Bundle Resources phase.

**Add the Following Script:**
```# Type a script or drag a script file from your workspace to insert its path.
if [ "$EXPO_CHANNEL_NAME" ]; then
  CHANNEL_NAME="$EXPO_CHANNEL_NAME"
else
  # Hardcoded fallback value
  CHANNEL_NAME="staging"
  echo "EXPO_CHANNEL_NAME is not set, using default: $CHANNEL_NAME"
fi

/usr/libexec/PlistBuddy -c "Set :EXUpdatesRequestHeaders:expo-channel-name $CHANNEL_NAME" "${PROJECT_DIR}/<app_name>/Supporting/Expo.plist"
```

Note: Replace the <app_name> with your application/project name

This will replace the expo-channel-name value in Expo.plist file

**Comment by gyanbhartip** [comment]
I am using `resValue "string", "expo_update_channel", "{\"expo-channel-name\":\"release\"}"` inside android.buildtypes in android/app/build.gradle and reading it as `<meta-data
      android:name="expo.modules.updates.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY"
      android:value="@string/expo_update_channel" />`

Still looking for a way to do the same for iOS

**Comment by sathishkrishnan20** [comment]
HI @gyanbhartip , Even I tried the same for long hours, but could not get any proper solution other than https://github.com/expo/expo/issues/8318#issuecomment-2600648800. 

The main concern I see here is that the value is being replaced each time, rather than being referenced.

**Comment by octopitus** [comment]
For anyone comes here to find a proper solution, this is the best I can think of:

```ts

const withUpdates: ConfigPlugin = (expoConfig) => {
  return withExpoPlist(expoConfig, async (modConfig) => {
    // Making sure that the header is set to the correct channel
    const headers = { 'expo-channel-name': expoUpdaetChannel[env] }

    modConfig.modResults[
      IOSConfig.Updates.Config.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY
    ] = headers

    return modConfig
  })
}

**Comment by octopitus** [comment]
For anyone comes here to find a proper solution, this is the best I can think of. This works for base workflow, and requires converting `app.json` to `app.config.js`. You also need to prebuild the app (Eg. `NODE_ENV=production expo prebuild`) before building the app.

```ts
import { ConfigPlugin, withExpoPlist } from '@expo/config-plugins'

const env = process.env.NODE_ENV || 'development'

const expoUpdateChannel = {
  // A mapping from env to channel name
  development: 'development',
  staging: 'staging',
  production: 'production'
}

const defaultExpoConfigs = {
  // Your Expo configs goes here
}

const withUpdates: ConfigPlugin = (expoConfig) => {
  return withExpoPlist(expoConfig, async (modConfig) => {
    // Making sure that the header is set to the correct channel
    const headers = { 'expo-channel-name': expoUpdateChannel[env] }

    modConfig.modResults[
      IOSConfig.Updates.Config.UPDATES_CONFIGURATION_REQUEST_HEADERS_KEY
    ] = headers

    return modConfig
  })
}

export default withUpdates(defaultExpoConfigs)
```
