### ISSUE TITLE
[docs] Adding release instructions for Bare Workflow

### ISSUE THREAD

**Issue by hanselsen** [expo/expo#8320]
I'm referring to [this section](https://docs.expo.io/bare/exploring-bare-workflow/#releasing-to-app-store-and-play-store). 
Currently, I just guessed that you should follow [the RN instructions](https://reactnative.dev/docs/signed-apk-android), but that just results in the error that the Metro bundler is not running. Running `react-native start` besides it, makes it work. 

I think it is not a bug, but just missing some pointers which should be available for everybody using the amazing Bare Workflow.

**Comment by brentvatne** [comment]
it's the same as https://reactnative.dev/docs/signed-apk-android - we could link out to there though to make it more clear for now. definitely want to have better release instructions in our docs soon, the plan is to handle this with the expo build service but we're still working on support for bare apps.

can you explain which of those instructions you followed that didn't run metro for you?

**Comment by hanselsen** [comment]
Good to hear it's the same instructions as RN.
Also, I like how hard you guys work to make everything easy and understandable. Keep it up!

Regarding my issue. Using `./gradlew [assemble|bundle|install]Release` is not starting the metro bundler.

My scenario is development on Windows and CI build using GitLab runners on a Mac. (Shell).

Apart from nog starting the metro builder, the GitLab runner also gets stuck on the `:app:createExpoManifest` task. I can imagine that would need the metro bundler. This happens only on Mac though.
