### ISSUE TITLE
Network request failed when trying to upload formData body

### ISSUE THREAD

**Issue by gustavolsilvano** [expo/expo#8323]
### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548

Android

### Steps to Reproduce

Trying to upload a formData to feathersjs server. It returns me a "Network request failed", but on my server it still goes with the request.

The problem is that my expo app goes on with the code, so I don't get the result from my server.
It seems to be some problem with React Native 0.62 using Flipper, and searching online I found that you need to comment out a line from:

/android/app/src/main/java/com/{your_project}/MainApplication.java

But I don't know how to access this file on expo.

Tried making a fetch request without a formData and it worked. It's clearly a problem that happens when trying to upload a file.

**Comment by brentvatne** [comment]
we don't have flipper set up in expo client and expo sdk 37 does not react-native 62. probably that is unrelated, "Network request failed" can happen for many reasons :)

see https://github.com/expo/examples/tree/master/with-formdata-image-upload for a working end-to-end example of uploading an image using formdata. if this example doesn't work for you, then please let me know and i'll reopen the issue. if it does, you may want to investigate what is going on with your server side of things.

**Comment by bconnorwhite** [comment]
I am seeing this as well (Android only), also assumed it was related to the issue @gustavolsilvano mentioned (https://github.com/facebook/react-native/issues/28551). Cannot upload with form data body ("Network request failed" for fetch, "Stream Closed" for XMLHttpRequest)

**Comment by olapiv** [comment]
@brentvatne, thanks for that link! I also received the error `TypeError: Network request failed` and thought it was related to Flipper, etc., but it was in fact the "type" that I had passed to the FormData.

```
let result = await ImagePicker.launchImageLibraryAsync({ .... })
let data = new FormData();
data.append('file', {
        uri: result.uri,
        name: image_name,
        type: result.type, // <-- This works for iOS, but not for Android.
});
```

`result.type` can for instance be equal to "image". However, for Android, the following is needed:

```
 const uriArray = result.uri.split(".");
 const fileExtension = uriArray[uriArray.length - 1];  // e.g.: "jpg"
 const fileTypeExtended = `${result.type}/${fileExtension}`; // e.g.: "image/jpg"

data.append('file', {
        uri: result.uri,
        name: image_name,
        type: type: fileTypeExtended
});
```

This also works for iOS.

**Comment by ewein** [comment]
I'm getting the same issue using Expo SDK 42. Uploading images from ImagePicker works fine on both iOS and Android. However, trying to upload a file like a PDF from Document Picker fails on Android only. There seems to be an issue with FormData uploads from Document Picker for Android only. The network error I receive:

`{
  "message": "Network Error",
  "name": "Error",
  "stack": "createError@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:241425:26\nhandleError@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:241335:27\ndispatchEvent@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:33389:31\nsetReadyState@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:32554:33\n__didCompleteResponse@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:32370:29\nemit@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:4020:42\n__callFunction@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:3204:36\nhttp://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:2936:31\n__guard@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:3158:15\ncallFunctionReturnFlushedQueue@http://192.168.50.79:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:2935:21\ncallFunctionReturnFlushedQueue@[native code]",
  "config": {
    "url": "https://53c2-24-71-244-159.ngrok.io/submit",
    "method": "post",
    "data": {
      "_parts": [
        [
          "amount",
          0.06
        ],
        [
          "serviceDate",
          1631170800
        ],
        [
          "docs[]",
          {
            "size": 680351,
            "name": "testing.pdf",
            "uri": "/data/user/0/host.exp.exponent/cache/ExperienceData/%40myapp%2Fmyapp/DocumentPicker/74cc1ce0-eb40-42ee-9350-839b6c44fd95.pdf",
            "type": "application/pdf"
          }
        ]
      ]
    },
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Authorization": "JSON-WEB-TOKEN-HERE",
      "Content-Type": "multipart/form-data"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    }
  }
}`

I also noticed the uri returned from Document Picker on Android only does not include the leading "file://", not sure if that causes any problems...

Any help would be much appreciated.

**Comment by frankcalise** [comment]
> @ewein , I faced the same issue after updating my expo app to 42 and found this is working
> 
> ` const selectDocuments = async () => { try { const result = await DocumentPicker.getDocumentAsync({ type: "application/pdf", // uploading pdf only copyToCacheDirectory: false, });
> 
> ```
>   if (!result.cancelled) {
>     const uri = FileSystem.documentDirectory + result.name;
>     await FileSystem.copyAsync({
>       from: result.uri,
>       to: uri
>     })
>     onChangeImage(uri); // add your logic
>   }
> } catch (error) {
>   console.log("Error reading an pdf file", error);
> }
> ```
> 
> };`
> 
> Hope it will help to someone

This was my finding as well, only failing on Android. However implementing this snippet worked beautifully. Thank you!

**Comment by techmodule** [comment]
Androdi need 'image/png" or "image/jpg" to upload.
`formData.append("file", {
            uri: manipResult.uri,          // this is the path to your file. see Expo ImagePicker or React Native ImagePicker
            type: Platform === "ios" ? 'png' : "image/png",  // example: image/jpg
            name: filename    // example: upload.jpg
        });`

**Comment by eightyfive** [comment]
In my case I had to increase [`client_max_body_size`](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) in my nginx server block configuration:

```
server {
    client_max_body_size 10M;
```

It's `1M` by default. Not enough for jpegs nowadays.

**Comment by shuo-hiwintech** [comment]
> @brentvatne，谢谢你的链接！我也收到了错误`TypeError: Network request failed`，并认为它与 Flipper 等有关，但实际上它是我传递给 FormData 的“类型”。
> 
> ```
> let result = await ImagePicker.launchImageLibraryAsync({ .... })
> let data = new FormData();
> data.append('file', {
>         uri: result.uri,
>         name: image_name,
>         type: result.type, // <-- This works for iOS, but not for Android.
> });
> ```
> 
> `result.type`例如可以等于“image”。但是，对于 Android，需要以下内容：
> 
> ```
>  const uriArray = result.uri.split(".");
>  const fileExtension = uriArray[uriArray.length - 1];  // e.g.: "jpg"
>  const fileTypeExtended = `${result.type}/${fileExtension}`; // e.g.: "image/jpg"
> 
> data.append('file', {
>         uri: result.uri,
>         name: image_name,
>         type: type: fileTypeExtended
> });
> ```
> 
> 这也适用于 iOS。

Thank you for saving my life.
