### ISSUE TITLE
[docs] Recommended replacement for ViewPager is @react-native-community/viewpager, which doesn't support Expo

### ISSUE THREAD

**Issue by danielvinson** [expo/expo#8325]
As discussed [here](https://github.com/react-native-community/react-native-viewpager/issues/18)

> @DrobyshevAlex you cannot as this library is not supported by Expo. You would have to eject your project.
> 
> The interesting thing is that Expo people recommend using the react-native-viewpager instead of one of their deprecated interface. It is literally the first-line link on the ViewPagerAndroid page.

It appears that the current release (4.0.0) of `@react-native-community/viewpager` has the same issues still, so it should not be recommended.

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/latest/sdk/view-pager/

it's included in sdk-37
