### ISSUE TITLE
The following problems occur when using Expo for Android native packaging.

### ISSUE THREAD

**Issue by yrjwcharm** [expo/expo#8327]
![image](https://user-images.githubusercontent.com/34397383/82112181-25da6f80-977d-11ea-9fd1-4327f9b7b34f.png)

**Comment by yrjwcharm** [comment]
Android APK can run in the simulator. But there was a problem with packaging. It's been a problem for a long time

**Comment by brentvatne** [comment]
run `yarn start` before doing the build, it looks like it's trying to connect to metro bundler but it's not running

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/82166982-d450f280-98ec-11ea-88ae-67f8093f76e1.png)

**Comment by yrjwcharm** [comment]
Can't track the error log at all

**Comment by yrjwcharm** [comment]
The service has been opened, but the packaging still has problems

**Comment by yrjwcharm** [comment]
![image](https://user-images.githubusercontent.com/34397383/82171947-521bfa80-98fb-11ea-8141-13b109c4a190.png)

**Comment by yrjwcharm** [comment]
@brentvatne  How to solve it.

**Comment by yrjwcharm** [comment]
我是用的打包方式 ./gradlew assembleRelease

**Comment by yrjwcharm** [comment]
@brentvatne  
Is this a mistake？

Is this the cause of packaging failure？


     provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:18 to replace other declarations but no other decla
ration present

![image](https://user-images.githubusercontent.com/34397383/82298706-1a8a7c80-99e7-11ea-8efc-9134c38b3144.png)
