### ISSUE TITLE
Expo (fast) refresh spawning notifyd process with high CPU

### ISSUE THREAD

**Issue by Rijk** [expo/expo#8340]
## 🐛 Bug Report

I've noticed this for a while (suddenly my computer fans start spinning out of control), but have tracked it down now to a specific component in my application. When I edit that screen, for some reason it triggers this issue, and it doesn't happen elsewhere.

The following happens. After saving, the "Refreshed" banner never disappears:

![image](https://user-images.githubusercontent.com/159500/82191887-7a076000-98f3-11ea-8065-d7bb106cc54c.png)

And in Activity monitor it looks like this (this is constant, the values stay consistently high indefinitely):

![image](https://user-images.githubusercontent.com/159500/82191942-8d1a3000-98f3-11ea-80af-7dbe7aeb12b3.png)

This doesn't stop until I hard close the Expo app on the iPhone Simulator. Refreshing doesn't help, the `notifyd` will keep running at 75% CPU. Note that this only happens with Fast Refresh enabled, not when it is disabled.

### Environment

```
  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/lib/node_modules/node/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/lib/node_modules/node/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.9 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.3
```

### Steps to Reproduce

Make a change in `/src/components/reflect/Overview.tsx`

### Reproducible Demo

Unfortunately it is a closed source project, so I cannot create a public reproduction case, but am willing to share private access.

**Comment by Rijk** [comment]
I have tracked down the issue to a `<FlatList>` where I put a function on the `data` that inadvertently modified the array that was passed as a prop of the `Overview` component:

`data={fillDays( highlights )}`

This fixed the issue:

`data={fillDays( [ ...highlights ] )}`

I don't know why this spawned the `notifyd` though, so might still be worth investigating.

**Comment by rbq10** [comment]
Hi @rijk , I'm experiencing the same issue after just updating one of my dependencies. 

How did you manage to track down the issue to the <Flatlist>?

**Comment by rijk** [comment]
@rbq10 not sure anymore, it was quite a while ago, but probably was just commenting out components until the problem went away. Poor man's profiling 😅

**Comment by victor-axelsson** [comment]
Is this only affecting the development environment or is CPU usage for a real device also high? Does it happen on a real device?
