### ISSUE TITLE
[expo-apple-authentication] never returns ERR_CANCELED

### ISSUE THREAD

**Issue by Marcados** [expo/expo#8341]
### Environment

Expo CLI 3.20.0 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.10 => 37.0.10 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.20.0

### Steps to Reproduce

This piece of code from the Doc does never return ERR_CANCELED, so that we can not catch a cancel press button.

```
try {
          const credential = await AppleAuthentication.signInAsync({
            requestedScopes: [
              AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
              AppleAuthentication.AppleAuthenticationScope.EMAIL,
            ],
          });
          // signed in
        } catch (e) {
          if (e.code === 'ERR_CANCELED') {
            // handle that the user canceled the sign-in flow
          } else {
            // handle other errors
          }
        }
```

### Expected Behavior

Expected ERR_CANCELED when the user click on CANCEL from the Apple Authentication

### Actual Behavior

It returns only ERR_APPLE_AUTHENTICATION_REQUEST_FAILED

**Comment by IjzerenHein** [comment]
Okay that doesn't seem right. What does the value of `e.message` contain ?

**Comment by Marcados** [comment]
The value of `e.message` contains `The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)`

**Comment by IjzerenHein** [comment]
It seems to be failing rather than detecting that is has been cancelled. Could you provide a short screen-recording demonstrating the problem?

**Comment by Marcados** [comment]
Indeed, it always returns this message and the same ERR_APPLE_AUTHENTICATION_REQUEST_FAILED error code. 
I can not provide a screen-recording because the project I work on is under NDA. But it is easy to reproduce, by copying the code in the documentation and cancelling the Apple SignIn, then logging the error.

**Comment by IjzerenHein** [comment]
Most likely, the configuration has not been fully setup yet. Can you confirm that you can correctly sign-in using Apple auth?

**Comment by Marcados** [comment]
It seems that the issue was only my fault, maybe due to tests only on simulator. On device all is ok. Sorry about the trouble.

**Comment by IjzerenHein** [comment]
No worries 👍
