### ISSUE TITLE
Error with Expo-SQLite in bare project TypeError

### ISSUE THREAD

**Issue by yesIamFaded** [expo/expo#8342]
I have a Problem with the SQLite package in a bare React Native project..

I installed everything you need to use the expo package in a bare project but I am facing this error: 

![Screenshot_1589799570](https://user-images.githubusercontent.com/48751859/82206265-38cd7b00-9908-11ea-99fb-d165f7c26f6d.png)

First I had the Error that SQLite there is no .openDB function but I fixxed it so React Native definitly knows that SQLite exists in the Project.. 

How do I fixx this error? I copied the function from where I call it from another project of mine where it works fine so that cant be wrong.

**Comment by byCedric** [comment]
Hi @yesIamFaded! Could you share your project or [another small example](https://stackoverflow.com/help/minimal-reproducible-example) of where this happens? I can't reproduce this on my end when following the instructions, unfortunately. Your previous issue could very much be related to this one. You could also try to remove `node_modules`, lockfiles and [clearing the cache](https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352).

Hope it helps!

**Comment by yesIamFaded** [comment]
I tried clearing the cache which didnt work for me. I dont know what is going on I guess there is something missing to get it to work because the actuall DB code works because I took it from another App I made. Here you can see how the db.js works and where I call my DB to create or listen maybe it can help: 

`import * as SQLite from "expo-sqlite";
// import {FileSystem} from "react-native-unimodules"; 

const db = SQLite.openDatabase("images.db");

export const init = () => {
  const promise = new Promise((resolve, reject) => {
    db.transaction((tx) => {
      tx.executeSql(
        "CREATE TABLE IF NOT EXISTS images (id INTEGER PRIMARY KEY NOT NULL, imageUri TEXT NOT NULL, todaysDate TEXT NOT NULL);",
        [],
        () => {
            resolve();
        },
        (_, err) => {
            reject(err);
        }
      );
    });
  });
  return promise;
};


export const insertImage = (imageUri, todaysDate) => {
  const promise = new Promise((resolve, reject) => {
    db.transaction((tx) => {
      tx.executeSql(
        "INSERT INTO images (imageUri, todaysDate) VALUES (?,?);",
        [imageUri, todaysDate],
        (_, result) => {
            resolve(result);
        },
        (_, err) => {
            reject(err);
        }
      );
    });
  });
  return promise;
}

export const getImages = () => {
  const promise = new Promise((resolve, reject) => {
    db.transaction((tx) => {
      tx.executeSql(
        "SELECT * FROM images;",
        [],
        (_, result) => {
            resolve(result);
        },
        (_, err) => {
            reject(err);
        }
      );
    });
  });
  return promise;
}

export const deleteImage = (imagePath) => {
  const promise = new Promise((resolve, reject) => {
    db.transaction((tx) => {
      tx.executeSql(
        "DELETE FROM images WHERE imageUri = (?);",
        [imagePath],
        (_, result) => {
            resolve(result);
        },
        (_, err) => {
            reject(err);
        }
      );
    });
  });
  return promise;
}`

Here where I call init inside my App.js so I know that it starts when the App starts: 

`import { init } from "./navigation/db";

init()
.then(() => {
  console.log("Database initialized! - ImagesDB")
})
.catch(err=> console.log("DB ERROR: " + err))
`

**Comment by yesIamFaded** [comment]
@byCedric also I noticed for example if I want to use the ImagePicker it also tells me that it cant use it 

`TypeError: Cannot read property 'launchCameraAsync' of undefined
`
I guess there must be a general thing or something that is not correct with my unimodules... I get the autocomplete from my IDE for the installed package but it does not work inside the app.

**Comment by fnaquira** [comment]
did you manage to solve it?

**Comment by Duell10111** [comment]
I also have some strange behaviors so that some functions are suddenly undefined and that the database file which contains the data can not be read anymore and therefore the tables can not be found anymore
