### ISSUE TITLE
AuthSession -> redirecting back to app on Android fails even on the "Expo Client" -> "Explore APIs" example

### ISSUE THREAD

**Issue by superKalo** [expo/expo#8348]
### Environment

```
  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v13.12.0/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: 37.0.0 => 37.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-native-web: 0.11.7 => 0.11.7
      react-navigation: 4.3.7 => 4.3.7
    npmGlobalPackages:
      expo-cli: 3.20.3
```

Android (via the Expo Client app), Android Standalone

### Steps to Reproduce

I can even reproduce it via the Expo Client app on Android -> "Explore" tab -> "Expo APIs".

1. Tap "Expo APIs" (from the "Explore" tab of the Expo Client app).
2. Tap AuthSession
3. Authenticate. Upon success, instead of the expected "success" response... "dismiss" comes.
4. Try to authenticate 2nd time. All good -> "success" response comes.

Here's a video showcasing the issue: https://youtu.be/_J05-tIX8pk

- The Phone is on Android 10, but it happens on Android 9 too.
- Expo client app v2.15.4, but it happens on our Android standalone app too
- works just fine on iOS (both - Expo Client and standalone app)

Same issue with our custom back-end. Always succeeds on the 2nd time, not the first one.

### Expected Behavior

To receive "success" right after the first successful authentication.

### Actual Behavior

As shown in the video I shared (https://youtu.be/_J05-tIX8pk), it always "succeeds" on the second attempt.

### Reproducible Demo

Expo Client app on Android -> "Explore" tab -> "Expo APIs" -> Tap AuthSession

**Comment by byCedric** [comment]
Hi @superKalo! Thanks for your detailed issue report and videos! That helps a lot, we will take a look at this 😄

**Comment by EvanBacon** [comment]
The demo needs to be updated to reflect the new API. It looks like this on master https://twitter.com/baconbrix/status/1256985914749759488?s=21

**Comment by superKalo** [comment]
@EvanBacon , I think that's different, no?

I actually want to use [`WebBrowser.openAuthSessionAsync()`](https://docs.expo.io/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl) for doing the authorization against my custom back-end.

I tried alternatively to use `AuthSession.startAsync()` but it takes me through this additional step with the `returnUrl`, which I don't need because my custom back-end redirects me back to the app.

**Comment by EvanBacon** [comment]
You can redirect back into your app on Android by using `Linking.makeUrl()` from `expo-linking` this guide should help you understand the patterns better https://docs.expo.io/guides/authentication/#redirect-uri-patterns -- alternatively you can eject to the bare workflow for a simpler redirecting system.
