### ISSUE TITLE
Background Location Tracking not working on iOS

### ISSUE THREAD

**Issue by iamnader** [expo/expo#8349]
### Environment

  ```
Expo CLI 3.17.21 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 13.2.0 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.17.21
```

This is a managed app targeting iOS and Android.  There is no issue on Android, this issue only exhibits on iOS.

### Steps to Reproduce

I am trying to get background location tracking working on iOS.  It works fine on Android.

I'm requesting Location Permission like this:
```
  const { status } = await Permissions.askAsync(Permissions.LOCATION);
  console.log(`*** requestLocationPermission: ${status}`);
```

The task is defined in a top level scope:
```TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
    if (error) {
      console.log("LOCATION_TRACKING task ERROR:", error.message);
      return;
    }
    if (data) {
      const { locations } = data;
      const { coords, timestamp } = locations[0];
      const { latitude, longitude } = coords;
    
     ...
    }
  });
```

In the component where I want to track location:
```
function LocationSubscriber({ profile }) {
  useEffect(() => {
    startLocationTracking();
  });

  const startLocationTracking = async () => {
    await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
      accuracy: Location.Accuracy.Highest,
      timeInterval: 60000,
      distanceInterval: 0
    });
    const hasStarted = await Location.hasStartedLocationUpdatesAsync(
      LOCATION_TASK_NAME
    ); 
  };

  return <></>;
}
```

In `app.json` I have:

```
"ios": {      
      "infoPlist": {
        "UIBackgroundModes": ["location"],
        ...
      }
    },
```

I bumped my app version and resubmitted through the app store to make the `app.json` changes take effect.

### Expected Behavior

Location should be tracked.  This works in Android, but not iOS

### Actual Behavior

In iOS when calling `Location.startLocationUpdatesAsync` I get this error: `Background Location has not been configured. To enable it, add 'location' to 'UIBackgroundModes' in Info.plist file.`

### Question

One thing I've noticed is in the [documentation](https://docs.expo.io/versions/latest/sdk/location/#background-location) it says `Permissions.LOCATION permission must be granted. On iOS it must be granted with Always option — see Permissions.LOCATION for more details.`

When the app requests permission it doesn't give the "Always" option, only the "When using the app", "One time" and "Never" options.  Is there a special way to request permission such that "Always" is an option? Is that necessary?

### Reproducible Demo

I don't think background location tracking is demoable in a Snack? If so please advice on how

**Comment by GMoon777** [comment]
this is the code I have in my app.json which is working 

`    "ios": {
      "bundleIdentifier": "com.ourtor.ourtorapp",
      "buildNumber": "0.0.8",
      "googleServicesFile": "./GoogleService-Info.plist",
"infoPlist": {
        "UIBackgroundModes": [
          "location",
          "fetch"
        ]
      },`

**Comment by iamnader** [comment]
Hi @GMoon777 your infoPlist looks like mine, though I don't have `fetch` as I'm not using that.

Do your users see the "always" option when requesting location?  I think that might be the issue, I'm not seeing that

**Comment by iamnader** [comment]
From the description here: https://docs.expo.io/versions/latest/sdk/permissions/. It looks like I need to include in infoPlist all 3 descriptions to get my users to see the "Always Allow" option to get background location tracking working.  @GMoon777 have you done that?

**Comment by byCedric** [comment]
Hi @iamnader! Did you manage to get it working after adding the `infoPlist` properties?

**Comment by iamnader** [comment]
Yes! Thanks for the help.

**Comment by reinaldonetof** [comment]
Hi @iamnader ! What did you do to resolve your problem?? 

Either SDK37 or SDK38 didn't work for me. Is the same issue that you had in init of here.

I tried to add into infoPlist, as:
 `"ios": {
      "infoPlist": {
        "UIBackgroundModes": ["location"],
        "NSLocationWhenInUseUsageDescription": "text",
        "NSLocationAlwaysAndWhenInUseUsageDescription": "text",
        "NSLocationAlwaysUsageDescription": "text"
      },
      "supportsTablet": true,
      "bundleIdentifier": "com.ohyeahapps.ohyeah",
      "buildNumber": "1.0.0"
    },`

I set `await Permissions.askAsync( Permissions.LOCATION )`, and continue to appear the same error: `Error: Background Location has not been configured. To enable it, add `location` to `UIBackgroundModes` in Info.plist file.`

both sdk37 and in sdk38.

I'm using Windows, and I tried the bare workflow too, but the same problem!

**Comment by iamnader** [comment]
Hi @reinaldonetof, after I rebuilt and deployed to the app stores with the infoPlist updates, it is strange, but I had to wait about 24 hours, and then it started working...I don't really understand why.  Good luck

**Comment by mehmetsalihakcan** [comment]
Hello @reinaldonetof ,
i have same problem on ios app.Did you solve this problem?

**Comment by sumit1317** [comment]
SDK 40..has the error on Android - "Not authorized to use background location services" and on iOS - "Background Location has not been configured. To enable it, add `location` to `UIBackgroundModes` in Info.plist file.]"
Any one else facing the same ?

**Comment by realfresh** [comment]
> SDK 40..has the error on Android - "Not authorized to use background location services" and on iOS - "Background Location has not been configured. To enable it, add `location` to `UIBackgroundModes` in Info.plist file.]"
> Any one else facing the same ?

Yeah can't get mine to work either on Android. Says the same thing "Not authorized to use background location services". I have requested location permission, the scope is `always`. Not sure what the issue is.

**Comment by brentvatne** [comment]
background location permissions are opt in on android in sdk 40. the error you're seeing on ios is pretty self explanatory so i'll skip over that.

https://docs.expo.io/versions/latest/config/app/#permissions

make sure your android.permissions config includes `ACCESS_BACKGROUND_LOCATION`

cc @byCedric

**Comment by sumit1317** [comment]
No success with ACCESS_BACKGROUND_LOCATION inside android.permissions config

**Comment by realfresh** [comment]
Thanks for the quick reply! Yeah, I've followed the permission documentation. My app is not ejected. I've done the following:

```
await Permissions.askAsync(Permissions.LOCATION);
```

Location permission comes back as:
```
{
  "canAskAgain": true,
  "expires": "never",
  "granted": true,
  "permissions": {
    "location": {
      "android": {
        "accuracy": "fine",
      },
      "canAskAgain": true,
      "expires": "never",
      "granted": true,
      "scope": "always",
      "status": "granted",
    },
  },
  "status": "granted",
}
```

I'm not on Android 10 either, the scope says `always`. However, it still throws the following error:

`Not authorized to use background location services.`

**Comment by realfresh** [comment]
Not sure what's changed but it magically works now! Literally changed nothing in the code or my phone. Just came back to it a few days later, ran the app and bam it worked

**Comment by phongduybui** [comment]
For anyone continue looking for a reason, in IOS 13 above apple have updated your policy below, so you dont see option `Always` in prompt:
![image](https://user-images.githubusercontent.com/66737107/188479686-1735f2c0-c048-4e6e-94f9-46c514be5dc0.png)

**Comment by AsijaR** [comment]
> For anyone continue looking for a reason, in IOS 13 above apple have updated your policy below, so you dont see option `Always` in prompt: ![image](https://user-images.githubusercontent.com/66737107/188479686-1735f2c0-c048-4e6e-94f9-46c514be5dc0.png)

Does this mean you have to wait at least 24h to get the user's location when using Expo Go the first time when running the app ?
