### ISSUE TITLE
Build custom client with Turtle CLI

### ISSUE THREAD

**Issue by destinybonavita** [expo/expo#8354]
### Please note that discussions opened as issues in the core Expo repository will be closed.

Is it possible to build a custom Expo Client with the `turtle-cli`? I'm not sure it normally takes on average for custom clients to build but I was hoping to be able to do it manually so I can track progress rather than sit and wait for it to finish

**Comment by byCedric** [comment]
Hi @destinybonavita! I'm not sure what you mean by custom Expo Client. When creating a build from the managed workflow, you get the Expo Client with your javascript or app embedded. If you want to create a build from the bare workflow, you have to do that yourself. Turtle does not support bare projects, _**yet**_ 😄 

[From the docs](https://docs.expo.io/introduction/why-not-expo/#limitations-of-the-bare-workflow):
> To build your app binaries for distribution on the Apple App Store and Google Play Store you will need to follow the same steps that you would in any native project, the Expo build service can't handle it for you. We are working on bringing bare workflow support to the build service in the near future.

Hope it helps!
