### ISSUE TITLE
[expo-media-library] MediaLibrary doesn't work on Android Devise

### ISSUE THREAD

**Issue by hoshinaoshi** [expo/expo#8359]
## 🐛 Bug Report
If you call MediaLibrary, it will be unresponsive, only on Android Device.
It fine on iOS Device, iOS Simulator and Android Emulator.
This is not a crash, it is unresponsive.

### Environment

  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.20.1

### Steps to Reproduce

The steps are very simple.

1. Write code to use MediaLibrary
2. Build .aad file
3. Release to Google Play
4. Install The app
5. Run on Android Device

### Expected Behavior

I'm hoping that it will work on Android devices without any problems.

### Actual Behavior

All MediaLibrary methods don't work.
(.requestPermissionsAsync(), .getAssetsAsync(), etc...)

### Reproducible Demo

```
import * as React from 'react';
import { Alert, View } from 'react-native';
import Constants from 'expo-constants';
import * as MediaLibrary from 'expo-media-library';

async function load(){
  await MediaLibrary.requestPermissionsAsync() 
  let options = { first: 1, sortBy: [[MediaLibrary.SortBy.creationTime, false]], mediaType: MediaLibrary.MediaType.photo }
  let mediaLibrary = await MediaLibrary.getAssetsAsync(options)
  Alert.alert("unreachable")
}

export default function App() {
  load()
  return (
    <View></View>
  );
}
```

Thanks in advance.

**Comment by byCedric** [comment]
Hi @hoshinaoshi, I can't seem to reproduce this issue. I put your code in a snack to test it, and the alert with `unreachable` is triggered. ([see snack here](https://snack.expo.io/@bycedric/media-library-android-issue-8359)). If you are running this from a standalone app, make sure you added the [required permissions to your app manifest](https://docs.expo.io/versions/latest/sdk/permissions/#android-permissions-equivalents-inside-appjson).

Hope it helps

**Comment by hoshinaoshi** [comment]
@byCedric 
Thank you for your advice.
When I checked my app.json, "WRITE_EXTERNAL_STORAGE" was missing.
When I added it and checked it, it worked fine...!

Thank you very much for this.

**Comment by rgdamalerio** [comment]
> @byCedric
> Thank you for your advice.
> When I checked my app.json, "WRITE_EXTERNAL_STORAGE" was missing.
> When I added it and checked it, it worked fine...!
> 
> Thank you very much for this.

can you post your sample app.json, mine does not work.  below is my app.json

`{
  "expo": {
    "name": "PDRRMOhhprofiler",
    "slug": "PDRRMOhhprofiler",
    "platforms": ["ios", "android", "web"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./app/assets/icon.png",
    "splash": {
      "image": "./app/assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./app/assets/favicon.png"
    },
    "android": {
      "permissions": ["WRITE_EXTERNAL_STORAGE"]
    }
  }
}
`

**Comment by ZanPerse** [comment]
import * as MediaLibrary from 'expo-media-library'; this is wrong 
import * as ImagePicker from 'expo-image-picker'; Correct 

Look at the link bellow where u have an example of the ImagePicker with permission and it works on android and u don't have to add nothing to app.json  if ur in managed workFlow. I hope this was helpful.

here is the documentation https://docs.expo.dev/versions/latest/sdk/imagepicker/#imagepickergetmedialibrarypermissionsasync
