### ISSUE TITLE
Error Loading Asset [expo-updates]

### ISSUE THREAD

**Issue by mdcuk34** [expo/expo#8362]
## 🐛 Bug Report

An `expo-export` hosted update for a bare application errors while downloading assets.

### Environment

```
Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.20.9
```

Expo Bare IOS Application 
Expo-Updates: 0.2.2

### Steps to Reproduce

- Build a release mode bare IOS application with expo-updates 0.2.2
- Build will run fine
- Generate update with `expo export --public-url xx --asset-url xx` and host on our own server
- `Updates.checkForUpdateAsync()` returns true
- Calling `Updates.fetchUpdateAsync();` returns `error loading asset 778ffc9fe8773a878e9c30a6304784de.png`.
- We get this 7 times all for assets related to react-navigation other assets don't appear to error.

Note: The urls to these assets are accessible.

### Expected Behavior

- Update completes successfully

### Actual Behavior

<img width="278" alt="Screenshot 2020-05-19 at 16 10 17" src="https://user-images.githubusercontent.com/8708607/82344635-35132480-99ec-11ea-9a99-2d7c0e1f194f.png">

```
2020-05-19 14:51:01.913070+0100 [46411:3570475] error loading asset 02bc1fa7c0313217bde2d65ccbff40c9.png: {Error in request: '0HLVRV9OOJ8LS'}
2020-05-19 14:51:02.044787+0100 [46411:3570474] error loading asset 778ffc9fe8773a878e9c30a6304784de.png: {Error in request: '0HLVRV9OOJ8LT'}
2020-05-19 14:51:02.048871+0100 [46411:3570475] error loading asset 0ea69b5077e7c4696db85dbcba75b0e1.png: {Error in request: '0HLVRV9NK7NMT'}
2020-05-19 14:51:02.065872+0100 [46411:3570474] error loading asset f5b790e2ac193b3d41015edb3551f9b8.png: {Error in request: '0HLVRV9TNK9GS'}
2020-05-19 14:51:02.132731+0100 [46411:3570439] error loading asset 376d6a4c7f622917c39feb23671ef71d.png: {Error in request: '0HLVRV9TNK9GT'}
2020-05-19 14:51:02.220883+0100 [46411:3570475] error loading asset 35ba0eaec5a4f5ed12ca16fabeae451d.png: {Error in request: '0HLVRV9TNK9GU'}
2020-05-19 14:51:02.489381+0100 [46411:3570475] error loading asset c79c3606a1cf168006ad3979763c7e0c.png: {Error in request: '0HLVRV9NK7NMU'}
```

**Comment by mdcuk34** [comment]
Switching to a more specific assetBundlePatterns fixes this, for this was: 
```
 "assetBundlePatterns": [
      "src/assets/**/*",
      "packages/ui-lib-native/assets/**/*"
    ],
```

**Comment by byCedric** [comment]
Hi @mdcuk34! Thanks for the issue and workaround. To investigate this a bit further, could you provide a small example repo? This would help extremely help us get it fixed asap 😄

**Comment by AlefiyaG** [comment]
I am facing a similar issue with expo sdk 37 and expo-updates 0.2.7. 
so I generate update with expo export --public-url xx --asset-url xx and host on our own server. When it tries to download the assets it doesn't use the absolute URL present in android-index.json file, it actually combines the expo update url in android manifest file with the assetUrlOverride.

Based on the documentation
https://docs.expo.io/workflow/expo-cli/ 

expo export  with --asset-url could be a relative or absolute path. in my case it is absolute but its treated as relative and suffixed with the expo update url from the manifest file. Could you please help me with this issue. I need the assets to be located at an absolute path.

**Comment by innonguyen** [comment]
I had the same issue when upgrading to Expo SDK 42 from SDK 41.
I recognize that Expo assets has been upgraded from 8.3.2 to 8.3.3 as well.

Here's my error

`Unable to resolve module ./LocalAssets from Documents/project/node_modules/expo-asset/build/Asset.js: 

None of these files exist:
  * node_modules/expo-asset/build/LocalAssets(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * node_modules/expo-asset/build/LocalAssets/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
> 1 | import { Platform } from '@unimodules/core';
  2 | import { getAssetByID } from './AssetRegistry';
  3 | import * as AssetSources from './AssetSources';
  4 | import * as AssetUris from './AssetUris';`

**Comment by vivek751** [comment]
its crash anroid
