### ISSUE TITLE
Expo Font -> Error finding directory | unable to load fonts

### ISSUE THREAD

**Issue by nickdebaise** [expo/expo#8368]
### Environment

Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:

      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.13.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.11
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.9

Built for IOS using expo-cli

### Steps to Reproduce

I have tried around 4 separate times. Each time I take these steps and produce the same result.

1) initiate a new project using expo init
expo init Jot

2) run expo install expo-font in directory

3) load up the project, create a font folder within /assets and import any font

4) Follow any steps in this documentation:
https://docs.expo.io/guides/using-custom-fonts/

5) Attempt to load fonts garners a warning error and the project does not load:

Note that this is not the exact error, the directory has been changed for privacy reasons
[Unhandled promise rejection: Error: Directory for file:///Users/nick/Library/Developer/CoreSimulator/Devices/SOMELONGEXPOSTRING/data/Containers/Data/Application/ANOTHERLONGSTRING/Library/Cac
hes/ExponentExperienceData/%2540nickdeb%252FJot/ExponentAsset-MORELONGSTRINGS.ttf doesn't exist.]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:99:50 in fn
- node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js:15:46 in moduleName.methodInfo.name
- node_modules/expo-file-system/build/FileSystem.js:105:50 in downloadAsync
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:274:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke

- node_modules/regenerator-runtime/runtime.js:170:17 in PromiseImpl$argument_0
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/regenerator-runtime/runtime.js:169:31 in PromiseImpl$argument_0
- node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:219:8 in exports.async
- node_modules/expo-file-system/build/FileSystem.js:101:7 in downloadAsync
- node_modules/expo-asset/build/PlatformUtils.js:49:50 in _downloadAsyncManagedEnv
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:274:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:145:19 in PromiseImpl.resolve.then$argument_0
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue

### Expected Behavior

I expected that the app would load the font and be able to use it within the app.

### Actual Behavior

The error appears, the font state never changes to true and is stuck in AppLoading. It is not a fatal error (app does not crash).
I have tried restarting and clearing the cache since, I have tried installing expo-asset in case it was missing a dependency. Other than that, expo-font simply does not load the font.
### Reproducible Demo

While I do not have a specific reproducible demo, in Expo Snack, I managed to create a demo where the font was not actually loaded but said it was, similar to my issue:

https://snack.expo.io/@nickdeb/demo

**Comment by brentvatne** [comment]
can you try reseting the state of your simulator?
 
<img width="288" alt="Screen Shot 2020-05-19 at 1 01 49 PM" src="https://user-images.githubusercontent.com/90494/82372487-e86e2000-99d0-11ea-8742-5f379084dbaa.png">

**Comment by nickdebaise** [comment]
@brentvatne thanks for that, it is now working. It felt like I tried everything but that. Thanks again.

**Comment by sugar3103** [comment]
> can you try reseting the state of your simulator?
> 
> <img alt="Screen Shot 2020-05-19 at 1 01 49 PM" width="288" src="https://user-images.githubusercontent.com/90494/82372487-e86e2000-99d0-11ea-8742-5f379084dbaa.png">

It work like a charm, thank you very much
