### ISSUE TITLE
MapView fails when used on web

### ISSUE THREAD

**Issue by diegoboston** [expo/expo#8369]
## 🐛 Bug Report

The snack linked from here:
https://docs.expo.io/versions/latest/sdk/map-view/
fails when I try to run on Web with the following error.

(0 , g.requireNativeComponent) is not a function
Evaluating module://react-native-maps.js
Evaluating module://App.js.js
Loading module://App.js

### Environment

web (expo snack environment)

### Steps to Reproduce

Go to
https://docs.expo.io/versions/latest/sdk/map-view/

Click on Try this example on snack

Choose to run on web

It will fail with a red error, message: 

(0 , g.requireNativeComponent) is not a function
Evaluating module://react-native-maps.js
Evaluating module://App.js.js
Loading module://App.js

### Expected Behavior

The example in the documentation should work.

### Actual Behavior

Red error

### Reproducible Demo

See steps above.

**Comment by byCedric** [comment]
Hi @diegoboston! Thanks for your issue report. Unfortunately, `MapView` is not supported on web. There were some attempts in the past of making the library compatible with web. There are other users who definitely want to see support, like [this issue](https://github.com/react-native-community/react-native-maps/issues/3113) for example.

There are three things that you can do at the moment.
1. Create a new issue asking for `react-native-web` support [at the repository](https://github.com/react-native-community/react-native-maps).
2. Create a component to render the map, e.g. `AwesomeMap.tsx`, and create a web alternative component with `AwesomeMap.web.tsx`.

You can read more about [how to write some platform-specific code here](https://reactnative.dev/docs/platform-specific-code). Hope it helps! 😄

**Comment by Agent215** [comment]
@byCedric byCedric
> Hi @diegoboston! Thanks for your issue report. Unfortunately, `MapView` is not supported on web. There were some attempts in the past of making the library compatible with web. There are other users who definitely want to see support, like [this issue](https://github.com/react-native-community/react-native-maps/issues/3113) for example.
> 
> There are two things that you can do at the moment.
> 
> 1. Create a new issue asking for `react-native-web` support [at the repository](https://github.com/react-native-community/react-native-maps).
> 2. Create a component to render the map, e.g. `AwesomeMap.tsx`, and create a web alternative component with `AwesomeMap.web.tsx`.
> 
> You can read more about [how to write some platform-specific code here](https://reactnative.dev/docs/platform-specific-code). Hope it helps! 😄

Hey I am building an app currently that uses react-native-maps, and I wanted to see if It is possible to use react-native-maps for the web build also. I see you proposed two workarounds. Pardon my ignorance, but what do mean when you say :
```2. Create a component to render the map, e.g. `AwesomeMap.tsx`, and create a web alternative component with `AwesomeMap.web.tsx`. ```
by web alternative do you mean like use regular google maps, and just call that component when we detect we are on a browser? 
Any specific help or examples would be greatly appreciated.
