### ISSUE TITLE
remove the AR module

### ISSUE THREAD

**Issue by esamelson** [expo/expo#8371]
- [x] add expo.fyi page (more info/context there) https://github.com/expo/fyi/pull/7
- [x] add deprecation message to SDK 37 expo package https://github.com/expo/expo/pull/8372
- [x] remove AR module and ARKit dependency from iOS client
- [x] remove AR module from expo package and change log message to indicate it's been removed rather than deprecated
- [ ] ensure nothing breaks in shell apps/expokit
- [x] remove AR example from applereview account

**Comment by tsapeta** [comment]
I'm closing this issue as almost all steps are done, ensuring nothing is broken in shell apps is gonna be a part of QA so we no longer need to track it here 🙂

**Comment by nik-sloop** [comment]
I am getting this error when I try to load my project, but I am not using AR. How do I clear the message?

**Comment by brentvatne** [comment]
@nik-sloop - you're probably on an old sdk version before this was fixed?

**Comment by nik-sloop** [comment]
I just updated to sdk38
