### ISSUE TITLE
IOS Iphone not displaying live video after giving "Yes" permission(expo) to camera in webview.

### ISSUE THREAD

**Issue by vasanthhr** [expo/expo#8376]
Hello ,
Does reactnative webview supports to open camera for Iphone(IOS) ?

I tried using below code and working properly on Android phones and displaying live video.
In IPhone(IOS), I could see pop coming to open webcamera and white screen displays after clicking "Yes" permission to camera.

```
  async componentDidMount() {

 // here Permissions imported  from 'expo-permissions';
   const { status } = await Permissions.askAsync(Permissions.CAMERA);
   const { status_camera_roll } = await Permissions.askAsync(Permissions.CAMERA_ROLL);

   this.setState({
     hasCameraPermission: status === 'granted'
   });
   
   }


  render() {
    const url = 'https://webcamtests.com/';
    return (
      <WebView
    useWebKit
      originWhitelist={['*']}
      allowsInlineMediaPlayback
    bounces={true}
        source={{
          uri: url,
        }}
        startInLoadingState
        scalesPageToFit
        javaScriptEnabledAndroid={true}
        javaScriptEnabled={true}        
        style={{ flex: 1 }}
      />
    );
  }
```
Please guide me . Thanks.

**Comment by byCedric** [comment]
Hi @vasanthhr! I don't think asking the Camera permissions in your app results in the permission being granted in the webview. Here is why:

- When you ask and receive permissions for the camera, iOS grants the installed app permission to the camera.
- When you ask permissions in Safari to use the camera, it uses a different permission system (Safari's built-in permissions).

You can, however, render the [`expo-camera`](https://docs.expo.io/versions/latest/sdk/camera/) after getting the camera permission! With that you can stream or render the camera within your app.

Hope it helps!

**Comment by vasanthhr** [comment]
@byCedric 

Can you update me, what kind of permission that we need to config or enable to make camera work seamlessly on react-native IOS webview. I believe IOS webview needs additional changes in .m file or additional config.

Please let me know if you can guide me on the same.
