### ISSUE TITLE
How to remove permissions in standalone app

### ISSUE THREAD

**Issue by pavlov-sergey-alexandr** [expo/expo#8379]
in my app.json 
    "android": {
      "package": "-----------",
      "permissions": [
        "CAMERA",
        "RECORD_AUDIO",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ],

in google play console i have permission:

android.permission.ACCESS_NETWORK_STATE
android.permission.ACCESS_WIFI_STATE
android.permission.CAMERA
android.permission.FOREGROUND_SERVICE
android.permission.INTERNET
android.permission.MODIFY_AUDIO_SETTINGS
android.permission.READ_EXTERNAL_STORAGE
android.permission.RECEIVE_BOOT_COMPLETED
android.permission.RECORD_AUDIO
android.permission.REQUEST_INSTALL_PACKAGES
android.permission.STORAGE
android.permission.SYSTEM_ALERT_WINDOW
android.permission.WAKE_LOCK
android.permission.WRITE_EXTERNAL_STORAGE
com.google.android.c2dm.permission.RECEIVE
com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE
com.game_name.C2D_MESSAGE
host.exp.exponent.permission.C2D_MESSAGE

My application for children. Therefore, high requirements for publication. The Google Play team asked me: why is your application collecting personal and confidential information from children? I think, because in my application there is permission that I do not need.

The permissions that my application needs are indicated in app.jsion. How to remove unnecessary permissions?
Help me please

**Comment by byCedric** [comment]
Hi @pavlov-sergey-alexandr! Could you try creating a new standalone version of your app with an empty `permissions` array in your manifest? That should remove all permissions that aren't required. Keep in mind that every time you update the permissions in your manifest, you will need to create a new standalone app. If you are creating one, make sure to _not use_ the `--no-publish` flag, because that won't update the manifest and therefore reuse the old permissions. Do you use the managed or bare workflow, because in bare you might need to update your android manifest too.

Hope it helps!

**Comment by pavlov-sergey-alexandr** [comment]
I made command expo build:android with next app.json
.......
    "updates": {
      "fallbackToCacheTimeout": 0,
      "enabled": false
    },
    "android": {
      "package": "app_name",
      "permissions": [],
.......

Now camera are not working in my application. When I start the camera, the Permissions.askAsync request is not executed.

When I launch the camera:
- the permission request window for using the camera does not appear
- A message will immediately appear stating that access to the camera is denied.
  This post was developed for the case when the user denies access to
  camera (status! == "granted")

My code to allow access to the camera is as follows

export const getPermissions = (type, denied, screen) => {
  return async (dispatch) => {

    const { status } = await Permissions.getAsync(Permissions[type]);

    if (status !== 'granted') {
      return dispatch(askPermission(type, denied, screen));
    }

    return dispatch({
      type: PERMISSIONS.SET_PERMISSIONS,
      payload: { type, value: true },
    });
  };
};

export const askPermission = (type, denied, screen) => {
  return async (dispatch) => {
    try {
      const { status } = await Permissions.askAsync(Permissions[type]);
  
      if (status !== 'granted') {.   <<<<<<<<<---------------- This condition is always true now.
        dispatch({
          type: NOTIFICATION,
          payload: {
            notificationMessage: denied.header,
            description: denied.meessage,
            typeNotification: 'info',
          },
        });

        return dispatch({
          type: PERMISSIONS.SET_PERMISSIONS,
          payload: { type, value: false, screen },
        });
      }

      return dispatch({
        type: PERMISSIONS.SET_PERMISSIONS,
        payload: { type, value: true },
      });
    } catch (e) {
      handlerError(dispatch, e);
    }
  };
};

 I use the managed workflow.

What should I do?

**Comment by pavlov-sergey-alexandr** [comment]
I use   "sdkVersion": "35.0.0",

My app.json is next

{
  "expo": {
    "name": "name",
    "slug": "slug",
    "privacy": "unlisted",
    "sdkVersion": "35.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.5",
    "orientation": "portrait",
    "icon": "./assets/images/init/brand.png",
    "splash": {
      "image": "./assets/images/init/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#4896C3"
    },
    "updates": {
      "fallbackToCacheTimeout": 0,
      "enabled": false
    },

    "assetBundlePatterns": ["**/*"],

    "android": {
      "package": "package_name",
      "permissions": [],
      "versionCode": 5,
      "adaptiveIcon": {
        "backgroundColor": "#4896c3",
        "backgroundImage": "./assets/images/init/backgroundImage.png",
        "foregroundImage": "./assets/images/init/foregroundImage.png"
      }
    },

    "ios": {
      "supportsTablet": true,
      "icon": "./assets/images/init/brand.png"
    },
    "packagerOpts": {
      "transformer": "node_modules/react-native-svg-transformer/index.js",
      "config": "metro.config.js",
      "sourceExts": ["js", "jsx", "ts", "tsx", "svg"]
    }
  }
}

**Comment by pavlov-sergey-alexandr** [comment]
What should I do?

**Comment by brentvatne** [comment]
please refer to this doc https://docs.expo.io/distribution/app-stores/#android-permissions

**Comment by pavlov-sergey-alexandr** [comment]
I did as written in your documentation. But in my app.json there are 3 permissions, and the build for the Google Play console has 18 permissions. I wrote about this above.

Is this normal? Expo does not allow to release applications for some groups of users?

**Comment by BloodyMonkey** [comment]
@pavlov-sergey-alexandr Any update on this ? I'm stuck and no clues about what happen

**Comment by felix-lambert** [comment]
Same for me :'( Any updates? I cannot deploy to google play

**Comment by loureirorg** [comment]
Use `blockedPermissions` to force Expo to remove any unwanted permissions. 

For example:
```js
// app.json
"android": {
  // ...
  "permissions": [],
  "blockedPermissions": [
    // use fully qualified names
    "android.permission.RECORD_AUDIO",
    "android.permission.CAMERA"
  ]
}
```

Sometimes it's a library in your "package.json" that is adding extra permissions. 

And, of course, use `permissions` to remove the tons of extra permissions added by Expo (ex. camera access, microphone recording, etc).

**Comment by brentvatne** [comment]
@loureirorg - heads up - the `permissions` key works differently in classic builds vs EAS Build. on EAS Build, `permissions` is just for adding permissions, it doesn't remove any.

**Comment by loureirorg** [comment]
That makes a lot of sense. I recently started using SDK 45 and EAS, and my binary got lots of unwanted permissions, like camera and microphone access. 

I wondered what I had done wrong or differently, as I had never had any issues before. Doing a `permissions: []` didn't work to remove the permissions, and things only got right when I added `blockedPermissions`.

I'm glad to know about these changes.

**Comment by ezekiel747** [comment]
It's not clear from the docs how to use blockedPermissions, at the moment.
For example, the permissions in docs has an array with the possible values (eg. RECORD_AUDIO)
The blockedPermissions, however, doesn't have any example and i thought that adding "RECORD_AUDIO" would be enough.
But it doesn't seem to work at all. Now i've read in this thread that it must be "android.permission.RECORD_AUDIO" instead.

I think this would be useful to mention in docs here https://docs.expo.dev/versions/latest/config/app/#blockedpermissions
@brentvatne or someone else.
Thank you.

**Comment by brentvatne** [comment]
@ezekiel747 - agreed, it is a bit unclear! to use it, indeed you need to specify the full permission name
