### ISSUE TITLE
IOS Client Crashes

### ISSUE THREAD

**Issue by jasuperior** [expo/expo#838]
I have built an app in expo, that worked fine until today. I've made no changes to my project, yet trying to load my app using the expo xde, or using react-native-scripts causes the expo ios app to crash after downloading and bundling the js. 

There are no errors being reported in the terminal, and i dont quite know what the issue could be considering it was working a day ago. 

Any help would be appreciated.

**Comment by jasuperior** [comment]
I've tried deleting the app and reinstalling, yet nothing.

**Comment by jasuperior** [comment]
I figured out the problem. There was a stray console.log(this.props) that was silently causing an error. I've since removed it and everything is working again.

**Comment by JulianKingman** [comment]
@jasuperior I have these issues off and on, can you reopen the issue?

**Comment by lucfranken** [comment]
Can reproduce this issue. 

Working:

    console.log('some string')

Crashing:

    console.log(this)

It seems the connection to the Expo applicaton has issues. The simulator also reported an error (red page) once saying something like: Could not write to Expo XDE console. Not sure of the exact text anymore unfortunately.

**Comment by chrisbobbe** [comment]
If I log props other than props.children, it doesn't crash.
