### ISSUE TITLE
is possible remove EXPO when log in in facebook and google?

### ISSUE THREAD

**Issue by ARChatco** [expo/expo#8389]
I have done it with the facebook schema and with the facebookDisplayName but I continue seeing "Expo wants to know your info bla bla"

**Comment by byCedric** [comment]
Hi @ARChatco, what are you using to authenticate with? Is it `AuthSession`, `AppAuth`, or anything else? Also, are you using managed or the bare workflow?

**Comment by ARChatco** [comment]
Managed, so it is an expo completely app. and I want to publish it. on production.

- 'expo-google-app-auth' for google 
-   'expo-facebook' for facebook

In both of of them I get the message from expo asking permission

**Comment by ARChatco** [comment]
is possible this consent screen is. just. showed when Im running the app through expo and when it is stand alone is dissapear?

![Image from iOS](https://user-images.githubusercontent.com/54442778/82613226-b15c6200-9bbc-11ea-886f-420fe7f12c9d.png)

**Comment by cruzach** [comment]
hi @ARChatco , that will only occur when using the App Store Expo Client, so once you build your .ipa file (or use a custom client build), you can use your own FacebookId, display name, and all the rest! We talk about all of this in our [documentation](https://docs.expo.io/versions/latest/sdk/facebook/#configuration):
> No configuration is needed to use the Facebook SDK in the App Store Expo client, because all of your Facebook API calls will be made with **Expo's Facebook App ID**. The slight downside to this is that you can't customize which permissions your app requests from Facebook (like user_photos or user_friends), or integrate Facebook login with other services like Firebase auth. If you need that functionality, you have two options:
[Build a standalone app](https://docs.expo.io/distribution/building-standalone-apps/)
[Build a custom Expo Client app](https://docs.expo.io/guides/adhoc-builds/)
