### ISSUE TITLE
expo-firebase-analytics doesn't allow number in property names

### ISSUE THREAD

**Issue by frantic** [expo/expo#8390]
### Environment

```
  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.12.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.1
```

Developing inside Expo app on iOS

### Steps to Reproduce

```
Analytics.setUserProperties({hello_11: 'test'});
```

### Expected Behavior

User property is set

### Actual Behavior

Promise returned from `setUserProperties` is rejected with:
> "Error: Invalid user-property name specified. Should contain 1 to 24 alphanumeric characters or underscores. The name must start with an alphabetic character"

### Looking into the code

[This comment](https://github.com/expo/expo/blob/6f0c3a53651063627b88ee322b9ef8a5344995d8/packages/expo-firebase-analytics/src/Analytics.ts#L130) claims the property name should be alphanumeric and not start with number. However the [actual code](https://github.com/expo/expo/blob/6f0c3a53651063627b88ee322b9ef8a5344995d8/packages/expo-firebase-analytics/src/FirebaseAnalyticsJS.ts#L233) rejects all properties with numbers.

**Comment by byCedric** [comment]
Hi @frantic! Awesome, thanks for the issue report _and the fix_ 😄 We will take a look at it and merge it asap!

**Comment by EvanBacon** [comment]
fixed in https://github.com/expo/expo/pull/8516
