### ISSUE TITLE
print.Async height & width

### ISSUE THREAD

**Issue by owenhope** [expo/expo#8392]
Hi,

I am trying to print to a 4in by 6in label using Print.printAsync using Expo 36.

In the docs, it says that you can pass height and width but I am getting very odd results.

For instance, it seems to print at least 4 or 5 extra blank pages.

Are the docs updated? Or am I missing something?

Basically I am getting a very small version of what I am trying to print due to what looks like from scaling.

Does anyone have a work around?

**Comment by byCedric** [comment]
Hi @owenhope! Could you maybe provide an example or small repro? The docs should be up to date in this case, but printing is always a tricky process. E.g., orientation is handled differently in the printer or the WebView or UIMarkupTextPrintFormatter might behave differently when printing to certain special formats.  But, to fully investigate possible issues here, we need an example.

Hope it helps 😄

**Comment by borkanee** [comment]
> Hi,
> 
> I am trying to print to a 4in by 6in label using Print.printAsync using Expo 36.
> 
> In the docs, it says that you can pass height and width but I am getting very odd results.
> 
> For instance, it seems to print at least 4 or 5 extra blank pages.
> 
> Are the docs updated? Or am I missing something?
> 
> Basically I am getting a very small version of what I am trying to print due to what looks like from scaling.
> 
> Does anyone have a work around?

Did you manage to get width and height working on a label printer?
