### ISSUE TITLE
expo-image-picker returns cancelled when used with "allowsEditing" set to true

### ISSUE THREAD

**Issue by ikroeber** [expo/expo#8397]
### Android

Expo CLI 3.18.0 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ^37.0.0 => 37.0.8
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-navigation: ^3.0.9 => 3.0.9

### Steps to Reproduce

Just use the ImagePicker with

```js 
// "launchCameraAsync" also gives the same response when withEditing is set to true
ImagePicker.launchImageLibraryAsync({
            allowsEditing: true, aspect: [5, 7],
            quality: 3, mediaTypes: ImagePicker.MediaTypeOptions.Images
        }).then((i) => {
            if (i.cancelled)
                return;
            //Any code here
        }).catch(() => {
            //Error treatment code here
        });
```

### Expected Behavior

It should return the image details as the width, height, uri, and type.

### Actual Behavior

It just returns:
```js
{ cancelled: true }
```

### Reproducible Demo

Reproducible demo:https://snack.expo.io/@ikroeber/imagepicker-returning-cancelled-when-shouldn't

**Comment by ikroeber** [comment]
The error was occurring because quality was set to 3. The error handling should warn people about wrong values like that. It was very difficult to find out where the error came from.

**Comment by brentvatne** [comment]
yup that’s a very reasonable point; can you create an issue for that or reopen and adjust this one?

**Comment by ikroeber** [comment]
May I change the title?
