### ISSUE TITLE
Do you need to download the Expo client to access the permanent QR code generated by the Expo publishing. You can't access it with wechat browser or mobile browser directly, right?

### ISSUE THREAD

**Issue by yrjwcharm** [expo/expo#8398]

**Comment by byCedric** [comment]
Hi @yrjwcharm. I think the [forums](https://forums.expo.io/) or [community slack](https://slack.expo.io/) might be better to ask these kinds of questions in the future 😄 We only use GitHub for issues and not necessarily questions. That being said:

We don't "officially" support integrating Expo in WeChat, but it might work if you convert it to a web app. You might be able to use it [using this docs](https://developers.weixin.qq.com/miniprogram/en/dev/#Apply-for-an-account).

Hope it helps!
