### ISSUE TITLE
Facebook login uses a webview on iOS

### ISSUE THREAD

**Issue by RLADR** [expo/expo#84]
Facebook standards indicate that a webview should not be used for Facebook login.
https://developers.facebook.com/docs/facebook-login/best-practices#avoidwebview

It is very desirable to allow users to log in to an app via Facebook without reentering their username and password. One of the main benefits of Facebook login is to reduce friction by eliminating that step.

Using a webview forces users to log in manually. This may only affect users who do not have the Facebook app installed, But that is a fairly high percentage of users. Facebook's own studies indicate that far more users are logged in via Safari, and if a web view is not used and if the user does not have the Facebook app installed, Safari will launch with the user already logged in, leaving them only to accept the apps permissions.

Please modify Facebook login to follow Facebook standards and not use a webview.

**Comment by jesseruder** [comment]
Did you see this? https://docs.expo.io/versions/v15.0.0/sdk/facebook.html#behavior-string--the-type-of-login-prompt-to-show-currently-this-is-only-supported-on-ios-and-must-be-one-of-the-following-valuesweb-default--attempts-to-log-in-through-a-modal-uiwebview-pop-upnative--attempts-to-log-in-through-the-native-facebook-app-this-is-only-supported-for-standalone-appsbrowser--attempts-to-log-in-through-safari-or-sfsafariviewcontroller-this-is-only-supported-for-standalone-appssystem--attempts-to-log-in-through-the-facebook-account-currently-signed-in-through-the-device-settings-this-is-only-supported-for-standalone-apps

**Comment by rlad** [comment]
Thanks jesseruder, I'm referring to the default behavior, which is a webview.

**Comment by jesseruder** [comment]
The default behavior where? In the main Expo app? That's a limitation of the Facebook SDK.

**Comment by terribleben** [comment]
Facebook login uses a webview in our Expo Client app and can be configured to use native behavior in a standalone build. Hopefully that is the info you were looking for.

**Comment by tofoli** [comment]
WebView only works (_default_) to log in with Facebook. When I change the "_behavior_" parameter to any of the other options, after I elevate the Facebook APP, the following message is displayed and nothing in the log is printed.

![whatsapp image 2017-08-14 at 17 55 57](https://user-images.githubusercontent.com/2599384/29291414-e099512e-8119-11e7-8191-5057d593578b.jpeg)

I'm testing on an iPhone 4S with IOS 9.3.5 and an iPhone 6S with IOS 10.2.1. On Android it works normally. Any idea what that might be?

PS: I used Google Translate. Excuse me
