### ISSUE TITLE
Unreliable Linking.getInitialUrl results from cold start on Android standalone app

### ISSUE THREAD

**Issue by jtbeach** [expo/expo#8408]
### Environment

```
  Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.11 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.9
```

Bug seems to be timing dependent, but can reproduce both in managed Expo workflow and after ejecting to bare workflow.

- I know about #6586, but we do not see our app being mounted twice on startup, so I think this is a separate issue with similar symptoms

### Steps to Reproduce

- **Bug appears to be Android only**
- **Bug appears to be timing dependent** -- it occurs on some phones and not others and is not 100% deterministic in simulator (but can be reproduced there). I believe there is some race condition that is causing this, which is why it appears on some phones and not others. It does not depend on Android SDK version, but does occur more on some phones than others due to timing. It can even be inconsistent on the same phone/installation.
- **Bug only reproducible in standalone builds**

1. Clone https://github.com/stellaai/expo-deeplink-test, which is a minimal reduced test case -- created directly from `expo init` and with some small changes made to `App.tsx` to listen to for deep links / initial URLs and display them. Is it registered to handle URLs of the format https://stella.jobs/deeplink/test in `app.json`
2. Build standalone app -- bug is not reproducible using the Expo client
3. Install app on simulator or device via `adb install`
4. Make sure that app is closed (cold start)
5. Try to launch app via intent: `adb shell am start -a "android.intent.action.VIEW" -d "https://stella.jobs/deeplinktest/test"`

### Expected Behavior

- App started with the link passed in the URL displayed (https://stella.jobs/deeplinktest/test) displayed

### Actual Behavior

Inconsistent behaviour of Linking.getInitialUrl. Sometimes it the initial URL is correctly set to that passed in the intent, but sometimes it is not (in those cases it is `null` in the bare workflow and  
`https://expo.io:443/@stellablaze/stella-deeplinktest` in the managed workflow).

Below are adb logs from the managed workflow version of the app when the initial URL is not set correctly. Note that ActivityTaskManager gets the right URL in the Intent, but by the time the main activity is run, `initialUri` is set to "https://expo.io:443/@stellablaze/stella-deeplinktest". In the bare workflow, this is null. 

**Note:** on the real app, I am also seeing this problem when trying to open the app on cold start from a push notification click.

```
05-21 07:33:40.772  1225  4195 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=https://stella.jobs/... cmp=jobs.stella.deeplinktest/host.exp.exponent.MainActivity (has extras)} from uid 10367 pid 30556
05-21 07:33:41.055  1225  1407 I ActivityTaskManager: Displayed jobs.stella.deeplinktest/host.exp.exponent.MainActivity: +292ms
05-21 07:33:41.064  1225  3334 D ActivityTaskManager: setRequestedOrientation() to 1 for ActivityRecord{29edde6 u0 jobs.stella.deeplinktest/host.exp.exponent.MainActivity t21208} from pid=5531, uid=10380
05-21 07:33:41.213  1225  1315 D ActivityTaskManager: setRequestedOrientation() to 1 for ActivityRecord{29edde6 u0 jobs.stella.deeplinktest/host.exp.exponent.MainActivity t21208} from pid=5531, uid=10380
05-21 07:33:41.232  5531  5531 D ReactNative: ReactInstanceManager.ctor()
05-21 07:33:41.239  5531  5531 D ReactNative: ReactInstanceManager.createReactContextInBackground()
05-21 07:33:41.239  5531  5531 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
05-21 07:33:41.239  5531  5531 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
05-21 07:33:41.239  5531  5531 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
05-21 07:33:41.239  5531  5531 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
05-21 07:33:41.242  5531  5621 D ReactNative: ReactInstanceManager.createReactContext()
05-21 07:33:41.263  5531  5621 D ReactNative: Initializing React Xplat Bridge.
05-21 07:33:41.263  5531  5621 D ReactNative: Initializing React Xplat Bridge before initializeBridge
05-21 07:33:41.268  5531  5621 D ReactNative: Initializing React Xplat Bridge after initializeBridge
05-21 07:33:41.268  5531  5621 D ReactNative: CatalystInstanceImpl.runJSBundle()
05-21 07:33:41.270  5531  5628 D ReactNative: ReactInstanceManager.setupReactContext()
05-21 07:33:41.270  5531  5628 D ReactNative: CatalystInstanceImpl.initialize()
05-21 07:33:41.271  5531  5628 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
05-21 07:33:41.521  5531  5627 I ReactNativeJS: Running "main" with {"initialProps":{"exp":{"initialUri":"https://expo.io:443/@stellablaze/stella-deeplinktest","manifest":{"id":"@stellablaze/stella-deeplinktest","bundleUrl":"https://d1wp6m56sqw74a.cloudfront.net/%40stellablaze%2Fstella-deeplinktest%2F1.0.0%2Fea11b9f03f7021bd04a9a3f42bfedc2d-37.0.0-android.js","revisionId":"1.0.0-r.coGXN45Cm","locales":{},"releaseId":"bdff7158-1eb5-440e-bf2d-e1fda11ae124","slug":"stella-deeplinktest","name":"deeplinktest","icon":"./assets/icon.png","loadedFromCache":true,"splash":{"resizeMode":"contain","backgroundColor":"#ffffff","image":"./assets/splash.png","imageUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/b8895f17edbefb9f51b1f863c9811e44"},"orientation":"portrait","publishedTime":"2020-05-20T12:05:50.164Z","releaseChannel":"default","iconUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/41aba486029b982d6f7773e6eed0f5b4","isVerified":true,"version":"1.0.0","bundledAssets":["asset_3a2ba31570920eeb9b1d217cabe58315.ttf","asset_8b12b3e16d591abc926165fa8f760e3b.json","asset_744ce60078c17d86006dd0edabcd59a7.ttf","asset_461d9bba8b6a3c91675039df12cfe6ca.json","asset_140c53a7643ea949007aa9a282153849.ttf","asset_94c4ffdcbffeb0570c635d7f8edd8a25.json","asset_ca9ce9ff0676a9b04ef0f8a3ad17dd08.ttf","asset_54a5c98d22f313098b3dbe2d5b2e87ba.json","asset_b49ae8ab2dbccb02c4d11caaacf09eab.ttf","asset_39843e5d52a6c5c42d5abdb0b34bcaa6.json","asset_b06871f281fee6b241d60582ae9369b9.ttf","asset_f1f91feb805137c9283fb766620ec5eb.json","asset_09dd345dbd4ec5a0874841d5749ac153.json","asset_0886a6b127c6057cee83f9c65c7ffd62.json","asset_f6c6f6c8cb7784254ad00056f6fbd74e.ttf","asset_b70cea0339374107969eb53e5b1f603f.ttf","asset_c39278f7abfc798a241551194f55e29f.ttf","asset_e20945d7c929279ef7a6f1db184a4470.ttf","asset_60668d999bbaf663420340f7bdd580d7.json","asset_b2e0fc821c6886fb3940f85a3320003e.ttf","asset_3e6805fbc794680014716b8c752f20b8.json","asset_3c851d60ad5ef3f2fe43ebd263490d78.ttf","asset_1a0e3525dd5df87e77057204129a5e6e.json","asset_a37b0c01c0baf1888ca812cc0508f6e2.ttf","asset_7e078700f0c35367a56c5bbb2047dda7.json","asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf","asset_fdc01171a7a7ea76b187afcd162dee7d.json","asset_d2285965fe34b05465047401b8595dd0.ttf","asset_647543ebfccf6e5495434383598453d1.json","asset_5cdf883b18a5651a29a4d1ef276d2457.ttf","asset_74d124a3caeac2bea111f3ca2f2dd34a.json"],"android":{"versionCode":1,"intentFilters":[{"category":["BROWSABLE","DEFAULT"],"data":[{"pathPrefix":"/deeplinktest/","host":"stella.jobs","scheme":"https"},{"pathPrefix":"/deeplinktest/","host":"*.stella.jobs","scheme":"https"}],"autoVerify":true,"action":"VIEW"}],"package":"jobs.stella.deeplinktest"},"sdkVersion":"37.0.0","platforms":["ios","android","web"],"hostUri":"exp.host/@stellablaze/stella-deeplinktest","commitTime":"2020-05-20T12:05:50.229Z","dependencies":["expo","react","react-dom","react-native","react-native-screens","react-native-web"],"ios":{"buildNumber":"1.0.0","bundleIdentifier":"jobs.stella.deeplinktest"},"updates":{"fallbackToCacheTimeout":0}},"shell":true}},"rootTag":1}
05-21 07:33:41.555  5531  5627 I ReactNativeJS: getInitialURL received: https://expo.io:443/@stellablaze/stella-deeplinktest
05-21 07:33:41.555  5531  5627 I ReactNativeJS: onUrlEvent received: https://expo.io:443/@stellablaze/stella-deeplinktest
```

### Reproducible Demo

- Minimal app for reproducible demo at https://github.com/stellaai/expo-deeplink-test
- There are 2 branches -- `master` (Expo managed workflow) and `ejected` (Expo bare workflow)
- *Only reproducible in a standalone app*
- We are seeing device-specific failures to load our Android app from a cold start. iOS is fine and some Android devices are fine (older ones). Known devices with failure our OnePlus 6 and Samsung Galaxy s10e 
- Deep linking works consistently once app is started -- warm start link opening seems reliable for the managed app, although I have seen some cases where I didn't get url events at all after the initial URL failed to load.

I have posted a video of this in action at: https://youtu.be/7djIsvL1nBs

- Simulator shows app showing URL currently sent via Intent
- Top terminal window shows adb logs for emulator
- Bottom terminal window shows me sending `adb shell am start -a "android.intent.action.VIEW" -d "https://stella.jobs/deeplinktest/test"` commands to test

Note that results are inconsistent. Sometimes when app is closed and then started from URL, the initial URL returned is null. When that happens, further attempts to send URLs to the app also fail. Other times it works fine.

The video is showing the ejected app in action (ie. the `ejected` branch of the Github repo).

**Comment by jtbeach** [comment]
Note: this seems to be a bug in vanilla React Native -- this works in Expo SDK 25, but fails in Expo 26 and Expo 27. I also reproduced this bug by tweaking the standard generated app using `react-native init`.

Unfortunately this means that creating a reliable app that can launch from a link or a push notification on React Native 0.61 (Expo 26 + 27) does not work and Apple is no longer accepting submission from the working React Native (Expo 25) due to UIWebView removal.

**Comment by byCedric** [comment]
Hi @jtbeach! Thanks for the issue report. As you said, this seems to be an issue with React Native. There are a few open issues at the moment: [#28727](https://github.com/facebook/react-native/issues/28727) and [#25675](https://github.com/facebook/react-native/issues/25675). Let's keep this open, as soon as we have some bandwidth we will fix this!

**Comment by jtbeach** [comment]
Thanks @byCedric  -- I have added some more detailed information / analysis at https://github.com/facebook/react-native/issues/25675#issuecomment-634442362 since that issue sounds closer to what I am seeing (I have not seen on iOS so far). 

Let me know if there's any other info I can provide to help!

**Comment by Stephen2** [comment]
@jtbeach thank you so much for your efforts!
