### ISSUE TITLE
Build is producing a 32-bit artifact, but I need a 64-bit for Facebook App Approval

### ISSUE THREAD

**Issue by kshahani** [expo/expo#8410]
I'm running `expo build:ios -t simulator`, and when I download the artifact, I'm presented with the fact that its a 32 bit build, and I can't open it on Catalina. Does anyone know what to do? I think it might have something to do with setting the build architecture on xcodebuild. Any help would be great!

```
Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.20.9
```

**Comment by brentvatne** [comment]
hello! there's a warning when you run the build:

> 🚨 If the build is not installable on your simulator because of "... is damaged and can't be opened.", please run: xattr -rd com.apple.quarantine /path/to/your.app

sadly this is needed on catalina. if you follow those instructions it will work

**Comment by kshahani** [comment]
![image](https://user-images.githubusercontent.com/22452366/82595447-9285ad80-9b73-11ea-9a5a-1740846d8254.png)

Unfortunately not! I've tried `xattr -rd com.apple.quarantine /path/to/your.app` as well, but this is still the case.

**Comment by kshahani** [comment]
@brentvatne If you don't mind, please re-open the issue as I'm sure others have encountered this as well.

**Comment by Madnarth** [comment]
Ran into the same issue, still without a solution.
```
  Expo CLI 3.22.1 environment info:
    System:
      OS: Windows 10 10.0.17134
    Binaries:
      Node: 12.16.2 - ~Program Files\nodejs\node.EXE
      Yarn: 1.15.2 - ~Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - ~Program Files\nodejs\npm.CMD
    npmPackages:
      expo: 36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
```

**Comment by Madnarth** [comment]
@kshahani did ever get it resolved?
