### ISSUE TITLE
[expo-auth-session] Redirect URI missing trailing slash for Facebook

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo#8411]
### Steps to Reproduce

1. Use the `-with-facebook-auth` example.
2. Add `@react-navigation/native`
3. Replace the request type to code and exchange this code on the server / manually using curl
3. Run on the web

### Expected Behavior

It works.

### Actual Behavior

_Getting_ a code works perfectly fine. The exchange will give an error along the line of "Verification failed, make sure redirect uri is correct".

```
https://www.facebook.com/v6.0/dialog/oauth
    ?code_challenge=<something>
    &display=popup
    &code_challenge_method=S256
    &redirect_uri=http%3A%2F%2Flocalhost%3A19006
    &client_id=<client-id>
    &response_type=code
    &state=<random-state>
    &scope=public_profile%20email"
```
- The redirect URI generated (console log) is: `http://localhost:19006`
- The redirect URI in the dialog seems to be `http%3A%2F%2Flocalhost%3A19006` (which is the same, so correct)

### Workaround

The facebook error goes away if you send `http://localhost:19006/` (trailing slash). If you run into this, you can append `/`, if the redirect uri equals `window.location.origin`. So before you send the `redirectUri` to your server to exchange the token, fix it:

```tsx
function fixRedirectUri(redirectUri: string) {
  if (Platform.OS !== 'web') {
    return redirectUri;
  }

  if (redirectUri !== window.origin) {
    return redirectUri;
  }

  return redirectUri + '/';
}
```

### Reproducible Demo

I'm currently on my phone; I'll happily try to snack this up when I have some spare cycles, but for now I'm just creating the issue to document it, in case other people run into this.

**Comment by EvanBacon** [comment]
Perhaps your URL could be modified in the Facebook console to not require a slash. I built a demo screen that is used to test Facebook auth on web. Here is the source https://github.com/expo/expo/blob/5a6e0d7fb0a083847752fbf3fcc8ae60abdb736e/apps/native-component-list/src/screens/AuthSession/AuthSessionScreen.tsx#L393

**Comment by SleeplessByte** [comment]
- The redirect uris on Facebook have no trailing slash.
- The domains on Facebook _automatically_ get a trailing slash.

Note that when I wrote the blog post, I facebook authentication worked fine on the web;

1. I'll try out the demo;
2. Then I'll diff it with a minimal reproducible example;
3. I'll explicitly check if this is resolved when removing react navigation

And then we can go from there 👯

**Comment by EvanBacon** [comment]
`response_type=token` works too, we use it for Firebase + Facebook auth https://docs.expo.io/guides/authentication/#facebook. Closing for now, feel free to reopen when you can reproduce the error.

**Comment by SleeplessByte** [comment]
In the end it seems that it might have been Facebook; it just didn't work for localhost addresses, but did work for everything else. Now it also works for localhost addresses. This started working without weird hacks :) (but #9917 so can't use it).
