### ISSUE TITLE
Build is producing a 32-bit artifact, but I need a 64-bit for Facebook App Approval

### ISSUE THREAD

**Issue by kshahani** [expo/expo#8412]
Opening a new issue since the last one was closed, CC @brentvatne.

![image](https://user-images.githubusercontent.com/22452366/82597506-12614700-9b77-11ea-8942-a45bf992c4c2.png)

I'm running `expo build:ios -t simulator`, and when I download the artifact, I'm presented with the fact that its a 32 bit build, and I can't open it on Catalina. I've tried the `xattr -rd com.apple.quarantine /path/to/your.app` trick to no avail either.

```
Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.20.9
```

**Comment by kshahani** [comment]
Resolved. FYI Facebook App Approval runs the app with `ios-sim launch /path/to/your-app.app`. Easy!

Zzz. 10/10 documentation from Facebook 🤦

**Comment by farhan-ibrahim** [comment]
Hi @kshahani , can you explain, how you convert to 64-bit apps?
