### ISSUE TITLE
ImageManipulator on Android applying resize height/ width to smaller dimension on portrait photos, resulting in wrong size

### ISSUE THREAD

**Issue by llamaluvr** [expo/expo#8416]
### Environment

Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.10 => 37.0.10 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: 4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.20.9

### Steps to Reproduce

On Android, send a portrait photo and a landscape photo through `ImageManipulator.manipulateAsync()` with options set to scale the size down by limiting the larger of width or height to a certain number of pixels.

### Expected Behavior

If `options` are set as such...
```
if (image.height > image.width) {
      options = { height: 640 };
    } else {
      options = { width: 640 };
    } 
}
```

Then both the portrait and landscape photo will be within 640px.

A 4:3 landscape photo will end up being scaled to 640x480.
A 3:4 portrait photo will end up being scaled to 480x640.

### Actual Behavior

A 4:3 landscape photo is scaled scaled to 640x480.
A 3:4 portrait photo will end up being scaled to 640x853.

Note that this is Android only. This is working just fine on iOS.

### Reproducible Demo

Snack: https://snack.expo.io/@llamaluvr/expo-37-image-manipulator-issue

![image](https://user-images.githubusercontent.com/8053974/82609235-18145800-9b8a-11ea-87a3-b5f656abf9db.png)

### Discussion

This is an issue on at least Expo 36 and 37. Confirmed with both a Pixel 2 and Galaxy S8. I tried to set `options` to `{ height: 640, width: 640 }`, but that didn't change the output.

There was a similar issue in Expo 30 that was resolved in Expo 31 (https://github.com/expo/expo/issues/2512). It seems like `ImageManipulator` isn't taking the `Orientation` on the exif data into consideration correctly, but in a different way than before.

### Workaround

So far, I've worked around this by changing my image manipulation logic as such:
```
if (
      Platform.OS === 'android' &&
      // this showed up again in Expo 36?
      pickedImage.exif &&
      pickedImage.exif.Orientation > 1 &&
      (pickedImage.exif.Orientation === 6 /* portrait up */ || pickedImage.exif.Orientation === 8 /* portrait reversed */) &&
      pickedImage.width > pickedImage.height
    ) {
      // portrait seems to reverse height and width just for the ImageManipulator, only on portrait
      resizeObj = { height: 640 };
    } else {
      if (pickedImage.height > pickedImage.width) {
        resizeObj = { height: 640 };
      } else {
        resizeObj = { width: 640 };
      }
    }
    operations.push({ resize: resizeObj });
    let manipResult = await ImageManipulator.manipulateAsync(pickedImage.uri, operations, {
      format: 'jpeg',
    });
```

**Comment by dsokal** [comment]
I tried to reproduce this in Expo 41 but it seems to be working fine - I used the provided snack. I tested it on a real device - Redmi 4A. I assume this is an outdated issue.

**Comment by grifotv** [comment]
I initially had this workaround https://github.com/expo/expo/issues/2512#issuecomment-442879454 and it was solving the Android issues for me.

After upgrading `expo-image-picker` from [14.1.1](https://github.com/expo/expo/blob/main/packages/expo-image-picker/CHANGELOG.md#1411--2023-02-09) to [14.3.0](https://github.com/expo/expo/blob/main/packages/expo-image-picker/CHANGELOG.md#1430--2023-06-13), I had to remove the above workaround as the latest version includes this fix https://github.com/expo/expo/pull/22383
