### ISSUE TITLE
[iOS] undefined is not an object (evaluating 'Payments.initialize')

### ISSUE THREAD

**Issue by iuliuvisovan** [expo/expo#842]
I'm using iOS, and I am doing as described here: https://docs.expo.io/versions/v21.0.0/sdk/payments.html#content

This is my code: 

```
import {DangerZone} from 'expo';
const {Payments} = DangerZone;

Payments.initialize({publishableKey: 'pk_live_Qcm47tqcL7ZYRL1F7h0AfWuN'})
```
This is my podfile:

![image](https://user-images.githubusercontent.com/11357552/31947567-470f733e-b8dd-11e7-95a0-d32fd14fc14e.png)

I then run `pod install` in the `ios` folder. Everything seems to be completing successfully.

I then run `exp start` and then `exp ios` (this I'm not sure is the right way since it's using unsupported native module), and when the app opens, I see this screen:

![image](https://user-images.githubusercontent.com/11357552/31947647-772b27ac-b8dd-11e7-8841-1675508cdf9c.png)

What am I doing wrong?

Is there any example project whatsoever that uses Payments w/ ExpoKit on iOS and works? I would like to take a look at it.

**Comment by brentvatne** [comment]
hello! you need to open the project's xcworkspace file and run it like other detached projects -- you can't use `exp ios` for it.  see these steps: https://docs.expo.io/versions/latest/guides/expokit.html#setting-up-your-project

**Comment by iuliuvisovan** [comment]
No matter what I did, the native module for TPSStripe was nowhere to be found. I eventually manually added the tipsi-stripe package, linked it to my project, and that added the TPSStripe native module, and was able to use the Payments API via expo. Not sure if it's a problem on my end or what but.. in case someone stumbles upon this in the future on iOS, this is the way to go.

**Comment by kodayashi** [comment]
Hi @brentvatne I hit this same issue. I've ejected following the instructions and am running the app from Xcode on an iPhone 5S/iOS 11.1 Simulator with the same issue (not using `expo ios`). Also tried on a real iPhone 8/iOS 11.1.2.

I will try @iuliuvisovan's workaround, but FYI this does appear to be an issue.

**Comment by asgeo1** [comment]
I'm having the exact same issue. Payments doesn't appear to work on iOS.

My app was already detached, and I run it via `exp start` / XCode. I've since added the `Payments` pod.

But payments are not available via `DangerZone` on iOS.

If I look at the `DangerZone` object, it looks like this:

```
{
   ...
   "Payments": undefined,
}
```

Why would it be undefined for if I've added the `Payments` pod?

**Comment by asgeo1** [comment]
OK, I worked it out. The Expo Podspec has a typo in it, which prevents the Payments module from being added into XCode. Hence why it appears to be missing.

I submitted a PR here:  https://github.com/expo/expo/pull/1080

**Comment by digitaledge** [comment]
That PR was overwritten with one of the latest commits.

**Comment by terribleben** [comment]
Argh. We have a script internally which generates this file, and that gets shipped to this repository. I will make a fix to the underlying script.
