### ISSUE TITLE
Cannot remove MODIFY_AUDIO_SETTINGS permission on Android

### ISSUE THREAD

**Issue by LinusU** [expo/expo#8432]
### Environment

```text
  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
      Yarn: 1.22.4 - node_modules/.bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
```

### Steps to Reproduce

1. Add an array of permission in your `app.json` that does **not** include `MODIFY_AUDIO_SETTINGS`
2. Publish, build and upload the app to the Google Play Console
3. Look at list of required permissions in the Google Play Console

### Expected Behavior

`MODIFY_AUDIO_SETTINGS` should not be in the required permissions for the app

### Actual Behavior

For some reason `MODIFY_AUDIO_SETTINGS` is still in the permissions required by the app.

### Reproducible Demo

not yet provided 😬

**Comment by byCedric** [comment]
Hi @LinusU! In your reproduce steps, you don't list creating a new build. Did you publish _and_ created a new build? Permissions are [one of the few properties that require a new standalone app](https://docs.expo.io/workflow/publishing/#some-native-configuration-cant-be-updated-by). If you haven't done this, that's your fix 😄 If not, I'd be happy to investigate it further.

Hope it helps!

**Comment by LinusU** [comment]
Sorry, I was a bit vague, with "Publish the app for Android" I meant build and upload to the Google Play Store.

Updating the main post now!

**Comment by LinusU** [comment]
I don't think that this needs more info 🤔

**Comment by LinusU** [comment]
@byCedric would it be possible to re-open this? Is there any more information needed from my side?

**Comment by LinusU** [comment]
@byCedric I can confirm that this is still an issue with SDK 42, would you mind reopen this?

It is however fixed with EAS Build, but since that is another service that's in beta I don't think that we can consider this fixed yet...

**Comment by Jeysoon** [comment]
Hello @LinusU 
I think you are having a misunderstanding about how permissions works in expo, according to the oficial documentation specifically [permissions section](https://docs.expo.dev/versions/latest/config/app/#permissions) i quote 

> To use ONLY the following minimum necessary permissions and none of the extras supported by Expo in a default managed app, set permissions to []. The minimum necessary permissions do not require a Privacy Policy when uploading to Google Play Store and are:
> • receive data from Internet
> • view network connections
> • full network access
> • change your audio settings
> • prevent device from sleeping 
>  To use ALL permissions supported by Expo by default, do not specify the permissions key. 
>   To use the minimum necessary permissions ALONG with certain additional permissions, specify those extras in permissions, e.g.
>  [ "CAMERA", "ACCESS_FINE_LOCATION" ].

Saying all this we can say its not possible to change this without using 'eject' from expo, also these permissions does not require a Privacy Policy so we can say is not that much to worry about in what regards to uploading you app to the stores.

**Comment by jankapunkt** [comment]
Any updates on this?
