### ISSUE TITLE
`getAvailablePictureSizesAsync` requires you to pass a ratio argument like '16:9'

### ISSUE THREAD

**Issue by zanona** [expo/expo#8433]
`getAvailablePictureSizesAsync` requires you to pass a ratio argument like '16:9'

_Originally posted by @jamesloper in https://github.com/expo/expo/issues/4190#issuecomment-507075197_

However, this doesn't seem to be type-checked by TS?

**Comment by byCedric** [comment]
I don't think you have to, in [this snack](https://snack.expo.io/@bycedric/github---camera---getavailablepicturesizes), you can fetch the aspect ratios without parameters. Also, we keep the doc as updated as possible. It's best to [look this up there](https://docs.expo.io/versions/latest/sdk/camera/#getavailablepicturesizesasync) 😄 

Hope it helps!

**Comment by zanona** [comment]
Hi, @byCedric. I'm afraid you do need it.
Whenever calling it without an argument it throws:

> [Unhandled promise rejection: Error: getAvailablePictureSizes -- unexpected error -- Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference]

Please note that the error is for `getAvailablePictureSizesAsync` and not `getSupportedRatiosAsync`.

The snack linked uses `selectedRatio` as argument which is expected, but it's not being type checked as I mentioned previousy?
