### ISSUE TITLE
Camera.getAvailablePictureSizesAsync not returning 19:9

### ISSUE THREAD

**Issue by zanona** [expo/expo#8435]
### Steps to Reproduce

My phone (Samsung Galaxy S10e) has a 19:9 ratio but whenever having a Camera preview in place which using the entire screen height (flex:1), the picture looks stretched. With that in mind, I'm using the `getAvailablePictureSizesAsync` which is only returning as max of '16:9' resolution without the full '19:9' one available.

```
ratios Array [
  "1:1",
  "3:2",
  "4:3",
  "11:9",
  "16:9",
]
```

### Expected Behavior

I expect that `getAvailablePictureSizesAsync` would return `19:9` and allow me to have the Camera preview using a non-stretched picture.

### Actual Behavior

The Camera preview is stretched even when using the max `16:9` ratio set.
Setting `<Camera ... ratio='19:9'/>` has no effect.

**Comment by byCedric** [comment]
Hi @zanona! thanks for the issue report, could you [try to run this snack on your S10e](https://snack.expo.io/@bycedric/github---camera---getavailablepicturesizes)? I receive the `19:9` aspect ratio on an OnePlus 6 without any issues. The issue could be Samsung-specific, but we need to find out what's going wrong before we can fix it 😄 

Hope it helps!

**Comment by zanona** [comment]
Hey, Cedric. Thanks for following up. Yes, I'm afraid I still only get up to 16:9 here. See:  ![](https://i.imgur.com/wbvIH2r.jpg)

**Comment by fabriziobertoglio1987** [comment]
https://github.com/expo/expo/blob/5d59e2b8d50bcdac71c669cfeef0e9765e0f9890/packages/expo-camera/android/src/main/java/expo/modules/camera/CameraModule.java#L264-L282

https://developer.android.com/reference/android/hardware/Camera.Parameters#getSupportedPictureSizes()
