### ISSUE TITLE
our expo-based app crashes at startup in some devices, does expo has logs?

### ISSUE THREAD

**Issue by mikewguo** [expo/expo#8439]
Our application based on expo, has user report of crashes at startup on some devcies.  This happens rarely, but when it does happen, we are hopeless/powerless.  Does expo has logs?

**Comment by brentvatne** [comment]
are you using sentry or some exception reporting service?

**Comment by mikewguo** [comment]
We aren't using any <yet>.  When a user reports a crash situation, we are just wondering whether there is any logs generated by expo itself.  Is there anything we need to do to enable expo logs?

**Comment by brentvatne** [comment]
we don't track logs for you, although that would be a nice feature one day maybe :)

you can try connecting your device to your computer and looking at the device logs to potentially get more info: https://docs.expo.io/workflow/logging/#optional-manually-access-device-logs

**Comment by tsapeta** [comment]
Brent already answered your question and created another issue #8443 which after completing would be helpful in such cases. Closing this one 🙂
