### ISSUE TITLE
[docs] Troubleshooting guide for "my app is crashing" and "my app just has a white screen"

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8443]
eg: https://github.com/expo/expo/issues/8439

it's very easy for people to make their app crash, and most people who would struggle with these issues also aren't familiar with error reporting services. so we should meet them where they're at and do things like recommend something like sentry/bugsnag, explain how to see device logs, look at native crash info, and others.

**Comment by brentvatne** [comment]
<img width="1144" alt="Screen Shot 2020-05-23 at 1 00 05 PM" src="https://user-images.githubusercontent.com/90494/82739577-5ed29100-9cf5-11ea-9cbb-2455700eba9a.png">

another example of this from today

**Comment by ujjuboay** [comment]
I am also getting the same error and I tried of viewing log as you suggested but I am not able to undestand the output of logs.
Please help with the white screen.

**Comment by brentvatne** [comment]
Follow these steps:
- Change `updates` `fallbackToCacheTimeout` to something large like `30000` and rebuild your apk, open it in the Android simulator
- Observe it not working as you explained
- Change your root component to be something simple like `<Text>Hello world</Text>` and then run `expo publish`
- Close and reopen the app in the simulator
- Do you see "Hello world?" - probably! Now you know some part of your code is leading to this happening.
- Add things back slowly, run `expo publish` each time and check the result.
- Eventually you will find the part that is causing this problem.

This happened to me yesterday because I was using `useWindowDimensions` from `react-native`, which [froze the app](https://github.com/facebook/react-native/issues/26733) due to a bug in react-native@0.61. If you have this hook in your app, you should remove it. But your specific issue might be caused by something else.
