### ISSUE TITLE
Expo recording on react native web

### ISSUE THREAD

**Issue by jackow98** [expo/expo#8447]
### Environment

 Expo CLI 3.20.3 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
      Yarn: 1.21.1 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.12.6 => 0.12.6
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: 0.61.5 => 0.61.5
      react-native-web: 0.11.7 => 0.11.7

web

### Steps to Reproduce

I am developing a react native app which allows users to record audio
The code works for Android however when using React Native web, I receive an error

### Expected Behavior
Recording starts

### Actual Behavior
TypeError: Cannot read property 'uri' of undefined
    at Recording.prepareToRecordAsync$ (Recording.ts:317)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:145

### Reproducible Demo
https://snack.expo.io/@jackow98/audio-recording

**Comment by jackow98** [comment]
Hello, wondering if you have any updates/insight into this issue?

**Comment by ishandikshit** [comment]
I am having the same issue as well

**Comment by WazzaJB** [comment]
When searching for my own issue, I noticed this below. Apologies, I created a separate PR and issue for this.

See issue #8721 

If you require web recording functionality, then your feedback on my PR #8791 would be most welcome :)
