### ISSUE TITLE
[docs] Explain how to share base64 encoded data uris with Sharing.shareAsync 

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8448]
https://forums.expo.io/t/how-to-share-images-of-the-form-data-uri-scheme-within-expo-managed-workflow/38089/4

basically you just need to use expo-file-system to write it to disk with base64 encoding. before you write, remove the data-uri meta prefix. https://snack.expo.io/@notbrent/excited-cereal

**Comment by Matth33w** [comment]
> https://forums.expo.io/t/how-to-share-images-of-the-form-data-uri-scheme-within-expo-managed-workflow/38089/4
> 
> basically you just need to use expo-file-system to write it to disk with base64 encoding. before you write, remove the data-uri meta prefix. https://snack.expo.io/@notbrent/excited-cereal

That solved my problem! Thank you very much!
