### ISSUE TITLE
[expo-cli] Build the bundle without publishing - bare workflow

### ISSUE THREAD

**Issue by jonathanstiansen** [expo/expo#8449]
With managed workflow you can run `expo build:<platform>` with a flag that stops it from pushing to expo's default channel.

I'd like the same thing to be true for `expo publish` because, we depend on expo publish to build a bundle to package with our iOS IPAs and APKs in our bareworkflow.

Use case - we add a native feature to our app, we want to submit to app store. But we don't want to push our javascript code out to previous users.

A current work around is to just change the release channel to be the same as our git tags.

**Comment by brentvatne** [comment]
you are in luck, we are switching over to this being the default in the bare workflow! you can see how to change your expo-updates configuration to be like this and learn more in this blog post: https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf
