### ISSUE TITLE
Getting "Converting circular structure to JSON" when navigating from a screen with navigationOptions with <TextInput>

### ISSUE THREAD

**Issue by Eyesonly88** [expo/expo#845]
I hit a very annoying bug which causes "Converting circular structure to JSON" when trying to navigate using the `react-navigation` library shipped with expo.

I tracked the problem to having the following in my component:
```
    static navigationOptions = ({navigation}) => {
        return {
            title: <TextInput
                onChangeText={(value) => {navigation.setParams({query: value})}}
                placeholder="search"
                placeholderTextColor= 'gray'
                style={{
                    height: 30,
                    width: 150,
                    borderColor: 'white',
                }} />,
        }
    };
```
Anything in the title object other than a string crashes the app with "Converting circular structure to JSON" error when navigating to another screen from this component.

When I remove the code above from my component, everything works fine.

I think the issue is related to this bug in `react-navigation` > https://github.com/react-community/react-navigation/issues/420

It happens in both normal and debug modes.

I wanted to report this bug in case other people hit it using Expo not knowing what is going on. It took me 3 hours to investigate and find the issue as the error messages when the crash happen don't make any sense. Perhaps updating the react-navigation lib to latest version might fix it but I don't know.

**Comment by ide** [comment]
This looks almost entirely related to React Navigation. Is there something that Expo could do to make it easier to read the error message and debug this kind of problem, or is it more that React Nav surfaces this error in a cryptic way and Expo's fine?

**Comment by Eyesonly88** [comment]
Yes, the main issue is related to React Navigation. The error is very cryptic and hard to figure out where it's coming from and why. 
I think it would be good if Expo makes it easier to find the main issue such as showing the line of code where the JSON operation is happening in the CRNA bundle (if possible).

**Comment by quinlanj** [comment]
Hey @Eyesonly88, thanks for your feedback and posting this problem.

Regarding surfacing errors better, we track feature requests here: https://expo.canny.io/feature-requests and if you could input the request there that would be awesome. Regarding the react navigation issue, do post on their issues page as well: https://github.com/react-community/react-navigation/issues 

We are keeping our github issues related to expo bugs, so I'm going to go ahead and close the issue.
