### ISSUE TITLE
There is no way to change navBar state on Android

### ISSUE THREAD

**Issue by henrikhasell** [expo/expo#8456]
### Please note that feature requests opened in the core Expo repository will be closed.

Could you please confirm two things before closing this issue:
1. There is currently not a way of doing this.
2. You would like to see this implemented.

I believe there is not a way of changing the navigation bar state during runtime, there is a `StatusBar` component for setting the status bar modes (hidden, colour, modes) [link](https://docs.expo.io/versions/latest/react-native/statusbar/) but no equivalent for the bottom navigation bar during runtime.

NavBar state can only be set in `app.json`. It would be good to set this dynamically.

**Comment by cruzach** [comment]
you're correct, there is no way of altering the navbar configuration at runtime, it can only be set in `app.json`

If you'd like to see this implemented, I recommend opening a feature request on [our Canny](https://expo.canny.io/feature-requests), and if it gains traction then can we look into implementing this!
