### ISSUE TITLE
BarCodeScanner preview is skewed on Nexus 7

### ISSUE THREAD

**Issue by rgangopadhya** [expo/expo#846]
I believe this is because Nexus 7 display is 16:9 aspect ratio. It would be great if we had control over the ratio the same way we have in the [`Camera`](https://docs.expo.io/versions/v21.0.0/sdk/camera.html#ratio-string) component. @aalices is this something that could be done in relation to using the `Camera` component to drive `BarCodeScanner`?

**Comment by aalices** [comment]
@rgangopadhya yes, `BarCodeScanner` will use `Camera` underneath soon.

**Comment by brentvatne** [comment]
we just merged the pr to combine the two, so this will land in sdk23
