### ISSUE TITLE
setAudioModeAsync with partial options changes audio sink

### ISSUE THREAD

**Issue by vgrocha** [expo/expo#8465]
### Environment

  Expo CLI 3.13.8 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.1 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.13.8

Target: Android

### Steps to Reproduce

On Android, when using `setAudioModeAsync` with a partial set of values

```
  Audio.setAudioModeAsync({
    playsInSilentModeIOS: false
    , allowsRecordingIOS: false
  }
```

the audio is set to "in-call" and the audio goes to the internal speaker, instead of the speaker.

### Expected Behavior
Setting `playsInSilentModeIOS` and `allowsRecordingIOS` options with `setAudioModeAsync` does not change the audio sink.

### Actual Behavior
Audio sink is set to the internal speaker as opposed to staying on the speaker.

### Reproducible Demo

I put together [this sample app](https://github.com/vgrocha/ExpoAndroidInCallBug), which a bare `expo init` with a Button that `setAudioModeAsync` with the options above.

Before pressing the  `Bug It` button, when changing the volume, it correctly changes the volume:
<img src="https://user-images.githubusercontent.com/1419824/82768009-31670f80-9de9-11ea-8681-75706f5b342b.jpeg" width="50%" style="border: 1px black solid">

After pressing the `Bug It` button, when changing volume, sound becomes "In-Call" (and if you play a sound, it goes to the internal speaker):

<img src="https://user-images.githubusercontent.com/1419824/82768010-33c96980-9de9-11ea-9596-d6858da8370a.jpeg" width="50%" style="border: 1px black solid">

**Comment by vgrocha** [comment]
I had a look at [Audio.ts](https://github.com/expo/expo/blob/sdk-36/packages/expo-av/src/Audio.ts), but couldn't think of anything.

**Comment by byCedric** [comment]
Hi @vgrocha! Thanks for the issue report and the reproducible example ❤️ I think this is the issue you are facing: [on this line](https://github.com/expo/expo/blob/master/packages/expo-av/src/Audio.ts#L49), the audio is set to "playThroughEarPiece" by default. Could you try adding `playThroughEarpieceAndroid: false` to the list you pass with `setAudioModeAsync`? 

I think this should be `false` by default, our docs aren't very clear about this. For that, I'm sorry! If adding the property with `false` is working for you, we know that's the issue. After that, we can patch it 😄 

Hope it helps!

**Comment by vgrocha** [comment]
Setting `playThroughEarpieceAndroid: false` works!

re [on this line](https://github.com/expo/expo/blob/master/packages/expo-av/src/Audio.ts#L49): :facepalm: I checked the mechanism, but not the default values. 

Here's my attempt to fix this: https://github.com/expo/expo/pull/8474

**Comment by Santi970** [comment]
How to avoid that when using my application with expo the volume of another application is not lowered. This happens only on Android. Thanks!
