### ISSUE TITLE
[bare] [expo-permissions] Give a more descriptive error warning when an unrecognized permission is found

### ISSUE THREAD

**Issue by jarvisluong** [expo/expo#8466]
## 🐛 Bug Report

Running in a bare workflow app and I installed `expo-permissions` together with `expo-camera`. Trying to build an app which ask for camera permission and audio recording permission but when I call `Permission.getAsync`, I got Error: unrecognized permission: audio recording.

After a big of digging through expo's source code, I see that I need to install the package which will handle the permission stuff since each of them will call `[UMPermissionsMethodsDelegate registerRequesters: withPermissionsManager:]` in their module registry register (the similar requirement also applies in android side).

So I propose that we can improve the error message to be something like:

`Error: unrecognized permission <permission>, please install and link <the package>, see more at <the link>`

I can happily make a PR regarding this! Please give your thought!

**Comment by lukmccall** [comment]
Hi @jarvisluong, I think this a good idea. It'll be so nice if you make this PR ;) 

If you have any problems or questions, let me know. I'll try to help you.

**Comment by jarvisluong** [comment]
Right on, will make the PR soon!

**Comment by lukmccall** [comment]
> Right on, will make the PR soon!

When you're finished, add me as a reviewer ;)

**Comment by jarvisluong** [comment]
closed because #8546 is merged
