### ISSUE TITLE
Android client crashes when using toLocaleDateString()

### ISSUE THREAD

**Issue by jtryan** [expo/expo#847]
Create new app using create-react-native-app version: 1.0.0.  
Edit App.js and try to use Date().toLocaleDateString() and the expo android client crashes with "Expo has stopped" message.
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>DATE TODAY:</Text>
        <Text>{new Date().toLocaleDateString() }</Text> <-- // This will break expo on android
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Comment by brentvatne** [comment]
thanks, this is a known bug with our JSC build on Android, we are working on fixing it

**Comment by lucasapereira** [comment]
Same problem here. Does anybody have a good workaround?

**Comment by dervondenbergen** [comment]
@lucasapereira I found this interesting StackOverflow answer, which *solved* the problem for me:

https://stackoverflow.com/a/42898759/2046802

**Comment by ide** [comment]
We're going to roll back JSC in SDK 23 which will address this issue.
