### ISSUE TITLE
[expo-auth-session] only retrieving one time code

### ISSUE THREAD

**Issue by TimoGruber** [expo/expo#8473]
I am only getting the one time execution code as a response for google login.

i am using the auth session with unimodules.

this is my google auth hook (GUID is my id from the google API console):
```
export const useGoogleAuth = () => {
  const discovery = useAutoDiscovery('https://accounts.google.com');

  const redirectUri = makeRedirectUri({
    native: 'com.googleusercontent.apps.[GUID]:/oauth2redirect',
  });

  const [request, response, promptAsync] = useAuthRequest(
    {
      clientId: '[GUID].apps.googleusercontent.com',
      redirectUri,
      prompt: Prompt.SelectAccount,
      extraParams: {
        hl: 'de',
      },
      scopes: ['openid', 'profile'],
    },
    discovery,
  );
  return [request, response, promptAsync];
};
```

response:

```
state: "bcWLeo2k5p"
code: "4/0AHkNewuTkYSKFqvUmh07OFxM-t49vPILyWWDng-H8bwmC1tTJLs8LJdX5KtZ0mGbz4a5zdcqsyOpGKNaVbgby0"
scope: "profile openid https://www.googleapis.com/auth/userinfo.profile"
authuser: "0"
prompt: "consent"
```
shouldn't the code be exchanged for the Tokens ?

**Comment by EvanBacon** [comment]
You can use `responseToken: AuthSession.ResponseToken.Token` to get the token.

**Comment by TimoGruber** [comment]
Thanks for the answer. I can't find a ResponseToken prop in the documentation, so I think you mean to set this config prop:
```
responseType: AuthSession.ResponseToken.Token
```

this uses the implicit type (which I don't want to) and resolves in other parameter not allowed errors for:

```
code_challenge
code_challenge_method
```

it seems they are integrated to the uri by default and setting them to undefined or an empty string won't help.

My initial though was this library handles the authorization by receiving the one time code and exchanging this for the other tokens. (because the DiscoveryDocument has all available informations - Code uri - Token uri ... etc.)

My current workaround is to exchange the one time code for the tokens by a custom fetch function, which seems kind of a hacky solution because the auth-session should reduce the boilerplate for this kind of login and handle those get and post request in its own manner ?

**Comment by ricardonava** [comment]
Why was this closed?

**Comment by raarts** [comment]
I think using `ResponseToken.Token` initiates the implicit flow, which is not a recommended flow in the RFC.

**Comment by ricardonava** [comment]
> I think using `ResponseToken.Token` initiates the implicit flow, which is not a recommended flow in the RFC.

I guess the issue is not solved right?
this should be opened again?

**Comment by sebastienlabine** [comment]
There's this issue https://github.com/expo/expo/issues/8300 that's open
