### ISSUE TITLE
DocumentPicker.getDocumentAsync does not resolve canceled picks on web

### ISSUE THREAD

**Issue by rprestezog** [expo/expo#8477]
### Environment
  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.19.2

I'm targeting ios, android, and web, but this bug is reproducible on web (Chrome and FireFox)

### Steps to Reproduce

Click on a button which causes an await on DocumentPicker.getDocumentAsync().

A file browser dialog box appears with Cancel and Open buttons.

Click on the Cancel button.

### Expected Behavior

I expected the dialog box to go away and the promise to resolve with a value { type: 'cancel' }

### Actual Behavior

The dialog box went away but the promise remained unresolved 

### Reproducible Demo

https://snack.expo.io/0aosTDDxT

**Comment by byCedric** [comment]
Hi @rprestezog! Thanks for the issue report and example. I can confirm the cancel isn't fired. Unfortunately, I don't think the "cancel event" is exposed in the web API. We might be able to simulate something similar with e.g. `onBlur` or on document focus. Do you know a proper way to determine if the file dialog was canceled? (cc @EvanBacon)

**Comment by rprestezog** [comment]
Thanks for looking into it @byCedric !  I've seen some StackOverflow suggestions regarding focus and blur, but they seem tricky to add to the SDK in a good way.

Here's a jsfiddle I threw together to look at the event timings:
http://jsfiddle.net/qobaz5hy/6/

On Chrome, we do get a blur while browsing and a focus on cancel.  The tricky part is that on non-cancel actions, the window gets focus back **before** the input change event happens, so you'd have a race condition to deal with.

On FireFox, I'm not seeing any blur or focus during the browsing. Perhaps there's a way to force the blur while you're adding the input element?

Another deadend idea I had was to set an initial file list value so that it would get changed on cancel to an empty list.  Chrome empties the list (and fires a change event) on cancel but Firefox leaves it intact and does nothing.  Also, setting the list with fake data is a non-standard thing to do. I found the answer to this question educational:
https://stackoverflow.com/questions/47515232/how-to-set-file-input-value-when-dropping-file-on-page

I've redesigned my app to work around this, but thanks for looking into this!

**Comment by AlastairTaft** [comment]
I just ran into this issue too, given it doesn't look like there's a good solution on the web I will do the same as above and redesign my app to workaround the problem.

**Comment by sebastam97** [comment]
estoy igual

**Comment by ocho-cesar** [comment]
This issue is still occurring.
