### ISSUE TITLE
Expo(bare workflow) with Expo-updates cannot be built manually in Xcode

### ISSUE THREAD

**Issue by OscarYuen** [expo/expo#8488]
### Environment

Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.7.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      expo-updates: ~0.2.0 => 0.2.5 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.9

### Steps to Reproduce

1. Start with bare-minimum template
2. Run npm install and npm start on the root folder path in terminal
2. Open the ios xcode project file with Xcode 11 and build the code and run it on simulator.

### Expected Behavior

Should behave like running command 'npx react-native run-ios'

### Actual Behavior

the following error shows in Xcode buildtime error message

```
+ DEST=/Users/XXXXXX/Library/Developer/Xcode/DerivedData/ABC/Build/Products/Debug-iphonesimulator/ABC.app
+ [[ Debug = *Debug* ]]
+ [[ ! iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ [[ iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ echo 'Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.'
Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.
+ exit 0
../node_modules/expo-updates/scripts/create-manifest-ios.sh: line 9: node: command not found

```

But when use back 'npx react-native run-ios' command, it could build the app and run on the simulator.

### Reproducible Demo

No demo is available as it doesn't involve any code change on it.

**Comment by brentvatne** [comment]
does `node_modules/expo-updates/scripts/create-manifest-ios.sh` exist in your project?

**Comment by pweisensee** [comment]
@brentvatne @OscarYuen  I just fixed the same error in my project while upgrading an existing Expo project and ejecting it. 

It is actually coming from Node.js not being accessible in the command line for Xcode. Notice the part of the error `/create-manifest-ios.sh: line 9`. You can tell its getting all the way to line 9 in the `.sh` file, but then it throws this error.

I fixed this by linking my nvm  Node version using a symlink. Try running `ln -s $(which node) /usr/local/bin/node` from your normal dev terminal window (the one that has `node --version` working correctly). I found this fix here: [realm-js](https://github.com/realm/realm-js/issues/1448)

Hope this helps.

**Comment by OscarYuen** [comment]
> does `node_modules/expo-updates/scripts/create-manifest-ios.sh` exist in your project?

yes, it exists.
I also can execute node -v in my terminal.

**Comment by pweisensee** [comment]
Yes, it will appear that you have `node` in your terminal. I also had `node` installed in my terminal. The problem is that shell is different in Xcode making the `PATH` variables and order different. See [https://github.com/realm/realm-js/issues/1448](https://github.com/realm/realm-js/issues/1448)

As a workaround, you can symlink your current `node` installation over to the shell Xcode uses by running `ln -s $(which node) /usr/local/bin/node` in a terminal window.

Or you can follow the link above and try to install node some other way in the Xcode shell. Or maybe there is a fix possible in the `PATH` variables.

**Comment by esamelson** [comment]
@OscarYuen you should also be able to provide a direct path to your node binary by modifying the NODE_BINARY export in the "Bundle React Native code and images" Xcode build phase.

We'll work on providing a better error message here. Sorry it's been causing you trouble 😞
