### ISSUE TITLE
expo-updates not working on bare

### ISSUE THREAD

**Issue by nebmesemaou** [expo/expo#8497]
### Environment

  Expo CLI 3.21.1 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\cagri\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7

also my package.json dependensies are 

>     "expo": "~37.0.3",
>     "expo-splash-screen": "^0.2.3",
>     "expo-updates": "~0.2.0",
>     "react": "~16.9.0",
>     "react-dom": "~16.9.0",
>     "react-native": "~0.61.5",
>     "react-native-gesture-handler": "~1.6.0",
>     "react-native-reanimated": "~1.7.0",
>     "react-native-screens": "~2.2.0",
>     "react-native-unimodules": "~0.9.0",
>     "react-native-web": "~0.11.7",
>     "react-native-device-info": "5.5.8"

app target = android

### Steps to Reproduce
```
expo init --template bare-minimum ExpoRNRelease
cd ExpoRNRelease
npm install
expo export --public-url https://xxx.fra1.digitaloceanspaces.com/expo (for app v1.0.0)
react-native run-android --variant=release
expo export --public-url https://xxx.fra1.digitaloceanspaces.com/expo (for app v1.0.1)
```
i just couldnt update app bundle to v1.0.1 (even auto update)
app has loaded "with no update" v1.0.0

when i run  `Updates.reloadAsync()` its reloading v1.0.0 again
when i run  `Updates.checkForUpdateAsync()` it freeze on default splash screen
when i run "https://xxx.fra1.digitaloceanspaces.com/expo/android-index.json" it online and public

my manifest config for expo-updates is

```
    <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://xxx.fra1.digitaloceanspaces.com/expo/android-index.json"/>
    <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="37.0.0"/>  
    <meta-data android:name="expo.modules.updates.EXPO_RUNTIME_VERSION" android:value="37.0.0"/> 
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="10000"/>
```

why expo export | expo publish not updating theese meta tags on AndroidManifest.xml
```
    <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="YOUR-APP-URL-HERE"/>
    <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="YOUR-APP-SDK-VERSION-HERE"/>
```

### Expected Behavior

expo-updates loads new version of app

### Actual Behavior
app is not up to date

**Comment by jonathanstiansen** [comment]
your expo_update_url and sdk_version isn't filled in. That's the placeholder value.

**Comment by nebmesemaou** [comment]
> your expo_update_url and sdk_version isn't filled in. That's the placeholder value.

here is my manifest config as i said. Pls read careful before comment

`
<meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://xxx.fra1.digitaloceanspaces.com/expo/android-index.json"/>
    <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="37.0.0"/>  
    <meta-data android:name="expo.modules.updates.EXPO_RUNTIME_VERSION" android:value="37.0.0"/> 
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="10000"/>
`

**Comment by esamelson** [comment]
hey there @nebmesemaou -- sorry you're having trouble with this! Unfortunately, I'm not able to reproduce this issue by taking the following steps:
- expo init --template bare-minimum ExpoRNRelease
- cd ExpoRNRelease
- expo export --public-url https://esamelson.github.io/self-hosting-test, upload
- change config in AndroidManifest.xml to match yours
- react-native run-android --variant Release
- change App.js & rerun expo export, upload
- close and relaunch app

I am able to successfully get the update with no issues by following these steps.

However, when I visit the URL you provided (https://xxx.fra1.digitaloceanspaces.com/expo/android-index.json) I do not see a valid manifest json file but rather an HTML error page. Please ensure your files are hosted correctly and your Android device is able to access them.

If the issue persists, please let me know where your steps differ from mine above, and provide clear, complete instructions we can follow to easily reproduce the issue on our end. Thank you!!

**Comment by nebmesemaou** [comment]
> However, when I visit the URL you provided (https://xxx.fra1.digitaloceanspaces.com/expo/android-index.json) I do not see a valid manifest json file but rather an HTML error page. Please ensure your files are hosted correctly and your Android device is able to access them.

i hide the url.


like i said on issue 
> when i run "https://xxx.fra1.digitaloceanspaces.com/expo/android-index.json" it online and public



have you try installing `react-native-device-info` ?

could be about native module ?

**Comment by esamelson** [comment]
Hi there -- in order for us to help we need clear, complete instructions that we can use to reliably reproduce and debug the issue. Please follow [this guide](https://stackoverflow.com/help/minimal-reproducible-example) to create a minimal, reproducible example. It's very hard and time-consuming for us to help out without this. And it's possible that in the process of following that guide, you can figure out the cause of the issue yourself! Thanks 🙂

**Comment by nebmesemaou** [comment]
thx @esamelson 

i will create the example :)

**Comment by Fatima-Naseer** [comment]
I'm having problem running expo-updates on Bare workflow. I have done all the necessary configurations required that includes unimodules and expo-updates. Anyone please share an example with issue solved.
