### ISSUE TITLE
Add option to ignore certain paths in the bundle .expignore

### ISSUE THREAD

**Issue by sonaye** [expo/expo#85]
Being able to specify some folders/files to be ignored by the packager would be a nice feature to have. I am talking specifically about the step when we execute `exp publish` or `exp build`, some files are just not needed in the bundle and shouldn't be uploaded.

### What are we gaining?
- Smaller bundle sizes, hence faster app loading times.
- We as developers won't need to have two dedicated directories, one for dev and another for production.

### The how
- Through `exp.json`, we can feed an array of the ignored paths (masking should be supported).
- Introduce `.expignore`

**Comment by jesseruder** [comment]
You can use a file called rn-cli.config.js to configure this. It's supported by raw React Native but unfortunately there aren't great docs for it. There's an example here for how to blacklist certain directories: https://github.com/facebook/react-native/issues/7271

**Comment by sonaye** [comment]
@jesseruder can I pass `--config=rn-cli.config.js` to `exp start`?

**Comment by jesseruder** [comment]
You can add a `rnCliPath` field to exp.json that gives the relative path to rn-cli.config.js

**Comment by sonaye** [comment]
I added `rnCliPath: "./rn-cli.config.js",` to `exp.json` and created `rn-cli.config.js` with

```javascript
import blacklist from 'react-native/packager/blacklist';

export default {
  getBlacklistRE: () => blacklist([
    /assets\/raw\/.*/,
    /crashlytics\/.*/,
    /firebase\/.*/,
    /website\/.*/
  ])
};
```

Not sure if I should also include `rn-cli.config.js` itself in the list and how its regex would be.

I will push the project now, maybe you could check @jesseruder to see if this actually works?

**Comment by sonaye** [comment]
The packager doesn't like es6 imports/exports, switched to `const blacklist = require('react-native/packager/blacklist');` and `module.exports = {`.

The packager is stuck now with `exp start`, the message `[exp] Starting React Native packager...` is displayed indefinitely, usually at this step we would get a link to the project, etc, am I doing something wrong?

**Comment by sonaye** [comment]
any help with this @jesseruder?

**Comment by jesseruder** [comment]
Hm ok. You'll need to reset the packager cache any time you change the rn-cli.config. After you've done that I'd recommend putting `console.log`s into that file and make sure it's getting called. Unfortunately this isn't a well supported feature so you might have to dive into the React Native source to figure out what's going wrong.

**Comment by sonaye** [comment]
`npm start -- --reset-cache`?

**Comment by jesseruder** [comment]
You can use `exp start --help` to see the options.

`-c, --clear            Clear the React Native packager cache`

**Comment by sonaye** [comment]
never mind, found it `exp start --clear`, i'll give it a shot

**Comment by sonaye** [comment]
do you have access to published expo project files? can you check if the items listed are ignored? I can provide you with the name of the project

**Comment by sonaye** [comment]
I've refactored `rn-cli.config.js` to
```javascript
const blacklist = require('react-native/packager/blacklist');

const config = {
  getBlacklistRE() {
    // prettier-ignore
    return blacklist([
      /assets\/raw\/.*/,
      /crashlytics\/.*/,
      /firebase\/.*/,
      /website\/.*/
    ]);
  }
};

module.exports = config;
```

should I add `rn-cli.config.js` to this list? and if so, what would the regex look like, what would the regex for a file and not a directory look like?

**Comment by jesseruder** [comment]
To see a bundle go to https://exp.host/@USER_NAME/EXPERIENCE_SLUG/index.exp?sdkVersion=15.0.0 and then open the bundle url there.

I don't think you need to add rn-cli.config to that list.

**Comment by sonaye** [comment]
@jesseruder Can the bundle tell me anything about weather certain directories with assets in them have been uploaded to your servers?

**Comment by sonaye** [comment]
As answered by @brentvatne

> We don't have any directories on our servers, we just have your minified JS bundle. Assets (.ttf, .otf, .png, .json for Lottie, etc) those go on S3, "only" the ones that you `require` in your project, if you require them, they are on S3, if you don't, they are not. If you don't want some asset to go up to S3 you can upload it to your own URL and refer to it by `uri` rather than `require`, nobody will ever be able to just stumble upon your asset btw.

**What about offline apps, can we build a pure offline app with Expo?**

> Sure you can, but you need to cache the assets you need for offline on first load, presumably when someone downloads and opens your app they have an internet connection, so the first time they do that you cache everything. See [Preloading & Caching Assets](https://docs.expo.io/versions/v15.0.0/guides/preloading-and-caching-assets.html).

Hence, there is no need for `rn-cli.config.js` at all with Expo.
