### ISSUE TITLE
Set status bar icon

### ISSUE THREAD

**Issue by James2516** [expo/expo#850]
https://i.imgur.com/VguekgR.png
Is there a way to change this status bar icon shown on Android (for local notifications)?

**Comment by brentvatne** [comment]
expo.notifications.icon

https://docs.expo.io/versions/latest/guides/configuration.html#notification

**Comment by James2516** [comment]
That's for remote push notifications. It doesn't appear to have any effect on local notifications.
https://docs.expo.io/versions/latest/sdk/notifications.html#local-notifications

**Comment by alanlanglois** [comment]
@james2516 did you find a solution?

**Comment by ShubhamOrbio** [comment]
I am still facing the same issue. Also, as of today the above urls are not working.

**Comment by gustavograupner** [comment]
Here @ShubhamOrbio 

https://docs.expo.io/versions/latest/workflow/configuration/#notification

**Comment by ShubhamOrbio** [comment]
@gustavograupner 
Thank you for the help. I wrote something like this in my app.json and it works like a charm.

> "notification": {
>       "icon": "https://res.cloudinary.com/shubhambhattacharya/image/upload/v1556269434/icon.png",
>       "color": "#800000",
>       "androidMode": "default",
>       "androidCollapsedTitle": "My Title"
>  }
