### ISSUE TITLE
[expo-web-browser] Example snack broken on the Web platform

### ISSUE THREAD

**Issue by LinusU** [expo/expo#8511]
### Environment

Latest snack.io

### Steps to Reproduce

https://snack.expo.io/?platform=web&name=Basic%20WebBrowser%20usage&sdkVersion=37.0.0&dependencies=expo-web-browser&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv37.0.0%2Fweb-browser.js

### Expected Behavior

I wanted to see how the web browser module worked on the web platform.

### Actual Behavior

I got this error:

<img width="321" alt="Screenshot 2020-05-27 at 14 37 53" src="https://user-images.githubusercontent.com/189580/83027129-a9bb1400-a027-11ea-89b8-e82f7791bba4.png">

### Reproducible Demo

See snack.io link above ☝️ 

-----

### Further info

It seems like fbjs is not specified as a dependency here:
https://github.com/expo/expo/blob/master/packages/expo-web-browser/package.json

But even adding fbjs manually to the list of dependencies in the Snack didn't fix the error 🤔

**Comment by byCedric** [comment]
Hi @LinusU! Thanks for the issue report! It looks like fbjs is one of those special packages that require a lot of attention, and I'm sorry that it broke. I also tested this on Android (through Snack), which seems to work. We will get to this asap! 😄

**Comment by EvanBacon** [comment]
It's fixed now on the latest version of snack
