### ISSUE TITLE
Error expo aplication LAN mode

### ISSUE THREAD

**Issue by EloFran** [expo/expo#8514]
### Steps to Reproduce

expo start and scan QR code con expo aplication

### Expected Behavior

 `Building JavaScript bundle: finished in 21845ms.` , for example and the project on my mobile with the expo application

### Actual Behavior
Since I updated new, yesterday, I get this message when use expo bar code with my phone in LAN mode. 
```
Error: Cannot find module 'C:\WINDOWS\system32\node_modules\node-sass\scripts\install.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```

### Reproducible Demo
i
`Error: ENOENT: no such file or directory, scandir 'E:\FOLDER\REACT\MIS WEBS\misWebs\assets\images'`
  What happens if you skip this step?
it run in web, but no in my mobile.

**Comment by byCedric** [comment]
It looks like you are using a package that requires `node-sass`, and something is up with that. Expo doesn't include it because it's incompatible with native code. Could you share a small repo with this issue? Without that, I'm not sure what's going on. 😄

**Comment by EvanBacon** [comment]
Removing the dependency on `node-sass` will resolve the error you've included. Metro bundler is not parsing the CSS file on native which is causing this error. On web we use Webpack which is bundling CSS as expected.
