### ISSUE TITLE
exp login fails with no feedback (-2 code) 

### ISSUE THREAD

**Issue by theronic** [expo/expo#852]
I am able to log in on the Expo website with my credentials, but when I try to log in from the CLI with `exp login`, I get two blank lines.

![image](https://user-images.githubusercontent.com/1011676/31990152-8fdbf64a-b974-11e7-84a9-f5360e53c68b.png)

**Comment by theronic** [comment]
```
exp --version
> 44.0.0
```

**Comment by brentvatne** [comment]
@theronic - can you give any info about your environment? also does this happen if you update to the latest version, 45.0.2?

**Comment by serpilacar** [comment]
i have this issue since this morning too. tried to login but it said i already logged in as `undefined`. then tried to login again and again with `exp login` but now it says `[exp] Your account has been blocked after multiple consecutive login attempts. We’ve sent you an email with instructions on how to unblock it.` but there's no mail in my box.

**Comment by fson** [comment]
There are problems with login right now, see https://forums.expo.io/t/2017-10-25-issues-with-logging-into-expo-developer-accounts/4236 for updates. Before this gets resolved, you can use `exp` without login using the `--offline` flag.

**Comment by ide** [comment]
Hi everyone - we believe the login & signup issues are fixed for nearly all developers. I'd recommend logging into the Expo website at https://expo.io/login first and once you're able to log in there, then log into XDE or exp on your computer. Please tell us if you're still having login issues. Really sorry about this incident :(

**Comment by terribleben** [comment]
Closing for now as I believe these issues are all resolved. Let us know if you still have a problem.

**Comment by amypellegrini** [comment]
Sorry, I'm having a similar issue right now:

`{ ApiV2Error: An unknown error occurred.
    at /xdl@49.0.2/src/ApiV2.js:225:19
    at Generator.throw (<anonymous>)
    at step (/Users/amypellegrini/.npm-global/lib/node_modules/exp/node_modules/xdl/build/ApiV2.js:48:191)
    at /Users/amypellegrini/.npm-global/lib/node_modules/exp/node_modules/xdl/build/ApiV2.js:48:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'INTERNAL_SERVER_ERROR',
  _isApiError: true,
  serverStack: undefined,
  details: undefined }`

I would use the expo login url, but this is my first time and I don't have a user, any ideas?

Thanks!

**Comment by EvanBacon** [comment]
@amypellegrini you can create an account through the [expo website](http://expo.io/). Also were you able to get pass this, it appears you are already developing something: https://github.com/expo/expo/issues/568#issuecomment-382423974
