### ISSUE TITLE
¿Is possible to remove the permission when opening a website and the redirection?

### ISSUE THREAD

**Issue by ARChatco** [expo/expo#8521]
Using:  const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(url, redirectUrl);

I. get, "Expo" wants permission.. I would like to remove this and not being asked

**Comment by brentvatne** [comment]
in Expo client it says "Expo" but it will say "Your App Name" when you build a standalone app.

you cannot remove this if you want to be able to access cookies in web browser, ios added this prompt for security reasons in i believe in ios 10.

**Comment by abdulrahman18** [comment]
<img width="350" alt="Screenshot 2021-04-27 at 7 03 45 PM" src="https://user-images.githubusercontent.com/31540549/116250372-4b446b80-a78b-11eb-9663-7dfff89f220b.png">
how can i change the expo.io string ?
