### ISSUE TITLE
Permissions.getAsync returns "always" for iOS scope instead of "whenInUse"

### ISSUE THREAD

**Issue by matthew-bise** [expo/expo#8523]
### Environment

Diagnostics output:
```
Expo CLI 3.21.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.21.1
```

Target: iOS

### Steps to Reproduce

1. Add `NSLocationWhenInUseUsageDescription`, `NSLocationAlwaysUsageDescription`, and `NSLocationAlwaysAndWhenInUseUsageDescription` to plist
2. Call `await Permissions.askAsync(Permissions.LOCATION);` and select "Allow while using the app"
3. Call `await Permissions.getAsync(Permissions.LOCATION);` and check the return value at `permissions.location.ios.scope`
4. Run app on iOS simulator - iPhone 11 (13.4.1)

### Expected Behavior

I would expect the value of `permissions.location.ios.scope` to be `whenInUse` since that's what I selected at the initial location prompt

### Actual Behavior

The value in `permissions.location.ios.scope` is `always`

### Reproducible Demo

https://snack.expo.io/c1sML2svi

Relevant code:
``` javascript
const requestPermissions = async () => {
  const { status } = await Permissions.askAsync(Permissions.LOCATION); // select "When in use" here
  if (status === 'granted') {
    const { permissions } = await Permissions.getAsync(Permissions.LOCATION);
    console.log(permissions.location.ios.scope); // This prints "always"
  }
};
```

**Comment by justinchan23** [comment]
im seeing this bug as well

**Comment by mohanees** [comment]
Hi, any updates on this we're still experiencing this issue.

**Comment by alexgyllos** [comment]
We are also dealing with this issue. Any updates?

**Comment by elly0t** [comment]
Same issue, need a patch asap on this
