### ISSUE TITLE
expo-linear-gradient and jest-expo: Cannot read property 'viewManagersNames' of undefined

### ISSUE THREAD

**Issue by chanonroy** [expo/expo#8527]
### Environment

```
Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
```

### Steps to Reproduce

1. Create a component using the `LinearGradient` from expo using the `index.native.tsx` naming scheme.
2. Write a jest test using [@testing-library/react-native](https://github.com/testing-library/native-testing-library)
3. Run `yarn test` and see a type error being thrown with console warnings about `The "UMNativeModulesProxy" native module is not exported through NativeModules`

### Expected Behavior

Component should render in the jest testing environment and we should be able to run assertions.

### Actual Behavior

Throws a type error on this line [here](https://github.com/expo/expo/blob/master/packages/@unimodules/react-native-adapter/src/NativeViewManagerAdapter.tsx#L30)

```
TypeError: Cannot read property 'viewManagersNames' of undefined

      at requireNativeViewManager (node_modules/@unimodules/react-native-adapter/src/NativeViewManagerAdapter.tsx:26:31)
      at Object.<anonymous> (node_modules/expo-linear-gradient/src/NativeLinearGradient.ios.tsx:20:34)
      at Object.<anonymous> (node_modules/expo-linear-gradient/src/LinearGradient.tsx:5:1)
```

On a side note, we also end up seeing this error message:
```
console.warn
    The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly
```

### Reproducible Demo

I made a repo with a reproducible demo [here](https://github.com/chanonroy/expo-linear-gradient-issue)

Simply run `yarn` and then `yarn test` to run jest. 

You will end up seeing this:

<img width="1153" alt="Screenshot 2020-05-28 at 12 20 47 am" src="https://user-images.githubusercontent.com/16366896/83081670-1c081480-a079-11ea-94cf-4daebf998d10.png">

**Comment by fernandobecker** [comment]
I have a problem similar to the linear-gradient expo
`({"Object. <anonymous>": function (module, exports, require, __ dirname, __ filename, global, jest) {export {default as LinearGradient} from './LinearGradient';
                                                                                              ^^^^^^
     SyntaxError: Unexpected token export

       4 | import PropTypes from 'prop-types';
       5 |
     > 6 | import {LinearGradient} from 'expo-linear-gradient';
         | ^
       7 | import moment from 'moment';
       8 | import {DEFAULT_ELEVATION} from '../Utils/Constants';
       9 |`

**Comment by chanonroy** [comment]
Update: I found the fix. 

The issue was that I was using `testing-library/react-native` and was not adding `jest-expo` to my jest config.

Adding this to my `jest.config.js` managed to resolve it:
```
require('jest-expo/jest-preset');
```

**Comment by byCedric** [comment]
Hi @chanonroy! Sorry for the delay. Awesome, glad you figured it out! It is easy to overlook the jest configuration, maybe we should add a bit more documentation on how to use `testing-library` with Expo since it's quite a popular library (I also use it 😄). I'll add the docs label and consider the original issue solved.

Thanks for the comment with your fix!

**Comment by chanonroy** [comment]
@byCedric - not a problem! 😄 Thanks for circling back.
Yeah, it would be wonderful to have more documentation on using the `jest-expo` and `@testing-library/react-native` presets together. 

I imagine it will be a common use case for people to want to use the universal testing of jest-expo with the capabilities of testing-library.

Anyways - thanks again !

**Comment by enesozturk** [comment]
Still having the issue, I saw a. update in [SDK 36](https://github.com/expo/expo/commit/87464e2fc6614e3f2a786868537f056f6b11f899) but cannot sure if it is related with it, maybe it needs an update?

### Versions
```json
"expo": "44.0.1",
"jest-expo": "^44.0.1",
```
