### ISSUE TITLE
[LocalAuthentication] Must have com.samsung.android.bio.face.permission.USE_FACE

### ISSUE THREAD

**Issue by Bardiamist** [expo/expo#8530]
## 🐛 Bug Report

Users who preferred `Face recognition` in system `Settings` -> `Biometrics and security` ->`Biometric preferences` -> `Preferred biometric` can't use `LocalAuthentication.authenticateAsync`.

### Environment

  Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.3.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      react: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
    npmGlobalPackages:
      expo-cli: 3.21.3

Android

### Steps to Reproduce

On Samsung Galaxy S8 with Android 9:
1. Enable `Face recognition` in `Settings` -> `Biometrics and security` ->`Biometric preferences` -> `Preferred biometric`
2. Try to call `LocalAuthentication.authenticateAsync`

### Expected Behavior

Fallback to fingerprint

### Actual Behavior

`Must have com.samsung.android.bio.face.permission.USE_FACE or android.permission.USE_BIOMETRIC permission.` error

### Reproducible Demo

https://snack.expo.io/@bardiamist/localauthentication

**Comment by byCedric** [comment]
Hi @Bardiamist! Thanks for reporting this, I see we are currently asking for the `USE_FINGERPRINT` permission. Which is deprecated and not enough for the new BiometricPrompt. We will get this fixed asap!

**Comment by Bardiamist** [comment]
Not fixed. New issue created #8530
