### ISSUE TITLE
Video consistently freezes

### ISSUE THREAD

**Issue by lachlanglen** [expo/expo#8538]
## 🐛 Bug Report

**Video freezes consistently on first playback on iOS in conjunction with `Camera.recordAsync()`, without any corresponding update to the video ref's PlaybackObject.**

### Environment

```
Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.8 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.12.2 => 0.12.2 
```

This bug occurs on Expo Client for iOS and in published iOS app (expo-managed). It does NOT occur on Android.

### Steps to Reproduce

Create a new Expo project (I used the tabs template), add the following in `App.js` and `/Components/RecordVideoModal.js`:

```
// App.js:

import * as React from 'react';
import { Text, View, StyleSheet, Button } from 'react-native';
import Constants from 'expo-constants';

import RecordVideoModal from './components/RecordVideoModal';

export default function App() {
  const [showModal, setShowModal] = React.useState(false);

  return (
    <View style={styles.container}>
      {
        !showModal ? (
          <Button
          onPress={() => setShowModal(true)}
          title="Show recording modal"/>
        ) : (
          <RecordVideoModal
          showModal={showModal}
          setShowModal={setShowModal} />
        )
      }
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});
```
```
// /components/RecordVideoModal.js:

import React, { useState, useEffect } from 'react';
import { View, Modal, StyleSheet, TouchableOpacity, Text, Dimensions } from 'react-native';
import { Video } from 'expo-av';
import { Camera } from 'expo-camera';
import * as Permissions from 'expo-permissions';
import * as FileSystem from 'expo-file-system';

const videoUrl = 'https://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_480_1_5MG.mp4'

const RecordVideoModal = (props) => {

  let screenWidth = Math.floor(Dimensions.get('window').width);
  let screenHeight = Math.floor(Dimensions.get('window').height);

  const { showModal, setShowModal } = props;

  const [recording, setRecording] = useState(false);
  const [cameraRef, setCameraRef] = useState(null);
  const [localFileUri, setLocalFileUri] = useState('');
  const [recordedUri, setRecordedUri] = useState('');
  const [vidRef, setVidRef] = useState(null);
  const [vidLoaded, setVidLoaded] = useState(false);
  const [vidDoneBuffering, setVidDoneBuffering] = useState(false);
  const [permissionGranted, setPermissionGranted] = useState(false);

  useEffect(() => { 
  const checkPermissions = async () => {
    const permissions = await Permissions.getAsync(Permissions.CAMERA);
    if (!permissions.granted) {
      const perms = await Permissions.askAsync(Permissions.CAMERA);
      if (perms.granted) setPermissionGranted(true);
    } else {
      setPermissionGranted(true);
    }
  }

  const downloadVideoLocally = async () => {
    const { uri } = await FileSystem.downloadAsync(
      videoUrl,
      FileSystem.documentDirectory + 'test.mov'
    )
    setLocalFileUri(uri);
  }
    checkPermissions();
    downloadVideoLocally();
  }, []);

  const toggleRecord = async () => {
    if (recording) {
      setRecording(false);
      cameraRef.stopRecording();
      vidRef.stopAsync();
    } else {
      try {
        setRecording(true);
        await vidRef.playAsync();
        const vid = await cameraRef.recordAsync();
        setRecordedUri(vid.uri);
      } catch (e) {
        console.log('error recording: ', e)
      }
    }
  }

  const handleCancel = async () => {
    try {
      await FileSystem.deleteAsync(localFileUri);
      await vidRef.unloadAsync();
      setShowModal(false);
    } catch (e) {
      console.log('error in handleCancel: ', e)
      setShowModal(false);
    }
  }

  const handlePlaybackStatusUpdate = (updateObj) => {
    if (updateObj.isLoaded !== vidLoaded) setVidLoaded(updateObj.isLoaded);
    if (!vidDoneBuffering && !updateObj.isBuffering) setVidDoneBuffering(true);
  }

  const handleRefresh = async () => {
    await vidRef.stopAsync();
    cameraRef.stopRecording();
    setRecording(false);
  }

  return (
    <Modal
      supportedOrientations={['portrait']}
    >
      <View style={{
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'black',
        paddingVertical: (screenHeight - screenWidth / 8 * 9) / 2,
        height: '100%'
      }}>
        <View style={{ flexDirection: 'row' }}>
          <Video
            ref={ref => setVidRef(ref)}
            source={{ uri: localFileUri }}
            rate={1.0}
            volume={1.0}
            isMuted={false}
            resizeMode="cover"
            positionMillis={0}
            progressUpdateIntervalMillis={50}
            onPlaybackStatusUpdate={update => handlePlaybackStatusUpdate(update)}
            style={{
              width: screenWidth / 2,
              height: screenWidth / 16 * 9,
            }}
          />
          <Camera
            style={{
              width: screenWidth / 2,
              height: screenWidth / 16 * 9,
            }}
            type={Camera.Constants.Type.front}
            ref={ref => setCameraRef(ref)}>
            <View>
              <TouchableOpacity
                onPress={!recording ? handleCancel : () => { }}
              >
                <Text style={{
                  color: 'red',
                  fontSize: screenWidth / 22,
                  paddingLeft: 20,
                  paddingTop: 20,
                  fontWeight: 'normal',
                }}
                >
                  {recording ? 'Recording' : 'Cancel'}
                </Text>
              </TouchableOpacity>
            </View>
            {
              vidLoaded && vidDoneBuffering &&
              <View
                style={{
                  flex: 1,
                  backgroundColor: 'transparent',
                  flexDirection: 'row',
                  justifyContent: 'center',
                }}>
                <TouchableOpacity
                  onPress={toggleRecord}
                  style={{
                    borderWidth: screenWidth / 100,
                    borderColor: recording ? 'darkred' : 'darkred',
                    alignSelf: 'flex-end',
                    width: screenWidth / 10,
                    height: screenWidth / 10,
                    backgroundColor: recording ? 'black' : 'red',
                    borderRadius: 50,
                    margin: 10,
                  }}
                />
              </View>
            }
          </Camera>
        </View>
          <TouchableOpacity
            onPress={handleRefresh}
          >
            <Text
            style={{
              color: 'red',
              marginTop: 20,
            }}>Having a problem? Touch here to try again.
            </Text>
          </TouchableOpacity>
      </View>
    </Modal >
  )
}

export default RecordVideoModal;
```
...or just check out [this snack.](https://snack.expo.io/@lachlanglen/playback-&-record)

### Expected Behavior

This is an app to record split-screen videos. In order to facilitate this, `playAsync()` is called on the video ref immediately before `recordAsync()` is called on the camera ref.

I expected the video to continue playing without freezing when `playAsync()` is called. This is what happens on Android, and on subsequent attempts on iOS (after `handleRefresh()` is called).

### Actual Behavior

Video freezes approx. 500ms after starting to play. I am certain it has something to do with the first call of `recordAsync()`. Importantly, **there is no update to the video's PlaybackObject indicating that it has frozen or that anything has changed.**

If user selects "Having a problem? Touch here to try again" which triggers `handleRefresh()` function (stopping `videoRef` and `cameraRef` from playing and recording, respectively), this bug does not occur on subsequent record attempts.

Again, this bug **does not** occur on Android.

### Reproducible Demo

Here is a [snack.](https://snack.expo.io/@lachlanglen/playback-&-record)

**Comment by lachlanglen** [comment]
Any thoughts on this? I'm planning to eject from Expo in a few days to implement In-App-Purchases so if there's a fix I can make in the native code, or something specific I should look for, I'd be very glad to know about it!

**Comment by wanderingbort** [comment]
Had a similar issue in an app that was also using `video.playAsync` and `camera.recordAsync` in the same component.

by imposing a delay between `camera.recordAsync` and `video.playAsync` I got the issue of video freezing to change into the camera throwing a error.   

This also made the following appear in the device's system logs:

```
Jul  4 17:14:11 mediaserverd(libEmbeddedSystemAUs.dylib)[27542] <Error>: AURemoteIO.cpp:1086:Initialize: failed: -10851 (enable 1, outf< 2 ch, 0 Hz, Float32, non-inter> inf< 1 ch,  44100 Hz, Int16>)
Jul  4 17:14:11 mediaserverd(Celestial)[27542] <Notice>: <<<< BWGraph >>>> -[BWGraph start:]_block_invoke: <0x104e2f2d0> error -10851 starting source node <0x10db93ff0, AudioDevice, (null)>
Jul  4 17:14:11 mediaserverd(Celestial)[27542] <Notice>: <<<< FigCaptureSession >>>> -[BWFigCaptureSession graph:didFinishStartingWithError:]: <0x104fa84a0> PID 46506: failed to start graph <0x104e2f2d0> due to err: -10851 , stopping session.
```

Internet suggests that error code is [kAudioUnitErr_InvalidPropertyValue](https://www.osstatus.com/search/results?platform=all&framework=all&search=-10851)

Armed with that information, I set the camera to only record video (`muted:true`) and magically it worked with and without the artificial delay from above. 

At the very least that should help narrow the search space.

**Comment by lachlanglen** [comment]
Awesome, thanks for the reply @wanderingbort! I have discovered that this error only occurs on iPhone, not on iPad or Android. I might try to get into the Objective-C and figure out what is going on...

**Comment by IjzerenHein** [comment]
I've been debugging this problem and it appears to be related to the Audio-session. When the Camera starts recording (non-muted), it adds an input to AVAudioSession which in turn causes the Video playback to pause.

I found that setting the audio-mode using `Audio.setAudioModeAsync` fixes the problem:

```js
const toggleRecord = async () => {
    if (recording) {
      setRecording(false);
      cameraRef.stopRecording();
    } else {
      try {
        setRecording(true);
        console.log('Setting audio modes');
        await Audio.setAudioModeAsync({
          allowsRecordingIOS: true,
          playsInSilentModeIOS: true,
        });
        console.log('playAsync');
        await vidRef.playAsync();
        console.log('recordAsync');
        const vid = await cameraRef.recordAsync();
        setDuetteUri(vid.uri);
      } catch (e) {
        console.log('error recording: ', e)
      }
    }
  }
```

I'm not quite sure why this is the case, and also why it would only appear on iPhone and not iPad. This might be a quirk or something deliberate in iOS (to prevent recoding audio from the speakers?), or perhaps there is something wrong with the  audio mixing.

@lachlanglen What is your goal towards playing/recording audio in this case? Do you want both the camera to record audio and the video to play audio, or just one of the two. Doing both at the same time would create a feedback loop where the microphone would record the audio-output of the video. If for instance the video has no audio, I would mute it and that might resolve this issue as well.

**Comment by lachlanglen** [comment]
Hi @IjzerenHein - firstly, THANK YOU so much for figuring this out! I added the Audio mode settings and it no longer freezes. I'm so grateful for your time and help!

The use case is recording split-screen videos, and users are required to use headphones to avoid the feedback loop you're referring to.

By the way, while you're here and since it's related... do you know if there's any way to use ExoPlayer instead of MediaPlayer on Android, so that seek parameters (specifically tolerance, which is integral to this app) can be set? I posted about it [here](https://forums.expo.io/t/how-to-add-seektolerencemillis-to-av-playback-object-on-android/40534). I'd love to avoid writing a native Java module but will do it if I have to, as this is the only thing holding me back from submitting it to Google Play.

**Comment by IjzerenHein** [comment]
Glad that helped @lachlanglen !

As far as I'm aware `expo-av` uses ExoPlayer by default on Android. You can switch it to MediaPlayer using the `androidImplementation` field. https://docs.expo.io/versions/latest/sdk/av/

> androidImplementation : underlying implementation to use (when set to MediaPlayer it uses Android's MediaPlayer, uses ExoPlayer otherwise). You may need to use this property if you're trying to play an item unsupported by ExoPlayer (formats supported by ExoPlayer, formats supported by Android's MediaPlayer). Note that setting this property takes effect only when the AV object is just being created (toggling its value later will do nothing). [Android only]

**Comment by IjzerenHein** [comment]
@lachlanglen Can this issue be closed?

**Comment by lachlanglen** [comment]
Thanks @IjzerenHein. Yep, closing it now.

**Comment by IjzerenHein** [comment]
Awesome, thanks!

**Comment by agconti** [comment]
@IjzerenHein thanks for solving this! 💖 

Where does the `Audio` import come from in your example? 

```js
 await Audio.setAudioModeAsync({
          allowsRecordingIOS: true,
          playsInSilentModeIOS: true,
        });
```

**Comment by IjzerenHein** [comment]
@agconti  Yes from `expo-av`

https://docs.expo.io/versions/latest/sdk/audio/
