### ISSUE TITLE
 Error: `fsevents` unavailable (this watcher can only be used on Darwin)

### ISSUE THREAD

**Issue by hazephase** [expo/expo#854]
Error: `fsevents` unavailable (this watcher can only be used on Darwin) 

why do I keep getting this error ?

**Comment by brentvatne** [comment]
hello! sorry i cannot help with this, i hope you can appreciate that there is little to no useful information in your issue that would help us with debugging the problem.

to learn more about how to get help on open source projects, please read this post: https://www.snoyman.com/blog/2017/10/manipulating-maintainers

after reading that, feel free to re-create an issue with more information! :) hope we can help you!

**Comment by Meekohi** [comment]
I also get
`Error: `fsevents` unavailable (this watcher can only be used on Darwin)` on a fresh install using

```
create-react-native-app myNativeApp
cd myNativeApp
npm install react-native-camera --save
npm install -g watchman
npm start
```
then trying to open the app in Expo XDE. Possibly related to https://forums.expo.io/t/error-fsevents-unavailable-this-watcher-can-only-be-used-on-darwin/3416, I'm using `n` to manage node versions, since seemingly `npm5` still isn't supported.
```
node v6.12.0
npm 3.10.10
```

**Comment by jihgao** [comment]
@Meekohi thanks, i fixed the problem according to your solution.

**Comment by kmw0710** [comment]
Omg Thanks @Meekohi ..
I had really bad time during this problem, and could not solve this for a few weeks. 
and It works!!!
Thansk!!

**Comment by Dewscntd** [comment]
@Meekohi thanx! helped me too!

**Comment by Meekohi** [comment]
You all are making me feel better, I thought I was the only one who screwed this up ;)

**Comment by Meekohi** [comment]
Maybe leave a comment there to the same effect if you want to help avoid this in the future: https://github.com/dfjones/watchman/issues

**Comment by turquoisemelon** [comment]
Thanks so much @Meekohi ! Fixed my problem, too!

**Comment by Meekohi** [comment]
Update: The owner of the npm package agreed to delist it since it isn't being maintained anymore. Hopefully that will avoid any confusion in the future :)

**Comment by XeeshanAnsari** [comment]
Thanks @Meekohi

**Comment by devworkpro** [comment]
Awesome @Meekohi .
Thanks :-)

**Comment by Anchises68** [comment]
Thank you @Meekohi

**Comment by qq897425998** [comment]
thank @Meekohi

**Comment by y-i-gmo** [comment]
Thank you @Meekohi

**Comment by bonlemuel** [comment]
Thank you, Bro @Meekohi

**Comment by Liceth** [comment]
Thank you so much yeihh @Meekohi

**Comment by nishantmehta2010** [comment]
Thanks for your help

**Comment by n-cong** [comment]
Thanks @Meekohi

**Comment by 303540023** [comment]
@Meekohi thanks, i fixed the problem according to your solution.

**Comment by makkabi** [comment]
Just installing fsevents worked for me, although I had the same issue in a totally different project and just got here via searching for the error: npm install fsevents

**Comment by Sungmiii** [comment]
Thank you! it's fixed my problem quickly 😄 @Meekohi

**Comment by lhy-luan** [comment]
it's work for me
sudo chown -R `whoami` /usr/local
brew install watchman

**Comment by Randyjp** [comment]
thanks you @Meekohi

**Comment by X9He** [comment]
thanks your comment fixed it for me @Meekohi

**Comment by netdesignr** [comment]
> Possible solution: I had installed watchman via `npm install -g watchman` but apparently this installs some garbage old version.
> 
> ```
> npm r -g watchman
> brew install watchman
> ```
> fixed the problem I think.

Superb!

**Comment by erdemkeren** [comment]
Thank you @Meekohi and @poohsen 😄🗡!

**Comment by Webbrother** [comment]
I don't think that using of workaround instead of understanding of reason of the problem is good idea.

**Comment by shenjo** [comment]
@Meekohi Thanks!

**Comment by leosouza28** [comment]
when i updated my os, i got this error.
Thanks @Meekohi !

**Comment by sumanpula** [comment]
@Meekohi It worked perfectly, thanks

**Comment by Biplovkumar** [comment]
> Possible solution: I had installed watchman via `npm install -g watchman` but apparently this installs some garbage old version.
> 
> ```
> npm r -g watchman
> brew install watchman
> ```
> 
> fixed the problem I think.

thanks,it worked
