### ISSUE TITLE
[expo-local-authentication] nothing happened in Samsung s8

### ISSUE THREAD

**Issue by Jekiwijaya** [expo/expo#8545]
### Steps to Reproduce
I'm using Samsung Galaxy S8 using expo local authentication

![Screenshot_20200517-201851_Expo](https://user-images.githubusercontent.com/6567775/83176955-80de7000-a148-11ea-9784-e9bf69c0b151.jpg)
My device already enrolled for fingerprint, but when I tried to authenticate, nothing happened.

When I tried to log, the authenticate throw an error `not_available`

### Expected Behavior
Able to authenticate

**Comment by cruzach** [comment]
@Jekiwijaya I think this is the same root cause as https://github.com/expo/expo/issues/8530

do you have `Face recognition` as your `Preferred biometric` in system Settings -> Biometrics and security ->Biometric preferences ?

**Comment by manohar-octifi** [comment]
This issue is still happening in Samsung Note 8 

- isEnrolledAsync true 
- hasHardwareAsync true
- authenticateAsync => result.error = not_available

expo-local-authentication: 11.1.1
