### ISSUE TITLE
Error: Cannot find module '/scripts/createManifest.js'

### ISSUE THREAD

**Issue by alexhulbert** [expo/expo#8547]
## 🐛 Bug Report

When running `react-native run-android --variant=release` or `./gradlew assembleRelease`, I get the following error:

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '/scripts/createManifest.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createReleaseExpoManifest'.
> Process 'command 'node'' finished with non-zero exit value 1
``` 

This issue is happening because `expoUpdatesDir` is empty in `create-manifest-android.gradle`. I'm able to fix the error by setting the value of this variable to `node_modules/expo-updates`. When I run the command whose output was originally stored in `expoUpdatesDir` in my terminal, the expected output is produced.

### Environment

```
  Expo CLI 3.20.9 environment info:
    System:
      OS: Linux 5.4 Arch Linux
      Shell: 3.0.2 - /usr/bin/fish
    Binaries:
      Node: 12.13.1 - ~/.asdf/installs/nodejs/12.13.1/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.12.1 - ~/.asdf/installs/nodejs/12.13.1/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.20.9

  Expo CLI 3.20.9 environment info:
    System:
      OS: Linux 5.4 Arch Linux
      Shell: 3.0.2 - /usr/bin/fish
    Binaries:
      Node: 12.13.1 - ~/.asdf/installs/nodejs/12.13.1/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.12.1 - ~/.asdf/installs/nodejs/12.13.1/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.20.9
```

`expo-updates` is version 0.2.7

### Steps to Reproduce

Run one of the following commands:
 - `react-native run-android --variant=release`
 - `./gradlew assembleRelease`

### Reproducible Demo

This issue happens for me on a freshly created bare workflow app, so a reproducible demo won't help.

**Comment by nebmesemaou** [comment]
delete node_modules folder and pacage-lock.json | yarn.lock
then update your expo-cli with `npm install -g expo-cli`
then rebuild

hope it helps !

**Comment by guiferpa** [comment]
@alexhulbert some solution for it?

**Comment by steffenabel** [comment]
I'm experiencing the same issue after upgrading from SDK 38 to SDK 39. The mentioned fix (changing the expoUpdatesDir variable in the script) works for me, but is there a general solution so we don't have to change the script?

**Comment by mrs2296** [comment]
This is quite the annoying issue, for it only affects some of my team members.  It results from the update for resolving the node_modules path in #8419 that is based off of how `react.gradle` resolves the path, except RN solved this in facebook/react-native#28625 by adding the default path as a fallback.  For expo-updates, something like the following could be added to the `create-manifest-android.gradle` script.  A better solution would be to use a project property as a secondary fallback as `react.gradle` does.

However, the best alternative would be avoiding the use of Groovy's `execute()`, which relies on Java's `Runtime.exec()`, for where this method searches for executables varies depending on the JRE implementation.  Perhaps it makes sense to explicitly require a project property to specify non-default paths, and to document as such in the bare workflow Android installation instructions.  This ensures that there is no confusion arises when the same project builds on one system yet fails on another.

```diff
  def expoUpdatesDir = ["node", "-e", "console.log(require('path').dirname(require.resolve('expo-updates/package.json')));"].execute([], projectDir).text.trim()
+ if (!expoUpdatesDir) {
+   if (new File("${projectDir}/../../node_modules/expo-updates").exists()) {
+     expoUpdatesDir = "${projectDir}/../../node_modules/expo-updates"
+   } else {
+     throw new Exception("Couldn't determine expo-updates location.");
+   }
+ }
```

For anyone else stumbling upon this issue, you can use the following `expo-updates+0.3.5.patch` patch file, changing the path from the default in the conditional as required.  This of course is for version 0.3.5, but should work for ^0.2.4.

```patch
diff --git a/node_modules/expo-updates/scripts/create-manifest-android.gradle b/node_modules/expo-updates/scripts/create-manifest-android.gradle
index b233ce1..94e0dc8 100644
--- a/node_modules/expo-updates/scripts/create-manifest-android.gradle
+++ b/node_modules/expo-updates/scripts/create-manifest-android.gradle
@@ -11,6 +11,13 @@ void runBefore(String dependentTaskName, Task task) {
 }
 
 def expoUpdatesDir = ["node", "-e", "console.log(require('path').dirname(require.resolve('expo-updates/package.json')));"].execute([], projectDir).text.trim()
+if (!expoUpdatesDir) {
+  if (new File("${projectDir}/../../node_modules/expo-updates").exists()) {
+    expoUpdatesDir = "${projectDir}/../../node_modules/expo-updates"
+  } else {
+    throw new Exception("Couldn't determine expo-updates location.");
+  }
+}
 
 def config = project.hasProperty("react") ? project.react : [];
 def nodeExecutableAndArgs = config.nodeExecutableAndArgs ?: ["node"]

```

**Comment by steffenabel** [comment]
Thank you @mrs2296 for the patch and the mention of patch-package. As I didn't know patch-package yet, here is the link, so  anybody else who doesn't know it can use it directly: https://www.npmjs.com/package/patch-package

**Comment by dillonhafer** [comment]
I have this same problem with the expo-constants and expo-updates packages on a brand new expo 41 app, I just created a new app, ejected, and tried to build. mrs2296 patch, that simply looks at the projectDir worked for me in both packages.

**Comment by daphil19** [comment]
I ran into this problem with a bare workflow app after I decided to switch from `nvm` to `asdf`. I did some digging before looking at the patch that @mrs2296 provided, and found that the [asdf direnv plugin](https://github.com/asdf-community/asdf-direnv) solved the problem without needing to apply the patch.
