### ISSUE TITLE
[expo-ads-admob] I can't use SSV

### ISSUE THREAD

**Issue by onurgule** [expo/expo#8548]
### I can't use ServerSideVerifications for Expo Admob

I am using expo-ads-admob in my app. I set my ad for server side verification but I can't set user_id or custom data for ad in my app.

`await AdMobRewarded.requestAdAsync({ servePersonalizedAds: true, additionalRequestParams: {user_id:122}});`

I am getting transaction_id in my server but I can't receive user_id.

Also I tried to get transaction_id for ad in my app but I can't get it too.
How can I use ServerSideVerification for admob with expo?
Thanks.

**Comment by chichke** [comment]
Any updates on this ?

**Comment by swittk** [comment]
Same. The ability to set user_id, custom_data, or get transaction_id, is very much needed for server-side verification.

**Comment by chichke** [comment]
Had to use [RnFirebase](https://rnfirebase.io/admob/usage) to get things to work :/

**Comment by beexo-si** [comment]
Any update on this?

Admob is not very useful if it cannot be verified from the server

**Comment by brentvatne** [comment]
please open a pull request if you are interested in this feature, thanks!

**Comment by swittk** [comment]
I opened a pull request here
https://github.com/expo/expo/pull/12368

Unfortunately despite my native development platform being iOS, I'm stuck on Mac OS X Mojave and..

- iOS : some other Expo modules require headers from Xcode 12 and up (I'm stuck with Xcode 11 on Catalina), so I can't compile and test it truly for now.
- As for Android, it compiles fine, but my Android Emulator (30.1.5) seems to crash with everything (I can't go newer; installing the latest 30.5 requires IOUSBHost.framework in Catalina and up).

Code changes are minimal, but would need someone to review/see if these changes are OK. I'm certain that the AdMob implementation inside the edited method on the iOS side is correct, but I'm not sure of the method signature if this is the correct form. While for the Android side, it's mostly the uncertainty of how ReadableArguments works, if this is the correct way then I guess it should be ok.
