### ISSUE TITLE
When uploading a built IPA file to Apple: "Error: description length:9808055"

### ISSUE THREAD

**Issue by Dygerati** [expo/expo#855]
When trying to submit the *.ipa file build by Expo, I get the following error in the console:

`description length:9808055`

After digging a bit I found [this post that seems relevant](https://forums.developer.apple.com/thread/86290). I know nothing about Cocapods, but it may be related-is there something that needs to be done on the Expo side to resolve this?

**Comment by brentvatne** [comment]
why do you think that seems relevant? where is the rest of the error description? the "description length" by itself seems not so useful, it is the description that comes after it (whose length is described by description length) that is the useful thing

**Comment by Dygerati** [comment]
You're right, I'm using a service to upload the IPA and that's all they gave me. I'm inquiring to see if I can get more information. 

Appreciate it.
