### ISSUE TITLE
Expo Speech resume and pause methods not working on Android 

### ISSUE THREAD

**Issue by avinashpatnaik** [expo/expo#8551]
import * as React from 'react';
import { View, StyleSheet, Button } from 'react-native';
import Constants from 'expo-constants';
import * as Speech from 'expo-speech';

export default class App extends React.Component {
  speak() {
    var thingToSay = 'Some Text here. I am writing this to test few features.';
    Speech.speak(thingToSay);
  }

  pausePlay(){
    Speech.pause();
  }
   
  resumePlay(){
    Speech.resume();
  }

  stopPlay(){
    Speech.stop();
  }

  render() {
    return (
      <View style={styles.container}>
        <Button title="Press to hear some words" onPress={this.speak} />
        <Button title="Press to pause" onPress={this.pausePlay} />
        <Button title="Press to resume" onPress={this.resumePlay} />
        <Button title="Press to stop" onPress={this.stopPlay} />
      </View>
    );
  }
}

The pause and resume methods dont work on Android Platform for the attached code. However, they do in the iOS platform. Is this expected? If yes, please provide a workaround for this.

PS: I dont want to eject Expo from my project.

**Comment by ngioldasis** [comment]
The same problem here.
(expo sdk 36.0.1)

**Comment by avinashpatnaik** [comment]
> The same problem here.
> (expo sdk 36.0.1)

**Comment by avinashpatnaik** [comment]
> The same problem here.
> (expo sdk 36.0.1)

Found any alternative?

**Comment by cruzach** [comment]
looks like there's the same issue on web - https://snack.expo.io/@charliecruzan/speech

**Comment by barthap** [comment]
Unfortunately, Android's `TextToSpeech` doesn't support pause/resume, so those methods are not supposed to work on that platform at the time.

However, I couldn't reproduce Web issue - tested on Chrome and Safari and pausing/resuming is working for me.

**Comment by Razorholt** [comment]
Looking at the doc (https://docs.expo.io/versions/latest/sdk/speech/), under SDK 40, I don't see that issue with Android being mentioned. Does it mean that pause/resume now works on Android?

**Comment by AlenToma** [comment]
Im having the same issue with latest update

**Comment by Razorholt** [comment]
That feature is simply not available in android.
