### ISSUE TITLE
[docs] InAppPurchases doesn't seem to work as explained

### ISSUE THREAD

**Issue by bidetaggle** [expo/expo#8559]
Hello,

I'm working on android (I plan to make also an iOS version) and I really have a hard time understanding how to use InAppPurchases.

Using the following code from the doc:
```
// Set purchase listener
setPurchaseListener(({ responseCode, results, errorCode }) => {
  // Purchase was successful
  if (responseCode === IAPResponseCode.OK) {
    results.forEach(purchase => {
      if (!purchase.acknowledged) {
        console.log(`Successfully purchased ${purchase.productId}`);
        // Process transaction here and unlock content...

        // Then when you're done
        finishTransactionAsync(purchase, true); // <- I want consumable items
      }
    });
  }

  // Else find out what went wrong
  if (responseCode === IAPResponseCode.USER_CANCELED) {
    console.log('User canceled the transaction');
  } else if (responseCode === IAPResponseCode.DEFERRED) {
    console.log('User does not have permissions to buy but requested parental approval (iOS only)');
  } else {
    console.warn(`Something went wrong with the purchase. Received errorCode ${errorCode}`);
  }
});
```

`results` always keep getting `"acknowledged": false` and `"purchaseState": 1` and it's just piling up on the older purchases each time I buy a new item until I close the app.

If I comment `finishTransactionAsync(purchase, true);` to simulate a problem with my server to unlock the content (in this case, I top-up credits to the user account) then I get a responseCode ERROR and errorCode 8 (ITEM_ALREADY_OWNED) after having bought 1 time an item, until I close the app.

I don't understand how am I supposed to use it properly.

I end up doing something like this but it feels like dirty hack to me:
```
InAppPurchases.setPurchaseListener(async ({ responseCode, results, errorCode }) => {
        if (responseCode === InAppPurchases.IAPResponseCode.OK) {
          console.log("RESPONSE CODE OK");
          results.forEach(async purchase => {
            if (!purchase.acknowledged) { // <- it's always === false anyway...
              console.log(`Successfully purchased ${purchase.productId}`);
              // Process transaction here and unlock content...

              // Let's simulate that things go wrong so I comment the following line
              //await InAppPurchases.finishTransactionAsync(purchase, true);
            }
          });
        }
        // Else find out what went wrong
        else if (responseCode === InAppPurchases.IAPResponseCode.USER_CANCELED) {
          console.log('User canceled the transaction');
        } else if (responseCode === InAppPurchases.IAPResponseCode.DEFERRED) {
          console.log('User does not have permissions to buy but requested parental approval (iOS only)');
        } else if (errorCode === InAppPurchases.IAPErrorCode.ITEM_ALREADY_OWNED){
          console.log("This item has been purchased already but failed to consume");
          const HISTORY = await InAppPurchases.getPurchaseHistoryAsync();
          if (HISTORY.responseCode === InAppPurchases.IAPResponseCode.OK) {
            HISTORY.results.forEach(result => {
              // Process transaction here and unlock content...
              // Let's say that this time things go well
              await InAppPurchases.finishTransactionAsync(purchase, true);
            });
          }
          else console.log("HISTORY didn't work");
        } else {
          console.warn(`Something went wrong with the purchase. Received errorCode ${errorCode}`);
        }
      })
```
Do you have any advice?

**Comment by cacharrin** [comment]
I am having exactly the same problem testing in Android...

When I call `finishTransactionAsync(purchase, true)` it seems the product is marked as "consumed" on Google Play (Because i can buy the same item multiple times)...
But in each new purchase, i got in `results` an array of all previous purchases, all with `acknowledged: false`:

```
[
    {"acknowledged": false, "purchaseState": 1, ...},
    {"acknowledged": false, "purchaseState": 1, ...},
    {"acknowledged": false, "purchaseState": 1, ...},
    {"acknowledged": false, "purchaseState": 1, ...}
]
```

Is it a bug?
How can I remove the purchase from the results, after the purchase has been succesfully procesed?

**Comment by bidetaggle** [comment]
Hi mate, thanks for your message. I never get any Item from Apple on iOS so other problems are on the way. 

I think the expo community is not big enough to maintain an up-to-date feature like this, unfortunately.

I guess you already ejected your project on the bare workflow, so better go where react-native people are.
I found this npm package and it seems to be more popular and serious: https://www.npmjs.com/package/react-native-iap (I didn't try it yet)

**Comment by chris-aeviator** [comment]
really expo? Why is this not a top priority? Why is there no big warning sign that in app purchases are only available for ejected apps on the startpage of the docs?

**Comment by bidetaggle** [comment]
@chris-aeviator I guess the expo project is unfortunately too ambitious. `react-native` itself is already cutting-edge, I believe it's still officially an alpha version (0.63.4 at the moment) - [Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.](https://semver.org/#spec-item-4)

From my experience, expo is an additional layer of complexity to handle (and update) and its benefits just don't worth it, especially for a long term purpose. I got an app, started on expo then ejected to bare. Eventually my project's core files became so far away from a regular RN app that a proper maintenance was impossible and `npm` were prompting more vulnerabilities from my package dependencies everyday.

I generated a new RN app from scratch, migrated my code to it and replaced each expo related dependency by an equivalent pure RN module/component and I have a way more stable project code and a radically faster build time.

`expo` should not be the main tool pointed in the official RN documentation in the first place(?)

**Comment by chris-aeviator** [comment]
@bidetaggle thanks for sharing your in-depth & long-term experience. After reading the many doc pages expo shares it becomes apparent that even expo thinks that their managed workflow is **not production ready**. Nonetheless this should be highly visible on the first line in github, since when starting a new project people do not tend to do a week of research into the docs. This turns out getting quite expensive for me now since I'm in the middle of a project, I'd appreciate the expo team would rethink their communication approach here.

**Comment by bidetaggle** [comment]
Same thing happened to me, if you have any blockage with you current project you can shoot me a message. Perhaps I can fast-forward you a solution.
