### ISSUE TITLE
Error: Cannot read property 'onboarded' of undefined

### ISSUE THREAD

**Issue by RyanPWalker** [expo/expo#856]
Please help.  This isn't the first time this has happened.  When using the XDE, I try to login and it displays the following error: "Cannot read property 'onboarded' of undefined" and refuses to let me log in.  I've tried reinstalling, restarting my computer, it won't even let me create a new account.  When I create a new account it just says, "an unknown error has occured".

**Comment by jimmylee** [comment]
Hey @RyanPWalker we're running into some critical failures with our login and sign up, please view this forum post for more details:

https://forums.expo.io/t/2017-10-25-issues-with-logging-into-expo-developer-accounts/4236/2

We promise to keep you updated.

**Comment by ide** [comment]
@RyanPWalker We believe the login & signup issues that Jim mentioned are fixed. You can try logging into the Expo website at https://expo.io/login first -- once you're able to log in there, then log into XDE or exp on your computer. I'm really sorry about this and please tell us if you're still having login issues.

**Comment by terribleben** [comment]
Hi there, closing this because we think the login issues are all fixed. Let us know if you're still having a problem.
