### ISSUE TITLE
Converting Android recording extension from .m4a to .mp3 issue 

### ISSUE THREAD

**Issue by yapdianhao** [expo/expo#8561]
Hi,

I am currently working on the project that requires to send a voice recording and send it to IBM watson for Speech to Text translations. It works fine with IOS, but I am having some problems with Android. Because the default recording extension is .m4a which is not supported by IBM as shown [here](https://cloud.ibm.com/docs/speech-to-text-data?topic=speech-to-text-data-audio-formats), therefore I am trying to set the recording extension to .mp3 format:

```
const recordingOptions = {
  android: {
    extension: ".mp3",
    outputFormat: Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_DEFAULT,
    audioEncoder: Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_DEFAULT,
    sampleRate: 44100,
    numberOfChannels: 2,
    bitRate: 128000,
    linearPCMBitDepth: 16,
    linearPCMIsBigEndian: false,
    linearPCMIsFloat: false
  },
  ios: {
    extension: ".wav",
    audioQuality: Audio.RECORDING_OPTION_IOS_AUDIO_QUALITY_HIGH,
    sampleRate: 44100,
    numberOfChannels: 1,
    bitRate: 128000,
    linearPCMBitDepth: 16,
    linearPCMIsBigEndian: false,
    linearPCMIsFloat: false
  }
};
```

but I always get an error shown below no matter what combinations of the `outputFormat` or `audioEncoder` of the `Audio` libary. 
![Screenshot 2020-05-29 at 4 33 25 PM](https://user-images.githubusercontent.com/48383749/83245109-e0815d80-a1d2-11ea-8cb4-088676c3b085.jpg)

I even tried the recommended `RECORDING_OPTIONS_PRESET_HIGH_QUALITY` and `RECORDING_OPTIONS_PRESET_LOW_QUALITY`, but get an extension of .mp4 for the former and .3gp for the latter. The code shown below:
const recording = new Audio.Recording();
  ```
  try {
      //await recording.prepareToRecordAsync(recordingOptions);
      await recording.prepareToRecordAsync(RECORDING_OPTIONS_PRESET_HIGH_QUALITY);
      await recording.startAsync();
    } catch (error) {
      this.stopRecording();
    }
```

Has anyone solved this before give some insights?

**Comment by SimNee** [comment]
Facing similar issue here too. Any advices? It seems to me that expo audio is only able to record in m4a or 3gp extensions. However, mp3 is what I wanted to have.

**Comment by chuksgpfr** [comment]
I'm having same issues, anybody solved it.

**Comment by vandemberg** [comment]
I've having same issues

**Comment by charliegmv** [comment]
Same here. If there's no way to record directly from Expo, has anyone found a possible workaround to transcode to mp3?
