### ISSUE TITLE
[expo-secure-store] Cannot read data from Unimodule from Expo App

### ISSUE THREAD

**Issue by LinusU** [expo/expo#8564]
## 🐛 Bug Report

We are currently rewriting our existing React Native app in a clean code base with Expo. Our plan is to release this version as just a new version of the old app, invisible to the user.

We have added `expo-secure-store` to the current app, so that it saves the user token in a way that will be compatible with the new app.

However, we cannot get reading of the saved data to work in the new Expo app.

### Environment

```text
  Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.0.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
```

### Steps to Reproduce

1. Create a normal React Native app
2. Add `expo-secure-store`
3. Save something using `setItemAsync`
4. Create a new app using Expo
5. Set the iOS bundle identifier to the same as previous app
6. Read the same value you set in step 3 using `getItemAsync`
7. Notice that you get `null` instead of the saved value

### Expected Behavior

I expected to be able to read the value from the new app

### Actual Behavior

I could not read the value.

Should also add that the value is still saved, if I go back and install the old app over the new again, it can read the value.

### Reproducible Demo

https://github.com/LinusU/expo-secure-store-migration-test

- `git clone git@github.com:LinusU/expo-secure-store-migration-test.git`
- `cd expo-secure-store-migration-test`
- `git checkout 10e2ae5` (this is the React Native app)
- `yarn`
- `cd ios && pod install && cd ..`
- `npm run ios`
- Press "write value", se that it saves it, then close the app
- `git checkout 83fa55e` (this is the Expo app)
- `expo build:ios -t simulator`
- wait for build to finish, then download and unpack it
- `xcrun simctl install booted /Users/foobar/Downloads/securestoremigrationtest.app`
- Start the new app in the simulator
- Try and read the value

-----

I've been trying to dig around in the Expo source code, but I cannot see anything that points to them namespacing this, or otherwise making changes that would be incompatible 🤔 

Would really appreciate some guidance here!

**Comment by jarvisluong** [comment]
Hi! I believe the reason is because during development, you are running with the Expo client, which has a different bundle id from the old react-native app, so that's why you can't read the same keychain content.

**Comment by LinusU** [comment]
@jarvisluong thanks for the response, I don't believe that is it though.

If you look at the reproduction steps and the `app.json` in the second checkout you'll see that it uses the same bundle id. This can also be confirmed by seeing that the apps gets replaced in the simulator, and that there isn't now two apps installed.

I've also experienced this with an app that was distributed via TestFlight.

I'm not using the Expo Client app at all, only building the app and then installing it.
