### ISSUE TITLE
[react-native-unimodules] AppDelegate examples are outdated, causing unimodules to break

### ISSUE THREAD

**Issue by macintoshhelper** [expo/expo#8568]
## 🐛 Bug Report

Notification events are broken in a bare Expo app, setup using the `react-native-unimodules` instructions: https://gist.github.com/brentvatne/1ece8c32a3c5c9d0ac3a470460c65603

I managed to fix this by adding the line `[super application:application didFinishLaunchingWithOptions:launchOptions];` in `AppDelegate.m` and using `UMAppDelegateWrapper` in `AppDelegate.h`.

I'm not using Expo updates, and it seems that most of the templates and examples use Expo updates.

This may be a documentation issue: I'm not sure if the `AppDelegate.h` instructions are out-of-date, or if the notification listeners should work with `UIResponder` instead of `UMAppDelegateWrapper`.

### Environment

**Platform**: iOS 10

GitHub repo (fork): https://github.com/macintoshhelper/notif-example

### Steps to Reproduce

1. Clone https://github.com/macintoshhelper/notif-example
2. `git checkout reverse-expo-update`
3. Edit `ios/notifs/AppDelegate.m` 
4. Remove line 34: https://github.com/macintoshhelper/notif-example/blob/patch/reverse-expo-update/ios/notifs/AppDelegate.m#L34 – to match the docs

### Expected Behavior

`Notifications.setNotificationHandler` would allow local notifications to appear in the app foreground, and `Notifications.addNotificationReceivedListener` would work.

### Actual Behavior

`Notifications.addNotificationReceivedListener` and `Notifications.setNotificationHandler` don't do anything.

### Reproducible Demo

https://github.com/macintoshhelper/notif-example/pull/1/files#diff-7f2795e17253bf1988070b59ed2d62c8R34

I hope this is enough info, please ask for more if needed 🙂.

**Comment by sjchmiela** [comment]
Hey, thank you for notifying us of this issue — this indeed is a problem with the example `AppDelegate.m` linked to in `react-native-unimodules`', it's soo outdated… I'll take care of this!

**Comment by macintoshhelper** [comment]
Great, thanks!
