### ISSUE TITLE
XDE prompts to "Please fill out all the fields" even when all fields are filled

### ISSUE THREAD

**Issue by ide** [expo/expo#857]
(Moved from https://github.com/expo/xde/issues/146)

During the Auth0 outage when login was disabled, it looks like XDE prints an alert about filling out fields rather than login being unavailable. We should probably print a more accurate message:

![expoerror](https://user-images.githubusercontent.com/3944526/32034982-bcb21b62-ba33-11e7-8672-a728efb1fc2e.png)

**Comment by abhitheawesomecoder** [comment]
now getting this when trying to login. ( check attachment 
![invalidreq](https://user-images.githubusercontent.com/3944526/32069579-35d24210-baa7-11e7-82fb-31307890c6c6.png)
)

**Comment by DaniyalArshad** [comment]
Hi,

Any idea till when is this issue going to be resolved?

**Comment by ide** [comment]
@abhitheawesomecoder We believe the login & signup issues are fixed for nearly all developers. Try logging into the Expo website at https://expo.io/login first -- once you're able to log in there, then log into XDE or exp on your computer. I'm really sorry this happened and please tell us if you're still having login issues.

**Comment by yevhene** [comment]
I have same problem

**Comment by ebennaga** [comment]
@ide how to fix it ?

**Comment by yevhene** [comment]
@ebennaga They have no meaningful error messages in app. So for any error it responds with "Please fill out all the fields". Wait a bit (maybe deployment in progress) or ask in clack channel (people respond very quickly).

**Comment by ide** [comment]
Have you tried the steps in https://github.com/expo/expo/issues/857#issuecomment-339880951 (signing in https://expo.io/login)?

**Comment by sjchmiela** [comment]
XDE has been deprecated in favor of Expo CLI — https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c. 🙂
