### ISSUE TITLE
video play slow, Always wait until the data is fully loaded

### ISSUE THREAD

**Issue by menglingyu** [expo/expo#8576]
video play slow, Always wait until the data is fully loaded,   how to Play while loading data

**Comment by byCedric** [comment]
Hi @menglingyu! I'm not sure what you mean by "playing slow". Do you mean it's pausing during play because of buffering? Or is the playback decreased? If you are able to, could you provide a small example? That way we can investigate this properly 😄

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
