### ISSUE TITLE
(Solved) Maximum call stack size exceeded - After downloading Javascript bundle 100% stuck

### ISSUE THREAD

**Issue by knoxgon** [expo/expo#8578]
### Environment

Expo CLI 3.21.3 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ^37.0.12 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ^0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7

**Target OS:** Android

### Steps to Reproduce

expo start
scan QR code with android phone
wait for phone to install javascript bundle
the js bundle downloading is stuck at 100%
after a short while, crash

### Expected Behavior
Should view the basic View with some Text
It works fine when showing in web browser

It should view my application

### Actual Behavior
Maximum call stack size exceeded

![image 1](https://user-images.githubusercontent.com/24989987/83345436-57be0b00-a313-11ea-94af-bfff4471199e.png)
![image 2](https://user-images.githubusercontent.com/24989987/83345356-5d672100-a312-11ea-8466-d24c22594223.png)
![image 3](https://user-images.githubusercontent.com/24989987/83345357-60faa800-a312-11ea-9653-53cf22401a7b.png)

### Reproducible Demo

**package.json**
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@ant-design/icons": "^4.2.1",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/native": "^5.5.0",
    "@react-navigation/stack": "^5.4.1",
    "expo": "^37.0.12",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "^0.61.4",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-hooks": "^2.5.1"
  },
  "private": true
}

I couldn't really figure out the root cause behind this error. I followed the following steps
* Reinstalled npm, node, expo client (android)
* Restarted both computer and phone
* Cleared the cache memory of expo client

It could be one of the installed packages that are incompatible.

[Source code](https://snack.expo.io/@knoxgon/adequate-beef-jerky)

**Comment by brentvatne** [comment]
something in your app is causing an infinite loop. we would need to see your source code to help more. based on your package.json there is more to the app than just an empty hello world.

**Comment by knoxgon** [comment]
> something in your app is causing an infinite loop. we would need to see your source code to help more. based on your package.json there is more to the app than just an empty hello world.

I'm posting the source code, hold on

**Comment by knoxgon** [comment]
> something in your app is causing an infinite loop. we would need to see your source code to help more. based on your package.json there is more to the app than just an empty hello world.
> 
> one thing to look out for - if you are using the useWindowDimensions hook, there is a bug with it in react-native 61 that can manifest like this.

Just uploaded the source code [Here](https://snack.expo.io/@knoxgon/9fdc81)

**Comment by brentvatne** [comment]
unfortunately i can’t read the source code from there, when published it’s transpiled and minimified. can you push it to a github repo?

**Comment by knoxgon** [comment]
> unfortunately i can’t read the source code from there, when published it’s transpiled and minimified. can you push it to a github repo?

Strange behaviour
I imported the exact code to github as you requested, [here](https://github.com/knoxgon/github-issue-max-size-exceed)

**Comment by knoxgon** [comment]
I found the problem...
The problem is produced by the following libraries
dependencies:
    "@react-navigation/native": "^5.5.0",
    "@react-navigation/stack": "^5.4.1",

devDependencies:
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-hooks": "^2.5.1"

I don't know why, I don't know how it doesn't produce the exact problem when running in snack.expo but it sure fix the problem by removing those packages from my project.
Especially react navigator packages causes the problem.

It could also be how I use them. I don't see any problem myself

`js
import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import HomeScreen from './src/screens/home';
import Forecast from './src/screens/forecast';

const Stack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator
        screenOptions={{
          headerShown: false,
        }}
      >
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Forecast" component={Forecast} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
`

**Comment by knoxgon** [comment]
Ok - I found the problem

The problem was that I had a json file that was well over 30mb in size. And I had no way of knowing that it was the root cause. The error message did not provide me with enough information to track it.
When running on browsers, I did not receive any faulty message or crashes. This exact problem was not present during web deployment.

So the rule of thumb: do not use local json files in React Native, especially when the size is in megabytes.

**Comment by owencm** [comment]
FYI for anyone reading in the future, I experienced `maximum call stack exceeded` and the culprit turned out to be calling `const lastNotificationResponse = Notifications.useLastNotificationResponse();`

**Comment by yeefun** [comment]
@owencm 

> FYI for anyone reading in the future, I experienced `maximum call stack exceeded` and the culprit turned out to be calling `const lastNotificationResponse = Notifications.useLastNotificationResponse();`

How did you know that? Could you explain how you identified the root cause? I'm struggling for it.
