### ISSUE TITLE
Resize images in ImagePicker

### ISSUE THREAD

**Issue by ahmed-wagdi** [expo/expo#858]
Is there anyway to resize images after selecting an image with the ImagePicker? I'm trying to restrict image sizes to help with upload speeds.

I also noticed that the ImagePicker's behavior isn't very consistent across platforms when it comes to image sizes. On android if you set allowEditing to false then the ImagePicker automatically resizes large images, but if you set allowEditing to true but select the entire image without cropping anything out then you get the full image size without any resizing. On iOS it's the other way around, if you allowEditing then the image is resized and if not then the image will remain at fullsize.

Android:
allowEditing false - 1512 x 2016
allowEditing true (full image) - 3024 x 4032

ios:
allowEditing false - 4288 x 2848
allowEditing true (full image) - 1239 x 822

Even if this behavior is based on how each platform operates it would be good to atleast be able to set the size of the image to make the UX consistent across platforms. As it is right now either ios or android will end up uploading huge images.

**Comment by tcdavis** [comment]
Giving you a way to do this is on the roadmap: https://expo.canny.io/feature-requests/p/image-manipulation

Those are the default behaviours on each platform.  We'd like to smooth out these inconsistencies where we can / it makes sense, but you'll need to do the resizing yourself for now.
