### ISSUE TITLE
Audio loop not behaving how it should 

### ISSUE THREAD

**Issue by shinedark** [expo/expo#859]
Need some help with expo audio setIsLoopingAsync. it works but it skips part of the audio track after the 1st loop. so let’s say i have a loop of a kick drum. It has 8 hits in the loop. when it loops it only plays 7 of them.Then their is the issue when running multiple sounds at a time they don't play how they should they get stop and start at random times while still trying to play.

i test it in ios simulator and iphone. both had the same issues 

if some one can help would be great thanks.

here is some basic code to recreate the issue and the repo 
https://github.com/shinedark/LoopNotWorking

`import React from 'react';
import { Text, View  } from 'react-native';
import { CardSection, Button, Button2 } from './src/components/common';
import { Audio } from 'expo';

export default class App extends React.Component {
  
    state = {
      playing1: false
    };

    async componentWillMount(){
      
      try{
        await Expo.Audio.setIsEnabledAsync(true);
      } catch(error) {console.log(error);}
    }

    

    handlePLay1 = async () => {
      const { playing1 } = this.state;
      this.setState({ playing1: true});
        const soundObject = new Expo.Audio.Sound();
          try {
            await soundObject.loadAsync(require('./sounds/drums/kick.wav'));
          { shouldPlay: true }
          this.audioPlayer1  = soundObject;
             this.audioPlayer1.setIsLoopingAsync(true);
             this.audioPlayer1.playAsync();
             this.audioPlayer1.setVolumeAsync(0.8);
           // Your sound is playing!
          } catch (error) {
          // An error occurred!
          
          } 
    }

    stopMusic1 = async () => {
      const { playing1 } = this.state;
      this.setState({ playing1: false});
        await this.audioPlayer1.stopAsync();

     }  

    renderButton1 () {
       
      if (this.state.playing1){
        return  (
          <View style={styles.col}>
            <Button2 style={styles.bol} onPressIn={this.stopMusic1.bind(this)}>
              ||
            </Button2>
          </View>
        );

      }
      return(
        
        <View style={styles.col}> 
          <Button style={styles.col1} onPressIn={this.handlePLay1.bind(this)}>
            |>
          </Button>
        </View>
      );
     }
    render(){
      
      return (
        <View style={{flex:1}}>
          <View style={styles.col}>
            {this.renderButton1()}
          </View>
        </View>

      );

    }
}

const styles =  {
  col: {
    flex: 2,
    flexDirection: 'row'
  }, 
  col1:{
    backgroundColor: 'rgba(44, 62, 80,1.0)'
  },
  bol:{
    // flex: 1,
    flexDirection: 'column'
  }
};
`

@nikki93

**Comment by terribleben** [comment]
@nikki93 possibly related to the threading thing you discovered last cycle?

**Comment by shinedark** [comment]
here is link to the expo project https://expo.io/@shinedark/NoiseMachineBeta enjoy the noise

**Comment by terribleben** [comment]
We've tentatively addressed this issue here: https://github.com/expo/expo/commit/0caf4d47bae0bc32b9facfe415be0dd8fb9288d7 and this change will ship with SDK 24.

**Comment by shinedark** [comment]
@terribleben yayyy!!!! thank you so much expo team !!

**Comment by shinedark** [comment]
The new released fix the issue. Thank you expo team !!!!!!  working version https://expo.io/@shinedark/NoiseMachineBeta

**Comment by terribleben** [comment]
Glad it's working for you! :)
