### ISSUE TITLE
Implement createCategoryAsync for expo-notifications

### ISSUE THREAD

**Issue by macintoshhelper** [expo/expo#8590]
As part of the effort of effort to unify the SDK Notifications and `expo-notifications` APIs, it would be great to start with implementing `createCategoryAsync` in `expo-notifications`. I can open a PR for this.

**Comment by byCedric** [comment]
Hi @macintoshhelper! Yes, that would be great to have and any help getting this in is appreciated 😄 If you are able to, feel free to create a PR and receive the eternal gratitude from me 👍

**Comment by brentvatne** [comment]
i'm going to close this issue because issues are reserved for bug reports, appreciate the pr though :)

**Comment by macintoshhelper** [comment]
> i'm going to close this issue because issues are reserved for bug reports, appreciate the pr though :)

Thanks :) . For the future, should I just open a draft PR straight away? I noticed the note in the issue template regarding feature requests, but wasn't sure on the process, as this is a feature that already exists in the SDK. For web API parity, should PRs be opened linking to the umbrella web support issue?
