### ISSUE TITLE
32-bit app compatibility with macOS High Sierra 10.13.4 and later

### ISSUE THREAD

**Issue by pioNavarro** [expo/expo#8602]
I tried to build the APP as a simulator. I'm having a problem running the app on iOS simulator because of this error.

![image](https://user-images.githubusercontent.com/51459273/83464281-fdec4b00-a4a2-11ea-8dbf-0ae0a593ef11.png)

anyway this is my current macOS
![image](https://user-images.githubusercontent.com/51459273/83464342-312eda00-a4a3-11ea-8e0f-c99886df00ce.png)

**Comment by brentvatne** [comment]
you should be able to resolve it with the instructions from this message when you run the build:

```
🚨 If the build is not installable on your simulator because of "... is damaged and can't be opened.", please run:
xattr -rd com.apple.quarantine /path/to/your.app
```

cc @byCedric - maybe apple has gone ahead and thrown another curveball and changed the message :\

**Comment by byCedric** [comment]
I just verified this with the [`use-expo` example app](https://github.com/byCedric/use-expo/tree/master/example). It worked and I had to do the following steps, maybe it helps:

```
// Build the app
$ expo build:ios --type simulator

// Wait for the build to finish
// Download the app
$ curl -L <URL> -o use-expo.tar.gz

// Untar or unzip the app
$ gunzip -c use-expo.tar.gz | tar xopf -

// Remove the quarantine, I also tried skipping this after the first run and it worked. 
// But doing this won't hurt :)
$ xattr -rd com.apple.quarantine use-expo.app

// Boot up the simulator
// Install the app on the simulator
$ xcrun simctl install booted use-expo.app

// There we go!
```

**Comment by byCedric** [comment]
@pioNavarro Could you share a bit more info on your project? e.g. version of the `expo` are you using or the command you used? It looks like the build you are getting is still 32-bit, but I can't replicate that issue in a new or existing project.

**Comment by pioNavarro** [comment]
> @pioNavarro Could you share a bit more info on your project? e.g. version of the `expo` are you using or the command you used? It looks like the build you are getting is still 32-bit, but I can't replicate that issue in a new or existing project.

Im using the SDK37 and this are the versions im currently using
![image](https://user-images.githubusercontent.com/51459273/84433276-9e3f2e00-ac60-11ea-9a24-5baa5c75245c.png)

**Comment by pioNavarro** [comment]
> I just verified this with the [`use-expo` example app](https://github.com/byCedric/use-expo/tree/master/example). It worked and I had to do the following steps, maybe it helps:
> 
> ```
> // Build the app
> $ expo build:ios --type simulator
> 
> // Wait for the build to finish
> // Download the app
> $ curl https://expo.io/artifacts/<id> -L -o use-expo.tar.gz
> 
> // Untar or unzip the app
> $ gunzip -c use-expo.tar.gz | tar xopf -
> 
> // Remove the quarantine, I also tried skipping this after the first run and it worked. 
> // But doing this won't hurt :)
> $ xattr -rd com.apple.quarantine use-expo.app
> 
> // Boot up the simulator
> // Install the app on the simulator
> $ xcrun simctl install booted use-expo.app
> 
> // There we go!
> ```
> 
> You can also manually unzip with the MacOS UI by double-pressing on it, and drag&drop the `.app` file in your simulator. But hey, if you like terminal this is also possible 😄
> 
> Hope it helps!

I followed this steps and its working fine now. 

Thank you!
