### ISSUE TITLE
Can't open an Excel document using the Sharing API

### ISSUE THREAD

**Issue by gregdburns** [expo/expo#8603]
## 🐛 Bug Report
When using the Expo Sharing API, Android emulators and phones cannot open certain apps (Microsoft Excel, Google Sheets).

### Environment

**Android Emulator**
Pixel 3a API 29

**Android Phone**
Version: 10
Security Patch level: May 5th, 2020
Google Play system update: May 1, 2020

Run using the Expo Managed workflow, SDK 36.

### Steps to Reproduce

1. Install either Microsoft Excel or Google Sheets on your emulator or phone.
2. Start whichever app you installed and walk through the set up process.
3. Run your Expo app - sample code here: https://snack.expo.io/@blackline/sharing-api-bug
4. If using sample code, click the "Press Me' touchable.

### Expected Behavior

- The "Share" dialog should show Excel and/or Sheets.
- Clicking Excel and/or sheets should open the document.

### Actual Behavior

The Share dialog shows, but does not show Excel or Sheets.

### Reproducible Demo

https://snack.expo.io/@blackline/sharing-api-bug

You will need to copy this code into an app where you can install the Excel/Sheets app.

**Comment by GregBlackLine** [comment]
It looks like the Sharing API uses android.intent.action.SEND, however android.intent.action.VIEW appears to be what's accepted by Excel and Sheets.

The following workaround appears to work using the Expo IntentLauncher:

`const cUri = await FileSystem.getContentUriAsync(filePath)

    await IntentLauncher.startActivityAsync('android.intent.action.VIEW', {
      data: cUri.uri,
      flags: 1
    })`

**Comment by cruzach** [comment]
For anyone running into a similar issue, I was looking into this further and it doesn’t look as simple as adding in `android.intent.action.VIEW`. [Android recommends using their “ShareSheet” to share data between apps](https://developer.android.com/training/sharing/send), and that requires using the `ACTION_SEND` action.
It seems like maybe it is Excel and Sheets who need to [update how they’re handling the incoming file](https://developer.android.com/training/sharing/receive#handling-content) sharing to match this? This lines up with why dropbox and other 3rd party apps do work with the current `expo-sharing` implementation

**Comment by marcvangend** [comment]
If it helps anyone: I had a similar problem with excel files, and was able to solve it by explicitly passing the mime type using the [mime](https://github.com/broofa/mime) package:
```js
async function openFile(filename) {
    const mime = require("mime");

    await IntentLauncher.startActivityAsync("android.intent.action.VIEW", {
        data: filename,
        flags: 1,
        type: mime.getType(filename),
    });
}
```

**Comment by vadakr** [comment]
> ```js
> IntentLauncher.startActivityAsync("android.intent.action.VIEW", {
>         data: filename,
>         flags: 1,
>         type: mime.getType(filename),
>     });
> ```

@marcvangend did you have to tweak your Android manifest to get this to work? I get -

```
Error: Call to function 'ExpoIntentLauncher.startActivity' has been rejected.
→ Caused by: android.os.FileUriExposedException: file:///data/user/0/<package/fileName> exposed beyond app through Intent.getData()
```
