### ISSUE TITLE
ALREADY TRIED POSTED SOLUTIONS - Uncaught error: packager is not running at http://10.0.1.243:19005

### ISSUE THREAD

**Issue by g4m3r2** [expo/expo#8606]
I've tried: 
1. Restarting my computer, android emulator, Visual Studio and Chrome 
2. Being on the same network as my computer (I am using an emulator so by default this is the case)
 3. Following the steps here https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352 
4. reinstalling npm install -g expo-cli 
5. Opening other projects
 6. Trying Expo on my mobile phone 
7. Turning my firewall off

But none of these solutions are working.

Could someone please help?

![image](https://user-images.githubusercontent.com/17416681/83482342-edad7f00-a454-11ea-84e9-437ec5ad24b7.png)

### Please note that discussions opened as issues in the core Expo repository will be closed.

  If you have a question about Expo or want to discuss about related aspects, consider posting it
  on our forums at https://forums.expo.io/. 🙂

**Comment by brentvatne** [comment]
your phone is unable to reach your computer on your network. i can’t help with config issues around that, but you can switch to a tunnel connection

**Comment by g4m3r2** [comment]
UPDATE: tried a few more things still to no avail:
1. Switched to Tunnel connection, 
![image](https://user-images.githubusercontent.com/17416681/83483960-b0e38700-a458-11ea-828a-fd31eabfee62.png)
2. Added 19000 on firewall (inbound rules -> new rule-> specific local port 19000
3. Making my home wifi private

**Comment by brentvatne** [comment]
can you open web page running on a web server that is running on your computer from your phone?

**Comment by g4m3r2** [comment]
> can you open web page running on a web server that is running on your computer from your phone?

Sorry, could you please explain how I can do this? I am not in IT/am a beginner coder

**Comment by brentvatne** [comment]
if you put a an index.html file in some directory on your computer and then run npx serve in that directory it will start a web server. if you then open a web browser on your phone and type in http://yournetworkip:port then you probably won’t be able to connect due to network configuration issues.

i’d suggest as another alternative that you connect your phone to your computer. run expo start --localhost and then run expo android in another terminal tab to have expo cli try to start the app on your phone.

**Comment by g4m3r2** [comment]
I receive the following error: 
PS C:\Users\Charles\React Native\realblog> expo start -- localhost
The expected package.json path: C:\Users\Charles\React Native\realblog\localhost\package.json does not exist

**Comment by brentvatne** [comment]
there is no space between -- and localhost

**Comment by g4m3r2** [comment]
Thanks, but I receive the error that says could not load exp://127.0.0.1: 19000.

Interestingly the URL states http://localhost:19002/ ... would such discrepancy cause the problem?

**Comment by brentvatne** [comment]
127.0.0.1 is the same as localhost :) i’m sorry i am going to sleep now. you may want to try installing an android emulator and working on your computer for now until you can figure out network issues. here is a guide for installing the emulator https://docs.expo.io/workflow/android-studio-emulator/

**Comment by g4m3r2** [comment]
Ok. I am also working on the issue on an emulator at the same time with no relief. But thank you for your help thus far :)

**Comment by g4m3r2** [comment]
Fixed it! Had to run expo upgrade!!

**Comment by byCedric** [comment]
Awesome! Glad you resolved this 😄 If there is anything else, please let us know!

**Comment by latiefdev** [comment]
> Fixed it! Had to run expo upgrade!!

how to fix it ?
