### ISSUE TITLE
Splash Screen Image is adding some margin on Android

### ISSUE THREAD

**Issue by deadcoder0904** [expo/expo#861]
On Android emulator, the image on splash screen displays some margin horizontal. On iOS simulator, it covers full screen. Also, I opened it up on my Android phone, it covers full screen. I don't own iPhone so don't know about it.

**Comment by deadcoder0904** [comment]
Oh jesus just scrolled down & saw `"resizeMode": "cover"` will fix it

**Comment by deadcoder0904** [comment]
Nope, it still doesn't work I added `"resizeMode": "cover"`, cleared cache & restarted

**Comment by dinoka** [comment]
"resizeMode": "cover" is not currently working on Android. Refer known issues section on https://docs.expo.io/versions/latest/guides/splash-screens.html

**Comment by deadcoder0904** [comment]
Ok cool 👍
