### ISSUE TITLE
Freshly created expo app crashes when run on ios simulator

### ISSUE THREAD

**Issue by kokaneka** [expo/expo#8618]
## 🐛 Bug Report
Getting this error
**FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory** 
when trying to run a bare bones expo app with any changes at all.
### Environment
Macos 10.14.6

  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.1

### Steps to Reproduce
- Create a new app using 
```
expo init
```
- Run the app using
```
npm run start
```
- Chose to run on ios simulator by pressing 'i'
Throws the error

### Expected Behavior
The app which got bootstrapped by expo init should have run on the installed ios simulator

### Actual Behavior
Throws this error
```
Trying to open the project in iOS simulator...

<--- Last few GCs --->

[49282:0x102802000]    56820 ms: Scavenge 1316.0 (1422.3) -> 1315.4 (1422.8) MB, 3.7 / 0.0 ms  (average mu = 0.254, current mu = 0.219) allocation failure 
[49282:0x102802000]    56827 ms: Scavenge 1316.3 (1422.8) -> 1315.7 (1423.8) MB, 2.4 / 0.0 ms  (average mu = 0.254, current mu = 0.219) allocation failure 
[49282:0x102802000]    56834 ms: Scavenge 1316.5 (1423.8) -> 1316.0 (1424.3) MB, 2.8 / 0.0 ms  (average mu = 0.254, current mu = 0.219) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3e60e43dbe3d]
Security context: 0x3db01f39e6e9 <JSObject>
    1: join [0x3db09fbc4ff1] [path.js:~1141] [pc=0x3e60e45f3800](this=0x3db09fb82201 <Object map = 0x3db07ec38bd1>)
    2: arguments adaptor frame: 2->0
    3: /* anonymous */ [0x3db0d6abd369] [/usr/local/lib/node_modules/expo-cli/node_modules/glob/glob.js:~258] [pc=0x3e60e45f44a4](this=0x3db025782201 <Glob map = 0x3db02dad6319>,f=0x3db0abd29349 <String[253]...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cf99 node::Abort() [/usr/local/bin/node]
 2: 0x10003d1a3 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001b7835 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100585682 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100588155 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: 0x100583fff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x1005821d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10058ea6c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10058eaef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x100560974 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
11: 0x1006924e9 v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
12: 0x100838cc8 v8::internal::Runtime_StringCharCodeAt(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x3e60e43dbe3d 
14: 0x3e60e45f3800 
15: 0x3e60e438a5c3 
```

**Comment by bnussman** [comment]
well, first things first, if your using expo, use `expo start`. I doubt that is a fix, but it may behave differently?

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by natemartins** [comment]
The OP said he spun a new project and ran it immediately without adding any codes. And you are still asking for a reproducible demo. How is he going to get you that when obviously the problem is from expo?

**Comment by akkiei** [comment]
The issue still exists even though it has been closed long ago.

**Comment by brentvatne** [comment]
https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas
