### ISSUE TITLE
exp start --lan selects the wrong Network interface

### ISSUE THREAD

**Issue by phillipwei** [expo/expo#862]
Because I have VirtualBox installed, the IP address that `exp start --lan` uses is wrong. I don't see a way to choose which of my network interfaces `--lan` would use.

**Comment by phillipwei** [comment]
Nevermind, I found a work around via https://github.com/react-community/create-react-native-app/issues/60#issuecomment-287081523

**Comment by spinus** [comment]
`export REACT_NATIVE_PACKAGER_HOSTNAME=$(ip route get 1.1.1.1 | awk '{print $7}')`
