### ISSUE TITLE
How to upload audio files in expo apps??

### ISSUE THREAD

**Issue by kumarmukul771** [expo/expo#8625]
### Please note that discussions opened as issues in the core Expo repository will be closed.

  If you have a question about Expo or want to discuss about related aspects, consider posting it
  on our forums at https://forums.expo.io/. 🙂

**Comment by byCedric** [comment]
Hi @kumarmukul771! You can check out the [image upload example](https://github.com/expo/image-upload-example), and more precisely [this method](https://github.com/expo/image-upload-example/blob/7705b137487a9e5a4d610884a616dc29f035527f/frontend/App.js#L165-L197). Both images and audio are considered files, so you should be able to repurpose this code for your audio upload. If you have any questions like these, feel free to post them on the [forums](https://forums.expo.io/) or our [community slack](https://slack.expo.io/).

Hope it helps!
