### ISSUE TITLE
How to test DeviceNotRegisteredError (Expo push notifications)

### ISSUE THREAD

**Issue by arveenkumar55** [expo/expo#8626]
The token generated by expo is unique per device-installation. That means that if a user removes the app and re-installs it, a new token will be generated for that device. How i check the old expo token is not valid. Is there any way to detect that old expo token is not valid anymore?

Thanks

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for expo forums - https://forums.expo.io. the issues are reserved for demonstrable bug reports.
