### ISSUE TITLE
Expo App crashes using Lottie

### ISSUE THREAD

**Issue by yesIamFaded** [expo/expo#8627]
Hi guys I have mad a small React Native App and I wanted to rebuild it in Expo.

I moved all the code and installed the dependencies. First I noticed that my font wont work but thats ok.

On 1 Screen in my App I have a Lottie Animation of a glass filling up. The problem I have is that in my old build (without expo) my Animation was working perfectly. NOW HOWEVER when I click on the screen that contains my animation the app crashes without any Error. I remeber having this before but dont remeber how I fixxed it.

Is there something extra I need to do to use Lottie in Expo? ~Faded

Versions: 

```
    "lottie-react-native": "^3.3.2",
    "moment": "^2.25.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
```

**Comment by yesIamFaded** [comment]
Ok I noticed when I use another animation it works... But I need the one I had before. How is that possible because it was working before?

**Comment by byCedric** [comment]
Hi @yesIamFaded! I think this is the same issue as [#8011](https://github.com/expo/expo/issues/8011#issuecomment-619993859), right? Your other animation is probable exported for little v2, that's why it should work 😄 If you export your new animation for v2, this should work too. We will upgrade lottie to v3 as soon as we are able to.

Hope it helps!

**Comment by yesIamFaded** [comment]
Hi so is expo lottie on that version that I am using working different then you can use it in a bare React Native app? Because my animationfile and my lottie version did not change from the bare app to expo.

But ty for the hint still I dont know if this is my issue.

**Comment by brentvatne** [comment]
let us know if you determine that this is a bug in expo. it seems like it is caused by an incompatibility in lottie file formats. if that's not the case and you can demonstrate it then please open a new issue and provide a mcve https://stackoverflow.com/help/mcve

thanks!
