### ISSUE TITLE
TypeError: "exports" is read-only

### ISSUE THREAD

**Issue by 2016CS112** [expo/expo#8629]
![image](https://user-images.githubusercontent.com/38519481/83632590-f74ff780-a5b8-11ea-9e9f-f6f020bb7ef9.png)
Dependenices :
 "@expo/vector-icons": "^10.0.6",
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/masked-view": "^0.1.5",
    "@use-expo/font": "^2.0.0",
    "axios": "^0.19.2",
    "config": "^3.3.1",
    "date-fns": "^2.12.0",
    "expo": "~36.0.0",
    "expo-font": "~8.0.0",
    "expo-image-picker": "~8.0.1",
    "expo-location": "~8.0.0",
    "jsonwebtoken": "^8.5.1",
    "jwt-decode": "^2.2.0",
    "react": "~16.9.0",
    "react-dom": "^16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-elements": "^1.2.7",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-floating-labels": "^1.1.9",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-keyboard-avoiding-scroll-view": "^1.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.3.1",
    "react-navigation-drawer": "^2.4.6",
    "react-navigation-stack": "^2.2.2",
    "react-navigation-tabs": "^2.8.6"

**Comment by byCedric** [comment]
Hi @2016CS112! It looks like something is up with the `react-native-floating-labels` package. A quick search resulted in [this issue](https://github.com/mayank-patel/react-native-floating-labels/issues/48). There is not a lot we can do to provide this, it might help if you comment on that issue and provide some more context and/or an example for that maintainer.

One thing you can do, is to manually change that line with the suggestion of the issue I mentioned. If that works, you can even help fix it in that repo 😄 Or use something like [patch package](https://github.com/ds300/patch-package) to auto-patch this once you download the library.

Hope it helps!
