### ISSUE TITLE
console.log in a ref possibly breaks exp logging in some circumstances

### ISSUE THREAD

**Issue by pstockley** [expo/expo#863]
I just upgraded my app to use SDK22 and ran into a really strange error. After the update, my app wouldn’t start (in the iOS simulator). All I got was a white screen and the Exponent app would peg the CPU. If I debugged with the chrome debugger, the app would start and function correctly. However, you could tell there was some background thread pegging the CPU.

After a day of eliminating all the causes I traced it down to 1 line of code I had that looked something like

  render() {
    return <RootStackNavigator ref={(r) => console.log("got ref", r)}/>;
  }
I am using react-navigation and had some logging left from before. If I take out the console.log everything works fine! It looks like some kind of race condition to me. You can have any code in the ref callback except for a console.log so it looks like an issue with logging.

You can reproduce it by taking the default tab navigation expo project and adding the ref property to the RootStackNavigator just as above.

**Comment by tcdavis** [comment]
If this is an issue with StackNavigator, can you open the issue on https://github.com/react-community/react-navigation/issues?

**Comment by pstockley** [comment]
I am pretty certain this has to do with expo client and not react-navigation. Just adding a console log should have zero impact. I can confirm it wasn't in some kind of render loop. Like I said, the app functions perfectly when debugging except for massive cpu usage off the main javascript thread. This only started with the 22 release.

**Comment by terribleben** [comment]
Similar to https://github.com/expo/expo/issues/466 so it's possible our streaming logs don't play nicely with certain objects.

**Comment by ide** [comment]
We rewrote some of the logging code in SDK 23 and added unit tests for logging React components (still not recommended since there's a huge amount of content logged and it will slow things down, definitely don't do this in an animation loop): https://github.com/expo/expo-sdk/blob/master/src/logs/__tests__/LogSerialization-test.js#L76. When SDK 23 is released please give it another try.

**Comment by pstockley** [comment]
Thanks, Will do.
