### ISSUE TITLE
expo-av: Fire a callback when native controls is fired, e.g.: play, pause, next/prev 15 seconds, how many minutes the user watched?

### ISSUE THREAD

**Issue by gpbaculio** [expo/expo#8632]
i'm trying to implement video analytics in a video using expo-av: https://docs.expo.io/versions/latest/sdk/video/

what i want use to achieve that is use a callback when native controls is called. e.g.: play, pause, next 15 secs, is called by using native controls? i'm not really sure what to use, i'd need idea how to get it done.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for our forums. see https://forums.expo.io.
