### ISSUE TITLE
 onPlaybackStatusUpdate when useNativeControls=false don't run on android

### ISSUE THREAD

**Issue by gpbaculio** [expo/expo#8634]
### Environment

Expo CLI 3.21.3 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Baculio\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^37.0.12 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7

### Steps to Reproduce

What i am simply doing is customize controls of a video, onPlaybackStatusUpdate does not fire status on play, when i log in it, nothing is returned but everything is okay on 

### Expected Behavior

i can't customize controls on android since onPlaybackStatusUpdate when useNativeControls=false dont work

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
