### ISSUE TITLE
Could not create task ':app:bundleDebugExpoUpdatesAssets'  with expo-updates.gradle

### ISSUE THREAD

**Issue by MickDev-X** [expo/expo#8637]
I'm not sure but I think the problem appeared after an Android Studio update.
All worked good before.

I don't understand what appens

I have the following message error that I don't manage to solve :

## 🐛 Bug Report

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Developpement web\_xxxx\node_modules\expo-updates\expo-updates.gradle' line: 54

* What went wrong:
A problem occurred configuring project ':app'.
> Could not create task ':app:bundleDebugExpoUpdatesAssets'.
   > Could not get unknown property 'config' for task ':app:bundleDebugExpoUpdatesAssets' of type org.gradle.api.tasks.Exec.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script 'E:\Developpement web\xxx\node_modules\expo-updates\expo-updates.gradle' line: 54

* What went wrong:
A problem occurred configuring project ':app'.
> Could not create task ':app:bundleDebugExpoUpdatesAssets'.
   > Could not get unknown property 'config' for task ':app:bundleDebugExpoUpdatesAssets' of type org.gradle.api.tasks.Exec.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
    at makeError (E:\Developpement web\xxxxx\node_modules\execa\index.js:174:9)
    at E:\Developpement web\xxx\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (E:\Developpement web\xxxx\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (E:\Developpement web\_xxxx\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)

### Environment

  Expo CLI 3.20.9 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: ^0.62.2 => 0.62.2
      react-native-web: ^0.11.7 => 0.11.7

##  Additional info

Moreover, after running react-native doctor I got the foollowing error:

 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 28.0.3

**Comment by caieu** [comment]
What's the version of your `expo-updates` package? I had this problem when i updated mine to `~0.2.0`, and i had to change on `app/build.gradle`:

from: `apply from: "../../node_modules/expo-updates/expo-updates.gradle"`
ro: `apply from: "../../node_modules/expo-updates/scripts/create-manifest-android.gradle"`

https://github.com/expo/expo/tree/master/packages/expo-updates#appbuildgradle

**Comment by MickDev-X** [comment]
it's "expo-updates": "~0.2.0"

Many thanks, it works !

**Comment by drdpedroso** [comment]
@caieu solution also works for `^0.2.7`.
