### ISSUE TITLE
[docs] Help users more with common submission questions

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8638]
Let's gather some common questions here and ensure to provide some guidance in our documentation around how to answer these questions.

- [ ] "Does your app use encryption? Select Yes even if your app only uses the standard encryption within Apple's operating system."
- [ ] Help to create a privacy policy - link to a template, provide information on where it can be hosted.

**Comment by andordavoti** [comment]
Size limit for the assets when using managed workflow. Haven't found a clear limit for it, the builds failed earlier with 30mb SQLite DB asset, now it works for a DB that's 32.6mb. It would be great to know the limit so I know if I will need to eject.
