### ISSUE TITLE
pod install failed on newly detached Expo app

### ISSUE THREAD

**Issue by riwu** [expo/expo#864]
## Repo

https://github.com/riwu/synergy-lab-time-estimation/tree/master/client/ios

## To replicate
Run `pod install`
Output: https://pastebin.com/raw/PXhwwaJR

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ca100dfa5fe8995d77c124f7c008fcbaf8854e01
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'synergy-lab--time-estimation-task' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.0.4",
    :subspecs => [
      "Core",
      "CPP"
    ]

  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion',
    :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec",
    :inhibit_warnings => true
  pod 'Folly',
    :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
    :inhibit_warnings => true
  pod 'GLog',
    :podspec => "../node_modules/react-native/third-party-podspecs/GLog.podspec",
    :inhibit_warnings => true


  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.pod_targets.each do |target|

    if target.pod_name == 'AppAuth'
      target.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
    if target.pod_name == 'ExpoKit'
      target.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
        # needed for GoogleMaps 2.x
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Base/Frameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '${PODS_ROOT}/GoogleMaps/Maps/Frameworks'
      end
    end


    # Build React Native with RCT_DEV enabled
    next unless target.pod_name == 'React'
    target.native_target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
    end

    end
  end
end
```

**Comment by riwu** [comment]
Seems like you have to change `"react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz"` to `"react-native": "^0.49.3"` before detaching. Should probably document it in https://docs.expo.io/versions/latest/guides/detach.html?

**Comment by terribleben** [comment]
What does the `version` field of `node_modules/react-native/package.json` say? It should say [0.49.3](https://github.com/expo/react-native/blob/9e77fe1344b86f68331a01f7af2ae10d36af5f67/package.json#L3) for your SDK. It seems like it contains some other string and cocoapods is barfing on the ill-formed version.

**Comment by terribleben** [comment]
You shouldn't need to use `"react-native": "^0.49.3"` - sticking with our fork is a better idea.

**Comment by terribleben** [comment]
What version of `npm` or `yarn` did you use to install your node_modules? (detaching a new expo project works for me right now.)

**Comment by riwu** [comment]
I'm using npm 5 (I know RN suggests npm 4 but 5 is so much faster)
node_modules/react-native/package.json:
`"version": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz"`

Seems like that's caused by a somehow broken package-lock.json. Deleting that with `rm -rf node_modules && npm i` restored react-native/package.json to `"version": 0.49.3`

package-lock.json content for reference: https://pastebin.com/raw/Dehnk1yf

**Comment by riwu** [comment]
Turns out the issue isn't with npm 5 / broken package.lock.
The default Expo XDE project template comes with `"version": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz"` in its `node_modules/react-native`. 
That should probably be fixed?

**Comment by terribleben** [comment]
That is the correct dependency for our template project. If your package manager didn't install the right version under `node_modules` then the most likely explanation is an issue with your package manager.
