### ISSUE TITLE
iOS Splash Screen Error - SDK22 - Reinstallation of Standalone Apps

### ISSUE THREAD

**Issue by ccheever** [expo/expo#865]
There seems to be a splash screen issue on iOS on *re*-installs of an app.

https://forums.expo.io/t/splash-screen-issue-with-expo-sdk-22/4238

Steps to repro:
1. Uninstall old app.
2. Reinstall new app from App Store.
3. Tap home icon of my app.

The user speculates that what gets loaded is some cached version of the splash stuff from the previous install of the app.

I can't repro this because I can't currently build anything with turtle with my Apple account right now.

**Comment by terribleben** [comment]
I think there's something in iOS 11+ where iCloud users don't actually get their app's data cleared when they uninstall an app? Maybe?

**Comment by wli** [comment]
@terribleben I don't know about the splash screen specific issue, but I can note that we encountered a similar issue on reinstallations where `SecureStore` values were persisting on latest ios. Not something that we need fixed right now, but sounds kinda similar. Perhaps it's worth documenting somewhere.
