### ISSUE TITLE
Cancel GoogleSignIn process trigger red screen: The operation couldn't be completed

### ISSUE THREAD

**Issue by rdhox** [expo/expo#8658]
### Environment

```bash
 Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.11 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.3
```

*Only iOS Simlulator and iOS device (Expo Client)*

### Steps to Reproduce

After reproducing the code for the Google Signin (https://docs.expo.io/versions/latest/sdk/google/), just try to sign in and press `cancel`. The red screen appear.

### Expected Behavior

Seeing the webview closing and going back to the application.

### Actual Behavior

RedScreen with following error:

```
ExceptionsManager.js:44 Error: ERR_APP_AUTH: The operation couldn’t be completed. (org.openid.appauth.general error -3.)
```

### Reproducible Demo

https://snack.expo.io/@rdhox/googlesigninbug

**Comment by dacevedo12** [comment]
Also happened to me. had to wrap it around a try catch.

**Comment by EvanBacon** [comment]
Sorry for the inconvenience :/ we are planning on revisiting the Google packages soon. Unfortunately the API changes often so the surface area has become large over time. I would suggest using the new AuthSession API which has a guide for using [Google Auth](https://docs.expo.io/guides/authentication/#google). This is also the only solution that supports Expo web as well. 

When using the `Google` module in the Expo client, the package utilizes a legacy system that lets you use a bundle identifier and android package to redirect back to the running app instance (as opposed to the custom URI scheme that Google provides) - this can be unreliable. `AuthSession` uses a proxy website in the Expo client which works the same as web authentication. 

Under the hood `expo-auth-session` and `expo-google` do the exact same thing btw. AuthSession is just a more powerful and better tested solution -- [E2E tests](https://github.com/expo/expo/blob/bf98bea7efd5f4d6257ed7532d963c04050d5f40/apps/native-component-list/src/screens/AuthSession/AuthSessionScreen.tsx#L103-L135).
