### ISSUE TITLE
Building for iOS errors out without information

### ISSUE THREAD

**Issue by pouriaa** [expo/expo#866]
When building an expo project for iOS, the build initiates sucessfully using `exp build:ios`. When checking on the status after a few seconds using `exp build:status`, I get the following response:

```
[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build.
```

I tried the suggested solution in this issue with no success https://github.com/expo/expo/issues/836

More info:
My Build ID: 4ac607d1-87ae-4f2c-8128-a6aa4b4e7102

package.json
```
{
  "name": "myapp",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "jest-expo": "~20.0.0",
    "react-native-scripts": "1.3.1",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^21.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.0",
    "react-native-elements": "^0.17.0",
    "react-navigation": "^1.0.0-beta.11"
  }
}
```

app.json
```
{
   "expo": {
    "name": "My app",
    "icon": "./app/assets/img/logo.png",
    "version": "1.0.0",
    "slug": "tolio",
    "sdkVersion": "21.0.0",
    "ios": {
      "bundleIdentifier": "com.pouriaassadipour.tolio"
    },
    "android": {
      "package": "com.yourcompany.yourappname"
    }
   }
 }
```

**Comment by tcdavis** [comment]
Can you use imagemagick or something to check your app icon / other assets and ensure that the formats match the file extensions?

**Comment by pouriaa** [comment]
@tcdavis I sent the app icon that I'm using to Adam on Slack and he couldn't see anything wrong with it. He said he forwarded my case to the iOS engineer last night. Haven't heard back yet though.

**Comment by pouriaa** [comment]
using imagemagick's `identify` command I found the following details:
```
logo.png PNG 512x512 512x512+0+0 8-bit sRGB 256c 23751B 0.000u 0:00.000
```

Hope this helps debug!

**Comment by terribleben** [comment]
Hey there - we've recently deployed a change that uses a more stable image library on our end, so if this was an app-icon-related issue, that should be fixed now. This issue references an old build id-- if you try again and you're still having trouble, please let us know in a new issue or on our forums.
