### ISSUE TITLE
getExpoPushTokenAsync() never fired

### ISSUE THREAD

**Issue by osoluche** [expo/expo#8668]
When run in iOs device i got an error trying get token; 

OK const req = await Permissions.askAsync(Permissions.NOTIFICATIONS);

FAIL token = await Notifications.getExpoPushTokenAsync();

Fail message
TypeError: null not an object _exponenNotifications.default.getExonentPushTokenAsync

And never can get's token,   in android or with expo client, all works fine !!

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
