### ISSUE TITLE
RNCWKWebView not found

### ISSUE THREAD

**Issue by jfcernel** [expo/expo#8670]
## 🐛 Bug Report

Invariant Violation: requireNativeComponent: "RNCWKWebView" was not found in the UIManager

### Environment

 Expo CLI 3.20.5 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.12 => 37.0.12
      react: ^16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^3.11.1 => 3.13.0

 Target: IOS 

### Steps to Reproduce

I get this error whenever I'm debugging with Expo and I navigate to a page that has a certain component.   The component (react-native-signature-pad) uses the {WebView} from 'react-native-webview' The way I debug with expo is on my Windows 10 machine, I use 'npm start' and then scan the QR code that pops up with my phone. 

### Expected Behavior

 I expect it to not crash?  Since upgrading to expo 37, i have been unable to get this to work.  I was previously on expo 34.0.1, and at one point I had that working but I keep running in circles with npm packages not being the correct version or not running the correct version of node.

### Reproducible Demo

 I can't effectively create a demo as it is a work app and under a lot of security/privacy requirements.

Here is my package.json.  I don't know if i'm using something that is the wrong version?  I have done my best scouring the internet for a solution, however, most of them involve linking and using pod and/or ejecting which none of that applies or works for me since I program on a Windows PC.  I only use the mac to actually create IPA file.  I've had lots of success in the past with using Expo and debugging on Windows, but since this app is not updated too often, it gets out of date and becomes near impossible to catch back up.

> {
>   "name": "project",
>   "version": "0.1.0",
>   "private": true,
>   "devDependencies": {
>     "jest-expo": "^32.0.0",
>     "react-test-renderer": "16.3.1"
>   },
>   "main": "./node_modules/expo/AppEntry.js",
>   "scripts": {
>     "start": "expo start",
>     "eject": "expo eject",
>     "android": "expo start --android",
>     "ios": "expo start --ios",
>     "test": "jest"
>   },
>   "jest": {
>     "preset": "jest-expo"
>   },
>   "dependencies": {
>     "babel": "^6.23.0",
>     "babel-preset-expo": "^8.2.1",
>     "btoa-atob": "^0.1.2",
>     "buffer": "^5.6.0",
>     "expo": "^37.0.12",
>     "expo-cli": "^3.21.5",
>     "lodash": "^4.17.15",
>     "moment": "^2.25.3",
>     "react": "^16.13.1",
>     "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz",
>     "react-native-datepicker": "^1.7.2",
>     "react-native-gesture-handler": "~1.6.0",
>     "react-native-screens": " ~2.2.0",
>     "react-native-select-input-ios": "^1.2.0",
>     "react-native-signature-canvas": "^1.9.0",
>     "react-native-signature-pad": "^0.1.0",
>     "react-native-webview": "8.1.1",
>     "react-navigation": "^3.11.1",
>     "react-navigation-stack": "^1.10.3"
>   }
> }

**Comment by brentvatne** [comment]
can you share your code? what i imagine is happening is that the signature pad library is using an old version of react-native-webview and attempting to access a native module that no longer exists in new versions of the library. please in the future respect our request for reproducible examples in the issue template

**Comment by brentvatne** [comment]
> I can't effectively create a demo as it is a work app and under a lot of security/privacy requirements.

learn more about what a minimal reproducible example is here: https://stackoverflow.com/help/mcve

here is a simple reproducible example of react-native-webview working as expected https://snack.expo.io/@notbrent/carefree-popsicle

happy to look at this if you can create a minimal example to reproduce

**Comment by jfcernel** [comment]
I started working on creating a small demo to see if I could get a reproducible issue.  I used the expo init command to create a new project.  In the new project, it works just fine.  It's the same component, same version, etc.  Is there anything you can think of that could possibly explain why it works with expo init and why it doesn't in my old app?  package.json differences?  expo cli differences?  etc.  I'm banging my head against the wall not understanding why it works with the expo init.

**Comment by jfcernel** [comment]
What I ended up doing was I just literally copied everything in my old app into the new bare expo init project and it worked just fine.  The only differences I could realistically point out was that I was on version 37.0.12 of expo and the expo init uses 37.0.3.
