### ISSUE TITLE
GLView flickering on Android

### ISSUE THREAD

**Issue by odusseys** [expo/expo#868]
Hello

I am currently working with a fork of Expo's GLView (https://github.com/react-community/react-native-webgl) - but the issue seems to also happen with Expo's GLView. 

It only occurs on Android, iOS works just fine. What's happening is I'm getting a "flicker" when animating an object with Threejs. The flickering is due to alternating between 3 different frames. This event happens when not animating, ie. not sending any calls to the GL context. 
We are assuming this is due to triple buffering, and that the buffers are being incorrectly cleared or swapped - note that we are seeing constant SwapBuffer instructions when debugging. 

Removing the EGL_BUFFER_PRESERVED option does not seem to help. 

@nikki93 : tagging you as you've actually helped me with GLView issues before

**Comment by odusseys** [comment]
Other things I've tried : 
- explicitly calling glClear before drawing and glFlush after
- calling setRenderMode(0) on the GLSurfaceView (actually stops working altogether)

**Comment by odusseys** [comment]
@nikki93 
OK so this is definitely a sync issue between js and java, and I'm pretty sure I know how to fix it. 
The problem is that if the screen is not fully redrawn during GLSurfaceView.onDrawFrame(), then the buffers will be swapped and a previous frame (or blank frame if the buffers are empty) will be displayed. 
So clearly, GLSurfaceView requires exactly one frame to be drawn, and the only way to fix this is to synchronise JS and java frames. 
What I suggest is the following : 
- we need a requestAnimationFrame method in javascript, with a callback which is triggered when entering the onDrawFrame() method of GLSurfaceView. This could be on the gl context extension too ?
- onDrawFrame() should sleep while the JS is not done. At the moment we already have a way of knowing if the js is done, as we have the endFrame() method on the gl context extension. 
Would have to rework the bridge extensively tho I think.

**Comment by odusseys** [comment]
I have a fix for this but it is a bit dirty :

set the renderMode to "RENDERMORE_WHEN_DIRTY"
do a requestRender() when calling endFrame (have to add a method to the bridge)
because some of the gl calls are blocking, we need to flush them regularly, and the above will cause a deadlock. The way I solved that is to add another thread which, in a loop, calls queueEvent on the GLSurfaceView, requesting a flush (btw, I don't see why we don't also do this for textures).
This makes it work, with a few caveats:

it seems to break textures again :( might be another concurrency issue, looking into it
Even with WHEN_DIRTY, the GLSurfaceView may perform a few onDrawFrame() calls before it "settles". This means that
It may cause sync issues when initializing the view (gl events being flushed to the wrong frame)
When the app is brought to the background, a new frame is drawn and thus blank.
Needs thoughts.

**Comment by nikki93** [comment]
@odusseys https://github.com/expo/expo/commit/34b3a648a9dd31074ca02ea43f4114bb2dafeecb should fix this issue -- I'm still testing it on various devices and we are hoping to release it in SDK 24. Since it seems you have been testing some native changes anyways, maybe you could build with this change and see how it goes? It will also need this https://github.com/expo/expo-sdk/commit/b34271c1e52599417d889e49c657abdb9aa4da60 minor change in the `expo` npm library.

**Comment by nikki93** [comment]
Closing this for now because I think that change should fix it (at least it does for me) -- feel free to comment here again if you run into it again.
