### ISSUE TITLE
Understanding Release Channels for ExpoKit

### ISSUE THREAD

**Issue by creativemind1** [expo/expo#8689]
Hello,

I've read about the documentation about Release channels many times but It doesn't make me understand how it works. I'm writing here to ask developers how it works.

So let's say I've my iOS App in production which was released with `expo publish --release-channel prod-10`. So let's say I'm making some changes in the native files of iOS and again publish the expo with `expo publish --release-channel prod-10` **but** I've not submitted any build to the AppStore. Does it means my changes are now working in production without submitting existing build to AppStore?

**Comment by tsapeta** [comment]
`expo publish` only updates the JS bundle that is being used by your production app. You should be careful not to publish any breaking changes between native and JS code. By the way, ExpoKit is no longer supported and I recommend switching to the bare workflow instead 🙂
