### ISSUE TITLE
Camera.recordAsync() - fails on Android with an error "setAudioSource failed"

### ISSUE THREAD

**Issue by rintoj** [expo/expo#869]
I am using **sdkVersion: 21.0.0**, and **expo app for android v2.0.0**. I get the following error when I try to do:

```js
 // maxVideoDuration is set to 3
 this.camera.recordAsync({ maxDuration: this.state.maxVideoDuration }).then((video) => {
      this.setState({ video, readyToSend: true });
 });
```

![whatsapp image 2017-10-27 at 11 33 44 pm](https://user-images.githubusercontent.com/10824903/32118625-f89c5c5e-bb6f-11e7-864a-47f91c67edb8.jpeg)

**Comment by tcdavis** [comment]
Could you provide a snack (snack.expo.io) replicating your issue so we can see how this.camera is initialized?

**Comment by markacola** [comment]
I was getting this when I had not yet asked for the `AUDIO_RECORDING` permissions, once I requested that I stopped getting this error.

**Comment by aalices** [comment]
Oh, sorry for not posting here - yes this is related to the permission that weren't requested. Along with SDK 23 the app will no longer crash but reject the action with proper description.
