### ISSUE TITLE
For Bare Workflow, is it mandatory to include expo as a dependency in package.json?

### ISSUE THREAD

**Issue by guanhuay** [expo/expo#8695]
### Please note that discussions opened as issues in the core Expo repository will be closed.

For my project, i used the bare-minimum-template from expo to start off my project. I noticed, in the package.json, there is an expo dependency. I suspect by including this library, it significantly increase my app size.

My question is, by utilize the expo function in bare-workflow, shouldn't we just use the react-native-unimodules, expo-camera and etc be sufficient enough?

What's the point of including expo as dependency?

Thank you for your help.

**Comment by EvanBacon** [comment]
The `expo` package is a [light-weight](https://packagephobia.now.sh/result?p=expo) module that provides a universal entry point (web, native), error handling, and other dev utilities like logging that get stripped in production. It also includes `babel-preset-expo` which provides improved tree-shaking for web projects. 

FWIU you don't need the expo package to use [react-native-unimodules](https://github.com/expo/expo/tree/master/packages/react-native-unimodules) but not having it will make web support and debugging harder to do.

**Comment by brentvatne** [comment]
also using the `expo` package allows you to use expo client as described in https://docs.expo.io/bare/using-expo-client/

you're welcome to remove it though, as @EvanBacon said
