### ISSUE TITLE
Android phone breaks when Camera and ImagePicker are used at the same time.

### ISSUE THREAD

**Issue by verzil** [expo/expo#870]
# Android phone breaks when Camera and ImagePicker are used at the same time.
Hey guys i'm building an application that use both Camera and ImagePicker. I've noticed that if i have Camera open once, and use ImagePicker. When i resolve the ImagePicker the application crashes due to unable to reclaim camera access. The error message from adb logcat says its not able to obtain camerav2 api, because a client with higher priority is using it. And I am unable to close the Camera module, once the camera is mounted is once. 

This issue does not happen on iOS 11, and Huawei P9 Android 7.0,
 but crashes on Nexus 6P Android 8.0 and BLU Vivo XL Android 6.5.

Here is a snack for you to test it out
https://snack.expo.io/ryaLUgZA-

**Comment by tcdavis** [comment]
Thanks for the snack!  I'm not able to replicate on a Galaxy S6 Android 7.0

**Comment by verzil** [comment]
Thanks for the fast reply. I don't know how obvious is on the expo snack. When you snap a picture with ImagePicker camera, there should be an Image component on screen displaying the captured image. If that Component is not there that means, the app has crashed and restarted. (it happens really fast for some reason) 

It does not happen with all android phones i've noticed.

I Checked the logcat logs, its always about unable to claim camera.
I am wondering if its because we never release the camera when unmounting a component?

Should be include an api for explicit camera termination, within the Camera Api.

I've included a logcat showing what I think it relevant to this problem
10-27 15:24:21.643   373   998 D CameraService: [getCameraInfo] id:0 NumberOfCameras:2 
10-27 15:24:21.643   373   998 D MtkCam/devicemgr: [getDeviceInfo] deviceId:0 device_version:0x100 facing:0 orientation:90
10-27 15:24:21.643   373 15730 D MtkCam/ImageTranform: [execute] -
10-27 15:24:21.644   373 15730 D MtkCam/ITNode: [0:onReturnBuffer] data 501, buf 0xe4e4ed00
10-27 15:24:21.644   373 15730 D MtkCam/DBHdl: [:enqueBuffer]buf(0xe4e4ed00),VA(0xe0378000),BS(307200),Id(438),TS(4704.296819),F(0x32315659),S(640x480),Str(640,320,320)
10-27 15:24:21.644   373 15730 D MtkCam/DataBufHdl: [returnBuffer] data 41 buf 0xd1a02280 flag 0x1
10-27 15:24:21.644   373 15730 D MtkCam/ITNode: [0:threadLoopUpdate] -
10-27 15:24:21.644   373 15716 D MtkCam/DisplayClient: [handleReturnBuffers] + (33) (29), Show frame:0 1 [ion:438 0xe0378000/460800 4704296819000]
10-27 15:24:21.648   373 15716 D MtkCam/DisplayClient: [handleReturnBuffers] -
10-27 15:24:21.650   373  1076 I CameraService: CameraService::connect call (PID 15486 "host.exp.exponent", camera ID 0) for HAL version default and Camera API version 1
10-27 15:24:21.650   373 15716 D MtkCam/DisplayClient: [waitAndHandleReturnBuffers] +
10-27 15:24:21.650   373  1076 I CameraService: i(0) pid(15486) priorities(2),Priority(2147483645)
10-27 15:24:21.650   373  1076 E CameraService: CameraService::connect evicting conflicting client for camera ID 0
10-27 15:24:21.651   373  1076 D CameraClient: disconnect E (pid 373)
10-27 15:24:21.651   373  1076 D CameraClient: hardware teardown

Thanks in Advance!

**Comment by wlwg** [comment]
Anyone who has this problem please go vote for this feature request https://expo.canny.io/feature-requests/p/explicit-openclose-methods-for-camera

**Comment by sibelius** [comment]
you can check this PR https://github.com/lwansbrough/react-native-camera/pull/859
