### ISSUE TITLE
Warning from upgrade to sdk 36 from 35

### ISSUE THREAD

**Issue by kamalpandey** [expo/expo#8700]
expo > babel-preset-expo > @babel/plugin-proposal-decorators > @babel/helper-create-class-features-plugin@7.10.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "expo > babel-preset-expo > @babel/plugin-proposal-decorators > @babel/plugin-syntax-decorators@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/helper-compilation-targets@7.10.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-class-properties@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-dynamic-import@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-json-strings@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-nullish-coalescing-operator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-numeric-separator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-object-rest-spread@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-optional-chaining@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-private-methods@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-class-properties@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-numeric-separator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-syntax-top-level-await@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-arrow-functions@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-async-to-generator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-block-scoped-functions@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-block-scoping@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-classes@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-computed-properties@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-destructuring@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-dotall-regex@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-duplicate-keys@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-exponentiation-operator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-for-of@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-function-name@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-literals@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-member-expression-literals@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-modules-amd@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-modules-commonjs@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-modules-systemjs@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-modules-umd@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-named-capturing-groups-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-new-target@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-object-super@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-parameters@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-property-literals@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-regenerator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-reserved-words@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-shorthand-properties@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-spread@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-sticky-regex@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-template-literals@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-typeof-symbol@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-unicode-escapes@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/plugin-transform-unicode-regex@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "expo > babel-preset-expo > @babel/preset-env > @babel/preset-modules@0.1.3" has unmet peer dependency "@babel/core@^7.0.0-0".

**Comment by byCedric** [comment]
Hi! Please use the issue template when filing issues. I understand that these are warnings when upgrading, but I have no idea about
- if this is related to NPM or Yarn
- what version of the CLI you are using
- what environment you are running

Without that, it's really hard for us to reproduce it. Luckily, this shouldn't be a blocking issue at the moment because those are warnings and not errors. If this causes issues for you, you can try reinstalling `node_modules` with either yarn or npm. If that doesn't help, feel free to open a new issue with the information-filled from the template.

Hope it helps 😄
