### ISSUE TITLE
[ Web ] expo-updates not retrieving latest version

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo#8701]
### Summary of Issue (just a few sentences)

`expo-updates` does not work reliably on web.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
 Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.12 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.1
```

### Reproducible Demo

Not a repro since that requires a full project, but if you want me to set up a full project for this let me know.

```
import * as Updates from 'expo-updates'
import * as Network from 'expo-network'
import { log, catcher, Dialogue } from '../helpers'
import { dev } from '../apis/platform'

const connectivityCheck = f => Network.getNetworkStateAsync().then( ( { isInternetReachable } ) => isInternetReachable ).catch( f => false )

export const updateAvailable = async f => {
	const internet = await connectivityCheck()
	if( internet ) return Updates.checkForUpdateAsync().then( ( { isAvailable } ) => isAvailable ).catch( f => false )
	else return false
}

export const updateIfAvailable = async f => {

	if( dev ) return log( `Update checking triggered, doesn't work in development mode though` )

	const available = await updateAvailable()
	if( !available ) return false
	
	try {
		await Updates.fetchUpdateAsync()
		await Dialogue( 'An update is available!', 'Do you want to restart the app now?', [{
			text: 'Yes, restart',
			onPress: f => Updates.reloadAsync()
		} ] )
		return true
	} catch( e ) {
		catcher( e )
	}



}
```

### Steps to Reproduce

1. Use `expo-updates`
2. Manually check for updates
3. No updates load on android/ios but not web

### Expected Behavior vs Actual Behavior

When an update check is triggered it should reload the cached PWA files to use the new versions.

**Comment by esamelson** [comment]
Hey there! Unfortunately `expo-updates` does not yet support web. This is something we'd like to do in the future but cannot promise on any given timeline. I noticed the docs erroneously state that this module DOES support web, so I've just pushed a change correcting that. Apologies for the confusion! 😞

**Comment by actuallymentor** [comment]
@esamelson I'd be happy to work on this and make a PR if you have some pointers.

I see that the web version is done through `workbox` in the `webpack-cli`. If I read the [google PWA lifecycle docs](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates) and [MDN service worker messaging docs](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/message_event) correctly this functionality would require:

1. A listener on the service worker
2. A message-sender in the `expo-updates` module

If you would like I can draft 2 PRs in the respective repositories.

**Comment by actuallymentor** [comment]
@esamelson / @EvanBacon I know you closed this, but would you appreciate me drafting a PR based on my previous comment or not?
