### ISSUE TITLE
GLView Demo !!!

### ISSUE THREAD

**Issue by MuZeQiu** [expo/expo#8702]
GLView Demo !!!

**Comment by byCedric** [comment]
Hi @MuZeQiu! Thanks for the issue report. Unfortunately, this isn't a proper filled issue. If you would like to request a specific example, please check out the [`expo/examples`](https://github.com/expo/examples) repo. I think [this issue](https://github.com/expo/examples/issues/73) is already created over there. If not, feel free to open a new request in that repo.

Hope it helps.

**Comment by cruzach** [comment]
@MuZeQiu if you'd like to make a PR to add a GLView demo to the docs, it'd be very much appreciated!
