### ISSUE TITLE
[docs] [react-native-unimodules] recent README.md instruction crash on startup in iOS

### ISSUE THREAD

**Issue by wood1986** [expo/expo#8706]
https://github.com/expo/expo/blob/master/packages/react-native-unimodules/README.md

```diff
-@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>
+@interface AppDelegate : UMAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate>
```

If I change it back to `UIResponder`, it runs

**Comment by RatebSeirawan** [comment]
+1

**Comment by sjchmiela** [comment]
The cited diff makes sure that `AppDelegate`'s superclass is `UMAppDelegateWrapper`, which is required for unimodules to work properly. `UMAppDelegateWrapper` is a simple class that makes sure that all the `UIApplicationDelegate` method calls are forwarded on unimodules' _application delegates_ if they need. Thus, it's probably not a problem of documentation but of some inner component or app's configuration.

To let me help you I would need some more information on the crash — the stack trace, where does it happen, do you have some special 3rd party library integrated? I know Flipper has caused some trouble for the developers—see https://github.com/expo/expo/issues/8723#issuecomment-641164673.

**Comment by wood1986** [comment]
I close this one and use 8723 to discuss
