### ISSUE TITLE
WebBrowser.openBrowserAsync with package parameter not working

### ISSUE THREAD

**Issue by jambanagar** [expo/expo#8707]
## 🐛 Bug Report

WebBrowser.openBrowserAsync() with package parameter set to "com.android.chrome" does not automatically open chrome rather it shows browser selection dialog on Android.

com.android.chrome

`WebBrowser.openBrowserAsync("https://facebook.com", {package: 'com.android.chrome'})
`

1. Install chrome for Android and at least one other browser app in your device such as firefox or edge for Android
2. When using the about code with package set to 'com.android.chrome' it opens the browser selection dialog or the default browser

If chrome is installed it should have opened chrome.

**Comment by jambanagar** [comment]
It looks like the documentation might be incorrect. If I set the key to "browserPackage" instead of "package" it works.

Please confirm.

**Comment by lukmccall** [comment]
Hi @jambanagar, you are right. This argument should be called `browserPackage`. I've changed the documentation.
