### ISSUE TITLE
undefined Errors in exp

### ISSUE THREAD

**Issue by tcdavis** [expo/expo#871]
If you were logged in to exp before Thursday Oct 26th, you can encounter errors when running exp commands, including:

exp start: "Error starting tunnel: XDLError: TypeError: Cannot read property ‘toLowerCase’ of undefined"
exp w: "Unexpected Error: Couldn't get user information"
exp login: "You are already logged in as undefined. Log in as new user?"

These issues can be resolved by signing out and back in.

**Comment by mlg87** [comment]
for some reason my app was still working in android studio, but not in xcode. however, thanks for help @tcdavis. all is well in the universe again

**Comment by kseidel92** [comment]
Thanks a lot for that help! solved for me

**Comment by brynnb** [comment]
THANK YOU! I spent hours today trying to fix this. Was frustrating for my `exp start` to suddenly stop working overnight with no changes.

**Comment by sbahn123** [comment]
So Thanks!

**Comment by LeiZeng** [comment]
Thank you. 

Such a wired issue!!

**Comment by dexterlv** [comment]
Cannot read property ‘toLowerCase’ of undefined problem is gone after logout/login procedure. But now new error of "Starting tunnels timed" out is showing every time I start a project.

**Comment by BWillis98** [comment]
I was also getting a tunneling error, but after I logged out and logged back in, that was resolved as well.
