### ISSUE TITLE
Android adaptive Icon not display 

### ISSUE THREAD

**Issue by fredcox** [expo/expo#8710]
### Summary of Issue (just a few sentences)
I edit my app.json with following lines

> "android": {
>       "package": "me.fredlins.questoespython3",
>       "adaptiveIcon": {
>         "backgroundColor": "#ffffff",
>         "foregroundImage": "./assets/icon.png"
>       }
>     }

The app icon continue with square borders. I want white background for square borders .
![Screenshot_20200607_112056](https://user-images.githubusercontent.com/65084421/83972543-1c917e00-a8b7-11ea-8538-8a4be5533f60.jpg)

**Comment by cruzach** [comment]
duplicate of https://github.com/expo/expo/issues/7374
