### ISSUE TITLE
expo-av OnPlaybackStatusUpdate Android Weirdness

### ISSUE THREAD

**Issue by happyruss** [expo/expo#8711]
### Summary of Issue (just a few sentences)
When attempting to use 2 expo-av players on a single component to implement a cross-fader on itself, this works fine in iOS, but in android, the playbackStatusUpdate is triggered multiple times for one of the players and almost never for the other.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.9 => 37.0.9 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.1
Targeting Android

### Reproducible Demo
https://github.com/happyruss/expo-fader-loop

### Steps to Reproduce
Run the demo and wait 30 seconds for the looping to begin. Notice it works fine in iOS but Android the bevavior is odd, starting with the fact that the same callback is called multiple times for the 1st player, and after 30 seconds, the second player's callback is not called in the loop

### Expected Behavior vs Actual Behavior
It should behave like iOS.

**Comment by sheshashayan** [comment]
I have exactly the same issue. Any work around for the same..?
