### ISSUE TITLE
Inconsistent AsyncStorage location after ejecting [iOS][Android]

### ISSUE THREAD

**Issue by luizjr92** [expo/expo#8712]
I had an app running on Expo SDK 37 Managed Workflow that used Firebasejs for auth, the current user auth information was kept (by firebase) using RN's AsyncStorage.

After ejecting and republishing the app, the AsyncStorage is pointing to a different location. The bundle id is the same.

On TestFlight I'm able to switch builds and verify that the managed build is logged in w/ Firebase as one user and the ejected build is logged in as a different user, they are both keeping track of the current user in different locations.

The firebasejs version is the same on both builds (7.9.0)

This is bad because the new update kicked out everybody out of their accounts. Is there any way I can make a new build (using the bare workflow) that will keep the same AsyncStorage location of the previous build (that used the managed workflow)?

I don't use RN's AsyncStorage for anything else.

How to reproduce this error:
1. Build app using RN's AsyncStorage on Managed Workflow
1. Save anything with AsyncStorage
1. Eject the same app
1. Build it an publish as an update
1. Verify that on the new build AsyncStorage is using a different location
1. Reinstall original build (managed workflow)
1. Verify that AsyncStorage still has the content you put there on step 2

**Comment by cruzach** [comment]
Hi! sorry about this, we're aware of the issue and are tracking it here - https://github.com/expo/expo/issues/8220

For now, you'll have to migrate that data manually while we come up with a better solution.
