### ISSUE TITLE
Missing SecureStore and AsyncStorage data migrating from Expokit to Bare

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#8713]
### Summary of Issue
When I want to migrate a project from Expokit to Bare it lost all SecureStore and AsyncStorage data.

### Environment
```
  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.21.5
```

The Issue appear in iOS and Android

### Reproducible Demo

- You must have an Expokit project
- Save data in SecureStore
- Save data in AsyncStorage

### Steps to Reproduce

1. You must have an Expokit project
2. Save values in SecureStore and AsyncStorage with the key `mykey`
3. Run on your device
4. Create another project with the same Bundle ID and Application ID
5. Run `expo eject` to create a Bare project
6. Install SecureStore with `expo install expo-secure-store`
7. Run on your device and read the key `mykey`
8. You will receive null values

### Expected Behavior vs Actual Behavior

The values of SecureStore and AsyncStorage must be exists.
The values of SecureStore and AsyncStorage are null.

### The problem is...

When you use Expokit all values are saved with a prefix in the key (prefix = `@username/project-name`). Your key is converted internally to `@username/project-name-mykey`

Instead in Android the shared preferences are saved on files with scaped prefix too. Ex:
```
shared_prefs/%40username%2Fproject-name-SecureStore.xml
databases/RKStorage-scoped-experience-%40username%2Fproject-name-journal
databases/RKStorage-scoped-experience-%40username%2Fproject-name
```

**Comment by cruzach** [comment]
hey @RodolfoGS , sorry about this behavior 🙁 

But i think it'd be better to keep track of this in https://github.com/expo/expo/issues/8220 since it already covers AsyncStorage there. It might be useful to also test `expo-sqlite` as well to see if you lose that data?
