### ISSUE TITLE
Unable to resolve “../../App” from “node_modules/expo/AppEntry.js”

### ISSUE THREAD

**Issue by nomi9995** [expo/expo#8715]
### Summary of Issue 
I am making a CLI `create-expo-library` npm package so user can make expo packages easily. my CLI is create template which have example directory to test but when i try to expo start in example directory then i get this error

### Environment
```
 Expo CLI 3.21.6-alpha.0 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.15.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.6-alpha.0
```

### Steps to Reproduce
https://github.com/nomi9995/create-expo-library
this repo is my CLI repo and now it is in development.
clone this repo
install node_module by npm or yarn
enter command on terminal `yarn link`
enter command on create-expo-library
giving basic info to create library
Goto example folder
enter `yarn start` and press i to open in IOS simulaot
then you will get this error

## Sometime resolve
if i change name of example folder sometime it fix and run from other name folder but after some time it gives same error then i have to again change of folder name

i have tried this but nothing fix https://github.com/GeekyAnts/vue-native-core/issues/117#issuecomment-520403713

### Expected Behavior vs Actual Behavior
when i start my example project then metro bundler should not give this error

**Comment by nomi9995** [comment]
@terribleben @brentvatne @byCedric can you help me

**Comment by byCedric** [comment]
Hi @nomi9995! It looks like you want to set up a monorepo-like structure, with the library and example packages. For that, you will have to do some additional configuration. You can try using [this library](https://www.npmjs.com/package/expo-yarn-workspaces) that we built for this use case, or [check out this guide](https://dev.to/expolovers/how-to-insert-an-expo-project-in-a-monorepo-5ab0). I'll close this issue because this isn't related to an issue in Expo.

Hope it helps!
