### ISSUE TITLE
Cannot find entry file node_modules/expo/AppEntry.js in any of the roots on build or publish

### ISSUE THREAD

**Issue by rafetkhallaf** [expo/expo#872]
Hi,

I've been facing this issue since I've started using Expo. IF i stasrt a new project and place my app.js, app.json, and package.json with the default expo files. everything works fine, publish and build. and also the app works with no issues.

if I work on another, then come back later to the first project I was working on, and tried either publish or build, via the ExpoXDE or the CLI I get the same error. My only solution for this issue was to make a copy of the custom files of my project, remove the project files, create a new project, and then copy back my files and build or publish the project.

I'm using latest version of watch, npm4 (and npm5 on another machine), ExpoXDE latest version on the website, exp --version 45.0.2 (all thought I've been having the same issues on previous versions).

The complaint is about the node_modules/expo/AppEntry.js file. and I've checked every time this error shows up, and the file does exists.

since this only happens when I switch between projects. I'm I suppose to do something before switching between projects?

The building log:
[exp] Making sure project is set up correctly...
[exp] Your project looks good!
[exp] Checking if current build exists...

[exp] No currently active or previous builds for this project.
[exp] Checking for existing Apple credentials...
[exp] Validating Apple credentials...
[exp] Credentials valid.
[exp] Validating distribution certificate...
[exp] Validating app id...
[exp] Validating push certificate...
[exp] Starting build process...
[exp] Unable to find an existing exp instance for this directory, starting a new one...
[exp] Starting React Native packager...
[exp] Scanning folders for symlinks in c:\xampp\htdocs\cirrb-app\node_modules (38ms)
[exp] Loading dependency graph.
[exp] Running packager on port 19003.
[exp] Publishing...
[exp] Building iOS bundle
[exp] Dependency graph loaded.
[exp] Failed building JavaScript bundle.
**[exp] Cannot find entry file node_modules/expo/AppEntry.js in any of the roots: ["c:\\xampp\\htdocs\\cirrb-app"]
[exp] Packager URL http://localhost:19003/node_modules/expo/AppEntry.bundle?dev=false&minify=true&hot=false&assetPlugin=c:\xampp\htdocs\cirrb-app\node_modules\expo\tools\hashAssetFiles&platform=ios returned unexpected code 404. Please open your project in the Expo app and see if there are any errors. Also scroll up and make sure there were no errors or warnings when opening your project.**

Any help or guidance is appreciated.
Thank you!

**Comment by tcdavis** [comment]
I'd stick to npm 4 since we've found it to be more reliable.

If c:\xampp\htdocs\cirrb-app\node_modules\expo\AppEntry.js exists, it feels like this might be a permissions issue, although I'm not great with windows :(

I suspect some part of your workflow is getting the project into a bad state, and then neither of them is about to build the project.  See if you can track down what part of your work flow is triggering this? Try switching in exp, xde, any other tools you use one by one to help us narrow down where this is coming from.

**Comment by rafetkhallaf** [comment]
@tcdavis We'll I don't think it's permission issue almost 100% sure, but i will check again just to make sure.

I also tried to see if one of the tools is causing the issue, but it happened with all of them. and honestly i thought it would be something that would be fixed with the new update. since it wasn't, thought I'd post it here in case somebody else faced the same issue.

Currently I found a work around which is removing the app from expo.io website and publishing again or building again. for some reason that seems to make it work just fine.

does this make any scenes?

**Comment by rafetkhallaf** [comment]
@tcdavis ok so, turns out even remove the project from expo online is not related. I just finished building the first project, and now went to the other one and tried to publish it and didn't work, showing the same message.

**Comment by btk** [comment]
@rafetkhallaf Have you tried removing your node_modules and installing npm `npm install` again? 

Or maybe updating `exp-cli` manually?

**Comment by rafetkhallaf** [comment]
@btk I did try removing the node_modules and running npm install. that didn't help.

If it's only me running with this issue then it's my machine for sure. maybe because i'm using NetBeans or something. I thought it was a wide issue.

If you guys want us to proceed and figure it out, i'll be more than happy if it will help make Expo better.

**Comment by terribleben** [comment]
As far as we know this issue isn't widespread. If you can find any other info to help pin down the cause, we'd appreciate it.

You might try checking out the contents of `your-project/.expo` and seeing if that changes when the issue happens.

**Comment by rafetkhallaf** [comment]
@terribleben we'll it's not netbeans for sure, and it's not something that is effecting the files, I started using a different editor (Visual Studio) and same issue still. I checked .expo folder content didn't change.

i'm only using the npm install and then npm install --save react-navigation (if that helps anybody) but even then everything works fine. it's only when i switch to another project and do build or publish then switching back the problem happens and it's only me in the team (and i'm the only windows user)

It feels as if when expo tries to publish its trying to contect to another project that's why it cannot fine the /node_module/expo/AppEntry.js file. I only say this because this error only happens if i switch projects. I can leave the project, restart the computer and everything will work fine, it's once i switch to a different project then come back this would happen.

i'm not well familiar with the exact details in how expo operate. but even when i visit the url in the error message it actually hows 404 error. could it be ports issue?

**Comment by rafetkhallaf** [comment]
For anybody who might face this issue in the future. It turned out to be a configuration issue with the devices that we were using in the office along side with the editor netbeans settings that we have set.

Thank you all for the help. i will close this issue now.
