### ISSUE TITLE
@expo/av doesn't support audio recording on web

### ISSUE THREAD

**Issue by WazzaJB** [expo/expo#8721]
### Summary of Issue (just a few sentences)
The documentation claims full support for this library on the web, however the recording aspect is missing.

`src/ExponentAV.web.ts` has empty methods for recording at the bottom:

```
/* Recording */
  //   async setUnloadedCallbackForAndroidRecording() {},
  async getAudioRecordingStatus() {},
  async prepareAudioRecorder() {},
  async startAudioRecording() {},
  async pauseAudioRecording() {},
  async stopAudioRecording() {},
  async unloadAudioRecorder() {},
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```Expo CLI 3.21.3 environment info:
    System:
      OS: macOS Mojave 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.3
```

### Reproducible Demo
Add expo-av to a project, and call:

```
 const recording = new Audio.Recording();

    try {
      await recording.prepareToRecordAsync(
        Audio.RECORDING_OPTIONS_PRESET_HIGH_QUALITY
      );
      await recording.startAsync();
      // You are now recording!
    } catch (error) {
      // An error occurred!
      console.log(error);
    }
```

On web, this will throw:

```
TypeError: Cannot read property 'uri' of undefined
```

I'm going to have a go at creating a PR for this, which may at least lay out the bones of it for someone to pick up? But thought it best to create an issue first.

Thanks for everything that Expo brings to React Native!

**Comment by byCedric** [comment]
Hi @WazzaJB! Thanks for mentioning this, we should properly reflect the state of web implementation in the docs. I'll create a PR to fix that part, but I think others can benefit from good web support as well. Any help making this possible is greatly appreciated, I'd be happy to check your PR 😄

**Comment by WazzaJB** [comment]
Thanks for the feedback @byCedric.

I have made some good progress, but am struggling with testing.

I have added the Recording tests (as they are) to `TestSuite-test.web.js`, but I wanted to check what is the correct/best approach for this?

If I wanted to test in a dummy project, how would I best do that within the context of the expo project? I think it might help me to move faster on immediate development versus re-running the test manually (even when commenting out other tests, time to startup etc on `yarn test:web` is high).

Thanks!

**Comment by WazzaJB** [comment]
I have started the outlines of a PR above.

In order to test this in terms of real world, am I best to just manually copy the `expo-av` build files into a project?

Thanks,
Warren

**Comment by byCedric** [comment]
That's one way of testing, and because this should be a JS-only change you won't have to do anything with the Expo Client to get it working. We also have the [Native Components List app](https://github.com/expo/expo/tree/master/apps/native-component-list) with everything ready to test. You can use that too 😄

**Comment by WazzaJB** [comment]
Thanks @byCedric.

Can confirm this PR works (have it working in my app) and the audio plays.

**Comment by byCedric** [comment]
Awesome, thanks for that! I should be able to test your PR soon. Waiting on some hardware before I can do that.

**Comment by WazzaJB** [comment]
No pressure, I'm going to use `patch-package` to keep my project moving 😄 

Thanks ✌️

**Comment by Federkun** [comment]
Thanks for this WazzaJB. I'll apply this patch on the project i'm working on as well. Will report any feedback if I do have any.

**Comment by WazzaJB** [comment]
> Thanks for this WazzaJB. I'll apply this patch on the project i'm working on as well. Will report any feedback if I do have any.

You're most welcome @Federkun, just let me know if you hit any issues etc and I'll do my best to help or update the PR. Any feedback is greatly appreciated :)

**Comment by Federkun** [comment]
Works great!
But I had to make some minor changes to make it work after rebasing against master. This is the patch that I applied on top of your PR:

```diff
diff --git a/packages/expo-av/src/ExponentAV.web.ts b/packages/expo-av/src/ExponentAV.web.ts
index be5f98d090..b136cf312d 100644
--- a/packages/expo-av/src/ExponentAV.web.ts
+++ b/packages/expo-av/src/ExponentAV.web.ts
@@ -1,7 +1,6 @@
 import { SyntheticPlatformEmitter } from '@unimodules/core';
 
 import { AVPlaybackNativeSource, AVPlaybackStatus, AVPlaybackStatusToSet } from './AV';
-
 import { RECORDING_OPTIONS_PRESET_HIGH_QUALITY } from './Audio/Recording';
 
 function getStatusFromMedia(media?: HTMLMediaElement): AVPlaybackStatus {
@@ -86,6 +85,7 @@ function setStatusForMedia(
 }
 
 let mediaRecorder: null | any /*MediaRecorder*/ = null;
+let audioChunks: Blob[] = [];
 
 export default {
   get name(): string {
@@ -187,6 +187,8 @@ export default {
       options?.web || RECORDING_OPTIONS_PRESET_HIGH_QUALITY.web
     );
 
+    audioChunks = [];
+
     return { uri: null, status: await this.getAudioRecordingStatus() };
   },
   async startAudioRecording() {
@@ -200,6 +202,10 @@ export default {
       mediaRecorder.resume();
     } else {
       mediaRecorder.start();
+
+      mediaRecorder.addEventListener('dataavailable', event => {
+        audioChunks.push(event.data);
+      });
     }
 
     return this.getAudioRecordingStatus();
@@ -227,14 +233,15 @@ export default {
       return { uri: null, status: this.getAudioRecordingStatus() };
     }
 
-    const dataPromise = new Promise(
-      resolve => (mediaRecorder.ondataavailable = e => resolve(e.data))
-    );
+    const objectUrl = new Promise(resolve => {
+      mediaRecorder.addEventListener('stop', () => {
+        const url = URL.createObjectURL(new Blob(audioChunks));
+        resolve(url);
+      });
+    });
 
     await mediaRecorder.stop();
-
-    const data = await dataPromise;
-    const url = URL.createObjectURL(data);
+    const url = await objectUrl;
 
     return { uri: url, status: await this.getAudioRecordingStatus() };
   },
```

When testing, `dataPromise` never resolved. But apart from that, I'm able to record and replay audio just fine.

A minor feedback: I think it would be better for `requestPermissionsAsync` on web to result on a noop

**Comment by WazzaJB** [comment]
Thanks so much for the feedback @Federkun ! Out of curiosity, what browser were you testing on?

Using the `ondataavailable` callback works fine for me in Chrome.

**Comment by Federkun** [comment]
Chrome as well. If I do get some time, i'll check again

**Comment by inglesuniversal** [comment]
Would the audio playback feature (web based) be release with SDK 43?

Thanks so much for your awesome work!

**Comment by EvanBacon** [comment]
This appears to have been completed in https://github.com/expo/expo/commit/dc7b526e48fb6dcb528c5c4c52d121fd1a779fe7

**Comment by inglesuniversal** [comment]
@EvanBacon good evening, how soon will this update be visible under the current Expo API list? Namely:

https://docs.expo.dev/versions/v43.0.0/sdk/audio/

Thanks
