### ISSUE TITLE
[unimodules] App doesn't launch on RN 0.62.2

### ISSUE THREAD

**Issue by mfkrause** [expo/expo#8723]
I've tried to set-up unimodules on a bare RN 0.62.2 project. During the configuration process, I've already encountered some differences to the documentation (especially when it comes to Flipper, which has newly been implemented in RN 0.62 and was missing in the example AppDelegate files).
These are my AppDelegate.m and AppDelegate.h as of now:

**AppDelegate.m**
```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <UMCore/UMModuleRegistry.h>
#import <UMReactNativeAdapter/UMNativeModulesProxy.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>

#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@interface AppDelegate () <RCTBridgeDelegate>

@property (nonatomic, strong) UMModuleRegistryAdapter *moduleRegistryAdapter;

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
  
#if DEBUG
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"internationalsos"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [super application:application didFinishLaunchingWithOptions:launchOptions];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
    NSArray<id<RCTBridgeModule>> *extraModules = [_moduleRegistryAdapter extraModulesForBridge:bridge];
    // If you'd like to export some custom RCTBridgeModules that are not Expo modules, add them here!
    return extraModules;
}

@end
```

**AppDelegate.h**
```
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>
#import <UMCore/UMAppDelegateWrapper.h>

@interface AppDelegate : UMAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate>

@property (nonatomic, strong) UIWindow *window;

@end
```

The app does not launch whatsoever. When run from Xcode, it crashes in Pods/FlipperKit/FlipperKitUserDefaultsPlugin/FKUserDefaultsSwizzleUtility.m in line 62 with the code EXC_BAD_ACCESS:
```
      if (blk != nil) {
        NSString* originalStr =
            [@"comfacebookFlipperKit_" stringByAppendingString:selStr];
        [invocation setSelector:NSSelectorFromString(originalStr)];
        block(invocation); // Crash
      } else {
        ((void (*)(id, SEL, NSInvocation*))orig)(this, fwdSel, invocation);
      }
```

Here's the dump from the console:
```
2020-06-08 09:50:38.626942+0200 Intl. SOS TeleDoctor24[15636:4330951] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2020-06-08 09:50:38.626982+0200 Intl. SOS TeleDoctor24[15636:4330951] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
flipper: FlipperClient::addPlugin Inspector
flipper: FlipperClient::addPlugin Preferences
flipper: FlipperClient::addPlugin React
flipper: FlipperClient::addPlugin Network
2020-06-08 09:50:39.000 [info][tid:main][RCTRootView.m:294] Running application internationalsos ({
    initialProps =     {
    };
    rootTag = 1;
})
(lldb) 
```

(I've already tried to add the two background modes by the way.)
When I disable the line `InitializeFlipper(application)` in AppDelegate.m, the app then crashes in main.m in line 7:
```
#import <UIKit/UIKit.h>

#import "AppDelegate.h"

int main(int argc, char * argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class])); // Crash
  }
}
```

**Comment by todorone** [comment]
Confirming immediate crash on iOS bare workflow project when setting up due to unimodules setup instruction.

@tsapeta The new instruction(https://github.com/expo/expo/pull/8683) is much better than previous one, but I guess something is missed in it, bc it leads to crash...

**Comment by wood1986** [comment]
see https://github.com/expo/expo/issues/8706

**Comment by sjchmiela** [comment]
Hey all, I've just verified that I got Flipper running alongside Unimodules. The project, created by:

- `expo init` a bare workflow app ([init](https://github.com/sjchmiela/flipper-with-unimodules/commit/185d62f05cc935c52f21e532facfb2af13cabfd2), [small stuff](https://github.com/sjchmiela/flipper-with-unimodules/commit/c2ae7c434d039e1f4b7f6ede7957b365ad2e7987))
- upgrading React Native to 0.62.2 ([upgrading dependencies and Podfile](https://github.com/sjchmiela/flipper-with-unimodules/commit/a9062549525c659a2d8983ec8b5479d4383525d4), [reinstalling Pods](https://github.com/sjchmiela/flipper-with-unimodules/commit/bdf9b43befa37de2f4691dc86678a64c4c7849dc))
- adding and integrating Flipper ([adding to Podfile](https://github.com/sjchmiela/flipper-with-unimodules/commit/77cafe29c6c41a1bbd4f683c7137b49372328852), [integrating into project](https://github.com/sjchmiela/flipper-with-unimodules/commit/4fda2a0a39f3e72394f05e6625bc4c6579f6daaf))

is available at https://github.com/sjchmiela/flipper-with-unimodules.

Let me know if this issue still exists or if there's still something wrong! 🙂

**Comment by MrFaisal100** [comment]
I am having the exact issue ,, with new project created with RN.0.62.2
I tried to follow the project settings https://github.com/sjchmiela/flipper-with-unimodules but still same issue

**Comment by sjchmiela** [comment]
The project was created the other way around — first, it was a unimodules project and only then I upgraded it to RN 0.62.2 and added Flipper. How did you initialize your project? I'll try to go through the process like you would do and find the bug this way. Or could you provide me with a preconfigured repository I could clone and tinker around with?

**Comment by MrFaisal100** [comment]
If you share you email I would grant you access to my gitlab project

**Comment by sjchmiela** [comment]
Please contact me on [Expo's Slack](https://slack.expo.io), the username is @sjchmiela, I'd rather not share my public e-mail in plaintext here. 🙂

**Comment by MrFaisal100** [comment]
Messaged you on slack

**Comment by mfkrause** [comment]
Thanks a lot @sjchmiela, updating to the next tag indeed fixed it.
Going to close this issue.

**Comment by tanoto-the-explorer** [comment]
@sjchmiela Thank you so much! I have spent 2 days searching for this problem and yours are the one that actually helped me!

**Comment by arun537** [comment]
I have the same issue. Also, updated to the latest version

@synthesize window = _window; 

but not getting the project to run on iOS

**Comment by arun537** [comment]
Thank You, So much for the fix
