### ISSUE TITLE
[exp] Cannot start new build, as there is a build in progress.

### ISSUE THREAD

**Issue by rafetkhallaf** [expo/expo#873]
This message have been stuck for hours now. and i'm sure there's something wrong.

based on what i read online, I believe this have to be done by Expo internal team. but one of the comments on the same issue the developer mentioned that he created a new account and managed to get his task done. I was wondering if removing my expo account and creating it again as a temporary solution to the issue.

Also what am I suppose to do now?

**Comment by tcdavis** [comment]
Sorry about that, I've cleared your build, so you should be able to kick it off again whenever you want.
We are working to make this process more reliable and transparent, and allow you to resolve issues like this without having to create a ticket

**Comment by adam-risberg** [comment]
My build has also been stuck in this state for some days now. Can you please kill it? Also the build-url I got from expo was https://expo.io/builds/0ed008d6-f759-44a3-bf75-51c48458e339 but it only return "internal server error".
