### ISSUE TITLE
In-App expo purchase 

### ISSUE THREAD

**Issue by miradario** [expo/expo#8732]
We are working on the in-app expo package. With some difficulty but we are progressing. 
Now, we couldn't find how to manage to unsubscribe action from a subscription generated.
Please tell us how to catch the unsubscribe action.

**Comment by Speedy1991** [comment]
This is only possible via AppStore or Playstore.
A quick fix is to add a Button with a deeplink to the store

**Comment by asobralr** [comment]
Hi, I'm having a similar problem. I'm working with auto renewable subscriptions too. Users are able to cancel the subscription from the AppStore/Playstore but I don't know how to listen to that event from the app, in order to prevent them from accessing premium content from now on. Thanks for your help.

**Comment by Speedy1991** [comment]
As far I know there is no listener.
You can check the purchase history (in IOS pick the latest received reipe) and validate these.

Google: https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get
IOS: https://developer.apple.com/documentation/appstorereceipts/verifyreceipt

On these endpoints you will get expiryTimes. Use this information to refetch PurchaseHistory with some grace period (e.g. 1 min).

**Comment by byCedric** [comment]
Hi people! Unfortunately, there is no event for canceled subscriptions from the stores. As @Speedy1991 said, you will have to look up if the purchase is still considered "valid" yourself I'm afraid. That being said, if you can find better ways to detect these changes in the underlying API's, feel free to open an RFC with a proposal. I'd be happy to take a look at it 😄 

Keep in mind that if you "remove" access to the subscription before this time, it could lead to [penalties from Google](https://developer.android.com/google/play/billing/subs#cancel). I think Apple has a similar policy on this, so please only revoke access to subscriptions when the user isn't entitled to it anymore.

Hope it helps!
