### ISSUE TITLE
BARCODE SCAN ISSUE

### ISSUE THREAD

**Issue by subhadipdutta21** [expo/expo#8738]
So I have encountered the following issue while using the barcode on expo -

1. when I scan the barcode in different orientations or mostly while scanning it upside down
the decoded value comes differently. 

2. This is not happening on **IOS** at all 
3. Happening on **Android** several times

**Comment by lukmccall** [comment]
Hi @subhadipdutta21, could you provide more information like your iOS and Android version, the output from `expo diagnostics`. Which barcode types did you use? Do you have an orientation in your app locked or no?

I've tested it and I couldn't reproduce this bug.

**Comment by subhadipdutta21** [comment]
Hey @lukmccall  thanks for the callback. On **IOS** no problem is there . Android versions we tried are- 9 , 8.
I tried with **barcode type 32** initially and also the other barcodes around in order to check. U have to scan the barcode **multiple times** and **multiple orientations** by **rotating the barcode image on your screen** or whatever but keep the **device camera fixed** and look at the  EAN number getting generated each time in order to catch the issue.

I'm providing u a barebone code snippet --

//barcode component
   <BarCodeScanner onBarCodeScanned={this.handleBarCodeScanned} style= 
     {StyleSheet.absoluteFillObject} />

//function call
handleBarCodeScanned = async ({ type, data }) => {console.log(type,data)}  //check this console each time , precisely the data.

**package informations**
    "expo": "^37.0.0",
    "expo-barcode-scanner": "~8.1.0",
    "expo-camera": "~8.2.0",
    "expo-constants": "~9.0.0",

**Comment by lukmccall** [comment]
Sorry for my misunderstanding (for some reason, I've thought it happens only on iOS 🤷🏼‍♂️)🤦‍♂️ I'll try it on Android. Thank you for providing more information 🏅

**Comment by lukmccall** [comment]
@subhadipdutta21, I've tested it on the two Android phones. Unfortunately, I'm still wasn't able to reproduce it. The barcode scanner almost every time returns the correct value. It only returns the wrong value, when I was in the middle of rotation the barcode. We can't do anything with that.

Does it return the wrong value when you don't move your code? If yes, please tell me what is your phone model.

**Comment by brentvatne** [comment]
closing because we can't reproduce and the issue is inactive
