### ISSUE TITLE
IOS ::: No suitable image URL loader found for assets-library://asset/asset

### ISSUE THREAD

**Issue by blazerroad** [expo/expo#8741]
Hi guys,
in IOS  at this code :
  ```
<ImageBackground
                        style={styles.item}
                        source={{ uri: item.uri }} >
                        {selected && selectedItemCount.lenght > 0 &&
                            <View style={{ ...styles.countBadge, backgroundColor: badgeColor }}>
                                <Text style={styles.countBadgeText}>{selectedItemCount}</Text>
                            </View>
                        }
                    </ImageBackground>
```
item.uri  is : assets-library://asset/asset.PNG?id=8602ACD9-04C2-4FA9-B8A1-F65E1C1299DD&ext=PNG

it work at andriod but IOS comes with this error : 

> 
> [tid:com.facebook.react.ImageLoaderURLRequestQueue][RCTImageLoader.mm:510] No suitable image URL loader found for assets-library://asset/asset.PNG?id=8602ACD9-04C2-4FA9-B8A1-F65E1C1299DD&ext=PNG
> 2020-06-08 23:16:28.129
> 

im using exp-camera , expo-media-library
that work fine on EXPO CLIENT app but after eject im getting this error
<img width="980" alt="Screen Shot 1399-03-20 at 14 10 13" src="https://user-images.githubusercontent.com/17562578/84140600-1f32d580-aa67-11ea-8828-5e996f6d23f0.png">

react version :  "react-native": "~0.61.5",
xcode version : 11.4.1 

<img width="980" alt="Screen Shot 1399-03-20 at 14 10 13" src="https://user-images.githubusercontent.com/17562578/84132829-96626c80-aa5b-11ea-899f-2015a8ba2716.png">

**Comment by tsapeta** [comment]
Hmm ok, could you try version `8.2.1`? It contains a fix for that 😉 It's been already published, but not promoted to `latest` tag on npm yet, so `8.1.0` is installed by default still.
As this issue is already solved in my opinion, I'm closing this thread but feel free to come back here if not 😄
