### ISSUE TITLE
[docs] Make it more obvious that inline snacks don't show the full code

### ISSUE THREAD

**Issue by cruzach** [expo/expo#8748]
Right now, inline snacks show the minimum amount of code to get the idea across. This saves space and scrolling in the docs, and if the person wants to see the full example, they can click the button to "Open in snack"

But this has confused people here and there, so we should figure out a way to make this better

**Comment by IjzerenHein** [comment]
@cruzach We added the @hide tag in https://github.com/expo/expo/pull/11191 and also removed all static examples in https://github.com/expo/expo/pull/11209

Would you say we can close this?

**Comment by cruzach** [comment]
yep 👍
