### ISSUE TITLE
Runtime version usage in expo

### ISSUE THREAD

**Issue by AlefiyaG** [expo/expo#8751]
### Please note that discussions opened as issues in the core Expo repository will be closed.

  If you have a question about Expo or want to discuss about related aspects, consider posting it
  on our forums at https://forums.expo.io/. 🙂 

Hi Team,
i am trying to use the runtime version feature in a bare workflow to avoid update compatibility. the assets and bundles is self hosted. We just want to make use of the OTA feature in expo. Somehow when ever I include the field in my android manifest file, it doesn't get added to the app.manifest file during export. Also its not present in android-index file. Even though i don't add the expo sdk in my android manifest file, it still gets added with the update url during export. 

Not sure if i am missing something here. below is the code snippet of my changes in android manifest file. Could you please help.

Android manifest:
<meta-data android:name="expo.modules.updates.EXPO_RUNTIME_VERSION" android:value="16.0" />

Expo environment:
expo --version
3.21.5

app.json:
{
  "expo": {
    "name": "XXX",
    "slug": "XXX",
    "sdkVersion": "37.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "assetBundlePatterns": [
      "**/*"
    ]
  }
}

Also in case you have more documentation or code examples which use the runtime version field, that would be helpful.

**Comment by duckbrain** [comment]
See #8231; it seems like the manifest is not provided to apps in the bare workflow.
