### ISSUE TITLE
Expo Client doesn't open in android

### ISSUE THREAD

**Issue by MeFon** [expo/expo#8752]
### Summary of Issue (just a few sentences)
The app freezes in splash sreen. I can't even open the camera to get the QR code to emulate my project. Is there any known issue?

### Expected Behavior vs Actual Behavior
The app should open so i Could scan the QR code. It freezes o splash screen. 

I have already reinstalled and given all permissions. Feels like a silly question... But I don't seem to find anything about it

**Comment by pacheco7** [comment]
> You asked abou Expo Cli, that should be in my computer right?

No, I'm asked about mobile app hehe. Sometimes (in most) a simple app update from store solves your problem ;)

**Comment by MeFon** [comment]
Ooh, sorry about that then. (Good morning also!)

I'm running expo 2.15.4



*Afonso Brunelli Ferragut*


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qui., 11 de jun. de 2020 às 06:35, Raphael <notifications@github.com>
escreveu:

**Comment by pacheco7** [comment]
Good morning, haha.

Please, update to 2.15.5 and try again.

**Comment by MeFon** [comment]
Maybe I'm missing something so obvious, but I really cannot update it
anywhere...
I have just deinstalled and reinstalled, and it comes as version  2.15.4
In playstore, there is no Update option. I can only deinstall or open it.
And "update automatically" is also checked. But my version is 2.15.4


[image: image.png]
[image: image.png]

Am I doing something wrong? That seems like it should be simple hahaha I'm
in the dark here



*Afonso Brunelli Ferragut*


Em qui., 11 de jun. de 2020 às 09:49, Raphael <notifications@github.com>
escreveu:

**Comment by pacheco7** [comment]
No, maybe the version 2.15.5 isn't available in android (I forget to write what I using iOS (d'oh) hahaha). I'll test with another phone here (Android, this time).

**Comment by pacheco7** [comment]
[UPDATE] - I test the QR code read in Android 7.0 Kernel 3.18.35 and it not crash.

I used this code as example: https://snack.expo.io/@_pacheco7/groaning-watermelon

Can you try it on your device?

**Comment by MeFon** [comment]
Can you help me how to do it?
My app literally does not leave this screen:
[image: image.png]

Nothing else happens, there is nowhere I can scan QR codes or input
anything or click anything. It only opens this first image and stays on it,
no matter what I do.
That's it, it does nothing else. Only this screen.


*Afonso Brunelli Ferragut*


Em qui., 11 de jun. de 2020 às 12:19, Raphael <notifications@github.com>
escreveu:

**Comment by byCedric** [comment]
Hi @MeFon! Could you try clearing the app's local storage? That should clean all existing data from the app and should solve this for you. You should be able to do this [using this guide](https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android), but instead of cache go for all data of the app.

Hope it helps! 😄

**Comment by MeFon** [comment]
Problem was solved by reinstalling the app (couple times....) and clearing all cache info  [using this guide](https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android)
Special thanks to @pacheco7
