### ISSUE TITLE
[iOS] BarcodeScanner should include bounds of detected barcodes

### ISSUE THREAD

**Issue by minhdang-idev** [expo/expo#8754]
### Summary of Issue (just a few sentences)
When using the BarCodeScanner component to scan for QRcode, onBarCodeScanned callback on Android returns bounding data (coordinates of detected QRcode). But on iOS, it doesn't return bounding data.
Because in the documentation, it's not mentioned that bounds are available on Android only, I think it's a bug or a missing feature that I think we really need. The data of bounds is very important to make the scanner become more convenient and it can also improve user experience.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
iOS

### Steps to Reproduce
- Add BarCodeScanner component into React Native.
- Set onBarCodeScanned for BarCodeScanner.
- onBarCodeScanned  = (data)  => {
   console.log(data); // on IOS, it does not include bounds inside data
}
It's mentioned here: https://github.com/expo/expo/issues/2700

### Expected Behavior vs Actual Behavior
onBarCodeScanned  should return data including bounds.

Thanks in advance.

**Comment by byCedric** [comment]
Hi @minhdang-idev! Thanks for the report. It looks like the bounding box is currently only implemented in Android as you mentioned. If you are able to add this, we would appreciate a PR. If not we will get to this when we have some bandwidth available.

**Comment by adityar15** [comment]
is this sorted?
