### ISSUE TITLE
Web Region doesn't work if the locale is just a language

### ISSUE THREAD

**Issue by sekistner** [expo/expo#8758]
https://github.com/expo/expo/blob/23e89c1b5f35b60b048a92817ab50bb435a83725/packages/expo-localization/src/ExpoLocalization.web.ts#L33-L39

If the current locale is just `"en"` for example it returns `"EN"` what is not a valid ISO code or an incorrect one.
It should be undefined, so check if a `-` does exist.
Instead of substring you can just check if `locale.split("-")[1]` is defined and the result is undefined otherwise.

**Comment by EvanBacon** [comment]
Thanks for reporting this, I opened a PR to include the proposed changes
