### ISSUE TITLE
How to access release-channel in app.config.js?

### ISSUE THREAD

**Issue by denisdenes** [expo/expo#8770]
Hi! 

How can i see the release-channel in app.config.js? I saw that is exposed in this [pull request](https://github.com/expo/expo-cli/pull/1524/files), but it returns 'undefined'. I tried also the 'mode' param, but it also returns 'undefined'. Checked the [docs](https://docs.expo.io/workflow/configuration/#app-config), but couldn't spot anything there either. 

What I am trying to do, is to drop the app.staging.json / app.production.json approach for setting up multiple envs, and instead parameterize it with app.config.js.

Thank you for the hard work you are putting into this package!

**Comment by brentvatne** [comment]
app.config.js is evaluated at publish time. if you want to pass something into it, you can do

`SOME_ENV_VAR=some-value expo publish --release-channel whatever`

then check for `process.env.SOME_ENV_VAR`

**Comment by denisdenes** [comment]
@brentvatne Thank you for your answer. Yeah, it's a good option, I just hoped that "mode" parameter could be useful in some way, that I don't need to have custom scripts in package.json.

Currently I have this in package.json:
` "publish:prod": "expo publish --config src/config/prod/app.prod.json --release-channel prod",`,

Passing an env var in the `expo publish` command and then access it in app.config.js, wouldn't change much, because i would still need to have something like this in package.json: 

`"publish:prod": ENV=prod expo publish --release-channel prod`
`"publish:stage": ENV=stage expo publish --release-channel stage`

But yeah, not a big deal. Unless I am missing a better way to handle the env, this can be closed

**Comment by EvanBacon** [comment]
I removed the mode parameter before `app.config.js` was released, https://github.com/expo/expo-cli/pull/1682 it didn't work very well.

**Comment by embray** [comment]
It would still be really nice to have something like this.I wanted to do something like have multiple `app.config.<release-channel>.json` with the correct one loaded / merged with the base `app.config.json` via `app.config.js`.

I came up with a hack for this by actually parsing the command-line arguments to get `--release-channel` but it doesn't seem to actually work when building on Expo's build servers, understandably.

The workaround of using an environment variable is fine for now, but it would be nice if the release channel were actually made available to `app.config.js`
