### ISSUE TITLE
Activate audio for videos in silent mode when the volume is changed

### ISSUE THREAD

**Issue by enesccinar** [expo/expo#8772]
Hi,

I am trying to find a way to activate audio if the user changed the volume level by physical buttons.

Regards,
Enes

**Comment by pacheco7** [comment]
Hi @enesccinar !

Actually, expo doesn't have a module for that, but you can use [react-native-system-setting](https://github.com/c19354837/react-native-system-setting). Also, in the [Expo Roadmap](https://expo.canny.io/feature-requests/p/hardware-keys-api-volume-updown-power-button) we have a feature request pending to approval.

**Comment by enesccinar** [comment]
Hi @pacheco7,

I do not want to eject the project. I will wait for the new feature. It is not a matter of life or death after all for the project that I have been working on :)

thanks for the answer btw. regards.
