### ISSUE TITLE
Local Connection in Expo

### ISSUE THREAD

**Issue by alishehzad2017** [expo/expo#8777]
It seems that there are three ways to run an expo app: Tunnel, Lan and Local connection.

When is local connection used and how to use it?

**Comment by byCedric** [comment]
Hi @alishehzad2017! You can switch between the connection types in the devtools page, [just below the production/development mode switch](https://docs.expo.io/workflow/development-mode/#toggling-development-mode-in-expo-dev-tools). This mostly affects the metro bundler and to what connections it should listen to.  You can also start expo with a specific connection type to quickly start up everything, you can do that by running these commands:

```
$ expo start --localhost
$ expo start --lan
$ expo start --tunnel

// or if you want to see all options
$ expo start --help
``` 


If you have any questions like these, feel free to ask on the [forums](https://forums.expo.io/) or in our [community slack](https://slack.expo.io/). Hope it helps!
