### ISSUE TITLE
Expo manifest.android.config missing in build apk

### ISSUE THREAD

**Issue by GiverDead** [expo/expo#8781]
**TypeError** undefined is not an object (evaluating 'f.default.manifest.android.config.googleMaps')

https://sentry.io/ error show me that key config are missing in my **manifest** in apk.

Any ideas how to fix it?

Expo 36.0.0
expo-managed app

**APK**
<image src="https://i.stack.imgur.com/oWvs1.png">

**DEV**
<image src="https://i.stack.imgur.com/5dhcn.png">

**Comment by byCedric** [comment]
Hi @GiverDead! I'm not sure yet what's happening here. So the general `android.config` property is used for all values to apply to the `AndroidManifest.xml`. It might be possible that this is removed from the manifest when either ejecting or creating standalone apps, but I'll have to dig deeper into this. Would you mind sharing your environment as well (`expo diagnostics`)? Could also explain #8708. Thanks for mentioning this!

**Comment by GiverDead** [comment]
Expo CLI 3.21.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.0 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7

For build i using expo build:android

App.json
`{
  "expo": {
    "name": "GeTruck transportation",
    "slug": "getruck",
    "privacy": "public",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "0.0.13",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#0057CC"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "androidStatusBar": {
      "backgroundColor": "#073f89",
      "translucent": true,
      "barStyle" : "light-content"
    },
    "ios": {
      "supportsTablet": true,
      "requireFullScreen": true,
      "config": {
        "googleMapsApiKey": "AIzaSyBiZAPLh2uJsFrxPRIWxAzhJ3***********E"
      }
    },
    "android": {
      "config": {
        "googleMaps": {
          "apiKey": "AIzaSyBiZAPLh2uJsFrxPRIWxAzhJ3ODrB******5E"
        }
      },
      "package": "com.getruck.app",
      "googleServicesFile": "./googles.json",
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        ..................
        "android.permission.WAKE_LOCK"
      ]
    },
    "packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": [
        "expo.ts",
        "expo.tsx",
        "expo.js",
        "expo.jsx",
        "ts",
        "tsx",
        "js",
        "jsx",
        "json",
        "wasm",
        "svg",
        "vue"
      ]
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "getruck",
            "project": "getruck",
            "authToken": "dc152499557d44e3a2b22ca095de9f03f34cba44*******f8384b2"
          }
        }
      ]
    }
  }
}
`

Manifest from sentry.io

`{
android: {
googleServicesFile: [Filtered], 
package: com.getruck.app, 
permissions: [Array]
}, 
androidStatusBar: {
backgroundColor: #073f89, 
barStyle: light-content, 
translucent: True
}, 
bundledAssets: [
asset_3a2ba31570920eeb9b1d217cabe58315.ttf
, 
asset_8b12b3e16d591abc926165fa8f760e3b.json
, 
asset_744ce60078c17d86006dd0edabcd59a7.ttf
, 
asset_461d9bba8b6a3c91675039df12cfe6ca.json
, 
asset_140c53a7643ea949007aa9a282153849.ttf
, 
asset_94c4ffdcbffeb0570c635d7f8edd8a25.json
, 
asset_ca9ce9ff0676a9b04ef0f8a3ad17dd08.ttf
, 
asset_54a5c98d22f313098b3dbe2d5b2e87ba.json
, 
asset_b49ae8ab2dbccb02c4d11caaacf09eab.ttf
, 
asset_39843e5d52a6c5c42d5abdb0b34bcaa6.json
, 
asset_b06871f281fee6b241d60582ae9369b9.ttf
, 
asset_f1f91feb805137c9283fb766620ec5eb.json
, 
asset_09dd345dbd4ec5a0874841d5749ac153.json
, 
asset_0886a6b127c6057cee83f9c65c7ffd62.json
, 
asset_f6c6f6c8cb7784254ad00056f6fbd74e.ttf
, 
asset_b70cea0339374107969eb53e5b1f603f.ttf
, 
asset_c39278f7abfc798a241551194f55e29f.ttf
, 
asset_e20945d7c929279ef7a6f1db184a4470.ttf
, 
asset_60668d999bbaf663420340f7bdd580d7.json
, 
asset_b2e0fc821c6886fb3940f85a3320003e.ttf
, 
asset_3e6805fbc794680014716b8c752f20b8.json
, 
asset_3c851d60ad5ef3f2fe43ebd263490d78.ttf
, 
asset_1a0e3525dd5df87e77057204129a5e6e.json
, 
asset_a37b0c01c0baf1888ca812cc0508f6e2.ttf
, 
asset_7e078700f0c35367a56c5bbb2047dda7.json
, 
asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf
, 
asset_fdc01171a7a7ea76b187afcd162dee7d.json
, 
asset_d2285965fe34b05465047401b8595dd0.ttf
, 
asset_647543ebfccf6e5495434383598453d1.json
, 
asset_5cdf883b18a5651a29a4d1ef276d2457.ttf
, 
asset_74d124a3caeac2bea111f3ca2f2dd34a.json
, 
asset_7d40544b395c5949f4646f5e150fe020.png
, 
asset_cdd04e13d4ec83ff0cd13ec8dabdc341.png
, 
asset_a132ecc4ba5c1517ff83c0fb321bc7fc.png
, 
asset_0ea69b5077e7c4696db85dbcba75b0e1.png
, 
asset_f5b790e2ac193b3d41015edb3551f9b8.png
, 
asset_6165c9d7a2e729ba57b23dd93add5366.png
, 
asset_2379ae894c2c9f63b852a9f3676c2763.png
, 
asset_189418f559071d9c6e406f41090a25ed.png
, 
asset_5187119d0e47d4e908204a2a5f4b6188.png
, 
asset_7bb0b9d7a8c603df41d6dc6796ed7a42.png
, 
asset_1a255483876a975a4e959dbc89246733.png
, 
asset_52da9c71832c841707f07dc4ff79679d.png
, 
asset_f576a159360969573d553e5eec1ddf5f.png
, 
asset_ae024509e0829059aa35e9d0b9527854.png
, 
asset_d4b85cc837b0b67a36147f6ad5b3ae28.png
, 
asset_ff598b1d85ceae3b34d0438b35a98d43.png
, 
asset_d21d84fd5f64b905389cafc3ed092b6a.png
, 
asset_57a1521a6eef8d740ff46b49cd5664aa.png
, 
asset_cc6b1d9dbc31b1dd653557124c7e475a.png
, 
asset_d4221e990f26bfd16e2f47739d48e997.png
, 
asset_79ee858d9d03d643ea03bf6e46d4ddb9.png
, 
asset_4413eadcdf63f4c85133bc7b2db14a42.png
, 
asset_d6d934c3984d480aeb220f2ebcffabbe.png
, 
asset_8bd8ca29b6d69812df90095626ede2bb.png
, 
asset_9134e9a7f58feb49899a3622a7033510.png
, 
asset_7b68890078dba651cbf7cda354293b8d.png
, 
asset_4b2a5acd692cdd3a2617b9f91e605b37.png
, 
asset_0aec7c2c4da05634506f0fa5530a0f27.png
, 
asset_8858d619821a21b57ebc2d12a5a2606d.png
, 
asset_a323d694027699a088cf50a6dc4b79e0.png
, 
asset_76d30895a6c76b3d04f38d58ffdc8c6c.png
, 
asset_a653ba6c17f66e5546097efefc0ac42e.png
, 
asset_ef8e491f0c8de7f534d151a3f2db64f0.png
, 
asset_602807265609383ebcdeb305aedc0581.png
, 
asset_b5f82bcc37c6b16c9e699e76dfb2cabf.png
, 
asset_268eb694383065bca783d7dd3bd02fc0.png
, 
asset_241987d509cccf91152e4d9f57ceed99.png
, 
asset_226f347c6f5f6d4acc52f1e8ec6e33bc.png
, 
asset_76c4d213d7ed9cda9bfc96c5acb1f839.png
, 
asset_8180431133d323a4985ffcda280f9da8.png
, 
asset_eefeff4ad268fb8fa7b718c17fe617ff.png
, 
asset_6615dde7c20462154d1215eb0db2628e.png
, 
asset_7d93f0c9b3db90cf3782244ac3e24a12.png
, 
asset_c204ebe8c5b919b3d716e647c3b79d17.png
, 
asset_f127e368d62ad92dacab340de5af50e8.png
, 
asset_60e8a8323a1f5c9dc59c6783d5974123.png
, 
asset_40bc3ae5444eae0b9228d83bfd865158.png
, 
asset_3b6d4044e1a80a28fcfc81fffed1eecb.png
, 
asset_7c413b90b312be15ef030cbc74565dc9.png
, 
asset_359c0002de508fc1afb9267ff5849e9a.png
, 
asset_f1c4361709b51bf84321b2f11342a7dd.png
, 
asset_e1dd8e43909dd4871b98ad617ad7dd22.png
, 
asset_34436712ed95a07c370af4b8cbf48754.json
, 
asset_de54151f81d2cfcdeac5ae0b8aa1c387.json
, 
asset_778ffc9fe8773a878e9c30a6304784de.png
, 
asset_376d6a4c7f622917c39feb23671ef71d.png
, 
asset_c79c3606a1cf168006ad3979763c7e0c.png
, 
asset_02bc1fa7c0313217bde2d65ccbff40c9.png
, 
asset_35ba0eaec5a4f5ed12ca16fabeae451d.png
], 
bundleUrl: https://d1wp6m56sqw74a.cloudfront.net/%40giverdead%2Fgetruck%2F0.0.13%2F0c6f76e7d0f954b05f9fea9d35e2d64c-37.0.0-android.js, 
commitTime: 2020-06-12T11:35:01.779Z, 
dependencies: [
@mapbox/polyline
, 
@react-native-community/datetimepicker
, 
@twotalltotems/react-native-otp-input
, 
axios
, 
babel-loader
, 
expo
, 
expo-constants
, 
expo-image-picker
, 
expo-linking
, 
expo-localization
, 
expo-location
, 
expo-permissions
, 
expo-screen-orientation
, 
expo-task-manager
, 
i18n-js
, 
react
, 
react-dom
, 
react-native
, 
react-native-confirmation-code-input
, 
react-native-gesture-handler
, 
react-native-google-places-autocomplete
, 
react-native-invertible-scroll-view
, 
react-native-keyboard-spacer
, 
react-native-maps
, 
react-native-paper
, 
react-native-reanimated
, 
react-native-screens
, 
react-native-signature-pad
, 
react-native-web
, 
react-native-webview
, 
sentry-expo
, 
vue-moment
, 
vue-native-core
, 
vue-native-helper
, 
vue-native-router
, 
vuex
], 
hostUri: exp.host/@giverdead/getruck, 
icon: ./assets/icon.png, 
iconUrl: https://d1wp6m56sqw74a.cloudfront.net/~assets/d92f0e332a6e48405a88a480ec69bdd4, 
id: @giverdead/getruck, 
ios: {
requireFullScreen: True, 
supportsTablet: True
}, 
isVerified: True, 
loadedFromCache: True, 
locales: {}, 
name: GeTruck transportation, 
orientation: portrait, 
packagerOpts: {
config: metro.config.js, 
sourceExts: [Array]
}, 
platforms: [
ios
, 
android
], 
privacy: public, 
publishedTime: 2020-06-12T11:35:01.530Z, 
releaseChannel: default, 
releaseId: 878edf1e-6893-4da4-8b2d-35e994148c55, 
revisionId: 0.0.13-r.PG!SWHikT, 
sdkVersion: 37.0.0, 
slug: getruck, 
splash: {
backgroundColor: #0057CC, 
image: ./assets/splash.png, 
imageUrl: https://d1wp6m56sqw74a.cloudfront.net/~assets/3b6d4044e1a80a28fcfc81fffed1eecb, 
resizeMode: cover
}, 
updates: {
fallbackToCacheTimeout: 0
}, 
version: 0.0.13
}`

**Comment by GiverDead** [comment]
ios.config missed to!

**Comment by GiverDead** [comment]
I solved this by replacing **Constants.manifest.android.config.googleMaps.apiKey** call with my own small config json (or just string) in all project. On standalone apk **Constants.manifest.android.config.googleMaps.apiKey** - is not exists.
react-native-map works fine

**Comment by byCedric** [comment]
Sounds like a good workaround for now. I'll double-check internally if it works like it should, and update the docs to make this a bit more understandable.
