### ISSUE TITLE
`expo-updates` uses hard-coded localhost

### ISSUE THREAD

**Issue by duckbrain** [expo/expo#8784]
### Summary of Issue (just a few sentences)

When trying to use `REACT_NATIVE_PACKAGER_HOSTNAME` to specify where the packager is located, it doesn't work for building a release app on Android and iOS.

This prevents the builds from completing.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Android (docker container running the Android build)

```
  Expo CLI 3.21.5 environment info:
    System:
      OS: Linux 5.6 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.18.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    npmPackages:
      expo: ^37.0.0 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: 0.61.4 => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
```

### Reproducible Demo

`localhost:8081` is hard-coded:

- https://github.com/expo/expo/blob/master/packages/expo-updates/scripts/create-manifest-android.gradle#L60
- https://github.com/expo/expo/blob/master/packages/expo-updates/scripts/create-manifest-ios.sh#L7

### Expected Behavior vs Actual Behavior

In both files, `REACT_NATIVE_PACKAGER_HOSTNAME` should used, but using `localhost:8081` as a fallback.

I'm trying to work around this by rewriting `/etc/hosts` in my Docker container from its entrypoint or merging the containers.

**Comment by brentvatne** [comment]
seems like a reasonable change to make, thanks for the issue!

**Comment by esamelson** [comment]
Hi, `expo-updates@0.2.9` has been released with this change. Please let us know if it doesn't work for you!
