### ISSUE TITLE
types for Localization come through as any

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#8785]
### Summary of Issue (just a few sentences)

The types for Localization come through as any currently. For example instead of being `boolean` Localization.isRTL is `any`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 

### Reproducible Demo

The types I see:

```
import { Localization } from './Localization.types';
export { Localization };
export declare const locale: string;
export declare const locales: any;
export declare const timezone: any;
export declare const isoCurrencyCodes: any;
export declare const region: any;
export declare const isRTL: any;
export declare function getLocalizationAsync(): Promise<Localization>;
```

it seems the types in `Localization.types` are correct:

```
export declare type Localization = {
    locale: string;
    locales: string[];
    timezone: string;
    isoCurrencyCodes?: string[];
    region?: string;
    isRTL: boolean;
};
```

however the types that my editor uses are the `any` exports mentioned above.

**Comment by AdamJNavarro** [comment]
Hey @chrisdrackett, thanks for submitting a bug report. Can you let me know what editor and version of said editor you are running?

I can confirm I see the same behavior with VS Code version: 1.46.0.

Cheers,
Adam

**Comment by chrisdrackett** [comment]
I’m also using vscode, but I’m not sure it has anything to do with the editor

**Comment by AdamJNavarro** [comment]
Most likely not but I like to gather as my information as possible. We'll look into this and hopefully find a resolution soon.
