### ISSUE TITLE
[expo-localization] turn off localization when in SSR

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#8790]
### Summary of Issue (just a few sentences)

if you use ExpoLocalization in a SSR environment like next.js it'll fail with `ReferenceError: navigator is not defined`. It would be nice if this at least had a default fallback or similar to prevent this.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4

**Comment by AdamJNavarro** [comment]
Hey @chrisdrackett,

Would you be able to create a reproducible example of this that we could use to test on our end?

Cheers,
Adam

**Comment by EvanBacon** [comment]
Good catch Chris, I've opened a PR to fix this.
