### ISSUE TITLE
Documentation for SortType for iOS (Contact API)

### ISSUE THREAD

**Issue by obax** [expo/expo#8794]
The documentation for Contacts (https://docs.expo.io/versions/latest/sdk/contacts) shows `SortType` as being unavailable for iOS, then later shows a table where all the possible values are acceptable in iOS. From my test, the former seems accurate. Could that be reflected in the documentation?

**Comment by AdamJNavarro** [comment]
Hey @obax,

We are always welcome to PRs if you are feeling up to it! The one nuance to submitting a PR to docs is that we ask that you make the changes to all applicable versions of the docs. Let me know if that's something you are willing to do. Regardless, thanks for bringing this to our attention.

Cheers,
Adam
