### ISSUE TITLE
UI modification 

### ISSUE THREAD

**Issue by alactic** [expo/expo#8797]
is there I can modify the modal UI to my own design?

**Comment by AdamJNavarro** [comment]
Hey @alactic,

I'm not exactly sure that you are referencing. If you are talking about a basic [react native modal](https://reactnative.dev/docs/modal), you can modify the UI by styling the View component that the Modal is wrapped around. If you are talking about something else, please feel free to create a post on our [Forums](forusm.expo.io)!

We try our best to limit Github issues to reproducible and actionable bug reports so in the future please direct questions such as this one to the forums.

Cheers,
Adam
