### ISSUE TITLE
🐛 Network request failed

### ISSUE THREAD

**Issue by fariasmateuss** [expo/expo#8798]
## 🐛 Bug Report

TypeError: Network request failed

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Emulator - Pixel 2 API 28
expo: ^37.0.12

### Reproducible Demo

The building is completed, but when trying to register in the application, it mentions the error.
I emphasize that in Insomnia the requests are all made without any problem.

In the console:

```
Network request failed
- node_modules\whatwg-fetch\dist\fetch.umd.js:473:29 in xhr.onerror
- node_modules\event-target-shim\dist\event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
- node_modules\react-native\Libraries\Network\XMLHttpRequest.js:574:29 in setReadyState
- node_modules\react-native\Libraries\Network\XMLHttpRequest.js:388:25 in __didCompleteResponse  
- node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:190:12 in emit
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:436:47 in __callFunction     
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:26 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17 in __guard$argument_0 
* [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by AdamJNavarro** [comment]
Hey @fariasmateuss,

Thanks for submitting a bug report. Would love to get some more information from you if possible such as is this only occurring on Android or on other platforms as well? Additionally, is this happening a physical device as well? Also have you tried testing on a different network to see if it may be something with the network environment you tested on?

Cheers,
Adam

**Comment by superyarik** [comment]
on our app we move to axios to handle network requests - fetch's errors in sentry logs showing like js error with line and column in bundle

**Comment by byCedric** [comment]
As @A-Nav mentioned, for us it's hard to reproduce this issue without the context of your environment or reproducible steps. If this is still an issue for you, please open a new issue with the info filled in from the issue template.
