### ISSUE TITLE
FCM for Push Notifications in iOS apps

### ISSUE THREAD

**Issue by sorxrob** [expo/expo#8799]
Hi, I was looking at the FCM for Push Notifications docs and noticed this line:

`Note that FCM is not currently available for Expo iOS apps.`

Does this mean it is not available only in development? But will work on a real device / production?

Thanks!

**Comment by AdamJNavarro** [comment]
Hey @sorxrob,

FCM will not work on a real device or in production as well when you are using the Managed workflow as the Expo Push Notification service does not allow one to configure FCM to be used for iOS. If you need to use FCM, you'll want to use the Bare Workflow which would allow you to configure FCM to be used on iOS and use a different push notification delivery service or create your own.

In the future, if you have questions such as this one it would be greatly appreciated if you could head over to our [Forums](https://forums.expo.io/) and create a post there! We try our best to limit Github issues for reproducible and actionable bug reports.

Cheers,
Adam

**Comment by sorxrob** [comment]
Hi @AdamJNavarro,

Thank you for this. I have rejected my expo app already.

Hoping expo will support both ios/android soon!

**Comment by brentvatne** [comment]
@sorxrob - notifications work on ios as well just not through FCM without ejecting. on ios we use apples push service APNS instead.

**Comment by MrIceman** [comment]
Hi, is FCM Support for iOS planned? To me this is a huge expo killer

**Comment by artvichi** [comment]
Any update on this? FCM for both platforms will bring some simplicity !

**Comment by mattgabor** [comment]
> If you need to use FCM, you'll want to use the Bare Workflow which would allow you to configure FCM to be used on iOS and use a different push notification delivery service or create your own.

do you have any recommendations here? Since `@react-native-firebase` does not support web, it seems like there are no web/ios cross-platform FCM delivery services for iOS that I can find.

**Comment by imagina** [comment]
Same question. We need to connect the existing backend that’s using FCM directly.

**Comment by edcity-charlie** [comment]
Same question, is FCM support for iOS at 2023?

**Comment by lucasbasquerotto** [comment]
@edcity-charlie @lhguerra If feasible for your projects, and if FCM is a requirement for iOS, couldn't you use react-native-firebase instead for push notifications (with notifee for notification grouping and other stuff)? It should work with managed Expo too: https://rnfirebase.io/messaging/usage and https://notifee.app/react-native/docs/integrations/fcm

**Comment by lhguerra** [comment]
that defeats the purpose of using the expo solution for both platforms

**Comment by edcity-charlie** [comment]
Yes, we at last adopted react-native-firebase + notifee.
Following https://notifee.app/react-native/docs/integrations/fcm.

**Comment by lhguerra** [comment]
Is notifee really needed?
