### ISSUE TITLE
[expo-media-library] properly handle iOS's slow motion videos

### ISSUE THREAD

**Issue by jarvisluong** [expo/expo#8801]
## 🐛 Bug Report

Currently when calling `MediaLibrary.getAssetInfoAsync` with a slow motion video from iOS will crash with this message:

```-[AVComposition URL]: unrecognized selector sent to instance```

This is because we are force casting this line:

https://github.com/expo/expo/blob/8fa0b005b391412fd4ee6e429646dd7a45892e71/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L425

while `requestAVAssetForVideo:` can also return an `AVComposition` (as both `AVURLAsset` and `AVComposition` is subclasses of `AVAsset`). `AVComposition` will need a special care to get the local uri.

One such solution can be found here: https://overflow.buffer.com/2016/02/29/slow-motion-video-ios/

Will make a PR for this soon!

**Comment by AdamJNavarro** [comment]
Hey @jarvisluong,

Thanks for submitting a bug report and even more so for taking the time to open a PR! We'll try and review it as quickly as we can. You're the best!

Cheers,
Adam
