### ISSUE TITLE
Using import statement in app.config.js causes an error

### ISSUE THREAD

**Issue by ShunyaWatanabe** [expo/expo#8803]
## 🐛 Bug Report

https://docs.expo.io/workflow/configuration/ tells me I can use import statements in app.config.js but it doesn't work.

### Summary of Issue (just a few sentences)

I wanted to use `import Constants from 'expo-constants';` in app.config.js but it gives me an error

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.21.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.5
```

### Reproducible Demo

- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve

As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

### Steps to Reproduce

create app.config.js and add `import Constants from 'expo-constants';`

### Expected Behavior vs Actual Behavior
**expected**
the app runs without problems.

**actual**
```
/Users/swatanabe025/Desktop/private/OtsukaiChain/packages/clients/supporter/node_modules/expo-constants/build/Constants.js:1
import { AppOwnership, UserInterfaceIdiom, } from './Constants.types';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Module._compile (/usr/local/lib/node_modules/expo-cli/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.newLoader [as .js] (/usr/local/lib/node_modules/expo-cli/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Constants (/Users/swatanabe025/Desktop/private/OtsukaiChain/packages/clients/supporter/app.config.js:1:1)
    at Object.<anonymous> (/Users/swatanabe025/Desktop/private/OtsukaiChain/packages/clients/supporter/app.config.js:4:28)
```

**Comment by byCedric** [comment]
Hi @ShunyaWatanabe! Thanks for the issue report. Although the docs states that you can use import statement, it also specifies some rules. One of them is:
> All functions in the config will be evaluated and serialized before any tool in the Expo ecosystem uses it. This is because the config must be a json manifest when it's hosted. 

This means that you can use import statements to load libraries or other configuration. It also means that Expo is not yet initialized when the config is loaded, and because of that, you can't import Expo modules that require Expo to be initialized.

In the `expo-constants` package, we load the manifest for example. This can't be loaded because that still needs to be initialized with the `app.config.js`. Would you mind sharing your use case why you would like to import this package in the config?

Hope it helps!

**Comment by ShunyaWatanabe** [comment]
Thank you for the quick response and concise explanation! 

I have two files `google-services.json` and `google-services-prod.json` that I want to switch based on which release channel the app is in.

It would be great if you could tell me how to achieve this in a different way 


```
android: {
    package: '',
    googleServicesFile:
      releaseChannel.indexOf('prod') !== -1
        ? './google-services-prod.json'
        : './google-services.json',
    versionCode: 1,
    config: {
      googleMaps: {
        apiKey: '',
      },
    },
  },
```

**Comment by ShunyaWatanabe** [comment]
@byCedric 
It'd be great if you can share with me how to achieve this in another way!

**Comment by Nicholson85** [comment]
I also have a requirement for this as I am facing a similar issue to @ShunyaWatanabe .  Was there any solution on this or does anyone know how else I can achieve a similar result.

**Comment by hbendix** [comment]
>This means that you can use import statements to load libraries or other configuration. 

Where am I going wrong then? 

```
import { ExpoConfig, ConfigContext } from '@expo/config';

import { Config } from './Config/Clients/client/client.config';

export default ({ config }: ConfigContext): ExpoConfig => ({
	...config,
	...Config,
	privacy: 'unlisted',
	platforms: [
		'ios',
		'android',
	],
	orientation: 'portrait',
	notification: {
		androidMode: 'default',
	},
	androidStatusBar: {
		barStyle: 'dark-content',
	},
	splash: {
		resizeMode: 'contain',
	},
});
```

Throws: `Failed to read config at: **/app.config.ts`

**Comment by iM-GeeKy** [comment]
> 

Was there ever any recommendation on this? I'm encountering a similar scenario to @ShunyaWatanabe.

**Comment by donni106** [comment]
i have changed my `export const xyz = ...` to  `module.exports.xyz = ...` in the file i rely on. this way the `import` works in `app.config.js` and other stuff seems to behave like the way before 🤞
