### ISSUE TITLE
Expo APP crash in Singapore Region

### ISSUE THREAD

**Issue by xdajay** [expo/expo#8808]
Hi Expo Team,

All of our users in Singapore facing app crash (OTA Enabled, Priority Managed workflow).
**I have also reproduced (ios) this issue via VPN and switched to Singapore IP and confirmed the app is crashing on start.**  As its crashing on start could not get any crash log on sentry. Please verify this, also share host details for OTA bundle, will test if it is blocked in Singapore.

Thanks,
Ajay

**Comment by byCedric** [comment]
Hi @xdajay! Thanks for mentioning this, we have received similar reports in the past about Singapore and possible blocks for the Expo infrastructure. We haven't fully discovered if we are listed, and if so, with what endpoints or urls.

The `expo-updates` package, assuming you are using the latest version, uses the `https://exp.host/@<owner>/<project>` endpoint. It uses this endpoint to download the manifest for a possible update, as you can [see in the Android code over here](https://github.com/expo/expo/blob/c0e35c0b6e4381d1c3d08a532b14747407a6900e/packages/expo-updates/android/src/main/java/expo/modules/updates/loader/FileDownloader.java#L201-L234).

I have an example project that you can use to check if the endpoint is blocked. I've tested this myself with NordVPN and a Singapore server, but for me it just worked.

```
curl --request GET \
  --url https://exp.host/@bycedric/testbaremanifestextra \
  --header 'accept: application/expo+json,application/json' \
  --header 'expo-accept-signature: true' \
  --header 'expo-api-version: 1' \
  --header 'expo-json-error: true' \
  --header 'expo-platform: android' \
  --header 'expo-sdk-version: 37.0.0' \
  --header 'expo-updates-environment: BARE'
```

If you have any luck confirming there is an issue related to censorship or blockage, please do let us know!

**Comment by byCedric** [comment]
As a follow-up, there might be one thing you can do right now to prevent your app from crashing during startup. If you disable automatic updates by [setting `updates.checkAutomatically` to `ON_ERROR_RECOVERY` in your manifest](https://docs.expo.io/workflow/configuration/#updates).

If you [switch from the automatic OTA to manual OTA](https://docs.expo.io/guides/configuring-ota-updates/#manual-updates), your app is not "blocked" when starting up. And when you manually check for updates, you might be able to catch the exact error and send it to an error logging service like Sentry. If you are able to pinpoint the exact issue, we might get this resolved faster 😄 

Hope this helps!

**Comment by xdajay** [comment]
@byCedric 
So the problem was **Singapore does not have any region or state** our IP lookup was failing on region filed, I have added region. length validation before storing in Asyncstorage  and issue was fixed 🎉
