### ISSUE TITLE
Local notifications in Android is not expanding

### ISSUE THREAD

**Issue by leenasn** [expo/expo#881]
In Android, the local notifications are not expandable because it doesn't use BigText. Attaching a screenshot of the issue.

![notification-issue](https://user-images.githubusercontent.com/559752/32167192-2e27b824-bd36-11e7-96b3-c2e0ca8ba9cd.png)

BigText is being used in the listener. But the same is missing in the Notification Helper which is used for showing local notifications.

**Comment by AdamJNavarro** [comment]
Hey @leenasn,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,
Adam
