### ISSUE TITLE
gl_InstanceID not recognised.

### ISSUE THREAD

**Issue by paolo31415** [expo/expo#8813]
I can't seem to use `gl_InstanceID` from within my vertex shader with expo-gl. I get a "program not valid" error in the console. Is gl_InstanceID currently unsupported? I believe it does exist in WebGL 2.0.

**Additional info:**

1. https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_InstanceID.xhtml

2. `gl instanceof WebGL2RenderingContext` returns `true`.

3. I notice that `gl.drawArraysInstanced` is present in expo-gl, and does not fail to execute, so I'm guessing `gl_InstanceID` should be available in the vertex shaders?

4. If I place `#version 300 es` at the top of my shader code, the shader fails to compile, which I believe is required to access `gl_InstanceID`. Should work since WebGL2.0 is based on OpenGL ES 3.0 (`#version 300 es`)

5. `gl_VertexID` is also affected.

**Comment by paolo31415** [comment]
My bad it's working fine. GLSL issues. I was able to work out the problems using `gl.getShaderInfoLog(shader)`. Apologies for the red herring.

**Comment by banebyte** [comment]
try using 'gl_InstanceIndex'
