### ISSUE TITLE
"React Navigation Stack" header is not showing

### ISSUE THREAD

**Issue by karakusnavy** [expo/expo#8815]
### Summary of Issue (just a few sentences)

"React Navigation Stack" header is not showing. This was showing just 1-2 hours ago but now this not showing. 

https://hizliresim.com/z9sXxQ

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

my package json: 

`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "@firebase/component": "^0.1.13",
    "@react-native-community/datetimepicker": "2.2.2",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/material-bottom-tabs": "^5.2.10",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "axios": "^0.19.2",
    "expo": "^37.0.12",
    "expo-analytics": "^1.0.15",
    "expo-app-auth": "~9.0.0",
    "expo-apple-authentication": "~2.1.0",
    "expo-asset": "~8.1.5",
    "expo-constants": "~9.0.0",
    "expo-facebook": "~8.1.0",
    "expo-firebase-analytics": "~2.1.1",
    "expo-firebase-core": "~1.0.0",
    "expo-font": "~8.1.0",
    "expo-google-app-auth": "^8.1.0",
    "expo-google-sign-in": "~8.1.0",
    "expo-image-picker": "~8.1.0",
    "expo-notifications": "~0.1.1",
    "expo-web-browser": "~8.2.1",
    "firebase": "7.9.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-base64": "0.0.2",
    "react-native-dropdown-menu": "^2.0.0",
    "react-native-fbsdk": "^1.1.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^2.3.1",
    "react-native-paper": "^3.10.1",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-svg": "11.0.1",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-web": "^0.11.7",
    "react-native-webview": "8.1.1",
    "react-native-zendesk": "^2.1.0",
    "react-native-zendesk-chat": "^0.3.1",
    "react-navigation": "^4.3.9",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.10.2",
    "babel-preset-expo": "^8.1.0",
    "jest-expo": "^37.0.0"
  },
  "private": true
}
`

my stack navigator : 

`  <Stack.Navigator headerMode={true} >

        {
          this.state.phone_verified == false ?
            <>
              <Stack.Screen options={{ headerStyle: { backgroundColor: Colors.primary }, headerTitleStyle: { alignSelf: 'center' }, headerTintColor: '#fff' }} name='Telefon Onayla' component={PhoneVerified} />
            </>
            :
            null
        }
        <Stack.Screen
          options={{

            headerRight: () => (
              <TouchableOpacity onPress={() => this.setState({ contactModal: true })} >
                <Modal
                  animationType="slide"
                  transparent={true}
                  visible={this.state.contactModal}
                  onRequestClose={() => {
                    this.setState({ contactModal: false })
                  }}
                >
                  <SafeAreaView style={{ flex: 1 }} >
                    <View style={{ padding: 10, height: 60, backgroundColor: Colors.primary, justifyContent: 'center', elevation: 5 }} >
                      <TouchableOpacity onPress={() => this.setState({ contactModal: false })} style={{ flexDirection: 'row' }}>
                        <AntDesign name="arrowleft" size={20} color={'white'} />
                        <Text style={{ color: 'white', fontSize: 18, marginLeft: 10 }} >Geri</Text>
                      </TouchableOpacity>

                    </View>
                    <WebView
                      source={{ uri: 'https://beautico.co/contact' }}
                    />
                  </SafeAreaView>
                </Modal>
                <AntDesign name={'message1'} size={25} style={{ marginRight: 10, color: 'white' }} />
              </TouchableOpacity>
            ),
            headerStyle: { backgroundColor: Colors.primary }, headerTitleStyle: { alignSelf: 'center' }, headerTintColor: '#fff'
          }

          }
          name='Lokasyon Seç' component={SelectLocation} />
        <Stack.Screen options={{ headerStyle: { backgroundColor: Colors.primary }, headerTitleStyle: { alignSelf: 'center' }, headerTintColor: '#fff' }} name='Beautico' component={HairDressers} />
        <Stack.Screen options={{
          headerStyle: { backgroundColor: Colors.primary },
          headerTitleStyle: { alignSelf: 'center' },
          headerTintColor: '#fff',
          title: this.props.reduxState.shoppingCardReducers[0].hairdressername,

        }}
          name='Beautico Kuaförü'
          component={ChooseServices}
        />
        <Stack.Screen options={{
          headerStyle: { backgroundColor: Colors.primary },
          headerTitleStyle: { alignSelf: 'center' },
          headerTintColor: '#fff',
          title: this.props.reduxState.shoppingCardReducers[0].hairdressername + ' Hakkında',
        }}
          name='Info'
          component={HairDresserInfo} />

        {
          this.state.selectLocation == true ?
            <Stack.Screen options={{ headerStyle: { backgroundColor: Colors.primary }, headerTitleStyle: { alignSelf: 'center' }, headerTintColor: '#fff' }} name='Lokasyon Seç' component={SelectLocation} />
            :
            null
        }
      </Stack.Navigator >`

### Reproducible Demo

https://expo.io/@karakusnavy/hellothiserror

### Steps to Reproduce

renpm install ... remove node modules and reinstall...

### Expected Behavior vs Actual Behavior

Expected Behavior:

https://hizliresim.com/YrJtMG

Actual Behavior:

https://hizliresim.com/z9sXxQ

**Comment by AdamJNavarro** [comment]
Hey @karakusnavy,

This appears to be an issue specific to react-navigation rather than Expo. I would recommend creating an issue on the react-nav [repo](https://github.com/react-navigation/react-navigation) so that this can be appropriately investigated.

If this is only occurring with an Expo project and not a vanilla react-native project then we can re-open this issue and investigate further.

Cheers,
Adam

**Comment by yann-jacquet** [comment]
Hey ! Got the same issue today, working well in dev env and simulator but not showing when building in CI. I fixed strictly the versions in the `package.json` to : 

```
"@react-navigation/bottom-tabs": "5.5.0",
"@react-navigation/native": "5.4.3",
"@react-navigation/stack": "5.4.0",
```

Not a long term fix but works for now until further investigations.

**Comment by miguelarnalot** [comment]
Try adding a _layout.js

**Comment by chirag-g-shetty** [comment]
If you are using <Stack.Screen ...> (in 2025), this may solve your issue

Scenario - Inside the directory where you app.tsx / app directory is located, suppose you have sub-directories, which are for different groups / sub tasks for your app (ex - app/auth/otp-handling.tsx). Each such directory will have its own _layout.tsx, in which we typically have the settings for the header, which is local to the directory.
Lets say you are developing / testing the otp-handling.tsx, so to do that you may have imported that component directly into your app.tsx (the mistake which I had done). And the header styles were not applied, despite mentioning then clearly in the Stack.Screen in _layout.tsx. Here when you import a component which is under a subdir with its own _layout.tsx, into app.tsx, it (otp-handling.tsx, say) would follow the _layout.tsx of the app directory (outer one). 
Hence instead of importing it, use 'useRouter' from expo-router and do router.push('/auth/otp-handling'), it will work, as the otp-handling.tsx will now follow _layout.tsx of the auth directory. 
Believe me, it works!
