### ISSUE TITLE
Identify method not being called in expo-analytics-segment on Android

### ISSUE THREAD

**Issue by pxr13** [expo/expo#8817]
### Summary of Issue (just a few sentences)
The identify method is not being called in expo-analytics-segment on Android.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
 Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ~4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.15.5
```

### Reproducible Demo
[Snack](https://snack.expo.io/@patrickxrivera/eager-candy). Make sure to use Android!

You will need to get Segment keys for iOS and Android. [Docs](https://segment.com/docs/getting-started/02-simple-install/)

### Steps to Reproduce
1) Use the Android environment in the Snack above.
1) Add your API keys in the code.
2) Use the Segment debugger in their dashboard to see which events are being sent

### Expected Behavior vs Actual Behavior
Expected - the identify method should be called on Android.

Actual - the identify method is NOT called on Android.

**Comment by byCedric** [comment]
Hi @pxr13! Thanks for the issue report and reproducible example. Unfortunately, I can't reproduce this issue (both on Android and iOS). When I create a new Segment project and test your code, I see the identities coming in (see screenshot below). Maybe your code is cached with the wrong keys by the Metro bundler? One thing you can try is (ofc) reinstalling your node modules and clear the cache of Metro with `expo start --clear`. If you think this is still an issue on our end, feel free to create a new issue with a repro where it fails identifying the user 😄 

![Screenshot (90)](https://user-images.githubusercontent.com/1203991/84772716-a2aa7480-afdb-11ea-826f-09fd429a46a4.png)
