### ISSUE TITLE
Incorrect "react-native -v" output with tabs template project

### ISSUE THREAD

**Issue by iTOYS** [expo/expo#882]
## Expo CLI version:

```
$exp --version
45.1.0

$node -v
v8.6.0

$npm -v
5.3.0
```

## Incorrect react-native version when init "blank" expo app:

```
$exp init ExpoBlankApp
? Choose a template type: blank
[exp] Downloading project files...
[exp] Extracting project files...
[exp] Customizing project...
[exp] Starting project...
[exp] Your project is ready at

$cd ExpoBlankApp
$react-native -v
react-native-cli: 2.0.1
react-native: https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz
```

## If init "tabs" app then version are correct:

```
$exp init ExpoAppTabs
? Choose a template type: tabs
[exp] Downloading project files...
[exp] Extracting project files...
[exp] Customizing project...
[exp] Starting project...
[exp] Your project is ready at 

$cd ExpoAppTabs
$react-native -v
react-native-cli: 2.0.1
react-native: 0.49.3
```

Same for windows and mac.

**Comment by ide** [comment]
`https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz` is correct I think. It's just reading the version from package.json. You can use the matching releases from npm instead of GitHub but they often are missing bug fixes and aren't as tested. The tabs app should be printing out `https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz`.

**Comment by iTOYS** [comment]
But we've used version in [vscode-react-native](https://github.com/Microsoft/vscode-react-native/) extension, and now we can't. Outputs were the same(e.g. 0.49.3)

**Comment by ide** [comment]
Can you send a PR or fork react native cli then? We can't change what's listed in your app package.json.

**Comment by iTOYS** [comment]
Also we use `xdl.Versions.facebookReactNativeVersionToExpoVersionAsync` method. Will it work correct, if I exec it with version like `https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz`

**Comment by iTOYS** [comment]
BTW, if i run `npm install` with this [`package.json`](https://github.com/expo/new-project-template/blob/894b4e1360c4f59dd0316b2f4f67d29a04b0f072/package.json)
Output is correct, problem only with `exp init` blank app
