### ISSUE TITLE
Add locale support to FirebaseRecaptcha

### ISSUE THREAD

**Issue by osamasayed** [expo/expo#8831]
I have a multi-language react-native app and I am using firebase to log users in using their phone and I am using `FirebaseRecaptcha.FirebaseRecaptchaVerifierModal` as the verifier. I want to know if it's possible to have a config to set the current language/locale? Note that [Google ReCaptcha](https://developers.google.com/recaptcha/docs/language) makes it possible to set the locale.

**Comment by AdamJNavarro** [comment]
Hey @osamasayed,

I have yet to use the FirebaseRecaptcha module personally and admittedly have limited experience with Firebase as of late but you are able to pass in a firebase configuration so you may be able to set a locale. If not, you may be able to leverage the [Localization](https://docs.expo.io/versions/v37.0.0/sdk/localization/) module in tandem with it to achieve what you want. If these approaches do not work, I would recommend creating a [Feature Request](https://expo.canny.io/feature-requests).

In the future, for questions such as this one, it would be greatly appreciated if you went to our [Forums](forums.expo.io) as we try to reserve github issues for reproducible and actionable bug reports.

Thanks,
Adam
