### ISSUE TITLE
AuthSession is not completed in Android standalone app (but deep linking works)

### ISSUE THREAD

**Issue by ludgerey** [expo/expo#8834]
### Summary of Issue (just a few sentences)
I am basically using Brent's approach for a oauth authorization (see here https://github.com/brentvatne/hour-power/blob/master/app/hooks/useSpotifyAuth.ts). It uses `useAuthRequest` and works fine with Expo clients, where it uses the `exp://` scheme.
In standalone build I need to rely on a custom scheme in `returnUrl`/`redirectUri`. This works up to the point the user is redirected to the app. Apparently the redirect is not handled by `useAuthRequest`, but however if I attach a custom url handler `Linking.addEventListener('url', deepLinkingHandler);` I see that the redirect url reaches the app (`hoemefff://auth?code=[...]`).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.11.0 - /usr/local/bin/node
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.5

Standalone build on Android 10 OnePlus 6T

### Reproducible Demo
Not my code, but I basically adopted everything from Brent: https://github.com/brentvatne/hour-power/blob/master/app/hooks/useSpotifyAuth.ts

My code:

```ts
import { useEffect, useState } from 'react';
import { Platform } from 'react-native';
import { useAuthRequest, makeRedirectUri } from 'expo-auth-session';
import * as WebBrowser from 'expo-web-browser';
import Constants from 'expo-constants';
import getToken from '../api/getToken';
import EnvVariables from '../variables';

const discovery = {
    authorizationEndpoint: `${EnvVariables.authBase}/oauth/authorize`,
    tokenEndpoint: `${EnvVariables.authBase}/oauth/token`,
};

const USE_PROXY = Platform.select({
    web: false,
    default: Constants.appOwnership !== 'standalone',
});
const REDIRECT_URI = makeRedirectUri({
    useProxy: USE_PROXY,
    native: 'hoemefff://auth',
});
const CLIENT_ID = EnvVariables.oauthClientId;

WebBrowser.maybeCompleteAuthSession();

const useAuthenticator = (successCallback: (token: string) => void) => {
    const [error, setError] = useState<any | null>(null);
    const [isAuthenticated, setIsAuthenticated] = useState(false);

    const [authRequest, authResponse, promptAsync] = useAuthRequest(
        {
            clientId: CLIENT_ID,
            usePKCE: true,
            scopes: [],
            redirectUri: REDIRECT_URI,
            extraParams: {
                // On Android it will just skip right past sign in otherwise
                show_dialog: 'true',
            },
        },
        discovery,
    );

    useEffect(() => {
        async function updateFromAuthResponseAsync() {
            if (authResponse === null) {
                //
            } else if (authResponse.type === 'error') {
                setError(authResponse.error);
            } else if (authResponse.type === 'success') {
                const token = await getToken({
                    code: authResponse.params.code,
                    redirect_uri: REDIRECT_URI,
                    client_id: CLIENT_ID,
                    code_verifier: authRequest?.codeVerifier ?? '',
                });

                successCallback(token);

                setIsAuthenticated(true);
            }
        }

        if (!isAuthenticated) {
            updateFromAuthResponseAsync();
        }
    }, [authResponse]);

    return {
        error,
        isAuthenticated,
        authenticateAsync: () => promptAsync({ useProxy: USE_PROXY }),
    };
};

export default useAuthenticator;
```

```ts
const HomeScreen = ({ navigation }: HomeScreenProps) => {
    const dispatch = useDispatch();

    const { isAuthenticated, error: authError, authenticateAsync } = useAuthenticator(
        (token) => {
            dispatch(login(token));
        },
    );
```

### Steps to Reproduce
Implement an authenticator using `useAuthRequest`, `expo build:android`, install APK on Android

### Expected Behavior vs Actual Behavior

Expected: `useAuthRequest` should handle returnUrl in standalone as it does in expo client
Actual: `useAuthRequest` does nothing on returning to app using a custom scheme

**Comment by ludgerey** [comment]
I found the bug. There was code in my login routine which apparently only breaks on standalone builds (notifications), which had nothing to do with the authenticator.

 I'm sorry to have bothered you!

**Comment by AdamJNavarro** [comment]
Glad you got to the bottom of things, @ludgerey. Best of luck moving forward with your project!
