### ISSUE TITLE
Big problems in expo building the standalone app for android

### ISSUE THREAD

**Issue by milad1367** [expo/expo#884]
I know I should not tell here but I forced, and I saw many related issues but I cannot take a right answer.
1-For the first run, you need the Internet! The serious problem is that in Iran, a proxy should be used for it. because Iran is on the blacklist.That is, I have to tell the client to use the proxy for the first run!

2-The next problem is that if there is an error for any reason, it will enter the EXPO page!
Please help me with this.
[expo forums link](https://forums.expo.io/t/big-problems-in-expo-building-the-standalone-app-for-android/4389)

**Comment by btk** [comment]
This is in progress;

See: https://expo.canny.io/feature-requests/p/allow-standalone-apps-to-load-and-function-with-no-internet-connection

**Comment by milad1367** [comment]
tnx for a reply . I want to know if the ejected project and take APK with the android studio I will not have problems?

**Comment by terribleben** [comment]
Hi there! Sorry you're frustrated. We're working on letting apps boot offline, so hopefully we can launch that feature soon. As mentioned in the thread, it's only the first launch which is affected, subsequent launches can use a cache.

If you detach to ExpoKit then you have full control over the Android java code, so you can do whatever you want. However I don't think it would be trivial to get the app working totally offline. If you require offline-first support then the best bet is to wait for us to finish supporting it.

**Comment by milad1367** [comment]
thanx for the answer and hoping

**Comment by webdevbyjoss** [comment]
@terribleben Hey, I've recently detached to ExpoKit and not able to spot the documentation describing the build for offline mode (no internet available on the first app run).

Looked through the following documentation pages:
- https://docs.expo.io/versions/latest/guides/detach.html#all-you-need-is-to-distribute-your-app-in-the-itunes-store-or-google-play-expo-can-build-binaries-for-you-in-that-case-if-you-detach-we-cant-automatically-build-for-you-any-more
- https://docs.expo.io/versions/latest/guides/advanced-expokit-topics.html#configuring-the-js-url
- https://docs.expo.io/versions/v27.0.0/guides/offline-support
- https://docs.expo.io/versions/latest/guides/configuring-ota-updates.html

So I'm building the app with Android Studio/Gradle and Xcode, but my app on both Android & iOS still expects the internet connectivity to start.

Maybe you can point me to the right page in docs?
It's a bit confusing that there is no easy way to find the documentation that describes the release process to AppStore/Android Market when you eject to ExpoKit - as that is probably the primary use case once you detach.
