### ISSUE TITLE
Expo Splash Screen errors on IOS

### ISSUE THREAD

**Issue by CarterBland** [expo/expo#8852]
### Summary of Issue (just a few sentences)

When using the npx expo-splash-screen command I get a variety of issues.

Some of them include:

```
Carters-MacBook-Pro-2 :: ~/apps/spire-native-app » npx expo-splash-screen -r cover -p ios "rgb(255,255,255)" ./assets/splash.png  

(node:31050) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/carterbland/apps/spire-native-app/ios/spire/Info.plist'
(node:31050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31050) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and if I fix that by moving the file then I get

```
(node:29843) UnhandledPromiseRejectionWarning: Error: Couldn't locate proper PBXGroup '.xcodeproj' file.
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

targeting IOS

```
Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.18.6
```

### Reproducible Demo

- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve

As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

### Steps to Reproduce

```
npx expo-splash-screen -r IOS -p android "rgb(255,255,255)" ./assets/splash.png
```

### Expected Behavior vs Actual Behavior

Expected to create the splash screen, but all it does is error out.

**Comment by byCedric** [comment]
Hi @CarterBland! Thanks for the issue, I'm not 100% sure what's happening here. If I set up a new bare project and run that exact command, I can't reproduce this. Are you able to create a small repro or grant me (limited/temporary) access to your project?

**Comment by CarterBland** [comment]
@byCedric Hey, I am using an ejected app, not bare. Was that package only made for bare?

**Comment by byCedric** [comment]
That should work as well :) Did you resolve this issue?
