### ISSUE TITLE
[expo-payments-stripe] Calling cancelApplePayRequestAsync fails with unhandled promise rejection

### ISSUE THREAD

**Issue by curtismgt** [expo/expo#8854]
### Summary of Issue (just a few sentences)
Calling the `cancelApplePayRequestAsync()` function on the expo-payments-stripe library causes an immediate unhandled promise rejection saying `StripeModule.cancelApplePayRequestAsync` is not a function.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^4.3.7 => 4.3.7 
    npmGlobalPackages:
      expo-cli: 3.21.5

### Steps to Reproduce

1. Bare workflow project on iOS simulator/device
2. Install expo-payments-stripe 8.2.2
3. Await paymentRequestWithApplePayAsync with items from documentation
4. Call cancelApplePayRequestAsync after await
5. Failure

### Expected Behavior vs Actual Behavior

In looking through the code, the issue is the call to `StripeModule` inside `Stripe.ts`. All other calls do not have the 'async' suffix, but the cancel one does. When removing the async suffix, everything works. This must be a typo/auto-complete problem.

**Comment by sjchmiela** [comment]
Just published a fix as `expo-payments-stripe@8.2.3`! 🎉 Sorry you had to encounter this problem!
