### ISSUE TITLE
The application is upside down after loading on iPad

### ISSUE THREAD

**Issue by artemrsx** [expo/expo#8866]
### Summary of Issue (just a few sentences)
The application is upside down after loading on iPad, after manual 180deg rotation, app works as expected
The same behaviour on real iPad device, works fine with Android

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
OS: macOS 10.15.5,
Simulator: Version 11.3.1,
"expo-cli" 3.18.6,
"expo-sdk": "^37.0.0",

npm packages:
"react": "16.9.0",
"react-dom": "16.9.0",
"react-native": "0.61",
"react-navigation": "^4.0.10",

### Reproducible Demo

app.json file:
```
"orientation": "landscape"
```

App.js file
```
import React from 'react';
import { View, Text } from 'react-native';

const App = () => {
  return (
    <View style={{ flex: 1, backgroundColor: 'grey', justifyContent: 'center', alignItems: 'center' }}>
      <Text style={{ position: 'absolute', fontSize: 30, top: 0 }}>TOP</Text>
      <Text style={{ position: 'absolute', fontSize: 30, left: 0 }}>LEFT</Text>
      <Text style={{ position: 'absolute', fontSize: 30, right: 0 }}>RIGHT</Text>
      <Text style={{ position: 'absolute', fontSize: 30, bottom: 0 }}>BOTTOM</Text>
    </View>
  );
};

export default App;
```
### Steps to Reproduce
[video](https://www.youtube.com/watch?v=LFqLXp3DSrM)
1. create simulator build with "expo build:ios"
2. download it and drop to simulator
3. start app, failure, screen rotates by 180deg

### Expected Behavior vs Actual Behavior
no rotation if iPad in landscape orientation

**Comment by byCedric** [comment]
Hi @artemrsx! Thanks for your issue report. I can confirm this bug, but only on app startup. Unfortunately, we don't have a lot of bandwidth at the moment to fix it. But we will get on this eventually!

**Comment by javascripter** [comment]
We have a  landscape only app that's used in a kiosk mode. Is there any workaround using ScreenOrientation module until this gets fixed?

**Comment by sergeu90** [comment]
I have some issue on iPad

**Comment by sergeu90** [comment]
@byCedric  Hi. Do you planning fix it is issue?
