### ISSUE TITLE
symlink component is not resolving

### ISSUE THREAD

**Issue by nomi9995** [expo/expo#8867]
### Summary of Issue (just a few sentences)
I am making a new ecosystem where I need to run the symlink component in the project. symlink are working with create-react-app with override some properties but it is not working on expo

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.21.6-alpha.0 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.15.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.6-alpha.0
```

### Reproducible Demo
you can make component symlink to your project and import that component in any screen will give you the error `Unable to resolve`

**Comment by byCedric** [comment]
Hi @nomi9995. Unfortunately, [Metro doesn't seem to support symlinks at the moment](https://github.com/facebook/metro/issues/1). Because React Native uses this bundler, so are we. In Create React App, webpack is used to process all code, that's why it's possible to use it there. If you want support for symlinks in Metro, please provide your use case in that issue I linked. It might help persuade the maintainers to add support for this.

Hope it helps!

**Comment by lucksp** [comment]
> If you want support for symlinks in Metro, please provide your use case in that issue I linked. It might help persuade the maintainers to add support for this.

I know this is closed, but ran across this thread.  Our main reason for needing symlinks is we have component library being built and we want to be able to test the packages inside our user app before the package gets released.  
This seems to have broken inside SDK 46.

**Comment by brentvatne** [comment]
hey @lucksp! please create a new issue and fill out the template
