### ISSUE TITLE
Calendar in Expo document not working

### ISSUE THREAD

**Issue by WIWAT43** [expo/expo#8876]
I am new dev so I learn coding from document i found that Calendar example is not working. I try it on Snack and Expo in my phone when I click on button noting happen. any suggestion about calendar?

https://docs.expo.io/versions/v37.0.0/sdk/calendar/

**Comment by byCedric** [comment]
Hi @WIWAT43! This example only logs output from the Calendar API. You might not see anything changing, but it actually creates new calendars. If you open it in snack, press "0 errors" (bottom left), and click the log tab you should see stuff happening. You can also double-check this if you open your calendar app. There should be (at least one) "Expo Calendar" listed in your sidebar, assuming you use Android.

Hope it helps!

**Comment by WIWAT43** [comment]
Wow Thank you very much

Sent via the Samsung Galaxy S9, an AT&T 5G Evolution capable smartphone

________________________________
