### ISSUE TITLE
Standalone android app crashing after showing up launch screen

### ISSUE THREAD

**Issue by jun-nguyen-goldenowl** [expo/expo#8878]
### Summary of Issue

Hi there, I have faced an issue that my standalone android app crashed all the time after showing up the splash screen. On dev environment, the app works well on both platforms iOS and Android. 

I used `expo build:android -t apk` command to build the app.
I have tried installing the standalone app using apk file on my Redmi phone (Android 10), an emulator Nexus 5X API 29 x86 (Android 10), an emulator Pixel 3 API 27 (Android 8.1) and just got the same result.

This is what I received from `adb logcat`:
![Screen_Shot_2020-06-19_at_9_40_49_AM](https://user-images.githubusercontent.com/52815696/85110858-b523e880-b23d-11ea-896d-9a2f14e1e8de.png)

This is the error message I received when the app crashed on the second time I launched it:
![Screenshot_2020-06-19-10-59-24-436_com_miui_bugreport](https://user-images.githubusercontent.com/52815696/85108509-07fba100-b23a-11ea-812f-0c0af0c3ea6d.jpg)

- Webpack config: 
![webpack](https://user-images.githubusercontent.com/52815696/85111405-7d697080-b23e-11ea-8060-0be71213b4fb.png)

- Babel config: 
![babel](https://user-images.githubusercontent.com/52815696/85111501-a0942000-b23e-11ea-9566-220b77696ec4.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.21.7 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.1/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: 0.11.25 => 0.11.25
      expo: ^37.0.0 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.7

### Expected Behavior vs Actual Behavior

* Expected behavior: The app runs correctly and shows up the Login screen.
* Actual behavior: The app crashed all the time after showing up the splash screen.

**Comment by brentvatne** [comment]
have you tried toggling development and production mode to test it in expo client before building a standalone app? https://docs.expo.io/workflow/development-mode/

**Comment by jun-nguyen-goldenowl** [comment]
hi @brentvatne, I've just switched to Production mode and got this issue

<img width="459" alt="Screen Shot 2020-06-22 at 2 22 28 PM" src="https://user-images.githubusercontent.com/52815696/85259812-e1d13d80-b493-11ea-9a4c-b533ffe39e10.png">

**Comment by byCedric** [comment]
Hi @jun-nguyen-goldenowl! This indicates that something is wrong with Metro (see [similar issue](https://github.com/facebook/react-native/issues/25622)). If reinstalling and clearing the cache doesn't work, we might need a repro for this to fully investigate what's going on. Are you able to send that?

**Comment by jun-nguyen-goldenowl** [comment]
Hi, @byCedric, I don't know how to repro for this issue.
Btw, I've just removed the red-underlined code line in babel.config.js and I can run the app in production mode. But, It resulted in the feature Fast refresh for web is no longer work. Whenever I save code, the browser auto reload the page to get updates instead of Hot uploading

![babel](https://user-images.githubusercontent.com/52815696/85277270-52388880-b4ad-11ea-807e-99dc61262f38.png)

**Comment by jun-nguyen-goldenowl** [comment]
hi @brentvatne @byCedric, the function `api.env('production')` returned 'undefined' even I launch the app under production mode. (Don't know why!!! \_shrug_/ ) So that the 'react-refresh/babel' was included in the production compiled code. It caused the crashing issue. I added a ENV 
 as a condition to disclude the plugin `react-refresh/babel`. Now, it woks.

**Comment by realabbas** [comment]
In my case, it was due to missing credential in AndroidManifest.xml file that I forgot to add. I ran `adb logcat` and found error in the logs thats why the app was crashing on the splash screen. 

    <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="YOUR_KEY"/>

Check for misconfiguration by running `adb logcat` and read logs when your app is crashing
