### ISSUE TITLE
androidNavigationBar sticky-immersive doesn't work when app comes to foreground. 

### ISSUE THREAD

**Issue by Mahesha-Bhat** [expo/expo#8879]
hi,

```
"androidNavigationBar": {
      "visible": "sticky-immersive",
      "backgroundColor": "#000000"
    },

```
1) when my app comes back to foreground from any other app, system default navigation bar will be shown instead of  one which i have mentioned in app.json
2) In mobile which does not have notch (example redmi series) default white status bar  will be given even though i have specified black backgroundColor. 
I tried to override this using StatusBar.setBackgroundColor() still same result.
please fix this issue.

**Comment by cruzach** [comment]
@Mahesha-Bhat I believe this issue was fixed in https://github.com/expo/expo/pull/7770, what SDK are you using?

**Comment by Mahesha-Bhat** [comment]
Hi,
I am using the latest SDK. It doesn't work in expo. But when I tried
installing it in real device then it worked fine. Still this problem is
there in expo app.
In expo app for redmi series still white statusBar is displaying.

**Comment by cruzach** [comment]
> But when I tried
installing it in real device then it worked fine. Still this problem is
there in expo app.

So in the Expo client on a device it works, or only works in standalone apps? This fix was probably only applied to standalone apps, and will be applied to the Expo Client app in the next release (coming very soon)

**Comment by Mahesha-Bhat** [comment]
Ya it works properly in stand alone app but not in expo.

**Comment by cruzach** [comment]
I confirmed this is fixed in the next release of the Expo Client, we'll announce the release on our [blog](https://blog.expo.io/)
