### ISSUE TITLE
ImagePicker - Does not work on web iPhone

### ISSUE THREAD

**Issue by sandrina-p** [expo/expo#8880]
### Summary of Issue
I'm using [ImagePicker.launchImageLibraryAsync](https://docs.expo.io/versions/latest/sdk/imagepicker/) and it works fine on native iOS and on the web desktop (chrome, firefox, safari), but it does not work on web mobile on Safari.

### Environment
<details>
 <summary>Click to see diagnostics</summary>

  ```
  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.5
```
</details>

- iPhone SE - OS13.0 - Safari

### Reproducible Demo

- The [snack from ImagePicker tutorial](https://snack.expo.io/@sandrina-p/06d6ac) is enough to replicate the problem.

### Steps to Reproduce
- Create a project locally with the code from the Snack
- Run the code locally on a phone browser (not on Expo client).
- Click the button to select an image.

### Expected Behavior vs Actual Behavior
- Expected: Open the native mobile image picker
- Reality: Nothing happens.

**Comment by EvanBacon** [comment]
Hmm looks like you need to invoke the method in a user-interaction. I'll open a PR to document this more clearly.

**Comment by sandrina-p** [comment]
Hi @EvanBacon, I didn't understand exactly the diff with the new docs. I'm already invoking the method directly:

```
async function handleClick() {
  console.log('here')

  result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true,
        aspect: [1, 1],
        quality: 0.3,
        base64: false,
        exif: false,
      })
  console.log('resul:', result)

}
<Button onPress={handleClick}>Select phone<Button>
```

the log `here` is logged, but the `result` isn't, and the camera or library isn't opened. What am I missing?
