### ISSUE TITLE
expo-file-system save a damn file in ios music folder

### ISSUE THREAD

**Issue by Ben-Mark** [expo/expo#8885]
First I wanna say, I have ejected from expo.
Second, expo-file-system PERMISSIONS don't have any regards to ios music folder.
Wasted an entire day on google searching for a way via expo to save an audio file to music folder
on device.

All I found was CAMERA_ROLL permissions or AUDIO_RECORDING (mic permissions required)

I am really disappointed.

**Comment by brentvatne** [comment]
i suggest filing a bug with apple. you cannot save files to the music folder on ios as far as i know.
