### ISSUE TITLE
[expo-updates][Bare] setting `expo.modules.updates.ENABLED` to false does NOT stop updates

### ISSUE THREAD

**Issue by jonathanstiansen** [expo/expo#8886]
### Summary of Issue (just a few sentences)
When working in bareworkflow turning off updates for android does not work.

`    <meta-data android:name="expo.modules.updates.ENABLED" android:value="false"/>`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.14.0 - ~/.nvm/versions/node/v13.14.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.9

### Reproducible Demo
1. `expo init` -> Bareworkflow
2. add this to `App.js` component
```

  const update = async () => {
    try {
      const update = await Updates.checkForUpdateAsync();
      if (update.isAvailable) {
        await Updates.fetchUpdateAsync();
        alert('Got update')
        await Updates.reloadAsync()
      }
    } catch (e) {
      console.log("Update fail", e);
    }
  }

  React.useEffect(() => {
    update()
  }, [])

```
2. add: `    <meta-data android:name="expo.modules.updates.ENABLED" android:value="false"/>` to `xxx/main/AndroidManifest.xml`
3. run `yarn android --variant=release`
4. Change `App.js` to include some text that is recognizable
5. run `expo publish`
6. Restart the app,
7. note that the alert is shown and the new text is displayed

[here](https://github.com/jonathanstiansen/bareWorkflorUpdatesRepo) is a repo to demonstrate.

### Expected Behavior vs Actual Behavior

I'd expect no updates to be received, or gotten from the app. But all are.

**Comment by esamelson** [comment]
yikes! thanks for the report, this has been fixed in expo-updates@0.2.10.
