### ISSUE TITLE
In expo do we have component to select a folder to save file?

### ISSUE THREAD

**Issue by SkyInTheSea** [expo/expo#8891]
It may like documentpicker, but just select folder as file location

**Comment by byCedric** [comment]
Hi @SkyInTheSea! We don't have a "folder picker" for this use case. A phone has a different filesystem compared to desktops, it's unusual for apps to allow you specify a specific folder. It's more restricted, some apps has access to only a couple of folders. In case you have more questions, please try the [forums](https://forums.expo.io/) or [community slack](https://slack.expo.io/) instead. Github is for bug reports only.

**Comment by trydalch** [comment]
This seems like a valuable feature to have. Not to mention, Android is linux based, where files and folders are treated basically the same.

Plenty of text editor applications allow you to select a folder to save in (Bear, 1Writer, etc.). Seems like if you can browse the folders using the DocumentPicker, you should be able to select a folder and get stats about it instead (like it's location, so you can save new files there, or copy them from the application's local directory).

**Comment by ROODAY** [comment]
Are there any updates on this? I too would like to be able to pick a directory to save files into.

**Comment by chmac** [comment]
You can use [react-native-document-picker](https://github.com/rnmods/react-native-document-picker) to select folders.

**Comment by emirhankarakoc** [comment]
> You can use [react-native-document-picker](https://github.com/rnmods/react-native-document-picker) to select folders.

this thing doesnt works without android studio & expo. i tried a lot of times to install 60 MB android34 BUT google servers doesnt want to give me that file. 

i need another solution.
