### ISSUE TITLE
[expo-camera] Choose recording codec #Camera #HEVC

### ISSUE THREAD

**Issue by MattiaMarche** [expo/expo#8892]
### iOS default: H.265/HEVC
Newer versions of iOS uses H.265/HEVC to generate video recording files by default.
This codec is not compatible with the majority of browsers, and they have no plans to support it in the future (https://caniuse.com/#feat=hevc).
This is a huge problem when an application should upload any kind of recording made in iOS that should be displayed in a web browser, or in any device that doesn't use this codec.

### Request
Since iOS 10 it is possible to specify the output format: https://developer.apple.com/documentation/avfoundation/avcapturemoviefileoutput/1388448-setoutputsettings?language=objc
Would be great to be able to specify the codec/output format of a video recorded by expo-camera.

### Informations (added on: June 26 2020)
RNCamera added this feature:
- https://github.com/react-native-community/react-native-camera/issues/1330
- https://github.com/bunchtogether/react-native-camera/commit/b970ea12e838e7eb55de5c5cc93c66b3ff69fc77

It could be helpful to read that.

### Optional improvements (added on: June 26 2020)
They also faced issues when setting an high quality with an older codec: https://github.com/react-native-community/react-native-camera/issues/1858
It seems they choose to throw an exception for that (I couldn't test it, correct me if I'm wrong).

**Comment by zazoomauro** [comment]
Any update on that?

**Comment by SparseSpeculator** [comment]
It would help greatly if this feature could be implemented! :)

**Comment by Rpaixao** [comment]
Yeah, this issue is also blocking my developments. It would be great if it could be done.

**Comment by GregKapustin** [comment]
+1 would use too !

**Comment by bbarthec** [comment]
Some changes in the following packages that may fix this issue have just been published to npm under `next` tag 🚀

| 📦 Package | 🔢 Version | ↖️ Pull requests | 📝 Release notes |
|:--:|:--:|:--:|:--:|
| [expo-camera](https://www.npmjs.com/package/expo-camera/v/11.1.0) | 11.1.0 | #12772 | [CHANGELOG.md](https://github.com/expo/expo/blob/master/packages/expo-camera/CHANGELOG.md) |

If you're using bare workflow you can upgrade them right away. We kindly ask you for some feedback—even if it works 🙏

They will become available in managed workflow with the next SDK release 👀

Happy Coding! 🎉
