### ISSUE TITLE
 debugView doesn't receive any event/connection in bare workflow with iOS expo-firebase-analytics

### ISSUE THREAD

**Issue by OscarYuen** [expo/expo#8893]
### Summary of Issue (just a few sentences)
debugView in firebase doesn't receive any event in bareworkflow after adding debug enabled argument in Xcode launch option.  [https://firebase.google.com/docs/analytics/debugview#ios](https://firebase.google.com/docs/analytics/debugview#ios)

All the events logged are submitted to production view.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.7.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.9

### Reproducible Demo
I just followed these two guides
https://docs.expo.io/guides/setup-native-firebase/?redirected
https://docs.expo.io/versions/v37.0.0/sdk/firebase-analytics/

and can't find any device connected to debugView in firebase after launch.

### Steps to Reproduce
1. Initialize bare workflow
2. Install expo-firebase-analytics and run npx pod-install
3. Add iOS app in Firebase and follow the setup guide for bareworkflow in https://docs.expo.io/guides/setup-native-firebase/?redirected
Firebase confirms it has connection with the app after set-up
4. Add debug enable argument in launch option in xcode in debug scheme(https://firebase.google.com/docs/analytics/debugview#ios)
5. run npx react-native run-ios --configuration Debug

### Expected Behavior vs Actual Behavior

Expected Behavior:
Should at least see the debug device in debug view on firebase after launching
No events are logged in production.

Actual Behavior:
No device available is shown in debug view on firebase.
All the events are logged in production instead.

<img width="802" alt="Screenshot 2020-06-20 at 10 00 16 PM" src="https://user-images.githubusercontent.com/5617834/85203619-8c851700-b341-11ea-94ed-d63e2152889e.png">

**Comment by OscarYuen** [comment]
After switching to android, I found the debug view is working.
And switch the library to react-native-firebase, iOS is still not working.

**Comment by IjzerenHein** [comment]
I don't think the problem lies with `expo-firebase-analytics` or the Expo tooling. When you run `npx react-native run-ios --configuration Debug` it runs the `react-native cli` which in turn should pass the arguments and options to XCode. You might want to drop this question in the react-native repo or the react-native cli repos for this.
