### ISSUE TITLE
app is restarting on long press

### ISSUE THREAD

**Issue by BodoWissemann** [expo/expo#8895]
I built an app using expo which uses onLongPress(). During development and testing everything worked as expected.

Then I built it using 'expo build:android -t app-bundle' and uploaded it to playstore. 

Now when I install the app from playstore, the onLongPress-functionality doesn't work anymore and the app restarts completely when pressing long. Even the redux-store is cleared.

I've no clue what I can do about it because I'm unable to reproduce this behavior locally.

thanks in advance

**Comment by byCedric** [comment]
Hi @BodoWissemann! Could you try [starting your app locally in production mode](https://docs.expo.io/workflow/development-mode/#toggling-development-mode-in-expo-dev-tools)? Maybe that could give you some answers to why the app is restarting. Without a repro I'm "flying blind", so I'm not sure what to do next. If you are able to extract the code to a small repro, that would help a lot. If not, I'm not sure how I can help you further.

Hope it helps!

**Comment by BodoWissemann** [comment]
Thx, I was hoping that already this could give you a hint.

Running in production-mode works as expected, its only happening when building standalone-apps.

I can't reproduce it atm, but I'll try a few things and get back to you if a have any more detailed questions.

**Comment by BodoWissemann** [comment]
OK the problem appeared because I had a typo in app.json:

permissions: ["VIBRATE,"] instead of ["VIBRATE"]

This was no problem in the expo-wrapper during development but caused an immediate crash + restart as standalone-app.
