### ISSUE TITLE
[android][facebook] upgrade FB SDK 

### ISSUE THREAD

**Issue by iambavith** [expo/expo#8897]
Please provide the following:

SDK Version: 37
Platforms(Android/iOS/web/all): Android
Facebook audience network SDK used for Android platform is v5.1, which is more than a year old and using it effectively means no ads served by Facebook and loss of revenue. Thankfully, iOS is using latest v5.9 of SDK. Seems like Android has been forgotten for a while. Refer -

https://github.com/expo/expo/blob/master/packages/expo-ads-facebook/android/build.gradle#L61

For next version of SDK release, can updating the FB audience network version be prioritized?

**Comment by bozzmob** [comment]
Any update on this? This is important for the app we are working on.

**Comment by abudhia-oyo** [comment]
Hi guys,

Is it planned to be fixed, or is there a workaround for managed workflow?

**Comment by cruzach** [comment]
This will be addressed in https://github.com/expo/expo/pull/10430, and is being tracked in two other issues so im going to close this as a duplicate
