### ISSUE TITLE
Push notifications in builds

### ISSUE THREAD

**Issue by thefabicraft-github** [expo/expo#8898]
# Push notifications in production builds

Hey. I have an issue with push notification in the production builds of an app. I have tested many things including to switch from my own build server to expos server but that didn't help either. With the expo app it gets the token, but with a production build it just does nothing.

# Used code to get the token
```js
pushKeyGet = async () => {
        const { status: existingStatus } = await Permissions.askAsync(Permissions.NOTIFICATIONS)
        let finalStatus = existingStatus

        if (finalStatus !== 'granted') {
            return Alert.alert("Fehler", "Ohne die Zustimmung können wir Ihnen keine Nachrichten schicken.");
        }

        let token = await Notifications.getExpoPushTokenAsync()
        await this.storeData(token, "@ep/notif/token")

        fetch(config.apiserver + "/addPushKey", {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                token: token
            })
        }).then(result => result.json()).then(async res => {
            if (res.request.status != "SUCCESS") {
                await this.removeData("@ep/notif")
                await this.removeData("@ep/notif/token")
                return Alert.alert("Fehler", "Ein unbekannter Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.")
            }
        }).catch(async e => {
            await this.removeData("@ep/notif")
            await this.removeData("@ep/notif/token")
            return Alert.alert("Fehler", "Ein unbekannter Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.")
        })
    }
```

# Repo
The source code of the app is private but I can give you access to the part of the app, that makes problems.

# Testing
I only tested the build on Android.

# Building
I am building with turtle-cli but using the normal expo-cli to build didn't change anything.

Many thanks in advance
Fabian

**Comment by AdamJNavarro** [comment]
Hey @thefabicraft-github,

I created a new Expo project and I was able to generate a token just fine on my Samsung Galaxy 8. Did you ensure you have FCM configured properly for you project? Could it be device specific?

Since I wasn't able to reproduce it on my end, could you give me the exact versions and steps you took from `expo init` to building the app?

Cheers,
Adam

**Comment by thefabicraft-github** [comment]
Hey @AdamJNavarro,
Thank you for the help, I will check it tomorrow and see, if that will fix it.

If it doesn't, I will provide every information you need to help. Of course I can make the push part of the app as a repo.

Thank you very much 👍
Fabian

**Comment by manikantasai-aurora** [comment]
Hi, @AdamJNavarro and @thefabicraft-github 

I am facing a problem production builds, I wasn't to generate an ExpoPushToken on my Asus M1 pro. when I am running an app through the Expo client app, ExpoPushToken works.

"expo": 37.0.12
"expo-permissions": "~8.1.0",


Please check the below expo snack. This is the exact code I used in my production build: 

https://snack.expo.io/?platform=android&name=Push%20Notifications&sdkVersion=37.0.0&dependencies=expo-constants%2Cexpo-permissions&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv37.0.0%2Fpushnotifications.js


Thank you
Mani

**Comment by thefabicraft-github** [comment]
Hey @manikantasai-aurora,
With your code, I was able to generate a push token on my Pixel 3.
Check the screenshot below

https://photos.app.goo.gl/nBKrekf3VLM3JuQU6

Does the console give you any error?

Cheers
Fabian

**Comment by thefabicraft-github** [comment]
Hey @manikantasai-aurora,
In my first comment, I thought you had problems with the expo client. I am sorry, that I didn't understand it right first and commented.

Did you confirm that FCM is configured properly?
Check the comment by Adam here for the instruction docs.

Have a nice day
Fabian

**Comment by manikantasai-aurora** [comment]
Hi, @thefabicraft-github 

With the expo app, it gets the token, but with a production build, it just does nothing. I think no need for FCM config because my app is in the developing stage (No Backend calls) so I am using the expo push notification tool to send notifications on my Asus M1 pro.

Thank you
Mani

**Comment by thefabicraft-github** [comment]
Hey @manikantasai-aurora,
According to the documentation, FCM is required for every standalone Android expo app.
So, you have to configure FCM to get it working in a standalone build.

Cheers
Fabian

**Comment by manikantasai-aurora** [comment]
Hi, @AdamJNavarro 

Thank you for the information, I will check it now and see if that will fix it.

Thanks
Mani

**Comment by thefabicraft-github** [comment]
Hey @AdamJNavarro,
thank you for your help. I was able to generate a token with FCM configured.
Now my question is: The notification tool located at https://expo.io/notifications gives an error like this:
> InvalidCredentials: Unable to retrieve the FCM server key for the recipient's app. Make sure you have provided a server key as directed by the Expo FCM documentation.

I have a server key from firebase but I dont know where to fill it in. There is no input on that page. Can you please help me?

Thank you so much
Fabian

**Comment by thefabicraft-github** [comment]
Or do I have to upload like this?
> expo push:android:upload --api-key <key>

Thank you
Fabian

**Comment by thefabicraft-github** [comment]
Hey @AdamJNavarro,
I made set the token through the command and it worked.
Thank you so much for your help and your time.

Have a nice day and safe
Fabian
