### ISSUE TITLE
Question : react-native-maps versionning

### ISSUE THREAD

**Issue by echap** [expo/expo#890]
Hello there, 

Consequently to my issue posted [on the airbnb repo](https://github.com/airbnb/react-native-maps/issues/1743), I would like to know the position of the expo team regarding to it's **native dependancies versionning** ? More precisely, in which timeframe do you believe the dependancy `react-native-maps@^0.17.1` (or above) will be part of the expo client ?

Furthermore, I would like to know where could we find out which versions are embedded in the expo client ?

Thanks a lot for your answers, you're doing an awesome job ! :)

**Comment by brentvatne** [comment]
we will update react-native-maps to the latest when release sdk23, which is I believe about 3 weeks from now

**Comment by echap** [comment]
Great ! Thank you for this information :)

**Comment by ide** [comment]
@echap To answer your question about how to learn which version is in the Expo client, go into `node_modules/expo/package.json` and you'll see `react-native-maps` listed as a dependency (that's how it works today, at least).
