### ISSUE TITLE
useWindowDimensions

### ISSUE THREAD

**Issue by andrenerd** [expo/expo#8901]
### Summary of Issue (just a few sentences)
seems that `useWindowDimensions` is not available in expo 37.0.1, even though it was implemented in RN 0.61: 
https://reactnative.dev/docs/usewindowdimensions

can try:
```
import { useWindowDimensions } from "react-native";
# useWindowDimensions  is undefined
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
-

### Reproducible Demo

- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve

As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

**Comment by byCedric** [comment]
Hi @andrenerd, please fill in the full issue template next time. Without this, I won't be able to help you or investigating this issue. I tried reproducing this, but with a new blank project, I wasn't able to. On the react-native docs, you also can see a Snack that uses this `useWindowDimensions` hook (using Expo). Could you provide a small repro where this issue happens?

**Comment by brentvatne** [comment]
not sure what is happening in your project, it does indeed exist in sdk 37, as @byCedric says a reproducible example would be interesting to see. that said, i would strongly advise against using this in rn 61! it has a bug that causes an infinite loop - https://github.com/facebook/react-native/issues/26733.

**Comment by andrenerd** [comment]
@brentvatne @byCedric 
ok, thanks. 
have decided not to use it for now (in favour of Dimensions).
please, close the issue.

ps. the setup was
```
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
```
