### ISSUE TITLE
Blurry Splash screen on standalone Android app

### ISSUE THREAD

**Issue by RazaShehryar** [expo/expo#8902]
Hi

I have recently deployed my build on Google Play Store. I noticed that the Splash screen appearing in the standalone build is blurry. On dev, it is working fine. I have also tested it on iOS standalone build and dev, it is fine on the platform. The only problem is with the Android standalone build. I am using Expo SDK 36. 

The image resolution is 414 x 896. ResizeMode is "contain".

Android development screenshot:

![Screenshot_20200621-231555_Expo](https://user-images.githubusercontent.com/42263739/85232056-c4f62500-b415-11ea-808b-b606957899f8.jpg)

Android standalone build screenshot:

![Screenshot_20200621-231505_ePage Service Provider](https://user-images.githubusercontent.com/42263739/85232064-cde6f680-b415-11ea-93ba-8e1b66f19569.jpg)

I am using Samsung Galaxy A10 for the screenshots.

Here's my expo diagnostics:

Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.5

**Comment by byCedric** [comment]
Hi @RazaShehryar, I would recommend using a higher resolution as your splash screen. You can see an example in our [SplashScreen guide](https://docs.expo.io/guides/splash-screens/#make-a-splash-image). `contain` will scale or stretch the image on Android, possibly causing the blurry-ness. I'm not sure why your development version would show a non-blurry version though. If that doesn't work for you, you can try adding higher-res images for specific pixel densities on Android, you can [read a more about that here](https://docs.expo.io/guides/splash-screens/#customizing-the-configuration-for-ios-and-android).

Hope it helps!

**Comment by Irfanwani** [comment]
same here

**Comment by meilechwieder** [comment]
I have the same issue. Blurry in production, Clear in Dev.

Could it be it has to do with expo compressing all assets when packaging?
