### ISSUE TITLE
Unable to retrieve the FCM server key for the recipient's app. (expo-server-sdk)

### ISSUE THREAD

**Issue by esteban199** [expo/expo#8905]
## 🐛 Bug Report

Hello, Im using expo-server-sdk on my nodejs server to send notifications to my ejected expo app, so i follow expo-notifications instructions, i just upload my server api key succesfully by typing: `expo push:android:upload --api-key <your-token-here>` but getting following error: "Unable to retrieve the FCM server key for the recipient's app. Make sure you have provided a server key as directed by the Expo FCM documentation."

### Summary of Issue (just a few sentences)

```
[
  {
    id: 'deb0636b-2f71-4c2f-8424-244bd532b9b5',
    status: 'error',
    message: "Unable to retrieve the FCM server key for the recipient's app. Make sure you have provided a server key as directed by the Expo FCM documentation.",
    details: { error: 'InvalidCredentials', fault: 'developer' }
  }
]
```

### Reproducible Demo

this is my nodejs function to send push notification: 
```
const { Expo } = require('expo-server-sdk')

const sendNotifications = (somePushTokens, message) => {
    console.log("sendNotifications / somePushTokens: ", somePushTokens);
    return new Promise(async(resolve, reject) => {
        // Create a new Expo SDK client
        let expo = new Expo();
        // Create the messages that you want to send to clients
        let messages = [];
        for (let pushToken of somePushTokens) {
            // Each push token looks like ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]

            // Check that all your push tokens appear to be valid Expo push tokens
            if (!Expo.isExpoPushToken(pushToken)) {
                console.error(`Push token ${pushToken} is not a valid Expo push token`);
                continue;
            }

            // Construct a message (see https://docs.expo.io/versions/latest/guides/push-notifications)
            const messageHandled = {
                to: pushToken,
                sound: 'default',
                body: 'This is a test notification',
                data: { withSome: 'data' },
            }
            messages.push(messageHandled)
        }

        // The Expo push notification service accepts batches of notifications so
        // that you don't need to send 1000 requests to send 1000 notifications. We
        // recommend you batch your notifications to reduce the number of requests
        // and to compress them (notifications with similar content will get
        // compressed).
        let chunks = expo.chunkPushNotifications(messages);
        let tickets = [];
        (async () => {
            // Send the chunks to the Expo push notification service. There are
            // different strategies you could use. A simple one is to send one chunk at a
            // time, which nicely spreads the load out over time:
            for (let chunk of chunks) {
                try {
                    let ticketChunk = await expo.sendPushNotificationsAsync(chunk);
                    console.log(ticketChunk);
                    tickets.push(...ticketChunk);
                    // NOTE: If a ticket contains an error code in ticket.details.error, you
                    // must handle it appropriately. The error codes are listed in the Expo
                    // documentation:
                    // https://docs.expo.io/versions/latest/guides/push-notifications#response-format
                } catch (error) {
                    reject(error);
                    console.error(error);
                }
            }
        })();

        // Later, after the Expo push notification service has delivered the
        // notifications to Apple or Google (usually quickly, but allow the the service
        // up to 30 minutes when under load), a "receipt" for each notification is
        // created. The receipts will be available for at least a day; stale receipts
        // are deleted.
        //
        // The ID of each receipt is sent back in the response "ticket" for each
        // notification. In summary, sending a notification produces a ticket, which
        // contains a receipt ID you later use to get the receipt.
        //
        // The receipts may contain error codes to which you must respond. In
        // particular, Apple or Google may block apps that continue to send
        // notifications to devices that have blocked notifications or have uninstalled
        // your app. Expo does not control this policy and sends back the feedback from
        // Apple and Google so you can handle it appropriately.
        let receiptIds = [];
        for (let ticket of tickets) {
            // NOTE: Not all tickets have IDs; for example, tickets for notifications
            // that could not be enqueued will have error information and no receipt ID.
            if (ticket.id) {
                receiptIds.push(ticket.id);
            }
        }

        let receiptIdChunks = expo.chunkPushNotificationReceiptIds(receiptIds);
        (async () => {
            // Like sending notifications, there are different strategies you could use
            // to retrieve batches of receipts from the Expo service.
            for (let chunk of receiptIdChunks) {
                try {
                    let receipts = await expo.getPushNotificationReceiptsAsync(chunk);
                    console.log(receipts);

                    // The receipts specify whether Apple or Google successfully received the
                    // notification and information about an error, if one occurred.
                    for (let receiptId in receipts) {
                        let { status, message, details } = receipts[receiptId];
                        if (status === 'ok') {
                            continue;
                        } else if (status === 'error') {
                            console.error(
                                `There was an error sending a notification: ${message}`
                            );
                            if (details && details.error) {
                                // The error codes are listed in the Expo documentation:
                                // https://docs.expo.io/versions/latest/guides/push-notifications/#individual-errors
                                // You must handle the errors appropriately.
                                console.error(`The error code is ${details.error}`);
                            }
                        }
                    }
                    resolve()
                } catch (error) {
                    resolve()
                    console.error(error);
                }
            }
        })();
    })
}

module.exports = sendNotifications;
```

this is similar issue: https://forums.expo.io/t/failed-to-authenticate-with-the-fcm-server-ensure-the-fcm-server-key-you-uploaded-is-correct/25399

@cruzach please help!

- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve

As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

**Comment by AdamJNavarro** [comment]
Hey @esteban199,

I created a new project, set up FCM, fired up a local node server and sent a notification without issue. Can you go to your Google Console and make sure that the Cloud Messaging key wasn't revoked for some reason.

If that's not it, can you take me step by step on how you are able to reproduce this issue? It might also be worth creating a new project like I did and seeing if you get the same issue.

Cheers,
Adam

**Comment by esteban199** [comment]
I really appreciate it bro thank you @AdamJNavarro, but im still stuck here :(,  ok this were my steps: 1. create new firebase project, create android app and name it with my app.json/android/package name, copy google-services.json to my rn expo ejected project to root: myapp/android/app, get server key from cloud messaging tab in the settings pane, upload it with `expo push:android:upload --api-key myServerKey`, 2. on my app project just download expo-notifications, get my Permissions.NOTIFICATIONS granted, get my expo push token with getExpoPushTokenAsync save it to my db, and on my server side with expo-server-sdk i try to send notification with the function i commented, i alse try with `https://expo.io/notifications` but i get the same error... i try creating another firebase project but i get same results...

**Comment by AdamJNavarro** [comment]
Hey @esteban199, just wanted to follow up with a question here. Do you have teams enabled and the 'owners' field in `app.json` configured?

**Comment by superyarik** [comment]
facing same error:

application get expo push token, but when we are trying to send something with https://expo.io/notifications - get error

`InvalidCredentials: Unable to retrieve the FCM server key for the recipient's app. Make sure you have provided a server key as directed by the Expo FCM documentation.`

**Comment by AdamJNavarro** [comment]
Hey all,

We're going to close this due to inactivity. If you still encounter this issue and provide some additional information, we'll be happy to revisit it.

Cheers,
Adam

**Comment by cruzach** [comment]
@superyarik it's unlikely that key cleared itself, we haven't made any related server-side changes. Did you change your project slug at any point?

**Comment by superyarik** [comment]
@cruzach we have 2 projects in one git repository and switch app.json(renaming, not config param) for start it. can this create this problem?

also another question: how we can debug push notification? from time to time some users not receive push messeges, but they receive expo push token and after sending with expo service we receive OK in response, but push is not delever. Is there is any debug options? Thanks

**Comment by cruzach** [comment]
see the guide to debugging here- https://docs.expo.io/push-notifications/sending-notifications/. You need to check both the push **tickets**, and push **receipts**. Your FCM key is mapped to your username & project slug, so yes changing either of those could affect the FCM notification setup

**Comment by pikooli** [comment]
Hello , i still got this error , i do 
 `expo push:android:upload --api-key <your-token-here>`

But it change nothing , how can i hand this ? 
i try to do a new project : 
`expo install expo-notifications`

and configure it for android 

i did check the name package "com.notif" and the firebase android project name is "com.notif"
i did download the "google-services.json" and put it in "android/app/"
put "classpath 'com.google.gms:google-services:4.2.0'" in the "android/build.gradle" file 
did put the "apply plugin: 'com.google.gms.google-services'" in the file "android/app/build.gradle"
as asked here : [https://docs.expo.io/guides/setup-native-firebase/#bare-workflow-setup](https://docs.expo.io/guides/setup-native-firebase/#bare-workflow-setup)

it give me the ExponentPushToken[***] 

but when i try to send a notification with [https://expo.io/notifications](https://expo.io/notifications) or with fetch
`fetch('https://exp.host/--/api/v2/push/send', {       
        method: 'POST', 
        headers: {
              Accept: 'application/json',  
             'Content-Type': 'application/json', 
             'accept-encoding': 'gzip, deflate',   
             'host': 'exp.host'      
         }, 
       body: JSON.stringify({                 
             to: token["data"],                        
             title: 'New Notification',                  
             body: 'The notification worked!',             
             priority: "high",            
             sound:"default",              
             channelId:"default",   
                 }),        `

it do not work and give me the error "Unable to retrieve the FCM server key for the recipient's app. Make sure you have provided a server key as directed by the Expo FCM documentation."

i did push my firebase server key with  expo push:android:upload --api-key "key"

what should i do ?
 
i did try to follow this to [https://docs.expo.io/push-notifications/using-fcm/](https://docs.expo.io/push-notifications/using-fcm/)

but it fixe nothing :/ 

help :'(

**Comment by jcpaesf** [comment]
Same error here. 

I got the token but when I send with https://expo.io/notifications return the error: "InvalidCredentials: Unable to retrieve the FCM server key for the recipient's app. Make sure you have provided a server key as directed by the Expo FCM documentation."

**Comment by dobradovic** [comment]
same problem here

**Comment by MadaShindeInai** [comment]
Got the same problem. It`s happend when i build/publish new app. To solve this:
1) expo push:android:show    (it was unconfigured for me)
2) Run "expo push:android:upload --api-key <your-token-here>" , replacing <your-token-here> with the string you just copied. (how to get token - read https://docs.expo.io/push-notifications/using-fcm/#uploading-server-credentials )
I believe it will help somebody =)

**Comment by dobradovic** [comment]
> Got the same problem. It`s happened when i build/publish new app. To solve this:
> 
> 1. `expo push:android:show`    (it was unconfigured for me)
> 2. Run `expo push:android:upload --api-key <your-token-here>` , replacing  with the string you just copied. (how to get token - read https://docs.expo.io/push-notifications/using-fcm/#uploading-server-credentials )
>    I believe it will help somebody =)

IT'S WORKING!!! 

Thank you very much man, I appreciate it.

**Comment by dobradovic** [comment]
Thank you, I appreciate it very much. It is working! :)

**Comment by syamjayaraj** [comment]
> facing same error:
> 
> application get expo push token, but when we are trying to send something with https://expo.io/notifications - get error
> 
> `InvalidCredentials: Unable to retrieve the FCM server key for the recipient's app. Make sure you have provided a server key as directed by the Expo FCM documentation.`
> 
> UPDATE: strange, but there there is FCM server key in expo servers was cleared. Repushing key via
> `expo push:android:upload --api-key <your-token-here>`
> solve problem. But why this key can clear himself?

It worked for me.
