### ISSUE TITLE
Universal Links success call my app from iOS Notes, buf faild when press same link in safari

### ISSUE THREAD

**Issue by imwilliamxy** [expo/expo#8914]
Hi all,

I’m tring add Universal Link for my app.
I’ve made the settings according to the documentation. document url
But the app didn’t worked as I expect .

I create a link in iOS Notes app. My app was successfuly lunched from background when press the link,
But when i press the same link from Safari, an alert prompt dialog is showed, My app was lunched when I press ‘ok’ this time. According to the documentation, the prompt dialog should NOT display.

Now, I’m confused if the settings of Universal Linking is ok ro not? Or still some bug with expo-linking?

The following is my develop environment:
```Expo CLI 3.21.5 environment info:
System:
OS: macOS Mojave 10.14.6
Shell: 5.3 - /bin/zsh
Binaries:
Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
Yarn: 1.21.1 - /usr/local/bin/yarn
npm: 6.14.5 - ~/.nvm/versions/node/v12.18.0/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
Android Studio: 3.6 AI-192.7142.36.36.6241897
Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
npmPackages:
expo: ^37.0.0 => 37.0.12
react: 16.9.0 => 16.9.0
react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
react-navigation: ^4.0.10 => 4.3.9
npmGlobalPackages:
expo-cli: 3.21.5```

**Comment by byCedric** [comment]
Hi @imwilliamxy! Unfortunately, without a repro we can't really help you find the cause. Apps are complex and a lot of things might go wrong, without some code this would be a needle in a haystack for us. I don't think we have any known issues which are similar to yours ([currently we have these](https://github.com/expo/expo/issues?q=is%3Aopen+is%3Aissue+label%3ALinking)). Are you able to provide a repro?

**Comment by imwilliamxy** [comment]
Problem resloved.
Safari open universal link with a prompt box is because the safari is in 'private' mode.
When open safari with normal mode, every thing run as I expect
