### ISSUE TITLE
Cannot log out from WebBrowser.openAuthSessionAsync in oauth flow for iOS13

### ISSUE THREAD

**Issue by dubchoi** [expo/expo#8918]
### Summary of Issue (just a few sentences)

When using WebBrowser.openAuthSessionAsync to implement Oauth flow (Google), Google sign-in state is remembered even after signing out from Google and uninstalling/reinstalling app.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

iOS 13 simulator

### Steps to Reproduce

1. Configure app to use WebBrowser.openAuthSessionAsync to sign in and out via google oauth.
2. Sign in with Google account.
3. Confirm on Safari, you are also signed in on google.com
4. Sign out of app.
5. From Safari, go to google.com and sign out of Google.
6. (You can even uninstall / reinstall Expo app here)
7. Try signing into the app again.

### Expected Behavior vs Actual Behavior

Expected that at this point, you should be prompted to sign into google again. However, the webview opened with WebBrowser.openAuthSessionAsync still somehow seems to have Google sign in cookies, and so it will just let you through.

This is ONLY happening on iOS 13. I have confirmed it does re-prompt on iOS 12 and below.

**Comment by brentvatne** [comment]
you can use the `prompt` param to always show the account picker: https://stackoverflow.com/a/14393492/659988

**Comment by dubchoi** [comment]
I don't have access to the actual oauth2 url due to the library I'm using (amazon cognito).

But regardless, isn't this a security issue? My understanding is that openAuthSessionAsync will share cookies with safari, but how is it that even when user signs out completely from google on safari, it is letting through w/ google credentials inside the webview opened by openAuthSessionAsync?

**Comment by dubchoi** [comment]
I looked into this more, and it seems like the issue is more general.

Seems like openAuthSessionAsync and Safari are no longer sharing cookies at all, at least as of iOS 13.5. The above is just one symptom, but I also can't get SSO to work as a result (i.e. if I am already logged in on Safari, those cookies cannot be used inside Expo so I need to re login).

I can confirm this still works as documented on iOS 12

**Comment by brentvatne** [comment]
can you share a minimal reproducible example? this works as expected on my end

**Comment by dubchoi** [comment]
This is very odd.

The minimal thing I'm doing is just calling `WebBrowser.openAuthSessionAsync(
    "https://www.google.com", ...);` and then while on the google.com page, inspecting cookies with Safari > Develop. The cookies are an entirely different set from the ones from Safari.

Are you using iOS simulator 13.5? That's where this repros for me. I have not been able to repro anywhere else.

**Comment by dubchoi** [comment]
It seems like this is a 13.5 simulator-only issue. I've tested on a physical device and could not repro.
