### ISSUE TITLE
MapView is broken on web

### ISSUE THREAD

**Issue by sam-coxon** [expo/expo#8921]
### Summary of Issue (just a few sentences)
I've seen this issue brought up before, but have found no solutions. MapView doesn't work with Expo running on the web. You can see this just by trying the Snack linked in this documentation:

https://docs.expo.io/versions/latest/sdk/map-view/

The error seems to either be (Snack):
```
(0 , g.requireNativeComponent) is not a function
  Evaluating react-native-maps.js
  Evaluating App.js
  Loading App.js
```
Or (locally): 
`TypeError: Object(...) is not a function`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.3.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.14 => 0.12.14 
      expo: ^37.0.12 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.5

### Reproducible Demo
To Reproduce _On Expo Web_  

```
...
import { MapView } from 'react-native-maps';

<View style={styles.mapContainer}>
     <MapView
          style={{ marginTop: 20, width: "80%", height:400 }}
          initialRegion={{
            latitude: 37.78825,
            longitude: -122.4324,
          }}
     />
</View>
```

**Comment by sam-coxon** [comment]
@EvanBacon I saw the shim/fork you made of "react-native-maps" to address this issue, can i tap into that somewhere?

**Comment by brentvatne** [comment]
related pr: https://github.com/react-native-community/react-native-maps/pull/3457

**Comment by sam-coxon** [comment]
@brentvatne That seems like just the pr for me. However, it's been merged to master and still no luck. Should I be importing MapView from somewhere other than 'react-native-maps'?

Thanks for your quick response to this

**Comment by brentvatne** [comment]
react-native-maps folks haven't released it yet, you can use patch-package for it or create `MapView.web.js` and `MapView.js` files where web provides some fallback

**Comment by sam-coxon** [comment]
Ok i mis-spoke, the PR mentioned above works as crash-prevention, but doesn't actually support MapView on web.

I ended up using patch-package to utilize a PR that @EvanBacon built (https://github.com/expo/react-native-maps/pull/2) for web. I see that that has been merged into master for "react-native-maps" but seems to not work out-of-the-box with react-native-maps. Is there a future for the work of that PR? Seems a shame to have that work be done but unavailable.

Ya'll are heroes! Thanks for the work you're doing

**Comment by augustosamame** [comment]
@sam-coxon I just ran into this issue. Could you elaborate on your solution? "Using patch-package to utilize that PR" ? Does it actually work (at least basic features) after patching? Or is it still a crash prevention fix?

**Comment by sam-coxon** [comment]
So what i did is take the code of the PR, then overwrite the entire react-native-maps in my node_modules with Evan Bacon's PR. After that you can run [patch-package](https://www.npmjs.com/package/patch-package) to make your edited react-native-maps the new default library if you're collaborating with others.

Btw it would also work to just clone Evan's PR into your project as **EvanMapView** for example, and import MapView from the **EvanMapView** folder if you're looking for something faster/simpler.

The downside of this is Evan's PR seems to be a mostly-but-not-fully implemented MapView. Is there any information on when that might work ootb with react-native-maps?

**Comment by expjess** [comment]
Hi @sam-coxon - thanks for sharing your workaround 🙏 . Re: OOTB support, I'm not sure! -- I don't know what the maintainers have planned, and over here we're prioritizing a bunch of other things right now. A contributor pr into rn-maps could probably do the trick though ;) if you're up for that!

**Comment by EvanBacon** [comment]
Unfortunately I don't have time to work on this feature right now. It's a really large project with lot's of differences between web and native. 
The developer interface should probably change as well to be more universal and support any arbitrary map service (i.e. Leaflet, Mapbox, Apple maps, Google maps).

The best solution would be to create a new maps package, but that would take a ton of time to create and maintain. I would recommend using the _extremely_ unstable fork for now.

**Comment by vrinch** [comment]
the maker works on system browsers, however, when I try to use markers on mobile browsers, it keeps showing a blank screen without any error whatsoever
