### ISSUE TITLE
Facebook Native Ads - AdTriggerView doesn't work - Clicking on the component does nothing

### ISSUE THREAD

**Issue by girishjjain** [expo/expo#8923]
### Summary of Issue (just a few sentences)
Clickable area in a Facebook native ads needs to be marked explicitly using `AdTriggerView` component. When the native ad renders, clicking on the component in `AdTriggerView` tree is supposed to navigate but nothing happens with Expo SDK v37. In a [separate issue](https://github.com/expo/expo/issues/4087), user was navigated to a blank screen though.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 3.21.8 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.2.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.21.8

Targeting iOS platform 

### Reproducible Demo
```
import * as FacebookAds from 'expo-ads-facebook';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
const { AdIconView, AdOptionsView, AdTriggerView, AdMediaView } = FacebookAds;

class CustomFacebookBannerAd extends React.Component<
{
  nativeAd: {
    advertiserName?: string;
    sponsoredTranslation?: string;
    headline?: string;
    socialContext?: string;
    bodyText?: string;
    callToActionText?: string;
  };
}, any> {

  render() {
    const { nativeAd } = this.props;
    return (
      <View style={styles.fullad}>
        <AdOptionsView
          iconSize={16}
          iconColor="#00AECD"
          style={{
            backgroundColor: '#EFEFEF',
          }}
        />
        <View style={styles.nativeRow}>
          <AdIconView style={styles.iconView} />
          {/* Although its native banner Ad, AdMediaView still needs to be mounted for icon to work */}
          <AdMediaView />
          <View style={styles.nativeColumn}>
            {nativeAd.advertiserName && (
              <Text style={styles.title}>{nativeAd.advertiserName}</Text>
            )}
            {nativeAd.sponsoredTranslation && (
              <Text style={styles.sponsored}>{nativeAd.sponsoredTranslation}</Text>
            )}
          </View>
          <AdTriggerView>
            <View style={styles.adButton}>
              <Text style={styles.ctaText}>{nativeAd.callToActionText}</Text>
            </View>
          </AdTriggerView>
        </View>
      </View>
    );
  }
}

export default FacebookAds.withNativeAd(CustomFacebookBannerAd);


const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 16,
  },
  ctaText: {
    color: 'white',
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  header: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 24,
    marginBottom: 8,
  },
  p: {
    marginBottom: 10,
    marginHorizontal: 40,
    textAlign: 'center',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  fullad: {
    flexDirection: 'column',
    backgroundColor: '#EFEFEF',
  },
  nativeRow: {
    maxWidth: '100%',
    alignSelf: 'stretch',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  nativeColumn: {
    flex: 1,
    flexDirection: 'column',
  },
  icon: {
    width: 50,
    height: 50,
    borderRadius: 10,
    overflow: 'hidden',
    marginRight: 10,
    marginTop: 5,
  },
  adButton: {
    backgroundColor: '#0A84FF',
    padding: 15,
    color: 'white',
    justifyContent: 'center',
  },
  title: {
    fontWeight: 'bold',
    fontSize: 14,
  },
  sponsored: {
    fontSize: 11,
    opacity: 0.8,
  },
  subtitle: {
    fontSize: 13,
    fontStyle: 'italic',
  },
  button: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 3,
    backgroundColor: 'yellow',
    marginRight: 10,
  },
  buttonText: {
    color: '#fff',
  },
  iconView: {
    width: 50,
    height: 50,
    marginRight: 10,
  },
  mediaView: {
    flex: 1,
    height: 100,
  },
});
```

### Steps to Reproduce
Render the component provided above in an app and click on CTA button and you would notice that user is not redirected anywhere.

### Expected Behavior vs Actual Behavior
Clicking on the component rendered as part of `AdTriggerView` should navigate user to the CTA URL of ad but nothing happens, user is not redirected anywhere.

**Comment by girishjjain** [comment]
@sjchmiela - Would you be able to take a look at this issue and provide some guidance? This directly affects developers that use FB native banner ads and not being able to click on the ad means loss of revenue. Also, I see Expo SDK v38 is released so does this mean that we would have to wait until next release before this gets fixed or a package update can address this? Please let me know if I could help in any way. Thanks.

**Comment by bantingGamer** [comment]
any news on this issue? adverts has completely stopped working. 
```
"expo": "~38.0.8",
"expo-ads-facebook": "~8.3.0" 
```
When using the **FacebookAds.withNativeAd()** HOC the component does render at all.

i also tried just loading a banner advert but i get this error: Ad was re-loaded too frequently

**has there been any traction on this?**

**Comment by girishjjain** [comment]
Can someone from expo team confirm whether fixing this issue is on roadmap for next SDK (v39) release?

**Comment by cruzach** [comment]
@girishjjain I tested this using [this example screen](https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/FacebookAdsScreen.tsx) and the AdTriggerView does navigate me correctly. Maybe having that working example will help you to debug the code you're using now?

**Comment by girishjjain** [comment]
Thanks @cruzach for looking into this. I tried using the example screen that you referenced and was able to verify that it works. The key was rendering `AdMediaView` which made the CTA button work. Earlier, I had it in the tree but apparently it requires to be rendered too. I am not sure why that makes any difference for a banner ad 🤷‍♂️ 
```
        <View style={styles.nativeRow}>
          {/* Although its native banner Ad, AdMediaView still needs to be mounted for icon AND CTA button to work */}
          <AdMediaView style={styles.mediaView} />
        </View>
```

**Comment by cruzach** [comment]
Closing since this _seems_ to not be an issue with the native library, and is instead on the usage side. If you're having trouble implementing facebooks ads, check out the example screen I shared above
