### ISSUE TITLE
Task is said to be not defined despite already being defined even explicitly

### ISSUE THREAD

**Issue by stevensim226** [expo/expo#8925]
### Summary of Issue (just a few sentences)
As said in the title, the line
```
await BackgroundFetch.registerTaskAsync(taskName, options);
```
will always cause an exception saying that task is not defined despite already being defined explicitly even globally also.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.21.7 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.7
```

### Reproducible Demo
Code is exactly the same from this [https://medium.com/@whitestonedata/adding-timers-to-your-expo-managed-react-native-app-with-backgroundfetch-351dab97b96b](url)

### Steps to Reproduce
Just run the code in the end of the medium article I read and pasted above

### Expected Behavior vs Actual Behavior
I am expecting it to actually console.log the random number but instead it gives me the exception saying task is not defined.

**Comment by AdamJNavarro** [comment]
Hey @stevensim226,

Thanks for creating an issue. The link you provided is faulty but after googling the article, it's also written back in February. Could you please provide a more up-to-date repro case that we can use on our end to test and try to replicate the behavior you mention?

Cheers,
Adam

**Comment by stevensim226** [comment]
Hello @AdamJNavarro 
I am a beginner in this field and there isn't much resource on this topic , so I can't really provide a new one, but looking from the code in the article it seems the problem is only at one line as I stated before, is there an update or a new way to fix this maybe? I don't really see the code being from February to be a problem if there were to be a simple fix.

**Comment by stevensim226** [comment]
Hello, is there an update on this issue?, I have searched for snacks using BackgroundFetch and all of them are broken (is this feature deprecated?)

I have made a simple code to console.log("Hello") everytime the BackgroundFetch runs, but it seems it's still saying that the Task is not defined.
```
const TASK_NAME = "get one"

TaskManager.defineTask(TASK_NAME, () => {
    try {
      const receivedNewData = 10
      console.log("Hello")
      return receivedNewData ? BackgroundFetch.Result.NewData : BackgroundFetch.Result.NoData;
    } catch (error) {
      return BackgroundFetch.Result.Failed;
    }
  });


export default function TaskScreen() {
    useEffect(() => {
        BackgroundFetch.registerTaskAsync(TASK_NAME, {minimumInterval: 5, stopOnTerminate: false, startOnBoot: true})
    }, [])

    return (
        <View style={styles.screen}>
            <Button title="Click" onPress={() => {
                console.log("pressed")
                
            }}/>
        </View>
    )
}
```

**Comment by Manfrin92** [comment]
stevensim226 was you able to solve it?

**Comment by stevensim226** [comment]
> stevensim226 was you able to solve it?

No.

**Comment by qria** [comment]
I am having the same problem and looking at the source code I have a hunch that there are multiple TaskManager object in play yielding to this bug. Specifically, I believe `tasks` object when `TaskManager.defineTask` is called and `tasks` object from `TaskManager.isTaskDefined` inside `BackgroundFetch.registerTaskAsync` is different. This can be shown by doing following:

```
import * as BackgroundFetch from 'expo-background-fetch';
import * as TaskManager from 'expo-task-manager';
import React, {ReactElement} from 'react';
import {SafeAreaView} from 'react-native';

const BACKGROUND_TASK_NAME = 'bgTask';

TaskManager.defineTask(BACKGROUND_TASK_NAME, () => {
  console.log('it ran');  // never runs
  return BackgroundFetch.Result.NoData;
});
const App = (): ReactElement => {
  (async () => {
    console.log(TaskManager.isTaskDefined('bgTask')); // prints `true`
    // Go inside the definition of `BackgroundFetch.registerTaskAsync` and also add the above line
    await BackgroundFetch.registerTaskAsync(BACKGROUND_TASK_NAME);  // prints `false`
  })();
  return (
    <SafeAreaView></SafeAreaView>
  );
};
export default App;

```

I also believe this bug arose when expo repository split into expo, expo-task-manager, and expo-background-fetch.

**Comment by RAVITEJANETHALA** [comment]
> Hey @stevensim226,
> 
> Thanks for creating an issue. The link you provided is faulty but after googling the article, it's also written back in February. Could you please provide a more up-to-date repro case that we can use on our end to test and try to replicate the behavior you mention?
> 
> Cheers,
> Adam

**Comment by qria** [comment]
Bumping both expo-task-manager and expo-background fetch to 8.4.0+ solved the issue. My hunch is that by using unimodules, they now reference the same `tasks` object.

Now there might exists expo-task-manager and expo-background-fetch versions that do not use unimodules in which they might blow up, but my problem was solved.

**Comment by srikanthkh** [comment]
@qria Does background fetch work on iOS for you?

**Comment by qria** [comment]
@srikanthkh It's been a while since I've worked on the project using background fetch but I have successfully used the background fetch back then.

**Comment by srikanthkh** [comment]
@qria  Thanks for your reply. I am using a managed expo project and testing on an expo client, do you remember if you used a device as well for testing?

**Comment by qria** [comment]
@srikanthkh Yes, we tested on both real ios and andriod device
