### ISSUE TITLE
Get the location updates after each 1 minute?

### ISSUE THREAD

**Issue by usamamashkoor** [expo/expo#8929]
Hi, I want to create an app like Uber, and I want to get the location updates of the user after each 1 minute even if the app is running in the background is there a way to do this using your library?

I want the solution to work for both Android and Ios.

kindly let me know Thanks.

**Comment by AdamJNavarro** [comment]
Hey @usamamashkoor,

Thanks for your interest in Expo. You could leverage the `TaskManager` and `Location` modules to set up the behavior that you are seeking. I would recommend reading the [docs](https://docs.expo.io/versions/v37.0.0/sdk/location/#configuration) to see how to set it up and what is all possible with the modules.

For future reference, it would be greatly appreciated if you could direct questions like these to our [forums](forums.expo.io). We intend to reserve Github issues for reproducible and actionable bug reports.

Cheers,
Adam
