### ISSUE TITLE
Video seek is inaccurate on iOS

### ISSUE THREAD

**Issue by cuimenc** [expo/expo#893]
To seek with setStatusAsync({positionMillis:NN}) can result in near 1s mismatch in my testing.
This probably is due to AVPlayer usage, as shown from this SO [question](https://stackoverflow.com/questions/11462843/avplayer-seektotime-does-not-play-at-correct-position)

Can you expose the toleranceBefore/toleranceAfter parameters of the seekToTime: toleranceBefore:toleranceAfter API?

That can make precise seek possible from JS code

**Comment by ide** [comment]
Thanks for this report and the diagnosis =D. Just want to acknowledge this issue.
