### ISSUE TITLE
Expo client crash(won't open) in XCode 9.1(latest) iOS simulator.

### ISSUE THREAD

**Issue by nuwanprabhath** [expo/expo#894]
Steps:
1. Create a new project in XDE using blank app template.
2. Go to Device -> Open on iOS Simulator
3.  Expo app gets downloaded and installed in the simulator with the following output in XDE.
`2:35:11 PM Downloading latest version of Expo
2:35:14 PM Installing Expo on iOS simulator`
4. After that nothing happens. 
5. Click on expo app icon in the simulator.
6. App opens with a black screen and after a while close and navigates to home.

Note: Same project open and work with an actual iOS device with iOS 11.1

Simulator info: Version 10.0 (SimulatorApp-835.2.1 CoreSimulator-494.22.7)
Simulator device and OS: iPhone 7 plus(both iOS 10.3 and iOS 11.1)
Xcode info: Version 9.1 (9B55)
xcode-select --print-path: /Applications/Xcode.app/Contents/Developer
npm exp -v: 3.10.10
Expo XDE Version: 2.21.0 (2.21.0)

**Comment by ide** [comment]
Thanks for the report. Xcode 9.1 just came out and we haven't tested it yet so in the meantime I'd recommend using an actual device (as you've been doing).

**Comment by terribleben** [comment]
Hey there, I've seen no issues with this on Xcode 9.0, 9.1 or 9.2 so I'm going to close. Let me know if it's still happening for you.

**Comment by 2hands10fingers** [comment]
@terribleben My "Installing Expo client on iOS simulator...." hangs. I'm using the latest version of Expo ("expo-cli": "^2.18.7") and Xcode. It has been hanging for 30 minutes now.

**Comment by josermorales** [comment]
same thing is happening to me on Mojave with the latest version of expo, ios 13 sim. Expo client is installed on ios but keeps stuck on "installing client"
<img width="378" alt="Screen Shot 2019-09-21 at 12 14 29 PM" src="https://user-images.githubusercontent.com/13815017/65376104-19dbf380-dc6a-11e9-8644-317eb5917e1a.png">
<img width="386" alt="Screen Shot 2019-09-21 at 12 19 25 PM" src="https://user-images.githubusercontent.com/13815017/65376105-19dbf380-dc6a-11e9-9a17-96425ed90b87.png">
