### ISSUE TITLE
Its not redirecting to mobile app after Google login, instead it goes to google.com

### ISSUE THREAD

**Issue by harmispatel** [expo/expo#8944]
### Summary of Issue (just a few sentences)

here is my code :-

try {
const result = await Google.logInAsync({
androidStandaloneAppClientId:"xxxx",
scopes: ['profile', 'email'],
redirectUrl: `${AppAuth.OAuthRedirect}:/oauthredirect/google`
});
console.log(result);
} catch(e) {
console.log({e});
}
### Environment - output of `expo diagnostics` & the platform(s) you're targeting
it's goes to google page insted of app

### Reproducible Demo

- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve

As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

**Comment by AdamJNavarro** [comment]
Hey @harmispatel, I'm going to close this issue. If you can follow the bug template and provide all the necessary information, we can re-open the issues and continue discussions.

**Comment by tslater** [comment]
I'm having this issue on 39.
