### ISSUE TITLE
expo-firebase-analytics.setAnalyticsEnabled is still throwing an error

### ISSUE THREAD

**Issue by superKalo** [expo/expo#8946]
### Summary of Issue

Calling `await Analytics.setAnalyticsCollectionEnabled(false)` (imported from 'expo-firebase-analytics' v2.1.1) results the following error thrown:

_Error: The method or property expo-firebase-analytics.setAnalyticsEnabled is not available on ios, are you sure you've linked all the native dependencies properly?_

### Environment

iOS and Android

```
  Expo CLI 3.13.8 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v13.12.0/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: 37.0.12 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-navigation: 4.3.7 => 4.3.7
    npmGlobalPackages:
      expo-cli: 3.13.8
```

### Reproducible Demo

I made all configuration instructions described in the [Managed Workflow Setup](https://docs.expo.io/guides/setup-native-firebase/?redirected#managed-workflow-setup).

I saw this issue https://github.com/expo/expo/issues/8264 , it ways its fixed. I'm on the latest version of everything (Expo SDK v37.0.1, expo v37.0.12, expo-firebase-analytics v2.1.1) and the error is still present on my side :(

### Steps to Reproduce

Just call `await Analytics.setAnalyticsCollectionEnabled(false)` (imported from 'expo-firebase-analytics' v2.1.1).

### Expected Behavior

To set analytics collection to `false`.

**Comment by barthap** [comment]
This was fixed in that commit from issue you mentioned. You could still encounter that, because fixes aren't always published immediately. Anyway, it's fixed in SDK 38, feel free to update.
