### ISSUE TITLE
expo-facebook login with firebase

### ISSUE THREAD

**Issue by hatim85f** [expo/expo#8951]
Hello all 

I am running into this error for a couple of days while I am trying to find some solution for it

I am applying a **#Facebook** authentication to my #Expo app . #Android everything is working as expected while is #ios **ONLY** getting this error

> [Error: Unsuccessful debug_token response from Facebook: {"error":{"message":"(#100) The App_id in the input_token did not match the Viewing App","type":"OAuthException","code":100,"fbtrace_id":"AatQy0aKnSRI8b_pOTa4txS"}}]

While I am searching everybody is pointing that means the **AppID** or **AppSecret** provided to firebase is wrong but I am 100% sure it's right as it's working well with android and the user is being authenticated and added to users so my expectations there is something wrong with **#ios** config

**Notes**

App is directing to FB successfully and return token through ios

Again I am 100% sure of my AppID and AppSecret is correct as I copied paste them

### Expo CLI 3.21.9 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.3.9 => 4.3.9
enter image description here

I will be very grateful if someone is willing to help me with this

Thanks in advance

@expo @react-native @firebase @facebook @ios

**Comment by EvanBacon** [comment]
IIRC the Facebook ID cannot be changed in the Expo client. If you create a custom client with `expo client:ios` it'll use the Facebook App ID you defined in the `app.json`. If you want to do auth in the app store expo client you can use expo-auth-session with the `useProxy` option enabled. https://docs.expo.io/guides/authentication/#facebook

**Comment by hatim85f** [comment]
thank you @EvanBacon  for your response. Actually the situation is totally different. I am still facing this issue with development mode with a very strange behaviour . The error now is coming on/off. i.e for couple of hours it's not appearing then suddenly it appears without any change in the code 
I am still having a strong believe it's something related to @firebase (#firebase) itself not to #Facebook as still it's returning a user authentication token normally but it's crashing in #firebase side. 
Add to this in the time it's not showing the error it's never save data to firebaes with #ios ONLY wile working perfectly with android 

project build using 

> **expo-cli init <projectName>**

for more information here is the last updated app.json
 _Kindly note that after that last update it was running normally but without sending data to firebase server for a couple of hours then I got it back_  

> {
  "expo": {
    "name": "LoginFlow",

    "slug": "LoginFlow",

    "privacy" : "public",

    "platforms": [

      "ios",

      "android",

      "web"

    ],

    "version": "1.0.0",

    "orientation": "portrait",

    "icon": "./assets/icon.png",

    "splash": {

      "image": "./assets/splash.png",

      "resizeMode": "contain",

      "backgroundColor": "#ffffff"

    },

    "updates": {

      "fallbackToCacheTimeout": 0

    },

    "assetBundlePatterns": [

      "**/*"

    ],

    "ios": {

      "supportsTablet": true,

      "bundleIdentifier" : "host.exp.Exponent", // the same issue with app BI also

      "infoPlist" : {

        "CFBundleURLTypes" : {

          "CFBundleURLSchemes" : [

            "fbxxxxxxxx"

          ]

        },

      "facebookAppId " : "xxxxxxxx",

      "FacebookDisplayName" : "LoginFlow",

      "LSApplicationQueriesSchemes" : [

         "fbapi", "fbapi20130214","fbapi20130410", "fbapi20130702", "fbapi20131010",
         "fbapi20131219", "fbapi20140410", "fbapi20140116", "fbapi20150313", "fbapi20150629",
         "fbapi20160328" , "fbauth", "fb-messenger-share-api" , "fbauth2" , "fbshareextension"
       ]

      }

    }

  }

}

**Comment by cruzach** [comment]
Hey @hatim85f, even though the FB SDK is responding with the user token, it's using Expo's Facebook appID, not the one you're providing. We state in the docs that all of your Facebook API calls will be made with Expo's Facebook App ID. The slight downside to this is that you can't customize which permissions your app requests from Facebook (like user_photos or user_friends), or integrate Facebook login with other services like Firebase auth. If you need that functionality, you have two options:
- [Build a standalone app](https://docs.expo.io/distribution/building-standalone-apps/)
- [Build a custom Expo Client app](https://docs.expo.io/guides/adhoc-builds/)

I would try one of those and see if that resolve your issue

**Comment by hatim85f** [comment]
dear @cruzach  let me tell you that I did a trial in a standalone app and following docs mentioned below 
[https://docs.expo.io/versions/latest/sdk/facebook/](url)
and unfortunately FBSDK not even responding with user token 
Any advice ?

**Comment by abelptvts** [comment]
Hey there! 

Unfortunately I'm getting the same error in the **Expo client** on **Android** using expo version **39**. I'm absolutely sure facebook auth is set up correctly in firebase, the same facebook app id is used in app.json, Facebook.initializeAsync and firebase console. I'd really appreciate your help. 

Let me know if I should create a new issue.

**Comment by cruzach** [comment]
The android Expo client uses the facebook credentials you provide, so I would double-check that your providing the correct values

**Comment by abelptvts** [comment]
Yep, I screwed it up, I was using a wrong Firebase instance. Sorry for the bother. Thanks for the quick answer!
