### ISSUE TITLE
yarn expo-splash-screen error

### ISSUE THREAD

**Issue by Syahrul** [expo/expo#8958]
## 🐛 Bug Report
Android: wrong value inserted into MainActivity.java when using 
`yarn expo-splash-screen [options] <backgroundColor> [imagePathOrDarkModeBackgroundColor] [imagePath] [darkModeImagePath]`

### Summary of Issue
In the [Android Manual Configuration](https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-android) steps, the code is `SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class);` but using CLI, the value inserted was `SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, false);` causing build to failed.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.9 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.9

### Reproducible Demo
`yarn expo-splash-screen -r "cover" "#ffffff" "./imagepath"`

**Comment by renatobcj** [comment]
Same here

**Comment by fr34q** [comment]
I had the same issue today after ejected an Expo managed project and changing the splash screen. Manually fixing works but it took me some time to figure out what to put there (it is actually written correctly in the manual installation guide in the README). It seems that the expo-splash-screen script is just outdated maybe?

**Comment by bbarthec** [comment]
This problem is fixed in the most recent `expo-splash-screen`. I'm tentatively closing this issues, but feel free to reopen if something is not working as expected regarding this matter.

**Comment by hogrid** [comment]
Same issue
