### ISSUE TITLE
Logging refs does not work in 22.0.0 and 21.0.0 in development mode only in debug mode

### ISSUE THREAD

**Issue by itsmeek** [expo/expo#896]
In the following screenshot, in 22.0.0, console logging the ref causes the app to crash but works fine when in debug mode. In 21.0.0, the app does not crash but nothing shows up in expos console
![screen shot 2017-11-01 at 11 30 38 am](https://user-images.githubusercontent.com/13013336/32290805-6b562a8c-bef8-11e7-8a2f-9ae719ff43b5.png)

**Comment by ide** [comment]
Can you please clarify what it is about refs that aren't working? Is it just logging them?

**Comment by itsmeek** [comment]
Just the logs. I changed the title to clarify the issue

**Comment by ngtan** [comment]
The same issue in 25.0.0

**Comment by ngtan** [comment]
Steps to reproduce:
Create an application follows steps from the below repo:
https://github.com/react-community/create-react-native-app

`
<View style={styles.container} ref={console.log}>
// another code here
</View>
`

Try to run on device.

**Comment by ngtan** [comment]
I did a simple demo here
https://github.com/ngtan/hello-ref

Help it's useful and fixed soon. :)

**Comment by sjchmiela** [comment]
Hey guys! The app is crashing and the logs aren't showing for a simple reason — an argument to `ref` method is a very deep and big cycle object and Expo 25 can't handle those properly. We've fixed this issue on `master` and the fix will go out in SDK 32. Thank you for your patience. 🙂 

Similar issue: https://github.com/expo/expo/issues/478
