### ISSUE TITLE
[Contacts] Contacts.addContactAsync returns wrong contacts id on android

### ISSUE THREAD

**Issue by dor6** [expo/expo#8961]
### Summary of Issue (just a few sentences)
Contacts.addContactAsync supposed to return the id of the newly created contact, on android it returns a random contact id.
seems to be the id of the last contact in your contact list when you open the contacts app, which means its the last contact in an alphabetic order.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
I found this bug on android standalone

### Reproducible Demo
Just use Contacts.addContactAsync on android standalone hard to give a demo because you can't save a contact on android in expo environment.

### Steps to Reproduce
1, save a contact using Contacts.addContactAsync on android stand alone (better if the contacts first name and last name start with a because as I said, I believe the returned id is of the last contact in alphabetical order).
2, use Contacts.getContactByIdAsync with the id given in step 1.
3. log the result of step 2 or show it on the screen using a Text component.
4. you will see a random contact from your contacts and not the contact you created ( you can tell by the name or other parameters).

### Expected Behavior vs Actual Behavior
Expected Behavior:
Contacts.addContactAsync returns the newly created contacts id.
Actual Behavior:
Contacts.addContactAsync returns arandom contacts id, probably the last contact alphabeticaly.

**Comment by chmorik** [comment]
Can you please reopen?
seems that addContactAsync return the "before last" id

**Comment by lukmccall** [comment]
@chmorik, do you mean that #8090 won't fix it?

Just for the record. Changes made by #8980 wasn't published yet. So, this bug still occurs.

**Comment by chmorik** [comment]
@lukmccall I'm using Ubuntu
Do you know when #8980 will be published?

**Comment by lukmccall** [comment]
@chmorik,
For managed workflow, it will be published in the next `SDK` (`40`). So, it will be in September. For the bare workflow, we might release it earlier.
