### ISSUE TITLE
expo 35 the release version that overwrites another

### ISSUE THREAD

**Issue by kbourchbane** [expo/expo#8962]
Hi,
I had a problem that I did not understand well, I have an ios and android app in prod I just updated my app and after I built an ipa and apk then I sent them to appstore in testflight and google play, the problem is that
### for ios:
`testflight`: I have version 4.0.0
`in prod`: I have version 3.9.9 but with the content of 4.0.0 version

### for android:
`in prod`: I have version 3.9.9 but with the content of 4.0.0 version

is there a logical explanation to this please.

thanx

**Comment by byCedric** [comment]
Hi @kbourchbane! Are you using OTA and build both `3.9.9` and `4.0.0` on the same release channel? If you did, that might explain why the production apps were updated. You can [read more about OTA](https://docs.expo.io/guides/configuring-ota-updates/) and [when new versions are pushed here](https://docs.expo.io/workflow/publishing/#what-version-of-the-app-will-my), and [here for more info on release channels](https://docs.expo.io/distribution/release-channels/). If you have more questions, please try the [forums](https://forums.expo.io/) or [community slack](https://slack.expo.io/) first. We use GitHub for issues and bug reports only.

Hope it helps.
