### ISSUE TITLE
Build iOS project inside Docker

### ISSUE THREAD

**Issue by iShawnWang** [expo/expo#897]
I just notice that there is a `Dockerfile` inside `ios` directory, and I have tried to build a docker image and run xcodebuild inside docker to build ipa for CI, but docker doesn't support osx image !
Is that possible ? I think docker will never support osx image, right ?
And how you guys build iOS App or ipa parallel ?

# :D

**Comment by ide** [comment]
We provision Macs with Mac Stadium and vSphere, not with Docker. Basically we use Mac VMs -- if you want to automate builds I'd recommend either buying some Macs or renting some VMs.

**Comment by iShawnWang** [comment]
I look into it, thanks ~
