### ISSUE TITLE
ExpoInAppPurchases: No virtual method setOldSku

### ISSUE THREAD

**Issue by barnu5** [expo/expo#8972]
### Summary of Issue (just a few sentences)
In app purchases work on iOS but not Android

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Android dev on Windows

`"expo-in-app-purchases": "~8.2.1",`

  Expo CLI 3.21.12 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^38.0.0 => 38.0.3
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

### Reproducible Demo
Successfully queried the products from the store. When I run `await purchaseItemAsync(item);`, I get error:

```
[17:28:00] W | ReactNativeJS ▶︎ 2, [Error: Encountered an exception while calling native method: Exception occurred while executing exported method purchaseItemAsync on module ExpoInAppPurchases: No virtual method setOldSku(Ljava/lang/String;)Lcom/android/billingclient/api/BillingFlowParams$Builder; in class Lcom/android/billingclient/api/BillingFlowParams$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingFlowParams$Builder' appears in /data/app/com.APPNAME.APPNAME
```

Note all appears fine on iOS

**Comment by AdamJNavarro** [comment]
Hey @barnu5,

Sorry for letting this fall through the cracks. Hoping to get an update on the current status of the issue. Are you still encountering the `setOldSku` error? If so, is there any additional information you found that might be helpful in debugging this?

Cheers,
Adam

**Comment by whusterj** [comment]
I am also seeing this issue today. 

### Error Summary

Same problem as reported. IAP works on IOS, but not on Android. Same `setOldSku` error message as reported...

`Exception occurred while executing exported method purchaseItemAsync on module ExpoInAppPurchases: No virtual method setOldSku`

### Expo Diagnostic

 Expo CLI 3.23.2 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.3.9 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.23.2

### Reproducible Demo

I am happy to create one, but I am not sure how. My understanding is that to fully test IAP on Android, you must have a "published" app that has passed review. Any advice?

**Comment by whusterj** [comment]
I was able to resolve the problem: app/build.gradle in expo-in-app-purchases/build.gradle specified different versions of the `com.android.billingclient:billing` library. Expo IAP uses version 2.0.0 and our app/build.gradle implemented 3.0.0. When I changed this to 2.0.0 I was able to make a test purchase.

According to our Git history, this may have happened after running `expo eject`. I will see if I can reproduce that. If not, this was a configuration error on our part, and perhaps this report will help someone else.

**Comment by floelm** [comment]
I ran into the same issue and for me it was that I had react-native-iap installed at the same time (uses billing api 3.0.0 in the latest release). I removed it and its dependencies and this package worked fine again.

**Comment by xhsynx** [comment]
Me also getting the same error any updates? :(

**Comment by barnu5** [comment]
My issue was as per above

**Comment by havanhuy1997** [comment]
> I ran into the same issue and for me it was that I had react-native-iap installed at the same time (uses billing api 3.0.0 in the latest release). I removed it and its dependencies and this package worked fine again.

I had same problem, removed react-native-iap and it is working well

**Comment by danielwaite6** [comment]
removed react-native-iap and I had same problem

**Comment by danielwaite6** [comment]
any solution ?
