### ISSUE TITLE
[SDK 38] Excessive number of pending callbacks: 501

### ISSUE THREAD

**Issue by Razorholt** [expo/expo#8987]
Now that I upgraded to SDK 38 I keep on getting the following error:

`Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"2594":{"module":"UIManager","method":"configureNextLayoutAnimation"},"2595":{"module":"UIManager","method":"configureNextLayoutAnimation"},"2668":{"module":"UIManager","method":"configureNextLayoutAnimation"},"2670":{"module":"UIManager","method":"configureNextLayoutAnimation"},"3005":{"module":"UIManager","method":"configureNextLayoutAnimation"},"3107":{"module":"UIManager","method":"configureNextLayoutAnimation"},"3427":{"module":"UIManager","method":"configureNextLayoutAnimation"},"3428":{"module":"UIManager","method":"configureNextLayoutAnimation"},"3429":{"module":"UIManager","method":"configureNextLayoutAnimation"}, ... It goes on and on...`

Nowhere in my codes am I using the "configureNextLayoutAnimation" method. However, I do have a Promise in App.js - I read somewhere that it could be related. Here are the lines:

```
useEffect(() => {
    const LoadResourcesAsync = async () => {
      try {
        await Promise.all([
          Asset.loadAsync([
            require("./assets/images/group.png"),
            require("./assets/images/Rolling.png"),
            require("./assets/images/pause.png"),
          ]),
          Font.loadAsync({
            "sf-compact-bold": require("./assets/fonts/SF-Compact-Display-Bold.otf"),
            "sf-black": require("./assets/fonts/SF-UI-Display-Black.otf"),
          }),
        ]);
        setLoaded(true);
      } catch (error) {
        console.error(error);
        setLoaded(false);
      }
    };
    LoadResourcesAsync();
  }, []);
```

Any recommendations? Thank you!

**Comment by brentvatne** [comment]
can you please share a minimal reproducible example example that we can clone and run?

**Comment by Razorholt** [comment]
Thanks @brentvatne for your reply. As I was about to put something together for you to test I found a lonely "LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);" hanging in the middle of nowhere... 

And thank you for the new SDK release! Much faster at loading content, especially images.
