### ISSUE TITLE
[SDK 38] Android Release crash at startup

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#8988]
### Summary of Issue
When you create a new project, eject and compile a release APK. It crash in the splash screen.

### Environment
```
  Expo CLI 3.21.12 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.3
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.12
```

### Steps to Reproduce
1. `expo init expo-sdk38`
2. choose "blank  -  a minimal app as clean as an empty canvas" 
2. `cd expo-sdk38`
3. `expo eject`
4. Would you like to proceed? **Y**
5. What would you like your bundle identifier to be? **com.expo.test**
6. What would you like your package to be named? **com.expo.test**
7. `npm start`
8. Open Android Studio
9. Open an existing Android Studio project
10. Navigate to project and select "android" folder
11. Build -> Generate Signed Bundle / APK...
12. Select APK -> Next
13. Create or select an existing keystore -> Next
14. Choose **release**
15. Check **V1 (Jar Signature)** and **V2 (Full APK Signature)**
16. Install the generated APK in your device
17. Open and crash.

![image](https://user-images.githubusercontent.com/870365/85913158-e2e9ce00-b7f7-11ea-8dfd-562524da4926.png)

### Expected Behavior vs Actual Behavior

Expected Behavior: Doesn't crash when open the app.
Actual Behavior: Crash in the splash screen.

**Comment by brentvatne** [comment]
hi there! can you share the resulting AndroidManifest.xml?

**Comment by Razorholt** [comment]
Try installing node 12 instead of 14

**Comment by RodolfoGS** [comment]
> hi there! can you share the resulting AndroidManifest.xml?

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.expo.test">
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.MANAGE_DOCUMENTS"/>
  <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
  <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.READ_CONTACTS"/>
  <uses-permission android:name="android.permission.READ_CALENDAR"/>
  <uses-permission android:name="android.permission.WRITE_CALENDAR"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.RECORD_AUDIO"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
  <uses-permission android:name="android.permission.WAKE_LOCK"/>
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">
    <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://exp.host/@rodolfogs/expo-sdk38"/>
    <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="38.0.0"/>
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="true"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"/>
  </application>
</manifest>
```

**Comment by stochris** [comment]
new project created

has the following issue in logcat

```
java.lang.RuntimeException: Unable to create application com.stochris.yogatapastimer.MainApplication: java.lang.IllegalStateException: UpdatesController.getInstance() was called before the module was initialized
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6665)
        at android.app.ActivityThread.access$1700(ActivityThread.java:231)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1965)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7695)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalStateException: UpdatesController.getInstance() was called before the module was initialized
        at expo.modules.updates.UpdatesController.getInstance(UpdatesController.java:82)
        at com.stochris.yogatapastimer.MainApplication$1.getJSBundleFile(MainApplication.java:59)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:81)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at com.stochris.yogatapastimer.MainApplication.onCreate(MainApplication.java:82)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6660)
        at android.app.ActivityThread.access$1700(ActivityThread.java:231) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1965) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7695) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
```

**Comment by stochris** [comment]
Temporarily solved by adding `UpdatesController.initialize(this.getApplication().getApplicationContext());` in `MainApplication.java` wherever `getInstance()` was called

![image](https://user-images.githubusercontent.com/9612572/85926815-a88d3900-b8aa-11ea-85c0-54ddab488b06.png)

**Comment by esamelson** [comment]
Hey all -- thanks for the heads up, and sorry for the trouble! The correct fix here is to initialize expo-updates before Flipper in `onCreate` rather than the other way around. So your `onCreate` method (inside of MainApplication.java) should look like this:

```
  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);

    if (!BuildConfig.DEBUG) {
      UpdatesController.initialize(this);
    }

    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }
```

This has been fixed for new projects created by `expo init` or `expo eject` starting now. If you already created or ejected your project, just update your `MainApplication.onCreate` method to look like the above.

**Comment by RodolfoGS** [comment]
Thanks @esamelson, that works perfect!

**Comment by CharlyPoppins** [comment]
I also needed to change 
`/**
   * Loads Flipper in React Native templates.
   *
   * @param context
   */
  private static void initializeFlipper(Context context) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         * We use reflection here to pick up the class that initializes Flipper, since
         * Flipper library is not available in release mode
         */
        Class<?> aClass = Class.forName("com.facebook.flipper.ReactNativeFlipper");
        aClass.getMethod("initializeFlipper", Context.class).invoke(null, context);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }`
to
`/**
   * Loads Flipper in React Native templates. Call this in the onCreate method
   * with something like initializeFlipper(this,
   * getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         * We use reflection here to pick up the class that initializes Flipper, since
         * Flipper library is not available in release mode
         */
        Class<?> aClass = Class.forName("com.rndiffapp.ReactNativeFlipper");
        aClass.getMethod("initializeFlipper", Context.class, ReactInstanceManager.class).invoke(null, context,
            reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }`
