### ISSUE TITLE
Any way to schedule notifications in background with expo ? 

### ISSUE THREAD

**Issue by hatim85f** [expo/expo#8989]
I have this question which may look easy or discussed before but please bare with me as I am still totally new to EXPO

I have built my app and applied a push notifications which is working perfectly but one of the needs of my app to schedule notifications in some specific times for the user 

I was trying to find a way around but I couldn't which affecting a lot my app users who are finally going to uninstall my app either from Google play or App Store 

My question is is there is anything can be done so local notification could pop up for the user in specific times ? 

Thanks in advance

**Comment by byCedric** [comment]
Hi @hatim85f, please ask the questions in either the [forums](https://forums.expo.io/) or [community slack](https://slack.expo.io/). We use github issues for bugs only.

One way to do this is to [check if the notifications are scheduled](https://docs.expo.io/versions/latest/sdk/notifications/#getallschedulednotificationsasync-promisenotification) as expected when the app loads, starts, or when the user signs in. If the notifications aren't scheduled, [you can schedule them](https://docs.expo.io/versions/latest/sdk/notifications/#schedulenotificationasyncnotificationrequest-notificationrequestinput-promisestring) after the user granted the notifications permission. Using this approach, it doesn't matter if the user uninstall and reinstalls the app again. 😄 

Hope it helps!

**Comment by hatim85f** [comment]
Thanks a lot @byCedric  😃
