### ISSUE TITLE
"Something went wrong" when implementing GitHub login with AuthSession

### ISSUE THREAD

**Issue by Rafaell416** [expo/expo#899]
Hello
Im trying to implement a github authentication using Authsession. I already added the callback url to github settings because is required. https://auth.expo.io/@rafaell416/github-gql-app 
and after i login in to github this error appears.

![whatsapp image 2017-11-01 at 6 00 02 pm](https://user-images.githubusercontent.com/18080929/32302636-b0d0c57a-bf31-11e7-92dd-157be8d5471c.jpeg)

**Comment by brentvatne** [comment]
it works https://github.com/brentvatne/oauth-examples

not sure what caused this without source of a demo app that can repro, closing

**Comment by ide** [comment]
We think this might be due to a missing returnUrl. Did you forget to specify it?

**Comment by EvanBacon** [comment]
Here is an official guide for doing Github auth with the new Expo AuthSession API https://docs.expo.io/guides/authentication/#github if you continue to run into problems, please open a new issue.
