### ISSUE TITLE
[expo-notifications] Android push notifications doesn't respect channel's id

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#8990]
### Summary of Issue (just a few sentences)
When you send a push notification, it doesn't appear in the expected channel. Always goes to **Miscellaneous** channel.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.21.12 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.3
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.12
```

### Steps to Reproduce

1. Create a new project (`expo init`)
2. Setup FCM (https://docs.expo.io/guides/using-fcm/#uploading-server-credentials)
3. Update App.js to create a channel and get Expo token.
```
// create channel
Notifications.setNotificationChannelAsync('test-channel', {
  name: 'test-channel',
  importance: Notifications.AndroidImportance.MAX,
  vibrationPattern: [0, 250, 250, 250],
  lightColor: '#FF231F7C',
});

// get expo token
const { data: token } = await Notifications.getExpoPushTokenAsync();
```
4. Send a notification from the Expo push notifications console: https://expo.io/notifications
5. Add your Expo token, title body and set Channel ID to `test-channel`
6. Send a push notification.
7. Long press in the notification
8. Tap on "ALL CATEGORIES"
9. And the category **Miscellaneous** will make two blinks, saying that the notification is in that category.

### Expected Behavior vs Actual Behavior

Expected Behavior: The notification is added in the `test-channel`
Actual Behavior: A **Miscellaneous** channel is created and the notification is added to this channel.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/870365/85928528-35b49b80-b873-11ea-8255-9b1f43ecad33.gif)

---
This is the channel that is created automatically and where the all notifications are added.
```
{
  "enableVibrate": true,
  "lockscreenVisibility": 0,
  "groupId": null,
  "sound": "default",
  "id": "expo_notifications_fallback_notification_channel",
  "lightColor": "#00000000",
  "audioAttributes": {
    "usage": 5,
    "flags": {
      "enforceAudibility": false,
      "requestHardwareAudioVideoSynchronization": false
    },
    "contentType": 4
  },
  "bypassDnd": false,
  "enableLights": false,
  "importance": 6,
  "vibrationPattern": null,
  "name": "Miscellaneous",
  "description": null,
  "showBadge": true
}
```

**Comment by JPSantistebanQ** [comment]
I don't receipt notifications with the new api.

**Comment by RodolfoGS** [comment]
Hi @JPSantistebanQ, I think that you may have the problem that I mentioned in this another issue: https://github.com/expo/expo/issues/9037#issuecomment-652515492
