### ISSUE TITLE
Unrecognized event after upgrade to Expo SDK 38.0.0 from ~37.0.3

### ISSUE THREAD

**Issue by mobeendev** [expo/expo#8994]
### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.12.0 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.3 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^3.11.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.20.3

### Steps to Reproduce
- run expo upgrade on ~37.0.3.

### Expected Behavior vs Actual Behavior
after the upgrade and running the expo start, I am seeing this error message in console:
however there's not yellow message on mobile app.

Unrecognized event: {"type":"client_log","level":"log","data":["Running \"main\" with {\"initialProps\":{\"exp\":{\"lastErrors\":[{\"isFatal\":true,\"errorMessage\":\"38.0.0 is not a valid SDK version. Options are 35.0.0, 36.0.0, 37.0.0, 34.0.0, UNVERSIONED.\",\"exceptionId\":-901541724}],\"initialUri\":\"exp://192.168.10.7:19000\",\"manifest\":{\"env\":{},\"id\":\"@mobeen/app_internet_status\",\"assetBundlePatterns\":[\"**/*\"],\"primaryColor\":\"#023C69\",\"bundleUrl\":\"http://192.168.10.7:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false\",\"slug\":\"app_internet_status\",\"name\":\"app_internet_status\",\"icon\":\"./assets/icon.png\",\"xde\":true,\"loadedFromCache\":false,\"splash\":{\"resizeMode\":\"contain\",\"backgroundColor\":\"#ffffff\",\"image\":\"./assets/splash.png\",\"imageUrl\":\"http://192.168.10.7:19001/assets/./assets/splash.png\"},\"orientation\":\"portrait\",\"iconUrl\":\"http://192.168.10.7:19001/assets/./assets/icon.png\",\"isVerified\":true,\"version\":\"1.0.0\",\"developer\":{\"tool\":\"expo-cli\",\"projectRoot\":\"/Users/abdulmobeen/Desktop/new-app/upgrade-version\"},\"mainModuleName\":\"node_modules/expo/AppEntry\",\"debuggerHost\":\"192.168.10.7:19001\",\"android\":{\"versionCode\":1,\"package\":\"com.my.gymapp\"},\"logUrl\":\"http://192.168.10.7:19000/logs\",\"packagerOpts\":{\"https\":false,\"dev\":true,\"lanType\":\"ip\",\"hostType\":\"lan\",\"minify\":false,\"urlRandomness\":\"5n-vw3\"},\"sdkVersion\":\"38.0.0\",\"platforms\":[\"ios\",\"android\",\"web\"],\"hostUri\":\"192.168.10.7:19000\",\"ios\":{\"buildNumber\":\"1.0.0\",\"supportsTablet\":true,\"bundleIdentifier\":\"com.my.gymapp\"},\"updates\":{\"fallbackToCacheTimeout\":0}},\"shell\":false}},\"rootTag\":1}"]}

**Comment by krishna-dalam** [comment]
I am seeing this too. As soon as the app opens,  following event is printed in the console.

**Comment by gustavolopess** [comment]
Same here

**Comment by brentvatne** [comment]
install the latest version of expo-cli to resolve the issue :)

**Comment by mobeendev** [comment]
@brentvatne Thanks, it's gone now.

**Comment by mobeendev** [comment]
> install the latest version of expo-cli to resolve the issue :)

@brentvatne Thanks, it's gone now.

**Comment by papb** [comment]
I'm still experiencing this with expo-cli 3.26.2. Maybe it was fixed at some point but a regression happened?

@mobeendev What version are you using?

**Comment by jtembrockhaus** [comment]
I upgraded expo sdk to 39.0.0 and have "expo-cli": "^3.28.5". I still experience the error that an "unrecognized event" is printed each time console.log is executed..
Any suggestions?

**Comment by papb** [comment]
@jtembrockhaus To debug, can you try my suggestion above? In other words:

* `expo --version`
* `npx expo --version`
* Create a `"lets-see": "expo --version"` script in `package.json` and then run it with `npm run lets-see`
* Also run `yarn lets-see`

And post the results here please.

**Comment by mobeendev** [comment]
@jtembrockhaus try to uninstall and reinstall expo cli, clear the cache and try upgrade then. I hope it would work.
