### ISSUE TITLE
 [Unhandled promise rejection: Error: Failed to schedule the notification. Trigger of type: calendar is not supported on Android.]

### ISSUE THREAD

**Issue by walkeknow** [expo/expo#8996]
### Summary of Issue
My trigger object in `scheduleNotificationAsync` conforms to the `DailyNotificationTrigger` interface as shown in the [documentation](https://docs.expo.io/versions/latest/sdk/notifications/#dailynotificationtrigger) yet I'm getting this error:
`[Unhandled promise rejection: Error: Failed to schedule the notification. Trigger of type: calendar is not supported on Android.]`

Below is the snippet of code that produces the error:

```
Notifications.scheduleNotificationAsync({
  content: {
    title: 'Complete a quiz',
    body: "👋 Don't forget solve a quiz today!",
  },
  trigger: {
    type: 'daily',
    hour: 15,
    minute: 42,
  },
})
```

### Environment

```
  Expo CLI 3.21.12 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.3 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.12
```

Target Platform: Android 10

**Comment by byCedric** [comment]
Hi @walkeknow! Thanks for your issue report. The notifications module is a big one and the documentation isn't always crystal clear, for that I'm sorry. To schedule a local notification, you have to use the [`NotificationTriggerInput`](https://docs.expo.io/versions/latest/sdk/notifications/#notificationtriggerinput) instead of the `NotificationTrigger`. If you check the input type for a [`DailyTriggerInput`](https://docs.expo.io/versions/latest/sdk/notifications/#dailytriggerinput), you have to supply these properties:

```
export interface DailyTriggerInput {
  hour: number;
  minute: number;
  repeats: true;
}
```

So, for you the example you provided, that would be:

```
{
  hour: 15,
  minute: 42,
  repeats: true,
},
```

Hope it helps!

**Comment by thecodearrow** [comment]
The documentation of Notifications needs to be improved. Please provide more snacks for scheduling notifications. I love Expo and it has made development much easier than native Android but better documentation would go the extra mile

**Comment by thecodearrow** [comment]
I also have one more doubt. If I change the time for scheduled notifications, will earlier scheduled notifications also be scheduled for the next day or only the latest scheduled time would work?

**Comment by miradario** [comment]
I declare the same trigger as shown below and I have the same error('Trigger of type: calendar is not supported on Android'), : 

        let weeklyNotificationAndroid = Notifications.scheduleNotificationAsync({
                    content: 'Test notification' ,
                    trigger: {
                       
                         hour: 17,
                         minute: 10,
                        repeats: true,
                        
                    },              
                    })

I'm testing in an Android device 
Could you help me please?

**Comment by bakerkretzmar** [comment]
I'm also still seeing this issue. This code produces the above error, `Trigger of type: calendar is not supported on Android.`:

```js
await Notifications.scheduleNotificationAsync({
    content: { body: 'Hello' },
    trigger: { channelId: 'default', hour: 10, minute: 23, repeats: true },
});
```

This code does nothing (note the omitted `channelId`):

```js
await Notifications.scheduleNotificationAsync({
    content: { body: 'Hello' },
    trigger: { hour: 10, minute: 23, repeats: true },
});
```

**Comment by webuijorgeGL** [comment]
is there any way to create a schedule notification base in a future date but compatible with ios and android?

**Comment by chefk5** [comment]
Yeah, I also need this fix to be implemented on Android.

**Comment by webuijorgeGL** [comment]
> Yeah, I also need this fix to be implemented on Android.

`Notifications.scheduleNotificationAsync({
    content: {
      title: title,
      body: text,
      data: {
        url: screen
      }
    },
    trigger: {
      seconds: secondsNearest
    }
  });`

You can pass the trigger in seconds

**Comment by RayKay91** [comment]
> > Yeah, I also need this fix to be implemented on Android.
> 
> `Notifications.scheduleNotificationAsync({ content: { title: title, body: text, data: { url: screen } }, trigger: { seconds: secondsNearest } });`
> 
> You can pass the trigger in seconds

Can confirm this works. The hour, minute trigger only work on iOS currently. This needs fixing please!

**Comment by chriszertamayo** [comment]
so no solution to this?

**Comment by phillipjfry93** [comment]
The problem I had was with using the trigger function with a Date instead of defining it by hour, minute, etc.. My problem turned out to just be I was trying to schedule it while on an emulator and that doesn't work.

**Comment by borodaty23** [comment]
Сan anyone help, I use scheduleNotificationAsync to send notifications on a given day and time (with repetition), on IOS everything works fine, but on android an error, (Failed to schedule the notification. Trigger of type: calendar is not supported on Android.) how to fix it?
![image](https://user-images.githubusercontent.com/92786893/208743020-9545f8ea-2d18-4c1e-b311-1fb18ce06b6f.png)

**Comment by robhern135** [comment]
Is there any reason why this sizeable bug has just been left with no answer?

**Comment by LagoonProject** [comment]
> > Yeah, I also need this fix to be implemented on Android.
> 
> `Notifications.scheduleNotificationAsync({ content: { title: title, body: text, data: { url: screen } }, trigger: { seconds: secondsNearest } });`
> 
> You can pass the trigger in seconds

Hi, if you pass the trigger in seconds how do you create a daily notification? 
For example if I want the notification to trigger every day at 8:00AM ?
Or every week, for example on sundays at 2:00PM?

**Comment by SecurID** [comment]
Maybe because it has been closed?

**Comment by robhern135** [comment]
Ok, then my question is why has this sizeable bug been closed with no answer or resolution?

**Comment by karcreativeworks** [comment]
For those still searching, android doesn't support calender, so we can only do seconds

```ts
const getSecondsUntilDate = ({ day, month, hour, minute }) => {
  const now = new Date();
  let date = new Date(now.getFullYear(), month - 1, day, hour, minute, 0);
  let diff = date.getTime() - now.getTime();
  //console.log("seconds untill", diff / 1000);
  if (diff > 0) {
    return Math.floor(diff / 1000);
  } else {
    date = new Date(now.getFullYear() + 1, month, day, hour, minute);
    diff = date.getTime() - now.getTime();
    return Math.floor(diff / 1000);
  }
};
```

and use it like

```ts
Notifications.scheduleNotificationAsync({
      content: {
        title: "Look at that notification",
        body: "I'm so proud of myself!",
      },
      trigger: {
        seconds: getSecondsUntilDate({
          day: 17,
          month: 11,
          hour: 8,
          minute: 5,
        }),
        repeats: false,
      },
    });
```

remember to keep repeat false, otherwise it will cause errors.

and repeat it using expo task manager
