### ISSUE TITLE
[Contacts] Contacts.updateContactAsync creates new contact on android

### ISSUE THREAD

**Issue by dor6** [expo/expo#8997]
### Summary of Issue (just a few sentences)
Contacts.updateContactAsync creates new contact on android instead of updating the existing one

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
android standalone

### Reproducible Demo
can't give a demo because you can only get write permissions on standalone.
but i guess the following code will do:

### Steps to Reproduce
1. run the following code in a standalone android app with WRITE_CONTACT and READ_CONTACT permissions:
`const contacts  = (await Contacts.getContactsAsync()).data;`
`const firstContact = contacts[0];`
`firstContact.firstName = firstContact.firstName + 'test expo';`
`await Contacts.updateContactAsync(firstContact)`;

2. go to your contacts app and search for "test expo".
3. search for the the real first name of the contact you found (the first name without the "test expo").
4. you will see both the original contact and a contact with the "test expo" added to its name.

### Expected Behavior vs Actual Behavior

Expected Behavior:
Contacts.updateContactAsync will update and exisitng contact.

Actual Behavior:
Contacts.updateContactAsync creates a new contact.

**Comment by byCedric** [comment]
Hi @dor6, thanks for the issue report. I can confirm this happens on SDK 38, even when you provide the proper contact id. `Contact.updateContactAsync` does return the id of the contact which should be updated. But eventually, it will create a new contact with a new id (in my case it was `id + 1`). Thanks, I'll mark it as confirmed bug and keep this issue open until it's resolved 😄
