### ISSUE TITLE
StatusBar doesn't work on android

### ISSUE THREAD

**Issue by mgorabbani** [expo/expo#90]
```
"androidStatusBarColor":"#FFFFFF",
  "androidStatusBar": {
    "barStyle": "light-content",
    "backgroundColor": "#0D8F4F"
  }
```
Here barStyle and androidStatusBarColor doesnt' do any changes. why?

**Comment by terribleben** [comment]
My understanding is that these keys only apply in circumstances where the normal React Native `<StatusBar>` component doesn't work, such as when the app is loading. @jesseruder can you clarify?

**Comment by jesseruder** [comment]
Those fields worked for me in an empty project. It turns the status bar `#0D8F4F` because `androidStatusBar` overrides `androidStatusBarColor`. Going to close for now, please link an example if you still can't get it working.

**Comment by mgorabbani** [comment]
Thanks. There should be mentioned that this can either use `androidStatusBarColor` which use default bar color is light. or 
```
"androidStatusBar": {
    "barStyle": "light-content",
    "backgroundColor": "#0D8F4F"
  }
```

**Comment by jesseruder** [comment]
Not sure what you mean. Our docs are here https://github.com/expo/exponent-docs if you want to send a PR!

**Comment by satya164** [comment]
`androidStatusBarColor` is deprecated btw. So don't use it. Can you open a new issue about `barStyle`?

**Comment by rahulrvp** [comment]
hey guys, do we have a solution for the issue with `barStyle`? Please give the link to the corresponding issue if we have it in this repo. I have the same problem. `light-content` shows the items on the status bar in black color.

**Comment by mgorabbani** [comment]
@rahulrvp https://docs.expo.io/versions/latest/guides/configuring-statusbar.html#content
follow this. they updated the doc. you'll get it working i think.

**Comment by rahulrvp** [comment]
@mgorabbani thanks for the reply. Actually, I was following the same link. I am using the `light-content` as described in the doc. But still, all the text and icons on the status bar is shown in black (dark grey) color. I thought there would be some workaround to fix this.

**Comment by abelta** [comment]
Still happening: content shows up dark, no matter the value in the ```light-content``` key.

**Comment by brentvatne** [comment]
@abelta - what's the exact config that you're using? what device and operating system?

**Comment by mmazzarolo** [comment]
Hey @brentvatne I'm having the issue too, setting `"barStyle": "light-content"` still renders a dark content status bar.  

Nothing fancy on my side, but here is the app.json:
```json
{
  "expo": {
    "sdkVersion": "22.0.0",
    "name": "Test App",
    "slug": "test-app",
    "version": "1.0.0",
    "icon": "./src/assets/images/logo-android.png",
    "primaryColor": "#003B60",
    "orientation": "landscape",
    "android": {
      "package": "com.test.test",
      "icon": "./src/assets/images/logo-android.png",
      "permissions": ["CAMERA", "VIBRATE"]
    },
    "androidStatusBar": {
      "backgroundColor": "#012338",
      "barStyle": "light-content"
    }
  }
}
```

And the package.json:
```json
{
  "name": "plastics-app",
  "version": "0.1.0",
  "private": true,
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "precommit": "lint-staged",
    "prettify": "prettier --write 'src/**/*.js'",
    "lint": "eslint src",
    "flow": "flow src",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^22.0.2",
    "react": "16.0.0-beta.5",
    "react-native": "^0.49.5",
    "react-native-animatable": "1.2.4",
    "react-navigation": "1.0.0-beta.19"
  },
  "devDependencies": {
    "eslint": "4.10.0",
    "eslint-plugin-react-app": "1.0.2",
    "flow-bin": "0.53.1",
    "husky": "0.14.3",
    "jest-expo": "^22.0.0",
    "lint-staged": "4.3.0",
    "prettier": "1.7.4",
    "react-native-scripts": "1.7.0",
    "react-test-renderer": "16.0.0-beta.5"
  },
  "prettier": {
    "printWidth": 100,
    "singleQuote": true,
    "trailingComma": "es5"
  },
  "lint-staged": {
    "src/**/*.js": ["lint", "prettier --write", "git add"]
  }
}

```
The issues arises on every device I tested:
- Virtual Nexus 5 (smartphone) - 5.1.0 - API 22
- Virtual Nexus 9 (tablet) - 6.0.0 - API 23
- Physical Asus Tablet P00C - 6.0.0 - API 23

**Comment by satya164** [comment]
> Virtual Nexus 5 (smartphone) - 5.1.0 - API 22

It's not supported on 5.0. I'll check on later versions.

**Comment by TheMarsGuy** [comment]
Yup RN's <StatusBar /> and Expo's keys for setting statusBar color doesn't work on 5.0. They do work from 6.0 on wards.

**Comment by ide** [comment]
@satya164 We have one note on the docs (https://docs.expo.io/versions/latest/guides/configuring-statusbar.html#content) about supporting only Android 6.0+ for the status bar's dark-content style. Are there other behaviors that are supported only on Android 6+ that we should call out clearly in the documentation?

**Comment by mmazzarolo** [comment]
Ops, bad copy paste, it was a Nexus 5x with API 23.  

I'm still able to reproduce the issue on Expo 23.

**Comment by satya164** [comment]
I'll take look today.

**Comment by mmazzarolo** [comment]
Sure, let me know if you need further infos.

**Comment by rexagod** [comment]
Tried all the fixes above, still no results. I think I'll have to stick with View for now. BTW my sdk version is 31 and I'm running this on a nougat device.

**Comment by jhoanborges** [comment]
i just removed barStyle and it solved my problem. It has no problems with emulator but when you compile it just doesn't shows up.
`           <StatusBar
         //barStyle="light-content"
          backgroundColor="#009FDA"
        />`
