### ISSUE TITLE
Unable to bundle asset even after ejecting

### ISSUE THREAD

**Issue by riwu** [expo/expo#900]
I ejected to ExpoKit and added react-native-vector-icons https://github.com/riwu/synergy-lab-time-estimation/blob/master/client/android/app/build.gradle#L3

But when I download my app from Google Play, open it, then turn off internet and go to the screen with the vector icons, it still doesn't show unless I turn on the internet.

**Comment by riwu** [comment]
I thought bundling assets mean that it gets it directly from the binary instead of having to download?

**Comment by terribleben** [comment]
Hi, just an update here:

- We're currently working on a change that will bundle Image assets in standalone apps for first-load-offline use. We're testing it now, and we hope to ship it in our upcoming SDK version (24).
- For non-images, we're also working on that, but it will take a little longer before we can ship it.

I recommend tracking this on the [canny feature request](https://expo.canny.io/feature-requests/p/allow-standalone-apps-to-load-and-function-with-no-internet-connection) for offline apps.
