### ISSUE TITLE
How to exit expo web?

### ISSUE THREAD

**Issue by mitaxe** [expo/expo#9003]
I haven't used expo for a long time and now I see there is support for the web. 
Maybe my question is stupid but I am a bit stuck. How to exit expo web?
I launched it once with `expo start` command and pressed `w` and now I can't exit it.
Every time when I run `expo start` only webpack loads and I can only work with web in the web browser. I haven't found any options in the metro bundler UI and in **--help** how to switch to mobile.

**Comment by AdamJNavarro** [comment]
Hey @mitaxe,

We try our best to reserve github issues for reproducible and actionable bug reports. Please direction questions such as this one to our [forums](forums.expo.io).

Cheers,
Adam
