### ISSUE TITLE
idToken: Null / Google Signin in standalone app

### ISSUE THREAD

**Issue by Ysrbolles** [expo/expo#9008]
When I log user data returned when type===‘success’, there is an accesstoken, but the idToken shows as null. Refresh token, token expiry are all null as well.

Am I doing something wrong?

this is my Code :

```
_signInAsync = async () => {

    try {

      await GoogleSignIn.askForPlayServicesAsync();

      const { type, user } = await GoogleSignIn.signInAsync();

      userAuth = await user.refreshAuth();

      if (type === "success") {

        alert(JSON.stringify(user));

        const credential = firebase.auth.GoogleAuthProvider(

          user.auth.idToken,

          user.auth.accessToken

        );

        firebase

          .auth()

          .signInWithCredential(credential )

          .catch((err) => {

            alert(err);

          });

        this._syncUserWithStateAsync();

      }

    } catch ({ message }) {

      console.error("[GoogleSignIn][_signInAsync] login: Error:" + message);

    }

  };
```

how can i use firebase credential without idToken?

**Comment by AdamJNavarro** [comment]
Hey @Ysrbolles, we try to reserve github issues for reproducible and actionable bugs so I'm going to close this issue. For future reference, please take questions like this to our [forums](forums.expo.io) (which I see you have already done).

Thanks,
Adam
