### ISSUE TITLE
[docs] Notifications has a lot of hard-to-differentiate types

### ISSUE THREAD

**Issue by byCedric** [expo/expo#9009]
The [notifications page](https://docs.expo.io/versions/latest/sdk/notifications/#types) has a lot of different types, including the _trigger-input_ and _trigger_ types. These are not that easily distinguishable from each other, causing issues like #8996. If we can trim the non-input/internal ones (or even separate them) that would be better I think.

**Comment by asobralr** [comment]
Hi,

I'm having trouble differentiating between the CalendarTrigger type (for iOS) and the DailyTrigger (for Android). Is there a workaround to explicitly declare which one I want to use?

Thanks in advance!

**Comment by SleeplessByte** [comment]
Not stale

**Comment by amandeepmittal** [comment]
I'll take a look at this. I have an ongoing ticket for updating the notifications page. Thanks for opening it!

**Comment by SleeplessByte** [comment]
I'm unsubscribing from this issue so the next round it'll be up to someone else.
