### ISSUE TITLE
Push Notifications with existing server

### ISSUE THREAD

**Issue by parachute-dev** [expo/expo#901]
Hi there,

Is the only way to achieve this to detach?

We are overhauling an existing app that has a push notification solution, with everything already setup in GCM and APNS. I'm hoping to re-integrate without having to detach, but having not used Push Notifications before, I'm unsure the best approach

**Comment by nikki93** [comment]
Hey is this forum post: https://forums.expo.io/t/push-notifications-with-existing-server/4510 also yours? Makes sense to keep the discussion in one place. And in this case it seems more of a question than an issue so closing the issue here.
