### ISSUE TITLE
[docs] expo-notifications demo doesn't works

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#9010]
The Snack example in the expo notifications docs doesn't work.

```
Device: (858:881) undefined is not an object (evaluating 'this._nativeModule.startObserving')
  Evaluating module://App.js.js
  Loading module://App.js
```

Steps to reproduce:
1. Open a new incognite window in your pc
2. Go to https://docs.expo.io/versions/latest/sdk/notifications/
3. Click on "**Try this example on Snack**" button
4. Install Expo app on your device (iOS and Android have the same bug)
5. Scan the QR code
6. You will see the error

![image](https://user-images.githubusercontent.com/870365/86017776-10966900-b9ea-11ea-8636-8d3305a71c54.png)

**Comment by byCedric** [comment]
Hi @RodolfoGS, thanks for the issue report. I've created a PR to fix this! You can work around this by setting the SDK version to 38 manually (bottom-right) and use the latest Expo Client (`expo client:install:android`, use latest or `SDK 38 - Client 2.16.1`). 

Hope it helps!

**Comment by RodolfoGS** [comment]
Thanks @byCedric, that worked. But now I found another issue. I don't know why but the `onReceived` and `onResponseReceived` functions never been called, even though the notifications works perfect.

Steps to reproduce:
1. Open https://docs.expo.io/versions/latest/sdk/notifications/
2. Click **Try this example on Snack**
3. Change to **expo sdk 38**
4. Open Expo app on your device
5. Scan QR Code
6. Tap on **Press to send notification** button
7. The notification appear but the function **onReceived** never was called
8. If you tap on the notification, **onResponseReceived** not is called

I don't know what happen ¯\_(ツ)_/¯

**Comment by pascalchristian** [comment]
> Thanks @byCedric, that worked. But now I found another issue. I don't know why but the `onReceived` and `onResponseReceived` functions never been called, even though the notifications works perfect.
> 
> Steps to reproduce:
> 
> 1. Open https://docs.expo.io/versions/latest/sdk/notifications/
> 2. Click **Try this example on Snack**
> 3. Change to **expo sdk 38**
> 4. Open Expo app on your device
> 5. Scan QR Code
> 6. Tap on **Press to send notification** button
> 7. The notification appear but the function **onReceived** never was called
> 8. If you tap on the notification, **onResponseReceived** not is called
> 
> I don't know what happen ¯_(ツ)_/¯

Same issue here on snack, expo sdk 38, android client.

**Comment by RodolfoGS** [comment]
@pascalchristian See that issue here https://github.com/expo/expo/issues/9058#issuecomment-653464268

> If you want to fully test it, you can use the `Expo APIs` app (you can find it in the second tab in expo-client) or you can just copy snack from docs to your application.

**Comment by zaherbasamak** [comment]
Same problem here

**Comment by lukmccall** [comment]
@zaherbasamak, please see https://github.com/expo/expo/issues/9058#issuecomment-653464268

**Comment by zaherbasamak** [comment]
> @zaherbasamak, please see [#9058 (comment)](https://github.com/expo/expo/issues/9058#issuecomment-653464268)

I upgraded everything (expo sdk, expo cli) and for now the error doesn't appear

**Comment by zaherbasamak** [comment]
In my case the error was happenning when calling 
const subscription = Notifications.addNotificationResponseReceivedListener(response => {
      const url = response.notification.request.content.data.url;
      Linking.openUrl(url);
    });

**Comment by yarapolana** [comment]
I added to Bare workflow yesterday and it gives the same error only on android so far.

**Comment by rahuldasgupta24** [comment]
Still facing the same error. Any solution yet?
