### ISSUE TITLE
iOS simulator is not taking library updates changes

### ISSUE THREAD

**Issue by psyycker** [expo/expo#9016]
### Summary of Issue (just a few sentences)
If I install a library, use it on my iOS simulator and then update it through the package.json. The previous version is kept in cache

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.21.13

I'm working on both Android and iOS, but Android is not affected by this issue

### Reproducible Demo

- Install this library in version 1.0.1: https://github.com/psyycker/react-native-hamburger
- In a iOS simulator (cannot test on proper device) use this component and try to use all available properties (Expected borderRadius which is available in version 1.1.1
- When the component is successfully rendered. Close your expo watcher and install the version 1.1.1 (For me side, I installed it by first cleaning the package-lock.json and node_modules and run `npm install`
- Apply the `borderRadius` property on the hamburger component
- Run expo start and have a look to the component

### Expected Behavior vs Actual Behavior

The expected behavior is that borderRadius should be present, but it's not

**Comment by AdamJNavarro** [comment]
Hey @psyycker,

Can you try running `npm cache clean` and then `expo start -c` to clear your npm cache and the metro bundler cache and see if the desired changes are picked up?

Cheers,
Adam
