### ISSUE TITLE
Only portrait orientation is really working

### ISSUE THREAD

**Issue by cseelus** [expo/expo#902]
Both settings for `orientation` (`default` and `landscape`) don't work properly in an Expo standalone App (tested on iOS 11.1 and some older versions).

**Expected behavior** would be to be able to open an App in landscape orientation when "orientation": "default"` is set. 

**Actual behavior** is that after a brief moment where the Splash Screen is shown in the right orientation, the App switches the Splash Screen back to portrait orientation and opens the App in that orientation. The user has to rotate her iPad or iPhone to portrait, then back to landscape, to finally get the App shown in the desired orientation.
This happens both on cold start and of course when switching back to such an already started App after a while and its not cached in RAM anymore.

The setting "orientation": "landscape"` has different problems:

**Expected behavior** would be to be able to open an App in landscape orientation with both the device turned right or left, when "orientation": "landscape"` is set. 

**Actual behavior** is that after a brief moment where the Splash Screen is shown in the right orientation, the App switches the Splash Screen back to portrait orientation, then opens the App in the right orientation. If you turn your device left though, then open the App, it shows the same behavior, only the App is turned upside down then.

I experienced the first behavior with my own Expo App after using `"orientation": "default"` and was able to reproduce it with one of Expos sample apps, ["Playlist Example" Expo App](https://github.com/expo/playlist-example).
I upgraded that App to use the latest SDK (22.0.2), added some iOS settings and utilize a Splash Screen in the following manner, so I was able to see that behavior better:

```javascript
    "ios": {
      "bundleIdentifier": "com.mycompany.sometestid",
      "isRemoteJSEnabled": false,
      "supportsTablet": true,
      "config": {
        "usesNonExemptEncryption": false
      },
      "splash": {
        "backgroundColor": "#fff8ed",
        "resizeMode": "contain",
        "image": "./assets/images/splash.png",
        "tabletImage": "./assets/images/splash-ios-tablet.png"
      }
    }
```

I built standalone Apps from that Expo example app for both `"orientation": "default"` and `"orientation": "landscape"` and tested on iPhones and an iPad using Apple Testflight.

**Comment by terribleben** [comment]
Thank you for the detailed report. This is on my radar but I haven't had a chance to deeply investigate it yet.

**Comment by markphilpot** [comment]
Has there been any progress on this (or any workaround discovered?) This issue is by far the number one reported issue, especially for iPad users that have their device in a keyboard... they have to rotate the entire device if the app restarts, potentially needing to undock the iPad...

**Comment by lropero** [comment]
Hi, any updates on this?
This bug affects negatively the UX for landscape-only apps.

**Comment by AdamJNavarro** [comment]
Hey all,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. Recent posts indicate this remains an issue, could one of you please open a new issue with a repro case? We'll get it appropriately assigned and we'll be happy to investigate.

Cheers,
Adam

**Comment by PizzaBrandon** [comment]
@AdamJNavarro I'll work on pulling together a reproduction case as I can't use my app as a demonstration, but I don't see how closing this ticket helps when you acknowledge it is an active issue. My app is built using v32, so this certainly does apply to "currently supported versions". To note the gravity and age of the issue, wouldn't it be more appropriate to leave this one open so it's more obvious than a new ticket that this is a well-aged and ongoing issue?

**Comment by cseelus** [comment]
@PizzaBrandon I have tested it again with Expo 32 and a standalone build, after we had deactivated landscape orientation for our app until now (since it didn't really work with previous Expo SDKs) and I have to say it works as expected now.

**Comment by PizzaBrandon** [comment]
I am glad it is working for you, but it is not for me. I had to go around and rotate all of my customer's mounted pads to have the home button on the left because, in the opposite orientation, the app would always start upside down and would not switch back until the pad had been removed and rotated a few times. @cseelus Can you please post what you can of your configuration? I will try to pull together a demonstration this weekend based on the configuration my app is running.

@AdamJNavarro Will you consider re-opening this ticket rather than requiring a new ticket?

**Comment by cseelus** [comment]
@PizzaBrandon All I did was changing to `"orientation": "default"` (from `"orientation": "portrait"` in the app.json. Works even with iPhone when starting in landscape orientation (both left and right).

One thing I noticed is that some packages require additional setup. We use some Native Base Pickers throughout our app and I had to set `supportedOrientations: ['portrait', 'landscape']` so it would not reset the orientation to portrait when selecting an Item from the Picker item list.

**Comment by PizzaBrandon** [comment]
Mine is a landscape-only app until I do some more work on it, so I had `"orientation": "landscape"`. I made the change to `"orientation": "default"` a few iterations ago, hoping to correct this, but still have the same behavior.

**Comment by souhaiebtar** [comment]
i have the same problem, i'm using expo 32,  when testing on ios ScreenOrientation is rendered correctly, but when testing on android ( 7.1.1 and 8) the screen show on landscape mode than it goes back to portrait mode, the code i'm using is 

```
componentDidMount() {
    ScreenOrientation.allowAsync(ScreenOrientation.Orientation.LANDSCAPE);
  }
```
like show in 
![OrientationGobackToPortrait](https://i.imgur.com/DGZmFMz.gif)
