### ISSUE TITLE
[expo-local-authentication] Authenticate without explicit user action

### ISSUE THREAD

**Issue by MiroYar** [expo/expo#9024]
### Authenticate without explicit user action.

  Good day.
I’m developing an application based on Expo. The application provides biometric authorization of the user, but if the user on the Android device uses authorization by the iris or face, then he has to additionally confirm his actions to complete authorization. From the [documentation](https://developer.android.com/training/sign-in/biometric-auth#no-explicit-user-action) it follows that this need can be disabled by adding setConfirmationRequired to Java code. Is it possible to add this function so that it is passed through the settings object in authenticateAsync?
(sorry for my English)

**Comment by AdamJNavarro** [comment]
Hey @MiroYar,

Thanks for taking an interest in Expo. As for you question, it's not currently possible with the `LocalAuthentication` module as is so implementing the behavior you desire in a Managed Expo project won't work. You could use the Bare workflow which grants you access to the native code in which you could write your own code to implement said functionality or find a third-party library as an alternative. If that's not something you are comfortable with, I'd also recommend creating a Feature Request on our [Canny Board](https://expo.canny.io/feature-requests) so we can track interest from the community.

One last thing, in the future if you could please take these types of questions to our [Forums](forums.expo.io) that would be greatly appreciated. We try to reserve Github Issues for reproducible and actionable bug reports.


Cheers,
Adam
