### ISSUE TITLE
Anchor support for expo-sharing running on iPad

### ISSUE THREAD

**Issue by outaTiME** [expo/expo#9025]
Hi guys, 
it will great to have anchor property for expo-sharing like actionsheet, im getting unexpected render issue, here the capture:

![CleanShot 2020-06-30 at 00 34 16](https://user-images.githubusercontent.com/140472/86080823-29466380-ba6a-11ea-8d95-6bfd5e877d63.gif)

(take a look where expo-sharing sheet is displayed)

**Comment by JackGlobetrotter** [comment]
Having the same issue, might look into if i have the time soon.

**Comment by rraczae** [comment]
Do you know if there is a workaround for this? This makes it unusable for ipads

**Comment by rraczae** [comment]
so a after looking at the source, a workaround could be to use RN's `ActionSheetIOS.showShareActionSheetWithOptions()` and pass `anchor` as an option (just like for `showActionSheetWithOptions`):

```
ActionSheetIOS.showShareActionSheetWithOptions(
            {
              url: uri,
              anchor: ref.current,
            },
            (error: Error) => {
              // ...
            },
            (success: boolean, shareMethod: string) => {
              // ...
            }
          );
```

**Comment by outaTiME** [comment]
sorry but I don't understand your workaround @rraczae, as seen in the animation the problem is not with the action sheet that I am using (https://github.com/expo/react-native-action-sheet) which has anchor support for iOS (https://github.com/expo/react-native-action-sheet#ios-only-props), but with the dialog that is shown after it is generated by 'expo-sharing' that it would be desirable that it also had it.

**Comment by rraczae** [comment]
hey @outaTiME, right, so instead of expo sharing use `ActionSheetIOS.showShareActionSheetWithOptions`:

https://reactnative.dev/docs/actionsheetios#showshareactionsheetwithoptions

Although it does not list anchor as an option, you can actually pass it.

Cheers,

Rob

**Comment by outaTiME** [comment]
Thanks and super clear, 
I am going to try to implement this workaround only for ios and for android I will continue using `expo-sharing`, 

when I have a snippet I will be sharing it 🙏

**Comment by rraczae** [comment]
Sweet! Just be cautious since this is not officially listed in the RN docs. I created a bug in that repo in case you're interested:

https://github.com/facebook/react-native/issues/30833

No response yet but we'll see.
