### ISSUE TITLE
Support for new limited access permission to media library (iOS 14)

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#9027]
iOS 14 introduces some new privacy tweaks, one of them is the new way of giving apps the access to media library assets. As an addition to granting access to the entire library, you can now select specific assets that you give the app access to.
We need to make sure it still works well in existing apps (right now it doesn't in Instagram and Messenger) and maybe add some new features related to this.
Another thing worth to mention is that if you don't choose "Allow Access to All Photos" in the first permission request/alert and choose "Select Photos..." instead, then subsequent alerts will give you other options: "Select More Photos..." and "Keep Current Selection".

**Comment by cvburgess** [comment]
Note, as of at least SDK 42 and 43 [this issue](https://github.com/expo/expo/issues/11081) appears where "limited" is an option that is never respected.

Steps to reproduce:

- Select limited photos when granting permissions
- Access the camera roll with expo-image-picker
- [ BUG ] All items, not just the ones selected appear as an option
- If the user goes to iOS settings, the limited option is selected and the selected options are accurate

It appears as if the image picker doesn't respect the limited selection. Is that a regression or a misunderstanding of the feature? Other react-native pickers we used pre-expo respected the option so it feels library-specific.

**Comment by brentvatne** [comment]
i'm a little confused by what you describe. when you select "limited" it means that you cannot programmatically read all images on the device, but rather you have access to whatever is selected in that image picker modal.

**Comment by cvburgess** [comment]
Sorry i may have done a poor job explaining.

Ill attach some videos that might explain it in 1000 words or whatever the cliche is.


If the user grants access to 5 of their 5000 photos and videos, iOS saves that selection and its totally a-ok.

When you programmatically then open the camera roll you would expect to see only 5 options as in every app I checked on my phone... but what really happens is all 5000 are there as if you never limited access in  the first place.

If you go to settings its still set to the same 5 selected photos... the expo-image-picker just appears to "ignore" that and show them all anyway.

https://user-images.githubusercontent.com/2141199/140529981-f3a856c9-3885-42b5-b12c-4dc2fd78ad9c.mov

https://user-images.githubusercontent.com/2141199/140529956-3fab2289-bcb1-4f74-ac38-e7d6e3a02a84.mov

**Comment by cvburgess** [comment]
https://user-images.githubusercontent.com/2141199/140530368-0b9e8aac-651b-4236-8b26-89967e516aea.mov


https://user-images.githubusercontent.com/2141199/140530405-a1700a86-0967-46be-aadb-48ea09d8f380.mov

**Comment by brentvatne** [comment]
@cvburgess - thanks for the info! can you create a new issue that includes the content from your comment?

**Comment by brentvatne** [comment]
@cvburgess - so i looked into this and it turns out that it's actually not necessary to request permissions *at all* before using `ImagePicker.launchImageLibraryAsync` because UIImagePickerController runs out of process on ios 11+ and therefore your app only is given access to the selected image

**Comment by cvburgess** [comment]
Oh wow, that's a hell of a plot twist!

So you're saying we don't need to request permission at all or that `ImagePicker.launchImageLibraryAsync` will auto-request them for us?

I'm going to give it a go and find out in our app, but if you need help with the docs let me know!

**Comment by brentvatne** [comment]
there is no need to request permissions for it as far as i can tell. to learn more, look up UIImagePickerController
