### ISSUE TITLE
Make sure opening projects from clipboard works well (iOS 14)

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#9028]
As of iOS 14, the system shows a notification when something accesses the clipboard. We need to make sure it works fine and doesn't cause too many notifications - afaik we're somehow listening for changes in the clipboard so it might behave weirdly right now.

**Comment by brentvatne** [comment]
moving from #9087 

> [ios14][home] Stop polling Clipboard, replace with intentional UI

> Currently we poll for clipboard changes every 2000ms when the projects screen is active, in order to display a button to press to open a URL from clipboard: https://github.com/expo/expo/blob/3bfa490507a04055183e36b99820d099c8f97f96/home/components/ProjectTools.js
>
> We should re-design this feature so the user explicitly opts-in to having their clipboard read from. Exactly how this looks is up to the implementor.

**Comment by ericlewis** [comment]
Stealing this from @EvanBacon on twitter:
```javascript
if (__DEV__) {
  Clipboard.setString('')
}
```

if you don't need copy and paste stuff for now, just throw this in your `App.js`
