### ISSUE TITLE
Investigate adding support to approximate location (iOS 14)

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#9029]
iOS 14 allows to get approximate location which is going to be faster way to check the location if we only need to get a city/state/country and so on.
Would be great to investigate this feature and if it's easy to add and somehow make it compatible with Android then we can add this to `expo-location`.

**Comment by Kjens93** [comment]
Expanding on this issue, we need `expo-location` to be enhanced with support for:
1. Querying the current value of [`accuracyAuthorization`](https://developer.apple.com/documentation/corelocation/cllocationmanager/3600215-accuracyauthorization)
2. Calling [`requestTemporaryFullAccuracyAuthorization(withPurposeKey:completion:)`](https://developer.apple.com/documentation/corelocation/cllocationmanager/3600217-requesttemporaryfullaccuracyauth) (including support for the new Info.plist dictionary key mentioned in the docs)

**Comment by haveneersrobin** [comment]
The permissions returned by `expo-permissions` should be extended with `accuracyAuthorization` like @kylerjensen mentioned above.

For example: connecting to a WiFi network that your app did not create, without 'Precise Location' turned on, is not possible. It would be very helpful if we could query this value beforehand and ask the user to turn on 'Precise Location' before trying to connect to the Wifi network.

More info, see comments on `fetchCurrentWithCompletionHandler.h` in `/Frameworks/NetworkExtension/NEHotspotNetwork.h`

![image](https://user-images.githubusercontent.com/7559898/146396310-d7acdd79-acbb-459a-95b6-735ad042c795.png)


```
 *   1. application is using CoreLocation API and has user's authorization to access precise location.
 *   2. application has used NEHotspotConfiguration API to configure the current Wi-Fi network.
 *   3. application has active VPN configurations installed.
 *   4. application has active NEDNSSettingsManager configuration installed.
 ```

**Comment by kylerjensen** [comment]
Bump. This is still an issue.

**Comment by tsapeta** [comment]
I'm moving this task to our internal board on Linear. I can't give any estimate on when this will be done, but it's the first in the queue for features to add to `expo-location` 😉

**Comment by danrivett** [comment]
Any update here? We also ran into this issue, and was hoping it would have been addressed already given the promising comment above, but it doesn't seem to have been yet.

**Comment by apbarratt** [comment]
Also hoping for an update on this.
Whilst I appreciate you've moved it to an internal issue tracker, marking the issue as Closed is a little frustrating.  Please reopen here and link with your internal tracker so we know it hasn't been forgotten.
