### ISSUE TITLE
Not compatible with react-native-device-info

### ISSUE THREAD

**Issue by MasterBee-io** [expo/expo#903]
It seems that Expo cannot work together with react-native-device-info even after correctly link with ios.

undefined is not object (evaluating 'RNDeviceInfo.deviceId')

**Comment by nikki93** [comment]
That module needs native code for which you would have to detach, but also Expo's built in `Constants` API https://docs.expo.io/versions/latest/sdk/constants.html has this information.

**Comment by nickdb93** [comment]
I am in the process of learning how to do this, but I think that future viewers would really appreciate some documentation on this workaround.

**Comment by yusrilmr** [comment]
Correct me if I am wrong. But the `Expo.Constants.deviceId` will be different if client uninstall their app and install it again.
Is there any solution to get a static value of Device Id?

**Comment by chcepe** [comment]
Expo.Constants.deviceId changes everytime to reinstall the app. I'm also finding a way to get a static one.

**Comment by chcepe** [comment]
Expo.Constants.deviceId changes everytime I reinstall the app. I'm also finding a way to get a static one.

**Comment by viniciusmaboni** [comment]
Any solution on this guys?
