### ISSUE TITLE
Non critical errors during packaging with module-resolver

### ISSUE THREAD

**Issue by vjsingh** [expo/expo#9032]
### Summary of Issue (just a few sentences)

Bundler will issue non-critical errors during packaging with module-resolver.

Despite, the errors, everything works perfectly. I've been seeing this in my project for over a year now.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.21.9 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/v12.13.0/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.11.25 => 0.11.25
      expo: ^37.0.12 => 37.0.8
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
      react-navigation: ^4.0.10 => 4.0.10

### Steps to Reproduce

Create a new app using expo-cli and choose TypeScript template.
Set up tsconfig.json as follows:

```
 "paths": {
      "@models/*": ["./src/models/*"],
      "@navigation/*": ["./src/navigation/*"],
      "@services/*": ["./src/services/*"],
      "@components/*": ["./tsx/components/*"],
      "@screens/*": ["./tsx/screens/*"],
      "@assets/*": ["./assets/*"]
    }
```

Similarly configure babel.config.js:

```
        plugins: [
            [
                'module-resolver',
                {
                    root: ['./'],
                    alias: {
                        '@models': path.resolve(path.dirname('.'), 'src/models'),
                        '@navigation': path.resolve(path.dirname('.'), 'src/navigation'),
                        '@services': path.resolve(path.dirname('.'), 'src/services'),
                        '@screens': path.resolve(path.dirname('.'), 'tsx/screens'),
                        '@components': path.resolve(path.dirname('.'), 'tsx/components'),
                        '@assets': path.resolve(path.dirname('.'), 'assets'),
                    }
                }
            ]
        ]
```

The above works, however when bundling there are many errors as follows:

```
transform[stderr]: Could not resolve "/Users/jblues/mobbiz/LOSMobileApp/src/navigation/AppNavigator" in file /Users/jblues/LOSMobileApp/tsx/App.tsx.
transform[stderr]: Could not resolve "/Users/jblues/LOSMobileApp/tsx/components/BottomTabNavigator" in file /Users/jblues/LOSMobileApp/src/navigation/AppNavigator.ts.
transform[stderr]: Could not resolve "/Users/jblues/mobbiz/LOSMobileApp/tsx/screens/Login" in file /Users/jblues/LOSMobileApp/src/navigation/AppNavigator.ts.

etc etc (more of the same errors follow)
```

**Comment by byCedric** [comment]
Hi @vjsingh, thanks for the issue report. What happens if you change the `'@models': path.resolve(path.dirname('.'), 'src/models'),` to just `'@models': './src/models'`? [Looking at their documentation, you shouldn't need to provide an absolute path to these directories](https://github.com/tleunen/babel-plugin-module-resolver#getting-started). I've used this babel module as well, without any warning, so I would assume it's related to config stuff.

Hope it helps!

**Comment by vjsingh** [comment]
Boom!!

I should have asked about this before.

That did it - thank you for the help @byCedric. Webpack and babel configs always get me confused.

🕺
