### ISSUE TITLE
Open Expo apps directly from Custom React Native App

### ISSUE THREAD

**Issue by deadcoder0904** [expo/expo#904]
I think this will be a great idea to open my apps pushed on Expo cloud.

Usecase - 

Now I have made 5 apps, but I am tired to scan QR code or open my profile again & again 5 times.

So I will make one single app which is my Main App & it provides link to all my apps. 

Now I can open all my apps from one single app. 

I don't know if this is already available or if Expo supports deep linking. 

But this might be a useful feature.

**Comment by quinlanj** [comment]
hi @deadcoder0904, yes we do support deeplinking https://docs.expo.io/versions/latest/guides/linking.html :)

we are trying to keep github issues related to our software bugs, and if you could put your feature request in https://expo.canny.io/feature-requests that would be awesome. thanks!
