### ISSUE TITLE
Expo notification icon is not rendered instead a white square in status bar and blue square in notification itself

### ISSUE THREAD

**Issue by ksrudeboy** [expo/expo#9048]
![Screenshot_20200701-124715](https://user-images.githubusercontent.com/48894454/86216083-1b443000-bb9b-11ea-9de9-a8953dd9583c.jpg)

I am seeing a white square bar instead of regular expo icon in status bar and blue square in notification instead of my app icon. Please look into the issue. I have seen many people discussing this issue.

**Comment by byCedric** [comment]
Hi @ksrudeboy, thanks for the issue report. Unfortunately, we need a bit more information to start working on a fix for this. If you are able to, submitting a small example through Snack or separate repo would be useful. If you can't supply this, please include the workflow you are using, how you set it up (e.g. `app.json` and the code), and the modules you use. Without this, it's really hard for us to determine the exact cause of this. 

Thanks

**Comment by ksrudeboy** [comment]
Hello @byCedric this is app.json where i have specified icon and color as fallback. 
```
{
  "expo": {
    "name": "Colab.notes",
    "slug": "Colabnotes",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/Cloud.png",
    "splash": {
      "image": "./assets/Colabnotes.png",
      "resizeMode": "cover",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "package": "com.colabnotes.app",
      "versionCode": 1,
      "config":{
        "googleMobileAdsAppId":"ca-app-pub-xxxxxxx-xxxxxxxxx"
      },
      "googleServicesFile":"./google-services.json"
    },
    "notification": {
      "icon": "./assets/cloudnotes_notification.png",
      "color": "#311b92",
      "iosDisplayInForeground": true,
      "androidMode": "default",
      "androidCollapsedTitle": "Updates from Colab.notes"
    }
  }
}

```

And I am sending notification with below code snippet. There is no issue sending or receiving notifications, it an only issue with displaying icons.

```
const sendPushNotification = async (message) => {
    // const message = {
    //   to: this.state.expoPushToken,
    //   sound: 'default',
    //   title: 'A note has been shared with you',
    //   body: 'Baibhav shared New Project meetings note with you',
    //   data: { data: 'click now' },
    //   _displayInForeground: true,
    // };
    const response = await fetch('https://exp.host/--/api/v2/push/send', {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Accept-encoding': 'gzip, deflate',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(message),
    });
};
```

**Comment by ksrudeboy** [comment]
Also as per Expo documentation regarding Notifications 'sound' is only available for ios. Is there any way we can add sound for android notifications. I am using SDK37

sound | iOS Only | 'default' \| null | Play a sound when the recipient receives this notification. Specify "default" to play the device's default notification sound, or omit this field to play no sound.
-- | -- | -- | --

**Comment by ksrudeboy** [comment]
Hi all, i see it is fixed now and regular expo icon now renders fine including my own icon. 
![Screenshot_20200701-193910](https://user-images.githubusercontent.com/48894454/86253935-c9b79780-bbd2-11ea-8c61-340fb5fd2d82.jpg)

**Comment by ksrudeboy** [comment]
Is there any way we can replace the expo icon on status bar and on left with our icon.

**Comment by byCedric** [comment]
Awesome, glad you found it. Did you know what was happening? Maybe we can improve the docs or add checks to see if the icon is valid, possibly helping you (and others) in the future 😄 

> Also as per Expo documentation regarding Notifications 'sound' is only available for ios. Is there any way we can add sound for android notifications. I am using SDK37

Unfortunately, the "old" notifications API, included in managed SDK 37 or 38 projects, doesn't have support for custom Android notification sounds. (`import { Notifications } from 'expo';`) We are working on a newer API with `expo-notifications` that has support for this, but this one is not (yet) available in the managed flow. 

> Is there any way we can replace the expo icon on status bar and on left with our icon.

You should be able to include your own with the `app.json` you currently have ([see the docs](https://docs.expo.io/workflow/configuration/#notification)). This icon is reused in the status bar on Android as well, [see Androids own docs](https://developer.android.com/guide/topics/ui/notifiers/notifications#appearances). But be aware of the limitations to this icon:
> ... image to use as the icon for push notifications. **96x96** png **grayscale** with transparency.

Hope it helps!

**Comment by ksrudeboy** [comment]
It auto fixed both in published app and one in expo client. I dont think it
was an asset issue otherwise published app on playstore will not get fixed
until i build a new binary. I think there were certain issues either on fcm
or expo backend. In slack also many had the same issue.

**Comment by byCedric** [comment]
That might explain it, if you change the `notifications` property in your `app.json` you have to build a new binary. This configuration describes the builders how it needs to configure the native code in your Android app. If you only publish a new bundle, without build, the code refers to configuration that might be missing (like the icon).

**Comment by ksrudeboy** [comment]
I think its a general android issue because i am now seeing the same error
in other apps including expo client sometimes. See this app for reference.
This is a popular game on play store.

**Comment by ksrudeboy** [comment]
![Screenshot_20200701-210035](https://user-images.githubusercontent.com/48894454/86263041-456b1180-bbde-11ea-93d4-7fb9c9ebbb69.jpg)

**Comment by jeanlucnguyen** [comment]
I have the exact same issue. Used this tool to generate the 96x96 png, but I keep having the grey icon. SDK 38, notification.icon is filled with the asset. Any help would be really appreciated

**Comment by mitchobrian** [comment]
> I have the exact same issue. Used this [tool](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=image&source.space.trim=1&source.space.pad=0&name=ic_stat_logo_fblanc_512_large) to generate the 96x96 png, but I keep having the grey icon. SDK 38, notification.icon is filled with the asset. Any help would be really appreciated
> 
> Here's the part in app.json
> 
> ```
> "notification": {
>   "icon": "./assets/logo/notification_icon_android.png",
>   "color": "#ee8172"
> },
> ```
> 
> I have tried to clear the cache by doing `expo start -c` as well, tried it in standalone and expo client.
> 
> Here's the icon below (transparent + white). I understood the white part would be replaced by the color tint in the notification.color key right? (you can't see it because it's white on white background in github, but it's just below)
> 
> ![storylation-transparent](https://user-images.githubusercontent.com/10912221/88771839-182f6600-d180-11ea-9ddf-b471c098c7fc.png)

Did you solved this? I stuck in the total same situation. :(

**Comment by jeanlucnguyen** [comment]
I wish. Spent 2 days trying to fix this, still not working... really want to know if this is a bug and I just need to wait until it is fixed, or if I'm doing something wrong

**Comment by mitchobrian** [comment]
I found a workaround. It works, if you set the native app icon to the requred format. So if you specify the icon not globaly you can set the icon for ios and android like this:

...
    "ios": {
      "icon": "./assets/icon.png"
    },
    "android": {
      "useNextNotificationsApi": true,
      "icon": "./assets/push/icon96x96.png",
      "googleServicesFile": "./google-services.json"
    },
...

**Comment by jeanlucnguyen** [comment]
Awesome, will try it now. Do you need to also set the color key for android in android.color ?

> I found a workaround. It works, if you set the native app icon to the requred format. So if you specify the icon not globaly you can set the icon for ios and android like this:
> 
> ...
> "ios": {
> "icon": "./assets/icon.png"
> },
> "android": {
> "useNextNotificationsApi": true,
> "icon": "./assets/push/icon96x96.png",
> "googleServicesFile": "./google-services.json"
> },
> ...

**Comment by mitchobrian** [comment]
the color setting works for me:
`
    "notification": {
      "color": "#002C56"
    }
`

**Comment by jeanlucnguyen** [comment]
@mitchobrian Thx a lot ! It works with your workaround, I do have the same icon as both the home screen icon and the notification icon. I used a colored icon with a transparent background directly, without needing to set the "notification": { "color": ... } property.
By setting the `notification.color` property, it has no effect on the tint of the notification icon, it still stays white. It's not bothering me so much as it's still better than a grey square. But the problem now is my home screen icon has no background, so it doesn't look good. If you have another workaround for this, would be great !

![white_icon](https://user-images.githubusercontent.com/10912221/89012562-b2271800-d312-11ea-8c2d-0d8ce19932d8.jpg)
![Screenshot_20200731-093957](https://user-images.githubusercontent.com/10912221/89012662-ccf98c80-d312-11ea-8e6e-86e87c9d9f87.png)

**Comment by sa1dai** [comment]
@jeanlucnguyen see this [comment](https://github.com/expo/expo/issues/9062#issuecomment-667860336) It will be fixed in Expo 39.

**Comment by luk3skyw4lker** [comment]
how do I do it on bare workflow? I've tried all the possible app.json configurations but it's said on expo docs that this configuration isn't supported on bare workflow.

**Comment by komelabbbas** [comment]
> Hi all, i see it is fixed now and regular expo icon now renders fine including my own icon.
> ![Screenshot_20200701-193910](https://user-images.githubusercontent.com/48894454/86253935-c9b79780-bbd2-11ea-8c61-340fb5fd2d82.jpg)

hello,
how can you fix it ..? plz help

**Comment by VSV6** [comment]
Me too got into the same situation as above @komelabbbas . How can I change notification icon as well as name. Please, can anyone share information about this? Thank you!

**Comment by tahmid1234** [comment]
> ![Screenshot_20200701-210035](https://user-images.githubusercontent.com/48894454/86263041-456b1180-bbde-11ea-93d4-7fb9c9ebbb69.jpg)

How did you manage to remove the expo icon?

**Comment by victormamede** [comment]
I figured you have to rerun `expo eject` if you are using the bare workflow

**Comment by dharmeshpathak** [comment]
> > Hi all, i see it is fixed now and regular expo icon now renders fine including my own icon.
> > ![Screenshot_20200701-193910](https://user-images.githubusercontent.com/48894454/86253935-c9b79780-bbd2-11ea-8c61-340fb5fd2d82.jpg)
> 
> hello, how can you fix it ..? plz help



> Hi all, i see it is fixed now and regular expo icon now renders fine including my own icon. ![Screenshot_20200701-193910](https://user-images.githubusercontent.com/48894454/86253935-c9b79780-bbd2-11ea-8c61-340fb5fd2d82.jpg)


> Hi all, i see it is fixed now and regular expo icon now renders fine including my own icon. ![Screenshot_20200701-193910](https://user-images.githubusercontent.com/48894454/86253935-c9b79780-bbd2-11ea-8c61-340fb5fd2d82.jpg)

Hey, Can you please tell me about how we can add our own images in the notification as you have added on the right side of your notification container?

**Comment by realmojo** [comment]
I need to build "npx expo prebuild" and do it again
Only then will the notification-icon be copied into the /android folder.
