### ISSUE TITLE
Hot reloading not detecting code change in Docker volume

### ISSUE THREAD

**Issue by kotappdev** [expo/expo#905]
Is there a polling mechanism which constantly polls the code in a Docker volume? Currently we have to reset the application each time to view a code change live. In our experience, inside a Docker container the Expo-App doesn't detect changes, so hot reloading isn't working.

Please advise.
Thanks.

**Comment by nikki93** [comment]
`watchman` is used to detect file changes, does that work in this filesystem outside Expo?
