### ISSUE TITLE
[jest-expo] expo's jest-preset is called twice, leading to warnings in console and a corrupted jest-preset

### ISSUE THREAD

**Issue by alex-fournier** [expo/expo#9050]
### Summary of Issue (just a few sentences)

Since upgraded to Expo SDK 38, I noticed some warnings in console when executing jest. The jest-preset.js file in jest-expo is called twice, it is due to a change since jest@25.

The preset is built by mutating the react-native preset, leading to warnings on the second pass and a corrupted output. The preset should be built in a immutable way.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.21.13 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.16.1 - D:\Programs\nodejs\node.EXE
      Yarn: 1.22.4 - D:\Programs\Yarn\bin\yarn.CMD
      npm: 6.13.4 - D:\Programs\nodejs\npm.CMD
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2
```

### Reproducible Demo

1. `expo init -t tabs jest-demo`
2. `cd jest-demo`
3. `yarn test`

Warnings showing in console:
```
Expected react-native/jest-preset to define transform[^.+\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$]
react-native/jest-preset contained different transformIgnorePatterns than expected
```

### Workaround

1. `yarn add jest@^24.0.0`
2. Launch tests using this command: `node ./node_modules/jest/bin.jest.js`

**Comment by byCedric** [comment]
Hi @alex-fournier! Thanks for the issue report _and_ a PR 😄  Do you know what change could cause this? I went over the [changelog](https://github.com/facebook/jest/blob/master/CHANGELOG.md) for 25.x.x, but I can't find anything that might have affected this.

**Comment by alex-fournier** [comment]
I think this commit is causing the issue : https://github.com/facebook/jest/pull/8894

`Fix Jest multi project runner still cannot handle exactly one project` in the [CHANGELOG](https://github.com/facebook/jest/blob/master/CHANGELOG.md#2510) of `25.1.0`.

**Comment by brunohkbx** [comment]
+1
This change here introduced the issue:
https://github.com/facebook/jest/pull/8894/files#diff-9787071c48fc2896fbe36394532b7288R294

**Comment by alex-fournier** [comment]
Any news on this? The PR is ready but still not merged.

**Comment by renanmav** [comment]
@alex-fournier I can confirm that it works for me (patched jest-expo here)
