### ISSUE TITLE
Default Expo Facebook App is in development mode

### ISSUE THREAD

**Issue by jwm0** [expo/expo#9056]
## 🐛 Bug Report
It looks like the default Expo Facebook App is currently set to development mode and I'm unable to use the `expo-facebook` package inside the Expo application.

### Summary of Issue (just a few sentences)
When trying to login via `expo-facebook` package using `Facebook.logInWithReadPermissionsAsync` once the FB popup is open, the action is canceled with error message saying that the app is not configured and currently in development mode.

### Expected Behavior vs Actual Behavior
FB popup shows the Expo application and allows to login using it.

**Comment by byCedric** [comment]
Hi @jwm0, thanks for the issue report. I'm not sure why you receive the "App is currently in development mode", but I can confirm the default app doesn't have a properly configured native platform setting. [This snack should show that](https://snack.expo.io/@bycedric/facebook-default-app). Thanks for the issue report and I'll mark it as a bug to fix!

**Comment by heyhyungi** [comment]
I'm using expo SDK 37 and got a same message from iOS.
But it worked on android without any error messages.

**Comment by c0deslayer** [comment]
Same problem here on iOS, expo SDK 37.

**Comment by jeanlucnguyen** [comment]
Same problem here, IOS, expo  SDK 37. I think it is just a switch to toggle in the Facebook App Dashboard

![Screenshot 2020-07-06 at 09 17 37](https://user-images.githubusercontent.com/10912221/86566228-988bee00-bf69-11ea-8fb0-bcc408b76248.png)

**Comment by cruzach** [comment]
I believe this should be resolved now, @jwm0 could you let me know?

**Comment by jeanlucnguyen** [comment]
It's working for me now

**Comment by cruzach** [comment]
Awesome! will close the issue then
