### ISSUE TITLE
[docs] expo-notifications demo don't work on Android

### ISSUE THREAD

**Issue by RodolfoGS** [expo/expo#9058]
If you run the Snack demo on Android the listeners don't work, so the state never is updated.

Steps to reproduce:
1. Go to https://docs.expo.io/versions/latest/sdk/notifications/
2. Click on "**Try this example on Snack**" button
3. Install Expo Client on your device (Android)
4. Scan the QR Code.
5. Tap on **Press to send notification**
6. The listener `onReceived` must be called, but it doesn't happen and of course the state is not updated.
7. Tap on the notification and the `onResponseReceived` listener must be called but also it doesn't work.

I think that this bug is because the `useNextNotificationsApi` is required in the app.json ([Doc](https://docs.expo.io/versions/latest/sdk/notifications/#android)). But can you add a custom app.json in a Snack project?

**Comment by lukmccall** [comment]
Hi @RodolfoGS, you're right. It won't work, cause  `app.json` needs to be updated. Unfortunately, `snack` doesn't support it. If you want to fully test it, you can use the `Expo APIs` app (you can find it in the second tab in expo-client) or you can just copy snack from docs to your application.

**Comment by RodolfoGS** [comment]
Hi @lukmccall, thanks for your response. However, could you take a couple of minutes to test this issue that is related with the new notifications api as well? It's super easy to test, I created several demos and examples of how to reproduce it, but I didn't get any response and the bug is critical, the notifications don't work when the device is idle with the new api.
With the same device and the same conditions, you just change the flag to true, and the bug appears. 100% of my tests have the same bug.
This is the issue: https://github.com/expo/expo/issues/9037

Thanks!

**Comment by lukmccall** [comment]
@RodolfoGS, we're currently working on it ;) I believe that the fix will appear quickly.

**Comment by faustoct** [comment]
the same in detach

**Comment by brentvatne** [comment]
@faustoct - open a new issue and fill in template please
