### ISSUE TITLE
If you haven't changed this prop yourself...

### ISSUE THREAD

**Issue by appjitsu** [expo/expo#906]
My project was working fine until I switched the emulator from 7 plus to 6 plus.

"expo": "21.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-21.0.0.tar.gz",

Restarting XDE doesn't help. Closing and reopening and clearing ios cache doesn't help.

![simulator screen shot nov 2 2017 4 07 14 pm](https://user-images.githubusercontent.com/10903600/32350445-649be114-bfe8-11e7-8a6d-ce96146df58a.png)

**Comment by nikki93** [comment]
What is `sdkVersion` in `app.json` and can you uninstall Expo from the simulator (so that XDE installs it again automatically).

**Comment by appjitsu** [comment]
Already tried uninstalling, reinstalling. Version is 22 in app.json. I use that version because there is a bug when you deploy if the versions is not 22. I don't use 22 in my project because it's not compatible with other dependencies.

**Comment by appjitsu** [comment]
It was just the version number in the app.json, which should match the expo module in package.json. @nikki93 thanks for your help.
