### ISSUE TITLE
[SDK38] Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.

### ISSUE THREAD

**Issue by linaia** [expo/expo#9065]
### Summary of Issue (just a few sentences)
Using https://github.com/expo/expo/tree/master/packages/expo-firebase-analytics with SDK38 (ejected app), and following https://docs.expo.io/guides/setup-native-firebase

This issue #4518 is back, when running `yarn react-native run-android`

`Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 3.10.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.21.13
```

```
./gradlew --version
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------
Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_221 (Oracle Corporation 25.221-b11)
OS:           Mac OS X 10.15.5 x86_64
````

Obviously targetting android ;)

### Reproducible Demo
No

### Steps to Reproduce

expo eject
Follow the steps for android from 
- https://github.com/expo/expo/tree/master/packages/expo-firebase-analytics
- https://docs.expo.io/guides/setup-native-firebase

**Comment by byCedric** [comment]
Hi @linaia! Thanks for the issue report, but I can't seem to reproduce this issue. Could you provide a [small repro](https://stackoverflow.com/help/minimal-reproducible-example)? It helps us finding and solving issues way faster.  The `appAuthRedirectScheme` is not related to any of the firebase packages, but [it is related to `expo-app-auth`](https://github.com/expo/expo/blob/master/packages/expo-app-auth/android/build.gradle#L45). Are you using this package by any chance?

**Comment by Naveen-g09** [comment]
did anyone find solution for this?
I am facing this error while building the app using eas
i am using keycloak as auth service
what could be a fix around?
![image](https://github.com/expo/expo/assets/76151123/d9196d7a-9163-4b6c-8e23-6c20171697e6)

please help me @byCedric @cruzach @linaia @EvanBacon
