### ISSUE TITLE
[SDK38] expo-firebase-analytics incompatible versions with @react-native-firebase (messaging , crashlytics)

### ISSUE THREAD

**Issue by linaia** [expo/expo#9066]
### Summary of Issue (just a few sentences)
Migrating SDK38 ejected app, using expo-firebase-analytics with previous firebase messaging.

```
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In Podfile:
    EXFirebaseAnalytics (from `../node_modules/expo-firebase-analytics/ios`) was resolved to 2.4.1, which depends on
      Firebase/Core (= 6.14.0)

    RNFBCrashlytics (from `../node_modules/@react-native-firebase/crashlytics`) was resolved to 8.0.1, which depends on
      Firebase/Core (~> 6.25.0)
```

```
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    EXFirebaseAnalytics (from `../node_modules/expo-firebase-analytics/ios`) was resolved to 2.4.1, which depends on
      Firebase/Core (= 6.14.0) was resolved to 6.14.0, which depends on
        Firebase/CoreOnly (= 6.14.0)

    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 8.0.0, which depends on
      Firebase/CoreOnly (~> 6.25.0)

    RNFBMessaging (from `../node_modules/@react-native-firebase/messaging`) was resolved to 7.2.1, which depends on
      Firebase/Messaging (~> 6.25.0) was resolved to 6.25.0, which depends on
        Firebase/CoreOnly (= 6.25.0)
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 3.10.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.21.13
```

### Reproducible Demo

No yet

**Comment by expjess** [comment]
Hi @linaia! It'd be great to get a reproducible example and more info so we can help look into this. (Here's more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example.) 

If you can reproduce your suspected problem, then it'll help us to investigate!

**Comment by linaia** [comment]
Do you really need a reproducible example to check if expo-firebase-analytics could be updated to use Firebase/Core version 6.25.0 (currently used 6.14.0 maybe old...).
Imho, relying triage only on "is there a reproducible example" is not the best choice. I understand that with 758 open issues, you have to choose the priority. This is not high priority and can be checked with expo-firebase-analytics next update.

For now, as it is blocking issue for us, I simply removed expo-firebase-analytics from my package, using instead @react-native-firebase/analytics.

**Comment by IjzerenHein** [comment]
Hi! You don't really need to update or exclude expo-firebase-analytics. Instead, you can just update the `$FirebaseSDKVersion` version in your podfile. This will cause the expo firebase packages to use this version as well. https://github.com/expo/expo/blob/master/packages/expo-firebase-analytics/ios/EXFirebaseAnalytics.podspec

**react-native-firebase docs on updating the firebase native sdk version**
https://rnfirebase.io/#ios

**Comment by free4mOriginal** [comment]
I'm having a similar issue but the fix above doesn't resolve it.

Error after adding `pod 'Firebase/Crashlytics'` in Podfile:

```[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In snapshot (Podfile.lock):
    Firebase/Core (= 6.14.0)

  In Podfile:
    EXFirebaseCore (from `../node_modules/expo-firebase-core/ios`) was resolved to 1.2.0, which depends on
      Firebase/Core (= 6.30.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Firebase/Core` inside your development pod `EXFirebaseCore`.
   You should run `pod update Firebase/Core` to apply changes you've made.
```

This is an expo bare migrated from managed workflow.
I have already done all the basics - wipe and attempt to update pods/node_modules.

**Comment by edwinckc** [comment]
Just confirming the solution above still works for SDK 41. I used `expo-firebase-core` for the recaptcha necessary for phone verification, which resolves to `7.7.0` as of this writing ([relevant code here](https://github.com/expo/expo/blob/master/packages/expo-firebase-core/ios/EXFirebaseCore.podspec#L5-L8)).

I was also using `react-native-firebase/app` which resolved to `7.11.0`. Adding `$FirebaseSDKVersion = '7.11.0'` at the very top (first line) of my Podfile and running `pod install` again worked. I originally wrote `#FirebaseSDKVersion` instead (doh!) so it didn't work.

**Comment by IjzerenHein** [comment]
Thanks for verifying that @edwinckc and sharing that here! 💌

**Comment by cglacet** [comment]
Is there any compatibility list somewhere?
