### ISSUE TITLE
[expo-updates] sdkVersion should not be mandatory if runtimeVersion is given

### ISSUE THREAD

**Issue by arberK** [expo/expo#9067]
Just giving runtimeVersion throws a JSON exception since sdkVersion is also needed, which contradicts the instructions from documentation. 

The bug is [here](https://github.com/expo/expo/blob/56962d2957403175b5feebc89417bcb7962fbc0a/packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/LegacyManifest.java#L56)

**Comment by byCedric** [comment]
Hi @arberK! Thanks for the issue report, could you explain how you got that error (or provide a small repro)? It looks like it's only used for legacy manifests. I can't trigger this on a new SDK 38 project, so it could be related to weird configuration. [It's mainly this piece of code that should not-trigger this](https://github.com/expo/expo/blob/master/packages/expo-updates/android/src/main/java/expo/modules/updates/manifest/ManifestFactory.java#L17-L27).

**Comment by arberK** [comment]
My project was initialised with react-native-init .  
I have not set the "expo.modules.updates.EXPO_LEGACY_MANIFEST" anywhere in my configuration.  I belive this issue is related to [this ](https://forums.expo.io/t/android-expo-updates-issues/38250)

**Comment by cruzach** [comment]
The above linked issue was fixed [(see here for details)](https://github.com/expo/expo/issues/10464#issuecomment-703178030), so I'm going to close this for now. If you're still having trouble- please open a new issue and fill out the bug report template
