### ISSUE TITLE
When I Build the Expo App, It Does Not Load the Latest Javascript Bundle

### ISSUE THREAD

**Issue by githubandrewd** [expo/expo#907]
Hi,

Ok, I have a problem with expo build. Please let me know if you need more details. Basically, the project I am working on is NOT detached. It is just using Expo.

So I publish it. Let's say the javascript bundle version is 0.17, and I am publishing a breaking change to 0.18.

When I load the app from Hockey App, the javascript bundle is clearly not 0.18 because I don't see my breaking changes. Then, I close the app and re-open it, and the JS bundle is updated.

The build script is:
exp build:android

[exp] Android:
[exp] APK: [AWS LINK] apk has been generated, it took 0 seconds

Then, I get an AWS link to the APK, which I download and upload to Hockey Apps.

How should I diagnose this problem?

Exp version is 44.0.0

**Comment by quinlanj** [comment]
hi @githubandrewd , so expo will try to pull in the most recent publish for your app. If you built your app with version 0.17, then publish version 0.18, your app will be polling for new updates and eventually pull the new version 0.18. 

We are currently working on a better system to manage publishes, but in the meantime, if you *dont* want 0.18 to be pulled by your app, you should republish 0.17 under the same expo sdkVersion you published 0.18.

**Comment by githubandrewd** [comment]
Hi @quinlanj . I actually want 0.18 to be embedded with the .APK from the start, but it embeds 0.17 instead, for some reason.

**Comment by quinlanj** [comment]
So when you build your apk, it also publishes whatever you have in your current directory. Is what you have in your directory at build time 0.18, or is it 0.17?

**Comment by libetl** [comment]
Same trouble for me 
https://expo.io/libe/sncf-le-panneau and 
https://play.google.com/store/apps/details?id=org.toilelibre.libe.trains

no matter how many times I issue exp ba in my console and how many times I upload a new version in apps publish, the bundle retrieved at the first place is a quite old version.
Users not understanding what is going on are likely to uninstall the app without restarting.

**Comment by terribleben** [comment]
@libetl from what I can tell, it looks like you updated your app to SDK 23 and published that, then went back and also published a SDK 21 version. Make sure the version you're expecting to see is SDK 23.

@githubandrewd I think we need more information before we can diagnose what's going on. When you run `exp ba` it will take the latest published bundle from the latest SDK you support. If that doesn't appear to be happening, maybe send me your app's url and we can diagnose from there. (or email it to support@expo.io and reference this github thread.)

**Comment by libetl** [comment]
@terribleben Can I send you my apk so you can figure out why an old version is displayed the first time ?
I really don't know why it happens. Even the JS bundle seems right in the apk.
