### ISSUE TITLE
androidNavigationBar configuration is unclear when using "sticky" behavior

### ISSUE THREAD

**Issue by mikkelwf** [expo/expo#9074]
### Summary of Issue (just a few sentences)
This issue spans multiple issue categories, so i'm starting here.
If I configure `app.json` with `androidNavigationBar.visible` set to `sticky`, the development app shows the android app as expected, with the navigation shown always.

If i try to `build` or `publish` with the cli, it throws a config error.

- Why does the cli throw an error when `sticky` obviously work
- Why is `sticky` left out of the app.json documentation

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8 
      react: ^16.x => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-navigation: ^4.x => 4.3.8 
    npmGlobalPackages:
      expo-cli: 3.21.13

### Reproducible Demo

- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve

As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

**Comment by byCedric** [comment]
Hi @mikkelwf, thanks for the issue report. To quickly answer your questions:

> Why does the cli throw an error when sticky obviously work

The value `sticky` is not an accepted value, it simply doesn't exist (see [Android documentation](https://developer.android.com/training/system-ui/immersive)). There is a `sticky-immersive` property, if you use that with a non-transparent background color, the navigation bar is always visible.

> Why is sticky left out of the app.json documentation

See [Android documentation](https://developer.android.com/training/system-ui/immersive), it doesn't exist. We have a `sticky-immersive` that might be the one that you are looking for.

As for why `expo start` works with `"visible": "sticky"`, we do validate the manifest when developing locally. When an invalid value is provided, we don't block it to allow new features to be developed. There should be something logged like the screenshot below. I tried using this in a managed SDK 38 project, and it seems to not have any effect (other than logging the output).

![Screenshot 2020-07-06 at 15 39 16](https://user-images.githubusercontent.com/1203991/86599859-8167f300-bf9f-11ea-88bd-e3543eec4339.png)

In case this doesn't work for you, could you open a new issue with a small repro? With that, we can double-check this way faster for you.

Hope it helps!

**Comment by mikkelwf** [comment]
I think my problems ultimately came down to the google documentation not begin clear on what is actually happening. 

I've tried your suggestion to set `visible` to `sticky-immersive` and setting `backgroundColor` to a non transparent color. This did not work, and expo seemed to ignore the set color all together.

I then removed the `visible` all together, which had the desired effect. Also not the `backgroundColor` kicked in and worked as expected.

Maybe I'm just misreading both the expo and google documentation, but the implied `sticky` when not setting `visible` is not clear at all, and I suggest updating the documentation to reflect this.

**Comment by byCedric** [comment]
Let's re-open this issue as documentation improvement! Thanks for your input @mikkelwf

**Comment by mikkelwf** [comment]
Much appreciated.. :)

Keep up the good work.. :D

**Comment by EvanBacon** [comment]
More info on the behavior: https://expo.fyi/android-navigation-bar-visible-deprecated
