### ISSUE TITLE
barCodeScanner cannot show in full screen

### ISSUE THREAD

**Issue by OscarYuen** [expo/expo#9078]
### Environment

Expo SDK 38 in Android

### Steps to Reproduce

```
const styles = StyleSheet.create({
    cameraContainer: {
        flex: 1,
        alignItems: 'center',
    }
}
```
Inside the React component, it only renders the BarCodeScanner
```
 <BarCodeScanner
      onBarCodeScanned={!this.state.loading ? this._scanQRCodeToRedeem : () => {}}
      barCodeTypes={[BarCodeScanner.Constants.BarCodeType.qr]}
      style={[StyleSheet.absoluteFill, styles.cameraContainer]}
>
</BarCodeScanner>
```

### Expected Behavior

barCodeScanner should show in full screen

### Actual Behavior

barCodeScanner cannot show in full screen with two white area on the top and bottom

![screenee](https://user-images.githubusercontent.com/5617834/62621706-2b359e80-b94f-11e9-9cd9-10591b311299.png)

#### Snack Demo
[Snack Demo](https://snack.expo.io/@oscaryuen/barcodescanner)

It has already existed in SDK 33, 34
Expo SDK 33:  https://github.com/expo/expo/issues/5212

For those who needs workaround, you can take a look on https://github.com/expo/expo/issues/5212

**Comment by renet** [comment]
Afaik, the BarCodeScanner uses the expo-camera component inside. If that's the case, it'd be great, if the other props supported by expo-camera can simply be passed through by BarCodeScanner. `ratio`, for example.

(Sorrily expo-camera causes problems on my Android device that BarCodeScanner doesn't, so I'll stick with the latter for now.)

**Comment by preflower** [comment]
I don't know why a style problem hasn't been solved until now!

**Comment by vankhoa01** [comment]
@OscarYuen: Is there any solution for this issue ?
I tried to refer #5212 but still not solve this issue

Thank you so much

**Comment by OscarYuen** [comment]
> @OscarYuen: Is there any solution for this issue ?
> I tried to refer #5212 but still not solve this issue
> 
> Thank you so much

Hello, I just switched to Camera component to solve my issue. I am not sure if it could solve at the latest version of expo.

**Comment by elabayoub** [comment]
I had same issue, i've tried different solutions, but neither worked;

Here is what i did:

`npx expo install expo-camera`

Then in my tsx file:

```
<Camera
            style={[StyleSheet.absoluteFill, dynamicStyles.container]}
            ratio={'16:9'}
            barCodeScannerSettings={{
              barCodeTypes: [BarCodeScanner.Constants.BarCodeType.qr],
            }}
          onBarCodeScanned={shouldScan ? handleBarCodeScanned : undefined}
        >
</Camera>
```
Container style:

```
const dynamicStyles = useMemo(
    () => ({
      container: {
        width: dimensions.width,
        //width: dimensions.width * 1.7,
        //height: dimensions.height * 1.1,
        height: dimensions.height,
      },
    }),
    [dimensions]
  );
```
