### ISSUE TITLE
import expo, but got empty Object

### ISSUE THREAD

**Issue by lucky3mvp** [expo/expo#908]
hi guys, 

i'm trying to use expo to create a simple app, the sdkversion is 22.0.0

i try to use font.loadAsync function

so i import expo like this:
```js
import Expo from 'expo';
```
and use it in this way:
```js
Expo.Font.loadAsync({
    fontname: require('somewhere')
})
```
but i got error like this( the expo client went to red screen):
```js
undefined is not an object
(evaluating '_expo2.default.Font.loadAync')
......
```

i even try to use console.log to see what i import from expo, like this: 
```js
import Expo from 'expo';
console.log(Expo)
``` 

and i got empty object `{}`

so where did i go wrong ???

anyone can help me ???

**Comment by EvanBacon** [comment]
Did you start from: `exp init`? Outside of verifying that the expo node module is installed correctly, you could get started in snack.expo.io/
If you could share the source or an example that reproduces the issue we can give a better diagnosis! 💙

**Comment by terribleben** [comment]
Let us know if you're still having an issue. As Evan mentioned, an example app (e.g. on [snack](https://snack.expo.io) would be helpful.

**Comment by lucky3mvp** [comment]
thank u guys

i don't know why , i finally re-create my project,  and  re-install the dependencies, and everything went all right.

sorry for troubleing.
