### ISSUE TITLE
Sending 'expo.purchasesUpdated' with no listeners registered. expo-in-app-purchases

### ISSUE THREAD

**Issue by dragslag** [expo/expo#9082]
Expo ejected and setting up in app purchases with expo-in-app-purchases on iOS device. Everything works great, I can make a call to my products and get the iOS sandbox test working, but after accepting a purchase through the iOS dialogues I get the error sending 'expo-puchasesUpdated' with no listeners registered. I checked the documentation and can't find anything about it....

**Comment by SleeplessByte** [comment]
Did you register a purchase handler?

https://docs.expo.io/versions/latest/sdk/in-app-purchases/#inapppurchasessetpurchaselistenercallback-result-iapqueryresponse--void

**Comment by dragslag** [comment]
I put one globally in the App.js and also locally in my payments.js screen which fixed the problem, thank you @SleeplessByte!

**Comment by DovletAmanov** [comment]
What are the other possible reasons for this warning? I use redux-saga and `InAppPurchases.setPurchaseListener()` is being initialized globally at the launch of app. When I call `InAppPurchases.purchaseItemAsync()` I get this warning and listener is not emitting the event. Btw, It started to happen after upgrading to Expo 43. Before migrating to new bare workflow (removing `unimodules` & expo-core setup), it used to work with no problem. Thanks for any suggestions in advance!

**Comment by jaysonlane** [comment]
I'm experiencing the same using Expo 43.0.3

**Comment by garrett-gottlieb** [comment]
Same here, Expo 43.0.2.

**Comment by jb9229** [comment]
i'm suffering from the same error at "Location.watchPositionAsync"

- build: expo run:ios

Who can help you?

**Comment by mstubna** [comment]
Seeing the same issue with expo 44.0.6 and expo-in-app-purchases 12.1.1.
@garrett-gottlieb did you by any chance find a workaround for this?

**Comment by appsgenie** [comment]
same on watchPositionAsync here
