### ISSUE TITLE
[TaskManager] Attempt to invoke interface method 'java.util.Map org.unimodules.interfaces.taskManager.TaskInterface.getOptions()' on a null object reference

### ISSUE THREAD

**Issue by padupuy** [expo/expo#9083]
### Summary of Issue (just a few sentences)
Hi, I use expo-task-manager in a bare React Native app :

When I start a foregroundTask via `startLocationUpdatesAsync` an error is raised for some users, when the app switch to background : 
```

Attempt to invoke interface method 'java.util.Map org.unimodules.interfaces.taskManager.TaskInterface.getOptions()' on a null object reference
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
 "expo-constants": "9.1.1",
 "expo-location": "8.2.1",
 "expo-task-manager": "8.3.0",
 "react": "16.11.0",
 "react-native": "0.62.2",
"react-native-unimodules": "0.10.1",
```

### Reproducible Demo
Here is my code :
```tsx
const updateAppLocationState = React.useCallback(async appState => {
    if (appState === 'active') {
      try {
        const hasStartedLocationUpdatesAsync = await Location.hasStartedLocationUpdatesAsync(LOCATION_TASK_NAME);

        if (hasStartedLocationUpdatesAsync) {
          Location.stopLocationUpdatesAsync(LOCATION_TASK_NAME);
        }
      } catch (error) {
        Logger.error(error);
      }
    }
    if (appState === 'background') {
      Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.BestForNavigation,
        distanceInterval: 20, //meters
        //ios
        showsBackgroundLocationIndicator: true,
        activityType: Location.ActivityType.AutomotiveNavigation,
        pausesUpdatesAutomatically: true,
        //android
        timeInterval: 1000, //milliseconds
        foregroundService: {
          notificationTitle: Config.APP_NAME,
          notificationBody: 'En service. Touchez pour ouvrir',
          notificationColor: theme.colors.primary,
        },
      });
    }
  }, []);
```

Here is a list of some devices where this bug appears : 
SM-A715F, Android 10
SM-A600FN,   Android 10
SM-A530F, Android 9
SM-A405FN, Android 9
SM-A320FL, Android 8.0.0
SM-A202F, Android 10
SM-G975F, Android 10
SM-G973F, Android 10
SM-G960F, Android 10
SM-G930F, Android 8.0.0
BKL-L09, Android 10
FIG-LX1, Android 8.0.0
<img width="1562" alt="Capture d’écran 2020-07-03 à 14 50 56" src="https://user-images.githubusercontent.com/715255/86473180-b9bdc600-bd40-11ea-9cf5-30969bf9733d.png">

**Comment by padupuy** [comment]
I find something relevant in the expo test suite https://github.com/expo/expo/blob/master/apps/test-suite/tests/TaskManager.js#L19-L24 
```
Some of these tests cause Expo to crash on device farm with the following error:
  "sdkUnversionedTestSuite failed: java.lang.NullPointerException: Attempt to invoke interface method
  'java.util.Map org.unimodules.interfaces.taskManager.TaskInterface.getOptions()' on a null object reference"
  getOptions() is being called from within LocationTaskConsumer.java in the expo-location module
  several times without checking for null
```

**Comment by syedhaider03** [comment]
Getting the same error when logging out of the app and then login to the home screen (unsubscribing from location updates in logout and then subscribing again ) , but not on when the app is reopened after being killed.

**Comment by dvester** [comment]
Also experiencing this issue. This is what I see after sometime, and it loops, so it crashes (Expo has stopped working), I dismiss the error, and in 30 seconds or so, it crashes again, it won't even allow me to open the expo app anymore untill I clear app storage.

![Screenshot_20200714-071421_Google](https://user-images.githubusercontent.com/55589943/87420555-803c5480-c5a3-11ea-856a-a4609ab9fddc.jpg)

**Comment by byCedric** [comment]
Hi @padupuy, thanks for the issue report. We found an issue within `expo-task-manager` that caused the problems you mentioned. I created an umbrella issue for that to keep track of. I'll close this issue in favor of that one.

Note, a fix is available in bare workflow already. 😄
