### ISSUE TITLE
Expo Lottie problem in iOS Simulator

### ISSUE THREAD

**Issue by ph-sw** [expo/expo#9084]
### Summary of Issue (just a few sentences)
 I am simply trying to get the Expo Lottie example code to run in the iOS Simulator (iPhone 11 Pro, 13.5) but it gives me an error message saying there was a problem loading the requested app and that it requires a newer version of the Expo Client app. I believe the simulator should be current as Xcode autoupdates. The code runs fine on my iPhone (iPhone 7, 13.5.1) via the Expo client app.

**Environment**
  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.13.0 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz => 0.62.2 
    npmGlobalPackages:
      expo-cli: 3.18.6

**Package.json:**
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz",
    "react-native-web": "~0.11.7",
    "lottie-react-native": "~2.6.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}

### Reproducible Demo
I cannot get Lottie to work in Expo. I am simply trying to get the Expo Lottie example code to run in the iOS Simulator (iPhone 11 Pro, 13.5) but it gives me an error message saying there was a problem loading the requested app and that it requires a newer version of the Expo Client app. I believe the simulator should be current as Xcode autoupdates. This screen shot is from the simulator (The code runs fine on my iPhone (iPhone 7, 13.5.1) via the Expo client app.)
![image](https://user-images.githubusercontent.com/59928201/86480683-7c474180-bd1c-11ea-8d24-883d4e469876.png)

### Steps to Reproduce
This is the code, whcih is copied from Expo Lottie with just the Lottie file changed (I even tried a few different ones).
import React from "react";
import { Button, StyleSheet, View } from "react-native";
import LottieView from "lottie-react-native";

export default class App extends React.Component {
  componentDidMount() {
    this.animation.play();
    // Or set a specific startFrame and endFrame with:
    // this.animation.play(30, 120);
  }

  resetAnimation = () => {
    this.animation.reset();
    this.animation.play();
  };

  render() {
    return (
      <View style={styles.animationContainer}>
        <LottieView
          ref={(animation) => {
            this.animation = animation;
          }}
          style={{
            width: 400,
            height: 400,
            backgroundColor: "#eee",
          }}
          source={require("./assets/2541-spin-lil-loader-v2.json")}
          // OR find more Lottie files @ https://lottiefiles.com/featured
          // Just click the one you like, place that file in the 'assets' folder to the left, and replace the above 'require' statement
        />
        <View style={styles.buttonContainer}>
          <Button title="Restart Animation" onPress={this.resetAnimation} />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  animationContainer: {
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  buttonContainer: {
    paddingTop: 20,
  },
});

**Comment by ph-sw** [comment]
Seems like the problem is with the iOS13.5, although this version has worked fine for me for some time it now seems to have probelms with other programs also (non-Lotiie). When changing to iOS13.2.2 the lottie animation works. However, I still get an error message from the metro bundler, which I didn't get before:
Unrecognized event: {"type":"client_log","level":"log","data":["Running \"main\" with {\"rootTag\":1,\"initialProps\":{\"exp\":{\"manifest\":{\"developer\":{\"projectRoot\":\"/Users/pbhansen/Documents/Coding/expo/Lottie-test\",\"tool\":\"expo-cli\"},\"assetBundlePatterns\":[\"**/*\"],\"hostUri\":\"127.0.0.1:19000\",\"xde\":true,\"env\":{},\"sdkVersion\":\"38.0.0\",\"version\":\"1.0.0\",\"web\":{\"favicon\":\"./assets/favicon.png\"},\"orientation\":\"portrait\",\"bundleUrl\":\"http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false\",\"id\":\"@anonymous/Lottie-test-7c165d7f-e1c5-409c-94a4-df10b1081f87\",\"iconUrl\":\"http://127.0.0.1:19001/assets/./assets/icon.png\",\"name\":\"Lottie-test\",\"loadedFromCache\":false,\"platforms\":[\"ios\",\"android\",\"web\"],\"icon\":\"./assets/icon.png\",\"mainModuleName\":\"node_modules/expo/AppEntry\",\"logUrl\":\"http://127.0.0.1:19000/logs\",\"ios\":{\"supportsTablet\":true},\"isVerified\":false,\"splash\":{\"resizeMode\":\"contain\",\"backgroundColor\":\"#ffffff\",\"image\":\"./assets/splash.png\",\"imageUrl\":\"http://127.0.0.1:19001/assets/./assets/splash.png\"},\"updates\":{\"fallbackToCacheTimeout\":0},\"slug\":\"Lottie-test\",\"packagerOpts\":{\"urlRandomness\":\"4v-zum\",\"https\":true,\"minify\":false,\"hostType\":\"lan\",\"dev\":true,\"lanType\":\"ip\"},\"debuggerHost\":\"127.0.0.1:19001\"},\"appOwnership\":\"expo\",\"initialUri\":\"exp://127.0.0.1:19000\",\"shell\":0}}}"]}

Sorry for the wrong direction in my first problem report...

**Comment by byCedric** [comment]
Hi @ph-sw! Thanks for the issue report!

The image you sent looks like an outdated Expo Client app. I can see that you use SDK 38, to run that locally, you have to use the Expo Client 2.16.0 or higher. You can install or update this with `expo client:install:ios` from your project, with the simulator open. If that doesn't work for you, lmk!

The log you mentioned looks like a known issue with Metro bundler. It picks up all logs and tries to interpret it as a command for Metro. The best thing you can try here is updating the `expo-cli` to the latest version (`3.21.13` as of writing).

If that doesn't work for you, could you create a repository with this issue for us? I'd be happy to investigate this further, but I can't reproduce this on my end.

Hope it helps!

**Comment by ph-sw** [comment]
Updating the expo client solved the problem with Lottie. not working. Thanks!
