### ISSUE TITLE
ImagePicker's permission request throws exception

### ISSUE THREAD

**Issue by woniesong92** [expo/expo#9088]
### Summary of Issue (just a few sentences)
On a fresh react native app, requesting permission using the ImagePicker module throws an exception: 

```
TypeError: undefined is not an object (evaluating '_ExponentImagePicker.default.requestCameraRollPermissionsAsync')
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.13
```

Targeting iOS

### Reproducible Demo

1. expo init
2. `yarn start` in one terminal and `yarn ios` in another
3. Use the code in https://docs.expo.io/tutorial/image-picker/
4. Click the button "Pick a photo"
5. Run into exception

![demo](https://user-images.githubusercontent.com/2935309/86497134-3fd40f80-bd35-11ea-9c2b-44abdb15e596.gif)

**Comment by lukmccall** [comment]
Hi @woniesong92, I've tried to reproduce it. Unfortunately, everything works as expected. 

**Note:** I needed to install `expo-image-picker`, but you didn't add this step in your demo. Please, check if you installed the module.

**Comment by zcr1** [comment]
I had this error when importing as `Import Permissions from 'expo-permissions';` make sure you use `Import * as Permissions`.

**Comment by lukmccall** [comment]
I think this issue is outdated. The `image-picker` in SDK 39 was refactored. So everything should work fine. 

For now, I'm closing this issue. However, feel free to reopen it, if you're still facing this problem.

**Comment by jcity** [comment]
For anyone that might come along this in the future.

This will happen if you select one of the `Bare workflow` options during the `expo init <projectName>` phase of the tutorial. Recreating with one of the `Managed workflow` options will fix it.

**Comment by hetanthakkar1** [comment]
@lukmccall  this issue is still valied
