### ISSUE TITLE
App show "Expo pasted from CoreSimulator" continuously

### ISSUE THREAD

**Issue by huy-lv** [expo/expo#9089]
### Summary of Issue (just a few sentences)
When i run app on iOS simulator iOS 14.0, app show "Expo pasted from CoreSimulator" continuously.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/opt/node@12/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/opt/node@12/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 12.0/12A6159 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.21.13

### Reproducible Demo
http://www.youtube.com/watch?v=F-aSHz9xh8w

- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve

As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

### Steps to Reproduce
Just run expo on iOS 14.0 simulator

**Comment by EvanBacon** [comment]
We don't support iOS 14 yet as it's not released.

**Comment by brentvatne** [comment]
see related code here https://github.com/expo/expo/blob/master/home/components/ProjectTools.js

**Comment by huylv-teko** [comment]
Yeah, i come too early :D

**Comment by huy-lv** [comment]
Yeah, i come too early :D

**Comment by lwerner-lshigh** [comment]
I have a hack for anyone dealing with this frustration. 
1. Break the app so that the error screen shows up on screen. 
2. Click on the copy button in the bottom menu bar.
3. Et Voila! No more annoying copy and paste messages!

**Comment by feliperaul** [comment]
@lwerner-lshigh Could you please share a code snippet that makes the app break? It's bc I've never managed to write code that broke the app before. Ever. Not a single time. I don't even know how to start!

Just kidding 😅 Thanks for the nice tip 😃

**Comment by elilambnz** [comment]
iOS 14 has just been officially released and your simulator would have likely updated too. For those lazy developers out there, here's a guide to stop the notification without manual intervention each time you reload your app.

1. (Taken from #9028) add the following to your `App.js`:
```js
import { Clipboard } from 'react-native'

// HACK: Prevent "Expo pasted from CoreSimulator" notification from spamming continuously
if (__DEV__) {
  Clipboard.setString('')
}
```
2. Disable syncing your pasteboard with Simulator, uncheck the option in `Edit > Automatically Sync Pasteboard`
![Disable syncing your pasteboard with Simulator](https://user-images.githubusercontent.com/14214838/93416859-c642cb00-f8fa-11ea-9581-277fd1c72948.png)

Note: Importing `Clipboard` from react-native core is deprecated, but as far as I can tell the new package from react-native-community is not yet compatible with Expo.

**Comment by codemancarter** [comment]
@elilambnz any idea how to fix this for the non lazy developer? I don't want the "hack" code on my file.

**Comment by ide** [comment]
This will be resolved in the upcoming SDK 39 release. Until then please see @elilambnz's very helpful comment (thank you!) above.

**Comment by brentvatne** [comment]
👉  you can now run `expo client:install:ios` in a sdk 38 project (or in any other project so long as you choose the sdk 38 client version) and you will get an updated client that resolves this.

one caveat is that it is the new version of the client that we will be releasing soon, and so it does not include support for sdk 35.
