### ISSUE TITLE
[expo-auth-session] Unable to get Google+Firebase authentication working in standalone app

### ISSUE THREAD

**Issue by davitykale** [expo/expo#9090]
### Summary of Issue (just a few sentences)

When attempting to follow either of the Google `AuthSession` demos with Firebase (the one using [`Token`](https://github.com/expo/expo/issues/8185#issuecomment-625037667) or with `IdToken` in the [Authentication guides](https://docs.expo.io/guides/authentication/#google).

While this works in development (using the Expo client), I consistently get the following error in my standalone iOS app:

```
Error 400: invalid request
Invalid parameter value for redirect_uri: Custom schemes cannot have authority: come.googleusercontent.apps.MY_GUID://redirect
```

I've also tried to set up the Google-services configuration files for the `expo-google-signin` documentation here: https://docs.expo.io/versions/latest/sdk/google-sign-in/#usage-with-firebase. But this still does not work.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Currently only testing on iOS.

```
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.4/11N111s - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.13
```

### Reproducible Demo

Here is how I am setting up Google authentication with `AuthSession`: 
```
const [request, response, promptAsync] = useAuthRequest(
    {
      responseType: ResponseType.Token,
      clientId: web,
      redirectUri: makeRedirectUri({
        // For usage in bare and standalone
        native: `com.googleusercontent.apps.${
          MY_IOS_GUID
        }://redirect`,
        useProxy,
      }),
      usePKCE: false,
      scopes: [
        "openid",
        "profile",
        "email",
      ],
    },
    discovery
  );
```

**Comment by EvanBacon** [comment]
This is a general Google OAuth error, I think it's unrelated to `expo-auth-session`.
See this SO https://stackoverflow.com/questions/16342191/google-oauth-redirect-to-ios-custom-url

I cannot tell from the issue cuz it seems like the error isn't correct:
```diff
- Invalid parameter value for redirect_uri: Custom schemes cannot have authority: come.googleusercontent.apps.MY_GUID://redirect
+ Invalid parameter value for redirect_uri: Custom schemes cannot have authority: com.googleusercontent.apps.MY_GUID://redirect
```

1. `come` should be `com`
2. Perhaps your auth doesn't allow `://redirect`

**Comment by Vista1nik** [comment]
Usage of Web Client ID in AuthSession `redirectUri` as native will cause `Error 400: Custom scheme URIs are not allowed for 'Web' client type`.

Looks like you need to create Android and IOS clients ID and pass them to AuthSession if app is standalone.
If app is expo client or web, you need to pass Web Client ID.

https://github.com/expo/expo/pull/9177#issuecomment-657209447
