### ISSUE TITLE
38.0.0 Notifications - no method to handle incoming notifications when app is in background

### ISSUE THREAD

**Issue by ermenkov** [expo/expo#9092]
### Summary of Issue
Can't seem to find a method that handles incoming notifications when app is in **background**, i.e. the analog of ```Notifications.addListener()``` from 37.0.0. Methods ```addNotificationReceivedListener``` and ```setNotificationHandler``` fire their callbacks only in a foregrounded app (as the docs say). ```addNotificationResponseReceivedListener``` works in background but it fires only when user interacts with notification (again as the docs say). That leaves no method for handling incoming notifications while app is backgrounded... Or at least I couldn't find it.

### Environment
Expo 38.0.0 & Android

### Steps to Reproduce
From the docs @ https://docs.expo.io/versions/v38.0.0/sdk/notifications/:
> setNotificationHandler -- sets the handler function responsible for deciding what to do with a notification that is received when the app is in **foreground**

From the docs @ https://docs.expo.io/push-notifications/overview/:
```javascript
    ...
    // This listener is fired whenever a notification is received while the app is foregrounded
    Notifications.addNotificationReceivedListener(notification => {
      setNotification(notification);
    });
    ...
```

### Expected Behavior vs Actual Behavior

Expected:
```addNotificationReceivedListener``` to fire it's callback when app is in **background** and **foreground**
(background/foreground then can easily determined by ```AppState```)

Actual:
```addNotificationReceivedListener``` fires it's callback when app is in **foreground**

**Comment by YahyaBagia** [comment]
@ermenkov Can you handle the tapped notification when app was killed? I am using `addNotificationResponseReceivedListener` to handle tapped notification and redirect the user to appropriate screen (based on the type of notification). But the listener only works when the app is in foreground or background. If it was killed and launched due to tapping the notification, then the listener doesn't get called.

`addNotificationResponseReceivedListener` is added in `App.js` :
```
useEffect(()=>{
    Notifications.addNotificationResponseReceivedListener( (response) => console.log(response) );
},[])
```

Am I missing something? Is this the right place to add the listener?

**Comment by ermenkov** [comment]
@YahyaBagia not related to the issue but good question. Anyway I think all listeners are gone with the killing of the app. Maybe someone from expo team can answer better.

**Comment by maurohmartinez** [comment]
@YahyaBagia I am having the same issue... when the app is killed, the listener `Notifications.addNotificationResponseReceivedListener` does not trigger when the app is open by tapping a push notification. Hence, I cannot redirect the user to the right screen. Has anyone been able to resolve it?

**Comment by YahyaBagia** [comment]
> @YahyaBagia I am having the same issue... when the app is killed, the listener `Notifications.addNotificationResponseReceivedListener` does not trigger when the app is open by tapping a push notification. Hence, I cannot redirect the user to the right screen. Has anyone been able to resolve it?

I'm also looking for the answer.

**Comment by cruzach** [comment]
@ermenkov in the legacy version of the notifications module, there was no way to handle notifications that came in while the app was backgrounded and the notification was **not** selected (see [this part](https://docs.expo.io/versions/latest/sdk/legacy-notifications/#notification)) of the docs). Handling notifications (without responses i.e. tapping the notification) while the app is backgrounded isn't possible in `expo-notifications` either. What's the use case for this?

@YahyaBagia are you testing in a standalone app? I tested this behavior and it's working fine for me

**Comment by ermenkov** [comment]
@cruzach thanks for taking the time to look at the issue.
> What's the use case for this?

One such is a messaging app. Say playing a custom short mp3 instead of the default sound.

>...in the legacy version of the notifications module, there was no way to handle notifications that came in while the app was backgrounded...

I venture to say that they are working on **Android**. App is fully expo managed. Tested in standalone and in-expo modes.
```javascript
// callback() is fired when app is backgrounded
// callback() is fired when phone is locked
Notifications.addListener(callback);
```
Did I stumble upon an accidental feature? :)

I still haven't had chance to test it on **iOS**.

**Comment by YahyaBagia** [comment]
@cruzach I've tested it in the standalone app apk (built by expo cli / managed workflow).  If the app was terminated / killed / closed, then tapping on the notification launches the app but the listener does not get fired. If you don't encounter this issue then please share your code where you added the listener, maybe we missed a little-bit and messed-up the listener.

**Comment by cruzach** [comment]
Okay @YahyaBagia I've reproduced the bug you're referring to- `addNotificationResponseReceivedListener` doesn't fire in the managed workflow when the app is killed and the user selects the notification. I was testing this in the bare workflow, and it works there as expected (same version)

**Comment by ermenkov** [comment]
Gotcha. Thanks for the support @cruzach

**Comment by maurohmartinez** [comment]
@cruzach so, where to follow the issue `addNotificationResponseReceivedListener` ??

**Comment by cruzach** [comment]
I linked it above ^ https://github.com/expo/expo/issues/9092#issuecomment-654905834

**Comment by jongbelegen** [comment]
It also seems to work for useLayoutEffect a class component is not necessary

**Comment by codingedgar** [comment]
> ```js
> // callback() is fired when app is backgrounded
> // callback() is fired when phone is locked
> Notifications.addListener(callback);
> ```

This is not accessible today with typescript, is there another work around? I have the same issue, none of the listed listeners invokes its callback in any scenario

**Comment by cruzach** [comment]
@codingedgar that is the old method from the legacy module that was removed in SDK 41. Please refer to the docs on the new module: https://docs.expo.io/versions/latest/sdk/notifications/
