### ISSUE TITLE
Facebook.logInWithReadPermissionsAsync crashes the app on iOS

### ISSUE THREAD

**Issue by denispixi** [expo/expo#9093]
### Summary of Issue (just a few sentences)
When I call the logInWithReadPermissionsAsync method on iOS, my app crashes instantly, idk why.
It's a completely new **BARE** app with the latest SDK 38 created with the command: **expo init --template bare-minimum**

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.13

Running on Simulator (iOS 13.5)

### Reproducible Demo
```tsx
import React from 'react'
import { StyleSheet, Text, View, Alert, Button } from 'react-native'
import * as Facebook from 'expo-facebook'

export default function App() {

  async function loginWithFacebook() {
    try {
      await Facebook.initializeAsync('<MY_FB_APP_ID>')
      const response = await Facebook.logInWithReadPermissionsAsync({
        permissions: ['public_profile', 'email']
      })
      console.log({ response })
    } catch ({ message }) {
      Alert.alert(`Facebook Login Error: ${message}`)
    }
  }
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <Button title="Login con FB" onPress={loginWithFacebook} />
    </View>
  )
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
})
```

### Steps to Reproduce
From the docs here => https://docs.expo.io/versions/v38.0.0/sdk/facebook/

### Expected Behavior vs Actual Behavior
Expected:
get response from FB login and console it

Actual:
App crashes when call the logInWithReadPermissionsAsync method

**Comment by brentvatne** [comment]
I just created a new blank typescript project with expo init, ran `expo install expo-facebook`, then copy and pasted the following code in and it worked as expected:

```js
import { StatusBar } from "expo-status-bar";
import React from "react";
import { Alert, Button, StyleSheet, View } from "react-native";
import * as Facebook from "expo-facebook";

const appId = "1201211719949057";

const testFacebookLogin = async () => {
  try {
    const result = await Facebook.logInWithReadPermissionsAsync({
      permissions: ["public_profile", "email", "user_friends"],
    });

    if (result.type === "success") {
      Alert.alert("Logged in!", JSON.stringify(result), [
        {
          text: "OK!",
          onPress: () => {
            console.log({ type: result.type, token: result.token });
          },
        },
      ]);
    }
  } catch (e) {
    Alert.alert("Error!", e.message, [{ text: "OK", onPress: () => {} }]);
  }
};

export default function App() {
  React.useEffect(() => {
    Facebook.initializeAsync(appId);
  }, []);

  return (
    <View style={styles.container}>
      <Button title="Sign in" onPress={() => testFacebookLogin()} />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

**Comment by denispixi** [comment]
@brentvatne you test was in a new bare workflow app o managed workflow? I’m facing the issue with bare workflow.
If you tested on an app with bare workflow, can u please share the output of expo diagnostics, maybe some version of my packages/tools is outdated

**Comment by brentvatne** [comment]
oh sorry it was in managed workflow. you should be able to trace the error back using the native stack trace in bare workflow to see more information

**Comment by brentvatne** [comment]
confirmed that this is happening in bare workflow

**Comment by denispixi** [comment]
I was starting to go crazy believing it was a problem in my environment 😅.

I logged the exception in the catch block at line 116 of the file `EXFacebook.m`:

![image](https://user-images.githubusercontent.com/20715348/86520406-7c713b00-be09-11ea-9ecd-b82ac3608227.png)

And got the following output:

![image](https://user-images.githubusercontent.com/20715348/86520354-d6bdcc00-be08-11ea-936f-db20d025949d.png)

Maybe some missing replacement of the FB appId value at runtime??

**Comment by OscarYuen** [comment]
Do you also follow this walkthrough?

Follow steps 3 and 4 in the Getting Started Guide(https://developers.facebook.com/docs/ios/getting-started/?sdk=cocoapods) for Facebook SDK for iOS.

If you're also using RCTLinkingManager to handle deep links, you should handle both results in your openUrl method.
```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }
  return [RCTLinkingManager application:app openURL:url options:options]
}
```

**Comment by denispixi** [comment]
I followed step 2 of the the [Get Started - Facebook SDK for iOS](https://developers.facebook.com/docs/ios/getting-started/#step-2---configure-your-project) guide and added the following lines to the `Info.plist` file and replacing the APP_ID and APP_NAME:

```xml
<key>CFBundleURLTypes</key>
<array>
  <dict>
  <key>CFBundleURLSchemes</key>
  <array>
    <string>fb[APP_ID]</string>
  </array>
  </dict>
</array>
<key>FacebookAppID</key>
<string>[APP_ID]</string>
<key>FacebookDisplayName</key>
<string>[APP_NAME]</string>
```
With this change I made the login work
Although it works, this is not mentioned in the `expo-facebook` docs, so I will not close the issue yet

**Comment by Apurva-Shet** [comment]
Hi, I have been facing the same issue when implementing Facebook login using expo-facebook package.
Has anyone found a workaround for the same?
I am using managed workflow with Expo sdk 38

Any help will be much appreciated.
Thanks!

**Comment by stevecode21** [comment]
@denispixi Hello bro, where do you find the Info.plist file?
I have the same issue with Expo SDK 37.0.0.

Thanks.

**Comment by cruzach** [comment]
Sorry about this, we now link out to the Android and iOS guides for anyone in the bare workflow - https://docs.expo.io/versions/latest/sdk/facebook/#installation

I should also note that if you have this set up in app.json and run `expo eject`, the configuration will be applied for you

**Comment by hafridi** [comment]
@Apurva-Shet Were you able to solve this?

**Comment by DavidBrear** [comment]
@hafridi I was experiencing the crash on my iOS device. I think I got it working by doing a new expo build of the standalone app. I did a build to test flight and installed the new version on my device and the modal is now functioning as expected. I think there is something when doing `expo install expo-facebook` that doesn't automatically get deployed when just pushing the bundled javascript.

**Comment by andrewinsoul** [comment]
@brentvatne, I used your exact code for the facebook's openId but the app freezes during initialization of the facebook's SDK. This is the code having the issue (Facebook.initializeAsync(appId)
