### ISSUE TITLE
other server option for download OTA jdk bundle?

### ISSUE THREAD

**Issue by soheils2** [expo/expo#9094]
### Summary of Issue (just a few sentences)
**amazon limitation for some countries!**
we have issue implementing OTA feature in some counteries that amazon banned them because of USA policy!

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

 **hey expo guys** 
in some countries amzon has already banned communication and the access for download bundle specially for download OTA updates.... (at least i think this is the problem)

### Expected Behavior vs Actual Behavior

i dont want add proxy in my app and like that to solve the problem .
but as far as i understand  --> callbacks and apk-download links from expo is open for download in **Iran**.
even existence of a new bundle is checkable and responces are good

but for bundle download i always get error 
then if i get proxy on it will works like a charm :!

**Comment by RodolfoGS** [comment]
You need to create your own server for Expo updates, see docs.
https://docs.expo.io/distribution/hosting-your-app/

> Normally, when over-the-air (OTA) updates are enabled, your app will fetch JS bundles and assets from Expo’s CDN. However, there will be situations when you will want to host your JS bundles and assets on your own servers. For example, OTA updates are slow or unusable in **countries that have blocked Expo’s CDN providers on AWS and Google Cloud**. In these cases, you can host your app on your own servers to better suit your use case.
