### ISSUE TITLE
Simple drawer app using SDK38 is broken on iOS (works on Android and Web)

### ISSUE THREAD

**Issue by ikakara** [expo/expo#9095]
Using the simple [drawer example](https://reactnavigation.org/docs/drawer-based-navigation/). Running the app on iOS returns the following error (works on Android and Web):

```
Device: (914:881) Tried to register two views with the same name RNCSafeAreaProvider
  Evaluating module://react-native-safe-area-context.js
  Evaluating module://@react-navigation/drawer.js
  Evaluating module://App.js.js
  Loading module://App.js
```
Appears related to this bug #https://github.com/th3rdwave/react-native-safe-area-context/issues/110

Try code on Snack: [https://snack.expo.io/@ikakara/github.com-ikakara-expo-sdk38-bug](https://snack.expo.io/@ikakara/github.com-ikakara-expo-sdk38-bug)

Environment:
Windows 10
Expo 3.21.13
yarn 1.22.4
npm 6.14.4

Tested on snack ...

You can find sample code here: https://github.com/ikakara/expo-sdk38-bug

**Comment by brentvatne** [comment]
update to the latest version of the `expo` package. run `expo install react-native-safe-area-context`. you need to ensure you only have one instance of react-native-safe-area-context in your app.

**Comment by ikakara** [comment]
The example uses the latest SDK38 and react-native-safe-area-context.  Regardless, I ran the scripts you suggested and tested on snack - still fails.  Please try the example on snack.  Does it work for you?

**Comment by brentvatne** [comment]
i cloned the repo, ran `yarn` it didn't work because it was missing react-native-gesture-handler, so i ran `expo install react-native-gesture-handler`, then it worked.

so it sounds like the issue you are encountering is a bug with snack, is that correct?

**Comment by ikakara** [comment]
Yes, I can't verify whether the example fails on xcode simulator yet, so I've been using snack.  I'll try the fix ...

**Comment by ikakara** [comment]
I've tried adding "react-native-gesture-handler": "^1.6.1", to the package.json dependencies.  On snack, it strips the react-native-gesture-handler (when I update from git).  When manually adding the dependency to the package.json (on snack) it returns "The package "react-native-gesture-handler" can be imported without adding to "dependencies"package.json" ... I still get the iOS error on snack.

**Comment by sam17896** [comment]
Same for me working on android, but getting error on IOS

**Comment by eliysha** [comment]
Same here
Working on Android simulator but failing on ios simulator

**Comment by IjzerenHein** [comment]
Hey guys, we've just released the fix for this, thanks for reporting!
