### ISSUE TITLE
Expo Notifications: Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by Sharvin26** [expo/expo#9096]
### Summary of Issue (just a few sentences)
I am integrating expo notifications in my application. I am getting Invariant Violation issue when importing the expo notification package.( This only occurs on IOS Simulator )

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
➜ expo diagnostics

  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.13
```

I am getting this issue on IOS simulator only.

### Reproducible Demo

> `expo init` ( Managed Work flow ) => Blank
> `expo install expo-notifications`
> `import * as Notifications from 'expo-notifications';`

### Steps to Reproduce

Same as Above.

### Expected Behavior vs Actual Behavior

I am not getting any error on the Android device. 

But on IOS simulator I am getting the following error:
```
Invariant Violation: Native module cannot be null.

constructor
    NativeEventEmitter.js:36:16
constructor
    EventEmitter.js:8:52
loadModuleImplementation
    require.js:322:6
loadModuleImplementation
    require.js:322:6
loadModuleImplementation
    require.js:322:6
guardedLoadModule
    require.js:201:45
runUpdatedModule
    require.js:657:17
metroHotUpdateModule
    require.js:533:8
define
    require.js:53:24
eval
    [native code]:0
inject
    injectUpdate.js:65:9
forEach
    [native code]:0
injectUpdate
    injectUpdate.js:71:26
on$argument_1
    HMRClient.js:40:21
emit
    index.js:202:37
_ws.onmessage
    WebSocketHMRClient.js:72:20
EventTarget.prototype.dispatchEvent
    event-target-shim.js:818:39
_eventEmitter.addListener$argument_1
    WebSocket.js:232:27
emit
    EventEmitter.js:190:12
callFunctionReturnFlushedQueue
    [native code]:0
```

I am unable to debug the following issue. I am referring [expo documentation](https://docs.expo.io/versions/latest/sdk/notifications/) for integration of the Expo Notification in the application.

**Comment by 1337LutZ** [comment]
Do you get this error already whilst importing the module, or using it? iOS simulator will throw an error because it doesn't support PN.

And to be sure, you are using the code from the snack example?: https://docs.expo.io/versions/latest/sdk/notifications/#api
```
Check out the Snack below to see Notifications in action, but be sure to use a physical device! Push notifications don't work on simulators/emulators.
```

**Comment by Sharvin26** [comment]
I get this error when I am importing the module. Also according to the documentation, simulators/emulators support Local notifications Platform. So How can I use it in the application?

**Comment by Sharvin26** [comment]
Also, It works perfectly on Android Emulator. I am only facing this issue on IOS Simulator.

**Comment by byCedric** [comment]
Hi @Sharvin26, testing push notifications on an emulator or simulator isn't supported at the moment. You can use local scheduled notifications, but not push notifications. It's related to simulators and emulators not having a device token to push to.

Could you share a bit more about how you use the code? This error shouldn't happen when just importing the notifications, if that's the case we need to fix that. But if the import works, and some method actually throws this, I'm afraid that's unsupported on a simulator.

Hope it helps!

**Comment by cruzach** [comment]
`expo-notifications` is supported in the managed workflow in SDK 38, not in SDK 37 (which it seems from your env info is what you're using?)

**Comment by netpoe** [comment]
Any updates with this one?

Environment:

- `"expo": "^37.0.0",`
- `"expo-notifications": "~0.1.1",`

I'm getting this error when using `expo-notifications` as described in the [expo-documentation](https://docs.expo.io/versions/latest/sdk/notifications/#setbadgecountasyncbadgecount-number-options-setbadgecountoptions-promiseboolean): 

<img width="376" alt="Screen Shot 2020-07-03 at 00 05 52" src="https://user-images.githubusercontent.com/4053518/86437089-f6e27380-bcc0-11ea-9002-2a3817ad6392.png">

I'm using a managed workflow. This happens in iOS Simulator iPhone 8. Could it be that it's because I'm at the simulator?
This error won't happen in an Android device running the same app. 

The code that's causing this is: 

```
React.useEffect(() => {
    Notifications.setBadgeCountAsync(2);
  }, [pendingPaymentRequestsCount]);
```

What I do get in Android is this warning: 

![photo_2020-07-03_00-09-35](https://user-images.githubusercontent.com/4053518/86437309-812ad780-bcc1-11ea-9a52-e95cd1692610.jpg)

**Comment by brentvatne** [comment]
> Any updates with this one?
> 
> 
> 
> Environment:
> 
> 
> 
> - `"expo": "^37.0.0",`
> 
> - `"expo-notifications": "~0.1.1",`
> 
> 
> 
> I'm getting this error when using `expo-notifications` as described in the [expo-documentation](https://docs.expo.io/versions/latest/sdk/notifications/#setbadgecountasyncbadgecount-number-options-setbadgecountoptions-promiseboolean): 
> 
> 
> 
> <img width="376" alt="Screen Shot 2020-07-03 at 00 05 52" src="https://user-images.githubusercontent.com/4053518/86437089-f6e27380-bcc0-11ea-9002-2a3817ad6392.png">
> 
> 
> 
> I'm using a managed workflow. This happens in iOS Simulator iPhone 8. Could it be that it's because I'm at the simulator?
> 
> This error won't happen in an Android device running the same app. 
> 
> 
> 
> The code that's causing this is: 
> 
> 
> 
> ```
> 
> React.useEffect(() => {
> 
>     Notifications.setBadgeCountAsync(2);
> 
>   }, [pendingPaymentRequestsCount]);
> 
> ```
> 
> 
> 
> What I do get in Android is this warning: 
> 
> 
> 
> ![photo_2020-07-03_00-09-35](https://user-images.githubusercontent.com/4053518/86437309-812ad780-bcc1-11ea-9a52-e95cd1692610.jpg)
> 
> 

expo-notifications is only available in managed workflow in SDK38+

**Comment by Sharvin26** [comment]
Yes I tried with Expo SDK38 and it's working perfectly now. I haven't tested the notifications working but I am not getting any error on IOS Simulator when I am importing the `expo-notifications`.
I think expo documentation for Notifications must indicate that `expo-notifications is supported in the managed workflow in SDK38+`.
Thanks

**Comment by 1337LutZ** [comment]
> Yes I tried with Expo SDK38 and it's working perfectly now. I haven't tested the notifications working but I am not getting any error on IOS Simulator when I am importing the `expo-notifications`.
> I think expo documentation for Notifications must indicate that `expo-notifications is supported in the managed workflow in SDK38+`.
> Thanks

Well to be fair, when checking the docs, in the top left it says SDK38. When you select SDK37 you get a different page with different code: https://docs.expo.io/versions/v37.0.0/sdk/notifications/

**Comment by RupamShaw** [comment]
expo-init
expo eject --manageworkflow
note : expo is 38.0.8 

install expo-notifications 

in app.js only import * as Notifications from 'expo-notifications'

gives  Expo Notifications: Invariant Violation: Native module cannot be null.
any update?

**Comment by leonaburime** [comment]
@1337LutZ @brentvatne  I am also getting this exact same error when trying use 

expo-location 

on SDK 38. Im using an Android phone that works perfectly however the iOS emulator tells
me the native module is null when its evaluated on line 291.

In the pictures Im attaching you can see that its trying to evaluate the Geolocation
and it completely crashes before anything is even run.  There must be some specific
interplay with iOS + native modules + expo correct?

![Screen Shot 2020-07-19 at 7 06 29 PM](https://user-images.githubusercontent.com/8000641/87892923-3e703b80-c9f3-11ea-8816-11b1de2c8a91.png)
![Screen Shot 2020-07-19 at 7 06 49 PM](https://user-images.githubusercontent.com/8000641/87892928-4039ff00-c9f3-11ea-8198-f879607ba68e.png)
![Screen Shot 2020-07-19 at 7 07 37 PM](https://user-images.githubusercontent.com/8000641/87892929-40d29580-c9f3-11ea-99c9-f371fee6a425.png)

**Comment by brentvatne** [comment]
@RupamShaw - if you ejected then you need to rebuild the binary when you add a native dependency

@leonaburime - what is `getCurrentLocation(Geolocation)`? this is not part of the expo-location api
