### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): TypeError: Network Request failed (uri to blob)

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#9098]
# Problem
Hi, I am trying to post an image to my firestore database. The thing is that when I try to upload it an unexpected error is printed on my console when using my iPhone 6 device, (not on my android).

# My environment is:

Expo SDK 37 v3.11.7
Firebase v8.1.1
Node v12.18.1
Yarn v1.22.4

# Dependencies: 
"expo": "~37.0.3",
"expo-camera": "^8.2.0",
"expo-file-system": "^8.1.0",
"expo-image-manipulator": "^8.1.0",
"expo-media-library": "^8.1.0",
"firebase": "7.9.0",
"firebase-admin": "^8.12.1",

# Reproducible Demo

1) Take a photo with expo camera
2) Crop it and resize it using ImageManipulator
```

    const manipPhoto = await ImageManipulator.manipulateAsync(
      photo.uri,
      [
        {
          crop: {
            ...getCropperProps(pageX, pageY),
          },
        },
        {
          resize: {
            // It is important to resize the image to a valid dimension
            width: actualCropper.width,
            height: actualCropper.height,
          },
        },
      ],
      { compress: 1, format: "jpeg" }
    );

```
3) Get the manipPhoto uri
4) Uri to blob
```

       const response = await fetch(uri);
       const blob = await response.blob();
```

5) Upload to firebase storage

  ```
   const {firebase} = props;
   firebase.getStorage().ref("photos").child(postId).put(blob);
   
   
```

# Error

[Unhandled promise rejection: TypeError: Network request failed]
- node_modules\whatwg-fetch\dist\fetch.umd.js:473:29 in xhr.onerror
- node_modules\event-target-shim\dist\event-target-shim.js:818:39 in EventTarget.prototype.dispatchEvent
- node_modules\react-native\Libraries\Network\XMLHttpRequest.js:574:29 in setReadyState
- node_modules\react-native\Libraries\Network\XMLHttpRequest.js:388:25 in __didCompleteResponse
- node_modules\react-native\Libraries\vendor\emitter\EventEmitter.js:190:12 in emit
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:436:47 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:26 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by byCedric** [comment]
Hi @VictorioMolina, thanks for the issue report!

The network error is correct, you can't request a file with fetch that's stored locally on your device. You can see a workaround for this in the [expo/examples](https://github.com/expo/examples/blob/master/with-firebase-storage-upload/App.js#L178-L205) repository, you could try implementing this as well. (The link to the comment has a detailed explanation of why `XMLHttpRequest` works)

But there are other workarounds that might work as well:
- [Use base64 encoded string to store the file](https://docs.expo.io/versions/latest/sdk/imagemanipulator/#arguments) (I'm not sure If the Firebase version in Expo supports this)
- [Get a `content://` URL with Expo Filesystem](https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemgetcontenturiasyncfileuri)

Hope it helps!
