### ISSUE TITLE
[feature request] Add wix interactable library

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#91]
Wix made this awesome highly performant animation/interaction library. I know it's kind of a stretch to be adding all kinds of things to the exponent core, but this would be a great addition:
https://github.com/wix/react-native-interactable

**Comment by terribleben** [comment]
Thanks for the suggestion, we agree it looks awesome and are discussing this internally. There are also some changes to the library that would make it easier to pull into Expo, which we've asked about. See [relevant discussion here](https://github.com/wix/react-native-interactable/issues/37).

**Comment by ckwong90** [comment]
Any updates to this integration?

**Comment by luispuig** [comment]
Hi. I am exited for this library in expo. Any update?

Thanks

**Comment by jbrunomonits** [comment]
+1

**Comment by dikaiosune** [comment]
Hi! I created a [feature request on Canny](https://expo.canny.io/feature-requests/p/add-wix-interactable-library) for this. Thanks!

**Comment by marstall** [comment]
👍

**Comment by yash2code** [comment]
waiting

**Comment by ide** [comment]
Please upvote the feature request that @dikaiosune linked instead of posting +1 comments.
