### ISSUE TITLE
exp build:ios stuck for over 24 hours

### ISSUE THREAD

**Issue by jordyvanraaij** [expo/expo#910]
Yesterday I started a new iOS build which is taking forever to build (over 24 hours). I think it might be stuck or something. My Build ID is: `ada73ff4-7275-4111-99ed-3d8b4a1f3b26`. Can you guys help me out? I need to ship the new build today.

```
$ exp build:status

[exp] Checking if current build exists...

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: Build in progress...
```

**Comment by krzysztofp** [comment]
@jordyvanraaij how long did you have to wait for the build to complete?

**Comment by blackdynamo** [comment]
I am getting this same issue today. I think it must be server related because I am periodically getting `Internal Server Error` when browsing expo.io/builds. Seems like it times out.

![image](https://user-images.githubusercontent.com/245688/36449798-23ec3d78-1649-11e8-9886-bccd24c41532.png)
