### ISSUE TITLE
Change WebGL viewport dimensions - "expo-gl" & "expo-2d-context"

### ISSUE THREAD

**Issue by Zurdge** [expo/expo#9100]
# Hi folks 😸 

I've been using ```expo-gl``` to port over a Javascript script which uses the standard HTML canvas. Everything is working perfectly apart from my ```expo-gl``` dimensions are too large for what I need. 
Currently it has a size of 1080 x 1920.

How can I change the resolution of the ```expo-gl```?

**Comment by AdamJNavarro** [comment]
Hey @Zurdge,

We try to reserve Github Issues for reproducible and actionable bug reports. For questions such as this one, could you please head over to our [Forums](forums.expo.io) and create a post?

Cheers,
Adam
