### ISSUE TITLE
using expo-image-picker, App crashes when calling ImagePicker.launchCameraAsync function, once returning to app after taking picture.

### ISSUE THREAD

**Issue by shubhamdeol** [expo/expo#9101]
I tried every version of ```expo-image-picker``` and ```react-native-unimodules``` even most latest one. But this issue never fixes for me. Maybe it's somewhere related to my codebase or its a bug. 

1. installed react-native-unimodules.
2. added code to android manifest.
```
<activity
  android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
  android:theme="@style/Base.Theme.AppCompat">
</activity>
```

and 
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

using it like 
```js
  askPermissionsAsync = async () => {
    const { status: camera } = await Permissions.askAsync(Permissions.CAMERA);
    const { status: cameraRoll } = await Permissions.askAsync(
      Permissions.CAMERA_ROLL
    );
    if (camera && cameraRoll !== "granted") {
      alert("camera roll not  granted");
    }
  };

  fetchingCameraimage = async () => {
    const { setPickUpImage } = this.props;
    await this.askPermissionsAsync();
    try {
      const result = await ImagePicker.launchCameraAsync({
        base64: true,
        quality: 0.1
      });
      const cameraImage = result;
      if (!cameraImage.cancelled) {
        setPickUpImage(cameraImage.uri);
      }
    } catch (error) {
      console.warn(error);
    }
  };
```

Adb Logs

```

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to
 activity {com.alluzo.store/com.alluzo.store.MainActivity}: java.lang.NullPointerException:
 Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
```

I don't know why I am receiving ```who``` and ```data``` key as null when seeing ADB logs. 

I tried reproducing in new new bare project but camera works fine. 

If anyone understands anything from these logs please help me out.

**Comment by lukmccall** [comment]
Hi @shubhamdeol, have you overwritten `public void onActivityResult(int requestCode, int resultCode, Intent data)` method in `MainActivity`?

**Comment by shubhamdeol** [comment]
@lukmccall  No I haven't overwritted onActivityResult method. 

But I have some native code for spash screen, which does somethign with Intent. but that should cause issue I guess.
here is my SpashActviity file code.

```
package com.alluzo.store;

import android.content.Intent;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;

public class SplashActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Intent intent = new Intent(this, MainActivity.class);
        // Pass along FCM messages/notifications etc.
        Bundle extras = getIntent().getExtras();
        if (extras != null) {
            intent.putExtras(extras);
        }
        startActivity(intent);
        finish();
    }
}


```

**Comment by lukmccall** [comment]
Could you check if the `getIntent()` method returns a valid object?

**Comment by shubhamdeol** [comment]
I was using ```Bundle extras = getIntent().getExtras();``` for some issue I was facing with notifications. I removed this method.  Still App is crashing after image gets clicked from camera and I press tick icon at top, while navigating back to the app. 
I do not have much knowledge of the native side. You can close the issue. As it works fine in the new project.

**Comment by lukmccall** [comment]
In SDK 39, the image-picker was refactored. So I believe it was fixed. 

For now, I'm closing it. However, feel free to open another one if this bug still occurs.

**Comment by bytesagar** [comment]
@lukmccall 
My expo SDK version ```~44.0.0```
Error i am getting while picking image is
```
Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:2678 flg=0x1 }} to activity {com.globalpanacea.sif/com.globalpanacea.sif.MainActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter mImageLoader
```
