### ISSUE TITLE
SecureStore deleteItemAsync is not working

### ISSUE THREAD

**Issue by AnasAlamin** [expo/expo#9102]
Expo secure store function deleteItemAsync is not working for some reason.
it stores the data and everything but it doesn't delete.

`await SecureStore.deleteItemAsync('userToken')`

Expo-secure-store: 9.0.1
Expo: 38.0.0

**Comment by byCedric** [comment]
Hi @AnasAlamin, thanks for the issue report. Unfortunately, I can't reproduce this on my end. Can you provide a [small repro](https://stackoverflow.com/help/minimal-reproducible-example) where this happens for you? With that, I'd be happy to check this out for you.

**Comment by AnasAlamin** [comment]
it turned out that i have a error in my code , and i alerady fixed it.
thank you anyway, i'm closing this
