### ISSUE TITLE
Android build issue: missing argument for new ModuleRegistryAdapter()

### ISSUE THREAD

**Issue by PolinaLiolia** [expo/expo#9104]
I'm trying to build an ejected React native expo project for android.

Right after eject command, I'm adding all necessary configurations for unimodules and @unimodules/react-native-adapter 
according to instructions from here https://github.com/expo/expo/tree/master/packages/react-native-unimodules and 
https://www.npmjs.com/package/@unimodules/react-native-adapter

Then I'm getting an error, trying to perform build from Android studio: 

...android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:72: error: constructor ModuleRegistryAdapter in class ModuleRegistryAdapter cannot be applied to given types;
      new ModuleRegistryAdapter(),
      ^
  required: ReactModuleRegistryProvider
  found: no arguments
  reason: actual and formal argument lists differ in length

Here is a list of my project dependencies:
"dependencies": {
    "expo": "~37.0.3",
    "expo-splash-screen": "^0.2.3",
    "expo-updates": "~0.2.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-screens": "~2.2.0",
    "react-native-unimodules": "~0.9.0",
    "react-native-web": "~0.11.7",
    "@unimodules/core": "^5.3.0",
    "@unimodules/react-native-adapter": "^5.4.0",
    "expo-ads-admob": "^8.1.0",
    "expo-av": "^8.1.0",
    "expo-facebook": "^8.1.0",
    "expo-google-sign-in": "^8.2.1",
    "expo-in-app-purchases": "^8.1.0",
    "react-native-webview": "^9.4.0",
    "tiny-emitter": "^2.1.0"
  },

Any ideas why does it happen are appreciated.

**Comment by cruzach** [comment]
Hi @PolinaLiolia ! For questions like this, it's always better to post on our [forums]() rather than open an issue on github since we keep github reserved for bug reports. 

I've answered your question here- https://forums.expo.io/t/configure-unimodules-after-ejecting/40072
