### ISSUE TITLE
[jest-expo] Upgrading from Jest-Expo 37 to 38 Breaks tests

### ISSUE THREAD

**Issue by wardjk87** [expo/expo#9105]
### Summary of Issue 
After using the expo upgrade command to upgrade from sdk 37 to 38, all my jest tests broke with following error:

`Test suite failed to run

    TypeError: this._getEventHandlerFor is not a function

      at Object.get (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:86:26)
          at Array.forEach (<anonymous>)
`

 Only reverting expo-jest to 37 fixed the issue.

**Comment by renanmav** [comment]
I’m facing the same problem

**Comment by bhall2001** [comment]
We only saw the issue when using the --runInBand switch (used for circle ci build, local dev did not use the switch). 

A workaround for us was to replace --runInBand with --maxWorkers=2. We also increased our build machine size on circle ci. Needed more memory to run the tests on the build machine with v38.

Note: if you set --maxWorkers=1 we see the same errors as with --runInBand

**Comment by renanmav** [comment]
@bhall2001 didn’t work for me. The issue that I got when I run `yarn test` is this one:

```
 FAIL  src/screens/sign-in/__tests__/forgot-password.test.tsx
  ● Test suite failed to run

    TypeError: (0 , _jestUtil(...).tryRealpath) is not a function

      at ScriptTransformer.transformSource (node_modules/jest-runtime/node_modules/@jest/transform/build/ScriptTransformer.js:424:50)
```
