### ISSUE TITLE
react-native-reanimated cannot be loaded in Expo Snacks with SDK >= 36

### ISSUE THREAD

**Issue by yolpsoftware** [expo/expo#9109]
Please have a look at the following Snack:

https://snack.expo.io/@yolpsoftware/reanimated-snacks

With SDK 35, it works well, the blue ScrollView appears. If you switch the Snack to SDK 36, 37 or 38, you get the following error message:

```
Unable to resolve module 'react-native-reanimated.js'
  Evaluating react-native-reanimated.js
  Evaluating App.js
  Loading App.js
Error: Unable to resolve module 'react-native-reanimated.js'
    at Object.eval (react-native-reanimated.js:1:1

    at eval (react-native-reanimated.js

    at eval (react-native-reanimated.js

    at eval (<anonymous>)
    at [snack internals]
    at Object.n ([snack internals]
    at e.evaluate ([snack internals]
    at Xe ([snack internals]
    at [snack internals]
    at https://snack.expo.io/web-player/38/static/js/app.b348c659.chunk.js:1:28526
```

Same problem if you add `react-native-reanimated` to `package.json` as a dependency.

Tested on Web and iOS, same problem.

**Comment by expjess** [comment]
It doesn't work for me with Snack switched to any version (tried 35-38) and gives me an error that this Snack was written <=SDK34. I think all of SDK35-38 are on `react-native-reanimated` 1.2.0 (vs 1.1.0 in SDK34) -- maybe related?

**Comment by IjzerenHein** [comment]
The snack is missing the `react-native-reanimated` dependency, if you add it it will work:

```
{
  "dependencies": {
    "react-native-reanimated": "1.9.0"
  }
}
```

Reanimated was imported by default in snack for sdk34 but that behaviour was changed in sdk35, so it needs to be added as a dependency explicitly. We are working on making importing dependencies easier. Once that lands you will be prompted to add the dependency an it will also help you select matching versions for the selected SDK.

**Comment by yolpsoftware** [comment]
@IjzerenHein Thanks, this really seems to work.

I did try that, but instead of `1.9.0` I tried `1.2.0` because `1.2.0` is the latest `reanimated` version included in the Expo SDK.

Why can we use `1.9.0` in Expo Snacks, if there is no Expo SDK with `react-native-reanimated: 1.9.0`?

Why are we seeing errrors when using `1.2.0` or `1.7.0`?

**Comment by IjzerenHein** [comment]
That's not entirely correct. Here is the table of `react-native-reanimated` versions shipped with the latest clients

```
sdk38 -> 1.9.0
sdk37 -> 1.7.0
sdk36 -> 1.4.0
sdk35 -> 1.2.0
```

Reanimated is sort of a special library that requires a very tight integration. Because of that the Expo client only the latest version of the native code (as opposed to multiple editions, one per supported sdk).
I'm not entirely sure but I think that is the reason that the 1.9.0 version works well with snack.

**Comment by yolpsoftware** [comment]
I see, thanks.
