### ISSUE TITLE
"npm link <local package>" is not recognized during "exp start" or "EXPO XDE" build

### ISSUE THREAD

**Issue by PavelPZ** [expo/expo#911]
I have Expo project which uses local package (included by ```npm link``` command). Building project with ```EXPO XDE``` or ```expo cli``` ends with ```Unable to resolve ../../App" from "./D:\\cross\\...``` error

**Versions**
- Windows 10 64-bit
- Expo SDK 22.0.2
- Android with Genymotion 2.11.0

**Comment by dikaiosune** [comment]
Which local package are you trying to link? React Native's support for symlinked packages is unfortunately a bit flaky at the moment.

**Comment by PavelPZ** [comment]
Yes, I mean "flaky" symlink...
I solved my problem by ```module-resolver``` plugin configured in ```.babelrc```

**Comment by dikaiosune** [comment]
OK!
