### ISSUE TITLE
Croping image with ImageManipulator on web giving larger result

### ISSUE THREAD

**Issue by offfffz** [expo/expo#9111]
### Summary of Issue 
ImageManipulator gives a larger image than expected when using crop. The result image width becomes `width + originX` instead of just `witdth`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v14.4.0/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.13
```

### Expected Behavior vs Actual Behavior
When cropping an image with ImageManipulator, it should result in the image with the given `(originX, originY, width, height)`.

**Comment by AdamJNavarro** [comment]
Hey @offfffz,

Thanks for filing a bug report. Could you provide a minimal reproducible example that we can use to test on our end?

Cheers,
Adam

**Comment by markstreich** [comment]
Here's a reproducible example, it will attempt to crop the picked image to a centered-square:

https://snack.expo.io/@markstreich/imagemanipulator-web-crop

For example picking [this image](https://user-images.githubusercontent.com/1214573/95973361-379f6c00-0e1c-11eb-83b4-74337842fa89.png) (210x443 original) will result in:

![Screen Shot 2020-10-14 at 12 56 01](https://user-images.githubusercontent.com/1214573/95973683-a8468880-0e1c-11eb-8b28-ac02a6d15add.png)

**Comment by rSkogeby** [comment]
I have a proposed solution for this in #12021.
