### ISSUE TITLE
adjust error message article url when importing node modules

### ISSUE THREAD

**Issue by zanona** [expo/expo#9112]
>Failed building JavaScript bundle.
> The package at "node_modules/eth-lib/lib/bytes.js" attempted to import the Node standard library module "crypto". It failed because the native React runtime does not include the Node standard library. Read more at https://docs.expo.io/introduction/faq/#can-i-use-nodejs-packages-with-expo

https://docs.expo.io/introduction/faq/#can-i-use-nodejs-packages-with-expo doesn't seem to point to a valid resource any more?

https://github.com/expo/expo/blob/5eba5f7f2a6232e70d8febfbd1285953db18f46c/docs/scripts/test-links.js#L19

Possibility, the correct link to point to, is:
https://forums.expo.io/t/can-i-use-node-js-packages-with-expo/29060

_Btw, I would also leave that forum post open to replies as users can contribute on different ways they have managed to make some packages whcih rely on native nodejs module, work. I am currently going through this with web3_

**Comment by AdamJNavarro** [comment]
cc @brentvatne How do you think we should handle this? Update error messaging or pull forum FAQs into docs?

**Comment by brentvatne** [comment]
@AdamJNavarro - it's probably best for us to link to this: https://docs.expo.io/workflow/using-libraries/#determining-third-party-library-compatibility

**Comment by brentvatne** [comment]
https://github.com/expo/expo-cli/commit/e186eaecbdeea5a48d5da1c06b3850cdb409d20c

updated link here, will go out on next deploy of expo-cli
