### ISSUE TITLE
How to connect my Expo with my REST API and a local DB?

### ISSUE THREAD

**Issue by yesIamFaded** [expo/expo#9113]
Hello there I hope you are all good, I have some questions regarding React Native with EXPO.

I have created an App that depends on a postgresql DB and communicates with my own REST API. I have one Folder where my Frontend lives - here I query with my Computers IP address and with the routes I defined in my Backend.

Like this: 192.xx.xx.xx:8080/api/hours/getDay/:userid

My Backend is in another Folder - and I start the server with npm run server. Here I have setup all the routes and the connection to a postgresql db wich is running on a Docker.

First Question I have is do I need to put the Server Folder inside my Frontend Folder? I guess yes because I currently have 2 Folders - If I need to do that, how do I tell my App that it has to start both the server and the Frontend?.

Now the second thing I would like to know is, how can I for example use my app with the Expo app but still access the DB? I think I need to change the IP I query against and somehow make the DB run online and not on a Docker? I want to show the app on my private Phone wich is not connected to the same Network as my PC.

Sincerly Faded~

**Comment by AdamJNavarro** [comment]
Hey Faded,

Thanks for your interest in using Expo. We try to reserve Github Issues for reproducible and actionable bug reports. For questions such as this one, please head over to our [Forums](forums.expo.io) (which I see you already did and that you got some help from another Expo user 😄 ).

Cheers,
Adam

**Comment by yesIamFaded** [comment]
Yeah :D thanks
