### ISSUE TITLE
Upgrade and setup for Reanimated v2

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#9115]
It would be great if we upgrade Reanimated to v2 in the next SDK (39). That may require some additional work and setup other than just running `et update-module` 😞

**Comment by hardcodet** [comment]
Keep in mind that Reanimated 2 is currently still in Alpha, and - more importantly - only works on Hermes on Android, which on the other hand currently breaks other packages.

**Comment by nandorojo** [comment]
This would be amazing! Do you expect it for Expo managed, too?

**Comment by tsapeta** [comment]
Closing as it's been already implemented and Reanimated v2 is already included in SDK39 and SDK40
