### ISSUE TITLE
Uncaught Error: Module AppRegistry is not a registered callable module and Uncaught Error: undefined is not an object(evaluating 'r.View.propTypes.style')

### ISSUE THREAD

**Issue by mehtaanshul** [expo/expo#912]
![qq](https://user-images.githubusercontent.com/17105835/32393117-58dde982-c0fe-11e7-8730-d033b04e42e8.jpg)
I am getting these two errors when i use the standalone app on my android device and I am not getting any error when i use the app in expo.

**Comment by EvanBacon** [comment]
This error comes as a breaking change in expo v22. You can read about this and all of our breaking changes on the [expo blog](https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6).

<img width="727" alt="screen shot 2017-11-03 at 4 28 40 pm" src="https://user-images.githubusercontent.com/9664363/32399568-413c13a2-c0b4-11e7-8f87-21df92a2aeb8.png">

**Comment by mehtaanshul** [comment]
I checked and no library is using the old syntax. Please help?

**Comment by ide** [comment]
Either you have a stale cache somewhere or some code is using the old syntax -- it'd be highly unlikely otherwise. Have you grepped every line of code your project could be running?

**Comment by mehtaanshul** [comment]
i followed this guide to clear cache https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352
and Also followed https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6
Still not working?

**Comment by mehtaanshul** [comment]
i have changed View.propTypes.style to ViewPropTypes.style and now i am getting this error ?
![1122](https://user-images.githubusercontent.com/17105835/32407689-804ec7de-c1b2-11e7-9a1e-9877dcdcc0c6.jpg)

**Comment by ide** [comment]
Did you import the variable?

**Comment by mustafaghali** [comment]
this happened for me after upgrading to expo 27.0.0 on production mode only
I tried clearing the packager cache 
npm start --reset-cache 
or  yarn start --reset-cache 
and it seems it solved it for me
