### ISSUE TITLE
[expo-localization] Incompatibility with Jest 26+

### ISSUE THREAD

**Issue by Shizerq** [expo/expo#9120]
### Summary of Issue 
Running unit tests of components, that use expo-localization ends with error caused by removing `require.requireActual`
in Jest 26+  ([facebook/jest/pull/9854]((https://github.com/facebook/jest/pull/9854))
### Steps to Reproduce
Write unit tests with Jest for components, that use expo-localization and simply run them.

### Expected Behavior vs Actual Behavior
Expected: working tests

Actual behavior:
```
  ● Test suite failed to run

    TypeError: require.requireActual is not a function

    > 1 | import * as Localization from "expo-localization";
        | ^

```

**Comment by byCedric** [comment]
Hi @Shizerq, thanks for your issue report. We have [patched the usage of `require.requireActual` in this PR](https://github.com/expo/expo/pull/8347), and should be included in SDK 38. I'm not sure what you are currently using, but upgrading to 38 should fix this for you.

I'm not sure why you get this error in `expo-localization`. The tests in that one shouldn't run in your project. We did have some traces of `require.requireActual` in `jest-expo`, I think that's the origin of your error (but correct me if I'm wrong).

Hope this helps!

**Comment by leonaburime** [comment]
Hi @byCedric, I have the exact same problem and am using "expo": "^38.0.0".  Im trying to run jest tests and installed everything on [this page](https://docs.expo.io/guides/testing-with-jest/)
 
<img width="712" alt="Screen Shot 2020-09-20 at 9 46 42 PM" src="https://user-images.githubusercontent.com/8000641/93733583-ce189e80-fb8a-11ea-9b60-43292d0004cd.png">

What else can I do?
