### ISSUE TITLE
Importing Notifications from 'expo-notifications': Native module cannot be null

### ISSUE THREAD

**Issue by marcusleeeugene** [expo/expo#9121]
Hi I am running expo on my Iphone, 

In my code, `import * as Notifications from 'expo-notifications';` always throws me the following error.
![IMG_564CDBE1C70C-1](https://user-images.githubusercontent.com/19762656/86796414-24ecfc80-c0a1-11ea-8983-04eb9190ad2e.jpeg)

The error message didn't tell me much, but I figured out the the import line was the problem from commenting it out.

I followed the guide in the following link:
https://docs.expo.io/versions/v38.0.0/sdk/notifications/#getexpopushtokenasyncoptions-expotokenoptions-expopushtoken

and am positive i installed correctly using: `expo install expo-notifications`

This is my code for the file I ran:
```
import Constants from 'expo-constants';
import * as Notifications from 'expo-notifications';
import * as Permissions from 'expo-permissions';
import React, { useState, useEffect } from 'react';
import * as firebase from "firebase";
import { Platform } from 'react-native';

registerForPushNotificationsAsync = async () => {
  if (Constants.isDevice) {
    const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
      finalStatus = status;
    }
    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;
    }
    const token = await Notifications.getExpoPushTokenAsync();
    console.log(`ExponentPushToken[${token}]`);
    this.setState({ expoPushToken: token });

  } else {
    alert('Must use physical device for Push Notifications');
  }

  if (Platform.OS === 'android') {
    Notifications.createChannelAndroidAsync('default', {
      name: 'default',
      sound: true,
      priority: 'max',
      vibrate: [0, 250, 250, 250],
    });
  }
};

registerForPushNotificationsAsync();

export default function Notification() {
}

```

**Comment by AdamJNavarro** [comment]
Hey @marcusleeeugene,

What type of Expo project are you running? Also, could you try re-installing the module via `expo install expo-notifications`?

**Comment by cruzach** [comment]
@marcusleeeugene this error indicates you're probably still using SDK 37, which does not contain the native code for `expo-notifications`. Please upgrade your app, or `expo init` new one using SDK 38, and try the same code again. You can also use the [snack](https://docs.expo.io/push-notifications/overview/#example-usage) in our push notification guide to double check

**Comment by marcusleeeugene** [comment]
> @marcusleeeugene this error indicates you're probably still using SDK 37, which does not contain the native code for `expo-notifications`. Please upgrade your app, or `expo init` a new one using SDK 38, and try the same code again. You can also use the [snack](https://docs.expo.io/push-notifications/overview/#example-usage) in our push notification guide to double check
> 
> (we ask for your environment info in the issue template so that identifying cases like a misconfigured SDK version is easier to spot 👍 )

You are right! Upgraded to SDK 38 and it works now! Thank you so much! :)

**Comment by RupamShaw** [comment]
using an existing react-native project for expo-notification that is managed workflow

  "expo": "^38.0.8",
    "expo-constants": "^9.1.1",
    "expo-notifications": "^0.3.3",
    "expo-permissions": "^9.0.1",
   "react-native": "0.61.5",
note: "expo-notifications": "^0.4.0" gives warning on expo start -c --localhost --ios so downgraded it 0.3.3
expo-cli -g --version is 3.22.3

getting error invariant violation: native module cannot be null
