### ISSUE TITLE
[Contacts] Contact.updateContactAsync fails on android

### ISSUE THREAD

**Issue by dor6** [expo/expo#9122]
### Summary of Issue
Contact.updateContactAsync throws an error on android.
The error is "Insert Failed" and some giberish about an unknown error

the function got the following input:
{ 
  "lastName": "Bba", 
  "lookupKey": "0r2701-29292B2B",  
  "name": "Aa Bb", 
  "imageAvailable": false, 
  "contactType": "person", 
  "id": "3583", 
  "firstName": "Aab", 
  "phoneNumbers": [ 
    {  
      "label": "mobile", 
      "type": "2", 
      "id": "17321", 
      "isPrimary": 0, 
      "number": "506856601"
    }
  ]
} 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
android 7, different phones, sdk 38.
on sdk 37 I had a different problem with this, that the contact was duplicated  as described in the issue: https://github.com/expo/expo/issues/8997

### Steps to Reproduce
1. create a contact on your phone with a distinguished name
2. find that contact by getting the cintacts and finding the contact above by name.
3. change first name to something else in the code.
4. use Contacts.updateContactAsync with the updated object from 3.
5. see that an error rises.

**note** : do not use Contacts.addContactAsync to create the new contact becuase in the current version this method have a bug that the id returned is the wrong one. see issue: https://github.com/expo/expo/issues/8961

### Expected Behavior vs Actual Behavior
expected:
Contacts.updateContactAsync will update the contact
actual:
Contacts.updateContactAsync fails.

**Comment by AdamJNavarro** [comment]
Hey @dor6, can you try using `presentFormAsync` as `updateContactAsync` is currently an iOS-only method? https://docs.expo.io/versions/v38.0.0/sdk/contacts/#contactsupdatecontactasynccontact

**Comment by dor6** [comment]
Preset from async opens a menu I need not to open a menu.
On sdk 37 the method worked but duplicated the contact, I referenced the issue that was resolved a few days ago.

**Comment by lukmccall** [comment]
Hi @dor6, this should be fixed by https://github.com/expo/expo/pull/9031.
