### ISSUE TITLE
publish and build of app from expo snacks

### ISSUE THREAD

**Issue by MaheshaBhat** [expo/expo#9123]
Hi,
I want publish and build my application from expo snacks.
please let me know if its possible. if not then please let me know 
if any way to run these commands online.
its urgent issue, looking for any solutions.

**Comment by AdamJNavarro** [comment]
Hey @MaheshaBhat,

In the top right of Snack you'll see an arrow down icon labelled "Download as zip". You'll want to click that to create a local project were you can then configure your `app.json` and do any publish or building actions.

One last note, we try to reserve Github Issues for reproducible and actionable bugs. In the future, if you could direct questions like these to our [Forums](forums.expo.io) that would be greatly appreciated.

Cheers,
Adam

**Comment by MaheshaBhat** [comment]
i wanted to publish app online without downloading it to the local. so is there any this can be done?

**Comment by MaheshaBhat** [comment]
i wanted to publish the app online without downloading it to the local. so is there any way, this can be done?
