### ISSUE TITLE
[SDK 38] expo-notifications works on expo client but not on react native android standalone and playstore

### ISSUE THREAD

**Issue by Alloyce** [expo/expo#9124]
### Summary of Issue 
when running await Notifications.getExpoPushTokenAsync() or await Notifications.getDevicePushTokenAsync() on Expo cli it gets the expo pushtoken, but when I try the same on standalone or the client app on playstore it does not return any token. So I figured it must be related to the package itself expo-notifications since even Notifications.permission behaves the same. The standalone I tried it is through expo build:android.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo SDK 38

### Reproducible Demo
My code that is troubling me is the below:

async function register() {
  let token;
    const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
    let finalStatus = existingStatus;
    if (existingStatus !== 'granted') {
      const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
      finalStatus = status;}

    if (finalStatus !== 'granted') {
      alert('Failed to get push token for push notification!');
      return;}
    token = (await Notifications.getExpoPushTokenAsync()).data;
    global.pushToken = token;
    console.log(token);

  if (Platform.OS === 'android') {
    Notifications.setNotificationChannelAsync('default', {
      name: 'default',
      importance: Notifications.AndroidImportance.MAX,
      vibrationPattern: [0, 250, 250, 250],
      lightColor: '#FF231F7C',
    }); }
  return token;}

 
### Expected Behavior vs Actual Behavior
Pull Expo pushtoken in standalone

**Comment by AdamJNavarro** [comment]
Hey @Alloyce,

Can you make sure you have your FCM credentials properly configured. When testing in the Expo client, it relies on the credentials from the client but once you create a standalone app, you must supply and configure your own. https://docs.expo.io/push-notifications/using-fcm/

Here's another report similar to yours that was due to FCM not being configured. https://github.com/expo/expo/issues/8898

Cheers,
Adam

**Comment by Alloyce** [comment]
Thanks Adam, that solved my problem.
