### ISSUE TITLE
[SDK 38] Google login (Google.logInAsync) redirects to google home page after login in android standalone app

### ISSUE THREAD

**Issue by Alloyce** [expo/expo#9132]
### Summary of Issue 
Googgle Login works well in expo cli, however, in the standalone (expo build:android) and apk installed from playstore, it redirects to the home page after choosing the account and allowing permissions. I tried adding the redireUrl to the code but doesn't work. I am using Google from 'expo-google-app-auth'.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
React Native, Expo SDK 38

### Reproducible Demo

Here is my code:

async googleLogin() {

    try {

      const result = await Google.logInAsync({
        androidClientId: 'mkey',
        iosClientId: 'mkey',
        androidStandaloneAppClientId: `mkey`,
        scopes: ['profile', 'email'],
      });

      if (result.type === 'success') {
        console.log("gmail results" + result.user + result.user.familyName + result.user.email + result.user.photoUrl), 
        return this.social_signup(result.user.givenName, result.user.familyName, result.user.email, result.user.photoUrl, "google_login")
      } else {
        return { cancelled: true };
      }
    } catch (e) {
      return { error: true };
    }

  }

**Comment by byCedric** [comment]
Hi @Alloyce, thanks for the issue report. Did you [follow the steps for Android standalone apps here](https://docs.expo.io/versions/latest/sdk/google/#deploying-to-a-standalone-app-on-android)? If it's working in the Expo Client, but not in a standalone app I think it's related to one (or more) of these steps. The good news here is that your JavaScript should be fine 😄  If you followed these steps, but still doesn't work, could you either provide a small example for this? Without that, I'm not sure what's going wrong.

Hope it helps!

**Comment by Alloyce** [comment]
Hi Cedric, thanks for your reply. Yes I followed those steps and it works till after allowing the app, so it does not return to the app but rather navigates to google.com. Meaning something is not right with the redirectUrl.

**Comment by wata-peter** [comment]
Hi @byCedric,
I also have a similar problem like @Alloyce. Google Login works well in expo cli, but when I got the standalone (expo build:android) and after apk installed from playstore, when I click login button (Google or Apple ID) it does not navigate to Google/Apple's page (Nothing happened).
And I also have followed the steps you mentioned about.
Do you have any advise?

**Comment by elallaouielmehdi** [comment]
Hello everyone, i facing the same issue and as @Alloyce  said i followed the exact steps from the documentation.
it works fine in expo, but when i generate the APK it goes to google.com after login.

**Comment by yaylinda** [comment]
I am actually having the same issue! However, for me, the redirect is not working even when in the Expo Client.

I am running the android emulator using `expo start --android`. Things are working fine in the iOS Simulator within the Expo app though. 

In my signIn config, the redirectUrl is: `redirectUrl: `{packageName}:/oauth2redirect/google`

**Comment by karimcambridge** [comment]
This has been setup since sdk 36 for me, just saying it's not happening on my end ;\. Hope you guys get through

**Comment by Alloyce** [comment]
I actually noticed that the issue was on my package name, it had caps in it, so when I changed it to lower case it is now working. My only problem now is how to lower case the package name on my already published app on Google playstore.

**Comment by karimcambridge** [comment]
> I actually noticed that the issue was on my package name, it had caps in it, so when I changed it to lower case it is now working. My only problem now is how to lower case the package name on my already published app on Google playstore.

Contact play store support and explain to them your issue. They should be able to help you.

**Comment by Alloyce** [comment]
> > I actually noticed that the issue was on my package name, it had caps in it, so when I changed it to lower case it is now working. My only problem now is how to lower case the package name on my already published app on Google playstore.
> 
> Contact play store support and explain to them your issue. They should be able to help you.

Thanks @karimcambridge I already did that, been waiting for feedback from them for 3 days now. Hopefully, they come back to me soon with a solution.

**Comment by oliver-ni** [comment]
I am having the same issue here, but I don't have any upper case letters.

**Comment by doubleh311** [comment]
@Alloyce I encounter the same issue with a live app, package name contains underscore. I have tried some way with a scheme that is the package name that removed underscore, the sign in flow can go back to the app with the scheme but sign in result cannot be resolved. I stills not find out any solution and also mention in this issue #4287. Still waiting for any support from Expo team

**Comment by truonghdpk** [comment]
> @Alloyce I encounter the same issue with a live app, package name contains underscore. I have tried some way with a scheme that is the package name that removed underscore, the sign in flow can go back to the app with the scheme but sign in result cannot be resolved. I stills not find out any solution and also mention in this issue #4287. Still waiting for any support from Expo team

me too

**Comment by basemkhirat** [comment]
Any fixes regarding this issue?

**Comment by oliver-ni** [comment]
My issue was that I had an underscore as well -- making a new app fixed it

**Comment by truonghdpk** [comment]
> My issue was that I had an underscore as well -- making a new app fixed it

really? are u using expo ver 38 or 39

**Comment by doubleh311** [comment]
@truonghdpk you can simply change the packageName to no uppercase and no underscore, follow the instruction, it can work well on the standalone app, but cannot apply this way to a live app

**Comment by taschdo** [comment]
@truonghdpk Good afternoon. I have the same problem. Did you manage to solve it?

**Comment by tslater** [comment]
I'm having the same issue in the managed flow. It works on iOS and did work on android. No uppercase chars or underscores in the name.

**Comment by taschdo** [comment]
@tslater yes, but I have the app already in google play...

**Comment by tslater** [comment]
i'm noticing that I'm seeing it on the android emulator 100% of the time, but not my device. I wonder what the difference is?

**Comment by taschdo** [comment]
@tslater  on the emulator when creating a key in console.developers.google.com is used package name host.exp.exponent, and when Standalone app each package name has its own. I was unlucky and at one time gave the name of the package name with an underscore.

**Comment by AfrozSiddiqui** [comment]
Hi, any fixes regarding this issue? i'm facing the same issue, i didn't use any caps or underscore in my package name...

**Comment by senda-dev** [comment]
Same problem...

**Comment by hirvesh** [comment]
Having the same problem as well, SDK 40.

**Comment by janrider** [comment]
Having the same issue with a redirect to google.com page after loading state on accounts.google.com, but only on Android 8.
It works like expected on Android 9 and above.
It's not about the only standalone app but both: expo client and a standalone app. 
SDK 40

**Comment by guffenix** [comment]
I my case I solve this issue rename the package with the same name with lowercase letter. eg: my.powerfullApp -> **my.powerfullapp** and generate again file google-services.json. It works to me =)

**Comment by fdoyanes** [comment]
I don't even have underscores an uppercase in the name of my package in only some android models it remains in google.com for example the motorola g6

**Comment by roto93** [comment]
Hi, I'm using three real android devices to test my app. One of them faces this problem.
And I have checked my package name all lower cases.

I'm using Expo SDK 40

After trying for hours I finally redirect to my app right after choosing account in accounts.google.com by simply **update the chrome app** in my phone from _ver.61_ -> _ver.89_ (latest)

Not sure if it is the main problem but still worth a try:) 
Also make sure that you're using the latest Android version.

**Comment by travishoki** [comment]
In the Android standalone app, after a successful login it basically just refreshes the login page. It doesn’t return to the app, I’m just stuck logging in again. Anyone experiencing this or know how to fix it?
