### ISSUE TITLE
Standalone Release app in iOS hangs on white loading screen on launch

### ISSUE THREAD

**Issue by fooshyangsong** [expo/expo#9133]
### Summary of Issue 
My app had been rejected by Expo due to the reason, the app stuck at white screen with a loading indicator on top.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
iOS Standalone, im using expo to build and upload my iPad to Apple. Expo CLI 3.22 

app.json
{
  "expo": {
    "name": "xxxxxxxxx",
    "androidStatusBar": {
      "backgroundColor": "#000000"
    },
    "slug": "xxxxxxxxxxxxxxxx",
    "privacy": "public",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.6",
    "orientation": "portrait",
    "icon": "./assets/IconApp.png",
    "splash": {
      "image": "./assets/splashscreen.png",
      "resizeMode": "contain"
    },
    "updates": {
      "enabled": false,
      "checkAutomatically": "ON_ERROR_RECOVERY",
      "fallbackToCacheTimeout": 1
    },
    "assetBundlePatterns": [
      "assets/images/*",
      "assets/icons/*",
      "assets/*",
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "xxxxxxxxxxxxxxxxx",
      "buildNumber": "1.0.6",
      "supportsTablet": false,
      "loadJSInBackgroundExperimental": true,
      "infoPlist": {
        "NSCameraUsageDescription": "This app uses the camera to scan QR Code on product purchased.",
        "userInterfaceStyle": "light"
      }
    },
    "android": {
      "package": "xxxxxxxxxxxxx,
      "googleServicesFile": "./google-services.json",
      "versionCode": 6,
      "adaptiveIcon": {
        "foregroundImage": "./assets/IconApp.png"
      }
    },
    "description": ""
  }
}

package.json

dependencies": {
    "@pusher/chatkit-client": "^1.13.2",
    "@react-native-community/datetimepicker": "2.2.2",
    "@react-native-community/netinfo": "5.5.1",
    "expo": "~37.0.3",
    "expo-asset": "~8.1.5",
    "expo-barcode-scanner": "~8.1.0",
    "expo-linear-gradient": "~8.1.0",
    "moment": "^2.24.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-animatable": "^1.3.3"
}

### Reproducible Demo
[https://ibb.co/wpqcW89](url)

 
### Steps to Reproduce
Turn on airplane mode before opening the test flight app.

### Expected Behavior vs Actual Behavior
I had try to add in offline support by bundle my asset, change updates.enables = false  in app.json. I am still getting a white screen in a  my new version, the actual result should be showing a login screen.

**Comment by cruzach** [comment]
Hi! We have a guide on debugging standalone issues like this [here](https://docs.expo.io/workflow/debugging/#production-errors). I would go through your native device logs to see if you can get some useful information from there, and then provide it in your issue

Note that after changing any `updates` keys in app.json, you'll need to rebuild the app with `expo build:ios`, not just run `expo publish`
