### ISSUE TITLE
MapView from react-native-maps crushing when ran on APK. 

### ISSUE THREAD

**Issue by kub1x** [expo/expo#9136]
## 🐛 Bug Report
Expo app with only single component `<MapView />` runs normally in Expo client with js sources fetched from server and from console, but when built into APK it crashes every time. 

I've made this version https://github.com/kub1x/expo-maps-repro with just the one MapView compnent. It freezes on splashscreen. 

When MapView is on next screen of react-navigations `bottomTabView` the app crashes (restarts) when user switches to the screen with MapView, it freezes when user clicks the button again after restart. 

Tried with SDK v38, but it happened exactly the same way in v37. 

I've also put all info to react-native-maps repo, but it might be an Expo problem. 
https://github.com/react-native-community/react-native-maps/issues/3477

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
% expo diagnostics
  Expo CLI 3.22.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.0
```

### Reproducible Demo

These are all the same thing: 

* https://github.com/kub1x/expo-maps-repro
* this works in expo client: https://expo.io/@cedule/maps-repro
* this fails on Android device: https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40cedule/maps-repro-6e06507b33c14bfbbc4ed4d55485a1c1-signed.apk

### Steps to Reproduce
Just run the apk. 

### Expected Behavior vs Actual Behavior
No crash.

**Comment by byCedric** [comment]
Hi @kub1x, thanks for the issue report and example! I can see that you are using the correct `react-native-maps` version for the SDK, and everything else looks pretty good. I did notice there is no configuration for standalone builds (like `android.config.googleMaps.apiKey`), [have you followed the steps listed here](https://docs.expo.io/versions/latest/sdk/map-view/#deploying-to-a-standalone-app-on-android)? If not, that's probably the cause why it works in the Expo Client but not in a standalone build.

Hope this helps!

**Comment by kub1x** [comment]
@byCedric Hey, you're right! It looks like it helped. Seeing the `react-native-maps` package to _just work_ in Expo client probably made me not even look for those additional steps, just used the packages docs. 

Still though, crashing the whole app because of a missing field in config seems a bit lot and would've never searched for such kind of error. It feels like an exception should've been caught somewhere and red banner presented to user/tester/developer in place of the map component or something. Not complaining, just a feedback. 

Anyway, thank you very very much for getting me back on track. I was ripping my hair on this.

**Comment by tsapeta** [comment]
> Still though, crashing the whole app because of a missing field in config seems a bit lot and would've never searched for such kind of error. It feels like an exception should've been caught somewhere and red banner presented to user/tester/developer in place of the map component or something. Not complaining, just a feedback.

We as a team are not the owners of `react-native-maps` module where such check for missing api key should be added, but we will try to do something with this.
