### ISSUE TITLE
BasCodeScanner camera view freezes

### ISSUE THREAD

**Issue by bsgbryan** [expo/expo#9139]
### Summary of Issue

1. Create two components that use BarCodeScanner (A and B)
1. Navigate between components: A -> B, then B -> A
1. Camera view in component A is frozen
1. Navigating back to component B, camera view is not frozen
1. Navigating between components, behavior is consistent: camera in component A is frozen, camera in component B is not frozen

### Environment

```
Expo CLI 3.21.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.9
```

**Platforms**:

iOS: **exhibits issue**
physical devices tested:

* iPhone Xs Max: _iOS 13.5.1_

Android: **does not exhibit issue**
physical devices tested:

* Samsung Galaxy A10s: _Android 10, patch level March 1st, 2020_
* Google Pixel3: _Android 10, build number QQ3A.200605.002_

### Reproducible Demo

This [Snack](https://snack.expo.io/@bsgbryan/barcodescanner-camera-freezes)
 
### Steps to Reproduce

1. Tap A
1. Tab B
1. Tap A

### Expected Behavior vs Actual Behavior

**Expected Behavior**

Camera in Tab A does not freeze

**Actual Behavior**

Camera in Tab A freezes

**Comment by OscarYuen** [comment]
According to Camera Doc,
only one active Camera preview is supported currently. When using navigation, the best practice is to unmount previously rendered Camera component so next screens can use camera without issues.

I think it also applied to BarCodeScanner

**Comment by cruzach** [comment]
I'm not sure if this is the same case as with `expo-camera`, since the camera behavior is the same on iOS and Android and this is just happening on iOS for barcode-scanner

**Comment by bsgbryan** [comment]
My code, the snack code, and the documentation code for BarCodeScanner, all use functional components - so mount/unmount happens automatically and is guaranteed.

I'm unclear as to what more info is needed.

**Comment by cruzach** [comment]
> mount/unmount happens automatically and is guaranteed 

I'm not sure this is true, since if I replace the `BarcodeScanner` components in the snack with `Camera` components, the same issue occurs

**Comment by OscarYuen** [comment]
According to life cycle from react-navigation(https://reactnavigation.org/docs/navigation-lifecycle/),  A is still mounted when tab B is being navigated. You could also confirm it by using cleanup function in useEffect hook to see cleanup function is called in A when navigation to B from A. 

I made it a little experiment on your snack by adding useFocusEffect hook to unmount Barcode component manually. The camera would not freeze.
https://snack.expo.io/@oscaryuen/barcodescanner-camera-freezes

**Comment by bsgbryan** [comment]
I'm really sorry it's taken me so long to respond.

Thank you for updating the docs! Hopefully this will save people some confusion 😄

I can confirm that your workaround works - neither scanner freezes anymore! 🥳

Thanks again for your help on this.

**Comment by developius** [comment]
For anyone who arrived here after their scanner view froze after leaving the app & returning (e.g. Linking.openURL), this solution here worked for me (React Navigation): https://github.com/expo/expo/issues/9619#issuecomment-1018179868
