### ISSUE TITLE
simulator stuck on white screen ( no loading indicator ) 

### ISSUE THREAD

**Issue by jpca999** [expo/expo#914]
Loading come but after a long time... 7-9 seconds. 

<img width="384" alt="screen shot 2017-11-04 at 1 42 53 pm" src="https://user-images.githubusercontent.com/1026325/32407952-876b3f44-c166-11e7-9280-b2fd2d7bc4b4.png">

    "sdkVersion": "21.0.0",

**Comment by dikaiosune** [comment]
Can you provide some more information about your environment? What OS version? What simulator version? Is this a fresh install of the Expo client app on your simulator?

**Comment by jpca999** [comment]
![image](https://user-images.githubusercontent.com/1026325/32460863-1c1d3448-c302-11e7-861e-38660aa2d3bb.png)

![image](https://user-images.githubusercontent.com/1026325/32460929-55401056-c302-11e7-9ded-ecffee6e7655.png)

![image](https://user-images.githubusercontent.com/1026325/32460971-6e1bc00c-c302-11e7-819d-fadadbd1f35b.png)


Yes i installed it fresh,

**Comment by terribleben** [comment]
If it hangs on that screen for a few seconds before the loading indicator appears, that's just your simulator/springboard agent being slow to open the app. The Xcode 9 tooling seems to be pretty slow at launching apps. Sorry but there's not a ton we can do about this.
