### ISSUE TITLE
[docs] Keep 3rd party documentation and versions in SDK in sync

### ISSUE THREAD

**Issue by byCedric** [expo/expo#9142]
Right now it's hard for us to keep the documentation for 3rd party libraries in sync.

- Links might point to newer versions of the library, causing developer confusion
- No way of detecting/fixing these pages for us

**Potential fixes**

- Link to versioned 3rd docs (e.g. by tag or commit) 
- Add meta info to the docs and compare it with `bundledNativeModules.json`
- Expand `et update-vendor-module` to update or warn about outdated docs

**Comment by expjess** [comment]
Is there also a workaround where we at least expose the conflict? Or would the way we print "version in SDK" info require just as much remembering/work as simply updating the documentation to match?

**Comment by byCedric** [comment]
Right now I don't think we have something to detect or expose these conflicts. We do know the versions bundled in specific SDK versions, using the `expo/bundledNativeModules.json`. But we don't know the versions within the SDK documentation pages. So I guess we have to fix that first 😄 

I think adding meta info like `externalLibrary: @react-native-community/netinfo@5.x.x` would be the best approach for now. With that we can pinpoint the exact node module and version used in the documentation, and detect those mismatches. We can also add a component that renders a block with "This depends on the external library `@react-native-community/netinfo`, version `5.x.x` 😄
