### ISSUE TITLE
Speech.speak Unhandled promise rejection

### ISSUE THREAD

**Issue by albertcito** [expo/expo#9143]
### Summary of Issue 
- Different audios are reproduced in different screens (using [react-navigation/native](https://reactnavigation.org/)), but after the to reproduce many kinds of audios, it shown a warning.
- It's a warning that appears only in **Android**.
- After the warning is shown, the Speech.speak doesn't works anymore.

### Environment

> Expo CLI 3.22.0 environment info:
>     System:
>       OS: macOS 10.15.5
>       Shell: 5.7.1 - /bin/zsh
>     Binaries:
>       Node: 12.16.3 - /usr/local/bin/node
>       Yarn: 1.22.4 - ~/.yarn/bin/yarn
>       npm: 6.14.4 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     IDEs:
>       Android Studio: 3.1 AI-173.4697961
>       Xcode: 11.5/11E608c - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ~37.0.3 => 37.0.11 
>       react: ~16.9.0 => 16.9.0 
>       react-dom: ~16.9.0 => 16.9.0 
>       react-native: ~0.61.5 => 0.61.5 
>       react-native-web: ~0.11.7 => 0.11.7 
>     npmGlobalPackages:
>       expo-cli: 3.22.0

### Reproducible Demo
Unfortunately I tried to replicate it, but I been not able to do it with a simple app code. I added try catch, but in any case I cannot to catch the warning event. 

## Warning from console

> [Unhandled promise rejection: Error: d.h.b.c.j0.n$b: AudioTrack init failed: 0, Config(44100, 12, 56704)]
> 
> Stack trace:
>   node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:99:50 in fn
>   node_modules/@unimodules/react-native-adapter/build/NativeModulesProxy.js:15:46 in moduleName.methodInfo.name
>   http://192.168.1.6:19001/index.bundle?platform=android&dev=true&minify=false&hot=false:173314:51 in <unknown>
>   node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
>   node_modules/promise/setimmediate/core.js:200:23 in doResolve
>   node_modules/promise/setimmediate/core.js:66:12 in Promise
>   node_modules/expo-av/build/Audio/Sound.js:89:34 in loadAsync
>   node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
>   node_modules/regenerator-runtime/runtime.js:274:30 in invoke
>   node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
>   node_modules/regenerator-runtime/runtime.js:135:28 in invoke
>   node_modules/regenerator-runtime/runtime.js:145:19 in PromiseImpl.resolve.then$argument_0
>   node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
>   node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
>   node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
>   node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
>   node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
>   [native code]:null in callImmediates
>   node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
>   node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
>   node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
>   node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
>   [native code]:null in flushedQueue
>   [native code]:null in callFunctionReturnFlushedQueue
>   ...

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by brentvatne** [comment]
- are you using a video player in your app anywhere?
- are you using any other kind of audio?
