### ISSUE TITLE
Full (system) brightness on OnePlus 6 is only 40%

### ISSUE THREAD

**Issue by byCedric** [expo/expo#9152]
### Summary of Issue 

When setting the system brightness to 100%, on a OnePlus 6, I only get ±40% of screen brightness.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

SDK 38, on Android 10 (OnePlus 6)

```
  Expo CLI 3.22.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
```

### Reproducible Demo

See [this snack](https://snack.expo.io/@bycedric/brightness-oneplus-6-issue).
 
### Steps to Reproduce

See video below

### Expected Behavior vs Actual Behavior

> If I set the brightness above `1` (e.g. `4`), there is no difference.

![ezgif-3-37d4493bbf6a](https://user-images.githubusercontent.com/1203991/87046408-74ded700-c1f9-11ea-9964-a9dfac6890df.gif)

**Comment by alextselegidis** [comment]
I have the same problem (Xiaomi Mi 10T)

```
 Expo CLI 4.12.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```
