### ISSUE TITLE
Can't change option for sound and vibration on scheduleNotificationAsync from expo-notifications

### ISSUE THREAD

**Issue by Danielgb23** [expo/expo#9155]
### Summary of Issue 
When I change the options for vibration or sound in the scheduleNotificationAsync function data like using 'sound:false' in the input object. The notification always plays the sound and vibrates irregardless of the input.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
I am using expo in bare workflow that has been ejected and android to test it.

### Reproducible Demo
That's how I implemented it:
```
      <Button
        title="Press to Send timed Notification"
        onPress={async () => {

          await Notifications.scheduleNotificationAsync({
  content: {
    title: "Time's up!",
    body: 'Change sides!',
    sound:false,
    vibrate: false,

  },
  trigger:{ 
  hour: 0,
  minute: 23,
  repeats: true,
  }
  
});

        }}
      />
```

 
### Steps to Reproduce
Execute the code above in an android phone with the expo emulator

### Expected Behavior vs Actual Behavior
I using the code above it should play no sound and not vibrate. Though it does.

**Comment by lukmccall** [comment]
Hi @Danielgb23, the `vibrate` parameter doesn't receive a boolean value. However, when you pass an empty array, it doesn't work either. I will look closely to this issue ;)

**Comment by Danielgb23** [comment]
but isn't it what it says here? https://docs.expo.io/versions/latest/sdk/notifications/#notificationcontentinput
```
export interface NotificationContentInput {
...
 sound?: boolean | string;
  // Android-specific fields
  // See https://developer.android.com/reference/android/app/Notification.html#fields
  // for more information on specific fields.
  vibrate?: boolean | number[];
...
```

**Comment by lukmccall** [comment]
Oh, you are right 👍  I was looking at ts types. 

However, I know the root cause of this problem. I will fix it soon ;)

**Comment by Danielgb23** [comment]
Good, thanks a lot for your attention! :)

**Comment by MaHermes** [comment]
Vibrate seems to be inverted? If I set it to true theres so vibration, false will cause vibration.

I additionally have the problem that my vibration pattern (setting vibrate: [0,200,100,500]) is ignored.

Thanks for having a look :)
