### ISSUE TITLE
Expo SDK 38: Unable to resolve module from symlinked local dependency

### ISSUE THREAD

**Issue by netpoe** [expo/expo#9156]
### Summary of Issue 

I started my app with managed workflow with Expo SDK 37 and a monorepo managed by lerna. Everything was working fine with local dependencies imports. I updated to Expo SDK 38 this week and now I get: 

<img width="376" alt="Screen Shot 2020-07-09 at 16 13 29" src="https://user-images.githubusercontent.com/4053518/87096040-2cc2b300-c1ff-11ea-8711-79b44a25d885.png">

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
expo diagnostics

  Expo CLI 3.22.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.0/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.22.1
```

### Reproducible Demo

https://github.com/netpoe/expo-sdk-38-test
 
### Steps to Reproduce

`expo start -c`

### Expected Behavior vs Actual Behavior

I expect the bundler to start the app, but it shows the error screen.

**Comment by byCedric** [comment]
Hi @netpoe, thanks for the issue report and repro! In general, using symlinks is not the best solution for Metro. Officially they don't support symlinks. When you upgraded to SDK 38 you also upgraded Metro, this could include the removal of experimental features related to that. Luckily, there is a way to run your monorepo with the structure you want 😄 

We have a library called [`expo-yarn-workspaces`](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces), we use it to power the expo/expo monorepo. You can use it yourself as well. I just created a PR to your repro that includes this and runs without issues. Please, do let us know if this doesn't work for you in your original project!

Hope this helps!

**Comment by netpoe** [comment]
> Hi @netpoe, thanks for the issue report and repro! In general, using symlinks is not the best solution for Metro. Officially they don't support symlinks. When you upgraded to SDK 38 you also upgraded Metro, this could include the removal of experimental features related to that. Luckily, there is a way to run your monorepo with the structure you want 😄
> 
> We have a library called [`expo-yarn-workspaces`](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces), we use it to power the expo/expo monorepo. You can use it yourself as well. I just [created a PR to your repro](https://github.com/netpoe/expo-sdk-38-test/pull/1) that includes this and runs without issues. Please, do let us know if this doesn't work for you in your original project!
> 
> Hope this helps!

@byCedric thank you very much.
Your solution worked very well with the test project. I pulled your PR, ran `lerna boostrap`, `expo start -c` and opened the project from metro in an iOS simulator without trouble. 

However, applying your changes to my real project, brought new problems: 

<img width="1440" alt="Screen Shot 2020-07-11 at 22 52 29" src="https://user-images.githubusercontent.com/4053518/87239174-3b5cc600-c3c9-11ea-900a-be810d456ba8.png">

I already ran `watchman watch-del-all`, `lerna clean`, `rm -rf /tmp/-metro-*`, etc. With no success. 

I added the config as specified in [expo-yarn-workspaces](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces) and the `main` path ended up being `.expo/AppEntry.js` (also tried with `__generated__/AppEntry.js`. The `postinstall` script is also in place. 

What could be the reason of the error here?

Thanks in advance. I appreciate your help.

**Comment by byCedric** [comment]
I'm not exactly sure, monorepos are a complex piece of tech and there are a lot of things that might go wrong. Are you able to temporarily give me access so I can check it out? I don't think it's something related to `expo-yarn-workspaces` because the expo/expo repo is doing just fine. But I want to see if we need to document other stuff that's going wrong.

You can ping me on the Expo community slack, search for `@bycedric` you should see me 😄

**Comment by netpoe** [comment]
> @netpoe I'm not exactly sure, monorepos are a complex piece of tech and there are a lot of things that might go wrong. Are you able to temporarily give me access so I can check it out? I don't think it's something related to `expo-yarn-workspaces` because the expo/expo repo is doing just fine. But I want to see if we need to document other stuff that's going wrong.
> 
> You can ping me on the [Expo community slack](https://slack.expo.io/), search for `@bycedric` you should see me 😄

Hi @byCedric thanks for following-up on this. 
Unfortunately I cannot give you access to the private repo. However, I was able to keep SDK 38 by pulling extensions from the npm registry, so `expo-yarn-workspaces` is no longer necessary :/
