### ISSUE TITLE
Module HMRClient is not a registered callable module (calling enable)

### ISSUE THREAD

**Issue by danstepanov** [expo/expo#916]
After upgrading to Expo SDK 22.0.0 per [the blog post](https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6), I run into this error while running the app in the simulator with hot reloading enabled. I use yarn and ran `yarn cache clean` prior to starting the server.
<img width="424" alt="screen shot 2017-11-04 at 12 25 52 pm" src="https://user-images.githubusercontent.com/5482800/32410174-df865dce-c190-11e7-8b05-db77b108a36a.png">

**Workaround:** After toggling remote debugging, the issue seems to go away and hot reloading seems to work just fine.

**Comment by orloffmarket** [comment]
I am getting this issue for published builds after going to SDK 22 and reverting back to 21, still get it.

**Comment by terribleben** [comment]
Hi, HMR works for me if I download the Expo SDK 22 tabs template, enable HMR, and start changing things. The changes are reflected in my simulator/device as expected. Is it possible for you to provide a repro project?

**Comment by danstepanov** [comment]
@terribleben I am no longer having this issue

**Comment by dikaiosune** [comment]
@orloffmarket what's the URL you published to? I'm surprised HMR is ending up in your production bundle.

**Comment by orloffmarket** [comment]
no you are correct, my issue is Module AppRegistry is not a registered callable

**Comment by dikaiosune** [comment]
@orloffmarket could you open a separate issue if you're still having this problem? Thanks!

**Comment by orloffmarket** [comment]
My issue is resolved, it was due to SDK 22 updates and not related to this. Thanks

**Comment by Irosshipaz** [comment]
I'm facing this problem right now, only on iOS, just after publish an application. Don't know what's happening.

**Comment by Awais00094** [comment]
just add in index.ios.js
var RCTLog = require('RCTLog');

**Comment by anp** [comment]
@Irosshipaz you can run your code locally the same way it happens when published by turning dev mode off. You should be able to reproduce the problem there, and you can look into version mismatches or other potential causes.

**Comment by ishraqe** [comment]
facing this issue when running my android project...

**Comment by ide** [comment]
"X is not a registered callable module" happens when the native side of React Native tries to invoke a method of a JS module that hasn't been loaded. One reason this can happen is if your bundle fails to load e.g. because of a syntax error in it, or a JS error that happens early on during module initialization. This is something that tends to be different to each specific project and debugged individually.

**Comment by ermarkar** [comment]
any solution to this?

**Comment by himanshuagrawal5947** [comment]
It works fine for me after enabling "hot reloading" can try the same.

**Comment by ITsolution-git** [comment]
Is there any solution to solve this issue?
What is this problem mainly related.

Anyone please help me. Thank you in advance.

**Comment by brentvatne** [comment]
`rm -rf node_modules && rm yarn.lock && rm package-lock.json && yarn`

**Comment by otaviogaiao** [comment]
I'm having the same issue when running my app on my iPhone with development mode off.  I tried removing my node_modules component many times, I cleaned the yarn cache and reload watchman. Nothing worked.

My package.json file is as follow:
```
{
  "name": "comissarios-react",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-eslint": "^8.2.2",
    "eslint": "^4.18.2",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0",
    "jest-expo": "^25.0.0",
    "prettier-eslint": "^8.8.1",
    "react-native-scripts": "1.8.1",
    "react-test-renderer": "16.0.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "axios": "^0.17.1",
    "date-fns": "v2.0.0-alpha.7",
    "expo": "^25.0.0",
    "promise": "^8.0.1",
    "prop-types": "^15.6.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-modal": "^5.0.0",
    "react-navigation": "^1.4.0",
    "react-navigation-redux-helpers": "^1.0.1",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }
}

```

**Comment by otaviogaiao** [comment]
Any Idea @brentvatne ?

**Comment by Demuzx** [comment]
Just open "Dev Settings" and set "JS Dev Mode to true". It works for me.

**Comment by bishoymelek** [comment]
cd android && ./gradlew clean
 then cd .. && react-native run-android

**Comment by nosykretts** [comment]
This error happen when I try runnng expo in dev mode ```exp start``` after checking out performance mode with ```exp start --no-dev```.

So if you need development mode back. ```exp start``` not enough. Need to force with ```exp start --dev``` then error is gone.

**Comment by Fea-Sin** [comment]
open "Dev setting" and reset "JS Dev Mode" is true，it works

**Comment by thevaleriemack** [comment]
If you got this error when trying to test with expo metro bundler in "production mode", switch back to dev mode and turn off hot reloading and live reload. Then try again in production mode and it should work fine.

**Comment by ManigandanRaamanathan** [comment]
Disable hot reloading, it will work fine

**Comment by esdrasevt** [comment]
I was having the same problem and solved it by stopping the npm packager, deleting the Expo app from the iPhone simulator and running the packager again on the simulator (which made it install the latest version of the Expo app).

**Comment by AkshayBaldia** [comment]
This has a simple solution. Just uninstall the current app from device and install again.

**Comment by daniel** [comment]
I have started getting this error when I start a published app or run the app in production mode locally. Haven't seen this before, but I recently upgraded a few npm packages so I'm suspecting it might have something to do with that.

**Comment by mulholio** [comment]
The hot module reloading options were disabled for me. Turned out my error was that I had accidentally switched production mode on in my Development Tools browser tab. Simply turning off and restarting the server fixed the issue.

![image](https://user-images.githubusercontent.com/20966690/57972694-e6284e80-7995-11e9-8949-72e370eacc59.png)
