### ISSUE TITLE
Getting a "not a system font" error for using an icon from react-native-elements

### ISSUE THREAD

**Issue by bchehraz** [expo/expo#917]
What happens is:

1. Red screen happens on initial run
2. When I dismiss it, it shows what it rendered but it shows a random icon (Chinese character)

console.error:  "fontFamily 'MaterialIcons' is not a system font and has not been loaded through Expo.Font.loadAsync.
- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
- If this is a custom font, be sure to load it with Expo.Font.loadAsync"

Dependencies- I haven't yet cleaned it up (sorry):

`  "dependencies": {
    "expo": "^22.0.0",
    "jest": "^21.2.1",
    "npm": "^4.4.3",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",
    "react-native-elements": "^0.17.0",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.19",
    "react-redux": "^5.0.6",
    "react-test-renderer": "16.0.0",
    "redux": "^3.7.2"
  },`

  `"devDependencies": {
    "babel-jest": "^21.2.0",
    "babel-preset-react-native": "^4.0.0",
    "blanket": "^1.2.3",
    "eslint-config-rallycoding": "^3.2.0",
    "eslint-plugin-jest": "^21.2.0",
    "expo": "^22.0.1",
    "jest": "^21.2.1",
    "jest-cli": "^21.2.1",
    "jest-expo": "^22.0.1-SNAPSHOT.2017.11.1",
    "react-dom": "16.0.0",
    "regenerator-runtime": "^0.11.0"
  }`

Component that is causing the problem- it's a tiny app at the moment. This worked a couple of days ago before I started configuring jest and snapshot testing. 

`import React, { Component } from 'react';
import { View } from 'react-native';
import { Icon } from 'react-native-elements';`

`class MapScreen extends Component {`

`  static navigationOptions = () => ({`
`    tabBarLabel: 'Map',`
`    tabBarIcon: ({ tintColor }) => (`
`      <Icon name="location" size={30} color={tintColor} />`
`    )`
`  })`
`...`

Any ideas on the issue?

Thank you!

**Comment by bchehraz** [comment]
Update:
If I remove react-native-vector-icons (which it says not to add as a dependency in the first place, but I had it for whatever reason), instead of the error showing up after the app ran on the phone, it doesn't run at all and shows the very same error. Interesting.. It seems like something is definitely messed up with my dependencies. I wish I read the documentation first :(

**Comment by brentvatne** [comment]
hey @bchehraz! sorry you ran into issues, that sounds frustrating. I'm not sure I totally follow what happened though. could you share a small project on Github that reproduces the same problem? :)

**Comment by bchehraz** [comment]
Thank you for the response. Here is the conclusion I came to while attempting to re-produce the problem (since re-producing the problem ended up working and not failing): _Is it possible that creating an Expo app with the XDE, deleting node_modules, and running "npm install" creates a different set of dependencies than if you simply created the Expo app without ever deleting node_modules? If so, this is the only explanation I can think of for why my problem occurred in the first place..._

Here are the steps I took upon trying to reproduce the problem:

1. Created a _new_ Expo project using Expo XDE
2. Added dependencies until the same code worked, which it did (_along with jest to make sure snapshot tests still run when using "npm test"_)
3. Copied the dependencies from the _new_ project to the _old_ project
4. Deleted node_modules and ran "npm install" inside the _old_ project directory, to try and make sure the dependencies installed
5. The _old_ project still failed at this point in time.
6. Then I realized that there was _one missing item_ that was the only thing different from the _old_ project, inside .babelrc of the _new_ project:

`"presets": ["babel-preset-expo"],`

However, making this change to the _old_ project in .babelrc caused an error, saying that the "babel-preset-expo" didn't exist. Found out that you can install it through npm... And doing so did _not_ solve my problem.

How is this possible?

**Comment by bchehraz** [comment]
Update:
I took the node modules from the _new_ project and added to the _old_ project...

**_The original project works now!!_**

**Comment by dikaiosune** [comment]
Glad to hear this is resolved!

**Comment by EndiGlavinic** [comment]
I had quite simmilar problem.
I installed test expo envirnoment with `exp init my-new-project` and after 2 days of working I run `npm install smth_i_dont_remember --s` which caused deletion of many files and installing new one...

**Comment by kevin-williams** [comment]
After cobbling together bits and pieces on loading the icons for react-native-elements I finally figured this out. Check out my blog for a write-up.
https://javascriptrambling.blogspot.com/2018/03/expo-icon-fonts-with-react-native-and.html
