### ISSUE TITLE
Reading pdf417 with expo barcode scaner does not return correct data

### ISSUE THREAD

**Issue by 1099366461** [expo/expo#9176]
## 🐛 Bug Report

reading pdf417 with expo barcode scaner does not return correct data

Expo barcode scaner

### Reproducible Demo

it is required to read the barcode pdf417 that is in the Colombian ID, it is done with the example of expo

https://snack.expo.io/?platform=android&name=Basic%20BarCodeScanner%20usage&sdkVersion=38.0.0&dependencies=expo-barcode-scanner&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv38.0.0%2Fbar-code-scanner.js
 
### Expected Behavior vs Actual Behavior

it is expected to open the scanner to obtain the data contained in the pdf417 barcode.

the result at the moment is a string like this: 0327036620

**Comment by AdamJNavarro** [comment]
Hey @1099366461,

I've been unable to reproduce this behavior on both Android and iOS. Can you share what platform you're encountering this on and what barcode you are scanning to test with?
  
![Barcode](https://user-images.githubusercontent.com/8992878/87451951-39138b00-c5c6-11ea-84ad-03bdffc61ac9.jpg)

![BarcodeScan](https://user-images.githubusercontent.com/8992878/87452051-5b0d0d80-c5c6-11ea-91db-ac638caae14a.PNG)

**Comment by 1099366461** [comment]
Thanks for the reply,
I am trying to scan the barcode found on the Colombian ID.

Attachment 3 example of identifications.

![barcode](https://user-images.githubusercontent.com/68158747/87483119-8ad50900-c5f8-11ea-9750-7233c870e312.jpg)

**Comment by brentvatne** [comment]
hello! see this response: https://github.com/expo/expo/issues/9233#issuecomment-658941249
