### ISSUE TITLE
Can't deploy detached expo project with native library

### ISSUE THREAD

**Issue by fcaride** [expo/expo#918]
I am trying to deploy on testflight a detached Expo project by uploading it to the appstore via XCode. This project has a native library added in the xcode after detached it with expo. When i run the  downloaded app on my phone and  tries to use any native library, it crashes with the following error:

undefined is not an object (evaluating "native function’s name" (code 1)

The app works fine in the local environment.

Does anyone know how to do this?. I want to use Expo, but if I can't fix this, I'll have to go with react-native alone.
How do i should deploy a detached project?  I read all the documentation and i didnt found anything :(

Thanks!

**Comment by brentvatne** [comment]
this issue was resolved by @fcaride -- he wasn't publishing the app so it was using an old version of js which, if I understand correctly, was calling into a different native api

**Comment by fcaride** [comment]
Yes its documented. My bad haha
