### ISSUE TITLE
Standalone doesn't update on launch. It fetches the update, but requires the user to close and reopen the app to see the changes.

### ISSUE THREAD

**Issue by zholmes1** [expo/expo#9182]
### Summary of Issue 

When I make a publish, wait a few minutes, then open my standalone app (fresh launch where I can see the splash screen), I find that I am still in the old version of the app. If I close out the app and relaunch it, then I will be in the updated version.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.22.1 environment info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.16.1 - /usr/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.4 - /usr/bin/npm
    npmPackages:
      expo: ^38.0.0 => 38.0.3 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7

Targeting Android, iOS

### Steps to Reproduce

1. Close standalone app
2. Publish new version with `expo publish`
3. Wait 2 minutes
4. Open standalone app
5. Notice that I am still in the old version
6. Close standalone app
7. Open standalone app
8. Notice that I am in the new version

### Expected Behavior vs Actual Behavior

Expected Behavior:

I think that Expo should absolutely reload the newest version of the app from the splash screen instead of only downloading it and waiting for the user to relaunch the app. It's not a big deal for a user that has been using the app for a while, but it is a big deal for brand new users. We are asking them to either use a potentially very outdated version of the app for their first use. Then the next time they open the app, it may look very different. Alternatively, we could ask the user to reload the app depending on the results of Updates.checkForUpdatesAsync() or Updates.fetchUpdatesAsync(). I don't think that asking a user to reload to apply updates on their very first launch of the app is good UX.

I tried to write a piece of code like this in my AppLoading.startAsync

```
if (!__DEV__) {
  try {
    const checkResult = await Updates.checkForUpdateAsync()
    if (checkResult.isAvailable) {
      const fetchResult = await Updates.fetchUpdateAsync()
      if (fetchResult.isNew) {
        Updates.reloadAsync()
      }
    }
  } catch (e) {
    console.error(e)
  }
}
```

Unfortunately `Updates.reloadAsync()` seems to do nothing in this early stage of launching the app.

**Comment by cruzach** [comment]
Hey @zholmes1 , good news is you can configure the exact behavior you want your OTA updates to exhibit! For instance, you can set a longer timeout (app.json `updates. fallbackToCacheTimeout`) so that your users will most likely get the most recent bundle. You can also disable automatic automatic updates and instead write your own update-handling code with the `expo-updates` module- https://docs.expo.io/versions/latest/sdk/updates/

> Unfortunately Updates.reloadAsync() seems to do nothing in this early stage of launching the app.

`Updates.reloadAsync()` is an async function so you need to `await` it

**Comment by zholmes1** [comment]
@cruzach That's great. I set the fallback timeout to 15000 and when I launch the APK, I now get the newest version. This is exactly what I wanted. I really think you should consider making something like that the default rather than 0. I figured 0 meant that there was no timeout, and it would just wait until it got a new version

**Comment by cruzach** [comment]
Glad that worked for you! And we'll think about that, but the current default is what most folks go with so changing that behavior isn't very likely for now

> I figured 0 meant that there was no timeout

0 means the timeout is literally 0 seconds, AKA it will instantly go towards loading the app. This is explained in the [docs](https://docs.expo.io/guides/configuring-ota-updates/#automatic-updates)
