### ISSUE TITLE
Help with sending expo-camera image to Google cloud storage signedUrl

### ISSUE THREAD

**Issue by leonimurilo** [expo/expo#9183]
Could someone help me with this please?

I am using expo-camera "[takePictureAsync](https://docs.expo.io/versions/latest/sdk/camera/#takepictureasync)" which returns: `{uri, base64 ... }`.

I need to send a PUT request with `'Content-Type': 'image/jpeg'` and the body of the request as the image itself to Google storage using a presigned URL.

The problem is that I have no idea whether I should send the uri or the base64. I actually tried both ways, but the image was always corrupted on the storage. Should I apply some kind of conversion to the base64 or something like that?
It seems I also can't use formData as content type.

Does anyone know how can I send the image taken from "takePictureAsync" via this PUT request?

**Comment by tsapeta** [comment]
I believe using FormData is the best choice and as far as I know Google Cloud supports that way. Maybe that can help https://cloud.google.com/storage/docs/json_api/v1/how-tos/multipart-upload ?

**Comment by leonimurilo** [comment]
Thank you @tsapeta 

I before reading your response, I managed to send the image without form data.

I used [this](https://www.npmjs.com/package/buffer) package to turn the base64 into a buffer and then sending the buffer fixed the issue with google cloud API. I honestly don't know if this is the best approach but now we might have 2 approaches to help someone in the future since I found a few people with the same issue but without a solution.

Here is more or less what I did:
```javascript
const signedUrl = 'PRE SIGNED URL OBTAINEDFROM STORAGE API';

const cameraData = await cameraref.current.takePictureAsync({
  quality: 0.75,
  base64: true,
});
const file = Buffer.from(cameraData.base64, 'base64')

axios.put(signedUrl, file, {
    headers: {
      'Content-Type': 'image/jpeg',
    },
  });
```
