### ISSUE TITLE
expo-calendar can't create events with notification alarms on Android

### ISSUE THREAD

**Issue by r20** [expo/expo#9184]
### Summary of Issue
I can't create an event with alarms on Android.  Depending on the attributes to the createEventAsync event object, I get a crash or error.  This happens with both all day events and non-all-day.  It happens if the relativeOffset is in the past or future.  It used to work in expo-calendar 8.1.0

### Environment 
Android, with expo-calendar 8.2.1

```
  Expo CLI 3.22.1 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Users\joshr\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```

### Reproducible Demo

This causes a crash. 
```
    const start = new Date(new Date().setUTCHours(0, 0, 0, 0));
    const end = new Date(new Date(start.getTime() + 24 * 60 * 60000).setUTCHours(0, 0, 0, 0));
    const newCalendarEvent = {
      alarms: [{ relativeOffset: 9 * 60, method: Calendar.AlarmMethod.ALERT }],
      notes: "This is an all-day test event",
      title: "Test event",
      startDate: start,
      endDate: end,
      allDay: true,
      timeZone: "UTC",
      endTimeZone: "UTC",
    };
    const eventId = await Calendar.createEventAsync(calendarId, newCalendarEvent);
```
In a previous release of expo 37 and expo-calendar 8.1.0 I had code like this, but with endTimeZone set to null and it worked.  In release 8.2.1, endTimeZone: null causes a "TypeError: Cannot convert undefined or null to object".

I probably had null because that's how they appear when created by the google calendar app.  I recall having problems (maybe the crash existed, I don't remember) and I got things to work after making my object look similar to events created by the google calendar app.  

The [stringifyDateValues ](https://github.com/expo/expo/blob/master/packages/expo-calendar/src/Calendar.ts#L702) function was recently changed.  Null is an object.  This function should be changed to return null if obj is null.

 
### Steps to Reproduce
To get the crash, attempt to create an all day calendar entry with an alarm with the code above.
To get the other error, try the same thing with endTimeZone: null

### Expected Behavior vs Actual Behavior
Expected: Calendar entry created without crash whether endTimeZone is specified, not specified, or specified as null.  

Note that it's good to support null because that's how the objects appear that are created by the default calendar app.  If an expo app wants to query and clone an all day event created with the default calendar app it would have endTimeZone: null.

Actual: Crash or error.

**Comment by AdamJNavarro** [comment]
Hey @r20,

Thanks for submitting a bug report! Would you be able to create a fully reproducible example of this crash so that we can test it on our end?

Cheers,
Adam

**Comment by r20** [comment]
@AdamJNavarro  I've tried creating a [snack ](https://snack.expo.io/@rjosh/cc71f0) but I can't get it to ask for calendar permissions and proceed.   I've tried on an android device and the android emulator within snack.

**Comment by brentvatne** [comment]
@r20 - you can share a github repo too

**Comment by r20** [comment]
@AdamJNavarro  and @brentvatne 
Here's a repo:  https://github.com/r20/create-cal-event
