### ISSUE TITLE
[expo-av] NullPointerException at VideoView.java

### ISSUE THREAD

**Issue by ahmetbicer** [expo/expo#9185]
### Summary of Issue 
I have an app that uses expo-av to show videos from users gallery. I am getting crash reports from play console.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
I am using expo-av on bare react native project.

react-native : 0.62.2
expo-av: 8.2.1
expo-image-picker: 8.3.0
react-native-unimodules: 0.10.1

buildToolsVersion = "29.0.0"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29

### Reproducible Demo
I don't have a reproducible demo because i don't know what causes this issue.

 
### Steps to Reproduce
I don't have steps to reproduce the error because i don't know what causes this issue.

### Expected Behavior vs Actual Behavior
Expected behavior is that the application does not crash.
Actual behavior is app crashing.

### Stack Trace

```
java.lang.NullPointerException: 
  at expo.modules.av.video.VideoView$5.a (VideoView.java:111)
  at expo.modules.av.player.SimpleExoPlayerData.a (SimpleExoPlayerData.java:14)
  at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners (ExoPlayerImpl.java:169)
  at com.google.android.exoplayer2.ExoPlayerImpl.a (ExoPlayerImpl.java:63)
  at com.google.android.exoplayer2.ExoPlayerImpl.a (ExoPlayerImpl.java:79)
  at com.google.android.exoplayer2.ExoPlayerImpl.a (ExoPlayerImpl.java:93)
  at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:2)
  at android.os.Handler.dispatchMessage (Handler.java:112)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

### My Code 

```
<Video
    source={{ uri: this.state.videoPath }}
    ref={ (ref) => this.player = ref }
    shouldPlay={this.state.pauseVideo}
    isLooping
    useNativeControls={true}
    style={{ width: Dimensions.get("window").width, height: "100%" }}
    resizeMode={Video.RESIZE_MODE_CONTAIN}
/>
```

VideoView.java:111 points to [this](https://github.com/expo/expo/blob/1df8bf885540e4780e17e9c451b08bcea7c543ae/packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java#L106) which is a function that throws an error and this function called in [this](https://github.com/expo/expo/blob/1df8bf885540e4780e17e9c451b08bcea7c543ae/packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java#L303) and [this](https://github.com/expo/expo/blob/1df8bf885540e4780e17e9c451b08bcea7c543ae/packages/expo-av/android/src/main/java/expo/modules/av/video/VideoView.java#L385) function. 

The first one is `setSource` and other one is `onLoadError` so my guess is when loading the video something happens. Maybe unsupported video format? How can i solve or debug this problem? Thank you so much.

**Comment by ahmetbicer** [comment]
Hey @cruzach,
You added the `needs repro` tag but i don't have a reproducible demo because users of my app getting this error and i am seeing from google play console as crash. Is it possible to get help without a reproducible demo? Thank you so much.

**Comment by IjzerenHein** [comment]
I had a closer look but I'm afraid we need more info in order to fix this issue. The call-stack doesn't provide sufficient insight into the problem. Does the callstack always look like this or are there variations?

@ahmetbicer Please provide us with a transscript on how you are using the `<Video>` component. Things like, which props you are changing, which video format, etc..

**Comment by ahmetbicer** [comment]
There are some variations in the call stack but it is not in expo's java codes. For example

```
java.lang.NullPointerException: 
  at expo.modules.av.video.VideoView$5.a (VideoView.java:111)
  at expo.modules.av.player.SimpleExoPlayerData.a (SimpleExoPlayerData.java:14)
  at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners (ExoPlayerImpl.java:169)
  at com.google.android.exoplayer2.ExoPlayerImpl.a (ExoPlayerImpl.java:63)
  at com.google.android.exoplayer2.ExoPlayerImpl.a (ExoPlayerImpl.java:79)
  at com.google.android.exoplayer2.ExoPlayerImpl.a (ExoPlayerImpl.java:93)
  at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:2)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7777)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1047)
```
It is basically the same error just last 6 lines is different. I can provide you different variations if it means something.

I am using expo-image-picker library to select a video from users gallery and that gives me an uri for the video. After that i am using that uri to change the source prop of the Video component with videoPath state. If user changes the screen i am using shouldPlay prop the pause the video. If user wants to select another video, they are clicking a button to reset the videoPath and this will also hide the video component from screen to show "Open Gallery" button. When they click the "Open Gallery" button expo-image-picker opens again to choose another video and the same process go on.

In case of video formats i don't know what users selecting because i am not logging that data. If user select an unsupported video format what expo-image-picker library returns? If it returns null, i am not controlling if the `result.uri` is null or not, so maybe it is causing this error?

```
selectVideo = async () => {
const { status } = await ImagePicker.requestCameraRollPermissionsAsync();
    if (status == "granted") {
      await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Videos,
        quality: 1
      }).then(result => {
        if (!result.cancelled) {
          this.setState({ videoPath: result.uri });
        }
      })
      .catch((err) => {
        crashlytics().recordError(err);
      })
    }
}
```

**Comment by IjzerenHein** [comment]
And what about specific Android devices. Are you seeing this problem for only specific users/devices/android API versions?

I understand that a repro might be difficult, but it will definitely help us find the issue faster. Creating an example snack/app that behaves the same as your app is also helpful in understanding how your sequence of API calls/loading/unloading might be affecting expo-av and leading to this crash.

**Comment by ahmetbicer** [comment]
I am listing the devices that affected: 
Huawei -> Nova 5T, P30 PRO, P10, P30 Lite, P20, HONOR 10i, P10 Plus
Xiaomi -> Redmi Note 8 pro
Samsung -> S20+, S10e, S10+, S8
Oneplus -> 8 5G

Affected android api versions -> 10 (68%), 9 (25%), 8 (7%)

I am trying to reproduce the problem but there is no chance for now.

 Thank you for the help btw!

**Comment by ahmetbicer** [comment]
I am closing this issue to get more information and better stack traces from users. When i reproduce the error i will re-open and we can discuss about it more. Thank you for all the help!

**Comment by Bug-Generator** [comment]
I am happy to help you chase down this interesting bug and might be able to reproduce the error. Essentially there are video types not supported that you do not handle hence it resolves to nothing and throws you a NPE 
```then(result => {
        if (!result.cancelled) {
          this.setState({ videoPath: result.uri });
        }
      }) ```
it is not best practice to trust what is coming from a user's device directly into your logic. Add some validation around `result.uri` if anything

**Comment by ahmetbicer** [comment]
I am now controlling whether the `result.uri` is null or not. But even if i manually set the `videoPath` to null, app not crashes, just a blank screen with no video.

**Comment by ahmetbicer** [comment]
Hi @IjzerenHein, i finally reproduce the error in an android emulator. I downloaded a video from youtube to test my app but i didn't realize the video was corrupted. Gallery says "can't play this video" if i try to play it (mp4 video btw). When i tried to show the video, app crashed. I get the log dump from `adb logcat` hope you find it useful to debug this problem. Probably users of my app tries to select a corrupted video from their gallery. `expo-image-picker` gives a valid uri for that video. Video not showing in the screen and later app crashes.

You can see the gist from this[ link](https://gist.github.com/ahmetbicer/daf596b85f54d337e1a86a297162c7c7). Null Pointer exception at line 262. Thank you so much.

**Comment by IjzerenHein** [comment]
@ahmetbicer That's great!

Could you provide a link to the corrupted video so I can test with that?

**Comment by ahmetbicer** [comment]
@IjzerenHein Video is not corrupted in youtube. Maybe it get corrupted while i download it. You can download the video from this [link](https://wetransfer.com/downloads/dd94beb6dbe04ad1fce7d4aa80ecbab720200806135111/bfcafc). But strangely video playing on my personal phone, not in the emulator. Hope you can reproduce as well. If you can't i can provide all of the information you need. Thanks!

**Comment by IjzerenHein** [comment]
@ahmetbicer Can you give some details about the Android emulator, which device and API version are you testing on?

**Comment by ahmetbicer** [comment]
Google pixel 3XL, Android 5.1 API 22

**Comment by ahmetbicer** [comment]
So i use onError method of `<Video>` component to detect if it gives "Player error: null". When it gives that error i am not showing the video anymore and app works as expected now. But i would like to understand if it is my implementation that causes this error or not. Thanks!

**Comment by SleeplessByte** [comment]
Hi there! I ran into this too. It happens to me when I give a not-working value as `src` on mount. When I do:

```typescript
const [actualSource, setSource] = useState<string | null>(null)

useEffect(() => { setSource(propSource) }, [propSource])
```

And then use `actualSource` as property for the video element, all errors go away. My guess is that it's similar to what @ahmetbicer says: errors aren't captured correctly when it's on mount / not via the onError prop.

**Comment by IjzerenHein** [comment]
I've actually been able to reproduce the problem using the information provided by @ahmetbicer 
There is an issue with how the error-handler cleans up classes when an error occurs when loading the video source.
I'm working on a solution.

**Comment by ahmetbicer** [comment]
Hey @SleeplessByte, Thank you for the information but i didn't understand how can i implement it in my app. Basically i am using `expo-image-picker` to get `uri` of the video from users gallery. Then i am setting a state for this uri. This state also in the source prop of <Video> component. You can see my implementation below. Thanks!

```
openGallery = async () => {
    const { status } = await ImagePicker.requestCameraRollPermissionsAsync();
    if (status == "granted") {
      await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Videos,
      }).then(result => {
        if (!result.cancelled && result.uri != null) ) {
            this.setState({ videoPath: result.uri, showVideo: true });  //This is how i get the video uri
        }
      })
      .catch((err) => {
        console.log(err)
        crashlytics().recordError(err);
      })
    }
  }
```
And in the render function;

```
{this.state.showVideo && <Video source={{ uri: this.state.videoPath }}  ... />}
```

**Comment by ahmetbicer** [comment]
@IjzerenHein Thank you so much for the help! I am glad that you could reproduce the error!

**Comment by ahmetbicer** [comment]
@IjzerenHein  I do the changes in #9596 pr in my local expo-av package and it is not crashes the app anymore. It is now showing blank screen for video but i can handle this with onError method on <Video> component. I would like to ask one more question. Is my implementation in this [comment](https://github.com/expo/expo/issues/9185#issuecomment-670015507) of showing a video is correct? How can i improve it? Thank you so much for the effort!

**Comment by SleeplessByte** [comment]
@IjzerenHein that makes complete sense and in-line with why what I did worked for me.

**Comment by IjzerenHein** [comment]
> @IjzerenHein I do the changes in #9596 pr in my local expo-av package and it is not crashes the app anymore. It is now showing blank screen for video but i can handle this with onError method on component. I would like to ask one more question. Is my implementation in this [comment](https://github.com/expo/expo/issues/9185#issuecomment-670015507) of showing a video is correct? How can i improve it? Thank you so much for the effort!

I'd probably do it like this:

```
  openGallery = async () => {
    const { status } = await ImagePicker.requestCameraRollPermissionsAsync();
    if (status == "granted") {
      try {
        const result = await ImagePicker.launchImageLibraryAsync({
          mediaTypes: ImagePicker.MediaTypeOptions.Videos,
        });
        if (!result.cancelled && typeof result.uri === 'string') ) {
          this.setState({ videoPath: result.uri, showVideo: true });
        }
      } catch (err) {
        console.log(err)
        crashlytics().recordError(err);
      }
    }
  }
```

And

```
<Video
    source={this.state.videoPath ? { uri: this.state.videoPath } : undefined}
/>
```

**Comment by ahmetbicer** [comment]
Thank you so much for everything! I am closing this issue as it resolved with PR.
