### ISSUE TITLE
I want to use a feature of Firebase 7.14.0 (increments), but expo Firebase version is 7.9.0

### ISSUE THREAD

**Issue by SrBrahma** [expo/expo#9186]
First I installed manually the Firebase version 7.16.0, but when I runned npm start, it warned me that it wasn't supported and I should install it via `expo install firebase`, and it installed the version 7.9.0. However, I want to use a feature only available since version 7.14.0, the `firebase.database.ServerValue.increment()`.

Would I have problems if I used the "non-supported" version of Firebase?

**Comment by brentvatne** [comment]
we recommend a specific version because more recent versions have regressed support for react-native in some ways. the firebase team is working on resolving those issues. if you would like to install the latest version anyways, you can do that and just ignore the warning.

**Comment by SrBrahma** [comment]
Thanks for the quick answer :)
Is there any link where I can read more about those drawbacks, so I can check if it's worth for my case?
