### ISSUE TITLE
Errors upgrading to Expo v. 22

### ISSUE THREAD

**Issue by jcalderaio** [expo/expo#919]
I followed the directions upgrading to v.22, and I am getting the following error on my phone:

`undefined is not an object (evaluating '_react.PropTypes.array')`

Here is my 'package.json':
<img width="894" alt="screen shot 2017-11-05 at 12 18 23 pm" src="https://user-images.githubusercontent.com/6464473/32417182-8cb18e78-c223-11e7-86dd-6c5c7ba6c45b.png">

....and my 'App.json':
<img width="896" alt="screen shot 2017-11-05 at 12 18 40 pm" src="https://user-images.githubusercontent.com/6464473/32417191-9d3d0808-c223-11e7-822f-c9d27c537366.png">

**Comment by JaredSartin** [comment]
You need to change your proptype include to this library, not React: https://github.com/facebook/prop-types

**Comment by dikaiosune** [comment]
Hi! Per the [SDK 22 Release Notes](https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6), you'll need to use `ViewPropTypes`:

https://www.dropbox.com/s/go9s2oasupor2up/Screenshot%202017-11-06%2013.32.10.png?dl=0

**Comment by jcalderaio** [comment]
@dikaiosune  I didn't use PropTypes anywhere in my code (which is why I'm confused it's throwing the error). Do I still need to do this regardless of whether I use PropTypes in my code?

**Comment by brentvatne** [comment]
@jcalderaio - a library that you depend on might use it. search in node_modules

**Comment by jcalderaio** [comment]
I thought maybe you'd say that. Thanks.
