### ISSUE TITLE
Background downloads API lacking download checks after restart?

### ISSUE THREAD

**Issue by hardcodet** [expo/expo#9192]
### Summary of Issue

Either this is not documented, or the downloads API in `expo-file-system` does not provide the means to simply monitor / reattach / check on a running downloads that were scheduled on earlier app runs. This also doesn't seem to be possible with resumables, since they seem to have been built for paused download only.

So basically, I can't do:

- start a long running download (which defaults to survive app restarts)
- close / kill my app
- restart my app and check on my running/completed/failed download

Unless I've missed something, this makes background downloads rather brittle.

### Suggestion

Why not expose the internal download IDs rather than just returning a promise from the FileSystem API? Something like this:

```
// init download - does NOT return a promise!
const transferInfo = FileSystem.downloadAsync(...);

// cache the download ID
this.database.cacheTransferId(transferInfo.transferId);

// if i really want a promise: wait for the transfer (wouldn't want to do that for long-running stuff though...)
await FileSystem.awaitTransfer(transferInfo.transferId);

// I'd rather register a listener though
FileSystem.monitorTransfer(transferInfo.transferId, someCallback);


--

// on restart, simply re-register the listener
const transferIds: string[] = this.database.getCachedTransfers();
for(const transferId of transferIds) {
    const transferInfo = FileSystem.getTransferInfo(transferId);

    if (transferInfo.ended) {
        // has completed or failed
    } else {
        FileSystem.monitorTransfer(transferInfo.transferId, someCallback);
    }
}

```

Addendum (minor documentation issue). On the docs page for `FileSystem`, in the initial example, you first use `FileSystem.createDownloadResumable` to construct a `DownloadResumable`, and then later down in the example use the constructor directly with `new FileSystem.DownloadResumable(...)`. Since the former simply seems to invoke the constructor, this just makes the sample more complex than needed, as it implies different behavior.

**Comment by pfcodes** [comment]
Did you ever figure this out? @hardcodet

**Comment by hardcodet** [comment]
You might have more luck opening a new issue rather than commenting on an old closed one. Chances are high the devs won't see this.

**Comment by 7ammer** [comment]
@mikefogg did you create a new issue for this or work out a solution / workaround? I think I'm encountering the same issue but I'm struggling to work out what exactly is going on.

Essentially though, for me, trying to save and resume a zip file is giving me nightmares.
