### ISSUE TITLE
Update SDK to 38, error in debug mode

### ISSUE THREAD

**Issue by AKclown** [expo/expo#9193]
question：
Error: Unable to resolve module `./debugger-ui/debuggerWorker.cff11639.js` from ``

surroundings：
    "expo": "^38.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
  "@react-native-community/cli-debugger-ui" "^4.9.0"

How to solve it?  thanks

**Comment by lukmccall** [comment]
This is a bug in the react-native bundler -> https://github.com/facebook/react-native/issues/28844

**Comment by cruzach** [comment]
@AKclown you may want to try some of the fixes listed in that issue, like clearing Google Chrome cache or uninstalling the app & restarting the device?

**Comment by AKclown** [comment]
> @AKclown您可能想尝试该问题中列出的一些修复程序，例如清除Google Chrome缓存或卸载应用程序并重新启动设备？

thanks, This is very helpful to me。 clearing Google Chrome cache and Reload the app

**Comment by AKclown** [comment]
> This is a bug in the react-native bundler -> [facebook/react-native#28844](https://github.com/facebook/react-native/issues/28844)

Thanks, let me see
