### ISSUE TITLE
Cannot Aligning animation value center in Circle in WEB

### ISSUE THREAD

**Issue by DevYuns** [expo/expo#9194]
### Summary of Issue 

Hi. I'm having trouble aligning animation value center in Circle to making a RadioButton in the `web`. The problem is that animation value is placed out of the center a little bit randomly. Some Value place in center, but others are not. It depends on size value.  There are no problems in `ios` and `android`.

It looks below. Green button is centered, but red button looks strange.

![image](https://user-images.githubusercontent.com/58724686/87297433-5f441700-c543-11ea-9bc4-1bd11bedf466.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Target : WEB

  Expo CLI 3.21.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.18 => 0.12.17 
      expo: ^38.0.8 => 38.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ^0.12.3 => 0.12.3 
    npmGlobalPackages:
      expo-cli: 3.21.1

### Reproducible Demo

For reproducible, I made a simple example that can be shown similar bug in my project. 

https://snack.expo.io/hf7IogfAM
 
My project repo is here : https://github.com/DevYuns/dooboo-ui/blob/master/main/RadioButton/index.tsx

### Expected Behavior vs Actual Behavior
Expected : Placing Animation value center in a Circle in web
Actual : Animation value is positioned randomly in a Circle.

How can I solve this problem? Thanks in advance!

**Comment by brentvatne** [comment]
hi there! I don't quite understand the example. I opened it on snack and it looks exactly the same on ios and android.
