### ISSUE TITLE
scripts/start-metro.sh: linha 24: open: not found

### ISSUE THREAD

**Issue by mozgbrasil** [expo/expo#9197]
### Summary of Issue 

Good morning my friends

Who can help

In my environment the error below is returned

	scripts/start-metro.sh: linha 24: open: not found

Also, many alerts

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

	$ expo diagnostics

	  Expo CLI 3.22.1 environment info:
	    System:
	      OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
	      Shell: 5.0.16 - /bin/bash
	    Binaries:
	      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
	      Yarn: 1.22.4 - /usr/bin/yarn
	      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.1/bin/npm
	      Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
	    npmPackages:
	      expo: ~38.0.0 => 38.0.0 
	      react-native: 0.62.2 => 0.62.2 
	    npmGlobalPackages:
	      expo-cli: 3.22.1

### Steps to Reproduce

	$ yarn android --verbose
	yarn run v1.22.4
	$ export NODE_ENV="development" && ./scripts/start-emulator.sh --verbose
	 ☛  Bootstrapping Expo in development mode
	 ☛  Ensuring Android project is setup...
	 ✅ Node modules installed
	 ✅ React Android is installed
	* daemon not running; starting now at tcp:5037
	* daemon started successfully
	 ⚠️  Starting emulator...
	 ☛  adb: no emulators found
	emulator: Requested console port 5554: Inferring adb port 5555.
	emulator: WARNING: encryption is off
	 ☛  adb: device offline
	 ☛  adb: device offline
	 ☛  stopped
	 ✅  Emulator is ready
	Broadcasting: Intent { act=android.intent.action.BOOT_COMPLETED }
	 ✅ Emulator is running
	 ⚠️  Starting Metro Bundler...
	/home/marcio/dados/projects/javascripts/expo-labs/apps/bare-expo/scripts/start-metro.sh: linha 24: open: comando não encontrado
	 ☛  Running the Android project...
	info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
	Jetifier found 0 file(s) to forward-jetify. Using 4 workers...
	info Installing the app...

	> Configure project :app

	Installing unimodules:
	 unimodules-core@5.3.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/@unimodules/core
	 unimodules-react-native-adapter@5.4.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/@unimodules/react-native-adapter
	 expo-analytics-amplitude@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-analytics-amplitude
	 expo-analytics-segment@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-analytics-segment
	 expo-app-auth@9.1.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-app-auth
	 expo-application@2.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-application
	 expo-av@8.3.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-av
	 expo-background-fetch@8.3.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-background-fetch
	 expo-barcode-scanner@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-barcode-scanner
	 expo-battery@2.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-battery
	 expo-bluetooth@1.0.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-bluetooth
	 expo-brightness@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-brightness
	 expo-calendar@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-calendar
	 expo-cellular@2.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-cellular
	 expo-constants@9.1.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-constants
	 expo-contacts@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-contacts
	 expo-crypto@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-crypto
	 expo-device@2.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-device
	 expo-document-picker@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-document-picker
	 expo-error-recovery@1.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-error-recovery
	 expo-facebook@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-facebook
	 expo-file-system@9.0.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-file-system
	 expo-firebase-analytics@2.4.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-firebase-analytics
	 expo-firebase-core@1.1.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-firebase-core
	 expo-font@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-font
	 expo-gl-cpp@8.3.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-gl-cpp
	 expo-gl@8.3.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-gl
	 expo-google-sign-in@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-google-sign-in
	 expo-haptics@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-haptics
	 expo-image-loader@1.1.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-image-loader
	 expo-image-manipulator@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-image-manipulator
	 expo-image-picker@8.3.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-image-picker
	 expo-in-app-purchases@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-in-app-purchases
	 expo-intent-launcher@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-intent-launcher
	 expo-keep-awake@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-keep-awake
	 expo-linear-gradient@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-linear-gradient
	 expo-local-authentication@9.2.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-local-authentication
	 expo-localization@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-localization
	 expo-location@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-location
	 expo-mail-composer@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-mail-composer
	 expo-media-library@8.3.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-media-library
	 expo-network@2.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-network
	 expo-notifications@0.4.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-notifications
	 expo-permissions@9.0.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-permissions
	 expo-print@9.0.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-print
	 expo-random@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-random
	 expo-screen-capture@1.0.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-screen-capture
	 expo-screen-orientation@1.1.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-screen-orientation
	 expo-secure-store@9.0.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-secure-store
	 expo-sensors@9.0.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-sensors
	 expo-sharing@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-sharing
	 expo-sms@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-sms
	 expo-speech@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-speech
	 expo-sqlite@8.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-sqlite
	 expo-task-manager@8.3.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-task-manager
	 expo-updates@0.2.11 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-updates
	 expo-video-thumbnails@4.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-video-thumbnails
	 expo-web-browser@8.3.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/expo-web-browser
	 unimodules-app-loader@1.2.0 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-app-loader
	 unimodules-barcode-scanner-interface@5.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-barcode-scanner-interface
	 unimodules-camera-interface@5.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-camera-interface
	 unimodules-constants-interface@5.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-constants-interface
	 unimodules-file-system-interface@5.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-file-system-interface
	 unimodules-font-interface@5.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-font-interface
	 unimodules-image-loader-interface@5.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-image-loader-interface
	 unimodules-permissions-interface@5.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-permissions-interface
	 unimodules-sensors-interface@5.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-sensors-interface
	 unimodules-task-manager-interface@5.2.1 from /home/marcio/dados/projects/javascripts/expo-labs/packages/unimodules-task-manager-interface
	 ☛  Ensuring Android project is setup...
	 ✅ Node modules installed
	 ✅ React Android is installed
	You don't have access to decrypted secrets. Falling back to `template-files/keys.json`.
	Resolving macros...
	Resolved TEST_APP_URI macro to ""
	Resolved TEST_CONFIG macro to ""
	Resolved TEST_SERVER_URL macro to "TODO"
	Resolved TEST_RUN_ID macro to "37d850a8-0c31-44c4-b4c9-a9cd31d59085"
	Resolved BUILD_MACHINE_LOCAL_HOSTNAME macro to "marcio-Inspiron-5548"
	Resolved DEV_PUBLISHED_KERNEL_MANIFEST macro to "{\"ios\":{\"supportsTablet\":true,\"bundleIdentifier\":\"host.exp.exponent\"},\"icon\":\"https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png\",\"name\":\"expo-home\",\"slug\":\"expo-home-dev-f9d2898589580c00f8cd995840931b93a9499544\",\"extra\":{\"amplitudeApiKey\":\"081e5ec53f869b440b225d5e40ec73f9\"},\"scheme\":\"exp\",\"android\":{\"package\":\"host.exp.exponent\"},\"iconUrl\":\"https://s3.amazonaws.com/exp-brand-assets/ExponentEmptyManifest_192.png\",\"locales\":{},\"privacy\":\"unlisted\",\"updates\":{\"checkAutomatically\":\"ON_LOAD\",\"fallbackToCacheTimeout\":0},\"version\":\"38.0.0\",\"platforms\":[\"ios\",\"android\"],\"sdkVersion\":\"UNVERSIONED\",\"description\":\"The Expo client app\",\"orientation\":\"portrait\",\"dependencies\":[\"@expo/react-native-action-sheet\",\"@expo/react-native-touchable-native-feedback-safe\",\"@expo/vector-icons\",\"@react-native-community/netinfo\",\"apollo-boost\",\"apollo-cache-inmemory\",\"dedent\",\"es6-error\",\"expo\",\"expo-analytics-amplitude\",\"expo-asset\",\"expo-barcode-scanner\",\"expo-blur\",\"expo-camera\",\"expo-constants\",\"expo-device\",\"expo-font\",\"expo-linear-gradient\",\"expo-location\",\"expo-permissions\",\"expo-task-manager\",\"expo-web-browser\",\"graphql\",\"graphql-tag\",\"immutable\",\"lodash\",\"prop-types\",\"querystring\",\"react\",\"react-apollo\",\"react-native\",\"react-native-appearance\",\"react-native-fade-in-image\",\"react-native-gesture-handler\",\"react-native-infinite-scroll-view\",\"react-native-maps\",\"react-native-safe-area-context\",\"react-navigation\",\"react-navigation-material-bottom-tabs\",\"react-navigation-stack\",\"react-navigation-tabs\",\"react-redux\",\"reanimated-bottom-sheet\",\"redux\",\"redux-thunk\",\"semver\",\"sha1\",\"url\"],\"primaryColor\":\"#cccccc\",\"androidStatusBar\":{\"barStyle\":\"dark-content\"},\"userInterfaceStyle\":\"automatic\",\"id\":\"@expo-home-dev/expo-home-dev-f9d2898589580c00f8cd995840931b93a9499544\",\"releaseId\":\"b91eccb9-f70c-446e-b8ff-a3165a3f53f1\",\"revisionId\":\"38.0.0-r.JMLh63NNW\",\"publishedTime\":\"2020-06-22T20:13:43.989Z\",\"commitTime\":\"2020-06-22T20:13:44.097Z\",\"bundleUrl\":\"https://d1wp6m56sqw74a.cloudfront.net/%40expo-home-dev%2Fexpo-home-dev-f9d2898589580c00f8cd995840931b93a9499544%2F38.0.0%2Fe2aa88e14721842bbe924fd3028f7ffa-38.0.0-android.js\",\"releaseChannel\":\"default\",\"hostUri\":\"exp.host/@expo-home-dev/expo-home-dev-f9d2898589580c00f8cd995840931b93a9499544\"}"
	Resolved BUILD_MACHINE_KERNEL_MANIFEST macro to ""
	Resolved TEMPORARY_SDK_VERSION macro to "38.0.0"
	Resolved INITIAL_URL macro to null

	Generating build config android/expoview/src/main/java/host/exp/exponent/generated/ExponentBuildConstants.java ...
	Using published dev version of Expo Home.
	Rendering /home/marcio/dados/projects/javascripts/expo-labs/android/app/src/main/AndroidManifest.xml from template /home/marcio/dados/projects/javascripts/expo-labs/template-files/android/AndroidManifest.xml ...
	Rendering /home/marcio/dados/projects/javascripts/expo-labs/android/app/google-services.json from template /home/marcio/dados/projects/javascripts/expo-labs/template-files/android/google-services.json ...
	Rendering /home/marcio/dados/projects/javascripts/expo-labs/android/expoview/src/main/java/host/exp/exponent/generated/ExponentKeys.java from template /home/marcio/dados/projects/javascripts/expo-labs/template-files/android/ExponentKeys.java ...
	Rendering /home/marcio/dados/projects/javascripts/expo-labs/apps/bare-expo/android/app/google-services.json from template /home/marcio/dados/projects/javascripts/expo-labs/template-files/android/bare-expo/android/app/google-services.json (Optional) ...
	google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 11.4.2 will be used.
	please apply google-services plugin at the bottom of the build file.
	Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
	registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
	Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
	registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

	> Configure project :expo-av
	WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugApi' is obsolete and has been replaced with 'testDebugImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugCompile' is obsolete and has been replaced with 'testDebugImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugProvided' is obsolete and has been replaced with 'testDebugCompileOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugPublish' is obsolete and has been replaced with 'testDebugRuntimeOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testProvided' is obsolete and has been replaced with 'testCompileOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testPublish' is obsolete and has been replaced with 'testRuntimeOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleaseApi' is obsolete and has been replaced with 'testReleaseImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleaseCompile' is obsolete and has been replaced with 'testReleaseImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleaseProvided' is obsolete and has been replaced with 'testReleaseCompileOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleasePublish' is obsolete and has been replaced with 'testReleaseRuntimeOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

	> Configure project :expo-updates
	WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugApi' is obsolete and has been replaced with 'testDebugImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugCompile' is obsolete and has been replaced with 'testDebugImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugProvided' is obsolete and has been replaced with 'testDebugCompileOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugPublish' is obsolete and has been replaced with 'testDebugRuntimeOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testProvided' is obsolete and has been replaced with 'testCompileOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testPublish' is obsolete and has been replaced with 'testRuntimeOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleaseApi' is obsolete and has been replaced with 'testReleaseImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleaseCompile' is obsolete and has been replaced with 'testReleaseImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleaseProvided' is obsolete and has been replaced with 'testReleaseCompileOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleasePublish' is obsolete and has been replaced with 'testReleaseRuntimeOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

	> Configure project :expo-web-browser
	WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugApi' is obsolete and has been replaced with 'testDebugImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugCompile' is obsolete and has been replaced with 'testDebugImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugProvided' is obsolete and has been replaced with 'testDebugCompileOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testDebugPublish' is obsolete and has been replaced with 'testDebugRuntimeOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testProvided' is obsolete and has been replaced with 'testCompileOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testPublish' is obsolete and has been replaced with 'testRuntimeOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleaseApi' is obsolete and has been replaced with 'testReleaseImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleaseCompile' is obsolete and has been replaced with 'testReleaseImplementation'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleaseProvided' is obsolete and has been replaced with 'testReleaseCompileOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
	WARNING: Configuration 'testReleasePublish' is obsolete and has been replaced with 'testReleaseRuntimeOnly'.
	It will be removed in version 5.0 of the Android Gradle plugin.
	For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

	> Task :app:processDebugGoogleServices
	Parsing json file: /home/marcio/dados/projects/javascripts/expo-labs/apps/bare-expo/android/app/google-services.json

	> Task :expo-gl-cpp:stripDebugDebugSymbols FAILED

	Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
	Use '--warning-mode all' to show the individual deprecation warnings.
	See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
	1305 actionable tasks: 3 executed, 1302 up-to-date
	Unable to generate manifest from home: Failed to fetch manifest from exp://192.168.1.6:80

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':expo-gl-cpp:stripDebugDebugSymbols'.
	> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.3.6528147

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

	* Get more help at https://help.gradle.org

	BUILD FAILED in 26s

	error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
	Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
	Unable to generate manifest from home: Failed to fetch manifest from exp://192.168.1.6:80

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':expo-gl-cpp:stripDebugDebugSymbols'.
	> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.3.6528147

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

	* Get more help at https://help.gradle.org

	BUILD FAILED in 26s

	    at makeError (/home/marcio/dados/projects/javascripts/expo-labs/node_modules/execa/index.js:174:9)
	    at /home/marcio/dados/projects/javascripts/expo-labs/node_modules/execa/index.js:278:16
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	    at async runOnAllDevices (/home/marcio/dados/projects/javascripts/expo-labs/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
	    at async Command.handleAction (/home/marcio/dados/projects/javascripts/expo-labs/node_modules/@react-native-community/cli/build/index.js:186:9)
	error Command failed with exit code 1.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

![Captura de tela de 2020-07-13 14-34-22](https://user-images.githubusercontent.com/17202780/87335022-fd20ed00-c515-11ea-9cbc-9b6a8521e925.png)

**Comment by byCedric** [comment]
Hi @mozgbrasil, I'm a bit confused here. There are 3 different errors, one you mentioned, one from the steps to reproduce, and one from the screenshot. I'm not sure what you want to do here, you are trying to open the expo client bare app on Linux right?

If you just want to create a new Expo app, please [see the tutorial](https://docs.expo.io/tutorial/planning/). If you want to contribute to Expo and develop with the Expo client, I'm afraid we don't (fully) support Linux. The error related to `open; not found` is something we probably won't fix anytime soon.

> \* What went wrong:
> Execution failed for task ':expo-gl-cpp:stripDebugDebugSymbols'.
> \> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.3.6528147

This issue (from the steps to reproduce) is related to a specific Android NDK version, not being installed. You can install the required NDK version `21.0.6113669` [with this guide](https://developer.android.com/studio/projects/install-ndk).

Hope this helps!
