### ISSUE TITLE
getLastLocation is always returning error 'E_LOCATION_UNAUTHORIZED' in android 11

### ISSUE THREAD

**Issue by arqex** [expo/expo#9199]
### Summary of Issue 
Seems that in Android 11, it's not possible to get the location in the background. 

The policy to access to the location has changed in this version of android (https://developer.android.com/preview/privacy/location) and using expo-location I can't get the location in a background task, even if I grant allowing the app to access to the location all the time.

`getLastLocation` returns an unauthorized error, and `getPermissionsAsync` returns that the app can't access to the location nor even ask for it (as I said, the permission is granted in the app's settings).

When the app goes to the foreground, it can access to the location again.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
expo-location v8.1.0
expo-task-manager v8.1.0
android 11 in emulator

### Expected Behavior vs Actual Behavior

From the docs, https://developer.android.com/preview/privacy/location, the app can know when it's possible to ask the user for the background permission using a native method `shouldShowPermissionRationale()`.

It would be great that we could enable that flow in expo-location.

**Comment by brentvatne** [comment]
is there a reason that you're not using (Location.startLocationUpdatesAsync(taskName, options))[https://docs.expo.io/versions/latest/sdk/location/#background-location-methods] for watching location in the background?

**Comment by roger-schaer** [comment]
I also noticed a problem with Android 11. Even when using the "startLocationUpdatesAsync" function, when my app goes into the background, I stop receiving location updates.

I think that the changes introduced in Android 11 regarding background location require some adaptation in Expo, as the request for background location should be "incremental", i.e. asked separately from the foreground location permission : https://developer.android.com/about/versions/11/privacy/location

It seems that users should now manually navigate to the permissions screen of the app and select "Allow all the time" manually : https://developer.android.com/training/location/permissions#request-background-location
