### ISSUE TITLE
BarCodeScanner not working

### ISSUE THREAD

**Issue by ErkanSensei** [expo/expo#92]
Whenever I use the BarCodeScanner example, BarCodeScanner returns null instead of the actual component.

**Comment by brentvatne** [comment]
Hi there! You must be on SDK14. You'll see in the SDK15 release notes that we moved components from the `Components` namespace to the root, so `Expo.Components.BarCodeScanner` is `Expo.BarCodeSanner`.

Here's an example of BarCodeScanner working: https://sketch.expo.io/rJXodKH2l

**Comment by nikki93** [comment]
Code example? And which version of the SDK (`sdkVersion` in `exp.json`) are you on?
