### ISSUE TITLE
Location.startLocationUpdatesAsync - no realtime updates on android, when in background (even with foregroundService)

### ISSUE THREAD

**Issue by krachtstefan** [expo/expo#9200]
### Summary of Issue
Using `Location.startLocationUpdatesAsync` with `foregroundService` gets much less updates than when the app is opened and in foreground. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 3.22.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.0/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.0.10 => 4.4.0
    npmGlobalPackages:
      expo-cli: 3.22.1

Tested in a standalone app on a __Nokia 5.1 Plus__ with __Android 10__

### Reproducible Demo

```javascript
Location.startLocationUpdatesAsync("taskname",  {
    accuracy: Location.Accuracy.BestForNavigation,
    timeInterval: 0,
    deferredUpdatesInterval: 0,
    deferredUpdatesDistance: 0,
    distanceInterval: 0,
    foregroundService: {
      notificationTitle: "title",
      notificationBody: "body",
      notificationColor: "#0000FF",
    },
  })
```
### Steps to Reproduce

__after real device testing with a standalone app__
- works great on iOS, the app gets spammed with location updates no matter if foreground or background
- works great on android too, __as long as I keep the app in foreground__ 
  - when the app is closed (swipe up to home screen, turn off the screen)
  - I see the expected sticky notification
  - I get frequent updates at the beginning
  - after some time the app just gets triggered at much larger intervals (10 minutes and more)
  - I get all the updates but in delayed batches

__some illustration__
<img width="963" alt="Bildschirmfoto 2020-07-13 um 19 48 11" src="https://user-images.githubusercontent.com/529711/87338915-248fae00-c546-11ea-9d69-fbe61cc6430f.png">
Both lines are from the same recording with the app. The blue line shows all the received locations in total. The red line only uses one single coordinate of a batch. Shouldn't there be much more frequent updates? With are foreground service and  `Location.Accuracy.BestForNavigation`, `deferredUpdatesInterval:0`,`deferredUpdatesDistance:0`, `distanceInterval:0` I would expect nearly as much updates as when the app is in foreground.

### Expected Behavior vs Actual Behavior
The `foregroundService` in this example should should trigger much more real time updates instead of updating in larger batches.

**Comment by reinaldonetof** [comment]
> works great on iOS, the app gets spammed with location updates no matter if foreground or background @krachtstefan 

Hey, @krachtstefan , did you using bare ou managed workflow? 

I'm using Windows, and either managed or bare, my android works constantly, but when I try to use with iOS appear: 

> " Error: Background Location has not been configured. To enable it, add `location` to `UIBackgroundModes` in Info.plist file."

This happened with you at any time?

thanks for any help!

**Comment by krachtstefan** [comment]
@reinaldonetof I'm using the managed workflow and I'm afraid that im might need to `expo eject` 😢

> " Error: Background Location has not been configured. To enable it, add location to UIBackgroundModes in Info.plist file."

Is it possible that you missed [this step](https://docs.expo.io/versions/latest/sdk/task-manager/#configuration-for-standalone-apps) here?!


> my android works constantly

Can you confirm that you don't have the problems that I mentioned above? As a simple example:
- when the app is closed (swipe up to home screen, turn off the screen, you see the sticky notification)
- and the background task is running for like 15 minutes (asuming you talk a walk and your location changes constantly)
- the task gets called at least one time a minute (probably much more often)

I you have any chance to test that, that would be a __HUGE__ help!

**Comment by reinaldonetof** [comment]
> Can you confirm that you don't have the problems that I mentioned above? As a simple example:

Appears some problems with android when putting these values: `deferredUpdatesInterval:0,deferredUpdatesDistance:0, distanceInterval:0` the expo app crash, I think because of the memory. 

But you have tried with `foregroundService (object) -- `? Maybe will help what you want.

So, to my problem, I didn't find the  [AppDelegate.h
](https://docs.expo.io/versions/latest/sdk/task-manager/#appdelegateh). Have you had a problem with that file? Or you inserted it?

> I'm using the managed workflow and I'm afraid that im might need to expo eject 

don't worry about eject if you're using SDK 38. if you want to try, just work with two separate branches.

Another question, how are you saving the location? Are you sending through REST?
@krachtstefan

**Comment by krachtstefan** [comment]
> Appears some problems with android when putting these values: deferredUpdatesInterval:0,deferredUpdatesDistance:0, distanceInterval:0 the expo app crash, I think because of the memory.

I have also tried various combinations with `deferredUpdatesInterval`, `deferredUpdatesDistance`, `distanceInterval`. All of them with and without `foregroundService`. A crashing app was never an issue for me. Also, I don't use the Expo app in this case! This is might be crutial, I have read some older issues here where background task might not be reliably working with background tasks. So to make sure it's not about expo client, I use a standalone app.

The AppDelegate should be in the forlder `ios/projectname` and is only present in the bare workflow

> how are you saving the location? 

To isolate this issue I use a simple redux store.

**Comment by reinaldonetof** [comment]
> So to make sure it's not about expo client, I use a standalone app.

Oh, I didn't use standalone yet, so I will try either iOS and Android to you. 

Thanks for your help Stefan!

**Comment by krachtstefan** [comment]
Thanks @reinaldonetof, iOS works fine btw. My issue is just about android. 

In the meantime I also tried to `expo eject` and the issue did not change. Using the [react-native-background-geolocation](https://github.com/mauron85/react-native-background-geolocation) package works for me. Even if this is a different library, I just wanted to make sure that my device and android version is capable of doing it in general.

Hope to hear from the expo team soon. Unfortunately I will have to use the expo ejected version with a different library for now.

**Comment by BlerasKRT** [comment]
Same problem. I hope they can fix it soon

**Comment by krithigagupta** [comment]
Expo Team,

Will this be fixed any soon? We have the same issue as well and trying to fix it. Will this be available as part of future updates?

@krachtstefan, I see that the react-native-background-geolocation package has not been updated for a while now. What version of Expo SDK/React Native are you using to get this to work?

**Comment by krachtstefan** [comment]
@krithigagupta I still use the configuration that I specified when I created this issue. I just did an `expo eject` and the react-native-background-geolocation is working very well. For android, it requires you to purchase a license and you will get access to a private repo (last updated 12 days ago). I tested it with the public version and I had no problems either.

**Comment by krithigagupta** [comment]
@krachtstefan Does it give you consistent location updates even when the Android phone is on sleep mode for a long period of time - say more than 8 hours?

**Comment by krithigagupta** [comment]
@krachtstefan ALso, can you point me to what android license you purchased for getting access to the private repo, please?

**Comment by krachtstefan** [comment]
@kristoferlund 

Sorry, I have only now realized that there are two repos with the same name, I posted the wrong one. I used this one here: [https://github.com/transistorsoft/react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation). That's why the repo had no recent commits. It was the wrong one. SORRY!

My longest test was around 3 hours. No problems, you just have this sticky notification all the time but it works.

**Comment by krithigagupta** [comment]
@krachtstefan That helps a lot. I came across this package too and found this one to be more on the lines of what you were suggesting earlier. I will give this a try.

**Comment by Zanchee** [comment]
Please move any future discussion of this issue to #9288 so that we can have it all in one place.

**Comment by arabold** [comment]
I have finally found a solution for my app. Similar to the reports here, the React Native location task simply stops receiving updates after about 5 minutes of the display being turned off. Turns out in my case the Expo Task Manager was the culprit. It simply stops firing the task once the device goes to sleep and will only run every 10 to 15 minutes from there on. Not useful for an app that needs real-time location updates.

I've submitted a separate bug report as this seems to be a problem of the Expo Task Manager (`expo-task-manager`), not the `expo-location` module itself: https://github.com/expo/expo/issues/14076

The above issue report also contains a `.patch` file to patch your local installation with a workaround.

**Comment by hbel** [comment]
So, the discussion was moved to #9288, which is now closed, but did not fix this issue at all?

**Comment by arabold** [comment]
Still shouldn't be closed

**Comment by mcottingham** [comment]
Seems this issue is still persistent.  Is there any update from the expo team as to when this may be addressed?

**Comment by rei-shaholli** [comment]
+1 here.  This is what i'm doing and am not getting location updates in android when the app is put in the background.
`await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
            accuracy: Location.Accuracy.Highest,
            showsBackgroundLocationIndicator: true,
            foregroundService: {
                notificationTitle: "Location Tracking",
                notificationBody: "Your location is being tracked.",
                notificationColor: "#fff"
            }
        });`
      app.json
      `    "android": {
      "useNextNotificationsApi": true,
      "permissions": ["ACCESS_COARSE_LOCATION", "ACCESS_FINE_LOCATION", "ACCESS_BACKGROUND_LOCATION", "CAMERA", "FOREGROUND_SERVICE"],
    
    },`

**Comment by Patafix** [comment]
Same problem here
