### ISSUE TITLE
the app is displayed very small on the iPad

### ISSUE THREAD

**Issue by AKclown** [expo/expo#9204]
question:

  [Apple app connect-Test Flight] There is a problem with the resolution of the downloaded app, the app is displayed very small on the iPad

surroundings：

  "expo": "^38.0.0",
  "react-native": "0.62.2",
   iPad 2019 Wi-Fi 10.2“

view：
![image](https://user-images.githubusercontent.com/33648653/87388436-61f04c00-c5d7-11ea-96e3-81cd43ce2bb1.png)

**Comment by OscarYuen** [comment]
You need to configure `supportsTablet` to `true` in app.json
https://docs.expo.io/versions/latest/config/app/

**Comment by byCedric** [comment]
Hi @AKclown, like Oscar mentioned, you need to configure this in your app manifest. Please [check this guide](https://docs.expo.io/distribution/app-stores/#make-sure-your-app-works-on-many) to see if you are missing something else.

Hope it helps!

**Comment by AKclown** [comment]
Thank you solved
