### ISSUE TITLE
The method or property Expo.Notifications.setBadgeNumberAsync is not available on android, are you sure you’ve linked all the native dependencies properly?

### ISSUE THREAD

**Issue by 026binit** [expo/expo#9206]
### Summary of Issue 

Expo.Notifications.setBadgeNumberAsync throws error on android. i have wrapped inside Platfor.os === "ios" but still error occurs.
i have wrapped Notifications.setBadgeNumberAsync(0) inside Platform.OS === "ios" but still throws error.
if (
      this.state.appState.match(/inactive|background/) &&
      nextAppState === "active" &&
      Platform.OS === "ios"
    ) {
      Notifications.setBadgeNumberAsync(0);
    }

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

expo SDK version : 35
platform : Android

**Comment by AdamJNavarro** [comment]
Hey @026binit,

As the documentation states, this method is not available on Android and it will reject so this is expected behavior. If you need Android support, you'll need to upgrade to SDK38 and use the new `expo-notifications` module.

Cheers,
Adam

**Comment by 026binit** [comment]
Thanks @adamjnav does checking the platform will not get rid of the error?

I am still on 35 and want to get rid of this one until i go with 38

i am checking platform.OS === "ios" in the code.

**Comment by Alamut98** [comment]
i too got the same error. i checked the platform iOS but still error permises.Is there any solution?
