### ISSUE TITLE
Feature request: include randombytes in Expo

### ISSUE THREAD

**Issue by NateFerrero** [expo/expo#921]
https://github.com/mvayngrib/react-native-randombytes

This is not in Expo by default and causes the following error:

![image](https://user-images.githubusercontent.com/688553/32418926-57009d1c-c22f-11e7-81b4-e3f5e1b0ac7b.png)

**Comment by dikaiosune** [comment]
Hi! We're trying to keep feature requests on [Canny](https://expo.canny.io), and there's an existing request over there: https://expo.canny.io/feature-requests/p/crypto-api.
