### ISSUE TITLE
[expo-image-picker] Jumpy animation at bottom of screen when the picker is closing

### ISSUE THREAD

**Issue by lewazo** [expo/expo#9214]
### Summary of Issue
On iOS, When cancelling in the image library or selecting a picture with the option `allowsEditing` set to false, there is a glitch or flicker happening on the bottom of the screen when the closing animation ends. This happens on bare and also on a brand new `expo init` managed workflow app. When `allowsEditing` is set to true this doesn't happen, I guess because there is an extra screen used for the cropping.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.22.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
      Yarn: 1.6.0 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.22.1
```

### Reproducible Demo
It happens with the provided code at https://docs.expo.io/versions/latest/sdk/imagepicker/ and the snack on iOS 13.
 
### Steps to Reproduce

- Create a new expo app `expo init MyApp`.
- Install image picker `expo install expo-image-picker`
- Replace the content of app.js with the example provided on the Expo doc.
- Start the app `expo start`.

Tested on iOS simulator with iPhone X and iOS 13 and physical iPhone 6S on iOS 13.

Note : This same behaviour happens in other React Native image picker libraries. `react-native-image-picker` and `react-native-image-crop-picker` both reacts the same way as this one.

### Expected Behavior vs Actual Behavior
Closing transition should be slick, rather than the jumpy behaviour. Pay attention to the bottom of the screen in the following gif.

![Screen Recording 2020-07-14 at 4 29 10 PM](https://user-images.githubusercontent.com/14063312/87474557-45610d80-c5f1-11ea-8d3d-827b90773648.gif)

**Comment by brentvatne** [comment]
this seems like it might be a bug with `UIImagePickerController` - which is part of the ios standard library. if someone wants to verify this you can create a simple native ios app that invokes this control and compare the result. the code around dismissing the `UIImagePickerController` is pretty straightforward: https://github.com/expo/expo/blob/75d29fa3f8a2f8cb7b8cb54797dd50ebec2e3b6e/packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m#L428-L436

**Comment by EvanBacon** [comment]
This does appear to be a common issue. If you are dissatisfied with the performance, you can create a custom media picker using media library API https://docs.expo.io/versions/latest/sdk/media-library/
