### ISSUE TITLE
expo build:android java.lang.ClassNotFoundException: host.exp.exponent.taskManager.ExpoHeadlessAppLoader

### ISSUE THREAD

**Issue by fullhdpixel** [expo/expo#9215]
### Summary of Issue 

App works perfectly fine in development and production mode, however when the app is build using expo and then downloaded & installed the app immediately crashes

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.22.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.1
```

Logs: https://pastebin.com/raw/kq8EmP09

### Reproducible Demo

git clone https://github.com/fullhdpixel/vegan_client
cd src/vegancore
git clone https://github.com/fullhdpixel/vegan-core .

### Steps to Reproduce

yarn install and yarn web should work fine (also launching on android/iOS device). Then publishing it and downloading the signed app does not work

### Expected Behavior vs Actual Behavior

Of course the app should not immediately crash as it does before signing it and creating either a standalone app or a bundle.

**Comment by brentvatne** [comment]
did you use `expo build` to produce the app or what? this is a bare app and so you cannot use `expo build`

**Comment by fullhdpixel** [comment]
@brentvatne Hi, this should actually be a managed app. I only used js/typescript during development. Did I actually create a bare app? How do I now turn to a managed app.

**Comment by brentvatne** [comment]
you can delete the ios and android directories and remove react-native-unimodules from your package.json. i'm not sure how you created the project - maybe you ran `create-react-native-app` or maybe you did `expo init` and chose a bare template. web works the same in managed and bare apps. it looks like you're using `react-native-flurry-sdk` which is not supported in the managed workflow

**Comment by fullhdpixel** [comment]
Thanks a lot. I have removed the package entry and the directories. Yes this issue is directly related to creating a bare workflow app while it should have been a managed workflow.
