### ISSUE TITLE
[lottie-react-native][Android] TypeError: undefined is not an object (evaluating '_reactNative.UIManager.LottieAnimationView.Commands') after upgrade Expo 38

### ISSUE THREAD

**Issue by hieu292** [expo/expo#9216]
### Summary of Issue 
I have an issue with Lottie on Android (IOS works normally) TypeError: undefined is not an object (evaluating '_reactNative.UIManager.LottieAnimationView.Commands') when after upgrade expo 38. Currently, "lottie-react-native": "~2.6.1" in package.json

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v10.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.3.9 => 4.3.9 
    npmGlobalPackages:
      expo-cli: 3.21.13

### Expected Behavior vs Actual Behavior
Lottie works normally,

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by brentvatne** [comment]
here's an example of lottie working as expected on ios and android in sdk38: https://snack.expo.io/@notbrent/lottie-example?platform=android
