### ISSUE TITLE
Error: Possible Unhandled Promise Rejection (id: 0): TypeError: Network Request failed

### ISSUE THREAD

**Issue by itggot-arvid-nilber** [expo/expo#922]
Hi! While I was trying to make a Weather app using Expo, I stumbled across this error message while trying to fetch some data from openweathermaps api. I googled it and the answer I got was to change some lines in Info.plist. But using Expo there is no Info.plist. Is there any workaround? 
`Possible Unhandled Promise Rejection (id: 0): TypeError: Network Request failed`

**Comment by terribleben** [comment]
There is [a way](https://docs.expo.io/versions/latest/guides/configuration.html#infoplist) to make changes to info.plist, but I think it's unlikely that this is the solution to your problem. We already enable arbitrary network requests in Expo. Can you post more information about the error, or some code to reproduce the issue?

**Comment by itggot-arvid-nilber** [comment]
I found the issue. In the rooturl I forgot to add http:// in front of the url. Silly mistakes

**Comment by dikaiosune** [comment]
Glad to hear this is resolved!

**Comment by Apollo725** [comment]
I have same issue, and I added also http:// in the front of the url, I used Ruby on Rails on my local machine for backend, API is working on POSTMAN but for now not working on Android Emulator (Genymotion or Android Studio). I use MacOS. could you help me?

**Comment by ps0305** [comment]
having same issue with iPhone Emulator(Xcode) on Mac mini.

**Comment by abuammar** [comment]
@Apollo725 i to have the same issue. is your issue resolved ?
