### ISSUE TITLE
Cannot read property 'measureInWindow' of undefined

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/expo#9221]
## 🐛 Bug Report

**Issue:**
I am upgrading from Expo SDK 37 to Expo SDK 38. Directly after the upgrade I am facing the following issue. 

TypeError: TaskQueue: Error with task : Cannot read property 'measureInWindow' of undefined.

When I search my app's root folder I am not finding any instance of a 'measureInWindow', so I can not pinpoint where the error is coming from.

**ios error output:**
TypeError: Cannot read property 'measureInWindow' of undefined

This error is located at:
    in SafeView (at withOrientation.js:50)
    in withOrientation (at TabBarBottom.js:234)
    in RCTView (at createAnimatedComponent.js:144)
    in AnimatedComponent (at createAnimatedComponent.js:194)
    in ForwardRef(AnimatedComponentWrapper) (at TabBarBottom.js:233)
    in TabBarBottom (at withOrientation.js:30)
    in withOrientation (at TabView.js:112)
    in RCTView (at TabViewAnimated.js:194)
    in TabViewAnimated (at TabView.js:192)
    in TabView (at withCachedChildNavigation.js:69)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:34)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at SceneView.js:17)
    in SceneView (at ResourceSavingSceneView.js:55)
    in RCTView (at ResourceSavingSceneView.js:48)
    in RCTView (at ResourceSavingSceneView.js:39)
    in ResourceSavingSceneView (at TabView.js:35)
    in RCTView (at TabViewPagerScroll.js:150)
    in RCTScrollContentView (at ScrollView.js:1063)
    in RCTScrollView (at ScrollView.js:1196)
    in ScrollView (at TabViewPagerScroll.js:128)
    in TabViewPagerScroll (at TabViewAnimated.js:71)
    in RCTView (at TabViewAnimated.js:194)
    in TabViewAnimated (at TabView.js:192)
    in TabView (at withCachedChildNavigation.js:69)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:34)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at SceneView.js:17)
    in SceneView (at ResourceSavingSceneView.js:55)
    in RCTView (at ResourceSavingSceneView.js:48)
    in RCTView (at ResourceSavingSceneView.js:39)
    in ResourceSavingSceneView (at TabView.js:35)
    in RCTView (at TabViewPagerPan.js:251)
    in RCTView (at createAnimatedComponent.js:144)
    in AnimatedComponent (at createAnimatedComponent.js:194)
    in ForwardRef(AnimatedComponentWrapper) (at TabViewPagerPan.js:238)
    in TabViewPagerPan (at TabView.js:127)
    in RCTView (at TabViewAnimated.js:194)
    in TabViewAnimated (at TabView.js:192)
    in TabView (at withCachedChildNavigation.js:69)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:34)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at App.js:43)
    in RCTView (created by Rehydrate)
    in Rehydrate (created by Rehydrated)
    in Rehydrated (at App.js:42)
    in ApolloProvider (at App.js:41)
    in WithProvider (created by ExpoRoot)
    in RNCAppearanceProvider (at src/index.tsx:70)
    in AppearanceProvider (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at AppContainer.js:109)
    in DevAppContainer (at AppContainer.js:124)
    in RCTView (at AppContainer.js:135)
    in AppContainer (at renderApplication.js:39)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

ios

### Reproducible Demo

**package.json:**

  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/cli-debugger-ui": "^4.9.0",
    "@react-native-community/netinfo": "5.9.2",
    "@redux-offline/redux-offline": "^2.5.2-native.0",
    "aws-amplify": "^3.0.19",
    "aws-amplify-react-native": "^4.2.1",
    "aws-appsync": "^3.0.4",
    "aws-appsync-react": "^4.0.0",
    "aws-sdk": "git://github.com/chrisradek/aws-sdk-js.git#fix-babel7",
    "babel-preset-expo": "^8.2.3",
    "country-code-lookup": "0.0.17",
    "country-list": "^2.2.0",
    "countrycodes": "0.0.5",
    "expo": "^38.0.0",
    "expo-av": "~8.2.1",
    "expo-cli": "^3.21.13",
    "expo-contacts": "~8.2.1",
    "expo-image-picker": "~8.3.0",
    "expo-intent-launcher": "~8.2.1",
    "expo-location": "~8.2.1",
    "expo-permissions": "~9.0.1",
    "expo-sms": "~8.2.1",
    "expo-status-bar": "^1.0.0",
    "expo-web-browser": "~8.3.1",
    "graphql": "^14.7.0",
    "graphql-tag": "^2.9.2",
    "immutability-helper": "^3.0.0",
    "lodash": "^4.17.10",
    "react": "16.11.0",
    "react-apollo": "^2.5.6",
    "react-dom": "16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-aws3": "0.0.8",
    "react-native-date-picker": "^2.7.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-fit-image": "^1.5.5",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-native-input-scroll-view": "^1.7.1",
    "react-native-inviewport": "^1.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^11.3.1",
    "react-native-modal-datetime-picker": "^7.5.0",
    "react-native-modal-dropdown": "^0.7.0",
    "react-native-phone-input": "^0.2.4",
    "react-native-photo-view-ex": "^1.0.4",
    "react-native-picker-select": "^7.0.0",
    "react-native-search-box": "0.0.19",
    "react-native-searchbar": "^1.15.0",
    "react-native-timeago": "^0.4.0",
    "react-native-view-more-text": "^2.1.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "1.5.11",
    "react-navigation-addons": "0.0.0",
    "react-number-format": "^4.0.8",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "recompose": "^0.30.0",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "shuffle-array": "^1.0.1",
    "stripe-client": "^1.1.5",
    "uuid": "^3.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "^8.2.3"
  },
 
### Expected Behavior vs Actual Behavior

Expected behavior is that the app would not crash as in sdk 37 it was working fine. When reading through sdk 38 guides it does not seem that I should be having any breaking changes. Another notable issue is that I do not have any instance of the undefined variable in the app.

Thanks for the help!!!

**Comment by brentvatne** [comment]
see: https://github.com/react-navigation/react-native-safe-area-view/issues/118#issuecomment-628078811

you can use yarn resolutions to force react-navigation to install a more recent version of react-native-safe-area-view, or you can update to a more recent version of react-navigation. we don't document breaking changes in all libraries, eg: react-native-safe-area-view, because we don't track them all. we just let you know about breaking changes in our libraries

**Comment by mikeRChambers610** [comment]
Thanks a lot for the quick response Brent. Upgrading my react-navigation fixed the issue.

Now I will just need to continue adding the necessary packages to align with the upgrade. I appreciate the help.
