### ISSUE TITLE
expo start --web, not compiling 

### ISSUE THREAD

**Issue by klmop** [expo/expo#9229]

**Comment by byCedric** [comment]
Hi @klmop! I'm sorry to hear you are having issues with Expo. Unfortunately, we can't help you if you don't supply the information we need. If you think you found a bug, open a new issue and provide all information that we ask there (e.g. environment info, short issue description, steps to reproduce, etc). If you just have a question related to this, feel free to ask it on the [forums](https://forums.expo.io/) or [community slack](https://slack.expo.io/).
