### ISSUE TITLE
BarCodeScanner not reading (probably non-standard) PDF-417

### ISSUE THREAD

**Issue by germancardenasm** [expo/expo#9233]
## 🐛 Bug Report
BarCodeScanner not reading PDF-417 code
### Summary of Issue 
The BarCodeScanner is having problems reading a PDF-417 code from an ID used in my country that I need to read. The specifications for this bar code says it is a PDF417 with a 30% correction.
The component never read the codes in this ID at all.

Trying with other mobile apps as PDF417, and web services as https://demo.dynamsoft.com/DBR/BarcodeReaderDemo.aspx I got the code decoded.

Example images:
https://ibb.co/0ymX9GN
https://ibb.co/9GYvMDS

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Plataform: android / IOS

Expo CLI 3.20.3 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.10 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^4.0.6 => 4.3.9 
    npmGlobalPackages:
      expo-cli: 3.20.3

### Reproducible Demo

https://snack.expo.io/@gcardenasm/380485

 
### Expected Behavior vs Actual Behavior

Expected Behavior: Get the PDF-417 code decoded 
Actual Behavior: The component never reads the code provided by the ID type I need to read. Example images added above in summary issue.

**Comment by brentvatne** [comment]
i opened [this snack](https://snack.expo.io/?platform=android&name=Basic%20BarCodeScanner%20usage&sdkVersion=38.0.0&dependencies=expo-barcode-scanner&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv38.0.0%2Fbar-code-scanner.js) on my phone and scanned the example pdf417 barcode from https://en.wikipedia.org/wiki/PDF417 and it works as expected and also on my driver's license and random results from google image search. on ios and android.

it seems that something must be non-standard about the barcodes that you are scanning. perhaps the little circle in the bottom right of it is causing issues?

you may need to eject to find another library to solve this for you.
