### ISSUE TITLE
Hot reloading on web

### ISSUE THREAD

**Issue by vjsingh** [expo/expo#9235]
@EvanBacon Hot reloading doesn't appear to be working on web. I couldn't find any mention of it - is it supposed to be working? If not, where is the missing link and any idea of a timeline?

Thank you,

**Comment by brentvatne** [comment]
it uses live reload, not hot reload. @EvanBacon has been working on getting fast refresh working, he'll announce it on twitter and possibly on the expo blog when it's ready :)

https://twitter.com/baconbrix
https://twitter.com/expo

**Comment by vjsingh** [comment]
@brentvatne Awesome thanks for the quick response, got it.

Go @EvanBacon !! Fast refresh on web would be a game-changer for us.
