### ISSUE TITLE
Invariant Violation: "main" has not been registered

### ISSUE THREAD

**Issue by dbarnathan** [expo/expo#9237]
![WhatsApp Image 2020-07-15 at 6 26 11 PM](https://user-images.githubusercontent.com/54187596/87606374-d656e800-c6c8-11ea-8f30-221daaa1e1ad.jpeg)
Here's a screenshot of the error. I saw the other issue, and I tried every suggested method with no solution.

**Comment by brentvatne** [comment]
https://github.com/expo/fyi/blob/master/no-registered-application.md

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
