### ISSUE TITLE
Packager constantly recreating js bundle

### ISSUE THREAD

**Issue by vitalbone** [expo/expo#924]
Every time I `yarn start` the packager just keeps rebuilding the js bundle in quick succession, over and over again. Almost as soon as the js bundle reaches 100% it starts rebundling from 0% again. It makes it next to impossible to do any work. It happens for both the simulator and on an iOS device.

My Expo configuration is exactly as the 'Upgrading Your App' section of the [latest blog post](https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6) asks for. Plus I downgraded to `npm@4.x` and it still occurs.

![bundle-loop](https://user-images.githubusercontent.com/5966259/32430674-5638795e-c324-11e7-8f25-3ed9b2441070.gif)

**Comment by dikaiosune** [comment]
Hi! Where is this project located? Is it inside of a folder for something like Dropbox or iCloud?

**Comment by vitalbone** [comment]
Yes, yes it is. Will relocate. Thanks for being so prompt 🙂
