### ISSUE TITLE
BackgroundFetch never stop

### ISSUE THREAD

**Issue by bobov4** [expo/expo#9241]
**Environment**
Expo CLI 3.21.5 
npmPackages:
"expo": "^38.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
"expo-background-fetch": "^8.3.0",
"expo-task-manager": "~8.3.0"

I'm building an android app and want to track location in background on every 1 minute. We test it on expo client, it work perfectly, We can get current location when app is in background. But when we clear all apps, every 1 minute the "expo has stopped" popup will be shown and never stop until we test our app in expo client again. It seem like our background process not terminated when app is terminated.

**Steps to Reproduce**
`import React, { Component } from 'react';
import { AsyncStorage, View } from 'react-native';
import NetInfo from "@react-native-community/netinfo";
import { Notifications } from 'expo';
import * as TaskManager from "expo-task-manager";
import * as BackgroundFetch from 'expo-background-fetch';
import * as Location from 'expo-location';
const updateLocationBGName = 'update-location-background';

async function trackBackground() {
    try {
      var respLocation = await global.func.getLocation();
      console.log("Background update");
      if(respLocation.success){
        global.trackLocation.push({'latitude' : String(respLocation.location.coords.latitude), 'longitude': String(respLocation.location.coords.longitude) , 'date':new Date()});
        AsyncStorage.setItem('trackLocation', JSON.stringify(global.trackLocation));
      }
      return respLocation? BackgroundFetch.Result.NewData : BackgroundFetch.Result.NoData;
    } catch (err) {
      console.log(err)
      return BackgroundFetch.Result.Failed;
    }
}

async function initBackgroundFetch(taskName,taskFn,interval = 60) {
  await TaskManager.unregisterAllTasksAsync();
  try {
    if (!TaskManager.isTaskDefined(taskName)) {
      TaskManager.defineTask(taskName, taskFn);
    }
    await BackgroundFetch.registerTaskAsync(taskName, {minimumInterval: interval, stopOnTerminate: true, startOnBoot:false});
  } catch (err) {
    console.log("registerTaskAsync() failed:", err);
  }
}

initBackgroundFetch(updateLocationBGName, trackBackground, 60);

export default class Check extends Component {
......
}`

**Expected Behavior**
the background process stop when app is terminated and the "has stopped" popup never shown.

Sorry for my bad english.

**Comment by byCedric** [comment]
Hi @bobov4, thanks for the issue report. We found an issue within `expo-task-manager` that caused the problems you mentioned. I created an umbrella issue for that to keep track of. I'll close this issue in favor of that one.

Note, a fix is available in bare workflow already. 😄

**Comment by tjmeal** [comment]
May i ask how is it possible to do the opposite so our background process not terminated when app is terminated ? Cause the did happend to me today, i am using backround location > was killing the app > after a while the process were started again > but when logout and login back again it never happened again ?
