### ISSUE TITLE
 local authentication

### ISSUE THREAD

**Issue by RameshDev92** [expo/expo#9244]
## 🐛 Bug Report

###In Local authentication is there a way i can check if android device is secured by password pattern or fingerprint.
Currently the method
 LocalAuthentication.isEnrolledAsync()
is letting me know only finger prints enrolled or not but how can i know if there is password or pattern is available.

**Comment by byCedric** [comment]
Hi @RameshDev92! Unfortunately, that's not something you (or we) can implement. Google changed the local authentication system when they [introduced the Biometric Prompt](https://android-developers.googleblog.com/2019/10/one-biometric-api-over-all-android.html). They abstracted away a lot of authentication-method specifics, including checking if fingerprint is available for example. We can only check if we _can_ authenticate with one of the methods available on the device. And we can ask Android to use a pin or pattern as a fallback, when the user doesn't have any of the biometric auth methods.

Hope this helps!
