### ISSUE TITLE
expo-branch: package androidx.localbroadcastmanager.content does not exist

### ISSUE THREAD

**Issue by clems36** [expo/expo#9245]
### Summary of Issue

When I try to build my app for android, i'm running into this issue: 
` error: package androidx.localbroadcastmanager.content does not exist`
located in
`node_modules/expo-branch/android/src/main/java/io/branch/rnbranch/RNBranchModule.java`.

This error is triggered by the fact that `expo-branch/android/build.gradle` does not contain the following dependency:
`implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0`

This is weird because that line was added in [this commit](https://github.com/expo/expo/commit/8e0a8c17b86babdaa61645e47bd69d187d75678d) but after running `expo install expo-branch`, my dependencies look like this:
```
dependencies {
  unimodule 'unimodules-core'
  implementation 'com.facebook.react:react-native:+'
  api 'io.branch.sdk.android:library:4.1.0'
}
```

I currently have to manually add that dependency to fix the error.

### Environment 

```
Expo CLI 3.22.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^4.0.10 => 4.4.0
```
Target platform: Android

### Expected Behavior vs Actual Behavior

After running `expo install expo-branch`, the dependencies inside `expo-branch/android/build.gradle` should look like this:

```
dependencies {
  unimodule 'unimodules-core'
  implementation 'com.facebook.react:react-native:+'
  api 'io.branch.sdk.android:library:4.1.0'
  implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
}
```
instead of this:

```
dependencies {
  unimodule 'unimodules-core'
  implementation 'com.facebook.react:react-native:+'
  api 'io.branch.sdk.android:library:4.1.0'
}
```

**Comment by clems36** [comment]
@esamelson sorry to tag you in here but since you pushed that commit I thought you might help me with this.

**Comment by esamelson** [comment]
Hey @clems36 - thanks for noticing this and figuring out the issue! Would you be willing to submit a PR with the fix?

**Comment by clems36** [comment]
Hey @esamelson, I'd love to but that line `implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.0.0"` is already present in the project. It seems to be removed when installing the package.
