### ISSUE TITLE
FileSystem: Permission evaluation fails on ExternalFilesDirectory (Android)

### ISSUE THREAD

**Issue by hardcodet** [expo/expo#9247]
### Summary of Issue

I can't access or manipulate anything under Android's external files directory (`context.getExternalFilesDir)`) since expo's permission check evaluates this wrongly.

Justification for using external files: internal files have a quota attached (apparently around 3 GB). Users of my app potentially will store more files, so using internal storage (which is the document directory expo uses) is not an option.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Target: Android Galaxy S10, Android 10

```
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      expo: ^38.0.0 => 38.0.3
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```
 
### Steps to Reproduce

- Natively resolve the path of the external dir (not built into expo Filesystem): `this.reactApplicationContext.getExternalFilesDir(null);`
- do smth like `await fs.makeDirectoryAsync(externalDir + "/tmp", {intermediates: true});` - this will fail

Now, `makeDirectoryAsync` would eventually just invoke `File.makedirs()`. If I do that myself (without expo's permission check), this works just fine, since the app of course *does* have access to its own external files dir.

### Expected Behavior vs Actual Behavior

Permission check should not fail rather than throwing a `file:///path/to/external/dir isn't writable` exception.

**Comment by cruzach** [comment]
Hi- we keep github reserved for bug reports, so I'm going to close this issue. This is actually an [open feature request on our canny](https://expo.canny.io/feature-requests/p/add-externaldirectory-to-expofilesystem), so you should upvote it there if you want to see it make its way into the SDK!
