### ISSUE TITLE
[docs] Add information about reserved names to Firebase Analytics

### ISSUE THREAD

**Issue by vjsingh** [expo/expo#9248]
It appears that certain event names are reserved in Firebase Analytics, and manually logging them will result in weird behavior.

I found this out the hard way by attempting to log `ad_impression` and `ad_click` events, which happened to correspond to reserved event names.

Perhaps a note about this, or even a list of reserved names could be added to the docs?

I'm sure the information is somewhere in the Firebase docs. But with some other libraries which Expo has integrated, I've greatly appreciated being able to find the information I need from the expo docs (e.g. notifications)

**Comment by cruzach** [comment]
Great idea! thanks for pointing this out, I'll update the docs

The list of reserved event names can be found here - https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event

**Comment by cruzach** [comment]
these are already included in the docs- https://docs.expo.io/versions/latest/sdk/firebase-analytics/#logevent

**Comment by vjsingh** [comment]
@cruzach D'oh! Of course they are. My fault.

Perhaps it would be nice to spit out an error as well if a user tries to use a reserved event name?
