### ISSUE TITLE
No Support for WAV/LinearPCM, AIFF and FLAC recording in android.

### ISSUE THREAD

**Issue by aup8497** [expo/expo#9252]
## 🐛 Bug Report
No Support for WAV/LinearPCM, AIFF and FLAC recording in android.

### Summary of Issue 
No Support for WAV/LinearPCM, AIFF and FLAC recording in android.

**Comment by byCedric** [comment]
Hi @aup8497, thanks for the feature request. Unfortunately, we only keep track of github issues in this repository. If you want to open a feature request to include these formats, please create a [new feature request on Canny](https://expo.canny.io/feature-requests) and promote it. That way we might include it in a future road map. If you are able to implement this yourself, feel free to contribute 😄 

Hope it helps!
