### ISSUE TITLE
await Linking.getInitialURL(); return wrong deep link in Build APK

### ISSUE THREAD

**Issue by imdeepakchahar** [expo/expo#9253]
**Dependencies**
`"expo": "~37.0.3",`

Build Apk with
expo build:android

My code: 
`let initialUrl = await Linking.getInitialURL();`

Problem is: initialUrl returning value `https://expo.io:443/@imchahardeepak/greenapple` in build apk
and when I open this URL then my project link opens.. not the app, so what I do?

By browsing the link which is given by await Linking.getInitialURL(); .. app should be open but my expo project URL is opening

**Comment by brentvatne** [comment]
please follow the issue template:

## 🐛 Bug Report

### Summary of Issue 


### Environment - output of `expo diagnostics` & the platform(s) you're targeting


### Reproducible Demo



 
### Steps to Reproduce


### Expected Behavior vs Actual Behavior

**Comment by imdeepakchahar** [comment]
I didn't understand your question? what actually you want to know? I already mentioned  my problem above and steps and required information above

**Comment by brentvatne** [comment]
please create a new issue when you have time to follow the issue template, thanks!
