### ISSUE TITLE
Expo 22 failing with "Module AppRegistry is not a registered callable module"

### ISSUE THREAD

**Issue by orloffmarket** [expo/expo#926]
After attempting to upgrade to Expo 22.0.0 existing builds (previous testflight on 21) broke, and all builds are broken with 

https://exp.host:443/@aorloff/APPNAME
"Module AppRegistry is not a registered callable module (calling runApplication)" (code 2)

Even though it loads up fine in XDE / Expo Client.  Trying to revert to SDK 21 now and unable to do so.  Totally stuck !

**Comment by dikaiosune** [comment]
Hi! This is usually caused by a version mismatch between JS & native. Can you share your package.json and app.json?

**Comment by orloffmarket** [comment]
app.json

{
  "expo": {
    "name": "APPNAME",
    "slug": "appname",
    "sdkVersion": "21.0.0",
    "version": "0.1.21",
    "orientation": "default",
    "primaryColor": "#cccccc",
    "icon": "./assets/images/app_icon.png",
    "notification": {
      "icon": "./assets/images/app_icon.png",
      "color": "#000000"
    },
    "privacy": "unlisted",
    "loading": {
      "icon": "./assets/images/app_icon.png",
      "hideExponentText": true
    },
    "packagerOpts": {
      "assetExts": [
        "ttf",
        "mp4",
        "jpg"
      ]
    },
    "ios": {
      "bundleIdentifier": "com.example",
      "buildNumber": "63",
      "icon": "./assets/images/app_icon.png",
      "config": {
        "usesNonExemptEncryption": false,
        "googleSignIn": {
          "reservedClientId": ""
        }
      },
      "supportsTablet": false,
      "infoPlist": {
      }
    },
    "android": {
      "package": "com.example.app",
      "versionCode": 63,
      "config": {
        "googleMaps": {
          "apiKey": ""
        },
        "googleSignIn": {
          "apiKey": "",
          "certificateHash": ""
        },
      },
      "permissions": ["ACCESS_FINE_LOCATION"]
    }
  }
}


package.json

{
  "name": "APPNAME-MobileApp",
  "version": "0.4.1",
  "description": "using Expo.io",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "test": "node ./node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "babel-preset-expo": "^3.0.0",
    "chalkdust": "1.1.0",
    "expo": "^21.0.0",
    "firebase": "^4.6.1",
    "hoist-non-react-statics": "^2.3.1",
    "jsx-control-statements": "3.2.8",
    "lodash": "4.17.4",
    "mobx": "3.3.1",
    "mobx-persist": "^0.4.1",
    "mobx-react": "^4.3.4",
    "moment": "^2.19.1",
    "prop-types": "^15.6.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
    "react-native-action-button": "^2.8.1",
    "react-native-app-link": "0.4.0",
    "react-native-collapsible": "0.9.0",
    "react-native-communications": "2.2.1",
    "react-native-dropdownalert": "3.1.2",
    "react-native-elevated-view": "^0.0.5",
    "react-native-fade-in-image": "^1.2.0",
    "react-native-flex-image": "^1.1.0",
    "react-native-gifted-chat": "^0.3.0",
    "react-native-google-places-autocomplete": "^1.3.6",
    "react-native-image-pan-zoom": "^2.0.7",
    "react-native-json-tree": "^1.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.4.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-notifyer": "^0.9.3",
    "react-native-progress-circle": "2.0.0",
    "react-native-snap-carousel": "^3.4.0",
    "react-native-swipeable": "^0.6.0",
    "react-native-swiper": "1.5.13",
    "react-navigation": "^1.0.0-beta.19",
    "styled-components": "^2.2.3",
    "tcomb-form-native": "^0.6.11",
    "tinycolor2": "1.4.1",
    "validator": "^9.1.1"
  },
  "devDependencies": {
    "jest-expo": "^21.0.0"
  }
}

**Comment by dikaiosune** [comment]
Thanks! Can you paste the contents of `node_modules/expo/package.json` and `node_modules/react-native/package.json`?

**Comment by orloffmarket** [comment]
node_modules/expo/package.json

{
  "name": "expo",
  "version": "21.0.3",
  "description": "The Expo SDK",
  "main": "src/Expo.js",
  "files": [
    "src",
    "tools",
    "AppEntry.js"
  ],
  "scripts": {
    "lint": "eslint src tools",
    "prepublishOnly": "proofread",
    "test": "jest --watch"
  },
  "jest": {
    "preset": "jest-expo",
    "clearMocks": true,
    "testRegex": "/__tests__/.*-test\\.js$"
  },
  "eslintConfig": {
    "root": true,
    "extends": "universe/native"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/expo/expo-sdk.git"
  },
  "keywords": [
    "expo"
  ],
  "author": "Expo",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/expo/expo-sdk/issues"
  },
  "homepage": "https://github.com/expo/expo-sdk",
  "dependencies": {
    "@expo/vector-icons": "^5.0.0",
    "babel-preset-expo": "^3.0.0",
    "fbemitter": "^2.1.1",
    "lodash.map": "^4.6.0",
    "lodash.zipobject": "^4.1.3",
    "lottie-react-native": "2.2.0",
    "md5-file": "^3.1.1",
    "pretty-format": "^20.0.3",
    "prop-types": "^15.5.10",
    "qs": "^6.5.0",
    "react-native-branch": "2.0.0-beta.3",
    "react-native-gesture-handler": "1.0.0-alpha.22",
    "react-native-maps": "0.15.3",
    "react-native-svg": "5.3.0",
    "uuid-js": "^0.7.5",
    "websql": "https://github.com/expo/node-websql/archive/18.0.0.tar.gz"
  },
  "devDependencies": {
    "@expo/npm-proofread": "^1.0.1",
    "eslint": "^4.6.1",
    "eslint-config-universe": "^1.0.5",
    "flow-bin": "^0.54.0",
    "jest-expo": "^21.0.1",
    "prettier": "^1.6.0",
    "react": "16.0.0-alpha.12",
    "react-native": "expo/react-native#sdk-21"
  }
}


node_modules/react-native/package.json

{
  "name": "react-native",
  "version": "0.48.4",
  "description": "A framework for building native apps using React",
  "license": "BSD-3-Clause",
  "repository": {
    "type": "git",
    "url": "git@github.com:facebook/react-native.git"
  },
  "engines": {
    "node": ">=4"
  },
  "jest": {
    "transform": {
      ".*": "./jest/preprocessor.js"
    },
    "setupFiles": [
      "./jest/setup.js"
    ],
    "timers": "fake",
    "moduleNameMapper": {
      "^React$": "<rootDir>/Libraries/react-native/React.js",
      "^[./a-zA-Z0-9$_-]+\\.png$": "RelativeImageStub"
    },
    "testPathIgnorePatterns": [
      "Libraries/Renderer",
      "/node_modules/",
      "/website/",
      "local-cli/templates/"
    ],
    "haste": {
      "defaultPlatform": "ios",
      "providesModuleNodeModules": [
        "react-native"
      ],
      "platforms": [
        "ios",
        "android"
      ]
    },
    "modulePathIgnorePatterns": [
      "/node_modules/(?!react|fbjs|react-native|react-transform-hmr|core-js|promise)/",
      "node_modules/react/node_modules/fbjs/",
      "node_modules/react/lib/ReactDOM.js",
      "node_modules/fbjs/lib/Map.js",
      "node_modules/fbjs/lib/Promise.js",
      "node_modules/fbjs/lib/fetch.js",
      "node_modules/fbjs/lib/ErrorUtils.js",
      "node_modules/fbjs/lib/URI.js",
      "node_modules/fbjs/lib/Deferred.js",
      "node_modules/fbjs/lib/PromiseMap.js",
      "node_modules/fbjs/lib/UserAgent.js",
      "node_modules/fbjs/lib/areEqual.js",
      "node_modules/fbjs/lib/base62.js",
      "node_modules/fbjs/lib/crc32.js",
      "node_modules/fbjs/lib/everyObject.js",
      "node_modules/fbjs/lib/fetchWithRetries.js",
      "node_modules/fbjs/lib/filterObject.js",
      "node_modules/fbjs/lib/flattenArray.js",
      "node_modules/fbjs/lib/forEachObject.js",
      "node_modules/fbjs/lib/isEmpty.js",
      "node_modules/fbjs/lib/nullthrows.js",
      "node_modules/fbjs/lib/removeFromArray.js",
      "node_modules/fbjs/lib/resolveImmediate.js",
      "node_modules/fbjs/lib/someObject.js",
      "node_modules/fbjs/lib/sprintf.js",
      "node_modules/fbjs/lib/xhrSimpleDataSerializer.js",
      "node_modules/jest-cli",
      "node_modules/react/dist",
      "node_modules/fbjs/.*/__mocks__/",
      "node_modules/fbjs/node_modules/",
      "<rootDir>/website/"
    ],
    "unmockedModulePathPatterns": [
      "node_modules/react/",
      "node_modules/regenerator-runtime/",
      "Libraries/Renderer",
      "promise",
      "source-map",
      "fastpath",
      "denodeify",
      "fbjs",
      "sinon"
    ]
  },
  "main": "Libraries/react-native/react-native-implementation.js",
  "files": [
    ".flowconfig",
    "android",
    "cli.js",
    "flow",
    "init.sh",
    "scripts/ios-configure-glog.sh",
    "scripts/ios-install-third-party.sh",
    "scripts/launchPackager.bat",
    "scripts/launchPackager.command",
    "scripts/packager.sh",
    "scripts/react-native-xcode.sh",
    "jest-preset.json",
    "jest",
    "lib",
    "rn-get-polyfills.js",
    "setupBabel.js",
    "Libraries",
    "LICENSE",
    "local-cli",
    "packager",
    "PATENTS",
    "react.gradle",
    "React.podspec",
    "React",
    "ReactAndroid",
    "ReactCommon",
    "README.md",
    "third-party-podspecs"
  ],
  "scripts": {
    "test": "jest",
    "flow": "flow",
    "lint": "eslint .",
    "start": "/usr/bin/env bash -c './scripts/packager.sh \"$@\" || true' --",
    "test-android-setup": "docker pull containership/android-base:latest",
    "test-android-build": "docker build -t react/android -f ContainerShip/Dockerfile.android .",
    "test-android-run-instrumentation": "docker run --cap-add=SYS_ADMIN -it react/android bash ContainerShip/scripts/run-android-docker-instrumentation-tests.sh",
    "test-android-run-unit": "docker run --cap-add=SYS_ADMIN -it react/android bash ContainerShip/scripts/run-android-docker-unit-tests.sh",
    "test-android-run-e2e": "docker run --privileged -it react/android bash ContainerShip/scripts/run-ci-e2e-tests.sh --android --js",
    "test-android-all": "npm run test-android-build && npm run test-android-run-unit && npm run test-android-run-instrumentation && npm run test-android-run-e2e",
    "test-android-instrumentation": "npm run test-android-build && npm run test-android-run-instrumentation",
    "test-android-unit": "npm run test-android-build && npm run test-android-run-unit",
    "test-android-e2e": "npm run test-android-build && npm run test-android-run-e2e"
  },
  "bin": {
    "react-native": "local-cli/wrong-react-native.js"
  },
  "peerDependencies": {
    "react": "16.0.0-alpha.12"
  },
  "dependencies": {
    "absolute-path": "^0.0.0",
    "art": "^0.10.0",
    "async": "^2.4.0",
    "babel-core": "^6.24.1",
    "babel-generator": "^6.24.1",
    "babel-plugin-external-helpers": "^6.18.0",
    "babel-plugin-syntax-trailing-function-commas": "^6.20.0",
    "babel-plugin-transform-async-to-generator": "6.16.0",
    "babel-plugin-transform-class-properties": "^6.18.0",
    "babel-plugin-transform-flow-strip-types": "^6.21.0",
    "babel-plugin-transform-object-rest-spread": "^6.20.2",
    "babel-polyfill": "^6.20.0",
    "babel-preset-es2015-node": "^6.1.1",
    "babel-preset-fbjs": "^2.1.4",
    "babel-preset-react-native": "^2.0.0",
    "babel-register": "^6.24.1",
    "babel-runtime": "^6.23.0",
    "babel-traverse": "^6.24.1",
    "babel-types": "^6.24.1",
    "babylon": "^6.17.0",
    "base64-js": "^1.1.2",
    "bser": "^1.0.2",
    "chalk": "^1.1.1",
    "commander": "^2.9.0",
    "concat-stream": "^1.6.0",
    "connect": "^2.8.3",
    "core-js": "^2.2.2",
    "create-react-class": "^15.5.2",
    "debug": "^2.2.0",
    "denodeify": "^1.2.1",
    "envinfo": "^3.0.0",
    "errno": ">=0.1.1 <0.2.0-0",
    "event-target-shim": "^1.0.5",
    "fbjs": "0.8.12",
    "fbjs-scripts": "^0.7.0",
    "form-data": "^2.1.1",
    "fs-extra": "^1.0.0",
    "glob": "^7.1.1",
    "graceful-fs": "^4.1.3",
    "inquirer": "^3.0.6",
    "jest-haste-map": "20.1.0-delta.4",
    "json-stable-stringify": "^1.0.1",
    "json5": "^0.4.0",
    "left-pad": "^1.1.3",
    "lodash": "^4.16.6",
    "merge-stream": "^1.0.1",
    "metro-bundler": "^0.11.0",
    "mime": "^1.3.4",
    "mime-types": "2.1.11",
    "minimist": "^1.2.0",
    "mkdirp": "^0.5.1",
    "node-fetch": "^1.3.3",
    "npmlog": "^2.0.4",
    "opn": "^3.0.2",
    "optimist": "^0.6.1",
    "plist": "^1.2.0",
    "pretty-format": "^4.2.1",
    "promise": "^7.1.1",
    "prop-types": "^15.5.8",
    "react-clone-referenced-element": "^1.0.1",
    "react-devtools-core": "^2.5.0",
    "react-timer-mixin": "^0.13.2",
    "react-transform-hmr": "^1.0.4",
    "rebound": "^0.0.13",
    "regenerator-runtime": "^0.9.5",
    "request": "^2.79.0",
    "rimraf": "^2.5.4",
    "sane": "~1.4.1",
    "semver": "^5.0.3",
    "shell-quote": "1.6.1",
    "source-map": "^0.5.6",
    "stacktrace-parser": "^0.1.3",
    "temp": "0.8.3",
    "throat": "^4.1.0",
    "whatwg-fetch": "^1.0.0",
    "wordwrap": "^1.0.0",
    "write-file-atomic": "^1.2.0",
    "ws": "^1.1.0",
    "xcode": "^0.9.1",
    "xmldoc": "^0.4.0",
    "xpipe": "^1.0.5",
    "xtend": ">=4.0.0 <4.1.0-0",
    "yargs": "^6.4.0"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^3.19.0",
    "eslint-config-fb-strict": "^20.0.3",
    "eslint-config-fbjs": "^1.1.1",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-flowtype": "^2.33.0",
    "eslint-plugin-prettier": "2.1.1",
    "eslint-plugin-react": "^7.0.1",
    "flow-bin": "^0.51.0",
    "jest": "20.1.0-delta.4",
    "jest-phabricator": "20.1.0-delta.4",
    "jest-repl": "20.1.0-delta.4",
    "jest-runtime": "20.1.0-delta.4",
    "mock-fs": "^4.4.1",
    "prettier": "1.5.2",
    "react": "16.0.0-alpha.12",
    "react-test-renderer": "16.0.0-alpha.12",
    "shelljs": "0.6.0",
    "sinon": "^2.2.0"
  }
}

**Comment by orloffmarket** [comment]
Looks like it was an issue related to updating to SDK 22, working through those issues now so closing this.

**Comment by sujit13666** [comment]
Is it resolved? I am stuck here too. Please advice what to do.

**Comment by orloffmarket** [comment]
Once you upgrade to a newer expo version you have to upgrade, expo will always give the latest version code JS to download iirc.

**Comment by mustafaghali** [comment]
this happened for me after upgrading to expo SDK 27.0.0 on production mode only
I tried switching to yarn and clearing the packager cache
yarn start --reset-cache
and it seems it solved it for me
