### ISSUE TITLE
symbolicStack error is being shown randomly 

### ISSUE THREAD

**Issue by Harshpinder-singh** [expo/expo#9268]
console.error: There was a problem sending log messages to your development environment TypeError: 
symbolicatedStack.map is not a function. (In 'symbolicatedStack.map(removeProjectRoot)', 
'symbolicatedStack.map' is undefined  

getting this error

**Comment by byCedric** [comment]
Hi @Harshpinder-singh, thanks for the issue report. Unfortunately, without context or additional information, we can't help you find the issue. You can try if this issue persists in a new project or remove/install your `node_modules`. If you think that this is an issue with Expo, please open a new issue and fill in the template.

Hope it helps!

**Comment by filozofer** [comment]
@Harshpinder-singh Did you found a solution to your problem ? I'm getting the same exact error when launching my app. No more clue !

**Comment by Harshpinder-singh** [comment]
@filozofer yeah i found something, i am using expo sdk 36 and react native version is 0.62.1 that was also giving the version mismatch error so i lowered the react native verison to 0.61.4  and there is react-native-svg package i lowered it version to 9.13 . after doing all these i never encountered that symbolicated error.

**Comment by filozofer** [comment]
Thanx to point me in the right direction. In my case, i run `expo upgrade` command to align versions of my packages correctly and the error is gone !

**Comment by Harshpinder-singh** [comment]
so u have figured it out ? i guess it was package version issue only.
