### ISSUE TITLE
detached project problem build with xcode

### ISSUE THREAD

**Issue by chptx** [expo/expo#927]
I built the sample project in follow steps:

```bash
git clone https://github.com/expo/new-project-template.git
cd new-project-template
# add ios.bundleIdentifier and android.package to app.json
npm install
exp detach
cd ios
pod install
open my-new-project.xcworkspace
# then click 'Play' button in xcode
```

and i get these errors:

![2017-11-07 10 06 37](https://user-images.githubusercontent.com/5226504/32473651-4f13089c-c32e-11e7-976e-ff7da2f3884f.png)

anybody else get the same error? 

node version: 8.9.0
npm version:  5.5.1
exp version: 45.0.2
xcode version: 8.2.1
macos: 10.12

**Comment by brentvatne** [comment]
please update to xcode 9 ;)
