### ISSUE TITLE
Optimization issue on playstore

### ISSUE THREAD

**Issue by imdeepakchahar** [expo/expo#9270]
I generated app bundle using expo build 
and uploaded to play store console

It gives me the optimization issue of the file size of these two file
```
assets/models/fssd_100_8bit_gray_v1.tflite | 2.49 MB
assets/models/fssd_100_8bit_v1.tflite
```
I didn't use these file in my project, they are being added by an expo build.

1. what's the purpose of these files
2. How I solve the error or optimization

**Comment by byCedric** [comment]
Hi @imdeepakchahar, those are TensorFlow (lite) models. They are pulled in from Google and used in the `expo-face-detector` module, and included in the managed flow by default. You can [read more why it's included](https://github.com/expo/fyi/blob/master/managed-app-size.md), even though you don't use it.

Hope it helps!

**Comment by imdeepakchahar** [comment]
But I'm not using `expo-face-detector` also not using `expo-camera` or any photo of camera dependency. 
then why `assets/models/fssd_100_8bit_gray_v1.tflite` and `assets/models/fssd_100_8bit_v1.tflite` added in my abb bundle of app.
So how I can remove these files?

Here is the list of my package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "homepage": "https://wefoodie.in/in/",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/hooks": "^2.5.1",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.5.1",
    "@react-navigation/drawer": "^5.8.1",
    "@react-navigation/material-bottom-tabs": "^5.2.9",
    "@react-navigation/native": "^5.5.0",
    "@react-navigation/stack": "^5.4.1",
    "expo": "~37.0.3",
    "expo-av": "^8.1.0",
    "expo-contacts": "~8.1.0",
    "expo-linear-gradient": "~8.1.0",
    "expo-location": "~8.1.0",
    "expo-permissions": "~8.1.0",
    "expo-updates": "^0.2.7",
    "jetifier": "^1.6.5",
    "native-base": "^2.13.12",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-animatable": "^1.3.3",
    "react-native-contacts": "^5.2.3",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-google-places-autocomplete": "^1.7.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-paper": "^3.10.1",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.3.9"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.1.0",
    "@babel/core": "^7.8.6"
  },
  "private": true
}

```

**Comment by brentvatne** [comment]
read more in https://expo.fyi/managed-app-size

**Comment by imdeepakchahar** [comment]
Sorry @brentvatne still i didn't understand that how to remove `assets/models/fssd_100_8bit_gray_v1.tflite` and `assets/models/fssd_100_8bit_v1.tflite` file from app bundle. Please can you help me to understand this that how to remove?

`npx expo-optimize` is not useful because I don't want to do anything with existing files, they are fine. I just want to remove `assets/models/fssd_100_8bit_gray_v1.tflite` and `assets/models/fssd_100_8bit_v1.tflite` which is not in my project, and these are added by expo during building android app bundle(aab)

**Comment by brentvatne** [comment]
from the doc:

## Opt-in to manual "lean builds" on Android

You can set the android.enableDangerousExperimentalLeanBuilds property to true in app.json to opt-in to only including the Expo SDK packages that you use in your app in your Android standalone app build. If you use this, we strongly recommend that you disable over the air updates or that you are very cautious and use release channels for updates to specific binary versions. Note that the react-native-* packages (eg: react-native-gesture-handler) that are included in the Expo SDK are not currently eligible for exclusion using this approach, only expo-* packages.

Using this approach you can get your binary size down to about 10mb on Android. There is no equivalent feature available on iOS yet, it is in progress.
