### ISSUE TITLE
BarCodeScanner does not recognize vertical bar codes

### ISSUE THREAD

**Issue by TunedMidja** [expo/expo#928]
A bar code is detected only if the camera sees it horizontally but not vertically. Will this be supported or is there any workaround (apart from rotating your phone)?

**Comment by aalices** [comment]
Hi @TunedMidja, for now some of barcodes are detected only if their rotation matches device's interface orientation. However, QR codes (and maybe some others) are detected even if they're rotated. We can think of supporting this. I think there's no better workaround than rotating your phone, unfortunately. You could also force landscape orientation using `ScreenOrientation` module but that won't be satisfactory probably.

**Comment by TunedMidja** [comment]
OK, thanks for the reply @aalices. It's definitely a feature I'd like to see in the future.

**Comment by aalices** [comment]
By the way, have you tested this on iOS? This seems work for this platform

**Comment by TunedMidja** [comment]
Aha, interesting. No, I have not tested this on iOS yet. I used a Samsung Galaxy S7 and it does not recognize vertical CODE_128 barcodes.
If it works on iOS I would consider it a bug.

**Comment by TunedMidja** [comment]
I've tried this on an iPhone 5s now and it does recognize vertical "code 128" barcodes.

**Comment by aarongifford** [comment]
@TunedMidja a quick update.  There was a bug in the latest version of Expo that was causing vertical barcode scanning to not work properly on certain Android devices.  At my company we encountered it when upgrading to 23.0.0.  After wrestling with the issue for the past few days I noticed that a new minor version was published yesterday 23.0.4.  I updated to the new version and the vertical scanning problems on Android are gone.  If you are still having the issue I would suggest trying an update and see if it resolves it for you.  To clarify @aalices I think maybe the issue reported here wasn't a new feature request for barcode scanning perpendicular to the current orientation, but instead a result of this bug which made vertical scanning not work at all or return incorrect barcodes.

**Comment by TunedMidja** [comment]
Thanks for the info @aarongifford. However, it still doesn't work for me even after updating to 23.0.4.

**Comment by aarongifford** [comment]
@TunedMidja sorry to hear that.  Long shot, but make sure you delete your node_modules folder and try loading your app several times.  It seemed like the first time the update didn't "take" for me and I was still running the old code.  You might even try reinstalling the Expo app as well.  Best of luck.

**Comment by aalices** [comment]
The lib we're using recognizes barcodes only in one orientation. We're going to change it soon so the issue will be fixed and hopefully with some better performance.
