### ISSUE TITLE
[expo-font] Fonts are not displaying correctly on published project

### ISSUE THREAD

**Issue by fernandaverzbickas** [expo/expo#9280]
### Summary of Issue

Hello, I've been stuck in this problem for a while now. I have researched many related issues and read expo documentation back to back and nothing seems to solve my problem. 

I've just started on a project and have some custom fonts to load. One of them are icon fonts. 

They are displayed correctly on my development environment but not on production (published expo).

### Environment

1. SDK Version: 38.0.0
2. Platforms(Android/iOS/web/all): Android and iOS

### Reproducible Demo

Git Repository: https://github.com/fernandaverzbickas/font-error-demo

Expo published Project: https://expo.io/@fverzbickas/font-error-demo
 
### Steps to Reproduce

yarn install

expo start

expo publish

### Expected Behavior vs Actual Behavior

On the git demo I've downsized the project for better understanding, but the images refer to the actual project.

All runs well on `expo start` and the fonts are loaded and displayed correctly as the following images show. 

![image](https://user-images.githubusercontent.com/20545152/87790192-8d14ae80-c816-11ea-894e-b6de477444f2.png)
![image](https://user-images.githubusercontent.com/20545152/87790355-d36a0d80-c816-11ea-9406-b4bbe28c832f.png)

So when I run `expo publish` or even build on ios or android and run the .app and .apk files on a device, the custom fonts are not displayed correctly:

![image](https://user-images.githubusercontent.com/20545152/87790262-ab7aaa00-c816-11ea-8b28-5123d8aa528c.png)
![image](https://user-images.githubusercontent.com/20545152/87790386-df55cf80-c816-11ea-898b-daa3390df737.png)

I've tried both ways described in the expo documentation, such as the useFont hook and Font.loadAsync function, but got the same result. 

Also, I'm using Sentry and no errors are displayed.
I am very positive fonts are loading due to the fact that there are hashes created on my custom fonts on my simulator web inspector:
![image](https://user-images.githubusercontent.com/20545152/87790295-b9302f80-c816-11ea-9fa1-6ff95ab3f3c2.png)

I don't know if only the provided informations suffice, I'm happy to provide more if needed. 

I wanna thank in advance for anyone who can provide any type of solution!!

**Comment by jasuno** [comment]
Same problem here...

**Comment by IjzerenHein** [comment]
Hi! I've tried to reproduce the problem using the project in https://github.com/fernandaverzbickas/font-error-demo.
After downloading it, I tried building it on iOS but got an error that certain .ttf files could not be found. After removing those from the XCode project file I was able to build the project. I then created an Archive and installed that app on a device, which showed the custom fonts correctly.

> So when I run expo publish or even build on ios or android and run the .app and .apk files on a device, the custom fonts are not displayed correctly:

Could you provide me with the steps that you used to reproduce this problem on the bare project that you referenced. Or was that project just for reference?

**Comment by fernandaverzbickas** [comment]
@IjzerenHein Not sure if I understood the question correctly, but the problem can be reproduced on the project I referenced just by running `expo publish`.

**Comment by moxorama** [comment]
I have the same issue
- If I'm publishing with --target=managed -  all Icons are ok
- If just building managed apps - getting broken icons

**Comment by brentvatne** [comment]
@moxorama - do you have an ejected app? in other words, do you have an `ios` directory and/or `android` directory and react-native unimodules in your project?

**Comment by moxorama** [comment]
@brentvatne  - app configured as managed in app.json and has no 'external' dependencies, but I have this folders for my ejected experiments.

**Comment by brentvatne** [comment]
@moxorama - it is considered by expo to be an ejected project then. you can remove ios and android directories to resolve your problem

**Comment by IronYeti** [comment]
I can confirm that @brentvatne 's suggestion to remove ios and android directories solved this issue for me (as well as an errant icon issue too).  I'm embarrassed knowing how much time I wasted on this.  (like @moxorama  I had these directories present because of some earlier experimenting with ejecting then left them there.)
thanks Brent!!!

**Comment by brentvatne** [comment]
related to https://github.com/expo/expo/issues/9517

**Comment by brentvatne** [comment]
the next version of expo-cli will include a warning when you run expo publish in a bare project with the expo package included in package.json
