### ISSUE TITLE
[expo-updates] Bare React Native iOS build fails with `The hashAssetFiles Metro plugin is not configured`

### ISSUE THREAD

**Issue by santiagomartinez** [expo/expo#9285]
### Summary of Issue
iOS build fails with message `The hashAssetFiles Metro plugin is not configured. You need to add a metro.config.js to your project that configures Metro to use this plugin.` on a bare fresh React Native project when including expo-updates and following the install instructions.

### Environment
Expo diagnostics output:
Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.8 => 38.0.8
      react: 16.13.1 => 16.13.1
      react-native: 0.63.1 => 0.63.1
    npmGlobalPackages:
      expo-cli: 3.22.3

### Reproducible Demo
https://github.com/santiagomartinez/expo-updates-error
 
### Steps to Reproduce
1. `npx react-native init AwesomeProject`
2. `npm install expo`
3. `npm install react-native-unimodules`
4. `npm install expo-updates`
5. `npx pod-install`
6. Configure according to instructions
6. Build iOS 

### Expected Behavior vs Actual Behavior
Should build fine

**Comment by byCedric** [comment]
Hi @santiagomartinez, thanks for the issue report _and_ repro! I don't think we support React Native 0.63 (yet). It's a good find that `expo-updates` seems to have some issues with RN 0.63, so let's keep this open until that's resolved. But I'm afraid that will be after we release SDK 39 with support for RN 0.63.

Thanks for the report!

**Comment by brentvatne** [comment]
@byCedric - i tested against react-native-unimodules and expo-updates against rn 0.63 on release and it works as expected.

@santiagomartinez - your metro config has `assetPlugins` in the wrong place, it needs to be under `transformer` like so:

```
module.exports = {
  transformer: {
    assetPlugins: ['expo-asset/tools/hashAssetFiles'],
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```

**Comment by brentvatne** [comment]
also, you don't need to install the `expo` package, i'd recommend against doing that if you're just adding expo-updates and assorted sdk packages to an existing react-native project. if you install `expo` it brings in `expo-splash-screen` automatically, which requires further configuration to work

**Comment by santiagomartinez** [comment]
Thank you very much. The cause of problem is now clear to me and also your explanation about the project config.
