### ISSUE TITLE
[expo-notifications][ios] Error encountered while fetching Expo token, expected an OK response, received: 400

### ISSUE THREAD

**Issue by brunoaduarte** [expo/expo#9290]
### Summary of Issue 
expo-notifications was working perfectly, but now:
`Error encountered while fetching Expo token, expected an OK response, received: 400`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.22.3 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

### Reproducible Demo

https://docs.expo.io/versions/latest/sdk/notifications/
 
### Steps to Reproduce

expo init notifications-test
copy source from demo above

### Expected Behavior vs Actual Behavior

Expected to get a token like "ExponentPushToken[blblablalbalblabla]"

Actual behavior

```
[Unhandled promise rejection: Error: Error encountered while fetching Expo token, expected an OK response, received: 400 (body: "{"errors":[{"code":"API_ERROR","message":"\"value\" must be of type object."}]}").]
* [native code]:null in construct
- node_modules\@babel\runtime\helpers\construct.js:19:9 in _construct
- node_modules\@babel\runtime\helpers\wrapNativeSuper.js:26:22 in Wrapper
* [native code]:null in construct
* http://192.168.15.85:19001/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:107191:321 in _createSuperInternal
- node_modules\@unimodules\react-native-adapter\build\errors\CodedError.js:8:8 in constructor
- node_modules\expo-notifications\build\getExpoPushTokenAsync.js:7:15 in getExpoPushTokenAsync
- node_modules\regenerator-runtime\runtime.js:45:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:274:29 in invoke
- node_modules\regenerator-runtime\runtime.js:45:36 in tryCatch
- node_modules\regenerator-runtime\runtime.js:135:27 in invoke
- node_modules\regenerator-runtime\runtime.js:145:18 in PromiseImpl.resolve.then$argument_0
- node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:135:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:183:16 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:446:30 in callImmediates
* [native code]:null in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:396:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:144:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:373:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:143:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

**Comment by emroot** [comment]
Yeah same issue. I have another issue here: https://github.com/expo/expo/issues/9291
Just started happening, I suspect there's a change on the expo server that broke this feature.

**Comment by ankur014** [comment]
I'm seeing the same error, suspecting it to be a server issue.

**Comment by emroot** [comment]
pinged @brentvatne they're on it.

**Comment by emroot** [comment]
it's been resolved and works now.

**Comment by rrupeshh** [comment]
There is the similar issue from today, it was working perfectly till yesterday.

**Comment by jkhales** [comment]
> There is the similar issue from today, it was working perfectly till yesterday.

Would you mind providing some more information and a reproducible example?

I just tried the example given for this one and it was successful.

**Comment by rrupeshh** [comment]
@jkhales  I am fetching from a client react application and it was working fine until yesterday but getting 400 from today.

`fetch("https://exp.host/--/api/v2/push/send", {
        method: "POST",
        mode: "no-cors",
        headers: {
          "accept-encoding": "gzip, deflate",
          "content-type": "application/json",
        },
        body: JSON.stringify([{
            "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
            "title": "Original Title",
            "body": "And here is the body!"
        },
        {
             "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
             "title": "Original Title",
             "body": "And here is the body!"
        }
      ]),
});`

**Comment by jkhales** [comment]
> @jkhales I am fetching from a client react application and it was working fine until yesterday but getting 400 from today.
> 
> fetch("https://exp.host/--/api/v2/push/send", {
> method: "POST",
> mode: "no-cors",
> headers: {
> "accept-encoding": "gzip, deflate",
> "content-type": "application/json",
> },
> body: JSON.stringify([{
> "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> "title": "Original Title",
> "body": "And here is the body!"
> },
> {
> "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> "title": "Original Title",
> "body": "And here is the body!"
> }
> ]),
> });

Hm, couldn't replicate it, got a `200` when I tried it:

<img width="1670" alt="Screen Shot 2020-07-28 at 11 28 14 AM" src="https://user-images.githubusercontent.com/1220444/88706234-70556200-d0c5-11ea-9dee-96d366d1f6ea.png">

**Comment by rrupeshh** [comment]
> > @jkhales I am fetching from a client react application and it was working fine until yesterday but getting 400 from today.
> > fetch("https://exp.host/--/api/v2/push/send", {
> > method: "POST",
> > mode: "no-cors",
> > headers: {
> > "accept-encoding": "gzip, deflate",
> > "content-type": "application/json",
> > },
> > body: JSON.stringify([{
> > "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> > "title": "Original Title",
> > "body": "And here is the body!"
> > },
> > {
> > "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> > "title": "Original Title",
> > "body": "And here is the body!"
> > }
> > ]),
> > });
> 
> Hm, couldn't replicate it, got a `200` when I tried it:
> 
> <img alt="Screen Shot 2020-07-28 at 11 28 14 AM" width="1670" src="https://user-images.githubusercontent.com/1220444/88706234-70556200-d0c5-11ea-9dee-96d366d1f6ea.png">

Don't know why I'm getting this !!

![image](https://user-images.githubusercontent.com/22337268/88755415-d521c280-d180-11ea-9324-9933d1f77889.png)

**Comment by jkhales** [comment]
> > > @jkhales I am fetching from a client react application and it was working fine until yesterday but getting 400 from today.
> > > fetch("https://exp.host/--/api/v2/push/send", {
> > > method: "POST",
> > > mode: "no-cors",
> > > headers: {
> > > "accept-encoding": "gzip, deflate",
> > > "content-type": "application/json",
> > > },
> > > body: JSON.stringify([{
> > > "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> > > "title": "Original Title",
> > > "body": "And here is the body!"
> > > },
> > > {
> > > "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> > > "title": "Original Title",
> > > "body": "And here is the body!"
> > > }
> > > ]),
> > > });
> > 
> > 
> > Hm, couldn't replicate it, got a `200` when I tried it:
> > <img alt="Screen Shot 2020-07-28 at 11 28 14 AM" width="1670" src="https://user-images.githubusercontent.com/1220444/88706234-70556200-d0c5-11ea-9dee-96d366d1f6ea.png">
> 
> Don't know why I'm getting this !!
> 
> ![image](https://user-images.githubusercontent.com/22337268/88755415-d521c280-d180-11ea-9324-9933d1f77889.png)

maybe add a `.catch(console.log)` for more info?

**Comment by rrupeshh** [comment]
> fetch("https://exp.host/--/api/v2/push/send", {
> method: "POST",
> mode: "no-cors",
> headers: {
> "accept-encoding": "gzip, deflate",
> "content-type": "application/json",
> },
> body: JSON.stringify([{
> "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> "title": "Original Title",
> "body": "And here is the body!"
> },
> {
> "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> "title": "Original Title",
> "body": "And here is the body!"
> }
> ]),
> });

![image](https://user-images.githubusercontent.com/22337268/88804321-7b93b500-d1cd-11ea-9b7c-9c55be98ad5b.png)

**Comment by rrupeshh** [comment]
> > > > @jkhales I am fetching from a client react application and it was working fine until yesterday but getting 400 from today.
> > > > fetch("https://exp.host/--/api/v2/push/send", {
> > > > method: "POST",
> > > > mode: "no-cors",
> > > > headers: {
> > > > "accept-encoding": "gzip, deflate",
> > > > "content-type": "application/json",
> > > > },
> > > > body: JSON.stringify([{
> > > > "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> > > > "title": "Original Title",
> > > > "body": "And here is the body!"
> > > > },
> > > > {
> > > > "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
> > > > "title": "Original Title",
> > > > "body": "And here is the body!"
> > > > }
> > > > ]),
> > > > });
> > > 
> > > 
> > > Hm, couldn't replicate it, got a `200` when I tried it:
> > > <img alt="Screen Shot 2020-07-28 at 11 28 14 AM" width="1670" src="https://user-images.githubusercontent.com/1220444/88706234-70556200-d0c5-11ea-9dee-96d366d1f6ea.png">
> > 
> > 
> > Don't know why I'm getting this !!
> > ![image](https://user-images.githubusercontent.com/22337268/88755415-d521c280-d180-11ea-9324-9933d1f77889.png)
> 
> maybe add a `.catch(console.log)` for more info?

![image](https://user-images.githubusercontent.com/22337268/88804439-a0882800-d1cd-11ea-93a6-b565744dfb71.png)

**Comment by jkhales** [comment]
can you try using curl?

`curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '[{
"to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
"title": "Original Title",
"body": "And here is the body!"
},
{
"to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]",
"title": "Original Title",
"body": "And here is the body!"
}
]'`

**Comment by rrupeshh** [comment]
> can you try using curl?
> 
> `curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '[{ "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" }, { "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" } ]'`

works in terminal using curl and also works well in postman. ...but in react app using fetch works well for single token object but for multiple token array it doesnot works

**Comment by jkhales** [comment]
> > can you try using curl?
> > `curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '[{ "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" }, { "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" } ]'`
> 
> works in terminal using curl and also works well in postman. ...but in react app using fetch works well for single token object but for multiple token array it doesn't work

OK great. So it seems like this is not something wrong with the servers.

It maybe an issue with notifications not being fully supported on web yet, see here: https://docs.expo.io/versions/latest/sdk/notifications/

If that doesn't solve your issue, the best place to research this further would be the forums: https://forums.expo.io/

**Comment by rrupeshh** [comment]
> > > can you try using curl?
> > > `curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '[{ "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" }, { "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" } ]'`
> > 
> > 
> > works in terminal using curl and also works well in postman. ...but in react app using fetch works well for single token object but for multiple token array it doesn't work
> 
> OK great. So it seems like this is not something wrong with the servers.
> 
> It maybe an issue with notifications not being fully supported on web yet, see here: https://docs.expo.io/versions/latest/sdk/notifications/
> 
> If that doesn't solve your issue, the best place to research this further would be the forums: https://forums.expo.io/

Okay sure I will look into it. Thanks for your time and support.

**Comment by jkhales** [comment]
> > > > can you try using curl?
> > > > `curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '[{ "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" }, { "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" } ]'`
> > > 
> > > 
> > > works in terminal using curl and also works well in postman. ...but in react app using fetch works well for single token object but for multiple token array it doesn't work
> > 
> > 
> > OK great. So it seems like this is not something wrong with the servers.
> > It maybe an issue with notifications not being fully supported on web yet, see here: https://docs.expo.io/versions/latest/sdk/notifications/
> > If that doesn't solve your issue, the best place to research this further would be the forums: https://forums.expo.io/
> 
> Okay sure I will look into it. Thanks for your time and support.

One last thought, if you are running the original fetch operation in a browser, in the chrome dev tools, in the network tab, you can right click any net request and say export to cURL.

Would you mind posting that here so we can compare with the functional cURL call you were making?

**Comment by rrupeshh** [comment]
> > > > can you try using curl?
> > > > `curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '[{ "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" }, { "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" } ]'`
> > > 
> > > 
> > > works in terminal using curl and also works well in postman. ...but in react app using fetch works well for single token object but for multiple token array it doesn't work
> > 
> > 
> > OK great. So it seems like this is not something wrong with the servers.
> > It maybe an issue with notifications not being fully supported on web yet, see here: https://docs.expo.io/versions/latest/sdk/notifications/
> > If that doesn't solve your issue, the best place to research this further would be the forums: https://forums.expo.io/
> 
> Okay sure I will look into it. Thanks for your time and support.

```
curl "https://exp.host/--/api/v2/push/send" ^
  -H "authority: exp.host" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" ^
  -H "content-type: text/plain;charset=UTF-8" ^
  -H "accept: */*" ^
  -H "origin: http://139.59.56.230" ^
  -H "sec-fetch-site: cross-site" ^
  -H "sec-fetch-mode: no-cors" ^
  -H "sec-fetch-dest: empty" ^
  -H "referer: http://139.59.56.230/" ^
  -H "accept-language: en-US,en;q=0.9" ^
  --data-binary "^[^{^\^"to^\^":^\^"ExponentPushToken^[fIsPA_Hf-SRThRt4sacSx8^]^\^",^\^"title^\^":^\^"Original Title^\^",^\^"body^\^":^\^"And here is the body^!^\^"^},^{^\^"to^\^":^\^"ExponentPushToken^[fIsPA_Hf-SRThRt4sacSx8^]^\^",^\^"title^\^":^\^"Original Title^\^",^\^"body^\^":^\^"And here is the body^!^\^"^}^]" ^
  --compressed
```

**Comment by rrupeshh** [comment]
> > > > > can you try using curl?
> > > > > `curl -H "Content-Type: application/json" -X POST "https://exp.host/--/api/v2/push/send" -d '[{ "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" }, { "to": "ExponentPushToken[fIsPA_Hf-SRThRt4sacSx8]", "title": "Original Title", "body": "And here is the body!" } ]'`
> > > > 
> > > > 
> > > > works in terminal using curl and also works well in postman. ...but in react app using fetch works well for single token object but for multiple token array it doesn't work
> > > 
> > > 
> > > OK great. So it seems like this is not something wrong with the servers.
> > > It maybe an issue with notifications not being fully supported on web yet, see here: https://docs.expo.io/versions/latest/sdk/notifications/
> > > If that doesn't solve your issue, the best place to research this further would be the forums: https://forums.expo.io/
> > 
> > 
> > Okay sure I will look into it. Thanks for your time and support.
> 
> One last thought, if you are running the original fetch operation in a browser, in the chrome dev tools, in the network tab, you can right click any net request and say export to cURL.
> 
> Would you mind posting that here so we can compare with the functional cURL call you were making?

```
curl "https://exp.host/--/api/v2/push/send" ^
  -H "authority: exp.host" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" ^
  -H "content-type: text/plain;charset=UTF-8" ^
  -H "accept: */*" ^
  -H "origin: chrome-search://local-ntp" ^
  -H "sec-fetch-site: cross-site" ^
  -H "sec-fetch-mode: no-cors" ^
  -H "sec-fetch-dest: empty" ^
  -H "accept-language: en-US,en;q=0.9" ^
  --data-binary "^[^{^\^"to^\^":^\^"ExponentPushToken^[fIsPA_Hf-SRThRt4sacSx8^]^\^",^\^"title^\^":^\^"Original Title^\^",^\^"body^\^":^\^"And here is the body^!^\^"^},^{^\^"to^\^":^\^"ExponentPushToken^[fIsPA_Hf-SRThRt4sacSx8^]^\^",^\^"title^\^":^\^"Original Title^\^",^\^"body^\^":^\^"And here is the body^!^\^"^}^]" ^
  --compressed
```

**Comment by jkhales** [comment]
So it seems like the content-type is being converted to `text/plain` you want to use `application/json` and it should work.

More documentation here: https://docs.expo.io/push-notifications/sending-notifications/#dont-want-to-use-one-of-the

Thanks again for all this debug info and good luck!

**Comment by soly2014** [comment]
disable remote debugger and try again
