### ISSUE TITLE
Does Expo supports realm?

### ISSUE THREAD

**Issue by mgorabbani** [expo/expo#93]

**Comment by terribleben** [comment]
At the moment, no, but we hope to add support in the longer term. We're also working on a SQLite implementation which we hope to ship much sooner.

**Comment by mgorabbani** [comment]
Thanks! good to know.

**Comment by kiodou** [comment]
Any update?

**Comment by terribleben** [comment]
https://expo.canny.io/feature-requests/p/support-for-realm

**Comment by johnkeychishugi** [comment]
any update for realm in expo??
