### ISSUE TITLE
usesIcloudStorage key missing in app.json documentation

### ISSUE THREAD

**Issue by peterbartfai** [expo/expo#930]
Hey.
The latest (22.0) [document picker documentation](https://docs.expo.io/versions/latest/sdk/document-picker.html) said, if we want to use this function in`Standalone app`, we should add `"usesIcloudStorage": true` to app.json. 
I can not find this specific part in the [app.json documentation](https://docs.expo.io/versions/latest/guides/configuration.html#ios). If I tried to add below ios section in app.json, the XDE said, 

> Field: ios - should NOT have additional property 'usesIcloudStorage'.

Any advice? 
(Realted expo forum topic: [here](https://forums.expo.io/t/cannot-set-usesicloudstorage-in-app-json/4158))

**Comment by quinlanj** [comment]
hi @peterbartfai , we’ve written the fix for this and will be deploying this in sdk23 . sorry for the inconvenience

**Comment by quinlanj** [comment]
cc: @terribleben

**Comment by JLarky** [comment]
is it `useIcloudStorage` or `useIcloudStorage`?

I see one in https://docs.expo.io/versions/latest/sdk/document-picker and the other in https://docs.expo.io/versions/latest/guides/configuration.html#ios

**Comment by defint** [comment]
`useIcloudStorage` doesn't work, only `usesIcloudStorage` pass through config validation
