### ISSUE TITLE
[expo-notifications] "sticky" notifications can be dismissed via swipe out (SDK 38)

### ISSUE THREAD

**Issue by MaHermes** [expo/expo#9302]
### Summary of Issue 
The old API had the problem that sticky notifications were dismissed if the user clicks on them. However, the user at least wasn't able to dismiss the notification himself by swiping.
The new system (using autoDismiss:false) works the other way arround. If the user clicks the message, it will not be dismissed, which is nice. But if he swipes it, it disappears.
I would love to control both behaviours (sticky = user can not dismiss it via swipe, app has to clear the notification & autoDismiss:false = if user clicks the notification it should not disappear)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.22.1 environment info:
   System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^3.13.0 => 3.13.0
```
Platform: Android

### Reproducible Demo

Set "useNextNotificationsApi": true in app.json

```
import * as Notifications from 'expo-notifications';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

Notifications.scheduleNotificationAsync({
  content: {
    title: 'Look at that notification',
    body: "I'm so proud of myself!",
    autoDismiss: false
  },
  trigger: null,
});

```
 
### Steps to Reproduce

Trigger a notification as shown in the demo.
Clear the notification by swiping.

### Expected Behavior vs Actual Behavior

If _autoDismiss_ is meant to replace the _sticky_ property of the former API I would expect that the user can not dismiss the notification by swiping, but it does.

I'm not sure this can be seen as a bug, it may be more like a regression, since the sticky-Property is gone.
Maybe an additional property _sticky_ beside _autoDismiss_ would be an acceptable solution?

Thank you :)

**Comment by barthap** [comment]
I have added this functionality in #9351 - now `sticky` makes notifications non-dismissable by swipe, and `autoDismiss` behavior hasn't been changed.

**Comment by AdityaThummar** [comment]
Hello @barthap I'm using latest expo packages for expo sdk and notification as well, When I try to add `sticky:true` in configs it still swappable, so would you please guide me where I'm going wrong? Here's my App.js file

```
import { Button, StyleSheet, Text, View } from "react-native";
import React from "react";
import * as Notifications from "expo-notifications";

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});

const App = () => {
  const showNoti = async () =>
    await Notifications.scheduleNotificationAsync({
      trigger: null,
      content: {
        title: "testing",
        priority: Notifications.AndroidNotificationPriority.MAX,
        sticky: true,
      },
    });

  return (
    <View>
      <Text>App</Text>
      <Button title="test" onPress={showNoti} />
    </View>
  );
};

export default App;

const styles = StyleSheet.create({});
```

And my package.json file as well

```
{
  "name": "officebuddy",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start -c",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "pstart": "rm -rf android && expo run:android"
  },
  "dependencies": {
    "expo": "~51.0.2",
    "expo-background-fetch": "~12.0.1",
    "expo-location": "~17.0.1",
    "expo-notifications": "~0.28.1",
    "expo-status-bar": "~1.12.1",
    "expo-task-manager": "~11.8.1",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-maps": "1.14.0",
    "react-native-mmkv": "^2.12.2",
    "zustand": "^4.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "typescript": "^5.1.3"
  },
  "private": true
}
```
