### ISSUE TITLE
[docs] [Notifications] Where to specify the target channel for local notifications (SDK 38)

### ISSUE THREAD

**Issue by MaHermes** [expo/expo#9303]
The doc: https://docs.expo.io/versions/v38.0.0/sdk/notifications

It says

> Starting in Android 8.0 (API level 26), all notifications must be assigned to a channel.

How can one specify the _channelId_ for local notifications (via. scheduleNotificationAsync)?
In the old API there was a property channelId (see https://docs.expo.io/versions/v37.0.0/sdk/notifications/#localnotification).
The new NotificationRequestInput is missing it (https://docs.expo.io/versions/v38.0.0/sdk/notifications/#notificationrequestinput).

Thank you for  your help!

**Comment by lukmccall** [comment]
Hi @MaHermes, now `expo-notifications` creates a channel for all of your local notifications. Unfortunately, currently, you can't specify channel id by yourself. However, we work on it.

**Comment by MaHermes** [comment]
Hi @lukmccall, thank you very much for your answer!

I noticed the missing property because I have problems with vibration patterns  #9155 and were not able to get a non dismissable notification #9302 and I wanted to test if these features will work if I set the corresponding properties in a channel setup.

So to be clear, there is not really a need for me to specify an other channel if these properties also work by just setting up the local notification.

Thanks for targeting this issue, can I give you a tip somewhere? :)

**Comment by lukmccall** [comment]
The problem with vibration patterns is more complex and it's connected with channels. From Android `8.0`, all notifications must be in the channel. Sadly, the pattern which you set to a single notification is less important than channel settings. Because of that, you can't set a vibration pattern directly to a notification.

**Comment by MaHermes** [comment]
Ok, thanks for the clarification. So if I change the _Miscellaneous_ channel vibration pattern (using _setNotificationChannelAsync_) that may be a workarround if I have only 1 type of notification? I'll give it a try...

**Comment by lukmccall** [comment]
It should work ;)
