### ISSUE TITLE
[expo-linking] Bare app doesn't fire url event listener if app is already open.

### ISSUE THREAD

**Issue by Cookizza** [expo/expo#9304]
### Summary of Issue 
The `Linking.addEventListener('url')` callback is never fired when using a custom url scheme link. The `getInitialURL` call works as expected when the app is closed.

I have tested this on testflight and the app foregrounds as you would expect but the event listener simply doesnt fire.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
 Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v14.4.0/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.3.9 => 4.4.0
    npmGlobalPackages:
      expo-cli: 3.22.3

### Reproducible Demo

    export default class App extends React.Component {
        componentDidMount(){
            Linking.addEventListener('url', event => {alert(event.url)});

            Linking.getInitialURL()
            .then(url => {
                if (url) {
                  alert(url);
                }
            });
        }
    }
 
### Steps to Reproduce

1. In a detached project, setup URL scheme in xcode project (e.g. myapp)
2. Run the project
3. Type URL scheme `myapp://test/123` into notes or similar which will create a link
4. You will only receive an alert with `test/123` if the app was closed before you pressed the link

### Expected Behavior vs Actual Behavior
The event listener should allow us to customise how inbound url schemes are handled.

**Comment by Cookizza** [comment]
I have tried quite a few ways to get this to work, but even a completely blank ejected project doesn't fire the event..

It seems like this effects things that use the event such as react navigation, too

**Comment by Cookizza** [comment]
Ok it seems like the bare projects need to the below added to the AppDelegate.m

`- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<NSString *, id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}`

**Comment by virus2016** [comment]
@Cookizza Works perfectly!

**Comment by lc3t35** [comment]
I don't think this should be closed as I should be included when the app is ejected ?
