### ISSUE TITLE
Expo client app crashes on android emulators while using Admob library

### ISSUE THREAD

**Issue by tamimaj** [expo/expo#9306]
I'm facing a crash (close) when I run the expo app on android emulator, first the ad load perfectly fine (it's a banner ad) then I change the screen by tab navagation using the react navigation library, when I tab the navigation button of the ad screen to get back the expo client app get closed, I tried on IOS simulator and there is no problem, I tried on real android devices and there is no problem.
I am not sure where the bug is, its not in my code because it runs perfectly on real devices and IOS simulators.

**Comment by AdamJNavarro** [comment]
Hey @tamimaj, thanks for opening up an issue! We are going to need a repro case before we are able to investigate this so if you could create a minimal, reproducible example to share with us that demonstrates the crash on Android emulators that would be fantastic. Any other information you think might be helpful is also certainly appreciated.

Cheers,
Adam

**Comment by danielsilvajobs** [comment]
Same here...

I have the ads in the home page the app does not even open it crash straight await. It does work fine on iOS though.

**Comment by tamimaj** [comment]
Hey again, while preparing a repo to reproduce the bug and upload it here, It didn't happened first, so after hours, I found out that combining MapView from expo and Admob in the same screen  is where the crash happens, could be something about rendering or memory of simulator, I'm not sure but, I took off the MapView from the screen and the issue is partially solved for me

**Comment by TiagoSeverino** [comment]
Hey, I am getting the exact same problem, when loading admob and mapview on same page.

**Comment by cruzach** [comment]
If you're having an issue loading admob + mapview on the same page, please open a new issue with a reproducible demo provided with a snack- https://snack.expo.io/, and we can keep track there. It might provide some useful information to run `adb logcat` during the crash and paste that output in the new issue
