### ISSUE TITLE
Getting AssertionError [ERR_ASSERTION]: missing path when building a release | using require() on assets | Android Studio & Expo Bare Workflow (SDK 38)

### ISSUE THREAD

**Issue by raymelon** [expo/expo#9309]
## 🐛 Bug Report
Getting `AssertionError [ERR_ASSERTION]: missing path` when building a release | using `require()` on assets | Android Studio & Expo Bare Workflow

### Summary of Issue 

Hi Expo Community, so everything is working well with Expo Bare Workflow, until the time when we need to generate a release build. As per docs, assets are hosted via metro for debug mode, and will be bundled on release. So this is where the issue revolves.

We're having problems with bundling assets for release. We have setup Expo Asset following the instructions on bare workflow docs, we also tried the `assetBundlePatterns` workaround.

The error manifested first on the assets that are bound to the main app (these include fonts and images, also note that we use `require()` to load our assets) and after commenting those out, it showed that the problem extends up to the dependencies. After realizing that, there's no point of commenting the code that has `require(asset path)` until no asset is used anymore because the problem is rooted on the bundling process.

```
error node_modules/react-navigation-stack/lib/module/vendor/views/assets/back-icon-mask.png: missing path. Run CLI with --verbose flag for more details.
AssertionError [ERR_ASSERTION]: missing path
    at Module.require (module.js:595:3)
    at require (internal/module.js:11:18)
    at *** /node_modules/metro/src/Assets.js:303:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep ( *** /node_modules/metro/src/Assets.js:52:24)
    at _next (*** /node_modules/metro/src/Assets.js:72:9)
    at *** /node_modules/metro/src/Assets.js:77:7
    at new Promise (<anonymous>)
    at *** /node_modules/metro/src/Assets.js:69:12

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'npx'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 32s
68 actionable tasks: 2 executed, 66 up-to-date
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.11.7 environment info:
    System:
      OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    npmPackages:
      expo: ^38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-navigation: ^4.3.9 => 4.4.0

### Steps to Reproduce

- Create an Expo Bare Workflow app
- Setup Expo Asset
- Load some assets to the app that need `require()`, make sure to use it with `require()`
- Run `yarn start`, keep open for bundling, else an error cannot connect to bundler server stuff will show
- Open Android Studio, sync Gradle
- When syncing done, goto Build menu, then Generate Signed Bundle / APK...
- Wait for the error to occur

### Expected Behavior vs Actual Behavior

- Expected is a generated release apk, deployable to Google Play and runnable without the need of the bundler running on the background
- Actual behavior is `AssertionError [ERR_ASSERTION]: missing path`. See the stacktrace on the summary part.

So that's it. Help will be really much appreciated. Cheers!

**Comment by byCedric** [comment]
Hi @raymelon, thanks for your issue report. Unfortunately, I can't reproduce the issue you mention using the steps you described. I've set everything up and using this to trigger the code:

```
useEffect(() => {
    Asset.loadAsync(require('./assets/splash.png'))
      .then((asset) => console.log('Splash screen loaded', asset))
      .catch((error) => console.warn('Failed to load splash screen', error));
  }, []);
``` 

Usually, this error is related to an empty `require()` call. This can be caused by missing quotes in your call, or typos like `require()('path/to/module')`. If you think this is an issue on our side, please create a repro that causes this issue. I'd be happy to take a look after that 😄 

Hope it helps!

**Comment by raymelon** [comment]
> Hi @raymelon, thanks for your issue report. Unfortunately, I can't reproduce the issue you mention using the steps you described. I've set everything up and using this to trigger the code:
> 
> ```
> useEffect(() => {
>     Asset.loadAsync(require('./assets/splash.png'))
>       .then((asset) => console.log('Splash screen loaded', asset))
>       .catch((error) => console.warn('Failed to load splash screen', error));
>   }, []);
> ```
> 
> Usually, this error is related to an empty `require()` call. This can be caused by missing quotes in your call, or typos like `require()('path/to/module')`. If you think this is an issue on our side, please create a repro that causes this issue. I'd be happy to take a look after that 😄
> 
> Hope it helps!

Hi @byCedric, I appreciate your prompt response. I found out that using `Asset.fromModule` (`Asset` is from `expo-asset`) looks like a viable workaround, since it worked when I applied it on my code. Unfortunately, the error still persists on the modules installed (those inside the `node_modules`), leaving me unable to make a release build still.

I will mention below the related issues that I looked into:

https://github.com/expo/expo/issues/6948#issuecomment-582433559
https://github.com/expo/expo/issues/1999
https://github.com/expo/expo/issues/3991

And from the forums and docs:

https://forums.expo.io/t/proper-way-to-use-assetbundlepatterns/11440/3
https://docs.expo.io/guides/offline-support/?redirected

 Unfortunately the code that exhibits the issue is an internal project. I'll try to make a repro, hoping to drop it here in a day or two.

Thank you so much!

**Comment by HackerHack224** [comment]
Hello bro maybe i use Asset.fromModule() in exchange for require() doesn't it give an error?
