### ISSUE TITLE
[exp] Android: Build waiting in queue...

### ISSUE THREAD

**Issue by RaghavendraNK** [expo/expo#931]
Expo is taking too long time to generate *.apk, anyone is having idea how to resolve it

**Comment by quinlanj** [comment]
hi @RaghavendraNK, there was an internal error that we are working on fixing right now. sorry for the inconvenience

**Comment by dshn197** [comment]
@quinlanj on an average it takes 10-18 minutes to generate an `.apk`. Isn't that too long?
