### ISSUE TITLE
Location.startGeofencingAsync calls (ONLY THE) Location.GeofencingEventType.Enter twice.

### ISSUE THREAD

**Issue by sinisa-nimcevic** [expo/expo#9314]
### Summary of Issue 
- I've set up a very basic application using the bare workflow. 
- I want to trigger a notification upon entering a geofenced location. 
- **My geofencing task get's triggered twice for location entry, but only once for location exit.** 
- I am only concerned about the **android** implementation at this point.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Here's a snapshot of my react-native info
```
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.47 GB / 15.54 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1
      System Images: android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Reproducible Demo

https://github.com/sinisa-nimcevic/expo-geolocation-test
react-native start
react-native run-android 

### Steps to Reproduce
You can use an application like Fake GPS on android and switch between any given location. I've set up both push notifications and console logs, although push notifications can be omitted if you wish. Switch your position from one geofenced area to the other and wait for the notifications/console logs.

### Expected Behavior vs Actual Behavior
We should get one notification/console log on Location.GeofencingEventType.Enter, and one of type Location.GeofencingEventType.Exit. The entry event is called twice.

**Comment by tsapeta** [comment]
Thanks for the report and sorry it's bothering you! As you already noticed, there is a duplicate report in #6283 so I'm going to close this one. We will be posting updates there as well.
