### ISSUE TITLE
[expo-av] Remote audio source duration mismatch on iOS

### ISSUE THREAD

**Issue by darcien** [expo/expo#9321]
### Summary of Issue 

When playing a remote audio source using `Audio.Sound.createAsync` from `expo-av`, the `durationMillis` from the playback status doesn't match the actual file duration on iOS.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

<details><summary>expo diagnostics output</summary>
<p>

  Expo CLI 3.15.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.20.1 - /var/folders/hd/87n7hm694j53ypgqgc28t0800000gn/T/fnm-shell-9865172/bin/node
      Yarn: 1.22.4 - node_modules/.bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 

</p>
</details>

Targeting iOS only for now.

### Reproducible Demo

Snack link: https://snack.expo.io/@darcien/remote-audio-duration-mismatch-ios

### Steps to Reproduce

1. Open that snack on an iOS device or Simulator.
2. Press "Play"

### Expected Behavior vs Actual Behavior

I would expect the `status.durationMillis` value to match the actual duration from the file.

[The docs](https://docs.expo.io/versions/latest/sdk/av/#playback-status) did mention:
>`durationMillis` : the duration of the media in milliseconds. This is only present if the media has a duration (note that in some cases, a media file's duration is readable on Android, but not on iOS).

I'm not sure whether this is a case where iOS couldn't read the duration but still returned a value for the duration _or_ it could read the duration, but the returned duration is wrong.

Also, this only happen on files that are relatively big (>6MB), this can be tested by selecting a different source in the snack.

I have not tested whether different audio format affect this or not.

One interesting point would be:
FireFox 78 | iPhone X (Device)
--- | ---
<img width="324" alt="image" src="https://user-images.githubusercontent.com/19742419/87949669-86b15b80-cad0-11ea-9d9c-68655ec2fb15.png">|<img width="324" alt="image" src="https://user-images.githubusercontent.com/19742419/87949764-a183d000-cad0-11ea-9e9c-b490289029b3.png">

The `status.durationMillis` mismatch, if you divide the value from the iOS with the one on the web, you would get: `862064 / 431032.018 = ~2`. Maybe this could be a clue or maybe it's just a coincidence, I'm not sure.

**Comment by IjzerenHein** [comment]
Hi! I've taken a closer look at this and this problem doesn't seem to be an `expo-av` issue, but happens either because the `mp4` file is incorrectly encoded or there is a deeper problem with iOS or Mac OSX.

When I save the file https://res.cloudinary.com/dm7sc2usi/video/upload/v1595254846/audios/susan_winter.mp4 to my Mac, and open it in QuickTime it also shows the duration of 14:22

![image](https://user-images.githubusercontent.com/6184593/88052308-5e6e3f00-cb5a-11ea-96c1-59e265bc9dc9.png)

You probably need to re-encode this file to get the correct duration.

**Comment by darcien** [comment]
OMG, I think you're right, it's encoding issue. I didn't notice this because the file have the correct duration on my Windows machine.

I re-encoded the file, and now I'm getting the correct duration, thank you so much for investigating this, you guys rocks! 🎉

**Comment by Elkaramany** [comment]
@darcien Can you elaborate on how you re-encoded the file

**Comment by darcien** [comment]
> @darcien Can you elaborate on how you re-encoded the file

Sorry, this is like 2 years ago, I barely remember the details.

But if I remember correctly, I'm using [foobar2000's converter](https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Converter) for easy to use UI. Depending on the format you want to convert, you might need additional specific encoder installed.
