### ISSUE TITLE
[notifications] [iOS] Push ticket always returns ok

### ISSUE THREAD

**Issue by 1337LutZ** [expo/expo#9322]
### Summary of Issue
Expo Push Notifications never return an error on iOS whilst the App is uninstalled.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.3
```

### Reproducible Demo
Repository: https://github.com/1337LutZ/android-pn-icon-bug
 
### Steps to Reproduce
1. Install bare push notification repo
2. Allow push notifications on an **iOS**
3. Send a push notification with the curl command: https://docs.expo.io/push-notifications/sending-notifications/#dont-want-to-use-one-of-the
4. Uninstall the Expo client
5. Repeat step 3. You will see that you will always receive a: `"status":"ok"`

### Expected Behavior vs Actual Behavior
When uninstalling the app/expo client, I would expect a response such as with Android:
```
{"data":{"status":"error","message":"\"ExponentPushToken[ExponentPushToken[ps9UllInqLuvFmk50K5FWr]\" is not a registered push notification recipient","details":{"error":"DeviceNotRegistered"}}}
```

Actual behavior:

Android uninstalled:
```
{"data":{"status":"error","message":"\"ExponentPushToken[ExponentPushToken[ps9UllInqLuvFmk50K5FWr]\" is not a registered push notification recipient","details":{"error":"DeviceNotRegistered"}}}
```

iOS installed:
```
{"data":{"status":"ok","id":"0e24f215-089e-4329-b6b1-3be31a94b404"}}
```

iOS uninstalled:
```
{"data":{"status":"ok","id":"c185c845-d0a3-4b37-907c-c40370b36a65"}}
```

Resources with similar issues regarding Apple:
- https://developer.apple.com/forums/thread/88332
- https://stackoverflow.com/questions/39290613/apns-http2-api-not-returning-status-410-after-uninstalling-app
- https://github.com/firebase/quickstart-ios/issues/332

**Comment by cruzach** [comment]
To provide context: @1337LutZ  and I dug into this a tiny bit more, and it seems like APNS can take a while (up to a few days) to register that an app has been uninstalled. This message should be relayed through the Expo notifications service once that happens (upon sending a notification), but we will keep this issue open until we've confirmed that behavior over the next few days

**Comment by ide** [comment]
The Expo notification service just reports what Apple (iOS) or Firebase (Android) reported. If Apple reports that they received the notification fine, the Expo notification service will say that Apple received the notification fine. We intentionally try not to abstract over APNs and FCM very much unless necessary.

**Comment by 1337LutZ** [comment]
After a week of waiting the 2 iOS Push Tokens still return a 200 OK. Im not sure if this is on iOS's end or not. I can DM anyone at Expo to check them.

**Comment by ide** [comment]
I'm not sure there's anything to do here. If the Expo push notification service is saying OK in the push *receipts* (not push tickets), it's because the Apple push notification service is saying OK.

**Comment by switz** [comment]
I'm trying to test my failure modes (so I can duly respect notification delivery rules) and no matter if I turn off notifications on my app settings or not, expo always reports the receipt as `ok`. Not a huge deal, but I'm trying to be respectful of both Apple and my users. Any idea what it takes to trigger a failure so I can properly disable expo push tokens?

I can just implement the supposed behavior but without a real world tests its tough to ensure it works. I don't want my push notifications getting disabled down the line because I didn't handle it properly.
