### ISSUE TITLE
await Linking.getInitialURL(); return wrong deep link after Build apk

### ISSUE THREAD

**Issue by imdeepakchahar** [expo/expo#9327]
## 🐛 Bug Report

##Summary of Issue
 `await Linking.getInitialURL();` return wrong deep link after Build APK

## Environment - output of expo diagnostics & the platform(s) you're targeting
```
Expo CLI 3.22.0 environment info:
    System:
      OS: Windows 8.1 6.3.9600
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.3.9 => 4.3.9
```

## Steps to Reproduce
Just copy demo code

## Demo Code
```
import {
  Linking
} from "react-native";
```
```
let initialUrl = await Linking.getInitialURL();
```

## Expected Behavior
The code  `await Linking.getInitialURL()` should return deep link which if I open that link in the browser then my installed app should open

## Actual Behavior
It returning the link of my expo project **https://expo.io:443/@imchahardeepak/greenapple**

**Comment by SleeplessByte** [comment]
Import `getInitialURL` from `expo-linking` instead:

```typescript
import { getInitialURL } from 'expo-linking'

let initialUrl = await getInitialURL()
```

**Comment by brentvatne** [comment]
you need to set a `scheme` in app.json otherwise there is no url to link to and so it falls back to the expo uri

**Comment by brentvatne** [comment]
you have posted this issue three times now. if you post it again i will block you from creating new issues for a while. i gave you a detailed response on your previous issue: https://github.com/expo/expo/issues/9255#issuecomment-659664743
