### ISSUE TITLE
Jest-preset expected to define transform warning

### ISSUE THREAD

**Issue by fokke-m** [expo/expo#9328]
Hello,

When I have a new Expo project and run a simple test as described in the expo testing documentation I always get a warning:

`Expected react-native/jest-preset to define transform[^.+\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$]
react-native/jest-preset contained different transformIgnorePatterns than expected`

My package.json:

```{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "verbose": true
  },
  "dependencies": {
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "jest-expo": "^38.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0",
    "react-test-renderer": "^16.13.1"
  },
  "private": true
}
```

My jest.config.js file:

```
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

module.exports = {
    'transform': {
      preset: 'jest-expo',
      transformIgnorePatterns: [
        'node_modules/(?!((jest-)?react-native|react-clone-referenced-element|expo(nent)?|@unimodules/.*|jest-expo/.*|@expo(nent)?/.*|react-navigation|@react-navigation/.*|sentry-expo|native-base))',
      ],
      '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$': require.resolve(
        './jest/assetFileTransformer.js'),
      '.*': './jest/preprocessor.js',
    },
    'setupFiles': [
      './jest/setup.js',
    ],
    'timers': 'fake',
    'testRegex': '/__tests__/.*-test\\.js$',
    'testPathIgnorePatterns': [
      '/node_modules/',
      '<rootDir>/template',
      'Libraries/Renderer',
      'RNTester/e2e',
    ],
    'haste': {
      'defaultPlatform': 'ios',
      'platforms': [
        'ios',
        'android',
      ],
    },
    'unmockedModulePathPatterns': [
      'node_modules/react/',
      'Libraries/Renderer',
      'promise',
      'source-map',
      'fastpath',
      'denodeify',
      'fbjs',
    ],
    'testEnvironment': 'node',
    'collectCoverageFrom': [
      'Libraries/**/*.js',
    ],
    'coveragePathIgnorePatterns': [
      '/__tests__/',
      '/vendor/',
      '<rootDir>/Libraries/react-native/',
    ],
};

```
The test passes ok, but I still get the warning. I checked that the pattern is in place and it seems ok. What could be the problem? If more information is needed please let me know. Thank you!

**Comment by byCedric** [comment]
Hi @fokke-m, these warnings are purely to inform you that something was different than we otherwise would expect. You can see them [here in the code](https://github.com/expo/expo/blob/master/packages/jest-expo/jest-preset.js#L27). It's not recommended to manually override some of these properties because they might change when we release a new SDK. It increases the maintenance burden on your end. Having that said, you can overwrite anything you want if you need more fine-grained control over this. You are eventually the owner/maintainer of the project and you should always be able to mold it in however you want it to work 😄 

If I look at your project dependencies, I think you are using a simple project template at the moment right? If so, you can remove _a lot_ of the configuration you provided. If you move `preset: 'jest-expo'` to the root of the exported object, you inherit all the defaults we set for you. If you are just starting, I would recommend start running Jest with the following config, and only add back what you absolutely need:

```
module.exports = {
  preset: 'jest-expo',
  setupFiles: ['./jest/setup.js'],
  collectCoverageFrom: [
    'Libraries/**/*.js',
  ],
};
```

PS, be sure to check the [docs on jest with expo](https://github.com/expo/expo/tree/master/packages/jest-expo) as well.

Hope it helps!

**Comment by fokke-m** [comment]
@byCedric Thanks so much for taking the time to answer! Some things are still not really clear to me though. I find it confusing what the best place for the configuration is. I have a package.json file, 2 jest-preset.js files and jest.config.js file. Three of them contain configuration data. According to the manual I should put it in package.json but you say I should move it to the root of the exported object. I'm not sure what you mean by that. Could you elaborate? Also, I still don't understand why something is different than expected in the transform options. It looks like everything is in place? Thanks again!

**Comment by byCedric** [comment]
You can [read more about configuring jest](https://jestjs.io/docs/en/configuration) (e.g. `jest.config.js` or `package.json`), there is no definitive answer for the best practice. I like to keep it in `jest.config.js` to allow using JS for configuring it, but that's just my personal preference. Just try to keep 1 type of configuration in your project 😄 

The jest presets are meant for libraries. They can hold the default configuration for certain projects, just like `jest-expo`. I wouldn't recommend creating your own preset if you use it in your project only.

I'm not sure how you set up your project, but you shouldn't have that many configuration files. If you created your project with `expo init` or `npx create-react-native-app` you already have a lot of sensible defaults. 😄

**Comment by fokke-m** [comment]
Thanks again! I was working in a fresh expo install. I only found a jest.config.js file in the node_modules/react-native directory. I think I'll put the config settings in my package.json folder so I can commit these settings to git.
After a fresh install and suggested settings I still get the warning though: 

`Expected react-native/jest-preset to define transform[^.+\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$]
react-native/jest-preset contained different transformIgnorePatterns than expected`

I'm sure it's not a huge problem since my tests work but I wonder if this is supposed to be desired behaviour.

**Comment by armanio123** [comment]
I don't know if this is relevant or not, but if you put a breakpoint on jest-preset.js you'll notice that it's called twice, causing the `transform` to change and the warning to show. Here's both callstacks:
![image](https://user-images.githubusercontent.com/13305542/89707465-ffaf1080-d922-11ea-8d60-0f5c3af2395e.png)
