### ISSUE TITLE
StatusBar not respecting device orientation (iOS)

### ISSUE THREAD

**Issue by thenewt15** [expo/expo#933]
I have my project set to portrait in app.json.

```
{
  "expo": {
   ...
    "sdkVersion": 22.0.0",
    "orientation": "portrait",
```
When I rotate my iOS device, the screen does not go into landscape mode (good). However, the status bar DOES go into landscape mode (bad). The status bar moves with an animation to each side of the screen, depending on how I have my device rotated.

**Comment by terribleben** [comment]
Hi, I can't reproduce this with the Expo tabs template project, using the same app.json shown in your report, on an iPhone SE running iOS 11. Can you maybe post a [snack](https://snack.expo.io) which reproduces the issue for you? (a video/screencast might also be helpful, this sounds like pretty strange behavior.)

**Comment by delantai** [comment]
A moment ago this was actually occurring for me too, which prompted me to search for any existing issues (where the app.json expo > orientation > portrait setting was not being respected by the status bar).  I've since restarted my expo app while trying to test out a snack for this post, and I can no longer produce the behavior on my own project.

It's no longer an issue for me, but just wanted to chime in.  Will take note if it happens again and try to discern what sequence of steps causes it.

**Comment by mchen37** [comment]
I experienced the same issue. I had set `"orientation": "landscape",`  in my app.json. I wanted to lock it to landscape right so I also added `Expo.ScreenOrientation.allow(Expo.ScreenOrientation.Orientation.LANDSCAPE_RIGHT);` in the app. The app itself locks to landscape right but I noticed the status bar still rotated to portrait or other landscape freely.

After creating a snack to test it, I could not reproduce the issue. It has gone away in my app for now as well. I have seen others describe it as an on and off problem. Version info: `"expo": "^23.0.0", "react": "16.0.0", "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",` and the latest version of Expo XDE.

**Comment by stefsulzer** [comment]
Having the similar issue using the Expo iOS app - native status bar will rotate despite ScreenOrientation lock, though I assume it is intended to interact with native code. Differences in my case: I am locking to PORTRAIT, and the only times I have ever seen the status bar stay put is when I have locked my phone orientation manually.

I don't know how to make a snack yet, but when I get to it I'll see what happens.

**Comment by gregblass** [comment]
I'm experiencing this with Expo detached + with the React Native StatusBar component. I can lock the app to portrait mode using app.json, but the status bar component will still move to the side of the phone if I turn it on iOS.

**Comment by gregblass** [comment]
@stefsulzer Exact same thing happening for me.

**Comment by gregblass** [comment]
The only reason I use a StatusBar component is to hide it when I pull up a camera modal. So, while I know it won't really address this issue, if anyone has any insight on how to do that without using a StatusBar component, that would ultimately solve my issue as well.

**Comment by townmulti** [comment]
+1

**Comment by andrzey** [comment]
+1

**Comment by felipebhz** [comment]
+1

**Comment by EmptyCrown** [comment]
+1

**Comment by marylychee** [comment]
+1

**Comment by mikechamberlain** [comment]
Kind of same thing here - I used the app.json to lock to portait, and while the app respected this the status bar would still rotate. I've now re-published and the problem has gone away. Very confusing.

**Comment by devth** [comment]
I'm seeing this issue when using nested `Modal`s. Orientation does not remain locked even though I specified it in `app.json`.

**Comment by KeevanDance** [comment]
Also getting this error, is there any update on this?

**Comment by ghivert** [comment]
Same issue here. Is there any update?

**Comment by pengel1** [comment]
Did anyone find a work around?

**Comment by AdamJNavarro** [comment]
Hey all,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. Recent posts indicate this remains an issue, could one of you please open a new issue with a repro case? We'll get it appropriately assigned and we'll be happy to investigate.

Cheers,  
Adam
