### ISSUE TITLE
Feature request: Rozorpay payment gateway - react-native-razorpay

### ISSUE THREAD

**Issue by imdeepakchahar** [expo/expo#9331]
### Feature request: Rozorpay payment gateway - react-native-razorpay

Razorpay payment gateway is widely used for apps and websites instead of Stripe in India, It has many features and pay options then stripe, please add this gateway else expo is not useful for medium size applications which include a payment gateway in their application in India.

Reference link
[https://github.com/razorpay/react-native-razorpay/](https://github.com/razorpay/react-native-razorpay/)

**Comment by AdamJNavarro** [comment]
Hey @imdeepakchahar,

Thanks for your interest in Expo! We try our best to reserve Github issues for reproducible and actionable bug reports. When it comes to feature requests, it would be greatly appreciated if you could create a Feature Request on our [Canny Board](https://expo.canny.io/feature-requests). We track interest and progress of features there.

Cheers,
Adam
