### ISSUE TITLE
expo/tools/hashAssetFiles failed to load 

### ISSUE THREAD

**Issue by kubido** [expo/expo#934]
this happen when I try to load a component from 'using react-native-elements'

```javascript
import { Header } from 'react-native-elements'
```
My expo version is 22.0.2
![image](https://user-images.githubusercontent.com/247114/32531752-4d064758-c478-11e7-8d01-b8455b39054b.png)

**Comment by sotocodes** [comment]
What was the problem @kubido ?

**Comment by gregbenner** [comment]
I had this... removed node_modules and used yarn to install again, wen't away

**Comment by eleallegue** [comment]
I tried to do that, to a problem that involves hasAssetFile.js but it didn't work...
