### ISSUE TITLE
Bare Workflow | Android : Debug build crashes right after startup: java.lang.AssertionError: APK bundle must contain the expected embedded asset

### ISSUE THREAD

**Issue by andrekovac** [expo/expo#9348]
### Summary of Issue 

**Bare Workflow**, **Android**: After successful build the app crashes with the following exception raised:

```
java.lang.AssertionError: APK bundle must contain the expected embedded asset asset_3a2ba31570920eeb9b1d217cabe58315.ttf
```

**Notes**: 

1. The mentioned `asset_3a2ba31570920eeb9b1d217cabe58315.ttf` is the first item in the `bundledAssets` array which one can observe in the log output when running `expo publish` or if building with `cd android && ./gradlew bundleRelease` it's also the first item you see below `Task :app:bundleReleaseExpoUpdatesAssets` in the build logs.

2. If you set the option `bundleInDebug: true` in `android/app/build.gradle` it will not crash, i.e. if you make this change:

```diff
project.ext.react = [
    entryFile: "index.ts",
    enableHermes: true, // clean and rebuild if changing
+  bundleInDebug: true
]
```

It doesn't crash because the android debug task `Task :app:bundleReleaseExpoUpdatesAssets` is run which somehow is necessary now... But this is of course not what you want. You want your debug build to use JS and assets served directly from the development server and not bundled in an APK.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

**Platform:** Android

Output of `expo diagnostics`:

```
Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.8 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.4.0 => 4.4.0
    npmGlobalPackages:
      expo-cli: 3.22.3
```
 
### Steps to Reproduce

1. In my app in the bare workflow run `react-native run-android`
2. App builds successfully
3. App crashes right away while attempting to launch after a few milliseconds. One still sees a color, i.e. the color 

### Expected Behavior vs Actual Behavior

Should not crash of course.

---

I still can't point my finger on what the reason may be.. I recently updated to react-native 0.62.2 and expo 0.38.8 and had to put in quite some work to get the release build to run (it would also crash with different error messages). Now the release build runs but the debug build crashes with this strange error message concerning embedded assets.

I thought there might be an issue with my `build.gradle` file.. but I compared it with the one of a blank bare expo project and can't find a crucial difference. I also set `enableHermes: true` in a blank bare expo project and everything worked fine.

---

Here a [SO question](https://stackoverflow.com/questions/61883343/expo-apk-bundle-must-contain-the-expected-embedded-asset) with the same error. No reply there yet.

**Comment by brentvatne** [comment]
can you please provide a minimal reproducible example? https://stackoverflow.com/help/mcve

the steps you've provided are not reproducible because we do not have your app and also we don't really want it 👼 we want a minimal reproduction case. you can compare config of a new project created through `expo init` to your app to try to get there

**Comment by andrekovac** [comment]
I found the issue. I mistakenly added the line `import com.facebook.react.BuildConfig;` to `MainApplication.java` which caused `UpdatesController.initialize(this);` to be called in Debug mode which shouldn't happen.

I elaborated more on it [in this StackOverflow reply](https://stackoverflow.com/a/63049053/3210677)
