### ISSUE TITLE
Published app is not receiving OTA updates

### ISSUE THREAD

**Issue by andrewfender** [expo/expo#9352]
After publishing OTA updates via `expo publish`, then force reloading the app on a mobile device, the expected JS updates are not received.

Tested on both Android and iOS. App was published to Google Play Store and Apple App Store prior to any attempted OTA updates.
Expo SDK version 35.0.0.
Expo CLI version 3.18.6.

Updates config in `app.json`:
`"updates": {
      "fallbackToCacheTimeout": 0
    }`

I understand that a value of 0 should mean that the app will download updates in the background if it finds them, which will then be stored in the cache and used when loading up the app next time. I have tried opening the app, leaving it open for several minutes (the update itself is very minor and the app is small overall), then force quitting it and re-opening it again.

Output of `expo diagnostics`:

>   Expo CLI 3.18.6 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.19.0 - C:\Users\andre\AppData\Local\Temp\yarn--1595433052388-0.9320824613427976\node.CMD
      Yarn: 1.22.4 - C:\Users\andre\AppData\Local\Temp\yarn--1595433052388-0.9320824613427976\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.0.10

Hopefully I'm missing something. Thanks for any help.

**Comment by brentvatne** [comment]
check these docs sections out and let me know if this answers your question:

- "What version of the app will my users get?" https://docs.expo.io/workflow/publishing/#what-version-of-the-app-will-my
- "Some native configuration can't be updated by publishing" https://docs.expo.io/workflow/publishing/#limitations
