### ISSUE TITLE
[android][file-system] content:// uris are not usable

### ISSUE THREAD

**Issue by awinograd** [expo/expo#9354]
### Summary of Issue 

The Contacts API returns `contact.image.uri` in the form `content://com.android.contacts/contacts/1064/photo`. However, I can't seem to use the `content` scheme with any file system APIs (e.g. `FileSystem.readAsStringAsync`) as I get the following error:

`Error: Unsupported scheme for location 'content://com.android.contacts/contacts/1064/photo'.`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```

  Expo CLI 3.22.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nodenv/versions/12.14.0/bin/node
      Yarn: 1.12.1 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nodenv/versions/12.14.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8 
      react-native: 0.63.1 => 0.63.1 
```

### Reproducible Demo

https://snack.expo.io/@ouihealth/content:-scheme-error
 
### Steps to Reproduce

1. Open snack on Android
1. Click button and accept permission

### Expected Behavior vs Actual Behavior

Actual: Error thrown

Expected: URI properly resolved

**Comment by barthap** [comment]
I don't know if we want `FileSystem` to have wider support for other schemes than `file://` - the module is intended to work on application local files inside `FileSystem.documentDirectory` and `FileSystem.cacheDirectory`.

However, `content://` scheme is supported by `getInfoAsync()` and `copyAsync()` - for now, as a workaround you can do this:
```js
    const tempUri = FileSystem.cacheDirectory + 'temp_img';
    await FileSystem.copyAsync({from: uri , to: tempUri});

    const result = await FileSystem.readAsStringAsync(tempUri, {
        encoding: FileSystem.EncodingType.Base64,
    });
    console.log(result);

    await FileSystem.deleteAsync(tempUri);
```

I admit, docs are unclear about this and I will strongly consider updating them.

**Comment by awinograd** [comment]
@barthap thanks for the information. `copyAsync` workaround is doing the trick for me. 

For now, it may make sense to have an inverse method of `FileSystem.getContentUriAsync(fileUri)` such as `getFileUriFromContentUriAsync(contentUri)` as an escape hatch. Only thing I'd be worried around with `copyAsync` is the implementation changing underneath me since the behavior isn't documented.

Look forward to seeing what you come up with!

**Comment by awinograd** [comment]
@barthap thanks for your additions to the docs in #9414. It's extremely helpful for RN devs like me who aren't familiar with the underlying native schemes.

**Comment by romain-sen** [comment]
This seems to not be working with the new `expo file system`. But using the `/legacy` one with `await FileSystem.copyAsync` as you did still works fine.

**Comment by barthap** [comment]
@romain-sen What exactly isn't working in the new file-system? Could you create a new issue and give a reproducible example so we can take a look and help?
Perhaps we need another workaround or docs clarification 😅

**Comment by romain-sen** [comment]
> [@romain-sen](https://github.com/romain-sen) What exactly isn't working in the new file-system? Could you create a new issue and give a reproducible example so we can take a look and help? Perhaps we need another workaround or docs clarification 😅

here is the issue : https://github.com/expo/expo/issues/42343
