### ISSUE TITLE
for Web version TextInput does not get focus on mouse click on TextInput, have to leave mouse pressed in order to write

### ISSUE THREAD

**Issue by eytanronen** [expo/expo#9356]
Packages:

  "expo": "^38.0.8"    
  "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
  "react-native-web": "^0.13.4"

import React, { useRef} from 'react';
import {View,TextInput} from 'react-native';

export default function Authenticate({state,setState}) {
  const inputRef = useRef();
  function setFocus() {
    inputRef.current.focus()
  }
  return (
    <TextInput
      onFocus={setFocus}
      ref={x => inputRef.current = x}
      placeholder='Email address'
      onChangeText={(value) => setState(state=>({...state,email:value}))}
      value={state.email}
    />
  )
}

**Comment by brentvatne** [comment]
https://snack.expo.io/@notbrent/expo-issue-9356 - notice this works as expected

please provide a [mcve](https://stackoverflow.com/help/mcve) as i'm not able to reproduce with the code provided. below is my standard reply to these issues:

<hr />

hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by eytanronen** [comment]
Thanks, figured it out ended being a result of having the component wrapped in...

<TouchableWithoutFeedback onPress={() => Keyboard.dismiss()}>
...
 </TouchableWithoutFeedback>
