### ISSUE TITLE
Constants for ios.model does not provide correct device information

### ISSUE THREAD

**Issue by jayeszee** [expo/expo#936]
Not sure if this is a known issue or not but it seems like when I use a simulator like the new iphone x simulator, the values for the Expo.constants are not what I expected.

Expo.Constants.platform.ios.model = simulator
Expo.Constants.deviceName = My Macbook Pro Name

Is this the expected behavior?

**Comment by terribleben** [comment]
Thanks for the report, we need to add the latest device models to our Constants. Will add this in SDK 23.

**Comment by terribleben** [comment]
Actually the simulators may just always return "simulator". Nonetheless, I'll add the newer phone models to constants.

**Comment by terribleben** [comment]
https://github.com/expo/expo/commit/ac4f4d9e33ab7fb229590f0c959fb0322eeb2175
