### ISSUE TITLE
Failed to load screen using imports

### ISSUE THREAD

**Issue by fbryo** [expo/expo#9360]
### Summary of Issue 
failed using import components

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
snack & expo web

### Steps to Reproduce
when separated component to other folder, then using import in app.js

### Expected Behavior vs Actual Behavior

![image](https://user-images.githubusercontent.com/36603375/88248289-dc515800-ccca-11ea-8e2b-ba3cd66b137d.png)

**Comment by brentvatne** [comment]
please share a link to the snack

**Comment by fbryo** [comment]
https://snack.expo.io/@fbr.yo/yove

**Comment by barthap** [comment]
`pages/Home.js`, 3rd line, you are importing from ''
```js
import { FlatGrid, SectionGrid } from '';
```

You probably want to import from `react-native-super-grid`
```js
import { FlatGrid, SectionGrid } from 'react-native-super-grid';
```
