### ISSUE TITLE
Issues while using TaskManager for my Location fetching.

### ISSUE THREAD

**Issue by umerasif0201** [expo/expo#9369]
I'm facing the issue that while fetching location using TaskManager, I'm getting 2 kinds of warnings/errors.
1. [Unhandled promise rejection: Error: Task 'location-tracking' not found for app ID '@umerasif2020/q_management_project'.]
2. TaskManager: Task 'location-tracking' has been executed but looks like it is not defined. Please make sure that "TaskManager.defineTask" is called during initialization phase. 

No idea what is happening, It was working fine previously but no idea why it is not working now. For the current scenario, I'm only getting the location once but after that getting the above warnings/errors.

import * as TaskManager from 'expo-task-manager';
import * as Location from 'expo-location';

const LOCATION_TASK_NAME = 'location-tracking';
TaskManager.defineTask(LOCATION_TASK_NAME, handleBackgroundFetching);

async function handleBackgroundFetching ({ data, error }) {
    if (error) {
      console.log('error', error);
      return;
    }
    if (data) {
      const { locations } = data;
      let point = {
        latitude: locations[0].coords.latitude,
        longitude: locations[0].coords.longitude
      };
    }
}

const { status } = await Location.requestPermissionsAsync();
    if (status === 'granted') {
      await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.High,
        timeInterval: 3000,
        showsBackgroundLocationIndicator: true,
        foregroundService: {
          notificationTitle: 'Background Fetching Enabled',
          notificationBody: 'We are watching your feet movements',
          notificationColor: 'white',
        },
      }
      );
    }

**Comment by AdamJNavarro** [comment]
Hey @umerasif0201,

Can you let me know what platform this is occurring on as well as if you made any changes to the SDK version in between when it was working and when it stopped?

Cheers,
Adam
