### ISSUE TITLE
Getting error when running npm install.

### ISSUE THREAD

**Issue by mehtaanshul** [expo/expo#937]
i am getting this error when i run npm install
npm ERR! tar.unpack untar error /tmp/npm-12569-62992e7e/github.com/expo/react-native/archive/sdk-20.0.0.tar.gz

**Comment by jesseruder** [comment]
Can you try running `npm cache clear`?

**Comment by mehtaanshul** [comment]
yes i already tried that but its not working ??

**Comment by mehtaanshul** [comment]
It worked. Thanks
