### ISSUE TITLE
canopenurl all of a sudden incorrectly returns whether or not an app link can be opened

### ISSUE THREAD

**Issue by tylerthedeveloper** [expo/expo#9371]
### Summary of Issue 

Previously I could launch twitter with the twitter uri scheme: `twitter://user?screen_name=${twitter}`

I have always had twitter in my LSApplicationQueriesSchemes in app.json

I know there is a breaking change (maybe in expo-linking, SDK change, still trying to pinpoint my changelist, thinking could be SDK 38)

I know this works because of 2 reasons:
- I can type in the browers the applink and it opens the app
- I can skip the "canopenUrl" and just "openurl" with the same URL variable, and it correctly opens the app

Only other thought is there could be some change in apple's info.plist requirements on twitter?

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

I am building a standalone app with react native on both ios and android.

This correctly validates "canopenurl" for both TWITTER AND FACEBOOK -> which doesn't work either on ios but does on android

  Expo CLI 3.21.13 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
    npmPackages:
      expo: ^38.0.0 => 38.0.3 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 

### Steps to Reproduce

simply call linking.openurl(`twitter://user?screen_name=${twitter}`) after adding twitter to app.json in the correct spot

### Expected Behavior vs Actual Behavior

twitter should open the same it does when I force call openUrl

**Comment by brentvatne** [comment]
`Linking.canOpenURL` will not work with a custom `LSApplicationQueriesSchemes` in app.json in Expo client. This field is only applied when you build a standalone app.

**Comment by tylerthedeveloper** [comment]
It does work for other apps though and in android?

Will build a standalone and update here

**Comment by brentvatne** [comment]
@tylerthedeveloper - there are some pretty arbitrarily selected options built into the client: https://github.com/expo/expo/blob/72ce2e9743eeec8490e15857dad7780e1e64d1db/ios/Exponent/Supporting/Info.plist#L72-L79

Android works differently and is more permissive around these things iirc

**Comment by tylerthedeveloper** [comment]
Thank you!

I tested on a stand-alone build and it works.

I did find a quirk with Facebook - if I launch the app via open url to a profile, it caches in the Facebook app.

When I change the url scheme (profile) in the app and click again on openURL with the new one, it goes back to original profile, even after I close the Facebook app.

Do you think this warrants a separate issue?

**Comment by brentvatne** [comment]
you might want to file that as an issue with facebook! we don't really have anything to do with how they handle deep linking. :)
