### ISSUE TITLE
Document picker fail on big files 

### ISSUE THREAD

**Issue by chichke** [expo/expo#9374]
### Summary of Issue 

**DocumentPicker** works great on smalls files but when i try file ~500MB **URI** property is **empty**

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.9 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.5
```

**My code**

```javascript
function uploadAction(set) {
  const pickerOptions = {
    copyToCacheDirectory: false,
    type: "video/*",
    multiple: false,
  };
  DocumentPicker.getDocumentAsync(pickerOptions)
    .then((file) => {
      console.log(file)
      uploadLogic(file, set);
    })
    .catch((err) => {
      console.log(err);
    });
}
```

**Chrome Output**

```
lastModified: 1464602400000
name: "somevideo.avi"
output: FileList
0: File
lastModified: 1464602400000
lastModifiedDate: Mon May 30 2016 12:00:00 GMT+0200 (heure d’été d’Europe centrale) {}
name: "somevideo.avi"
size: 502217770
type: "video/avi"
webkitRelativePath: ""
__proto__: File
length: 1
__proto__: FileList
size: 502217770
type: "success"
uri: ""
```

<img width="827" alt="Capture d’écran 2020-07-24 à 7 18 14 AM" src="https://user-images.githubusercontent.com/26006762/88362710-d9fc0600-cd7d-11ea-98b2-73238fa5c7f4.png">

**Comment by chichke** [comment]
Any updates ?

**Comment by chichke** [comment]
**Minimal code to reproduce**

```javascript
import * as DocumentPicker from 'expo-document-picker';
import React from 'react';
import { SafeAreaView, TouchableOpacity } from "react-native";

const App = () => {
  const onPress = async () => {
    console.log('Starting Loading')
    const {type, uri, name, size } = await DocumentPicker.getDocumentAsync();
    console.log(uri)
  }
  return (
    <SafeAreaView style={{flex: 1, backgroundColor: 'red'}}>
      <TouchableOpacity onPress={onPress} style={{width: 200,  height: 200, backgroundColor: 'white'}}/>
    </SafeAreaView>
  );
};

export default App;
```

**Where the error come from:**

**ExpoDocumentPicker.web.js**

```javascript
reader.onerror = (reason) => {
                        console.log(reason.currentTarget.error) // 
                        reject(new Error(`Failed to read the selected media because the operation failed.`));
                    };
```

**Console.log output** 
```
DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired
.
```

Same as Mozilla documentation 
<img width="1015" alt="Capture d’écran 2020-11-24 à 4 59 44 PM" src="https://user-images.githubusercontent.com/26006762/100118788-75a99a00-2e76-11eb-9715-2b4d7366a9b8.png">



If you

**Comment by chichke** [comment]
[Youtube Video](https://youtu.be/rBQfIvVS87U)

**Comment by jeremyfrancis** [comment]
This is a big deal, need help on this.

**Comment by himrocks33** [comment]
Why is this bug closed?  This still fails on Web.  Anyone have a work around for web?

**Comment by himrocks33** [comment]
@chichke any work around?

**Comment by KyleHagy** [comment]
Had this same problem and figured out a solution.

On web, don’t rely on using the uri for big files. expo-document-picker returns a Base64 string for the uri that bloats memory. It can crash the browser or result in uri being empty entirely.

The happens because Chrome’s JS engine has limits on string size. 
> In V8 (used by Chrome and Node), the maximum length is 229 - 24 (~1GiB). On 32-bit systems, the maximum length is 228 - 16 (~512MiB). [^1]

Instead use the `File` object and generate a Blob URL with `URL.createObjectURL(file)`. It gives you a compact blob:<uuid> reference that points to file bytes.

You can also disable base64 and cache copying on web to prevent potential crashing if large files are selected by inserting the following: 
```
base64: false,
copyToCacheDirectory: false
```

[^1]: [MDN Web Docs – String.prototype.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length)
