### ISSUE TITLE
Asset Download Fails - Wrong extension [expo-updates] [bare] [ios]

### ISSUE THREAD

**Issue by mdcuk34** [expo/expo#9375]
### Summary of Issue
A bare expo IOS application fails to download changed assets from our own S3 bucket due to requiring the file extension.
- `expo export` creates all assets in the `assets` folder with no file extension. e.g. `cec49ef2741941ccb25a382cfa463189`.
- ios app is requesting `assets/cec49ef2741941ccb25a382cfa463189.png` and receives access denied due to the correct url actually being `assets/cec49ef2741941ccb25a382cfa463189`.

```
2020-07-23 17:01:00.543811+0100 Test App[7736:11806467] error loading asset cec49ef2741941ccb25a382cfa463189.png: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>XXXX</RequestId><HostId>XXXX</HostId></Error>
```

### Environment 
- ios - bare 
- S3 bucket hosting content of an expo-export

```
  Expo CLI 3.20.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: 37.0.10 => 37.0.10 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: 0.61.5 => 0.61.5 
```
 
### Steps to Reproduce
- Build a bare IOS application with a couple of images
- Run app
- Change one of the images
- Run an expo export and upload build to S3 
- Reload the native app to fetch the latest update
- Receive `error loading asset` 

### Expected Behavior vs Actual Behavior
- Expect the native app to use no `.png`  when requesting files from the hosted update.
OR
- Expect `expo export` to generate assets with file extensions.

**Comment by samithaf** [comment]
Seems like a bug and following change should fix the problem. We will need to use the `assetUrlOverride` string as it is when that property is a absolute URL. 

This method is in EXUpdatesLegacyUpdate 


```
+ (NSURL *)bundledAssetBaseUrlWithManifest:(NSDictionary *)manifest
{
  NSURL *manifestUrl = [EXUpdatesConfig sharedInstance].updateUrl;
  NSString *host = manifestUrl.host;
  if (!host ||
      [host containsString:kEXUpdatesExpoIoDomain] ||
      [host containsString:kEXUpdatesExpHostDomain] ||
      [host containsString:kEXUpdatesExpoTestDomain]) {
    return [NSURL URLWithString:kEXUpdatesExpoAssetBaseUrl];
  } else {
    NSString *assetsPath = manifest[@"assetUrlOverride"] ?: @"assets";
    if ([assetsPath hasPrefix:@"http://"] || [assetsPath hasPrefix:@"https://"]) {
          return [NSURL URLWithString:assetsPath];
      } else {
          return [manifestUrl.URLByDeletingLastPathComponent URLByAppendingPathComponent:assetsPath];
      }
  }
}
```

**Comment by mdcuk34** [comment]
I can confirm @samithaf patch does fix the issue.

There's a repo here: https://github.com/mdcuk34/updates-bug-repo you'll just need to: 
- Change the updates url
- Build the native app (release)
- Add a new image to assets and edit the `App.tsx` to reference it
- Run `yarn build`
- Upload the update to you your URL
- Watch the app fail to download the new asset
- Apply the fix and start steps from the start

**Comment by peter-jozsa** [comment]
I'm experiencing this error on self-hosted and self-built (turtle-cli) managed workflow too. Any workaround for the issue?

**Comment by samithaf** [comment]
@peter-jozsa There was a bug with SDK 37 and above code I posted fixes the following issue in ObjectiveC code. 

When you specify an absolute URL for --asset-url prop then Expo was appending that URL to --public-url prop instead of using --asset-url as it is when the --asset-url is an absolute URL.

**Comment by peter-jozsa** [comment]
I see you have another problem related to absolute asset urls. Actually our usage is ok with the way how Expo is appending `--asset-url` to `--public-url`. I just wanted to share that our problem was caused by the default relative `"./assets"` value since iOS is unable to resolve this path when appended to URLs. This is why we saw the same error messages in the device logs.

**Comment by brentvatne** [comment]
PRs related to assetUrlOverride:

- https://github.com/expo/expo/pull/10342
- https://github.com/expo/expo/pull/10337
