### ISSUE TITLE
Case-error in SDK for Modal require() statement

### ISSUE THREAD

**Issue by hctom** [expo/expo#938]
I'm getting the error `Unable to resolve ./modal/Modal" from ".//node_modules/expo/src/Expo.js`during compilation.

The following snippet from `Expo.js` (from line 111 on) shows directory name with lowercase `m`:

```js
get Modal() {
  return require('./modal/Modal').default;
},
```

...but in the filesystem, the directory has an uppercase `M`:

`./node_modules/expo/src/Modal/Modal.js`

Manually changing the code in the package solves the error, so I'd really appreciate to see this fixed ;)

**Comment by royderks** [comment]
Having the same issue, what version of Expo are you using?

**Comment by ide** [comment]
Sorry about this -- published 22.0.3 to npm, which changes the name of the directory itself to be lowercase.

**Comment by hctom** [comment]
Thanx for the fix in such a short time!

**Comment by tianlinzx** [comment]
This issue occurs again on version `28.0.0`
