### ISSUE TITLE
[expo-updates] Assets not downloading

### ISSUE THREAD

**Issue by arberK** [expo/expo#9380]
App does not trigger a download for assets. Bundle gets downloaded und updated normally. I host updates on my own server and I could see the requests comming from expo-updates only for the manifest and js bundle, but not for assets. 

Since I could not share my privte project, I made a rep. demo, where updates are hosted by Expo.  Even in this case the app does not update at all. 

### Reproducible Demo
https://github.com/arberK/OTATest

 
### Steps to Reproduce
(Tested only on Android)
run `react-native run-android --variant=release`
run `expo publish` 

### Expected Behavior vs Actual Behavior
Expected: App downloads bundle and assets
Actual: App downloads bundle but not asset

`    npmPackages:
   react-native: 0.62.2 => 0.62.2
   expo-updates: 0.2.11
`

**Comment by mdcuk34** [comment]
What happens for you on IOS? Could be related to: https://github.com/expo/expo/issues/9375

**Comment by arberK** [comment]
> What happens for you on IOS? Could be related to: #9375

Same issue on iOS also. The issue on my project is that expo-updates does not trigger any download request for my assets.

**Comment by LouisJS** [comment]
I've seen that your Expo.plist was in `/ios/OTATest/Supporting/Expo.plist`
Mine, and as it is documented in the expo-update implementation guideline, i've set mine in `/ios/Supporting/Expo.plist` and made sure i drag'n'drop it in my XCode 'OTATest' project.

**Comment by LouisJS** [comment]
I believe you've forgot the `import 'expo-asset';` in your index.js !
As it is mentioned in https://docs.expo.io/bare/installing-updates/
