### ISSUE TITLE
Expo updates new bundle doesn't load and requires multiple restarts on iOS

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#9386]
### Summary of Issue 
See the real description of the problem in the comments below
~~After pushing OTA updates, I cannot force a manual update on iOS. Have not tested Android. Restarting the app and getting updates works fine, but manual does not. I believe this is failing at  `await Updates.checkForUpdateAsync()` or could  `update.isAvailable` have changed in between the new release of the updater but the types weren't updated? This code worked fine in ExpoKit before I moved to the bare workflow and started using the new expo-updates. The following is my manual updater code which fails~~:

```typescript
export const checkForOTAUpdates = async () => {
  try {
    const update = await Updates.checkForUpdateAsync();

    if (update.isAvailable) {
      Alert.alert(
        'Updates Completed',
        'Updates to the platform have been installed and must be loaded now. Pressing ok will quickly restart the application. You will not lose any visits or data but any video chats will need to be reopened.',
        [
          {
            text: 'Ok',
            onPress: async () => {
              await Updates.fetchUpdateAsync();
              await Updates.reloadAsync();
            },
          },
        ],
        { cancelable: false }
      );
    }
  } catch (e) {
    console.log(`Error when checking for OTA updates: ${e}`);
  }
};
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```shell
Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.1.0 - /usr/local/bin/fish
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4 => 4.4.0
    npmGlobalPackages:
      expo-cli: 3.22.3
```

**Comment by cruzach** [comment]
What version of `expo-updates` are you using? What is the error you're getting?

**Comment by shamilovtim** [comment]
`"expo-updates": "^0.2.11"`

No error, nothing happens after `await Updates.checkForUpdateAsync()`. Update only triggers after app restart.

**Comment by SleeplessByte** [comment]
FWIW, the following code on `expo-updates` `0.2.11` is running in production. We pushed today, and it was working (not requiring a restart). 

```typescript
Updates
  .checkForUpdateAsync()
  .then((value) => {
    if (!value.isAvailable) {
      return Promise.reject(new Error('No updates available'));
    }

    return Updates.fetchUpdateAsync();
  })
  .then((value) => {
    if (!value.isNew) {
      return Promise.reject(new Error('No new updates available'));
    }
})
```

If this resolves, running `Updates.reloadAsync().catch(() => {});` restarts the app.

Perhaps related information. In `app.json` we have updates on `ON_RECOVERY`. Maybe the default value (always) breaks the behaviour.

**Comment by shamilovtim** [comment]
@cruzach Can you confirm that app.json default value for expo-updates disables being able to do manual updates? I'm not sure why that would be the case since in our situation both at app start and during long term app run updates are desirable and I believe this isn't uncommon. Since some apps stay open for a long time on users phones, we want to be able to ensure they get updates even if they've had the app open for 3 days straight.

**Comment by SleeplessByte** [comment]
It would be a bug if that's the issue :). 

However, if you check yourself, using a timer or whatever, there is really no point relying on expo to start the first update. We schedule the first update after all Interactions are done. Might be an okay workaround for you, for now :)

**Comment by shamilovtim** [comment]
Yeah for the very first instance of opening the app it's just nice that no extra code is required there. Extra code is always a burden on any project, and since Expo offers the first update built in at app start, we've been taking advantage of that. The rest of our updates are checked semi regularly in the background for as long as the user has the app open. Truth be told, I wish expo-updates offered that as an option on some sort of background thread so we didn't have to have a long running timer doing that. I've recommended it as a feature and I'm puzzled why the expo team doesn't see value in that. On the contrary it seems to me like since long app sessions and infrequent phone restarts are common, expo-updates really should offer an out of the box way to check for app updates during long sessions.

**Comment by cruzach** [comment]
> Can you confirm that app.json default value for expo-updates disables being able to do manual updates?

This is not the case

> nothing happens after await Updates.checkForUpdateAsync()

Have you checked to make absolutely sure `update.isAvailable` is `true`?

**Comment by shamilovtim** [comment]
Ok so I was wrong on this. The manual updater works fine. The issue is that the new build load in general is not consistent. Sometimes it takes multiple app restarts to get the app to actually load the new bundle. It's not timing out the timeout limit for a fact because 15 seconds definitely haven't passed in the time that it exits the splash screen. Sometimes I have to restart the app 3 times to get it to load the new build.

**Comment by shamilovtim** [comment]
This issue is very serious. It's not pulling the new bundle on first app load ever and it takes restarting the app to force the new bundle to load. That means potentially some users will never receive the new bundle at all unless they manually close the app on the launcher or restart their phones. Is there any plan to fix this problem ASAP?

**Comment by cruzach** [comment]
@shamilovtim I haven't been able to reproduce that, and this is the first report like this we've received, so it's not for sure that this is a bug with `expo-updates` yet. As with the original issue you reported (that the manual updater wasn't working), we'll need a reliable reproducible demo to investigate this. I've tested both managed and bare workflow IPAs and haven't had this issue

**Comment by shamilovtim** [comment]
Wait can you confirm if `EXUpdatesLaunchWaitMs` is now set to default at 0 meaning the default behavior of expo-updates is now to not wait for and load updates when they happen? That would explain the problem. Isn't this a big breaking change from the past in which the past timeout was waited about 15 seconds by default? If so that would explain everything.

**Comment by shamilovtim** [comment]
@cruzach  Please see the below. These two are contradictory in the docs (I think):

app.json docs say updates will hold the splash screen for 30 seconds to fetch update by default:
<img width="1106" alt="Screen Shot 2020-07-25 at 3 17 40 PM" src="https://user-images.githubusercontent.com/3495974/88464588-187ee700-ce8a-11ea-8146-43877a79a1f6.png">

vs.

expo-updates docs say it will not hold the splash screen at all by default and will not attempt to load updates on first app load:
<img width="1045" alt="Screen Shot 2020-07-25 at 3 18 16 PM" src="https://user-images.githubusercontent.com/3495974/88464589-1a48aa80-ce8a-11ea-93a8-f3bf3c981e41.png">

In this case it seems like the docs at the bottom are true?

**Comment by cruzach** [comment]
Yeah sorry, we're aware those are contradictory and are planning to align on one. You can find more details on that in [this issue](https://github.com/expo/expo/issues/9368)

**Comment by shamilovtim** [comment]
Thank you! If I set the value in app.json does it somehow override the static value in the plist?

**Comment by cruzach** [comment]
For right now, you do most of the configuration in the native files (expo.plist and androidmanifest), although when publishing we can set these values for you based off of the values you set in app.json **if they aren't provided in the corresponding native files already** - https://github.com/expo/expo-cli/blob/b125430c2e18e73975cf2c8af3a7f2ece18888ed/packages/xdl/src/EmbeddedAssets.ts#L369-L377

Even then though, you'd need to rebuild the binary afterwards, since any native code/native file changes will require a binary update to take effect

**Comment by RocKer004** [comment]
Hi guys, I'm also having this issue and I've been searching for the solution for a long time.. Can you give me a hint of what the best solution here could be ?

**Comment by shamilovtim** [comment]
It depends if you're on bare or managed. Make sure that the timeout variable is set correctly. If you need to force a restart, you will need to code that by hand.

**Comment by aztax-dev-vashu** [comment]
hi
