### ISSUE TITLE
 event to show the horientacion in real time?

### ISSUE THREAD

**Issue by davibar** [expo/expo#9387]
Could someone help me, how to get the orientation of the device in real time every time it changes?

I am using expo-screen-orientation

**Comment by cruzach** [comment]
Hi @davibar, please read the documentation thoroughly before opening up issues- we provide the [`addOrientationChangeListener`](https://docs.expo.io/versions/latest/sdk/screen-orientation/#screenorientationaddorientationchangelistenerlistener) for this use case. You can also use [`getOrientationAsync`](https://docs.expo.io/versions/latest/sdk/screen-orientation/#screenorientationgetorientationasync)

**Comment by davibar** [comment]
> Hola @davibar , lea detenidamente la documentación antes de abrir los problemas. Proporcionamos el [`addOrientationChangeListener`](https://docs.expo.io/versions/latest/sdk/screen-orientation/#screenorientationaddorientationchangelistenerlistener)para este caso de uso. También puedes usar[`getOrientationAsync`](https://docs.expo.io/versions/latest/sdk/screen-orientation/#screenorientationgetorientationasync)


and how do I apply that function?
