### ISSUE TITLE
[docs] Authentication: Suggestion for the Google docs

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo#9391]
When implementing `Google` with `expo-auth-session`, a few things were difficult to understand. This may be my fault; here are a few suggestion to perhaps make it better. [Link to the section in the docs on GitHub](https://github.com/expo/expo/blob/master/docs/pages/guides/authentication.md#google)

## Preamble

The link of `Get Your Config` doesn't go to a place where you can get your config, but instead links to [this tutorial](https://developers.google.com/identity/protocols/oauth2) which _in turn_ links to [the console](https://console.developers.google.com/). The wording **Follow these steps** might be more appropiate.

It then starts out with "you can't use this in the expo client" and then continues with "You can't use this" followed by "But wait, you can, 'just' do abc". For someone who doesn't know the `cloud.google.com` console, there is no such thing as _just_ configuring a website, apart from it being very confusing.

> - Google will provide you with a custom redirectUri which you cannot use in the Expo client.
>   - URI schemes must be built into the app, you can do this with bare workflow, standalone, and custom clients.
>   - You can still develop and test Google auth in the Expo client with the proxy service, just be sure to configure the project as a website in the Google developer console.

I have a few suggestions that are detailed steps how everything works. For example, it was unclear to me how the web project steps worked for non-expo client usage (web usage), or how to get the **GOOGLE_UUID**, which is listed nowhere. Additionally, I think it should have a bit on the data to send to the server, for Auth Code flow, as it's not clear _which_ guide to follow on the Google Documentation Website.

## Suggestion:

Change the listed scopes:

```diff
- scopes: ['openid', 'profile'],
+ scopes: ['openid', 'profile', 'email']
```

Consider listing them out (instead of having them resolve), so that they match better with Google's documentation:

```diff
- scopes: ['openid', 'profile'],
+ scopes: [
+   'openid', 
+   'https://www.googleapis.com/auth/userinfo.profile', 
+   'https://www.googleapis.com/auth/userinfo.email'
+ ]
```

---

The following information is for _both_ auth code and implicit flow. It's very confusing that these two do not have dedicated steps, but `Firebase` then goes ahead and lists it all out. 

### Expo Client / Web

Google requires the proxy service and a web-project to develop and test using the expo client. The same steps apply for using Google Sign in in `web` projects.

1. [Create a new OAuth client with the **Web Application** type](https://console.developers.google.com/apis/credentials/oauthclient)
2. Under `Authorised JavaScript origins` add your host urls, including:
    - https://localhost:19006 (Web development)
    - https://auth.expo.io (Expo Client Proxy)
3. Under `Authorised redirect URIs` add your redirect urls, including:
    -  http://localhost:19006 (This is assuming you want to invoke `WebBrowser.maybeCompleteAuthSession();` from the root URL of your app.)
    -  https://auth.expo.io/@[username]/[project-slug] (Expo Client Proxy)
4. Copy the `Client ID` on this page (looks like: `[project-id]-[credential-part].apps.googleusercontent.com`)

The part _before_ `.apps.googleusercontent.com` is your `GOOGLE_GUID`.

### Android apps (standalone/bare)

For a slightly more native experience in bare Android apps, you can use the `expo-google-sign-in` package. For a unified setup, follow the steps under _Managed standalone apps, bare workflow, and custom clients_.

### Managed standalone apps, bare workflow, and custom clients

In the bare workflow, managed standalone apps, and custom clients, a custom Redirect URI needs to be built into the app.

#### Android

1. [Create a new OAuth client with the **Android** type](https://console.developers.google.com/apis/credentials/oauthclient)
2. Fill in the package name (from `app.json`)
3. Add the debug SHA (For managed standalone apps use `expo fetch:android:hashes`, this will only work áfter you've made your first build)
4. If you're using app signing, or a custom keystore, add those hashes as well
5. Copy the `Client ID` from the dialog after saving

This is the Client ID _only_ for Android clients. You can hard-code this into your app, or add it to `app.json` via the `extra` key. 
The part _before_ `.apps.googleusercontent.com` is your `GOOGLE_GUID`.

You'll need to **Repeat these steps** if you have a _different production SHA_ (such as using Google App Signing). 

#### iOS

1. [Create a new OAuth client with the **iOS** type](https://console.developers.google.com/apis/credentials/oauthclient)
2. Fill in the bundle identifier
3. Optionally add your app and team id
5. Copy the `Client ID` from the dialog after saving

This is the Client ID _only_ for iOS clients. You can hard-code this into your app, or add it to `app.json` via the `extra` key.
The part _before_ `.apps.googleusercontent.com` is your `GOOGLE_GUID`.

### Other options

- You can change the UI language by setting `extraParams.hl` to an ISO language code (ex: fr, en-US). Defaults to the best estimation based on the users browser.
- You can set which email address to use ahead of time by setting `extraParams.login_hint`.
- If you leave out `prompt`, and the user is already authenticated, no dialog will be shown. Use `Prompt.SelectAccount` to allow a user to _switch_ accounts.

### Server side code

(This section is _only_ applicable to the Auth Code flow)

```diff
+ // You will need the redirectUri to make the request to exchange the token.
+ const redirectUri = makeRedirectUri({
+   // For usage in bare and standalone
+   native: 'com.googleusercontent.apps.GOOGLE_GUID://redirect',
+   useProxy,
+ })

  //

  React.useEffect(() => {
    if (response?.type === 'success') {
-     const { code } = response.params;
+    const codeVerifier = request.codeVerifier,
    }
  }, [response]);
```

In order to validate the access token and exchange it, follow the final steps of [this guide](https://developers.google.com/identity/protocols/oauth2/native-app). You'll need to send the following information to your back-end:

- `response.params.code`: the auth code
- `request.codeVerifier`: the code verifier
- `redirectUri`: the redirect URI
- a way to map the request to a specific key-set, e.g. the `Platform.OS`, the `clientId` or re-use the `redirectUri`.

On the server, you need these:

| query param | |
| --------- | ---- |
| client_id | The client ID obtained from the API Console Credentials page. Must match the client id that was used to obtain the auth code. |
| client_secret | The client secret obtained from the API Console Credentials page. **Never embed this in your app** . _There are no secrets for iOS and Android keys. Leave this field an empty string_.|
| code | The authorization code, passed from the client, as mentioned above  |
| code_verifier | The code verifier, passed from the client, as mentioned above |
| grant_type | The value 'authorization_code.' |
| redirect_uri | The redirect URI, passed from the client, as mentioned above |

You can construct the redirect uri on the back-end, but it's much _safer_ to pass it from the client, as that allows you to make client changes and redirect URI changes, without having to touch the server. 

#### Token exchange

Make a POST request using form urlencoded value, where each key is a query param from the table above:

```
POST https://oauth2.googleapis.com/token
> accept: application/json
> content-type: application/x-www-form-urlencoded
```

**Comment by barthap** [comment]
Hello,
I see you have recently opened a few issues with suggestions to docs. If you're feeling familiar with it, we'd love to see a PR from you!

**Comment by SleeplessByte** [comment]
Certainly! Brent told me to start opening issues when I saw discrepancies, and I wasn't going to invest the time to PR this correctly if these changes are not wanted in the first place. In about 1.5 weeks time I'll be able to PR all of that up, along with anything else.

**Comment by ottob** [comment]
I  have also noticed a couple of issues with the Google Firebase docs.

1. https://github.com/expo/expo/blame/master/docs/pages/guides/authentication.md#L1050 the parameter to `Google.useIdTokenAuthRequest()` should probably be:
```js
expoClientId: 'GOOGLE_GUID.apps.googleusercontent.com',
iosClientId: 'GOOGLE_GUID.apps.googleusercontent.com',
androidClientId: 'GOOGLE_GUID.apps.googleusercontent.com',
webClientId: 'GOOGLE_GUID.apps.googleusercontent.com',
```
instead of `clientId: 'Your-Web-Client-ID.apps.googleusercontent.com',`?
1. https://github.com/expo/expo/blame/master/docs/pages/guides/authentication.md#L1071 the `)` in `disabled={!request)}` should be removed.

**Comment by SleeplessByte** [comment]
Didn't have time to address it yet.

**Comment by SleeplessByte** [comment]
I don't think the docs have been updated

**Comment by SleeplessByte** [comment]
Sure.
