### ISSUE TITLE
[docs] AuthSession: Google - docs has errors for standalone apps

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo#9392]
Related: https://github.com/expo/expo/issues/9391.

My guess is that either I have missed a vital step, or that the following was only ever tested in isolation, and not e2e.

### Documentation assumes using proxy always

The _documentation_ says to add the following code:

```typescript
const useProxy = Platform.select({
  web: false,
  default: true
});
```

The above will make the _standalone_ app use the proxy. The proxy won't send the request back to your app (see below why). But we probably want the following anyway:

```typescript
const useProxy = Platform.select({
  web: false,
  default: Constants.appOwnership === 'expo',
});
```

### Incorrect native redirect URI

The documentation lists the following:

```text
com.googleusercontent.apps.GUID://redirect
```

Using this redirect uri will result in a `400: invalid_request` with the error that the `redirect_uri` parameter is incorrect and **"cannot have authority"**. First feeling is to check the credentials page. Here the correct/same scheme is listed in the key if you follow the link on the [credentials page (only for iOS keys)](https://console.developers.google.com/apis/credentials). 

Removing the `authority` part will result in:

```text
com.googleusercontent.apps.GUID:

# or com.googleusercontent.apps.GUID://
```

- Leaving out the colon (`:`) results into the error "Missing scheme"
- Using the above doesn't work, because the Auth session will never get the redirection, and thus it breaks (it will redirect to google.com).

From the [google documentation](https://developers.google.com/identity/protocols/oauth2):

> `redirect_uri_path` is an optional path component, such as `/oauth2redirect`. **Note that the path should begin with a single slash**, which is different from regular HTTP URLs.

But even when using the following (which doesn't error), the app doesn't redirect to "the app", but to google.com instead:

```text
com.googleusercontent.apps.GUID:/redirect
```

Why? 

Because *com.googleusercontent.apps.GUID* is not our `scheme`, so the app will not respond to this redirection. Okay so just set the `scheme` to `com.googleusercontent.apps.GUID`? **No**, because you will have a different GUID for Android and iOS.

### Solution(s)

```typescript
redirectUri: makeRedirectUri({
  // For usage in bare and standalone
  native: Platform.select({ 
    android: `com.googleusercontent.apps.${GOOGLE_GUID_FOR_ANDROID}:`,
    ios: `com.googleusercontent.apps.${GOOGLE_GUID_FOR_IOS}:`,
  }),
  useProxy,
})
```

- In order to set this up correctly for Android, "app links" for a custom scheme have to be added.
- In order to set this up correctly for iOS, the scheme needs to be added to the Info.plist

#### Package Name and Bundle Identifier match scheme

There is a _third_ option:

Again using the [google documentation](https://developers.google.com/identity/protocols/oauth2):

> The table below shows the appropriate redirect_uri parameter value for each method:
> 
> `com.example.app:redirect_uri_path`
> or
> `com.googleusercontent.apps.123:redirect_uri_path`
>
> `com.example.app` is the reverse DNS notation of a domain under your control. The custom scheme must contain a period to be valid.

Fun fact. According to some documentation from 2013, which is on Google Plus and thus no longer readible, you can also use the _bundle identifier_ **or** _package name_ for the scheme. These are set-up automatically for a client key. This is not documented on the credentials portal.

In this case it's straigh-forward:

```
native: `${Constants.manifest.scheme}:`,
```

**Comment by tsdmrfth** [comment]
@SleeplessByte Thanks for your solution. This link also shows how to do it on iOS https://developers.google.com/identity/sign-in/ios/start-integrating

**Comment by SleeplessByte** [comment]
@tsdmrfth Yes, there are quite a few google guides out there for all the various ways. Do you think we should add those to this documentation as well? This is specifically for `expo-auth-session`, which doesn't use those pods :). Let me know, I'll be crafting PRs next week-ish.

**Comment by tsdmrfth** [comment]
@SleeplessByte Yes you are right. I have a bare RN project that's why i could change scheme from Xcode. 
```
 native: Platform.select({ 
    android: `com.googleusercontent.apps.${GOOGLE_GUID_FOR_ANDROID}:`,
    ios: `com.googleusercontent.apps.${GOOGLE_GUID_FOR_IOS}:`,
  }),
```
this part of your solution absolutely should be added to docs because i spent 3 hours to find a solution for only adding `:` at the end of `redirect_uri`

**Comment by SleeplessByte** [comment]
Yeah. Swamped at the moment but I will PR all this + the related issue when that dies down 👍

**Comment by SleeplessByte** [comment]
Not stale. Sorry, COVID has been hell!

**Comment by SleeplessByte** [comment]
I don't think the docs have been updated
