### ISSUE TITLE
FirebaseRecaptcha throws an Error sometimes

### ISSUE THREAD

**Issue by SirPhemmiey** [expo/expo#9394]
Hi guys, i tried to use the `<FirebaseRecaptcha>` (for invisible reCaptcha) component directly but it's really weird that it throws an error sometimes and works fine sometimes. I'm really skeptical to push this to production as i don't know what will happen to the users of the application.

To give more context, when i click on my sendOTP button, i expect the token to be generated with the onVerify prop. But sometimes, it generates the token (becomes successful) and sometime it doesn't (an error occured). Initially i thought this was related to my internet connection, but i moved to a location with a very good network connection and the issue still remains the same. Please kindly help. Thanks

"expo": "^37.0.0",
"expo-firebase-recaptcha": "^1.1.0", 
"firebase": "7.15.4",

**Comment by IjzerenHein** [comment]
What's the error that you are getting?

**Comment by SirPhemmiey** [comment]
@IjzerenHein , it just says "An internal error occured", which is really difficult to debug what the actual issue is. And sometimes, it just works suddenly. It's strange

**Comment by SirPhemmiey** [comment]
@IjzerenHein, please note that the "visible" Recaptcha with `<FirebeRecaptchaModal>` component works well without issues but I'm having the issue in using the `<FirebaseRecaptcha>` component for invisible recaptcha. I'm just reiterating this so as to be clear.

**Comment by IjzerenHein** [comment]
@SirPhemmiey I don't understand, we don't support invisible reCAPTCHA (yet). How are you using it, can you provide a snack or example?

**Comment by SirPhemmiey** [comment]
Hi @IjzerenHein , yes i can provide a little example. 

First, i copied the `FirebaseRecaptcha` component code from [here](https://github.com/expo/expo/blob/e8e2d55569a68566dcf0cdc48c35503ec66ea5dc/packages/expo-firebase-recaptcha/src/FirebaseRecaptcha.tsx)
And then the sendOTP function;

```import { FirebaseRecaptchaVerifier } from "expo-firebase-recaptcha";
const sendOTPInvisibleReCaptcha = async () => {
        try {
            const phoneProvider = new firebase.auth.PhoneAuthProvider(getExpoFirebaseApp().auth());
            const verifier = new FirebaseRecaptchaVerifier(verificationId);
            phoneProvider.verifyPhoneNumber(phone_number, verifier).then((id) => {
                setVerificationId(id);
            }).catch((err) => {
                console.log("Error occured here", err.message);
            })
        } catch (err) {
            getSentry().captureException(err);
        }
    };
```

And then inside my return function;
```
<FirebaseRecaptcha
                    firebaseConfig={getExpoFirebaseConfig()}
                    onLoad={() => {
                        console.log("loaded");
                    }}
                    onError={() => {
                        console.log("error loading");
                    }}
                    onVerify={(token) => {
                        console.log("tokenYeah", token);
                        if (token) {
                            setVerificationId(token);
                            setIsToken(true);
                        }
                    }}
                />
```

**Comment by SirPhemmiey** [comment]
With that, i can achieve an invisible reCaptcha and it'll just navigate me to the otp screen where I'd input the code and get logged in. But the surprising thing is that it doesn't work always. Out of 10 tries, it works like 5 times

**Comment by IjzerenHein** [comment]
Your example seems incomplete, if you provide a working snack example I might be able to help.

**Comment by SirPhemmiey** [comment]
@IjzerenHein this is literally all the code related to this issue. But i have provided a working snack as you suggested [here](https://snack.expo.io/@sirphemmiey/c8d4c6)

Thanks

**Comment by IjzerenHein** [comment]
Your snack doesn't compile (e.g. `sendOTPInvisibleReCaptcha` isn't called anywhere). Please provide a working example, complete with test firebase project.

**Comment by IjzerenHein** [comment]
Firebase Invisible reCAPTCHA is now supported as of version 1.3.0 (albeit experimental)
https://github.com/expo/expo/blob/master/packages/expo-firebase-recaptcha/CHANGELOG.md#130--2020-11-23

Please use the latest library and the instructions from docs:
https://docs.expo.io/versions/latest/sdk/firebase-recaptcha/
