### ISSUE TITLE
[docs] Consolidate app.json documentation

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo#9396]
Related #9395 

When searching for the limitations on `app.json` (which fields can I update using OTA, and which need a new binary), searching for `app.json` gets the result on the left. You need to know the _exact_ wording in order to find the result you want to get the information on the right.

| app.json | app.json limitations |
| --------- | ---------------------- |
| ![search results for app.json](https://user-images.githubusercontent.com/1964376/88458198-a65bd180-ce8c-11ea-8110-a002904479e3.png) | ![search results for app.json limitations](https://user-images.githubusercontent.com/1964376/88458221-d2775280-ce8c-11ea-90a1-2882646a1770.png) |

Every single page in these search results has **vital** information for building apps with Expo, but the information is _partially_ overlapping and _partially_ unique. This is fine if you're reading through the docs, but not when you're using the docs as reference material. It would be great if these could be consolidated into one or two items, and not have almost the same title. At _least_ link to the limitations from the configuration.

The reason I'm mentioning this is that quite often (about once a week) someone on the slack asks "what can I update", and "just search for `app.json`" isn't actually a usable answer.

**Comment by shamilovtim** [comment]
My problem in #9386 kind of stemmed from this and plus the breaking changes from ExpoKit. It's not clear whether expo-updates can be controlled via app.json anymore on the bare workflow. I'd assume not since those values are in native manifests now but app.json docs don't specify and also didn't call out the breaking change from ExpoKit.

**Comment by SleeplessByte** [comment]
![image](https://user-images.githubusercontent.com/1964376/153388867-f47d1e70-801c-4ac6-89b6-b5eb22097c95.png)

Still relevant, but search is a bit better now.

**Comment by SleeplessByte** [comment]
I don't think this has improved
