### ISSUE TITLE
exp detach not working?

### ISSUE THREAD

**Issue by VinZenTz1989** [expo/expo#94]
When I detached the ios and andriod project 
I couldn't start project from xde or exp 

**iOS**
Error running `xcrun simctl openurl booted exp33f7b95f99f042bb9a9757a30db770fb://localhost`: An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)

**Android**
I could run my app but if I wanna see the result I have to open it again 
The Live Reload or Hot reloading doesn't affect

**Comment by terribleben** [comment]
Hi, the iOS error you see from XDE indicates that your app doesn't exist on the device yet. After you detach, make sure you run `pod install`, open the `xcworkspace` in Xcode, and build+install your app on your device.

**Comment by jesseruder** [comment]
> I could run my app but if I wanna see the result I have to open it again
The Live Reload or Hot reloading doesn't affect

Can you add more details? Do you have dev set to true in XDE? When you reopen the app is it successfully getting the new code?

**Comment by VinZenTz1989** [comment]
I got error with these lib 
cxxreact/JSBundleType.h file not found
jschelpers/JavaScriptCore.h file not found

that's why I could install the app to simulator

**Comment by VinZenTz1989** [comment]
I did what you guys suggest now. It's working but Android's still broken when open Hot reloading feature 

![screen shot 2560-03-28 at 1 43 45 am](https://cloud.githubusercontent.com/assets/13885730/24372420/1a2e8e5c-1358-11e7-9f1c-0b3556f76c02.png)

**Comment by jesseruder** [comment]
That's a different issue, you need to open that url with port `:80` instead of `:-1`. The next version of XDE will fix that but for now you can change the url manually. Going to close this issue since the initial issue was resolved.
