### ISSUE TITLE
Expo.plist how to use variables like $(PRODUCT_NAME)

### ISSUE THREAD

**Issue by midoushitongtong** [expo/expo#9404]
hi
Because I use `bare workflow`, I want to dynamically set `EXUpdatesReleaseChannel` when building.

But now I can get it in my `Info.plist`, but I can't get it in `Expo.plist`. Any suggestions?

I am using [react-native-config](https://github.com/luggit/react-native-config)

**Comment by cruzach** [comment]
Since the bare workflow is a normal, react native project, this is handled in the same way you'd dynamically set any plist value in Xcode. Have you already tried setting a value under your app's `Build Settings` > `User-Defined` values, and then placing `$VARIABLE_NAME` in expo.plist?

**Comment by midoushitongtong** [comment]
> Since the bare workflow is a normal, react native project, this is handled in the same way you'd dynamically set any plist value in Xcode. Have you already tried setting a value under your app's `Build Settings` > `User-Defined` values, and then placing `$VARIABLE_NAME` in expo.plist?
> 
> Closing since this is not a bug with the Expo SDK

I've tried your suggestion, but it doesn't work.

I've tried `${VARIABLE_NAME}` `$(VARIABLE_NAME)` `$VARIABLE_NAME`

Did I do something wrong?

**Comment by grifotv** [comment]
@midoushitongtong An alternative would be overriding the `Expo.plist` values [as stated here](https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#configuration):

> On iOS, you may set these properties at runtime by calling [UpdatesController.sharedInstance setConfiguration:] at any point before calling start or startAndShowLaunchScreen, and the values in this dictionary will override Expo.plist.

I can see this feature was added by @esamelson with this commit https://github.com/expo/expo/commit/d0394e59110531342dea2a132d3f7f3b60bdd4b6 - thanks btw 🙏

It would be great to have some guidance on how to accomplish this override on iOS. For instance, that's my `AppDelegate.m`:

```objective-c
...

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if DEBUG
  InitializeFlipper(application);
#endif
  
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
  self.launchOptions = launchOptions;
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  #ifdef DEBUG
    [self initializeReactNativeApp];
  #else
    EXUpdatesAppController *controller = [EXUpdatesAppController sharedInstance];
    controller.delegate = self;
    [controller startAndShowLaunchScreen:self.window];
  #endif

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
}

...
```

For instance, how could I override `EXUpdatesURL` and `EXUpdatesReleaseChannel` values?

**Comment by kubanac95** [comment]
@grifotv 

I might be late to the party but I finally figured it out how to use `setConfiguration` to change the `EXUpdatesReleaseChannel`. I'm using [react-native-config](https://github.com/luggit/react-native-config) to manage `EXPO_RELEASE_CHANNEL`.

You could probably use something else as well

```
  #else
    EXUpdatesAppController *controller = [EXUpdatesAppController sharedInstance];
    controller.delegate = self;
  
    [controller setConfiguration:(@{@"EXUpdatesReleaseChannel": [ReactNativeConfig envFor:@"EXPO_RELEASE_CHANNEL"]})];
    [controller startAndShowLaunchScreen:self.window];
  #endif
  ```

**Comment by sathishkrishnan20** [comment]
For anyone looking without the react-native-config. Use the below steps.

**Add User Defined Environment Variable:**

1. Navigate to Build Settings.
2. Add a new User Defined Environment Variable named EXPO_CHANNEL_NAME for your specific scheme/environment.


**Add a New Run Script Phase:**

1. Under Build Phases, add a new Run Script Phase.
2. Ensure the script is placed before the Copy Bundle Resources phase.

**Add the Following Script:**
```# Type a script or drag a script file from your workspace to insert its path.
if [ "$EXPO_CHANNEL_NAME" ]; then
  CHANNEL_NAME="$EXPO_CHANNEL_NAME"
else
  # Hardcoded fallback value
  CHANNEL_NAME="staging"
  echo "EXPO_CHANNEL_NAME is not set, using default: $CHANNEL_NAME"
fi

/usr/libexec/PlistBuddy -c "Set :EXUpdatesRequestHeaders:expo-channel-name $CHANNEL_NAME" "${PROJECT_DIR}/<app_name>/Supporting/Expo.plist"
```

Note: Replace the <app_name> with your application/project name

This will replace the expo-channel-name value in Expo.plist file

**Comment by tfreitas90** [comment]
I was able to do it for iOS. I have `react-native-config` and a var named `ENVIRONMENT` on my `.env`. I added the following code on `didFinishLaunchingWithOptions` inside `AppDelegate.mm`. Got the info mainly from [here](https://docs.expo.dev/versions/v50.0.0/sdk/updates/#configuration-options).

I'm using:
 ``"expo": "^50.0.0",
 "expo-updates": "~0.24.13",
 "react-native": "0.73.7",
````

```
//Expo Updates
#import "ExpoModulesCore-Swift.h"
#import "EXUpdatesInterface-Swift.h"
#import "EXUpdates-Swift.h"

  /**
   expo-updates
   
   These properties are set as keys in the Expo.plist file.
   We can also set them at runtime  @see https://docs.expo.dev/versions/v50.0.0/sdk/updates/#configuration-options
  */
  NSDictionary *newConfig = @{
    @"EXUpdatesRequestHeaders": @{
      @"expo-channel-name": [ReactNativeConfig envFor:@"ENVIRONMENT"] //sets expo-updates channel according to our ENV
    }
  };

  [EXUpdatesAppController overrideConfigurationWithConfiguration:newConfig];

```
