### ISSUE TITLE
iOS TestFlight Build considerably slower and unusable compared to running in expo client 

### ISSUE THREAD

**Issue by asp3** [expo/expo#9406]
### Summary of Issue 
When testing on an iPhone 11 Simulator using `expo start`, all animations/transitions work very smoothly. However, once we built the app using `expo build:ios` and pushed to test flight, one specific screen becomes unusably slow. This screen uses the packages `react-native-snap-carousel`, `react-native-slide-charts`, and `d3-shape`. All other screens function as they should.

**Comment by byCedric** [comment]
Hi @asp3, thanks for the issue report. Unfortunately, without a [repro](https://stackoverflow.com/help/minimal-reproducible-example) we can't investigate this issue. I don't think we have encountered a similar issue yet, so this has to be something specific for your project. Have you tried using `expo start --production`?

**Comment by cruzach** [comment]
Closing for lack of info and inactivity

**Comment by Hyeyeah** [comment]
same issue here
