### ISSUE TITLE
How to edit AndroidManifest.xml without detaching?

### ISSUE THREAD

**Issue by lucastobrazil** [expo/expo#941]
I need to set `windowSoftInputMode` for android in order for something to work. See the linked comment below for more info (https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/190#issuecomment-342680446)

Is it possible to set this within an expo-generated app without detaching? My app was made with CRNA.

Thanks!

**Comment by jesseruder** [comment]
We have `windowSoftInputMode` set to `adjustResize`. If you need something else you'll have to detach. Unfortunately there's not a great way for us to make this configurable. Thanks!

**Comment by virus2016** [comment]
+1

**Comment by MedinaGitHub** [comment]
+1

**Comment by terrysahaidak** [comment]
Hi @jesseruder, have you ever seen this lib https://github.com/zubricky/react-native-android-keyboard-adjust ?
That can be your solution.

**Comment by erspark2002** [comment]
> Unfortunately there's not a great way for us to make this configurable. 
What about creating a config directory containing local overrides?
eg. If AndroidManifest.xml file exists in /config/ then use that file instead of the default.
