### ISSUE TITLE
Screen navigation incompatibility

### ISSUE THREAD

**Issue by mateus-costa33** [expo/expo#9410]

**Comment by byCedric** [comment]
Hi @mateus-costa33, thanks for the issue report. Unfortunately, without the information from the issue template, there isn't a lot we can do. We don't know the environment you are using, SDK version, CLI version, libraries used, repro, etc. If you can supply that, please open a new issue. I'm sure we can help you after that!

For now, the only thing I can suggest is [checking the `logcat` logs from an Android device running your app](https://docs.expo.io/workflow/logging/#view-logs-from-android-device-or-emulator). Hope it helps!
