### ISSUE TITLE
getPresentedNotificationsAsync()  function is not working 

### ISSUE THREAD

**Issue by arveenkumar55** [expo/expo#9412]
## 🐛 Bug Report

When i try to use getPresentedNotificationsAsync() method in expo notification I am getting this error. 

![test](https://user-images.githubusercontent.com/39855662/88511691-b5fb2780-cffe-11ea-9496-9fa14d5911d0.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Android 8.0 
sdk 36.0.0 
Mobile honor7c

### Reproducible Demo

import * as Notifications from 'expo-notifications'
  getPushNotificationsAsync = async () => {
    let notification =  Notifications.getPresentedNotificationsAsync()
    console.log('notification in Live chat', notification)
  }

I looked in the documentation the function exists but when i try to use in my project i am getting error 
**[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_NotificationPresenterModule.default.getPresentedNotificationsAsync')]**

**Comment by barthap** [comment]
You are probably using wrong Notifications API. If you are using SDK **36**, then you have to use Notification API described in [SDK 36 docs](https://docs.expo.io/versions/v36.0.0/sdk/notifications/)! In SDK **38** docs, it is called [LegacyNotifications](https://docs.expo.io/versions/v38.0.0/sdk/legacy-notifications/). This API will no longer be available in SDK 39.

Method `getPresentedNotificationsAsync()` is available only in new Notifications API introduced in SDK 38, and it won't work with your version. If you want to use it, update to Expo SDK 38, or if you don't want to, check your `package.json` and imports to use legacy Notification API (see docs for installation instructions).
