### ISSUE TITLE
allow ImagePicker.launchCamerAsync to add overlay to capture images

### ISSUE THREAD

**Issue by dipeshkoirala21** [expo/expo#9416]
I would like to draw some lines or Overlay to guide users to align the camera with the object in a certain way when taking pictures. I don't think I can achieve this with ImagePicker.launchCameraAsync.

**Comment by lukmccall** [comment]
Hi @dipeshkoirala21, it won't be possible using the `ImagePicker`. However, you can use the `expo-camera` to achieve this. You can create a simple camera view and draw something on it. It should be relatively easy.  
For reference, see https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/BarCodeScannerScreen.tsx.
