### ISSUE TITLE
Expo web hook returns incorrect artifactUrl

### ISSUE THREAD

**Issue by anasanzari** [expo/expo#9418]
Received this as request body:
`{
   "status":"finished",
  "id":"7862b6fe-e9e8-499a-8f19-0284897d022d",
  "artifactUrl":"http://localhost:3000/artifacts/32d119fb-a1f1-4867-9d4e-d0a34af0685f",
"releaseChannel":"default",
"platform":"android"
}`

**Comment by byCedric** [comment]
Hi @anasanzari, thanks for your issue report. Unfortunately, without the info from the issue template, we don't exactly know what's going on. We don't know the environment, SDK version, CLI version, project type, etc. Could you please open a new issue and fill in the issue form? With that information, I'm sure we can help! 😄
