### ISSUE TITLE
response of Linking.openURL with "UPI" integration (whatsapp upi, amazon upi, gpay upi, etc) 

### ISSUE THREAD

**Issue by proteche** [expo/expo#9419]
I am trying to integrate upi through hyperlink(basically opening upi apps and transfer money), and want response back like transaction ID, trans Status code etc, but here its just giving me "true" in console log.

**note:** i am able to open any upi app through the upi scheme, and also can do transaction on respective "VPA"
**RESOURCES: -** here is all u need to know about upi linking specs :- https://www.npci.org.in/sites/default/files/UPI%20Linking%20Specs_ver%201.6.pdf

**REPRODUCE: -** 
 1) setup any upi app,(whatsapp upi, amazon upi, gpay upi,...).
2) and just call the below function, in expo client (android physical device)

**CODE: -**
```_handlePress = async () => {
    try {
      await Linking.openURL(
        'upi://pay?pa=testi@bank&cu=INR&appName=TEST&tn=To&am=1.0&pn=TEST&tr=TEST-1574159602902&url=exp://h.anonymous.m.exp.direct:80&refUrl=exp://h.anonymous.m.exp.direct:80',
      ).then((response) => {
        console.log('res', response);
      });
    } catch (e) {
      console.log('err', e);
    }
  };

**Comment by barthap** [comment]
`Linking.openURL()` is a _react-native_ method, and [according to its docs](https://reactnative.dev/docs/linking#removeeventlistener), it just resolves without any response.

**Comment by proteche** [comment]
can you suggest me any alternative options? should i use "expo intent launcher" to launch app?(but not sure how to launch the app with intent Launcher?)
