### ISSUE TITLE
Problems with exp build:ios

### ISSUE THREAD

**Issue by fabiocastrodev** [expo/expo#942]
Hello, I'm having trouble compiling for ios, follow the error below:

exp build:ios -c

Error validating credentials. You may need to clear them (with `-c`) and try again.
[exp] Unable to validate credentials. Request ID 34189370-c579-11e7-bf87-b90d85893784, message: Internal error occurred. Please try again in a few minutes or contact support.

**Comment by jesseruder** [comment]
I'm seeing this error in our logs:

> No teams available on the Developer Portal. You must accept an invitation to a team for it to be available. To learn more about teams and how to use them visit https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html. Your account is in no teams

**Comment by fabiocastrodev** [comment]
Now I have the following problem:

[exp] ============
[exp] Build Status
[exp] ============

[exp] iOS: There was an error with this build.

Build ID: d37544c5-f7a6-47aa-a857-78a00c7f4602

**Comment by terribleben** [comment]
Hi, it looks like your app's icon isn't square, and this broke your build. Can you try making sure your icon is a square and rebuilding? Sorry for the delay. Feel free to follow up if you're still having issues.
