### ISSUE TITLE
The URL returned by await Linking.getInitialURL(); not helping to open app from browser

### ISSUE THREAD

**Issue by imdeepakchahar** [expo/expo#9424]
## REPOSTING 3rd time FOR CORRECT ANSWER

Issues reference #9255 and #9327 
and please don't close issue without solving(knowing that whether it is working or not in developer system) or telling the right alternative/solution

**Comment by brentvatne** [comment]
please provide a minimal reproducible example

**Comment by imdeepakchahar** [comment]
Hello @brentvatne I already provided my `package.json` and `app.json` and `implemented code` and `new updated code` in  #9255 and #9327 . What else I can provide you to which helps you to understand my issue.

**Comment by imdeepakchahar** [comment]
Hi @brentvatne I was testing in different ways and noticed that when I open `greenapple://` manually by typing then my application didn't launch but when I open `greenapple://` with redirection in PHP then my application launched. 

I also double-checked that when I was opening `greenapple://` manually by typing then is I clicked on search or opened `greenapple://` as a web URL. And it was fine I was opening `greenapple://` as a web URL.

So can tell me why manually not working and with PHP redirection is working.

And thanks for your help :)
