### ISSUE TITLE
Barometer always showing 1000 hPa?

### ISSUE THREAD

**Issue by tusindfryd** [expo/expo#9427]
### Summary of Issue 
Should the barometer always be showing exactly 1000 hPa? I have run [the example Snack from the docs](https://snack.expo.io/?platform=android&name=Basic%20Barometer%20usage&sdkVersion=38.0.0&dependencies=expo-sensors&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv38.0.0%2Fbarometer.js) on two different iPhones on three different days and each time it showed 1000 hPa.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
I have run [the example Snack from the docs](https://snack.expo.io/?platform=android&name=Basic%20Barometer%20usage&sdkVersion=38.0.0&dependencies=expo-sensors&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv38.0.0%2Fbarometer.js) in the iOS Expo Client app (iOS 13.5.1, Expo Client 2.16.0, iPhones 8 and 11).

 
### Steps to Reproduce
Run [the example Snack from the docs](https://snack.expo.io/?platform=android&name=Basic%20Barometer%20usage&sdkVersion=38.0.0&dependencies=expo-sensors&sourceUrl=https%3A%2F%2Fdocs.expo.io%2Fstatic%2Fexamples%2Fv38.0.0%2Fbarometer.js) in the iOS Expo Client app and see if the value is right.

### Expected Behavior vs Actual Behavior
I don't think it should show exactly 1000 hPa on three different days on two different phones? Shouldn't the air pressure change at least slightly with the weather? I'm sorry if I got something wrong - maybe it is alright - it just seemed really odd to me.

**Comment by barthap** [comment]
Did you check if these phones support Barometer with [`Barometer.isAvailableAsync()`](https://docs.expo.io/versions/v38.0.0/sdk/barometer/#barometerisavailableasync)?

**Comment by tusindfryd** [comment]
Yeah. It's weird - now it's showing 990 hPa. Maybe the precision is of 1 kPa?

**Comment by barthap** [comment]
Yes, [Apple docs confirm it too](https://developer.apple.com/documentation/coremotion/cmaltitudedata). I tested this on my iPhone XS and it showed me 980 hPa.

**Comment by tusindfryd** [comment]
Except - isn't `data.pressure` cast to int from NSNumber?

**Comment by barthap** [comment]
Right, I debugged `data.pressure` value and it actually is far more accurate.
```
(lldb) po data.pressure
98.48968505859375
```

Bug confirmed, I'll fix it
