### ISSUE TITLE
Show actual error instead of "Main has not been registered error"

### ISSUE THREAD

**Issue by Aryk** [expo/expo#9428]
The thread that housed this very important point is closed:

https://github.com/expo/expo/issues/9042#issuecomment-654894793

> We're looking into a way to better show the error that really matters here- Invariant Violation: "main" has not been registered. is most likely the result of another error that is showing up after upgrading your app (with a dependency you're using).

I would like to open a thread to track the progress of the "bug that is hiding another bug".

I've noticed sometimes that the real error will show up for literally 100ms before this will show up over it. If someone did a ton of changes to their app and gets this...it's virtually impossible to track down.

EXPO VERSION: 38

**Comment by brentvatne** [comment]
you should update to the latest version of react-native used in a new project (i believe 38.0.2) and the latest expo package version. you can initialize a new blank project and compare dependencies. this will vastly improve the error message
