### ISSUE TITLE
Unable to resolve ./modal/Modal

### ISSUE THREAD

**Issue by conblem** [expo/expo#943]
```
Unable to resolve ./modal/Modal" from "./C:\\Users\\Ramon\\Code\\native\\bs.li\\node_modules\\expo\\src\\Expo.js`: could not resolve `C:\\Users\\Ramon\\Code\\native\\bs.li\\node_modules\\expo\\src\\modal\\Modal' as a file nor as a folder","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]},"type":"bundling_error"}"
```
I have been getting this error on my Windows 10 machine.
I tried going back to an older commit but this doesn't fix the error.

![explorer](https://i.imgur.com/hGIHMWL.png)
The files in question are present.

**Comment by robblovell** [comment]
What did you do to fix this?

**Comment by ide** [comment]
We updated expo SDK on npm with a version with the "modal" directory lowercased.

**Comment by robblovell** [comment]
Okay, fix coming shortly then? Or, is there a work around?

**Comment by ide** [comment]
The fix is already on npm, just get the latest package (published yesterday IIRC).

**Comment by robblovell** [comment]
okay, thanks.

**Comment by conblem** [comment]
Yeah i just fixed it by deleting the node_modules directory.

**Comment by marano** [comment]
The fix didn't seem to work for me. I had to manually rename the folder from `Modal` to `modal`.
