### ISSUE TITLE
Facebook login not working with Android build on simulator

### ISSUE THREAD

**Issue by jwm0** [expo/expo#9434]
### Summary of Issue 
When clicked on "Login with Facebook" button the promise is rejected. This issue only concerns the Android build, the login works with iOS simulator and physical device without any issues. I followed the docs step by step and all fields are present in `app.json` (facebookAppId, facebookDisplayName, facebookScheme).

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Android `.apk` build run on simulator (Pixel 3 API 28, Android 9.0 Pie)

JS Error:
```
Error: A valid Facebook app id must be set in the AndroidManifest.xml or set by calling FacebookSdk.setApplicationId before initializing the sdk.
--
```

expo diagnostics:
```
  Expo CLI 3.18.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.18.2
```
 
### Steps to Reproduce
1. Create FB app
2. Fill in all required fields in `app.json`
3. Generate android hash keys and add them in FB panel
4. Run `expo build:android` and select `apk`
5. Open up Android Studio -> Tools -> AVD Manager -> Select device (Pixel 3 API 28) -> Drag and drop the `.apk` into simulator
6. Click "Login with Facebook" button

### Expected Behavior vs Actual Behavior
I get redirected to FB app/site once the button is clicked and can complete the login.

**Comment by giuseppelt** [comment]
Same here. Additional info:
- it fails only when login options (`{ permissions:[...]`) are specified
- grabbed the stack from android, relevant bits:
```
    "nativeStackAndroid",
    Array [
      Object {
        "class": "com.facebook.login.LoginManager",
        "file": "LoginManager.java",
        "lineNumber": 4,
        "methodName": "validateReadPermissions",
      },
      Object {
        "class": "com.facebook.login.LoginManager",
        "file": "LoginManager.java",
        "lineNumber": 5,
        "methodName": "logInWithReadPermissions",
      },
      Object {
        "class": "abi38_0_0.expo.modules.facebook.FacebookModule",
        "file": "FacebookModule.java",
        "lineNumber": 12,
        "methodName": "logInWithReadPermissionsAsync",
      },
```

So it seems it fails on the sdk end when it validates the permissions. Probably something malformed is passed.

**Comment by jwm0** [comment]
When explicitly provided with `appId/appName` to Facebook.initializeAsync() function, it does seem to work. Perhaps the android manifest file is missing some data that's present in `app.json` like the `facebookAppId`?

**Comment by byCedric** [comment]
Hi @jwm0! Thanks for the issue report! Unfortunately, this is a known limitation when using the pre-configured Facebook app from the Expo Client. To make developing authentication with Facebook easier, we ship an app id by default. But, this app has a limited set of permissions. 

From [the docs](https://docs.expo.io/versions/v38.0.0/sdk/facebook/#registering-your-app-with-facebook):

> **No configuration is needed to use the Facebook SDK in the App Store Expo client**, because all of your Facebook API calls will be made with Expo's Facebook App ID. The slight downside to this is that _you can't customize which permissions your app requests from Facebook_ (like `user_photos` or `user_friends`), or integrate Facebook login with other services like Firebase auth. 

As you correctly mentioned, using an app id (with optional name), you can switch to your own Facebook app. I would heavily recommend this option if you want to use another set of permissions.

Hope it helps!

**Comment by giuseppelt** [comment]
@byCedric this issue is not about configuration, this issue is about crashing.

The `logInWithReadPermissionsAsync` crashes on Android if called with options.

Hope you reopen this, and checkout the error.

**Comment by byCedric** [comment]
You are right, I'll double-check the native error. Luckily, I can reproduce this error.
