### ISSUE TITLE
Support `adjustsFontSizeToFit` for custom fonts

### ISSUE THREAD

**Issue by nikki93** [expo/expo#944]
Custom fonts (for example, loaded with `Expo.Font.loadAsync(...)`) don't support use with `Text`'s `adjustsFontSizeToFit` prop. Fix this.

**Comment by cohendl** [comment]
Was this just closed because adjustsFontSizeToFit is now implemented for custom fonts with expo sdk??

**Comment by terribleben** [comment]
Oh for some reason it didn't attach the commit here: https://github.com/expo/expo/commit/471020caf9ea6e326beb6a63f8e73fd603f096cb

**Comment by cohendl** [comment]
Does this now work on current sdk or wait for sdk 23
