### ISSUE TITLE
MediaLibrary.getAssetsAsync() crashes and closes app in expo on android

### ISSUE THREAD

**Issue by JovanShandro** [expo/expo#9440]
### Summary of Issue 
Calling MediaLibrary.getAssetsAsync() after asking for permission to view the camera roll, closes the app
immediately  saying expo has stopped.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.22.3 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.7.1 - /usr/bin/zsh
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    npmPackages:
      expo: ~38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.3

I have tried running the application only on android emulators and my own android device. Same issue happens.

### Reproducible Demo

The closest snack I managed to create is this:
https://snack.expo.io/@jshandro/message-app
even though for some reason I do not get the same error as I cannot seem to go past the 
line asking for permission, maybe because there is something I do not know about permissions in expo snack.

If a repo might be helpful this is the link to it. The lines of code can be found in the components/ImageGrid.tsx file.
https://github.com/JovanShandro/Message-App
 
### Steps to Reproduce
The code snippet that causes this
```js

    const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);

    if (status !== "granted") {
      console.log("Camera roll permission denied");
      return;
    }

    let results: any;

    try {
      results = await MediaLibrary.getAssetsAsync({
        first: 20
      });
    } catch (e) {
      /* handle error */
      console.log(e.message);
      return;
    }
```

Nothing after the try catch block gets executed and the app closes.

### Expected Behavior vs Actual Behavior
As I understand it, the getAssetsAsync function call should return the images as 'Assets' from the camera roll as default.
I don't know if it is expected for this crash to happen if the device has no images in gallery (even though I doubt it), 
however I get the same result on my phone as mentioned above.

**Comment by AdamJNavarro** [comment]
Hey @JovanShandro,

I cloned your repo and it looks like the `after` variable you are passing into is causing the crash. After testing, it seems that if a value that isn't a valid asset ID is passed to `after` the app will crash.

Also, if you want to clean up your imports a bit, you can use `MediaLibrary.requestPermissionsAsync` instead of importing the `Permissions` module.

Cheers,
Adam

**Comment by barthap** [comment]
Thank you Adam for your investigation. It looks like this code is causing crash:

https://github.com/expo/expo/blob/2f1b80c8fec00e4bd8e9ae3424ffe2cfa0cc6e4c/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetQueryInfo.java#L89-L91

There's no validation for invalid number strings and `parseInt()` causes `NumberFormatException`.

**Comment by JovanShandro** [comment]
> Hey @JovanShandro,
> 
> I cloned your repo and it looks like the `after` variable you are passing into is causing the crash. After testing, it seems that if a value that isn't a valid asset ID is passed to `after` the app will crash.
> 
> Also, if you want to clean up your imports a bit, you can use `MediaLibrary.requestPermissionsAsync` instead of importing the `Permissions` module.
> 
> Cheers,
> Adam

Thanks Adam.

**Comment by mSenad** [comment]
Hi Guys, I'm using expo-media-library in order to access the camera's roll photos but the issue with the crashing still persists for me... I'm not sure why though...

Calling: 

`MediaLibrary.getAssetsAsync({
      mediaType: MediaLibrary.MediaType.photo,
      sortBy: MediaLibrary.SortBy.creationTime,
    }).then(this.processPhotos);`

crashes the app on android but it works perfectly with IOS. Not sure if it's the problem in the call where **"after"** parameter is not included for **getAssetsAsync** method but I'm not sure which value should be provided if I'm on the 1st page...

Thanks in advance.

**Comment by barthap** [comment]
Hi @mSenad, are you using bare workflow? If so, I think I've found the solution: https://github.com/expo/expo/issues/10488#issuecomment-701922936

**Comment by mSenad** [comment]
Hi @barthap, thanks for reaching out. No, I'm actually not using the bare workflow, I chose the managed one.

**Comment by barthap** [comment]
I see you are using Expo SDK 37 🙄 There may be dozens of reasons it doesn't work, there were so many MediaLibrary bugfixes in SDK 39. Try upgrading to SDK 39 or maybe create a new temporary Expo project and test it there.

**Comment by mSenad** [comment]
> I see you are using Expo SDK 37 🙄 There may be dozens of reasons it doesn't work, there were so many MediaLibrary bugfixes in SDK 39. Try upgrading to SDK 39 or maybe create a new temporary Expo project and test it there.

Will do. Thanks for helping.
