### ISSUE TITLE
using 'expo-intent-launcher' to launch Third party apps(like maps, chrome, etc) with package name 

### ISSUE THREAD

**Issue by proteche** [expo/expo#9468]
i am able to open apps with linking.openurl(), but due to some reason i need to open apps through intentLauncher, i saw this below code in docs but doesn't know where to add package name. any code snippet will helpful. Thanks in advance

```IntentLauncher.startActivityAsync(IntentLauncher.ACTION_LOCATION_SOURCE_SETTINGS);```

**Comment by barthap** [comment]
Ok, you call function with this signature:
```ts
IntentLauncher.startActivityAsync(action: string, {
  type?: string;
  category?: string;
  extra?: object;
  data?: string;
  flags?: number;
  packageName?: string;
  className?: string;
});
```

On Android side, this creates `Intent` this way:
https://github.com/expo/expo/blob/d56ff1c899b2114190616f8506433e74cd082098/packages/expo-intent-launcher/android/src/main/java/expo/modules/intentlauncher/IntentLauncherModule.java#L71-L101

where `params.getString(ATTR_XXX)` corresponds directly to your JavaScript parameters shown above.

**Comment by proteche** [comment]
@barthap so if my package name is "com.ganna" what should i pass in "action" first parameter.
do i need to pass 'android.intent.action.VIEW'
`IntentLauncher.startActivityAsync(?,{packageName:"com.gaana"})`

**Comment by rohitgurudasani** [comment]
i am also looking for the same, any solution?

**Comment by proteche** [comment]
thanks bro

**Comment by Duduzera1997** [comment]
@proteche How to you arrived a result? i need to open a thrirdy party app with a packageName.
