### ISSUE TITLE
jest-expo cause an error with Firebase SDK 7.5.1 or later

### ISSUE THREAD

**Issue by goodpic** [expo/expo#9477]
### Summary of Issue 

The following jest test case works fine with Firebase SDK 7.5.0 or earlier but cause an error with Firebase SDK 7.5.1 or later.

https://github.com/goodpic/expo-jest-firebase/blob/master/src/__tests__/firebase.spec.ts

```
 PASS  src/__tests__/firebase.spec.ts
  UseProduct
    ✓ fetchProduct (157 ms)

  console.log
    Error: addEventListener and attachEvent are unavailable.
        at goog.events.listen_ (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/node_modules/google-closure-library/closure/goog/events/events.js:280:15)
        at goog.events.listen (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/node_modules/google-closure-library/closure/goog/events/events.js:189:12)
        at ak.addStorageListener [as $] (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/storage/localstorage.js:172:5)
        at pk.addListener (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/authstorage.js:459:3)
        at new Am (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/storageusermanager.js:107:3)
        at new Km (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/auth.js:121:7)
        at Object.instanceFactory (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/auth/dist/src/exports_auth.js:679:16)
        at Provider.getOrInitializeService (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/component/src/provider.ts:187:33)
        at Provider.getImmediate (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/component/src/provider.ts:95:29)
        at FirebaseAppImpl._getService (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/app/src/firebaseApp.ts:127:54)

      at src/__tests__/firebase.spec.ts:16:15
```
### Workaround

remove  "preset": "jest-expo" from jest.config.js

https://github.com/goodpic/expo-jest-firebase/commit/2dadd693bef1b37ac9221c5985803d9250a4ebde#r41011908

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    IDEs:
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.22.3
```

### Steps to Reproduce

``` 
git clone https://github.com/goodpic/expo-jest-firebase.git
```

Place the firebase config file under /config/firebase.ts

``` 
const projectId = 'YOUR_PROJECT_ID'
export const firebaseConfig = {
  projectId,
  apiKey: YOUR_API_KEY,
  authDomain: `${projectId}.firebaseapp.com`,
  databaseURL: `https://${projectId}.firebaseio.com`,
  storageBucket: `${projectId}.appspot.com`,
}
``` 

then run jest

``` 
npm install
npm run test
```

**Comment by brentvatne** [comment]
you should look at at `goog.events.listen_ (/Users/junkaneko/workspace/expo-jest-firebase/node_modules/@firebase/node_modules/google-closure-library/closure/goog/events/events.js:280:15)` to see what it is trying to call `addEventListener` on. it's possible that a web api is expected here, and that web api may not be available on native

**Comment by goodpic** [comment]
Thank you for your comment @brentvatne 
TypeScript compiles and Expo itself works fine with the latest version of Firebase SDK. So I presume it relates to jest-expo only. Probably some change between Firebase SDK 7.5.0 and 7.5.1 is causing this jest-expo issue. 

https://github.com/firebase/firebase-js-sdk/compare/firebase@7.5.0...firebase@7.5.1

**Comment by brentvatne** [comment]
@goodpic - we can't really search out compatibility issues with different versions of arbitrary libraries, but if you investigate and give us more info on precisely what's wrong (eg: no mock for xyz api, where we should mock out addEventListener) we can definitely help with that

**Comment by goodpic** [comment]
@brentvatne Sure, I will try to look into the details.

**Comment by tickietackie** [comment]
@goodpic I also cannot get this to work with version Firebase SDK 7.5.0. I'm talking about the package firebase-tools. Is this the one you are referring to? I'm getting the same error message.

**Comment by MattGoldwater** [comment]
Thanks @tickietackie. In case it helps anyone, you can add those lines of code directly in the test. They need to be added in the setup file or a file that's imported into the test file. [https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)

**Comment by queeeentin** [comment]
sorry, how is this issue being solved? I am having the same issue when my test is importing a file that initialize firebase and setting up auth and Firestore. 

I tired importing  https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom like mentioned, but it is still not working

**Comment by brentvatne** [comment]
@queeeentin - provide a mock for whatever api the library that you are using needs. that's just how jest works :)

**Comment by chanonroy** [comment]
@queeeentin what this could look like is adding this line to your `package.json`:
```
"setupFilesAfterEnv": ["./jest.setup.js"]
```
Then in your `jest.setup.js` file, add the following from @tickietackie:
```
window.addEventListener = jest.fn()
window.attachEvent = jest.fn()
```

**Comment by kav** [comment]
Looking at the firebase side code it seems there is some special react native handling that is perhaps not being triggered on the jest run.
https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/platform_react_native/persistence/react_native.ts#L75
would seem to indicate that the codebase is somewhat aware here. Might just be expanding that context a bit on the firebase side or having jest-expo look a bit more like "react-native" to firebase.

 @goodpic do you want to file a bug over there and see if someone with a bit more context on the platform detection can help out?

**Comment by Matheus8174** [comment]
update your jest configuration to include this rule

````json
  "jest": {
      "preset": "jest-expo",
      "testEnvironment": "jsdom" <-- this rule make the jest undestand the browser stuff
  },
````
