### ISSUE TITLE
ImagePicker.launchCameraAsync imposes a 10-minute limitation on video duration on iOS

### ISSUE THREAD

**Issue by gyoung-panopto** [expo/expo#9482]
### Summary of Issue 

When using ImagePicker.launchCameraAsync to record a video on iOS, the video taken is capped at a maximum duration of 10 minutes. I suspect this is due to iOS' "videoMaximumDuration" flag defaulting to 10 minutes (https://developer.apple.com/documentation/uikit/uiimagepickercontroller/1619146-videomaximumduration), but I don't see a way to override it.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.22.1 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^3.11.0 => 3.13.0

### Reproducible Demo

The repro is very simple and happens with any call to ImagePicker.launchCameraAsync that allows videos.
 
### Steps to Reproduce

1. On iOS, launch the camera using ImagePicker.launchCameraAsync
2. Start recording video
3. Wait until the video has been recording for 10 minutes

### Expected Behavior vs Actual Behavior

Expected:

There is no maximum video duration, or it is configurable through ImagePicker API

Actual:

iOS displays a message about hitting the maximum duration of 10 minutes

Is there a way to configure this limit, or can you add one?

**Comment by barthap** [comment]
There's currently no way to configure it from Expo, but I'm going to add this option.

If you are using bare Expo, you can change it manually by editing `<your-project>/node_modules/expo-image-picker/ios/EXImagePicker/EXImagePicker.m`, about line 170 (inside `launchImagePicker`) add the following line:
```objectivec
//disable video capture duration limit
self.picker.videoMaximumDuration = 0;
```

**Comment by gyoung-panopto** [comment]
Thanks for the quick response and the information/fix!

After posting this I noticed the expo-camera API which allows configuring both the limit and the video quality, I'll try that and see if it will work for me in the meantime, since I haven't ejected my app.

I think it would still be good to allow configuring videoMaximumDuration as well as videoQuality (https://developer.apple.com/documentation/uikit/uiimagepickercontroller/1619154-videoquality) through the ImagePicker API.
