### ISSUE TITLE
[docs] Incorrect documentation hyperlinks in README file

### ISSUE THREAD

**Issue by deanesmith** [expo/expo#9484]
The [expo README.md file](https://github.com/expo/expo/blob/master/README.md) contains hyperlinks to the documentation which appear to be referencing incorrect locations:

Current links:
- [Getting Started](https://docs.expo.io/versions/latest/)
directs to API reference

- [API Reference](https://docs.expo.io/versions/latest/sdk/overview/)
directs to introduction

- [Using Custom Native Modules](https://docs.expo.io/versions/latest/bare/exploring-bare-workflow/)
directs to correct location via redirect 

I can provide a PR to address this matter.

**Comment by barthap** [comment]
> I can provide a PR to address this matter.

Go ahead! 😃

**Comment by barthap** [comment]
Closing, the links were fixed when switching domain `expo.io` -> `expo.dev`
