### ISSUE TITLE
How to re-name of Expo-AV Record (FileSystem)

### ISSUE THREAD

**Issue by driouecheMed** [expo/expo#9489]
## Expo-av && Expo-file-system

I'm recording using expo-av it's work perfectly (recording sounds & playing records).

My problem is all records are saved under this title :

    recording-*.3gp (for example: recording-c860412c-8ce7-4975-8fb7.3gp)

But for some reasons, I want to change the title of the record on the System File to :

    NameOfApp-*.3pg

Anyone could help me to change the file (record) name, Thanks!

**Comment by cruzach** [comment]
Hi! you can just "move" the file and specify the name you want as the destination : https://docs.expo.io/versions/latest/sdk/filesystem/#filesystemmoveasyncoptions

btw- we keep github reserved for bug reports, so questions like this belong on our [forums](https://forums.expo.io/)
