### ISSUE TITLE
No accessToken from Google in standalone

### ISSUE THREAD

**Issue by roblingle** [expo/expo#949]
I think this is related to #69.
 
I have `webClientId` configured in my call to Google.loginAsync, but I don't get an `accessToken` in standalone unless I use `behavior: 'web'`. It does return most of the user data, just not an accessToken. I use accessToken on the server to verify the user.

I'm on SDK 21.

**Comment by brentvatne** [comment]
cc @janicduplessis

**Comment by ArsenyYankovsky** [comment]
Same affects my app, any progress on that?

**Comment by aalices** [comment]
Investigating!

**Comment by rulgf** [comment]
Why is this closed? has the issue been solved?
I'm having the same issue with SDK version 25.0.0
