### ISSUE TITLE
'Download IPA' link has not '.ipa' [docs] 

### ISSUE THREAD

**Issue by hk-dev-app** [expo/expo#9490]
'Download IPA' link at https://expo.io/tools#client has '.tar.gz' file.
I want an '.ipa' file.

**Comment by cruzach** [comment]
You wouldn't be able to install an IPA directly onto your device (unless it's signed with a specific kind of certificate), so an IPA file wouldn't really help you. If you want to download the Expo client on your iOS device, download it from the App Store. If you need to install it on your simulator, you can follow [these steps with the tar.gz file](https://docs.expo.io/distribution/building-standalone-apps/#5-test-it-on-your-device-or), or just start your project with `expo start` and then press `i` to automatically run it on your simulator

**Comment by iamhrayr** [comment]
Any clear instruction how to get Simulator version of `Expo Client` app? The documentation doesn't give information about it, it just tells how to create custom app and make simulator version of it.

**Comment by brentvatne** [comment]
a custom client build or a normal version of the expo client app?

the [iOS simulator](https://docs.expo.io/workflow/ios-simulator/) docs page explains that you just need to start your project and then press `i` to open the project in the ios simulator. it'll install itself. or you can run `expo client:install:ios` to do it manually

**Comment by iamhrayr** [comment]
Yeah, I was referring to the normal Expo client, but somehow just starting the project hangs on `Installing Expo client on iOS simulator`. But that might be some issue from my side. 

Anyway, I found the Expo client app in the `~/.expo/ios-simulator-app-cache/Exponent-2.16.0.tar.app` and installed it by dragging it into simulator.

Thanks for the quick reply.

**Comment by brentvatne** [comment]
@iamclaytonray 

> Yeah, I was referring to the normal Expo client, but somehow just starting the project hangs on Installing Expo client on iOS simulator. But that might be some issue from my side.

is the simulator already open? or is it hanging on opening the simulator?

if it's not open and hanging: https://docs.expo.io/workflow/ios-simulator/#the-cli-seems-to-be-stuck-on

if it's not open and hanging, i'm not sure why that would happen exactly but you can go to Device in the menu bar and reset the simulator:

<img width="309" alt="Screen Shot 2020-08-05 at 4 38 53 PM" src="https://user-images.githubusercontent.com/90494/89474329-26f6b980-d73a-11ea-8746-c22a56469b2e.png">

the workaround you used is also fine of course, just a bit harder to explain to people

**Comment by iamclaytonray** [comment]
@brentvatne - i think you meant @iamhrayr (just so he gets the notif) 🙂

**Comment by brentvatne** [comment]
ah yes, i should pay more attention to autocomplete on mentions ;) thanks @iamclaytonray

**Comment by dacevedo12** [comment]
Hi, I'm working with AWS Device Farm and they only accept valid IPAs. The tar.gz simulator build won't work as it runs on real devices.

Could you please consider publishing it?

**Comment by iamhrayr** [comment]
@dacevedo12 you can download production build from https://expo.io/tools

**Comment by dacevedo12** [comment]
> @dacevedo12 you can download production build from https://expo.io/tools

I only see the apk and tar.gz options. Downloading it from the AppStore won't work, I need the expo client .ipa binary
