### ISSUE TITLE
A server with the specified hostname could not be found (code -1003)

### ISSUE THREAD

**Issue by Pau1fitz** [expo/expo#95]
I am trying to set up react native and run on my phone using expo.

I have [created a react native app using][1] `create-react-native-app`.

After running this command everything gets built on my machine. I have also downloaded the expo app on my phone. 

I then ran `npm start` and was given the following in my terminal:

> enter this address in the Expo app's search bar:
> 
>   exp://12.34.567.89:19000

When I try this I get the following error in expo - 

> Error while loading: A server with the specified hostname could not be
> found (code -1003)

Has anyone come across this issue before?

  [1]: https://facebook.github.io/react-native/blog/2017/03/13/introducing-create-react-native-app.html

**Comment by terribleben** [comment]
Hi there! I think you would be better off asking this (or searching for a similar issue) in [the CRNA repo](https://github.com/react-community/create-react-native-app/issues).

My intuition is that that seems like a highly coincidental IP address, unless you sub'd that in when writing the issue, so it wouldn't be extremely surprising to me if it did not exist.
