### ISSUE TITLE
Expo Audio can not prepareToRecordAsync once prepareToRecordAsync has failed

### ISSUE THREAD

**Issue by chromacoma** [expo/expo#9504]
### Summary of Issue 
As expected, Audio can not be prepared for recording when another process has control of the microphone. However, when that process has stopped using the microphone, Audio still can not be prepared for recording.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Happening on ios, i cannot test android so I'm unsure if it happens there

expo diagnostics:
  Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.3

### Reproducible Demo
https://github.com/chromacoma/audio-recording-example

This is the same as the expo audio-recording-example, updated to the current expo and expo-av. There's a try-catch block around the problematic code so that the demo will continue to run.
 
### Steps to Reproduce
To reproduce:
1. Call the phone that the demo will run on and keep the call running in the background throughout
2. run the demo
3. press the record button. The error "Prepare encountered an error: audio session not activated!" will occur
4. end the call
5. press the record button. __The error "Prepare encountered an error: audio session not activated!" will occur again__

### Expected Behavior vs Actual Behavior
I'd hope that, once the call had ended, recording could begin.

**Comment by ronaiza-cardoso** [comment]
Hi, is this fix already published?

**Comment by IjzerenHein** [comment]
Hi! This was released in version 8.5.0 of expo-av.
https://github.com/expo/expo/blob/master/packages/expo-av/CHANGELOG.md

You can use it in bare by installing `expo-av@next` and will be released with the new Expo SDK 39 Client.
