### ISSUE TITLE
[bare] Assets not loading after eject

### ISSUE THREAD

**Issue by giautm** [expo/expo#9517]
### Summary of Issue 
None of any asset was loaded when run project in Expo client
![IMG_2596](https://user-images.githubusercontent.com/12751435/89069215-f2cb7380-d39c-11ea-9c29-52a387ce8e63.PNG)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.23.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.3.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.0/12A8169g - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.23.0
```

### Reproducible Demo

Link to Reproducible repo: https://github.com/giautm/asset-test
 
### Steps to Reproduce

1) Run `expo init asset-test`, choose `tabs (TypeScript)` form the list.
2) Run `expo eject` to eject to bareflow.
3) Run `expo publish`

### Expected Behavior vs Actual Behavior

Asset will load as normal.

**Comment by brentvatne** [comment]
this is awkward but expected behavior. you need to run `expo publish --target managed` to publish for expo client when you eject. the default behavior of `expo publish` in ejected projects is to publish for consumption by a bare app which has a slightly different way of loading fonts

**Comment by giautm** [comment]
Thank a lot, I didn't found any mention about `--target managed` in any where. Even in docs, https://docs.expo.io/workflow/expo-cli/

**Comment by brentvatne** [comment]
going to keep this open while i resolve this

**Comment by brentvatne** [comment]
the next version of expo-cli will include a warning when you run `expo publish` in a bare project with the `expo` package included in package.json

**Comment by hhananda** [comment]
Thank you, I faced the same problem, that's working for me too, `expo publish --target managed`
