### ISSUE TITLE
how to resolve  React.createClass({   error when upgrading to expo 22 ?

### ISSUE THREAD

**Issue by jpca999** [expo/expo#952]
![image](https://user-images.githubusercontent.com/1026325/32693144-863f5a64-c6f3-11e7-8948-bd784cffa662.png)

Heres my package. 

{
  "name": "App-22-1",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "axios": "^0.16.2",
    "create-react-class": "^15.6.2",
    "expo": "^22.0.0",
    "latlng-to-zip": "^0.0.1",
    "lodash": "^4.17.4",
    "react": "16.0.0-beta.5",
    "react-addons-update": "^15.6.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",
    "react-native-calendar": "^0.12.3",
    "react-native-calendars": "^1.5.8",
    "react-native-communications": "^2.2.1",
    "react-native-easy-toast": "^1.0.6",
    "react-native-elements": "^0.16.0",
    "react-native-flexbox-grid": "^0.3.1",
    "react-native-google-place-autocomplete": "^0.3.0",
    "react-native-indicator": "^0.6.7",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-maps": "^0.16.2",
    "react-native-modal": "^3.1.0",
    "react-native-modal-datetime-picker": "^4.11.0",
    "react-native-multiple-select-list": "^1.0.4",
    "react-native-progressive-input": "^1.0.3",
    "react-native-redux-toast": "^1.0.0",
    "react-native-segmented-control-tab": "^3.2.1",
    "react-native-signature-pad": "^0.0.8",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-form": "^5.0.1",
    "redux-persist": "^4.9.1",
    "redux-thunk": "^2.2.0"
  },
  "resolutions": {
    "moment": "2.19.1"
  }
}

===================================================

signin.js where the issue occurs. 

// import React, { Component } from 'react';
import React from 'react';
import {reduxForm} from 'redux-form';

// import createReactClass from 'create-react-class';
var createReactClass = require('create-react-class');

import {
  StyleSheet,
  Text,
  View,
  TextInput,
  TouchableOpacity
} from 'react-native';

import * as actions from '../../actions';

// var Signin = React.createClass({
var Signin = React.createReactClass({

Even after upgrading I still see the error. 

Questions: 
1) Is it ok to install    "create-react-class": "^15.6.2",    in the package  coz expo provides its own version of react.

**Comment by brentvatne** [comment]
I just updated the release notes to clarify this

<img width="742" alt="screen shot 2017-11-11 at 12 22 12 pm" src="https://user-images.githubusercontent.com/90494/32693168-fde6956e-c6da-11e7-8038-5ab5463f0e4e.png">

https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6
