### ISSUE TITLE
Location subscribers persist through fast refresh with no way to unsubscribe.

### ISSUE THREAD

**Issue by Zanchee** [expo/expo#9524]
### Summary of Issue
In the Expo client, if I am currently subscribed to location updates via `Location.watchPositionAsync(options, callback)`, and I make changes to my code, causing a fast refresh, I lose reference to the object due to the reload. As a result, there is no way to reference my old callback to remove it, so every fast reload, adds an additional callback subscribed to updates.

If possible, there should be a way to retrieve the list of currently subscribed callbacks, and remove them. Something similar to `Location.hasStartedLocationUpdatesAsync(taskName)`

**Comment by krachtstefan** [comment]
Have you tried to remove the listener when the component unmounts (with a `useEffect` return function or `componentWillUnmount`)?

**Comment by Zanchee** [comment]
I'll give that a shot! I'm not sure if that would cover a fast reload In the development environment, but if it does, awesome!

**Comment by krachtstefan** [comment]
[This is how](https://reactnative.dev/docs/fast-refresh#how-it-works) fast refresh decides how to reload your component or fully refresh your app.

Without knowing your specific code: the component where you add the listener, should be the component where you remove listener on unmount. This should avoid having dublicates.

**Comment by EvanBacon** [comment]
Try using this in the file to force a refresh
```
// @refresh reset
```

**Comment by Zanchee** [comment]
Thanks to both of you! I'll give it a shot and report back.
