### ISSUE TITLE
How can i add video quality option on android expo player

### ISSUE THREAD

**Issue by prakashtiwari88** [expo/expo#9526]
someone help me I am using **expo player** with **YouTube video server** on my app how can i add **quality option on expo** player i am using java on android studio please share code with me thank you.

**Comment by AdamJNavarro** [comment]
Hey @prakashtiwari88,

We try to reserve github issues for reproducible and actionable bug reports. For questions such as this one, please post in the [How To section](https://forums.expo.io/c/how-to/15) of our Forums.

Cheers,
Adam
