### ISSUE TITLE
Google play Upload failed Your app currently targets API level 28 and must target at least API level 29 

### ISSUE THREAD

**Issue by wsworkshop** [expo/expo#9531]
### Summary of Issue 
I have build a standalone app with SDK 38 and latest exp-cli and when trying to upload it to Google Play I get this error message below.

"Upload failed
Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 29. Learn how.
UPLOAD ANOTHER FILE"

See attached screenshot.
![expo1](https://user-images.githubusercontent.com/343459/89191933-e8c79180-d5a3-11ea-9a04-1a5fa6275a5b.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.23.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
    npmPackages:
      expo: ^38.0.0 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^4.3.9 => 4.4.0
 
### Steps to Reproduce
1. Build a standalone app (managed app) using the latest code base and exp-cli.
2. When uploading it to Google Play i get the error 

### Expected Behavior vs Actual Behavior
The Google requires to target API 29 but current framework version uses API 28. How can I build an app with required API version?

**Comment by tomasgvivo** [comment]
I have the same issue.

A post in the thunkable forum explains this issue.
https://community.thunkable.com/t/everything-you-need-to-know-about-the-api-29-update/709908

> **New Apps**
> Anyone publishing a new app, on or after August 3rd, 2020 must have an APK file that targets Android 10 (API 29)
> 
> **Upgrading Apps**
> If you’re upgrading an existing app, you have until November 2nd, 2020 before this requirement comes into effect.

Is there a solution in progress?

**Comment by tomasgvivo** [comment]
I see there is a pull request in progress: https://github.com/expo/expo/pull/9446

**Comment by AdamJNavarro** [comment]
Hey all,

We are working on getting the SDK38 builders updated this week. As @tomasgvivo linked to, you can follow the progress on that PR. I'm going to close this issue to reduce noise.

Cheers,
Adam
