### ISSUE TITLE
expo build error?

### ISSUE THREAD

**Issue by heyhyungi** [expo/expo#9537]
### Summary of Issue 
Hi, when I build new version, App store & play store application automatically updates without new file.
It only worked well with exact version when I download through both stores.
But it automatically updated new version without any notice/download when the app restarts.
I also asked apple why it happened with some videos, and waiting for the response.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: 37.0.12 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: 3.11.0 => 3.11.0 

### Expected Behavior vs Actual Behavior
Expected Behavior: The app should be working with exact version what I upload play console and apple developer.
Actual Behavior: The app works with new version that I do not upload yet.

**Comment by brentvatne** [comment]
this sounds like you are pushing an over-the-air update to an app. this is enabled by default, you can disable it if you like. more information: https://docs.expo.io/guides/configuring-ota-updates/
