### ISSUE TITLE
Expo notifications still displaying even after setNotificationHandler return false for shouldShowAlert on Android

### ISSUE THREAD

**Issue by Aryk** [expo/expo#9542]
### Summary of Issue 

Using useNextNotifications: true and running:

```ts
Notifications.setNotificationHandler({
  handleNotification: async (notification) => {

    return {
          shouldShowAlert: false,
          shouldPlaySound: false,
          shouldSetBadge: false,
    }
  }
})

```

The notification still shows up at the top while the app is running in Android (but iOS works correctly). My notification config section:

```
    "notification": {
      "iosDisplayInForeground": false,
      "androidMode": "default"
    },
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.5.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.8 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0

**Comment by Aryk** [comment]
Same issue reported by another person:

https://forums.expo.io/t/expo-notifications-still-displaying-even-after-setnotificationhandler-return-false-for-shouldshowalert-on-android/40272

**Comment by barthap** [comment]
Here is a reproducible demo for this issue: https://snack.expo.io/@barthap10/notifications-visibility
Values to experiment with:
- `priority` in `Notifications.scheduleNotificationAsync()` inside `onPress()`
- `shouldShowAlert` in `setNotificationHandler()`

Native unversioned code handling this behavior:
https://github.com/expo/expo/blob/e8894279ee4830cd5423f8c386f5c81e82abf80f/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/presentation/builders/ExpoNotificationBuilder.java#L196-L232

**Comment by Aryk** [comment]
Great...looking forward to having this working!

Is there any way to get this update before SDK 39.0 is out?

**Comment by barthap** [comment]
If you are using bare workflow, then you can edit Java code yourself and apply modifications from the PR above.

If you cannot (don't want) do that, I've found another workaround. It's not nice, but seems to work - `handleNotification` returns a promise, which you can reject. Simple demo:
```ts
let show = false;

Notifications.setNotificationHandler({
    handleNotification: async () => {
      show = !show; //every second message will be shown
        console.log('handleNotification, show:', show);
        
        //reject promise when you want to hide notification
        if (!show) return Promise.reject('This notification should not be shown');

        //and this code will show it
        return {
          shouldShowAlert: true,
          shouldSetBadge: false,
          shouldPlaySound: false,
        }
    },
    handleSuccess: (notificationId) => console.log('onSuccess'),  //when promise resolved
    handleError: (notificationId, error) => console.log('onErr, reason:', error) //when promise rejected
  });
```

**Comment by Aryk** [comment]
Got it, yeah 

> If you are using bare workflow, then you can edit Java code yourself and apply modifications from the PR above.
> 
> If you cannot (don't want) do that, I've found another workaround. It's not nice, but seems to work - `handleNotification` returns a promise, which you can reject. Simple demo:
> 
> ```ts
> let show = false;
> 
> Notifications.setNotificationHandler({
>     handleNotification: async () => {
>       show = !show; //every second message will be shown
>         console.log('handleNotification, show:', show);
>         
>         //reject promise when you want to hide notification
>         if (!show) return Promise.reject('This notification should not be shown');
> 
>         //and this code will show it
>         return {
>           shouldShowAlert: true,
>           shouldSetBadge: false,
>           shouldPlaySound: false,
>         }
>     },
>     handleSuccess: (notificationId) => console.log('onSuccess'),  //when promise resolved
>     handleError: (notificationId, error) => console.log('onErr, reason:', error) //when promise rejected
>   });
> ```
> 
> _Edit: It can also catch another rejection due to handling timeout, because our promise rejection disrupts standard notification handling procedure_

Yeah that's what I was thinking about doing when I want to dismiss. Then I can inspect the error message to see how I should handle the Error...

Super hacky but I guess people in managed workflow must wait until SDK 39. 

Thanks for your input.

**Comment by VictorioMolina** [comment]
Getting same behaviour on Expo 40

**Comment by lieberscott** [comment]
I just tried the solution code and while it at first rejects the error, it then says "notification handling has timed out" and **the notification is displayed**. This is the output of my console:
```
onErr, reason: This notification should not be shown
onErr, reason: [Error: Notification handling timed out for ID 637F9CC8-6420-432F-B63F-A0D60FF0F8BF.]
```

**Comment by lieberscott** [comment]
I'm using the solution code, but while it is at first rejecting the notification, I then am getting a timeout error and the notification is displayed. This is the output of my console:
```
onErr, reason: This notification should not be shown
onErr, reason: [Error: Notification handling timed out for ID 0626C1BA-7149-4707-9BBE-3499EBCC6348.]
```
