### ISSUE TITLE
Background location sticky notification layout

### ISSUE THREAD

**Issue by GiverDead** [expo/expo#9546]
Hi, can i add my own notification layout for foreground service sticky notification on `startLocationUpdatesAsync`?
I have Hebrew text and it written in ltr and at left side of notification. I need write it in rtl and move to right side of notification 

```
    foregroundService:{
        notificationTitle:"אתה נמצא בהובלה פעילה",
        notificationBody :"יש להחתים דיגיטלית את הלקוח בפריקה",
    }
```

![Screenshot_2](https://user-images.githubusercontent.com/15796944/89310910-fd785800-d67d-11ea-83f3-84acaf312c41.png)

**Comment by sjchmiela** [comment]
Frankly speaking I don't think the RTL-ity of the notification title can be governed by notification builder (it's done here https://github.com/expo/expo/blob/1168f4cb255c81f933008943040db4b42c3908fc/packages/expo-location/android/src/main/java/expo/modules/location/services/LocationTaskService.java#L78-L84).

Searching for solutions online I found a [Right-to-left mark](https://en.wikipedia.org/wiki/Right-to-left_mark). See the following StackOverflow answer for information how to add support for RTL in notification text — https://stackoverflow.com/a/45649179/1123156
