### ISSUE TITLE
[expo-notifications] DeviceNotRegistered: The recipient device is not registered with FCM.

### ISSUE THREAD

**Issue by brunoaduarte** [expo/expo#9550]
### Summary of Issue 

token = (await Notifications.getExpoPushTokenAsync({ experienceId: experienceId })).data;
retrieves invalid push tokens
Here are some:

ExponentPushToken[0J23tlOl6Qz92gG9SM4ceI]
ExponentPushToken[qcL4EiLB_aTct8VdVsXFfu]
ExponentPushToken[D5PQ0qDWvvDqoomMg8I2G8]

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Bare workflow

```
  Expo CLI 3.22.3 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Myself\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```

### Reproducible Demo

https://expo.io/notifications
 
### Steps to Reproduce
retrieved token with
token = (await Notifications.getExpoPushTokenAsync({ experienceId: experienceId })).data;

```
https://exp.host/--/api/v2/push/send
POST
{
    "to": "ExponentPushToken[qcL4EiLB_aTct8VdVsXFfu]",
    "sound": "default",
    "title": "Test",
    "body": "Test",
    "data": { "data": "goes here" }
  }
```

### Expected Behavior vs Actual Behavior

```
{
    "data": {
        "id": "20ede6dd-95d8-484d-96aa-3560c21031a3",
        "status": "error",
        "message": "The recipient device is not registered with FCM.",
        "details": {
            "error": "DeviceNotRegistered",
            "fault": "developer"
        }
    }
}
```

**Comment by brunoaduarte** [comment]
I've removed the app and downloaded from Google Play Store again, token changed and now it worked.
This is a serious bug.

**Comment by cruzach** [comment]
Hi! Is this a managed workflow app, or a bare workflow app? Also- is this a standalone app (built with `expo build:[ios||android]`), or are you running in the Expo client app? It helps to provide as much info as possible so we can try to reproduce the problem (I've tested the push token from both managed and bare apps and they seem to be working for me)

**Comment by brunoaduarte** [comment]
> Hi! Is this a managed workflow app, or a bare workflow app? Also- is this a standalone app (built with `expo build:[ios||android]`), or are you running in the Expo client app? It helps to provide as much info as possible so we can try to reproduce the problem (I've tested the push token from both managed and bare apps and they seem to be working for me)

It's a bare workflow project built as standalone app.
```
cd android
./gradlew bundleRelease
```

Seems it just happens for some devices... maybe old devices that doesn't support FCM ? Is that possible?

**Comment by cruzach** [comment]
What devices? I don't believe that's the case, but if it is then those devices are probably documented by FCM. Make sure that you've followed [this guide](https://docs.expo.io/push-notifications/using-fcm/) on setting up FCM and that your submit a new binary afterwards

Those two commands don't really constitute a reproducible demo, [here's a great guide on how to create one](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by brunoaduarte** [comment]
> What devices? I don't believe that's the case, but if it is then those devices are probably documented by FCM. Make sure that you've followed [this guide](https://docs.expo.io/push-notifications/using-fcm/) on setting up FCM and that your submit a new binary afterwards
> 
> Those two commands don't really constitute a reproducible demo, [here's a great guide on how to create one](https://stackoverflow.com/help/minimal-reproducible-example)

I don't know which devices as these were tokens generated by users that downloaded it from the PlayStore...
Anyways new users registered today and the problems seems not to be happening anymore...
I'm not sure of what happened but i think it's ok to close this for now.

Thanks!

**Comment by brunoaduarte** [comment]
Another invalid token just issued `ExponentPushToken[8ITvsCPnjPU1FAyFb8-EUd]`
Can't you check on expo servers what happens in these cases?

**Comment by cruzach** [comment]
@brunoaduarte we document this error in the docs- https://docs.expo.io/push-notifications/sending-notifications/#individual-errors
If you believe this to be a bug then please provide a way for us to reliably reproduce the same behavior on a minimal project

**Comment by brunoaduarte** [comment]
> @brunoaduarte we document this error in the docs- https://docs.expo.io/push-notifications/sending-notifications/#individual-errors
> If you believe this to be a bug then please provide a way for us to reliably reproduce the same behavior on a minimal project

That's impossible. This a problem on the client device... some clients that download my app get these invalid ExpoPushTokens... can't you check on the backend that generates the ExponentPushTokens what's happening?

**Comment by brunoaduarte** [comment]
Expo servers are definetaly presenting some problems, i just tested on a new device. Downloaded the app from PlayStore, notifications worked the first time, second attempt i got the error message `The recipient device is not registered with FCM`.
Here's the invalidated token `ExponentPushToken[KGkalgHgF9QYX6xyljkDpn]`

**Comment by cruzach** [comment]
when you say second attempt, you mean the second time sending a push notification, or you've deleted the app and then re-installed it a second time?

**Comment by brunoaduarte** [comment]
Second time sending a push notification to the same token. I didn't even close the app.

**Comment by cruzach** [comment]
I'm not really sure what exactly is causing this issue, but we aren't seeing any abnormalities with FCM notifications from our end. Expo is simply forwarding along this error message from FCM- it's the `Unregistered device` error listed here: https://firebase.google.com/docs/cloud-messaging/http-server-ref

This looks like a similar issue to [this one](https://github.com/expo/expo/issues/9220#issuecomment-662198504), so just double-check your steps match those

**Comment by brunoaduarte** [comment]
> I'm not really sure what exactly is causing this issue, but we aren't seeing any abnormalities with FCM notifications from our end. Expo is simply forwarding along this error message from FCM- it's the `Unregistered device` error listed here: https://firebase.google.com/docs/cloud-messaging/http-server-ref
> 
> This looks like a similar issue to [this one](https://github.com/expo/expo/issues/9220#issuecomment-662198504), so just double-check your steps match those

I've followed all those steps... otherwise it would not work at all.... 🤷‍♂️

**Comment by Ciberusps** [comment]
Hi, i cant get do i even need to setup FCM using this guide https://docs.expo.io/push-notifications/using-fcm with new [expo-notifications](https://github.com/expo/expo/tree/master/packages/expo-notifications) module there is no even a word about it in expo-notifications docs

**Comment by jwm0** [comment]
I have the same issue, I'm using a TestFlight distributed app. When I generated the Expo Push Token for the first time - it worked just fine when I was testing notifications via https://expo.io/notifications
However, when I reinstalled the app - a new token was generated and this time the above tool throws this error:
```
DeviceNotRegistered: "ExponentPushToken[<token>]" is not a registered push notification recipient
```

**Comment by cruzach** [comment]
@Ciberusps there's a section in the `expo-notifications` module docs guide specifically for this - https://github.com/expo/expo/tree/master/packages/expo-notifications#add-your-projects-credentials-to-expo-server-optional - and it links to that page 😄

**Comment by Vetsch0r** [comment]
Do you have found the issue yet? We have exactly the same problem. Most of the time and for most of the user it does work. But sometimes we receive the message "The recipient device is not registered with FCM." 

We followed the instructions, otherwise it would probably don't work at all?

We're using 38.0.9 with the managed workflow built as standalone

**Comment by aguridisig** [comment]
I have the exactly de same issue. 
I´m using 3.20.3  
The problem is with one token.
I get the error:
 {
    "data": {
        "id": "27843838-a7b3-4ef4-950f-2aa6d7e0f794",
        "status": "error",
        "message": "The recipient device is not registered with FCM.",
        "details": {
            "error": "DeviceNotRegistered",
            "fault": "developer"
        }
    }
}
It seems FCM doesn´t like the ExponentPushToken for this device. It is possible to renew the ExponentPushToken for a device?
Thanks in advance

**Comment by cruzach** [comment]
Deleting the app and reinstalling it will generate a new Expo push token

As I've stated above, Expo is simply forwarding this error message along from FCM. We've had this error message posted a few times, and it's always been a configuration issue, or the device's token is no longer valid (app hasn't been opened in a while or the user revoked notification permissions). 

[Here's a great list of common mistakes](https://github.com/expo/expo/issues/9220#issuecomment-662198504) when setting up FCM notifications in Expo.

Google's documentation is very clear that if you receive this message, you should stop sending notifications to the app: 

> An existing registration token may cease to be valid in a number of scenarios, including:
> - If the client app unregisters with FCM.If the client app is automatically unregistered, which can happen if the user uninstalls the application. For example, on iOS, if the APNs Feedback Service reported the APNs token as invalid.
> - If the registration token expires (for example, Google might decide to refresh registration tokens, or the APNs token has expired for iOS devices).
> - If the client app is updated but the new version is not configured to receive messages.
>
> For all these cases, remove this registration token from the app server and stop using it to send messages.

**Comment by Vetsch0r** [comment]
But how is the handling on Expo for that? When the token is invalid and we call the function _Notifications.getExpoPushTokenAsync()_ do we still receive the invalid token from Expo or does it generate a new one for us automatically? It can't be that the user has to reinstall the app just for that case?

**Comment by cruzach** [comment]
the Expo push token relies on a the device ID, expo experience ID, the application ID, _and_ most importantly the native device token. This device token is what FCM is referring to in the quote I pasted above, and firebase lists when the token changes here - https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId (besides uninstalling/reinstalling, the user can also clear app data)

Currently, we don't expose a method in the managed workflow for you to manually delete this instance ID

**Comment by sjchmiela** [comment]
Is it possible that for some reason the device push token keeps rotating on your device? Maybe if you add a push token listener using [`addPushTokenListener`](https://docs.expo.io/versions/latest/sdk/notifications/#addpushtokenlistenerlistener-pushtokenlistener-subscription) and refetch Expo push token there you'd always have a valid token in place?

**Comment by Vetsch0r** [comment]
In the end I'm not sure what exactly the problem was. We solved it by implementing the routing to APN and FCM by our own. 
After that we had still problems on certain Android devices, but after upgrading to 39.x all our tests went fine and we're now live with everything and it seems working. So I can not tell, if the server side changes or the upgrade to 39 was the solution but at least it works for us now.

**Comment by cruzach** [comment]
The above PR (10908) should help to remedy this issue, so please upgrade `expo-notifications` and if you're still seeing this issue open a new bug report, thanks!

**Comment by virgiledelplace** [comment]
Same issue for me at this day.. on lot of client app

**Comment by samih-sghier** [comment]
same issue here ...

**Comment by beydogan** [comment]
@samih-sghier have you figured out a solution?

**Comment by samih-sghier** [comment]
@beydogan yes at least for my application, so it's been a while but reading through the comments I started remembering what it was.

 My issue was that when I was sending push notifications, I did not know that there is a cap on the amount of data you can send along with your notifications to the expo servers so instead of sending full data package I just send an identifier and when the user clicks on the notification it makes a subsequent request to my server to retrieve the actual data! Lmk if I make sense!

**Comment by beydogan** [comment]
> there's a cap on the amount of data

This was causing `The recipient device is not registered with FCM` errors? 🤔

**Comment by samih-sghier** [comment]
@beydogan as weird as it sounds that was the source of my issue, error message was completely irrelevant to the actual issue. It took me a while to figure it out.. maybe try to replicate the issue by sending big amount of data to expo servers from your local and see if you're going to get the same error.

**Comment by tommyvn** [comment]
to add to this issue:

https://docs.expo.dev/push-notifications/sending-notifications/#push-ticket-errors seems to suggest that `DeviceNotRegistered` is returned along with the ticket ids, as part of the `send` api call.

I say specifically with the ticket id as part of the `send` api call because `DeviceNotRegistered` is again mentioned in the context of the push receipt under the `getReceipts` api call just below this, at https://docs.expo.dev/push-notifications/sending-notifications/#push-receipt-errors, implying that it is present in both the `send` *and* `getReceipts` API responses.

However this does not seem to be the case, the documentation does not match my observation of Push Ticket responses.

Here is my observation:
I have a token that is no longer valid. It *always* returns `DeviceNotRegistered`. I got this token by setting up an app on my phone, sending a valid push notification to the then valid push token, and then removing the app.

at this point in time the push token returns an "ok" status on a `send` api call despite the device no longer being registered, but a `DeviceNotRegistered` on `getReceipts` when I follow up. I believe this aligns with https://docs.expo.dev/push-notifications/sending-notifications/#push-receipt-errors but contradicts https://docs.expo.dev/push-notifications/sending-notifications/#push-ticket-errors .

Personally my workaround will be to always retrieve receipts but it would be good to update the docs to reflect that `DeviceNotRegistered` is not returned with push tickets, push receipts must be retrieved to see this error.
