### ISSUE TITLE
 Cannot find module 'expo-asset/tools/hashAssetFiles'

### ISSUE THREAD

**Issue by Abdullah-Shamhan** [expo/expo#9557]
After ejecting project to bare workflow  I'm getting this error :
`error node_modules\react-navigation-stack\lib\module\vendor\views\assets\back-icon.png: Cannot find module 'expo-asset/tools/hashAssetFiles'.
Error: Cannot find module 'expo-asset/tools/hashAssetFiles'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)`

when i run 
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

dependencies": {
    "@appandflow/masonry-list": "^0.4.0",
    "@react-native-community/masked-view": "0.1.10",
    "expo-blur": "~8.1.2",
    "expo-document-picker": "~8.2.1",
    "expo-file-system": "^9.1.0",
    "expo-font": "~8.2.1",
    "expo-image-picker": "~8.3.0",
    "expo-localization": "~8.2.1",
    "expo-notifications": "~0.3.3",
    "expo-permissions": "^9.0.1",
    "expo-splash-screen": "^0.5.0",
    "expo-status-bar": "^1.0.0",
    "expo": "^38.0.9",
    "expo-asset": "^8.1.7",
    "firebase": "7.9.0",
    "formik": "^2.1.4",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-elements": "^2.0.3",
    "react-native-expo-cached-image": "^1.1.1",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-image-slider-box": "^1.0.12",
    "react-native-image-viewing": "^0.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-modal": "^11.5.6",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "3.0.2",
    "react-native-screens": "^2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^9.4.0",
    "react-navigation": "^4.4.0",
    "react-navigation-header-buttons": "^4.0.2",
    "react-navigation-stack": "^2.8.2",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-jest": "~25.2.6",
    "babel-preset-expo": "~8.1.0",
    "jest": "~25.2.6",
    "jest-transform-stub": "^2.0.0",
    "react-test-renderer": "~16.11.0"
  }

**Comment by brentvatne** [comment]
does `node_modules/expo-asset/tools/hashAssetFiles.js` exist?

**Comment by Abdullah-Shamhan** [comment]
> does `node_modules/expo-asset/tools/hashAssetFiles.js` exist?
> 
> i initialized a new bare project and ran this and it worked as expected:
> 
> ```
> ╰─$ npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./index.android.bundle --assets-dest android/app/src/main/res                                                            1 ↵
>                  Welcome to React Native!
>                 Learn once, write anywhere
> 
> 
> info Writing bundle output to:, ./index.android.bundle
> info Done writing bundle output
> ```

It dose 
and this is it's content

```
'use strict';

const md5File = require('md5-file/promise');

module.exports = function hashAssetFiles(asset) {
  return Promise.all(asset.files.map(md5File)).then(hashes => {
    asset.fileHashes = hashes;
    return asset;
  });
};
```

**Comment by brentvatne** [comment]
can you share your project?

**Comment by barthap** [comment]
I just wanted to let you know, that simillar issue happened a few days ago - #9485 😉

**Comment by Abdullah-Shamhan** [comment]
The 

> does `node_modules/expo-asset/tools/hashAssetFiles.js` exist?
> 
> i initialized a new bare project and ran this and it worked as expected:
> 
> ```
> ╰─$ npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./index.android.bundle --assets-dest android/app/src/main/res                                                            1 ↵
>                  Welcome to React Native!
>                 Learn once, write anywhere
> 
> 
> info Writing bundle output to:, ./index.android.bundle
> info Done writing bundle output
> ```

Ok this helped, i was supposed to add npx  and it worked  ..
