### ISSUE TITLE
Expo latest client app crashing on Android

### ISSUE THREAD

**Issue by Abhay07** [expo/expo#9559]
### Summary of Issue 
Expo latest client app crashing on Android

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Android, Device Redmi 4A, Latest version from playstore.

### Steps to Reproduce
Open Expo App (Latest from playstore)

### Expected Behavior vs Actual Behavior
App crashing immediately on opening.

**Comment by cruzach** [comment]
What Android version is your device on? Also, if you can run `adb logcat` and then reproduce the crash and share those logs with us (there should be a `FATAL EXCEPTION` somewhere) that would be very helpful

**Comment by Abhay07** [comment]
Android version - 7.1.2

adb logcat output in attachment
[log.txt](https://github.com/expo/expo/files/5035634/log.txt)

**Comment by cruzach** [comment]
This is happening without running an Expo project, and opening it in the app? the logs seem to point to `expo-task-manager`

**Comment by Abhay07** [comment]
Yes, without running, an Expo project. As soon as i open the Exp client app itself. It crashes.
