### ISSUE TITLE
Push notifications do not appear when exiting the app with the back button on Android.

### ISSUE THREAD

**Issue by Woong25** [expo/expo#9560]
### Summary of Issue 
On the Android device, if you close the app by pressing the 'back button' and swipe it off completely by pressing the "Recently Running App Button" to shut it down, you will not receive a push notification,
but without pressing the 'back button' to exit, just press the 'recent app button' Swipe to exit to get a push notification.
(Galaxy s9 plus)

![img](https://user-images.githubusercontent.com/44948010/89385553-bef4a300-d73a-11ea-8780-20661ce3b06c.jpg)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
`  Expo CLI 3.23.2 environment info:

    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\ST\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^38.0.8 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.4.0 => 4.4.0`
+ "expo-notifications": "~0.3.3"
### Reproducible Demo
It is difficult to create a demo.
You issue tokens on your Android device.
Test it at https://expo.io/notifications
 
### Steps to Reproduce

1. Send a notification after exiting the app with the cancel button and swipe
2. Send a notification after quitting the app by swiping

### Expected Behavior vs Actual Behavior

I built the app and uploaded it to the Play Store, and in the foreground, I noticed that the notification was coming.

Can the above be confirmed?
Please check this. Thank you.

**Comment by lukmccall** [comment]
I think it was fixed by https://github.com/expo/expo/issues/9037.

**Comment by lukmccall** [comment]
or it wasn't :/ 
I will check it ;)

**Comment by lukmccall** [comment]
@Woong25, Hi, would you check in settings if your app was forced to stop? When you swipe your app, go to the settings -> apps -> your app and check if you can press the `force stop` button.

**Comment by Woong25** [comment]
@lukmccall Thank you for your reply.
This is the picture captured by moving to the app setting screen.

![Screenshot_20200908-100434_Settings](https://user-images.githubusercontent.com/44948010/92423149-f8e21a80-f1ba-11ea-8313-8014bb921569.jpg)

But now I don't get a notification no matter how I close the app.

**Comment by okeybond** [comment]
Notifications don't seem to come through on Android

**Comment by brunoaduarte** [comment]
@Woong25 do you know if this problem occurs with the 'legacy-notifications' module?

**Comment by lukmccall** [comment]
Could you try to reproduce this bug in the newest SDK (39)? I believe it was fixed.

**Comment by Woong25** [comment]
I ran into a problem before checking this..
Please check here!... #10282 

Thank you.

**Comment by Woong25** [comment]
@lukmccall 
I fixed the problem and updated it to sdk39 and it works!
Thank you.
