### ISSUE TITLE
Expo Client App ID instead Facebook App ID in Facebook login `logInWithReadPermissionsAsync`

### ISSUE THREAD

**Issue by Ivanov89** [expo/expo#9561]
When try to make facebook login with `expo-facebook` , Facebook sends wrong token...i.e. for the `Expo Client App Id` instead of our "Facebook App Id", which is defined in the project...so that `Expo Client App Id` is sent to the server, and the server checks that it is for different app and our login is broken now...

The Facebook app id is defined in `app.json` file and in the `initializeAsync` but with no success...

<img width="1001" alt="Screenshot 2020-08-05 at 11 39 39" src="https://user-images.githubusercontent.com/4004486/89391098-627c8e00-d710-11ea-8589-fbf395a3be56.png">

`
Expo CLI 3.23.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-navigation: ^3.11.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.23.2
`

Any advices will be appreciated because we are blocked now!
Thanks!

**Comment by cruzach** [comment]
hi @Ivanov89 , we document why we use the Expo client facebook app ID on iOS here- https://docs.expo.io/versions/latest/sdk/facebook/#registering-your-app-with-facebook

> No configuration is needed to use the Facebook SDK in the App Store Expo client, because all of your Facebook API calls will be made with Expo's Facebook App ID. The slight downside to this is that you can't customize which permissions your app requests from Facebook (like user_photos or user_friends), or integrate Facebook login with other services like Firebase auth. If you need that functionality, you have two options:
Build a standalone app
Build a custom Expo Client app

If you'd like to use your own, you'll need to build a custom Expo client or a standalone app (guides on how to do that are documented in that link I shared)

**Comment by Ivanov89** [comment]
Hi @cruzach,
thanks a lot for your feedback !
