### ISSUE TITLE
Packages Conflict - expo image picker with react-native-reanimated

### ISSUE THREAD

**Issue by MariaMPSerra** [expo/expo#9568]
Hi,
when I install expo-image-picker I have this error: "Unsupported node type: param" and when I re-install react-native-reanimated@1.4.0 because supposedly solves the error I have another error: Unable to resolve "expo-image-picker" and I dont know how to fix it because I really need the image picker in my app. Can someone help me? Thanks

**Comment by brentvatne** [comment]
```
expo install react-native-reanimated exop-image-picker
```

this will work :)
