### ISSUE TITLE
Heads-up notifications on Android

### ISSUE THREAD

**Issue by FelipeBohnertPaetzold** [expo/expo#957]
I would like the push to appear on the screen at the moment it arrives on Android devices.
When the push is received, the device only alerts with sound and shows the icon in statusbar.

![exp](https://user-images.githubusercontent.com/15256199/32727672-8afdc44c-c864-11e7-8fd0-5cfc50d17ed5.gif)

Is there any way to present it this way?

![whatsapp](https://user-images.githubusercontent.com/15256199/32727675-8d55b150-c864-11e7-8293-e59366762728.gif)

**Comment by jimmylee** [comment]
I'm not sure at the moment, I'm looping in @jesseruder who has far more expertise in this domain to take a quick look at this.

**Comment by Facu33** [comment]
Any idea about this? Please, I'm going crazy trying to do it

**Comment by lipusal** [comment]
Hi, is there any update on this? I notice that on the [as-of-now-latest V30 docs](https://docs.expo.io/versions/v30.0.0/sdk/notifications#priority-optional-min--low--default) there is support for this when creating a notifications channel for Android. However, as also stated [slightly above that](https://docs.expo.io/versions/v30.0.0/sdk/notifications#exponotificationscreatechannelandroidasyncid-channel), this feature is Android 8.0+ only. Is there any way to specify a priority without creating a channel?

**Comment by AdamJNavarro** [comment]
Hey @lipusal,

Unfortunately the only way to implement this with the Expo SDK is via the notification channels on Android 8+.
