### ISSUE TITLE
Calendar.getEventsAsync returns events for calendars that I didn't fetch for

### ISSUE THREAD

**Issue by special-character** [expo/expo#9571]
### Summary
The [calendar.getEventsAsync](https://docs.expo.io/versions/latest/sdk/calendar/#calendargeteventsasynccalendarids-startdate-enddate) function returns events for calendars that I didn't fetch for.

EX: I call `getEventsAsync(["calendarId1"])` and will get events back like

```
{
  "id": "eventId",
  "calendarId": "calendarId2",
  "title": "some event title"
}
```

### Environment
  Expo CLI 3.22.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild

 
### Steps to Reproduce
- Have a device with multiple calendars
- Add an event on a calendar
- Only request events for one calendar (that didn't have the previous event)

### Expected Behavior vs Actual Behavior
I would expect the returned events to only be for the calendar ids I requested them for.

**Comment by AdamJNavarro** [comment]
Hey @special-character,

Can you provide us with a reproducible example of this behavior as well as let us know what platform(s) it is occurring on?

Cheers,
Adam

**Comment by special-character** [comment]
@AdamJNavarro this was on iOS, sorry for missing that in the original! I can work on making a repro but not sure how soon I will have it done.

**Comment by special-character** [comment]
@AdamJNavarro Here is a reproducible example: https://snack.expo.io/@tiltshift/laughing-croissant

I connected to my device which has events on multiple calendars however I only fetched for one calendar (ending in `5F6`). The events I get back from the call to `Calendar.getEventsAsync` has events for other calendars on my device that I didn't fetch for.

![IMG_0420](https://user-images.githubusercontent.com/5407471/90054469-c19e4d80-dc90-11ea-9c53-4bd816e1210a.PNG)

**Comment by barthap** [comment]
Hi @special-character 
I have run your demo on my iPhone and it behaves as you described, however you are using `getEventsAsync()` wrong. As first parameter, you should pass array of calendar **ID**s, not the whole objects. See [docs](https://docs.expo.io/versions/v38.0.0/sdk/calendar/#calendargeteventsasynccalendarids-startdate-enddate). Doing
```diff
       const events = await Calendar.getEventsAsync(
---      fetchedCalendars,
+++      fetchedCalendars.map(calendar => calendar.id),
         new Date(new Date().setDate(new Date().getDate()-14)),
         new Date(new Date().setDate(new Date().getDate()+14))
       );
```
fixed the issue.

**Comment by special-character** [comment]
@barthap That was my mistake in the example but I know this is a real issue. In my own app I didn't make that mistake. I can fix the example today and test again.

**Comment by special-character** [comment]
@barthap Thanks for looking at this. I updated the example and seems like I can't repro anymore, that was my mistake. Thanks for confirming. I don't quite understand why it is behaving this way in my app (confirmed I use string ids) but will re-open if I find a way to make a reproducible example.
