### ISSUE TITLE
[expo-store-review] Expo.StoreReview.requestReview(): Couldn't link to store...

### ISSUE THREAD

**Issue by brunoaduarte** [expo/expo#9579]
### Summary of Issue 

StoreReview.requestReview() doesn't work for BARE project.

Expo.StoreReview.requestReview(): Couldn't link to store, please make sure the `android.playStoreUrl` & `ios.appStoreUrl` fields are filled out in your `app.json`

I've set the proper fields in app.json

```
    "android": {
      "useNextNotificationsApi": true,
      "playStoreUrl": "https://play.google.com/store/apps/details?id=my.app"
    },
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.23.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE     
      Yarn: 1.22.4 - C:\Users\Myself\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD       
    npmPackages:
      expo: ^38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

### Steps to Reproduce

Just create a bare android expo project, install `expo-store-review` and try to call `StoreReview.requestReview();`

### Expected Behavior vs Actual Behavior

Expo.StoreReview.requestReview(): Couldn't link to store, please make sure the `android.playStoreUrl` & `ios.appStoreUrl` fields are filled out in your `app.json`

**Comment by barthap** [comment]
I can confirm that - `expo-constants` is missing some exports in bare workflow. I'll take a deep look into it.

**Comment by barthap** [comment]
The cause is here:
https://github.com/expo/expo/blob/d19a1f0af673624413858da639e29ac09466c8b0/packages/expo-store-review/src/StoreReview.ts#L58-L68

Store URL is gathered from `Constants.manifest` (`app.json`), which is unavailable from bare workflow.

**Comment by elhamposhtiban** [comment]
Hi everyone I'm new on react-native so I suppose to do a store review for our application at my job and on Ios, I got the modal on the iPhone emulator successfully but the submit is not working can you help me, please?  is this happen because I am not passing URL?

**Comment by elhamposhtiban** [comment]
I find my answer you can not submit your review on dev mode, xcode emulator, and test flight :)

**Comment by vanacoree** [comment]
> I find my answer you can not submit your review on dev mode, xcode emulator, and test flight :)

But did it end up working without passing an URL? Is a user able to send reviews in the production app?

**Comment by willryanuk** [comment]
@elhamposhtiban understood it didn't work in dev mode... but it worked on the live store app right?

**Comment by elhamposhtiban** [comment]
@willryanuk  @vanacoree  as far as I remember yes! it worked on the production and in apple store
