### ISSUE TITLE
Type error problem after updating expo version from 36 to 38

### ISSUE THREAD

**Issue by HoWonJang** [expo/expo#9585]
I updated the expo version to 38. When I was 36, the app worked normally, but an error occurs in the image. I tried the npm intall and other methods, but they were not solved. How can I solve this problem? thank you
![update error](https://user-images.githubusercontent.com/49952957/89507361-5cb5a400-d807-11ea-9758-a6332e34f1d8.jpg)
[my app file.zip](https://github.com/expo/expo/files/5033427/my.app.file.zip)

**Comment by HoWonJang** [comment]
![info](https://user-images.githubusercontent.com/49952957/89509453-4ceb8f00-d80a-11ea-95fa-4ab4554049b5.PNG)

**Comment by cruzach** [comment]
Did you upgrade with `expo upgrade`, and check through the changelog for any breaking changes? 

You may want to try clearing your node modules folder and reinstalling. Maybe this is related to `react-native-appearance`? But without more information this is pretty difficult to help you troubleshoot. If you can fill out the full bug report (most notably sharing your code or preferably a reproducible demo), I can reopen this issue, but as it stands this doesn't look like it's a bug in the Expo SDK
