### ISSUE TITLE
Detached Android: `Expo.Util.reload()` does nothing

### ISSUE THREAD

**Issue by DomKM** [expo/expo#959]
No error. Nothing.

`Expo.Util.reload()` does work correctly in detached iOS.

**Comment by fxfactorial** [comment]
Can you check device logs to see if something useful is printed when you do this? (maybe a warning/error)

**Comment by jesseruder** [comment]
This is definitely broken in detach right now. We're doing a refactor for Android detach that will be available in SDK 24 and will fix this.
