### ISSUE TITLE
Error: Unable to resolve module `./node_modules\expo\AppEntry (PNPM)

### ISSUE THREAD

**Issue by whitecolor** [expo/expo#9591]
### Please note that Expo CLI issues opened in the core Expo repository will be closed.

I'm trying to use PNPM as a package manager, it actually creates symlinks for the needed package. Have created blank project using `expo init`, removed node_modules and installed using with PNPM.

When I start and try to open the app in the emulator I get:

```
Error: Unable to resolve module `./node_modules\expo\AppEntry` from ``:

None of these files exist:
  * node_modules\expo\AppEntry(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.wasm|.native.wasm|.wasm|.android.vue|.native.vue|.vue)
  * node_modules\expo\AppEntry\index(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.wasm|.native.wasm|.wasm|.android.vue|.native.vue|.vue)
    at ModuleResolver.resolveDependency (D:\Code\chartify\node_modules\.pnpm\metro@0.58.0\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (D:\Code\chartify\node_modules\.pnpm\metro@0.58.0\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\Code\chartify\node_modules\.pnpm\metro@0.58.0\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at D:\Code\chartify\node_modules\.pnpm\metro@0.58.0\node_modules\metro\src\lib\transformHelpers.js:267:42
    at Server.<anonymous> (D:\Code\chartify\node_modules\.pnpm\metro@0.58.0\node_modules\metro\src\Server.js:841:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\Code\chartify\node_modules\.pnpm\metro@0.58.0\node_modules\metro\src\Server.js:99:24)
    at _next (D:\Code\chartify\node_modules\.pnpm\metro@0.58.0\node_modules\metro\src\Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

There are issues like https://github.com/expo/expo/issues/5069#issuecomment-539761295 but it is another issue `./node_modules\expo\AppEntry.js` is in place, but it is located in the symlinked directory.

So I don't get what files expo is trying to require and where they are supposed to be located?

**Comment by MapleAzure** [comment]
same problem

**Comment by whitecolor** [comment]
@byCedric any comment on this?

**Comment by brentvatne** [comment]
metro does not support symlinks

**Comment by brentvatne** [comment]
also see: https://github.com/pnpm/pnpm/issues/2365

**Comment by mikib0** [comment]
PNPM have stated it on their documentation ["A React Native project will most probably only work if you use a hoisted node_modules."](https://pnpm.io/npmrc#node-linker)

**Comment by Gbr22** [comment]
I would like to add that it is very counterintuitive to recommend the use of pnpm when creating a project, if with the default pnpm configuration the project will not build
```
$ npx create-expo-app name
npx: installed 1 in 4.457s
✔ Downloaded and extracted project files.
✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following pnpm commands.

- cd name
- pnpm run android
- pnpm run ios # you need to use macOS to build the iOS project - use the Expo app if you need to do iOS development without a Mac
- pnpm run web
```

**Comment by Harukisatoh** [comment]
Same problem here. I would like to use Pnpm, but unfortunately, I'll have to switch to yarn because of this issue.

**Comment by tilman** [comment]
Problem is that pnpm uses symlinks which will not work with this import statement `import App from '../../App';` of `node_modules/expo/AppEntry.js'. You can change pnpm to use hardlinks to support the uncommon import.

Just create a .npmrc file next to your package.json and copy following content:
```
shamefully-hoist=true
node-linker=hoisted
```

Next delete the whole `node_modules` folder and reinstall everything. Hope this helps :)

**Comment by sigmaSd** [comment]
>Just create a .npmrc file next to your package.json and copy following content:
shamefully-hoist=true
node-linker=hoisted

I think this should be documented here https://docs.expo.dev/more/expo-cli/#install-package-managers pnpm doesn't seem to work without it
