### ISSUE TITLE
[expo-av] videoplayer isLooping not working on iOS stops after 3 plays

### ISSUE THREAD

**Issue by sanborN93** [expo/expo#9592]
### Summary of Issue 
Hey, i am using expo video player on a bare react native app.

I got a newsfeed build with react native snap carousel, inside there are my activities (media with text).

The expo video component has isLooping but it does not work as exspected on iOS. While Android works fine!

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.18.1 - /usr/local/opt/node@10/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.8 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
      react-navigation: ^4.4.0 => 4.4.0
    npmGlobalPackages:
      expo-cli: 3.21.5

iOS 13.6

### Reproducible Demo

```
const uri = some Video url;
<Video
                    ref={ref => (this.video = ref)}
                    source={{
                        uri: uri,
                    }}
                    rate={1.0}
                    volume={1.0}
                    isMuted={false}
                    resizeMode="cover"
                    onPlaybackStatusUpdate={this.onProgress}
                    onError={() => console.log('error')}
                    isLooping
                    shouldPlay
                    useNativeControls={false}
                    style={{
                        flex: 1
                    }}
                />
 ```

### Steps to Reproduce

Build a new Component with the expo video component in it.
Set isLooping.

Wait for 3 Playbacks.

Video status -> isLoaded: false -> Video stops playing

### Expected Behavior vs Actual Behavior

Video should loop infinitely.

**Comment by IjzerenHein** [comment]
Hi! Which version of expo-av are you using?

**Comment by sanborN93** [comment]
I just updated to the newest version. Problem still occurs.

**Comment by IjzerenHein** [comment]
I'm just trying to create a full picture of the problem. Could you check your package.json/node-modules and let me know which version of expo-av is installed?

**Comment by IjzerenHein** [comment]
Hi, I've tested with the latest Expo client on SDK 38 (which contains expo-av@8.2.1) and using expo-av@8.4.1, but was unable to reproduce this problem.

Please provide a working reproduction, either in the form of a snack or a project in a github repo.

**Comment by sanborN93** [comment]
In a brand new React Native project it seems to work. Unfortunately, my actual project is so big that it will be difficult to reproduce the whole thing.

I've switched to react-native-video for the time being, as it works fine with it.

I will try to get to the bottom of this and get back to you.

**Comment by guillaume-g** [comment]
Hi @sanborN93, I have the same problem and unfortunately, can't find a solution 👎 .
I will have to use react-native-video too....

**Comment by IjzerenHein** [comment]
@guillaume-g If you could provide us with a Snack or example app that reproduces this problem, then we can have a look 👍

**Comment by M46N3** [comment]
I have the same problem. Tested with Expo SDK 38 and both expo-av@8.2.1 and expo-av@8.4.1 has the same problem. However it seems to work fine if the video source is a mp4 file. The problem only occurs for me when using HLS format (.m3u8).

**Comment by IjzerenHein** [comment]
Hi! I've confirmed that this problem happens when using `.m3u8` files. When the playback ends, it should rewind the AVPlayerItem and re-add it to the queue. However, for `.m3u8` files, the call to `seekToTime` never call its completion callback after the AVPlayerItem has reached the end.

https://github.com/expo/expo/blob/master/packages/expo-av/ios/EXAV/EXAVPlayerData.m#L764-L771

This appears to be a bug in iOS rather than expo-av. I'll have a closer look in order to find a workaround for this.

**Comment by remirez** [comment]
Hi @IjzerenHein I am still having this issue with expo-av@8.6.0 and expo SDK 39.

**Comment by IjzerenHein** [comment]
@remirez The looping-fix for this has been merged but not yet released. It will be included in the Expo client for SDK 40. If you are using the bare workflow I can release an update for you.

**Comment by assimovt** [comment]
I am using SDK 40 and can't loop  .m4v files. mp4 files work fine though.

Another question: When looping is false, isn't the play button supposed to replay? Cause I can't get it working either.

**Comment by manjuy124** [comment]
@assimovt I have the same. Did you get any solution?

**Comment by samiklah** [comment]
you can replay using videoRef every time status.didJustFinish return true

`
const video= useRef();
const [status, setStatus] = useState();

  useEffect(() => {
    (async () => {

     if (status.didJustFinish) {
      await video.replayAsync(); 
     }

    })();
  }, [status]);

return (
<Video 
        ref={ref => (this.video = ref)}
        source={{uri: }}                   
        style={{height:screenHeight}}
        resizeMode="contain"
        onPlaybackStatusUpdate={status => setStatus(() => status)}
        shouldPlay={screenIsFocused}
        isLooping
      />
);
`

**Comment by junedomingo** [comment]
> 

It worked! thanks
