### ISSUE TITLE
Background location task example not working

### ISSUE THREAD

**Issue by AidanRRR** [expo/expo#9595]
## 🐛 Bug Report

The task manager background example does not work.

https://docs.expo.io/versions/latest/sdk/task-manager/

- The task is defined out of the app lifecycle events (App.tsx)
- The task is however registered but is not executed

Does this work for someone?

expo: 38.0.8
expo-task-manager: 8.3.0
expo-location: 8.2.1

*EDIT: it does work on my friends phone with a tunnel.

**Comment by AdamJNavarro** [comment]
Hey @AidanRRR,

If you can provide us with a reproducible example and more information, we can continue the conversation and try to debug what's going on. Simply saying something doesn't work does not make for a good github issue. Please follow the issue template if you choose to revisit this.

Cheers,
Adam

**Comment by AidanRRR** [comment]
Hello @AdamJNavarro ,

I did not add any code because I followed the example code to the letter.

`import React from 'react';
import { Text, TouchableOpacity } from 'react-native';
import * as TaskManager from 'expo-task-manager';
import * as Location from 'expo-location';

const LOCATION_TASK_NAME = 'background-location-task';

export default class Component extends React.Component {
  onPress = async () => {
    const { status } = await Location.requestPermissionsAsync();
    if (status === 'granted') {
      await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
        accuracy: Location.Accuracy.Balanced,
      });
    }
  };

  render() {
    return (
      <TouchableOpacity onPress={this.onPress}>
        <Text>Enable background location</Text>
      </TouchableOpacity>
    );
  }
}

TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
  if (error) {
    // Error occurred - check `error.message` for more details.
    return;
  }
  if (data) {
    const { locations } = data;
    // do something with the locations captured in the background
  }
});`
