### ISSUE TITLE
Notifications on Android - focus on the app

### ISSUE THREAD

**Issue by xcarpentier** [expo/expo#96]
On Android, if I'm in the application and send notification from server, I received in parallel the notification in the app (ok with that) and the notification panel outside of the app (attended to not receive it on this panel when i'm focused on the app). Is there something I can do to change it?

**Comment by jesseruder** [comment]
Hey! I answered it in your forum question here: https://forums.expo.io/t/notifications-on-android-focus-on-the-app/241
