### ISSUE TITLE
Development mode when toggled off still runs on development mode.

### ISSUE THREAD

**Issue by visylvius** [expo/expo#960]
So the flow goes as follows:

- Turn off development mode
- Refresh Expo XDE
- create a new instance of the app you are working on
- command D or command m 
- still pulls up the developer menu even if Development mode has been checked off.

This issue has persisted across 4 of my co-workers computers as well.

**Comment by jimmylee** [comment]
@visylvius this may be a redundant question, but have you tried closing and reopening the app?

**Comment by visylvius** [comment]
@jimmylee Hey! Thanks for getting back to me so quickly. And that is totally a fair question to ask.

Yes, not only did I close it, but I also uninstalled the app and the same behavior persisted. I didn't try to recursively remove it however. 

This behavior was also reproduced on 2 of my teammates computers as well. Same flow.
Toggled Development Mode off/Refreshed XDE and they could also pull up the developer menu even though it was toggled off.

**Comment by terribleben** [comment]
The developer menu will still appear in Expo Client when dev mode is off. There was an [issue on iOS](https://github.com/expo/expo/issues/889) where some items still appeared enabled on that menu even with dev mode turned off. We recently landed a fix for that issue which will ship in the next Expo Client release. In the revised version, the menu still appears, but those unavailable items are greyed out.

**Comment by visylvius** [comment]
Ah that makes sense. Did that change from recent versions? I remember not that long ago that if the development mode was turned off I couldn't access the developer menu at all with my Android Emulator.

Thank you guys again for responding so quickly.

**Comment by jesseruder** [comment]
@visylvius that's still true on Android, ben is just talking about the behavior on iOS

**Comment by visylvius** [comment]
Ah for certain. Thank you guys for being so awesome!
