### ISSUE TITLE
Impossible to remove expo-splash-screen after expo eject

### ISSUE THREAD

**Issue by rdhox** [expo/expo#9604]
I start an app with expo using expo-splash-screen. After ejected, being not happy with expo-splash-screen, I decided to switch with react-native-splash-screen. After hours trying to find ways to remove the pod dependencies and the lines of code of expo-splash-screen, I still have this error:

```
Terminating app due to uncaught exception 'ERR_NO_SPLASH_SCREEN', reason: 'Couln't locate neither 'SplashScreen.storyboard' file nor 'SplashScreen.xib' file. Create one of these in the project to make 'expo-splash-screen' work (https://github.com/expo/expo/tree/master/packages/expo-splash-screen#-configure-ios).'
```

It is possible to have a "how to" for removing this package from a project?

Thanks.

**Comment by zeritte** [comment]
I have the same problem. I have updated my already ejected app to sdk38 from 37. it now fails to open. expo-splash-screen is one of the dependencies of expo and automatically installed. However I am using react-native-splash-screen and do not want to switch to expo's package

**Comment by brentvatne** [comment]
to uninstall it you can remove the package and then follow the reverse installation instructions in reverse. if that doesn't work for you then let me know

**Comment by rdhox** [comment]
For the moment I removed react-native-splah-screen and reinstall expo-splash-screen to make my application works since I had no choice, but expo-splash-screen have some problem.
In my configuration, simple eject from the sdk 38, I'm not able to find a solution to work without expo-splash-screen. Event with the package remove, the pod is always installed by I don't know which dependencies the error above always shows. 
And I tried to reverse install and all other stuff that normally work.

**Comment by zeritte** [comment]
I am not switching to react-native-splash-screen @brentvatne. I am currently using it and do not want to switch to expo's one. as @rdhox states, it is impossible remove it atm

**Comment by rdhox** [comment]
@brentvatne Apparently ejecting or even initiating a new bare project install the "expo-splash-screen" by default. So the problem start maybe here.

**Comment by Jerry-devblog** [comment]
even not using at all on expo init --template bare-minimum ! ?? 
also example to use expo/configure-splash-screen please!

yarn run configure-splash-screen backgroundColor:#000000 ??

SplashScreen.hide() is deprecated in favour of SplashScreen.hideAsync()

**Comment by rdhox** [comment]
Here the informations after an `expo init --template bare-minimum` with the last version of `expo-cli`.

**package.json**:

```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "expo": "~38.0.9",
    "expo-splash-screen": "^0.5.0",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

**Podfile:**

```
platform :ios, '10.0'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!(versions = {})
  versions['Flipper'] ||= '~> 0.33.1'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.1'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.0'

  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'

  # List all transitive dependencies for FlipperKit pods
  # to avoid them being linked in Release builds
  pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
  pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'testExpo' do
  # Pods for testExpo
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!
  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

**AppDelegate.m:**

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <UMCore/UMModuleRegistry.h>
#import <UMReactNativeAdapter/UMNativeModulesProxy.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>
#import <EXSplashScreen/EXSplashScreenService.h>
#import <UMCore/UMModuleRegistryProvider.h>

#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@interface AppDelegate () <RCTBridgeDelegate>

@property (nonatomic, strong) UMModuleRegistryAdapter *moduleRegistryAdapter;
@property (nonatomic, strong) NSDictionary *launchOptions;

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if DEBUG
  InitializeFlipper(application);
#endif
  
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
  self.launchOptions = launchOptions;
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  #ifdef DEBUG
    [self initializeReactNativeApp];
  #else
    EXUpdatesAppController *controller = [EXUpdatesAppController sharedInstance];
    controller.delegate = self;
    [controller startAndShowLaunchScreen:self.window];
  #endif

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
}

- (RCTBridge *)initializeReactNativeApp
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:self.launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"main" initialProperties:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  return bridge;
 }

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  NSArray<id<RCTBridgeModule>> *extraModules = [_moduleRegistryAdapter extraModulesForBridge:bridge];
  // If you'd like to export some custom RCTBridgeModules that are not Expo modules, add them here!
  return extraModules;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 #ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
 #else
  return [[EXUpdatesAppController sharedInstance] launchAssetUrl];
 #endif
}

- (void)appController:(EXUpdatesAppController *)appController didStartWithSuccess:(BOOL)success {
  appController.bridge = [self initializeReactNativeApp];
  EXSplashScreenService *splashScreenService = (EXSplashScreenService *)[UMModuleRegistryProvider getSingletonModuleForClass:[EXSplashScreenService class]];
  [splashScreenService showSplashScreenFor:self.window.rootViewController];
}

@end

```

**Comment by rdhox** [comment]
> update Try do this
> in your node_modules/expo/build/launch/splashScreen.js
> `import { NativeModules } from 'react-native'; import* as SplashScreen from 'expo-splash-screen' export function preventAutoHide() { if (SplashScreen.preventAutoHideAsync) { SplashScreen.preventAutoHideAsync(); } } export function hide() { if (SplashScreen.hideAsync) { SplashScreen.hideAsync(); } }`

I don't see how doing that solve the fact that we can't get rid of expo splash screen in bare workflow?

**Comment by Jerry-devblog** [comment]
@rdhox try build init bare app first, Change as above, then try add <APPLOADING />  should work

when you eject the expo, there should be somethig else had change which is not in my case.

I don't have skillset to debug the java-javascript-c kind of code sorry  :smiley:

**Comment by davx1992** [comment]
Having same issue, problem is that Expo Splash Screen is part of Unimodules, and is automatically installed. Question would be how it is possible to remove that package?

**Comment by davx1992** [comment]
I found solution. As per instructions on installation of Unimodules, there is possibility to exclude some modules. - 

If you need to exclude some of the unimodules that you are not using but they got installed by your other dependencies (like expo), then you can pass in exclude param for this. For example, if you want to exclude expo-face-detector, you may want to use this: use_unimodules!(exclude: ['expo-face-detector'])

So I updated my Pods file with   use_unimodules!(exclude: ['expo-splash-screen'])
And now it works!

**Comment by rdhox** [comment]
@davx1992 Thanks! Soon good, will try as soon as I can :)

**Comment by rdhox** [comment]
> I found solution. As per instructions on installation of Unimodules, there is possibility to exclude some modules. -
> 
> If you need to exclude some of the unimodules that you are not using but they got installed by your other dependencies (like expo), then you can pass in exclude param for this. For example, if you want to exclude expo-face-detector, you may want to use this: use_unimodules!(exclude: ['expo-face-detector'])
> 
> So I updated my Pods file with use_unimodules!(exclude: ['expo-splash-screen'])
> And now it works!

Worked for me too! Here the expo doc where the info is: https://docs.expo.io/bare/installing-unimodules/
Thanks @davx1992, the issue can be close for me :)

**Comment by byCedric** [comment]
Awesome, glad you solved this!

**Comment by tiavina-mika** [comment]
> (exclude: ['expo-splash-screen'])

I have this error:
 #import <EXSplashScreen/EXSplashScreenService.h>
     |         ^ 'EXSplashScreen/EXSplashScreenService.h' file not found

![image](https://user-images.githubusercontent.com/42656064/148026320-65260907-3a70-4f99-8d5e-fa7e6a5f8a08.png)

Have you removed it from the AppDelegate.m?

**Comment by VitaliiTsurkan** [comment]
This bug still appears in bare flow (latest version). Sometimes if you add "SplashScreen.storyboard" it can show the same error but with 2 .storyboard extensions, like this "SplashScreen.storyboard.storyboard" and so on.

**Comment by AdamGerthel** [comment]
Can confirm, I'm getting this error on a brand new RN project (i.e "bare" Expo), where I've installed expo splash screen and used the `yarn expo-splash-screen` to generate the splash screen,

**Comment by theDeji** [comment]
thank you!!! you're a life saverrrrr 👏🏾👏🏾👏🏾👏🏾 !

**Comment by tbergeron** [comment]
@AdamGerthel THANK YOU!

What a stupid error. Why wasn't that fixed?

**Comment by tenusha10** [comment]
> Can confirm, I'm getting this error on a brand new RN project (i.e "bare" Expo), where I've installed expo splash screen and used the `yarn expo-splash-screen` to generate the splash screen.
> 
> > 'ERR_NO_SPLASH_SCREEN', reason: 'Couln't locate neither 'SplashScreen.storyboard.storyboard' file nor 'SplashScreen.storyboard.xib' file. Create one of these in the project to make 'expo-splash-screen' work
> 
> All files exist from what I can tell, but it's odd that the error message is about a file named "SplashScreen.storyboard.storyboard" because that seems to me like an expo error since the file that is generated is called "SplashScreen.storyboard".
> 
> **Update**: Solved by editing the below value ("Launch screen interface...") from `SplashScreen.storyboard` to `SplashScreen`
> 
> <img alt="Screen Shot 2022-12-06 at 10 42 46" width="571" src="https://user-images.githubusercontent.com/1490370/205876699-de35c8e2-02dd-4968-b345-97d178f763d5.png">

Thank you sm !!

**Comment by xwiz** [comment]
It's simply so insane, that expo forces you to use expo splash screen, makes no sense whatsoever..

**Comment by mohitsinghofficial** [comment]
Is ther any way to remove default splash screen in expo react native app? I tried manything, nothing worked till hours..
