### ISSUE TITLE
Release patch notes of minors versions

### ISSUE THREAD

**Issue by NeOMakinG** [expo/expo#9609]
### Please note that discussions opened as issues in the core Expo repository will be closed.

It seems that every "majors" versions got a patchnote on you'r blog, but what about minor releases such as 38.0.9 ? 

Except by going through you'r repo and looking to merged things, it's hard to see if some fixes came with a minor version !

At PrestaShop we use an issue/PR template which is used to build changelogs, it provide us a way to "automate" the changelog even for minor releases, I don't really know if you'r using such a workflow, but it would be so good to have a list of things that has been done inside minor releases :)

Maybe I just didn't find it and then I'm totally wrong, my apologies then !

Keep up the good work, love your project !

**Comment by AdamJNavarro** [comment]
Hey @NeOMakinG,

Thanks for your support and interest in Expo. We hope to get better at detailing changes in minor versions of expo and its packages but for right now you'll have to do some repo exploration.

Cheers,
Adam
