### ISSUE TITLE
Notifications.getExpoPushTokenAsync returns 400 error 

### ISSUE THREAD

**Issue by peti123x** [expo/expo#9617]
## 🐛 Bug Report
Calling Notifications.getExpoPushTokenAsync() is rejected and returns an API error instead of the desired token.
### Summary of Issue 
I am using the snack outlined here https://docs.expo.io/push-notifications/push-notifications-setup/ to ask for permission and retrieve the device's token for push notifications. Asking for permission the first time around worked (and so did returning the token), but since then I have not been able to get the device token again as it returns a 400 error instead as such:

`Unhandled promise rejection: Error: Error encountered while fetching Expo token, expected an OK response, received: 400 (body: "{"errors":[{"code":"API_ERROR","message":"The Expo push notification service is supported only for Expo projects. Ensure you are logged in to your Expo developer account on the computer from which you are loading your project."}]}")`

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.23.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
      Shell: 5.0.16 - /bin/bash
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ~38.0.9 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.23.2

Dependencies:
"dependencies": {
    "@react-native-community/push-notification-ios": "^1.4.0",
    "expo": "~38.0.9",
    "expo-constants": "~9.1.1",
    "expo-notifications": "~0.3.3",
    "expo-permissions": "~9.0.1",
    "expo-splash-screen": "^0.3.1",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-config": "^1.3.3",
    "react-native-expo-viewport-units": "^0.0.8",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-push-notification": "^5.0.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-web": "~0.11.7",
    "react-native-webview": "9.4.0"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0"
  }

Target: iPhone 8s Plus @ iOS 13.3.1

How can I resolve this problem? I want to be able to grab the token from a device which has already allowed push notifications to check against records in our database. Thanks

**Comment by AdamJNavarro** [comment]
Hey @peti123x,

You'll need to log into your expo account in the terminal via `expo login`. If you are logged in and still receiving this error, we can open this issue back up.

Cheers,
Adam

**Comment by navicstein** [comment]
https://github.com/expo/expo/issues/11508

**Comment by lokomass** [comment]
How can we do that on a production app ? We can't login expo anymore ?
