### ISSUE TITLE
Once Barcode is Scanned, Cant Scan again

### ISSUE THREAD

**Issue by BND10706** [expo/expo#9619]
SO I have a scanner to scan a barcode and extract the numbers from it. if you do it the first time it works. after the barcode is submitting and you push the camera button I made to open the modal that scanner is attached to, it will not let you scan it again.

**Comment by byCedric** [comment]
Hi @BND10706! Unfortunately, I wasn't able to reproduce this issue. Could you share a working example? That would help is investigate the issue and help you resolve this.

**Comment by BND10706** [comment]
I have barcode scanner sitting in a Modal, that opens when you push the camera button.

`<Modal transparent={true} visible={showScanner}>
        <View style={styles.cameraView}>
          <BarCodeScanner
            onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
          />
          <TouchableOpacity
            style={styles.cameraTouch}
            onPress={() => setShowScanner(false)}
          >
            <Text style={styles.valid}>Close</Text>
          </TouchableOpacity>
        </View>
      </Modal>`

the action is only this.

` const handleBarCodeScanned = ({data}) => {
    setScanned(true);
    setTag(data);
    setShowScanner(false);
  };`

When i open the scanner, the modal pops up. It scans the barcode, and puts in the correct numbers into the text field. After the app submits the data, it refreshes and clears the text field. if you hit the camera button to open the modal again, the modal comes up, but you cannot scan a barcode at all.

**Comment by BND10706** [comment]
@byCedric any another information that i could provide?

**Comment by brentvatne** [comment]
@BND10706 - yup. create an example on https://snack.expo.io/ that we can run

**Comment by BND10706** [comment]
I took a snippet of my code... the problem is that I had to remove a-lot of proprietary stuff. https://snack.expo.io/@bnd10706/4766f4

**Comment by FaggioniHQ** [comment]
Hello There,

I had the same issue on Android (I didn't run any test on iOS). 

I solved it by Unmounting the screen where the scanner is located once the information is processed.

The Docs refer to this issue.

Note: Only one active BarCodeScanner preview is supported currently. When using navigation, the best practice is to unmount any previously rendered BarCodeScanner component so the following screens can use <BarCodeScanner /> without issues.

We are using react-native-router-flux, so I just used Actions.popTo('screen-key'). It should work in a similar way on React Navigator.

Hope it helps!!!

**Comment by yarapolana** [comment]
@BND10706 Did you manage to solve it? I am having the same issue.
In my case it scans once and navigates to a different page, once completed and returned to the camera screen it stops scanning.

**Comment by BND10706** [comment]
nope, never solved it, but this is the issue that I am having.
once you scan, it wont scan again

**Comment by brentvatne** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

we need an example to be much more minimal than the one provided above. there is too much code for us to read through there, we'd have to delete half of it before we're able to narrow it down to just reproducing this issue :)

**Comment by yarapolana** [comment]
I managed to reproduce one example.

I normally use `<Camera>` in my production app, and here I used both `<Camera>` and `<BarCodeScanner>` to compare.
Hope this helps.

[Repo with Scanner](https://github.com/yarapolana/expo-review-scanner)

**Comment by sk1llsh0t** [comment]
Looks like i'm stuck at Expo 42 until this is fixed.

**Comment by tones31** [comment]
I am also facing the same issue - works once then never again. The weird thing is I have to close not only my app, but Expo Go as well (on a real device). Also on the latest SDK

**Comment by Zirpoo** [comment]
Same problem, I am using it on android and it can't scan twice. I use expo 43 and barcode scanner version 11.1.2 wit hthe same setup as you'all

**Comment by FedeMartinez** [comment]
I'm with the same error... does anybody knows if there is someone working on fix it or do you know an alternative? I'm driving mad about this

**Comment by zero-skill** [comment]
I have the same problem, in a physical android it works only once. If I press `tap to scan again` button it scans again. But if I go back to the previous screen and then go back to the scan screen it doesn't do it anymore. In the Android emulator it crashes immediately.

I am using the sample code found in the expo-barcode-scanner usage [documentation](https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/).


>Note: i'm using react-navigation, expo SDK 43 and expo-barcode-scanner 11.1.2.


Any solution? Some alternative for this? I only need to read a qr code

**Comment by accompso-ltd** [comment]
I also had to revert to 40 however I had a tag 1 issue resolved here -[]( https://forums.expo.dev/t/error-on-launching-android-app-animated-node-with-tag-1-does-not-exist/50053/6)

**Comment by naor10** [comment]
I am also experiencing this issue with Expo 43.
Is there a solution without downgrading Expo?

**Comment by FedeMartinez** [comment]
I really don't know... If you downgrade Expo... can you target the newer
Android SDK? if possible. Can you tell me how? I just need to upload an
update of my app and I'm not being able to do it

**Comment by sk1llsh0t** [comment]
Expo 42 targets android 11. Use expo-Barcode-scanner version 10.2.2. Those are the latest versions that work and should be accepted by the play store

**Comment by naor10** [comment]
I moved from using expo-barcode-scanner to expo-camera, and it works as expected.

**Comment by tones31** [comment]
@naor10 is right. Just dump `expo-barcode-scanner` and use `expo-camera` and it will work fine.

**Comment by moshedolev** [comment]
found this workaround:

edit the file BarCodeScannerViewFinder.kt
located at:
[your project]\node_modules\expo-barcode-scanner\android\src\main\java\expo\modules\barcodescanner
add the following two lines at the declarations part (around line 44):

@Volatile
private var barCodeScannerTaskLock = false

worked fine for me.

note: i dont know java, and even less so kotlin. i reached this solution by comparing the files of the latest working version i had (10.2.2 - java) with the current version (11.1.2 - kotlin).

**Comment by Zirpoo** [comment]
Is it working for someone ? Because I tried the fix proposed by moshedolev and it didn't work for me.
Using a physical Android 11 phone, expo 43.0.0 and expo-barcode-scanner 11.1.2.
I just want confirmation in case my code environment is at fault

**Comment by moshedolev** [comment]
@Zirpoo - i tested it on my physical device - android 8.1.0. attaching the modified file, if it will help you
(unzip it first, of course). maybe you need to clean the build first.
 good luck
[BarCodeScannerViewFinder.zip](https://github.com/expo/expo/files/7613633/BarCodeScannerViewFinder.zip)
.

**Comment by tones31** [comment]
Just use the expo-camera instead. It works.

**Comment by moshedolev** [comment]
@tones31 - correct me if i am wrong, but the expo-camera doesn't have the bounds parameter in the onBarCodeScanned event. i use this parameter to dismiss barcodes that are scanned outside a pre-defined area in the center of the screen. for example, if you are in a supermarket, and there are many products on the shelf. each has a different barcode. you don't want the onBarCodeScanned event to be triggered on some random barcode caught somewhere in the frame. you want to scan only the barcode that the user to placed in a specified are in the frame.

**Comment by tones31** [comment]
Hmm, I didn't think of that. I scan books so this never is an issue for me. Sorry! Maybe you can mask the view somehow?

**Comment by moshedolev** [comment]
@tones31 - that's an interesting idea. i didn't think of it. i am quite newbie in rn (was forced to rewrite my old cordova app). anyway, the solution i suggested works fine for me, and i thought to share it, in case someone else will need it. i assume expo will fix their code in the next version.

**Comment by tones31** [comment]
Might be a long wait, this bug is over 1 year old :(

**Comment by barbhackk** [comment]
@byCedric any suggestions to escalate this please.

**Comment by barbhackk** [comment]
> Might be a long wait, this bug is over 1 year old :(

@byCedric any suggestions to escalate this

**Comment by tones31** [comment]
Lo and behold, `expo-camera` blows up on web. So.. no solution to anything. :(

**Comment by sk1llsh0t** [comment]
i upgraded from sdk 43 to 44.0.1 and barcode scanner 11.2.0. everything appears to be working properly now.

**Comment by a-eid** [comment]
how did you upgrade to `44.0.1` seems that `expo upgrade` only upgrades to `44.0.0`.

**Comment by sk1llsh0t** [comment]
after the expo upgrade, i ran npm install expo@44.0.1

**Comment by chunghn** [comment]
> @tones31 - that's an interesting idea. i didn't think of it. i am quite newbie in rn (was forced to rewrite my old cordova app). anyway, the solution i suggested works fine for me, and i thought to share it, in case someone else will need it. i assume expo will fix their code in the next version.

Hello. Off-topic though. Would you mind sharing more on the bounding features? I think it also works on the expo camera. However, in some devices, I do not receive the return of corner point. Do you have any experience with that?

**Comment by ritishgumber** [comment]
I was able to resolve the issue by using  `useIsFocused` method of react-navigation.

Adding import statement:
`import { useIsFocused } from "@react-navigation/native";`

get the value of isFocused;
`  const isFocused = useIsFocused();`

return conditionally

```
if (!isFocused) {
    return <View></View>;
  } else {
    return (
      <View style={styles.container}>
        <BarCodeScanner
          onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
          style={StyleSheet.absoluteFillObject}
        />
        {scanned && (
          <Button
            title={"Tap to Scan Again"}
            onPress={() => setScanned(false)}
          />
        )}
      </View>
    );
  }
```

**Comment by moshedolev** [comment]
> > @tones31 - that's an interesting idea. i didn't think of it. i am quite newbie in rn (was forced to rewrite my old cordova app). anyway, the solution i suggested works fine for me, and i thought to share it, in case someone else will need it. i assume expo will fix their code in the next version.
> 
> Hello. Off-topic though. Would you mind sharing more on the bounding features? I think it also works on the expo camera. However, in some devices, I do not receive the return of corner point. Do you have any experience with that?

The onBarCodeScanned event in the expo barcode scanner is triggered with these parameters: {type, data, bounds}. i use the parameter bounds.origin.y to check if it is between 0.4 * useWindowDimensions().height and 0.6 * useWindowDimensions().height. if it is not, i just ignore it. as far as i know, you cant do it on the expo camera, because it doesnt have the bounds parameter.

**Comment by AlexadnerLobanov** [comment]
Hello Everybody. I found a solution to this problem thanks to [ritishgumber](https://github.com/ritishgumber)'s post. But i modified it like this way:

_**first import this:**_
`import { useIsFocused } from "@react-navigation/native";`
 
**_after that go to your function and create variable:_**

```
export default function Scanner( ) {      
       const isFocused = useIsFocused(); 
... }
```

**_and now  use your variable in your return function:_**

```
  return (
    <View style={styles.container}>
        {isFocused && <BarCodeScanner
          onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
          style={StyleSheet.absoluteFill} />}
    </View>
  );
```

**Comment by elenamg75** [comment]
The solution proposed by @ritishgumber and @AlexadnerLobanov worked for me!!!!
I love you both!!!

**Comment by AmenBreak175** [comment]
Thank you @ritishgumber  and @AlexadnerLobanov!!!

**Comment by Yash-Agrawal-flecksTech** [comment]
Thank you @ritishgumber and @AlexadnerLobanov!!!
works perfectly fine now.. I have been stuck on this for a couple of days and noting seemed to work but you two are life saver!

**Comment by edi** [comment]
I currently have the same issue. Have `expo: ^44.0.1` and `expo-camera: ~12.1.1` installed. 

On android, it scans once, then it cannot scan again unless I unmount / mount the scanning component again.
On iOS, it works just fine.  Same behaviour is present in Expo Go client (latest version) as well as in standalone app.

**Comment by zoolyka** [comment]
Same issue here with expo-camera's `Camera` component using SDK 45 with `expo-camera 12.2.0` and `expo-barcode-scanner 11.3.0`. It scans only 1 code with live preview, if I unmount then remount the Camera component then it scans 1 code again.

**Comment by edi** [comment]
Really not sure why this is closed, @byCedric @brentvatne as this is obviously not fixed?

**Comment by zoolyka** [comment]
I've just tested it with clean installs of SDK `45.0.0`, `44.0.1`, `44.0.0` and `42.0.0`, only SDK 42 works as expected (which is not even supported by the latest Expo Go app).

**Comment by musatotan** [comment]
If you handle scanner page with a navigation, you may push with same route parameter(s). Here is a working sample for my project. (Please consider or pretend you are using your own navigations.)
[barcode-rescan](https://snack.expo.dev/@musatotan/barcode-rescan)

**Comment by zoolyka** [comment]
Looks like it's fixed in SDK46.

**Comment by TobiSc** [comment]
Event though @zoolyka mentioned that this issue has been fixed recently, I figured out a different approach which could be useful, even if this is fixed.
It will also allows to scan multiple codes without interruption.
This is achieved by forcing a rerender of the component every time a result has been processed, by changing the key.

export default function ScanPage() {
    const [key, setKey] = useState(0);

    const onScanned = ({type, data}) => {
        //do whatever you want to do with data
        setKey(key + 1);
    }

    return (
        <View>
            <BarCodeScanner key={key} onBarCodeScanned={onScanned} />
        </View>
    );
  }
```

**Comment by AndonMitev** [comment]
I have following issue on `Android` ( works fine on iOS ) and tried everything mentioned everywhere and didn't manage to solve it.
```
"expo": "~46.0.17",
"expo-barcode-scanner": "11.4.0"
```

[code example](https://snack.expo.dev/@doni94/test-qr-code-scan)

When i scan qr code and tap `Scan Again` whole `QR` component just dissapears

Initial state:

![image](https://user-images.githubusercontent.com/32274987/206854197-a29d1f27-3e09-49cd-b882-9e29d8b5da14.png)

On scan:

![image](https://user-images.githubusercontent.com/32274987/206854204-239e336d-c132-4edf-95d3-b5078d5185f2.png)

After closing the modal:

![image](https://user-images.githubusercontent.com/32274987/206854219-d91a59ac-af86-49f4-99ce-a0227ae78816.png)


After pressing `Scan Again`:

![image](https://user-images.githubusercontent.com/32274987/206854234-ebec4d6f-91df-4255-910d-872d8015445d.png)

**Comment by TobiSc** [comment]
@AndonMitev Unfortunately I am not able to test now, but you could try to add the `key` to the dependency list of the useMemo hook

**Comment by nicredshaw** [comment]
Still an issue with Expo 47 and BarCodeScanner 12.1.0, but the workaround above fixes it for me (and I guess the problem is mentioned in the documentation - would be handy if this fix appeared there though !).

**Comment by Vicente-ferrer** [comment]
i don't know if you are using Stack or tab navigations, but you can use one screen configuration for fix this problem, write  {unmountOnBlur: true} on your screen when you leave for other page

**Comment by FedeMartinez** [comment]
Hey! just updated the app last week (yeah, side projects haha) it got fixed
(at least for android) in expo 48
