### ISSUE TITLE
Silent notifications

### ISSUE THREAD

**Issue by mtnptrsn** [expo/expo#962]
Is it possible to push silent notifications with Expo? (With no badge or sound when you're out of the app) I prefer not using sockets for real-time updates due to performance and server costs. Silent notifications are possible with both iOS and Android natively, so this should be possible, right?

Today the notification structure looks like this:
```json
{
    "to": "ExponentPushToken[vnHQhIPbBLKaDN9yZsRePx]",
    "title": "My title",
    "body": "My body",
    "data": {
        "myData": "this is something very important"
    }
}
```

It would be cool if we could have something like this:
```json
{
    "to": "ExponentPushToken[vnHQhIPbBLKaDN9yZsRePx]",
    "data": {
        "myData": "this is something very important"
    },
    "silent": true
}
```

Thanks in advance.

**Comment by terribleben** [comment]
Hey there, we don't support this right now but we might build it later when we have time. We'd appreciate if you could upvote this [feature request](https://expo.canny.io/feature-requests/p/silent-push-notifications) that we are tracking for it.
