### ISSUE TITLE
Expo managed workflow: debuggin webview (docs?)

### ISSUE THREAD

**Issue by wclr** [expo/expo#9624]
If debugging webview is not possible for managed workflow, then probably have to be mentioned in docs.

https://docs.expo.io/versions/latest/sdk/webview/

**Comment by byCedric** [comment]
Hi @whitecolor, thanks for mentioning it. Right now, you can only do that using the bare workflow. I'll keep this open, maybe we can add a manifest property that enables this but I'm not sure. For now, we should update the docs as you mentioned.

**Comment by whitecolor** [comment]
Yes, it is very inconvenient to debug webview issues without normal tools support.

**Comment by whitecolor** [comment]
On ios webview launched in expo/managed too seems to be unavailable for debugging, though there is no additional actions in RN required to debug ios webview.
