### ISSUE TITLE
Unable to reinstall Expo client onto Android Simulator

### ISSUE THREAD

**Issue by dkulagin** [expo/expo#9627]
I removed Expo app from Android Simulator trying to solve some other problem. Now for some reason, I can't reinstall it on the virtual device.

What did I try?

```
remove ./node_modules

npm i

expo client:install:android
```

Not helping. Expo Developer Tools gives:

```
Couldn't start project on Android:

“Error opening simulator. Check Metro logs for details.”
```

Checked _adb_ as well:

```
> adb --version
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5~18.04
Installed as /usr/lib/android-sdk/platform-tools/adb
```

**Q.** What could be wrong and how to address the problem?

![Screenshot from 2020-08-07 18-36-32](https://user-images.githubusercontent.com/2980869/89665483-72979780-d8e1-11ea-9fd2-290854095fcd.png)

![Screenshot from 2020-08-07 18-36-20](https://user-images.githubusercontent.com/2980869/89665491-75928800-d8e1-11ea-8e3b-88b99e5192ae.png)

**Comment by dkulagin** [comment]
There were 2 problems:

1. `$ANDROID_HOME` pointed to the wrong directory. Please, check it first if having issues with connecting to a simulator.
2. There were two versions of `adb` producing the following error:

`adb server version (41) doesn't match this client (39); killing...`

**Solution.** To find out which `adb` executable is running as server on your machine follow the steps:

`netstat -tlpn | grep -i adb`

It helps you find out what is the `pid` of the adb server. Remember it. Then run:

`ls -la /proc/ADB_PROCESS_ID/` (change ADB_PROCESS_ID to the pid you discovered on the previous step)

It helps you find out which `adb` executable runs as a server on your machine.

If the client adb (find out with `which adb`) and server adb have different versions it could cause a problem too.

**Proposal. ** I wish error messages to be a bit more detailed in cases like the described in here.

**Comment by leonzuendel** [comment]
@dkulagin i'm having the same issue and fixed the `$ANDROID_HOME` to point to the correct location, but it's still not working. i downgraded android studio, tried creating a new expo app and so on, but it's never working with the android emulator. i'm getting the EXACT same error as you without furher detail in the metro logs. how did you solve it yourself? i'm not really understanding your solutions... (also i'm on mac btw.)

**Comment by leonzuendel** [comment]
also when i try to run `expo client:install:android` it's not giving me an error and it seems like it worked, but i'm never getting the expo app on the simulator... seems like it's just sending it into the void 😄

**Comment by tojo007** [comment]
please give me proper guidance on this solution

**Comment by tojo007** [comment]
![image](https://user-images.githubusercontent.com/50801662/139578363-cb31daf0-4e5b-4fd9-9b3f-cca0c909a956.png)

**Comment by faizanali1192** [comment]
I'm having the same issue and I have fixed this issue by enabling the develop mode in my emulator device. 
1 Go to "Settings", then tap "About device" or "About phone".
2 Scroll down, then tap "Build number" seven times. ...
3 Enter your pattern, PIN or password to enable the Developer options menu.
4 The "Developer options" menu will now appear in your Settings menu.

**Comment by Ponevejski** [comment]
In my case the problem was, that i hadn`t been using the latest version of expo
So, **npm install -g expo-cli helped** me.

**Comment by smooth038** [comment]
I had the same problem while running expo in WSL. I got everything working once I installed node.js directly in Windows and ran expo from the powershell.
