### ISSUE TITLE
MapView.fitToCoordinates crashes expo, MapView.fitToSuppliedMarkers does nothing

### ISSUE THREAD

**Issue by iway1** [expo/expo#9629]
### Summary of Issue 
Calling react-native-maps MapView.fitToCoordinates immediately causes expo to close without an error, and fitToSuppliedMarkers doesn't seem to do anything. Haven't tried this in a non-expo react native application but I assume it wouldn't cause the application to close.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.23.3 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.23.3

### Reproducible Demo
# Fit to coordinates crashing expo:

```
import { StatusBar } from 'expo-status-bar';
import React, {useRef} from 'react';
import { StyleSheet, Text, View, Dimensions} from 'react-native';
import MapView, {Marker} from 'react-native-maps';


export default function App() {
  const mapRef = useRef(null);

  return (
    <View style={styles.container}>
      <MapView 
        ref={mapRef}
        style={{
          flex: 1,
          width: Dimensions.get('window').width,
        }}
        onLayout={()=>{
          mapRef.current.fitToCoordinates({latitude: 34.5, longitude: 82.5})
        }}
      >
      </MapView>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

# Fit to supplied markers doing nothing:
```
import { StatusBar } from 'expo-status-bar';
import React, {useRef} from 'react';
import { StyleSheet, Text, View, Dimensions} from 'react-native';
import MapView, {Marker} from 'react-native-maps';


export default function App() {
  const mapRef = useRef(null);

  return (
    <View style={styles.container}>
      <MapView 
        ref={mapRef}
        style={{
          flex: 1,
          width: Dimensions.get('window').width,
        }}
        onLayout={()=>{
          mapRef.current.fitToSuppliedMarkers([{latitude: 34.5, longitude: 82.5}])
        }}
        region={{latitude: 34.5, longitude: 82.5, latitudeDelta: 1.0, longitudeDelta: 1.0}}
      >
        <Marker 
          coordinate={{latitude: 36.5, longitude: 82.5}}
          title={"Marker"}
          description={"A description"}
          
        />
      </MapView>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

 
### Steps to Reproduce
Start new application with expo-cli, run `expo install react-native-maps` in the app directory, and run the above code in App.js.

### Expected Behavior vs Actual Behavior
App shouldn't crash, fitSuppliedMarkers should fit the markers.

**Comment by byCedric** [comment]
Hi @iway1, thanks for the issue report. Unfortunately, you provided the wrong parameters in the crashing example. Instead of passing `({ latitude: xx.x, longitude: xx.x })`, you have to supply an array of arguments. But, apparently `react-native-maps` doesn't catch that and results in a native error being thrown. You can open an issue over there if you think that's an error. If you provide this, the map is bound to that coordinate:

```
// This is the good one
mapRef.current.fitToCoordinates([{latitude: 34.5, longitude: 82.5}])

// This results in a crash
mapRef.current.fitToCoordinates({latitude: 34.5, longitude: 82.5})
```

I think it's also recommended to supply 2 or more coordinates so `react-native-maps` can calculate a zoom as well. Else it tries to zoom in as much as possible.

As for the example where nothing happens, you need to provide an array of marker ids, not coordinates. You can see that in the [typescript types they provide](https://github.com/react-native-community/react-native-maps/blob/master/index.d.ts#L284-L291).

Hope it helps!

**Comment by mtalhagaoglu** [comment]
Hi have same problem and the answer above this not helped me :/ Tried to use try catch but there is no error understandable.
