### ISSUE TITLE
iOS client SDK15 -> SDK21 update, LegacyAsyncStorage cannot find the old data 

### ISSUE THREAD

**Issue by turbozv** [expo/expo#963]
Hi, I followed this instruction to use LegacyAsyncStorage in SDK21, but it doesn't show any user data.
https://blog.expo.io/expo-sdk-v16-0-0-is-now-available-2151d555a580

Here's the migration code runs in SDK21

```
await LegacyAsyncStorage.getAllKeys((err, keys) => {
     LegacyAsyncStorage.multiGet(keys, (err, stores) => {
       stores.map((result, i, store) => {
         // get at each store's key/value so you can work with it
         let key = store[i][0];
         let value = store[i][1];
         console.log("[LIST]" + key + ":" + value });
       });
     });
   });
```

On the iPhone updated from SDK15 to 21, I only see these:

```
[LIST]@exponent/home.migrationDone:YES
[LIST]@turbozv/CBSFApp.migrationDone:YES
```

No user data (e.g. I used to store 'ANSWER' as key in AsyncStorage using SDK15).

Sorry to say this, but users are asking how they can get their data back. Is there anything that we can do?

**Comment by nikki93** [comment]
@turbozv Did you call `migrateItems` with the keys that you want to migrate before this?

**Comment by nikki93** [comment]
Could you check if the values are returned if you list the keys for your app manually? (Rather than `getAllKeys`

**Comment by turbozv** [comment]
Working with @nikki93 on this, I tried Sdk16/Sdk19/Sdk21, the LegacyAsyncStorage works well on Sdk16, but not Sdk19/21, something is broken. I'm trying Sdk17/18 to see where it exactly fails.

BTW: I did the following, so I know the user data is not lost - which is cool!
1) Run Sdk15 app, store data in AsyncStorage.setItem('ANSWER', ...)
2) Update to Sdk19, LegacyAsyncStoreage.getItem('ANSWER') returns null
3) Downgrade to Sdk15, AsyncStorage.getItem('ANSWER') returns the data stored in 1

**Comment by turbozv** [comment]
Sdk16 works, but Sdk17 doesn't. Something is broken in Sdk17 for LegacyAsyncStoreage?

**Comment by turbozv** [comment]
Repro code: https://github.com/turbozv/LegacyAsyncStorage

**Comment by turbozv** [comment]
@nikki93 is this the fix? 
https://github.com/expo/expo/commit/923351abcff82a3b92b1542e1c1bc126792b0232

**Comment by nikki93** [comment]
Yup, that's the one. Closing this now since it will be out in a minor release soon.
