### ISSUE TITLE
[expo-media-library] requestPermissionsAsync() always asks permissions on Android 6

### ISSUE THREAD

**Issue by ahmetbicer** [expo/expo#9637]
### Summary of Issue 
`MediaLibrary.requestPermissionsAsync()`  always asks for permission even it already granted by user in android 6. I tested this behaviour from Android 5 to Android 10. It is only happening in Android 6.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Bare react native project
"expo-av": "^8.4.0",
"expo-media-library": "^8.4.0",
"expo-video-thumbnails": "^4.2.1",
"react-native-unimodules": "^0.10.1",

buildToolsVersion = "29.0.0"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29

Also i am requesting legacyExternalStorage on my AndroidManifest.xml file.
```
<application  
...
android:requestLegacyExternalStorage="true" 
>
...
</application>
```

### Reproducible Demo

Call `MediaLibrary.requestPermissionsAsync()` on android 6. I am asking for permissions in this way. 
```
getAlbums = async () => {
    const res = await MediaLibrary.requestPermissionsAsync()
    if (res.granted) {
      MediaLibrary.getAlbumsAsync()
                     .then((albums) => console.log(albums))
                     .catch((err) => console.warn(err))
    }
  }
```
### Steps to Reproduce
Ask for permission with `MediaLibrary.requestPermissionsAsync() `, grant permission and ask again.

### Expected Behavior vs Actual Behavior
Expected: Don't ask again if user already granted the requested permission.
Actual:  `MediaLibrary.requestPermissionsAsync() ` always asks for permission even if permission granted by user in Android 6.

I got a log dump from `adb logcat` you can see from this [link](https://gist.github.com/ahmetbicer/8eae371ad671b4b89cc5b02137c74013). You can see in line 63. User granted the permission and `expires` set to `never` but in line 126 permission dialog appears again.

Thanks.

**Comment by byCedric** [comment]
Hi @ahmetbicer! Thanks for your issue report. If I'm not mistaken, I think there is also a [`MediaLibrary.getPermissionsAsync()`](https://docs.expo.io/versions/latest/sdk/media-library/#medialibrarygetpermissionsasync). This one should never prompt the user again, it should only fetch the current permission status. Could you try using that as a check before using `.requestPermissionsAsync`? What's the permission status you get from that?

**Comment by ahmetbicer** [comment]
Hi @byCedric, when i check with `MediaLibrary.getPermissionsAsync()` before requesting, permissions works as expected but it is strange that it is only happening in Android 6 maybe there was an issue in my emulator? I don't know. Is it happening on your emulator? If it is not i can close the issue. Thanks!

**Comment by byCedric** [comment]
Great! No, I don't think there is anything wrong with your emulator. Android 6 changed some stuff related to the `CAMERA_ROLL` permission if I'm not mistaken. So I guess it's not receiving the status properly when requesting permissions. And, because this is an older Android, I think it might be really hard to find another workaround for this.

Glad the one I mentioned works for you 😄
