### ISSUE TITLE
Unexpected token, expected ";" - SafeArea.types.ts

### ISSUE THREAD

**Issue by elie222** [expo/expo#9638]
### Summary of Issue 

Unable to run app on iOS simulator on SDK 38. Error:

```
Failed building JavaScript bundle.
SyntaxError: ..../node_modules/react-native-safe-area-context/src/SafeArea.types.ts: Unexpected token, expected ";" (42:19)

  40 |   children?: React.ReactNode;
  41 |   mode?: 'padding' | 'margin';
> 42 |   edges?: readonly Edge[];
     |                    ^
  43 | };
```

It's this issue:
https://github.com/th3rdwave/react-native-safe-area-context/issues/134

But expo is relying on a bad version of this package.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.23.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
    npmGlobalPackages:
      expo-cli: 3.23.3
```

### Expected Behavior vs Actual Behavior

App not crashing.

**Comment by byCedric** [comment]
Hi @elie222, thanks for the issue report. Unfortunately, this is an issue in a 3rd party library and we don't control that. I can see there is a bug report open in [that repository for the same issue](https://github.com/th3rdwave/react-native-safe-area-context/issues/134). Once that's resolved we can upgrade our internal version as well.

For now, I'll keep this open until it's resolved.

**Comment by elie222** [comment]
Yes, I referenced that issue. 

I believe expo is pinned to an older version of that project but it has been fixed in the latest version.

**Comment by byCedric** [comment]
Ah yeah, sorry, I overlooked your mention as well. It might be related to an issue in babel though. Are you able to share a project with this error? With that, I would be able to double-check if this related to babel.

**Comment by elie222** [comment]
Hmm. This is my babel config. Will try removing items from it to see if that has an impact:

```
{
  "presets": ["babel-preset-expo"],
  "plugins": ["@babel/plugin-syntax-export-namespace-from"],
  "env": {
    "development": {
      "plugins": ["@babel/plugin-syntax-export-namespace-from"]
    },
    "production": {
      "plugins": ["transform-remove-console"]
    }
  }
}
```

It's not a TypeScript project but seems to be a TypeScript error.

**Comment by mchepurnoy** [comment]
> Hi @elie222, thanks for the issue report. Unfortunately, this is an issue in a 3rd party library and we don't control that. I can see there is a bug report open in [that repository for the same issue](https://github.com/th3rdwave/react-native-safe-area-context/issues/134). Once that's resolved we can upgrade our internal version as well.
> 
> For now, I'll keep this open until it's resolved.

Hi @byCedric. I have encountered the same error. 
I see that linked issue is resolved. Maybe now it can be upgraded in expo.

**Comment by mchepurnoy** [comment]
In case someone is interested, adding "@babel/core": "^7.8.6" to devDependies helped me with this error.
