### ISSUE TITLE
Android: there was an error in the build 

### ISSUE THREAD

**Issue by jpca999** [expo/expo#964]
I keep getting this error time and again after i updated my app.json file. 
Can somebody suggest me what am i doing wrong ?

It starts the build process and when i try to get the status of the build, i get the error.. 
![image](https://user-images.githubusercontent.com/1026325/32812407-cd632c8c-c972-11e7-8da8-44877420bf40.png)

Heres the  Build ID: 7b2607d2-6706-4a69-a7c1-201f278bcc89

Here's my app.json file.. 

{
  "expo": {
    "name": "App",
    "description": "the App",
    "slug": "theApp",
    "privacy": "unlisted",
    "sdkVersion": "21.0.0",
    "version": "1.0.20",
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "icon": "./assets/icons/app.png",
    "hideExponentText": true,
    "versionCode": "2",
    "loading": {
      "backgroundImage": "./assets/icons/splash_ink.jpg",
      "splash": {
        "backgroundColor": "#222127",
        "image": {
          "ios": {
            "backgroundImage": "./assets/icons/splash_ink.jpg"
          }
        }
      }
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
          "bundleIdentifier": "com.theAppp.exp",
          "supportsTablet": true
    },
    "android": {
       "package": "org.theAppp.exp",
        "versionCode": "4.4.2"
     }
  }
}

**Comment by tcdavis** [comment]
versionCode should be an integer
> "android": {
>  "package": "org.theAppp.exp",
>  "versionCode": "4.4.2"
>}

**Comment by jpca999** [comment]
ok got it. thx -  resolved.
