### ISSUE TITLE
supportsTablet = false

### ISSUE THREAD

**Issue by djaygit** [expo/expo#965]
Still apple keeps rejecting because it doesn't work on iPad

**Comment by tcdavis** [comment]
supportsTablet is a bit of a misnomer; it actually means something like scaleToIpadViewport.
All iOS apps are expected to support iPad, but they only seem to test for this inconsistently.  We're working on better documentation for what supportsTablet actually does.

**Comment by mertnesvat** [comment]
So how can we disable for ipad? I don't think changing documentation will help.
