### ISSUE TITLE
Expo refreshing extremely slowly

### ISSUE THREAD

**Issue by EmirGluhbegovic** [expo/expo#966]
Hey,

I tried to log onto the forums but got a unknown error on sign up, so I am asking here.

When I am developing and everytime I save expo reloads and takes sometimes a few minutes to complete the refresh. I changed the host setting to LAN from tunnel but it still takes long. Every time it start to refresh it sais in the bottom right hand corner: downloading javascript bundle and thats what takes long.

Any recommendations?

**Comment by tcdavis** [comment]
LAN is usually faster than tunnel.  Depending on what you are working on, you might try using snack.expo.io.  It has a different strategy for getting code on your device that can be faster.
