### ISSUE TITLE
Field: android - should NOT have additional property 'notification'

### ISSUE THREAD

**Issue by pyxploiter** [expo/expo#9664]
### Summary of Issue
I am unable to set Notification config under Android inside app.json.
```
"Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v38.0.0/workflow/configuration/
 • Field: android - should NOT have additional property 'notification'."

```

### Environment:
Device: Android
app.json
```
{
  "expo": {
    "name": "Nustalgia",
    "slug": "Nustalgia",
    "version": "1.0.0",
    "userInterfaceStyle": "automatic",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "android": {
      "userInterfaceStyle": "dark",
      "googleServicesFile": "./google-services.json",
      "package": "com.pyxploiter.nustalgia",
      "versionCode": 1,
      "useNextNotificationsApi": true,
      "config": {
        "googleMobileAdsAppId": "ca-app-pub-1296423708724059~8749121009"
      },
      "notification": {
        "icon": "./assets/favicon.png",
        "androidMode": "collapse"
      }
    }
  }
}
```
package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.7.2",
    "@react-navigation/native": "^5.7.1",
    "@react-navigation/stack": "^5.7.1",
    "expo": "~38.0.8",
    "expo-ads-admob": "~8.2.1",
    "expo-camera": "~8.3.1",
    "expo-font": "~8.2.1",
    "expo-image-picker": "~8.3.0",
    "expo-linear-gradient": "~8.2.1",
    "expo-notifications": "~0.3.3",
    "firebase": "7.9.0",
    "native-base": "^2.13.13",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-parsed-text": "0.0.22",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-svg": "12.1.0",
    "react-native-typing-animation": "^0.1.7",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}
```
### Reproducible Demo
Just add "notification" json object under "android" inside app.json

### Expected Behavior vs Actual Behavior

Expecting to add custom notification icon and collapse notification mode. but getting this error.
![image](https://user-images.githubusercontent.com/20368350/89726390-8ce18a80-da33-11ea-989e-d727ebe16da7.png)

**Comment by byCedric** [comment]
Hi @pyxploiter, you should place the `expo.android.notifications` object to  `expo.notifications`. That will work 😄 You can check the full manifest properties, what type of values it should contain and for what purpose they serve, [here](https://docs.expo.io/versions/v38.0.0/config/app/#notification).

Hope it helps!

**Comment by exp8589ert** [comment]
@[byCedric](https://github.com/byCedric) Thanks man. This also solves a similar error that I had. 

{
  "expo": {
    (... some other keys and values)
    "android": {
	"adaptiveIcon": {
	"foregroundImage": "./assets/images/money.png",
	"backgroundColor": "#fff"
    },
   "package": "com.taxiservice",
   "config" : {
   "googleMaps": {
	 "apiKey": "xxxxxxxxxxxx"
   },
   "permissions": ["ACCESS_COARSE_LOCATION","ACCESS_FINE_LOCATION","FOREGROUND_SERVICE"]
    }    
    }
  }
}

I had to put "permissions" property directly under "android" property like so

 "android": {
	"adaptiveIcon": {
	"foregroundImage": "./assets/images/money.png",
	"backgroundColor": "#fff"
},
"package": "com.taxiservice",
"config" : {
"googleMaps": {
"apiKey": "xxxxxxxxxxxx"
},
},
    "permissions": ["ACCESS_COARSE_LOCATION","ACCESS_FINE_LOCATION","FOREGROUND_SERVICE"]
    },

This solved the problem.
