### ISSUE TITLE
Network Request failed (Android Emulator, Iphone device)

### ISSUE THREAD

**Issue by Calls4ever** [expo/expo#9667]
I am doing a fetch request from Rails backend and i got network request failed error, i browsed issues and found they are closed without a comprehensive solution.

This fetch was working before and then stopped working at all, then came back like magic only on IOS emulator
```js
 fetch(`http://localhost:3000/api/v1/users/search_user/${user.username}`)
        // fetch(`http://dummy.restapiexample.com/api/v1/employee/1`)
        .then(res=>res.json())
        .then(res=>{
            if(res.message!==''){
                res.password===user.password?props.setUser(res):window.alert('wrong Credentials!')
            }
        })
        .catch(error=> window.alert(`error is ${error}`))`
```

**Comment by AdamJNavarro** [comment]
Hey @Calls4ever,

This is not an Expo-specific problem. I would recommend checking your localhost is reachable and searching stackoverflow for other reasons as to why you can get a network request failed.

Cheers,
Adam
