### ISSUE TITLE
ImagePicker input not working on Safari

### ISSUE THREAD

**Issue by vjsingh** [expo/expo#9678]
### Summary of Issue 
Calling `ImagePicker.launchImageLibraryAsync` does nothing on Safari.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Targeting: **Safari 13.1.1**
```
  Expo CLI 3.21.9 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.0 - ~/.nvm/v12.13.0/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.11.25 => 0.11.25
      expo: ^37.0.12 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
      react-navigation: ^4.0.10 => 4.0.10
```

### Steps to Reproduce
I'm calling `await ImagePicker.launchImageLibraryAsync({...` and it does nothing visible on Safari, but works fine on Chrome.

Notes:
- `openFileBrowserAsync` is being successfully called, and the input element is being added to the page, but with `display: none`. If I remove this `display: none` on Safari I can successfully add images although the UI looks weird.
- I know I'm running an old version of Expo, but I couldn't find any recent changes that seemed like they would fix this.

@EvanBacon Any idea?

**Comment by EvanBacon** [comment]
Maybe try invoking it after a user interaction like a button press. It works on master https://expo-web.now.sh/apis/imagepicker
