### ISSUE TITLE
iOS crash using WebBrowser.openAuthSessionAsync

### ISSUE THREAD

**Issue by Freeminderus** [expo/expo#968]
If you tap 'Done' in browser it will close it and crash app. This happens only on iOS 10, on 11 everything is fine. 
Also, if second argument (`redirect_uri`) is not specified, after backend redirect it will open blank browser page instead of redirect to app (our backend handles redirect properly). If you close that blank page app crashes as well. However if you pass empty string there - everything is fine.
I'm using SDK 22

**Comment by ide** [comment]
For (1), we definitely want to not crash.

For (2), it sounds like we need more guards against empty/invalid redirect URIs.

**Comment by AdamJNavarro** [comment]
Hey @Freeminderus,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
