### ISSUE TITLE
Audio record for google speech to text not working on android

### ISSUE THREAD

**Issue by chuksgpfr** [expo/expo#9688]
Hi,

I am currently working on the project that requires to send a voice recording and send it to Google Cloud Speech for Speech to Text translations. It works fine with IOS, but I am having some problems with Android. It seems the audio record is not recognized on android. 

```
const recordingOptions = {
        // android not currently in use, but parameters are required
        android: {
            extension: '.m4a',
            outputFormat: Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_MPEG_4,
            audioEncoder: Audio.RECORDING_OPTION_ANDROID_AUDIO_ENCODER_AAC,
            sampleRate: 44100,
            numberOfChannels: 1,
            bitRate: 128000,
          },
          ios: {
            extension: '.wav',
            audioQuality: Audio.RECORDING_OPTION_IOS_AUDIO_QUALITY_HIGH,
            sampleRate: 44100,
            numberOfChannels: 1,
            bitRate: 128000,
            linearPCMBitDepth: 16,
            linearPCMIsBigEndian: false,
            linearPCMIsFloat: false,
          },
    };
```

**Comment by ronaiza-cardoso** [comment]
Can you provide the error message that is showing when you uploaded the audio?

**Comment by chuksgpfr** [comment]
No errors, On android it returns empty Transcription but returns value on ios devices. I'm using NODE JS API with Express to interface with google speech, i can share my api code for you to test on your machine. @ronaiza-cardoso

**Comment by jeffsteinmetz** [comment]
Android 4.1+ supports PCM.  Have you tried .wav instead of .m4a on android?

@expo, Does `Audio.RECORDING_OPTION_ANDROID_OUTPUT_FORMAT_DEFAULT' generate a .wav PCM file on android?

**Comment by thanh90** [comment]
same here, anyone knows how to make 16 bit PCM record with Android ? it seems there is no option for outputFormat and audioEncoder to do that.
