### ISSUE TITLE
Android not fetching updated manifest when developing from localhost

### ISSUE THREAD

**Issue by tyler-king** [expo/expo#969]
When working on multiple projects in dev, running on localhost, the app.json file doesn't change when switching projects. If I have keys being used in Expo.Constants.manifest.extra then the app won't work since it is looking in another project's app.json for those keys. I can't find any way to force it to refresh and have to clear all Expo data to start over.

Seeing this on Android.

**Comment by deadcoder0904** [comment]
Yes I have to Restart Packager & Clear Cache to make it work

**Comment by AdamJNavarro** [comment]
Hey @tyler-king ,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
