### ISSUE TITLE
Can't load Sketch apps on Expo

### ISSUE THREAD

**Issue by cooperka** [expo/expo#97]
Since at least yesterday, any new app created on https://sketch.expo.io/ fails to load on either the Appetize preview or the Expo mobile app. Apps that were created a while ago, however, seem to still work.

Error message: `No experience found at exp://expo.io/@sketch/sdk.undefined-foobarbaz.` (iOS) or `Could not load exp://expo.io/@sketch/sdk.undefined-foobarbaz.` (Android), where `foobarbaz` is the unique URL of your Sketch project.

Tested on Android and iOS using SDK 15.0.0 and 14.0.0.

**Comment by cooperka** [comment]
Wow, right after I created this issue it began working again. Server was very slow at first as if it just deployed some changes. Closing this.

**Comment by jesseruder** [comment]
We actually just fixed this - you're not going crazy :). Thanks for the report.
