### ISSUE TITLE
Permissions.CAMERA should not ask for more than one permission

### ISSUE THREAD

**Issue by jhalborg** [expo/expo#970]
Hello, 

I've experienced an issue with the camera permissions, where to flow of control is erroneous: 

1. Ask the user for permissions using Permissions.CAMERA
2. The user is shown the first permission request alert for storage
3. The user is allowed to select an image
4. When the user returns to the app, he's asked for the camera permissions
5. The library picker is launched again

I've only seen it on iOS so far, can't reproduce on Android. 

I think it'd be great if the CAMERA permissions could be divided into two separate permission categories, CAMERA_STORAGE and CAMERA (or something along those lines), instead of having them bundled together? You could optionally keep a CAMERA_BOTH enum for keeping the current implementation for use cases where it's relevant. This would give developers more granular control over their permission flows. 

This could perhaps also help fix #800 ?

**Comment by ide** [comment]
We added a CAMERA_ROLL permission in SDK 23. That might address this. 

One thing that could have happened in your case is that your code asked for camera permissions and also displayed the image picker, which automatically triggers asking for camera roll permissions (if the user is picking from the camera roll), hence the two dialogs.

**Comment by EvanBacon** [comment]
Closing as v23 provides a way to ask for separate permissions:
* [Camera](https://docs.expo.io/versions/latest/sdk/permissions.html#expopermissionscamera)
* [Camera Roll](https://docs.expo.io/versions/latest/sdk/permissions.html#expopermissionscamera_roll)

**Comment by terribleben** [comment]
Hi, contrary to the comments by @ide and @EvanBacon, iOS didn't include this permission in SDK 23. We'll be adding it in a minor update sometime in the next few days. Sorry for the confusion.

**Comment by jhalborg** [comment]
Thanks @terribleben , sounds great :-) 

What's the best way to stay updated on minor releases? I usually get notified about major versions from blog.expo.io, but don't know where to subscribe/look for minor updates?

**Comment by terribleben** [comment]
Hi, sorry for the slow update here. The best place to check for minor releases is probably the #releases channel on our slack. This change went out mid-last-week.
