### ISSUE TITLE
[expo-linear-gradient] No component is rendered when big borderRadius set

### ISSUE THREAD

**Issue by BZaldua** [expo/expo#9701]
### Summary of Issue 
When a LinearGradient is created with a big borderRadius as style, the element disappears.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.15.4 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.10 => 37.0.10 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.15.4
```

**Targeting**: iOS devices (iPhone/iPad). Android works fine

### Reproducible Demo
Create a LinearGradient with a borderRadius with value 360 for example and you will see that nothing is displayed on iOS but it is on Android.
Actually, the example code used in LinearGradient can be used to reproduce it.
 
### Steps to Reproduce
1. Create a LinearGradient
2. Set style props (the same as the doc example) with a borderRadius: 360

### Expected Behavior vs Actual Behavior
- LinearGradient with round borders is expected vs. No element is seen

**Comment by BZaldua** [comment]
Any update?

**Comment by EvanBacon** [comment]
Related https://github.com/expo/expo/issues/15118
