### ISSUE TITLE
Inability to run Expo Init

### ISSUE THREAD

**Issue by imKevinWillian** [expo/expo#9702]
I'm having this problem when trying to start a project with the name mobile with the command "expo init mobile".
I'm behind a corporate proxy.
I had similar problems when installing the expo but I solved it by setting the proxy with "npm config set proxy http: // username: password @ host: port"

The proxy is ok. I can see the expo version with expo --version.
I just can't start a project.
Can someone help me?

npm -v:
6.14.6
expo --version:
3.24.0

This is the error description: 

 Choose a template: expo-template-blank-typescript
request to https://registry.npmjs.org/expo-template-blank-typescript failed, reason: connect ECONNREFUSED 104.16.22.35:443
FetchError: request to https://registry.npmjs.org/expo-template-blank-typescript failed, reason: connect ECONNREFUSED 104.16.22.35:443
    at ClientRequest.<anonymous> (C:\Users\kwsouza\AppData\Roaming\npm\node_modules\expo-cli\node_modules\minipass-fetch\lib\index.js:97:14)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by byCedric** [comment]
Hi @imKevinWillian! Thanks for writing in. I think your fix for the previous error is causing some trouble in the template-fetching code that we use. What we do is this:

1. Ask the user what template he/she wants to use.
2. Download the published template, as NPM package, from the registry
3. Unpack the downloaded NPM package or template
4. Install the node modules and set some default config

It looks like it's failing in step 2, where we try to contact the NPM registry to download the template package. If you open that link manually in the browser, it should show the information about this package. If not, there is something blocking you from accessing the NPM registry.

I think there are 2 things to try:

1. Remove the previous NPM fix using a proxy with username/password
2. Using Yarn, which as a different registry which you might be able to access

If none of these 2 works, you could help adding support for proxies in this template-fetching code. But that might be hard.

Hope it helps!
