### ISSUE TITLE
Error while updating property '' in shadow node of type: ''

### ISSUE THREAD

**Issue by clems36** [expo/expo#9703]
### Summary of Issue

Some random **Android** devices crash with `Expo encountered a fatal error : Error while updating property 'x' in shadow node of type: 'y'`. 
`x` is always a different random property (i.e. `fontSize`, `width`, `flex`, ...) and `y` a random type (i.e. `RCTView`, `RCTText`, ...).
This started to happen after upgrading to expo 38. 
I've tried launching my app with 3 different devices - Huawei, Samsung, OnePlus - and so far only the OnePlus is experiencing the crash. 
It's also worth mentioning that the crash only happens around 20% of the time.

### Environment

```
Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^4.0.10 => 4.4.0
```

The device on which it fails is a OnePlus6T running on Android 10.

### Reproducible Demo

It's hard for me to provide a reproducible demo, especially because of the randomness of the crash, and also because I cannot transform my project into an MCVE at the moment. 
 
### Expected Behavior vs Actual Behavior

The app should launch normally 100% of the time and not crash on random properties only on _some_ launches.

### What i've tried

After reading a lot about that issue, here are a couple of things i've tried:
- Get rid of every single `&&` operator inside of JSX render code: for instance, I've turned `{isLoading && <ActivityIndicator />}` into `{isLoading ? <ActivityIndicator /> : null}`
- Get rid of every single `&&` in conditional styling: for instance, I've turned `styles={isLoading && loadingStyle}` into `style={isLoading ? loadingStyle : {}}`
- Adding `Thread.sleep(2000)` at the first line of the `onCreate` method in `MainApplication.java` to somehow leave more time to the app to initialise correctly.
- Make `App.tsx` return a simple `<View />` to make sure it's a render issue. This stopped the crashing, as expected.

I would be very grateful to be pointed in any direction in order to resolve this as I'm currently unable to push an urgent update of my project.

**EDIT:** I believe the problem is due to dark mode being on. If it is turned off, the app does not crash anymore. After looking it up I saw that it was [fixed in SDK 36](https://github.com/expo/expo/pull/6825), but the issue is still there for me in SDK 38.

**EDIT 2:** My current workaround is to delay the app rendering with a timeout as suggested [here](https://github.com/expo/expo/issues/6523#issuecomment-573855517) but of course that is not ideal.

**Comment by lukmccall** [comment]
Hi @clems36, I think your issue will be fixed in the SDK 39 by https://github.com/expo/expo/pull/8838. The fixed which was introduced in SDK 36 was a little bit hacky 😅

**Comment by clems36** [comment]
Hi @lukmccall, that's "good" to hear! Is there any way for me to fix it in my current project ?

**Comment by lukmccall** [comment]
Unfortunately, no. However, the SDK39 should be released soon.

**Comment by clems36** [comment]
Ok... guess we can close this

**Comment by bhattchirayu777** [comment]
Hey, @clems36,  I understand that you decided to close this issue because you thought it will be fixed with SDK version 39 but I am getting the same error even though I am running the latest SDK version (39+).

**Comment by clems36** [comment]
Expo 41 is available now, did you try on that version?
I didn't encounter this error again.

**Comment by mikeRChambers610** [comment]
I am getting this error on Android only in SDK 44.
