### ISSUE TITLE
Splash on android SDK23 seems to always use resize=cover

### ISSUE THREAD

**Issue by slorber** [expo/expo#971]
Hi,

I expected to be able to replace this:

```
    "loading": {
      "icon": "./resources/iconLoading.png",
      "backgroundColor": "#ffffff",
      "hideExponentText": true
    },
```

with this:

```
    "splash": {
      "image": "./resources/iconLoading.png",
      "backgroundColor": "#ffffff",
      "resizeMode": "contain"
    },
```

It's almost working, except the image is not contained in screen but stretched and I only see the middle of it, zoomed while I expected my image to fit correctly withing the screen.

For this image, I only see the letters in the middle `hoo` and text is truncated:

![iconloading](https://user-images.githubusercontent.com/749374/32953501-ab7d6b1a-cbb0-11e7-8bed-dd4eba7dcc23.png)

For above image, I only see the letters in the middle `hoo` and text is truncated like that:

![image](https://user-images.githubusercontent.com/749374/32953564-f381688a-cbb0-11e7-8142-ec6da1fe9ff9.png)

I'm using new SDK 23, and it works as expected on iOS.

**Comment by gamingumar** [comment]
i am also facing the same issue. it was working fine before the expo app update. even though my app is still on version 22

**Comment by aalices** [comment]
Is this happening on a standalone-app or in Expo client?

**Comment by slorber** [comment]
I am getting this in Expo client, didn't deploy to standalone app

**Comment by gamingumar** [comment]
happening in expo client. haven't tested in standalone

**Comment by brentvatne** [comment]
hi folks! sorry for the hassle. we are investigating this issue

**Comment by aalices** [comment]
Hey! Sorry again for that, this should be fixed in a couple a days with a minor release to SDK 23!
