### ISSUE TITLE
React Native Web: After ejecting web doesn’t work

### ISSUE THREAD

**Issue by fullhdpixel** [expo/expo#9714]
### Summary of Issue

Just tried to eject my RN expo app, because I want to add in app payments for android and iOS. However, the app crashes on web giving the following error:

> funcError: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of ExpoRootComponent. “registerRootComponent.web”

SDK version: 38
Platforms: All

So, in the managed workflow the web version works fine, but not in the bare workflow.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

SDK version: 38
Platforms: All

### Steps to Reproduce

’ve just tried to eject my RN expo app, because I want to add in app payments for android and iOS. However, the app crashes on web giving the following error:

funcError: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of ExpoRootComponent. “registerRootComponent.web”

So, in the managed workflow the web version works fine, but not in the bare workflow. Steps to reproduce:

1. Create new app
2. Add react-native-web
3. Eject to bare workflow
4. Try to start app

### Expected Behavior vs Actual Behavior

Expected behaviour: show web app
Actual behaviour: crash

**Comment by brentvatne** [comment]
```
Create new app
Add react-native-web
```

i'm not following this. what does "add react-native-web" mean? if you run `expo init` and choose any of the templates you already have react-native-web installed automatically.

i initialized a new blank app, ran it with `expo start` and chose web, it worked. then i ejected, ran it again on web, worked as expected. so there is something going on with your configuration. you may want to post more information and a minimal reproducible example to https://forums.expo.io.
