### ISSUE TITLE
Error messages when submitting a new SDK 23 build

### ISSUE THREAD

**Issue by sonaye** [expo/expo#972]
Thought I should share this here, no error messages in SDK 22 builds.

<img width="662" alt="screen shot 2017-11-17 at 5 44 58 pm" src="https://user-images.githubusercontent.com/23000873/32953677-0095af2a-cbc2-11e7-8925-33b9fbc2b107.png">

**Comment by terribleben** [comment]
Thanks, can you share the build id that resulted in this?

**Comment by sonaye** [comment]
Not sure, but it could be this one `3e73b792-e47b-490b-9918-4ff51da47d66`, ran `exp build:status` on the project I think I was working on at the time.

**Comment by terribleben** [comment]
Thanks. It looks like that build failed for a keychain reason so it's probably not the one I'm looking for.

I'm consolidating reports of this issue to [here](https://github.com/expo/expo/issues/980). I would appreciate it if you could share any build ids you come across which seem to demonstrate this icon issue. :)
