### ISSUE TITLE
Expo Contact Source?

### ISSUE THREAD

**Issue by SirPhemmiey** [expo/expo#9723]
Hi guys, 

You know a contact can be saved directly on the Phone, and in the case of Dual Sim Phone, contacts can be saved on either sim.

So i wanna ask, what's the source of where expo-contact gets the contact to render? Phone contacts or Sim contacts? Or where generally? 

Thanks for your response.

**Comment by byCedric** [comment]
Hi @SirPhemmiey! We use the default native platform contact source, meaning we simply ask the OS for contacts.

- On Android, that's the [Contacts Provider](https://developer.android.com/guide/topics/providers/contacts-provider). 
- On iOS, that's the [Contacts API](https://developer.apple.com/documentation/contacts)

I think it includes the SIM contacts, but it's probably listed in the documentation I linked.

Hope it helps!
