### ISSUE TITLE
unable to login 

### ISSUE THREAD

**Issue by jpca999** [expo/expo#973]
Whenver you have this kind of url it always throws this error even when the username is provided.... but if the url is clean it works fine..  Thought you should know. 

![image](https://user-images.githubusercontent.com/1026325/32958081-667f46b6-cb8b-11e7-93ed-0acd94d7a870.png)

**Comment by terribleben** [comment]
Hey there, I'm not sure what you're reporting. Your screenshot shows a field with no username and an error asking you for a username. And I don't understand your comment about the url. Can you be more specific about what you expect to happen and what you observe that is different from that?

**Comment by jpca999** [comment]
" Your screenshot shows a field with no username"
i hide my username, but its there.

**Comment by terribleben** [comment]
Please let us know if you're still having an issue with this, we've changed the way login works since this issue was opened. Closing for now.
