### ISSUE TITLE
fix link to README in configure-splash-screen (Android section) for react native bare workflow

### ISSUE THREAD

**Issue by Oooom** [expo/expo#9733]
currently the link to README in Android section for configure-splash-screen points to a deprecated package, it should point to "https://github.com/expo/expo-cli/tree/master/packages/configure-splash-screen"  which was the intended target. Do note that the iOS section has the correct linkage.

**Comment by Oooom** [comment]
should I provide a PR ?

**Comment by byCedric** [comment]
Hi @Oooom! Yes, that would be awesome! I'm not exactly sure what link you mean, but if you can put up a PR I can double-check this and merge your contribution! (add me as a reviewer to the PR please) 😄

**Comment by Oooom** [comment]
Since this was my first contribution to this repo, I did not have any option to Request Reviewer, however it got automatically assigned to @bbarthec.  However it seems, I failed some checks, I literally swapped a link with the other one 🤔

**Comment by byCedric** [comment]
@Oooom, no worries! Thanks for the PR it looks great 😄  The failing CI is mostly because you are creating an external PR, meaning the PR doesn't have access to some keys. Don't worry about that 😄
