### ISSUE TITLE
[docs] Keeping the bundle size small in bare apps with exclude

### ISSUE THREAD

**Issue by etaiklein** [expo/expo#9736]
Improvement for https://docs.expo.io/bare/installing-unimodules/ (or maybe a new page in /bare relating to app performance?)

see https://forums.expo.io/t/unimodules-what-else-can-i-exclude/41079/3

I would like to avoid integrating with unnecessary modules and bloating my app. Since there is only a denyList exclude option and not an allowList include option- how can I get the full list of excludable modules?

Also, modules excluded in native integrations are still unnecessarily downloaded into /node_modules. I would love the documentation to show steps for removing excluded node_modules safely.

Request:
How can I get the full list of excludable modules?
How can I remove excluded modules from node_modules?
Any other tips for keeping the bundle small in the bare workflow.

**Comment by brentvatne** [comment]
hi there!

> How can I get the full list of excludable modules?

the following pages are added via react-native-unimodules: https://github.com/expo/expo/blob/714a594adb16175b6490ad488f3a97c7fbf922b1/packages/react-native-unimodules/package.json#L42-L57

first, you don't need to exclude any of the interfaces. they [empty js files](https://github.com/expo/expo/blob/master/packages/unimodules-file-system-interface/index.js) and [one or two header files](https://github.com/expo/expo/blob/master/packages/unimodules-file-system-interface/ios/UMFileSystemInterface/UMFileSystemInterface.h) that allow distinct modules to depend on functionality from other modules by requesting a module that implements an interface. these will have no size or performance impact on your app when it's built.

second, you almost certainly want expo-asset, expo-file-system (required by expo-asset), expo-constants, and expo-permissions. these are used by every app, through apis like `Font` or `Camera` or `Updates` and a variety of other things.

so what's left? if you have the `expo` package in your project, there are some additional dependencies here: https://github.com/expo/expo/blob/714a594adb16175b6490ad488f3a97c7fbf922b1/packages/expo/package.json#L59-L70

you may want to remove expo-sqlite, expo-splash-screen (although i'd recommend keeping it), expo-location, and expo-linear-gradient. up to you.

> How can I remove excluded modules from node_modules?

the only impact this will have is on your `npm install` time, js from packages that aren't used in your app will not be included in you final bundle. you can see this with https://github.com/IjzerenHein/react-native-bundle-visualizer
