### ISSUE TITLE
Expo camera does not take photos in landscape orientation

### ISSUE THREAD

**Issue by lucianoacsilva** [expo/expo#9740]
Hello,

Working here with Expo 36.0.0. When I use the expo-camera, it works fine in iOS (photos and videos are recorded both in portrait and landscape orientations). However, in Android, it is forced to portrait orientation.
Anyone knows how could this issue be fixed?

Luciano

**Comment by lucianoacsilva** [comment]
**Steps to reproduce:**

Take a picture or record a video on portrait mode. It works fine.

Turn device to horizontal and make the same thing: photo/video is rotated by 90º.

This issue only happens on Android.

**Comment by nachozullo** [comment]
Same issue SDK 38

**Comment by fabriziobertoglio1987** [comment]
https://docs.expo.io/versions/latest/sdk/camera/#recordasync exif should tell you the orientation of the video.
