### ISSUE TITLE
DeviceMotion - addListener not listening

### ISSUE THREAD

**Issue by moshfeu** [expo/expo#9742]
### Summary of Issue 

`addListener` callback doesn't fired when the device moved

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

See the snack (can't run `expo diagnostics`).

Tested on Xiomi Redmi 7A - Android 10 QKQ1.191014.001.
Expo 2.16.1

### Reproducible Demo

https://snack.expo.io/@moshfeu/ori

 
### Steps to Reproduce

Just play the snack

### Expected Behavior vs Actual Behavior

It was working some time ago, I'm not sure what changed.
https://github.com/moshfeu/expo-detect-orientation-device-motion

**Comment by EvanBacon** [comment]
Works on iOS. Please fill out the entire issue template.

**Comment by moshfeu** [comment]
Thanks! I've updated the issue. I think the platform was the only missing part.

**Comment by icetee** [comment]
I try iPhone 8, and no listening. On Android device listening.

Expo **39.0.5**
expo-sensors **9.10.0**

**Comment by liquidvisual** [comment]
Testing with iPhone 6s and also no listening.

Expo 44.0.0
expo-sensors 11.1.0

**Comment by liquidvisual** [comment]
Update: it does appear to work on iOS, however enabling Chrome Debugging prevents the listener from firing it seems. Testing on an iPhone 6s, 13, iPad Air 2 - results are all the same. I can only see my listener logs in the XCode console when debugging is off. Android works fine, but I'm using Flipper for debugging there.
