### ISSUE TITLE
FCM Push Notifications give 2 notifications and don't trigger listener [SDK 38.0.9]

### ISSUE THREAD

**Issue by JamieS1211** [expo/expo#9743]
### Summary of Issue 
When sending push notifications (managed workflow) to android devices directly (running a built standalone app), using FCM and firebase-admin-sdk, 2 notifications are presented to the user, one with and one without the correct logo. Furthermore, both of these notifications open the app, however neither run the `NotificationResponseReceivedListener`.

![image](https://user-images.githubusercontent.com/8209033/90180685-4085aa00-dda7-11ea-8e44-dbfa00248614.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.24.0 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: 38.0.9 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2

### Reproducible Demo

app - https://github.com/JamieS1211/Expo-Notification-bug-app
api - https://github.com/JamieS1211/Expo-Notification-bug-api
 
### Steps to Reproduce

1. Install demo on android device using apk included in demo repo (https://github.com/JamieS1211/Expo-Notification-bug-app/blob/master/Builds/notification-demo-app-a329051fa10249ee9954446488fe7002-signed.apk) OR by:
    - Cloning demo
    - Build app using `expo ba`
    - Download freshly build apk
2. Run app open app on phone and copy the device token
3. Navigate away from the app so it is in background (there are further bugs meaning notifications won't get delivered when in foreground or closed - this bug is mentioned in #9745)
4. Copy device token into api code at (https://github.com/JamieS1211/Expo-Notification-bug-api/blob/master/src/index.ts#L16)
5 . Run api using `npm run dev-start`
6. Perform a get request to [http://localhost:3001FCMTestNotificationMessage](http://localhost:3001/FCMTestNotificationMessage) (you can just open this address in your browser) to get API to send notification

### Expected Behavior vs Actual Behavior
I would expect a single notification, with the logo, that on clicked ran the `NotificationResponseReceivedListener`.

**Comment by lukmccall** [comment]
Hi @JamieS1211, you're sending the `notification` object so the notification will be handled by the FCM itself. Moreover, the firebase copies the `notification` Consequently, you will see two notifications 😕

How it's work?
When the system gets the remote message it checks if the `notification` key is present. Then it decides if it should show the notification and if it should be dispatch to `expo-notifications`.

**Comment by JamieS1211** [comment]
Hi @lukmccall, thanks for the info. Really interesting about the two notifications, I was wondering what may be the cause. I am assuming you closed this as this is intended behaviour. While it would be nice to handle this via expo-notifications, if you can't prevent firebase handling the message itself, I can see why this is not supported.
