### ISSUE TITLE
FCM "data" type Push Notifications not recieved [SDK 38.0.9]

### ISSUE THREAD

**Issue by JamieS1211** [expo/expo#9744]
### Summary of Issue 
When sending "data" type (please see documentation found here [https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages](https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages)) push notifications (managed workflow) to android devices directly (running a built standalone app), using FCM and firebase-admin-sdk, no notifications are shown to user.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.24.0 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: 38.0.9 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2

### Reproducible Demo

app - https://github.com/JamieS1211/Expo-Notification-bug-app
api - https://github.com/JamieS1211/Expo-Notification-bug-api
 
### Steps to Reproduce

1. Install demo on android device using apk included in demo repo (https://github.com/JamieS1211/Expo-Notification-bug-app/blob/master/Builds/notification-demo-app-a329051fa10249ee9954446488fe7002-signed.apk) OR by:
    - Cloning demo
    - Build app using `expo ba`
    - Download freshly build apk
2. Run app open app on phone and copy the device token
3. Navigate away from the app so it is in background (there are further bugs meaning notifications won't get delivered when in foreground or closed)
4. Copy device token into api code at (https://github.com/JamieS1211/Expo-Notification-bug-api/blob/master/src/index.ts#L16)
5 . Run api using `npm run dev-start`
6. Perform a get request to [http://localhost:3001FCMTestDataMessage](http://localhost:3001/FCMTestNotificationMessage) (you can just open this address in your browser) to get API to send notification

### Expected Behavior vs Actual Behavior
I would expect a "data" type notification to arrive on device.

**Comment by lukmccall** [comment]
Hi @JamieS1211, I think that if you add the `experienceId` field to your data object, it should work. See https://github.com/expo/expo/issues/8250#issuecomment-666319674

**Comment by JamieS1211** [comment]
Hi @lukmccall thanks for your message.

I have just read the thread with the tagged comment and its important to note that that other thread is discussing sending notifications with the Expo service, not FCM directly using firebase-admin-sdk as in this case (See server side sending code here: https://github.com/JamieS1211/Expo-Notification-bug-api/blob/master/src/index.ts#L20).

When trying as you suggested firebase-admin-sdk, I attempted adding the `experienceId` key in 4 different ways summarised below:

--------------------
Data object with `experienceId`

![image](https://user-images.githubusercontent.com/8209033/90235816-d1956900-de19-11ea-8c2e-351ce2332c78.png)

This resulted in the same behaviour as outlined in bug report.

-------------------
Data object with `experienceId` within the notification object

![image](https://user-images.githubusercontent.com/8209033/90235287-f5a47a80-de18-11ea-8734-f33f92aa24f4.png)

Typescript error and throws a `messaging/invalid-argument` error when forced to run.

-------------------
Add `experienceId` to the notification object

![image](https://user-images.githubusercontent.com/8209033/90236205-6009ea80-de1a-11ea-8c41-a0d9e8f6864b.png)

Typescript error and throws a `messaging/invalid-argument` error when forced to run.

-------------------
Add `experienceId` as a key directly in the message object

![image](https://user-images.githubusercontent.com/8209033/90236346-89c31180-de1a-11ea-812c-318bc5198657.png)

Typescript error and throws a `messaging/invalid-argument` error when forced to run.

**Comment by JamieS1211** [comment]
I have also seen this section of code in expo that _could_ be the problem:

https://github.com/expo/expo/blob/master/packages/expo/src/Notifications/Notifications.ts#L93

> function _validateNotification(notification) {
  if (Platform.OS === 'ios') {
    invariant(
      !!notification.title && !!notification.body,
      'Local notifications on iOS require both a title and a body'
    );
  } else if (Platform.OS === 'android') {
    invariant(!!notification.title, 'Local notifications on Android require a title');
  }
}

This seems like any data message according the the spec set out by FMC (https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages) would be incorrectly identified as invalid. I'm not well versed in the source so this code snippet may well only apply to local notifications.

**Comment by lukmccall** [comment]
Firebase handles two different types of remote messages:
- `data` message which is handled by the client app.
- `notification` message which is handled by the FCM SDK automatically.
If you send an object with a `notification` key, the system will handle it. You can read more about it [here](https://firebase.google.com/docs/cloud-messaging/concept-options). The `expo-notifications` was created to handle `data` messages. So your notification object should look like this:
```ts
const message = {
	token: "<token>",
	data: {
    	title: "<title>",
			body: "<body>",
	  	experienceId: "<your experienceId>"
    }
}
```
You can customize it by adding more fields: https://github.com/expo/expo/blob/faec32dd55b4aa17b4c3d8e31717f2ef27860f90/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/JSONNotificationContentBuilder.java#L17-L28
but they must be in the `data` object.

The code snippet which you provided only applies to local notifications - we can ignore it for now 😅

**Comment by JamieS1211** [comment]
Thanks so much for the info. Firstly I want to say I made a mistake and got the value of the `experienceId` wrong. For those of you who may read this at a later date, I found the correct value marked as the "full name" of the app in the Expo build logs (will leave a photo below).

I can confirm that when specifying the `experienceId` correctly in `data` does result in Expo handling the notification. It would however be nice to be able to customise the behaviour such that this wasn't required. This has caused us a problem because we use a third party analytics tool that isn't very flexible with the data structure to send push notifications via FCM. In this exact case I am able to work around this but I am sure others will find this problem at some point. 

Should I open another ticket to request this feature?

I have also just tested notifications on android in every way I can think of and gave this:
![image](https://user-images.githubusercontent.com/8209033/90402695-b899eb80-e097-11ea-81b0-11f1c56cf029.png)

------------
Details on finding full name
------------
![image](https://user-images.githubusercontent.com/8209033/90399533-006a4400-e093-11ea-8078-1a396ba27ac0.png)

**Comment by lukmccall** [comment]
@JamieS1211, could you open a new issue for that? It will be easier to track.

**Comment by JamieS1211** [comment]
@lukmccall Just had a look at the feature request template and said I should use Canny instead of GitHub. To clarify, would you prefer a Canny feature request about the handling of FCM "data" type messages without needing the "experienceId" or a new bug report stating that this doesn't function?

Its the age old tale of is this a bug or an intended feature 😀

**Comment by giautm** [comment]
I ran to same issue with @JamieS1211 on Android, I used third-party chat system (GetStream.io) for chat feature. They allow to config notification on Android with FCM server key & template for `notification` & `data`. But, they require `notification` always exist. So, the notification send from GetStream result in duplicate as 2 two notifications & can't open app (https://github.com/expo/expo/issues/9743).

The way that Expo team implement expo-notifications use `data` type was not intended. It may helpful in Expo client, but not on Standalone build/Bare workflow.

**Comment by lukmccall** [comment]
@JamieS1211, sorry for my late reply.

You can use Canny. Hovewer, I don't know if we'll add support for this. Why? The answer is pretty simple. This will make our API more confusing and unpredictable. Becouse we can't manage such a notification. We don't have any control - for example, it can look different on different phones.  Maybe in the future, when `expo-notification` will become more mature. But for now, we want to improve the existing code.

**Comment by rizikolik** [comment]
> Firebase handles two different types of remote messages:
> 
> * `data` message which is handled by the client app.
> * `notification` message which is handled by the FCM SDK automatically.
>   If you send an object with a `notification` key, the system will handle it. You can read more about it [here](https://firebase.google.com/docs/cloud-messaging/concept-options). The `expo-notifications` was created to handle `data` messages. So your notification object should look like this:
> 
> ```ts
> const message = {
> 	token: "<token>",
> 	data: {
>     	title: "<title>",
> 			body: "<body>",
> 	  	experienceId: "<your experienceId>"
>     }
> }
> ```
> 
> You can customize it by adding more fields:
> 
> https://github.com/expo/expo/blob/faec32dd55b4aa17b4c3d8e31717f2ef27860f90/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/JSONNotificationContentBuilder.java#L17-L28
> 
> 
> but they must be in the `data` object.
> The code snippet which you provided only applies to local notifications - we can ignore it for now 😅

@lukmccall , so after sending a notification from FCM, if notification object includes a notification field, that notification will be handled by the sysytem not the expo-notification.
But how sytem will show that message or how we should detect click events ?
Are you suggesting to use another package for handling that parts  ?
