### ISSUE TITLE
FCM Push Notifications not received when app is in foreground [SDK 38.0.9]

### ISSUE THREAD

**Issue by JamieS1211** [expo/expo#9745]
### Summary of Issue 
When sending push notifications (managed workflow) to android devices directly (running a built standalone app), using FCM and firebase-admin-sdk, 2 notifications are not delivered when app is in the foreground ~~or the app is closed~~. These notifications are delivered when the app is in the background, however please note there is an additional issue with these messages when delivered as mentioned in #9743 .

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.24.0 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: 38.0.9 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2

### Reproducible Demo

app - https://github.com/JamieS1211/Expo-Notification-bug-app
api - https://github.com/JamieS1211/Expo-Notification-bug-api
 
### Steps to Reproduce

1. Install demo on android device using apk included in demo repo (https://github.com/JamieS1211/Expo-Notification-bug-app/blob/master/Builds/notification-demo-app-a329051fa10249ee9954446488fe7002-signed.apk) OR by:
    - Cloning demo
    - Build app using `expo ba`
    - Download freshly build apk
2. Run app open app on phone and copy the device token (leave app in the foreground ~~OR close the app~~)
3. Copy device token into api code at (https://github.com/JamieS1211/Expo-Notification-bug-api/blob/master/src/index.ts#L16)
4 . Run api using `npm run dev-start`
5. Perform a get request to [http://localhost:3001/FCMTestNotificationMessage](http://localhost:3001/FCMTestNotificationMessage) (you can just open this address in your browser) to get API to send notification

### Expected Behavior vs Actual Behavior
I would expect a the notification to be recieved.

**Comment by JamieS1211** [comment]
Following discussion on issue #9748 (https://github.com/expo/expo/issues/9748), I can confirm that the problem with the app being closed is the same as there.

Hence this bug report now only refers to when the app is in the foreground

**Comment by cruzach** [comment]
Hey @JamieS1211 , I tried to repro this behavior and couldn't (notifications delivered while the app is in foreground come through correctly)

Does this only happen when using the server you linked? Could you try sending a notification with the [Expo push tool](https://expo.io/notifications), or [with your CLI](https://docs.expo.io/push-notifications/sending-notifications/#dont-want-to-use-one-of-the) so that you can get more info from the push receipt?

**Comment by JamieS1211** [comment]
Hi @cruzach thanks for your help on this topic.

I can confirm that this is still the behaviour (just tested with the demo code bases) however given the suggestion of using the Expo push tool I think its worth clarifying that this is when using FCM and firebase-admin-sdk. If you look at the endpoint mentioned (/FCMTestNotificationMessage) in the api you can find the payload sent and sending method - https://github.com/JamieS1211/Expo-Notification-bug-api/blob/master/src/index.ts#L18.

I have been doing a review of all push notification methods for android and this may also help (Purple is this issue)
![image](https://user-images.githubusercontent.com/8209033/90537990-d6d61900-e175-11ea-9ff4-45afac8ce709.png)

**Comment by JamieS1211** [comment]
Hi @cruzach, I just checked #9743 and @lukmccall closed the issue and mentioned a bit of what was going on behind the scenes. From the sound of that (and given the issue was closed) I think I am operating outside of the realm of what is supported. Are you able to clarify if this is the correct?

If this is the case, I think we can close the issue, but given that expo offers the `getDevicePushTokenAsync()` function, I think it should be noted somewhere that this behaviour is not supported. It could also be mentioned that `experienceId` is required on "data" messages to be processed correctly.

I would be really happy to write (or help write) such documentation messages following all the testing I have done but not quite sure where it belongs. Would you recommend the notifications API reference (https://docs.expo.io/versions/v38.0.0/sdk/notifications/#getdevicepushtokenasync-devicepushtoken), guide (https://docs.expo.io/push-notifications/using-fcm/), both, or other?

**Comment by cruzach** [comment]
Sure @JamieS1211, we can definitely work on those docs. It's actually an open issue right now- https://github.com/expo/expo/issues/9574 so let's close these issues in favor of that.

**Comment by JamieS1211** [comment]
Oh god, If I had seen that a few weeks ago would have saved me a bunch of time haha
