### ISSUE TITLE
[iOS][Expo SDK 38]TextInput font is shaking when inputting Japanese text

### ISSUE THREAD

**Issue by rajkumarwaghmare** [expo/expo#9751]
### Summary of Issue 
After upgrading to Expo SDK 38, inputting Japanese text in TextInput shakes(flickers) the text.
This is problem already reported for RN 0.62 https://github.com/facebook/react-native/issues/28488
Its fixed in RN 0.63.1
When will Expo SDK will deliver this fix?

![image](https://user-images.githubusercontent.com/4617627/90217588-bf78f200-de3c-11ea-8cb1-bf8feff90210.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: 38.0.9 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.3`
`

### Steps to Reproduce
- Create screen with TextInput element in it
- Start typing Japanese or Korean or Chinese

### Expected Behavior vs Actual Behavior
Expected Behavior: Text should not shake (as it wont for English)
Actual Behavior: Japanese text shakes(flickers) when started typing

**Comment by brentvatne** [comment]
hi there! we plan on including rn 63 in sdk 39, so this should be resolved soon. rn 63 is already on expo/expo master, we're working on getting sdk 39 ready.
