### ISSUE TITLE
[expo-camera] Camera crashes on iOS

### ISSUE THREAD

**Issue by Saifadin** [expo/expo#9752]
### Summary of Issue

On a Bare, Ejected App the App Crashes sometimes when the Camera is opened. There is no discernable pattern. Sometimes it happens right after a Download from TestFlight. Sometimes it happens after an OTA Update (pretty regular)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.22.3
```

We are targeting iOS and Android

### Reproducible Demo

I do not have a reproducible Demo, unfortunately. But I have a recent Crash Log from testflight.
[testflight_feedback (3).zip](https://github.com/expo/expo/files/5073444/testflight_feedback.3.zip)

I hope that helps to figure it out. Also I got this error, while debugging with XCode and it happened in the EXCamera pod.

```
-[AVCaptureDevice setActiveColorSpace:] Not supported - use activeFormat.supportedColorSpaces"
```
 
### Expected Behavior vs Actual Behavior

Camera opens without crashing the App.

**Comment by brentvatne** [comment]
hi there! feel free to reopen the issue when you have a reproducible demo
