### ISSUE TITLE
Flatlist crashes on iOS when maintainVisibleContentPosition is set to true

### ISSUE THREAD

**Issue by divonelnc** [expo/expo#9757]
### Summary of Issue 
When using `maintainVisibleContentPosition` on a Flatlist on **iOs**, the app throws the error: `Exception thrown while executing UI block: - [__NSCFBoolean objectForKeyedSubscript:]: unrecognized selector sent to instance 0x11bfcae48.`

The crash stops when the prop is removed.

### Environment 
```
Expo CLI 3.24.0 environment info:      
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.15.3 - E:\nodejs\node.EXE 
      Yarn: 1.22.0 - E:\Yarn\bin\yarn.CMD
      npm: 6.14.5 - E:\nodejs\npm.CMD
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```

### Reproducible Demo
Here is the snack with exactly the same code from my app (direct copy-paste of my `App` component). For some reason, it works fine on the snack.
https://snack.expo.io/@divone/flastlist-crash
 
### Steps to Reproduce
- Use a Flastlist anywhere in your code and set the `maintainVisibleContentPosition` props to true.

Screenshot of the crash:
![Simulator Screen Shot - iPhone X - 2020-08-14 at 13 05 19](https://user-images.githubusercontent.com/1695307/90258867-6ebbc600-de49-11ea-8e2d-d5c367515346.png)

**Comment by divonelnc** [comment]
This still happens with react-native 0.63.2, expo SDK 39.

```
 Expo CLI 3.27.14 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.15.3 - E:\nodejs\node.EXE
      Yarn: 1.22.0 - E:\Yarn\bin\yarn.CMD
      npm: 6.14.5 - E:\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.0, 29.0.3
        System Images: android-29 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.16
    Expo Workflow: managed
```

**Comment by tslater** [comment]
@divonelnc  have you determined that this is expo specific? I just came across it and am wondering if you think ejecting would help.

**Comment by divonelnc** [comment]
I haven't ejected so I am not sure if it is expo specific. It does happen in production though, so I am not sure ejecting will help.
