### ISSUE TITLE
[media-library] asset.getString() throws IllegalStateException

### ISSUE THREAD

**Issue by ahmetbicer** [expo/expo#9759]
### Summary of Issue 
In media-library 9.1.0 when asset.getString() called in GetAlbums.kt app crashes and throws an IllegalStateException. It wasn't happened in emulator, i found about this crash when i tested in a device (Samsung galaxy M20 API29)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Bare react native project
"react-native": "0.63.2"
"expo-av": "^8.5.0",
"expo-media-library": "^9.1.0",
"react-native-unimodules": "^0.10.1",

buildToolsVersion = "29.0.0"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29

I debugged it in android studio. This is happening because in GetAlbums.kt `asset.getString(bucketDisplayNameIndex)` [called](https://github.com/expo/expo/blob/714a594adb16175b6490ad488f3a97c7fbf922b1/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt#L42) and implementation of `getString()` in `Cursor.java` says;
```
The result and whether this method **throws an exception** when the column value is null or the column type is not a string type is implementation-defined.
```
So we just need to handle this exception and give it a fallback string to get rid of this error.

When i changed the following line to a normal string in GetAlbums.kt, media-library works as expected.

```
while (asset.moveToNext()) {
            val id = asset.getString(bucketIdIndex)
            val album = albums[id] ?: let {
              Album(
                id = id,
                title = asset.getString(bucketDisplayNameIndex) // i changed this line to title = "example" and error resolves.
              ).also {
                albums[id] = it
              }
            }

            album.count++
          }
```
Thanks!

edit: stack trace added

```
I/System.out: 1 // this is what println(bucketDisplayNameIndex) gives
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.framebyframe, PID: 9371
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: asset.getString(bucketDisplayNameIndex) must not be null
        at expo.modules.medialibrary.GetAlbums.doInBackground(GetAlbums.kt:42)
        at expo.modules.medialibrary.GetAlbums.doInBackground(GetAlbums.kt:10)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by barthap** [comment]
Hmm... that's interesting - it worked for me as expected, I'll investigate it more

**Comment by ahmetbicer** [comment]
Hi @barthap, Very interesting issue because It is working in android emulator (pixel 3XL API29) and another device (samsung galaxy M31 API29) as excepted. I tried `8.4.0` but it is crashing too because in `8.4.0` the `Invalid Column Count(*)` error not yet resolved.

**Comment by barthap** [comment]
> I tried 8.4.0 but it is crashing too because in 8.4.0 the Invalid Column Count(*) error not yet resolved.

Yeah, I expected that. But I'm wondering, why on some devices column `bucket_display_name` is `null` - there's nothing in Android docs about it, the only comment I found is [here](https://stackoverflow.com/questions/4195660/get-list-of-photo-galleries-on-android#comment111531117_4196411). This column should always exist along with `bucket_id`.

**Comment by ahmetbicer** [comment]
I found [this](https://stackoverflow.com/a/60162322/12046988) comment, maybe it is worth checking? I found some `.mp3` and `.pptx` files in root directory of sd card, moved it to another folder but it didn't work.

**Comment by barthap** [comment]
Thanks, I'll check that. You can also check for all media locations using sth like
```js
const { assets } = await MediaLibrary.getAssetsAsync({ first: 9999, /* mediaType: [...] */ });
assets.forEach(asset => console.log(asset.uri));
```
Try with different [_media types_](https://docs.expo.io/versions/v38.0.0/sdk/media-library/#medialibrarymediatype) - `getAlbumsAsync()` returns directories with files of all types, except `unknown`.

**Comment by ahmetbicer** [comment]
> You can also check for all media locations using sth like

Did you suggest this because i said `I found some .mp3 and .pptx files in root directory of sd card, moved it to another folder but it didn't work.` ? I didn't quite understand. I said that because [this](https://stackoverflow.com/a/60162322/12046988) comment says 

> One of the situation that occurred was that, in Android Q any media files (images, videos etc) in the root directory, the folder name will be returned as null (in case of Internal Storage). In previous versions, it's been returned as 0 as album name. Just check for null for returned folder name and assign some default album name and you can avoid this crash I guess.

So i thought `.mp3` and `.pptx` files in root directory of sd card causes this issue and moved to another folder and it still crashed.

Sorry, my english not that good if i understand it wrong.

Thanks.

**Comment by barthap** [comment]
Sorry, I didn't explain my point. You said about some non-media extensions like `.pptx` - I thought it could also find files (and directories) which should not be treated as media. My code above should list all places where media files (of different types) are found.
That's because you said you moved them to another folder but it still didn't work. However, you mean _sd card_, but the original post meant _internal storage_. Please also check internal storage.

The last thing you can do is to debug value of album `id` (I mean [this line](https://github.com/expo/expo/blob/714a594adb16175b6490ad488f3a97c7fbf922b1/packages/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt#L37)) when it crashes. Or, to give even more useful info, debug this to give an URI of crashing album:
```diff
--- a/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt
+++ b/node_modules/expo-media-library/android/src/main/java/expo/modules/medialibrary/GetAlbums.kt
@@ -11,7 +11,7 @@ internal open class GetAlbums(private val mContext: Context, private val mPromis
   : AsyncTask<Void?, Void?, Void?>() {

   override fun doInBackground(vararg params: Void?): Void? {
-    val projection = arrayOf(Media.BUCKET_ID, Media.BUCKET_DISPLAY_NAME)
+    val projection = arrayOf(Media.BUCKET_ID, Media.BUCKET_DISPLAY_NAME, Media.DATA)
     val selection = "${MediaStore.Files.FileColumns.MEDIA_TYPE} != ${MediaStore.Files.FileColumns.MEDIA_TYPE_NONE}"

     val albums = HashMap<String, Album>()
@@ -32,9 +32,13 @@ internal open class GetAlbums(private val mContext: Context, private val mPromis
           }
           val bucketIdIndex = asset.getColumnIndex(Media.BUCKET_ID)
           val bucketDisplayNameIndex = asset.getColumnIndex(Media.BUCKET_DISPLAY_NAME)
+          val dataIndex = asset.getColumnIndex(Media.DATA)

           while (asset.moveToNext()) {
             val id = asset.getString(bucketIdIndex)
+
+            val uri = asset.getString(dataIndex)    //DEBUG THIS VALUE
+                                                            //it should be the asset URI

             val album = albums[id] ?: let {
               Album(
```

**Comment by ahmetbicer** [comment]
Hi @barthap, 

> That's because you said you moved them to another folder but it still didn't work. However, you mean sd card, but the original post meant internal storage. Please also check internal storage.

At first i checked internal storage, there was no media files in root directory after that i checked sd card. 

I am going to debug the value you talked about but the phone that crashes is not with me now. I will give feedback to you this night.

Thank you so much!

**Comment by barthap** [comment]
I managed to reproduce this crash (using sdcard root directory) and prepared a fix (#9787). One solution is to simply skip those directories without name, but you can handle them as you wish.

But I'm curious what else directories could cause this crash.

**Comment by ahmetbicer** [comment]
Hey @barthap thank you for quick fix,
Only one question, if there is a video on the root directory. of sd card I can get that video with getAssetsAsync() but i can't get that directory as a album right?

**Comment by barthap** [comment]
Yes, you can use `MediaLibrary.getAssetsAsync()` to get that file. Only `getAlbums()` will not list the root directory as album. You can still do it manually by filtering `uri` path of your media assets.

```ts
function isRootDir(uri: string): boolean {
  const lastSlashPos = uri.lastIndexOf('/');
  if(lastSlashPos < 0) {
    return false;
  }

  const dir = uri.substring(0, lastSlashPos);
  return dir === 'file:///storage/emulated/0';
}

//now filter assets in root
const assetsInRoot = assets.filter(a => isRootDir(a.uri));
```

**Comment by ahmetbicer** [comment]
Thank you so much! It is been a quite of journey with different issues since last week. Thanks for everything.
