### ISSUE TITLE
AuthSession should provide an option to use SFSafariViewController

### ISSUE THREAD

**Issue by schettino** [expo/expo#976]
There are some occasions that we handle an authentication flow without relying on Cookies (i.e. just a code returning from the auth provider).

So, would be fine to use the SFSafariViewController within the WebBrowser API that the AuthSession API relies on, instead of SFAuthenticationSession, which is automatically selected.

Thus, we could avoid the message " 'MyAPP' Wants to Use "expo.io" to Sign In" that shows even on a stondalone app. (my users won't know what expo.io is - I felt in love with it, btw).

AuthSession is, indeed, a great wrapper for keeping a straightforward way to authenticate users.

**Comment by seekshiva** [comment]
You can use `WebBrowser.openAuthSessionAsync()` instead of `AuthSession.startAsync()` to open an auth session directly via your website so it will ask "'MY APP' wants to use "mysite.com" to Sign In".

**Comment by schettino** [comment]
@seekshiva sure, but the point here is that most users eventually will be using AuthSession, which provides linking out of the box in a very straightforward manner, but some users are struggling with the alert described above. If the main reason of the AuthSession is facilitate a web browser based authentication, would be nice such flag that makes possible call SFSafariViewController within the AuthSession component.

**Comment by brentvatne** [comment]
hello! sure, we could add this option. do you want to try opening a PR to https://github.com/expo/expo-sdk to support this?

**Comment by terribleben** [comment]
Hey there - we're hoping to keep this venue limited to bugs with Expo. Feel free to track this with a [canny feature request](https://expo.canny.io/feature-requests), or reach out if you're interested in adding support for this yourself in expo-sdk.
