### ISSUE TITLE
[docs] Hash in url includes in link for "Edit this page" and it shouldn't be

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#9760]
when using the "edit this page button here: https://docs.expo.io/versions/v38.0.0/sdk/permissions/#permissionslocation

I get directed to a 404 page here: https://github.com/expo/expo/edit/master/docs/pages/versions/v38.0.0/sdk/permissions/#permissionslocation.md

**Comment by brentvatne** [comment]
thanks for the report!

**Comment by barthap** [comment]
If anyone want to make a PR for this, here's the code that needs to be modified 😉 
https://github.com/expo/expo/blob/1de9452d2c00aa8dbcbeb7c4f5322da6a5b8be14/docs/components/DocumentationFooter.js#L20-L42

**Comment by barthap** [comment]
Hi @saideepesh000 
Just open a PR and reference this issue there. The URL with `edit` instead of `blob` is OK - it goes to edit page directly. Check it: https://github.com/expo/expo/edit/master/docs/pages/versions/v38.0.0/sdk/permissions.md

**Comment by saideepesh000** [comment]
Hi @barthap, if this seems to be correct then, I would PR this. Thanks 

```// Remove trailing slash and append .md
function githubUrl(path) {
  if (path.includes('/versions/latest/')) {
    if (path === '/versions/latest') {
      path = '/versions/unversioned/index';
    } else {
      path = path.replace('/versions/latest/', '/versions/unversioned/');
    }
  }

**if url contains "/#" then replace '#word' with 'empty string'** 
if(path.includes('/#')){ 
      path = path.replace('/#\w', '');
  } 


  else if (path.match(/v\d+\.\d+\.\d+\/?$/) || path === '/') {
    if (path[path.length - 1] === '/') {
      path = `${path}index`;
    } else {
      path = `${path}/index`;
    }
  }

  let pathAsMarkdown = path.replace(/\/$/, '') + '.md';
  if (pathAsMarkdown.startsWith('/versions/latest')) {
    pathAsMarkdown = pathAsMarkdown.replace('/versions/unversioned');
  }

  return `https://github.com/expo/expo/edit/master/docs/pages${pathAsMarkdown}`;
}
```

**Comment by saideepesh000** [comment]
@barthap, In your knowledge, are there any special characters that are used in those links other than this '-', so that I can add those chars to the regex.

**Comment by barthap** [comment]
I think there are none. URL paths match those from git `docs/pages` directory.

**Comment by saideepesh000** [comment]
> 
> 
> I think there are none. URL paths match those from git `docs/pages` directory.

Actually, there are some, For example [location](https://docs.expo.io/versions/v38.0.0/sdk/location/#returns-4), and also there are numbers, and that's why I included numbers in the regex.

**Comment by barthap** [comment]
But can't you just cut off everything that appears after # sign with the hash itself? Isn't that easier than using regex?

**Comment by saideepesh000** [comment]
> 
> 
> But can't you just cut off everything that appears after # sign with the hash itself? Isn't that easier than using regex?

Ya, didn't think about it, xD

**Comment by saideepesh000** [comment]
@barthap, is this fine 

```
 if(path.includes('/#')){
      path = path.substring(0, path.indexOf('/#'));
  } 
```

**Comment by barthap** [comment]
@saideepesh000, you can fork this repo, clone your fork, apply this code, cd `docs`, run `yarn`, then `yarn dev` and open `http://localhost:3000` in your browser to see if your change is working, then open a PR 😁 
More details [here](https://github.com/expo/expo/blob/master/CONTRIBUTING.md#-updating-documentation) (also check _Download and Setup_ section if something is not working).

**Comment by saideepesh000** [comment]
@barthap, ya I've done it, it's just a confirmation, if this looks good, I'd PR this.

**Comment by brentvatne** [comment]
thank you @saideepesh000 for moving this forward! ❤️
