### ISSUE TITLE
ScreenOrientation issue on iOS (iPad)

### ISSUE THREAD

**Issue by Xopsy** [expo/expo#9766]
### Summary of Issue

[ScreenOrientation](https://docs.expo.io/versions/latest/sdk/screen-orientation/) is not working properly on iPad:

ScreenOrientation.addOrientationChangeListener(listener) on iPad is not called when ScreenOrientation.Orientation.PORTRAIT_DOWN ==> 2

And when you call ScreenOrientation.getOrientationAsync() on Portrait upside down, you get wrong ScreenOrientation.Orientation, never is getting  ScreenOrientation.Orientation.PORTRAIT_DOWN

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.8 
      react: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-navigation: 3.12.0 => 3.12.0 
      expo-screen-orientation": 1.1.1 => 1.1.1
    npmGlobalPackages:
      expo-cli: 3.23.1

Platform for testing: Simulator iPad Prop (9,7-inch) iOS 13.5

### Reproducible Demo
 
[Snack](https://snack.expo.io/@heto/orientation-test)  to reproduce

### Steps to Reproduce

Launch on iPad on real device or simulator, and change the orientation of the device.

### Expected Behavior vs Actual Behavior

When iPad is on Portrait upside down --> ScreenOrientation.Orientation.PORTRAIT_DOWN:

 - ScreenOrientation.addOrientationChangeListener(listener) --> it should trigger the listener.
 - ScreenOrientation.getOrientationAsync() --> it should get ScreenOrientation.Orientation.PORTRAIT_DOWN, value 2.

**Comment by rodolfobarretoweb** [comment]
I'm getting the same behavior here.

**Comment by archcorsair** [comment]
I am experiencing the same problem.
The only time the orientation change listener triggers is when you move away or to orientation: `PORTRAIT_UP`.
I was able to reproduce this on iPad and iPhone simulators.

expo-screen-orientation: `~2.0.0`
Expo SDK: `39`
iOS Simulator: `iPad Pro (11-inch) 2nd Gen (iOS 14)`

**Comment by allandiego** [comment]
After upgrading to sdk 39 I'm getting the same behavior on android, listener function not begin called anymore on orientation change

expo 39
"expo-screen-orientation": "~2.0.0",

```ts
useEffect(() => {
    function handleOrientationChange(
      event: ScreenOrientation.OrientationChangeEvent
    ): void {
      setIsLandscapeLayout(event.orientationInfo.orientation > 2);
    }

    navigation.addListener('focus', () => {
      ScreenOrientation.addOrientationChangeListener(handleOrientationChange);
    });

    navigation.addListener('blur', () => {
      ScreenOrientation.removeOrientationChangeListeners();
    });
  }, [navigation]);
```

**Comment by badbod99** [comment]
Same issue here on SDK 39.  Function is not always being called.

```javascript
import { useEffect, useState } from 'react';
import * as ScreenOrientation from 'expo-screen-orientation';

const useScreenOrientation = () => {
  const [screenOrientation, setScreenOrientation] = useState();

  useEffect(() => {
    const initScreenOrientation = async () => {
      const currentOrientation = await ScreenOrientation.getOrientationAsync();
      setScreenOrientation(currentOrientation);
    };

    const screenOrientationListener = ScreenOrientation.addOrientationChangeListener(
      setScreenOrientation,
    );

    initScreenOrientation();
    return () => {
      ScreenOrientation.removeOrientationChangeListener(screenOrientationListener);
    };
  }, []);

  return screenOrientation?.orientationInfo
    ? screenOrientation.orientationInfo.orientation
    : screenOrientation;
};

export default useScreenOrientation;
```
