### ISSUE TITLE
Notifications.getExpoPushTokenAsync() throws error "Fetching the token failed: Given string is empty or null"

### ISSUE THREAD

**Issue by divonelnc** [expo/expo#9770]
### Summary of Issue
In production, the promise `await Notifications.getExpoPushTokenAsync()` throws the error: fetching the token failed: Given string is empty or null

The promise resolves properly in development, when using the expo app, but not on the published app on my Android phone.

### Environment
  ```
Expo CLI 3.24.0 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.15.3 - E:\nodejs\node.EXE
      Yarn: 1.22.0 - E:\Yarn\bin\yarn.CMD
      npm: 6.14.5 - E:\nodejs\npm.CMD
    npmPackages:
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```

### Steps to Reproduce
use the `registerForPushNotificationsAsync` method from the doc:

```
export async function registerForPushNotificationsAsync(userId) {
	let token;
	
	if (Constants.isDevice) {
		const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);		
		let finalStatus = existingStatus;
		if (existingStatus !== "granted") {
			const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
			finalStatus = status;
		}
		if (finalStatus !== "granted") {
			alert("Failed to get push token for push notification!");
			return;
		}
		try {
			token = await Notifications.getExpoPushTokenAsync();
		}catch(err){
			alert(`failed to get token error ${err}`);
		}
                token = token.data
	} else {
		alert("Must use physical device for Push Notifications");
	}

	return token;
}
```

I can't find any help to solve this and would greatly appreciate any sort of direction, because it delays the release of my app :(

**Comment by divonelnc** [comment]
Okay, I managed to fix it by adding `android.useNextNotificationsApi` on true to the app.json. Then doing `expo:build` would not be enough to fix the issue, I had to manually upload the new build. Now it works properly!

**Comment by barthap** [comment]
FYI - this error may also sometimes happen when your `google-services.json` is corrupted or missing. But if it's working properly, I'm closing the issue.

**Comment by tolgaduzenli** [comment]
@barthap we dont have google-service.json and still having same issue. After sdk 38 upgrade, we faced with this issue.
Any suggestion ?

Our app.json looks like;
`
"android": {
      "package": "",
      "versionCode": 1,
      "useNextNotificationsApi": true,
      "config": {
        "googleMaps": {
          "apiKey": ""
        }
      }
    },
`

**Comment by tolgaduzenli** [comment]
@divonelnc 

What you mean 'I had to manually upload the new build.'  Did you handle all of the steps while expo building android ?
Can you give more detail how did you handle the issue manually ?

Thanks.

**Comment by divonelnc** [comment]
> What you mean 'I had to manually upload the new build.' Did you handle all of the steps while expo building android ?

I did `expo build`, but instead of using `expo upload`, I downloaded the .apk and uploaded it myself through the Google play console (like you have to do when you first submit your build to the Play store).

**Comment by ran-cohen2804** [comment]
Anyone solved this issue?
getExpoPushTokenAsync still returned this error in stand alone version - APK.
Please help. We must go to Production with our App...

**Comment by divonelnc** [comment]
@ran-cohen2804 did you already add `android.useNextNotificationsApi` to the app.json file like I had to do? Because that solved it for me. (along with the manual upload of the build like I described above)

**Comment by ran-cohen2804** [comment]
I have already add useNextNotificationApi:
"useNextNotificationsApi": true
What do you mean in manual upload?
I make a build and install the apk on my device.

**Comment by ran-cohen2804** [comment]
I solved the issue.
Setup of FCM is **required** for standalone application (APK).
Unfortunately, EXPO is missing this part in their document: [https://docs.expo.io/versions/latest/sdk/notifications](url) 
You can find how to setup a Firebase account in this link: 
[https://docs.expo.io/push-notifications/using-fcm](url)

**Comment by carlosag012** [comment]
I know it's been a while but I am facing the same issue on iOS. I am using SDK 40 with EAS build. Running the app locally from the Expo.Go works OK, but not when deployed. Even when I build it, it logs the push notification setup. I thought Expo handled all of that with EAS now. Anybody has any idea where I can start looking? My issue is the same, `registerForPushNotificationsAsync` doesn't run, or returns anything, I get no alert. I also got `expo.plugins.expo-notifications` in my app.json.

**Comment by hislordshipprof** [comment]
> android.useNextNotificationsApi
hi i have a question. if you setup FCM how will you send the token to your backend? in my case i am using php for the backend so i wanted to do it the managed way.

**Comment by hislordshipprof** [comment]
> I have already add useNextNotificationApi: "useNextNotificationsApi": true What do you mean in manual upload? I make a build and install the apk on my device.

Hello, have you already set up FCM. in my case i havent set it up but i get the token for ios but not that of android when in production but works on my expo go app. any insight as to how you did yours since with mine i will be using php as the backend to store the user token.
