### ISSUE TITLE
Some modules not functioning in expo web

### ISSUE THREAD

**Issue by TagareRohan** [expo/expo#9771]
Hi.
I am trying to use Alert in expo web using react native Alert. However it is not displaying any alert messages on the screen. Also while using the Modals, the modals don't get toggled in the expo web.
And when I am trying to use react native DatePicker it first shows the following warning:

Warning: Failed prop type: Invalid prop `iconSource` supplied to `DatePicker`.

And on clicking the DatePicker icon shows the following error:

TypeError: react_native_web_dist_exports_DatePickerAndroid__WEBPACK_IMPORTED_MODULE_13__.default.open is not a function.

**Comment by mikirejf** [comment]
Alert (https://github.com/necolas/react-native-web/issues/1026) and modal (https://github.com/necolas/react-native-web/issues/1020) aren't implemented in react-native-web yet.

**Comment by TagareRohan** [comment]
Okay Thanks. And what about the DatePicker problem?

**Comment by mikirejf** [comment]
DateTimePicker is also not supported: https://docs.expo.io/versions/v38.0.0/sdk/date-time-picker/
You probably need to use a separate library for web only.

**Comment by cruzach** [comment]
Closing since this isn't a bug with Expo
