### ISSUE TITLE
undefined is not an object (evaluating 'StripeModule.init') ... working in Android, the problem is in IOS ...

### ISSUE THREAD

**Issue by LivanDiaz** [expo/expo#9772]
I'm using (expo-payments-stripe) I followed the steps of the expo documentation for android, (https://docs.expo.io/versions/v38.0.0/sdk/payments/#register-hook-in-order- to-let-stripe) ... I'm not sure if I followed them correctly for IOS,  I'm developing from Window ... and it's throwing me this error on IOS devices :::
**TypeError: undefined is not an object (evaluating 'StripeMudule.init')** ... if you could help me I would appreciate it ...

**Enviroment:**
react-native-cli: 2.0.1
react-native: 0.61.4
"react": "~16.9.0"
"expo": "~37.0.3"
"expo-payments-stripe": "~8.1.0",

**Comment by byCedric** [comment]
Hi @LivanDiaz, thanks for writing in. Without a [repro](https://stackoverflow.com/help/minimal-reproducible-example) I'm not exactly sure what's going on. It looks like the native code of `expo-payments-stripe` isn't properly set up, [it looks like it fails on this line](https://github.com/expo/expo/blob/master/packages/expo-payments-stripe/src/Stripe.ts#L28). 

My best guess would be:
1. Did you run [`npx pod-install`](https://github.com/expo/expo/tree/master/packages/expo-payments-stripe#configure-for-ios) after you installed the module?
2. Did you rebuild your app after the module was installed?

If you did both, please provide a small example. With that, we can investigate further 😄 

Hope it helps!

**Comment by LivanDiaz** [comment]
Hi @byCedric Thank you, I am very grateful that you answered ... I have been with the same error for several weeks. I am developing from Window OS. Here I show you the package.json and the screen where I use Stripe ... it's just a test screen, automatically when I jump to that screen it throws me the error. let me know if you need anything else, thanks in advance and blessings.


package.json
`
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "~10.0.6",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "cocoapods": "0.0.0",
    "expo": "~37.0.3",
    "expo-asset": "~8.1.4",
    "expo-constants": "~9.0.0",
    "expo-facebook": "~8.1.0",
    "expo-font": "~8.1.0",
    "expo-payments-stripe": "~8.1.0",
    "expo-stripe-checkout": "^1.0.1",
    "expo-web-browser": "~8.2.0",
    "firebase": "7.9.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-modal": "^11.5.6",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-stripe-api": "^0.1.0",
    "react-native-web": "~0.11.7",
    "stripe": "^8.60.0",
    "stripe-client": "^1.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0",
    "jest-expo": "~37.0.0",
    "react-native-credit-card-input": "^0.4.1",
    "react-native-keyboard-spacer": "^0.4.1"
  },
  "private": true
}`
 
**this is the screem where I use Stripe**
`import * as React from "react";
import { PaymentsStripe as Stripe } from "expo-payments-stripe";
import { useState, useEffect } from "react";
import {
  Image,
  Platform,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  Button,
} from "react-native";
import { ScrollView } from "react-native-gesture-handler";

export default function CheckOut({ route }) {
  useEffect(() => {
    Stripe.setOptionsAsync({
      publishableKey: "pk_test_9G7p1S7BszYU3DYMNm5I8wVT00xTBUpJ4N", // Your key
      androidPayMode: "test", // [optional] used to set wallet environment (AndroidPay)
      merchantId: "your_merchant_id", // [optional] used for payments with ApplePay
    });
  });
  const paramsCharge = {
    type: "alipay",
    amount: 5 * 300,
    currency: "USD",
    returnURL: "expaymentsstripe://stripe-redirect",
  };

  const paramsToken = {
    // mandatory
    number: "4242424242424242",
    expMonth: 6,
    expYear: 2021,
    cvc: "314",
    // optional
    name: "Test User",
    currency: "usd",
    addressLine1: "123 Test Street",
    addressLine2: "Apt. 5",
    addressCity: "Test City",
    addressState: "Test State",
    addressCountry: "Test Country",
    addressZip: "55555",
  };

  const paramsRequest = {
    requiredBillingAddressFields: "full",
    prefilledInformation: {
      billingAddress: {
        name: "Gunilla Haugeh",
        line1: "Canary Place",
        line2: "3",
        city: "Macon",
        state: "Georgia",
        country: "US",
        postalCode: "31217",
      },
    },
  };

  async function CreateToquenCard() {
    const token = await Stripe.createTokenWithCardAsync(paramsToken);
    console.log(token.tokenId);
  }

  async function PaymentRequest() {
    const token = await Stripe.paymentRequestWithCardFormAsync(paramsRequest);
    console.log(token);
  }
  async function Paymentpay() {
    const source = await Stripe.createSourceWithParamsAsync(paramsCharge);
    console.log(source);
  }

  return (
    <View style={styles.container}>
      <View style={styles.welcomeContainer}>
        <Image
          source={
            __DEV__
              ? require("./../../assets/images/robot-dev.png")
              : require("./../../assets/images/robot-prod.png")
          }
          style={styles.welcomeImage}
        />
      </View>
      <View style={{ paddingBottom: 15, paddingTop: 15 }}>
        <Button title="token" onPress={() => CreateToquenCard()}></Button>
      </View>
      <View style={{ paddingBottom: 15 }}>
        <Button title="PaymentReq" onPress={() => PaymentRequest()}></Button>
      </View>
      <View style={{ paddingBottom: 15 }}>
        <Button title="PaymentSource" onPress={() => Paymentpay()}></Button>
      </View>
    </View>
  );
}`

Sorry for my inexperience, I have been programming for a short time ... thanks ...

**Comment by LivanDiaz** [comment]
Hi @byCedric Thank you, I am very grateful that you answered ... I have been with the same error for several weeks. I am developing from Window OS. Here I show you the package.json and the screen where I use Stripe ... it's just a test screen, automatically when I jump to that screen it throws me the error. let me know if you need anything else, thanks in advance and blessings.

package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "~10.0.6",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "cocoapods": "0.0.0",
    "expo": "~37.0.3",
    "expo-asset": "~8.1.4",
    "expo-constants": "~9.0.0",
    "expo-facebook": "~8.1.0",
    "expo-font": "~8.1.0",
    "expo-payments-stripe": "~8.1.0",
    "expo-stripe-checkout": "^1.0.1",
    "expo-web-browser": "~8.2.0",
    "firebase": "7.9.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-modal": "^11.5.6",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-stripe-api": "^0.1.0",
    "react-native-web": "~0.11.7",
    "stripe": "^8.60.0",
    "stripe-client": "^1.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0",
    "jest-expo": "~37.0.0",
    "react-native-credit-card-input": "^0.4.1",
    "react-native-keyboard-spacer": "^0.4.1"
  },
  "private": true
}

this is the screem where I use Stripe
`import * as React from "react";
import { PaymentsStripe as Stripe } from "expo-payments-stripe";
import { useState, useEffect } from "react";
import {
Image,
Platform,
StyleSheet,
Text,
TouchableOpacity,
View,
Button,
} from "react-native";
import { ScrollView } from "react-native-gesture-handler";

export default function CheckOut({ route }) {
useEffect(() => {
Stripe.setOptionsAsync({
publishableKey: "pk_test_9G7p1S7BszYU3DYMNm5I8wVT00xTBUpJ4N", // Your key
androidPayMode: "test", // [optional] used to set wallet environment (AndroidPay)
merchantId: "your_merchant_id", // [optional] used for payments with ApplePay
});
});
const paramsCharge = {
type: "alipay",
amount: 5 * 300,
currency: "USD",
returnURL: "expaymentsstripe://stripe-redirect",
};

const paramsToken = {
// mandatory
number: "4242424242424242",
expMonth: 6,
expYear: 2021,
cvc: "314",
// optional
name: "Test User",
currency: "usd",
addressLine1: "123 Test Street",
addressLine2: "Apt. 5",
addressCity: "Test City",
addressState: "Test State",
addressCountry: "Test Country",
addressZip: "55555",
};

const paramsRequest = {
requiredBillingAddressFields: "full",
prefilledInformation: {
billingAddress: {
name: "Gunilla Haugeh",
line1: "Canary Place",
line2: "3",
city: "Macon",
state: "Georgia",
country: "US",
postalCode: "31217",
},
},
};

async function CreateToquenCard() {
const token = await Stripe.createTokenWithCardAsync(paramsToken);
console.log(token.tokenId);
}

async function PaymentRequest() {
const token = await Stripe.paymentRequestWithCardFormAsync(paramsRequest);
console.log(token);
}
async function Paymentpay() {
const source = await Stripe.createSourceWithParamsAsync(paramsCharge);
console.log(source);
}

return (


<Image
source={
DEV
? require("./../../assets/images/robot-dev.png")
: require("./../../assets/images/robot-prod.png")
}
style={styles.welcomeImage}
/>

<View style={{ paddingBottom: 15, paddingTop: 15 }}>
<Button title="token" onPress={() => CreateToquenCard()}>

<View style={{ paddingBottom: 15 }}>
<Button title="PaymentReq" onPress={() => PaymentRequest()}>

<View style={{ paddingBottom: 15 }}>
<Button title="PaymentSource" onPress={() => Paymentpay()}>


);
}`

Sorry for my inexperience, I have been programming for a short time ... thanks ...

**Comment by LivanDiaz** [comment]
Hi @byCedric Thank you, I am very grateful that you answered ... I have been with the same error for several weeks. I am developing from Window OS. Here I show you the package.json and the screen where I use Stripe ... it's just a test screen, automatically when I jump to that screen it throws me the error. let me know if you need anything else, thanks in advance and blessings.

package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "~10.0.6",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "cocoapods": "0.0.0",
    "expo": "~37.0.3",
    "expo-asset": "~8.1.4",
    "expo-constants": "~9.0.0",
    "expo-facebook": "~8.1.0",
    "expo-font": "~8.1.0",
    "expo-payments-stripe": "~8.1.0",
    "expo-stripe-checkout": "^1.0.1",
    "expo-web-browser": "~8.2.0",
    "firebase": "7.9.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-modal": "^11.5.6",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-stripe-api": "^0.1.0",
    "react-native-web": "~0.11.7",
    "stripe": "^8.60.0",
    "stripe-client": "^1.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0",
    "jest-expo": "~37.0.0",
    "react-native-credit-card-input": "^0.4.1",
    "react-native-keyboard-spacer": "^0.4.1"
  },
  "private": true
}

this is the screem where I use Stripe
`import * as React from "react";
import { PaymentsStripe as Stripe } from "expo-payments-stripe";
import { useState, useEffect } from "react";
import {
Image,
Platform,
StyleSheet,
Text,
TouchableOpacity,
View,
Button,
} from "react-native";
import { ScrollView } from "react-native-gesture-handler";

export default function CheckOut({ route }) {
useEffect(() => {
Stripe.setOptionsAsync({
publishableKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX", // Your key
androidPayMode: "test", // [optional] used to set wallet environment (AndroidPay)
merchantId: "your_merchant_id", // [optional] used for payments with ApplePay
});
});
const paramsCharge = {
type: "alipay",
amount: 5 * 300,
currency: "USD",
returnURL: "expaymentsstripe://stripe-redirect",
};

const paramsToken = {
// mandatory
number: "4242424242424242",
expMonth: 6,
expYear: 2021,
cvc: "314",
// optional
name: "Test User",
currency: "usd",
addressLine1: "123 Test Street",
addressLine2: "Apt. 5",
addressCity: "Test City",
addressState: "Test State",
addressCountry: "Test Country",
addressZip: "55555",
};

const paramsRequest = {
requiredBillingAddressFields: "full",
prefilledInformation: {
billingAddress: {
name: "Gunilla Haugeh",
line1: "Canary Place",
line2: "3",
city: "Macon",
state: "Georgia",
country: "US",
postalCode: "31217",
},
},
};

async function CreateToquenCard() {
const token = await Stripe.createTokenWithCardAsync(paramsToken);
console.log(token.tokenId);
}

async function PaymentRequest() {
const token = await Stripe.paymentRequestWithCardFormAsync(paramsRequest);
console.log(token);
}
async function Paymentpay() {
const source = await Stripe.createSourceWithParamsAsync(paramsCharge);
console.log(source);
}

return (


<Image
source={
DEV
? require("./../../assets/images/robot-dev.png")
: require("./../../assets/images/robot-prod.png")
}
style={styles.welcomeImage}
/>

<View style={{ paddingBottom: 15, paddingTop: 15 }}>
<Button title="token" onPress={() => CreateToquenCard()}>

<View style={{ paddingBottom: 15 }}>
<Button title="PaymentReq" onPress={() => PaymentRequest()}>

<View style={{ paddingBottom: 15 }}>
<Button title="PaymentSource" onPress={() => Paymentpay()}>


);
}`

Sorry for my inexperience, I have been programming for a short time ... thanks ...

**Comment by byCedric** [comment]
Ah, this is my bad! I assumed you were using the bare workflow. But it looks like you use the managed workflow. If you are not sure what the differences are, [here is a small guide](https://docs.expo.io/introduction/managed-vs-bare/#workflow-comparison). So, we have two main things here.

1. **The [Expo Stripe payments module is not supported in the managed flow, on iOS](https://docs.expo.io/versions/latest/sdk/payments/#compatibility)**
The Apple store requires additional configuration and meta-info for your app. We can't fully cover that (yet) in the managed flow.

2. **If you eject to the bare workflow, you have to use xcode to build your iOS app**
You can [either setup a VM to run xcode/macos from that](https://stackoverflow.com/a/40587509), or build your IPAs using a CI (like [github actions](https://blog.usejournal.com/automate-react-native-builds-with-github-actions-af54212d26dc))

I would recommend to do 2 with a CI, that way you don't have to mess around with a VM. Hope this helps more! 😄

**Comment by LivanDiaz** [comment]
@byCedric hi ... mount a macOS virtual machine on my windows pc to run the command (npx pod-install) as you suggested and create a little project in just to see if it works. But the problem persists ... here I share ... the truth is that I am going to thank you very much ...
package.json:
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "expo": "~38.0.9",
    "expo-payments-stripe": "~8.2.1",
    "expo-splash-screen": "^0.5.0",
    "expo-status-bar": "^1.0.0",
    "expo-updates": "~0.2.10",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "^0.10.1",
    "react-native-web": "~0.11.7",
    "tipsi-stripe": "^8.0.0-beta.10"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

Podfile:
platform :ios, '10.0'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!(versions = {})
  versions['Flipper'] ||= '~> 0.33.1'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.1'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.0'

  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'

  # List all transitive dependencies for FlipperKit pods
  # to avoid them being linked in Release builds
  pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
  pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'pruebaUnoo' do
  pod 'Stripe', '~> 19.0.1'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
 

  # Install additional dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
  #Pods for pruebaUnoo
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!
  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

**Comment by chaohuichen** [comment]
@LivanDiaz  hi, I am getting the same error as well on expo39 and  expo-payments-stripe: "~8.3.0". I am wondering did you find a solution for it or eject expo using bare react native?

**Comment by lucascooelho** [comment]
I'm facing the same issue... I still looking for a solution.

**Comment by chaohuichen** [comment]
> I'm facing the same issue... I still looking for a solution.

I think the only solution right now is to eject the expo and use bare workflow to manage the stripe integration.

**Comment by lucascooelho** [comment]
> > I'm facing the same issue... I still looking for a solution.
> 
> I think the only solution right now is to eject the expo and use bare workflow to manage the stripe integration.

Did it work for you when you used bare workflow?

**Comment by chaohuichen** [comment]
> > > I'm facing the same issue... I still looking for a solution.
> > 
> > 
> > I think the only solution right now is to eject the expo and use bare workflow to manage the stripe integration.
> 
> Did it work for you when you used bare workflow?

Yes, it works for me by using bare workflow, and I swap using https://github.com/tipsi/tipsi-stripe instead of the expo stripe.

**Comment by LivanDiaz** [comment]
@chaohuichen, @lucascooelho ... i eject expo using bare react native ... and it work for me, I was developing from Window ... and it still didn't work until I mounted a mac virtual machine, created a small test project and got it up from Xcode and it worked perfectly fine.
