### ISSUE TITLE
[docs] expo-yarn-workspaces missing @expo/vector-icons assets

### ISSUE THREAD

**Issue by peter-jozsa** [expo/expo#9773]
I created an app based on the "tabs" template in a monorepo (yarn workspaces). I followed the instructions I found in the README.md of `expo-yarn-workspaces` package to make sure everything is working. I use my own servers to build and host ios and android bundles of this application via `turtle-cli` package and `expo export`. Everything was working as expected and I managed to build Ad-Hoc distributable .ipa files of the app. I installed the .ipa file on a physical device and realised icons imported from @expo/vector-icons are missing, see screenshot below. After hours of trying to fix this issue I realised my ios-index.json contained only one .ttf file under `bundledAssets` field (which was the `SpaceMono-Regular.ttf` found in `assets/fonts` folder). After some hours of investigation I found out that the default and recommended `assetBundlePatterns` value (`**/*`) in app config file (app.json) causes the issue.

My folder structure is the following:
```
|- my-monorepo
   |- node_modules
       |- @expo
          |- vector-icons
   |- packages
      |- my-expo-app
         |- app.json
```

I run `expo export` in `my-monorepo/packages/my-expo-app` folder. The problem is that `@expo/vector-icons` resolves to `my-monorepo/node_modules/@expo/vector-icons` during bundling but the `assetBundlePatterns` is evaluated relative to cwd (`my-monorepo/packages/my-expo-app`) so assets in vector-icons package filtered out and not exported.

**I managed to fix this issue by using `../../**/*` as `assetBundlePatterns ` in my app config file.** This way `.ttf` files of vector-icons are exported and the icons appeared after installing the generated .ipa file.

I did not check if this issue also occurs when using expo's servers to build and host the app.
I think this fix should be added to the docs of expo-yarn-workspaces in order to save others from this headache or maybe a fix could be implemented in the bundler.

I hope I could help those who found this issue. ;)

![IMG_4EAB605CEC83-1](https://user-images.githubusercontent.com/6742328/90321123-1a970b80-df47-11ea-9963-75a9a3a55a6e.jpeg)

**Comment by conor909** [comment]
I have this issue with the [Solito Starter Monorepo](https://solito.dev/starter) setup
