### ISSUE TITLE
[Audio] sound.playAsync results in "AudioTrack init failed" after couple of successful tries

### ISSUE THREAD

**Issue by maheraldous** [expo/expo#9774]
## 🐛 Bug Report
Look to this snack https://snack.expo.io/@lukis/audio-issues

No matter how much I tried it's keep fail.

The problem happen when you press the sound to play continually like for example if you bulid a game and want to play a sound continually when firing the gun then it's work but after a while it fail and the sound will go.

I hope you can create a snack demo to show us how to use this https://docs.expo.io/versions/latest/sdk/av/ in the right way where no matter how many time you play or press the button to play it won't crash.

**Comment by IjzerenHein** [comment]
Hi! I think this is because the system is running out of resources. For every sound that you load, you also need to unload using `unloadAsync` it after it has completed playing to free its allocated resources.

https://docs.expo.io/versions/latest/sdk/audio/#example

**Comment by gstcyr** [comment]
> Hi @IjzerenHein here is the code after the update with your tips
> 
> ```
>   play(source) {
>     // console.log(source);
>     const sound = new Audio.Sound();
>     const play_sound = (async () => {
>       await sound.loadAsync(source); //Error Here
>       await sound.playAsync();
> 
>       await sound.unloadAsync(); // with this the song dose not even work
>     })();
>   }
> ```
> 
> The sound dose not work when I add what you told.

I know this is old, but you need to call unloadAsync in the playbackStatusUpdate function
