### ISSUE TITLE
Expo Push Notification not working after Android Build

### ISSUE THREAD

**Issue by YuntongLi6543** [expo/expo#9775]
### Summary of Issue 
Hello, I have a problem that, after I build android, the push notification of Expo (legacy) is not working, but it works fine on expo app. I use EXPO 38.

**Comment by byCedric** [comment]
Hi @YuntongLi6543, thanks for writing in. Did you follow the steps listed under "[Setting up FCM](https://docs.expo.io/push-notifications/using-fcm/)"? If not, could you share an example where this is happening for you?

**Comment by YuntongLi6543** [comment]
> 
> 
> Hi @YuntongLi6543, thanks for writing in. Did you follow the steps listed under "[Setting up FCM](https://docs.expo.io/push-notifications/using-fcm/)"? If not, could you share an example where this is happening for you?

Ok, I miss this FCM setup step. Now I have push notification working in android standalone APP! Thanks for your reply!

**Comment by yxy-smile** [comment]
Now I have a problem that when I follow the steps listed under "Setting up FCM", then I run the command "expo build :android", The build log shows that "Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]  registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)".   Can you help me ?
