### ISSUE TITLE
Azure Pipelines CI/CD - App Release Notes Location

### ISSUE THREAD

**Issue by rrdesignweb** [expo/expo#9776]
Hi there, I am not sure if this is the best place to post this question but here it goes:

 I have setup a CI azure-pipelines.yml script to build my .apk file with turtle-cli etc.

I also have a release going out to Google Play Store using the **google-play-vsts-extension**  

I am trying to figure out how to add the app release notes file i.e where to add this file in my expo file structure / how it gets bundled with the apk and if I add it as a build step and how to reference it?

Azure Pipelines google-play-vsts-extension
<img width="1018" alt="Screen Shot 2020-08-16 at 1 17 40 pm" src="https://user-images.githubusercontent.com/4110276/90325754-f7aa3d00-dfc2-11ea-8147-2469c43d9b8d.png">

Expo File Structure:
<img width="222" alt="Screen Shot 2020-08-16 at 1 25 23 pm" src="https://user-images.githubusercontent.com/4110276/90325832-0513f700-dfc4-11ea-92ab-cbe8bf08100e.png">

If anyone can point me in the right direction that would be great

**Comment by byCedric** [comment]
Hi @rrdesignweb, we don't bundle the release notes in the APK. This is something you have to supply manually I'm afraid. There are [tools to help generate a changelog](https://github.com/conventional-changelog/conventional-changelog), which could help in this process. But you still need to generate that text file and upload it to Azure somehow.

As an alternative, you also might want to check out the `$ expo upload:*` commands, e.g. `$ expo upload:android --help`. It can help uploading the APK to the artifact store. After that, you only have to create a release and provide the "What's new in this version" or release notes.

Hope it helps!
