### ISSUE TITLE
ImagePicker with `allowEditing: true` doesn't return expected results for Images on Android

### ISSUE THREAD

**Issue by haciSeydaoglu** [expo/expo#978]
As I said in the title, there is an error in the image picker. No photo selected.
Thanks for everything.

edit: When I make allowEditing false, it is improving.

**Comment by newfylox** [comment]
As **haciSeydaoglu** mentioned it, result URI seems to be broken when using `allowEditing: true` with SDK 23. I did an upgrade today from 22 to 23 and the error appeared after that. I only tried it on Android, don't know about iOS.

Everytime I want to load/show an image with the `result.uri` (e.g. \<Image />) it only works with `allowEditing: false`

**Comment by aalices** [comment]
This will be probably fixed along with a minor release this week. Sorry for the inconvenience!

**Comment by newfylox** [comment]
Thank you :)

**Comment by kadoshms** [comment]
Is there an ETA for this issue? :)

**Comment by gilbertKaradja** [comment]
Hi. I have the same issue with expo v 32.0.0. If i specify allowEditing and select a file nothing happens
