### ISSUE TITLE
Asyncstorage doesn't work in react-native-web

### ISSUE THREAD

**Issue by barnu5** [expo/expo#9780]
### Summary of Issue 
First time building managed project for web. I get error:

`Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage'`

I'm using SDK 38, which I understood fixed this issue?

Is AsyncStorage supported?

Thanks!

**Comment by EvanBacon** [comment]
Ensure you're using `react-native-web@0.11`. Expo SDK 39 will use `react-native-web@0.13`
