### ISSUE TITLE
Patch release for TextInput bug in React Native 0.62.x in managed workflow

### ISSUE THREAD

**Issue by sebasthuis** [expo/expo#9786]
# Context

The `TextInput` component in React Native has a bug when the input text is styled in conjunction with Japanese or Chinese characters on iOS. The font styling switches between the default styling and the applied styling after every change in the TextInput field. See issues [here](https://github.com/facebook/react-native/issues/29363) and [here](https://github.com/facebook/react-native/issues/29363). 

This bug is fixed in [React Native 0.63.1](https://github.com/facebook/react-native/pull/28805), but expo 38 uses React Native 0.62.2 therefore our app still contains this bug.

# Question

Is there any possibility of doing a patch release of expo to get this issue fixed?

**Comment by cruzach** [comment]
Hi @sebasthuis , we won't do a patch release to upgrade SDK 38 to RN 63, but the next SDK release (39) will be on RN 63
