### ISSUE TITLE
npm i, invalid tar file

### ISSUE THREAD

**Issue by skyride99** [expo/expo#979]
I get his error when running npm i, or Yarn. For any version of exp sdk

npm ERR! tar.unpack untar error /var/folders/mw/n9g6rylx38vdw9d9qxt39pl40000gn/T/npm-82848-2cf93922/github.com/exponent/react-native/archive/sdk-17.0.0.tar.gz

npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! invalid tar file

**Comment by EvanBacon** [comment]
A few general things you can try:
* $ npm cache clean
* $ bower cache clean
* $ node -v
  * Make sure node is v8+ https://github.com/creationix/nvm

**Comment by skyride99** [comment]
watchman watch-del-all
npm cache clean
rm -fr $TMPDIR/react-*
npm start -- --reset-cache

and delete node_modules 
node i 

works however I am using 
Node 6.11.2
NVM 3.10.10
and now expo 17 but probably need to upgrade everything
