### ISSUE TITLE
[face-detector] Firebase SDK hard set to 6.14.0

### ISSUE THREAD

**Issue by KDederichs** [expo/expo#9791]
### Summary of Issue 

The Firebase SDK in the Face-Detector module seems to be hard set to 6.14.0 making it hard to work with in bare-projects if you want to use a newer version of Firebase.
It would be better to set more loose constraints in the podspec to allow newer versions, providing there's no BC

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.24.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.24.0
```
Only iOS bare-workflow is affected by this
### Steps to Reproduce

1. Initialise a bare project
2. Add firebase to it (as of writing 6.28.1)
3. Install Pods
4. Add expo-face-detect
5. Install Pods
6. -> Dependency conflict

### Expected Behavior vs Actual Behavior

I'd expect it to work with newer versions of Firebase but instead there's a conflict in dependencies.

**Comment by IjzerenHein** [comment]
Hi! Hi! You can just update the `$FirebaseSDKVersion` version in your podfile. This will cause the expo firebase packages to use this version as well. https://github.com/expo/expo/blob/master/packages/expo-face-detector/ios/EXFaceDetector.podspec

**react-native-firebase docs on updating the firebase native sdk version**
https://rnfirebase.io/#ios

EDIT: link on rnfirebase doesn't seem to work properly, here is the part of the docs

Open your projects /ios/Podfile and add any of the globals shown below to the top of the file:

```
# Override Firebase SDK Version
$FirebaseSDKVersion = '6.28.1'
```

**Comment by IjzerenHein** [comment]
Closing this issue as the answer has been provided
