### ISSUE TITLE
Performance difference between development and production

### ISSUE THREAD

**Issue by clems36** [expo/expo#9793]
## 🐛 Bug Report

After upgrading to SDK 38 (from SDK 35), the performance of one specific function has decreased **a lot**.
What bugs me about this issue is that the performance is fine in dev mode, but is very low in production mode.

### Environment

The issue occurs for both iOS and Android.

```
Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^4.0.10 => 4.4.0
```

### Reproducible Demo

I unfortunately can't provide a reproducible demo for this one as it's hard for me to turn my project into a MCVE.
 
### Steps to Reproduce

Consider the following, where the 4 json files are a little over 200 KB each:
```js
const en = require('@assets/translations/en.json');
const fr = require('@assets/translations/fr.json');
const nl = require('@assets/translations/nl.json');
const de = require('@assets/translations/de.json');

const translate = (key: string, formattingVars?: any) => {
  const currentLanguage = selectCurrentLanguage(store.getState());
  let word = `#${key || ''}`;

  switch (currentLanguage) {
    case 'en':
      word = en[key]; // This makes the function slow to execute
      break;
    case 'fr':
      word = fr[key];
      break;
    case 'nl':
      word = nl[key];
      break;
    case 'de':
      word = de[key];
      break;
    default:
      word = en[key];
      break;
  }

  return word;
};
```

The `translate` function is extremely slow to execute (only in production!). Now if I just remove the whole `switch` part where it accesses the key in the json file and return a simple string instead, it works fine (as expected).

It is worth mentioning that this function is called for each word displayed in the app (**a lot**) so it makes the app currently unusable.

### Expected Behavior vs Actual Behavior

I would expect the production build to run at the same pace (or even faster!) than the dev build.
Why would it be slow to access keys in a json file? And why only in production?

As mentioned above, I did not have this issue in SDK 35 and this piece of code has not changed during the process of the SDK upgrade.

**Comment by byCedric** [comment]
Hi @clems36, thanks for writing in. I'm not exactly sure what's happening here. [I tried reproducing this using a benchmark that generates an array using a data-object lookup](https://github.com/byCedric/expo-issue-9793/blob/master/App.tsx). You can see the results below, I ran the benchmark 3x and took the average. There shouldn't be any performance issue on either development or production mode.

benchmark | development | production 
--- | --- | ---
100.000 | `53ms` | `55.6ms`
1.000.000 | `251.3ms` | `227ms`
10.000.000 | `2109.3ms` | `2068ms`
100.000.000 | _out of memory_ | _out of memory_

If you think this is still an issue on our side, please provide a small example for us to investigate.

Hope this helps!

**Comment by clems36** [comment]
Thanks for taking the time @byCedric. I wasn't sure where to open the issue but since it appeared after an SDK update I thought I'd open it here, but maybe I was wrong to do so. 
Anyway i've managed to work around the issue by calling the function less.
Cheers!
