### ISSUE TITLE
[expo-av] [iOS 14 beta 4] White screen when video is loaded with required

### ISSUE THREAD

**Issue by pckz** [expo/expo#9798]
## 🐛 Bug Report

Video not loaded using require, in iOS 14 beta 4
### Summary of Issue 

I been using expo in an App in production (iOS and Android) for one year and 6 months, with a video background in the Home Screen. Now, testing the new iOS 14 beta 2-3 and 4 (will be release in September 18th), the video, loaded with the expo library, are not displayed. I tested with Expo SDK 34 and 31

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo 34
iOS 14 beta 4

### Reproducible Demo

(video is in the background)

![IMG_6EABF5A8F628-1](https://user-images.githubusercontent.com/1050628/90449916-6a481500-e0b6-11ea-9bfb-e1a1746ec0a4.jpeg)

 
### Steps to Reproduce

 ```
<Video
            source={ require('../assets/videos/background.mp4') }
            shouldPlay
            isLooping
            resizeMode="cover"
            /* style [...] */
          />
```
path is OK

I tested using `{ uri: 'http://link/to/video.mp4' } ` and it works, but I can't implement as an option.

Also I tried using reference (as issue https://github.com/expo/expo/issues/7339) but did not work.

Thanks!

**Comment by cruzach** [comment]
@pckz thanks for the report! Could you try this on a more recent SDK, like SDK 38, just to check if there's any difference?

**Comment by cruzach** [comment]
we're keeping track of this in https://github.com/expo/expo/issues/9931
