### ISSUE TITLE
Push Notification Icon Is Not Working in iOS

### ISSUE THREAD

**Issue by ChenLi0830** [expo/expo#98]
When sending push notifications, the Expo's icon and app name were shown in iOS. Android doesn't seem to suffer from this problem. Is there something else that is required to have the push notification correctly configured in iOS?

Here is the notification part in the exp.json file

````
  "notification": {
    "icon": "./public/images/nomii-rewards-app-icon_192.png",
    "color": "#e8314a",
    "androidMode": "collapse",
    "androidCollapsedTitle": "Your cards will expire soon"
  },
````

![img_1116](https://cloud.githubusercontent.com/assets/9557418/24529780/81d4e306-1562-11e7-9df3-6c6a57cf9855.PNG)

**Comment by ide** [comment]
The custom notification icon is supported only on Android (this is just how iOS works). When you create a standalone app with `exp build:ios`, the notifications will use your home screen icon.

**Comment by ChenLi0830** [comment]
@ide Hey James, thanks for the quick reply!
