### ISSUE TITLE
Beep when starting record video

### ISSUE THREAD

**Issue by lucianoacsilva** [expo/expo#9800]
Hello,

When using**expo-camera**, it makes a loud beep when user starts recording a video. Is it possible to remove this beep?

**Comment by brentvatne** [comment]
hi there! please fill out the issue template.

<hr />

## 🐛 Bug Report

### Summary of Issue 


### Environment - output of `expo diagnostics` & the platform(s) you're targeting


### Reproducible Demo



 
### Steps to Reproduce


### Expected Behavior vs Actual Behavior

**Comment by lucianoacsilva** [comment]
Hi, there! Does a question needs a reproducible demo?

**Comment by EvanBacon** [comment]
Maybe you can avoid it by using the Camera2 API but no way of knowing without any information about the platform or OS.
