### ISSUE TITLE
 🐛 Bug Report: BackgroundFetch runs ok on Android, but never runs on iOS.

### ISSUE THREAD

**Issue by imwilliamxy** [expo/expo#9801]
## 🐛 Bug Report
BackgroundFetch runs ok on Android, but NEVER runs on iOS.
### Summary of Issue 
I have create a app for test BackgroundFetch api. It runs well on Android device with expo client.
But never runs on iOS. Of cause, the custom version Expo client is  compiled & installed .
Background task still NEVER run on iOS device.

### Environment
Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v12.18.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.3

### Reproducible Demo
Source cofe: https://github.com/imwilliamxy/test-expo-background-fetch-task

 
### Steps to Reproduce
Use git clone get the source code, install packages with `npm install` or `yarn install`, then run `expo r -c --lan` to run the app.

### Expected Behavior vs Actual Behavior
Expected Behavior : background tasks runs ok on iOS
Actual Behavior: background tasks NEVER runs on iOS

**Comment by byCedric** [comment]
Hi @imwilliamxy! Thanks for writing in and providing a repro, that helps us a lot 😄  I see that you didn't configure the proper Plist fields in your `app.json` manifest. [You can read here what you need to configure to set up your app for background tasks on iOS.](https://docs.expo.io/versions/latest/sdk/task-manager/).

I think it's a bit hidden, so I'll make a PR to mention this as well on the `BackgroundFetch` docs.

Hope this helps!

**Comment by srikanthkh** [comment]
@imwilliamxy Did you manage to fix this issue? I have been trying for days to figure this out.. having the same issue.

**Comment by mogery** [comment]
Same issue here. Any solutions known?
