### ISSUE TITLE
Bare workflow not reading AndroidManifest.xml permissions

### ISSUE THREAD

**Issue by mag1cDev** [expo/expo#9802]
Hello,

I’m building an android app that uses InAppPurchases. I built it on expo and then ejected to bare workflow.

I have already added the required permission to the AndroidManifest.xml (`<uses-permission android:name="com.android.vending.BILLING" />`).

However, when I compile my app bundle in visual studio using “expo build:android”, the Playstore will then give me an error when I upload the app and try to configure the purchases, saying “you need to add the BILLING permission to your APK”.

This tells me the compiler is only taking into account the permissions specified in app.json but I can’t add the billing permission to app.json because it’s not supported.

I have tried to compile my bundle via the android studio compiler and that does fix the permissions issue on the Playstore but I then get other compilation errors that I don’t get with the “expo build:android” compilation method, including one annoying error “cannot find symbol return BuildConfig.DEBUG;” on the MainAppilcation.java file. I looked everywhere and tried everything but this error seems to be unfixable.

So to recap:

- If I build my android app bundle via “expo build:android”, I get no errors but Playstore doesn’t read the IAP permission on the AndroidManifest.xml.
- If, on the other hand, I build my bundle via Generate Signed Bundle on the Android Studio, Playstore does read the (billing) permissions from the AndroidManifest.xml but my app won’t work because of the BuildConfig error.

My question is, is there a way to add the billing permissions to app.json or make sure the expo build takes into account the permissions on AndroidManifest.xml?

This is my AndroidManifest.xml code:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="com.myapp.app1">
  <uses-permission android:name="com.android.vending.BILLING" />
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"  />
  <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" tools:node="remove" />
  <uses-permission android:name="android.permission.READ_PHONE_STATE"  />
  <uses-permission android:name="android.permission.USE_FINGERPRINT"  />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" tools:node="remove"  />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" tools:node="remove"  />
  <uses-permission android:name="android.permission.CAMERA"  tools:node="remove" />
  <uses-permission android:name="android.permission.READ_CONTACTS" tools:node="remove" />
  <uses-permission android:name="android.permission.READ_CALENDAR"  />
  <uses-permission android:name="android.permission.WRITE_CALENDAR"   />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"  />
  <uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove"  />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"  />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"  />
  <uses-permission android:name="android.permission.WAKE_LOCK"  />
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">
    <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://exp.host/@mag1cp0t/app1" />
    <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="38.0.0" />
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="true"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
    <meta-data android:name="expo.modules.updates.EXPO_RELEASE_CHANNEL" android:value="default" />

  <activity
    android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"/>
  </application>
</manifest>
```

**Comment by barthap** [comment]
`expo build:android` is part of managed workflow and takes permissions from `app.json`. It has nothing to do with `AndroidManifest.xml` which is part of bare workflow.

The error you mentioned _“cannot find symbol return `BuildConfig.DEBUG`;”_  means that something gone wrong with gradle build. The file `BuildConfig.java` should be generated automatically under `android/app/build/generated/source/...`

**Comment by byCedric** [comment]
Hi @mag1cDev! Like @barthap mentioned, there are two development flows with Expo. Managed and bare, currently we do not support building bare projects through `expo build:*`. We do support OTA updates, through `expo publish` but you have to build the APK/AAB (Android) and IPA (iOS) standalone apps yourself. You can see a [quick walkthrough of that here](https://docs.expo.io/bare/exploring-bare-workflow/#build-and-open-the-project).

I would suggest trying the following commands. If one of these is failing, something is up with your project and that should be addressed first.

- `yarn android` - builds APK in dev mode
- `yarn android --variant Release` - builds APK in production mode

Hope this helps!
