### ISSUE TITLE
iOS: No OTA on SDK 38

### ISSUE THREAD

**Issue by clems36** [expo/expo#9812]
## 🐛 Bug Report

Over The Air updates are being downloaded on Android but not on iOS for the same build and release-channel.
This issue appeared after upgrading to SDK 38.

Both `android/app/src/main/assets/shell-app-manifest.json` and `ios/myApp/Supporting/shell-app-manifest.json` contain the same release-channel related fields:
```
"releaseChannel":"prod-63-expo-38"
"hostUri":"exp.host/@myApp/myApp?release-channel=prod-63-expo-38"
```
Both apps on respective OS's also have the same build number and version number.

`app.json` contains the following:
```
"updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    },
```

Overall no code change has been made regarding OTA's on my side.

=> It might be worth mentioning that I can't access the developer menu from iOS neither (Android works fine). Could these two issues be related ?

### Environment

```
Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^4.0.10 => 4.4.0
```

**Comment by clems36** [comment]
@byCedric if you need any additional info like the `bundleIdentifier` or anything else related to the app, i'll be happy to provide them.

**Comment by byCedric** [comment]
Hi @clems36, no I think I might know what's going on here. So it looks like you are using a bare or ejected project, right? The upgrade might have changed your native config related to OTA. Could you double-check if everything is configured properly in the iOS native code? You can see the [config docs here](https://github.com/expo/expo/tree/master/packages/expo-updates#configuration).

As a side note, after ejecting I think you have to manually update your native code settings for this. Changing it in the manifest isn't actually changing it in Android or iOS builds.

Hope it helps! If not, let me know 😄

**Comment by clems36** [comment]
@byCedric thank you for your answer. The problem is that my project is still using ExpoKit, and `expo-updates` is not compatible with ExpoKit. I know ExpoKit has been deprecated and should be removed asap, but I'm short on time (like, really short on time) for doing this right now, my plan is to do so during the next SDK update.

That being said, I still have access to the `Updates` library from the `expo` package. 
Could you point me in a similar direction than the docs you've linked, but for my configuration ? Surely there must be a way to bring back OTA's (maybe adding something to `AppDelegate.m`?).

I'd really be grateful 🙏

**Comment by clems36** [comment]
Hi @byCedric, any idea ?
