### ISSUE TITLE
react native npm start loads webpack instead of metro bundler 

### ISSUE THREAD

**Issue by Chibuzor44** [expo/expo#9824]
## 🐛 Bug Report

I started a new react native project with Expo, everything worked fine until I installed a few packages. Instead of opening a metro bundler to allow running on ios or android expo simulator as a native app, it is opening a webpack with localhost to run on the browser. How can I reverse this process to running on the expo simulator? I tried deleting and starting a new project but it keeps happening.

#### This is what I am getting:
INFO
19:14 web  Starting Webpack on port 19006 in development mode.

#### Instead of
INFO
19:21 Starting Metro Bundler.

This means I am going to end up with a web app instead of a native app.

**Comment by brentvatne** [comment]
if you press `w` it will open web, if you press `i` (ios) or `a` (android) it will open on one of those platforms. `expo start` starts webpack for web and metro for ios/android

**Comment by Chibuzor44** [comment]
Yes. But when you press `i` it opens on the simulator Safari browser instead of the expo app. The expected behavior is for it to open as a native app in the expo app installed in the simulator.

#### This is what I get:
<img width="297" alt="Screen Shot 2020-08-18 at 7 25 23 PM" src="https://user-images.githubusercontent.com/34400221/90652129-6a096000-e203-11ea-8f06-c10e1761176d.png">



#### This is what is expected:
<img width="298" alt="Screen Shot 2020-08-18 at 7 25 03 PM" src="https://user-images.githubusercontent.com/34400221/90652270-7db4c680-e203-11ea-95a4-158d42cdced9.png">

**Comment by mnearents** [comment]
I have the same problem. Pressing i opens in safari on the simulator. In Metro Bundler it says "Starting Webpack on port 19006 in development mode." Instead of "Starting Metro Bundler on port 19006."

**Comment by mnearents** [comment]
This fixed it for me: https://stackoverflow.com/a/63039216/1391672
Delete all metro modules from node_modules and run `npm install`
