### ISSUE TITLE
The expo package adds versionCode and the program crashes

### ISSUE THREAD

**Issue by AKclown** [expo/expo#9826]
question：
     When I packaged the program, it was perfect without adding versionCode，But I added the versionCode program and it crashed

environment：
          "expo": "^38.0.0",
          "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",

code：
   "android": {
            "package": "com.maintank.rwa2",
            "permissions": [],    
            "versionCode": 1    
        },
How to deal with it ，thanks

**Comment by brentvatne** [comment]
hi! we need a reproducible example to help with this. please create a new issue and provide an example that we can run to demonstrate the issue. this is likely a bug in your own code and trying to provide a minimal reproducible example will help you to locate that bug! if you can reproduce it then it'll help us to investigate! more guidance on how to do this if you need it: https://stackoverflow.com/help/minimal-reproducible-example
