### ISSUE TITLE
SecureStore.getItemAsync returning wrong value

### ISSUE THREAD

**Issue by dervondenbergen** [expo/expo#983]
There is an error with the docs for [SecureStore](https://docs.expo.io/versions/latest/sdk/securestore.html)

They say that `SecureStore.getItemAsync` returns `null` if nothing is set but in reality it returns `undefined`.

I have here a test Snack, where you can see the output in the console: https://snack.expo.io/@dervondenbergen/securestore.getitemasync-error

**Comment by dalaniz** [comment]
seems to be fixed. I've tryed in xde latest version

**Comment by ide** [comment]
Can you please clarify which OS you're seeing this on?

**Comment by dalaniz** [comment]
I revisited the snack demo and modifying  some lines to render the results, I can see differences between iOS (undefined) and Android (null)
