### ISSUE TITLE
Android: Missing advertisingId in expo-analytics-segment

### ISSUE THREAD

**Issue by dasovm** [expo/expo#9835]
### Summary of Issue 
Since upgrading Expo SDK from 36 to 38 (and therefore upgraded the `expo-analytics-segment` package from ~8.0.0 to ~8.2.1), the properties `context.device.advertisingId` and `context.device.adTrackingEnabled` are missing on Android while they still are included on iOS.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```
```
"expo-analytics-segment": "~8.2.1"
```
### Reproducible Demo
See steps to reproduce below.

### Steps to Reproduce
1. `expo init`, use blank template
2. `expo install expo-analytics-segment`
3.  Replace App.js with the following code:
```js
import * as Segment from "expo-analytics-segment";
import { StatusBar } from "expo-status-bar";
import React, { useEffect } from "react";
import { StyleSheet, Text, View } from "react-native";

export default function App() {
  useEffect(() => {
    Segment.initialize({
      iosWriteKey: "SEGMENT_IOS_WRITE_KEY",
      androidWriteKey: "SEGMENT_ANDROID_WRITE_KEY",
    });

    Segment.track("SEGMENT:TEST");
  }, []);

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

```
4. `yarn start`
5. Visit [Segment debugger](https://segment.com/docs/connections/sources/debugger/) for both Android- and iOS-source.

### Expected Behavior vs Actual Behavior
Expected Behavior: `context.device.advertisingId` and `context.device.adTrackingEnabled` should be included on both iOS and Android.
Actual Behavior: `context.device.advertisingId` and `context.device.adTrackingEnabled` are missing on Android while they are present on iOS.

**Comment by rvieceli** [comment]
We are trying to setup Segment to send analytics to Facebook and we get the same issue.
For IOS I can see the `adTrackingEnabled` and `advertisingId` in device data, but is missing for Android.

I tried with a standalone app, and get the same problem. 

Expo SDK 38 with expo-analytics-segment = "~8.2.1".

Is anything missing in the documentation, any new permission to add?

**Comment by rvieceli** [comment]
@cruzach Was missing anything in the configuration to get  `advertisingId` in Android? We have facebook package and for iOS I can see `automatic logging app events` in Facebook analytics, but Android don't send anything.

**Comment by cruzach** [comment]
I've reproduced this in the managed workflow, it's working fine in the bare workflow. Accessing the advertisingId requires the Play Services Ads library to be imported, so maybe we are excluding that somehow as of SDK 37 or 38?

**Comment by joshuarize** [comment]
I noticed that the `advertisingId` is not present when in development mode (using the Simulator or Expo app). In the docs, it does say:

> Note: Session tracking may not work correctly when running Experiences in the main Expo app. It will work correctly if you create a standalone app.

I'm curious if you guys are running the app as a standalone build or are you detached or not detached?

**Comment by dasovm** [comment]
@joshuarize we've tested this in both development mode and in the production build. The `advertisingId` is not present in any of the cases.

**Comment by dasovm** [comment]
@aarshaw No, unfortunately we didn't figure out any solution to this, except ejecting to bare workflow which seemed to work for @cruzach.

**Comment by cruzach** [comment]
FYI Segment has recently released a brand new react native library that is Expo-compatible, and it is likely that we will deprecate `expo-analytics-segment` in favor of their new library. 

I recommend trying out this new library if you're looking for the best Segment experience: https://github.com/segmentio/analytics-react-native/blob/master/README.md
