### ISSUE TITLE
Expo client crashes with error t.preventAutoHide

### ISSUE THREAD

**Issue by jzarca01** [expo/expo#9836]
### Summary of Issue 

Cannot open Expo Client either from a project or just from iOS simulator (without a specific project)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.13.1/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.24.2

### Reproducible Demo

There was a problem running expo
Unhandled JS Exception: TypeError: null is not an object (evaluating _t.preventAutoHide)
 
### Steps to Reproduce

expo init testProject
yarn start
open project in iOS simulator (iPhone 11 13.4.1)

### Expected Behavior vs Actual Behavior

I should be able open the app and retrieve a list of my projects

**Comment by kurniawanw0194** [comment]
I got the same issue.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-20 at 15 50 36](https://user-images.githubusercontent.com/26651920/90721834-f77cab00-e2fc-11ea-9f2d-555214577217.png)

**Comment by brentvatne** [comment]
can you try uninstalling and reinstalling it?

**Comment by kurniawanw0194** [comment]
> can you try uninstalling and reinstalling it?

I did multiple times, no luck though.

**Comment by brentvatne** [comment]
> > can you try uninstalling and reinstalling it?
> 
> 
> 
> I did multiple times, no luck though.

so, to clarify, you uninstall the app on your device, then go to the store and reinstall it, and then when you open it you see the error screenshotted in the original post?

**Comment by kurniawanw0194** [comment]
> > > can you try uninstalling and reinstalling it?
> > 
> > 
> > I did multiple times, no luck though.
> 
> so, to clarify, you uninstall the app on your device, then go to the store and reinstall it, and then when you open it you see the error screenshotted in the original post?

I used iOS simulator. I deleted the app, re-installed it, and when I opened it I saw that error. I tried to reset the simulator too, but same error occurred.

**Comment by byCedric** [comment]
Just to clarify, are you installing the Expo Client through `$ expo client:install:ios`? If so, what version are you selecting?

@brentvatne did we change build versions on SDK 38, it looks like the versions don't fully match anymore.

![Screenshot 2020-08-20 at 17 28 32](https://user-images.githubusercontent.com/1203991/90792457-c73c0900-e30a-11ea-9dab-8247cf5bd4b0.png)

**Comment by brentvatne** [comment]
if you're experiencing this can you try selecting this option in the simulator?

<img width="410" alt="Screen Shot 2020-08-20 at 12 37 02 PM" src="https://user-images.githubusercontent.com/90494/90816917-dfe3f900-e2e1-11ea-90a6-fca6f0045b1b.png">

**Comment by brentvatne** [comment]
also, to be totally clear, please let me know explicitly if this is happening when you just tap on the expo client app icon in the simulator, or only if you open a project in expo client. thanks!

**Comment by brentvatne** [comment]
@jzarca01 - did you try what i suggested in https://github.com/expo/expo/issues/9836#issuecomment-677860881?

**Comment by kurniawanw0194** [comment]
> @jzarca01 - did you try what i suggested in [#9836 (comment)](https://github.com/expo/expo/issues/9836#issuecomment-677860881)?

I did, no luck though.

**Comment by brentvatne** [comment]
> > @jzarca01 - did you try what i suggested in [#9836 (comment)](https://github.com/expo/expo/issues/9836#issuecomment-677860881)?
> 
> 
> 
> I did, no luck though.

could you try doing this and and also deleting ~/.expo before installing the app in the simulator again? let me know how it goes. thank you so much!

**Comment by kurniawanw0194** [comment]
I did delete `~/.expo`, and still no luck.

**Comment by brentvatne** [comment]
does this happen on your phone too or only simulator?

**Comment by brentvatne** [comment]
if you're encountering this can you run `expo doctor` in your project and let me know what the result is?

**Comment by brentvatne** [comment]
we were finally able to repro this on our ends, investigating

**Comment by brentvatne** [comment]
thanks for your patience. it looks like what happened was that a new simulator build was uploaded via our ci service *using the same version name* so it overwrote the previous one, so anyone who had downloaded it before was fine but new downloads would break.

**to resolve this issue**

- stop expo cli
- run `expo client:install:ios`
- it should prompt to install 2.16.1
- say yes
- try loading your project
- if that doesn't work, clear `~/.expo` (`rm -rf ~/.expo` will do the trick)
- try loading your project again

**Comment by kurniawanw0194** [comment]
Thanks @brentvatne! It works.

**Comment by jzarca01** [comment]
Thanks @brentvatne you solved it

**Comment by mrflip** [comment]
Hi all, would you consider leaving this issue open for some number of days? Colleague and I spend a couple hours debugging this, with the last half being _after_ searching the issues for preventAutoHide but of course github defaults to only searching open issues. Until the google juice of this issue rises a bit, you'd do the community a favor by holding it open.

`The error is located at: in Y in a in P`

**Comment by jzarca01** [comment]
Sure ;)

**Comment by roggc** [comment]
It just helped me too. Thanks!

**Comment by rangerezekiel** [comment]
Thanks! This solution works!

> thanks for your patience. it looks like what happened was that a new simulator build was uploaded via our ci service _using the same version name_ so it overwrote the previous one, so anyone who had downloaded it before was fine but new downloads would break.
> 
> ## 👇 to resolve this issue 👇
> * stop expo-cli
> * run `expo client:install:ios`
> * it should prompt to install 2.16.1
> * say yes
> * try loading your project
> * if that doesn't work, stop expo-cli and clear `~/.expo` (`rm -rf ~/.expo` will do the trick)
> * try loading your project again
