### ISSUE TITLE
ITMS-90023 Missing required icon file

### ISSUE THREAD

**Issue by blackflamedigital** [expo/expo#984]
I started getting this error just today when I tried to build for iOS.
**My Build ID: 59228e85-7c92-4b5f-8028-8ad2356dba27**

I am getting 2 of these errors:
**ITMS-90023 Missing required icon file**. Says it needs icons of 167x167 and 152x152 sizes.

I never had this issue before and I haven't touched the icons since the first build I made a long time ago.
Could anyone point me in the right directions for this?

Thanks!

**Comment by terribleben** [comment]
Hey there, sorry you ran into this. This is an issue with our build service which we discovered over the weekend and are hoping to resolve soon. We're tracking details [here](https://github.com/expo/expo/issues/980), so please follow that issue and feel free to provide any other info.
