### ISSUE TITLE
[docs] expo-calendar sample code is misleading regarding default calendar sources on iOS

### ISSUE THREAD

**Issue by grossvogel** [expo/expo#9842]
I've attempted to learn some best practices from the documentation [here](https://docs.expo.io/versions/latest/sdk/calendar/#example-usage) and I'm left feeling confused about how things work and the best ways to achieve results. This bit in particular has me confused:

```
async function getDefaultCalendarSource() {
  const calendars = await Calendar.getCalendarsAsync();
  const defaultCalendars = calendars.filter(each => each.source.name === 'Default');
  return defaultCalendars[0].source;
}
```

Reading this sample led me to believe there'd always be a calendar on the device with a source whose name is `"Default"`, but on real devices this doesn't seem to hold. Would it make more sense to call `Calendar.getDefaultCalendarAsync()` and use the source of _that_ calendar? Of course the follow-up to that is whether we have any reason to believe a default calendar would be found by that mechanism.

If someone could help me get clear on these points, I'd be happy to submit a PR to help make the docs better for everybody.

**Comment by lukmccall** [comment]
Hi @grossvogel, I think it would make sense to call `Calendar.getDefaultCalendarAsync()` and then get the source. Hovewer, you need to remember that it can return `null` (very relly, but it could happen). In this case, you can fall back to a method which will look like this one: https://github.com/expo/expo/blob/17b0e52ee395799758c61717a4a9e7b57ccd90c2/apps/test-suite/tests/Calendar.js#L31-L37

**Comment by lukmccall** [comment]
I think this is a best solution right now.

**Comment by jameswilddev** [comment]
I should mention that on my test device, falling back from the iCloud calendar source to the first in the list doesn't work, as the first in the list (for me) is an Exchange calendar, which deletes any local changes whenever it syncs - so it might appear to work at first, but then an hour later any changes your app made are gone.
