### ISSUE TITLE
AuthSession Android login hangs for Auth0

### ISSUE THREAD

**Issue by tiagob** [expo/expo#9845]
### Summary of Issue
After logging in via Auth0 using AuthSession redirecting to the expo app hangs on Android (iOS works fine)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
```

Expo Android App Client version: 2.16.1
Virtual Device Name: Pixel_3_API_R

### Reproducible Demo
I copied https://github.com/expo/examples/tree/master/with-auth0. No changes. My app.json came from `expo init`

Cross-post of https://github.com/expo/examples/issues/210
 
### Steps to Reproduce
Setup the demo. Then run on the Android Emulator. Try Signing in.

**Comment by byCedric** [comment]
Hi @tiagob! Unfortunately I couldn't reproduce this issue. For me, everything either works as expected or shows the error from Auth0 (like invalid redirect uri). Could you provide a [repro](https://stackoverflow.com/help/minimal-reproducible-example) for this?

**Comment by tiagob** [comment]
Thanks for looking at this!

Repo
https://github.com/tiagob/expo-auth0

Auth0 settings (sent an invite to me@bycedric.com)
https://manage.auth0.com/invite?token=akdnem1iVG82UEliSXg3MjpleHBvLWF1dGgwQHB1czM=

**Comment by byCedric** [comment]
No problem! It looks like everything works on my end, your callback urls were good. I only added the `"owner": "<yourexpousername>"` to the manifest to force my local Expo instance to use that name as well. It works fine on both the Pixel emulator and OnePlus device, you should see 2 new users in your app. So, unfortunately, we are dealing with an edge case here.

What do you see exactly? Does the chrome tab opens with Auth0 content, or is it stuck in "limbo"? These are the steps you should see with the current setup:

1. Your app + login button
2. Intermediate screen with "The app at exp://xxx is asking you to sign in to another service. Is this ok?" + yes/no buttons
3. Auth zero content
4. After you are done (either successfully or not) back to the app.

**Comment by tiagob** [comment]
I'm able to get to step 4. After auth0 login, it redirects to the expo app and hangs with a spinner. The spinner never goes away. No logs. It never returns to my App.js code.

I updated Android Studio and created a new virtual device. Same issue.

**Comment by barthap** [comment]
Hey @tiagob 
We suspect this issue has the same root cause as #9522. Please update your emulator to [Android 11 Beta 3](https://developer.android.com/preview/release-notes#beta3) and let us know if this issue still occurs.

**Comment by tiagob** [comment]
That sounds likely. I’m away from my computer but will check when I’m back
September 2nd

**Comment by himadrinath** [comment]
i am using with azure b2c after successful login redirect nothing coming back from promise

**Comment by tiagob** [comment]
This works! Android 11 Beta fixes the issue. Thank you @byCedric !
