### ISSUE TITLE
SDK 39 umbrella issue

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#9850]
## 🎢 SDK 39 umbrella issue
_This issue contains a list of issues per module that occurred during release QA process_

**expo-gl**:
- ~_iOS_ https://github.com/expo/expo/issues/9853~
- ~_Android_ https://github.com/expo/expo/issues/9873~

**gif**:
- ~_iOS_ `ncl/Components/Gif` is not animating https://github.com/expo/expo/issues/9858 (@sjchmiela)~

**expo-media-library**
- ~_iOS_ https://github.com/expo/expo/issues/9857 (@tsapeta)~

**expo-app-auth**
- ~_Android_ https://github.com/expo/expo/issues/9522~ fixed in latest Android 11 beta

**expo-web-browser**
- _Android_ https://github.com/expo/expo/issues/9845

**expo-av**
- ~_Android_ test-suite Audio tests fail due to server deprecation https://authenticated-static-files-hagckpsbra.now.sh/ - https://github.com/expo/expo/pull/9871~

**expo-notifications**
- ~_iOS_ https://github.com/expo/expo/issues/9882 (@sjchmiela)~ _edit: @lukmccall suggested that the failing test is not going to work on iOS anyway, so it's narrowed down to Android platform only_
- ~_Android_ https://github.com/expo/expo/issues/10105~

**expo-permissions**
- ~_Android_ https://github.com/expo/expo/issues/9895~

**expo-splash-screen**
- _Android_ https://github.com/expo/expo/issues/10106

**expo-updates**
- ~https://github.com/expo/expo/pull/9919~
- ~https://github.com/expo/expo/issues/9920 (_does not block versioning_)~
- https://github.com/expo/expo/issues/9921 (_JS only, does not block versioning_)
- ~https://github.com/expo/expo/issues/9922~ (_does not block versioning_)

**video/media-library**
- _iOS 14 Beta 7_ https://github.com/expo/expo/issues/9931 - _wait for iOS 14 GM to see if this is still an issue_

**webview**
- ~_Android_ https://github.com/expo/expo/issues/10016~

**various - sharing/sms/etc**
- ~_Android_ https://github.com/expo/expo/issues/10015~

**reanimated v2**
- _iOS_ https://github.com/expo/expo/issues/10027

**Comment by sjchmiela** [comment]
1. I had to `promote-versions` before building an iOS shell app, otherwise XDL wouldn't know it needs to install `react-native-unimodules` (based on `packagesToInstallWhenEjecting` field in `versions` endpoint) as it uses a production URL.
2. I had to `update-versions -k 'packagesToInstallWhenEjecting.expo-cli` to let XDL know it has to install `expo-cli` too, otherwise `Prepare Expo` `xcodebuild` phase would fail (+ `promote-versions` afterwards).
