### ISSUE TITLE
[Android] ImagePicker invalid URI

### ISSUE THREAD

**Issue by hueyy** [expo/expo#986]
The URI returned from the ImagePicker on an Android device is a little strange:
<pre>
file:///file%3A/data/user/0/host.exp.exponent/cache/ExperienceData/%252540anonymous%25252Fbookswap-ffc75952-eda5-4edc-a172-4c07f3580b98/ImagePicker/30b656a3-c073-44e3-a7f9-38c765ac959e.jpg
</pre>

There is an additional `file%3A/` portion that appears to be `file:/` encoded. This issue appears to be new; I did not experience this on v21.0.0.

The [v23.0.0 ImagePicker](https://docs.expo.io/versions/latest/sdk/imagepicker.html) example returns the above URI. I've [adapted the ImagePicker example snack](https://snack.expo.io/H1KF4IbxM) to show the URI result on-screen (see below). The Image also fails to display because of the incorrect URI.

![photopicker](https://user-images.githubusercontent.com/6523121/33060254-9ef7a4da-ced2-11e7-8e35-1f39a5346bd4.png)

**Comment by terribleben** [comment]
Thanks for the detailed report. Is there any chance this is the same issue as [this one](https://github.com/expo/expo/issues/978)? There's less information in that thread so I can't tell if they are the same thing.

**Comment by hueyy** [comment]
Yup, looks like the same issue. Setting `allowsEditing: false` fixes the URI

**Comment by Jozsef86** [comment]
I'm having the same issue. As @hueyy pointed out, it works if allowsEditing is set to false.

**Comment by brentvatne** [comment]
this is now fixed! update your Android client through the play store or with `exp` / XDE, and re-build your standalone app if it depends on this behavior.

**Comment by hueyy** [comment]
Thank you!
