### ISSUE TITLE
Screen inactive after fast refresh with opened modal from react-native-screens

### ISSUE THREAD

**Issue by WoLewicki** [expo/expo#9861]
### Summary of Issue 

It's a copy of https://github.com/software-mansion/react-native-screens/issues/401. I am not sure if the modal screen is still there but invisible or just the screen under the modal has user interaction disabled after the fast refresh.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Platform: iOS

  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v10.16.1/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v10.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.4 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.13

### Reproducible Demo

https://snack.expo.io/@wolewicki/modal-in-screens
 
### Steps to Reproduce

Go to the second screen which is a modal, and refresh the app there. The first screen will be inactive.

### Expected Behavior vs Actual Behavior

The screen should be active after fast refresh just as it happens in the pure RN app.

**Comment by edi** [comment]
Wondering if this has any workaround, code wise.

My solution is to simply restart the Expo Go client.
