### ISSUE TITLE
Expo Error: IOS simulator Unhandled JS exception, null is not an object (Evaluating t.preventAutoHide)

### ISSUE THREAD

**Issue by kaushik1094** [expo/expo#9863]
![image](https://user-images.githubusercontent.com/23369030/90817299-76b0b580-e2e2-11ea-831c-46ee8c6fe6e2.png)

Running app on ios simulator, installing expo successfully but being thrown this error, this might be an issue with expo app, or probably I am missing something on my end.

macOS: 10.15.6
expo: 35.0.0

**Comment by brentvatne** [comment]
tracking in https://github.com/expo/expo/issues/9836

could you please try the recommendation in this comment https://github.com/expo/expo/issues/9836#issuecomment-677860881 and let me know if that helps?
