### ISSUE TITLE
ForegroundGranted in documentation

### ISSUE THREAD

**Issue by hazelf42** [expo/expo#9864]
"To check whether permission is granted for when app is in use, use `foregroundGranted`."
The wording in this one is confusing -- how do I "use" this? I do not see any mention of "foregroundGranted" in the repo.

**Comment by brentvatne** [comment]
this will be included in the result object where the `... // any additional permission-specific fields` comment indicates

```
{
  status, // combined status of all component permissions being asked for, if any of has status !== 'granted' then that status is propagated here
  expires, // combined expires of all permissions being asked for, same as status
  canAskAgain,
  granted,
  permissions: { // an object with an entry for each permission requested
    [Permissions.TYPE]: {
      status,
      expires,
      canAskAgain,
      granted,
      ... // any additional permission-specific fields
    },
    ...
  },
}
```

agree we should clarify the permissions docs

**Comment by brentvatne** [comment]
https://github.com/expo/expo/issues/9865
