### ISSUE TITLE
[docs] Organize the "notes" in the location permissions doc better

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#9865]
https://docs.expo.io/versions/latest/sdk/permissions/#permissionslocation - this is fairly difficult to digest.

<img width="1125" alt="Screen Shot 2020-08-20 at 1 42 32 PM" src="https://user-images.githubusercontent.com/90494/90823598-00fd1780-e2eb-11ea-8bcd-87c8e65a9cff.png">

**Comment by byCedric** [comment]
I already addressed some of these in the unversioned docs, for SDK 39. Here is a screenshot of the same documentation area. Here I split the large content into its own subheader, and the scope property is added as well.

![Screenshot 2020-08-21 at 02 49 17](https://user-images.githubusercontent.com/1203991/90839936-0133fc00-e359-11ea-8ef8-fdb60cf43fb4.png)
