### ISSUE TITLE
Turn off expo web!!!

### ISSUE THREAD

**Issue by NakulParekh** [expo/expo#9867]
Hello, I am making a note taking app and I am very new to app development. Before, when I ran `expo start`, I was able to open up my app on my phone (connected to my computer) through the expo app, and I can see the changes I make the moment I save my file. However, suddenly, whenever I run `expo start`, it opens through expo web, and only opens my app in my browser. I don't believe I did anything to trigger this, but it is very annoying since my app does not work properly on web, and I want to run it on my phone. Is there any way to change it back so I am working on my phone?

I constantly get this error while it is trying to open in the web:
`Couldn't adb reverse: cannot bind listener: missing port in specification: tcp:null`

**Comment by brentvatne** [comment]
please follow the issue template! we need to see the result from expo diagnostics
