### ISSUE TITLE
Support for slide over on iPad

### ISSUE THREAD

**Issue by Maxim-Filimonov** [expo/expo#987]
Hi,
I was wondering how feasible is to add support for slide over on iPad? 
I'm coding on my ipad using terminal and right now I need to use my iPhone to look at the app as it's impossible to use Expo client on iPad in slide over(or 3/4 split screen in ios 11). 
It does look like relatively straitghforward change from [the docs](https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/AdoptingMultitaskingOniPad/QuickStartForSlideOverAndSplitView.html#//apple_ref/doc/uid/TP40015145-CH13-SW1)

**Comment by terribleben** [comment]
Hey there, this is a reasonable feature request. Right now we don't support any iPad multitasking behaviors, but at some point we could add that. We track feature requests on [canny](https://expo.canny.io/feature-requests?search=multitasking), would you mind opening something there? :)

**Comment by Maxim-Filimonov** [comment]
For anyone who finds this via search here is [the feature to vote on](https://expo.canny.io/feature-requests/p/support-for-multitasking)
