### ISSUE TITLE
Asking for Permissions.CAMERA_ROLL: unrecognized permission: cameraRoll (SDK 23.0.0)

### ISSUE THREAD

**Issue by phehaz** [expo/expo#988]
As the title states, in 23.0.0 Camera/Library access has been split in two permission (https://github.com/expo/expo/issues/970), but the new Permission seem to be unrecognized on iOS? 

log error: [Unhandled promise rejection: Error: Unrecognized permission: cameraRoll]

**Comment by terribleben** [comment]
Hi, that feature didn't ship in our SDK 23 iOS release. Sorry the other thread has a misleading comment. I'll go add more information over there.

We'll be adding the CAMERA_ROLL permission on iOS in a minor update, probably sometime this week.

**Comment by serranoarevalo** [comment]
Is this out?

**Comment by terribleben** [comment]
Yes, this shipped with iOS 2.1.3 and higher: https://github.com/expo/expo/commit/36ea682ee7da160d71709d1f116bd7d417e22c5f#diff-9e304d4e8df1b74cfa009913198428ab

Sorry I didn't reply here earlier.
