### ISSUE TITLE
[iOS][notifications] getPresentedNotificationAsync() does not return foreign notifications info

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#9882]
### Summary of Issue

`getPresentedNotificationAsync()` does not return foreign notifications info and thus test is failing

### Environment

Expo CLI 3.24.2 environment info:
```
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.16.1/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.24.2
```

Device:
```
	iOS version: OS 13.6
	Model: iPhone 11
```

### Reproducible Demo

- on master launch `Expo Client` with `test-suite`
- launch `expo-notifications` tests and observe:
```
+++ :broken_heart: expo-notifications getPresentedNotificationsAsync() includes the foreign persistent notification
toContain: Expected [  ] to contain <jasmine.objectContaining(Object({ request: <jasmine.objectContaining(Object({ identifier: <jasmine.stringMatching(/^expo-notifications:\/\/foreign_notifications/)>, content: <jasmine.objectContaining(Object({ data: <jasmine.objectContaining(Object({ android.contains.customView: true }))> }))> }))> }))>.
```

![Screen Shot 2020-08-21 at 13 32 55](https://user-images.githubusercontent.com/16623003/90886818-6c122100-e3b3-11ea-9eb5-ce4b3b8c469c.png)

**Comment by ide** [comment]
If this test is not expected to pass on iOS, let's omit the test from running on iOS. The built-in way to do this is to use platform-specific files: `example-test.ts`, `example-test.ios.ts`, ... where the iOS file does not include tests that shouldn't run on iOS.
