### ISSUE TITLE
[expo-video-thumbnails][Android]: `[TypeError: Cannot read property 'getThumbnail' of undefined]`  when using unimodules in bare react-native app

### ISSUE THREAD

**Issue by Sine99** [expo/expo#9886]
### Summary of Issue 
Getting  Error `[TypeError: Cannot read property 'getThumbnail' of undefined]`  while fetching thumbnail of video from remote URL. Using React Native CLI with unimodules to import expo libraries into rn-cli app 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
OS: windows10, Powershell
Editor: VSCode 1.46.1
Binaries: Node 12.18.0, npm 6.5.0
**npm packages:**
"react": "16.11.0",
"react-native": "^0.63.2",
"react-native-unimodules": "^0.10.1",
 "expo-video-thumbnails": "^4.2.1",
**Device**
Android (real device)

### Reproducible Demo

![image](https://user-images.githubusercontent.com/3010749/90904291-b5cb2d80-e3ec-11ea-81c8-25822753a477.png)

### Steps to Reproduce
I am using react-native-unimodules to implement expo-video-thumbnails library in in my react-native app created through React-Native CLI. While trying to import the thumbnails from a remote url (cdn link), i am getting the following issue.

`[TypeError: Cannot read property 'getThumbnail' of undefined]` . No thumbnail is visible

### Expected Behavior vs Actual Behavior
**Expected Behavior**
Thumbnail of the remote url should have been generated at the documentation of expo library mentions

**Actual Behaviour**
No thumbnail is generated and a error is displayed

![error](https://user-images.githubusercontent.com/3010749/90905612-0e4efa80-e3ee-11ea-9f38-249a32a860bc.jpeg)

![error2](https://user-images.githubusercontent.com/3010749/90905506-e9f31e00-e3ed-11ea-93f9-914c73c13518.jpeg)

![error3](https://user-images.githubusercontent.com/3010749/90905657-1e66da00-e3ee-11ea-9c4a-486a044ef3d9.jpeg)

**Comment by byCedric** [comment]
Hi @Sine99, your code from the screenshot looks fine. This error indicates that the module isn't properly linked. Now I'm not sure how you set it up, but if `getThumbnail of undefined` is thrown, it's [failing on this line](https://github.com/expo/expo/blob/master/packages/expo-video-thumbnails/src/VideoThumbnails.ts#L10). Without a repro there isn't a lot I can do for you. If you can supply one that would be helpful.

**Comment by Sine99** [comment]
@byCedric, well its a late reply, (was too busy with my life).
I have noticed that the issue resolved when I downgraded react-native version from 0.63.2 to 0.62.2. I am not sure, but i doubt if the  expo-video-thumbnails is compatible with rn-0.63.2 ?

**Comment by caferyukseloglu** [comment]
Bumb getting same error
