### ISSUE TITLE
[expo-video] Fullscreen on Android is locked by orientation, while iOS can rotate to landscape

### ISSUE THREAD

**Issue by mleister97** [expo/expo#9899]
Why was this issue closed? => https://github.com/expo/expo/issues/6864
I added my "Hotfix"-Code for the bug but I think this issue should be fixed as the native controls of the video-player should also support rotating without manually unlocking the orientation-mode

My hotfix for now (for anyone who is interested): 

New working version inspired by @bapjiws (typescript):

```javascript
import * as ScreenOrientation from 'expo-screen-orientation';
import {Platform} from 'react-native';

const videoRef = useRef<any>() // Note: No idea which type i should use here

const onFullscreenUpdate = async ({fullscreenUpdate}: VideoFullscreenUpdateEvent) => {
    if (Platform.OS === 'android') {
        switch (fullscreenUpdate) {
            case Video.FULLSCREEN_UPDATE_PLAYER_DID_PRESENT:
                await ScreenOrientation.unlockAsync()
                break;
            case Video.FULLSCREEN_UPDATE_PLAYER_WILL_DISMISS:
                await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT)
                break;
        }
}

const showVideoInFullscreen = async () => { await videoRef.current.presentFullscreenPlayer() }

<Button title="Play video" onPress={showVideoInFullscreen} />

<Video
    ref={videoRef}
    source={{uri: videoSource}}
    resizeMode={ResizeMode.CONTAIN}
    useNativeControls={true}
    onFullscreenUpdate={onFullscreenUpdate}
/>
```

Anyways, I think this is a bug and should be fixed.

**Comment by byCedric** [comment]
Hi @mleister97! Just to clarify, you want the same behavior of the `<Video />`'s fullscreen on Android to be like iOS. On iOS you can rotate your phone with a video fullscreen, without having to unlock the screen orientation (set through `app.json`'s `orientation` property), right?

If so, I'm not sure why they are implemented differently but we should double-check if we can unify this behavior. That way, you don't have to perform the dirty workaround for Android only. But correct me if I'm wrong here!

**Comment by SleeplessByte** [comment]
@byCedric you have not implemented this differently. This is a relatively new "iOS" feature.

The feature lets iOS "disrepect" the portrait mode when watching fullscreen, whereas Android _always_ respects it (hence you can't rotate the screen without unlocking). It might _feel_ like the iOS way is preferable, but it has some issues. Reproducible:

- Have a video on iOS
- Watch it in landscape
- Now exist fullscreen.

iOS will _respect_ the `portrait` mode for the `app.json`, but `Dimensions.get` now reports its width as height and height as width.

The only way to get around that is to use the same "hack" as described above! So to me that points that the _expo_ implementation is consistent, but the iOS native video driver is different.

**Comment by mleister97** [comment]
> Hi @mleister97! Just to clarify, you want the same behavior of the `<Video />`'s fullscreen on Android to be like iOS. On iOS you can rotate your phone with a video fullscreen, without having to unlock the screen orientation (set through `app.json`'s `orientation` property), right?
> 
> If so, I'm not sure why they are implemented differently but we should double-check if we can unify this behavior. That way, you don't have to perform the dirty workaround for Android only. But correct me if I'm wrong here!

Yes you unterstood everything correctly!

**Comment by chishing96** [comment]
this issue still exist

**Comment by navuyi** [comment]
I think the reason for that different behavior is that native Video component is made as another layer of view in case of iOS. On Android it is put together along with other UI components.
I unlocked the orientation on both systems and subscribed to ScreenOrientation changes. What I noticed is that when in fullscreen mode (on both) the callback was invoked only on Android. Because on Android the whole UI was changing orientation but on iOS the UI orientation was the same. Only the Video component layer was changing.

**Comment by SleeplessByte** [comment]
It's not stale

**Comment by SleeplessByte** [comment]
on iOS (eas) the video now closes (SDK 44), when opened in full screen from a flatlist. Seems to be the exact same issue as Android.

**Comment by SleeplessByte** [comment]
It's not stale.

**Comment by stuckj** [comment]
Yep, this is definitely still broken.

**Comment by SleeplessByte** [comment]
https://github.com/expo/expo/issues/9899#issuecomment-1194623090

**Comment by SleeplessByte** [comment]
The behaviour between iOS and Android when fullscreen is enabled isn't consistent. Between expo releases the platform that breaks _can_ change, as seen between 40, 44, and 46. My personal recommendation would be to **not** lock orientation to begin with, if you want to support fullscreen video.

That said, I have no interest in keeping this open so I am unsubscribing from this issue. You'll likely see this close in 67 days.

**Comment by yavuzakyazici** [comment]
I have been struggling with the same issue. And the hotfix above is not working on physical android phone or emulator.
Anybody has a solution for this?

**Comment by lsarni** [comment]
@yavuzakyazici There are some other workarounds on this issue https://github.com/expo/expo/issues/6864
