### ISSUE TITLE
system auth behavior doesn't recognize permissions list

### ISSUE THREAD

**Issue by sheerun** [expo/expo#99]
I authenticate with following:

```
const { type, token } = await Expo.Facebook.logInWithReadPermissionsAsync('xxx', {
  permissions: ['public_profile', 'email'],
  behavior: 'system'
})
```

But the Facebook auth prompt says `"Expo" would like to access your basic profile info and list of friends`.

It seems that `system` auth behavior doesn't recognize permissions set.

Everything's OK when using any other auth method (web/native)

**Comment by terribleben** [comment]
cc @nikki93
