### ISSUE TITLE
Description not updating in expo.io

### ISSUE THREAD

**Issue by kanwar002** [expo/expo#9902]
Description not updating in expo.io but its updating in apps.json i tried to publish it through dev tool but publishing also not worked so i did publishing with code(expo publish). Now i'm trying to update description and it's also not working. I tried to change it from apps.json but it still didn't update it

![Screenshot (41)](https://user-images.githubusercontent.com/56306542/90978341-d3be9c80-e56a-11ea-9aaf-e12ce6333dcb.png)
![Screenshot (42)](https://user-images.githubusercontent.com/56306542/90978343-d5886000-e56a-11ea-875a-59e880b42eaf.png)
![Screenshot (43)](https://user-images.githubusercontent.com/56306542/90978344-d620f680-e56a-11ea-9172-41837d1206ac.png)

**Comment by byCedric** [comment]
Hi @kanwar002! You need to publish the version of your app, _with the manifest changes_, to show this on expo.io. Right now, with the latest published manifest, I can see that `description` is set to `""` (empty). Run `$ expo publish` with the updated manifest to fix that. (**note**: this will update the app for your users as well)

Hope this helps!

**Comment by kanwar002** [comment]
@byCedric I'm using latest version. I made new app but got same thing, description not updating, i don't know why it's not showing any error. I tried to update description from app.json still didn't work

**Comment by byCedric** [comment]
What exactly do you mean by "using the latest version"? For both your apps `homemade` and `HomeMade`, the `description` is still set to `""`. Running it locally, as you shared in the screenshots, _does not update the manifest on expo.io_. Please check the [walkthrough to see what you need to do](https://docs.expo.io/introduction/walkthrough/#publish-and-share-your-app).

**Comment by kanwar002** [comment]
the version is 3.24.2, and homaemade and HomeMade is same app. Description is still set to "" O.o but in 1st screen shot description has text in it. That site crashing my browser :/
