### ISSUE TITLE
Android - KeyboardAvoidingView is not behaving properly (Even with SDK 38 and softwareKeyboardLayoutMode: pan)

### ISSUE THREAD

**Issue by ronbel** [expo/expo#9903]
### Summary of Issue 
I am trying to lift a TextInput I have just a tiny bit above the keyboard using KeyboardAvoidingView. On iOS it works just fine, on Android it won't behave properly, regardless of the behavior prop I pass to it. Changing "softwareKeyboardLayoutMode" to "pan" makes no difference, neither locally nor when building a standalone app. Reproducible in a blank app.

### Environment 

 Expo CLI 3.24.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Ron Belkin\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ^38.0.9 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^3.8.1 => 3.13.0

Tested on a Huawei Mate 20 Pro

### Reproducible Demo
Create a new app with `expo init` using the blank template in managed workflow, edit `App.js` to be:
```
import React from 'react';
import {KeyboardAvoidingView, StyleSheet, TextInput, View, ScrollView}  from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
        <KeyboardAvoidingView  keyboardVerticalOffset={20} behavior="padding">
         <TextInput style={{width: 200, height: 50, borderRadius: 10, borderWidth: 1}}/>
        </KeyboardAvoidingView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 90
  },
});
```

The `app.json` file looks like that:
```
{
  "expo": {
    "name": "kav-test",
    "slug": "kav-test",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "android": {
      "softwareKeyboardLayoutMode": "pan"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}

```
 
### Steps to Reproduce
Use an Android device. Focus the TextInput on the screen, notice the behavior (explained below).

#### Expected behavior: 
Input should be slightly higher than the keyboard

#### Actual behavior:
When passing no "behavior" prop, input is lifted but still is partially hidden by the keyboard
With "padding" behavior, input gains excess padding *until I type a character*, then it positions itself as expected
With "height" behavior, input is indeed lifted properly (when you tweak the `keyboardVerticalOffset` prop), but when you type a character, it returns to the position of the first case (when behavior is unspecified)

Honestly, with behavior "position" it kinda does what I want *in the demo app*, but in my app the three last cases behave exactly like the case where behavior is "padding"

The `"softwareKeyboardLayoutMode": "pan"` makes no difference in this scenario whatsoever.

Is there any workaround I haven't managed to find?

**Comment by ronbel** [comment]
bump, hard to believe no one else has encountered it, especially when it's reproducible with no additional dependencies

**Comment by xXDeonoXx** [comment]
Same issue here, my inputText is inside a TouchableOpacity and the keyboard only push right bellow the input, cutting half the touchable opacity around.

**Comment by Charmix** [comment]
Same issue

**Comment by VictorioMolina** [comment]
same here

**Comment by brentvatne** [comment]
as far as i know this behaves exactly as it does in react-native, so this is not an expo issue but a react-native upstream issue. if you believe this is not the case, please demonstrate and explain further. i'll close the issue tomorrow otherwise

**Comment by brentvatne** [comment]
here is the list of issues related to keyboardavoidingview on react-native: https://github.com/facebook/react-native/issues?q=KeyboardAvoidingView++android+is%3Aopen

**Comment by VictorioMolina** [comment]
@brentvatne I am experiencing this issue in Android. In my case, I have also implemented my own "KeyboardAvoidingView" (just listening the keyboard height and giving a paddingBottom to the container) to manipulate the layout. All works good on iOS, but for android, two paddings are given. One which seems to be the default behaviour (a default padding when the keyboard is shown), and the last one which I have developed. 

Do you know how to avoid the first default padding behaviour on Android? I have been testing with "softwareKeyboardLayoutMode": "pan" (on android, in app.json), but as @ronbel said, 

> The "softwareKeyboardLayoutMode": "pan" makes no difference in this scenario whatsoever.

This seems really confusing to me... why is it necessary to have a "first default extra padding" when the keyboard shows on Android?

Pd: what I mean by "first default extra padding", is that, for example, if I have one screen like this:

```
<View style={{flex: 1}} >
    <View style={{flex: 1}} />
    <TextInput />
</View> 
```

without any "KeyboardAvoidingView" component, the keyboard pushes up the content.

So, if then I do:

```
<View style={{ flex: 1 }} >
    <KeyboardAvoidingView> { /*  <--- Can be my custom or the default RN component... the result is the same */  }
        <View style={{flex: 1}} />
        <TextInput />
    </KeyboardAvoidingView>
</View> 
```
on Android, two paddings are given.


Any ideas what I am doing wrong??

Thank you.

**Comment by TomasSestak** [comment]
I have the same problem, any workaround?

**Comment by VictorioMolina** [comment]
@TomasSestak in my case, I have solved this "problem" by setting custom styles for android, playing with minHeight (not the best solution but works in most of the cases)

**Comment by TomasSestak** [comment]
> @TomasSestak in my case, I have solved this "problem" by setting custom styles for android, playing with minHeight (not the best solution but works in most of the cases)

I tried playing with minheight, height values but nothing helped, so i did this: 
<img width="625" alt="Screenshot 2021-01-05 at 17 29 09" src="https://user-images.githubusercontent.com/27310585/103671688-87a15100-4f7b-11eb-9f89-f63a48254452.png">

**Comment by VictorioMolina** [comment]
@TomasSestak have you tested "softwareKeyboardLayoutMode": "pan" ?  Based on what I have read in some answers on StackOverflow, it is used to avoid the default padding behaviour for android... Anyways, I have tested it with Expo SDK 40, and the behaviour is the same as using the default value "resize".

**Comment by fabriziobertoglio1987** [comment]
Do you experience this on Devices that have a notch? My pr fixed that issue https://github.com/facebook/react-native/pull/30919

Are you using windowTranslucentState=true? Should be fixed in react-native 0.63.3 https://github.com/facebook/react-native/pull/29292

**Comment by DatMoser** [comment]
Figured out that it is because of the "softwareKeyboardLayoutMode" prop on android. When I remove it, the KeyboardAvoidingView works properly, but the screens are buggy as soon as the keyboard opens up.

Don't have a fix yet, but it seems like as if we have to choose between buggy screens or a buggy keyboards on android :-/

**Comment by rphlmr** [comment]
Hi all, this keyboard management in React is hell 🤪

I don't know if my video is what you are looking for, but in case, this is how I manage keyboard in my apps (with expo or not).

In expo conf I use `"softwareKeyboardLayoutMode": "pan"`

For keyboard view, I use an other package : https://github.com/APSL/react-native-keyboard-aware-scroll-view

And the code : 

```js
import { KeyboardAwareScrollView } from "react-native-keyboard-aware-scroll-view";

const KeyboardScrollView = ({ children }) => (
  <KeyboardAwareScrollView
    style={{
      flex: 1,
      backgroundColor: "white"
    }}
    contentContainerStyle={{
      flexGrow: 1,
      backgroundColor: "white"
    }}
    extraHeight={20}
    extraScrollHeight={15}
    enableResetScrollToCoords={true}
    endFillColor="white"
    enableAutomaticScroll
    keyboardOpeningTime={0}
    enableOnAndroid={true}
    keyboardShouldPersistTaps="handled"
  >
    {children}
  </KeyboardAwareScrollView>
);
```

It seems that extraHeight should be > to extraScrollHeight.

Disclaimer : it's not working every time 😂

https://user-images.githubusercontent.com/20722140/113515411-97c5ce00-9574-11eb-9c84-0ae4133825ab.mp4

**Comment by samih-sghier** [comment]
For anyone wondering - I have solved this issue by simply removing `behavior="padding"` for KeyboardingAvoidingView on Android 👍

**Comment by SegoviaDiego** [comment]
@VictorioMolina Same thing is happening to me.

IOS works perfectly, but Android has duplicated padding.

Already tried playing with min-height and removing `"softwareKeyboardLayoutMode": "pan"` too, nothing seems to change that android default behavior.

Did you find a solution to this?

**Comment by quochuy2405** [comment]
> > @TomasSestak in my case, I have solved this "problem" by setting custom styles for android, playing with minHeight (not the best solution but works in most of the cases)
> 
> I tried playing with minheight, height values but nothing helped, so i did this: <img alt="Screenshot 2021-01-05 at 17 29 09" width="625" src="https://user-images.githubusercontent.com/27310585/103671688-87a15100-4f7b-11eb-9f89-f63a48254452.png">

thank you it work for me

**Comment by TomasSestak** [comment]
I recommend this library to everyone - works like charm though not mantained anymore
https://github.com/iway1/react-native-keyboard-avoider#readme

**Comment by ehcorrea** [comment]
> I recommend this library to everyone - works like charm though not mantained anymore https://github.com/iway1/react-native-keyboard-avoider#readme

you can use this lib https://kirillzyusko.github.io/react-native-keyboard-controller/docs/api/keyboard-controller#setinputmode-, have suport and you can change input mode dynamically.

Just use this in your root app and done

```
export default App(){
  useEffect(() => {
      KeyboardController.setInputMode(
      AndroidSoftInputModes.SOFT_INPUT_ADJUST_PAN
    );
   },[])

 {...}
}
```
