### ISSUE TITLE
 The key hash does not match any stored key hashes

### ISSUE THREAD

**Issue by Mersall** [expo/expo#9904]
Hello, i try to get login with Facebook work on my expo app android, this massage appears, I'm sure I use same 
hash  with this command expo fetch:android:hashes  and this error appear 

SERVER_ERROR: [code] 1349195 [message]: The key hash does not match any stored key hashes. Go to https://developers.facebook.com/docs/facebook-login/android for more information. [extra]:

**Comment by byCedric** [comment]
Hi @Mersall! I'm sorry this happens to you, but without any context, we can't help a lot here. It might be better to send an email to secure@expo.io with the app name and full output/screenshot of the command.

There are some things that you can try first:
- Did you build a standalone app for Android (APK) yet? If not, try that first.
- Did you upload custom credentials already?
- Have you configured the Android bundle identifier properly?

Hope this helps!

**Comment by johinsDev** [comment]
@Mersall you found a solution, i have the same problem

**Comment by Mersall** [comment]
> @Mersall you found a solution, i have the same problem

yes, hash key is different in develoent, you should build one time then get the hash keu, after that, when I tried to login with the apk, igot erorr that with hash key, said this hash key not asigned to any account, itaked it and, past it in my account in fb, and the problem solved

**Comment by johinsDev** [comment]
> > @Mersall you found a solution, i have the same problem
> 
> yes, hash key is different in develoent, you should build one time then get the hash keu, after that, when I tried to login with the apk, igot erorr that with hash key, said this hash key not asigned to any account, itaked it and, past it in my account in fb, and the problem solved

ok, thanks, but  i you create a new build, you new upload to play store?
