### ISSUE TITLE
[docs] Missing permission on app.json of expo-camera

### ISSUE THREAD

**Issue by renanmav** [expo/expo#9914]
It's not clear that you need to add `CAMERA` do `android.permissions` on `app.json` on this page:
https://docs.expo.io/versions/latest/sdk/camera/#configuration

I think it worths mentioning this change since I just found out on the production environment.

I suggest something like this:

> In managed apps, Camera requires `Permissions.CAMERA`. Video recording requires `Permissions.AUDIO_RECORDING`. **Don’t forget to add those in `android.permissions` on `app.json`.**

**Comment by byCedric** [comment]
Thanks for the feedback, we should do that for all modules that require additional permissions.

**Comment by vivere-dally** [comment]
> Thanks for the feedback, we should do that for all modules that require additional permissions.

The docs are not updated and I can't figure out if I need to specify it in both places, and also if I need to specify the microphone one. Please extend the docs with:
- how to correctly set the permissions requirement
- how to correctly require permissions in the component
