### ISSUE TITLE
facebookScheme on Standalone Android is broken, CustomTabActivity doesn't do anything.

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo#9917]
### Summary of Issue 

- Cross-post from [this forum post](https://forums.expo.io/t/standalone-android-facebook-auth-never-returns-from-com-facebook-customtabactivity/42030/2).
- The `facebookScheme` on standalone Android resolves to a `CustomTabActivity` that is completely blank and doesn't do anything.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.24.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~38.0.8 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```

### Reproducible Demo

Code is reduced to a single file, one package (`expo-auth-session`), and only adding the `facebook*` properties to `app.json`. See [this post](https://forums.expo.io/t/standalone-android-facebook-auth-never-returns-from-com-facebook-customtabactivity/42030/2?u=derk-jan). 

[APK download (available up to 29 days of this post)](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40derk-jan/sounders-music-facebook-d57904c5f63844f8baa51b04f9f20314-signed.apk).

### Steps to Reproduce

- `expo init` minimal typescript
- `expo install expo-auth-session`
- create new facebook project, add login, add `https://auth.expo.io/@user/slug`
- copy code from reproducible post
- make a standalone build

### Expected Behavior vs Actual Behavior

- Web: it works
- Expo client: it works (using proxy)
- Android standalone client: clicking "continue" OR "cancel" returns to a second activity with just the app title in an appbar.

Reproduce by running:

```shellscript
adb shell am start -W -a android.intent.action.VIEW -d "fb<FACEBOOKID>://authorize?code=invalid&state=a01bCdEFJK" com.example.app
```

### Other things

Because I had not seen this issue anywhere else, I suspected this was a me problem; but I think it might not be. It's also not unique to `expo-auth-session`, as you can tell by the shellscript reproduction.

**Comment by cruzach** [comment]
hey @SleeplessByte, when you say it's unique to `expo-auth-session`, does that mean logging the user in with [`Facebook.loginWithReadPermissionsAsync`](https://docs.expo.io/versions/latest/sdk/facebook/#facebookloginwithreadpermissionsasyncoptions) works as expected?

**Comment by SleeplessByte** [comment]
@cruzach it's _not_ unique to `expo-auth-session`. You can reproduce the issue by adding `facebookScheme` to a fresh init and running the adb commmand.

**Comment by cruzach** [comment]
have you added the Facebook Key Hash in your Facebook project? It would be useful to know if logging in with the `expo-facebook` api is working

**Comment by SleeplessByte** [comment]
@cruzach I did add that, but why don't I make you also a version using `expo-facebook` (but otherwise same minimal code) and see if it's failing still. I'll make sure the Facebook hash is set on Facebook. Then we can compare the two / see if it's `expo-auth-session` or `expo-facebook` related.

**Comment by SleeplessByte** [comment]
@cruzach 

Expo client:
- `expo-facebook`: works
- `expo-auth-session`: works

Standalone android build:
- `expo-facebook`: works (!!)
- `expo-auth-session`: behaves as described above (doesn't work).

**Comment by SleeplessByte** [comment]
FWIW: this is still present in SDK 39 / `expo-auth-session: "~2.0.0"`

**Comment by EvanBacon** [comment]
As far as I can tell, it would seem that facebook auth-session may not work with Android standalone apps in their current form. The custom activity is required for expo-facebook to work properly. Perhaps we could try making expo-auth-session require expo-facebook to work on Android 🤔

**Comment by SleeplessByte** [comment]
If there is a way that `expo-facebook` can return a _code_ instead of an access token, that would provide a workaround path too.

**Comment by PPjev** [comment]
I have exactly the same behavior as described above. Only on Android Standalone. iOS TestFlight works fine. Is there a solution?

**Comment by SleeplessByte** [comment]
You can try `expo-facebook` @PPjev; but it requires some type-juggling.

**Comment by PPjev** [comment]
I am just curios, for all the others it works just fine? is it just the two of us? I see other people have same issues on the internet, but this is not solved for such a long time... and facebook login is broadly used. I mean, are we doing something wrong, or it just dont work for everyone?

**Comment by SleeplessByte** [comment]
No, it's broken for everyone.

**Comment by brentvatne** [comment]
@SleeplessByte - thanks for the detailed report! could you `useProxy` in the standalone app until we have time to investigate further?

**Comment by PPjev** [comment]
i tried to explicitly state useProxy, but then it never reaches facebook, I get redirected to auth.expo.io and the text saying that I should go back, since something is not right. Or am I doing it wrong?
I set redirectUri to makeRedirectUri({
    useProxy: true
})

**Comment by SleeplessByte** [comment]
> @SleeplessByte - thanks for the detailed report! could you `useProxy` in the standalone app until we have time to investigate further?

Unfortunately no. When the proxy "comes back" to the app, it still opens that other activity (as that is apparently set as the "return URL" or something like that).

Unless this changed in the past 2 months (which is when I last tested it, forcing useProxy on Android).

**Comment by SleeplessByte** [comment]
Short update.

- expo 39.0.5 (react-native expo/39.0.4)
- expo-cli 4.0.17
- expo-auth-session ~2.0.0

I'm well aware there is Expo 40, and Auth session 3, but if this issue hasn't been worked on (and I don't think it has), there is no point just yet forcing that upgrade. If it _has_ been worked on, I can probably redo all these tests using expo 40 + auth-session 3, but understand that it's a lot of work.

| key | meaning |
|---|---|
| 💥 | A wild error occurred |
| ❌ | It was not very effective |
| ✔️ | It's super effective |
| ⚠️ | Caveat |

- `useProxy: true` means `makeRedirectUri({ useProxy: true })` + `promptAsync({ useProxy: true })`
- `redirectUri: ...` means *not* using `makeRedirectUri` at all

# Summary

| platform | build | expo-auth-session | technique | result |
|---|---|--|--|--|
| android | standalone managed | `2.0.1` | `useProxy: true` (`makeRedirectUri`) | ❌💥 |
| android | standalone managed | `2.0.0` | `useProxy: true` | ❌ |
| android | standalone managed | `2.0.1` | `redirectUri: fb${FACEBOOK_ID}://authorize` | ❌ |
| android | standalone managed | `2.0.0` | `redirectUri: fb${FACEBOOK_ID}://authorize` | ❌ |
| android | standalone managed | `2.0.1` | `redirectUri: https://auth.expo.io/@username/slug` | ❌ |
| android | standalone managed | `2.0.0` | `redirectUri: https://auth.expo.io/@username/slug` | ✔️⚠️ |
| android | expo client | `2.0.1` | `useProxy: true` | ✔️ |
| android | expo client | `2.0.0` | `useProxy: true` | ✔️ |

It seems that `2.0.1` is _more_ broken than `2.0.0` in every aspect.

# Android standalone (managed build)

## Forcing `useProxy`

- ❌💥 When using `expo-auth-session` version `2.0.1` it blows up:

  ```text
  … \node_modules\expo-auth-session\build\BareSessionUrlProvider.js in getRedirectUrl at line 13:19
  
      }
      getRedirectUrl(urlPath) {
          if (Platform.OS === 'web') {
              return [window.location.origin, urlPath].filter(Boolean).join('/');
          }
          throw new Error("No default redirect URL could be found. If you're using the bare workflow, you'll need to provide this yourself.");
      }
  }
  //# sourceMappingURL=BareSessionUrlProvider.js.map
  ```

- ❌ When downgrading to `2.0.0` it has the described behaviour:

  1. proxy page loads and redirects
  2. login screen shows
  3. upon completion opens the empty activity.

## Manually entering `fb${FACEBOOK_ID}://authorize`

So here `makeRedirectUri` is not used, but it just forces the correct native uri.

- ❌ When using `expo-auth-session` version `2.0.1`

  a nothing happens (it doesn't redirect to the browser), with `promptAsync({ useProxy: true })`
  b. it redirects to login, but upon completion opens the empty activity.

- ❌ When downgrading to `2.0.0` 

  1. proxy page loads and redirects
  2. login screen shows
  3. upon completion opens the empty activity.

## Manually entering `https://auth.expo.io/@username/slug`

- ❌ When using `expo-auth-session` version `2.0.1`

  a nothing happens (it doesn't redirect to the browser), with `promptAsync({ useProxy: true })`
  b. it redirects to "Something went wrong trying to finish signing in" with  `promptAsync({ useProxy: false})`

- ✔️⚠️ When downgrading to `2.0.0` 

  1. proxy page loads and redirects (using `promptAsync({ useProxy: true })`)
  2. login screen shows
  3. upon completion shows 2 (!) activities to open. Both open the app. One of them will result in the regular startup screen, but no auth request; One of them actually results in an auth request with response (and so this works). Both activities are named the same. There is no way for a user to understand which one to click.

# Android, expo client

## Forcing `useProxy`

- ✔️ When using `expo-auth-session` version `2.0.1`:

  It works using `useProxy` and `makeRedirectUri`
  
- ✔️ When downgrading to `2.0.0` 

  It works using `useProxy` and `makeRedirectUri`

**Comment by christianmellor** [comment]
Hello, will this be fixed in a new version of `expo-auth-session`? I am currently using the `expo-facebook` package as a workaround with a different auth flow for Android users - which works fine but it would be great if this was unified for both platforms

**Comment by SleeplessByte** [comment]
I think the intention is to fix this eventually ;)

**Comment by sgvolpe1** [comment]
Hi, some new about that issue?

Thanks

**Comment by farhan-ibrahim** [comment]
Hi, any update on this issue? Just encountered this when try to build standalone android apps. I initially use expo-facebook, but change it since expo-facebook only allow read permission

**Comment by SleeplessByte** [comment]
You can follow https://github.com/expo/expo/issues/9917#issuecomment-758369766 for a workaround.

**Comment by farhan-ibrahim** [comment]
> You can follow [#9917 (comment)](https://github.com/expo/expo/issues/9917#issuecomment-758369766) for a workaround.

You mean by downgrading to expo-auth-session 2.0.0 ? Currently, I'm using 3.0.0 with expo sdk40

**Comment by SleeplessByte** [comment]
The workaround also works with `"expo-auth-session": "~3.0.0"`, and Expo 40. 

Here's the config:

```ts
const FACEBOOK_ID = Constants.manifest.extra['facebook-client-id'];

const isNative = Constants.appOwnership !== 'expo' && Platform.OS !== 'web';
const useProxy =
  (Constants.appOwnership === 'expo' && Platform.OS !== 'web') ||
  Platform.OS === 'android';
  
const config: {
  clientId: FACEBOOK_ID,
  scopes: ['public_profile', 'email'],
  
  // For usage in managed apps using the proxy
  redirectUri: isNative
    ? Platform.OS === 'android'
      ? `https://auth.expo.io/@YOURUSERORORGANISATION/${Constants.manifest.slug}`
      : `fb${FACEBOOK_ID}://authorize`
    : makeRedirectUri({
        useProxy,
        // For usage in bare and standalone
        // Use your FBID here. The path MUST be `authorize`.
        native: `fb${FACEBOOK_ID}://authorize`,
      }),
  useProxy,
  extraParams: {
    // Use `popup` on web for a better experience
    display: Platform.select({ web: 'popup' }) as string,
    // Optionally you can use this to rerequest declined permissions
    // auth_type: 'rerequest',
  },
}
```

**Comment by farhan-ibrahim** [comment]
Thank you @SleeplessByte. Now it's working but like what you said, it will show 2 activities. Any trick on how to resolve this?

**Comment by danieldauk** [comment]
Hey expo team,
is there any news regarding this issue? Will it be fixed in expo SDK 41?

**Comment by SleeplessByte** [comment]
> Thank you @SleeplessByte. Now it's working but like what you said, it will show 2 activities. Any trick on how to resolve this?

In managed mode you can't resolve it. It's because both packages add schemas into the `AndroidManifest.xml`.

**Comment by EvanBacon** [comment]
I've updated the docs to reflect the limitations https://docs.expo.io/guides/authentication/#facebook

- Expo Go: You must use the proxy
- Bare: Ensure the `com.facebook.CustomTabActivity` is not included, or use the proxy.

**Comment by SleeplessByte** [comment]
Perhaps it's wise to _also_ update the docs that there's only one way to make it work on Managed, ánd it's "flaky"?

**Comment by DGiannaris** [comment]
Hey all, 
we are building a managed flow app using auth session. The research you did on fb login helped us tremendously as we also encountered the same problem. We also noticed that google login , returns a double activity, one of which leads back to the app, the other into a new app instance.
We are using:
expo: 41.0.0
expo-auth-session: 3.2.3

Thought this might help you find out what's going on.

**Comment by SleeplessByte** [comment]
> We also noticed that google login , returns a double activity, one of which leads back to the app, the other into a new app instance.

Correct. Same issue as listed above (double listing in `AndroidManifest.xml`). You can't fix it unless you eject (you can still use eas when you do).

**Comment by DGiannaris** [comment]
It's me again :).
So after we established that auth session doesn't work for managed apps yet, we tried expo-google-app-auth.
It has the same results...double activity on redirect.
Is there any workaround for either auth session or expo-google-app-auth? (cause expo-facebook works fine)
Is the hardcoded redirectUri the only option here?

**Comment by SleeplessByte** [comment]
There is no workaround to prevent the double activity. The only workaround is to eject and fix `AndroidManifest.xml` manually.

**Comment by DGiannaris** [comment]
Does anyone have any knews on the matter?
Any workarounds ?

**Comment by EvanBacon** [comment]
Now with EAS Build, you can create custom dev clients and builds that have modified `AndroidManifest.xml` files. In this case, I would suggest adding the FB scheme directly to the manifest and avoid using `facebookScheme` which would generate the extra activity that is used in `expo-facebook`. 

`withAndroidScheme.js`
```js
const { AndroidConfig, withAndroidManifest } = require("@expo/config-plugins");

const withAndroidScheme = (config, scheme) =>
  withAndroidManifest(config, (config) => {
    if (!AndroidConfig.Scheme.hasScheme(scheme, config.modResults)) {
      config.modResults = AndroidConfig.Scheme.appendScheme(
        scheme,
        config.modResults
      );
    }
    return config;
  });

module.exports = withAndroidScheme;
```

Then in your `app.json`

```json
{
  "expo": {
    "plugins": [
      ["./withAndroidScheme", "fbMyCustomScheme"]
    ]
  }
}
```

If you use the vscode-expo extension, you can use <kbd>⌘⇧P</kbd> and type "Expo: Preview modifier" then select "android.manifest" to see a preview of what the AndroidManifest.xml will look like after you build with `eas build -p android` or `expo run:android`.

**Comment by SleeplessByte** [comment]
Not stale, but the workaround works!

**Comment by SleeplessByte** [comment]
FYI, the same issue is present in `expo-authentication` (https://docs.expo.dev/guides/authentication/). Two activities generated. One will work, one doesn't.

**Comment by SleeplessByte** [comment]
@EvanBacon when using the workaround `withAndroidScheme`, iOS can no longer redirect from facebook. "Safari cannot open the page because the link is invalid".

**Comment by SleeplessByte** [comment]
I was able to make this work for me by:
- not using expo-facebook
- using the withAndroidScheme plugin
- making sure there is NO Facebook scheme value in app json
- using proxy for iOS

**Comment by ScreamZ** [comment]
@brentvatne @tsapeta Maybe you have some information that we don't have about this? Is is planned for a fix ?

**Comment by rodrigopa** [comment]
in app.config.js:

```js
import { withAndroidManifest } from "@expo/config-plugins";

const withCustomConfig = (config) => withAndroidManifest(config, async (config) => {
  config.modResults.manifest.application[0].activity = config.modResults.manifest.application[0].activity.filter(
    (item) => item.$['android:name'] !== 'com.facebook.CustomTabActivity'
  );
  return config;
});

export default ({ config }) => ({
  ...
  facebookScheme: 'fb...',
  plugins: [[withCustomConfig]],
  ...
});
```

`npx uri-scheme add fb...`

`expo prebuild -p android`

**Comment by DukeNuken** [comment]
I found probably not the best solution here, but facebook auth works when just make in **app.json** that facebook app as main scheme. something like that 

`{
  "expo": {
    .........
    "scheme": "fb11111112312232",
    .........
}
`
I understand what it can have effect on some other logic which use deep links, but it works.

**Comment by ScreamZ** [comment]
Can we do something in the documentation about all of this ?

**Comment by SleeplessByte** [comment]
@offminded yep, that's exactly what we do too.

**Comment by nissimzarur** [comment]
> Now with EAS Build, you can create custom dev clients and builds that have modified `AndroidManifest.xml` files. In this case, I would suggest adding the FB scheme directly to the manifest and avoid using `facebookScheme` which would generate the extra activity that is used in `expo-facebook`.
> 
> `withAndroidScheme.js`
> 
> ```js
> const { AndroidConfig, withAndroidManifest } = require("@expo/config-plugins");
> 
> const withAndroidScheme = (config, scheme) =>
>   withAndroidManifest(config, (config) => {
>     if (!AndroidConfig.Scheme.hasScheme(scheme, config.modResults)) {
>       config.modResults = AndroidConfig.Scheme.appendScheme(
>         scheme,
>         config.modResults
>       );
>     }
>     return config;
>   });
> 
> module.exports = withAndroidScheme;
> ```
> 
> Then in your `app.json`
> 
> ```json
> {
>   "expo": {
>     "plugins": [
>       ["./withAndroidScheme", "fbMyCustomScheme"]
>     ]
>   }
> }
> ```
> 
> If you use the vscode-expo extension, you can use ⌘⇧P and type "Expo: Preview modifier" then select "android.manifest" to see a preview of what the AndroidManifest.xml will look like after you build with `eas build -p android` or `expo run:android`.

Thank you for that!!!!

**Comment by jwm0** [comment]
Still an issue on Expo SDK v46 using expo-auth-session. If there's no fix on the horizon can we put the workaround/link to issue in the official docs?

**Comment by Pcummings** [comment]
I can confirm this is still an issue, and Facebook just disabled my app due to this - not ideal...

**Comment by AkinAgbejoye** [comment]
My own redirected, but restart the react native android app. Pls anyone with solution

**Comment by SleeplessByte** [comment]
I have no interest in keeping this open despite this still being an issue. The workarounds work "okay", and it's what I recommend if you run into this. 

If you feel like this should be fixed please create a new issue instead. 

Normally I would just have unsubscribed, but because I am the original author, it will still ping me when there are new responses like the hostile stalebot.

**Comment by sgvolpe1** [comment]
Thanks everyone for the information, from me works this approach:

app.config.json
`const { AndroidConfig, withAndroidManifest } = require("@expo/config-plugins");

const withAndroidScheme = (config, scheme) =>
  withAndroidManifest(config, (config) => {
    if (!AndroidConfig.Scheme.hasScheme(scheme, config.modResults)) {
      config.modResults = AndroidConfig.Scheme.appendScheme(
        scheme,
        config.modResults
      );
    }
    return config;
  });

let plugins = [
  [withAndroidScheme, "fb99999999999999"]
];`

deleting facebookScheme and add the variable plugins in the return on app.config.json
`plugins: plugins,`
