### ISSUE TITLE
[expo-notifications][IOS] IOS is not receiving notification

### ISSUE THREAD

**Issue by Silavin** [expo/expo#9925]
Summary of Issue
Using the managed workflow and expo-notification, I can manage to receive the notification on android but not ios for some odd reason. 

I made use of the setNotificationHandler like so:

`Notifications.setNotificationHandler({
	handleNotification: async () => ({
		shouldShowAlert: true,
		shouldPlaySound: true,
		shouldSetBadge: true,
	}),
	handleSuccess: (notificationId) => {
		console.log("Notification Success")
		console.log(notificationId)
	},
	handleError: (err) => {
		console.log("Notification Has Error!!")
		console.log(err)
	}
});`

There were no message logged on the IOS while there was the 'Notification Success' on Android. 

Even using Postman, the api call to push a notification to the IOS device has reported 200 without issue. So, it is a strange occurrence, which I do not understand where the issues lie. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
   

> Expo CLI 3.23.3 environment info:
>     System:
>       OS: macOS 10.15.5
>       Shell: 5.7.1 - /bin/zsh
>     Binaries:
>       Node: 12.14.0 - /usr/local/bin/node
>       Yarn: 1.22.4 - /usr/local/bin/yarn
>       npm: 6.14.4 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     IDEs:
>       Android Studio: 3.5 AI-191.8026.42.35.6010548
>       Xcode: 11.6/11E708 - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ~38.0.8 => 38.0.9 
>       react: ~16.11.0 => 16.11.0 
>       react-dom: ^16.11.0 => 16.11.0 
>       react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
>       react-native-web: ~0.11.7 => 0.11.7 
>     npmGlobalPackages:
>       expo-cli: 3.23.3

**Comment by cruzach** [comment]
hi @Silavin , I think what you're looking for is the [`addNotificationReceivedListener`](https://docs.expo.io/versions/latest/sdk/notifications/#addnotificationreceivedlistenerlistener-event-notification--void-void). We also have a [full working example](https://snack.expo.io/@charliecruzan/push-notifications) in that docs page as well, to hep you find out what pieces of the `expo-notifications` module do what 👍

**Comment by Silavin** [comment]
HI @cruzach. Thank you for your help!

I tried using this method. 

The whole project is made before React had hooks so a ton of codes do not follow that example. So, this is what I did.

`	const token = await Notifications.getExpoPushTokenAsync();
	Notifications.addNotificationReceivedListener((notification) => {
		console.log("ADDED NOTIFCATION RECEIVE LISTENER HERE!!!!");
		console.log(notification);
	});`

So, within the function to create the token, I added the listener in. (I believe it should work since addNotificationReceivedListener seems to be a listener that invokes the callback when the conditions are met.)

However, on both the android phone and ios, there is no logs for this listener.

**Comment by cruzach** [comment]
> So, within the function to create the token, I added the listener in. (I believe it should work since addNotificationReceivedListener seems to be a listener that invokes the callback when the conditions are met.)

I'm not sure what you mean by this, but `addNotificationReceivedListener` adds a listener for notifications that come through while the app is foregrounded. So the callback you provide to it is called when a notification comes in while the app is foregrounded, not when the listener is added. 

Even though the example uses hooks, you can still use it as a base for implementing `expo-notifications`, you don't have to use hooks 😄 I suggest reading the `expo-notifications` documentation thoroughly

**Comment by Silavin** [comment]
@cruzach Hi,

**Comment by Silavin** [comment]
@cruzach Hello,

I went in more into the documentation as you suggested and found out that the APN is not sending out the token because:

> {
>     "data": {
>         "5a59ba77-ada9-401c-bfc7-3e0787a1ff1b": {
>             "status": "error",
>             "message": "The Apple Push Notification service failed to send the notification (reason: BadDeviceToken, status code: 400). Read Apple's docs about \"Communicating with APNs\" to learn what this error means.",
>             "details": {
>                 "apns": {
>                     "reason": "BadDeviceToken",
>                     "statusCode": 400
>                 },
>                 "error": "ExpoError",
>                 "sentAt": 1598861088
>             },
>             "__debug": {}
>         }
>     }
> }

This is the response I get when using https://exp.host/--/api/v2/push/getReceipts.

**Comment by cruzach** [comment]
So you have the push token, but you're not able to send a notification to it. I would double-check that the push token you're trying to send notifications to (which you should've gotten with `getExpoPushTokenAsync` is correct and up-to-date
