### ISSUE TITLE
Error: Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Default FirebaseApp is not initialized in this process <package>. Make sure to call FirebaseApp.initializeApp(Context) first.

### ISSUE THREAD

**Issue by LorhanSohaky** [expo/expo#9926]
## 🐛 Bug Report
```
Error: Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Default FirebaseApp is not initialized in this process <package>. Make sure to call FirebaseApp.initializeApp(Context) first.
promiseMethodWrapper@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2808:45
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:105900:40
getDevicePushTokenAsync$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:158961:83
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27534:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27707:32
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27534:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27607:30
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27637:19
tryCallTwo@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:29537:9
doResolve@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:29701:25
Promise@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:29560:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27636:33
enqueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27641:157
async@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27658:69
getDevicePushTokenAsync@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:158933:38
getExpoPushTokenAsync$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:159047:84
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27534:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27707:32
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27534:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27607:30
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27637:19
tryCallTwo@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:29537:9
doResolve@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:29701:25
Promise@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:29560:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27636:33
enqueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27641:157
async@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27658:69
getExpoPushTokenAsync@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:159034:38
registerForPushNotificationsAsync$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:158303:84
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27534:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27707:32
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27534:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27607:30
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27617:21
tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:29528:16
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:29629:27
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:33068:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:33104:19
callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:33322:33
callImmediates@[native code]
__callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3313:35
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3099:34
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3296:15
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3098:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.24.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7

### Reproducible Demo
```js
import { Linking } from 'expo'
import * as Notifications from 'expo-notifications'
import * as Permissions from 'expo-permissions'
import Constants from 'expo-constants'

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: false,
    shouldSetBadge: false,
  }),
});
export default function Root(){
  const registerForPushNotificationsAsync = async () => {
    if (Constants.isDevice) {
      const { status: existingStatus } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
      let finalStatus = existingStatus;
      if (existingStatus !== 'granted') {
        const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
        finalStatus = status;
      }
      if (finalStatus !== 'granted') {
        alert('Failed to get push token for push notification!');
        return;
      }
      const expoToken = await Notifications.getExpoPushTokenAsync()
      console.log(expoToken)
    } else {
      alert('Must use physical device for Push Notifications');
    }

    if (Platform.OS === 'android') {
      Notifications.createChannelAndroidAsync('default', {
        name: 'default',
        sound: true,
        priority: 'max',
        vibrate: [0, 250, 250, 250],
      });
    }
  };

  useEffect(()=>{
    try{
      registerForPushNotificationsAsync()
      Notifications.addNotificationReceivedListener(_handleNotification)
    }catch(err){
      console.error(err)
    }
  },[])

  const _handleNotification = notification => {
    console.log(notification);
  };
}
```

**Comment by byCedric** [comment]
Hi @LorhanSohaky. Thanks for the report, but I'm missing your question. This error is usually related to Android standalone builds missing FCM credentials, described in [this doc](https://docs.expo.io/push-notifications/using-fcm/). If this isn't your case, please provide additional context, e.g. iOS/Android or standalone/client.

Hope this helps!

**Comment by LorhanSohaky** [comment]
@byCedric ok, I got it. Changing the subject, do you have any recommendations for having web notifications?

**Comment by uzaymacar** [comment]
Here is the relevant documentation in case anyone is wondering: https://docs.expo.dev/push-notifications/push-notifications-setup/#android

**Comment by iway1** [comment]
also remember to do 🧠 `expo prebuild` 🧠 to regenerate the native code as this is when expo places the google-services.json into its home in the `android/app` folder

**Comment by fahmieshaq** [comment]
> also remember to do 🧠 `expo prebuild` 🧠 to regenerate the native code as this is when expo places the google-services.json into its home in the `android/app` folder

This answer solved my problem! Thank you

**Comment by alexmlong** [comment]
This isn't solving the issue for me. I've run prebuild and there's no google services json file. Any ideas? 🙏

**Comment by jahazielmtz** [comment]
> This isn't solving the issue for me. I've run prebuild and there's no google services json file. Any ideas? 🙏

Make sure google-services.json isn't in your .gitignore or create .easignore not including google-services.json. Also remove andriod folder before run prebuild. I was having a lot of problems with dependencies but that solved my problems

**Comment by alexmlong** [comment]
H

> > This isn't solving the issue for me. I've run prebuild and there's no google services json file. Any ideas? 🙏
> 
> Make sure google-services.json isn't in your .gitignore or create .easignore not including google-services.json. Also remove andriod folder before run prebuild. I was having a lot of problems with dependencies but that solved my problems

Hmm thanks for your reply, I tried this but no look... I'll continue working on it

**Comment by alexmlong** [comment]
The Expo docs actually say to gitignore google-services.json, are you committing it? https://docs.expo.dev/push-notifications/fcm-credentials/

**Comment by jahazielmtz** [comment]
> The Expo docs actually say to gitignore google-services.json, are you committing it? https://docs.expo.dev/push-notifications/fcm-credentials/

That's right but seems like eas build considers also .gitignore when it's performed. So what I did was creating .easignore file and not ignore google-services.json there and include it in .gitignore

**Comment by alexmlong** [comment]
That seems to have done the trick 😲 Thanks!

**Comment by alexmlong** [comment]
> > The Expo docs actually say to gitignore google-services.json, are you committing it? https://docs.expo.dev/push-notifications/fcm-credentials/
> 
> That's right but seems like eas build considers also .gitignore when it's performed. So what I did was creating .easignore file and not ignore google-services.json there and include it in .gitignore

That seems to have done the trick! 😲 Thanks

**Comment by saintejon** [comment]
> > The Expo docs actually say to gitignore google-services.json, are you committing it? https://docs.expo.dev/push-notifications/fcm-credentials/
> 
> That's right but seems like eas build considers also .gitignore when it's performed. So what I did was creating .easignore file and not ignore google-services.json there and include it in .gitignore

I don’t quite understand this, did you add easignore to gitignore? Then what? I don’t understand please

**Comment by jahazielmtz** [comment]
> > > The Expo docs actually say to gitignore google-services.json, are you committing it? https://docs.expo.dev/push-notifications/fcm-credentials/
> > 
> > 
> > That's right but seems like eas build considers also .gitignore when it's performed. So what I did was creating .easignore file and not ignore google-services.json there and include it in .gitignore
> 
> I don’t quite understand this, did you add easignore to gitignore? Then what? I don’t understand please, kindly drop a code snippet

What I did was including google-services.json in .gitignore and then create a new file .easignore, there I only included node-modules folder, I'm still in the way to know which files are not needed for eas build to include them into .easignore

**Comment by bj97301** [comment]
My issue seemed to be that eas didn't have my google service file.  Found a good way to give it my "file" securely using secrets:
https://docs.expo.dev/build-reference/variables/#how-to-upload-a-secret-file-and-use-it-in-my-app-config

```bash

eas secret:create --scope project --name GOOGLE_SERVICES_JSON --type file --value ./path/to/google-services.json


```

then update your app.config.js/json
```js

export default {
  android: {
    googleServicesFile: process.env.GOOGLE_SERVICES_JSON,
  },
}

```

**Comment by prpwebsteam** [comment]
> also remember to do 🧠 `expo prebuild` 🧠 to regenerate the native code as this is when expo places the google-services.json into its home in the `android/app` folder

You are awesome man. Stuck from 3 days.

**Comment by scansio** [comment]
> > also remember to do 🧠 `expo prebuild` 🧠 to regenerate the native code as this is when expo places the google-services.json into its home in the `android/app` folder
> 
> This also solved my problem! It should be added in docto for first-timers.

Yes it should be documented, it was fustrating when I followed step by step process yet my app was not working

**Comment by Krishcode264** [comment]
> My issue seemed to be that eas didn't have my google service file. Found a good way to give it my "file" securely using secrets: https://docs.expo.dev/build-reference/variables/#how-to-upload-a-secret-file-and-use-it-in-my-app-config
> 
> eas secret:create --scope project --name GOOGLE_SERVICES_JSON --type file --value ./path/to/google-services.json
> 
> then update your app.config.js/json
> 
> export default {
>   android: {
>     googleServicesFile: process.env.GOOGLE_SERVICES_JSON,
>   },
> }
> Looks like if you put the googleServicesFile value in quotes it tries to find a file but if you give it an env var value it uses that directly.

 @bj97301  thank you so much , it worked for me , prebuilding was not working for me

**Comment by haseeb-usman** [comment]
> > also remember to do 🧠 `expo prebuild` 🧠 to regenerate the native code as this is when expo places the google-services.json into its home in the `android/app` folder
> 
> This also solved my problem! It should be added in docto for first-timers.

this aslo worked for me . Thanks man 🤝
