### ISSUE TITLE
[iOS 14] Video assets does not work

### ISSUE THREAD

**Issue by bbarthec** [expo/expo#9931]
## 🐛 Bug Report

Wait for iOS 14 GM and see if this is still an issue.
This bug might be premature as it's has been spotted in iOS 14 Beta 5.

### Summary of Issue

Local video assets does not work:
1. in `test-suite`/`MediaLibrary` the file `require('../assets/big_buck_bunny.mp4')` is being loaded and fails on the line https://github.com/expo/expo/blob/581067249dbb121aa3a74221d97cd9c2643b4ceb/apps/test-suite/tests/MediaLibrary.js#L65
because for some unknown reason `MediaLibrary.createAssetAsync` that tries to create a video asset from the locally loaded file ends up with the `The operation couldn’t be completed. (Cocoa error -1.)` error in the file: https://github.com/expo/expo/blob/581067249dbb121aa3a74221d97cd9c2643b4ceb/packages/expo-media-library/ios/EXMediaLibrary/EXMediaLibrary.m#L151-L165

2. in `test-suite`/`Video` some tests that are waiting for the `<Video />` component to be mounted and thus fire `onReadyForDisplay` callback are failing with timeout, because this event is not being called whenever `source = someLocalFile`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Environment:
```
  Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.16.1/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.0 => 39.0.0
      react-native: 0.63.2 => 0.63.2
    npmGlobalPackages:
      expo-cli: 3.24.2
```

Phone:
```
iOS version: OS 14 Beta 5
Model: iPhone SE 2
```

### Reproducible Demo

1. Open `test-suite`/`MediaLibrary` and see all tests failing, because of 
 
2. Open `test-suite`/`Video` and see some of the test that are waiting for `fullscreen` events are failing.

**Comment by lukmccall** [comment]
``MediaLibrary` and `Video` are only failing on real devices - simulators work fine 🤷🏼‍♂️`

**Comment by pckz** [comment]
Someone knows more about this?
Today in iOS 14 beta 8 still happening. 

My main concern is this will still happen with the apps already published in Apple AppStore, when the other week iOS 14 will be released. :( It would be the worst

**Comment by lukmccall** [comment]
It seems to work with `.mov` files. I'm not sure why the same code doesn't work with `.mp4` but I assume that the Apple change something in the iOS 14 - maybe they dropped support for some audio codec used by `mp4` format.

**Comment by pckz** [comment]
Confirmed, iOS 14 was released today and my published apps won’t work :( is the same as the first attached screenshot

Thanks @lukmccall I will try that!

**Comment by dewnull** [comment]
neither `.mov` nor `.mp4` works. I even updated from SDK 36 to 38.

**Comment by dewnull** [comment]
I set `shouldPlay` and it starts to work. See 
[#2144](https://github.com/react-native-community/react-native-video/issues/2144)

**Comment by mi-mazouz** [comment]
any update I still have this issue... Video is not showing at all I got

**Comment by alexlren** [comment]
if somebody else runs into this issue, updating expo-updates seems to work, I suppose there is an update on create-bundle-ios.sh script

**Comment by mrousavy** [comment]
Hey everyone!

Are `ph://` assets in `<Video>` components now supported? For some reason this fails to load for me with Error Code `AVFoundation Error -1002`...
