### ISSUE TITLE
[expo-gl][expo-gl-cpp]#import <future> file not found in bare react-native project

### ISSUE THREAD

**Issue by anutting** [expo/expo#9936]
### Summary of Issue 

Adding react-native-unimodules, expo-gl, and expo-gl-cpp has caused some build errors in my Xcode project. I followed installing unimodules documentation.

The errors

- node_modules/expo-gl-cpp/cpp/EXGLContext.h:15:10: 'future' file not found
- node_modules/expo-gl/ios/EXGL/EXGLView.h:3:9: Could not build module 'EXGL_CPP'

My Podfile
```
platform :ios, '11.1'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'MyTarget' do
  use_frameworks!
  use_unimodules!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React-Core"
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCTLOG_REDBOX_LEVEL=RCTLogLevelFatal'
        end
    end
  end
end
```

Any suggestions for a fix would be appreciated. Thanks.

### Steps to Reproduce

```
npx react-native init AwesomeProject
cd AwesomeProject
npm i -S react-native-unimodules expo-gl expo-gl-cpp
# edit AppDelegate.m according to unimodules installation instructions
# edit Podfile according to unimodules installation instructions
# add use_frameworks! below use_unimodules!
# comment out the flipper section of the Podfile
cd ios && pod install && cd ..
npx react-native start
# open a second terminal
npx react-native run-ios
```
Alternatively, the .xcworkspace file can be opened in Xcode and the errors can be viewed there.

### Expected Behavior vs Actual Behavior

The Xcode project is expected to build without failure.

**Comment by anutting** [comment]
I found the issue is due to having use_frameworks! in my Podfile. Is there another setting in Xcode to support use_frameworks! and find the correct header files?

**Comment by ArnoldoJr** [comment]
When you installed react-native-unimodules as per: https://docs.expo.io/bare/installing-unimodules , were you able to test that `console.log(Constants.systemFonts)` didn't print undefined? (https://docs.expo.io/bare/installing-unimodules/#usage)

**Comment by riku99** [comment]
Hello.
I got the same error.
Did you find a solution?

**Comment by DingSoung** [comment]
usually Xcode buildsetting - GCC_INPUT_FILETYPE is set to automatic (by file type)

if a header is imported by c file, it will be combined as c, 
if is imported by cpp file, it will be combined as cpp

I have check EXGLContext.h is always imported by cpp file, so the source code is correct.

finally I found EXGLContext.h is imported by EXG_CPP-umbrella.h, witch is combined by automatic（default obj-c)

```objc
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "EXiOSUtils.h"
#import "EXJSConvertTypedArray.h"
#import "EXJSUtils.h"
#import "stb_image.h"
//#import "EXGLContext.h"
#import "UEXGL.h"
#import "UEXGLcppheader.cpp.h"

FOUNDATION_EXPORT double EXGL_CPPVersionNumber;
FOUNDATION_EXPORT const unsigned char EXGL_CPPVersionString[];
```

**Comment by DingSoung** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DingSoung** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DingSoung** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DingSoung** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Kudo** [comment]
i'm closing this issue because it's stale for a while. if anyone has still encounter same issue with latest sdk, please report to us and i'm happy to reopen this.

**Comment by DingSoung** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
