### ISSUE TITLE
[docs] publishManifestPath for iOS references Android

### ISSUE THREAD

**Issue by gregfenton** [expo/expo#9939]
The description of [publishManifestPath for iOS](https://docs.expo.io/versions/latest/config/app/#publishmanifestpath) seems to be a copy/paste error from [the Android description](https://docs.expo.io/versions/latest/config/app/#publishmanifestpath-1):

> The manifest for the Android version of your app will be written to this path during publish

Even if this is intentional and correct (which I doubt), there should be a mention as to why Android is being referenced in the iOS section.

**Comment by byCedric** [comment]
Hi @gregfenton, thanks for bringing this up! I'll create a PR to fix that, it looks like [these are deprecated ExpoKit fields](https://github.com/expo/expo/blob/2a30c4fb4f65da6d9303f68936d30496c5e5c645/docs/pages/bare/installing-updates.md#-migrating-from-an-expokit-project). I wouldn't recommend using them, and will check internally if they should be marked as deprecated.

**Comment by byCedric** [comment]
All right, we made the docs changes in the schema! It will take _some_ time to get deployed though. Again, thanks for mentioning this! I'll close this issue for now 👍

**Comment by gregfenton** [comment]
My pleasure.  I've submitted a [few docs PRs ](https://github.com/expo/expo/pulls/gregfenton)in the past couple of days too.  Cheers!
