### ISSUE TITLE
Dismiss digital fingerprint biometric

### ISSUE THREAD

**Issue by clems36** [expo/expo#9941]
## 🐛 Bug Report

In our app we have a biometrics login screen but we also offer the possibility to switch to a password screen. I can't find a way to dismiss the digital fingerprint biometrics on my OnePlus 6T using `expo-local-authentication` when leaving the biometrics screen.

### Environment 

Target: Android - OnePlus 6T.

```
Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^4.0.10 => 4.4.0
```
 
### Steps to Reproduce

- Call `LocalAuthentication.authenticateAsync` to make the fingerprint button appear
- Try to dismiss it without actually putting your finger on it (looks like a function does not exist for that).

### Expected Behavior vs Actual Behavior

I would expect a function that simply dismisses the fingerprint button. I've tried `LocalAuthentication.cancelAuthenticate` but that's not it's purpose.

Here's what currently happens, the fingerprint button stays on no matter what screen I navigate to:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6041593/91286035-393ea300-e78e-11ea-8857-918a90ae5c46.gif)

This is pretty big deal because if I log into a different account than the one I usually use and then press the fingerprint button after being logged in, that would log me into my usual account (the one registered with the fingerprint).

**Comment by byCedric** [comment]
Hi @clems36! Unfortunately, I don't think we can [cancel the biometric prompt on Android](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt#public-methods). This seems like a vendor-specific issue from OnePlus itself. If you cancel the biometric authentication, it must fire the [`BIOMETRIC_ERROR_USER_CANCELED`](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt#BIOMETRIC_ERROR_USER_CANCELED) event. This event is recorded and handled properly, but if the event is never triggered we can't cancel it programmatically.

Might be worth pinging OnePlus support for this as well.

**Comment by clems36** [comment]
Hey @byCedric thanks for your answer.
Just to make sure we're not missing something, the following shows the behaviour we had on OnePlus 6T prior to the SDK 38 upgrade:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6041593/91463824-23170c80-e88c-11ea-89e9-8d78ed456d9e.gif)

We were using `react-native-touch-id` back then (which is not supported anymore in favour of `expo-local-authentication`) but I suppose this is a native behaviour. 
Do you confirm we can't implement something similar with this SDK version ?

(by the way, i'm sorry to bring this up here but I don't know how else to reach out to you, have you had a chance to see my answer on [this issue ?](https://github.com/expo/expo/issues/9812) - i'll remove this note asap)

**Comment by clems36** [comment]
Hey @byCedric, sorry to bring this old issue back up, but it's still an issue for us. 
Did you see my last comment regarding `react-native-touch-id` and the fact that the in-screen fingerprint reader was being dismissed back then ?

**Comment by lucassouza16** [comment]
Same problem...
