### ISSUE TITLE
"The Expo SDK requires Expo to run" issue when running brand new project in Android Simulator.

### ISSUE THREAD

**Issue by NguyenCongVN** [expo/expo#9954]
### Summary of Issue

Cannot open Expo Client from Android simulator even with brand new project.

### Environment - Expo CLI 3.25.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.25.0

### Reproducible Demo
Expo SDK requires Expo to run.It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn about developing an Expo project.

<global>
validate.fx.js:9:10

loadModuleImplementation
require.js:321:11

<global>
Expo.fx.expo.js:1
..
...
 
### Steps to Reproduce
expo init new-app
npm start
open Android Simulator
run project in Android Simulator but issue happended.
updated Expo-cli and reinstalled Expo client but no luck.
run expo without cache and create brand new Simulator but they didn't fix too.

### Expected Behavior vs Actual Behavior
It should open project in Android Simulator but Red issue happends.

**Comment by brentvatne** [comment]
> expo init new-app

what template did you choose?

**Comment by NguyenCongVN** [comment]
> > expo init new-app
> 
> what template did you choose?

I chose blank template

**Comment by brentvatne** [comment]
so the managed template, which means you opened the project in the expo client app in the emulator, correct?

**Comment by NguyenCongVN** [comment]
Yes sir. I just clicked button to run on Android emulator on devTools with new blank template project

**Comment by NguyenCongVN** [comment]
Working on IOS simulator is fine.
![Screen Shot 2020-08-27 at 8 39 06 AM](https://user-images.githubusercontent.com/47655418/91373517-c7736180-e840-11ea-8584-407946f18203.png)

**Comment by brentvatne** [comment]
it's unclear to me how this could be happening. can you try switching to a tunnel connection to see if there is some connection issue? or try opening from a physical android device?

**Comment by NguyenCongVN** [comment]
Couldn't load issue when change to tunnel.
![Screen Shot 2020-08-27 at 9 22 07 AM](https://user-images.githubusercontent.com/47655418/91376231-d3fab880-e846-11ea-8ce2-0f8b3d0b989a.png)

**Comment by brentvatne** [comment]
let me know how that works out for you. there might be a network connectivity issue in your emulator.

**Comment by NguyenCongVN** [comment]
It's fine with physical device. I don't know what is the problem with my simulator.

**Comment by brentvatne** [comment]
can you open websites in chrome in the emulator? if not, maybe this stackoverflow post is relevant: https://stackoverflow.com/questions/42736038/android-emulator-not-able-to-access-the-internet

**Comment by NguyenCongVN** [comment]
It works now. Thanks sir.

**Comment by byCedric** [comment]
Awesome, glad you got it working! Have fun building your app 😄
