### ISSUE TITLE
Ensure deep linking with a custom scheme works when testing ExpoKit in development

### ISSUE THREAD

**Issue by terribleben** [expo/expo#996]
https://forums.expo.io/t/third-party-app-linking/5878
https://forums.expo.io/t/deep-linking-only-works-when-app-not-in-background/4970/3

workaround for now would probably be to test this kind of feature on a prod/published build.

**Comment by mechabyte** [comment]
Hey, just wanted to reach out and see if there was any progress on this?

**Comment by kadoshms** [comment]
@terribleben hey there, is there any progress with that?

https://forums.expo.io/t/deep-linking-only-works-when-app-not-in-background/4970/5

We are also using a custom scheme and encounter this issue..

**Comment by kadoshms** [comment]
@terribleben well it is not only in ExpoKit, we are using a regular expo client app and still see the -1003 error (both in dev and prod)

**Comment by terribleben** [comment]
Hey folks, can people who were affected by this try the following?

- [Update to SDK 27](https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4)
- Make sure your `app.json` has some value for `scheme` - it can be any custom value that you intend to use in production.
- If your iOS app's Info.plist contains a generated scheme like `exp12345`, delete that from Info.plist

Now try running and see if this issue is fixed for you. We redid the way we handle Linking in SDK 27.
