### ISSUE TITLE
Notifications.addNotificationResponseReceivedListener doesn't trigger if app is killed (Android Only)

### ISSUE THREAD

**Issue by macuna** [expo/expo#9968]
I have this issue in a Bare workflow and only happens in Android (if app is killed) after expo-in-app-purchases is installed (IOS Works fine)

Steps to reproduce:

```
expo init --template bare-minimum
```
```
expo install expo-notifications
```
--- After this everything working fine in both platforms ---
```
npm install expo-in-app-purchases
```
Notifications.addNotificationResponseReceivedListener doesn't work anymore in Android when app is killed.

App.js

```
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View, Linking } from 'react-native';
import * as Notifications from 'expo-notifications';
import Constants from 'expo-constants';



export default function Container({ navigation }) {
  React.useEffect(() => {
    registerForPushNotificationsAsync()
    const subscription = Notifications.addNotificationResponseReceivedListener(response => {
      console.log("User entered from notification.")
    });
    return () => subscription.remove();
  }, [navigation]);

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

async function registerForPushNotificationsAsync(userId: string) {
  let experienceId = undefined;
  if (!Constants.manifest) {
    // Absence of the manifest means we're in bare workflow
    experienceId = '@user/project';
  }
  const expoPushToken = await Notifications.getExpoPushTokenAsync({
    experienceId,
  });
  console.log("TOKENNNN")
  console.log(expoPushToken)
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

expo diagnostics 
```
  Expo CLI 3.25.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.9 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.25.0
```

**Comment by macuna** [comment]
ref: @cruzach https://github.com/expo/expo/issues/6943#issuecomment-666743870

**Comment by cruzach** [comment]
@macuna this is a duplicate of https://github.com/expo/expo/issues/9866, so we should probably close this (it's unrelated in `expo-in-app-purchases`)

**Comment by macuna** [comment]
> ref: @cruzach [#6943 (comment)](https://github.com/expo/expo/issues/6943#issuecomment-666743870)

I only said, this happened after expo-in-app-purchases but when I uninstall that library it works again.

**Comment by cruzach** [comment]
Using the code you shared, the issue occurs whether or not I install `expo-in-app-purchases`, can you try again? I'm pretty confident the issue exists without installing `expo-in-app-purchases`, since plenty of people have reported it https://github.com/expo/expo/issues/6943

**Comment by macuna** [comment]
@cruzach I tried several times and it works if expo-in-app-purchases is not installed.

**Comment by cruzach** [comment]
@macuna can you provide a link to a gh repo that reproduces this?

**Comment by brunoaduarte** [comment]
I have the same problem with expo-in-app-purchases installed

"expo-in-app-purchases": "~8.2.1",
"expo-notifications": "^0.3.3",

**Comment by macuna** [comment]
> @macuna can you provide a link to a gh repo that reproduces this?

@cruzach I've just invited you a private project so you can reproduce the error.

**Comment by macuna** [comment]
> I have the same problem with expo-in-app-purchases installed
> 
> "expo-in-app-purchases": "~8.2.1",
> "expo-notifications": "^0.3.3",
> 
> @macuna do you know if this problem occurs with the 'legacy-notifications' module?
> have you tried it?

No I didn't. It worked for you @brunoaduarte ?

**Comment by brunoaduarte** [comment]
> > I have the same problem with expo-in-app-purchases installed
> > "expo-in-app-purchases": "~8.2.1",
> > "expo-notifications": "^0.3.3",
> > @macuna do you know if this problem occurs with the 'legacy-notifications' module?
> > have you tried it?
> 
> No I didn't. It worked for you @brunoaduarte ?

Didn't tried either, just updated to SDK39. Hope this is fixed in this version.

**Comment by macuna** [comment]
> > > I have the same problem with expo-in-app-purchases installed
> > > "expo-in-app-purchases": "~8.2.1",
> > > "expo-notifications": "^0.3.3",
> > > @macuna do you know if this problem occurs with the 'legacy-notifications' module?
> > > have you tried it?
> > 
> > 
> > No I didn't. It worked for you @brunoaduarte ?
> 
> Didn't tried either, just updated to SDK39. Hope this is fixed in this version.

I've upgrade to SDK 39 and now the problem occurs even without having expo-in-app-purchases installed.

**Comment by kaushik-prasanna** [comment]
Has this been fixed as of Expo SDK 39?

**Comment by macuna** [comment]
> Has this been fixed as of Expo SDK 39?

I've upgraded to SDK39 but the issue still persists.

**Comment by Jhalter5Stones** [comment]
@macuna Any luck on finding a fix / workaround? I am seeing this issue as well still using SDK 39

**Comment by brunoaduarte** [comment]
> @macuna Any luck on finding a fix / workaround? I am seeing this issue as well still using SDK 39

Me too #10456

**Comment by cruzach** [comment]
I've followed the steps in the ticket to reproduce this, and still have not been able to. To be clear, this issue is for the bare workflow only, since `expo-in-app-purchases` is only available in the bare workflow.

@macuna after running 
`expo init --template bare-minimum`
`yarn add expo-notifications`
`yarn add expo-in-app-purchases`

I am still able to trigger the response received, here's my code: https://gist.github.com/cruzach/d6d49089ffca1491d26fff1eed068494

**Comment by macuna** [comment]
> I've followed the steps in the ticket to reproduce this, and still have not been able to. To be clear, this issue is for the bare workflow only, since `expo-in-app-purchases` is only available in the bare workflow.
> 
> @macuna after running
> `expo init --template bare-minimum`
> `yarn add expo-notifications`
> `yarn add expo-in-app-purchases`
> 
> I am still able to trigger the response received, here's my code: https://gist.github.com/cruzach/d6d49089ffca1491d26fff1eed068494

Did you have a chance to try the repo I've shared with you @cruzach ?

**Comment by macuna** [comment]
> I've followed the steps in the ticket to reproduce this, and still have not been able to. To be clear, this issue is for the bare workflow only, since `expo-in-app-purchases` is only available in the bare workflow.
> 
> @macuna after running
> `expo init --template bare-minimum`
> `yarn add expo-notifications`
> `yarn add expo-in-app-purchases`
> 
> I am still able to trigger the response received, here's my code: https://gist.github.com/cruzach/d6d49089ffca1491d26fff1eed068494

Thank you @cruzach, I created a new project following the same steps you've suggested and it works. I don't know what changed because I made the same steps before but this time worked.

**Comment by macuna** [comment]
> I've followed the steps in the ticket to reproduce this, and still have not been able to. To be clear, this issue is for the bare workflow only, since `expo-in-app-purchases` is only available in the bare workflow.
> 
> @macuna after running
> `expo init --template bare-minimum`
> `yarn add expo-notifications`
> `yarn add expo-in-app-purchases`
> 
> I am still able to trigger the response received, here's my code: https://gist.github.com/cruzach/d6d49089ffca1491d26fff1eed068494

Thank you @cruzach, after following the steps you've suggested, this is working.

But apparently the problem is happening when ```expo-in-app-purchases``` and ```expo-ads-admob``` are installed. (Apologies for the confusion)

**I've tried this and it worked:**

```
expo init --template bare-minimum
yarn add expo-notifications
yarn add expo-in-app-purchases
```

**I've tried this and it also worked:**

```
expo init --template bare-minimum
yarn add expo-notifications
yarn add expo-ads-admob
```
*Adding ```<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>``` on AndroidManifest.xml*

**But this, it didn't work:**

```
expo init --template bare-minimum
yarn add expo-notifications
yarn add expo-in-app-purchases
yarn add expo-ads-admob
```

Can you try to add ```expo-ads-admob``` to your project and see if you're experiencing the same issue?

Thank you.

**Comment by macuna** [comment]
Adding more information to this issue.

If you run either ```yarn remove expo-in-app-purchases``` or ```yarn remove expo-ads-admob``` it will work again.

**Comment by cruzach** [comment]
@macuna it works even with 
```
expo init --template bare-minimum
yarn add expo-notifications
yarn add expo-in-app-purchases
yarn add expo-ads-admob
```

for me. And I think this issue is getting a little difficult to follow 😕

**Comment by macuna** [comment]
> @macuna it works even with
> 
> ```
> expo init --template bare-minimum
> yarn add expo-notifications
> yarn add expo-in-app-purchases
> yarn add expo-ads-admob
> ```
> 
> for me. And I think this issue is getting a little difficult to follow 😕

Have you tried to open the notification when  the app is killed, right?

I've tried several times and the issue is happening always when both packages are installed.

**Comment by cruzach** [comment]
Yes I've tried it with the app killed, backgrounded, and foregrounded. With just `expo-notifications` installed, with `expo-in-app-purchases` installed, and with `expo-ads-admob` installed and configured.

**Comment by macuna** [comment]
Definitely I'm not able to trigger Notifications.addNotificationResponseReceivedListener when both packages are installed.

This is my environment:

```
  Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /Users/martin/.rvm/gems/ruby-2.5.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.16 
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: bare
```

and this the package.js

```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "expo": "~39.0.2",
    "expo-ads-admob": "^8.3.0",
    "expo-in-app-purchases": "^9.1.0",
    "expo-notifications": "^0.7.2",
    "expo-splash-screen": "~0.6.2",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.3",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-screens": "~2.10.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

I'll really appreciate if you can make a quick view in order to check if something can be wrong @cruzach.

Thank you.

**Comment by macuna** [comment]
After lot of testing I've noticed that this happening with Android versions bellow 8.0. I was mostly testing my apps in two devices with Android 6.1 and 7.1 respectively.

@cruzach, thank you for taking time on this issue.

**Comment by kleytonbarcelos** [comment]
This library (expo-in-app-purchases) is crashing your app. I tried used that.

Now I am using RevenueCat.

**Comment by cruzach** [comment]
@kleytonbarcelos its not very helpful to comment on a closed & unrelated issue without providing any details on what your issue is. If you can open a new issue with details and a reproducible demo, I would be happy to look into any potential issue with `expo-in-app-purchases`
