### ISSUE TITLE
[docs] Push Notification Upload link 404

### ISSUE THREAD

**Issue by ryekerjh** [expo/expo#9969]
### Problem
The [Expo Notifications Documentation](https://docs.expo.io/versions/latest/sdk/notifications/#getexpopushtokenasyncoptions-expotokenoptions-expopushtoken) references how to upload your Push Notificaton keys to Expo's backend using the CLI, but the [link to that article](https://expo.fyi/upload-notifications-credentials) is a 404.

**Comment by byCedric** [comment]
@lukmccall I see [you added this](https://github.com/expo/expo/commit/4bcd395af345e10649cee58827e8aa3142c2ae09), is there a PR for FYI to fix this?

**Comment by lukmccall** [comment]
@byCedric hmm...

I didn't notice that this link doesn't work. I've copied this doc page from https://github.com/expo/expo/blob/master/packages/expo-notifications/README.md.

Hovewer, it looks like this should be pointing here https://docs.expo.io/push-notifications/push-notifications-setup/#credentials instead.

**Comment by lukmccall** [comment]
I will change it 😉
