### ISSUE TITLE
Live reloading no longer appears in dev menu

### ISSUE THREAD

**Issue by lateefbeats** [expo/expo#9975]
Hi, "Live reloading" no longer appears when I run my app on iOS simulator, or on my real device thru QR code scan. I only see "Fast refresh" which refreshes the app constantly even if I am not making any changes. This is making development a real headache, any help greatly appreciated. Here is my environment:

 Expo CLI 3.24.2 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 5.1.0 - /Library/Mobile Documents/com~apple~CloudDocs/Desktop/Desktop - XXX MacBook Pro/dev/xxx-app/node_modules/.bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.3.9 => 4.4.0

**Comment by byCedric** [comment]
Hi @lateefbeats! I think fast refresh "replaced" the old live reloading feature. You can disable live reload and manually refresh the app whenever you need it. But, I think it's better to find out why your app keeps refreshing. Unfortunately, there are a lot of possibilities where this is going wrong. E.g. use `setState` in a render method. If you need us to check this out, we need a [small repro](https://stackoverflow.com/help/minimal-reproducible-example) so we can investigate it.

Hope this helps!
