### ISSUE TITLE
ImagePicker returns base64 on the web

### ISSUE THREAD

**Issue by sanealytics** [expo/expo#9984]
### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.9.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.25.1
```

### Reproducible Demo

Just the sample code, but run it on the web
 
### Expected Behavior vs Actual Behavior

Expected: blob, but get base64 output.

This does not change if we use `base64: false` flag.

Workaround:

```
fetch(uri)
    .then(res => res.blob())
    .then(blob => {
        const fd = new FormData();
        const file = new File([blob], "filename.jpeg");
        fd.append('image', file)
  
        // Let's upload the file
        // Don't set contentType manually → https://github.com/github/fetch/issues/505#issuecomment-293064470
        const API_URL = 'https://example.com/add_image'
        fetch(API_URL, {method: 'POST', body: fd)
             .then(res => res.json()) 
             .then(res => console.log(res))
```

**Comment by leonardopaglia** [comment]
Same thing happening in the Expo document picker

**Comment by bnussman** [comment]
I agree that this is an issue. Thank you for your workaround, it helped me a lot!

**Comment by DannyChambers** [comment]
Damn, I'm really stuck here.. Haven't been able to get the workaround to work. Is there anyway yet to return the file rather than base64?

**Comment by leonardopaglia** [comment]
I personally solved it (in the ImagePicker) by making a simple patch with `npx patch-package` to also return the file object, maybe it can help. This is the really simple patch:

```

diff --git a/node_modules/expo-image-picker/build/ExponentImagePicker.web.js b/node_modules/expo-image-picker/build/ExponentImagePicker.web.js
index 72929bb..e287ef2 100644
--- a/node_modules/expo-image-picker/build/ExponentImagePicker.web.js
+++ b/node_modules/expo-image-picker/build/ExponentImagePicker.web.js
@@ -68,6 +68,9 @@ function openFileBrowserAsync({ mediaTypes, capture = false, allowsMultipleSelec
     return new Promise((resolve, reject) => {
         input.addEventListener('change', () => {
             if (input.files) {
+
+                // Added file to the returned object. We need it for the multiform request.
+
                 const targetFile = input.files[0];
                 const reader = new FileReader();
                 reader.onerror = () => {
@@ -81,6 +84,7 @@ function openFileBrowserAsync({ mediaTypes, capture = false, allowsMultipleSelec
                             uri,
                             width: 0,
                             height: 0,
+                            file: targetFile
                         });
                     };
                     if (typeof target?.result === 'string') {
@@ -92,6 +96,7 @@ function openFileBrowserAsync({ mediaTypes, capture = false, allowsMultipleSelec
                                 uri,
                                 width: image.naturalWidth ?? image.width,
                                 height: image.naturalHeight ?? image.height,
+                                file: targetFile
                             });
                         };
                         image.onerror = () => {

```

**Comment by bnussman** [comment]
Not sure if this will help you @DannyChambers but here is how I handle a Profile Photo selection and upload in my app. 

https://github.com/bnussman/Beep/blob/master/routes/settings/ProfilePhoto.tsx

**Comment by DannyChambers** [comment]
Thank you. In my case I need to pic a document (CSV specifically) to upload and process. Currently DocumentPicker is returning base64. When I convert it to a blob and upload it, it's just a CSV containing base64 data.

I'm going to try to revert DocumentPicker to a previous version (Currently using "expo-document-picker": "~8.4.0").

Thanks for the support

**Comment by metasection** [comment]
@DannyChambers Any luck resolving this?  We have the same issue with Expo SDK 39 and Web.

We get a nice file:// uri on iOS but Web is giving us base64 data.

**Comment by OKNoah** [comment]
I'm having the opposite problem where setting `base64: true` does _not_ return an object with a `base64` key as the documentation describes.

**Comment by dmellstrom** [comment]
The cause can be seen here, in the source
https://github.com/expo/expo/blob/1b94ad2f808507c8e3ccbbc69b6f4413f73d4b1b/packages/expo-image-picker/src/ExponentImagePicker.web.ts#L160

The web component returns base64 regardless, whereas the Expo component pays mind to the flag, for example here on iOS

https://github.com/expo/expo/blob/1b94ad2f808507c8e3ccbbc69b6f4413f73d4b1b/packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m#L330

I have a sneaking suspicion this is just a hack to make tutorials and examples work, or something of that nature. I can think of no other reason why the API would be different on web

**Comment by simonezuccala** [comment]
Not strictly related to the issue, but [here](https://github.com/expo/expo/pull/12529)'s a fix so the base64 is correctly returned on web when `base64: true` is passed to `launchCameraAsync()` and `launchImageLibraryAsync()`.

**Comment by ElForastero** [comment]
Yeah, I started using expo-image-picker a few days ago and noticed that there's no way to get a blob on the web.

base64 is bloated by ~30% and uploading in base64 requires some changes on the backend

**Comment by ycjcl868** [comment]
same question

**Comment by hyochan** [comment]
For those of you facing this problem, I've managed to solve this by converting blob to file. Here is the sample code in [my gist](https://gist.github.com/hyochan/dee15792b2a308e37ff82c9a6c17b7fc). Hope this helps.

@ElForastero You don't need extra changes in backend as long as you apply my solution in react-native.

However, this is just a workaround.

**Comment by ElForastero** [comment]
@hyochan I made something similar

```ts
const res = await fetch(base64);
const blob = await res.blob();
```

**Comment by Vimiso** [comment]
Why was this never solved? It seems to me, on all platforms, `uri` should only return base64 if `base64` is set to `true`. In all other cases a file uri should be return, like what happens on native.

**Comment by Vimiso** [comment]
Workaround / code necessary to make this work cross platform:

`support/file.js`
```js
export const mimeTypeToExtension = mimeType => {
  const mimeMap = {
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'image/gif': 'gif',
    'image/webp': 'webp',
    'image/bmp': 'bmp',
  }

  return mimeMap[mimeType]
}

export const base64ToBlob = (base64Str, type = 'application/octet-stream') => {
  // Decode base64 string.
  const byteCharacters = atob(base64Str)

  // Set byte numbers array.
  const byteNumbers = new Array(byteCharacters.length)

  // Convert characters to byte numbers.
  for (let i = 0; i < byteCharacters.length; i++) {
    byteNumbers[i] = byteCharacters.charCodeAt(i)
  }

  // Create a byte array.
  const byteArray = new Uint8Array(byteNumbers)

  // Create a blob from the byte array.
  return new Blob([byteArray], { type })
}

export const base64ToFile = base64Str => {
  // Split metadata from base64.
  const [metadata, base64] = base64Str.split(',')

  // Extract MIME type.
  const mimeType = metadata.match(/:(.*?);/)[1]
  const extension = mimeTypeToExtension(mimeType)

  // Convert base64 to bob.
  const blob = base64ToBlob(base64, mimeType)

  // Create the file name.
  const fileName = `file.${extension}`

  // Create a File object.
  return new File([blob], fileName, { type: mimeType })
}
```

`screen.jsx`
```jsx
const result = await ImagePicker.launchImageLibraryAsync({
  mediaTypes: ImagePicker.MediaTypeOptions.Images,
  allowsEditing: true,
  aspect: [4, 3],
  quality: 1,
})

if (! result.canceled) {
  setSelectedImages(prevImages => {
    const newImages = [...prevImages]

    const uri = Platform.OS === 'web'
      ? URL.createObjectURL(base64ToFile(result.assets[0].uri))
      : result.assets[0].uri

    newImages[slot] = uri

    return newImages
  })
}
```
