### ISSUE TITLE
MapView user location not working on android.

### ISSUE THREAD

**Issue by gdaunton** [expo/expo#999]
It looks like user location for the MapView is not working properly.
[It's just broken](https://snack.expo.io/rkLAx14xf), the user location button doesn't show up, nor does the user location blue dot. Seems to be working fine on ios.

**Comment by brentvatne** [comment]
hi! this looks like an issue upstream in react-native-maps: https://github.com/airbnb/react-native-maps/issues/1698#issuecomment-344160040 -- perhaps you could try contributing a fix to that repo?

**Comment by gdaunton** [comment]
Did a bit of digging, it looks like if the location permission is granted, the current location dot and button show up. Should it be a default that the map view asks for location permissions?

**Comment by jesseruder** [comment]
I think this is more an issue with our docs than the implementation. Asking for `Permissions.LOCATION` before showing a map view seems right.

**Comment by lucasmouse** [comment]
Is my location not my Button "show my current location". The same problem, i really need to fixe

**Comment by SanderBreivik** [comment]
As @jesseruder said, you can ask for permission when the component is mounted.
```
componentDidMount() {
    this.getLocationAsync();
  }
    
  getLocationAsync = async () => {
    await Permissions.askAsync(Permissions.LOCATION);
  }

  render() {
    return (
      <MapView
        showsUserLocation={true}
	showsMyLocationButton={true}
        style={styles.container}
        region={{
          latitude:  63.446827,
          longitude: 10.421906,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
        onPress={this.props.handlePress}
      >
```
