### ISSUE TITLE
Expo App crashes on Notifications.setBadgeNumberAsync(0)

### ISSUE THREAD

**Issue by mrizwan18** [expo/expo#9992]
### Summary of Issue 

Expo app crashes when using Notifications.setBadgeNumberAsync(0) inside 
componentDidMount() {
    if (Platform.OS === "ios") {
      Notifications.setBadgeNumberAsync(0);
    }
......}

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

SDK Version 38. App crashes on both iOS and Android.
### Reproducible Demo

 https://github.com/mrizwan18/snsfitness contains all the code, can be installed from playstore as well.
### Steps to Reproduce

Once app is installed, opening it causes the app to crash in App.js -> onComponentDidMount()

### Expected Behavior vs Actual Behavior

It should clear the badge count instead it crashes the app with this exception caught on sentry: 

![image](https://user-images.githubusercontent.com/34402664/91645272-3b8a5100-ea5d-11ea-97d0-4931552cf103.png)

**Comment by brentvatne** [comment]
the method is called `setBadgeCountAsync` - https://docs.expo.io/versions/latest/sdk/notifications/#setbadgecountasyncbadgecount-number-options-setbadgecountoptions-promiseboolean

**Comment by pweisensee** [comment]
@brentvatne if we are using the Legacy Notifications API, in that case is the function still `setBadgeNumberAsync`? We're having issues with it not clearing out the badge count on iOS (13 and 14) using Legacy Notifications from SDK 38 (managed workflow).

[Reference: setBadgeNumberAsync](https://docs.expo.io/versions/latest/sdk/legacy-notifications/#notificationssetbadgenumberasyncnumber)

**Comment by talha7o** [comment]
> @brentvatne if we are using the Legacy Notifications API, in that case is the function still `setBadgeNumberAsync`? We're having issues with it not clearing out the badge count on iOS (13 and 14) using Legacy Notifications from SDK 38 (managed workflow).
> 
> [Reference: setBadgeNumberAsync](https://docs.expo.io/versions/latest/sdk/legacy-notifications/#notificationssetbadgenumberasyncnumber)
I have the same issue, how did u tackle it?

**Comment by pweisensee** [comment]
@talha7o SDK 37 and 38's Legacy Notifications API weren't working so great for me in production apps. So, I'm upgrading all my apps to SDK 40 and the new Notifications API. Hoping that will fix things 🤞
