### ISSUE TITLE
Local notification does not work with month as value in CalendarTriggerInput 

### ISSUE THREAD

**Issue by dominick-designs** [expo/expo#9996]
### Summary of Issue 
```month``` trigger in ```CalendarTriggerInput``` does not appear to work

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
targeting iOS and Android

```
xpo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.25.1

```

### Reproducible Demo

the project can be seen here: https://github.com/dominick-designs/sandbox-expo-1
I know you said not to link to entire project but if you look at ```screens``` directory then ```TabOneScreen.tsx``` and look around lines 26- 28 you will see where I am having the issue.
 
### Steps to Reproduce
* I created a fresh expo app using expo init
* I used the code from https://docs.expo.io/versions/v38.0.0/sdk/notifications/#schedulenotificationasyncnotificationrequest-notificationrequestinput-promisestring  and the ```CalendarTriggerInput``` on the same page here: https://docs.expo.io/versions/v38.0.0/sdk/notifications/#calendartriggerinput

NOTE: this requires an actual device to reproduce

### Expected Behavior vs Actual Behavior
* local notifications work as expected when ```month``` is not provided and when ```hour``` ```minute``` and ```second``` are provided
* however, when ```month``` is provided as a number  (in my case I entered ```7``` as the month) the local notification is not triggered

**Comment by dominick-designs** [comment]
* appears to work when I add year value
* I was getting local notifications with app expo app foregrounded during development
* after build and upload to Test Flight, local notifications not working at all
* made a fresh build anyway and submitted for review in apple store
* live app now asks user to allow notifications but notification does not appear as expected

see my forum post here: https://forums.expo.io/t/how-to-use-export-interface-calendarnotificationtrigger/42028

why are local notifications only working when app is open and in foreground? How can calendar-based notifications work when app is not open or in foreground?

**Comment by sjchmiela** [comment]
For what it's worth — from my experience calendar-based triggers sometimes work unpredictably. I think adding a method returning _next date matching this calendar trigger_ may be valuable for development and debugging purposes. I'll see it done. 👍

**Comment by dominick-designs** [comment]
thank you for this commit. How would I implement this? Can I help update documentation somehow? I'd be happy to contribute somehow.

**Comment by sjchmiela** [comment]
What do you meant by

> How would I implement this?

If you're asking how to use it in your project I would recommend waiting for a new release of `expo-notifications` (can't promise when it will be, I guess by the end of next week should be doable). Keep in mind most probably you'll be able to use it only in bare workflow project, not the managed SDK39 project. If you want to verify if the trigger you specify resolves to an expected trigger date creating a simplest bare workflow project just for that should be ok. 🙂 

When it comes to documentation I updated it with `getNextTriggerDateAsync` description, see [here](https://github.com/expo/expo/blob/06653a0fa9f555f05ecfa51e8fa2b69444cb4a8b/docs/pages/versions/unversioned/sdk/notifications.md#getnexttriggerdateasynctrigger-schedulablenotificationtriggerinput-promisenumber--null).
