### ISSUE TITLE
Unable to resolve module 'expo-auth-session/providers/google.js'

### ISSUE THREAD

**Issue by yanalt** [expo/expo#9997]
### Reproducible Demo

straight from the documentation in [here](https://docs.expo.io/guides/authentication/#google) you have this piece of code (with a minor syntax correction):
https://snack.expo.io/@timsa7/7a6cfc
 
### Steps to Reproduce

use the snack above

### Expected Behavior
for the module to load. the documentation talks about ways to implement a web sign-in with several providers from A to Z. note: this isn't a documentation issue, the google part of the module is just gone.
### vs Actual Behavior
the module doesn't load, and it doesn't exist, and from looking around manually the needed functions for the code in the documentation (like useIdTokenAuthRequest) don't exist.

**Comment by brentvatne** [comment]
looks like snack needs to be updated to support this path. snack has a different way of resolving modules than with metro and so it needs to account for nested imports manually. cc @IjzerenHein

**Comment by brentvatne** [comment]
cc @EvanBacon - heads up that we should notify snack folks when adding new import paths like this

**Comment by IjzerenHein** [comment]
No I think something else is going on. It seems the latest official version of `expo-auth-session` is 1.4.1 and this version doesn't contain the providers. The new 1.5.0 version does contain the providers, but has only been released on `@next`.

**Comment by jonixj** [comment]
Any progress on this? :/

**Comment by sospedra** [comment]
No `google` file nor `providers` dir exists inside `expo-auth-session`

**Comment by byCedric** [comment]
@sospedra, @jonixj, @pyataevsv and @yanalt: Please see [this comment](https://github.com/expo/expo/issues/10178#issuecomment-692099356) as temporary workaround while we update the dependency chain 😄

**Comment by EvanBacon** [comment]
Published the package.

**Comment by humbertocruz** [comment]
@EvanBacon I try to use the v1.5.0 and it's works, but I had to add expo-random inside the expo-auth-session/node_modules and the auth is made inside a normal web browser, the webview did not open. but it's worked any way. thanks

**Comment by fr3fou** [comment]
![image](https://user-images.githubusercontent.com/1344906/103181351-e2b2b400-48a8-11eb-9465-7e9ab2b7eec9.png)
I get this error on `expo-auth-session: ~2.0.1`

**Comment by ktseo41** [comment]
I installed `expo-application` via `expo install expo-application` and works well

**Comment by Hakeemmidan** [comment]
If you're still having this issue, maybe try running:
```
expo install expo-auth-session expo-random
```
([Documentation reference](https://docs.expo.dev/versions/latest/sdk/auth-session/#installation))

<br/>

If that doesn't work, you can undo it by running:
- yarn:
```
 yarn remove expo-auth-session expo-random 
```

- npm:
```
npm uninstall expo-auth-session expo-random 
```

**Comment by SanRicl** [comment]
I was getting this error: 

Unable to resolve "expo-auth-session" from "node_modules/@clerk/clerk-expo/dist/useOAuth.js"  while I was using clerk

I solved the problem following @Hakeemmidan solution. 

Thx!!
