### ISSUE TITLE
[expo-linear-gradient] imports react-native-web/src directly

### ISSUE THREAD

**Issue by liorJuice** [expo/expo#9999]
### Summary of Issue 
when trying to build with webpack something that use expo-linear-gradient you get an error, as expo-linear-gradient imports normalizeColor directly from react-native-web/src which is in typescript.

see line 3 in this file:
https://github.com/expo/expo/blob/master/packages/expo-linear-gradient/src/NativeLinearGradient.web.tsx

this is the webpack error:

```
Failed to compile.
.../node_modules/react-native-web/src/modules/normalizeColor/index.js: Unexpected token (13:30)
  11 | import processColor from '../../exports/processColor';
  12 | 
> 13 | const normalizeColor = (color?: number | string, opacity?: number = 1) => {
     |                               ^
  14 |   if (color == null) return;
  15 | 
  16 |   if (typeof color === 'string' && isWebColor(color)) {
```

### Expected Behavior vs Actual Behavior
the module should import things from react-native-web/dist (or even only react-native-web if possible) instead of from react-native-web/src.

**Comment by alonp99** [comment]
Same issue here!

**Comment by natew** [comment]
For now I just copied this and have it imported directly for the web:

```
import normalizeColor2 from 'normalize-css-color'
import React, { FunctionComponent, useEffect, useState } from 'react'
import { LayoutRectangle, View } from 'react-native'

// temp took this from expo because its a bad citizen for compiling

const isWebColor = (color: string): boolean =>
  color === 'currentcolor' ||
  color === 'currentColor' ||
  color === 'inherit' ||
  color.indexOf('var(') === 0
const processColor = (color) => {
  if (color === undefined || color === null) {
    return color
  }
  // convert number and hex
  let int32Color = normalizeColor2(color)
  if (int32Color === undefined || int32Color === null) {
    return undefined
  }
  int32Color = ((int32Color << 24) | (int32Color >>> 8)) >>> 0
  return int32Color
}
const normalizeColor = (color: number | string, opacity = 1) => {
  if (color == null) return

  if (typeof color === 'string' && isWebColor(color)) {
    return color
  }

  const colorInt = processColor(color)
  if (colorInt != null) {
    const r = (colorInt >> 16) & 255
    const g = (colorInt >> 8) & 255
    const b = colorInt & 255
    const a = ((colorInt >> 24) & 255) / 255
    const alpha = (a * opacity).toFixed(2)
    return `rgba(${r},${g},${b},${alpha})`
  }
}

type Props = {
  colors: string[]
  locations?: number[] | null
  startPoint?: Point | null
  endPoint?: Point | null
  onLayout?: Function
} & React.ComponentProps<typeof View>

type Point = [number, number]

export const LinearGradient: FunctionComponent<Props> = ({
  colors,
  locations,
  startPoint,
  endPoint,
  ...props
}: Props) => {
  const [layout, setLayout] = useState<LayoutRectangle | null>(null)
  const [gradientColors, setGradientColors] = useState<string[]>([])
  const [pseudoAngle, setPseudoAngle] = useState<number>(0)

  useEffect(() => {
    const getControlPoints = (): Point[] => {
      let correctedStartPoint: Point = [0, 0]
      if (Array.isArray(startPoint)) {
        correctedStartPoint = [
          startPoint[0] != null ? startPoint[0] : 0.0,
          startPoint[1] != null ? startPoint[1] : 0.0,
        ]
      }
      let correctedEndPoint: Point = [0.0, 1.0]
      if (Array.isArray(endPoint)) {
        correctedEndPoint = [
          endPoint[0] != null ? endPoint[0] : 0.0,
          endPoint[1] != null ? endPoint[1] : 1.0,
        ]
      }
      return [correctedStartPoint, correctedEndPoint]
    }

    const [start, end] = getControlPoints()
    const { width = 1, height = 1 } = layout || {}
    start[0] *= width
    end[0] *= width
    start[1] *= height
    end[1] *= height
    const py = end[1] - start[1]
    const px = end[0] - start[0]

    setPseudoAngle(90 + (Math.atan2(py, px) * 180) / Math.PI)
  }, [startPoint, endPoint])

  useEffect(() => {
    const nextGradientColors = colors.map(
      (color: string, index: number): string => {
        const hexColor = `${normalizeColor(color)}`
        let output = hexColor
        if (locations && locations[index]) {
          const location = Math.max(0, Math.min(1, locations[index]))
          // Convert 0...1 to 0...100
          const percentage = location * 100
          output += ` ${percentage}%`
        }
        return output
      }
    )

    setGradientColors(nextGradientColors)
  }, [colors, locations])

  const colorStyle = gradientColors.join(',')
  const backgroundImage = `linear-gradient(${pseudoAngle}deg, ${colorStyle})`
  // TODO: Bacon: In the future we could consider adding `backgroundRepeat: "no-repeat"`. For more
  // browser support.
  return (
    <View
      {...props}
      style={[
        props.style,
        // @ts-ignore: [ts] Property 'backgroundImage' does not exist on type 'ViewStyle'.
        { backgroundImage },
      ]}
      onLayout={(event) => {
        setLayout(event.nativeEvent.layout)
        if (props.onLayout) {
          props.onLayout(event)
        }
      }}
    />
  )
}
```

**Comment by d4rky-pl** [comment]
*Workaround:* whitelist `node_modules/react-native-web/src` in your babel-loader configuration

**Comment by MalteBoehm** [comment]
@d4rky-pl i tried to solve it like this `exclude: '/node_modules/react-native-web/src'` but it didn't worked out. still getting:

`Error: Unable to resolve module `./debugger-ui/debuggerWorker.aca173c4` from ``: 

None of these files exist:
  * debugger-ui\debuggerWorker.aca173c4(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
  * debugger-ui\debuggerWorker.aca173c4\index(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
    at ModuleResolver.resolveDependency (C:\Users \Documents\Codingproject\project\frontend\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users \Documents\Codingproject\project\frontend\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users \Documents\Codingproject\project\frontend\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at C:\Users \Documents\Codingproject\project\frontend\node_modules\metro\src\lib\transformHelpers.js:267:42
    at C:\Users \Documents\Codingproject\project\frontend\node_modules\metro\src\Server.js:1096:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users \Documents\Codingproject\project\frontend\node_modules\metro\src\Server.js:99:24)
    at _next (C:\Users \Documents\Codingproject\project\frontend\node_modules\metro\src\Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

Did I whitelist it the right way? 

Thanks you!

**Comment by d4rky-pl** [comment]
@MalteBoehm you did the exact opposite of whitelisting

**Comment by nicolaslazzos** [comment]
I fixed it by adding an alias in my webpack configuration from `react-native-web/src` to `react-native-web/dist`.

**Comment by d4rky-pl** [comment]
@EvanBacon this was merged 26 days ago but it still crashes in expo-linear-gradient 11.0.3 that was released 17 days ago. Will the fix be available only in 12.x or is it a bug?
